### ISSUE TITLE
Incorrect storing of Cyrillic in the `config.xml` and `shortcuts.xml`

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#13222] opened 2023-02-24 18:29 UTC
### Description of the Issue

When I use Cyrillic it is not stored in readable form in the `config.xml` and `shortcuts.xml` files.
### Steps to Reproduce the Issue

For `config.xml`
1. Use any version of Notepad++
2. Do a Search (Ctrl+F) in Cyrillic with `кирилица`
3. Close Notepad++ to save the changes in `config.xml`
4. Open `config.xml` and see the the first line starting with `<Find name=` - it should contain incorrect `"&#x043A;&#x0438;&#x0440;&#x0438;&#x043B;&#x0438;&#x0446;&#x0430;"` instead of proper`"кирилица"`

For `shortcuts.xml`
1. Record a macro with the actions above
2. Give it a name `макрос`
3. Close Notepad++ to save the changes in `shortcuts.xml`
4. Open the `shortcuts.xml`
5. See the line starting with `<Macro name=` - it should be stored incorrectly as `"&#x043C;&#x0430;&#x043A;&#x0440;&#x043E;&#x0441;"` instead of proper `"макрос"`
6. See the line starting with `<Action type="3" message="1601" wParam="0" lParam="0" sParam=` - it should contain incorrect `"&#x043A;&#x0438;&#x0440;&#x0438;&#x043B;&#x0438;&#x0446;&#x0430;` instead of proper`"кирилица"`
### Expected Behavior

I have expected to have readable cyrillic in this files, because sometimes I need to make changes and I don't know what is what
### Actual Behavior

The cyrillic is stored as `&#x04XX;` instead of human readable cyrillic
### Debug Information

```
Notepad++ v8.4.9   (64-bit)
Build time : Jan 27 2023 - 03:11:16
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : D:\Install\Office Programs\Notepad++\_settings
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : 
    AutoSave (1.6.1)
    ComparePlus (1.1)
    TakeNotes (1.2.4)
    VisualStudioLineCopy (1.0.0.2)
```

@donho pointed here

**Comment by donho** [comment] 2023-07-01 19:24
For shortcuts.xml it's been fixed in the previous version, and the current version works fine.
For config.xml ithis issue won't be fixed due to that the format changing will bring a lot of regression.

**Closed by donho** 2023-07-01 19:24 UTC
