### ISSUE TITLE
Change of 'Move current line' behaviour for multiple lines from 6.8.8 to 6.9

### ISSUE THREAD

**Issue by donpatzone** [notepad-plus-plus/notepad-plus-plus#1690] opened 2016-03-30 11:18 UTC
## Problem description

Hi,

as I work on a daily basis with this feature I noticed a change of behaviour when it comes to the _move current line up_ or _move current line down_ function.

Up until 6.8.8 all lines **including** the one where the cursor was placed were selected.
Since 6.9 this is no longer the case.

Also when starting to move multiple lines the cursor is placed at the beginning of the first selected line instead the end of the last selected line since 6.9.
Problem still occurs after disabling all plugins including default ones.
## 

[Short clip on NP++ version 6.8.8 behaviour](https://youtu.be/fG2D95RZ32Q)
[Short clip on NP++ version 6.9 behaviour](https://youtu.be/tAjbkLcunsI)
### Additional information

OS: Windows 7
NP++ 6.9.1 (Behaviour was already in 6.9)

**Comment by MetaChuh** [comment] 2019-04-13 02:21
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:21 UTC
