### ISSUE TITLE
Find in Files...shouldn't prompt if file is too big to be opened

### ISSUE THREAD

**Issue by ramgarden** [notepad-plus-plus/notepad-plus-plus#1889] opened 2016-05-24 13:19 UTC
when doing a text search in a folder with lots of subfolders and files (thousands) it shouldn't pop up any dialogs requiring the user to click OK like the "file is too big to be opened in notepad++".  A really long search should be able to run unattended and finish on its own.

**Comment by danielddubois** [comment] 2016-07-28 18:18
Agreed

**Comment by kalendello** [comment] 2016-12-20 06:17
This issue forces me to rely on other software for an unattended "find in files" search.  It'd be very easy to suppress the messagebox.

**Comment by LazyBui** [comment] 2017-11-25 10:27
I personally think there are several usability issues here:

1. It doesn't display the actual file name, so you have no idea what file it's stuck on.
2. It doesn't display the file size so you have no sense of scale.
3. It pops up and there's no way to silence them for a particular search operation or permanently (with a reset toggle in the configuration).
4. The search option granularity is such that it forces you to see this when you must search large or deep directory hierarchies looking for some information you're interested in. For example, configuration keys. You don't know if they're in .txt files, .ini files, .xml files, .cfg files, or what other sort of file. But you have a string that you know is in there. If these options were improved, the issue would be mitigated somewhat (being able to exclude .exe and .dll files from your *.* search filter, for example, would be a great start).

This information could also be collected throughout the operation and reported singularly at the end like the results are instead of utilizing the message dialog. It would be nice to be able to cancel the operation if one of these pops up, but that would be nice generally speaking and doesn't need to be related.

If keeping the dialog is desired, I've taken a look at the code and API revision will be required since a catch block divorced from the context of what's going on pops up the error and it's a simple `MessageBox`, not something more complex that could be customized. This load function is used by several places, so it may not be so straightforward to change the API.

I'm interested in solving this issue because I'm quite tired of having to hit OK hundreds of times for a search. The only question is basically how @donho wants to handle the work.

What I would personally like to see is something like this mockup:
![mock_big_options](https://user-images.githubusercontent.com/43490/33229601-10b7d4e8-d197-11e7-9099-f0b18c9cfa96.png)

The reason why I would like to see this is that I can see it being useful for some searches even if you don't want it most of the time. The ability to banish it temporarily or permanently makes me feel good about it being the default so the user knows it exists.

I realize that this would require quite a bit of API change, but I don't mind doing that as long as I know I'll be able to work with the author and get the code into mainline. Any comments or recommendations if I'm going to do this work?

**Comment by ramgarden** [comment] 2018-03-20 00:50
I found the line of code that is the problem.  It should be changed from a messagebox to just a log message in the main app log or even the Windows App event log.  It looks like this function gets the filename passed in so you could add the file name to the log message as well.  I wonder if I have permissions to create a branch and make the fix myself?

**Comment by cmeriaux** [comment] 2018-03-20 11:10
@ramgarden no need to ask permission. Fork the repository, create  new branch and do what you need to do in your own branch. 
Then submit a pull request so that your branch can be merged. 
Good luck

**Comment by realityexists** [comment] 2018-05-06 11:09
Yes, this dialog is really annoying, but it also seems dangerous to just skip files that cannot be opened, giving the user the impression that the text is not in those files, when it might be.

Does Notepad++ have some way of reporting errors non-intrusively? Ideally I'd like to see an error line added to the search results.

**Comment by xantari** [comment] 2018-11-27 00:57
+1 hoping for a fix, this should be a very easy one to fix?

**Comment by MetaChuh** [comment] 2019-05-01 22:31
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by bladeoflight16** [comment] 2019-06-27 22:26
@MetaChuh Has this been changed? Or did you just close it for absolutely no reason? The pull request doesn't appear to have been merged.

**Comment by grantmatheny** [comment] 2020-03-31 23:09
This is still happening in notepad++ 7.8.5.

**Comment by Aevum11** [comment] 2021-04-27 17:16
This should not have been closed. No explanation given and is still an issue. Reason why this was closed consists of useless info and does nothing whatsoever to help solve this issue. At least make it an option to disable the box / skip it.

**Comment by LanchParty** [comment] 2022-04-08 15:19
How can this be fixed? Seems like there are great ideas here and this is one of my biggest complaints about Find in Files.

**Comment by alankilborn** [comment] 2022-04-08 15:28
@LanchParty 

It seems like with the addition of better huge file support (N++ >= 8.3), this should be less of a problem -- is that not your experience?

**Comment by LanchParty** [comment] 2022-04-08 15:46
@alankilborn - That's good to know about. My org has only deployed 8.1.3. I'll see if I can update and re-try the search I just did. Thank you!

I've experienced this before: when I try to update, I get an error "Error opening file for writing" on multiple files. A quick search doesn't yield much. I tried running as Admin. I'll need to get through this issue (without pissing off IT). So I'll assume that 8.3+ will solve this until I know otherwise. Thank you again!

**Comment by DoughyInTheMiddle** [comment] 2022-12-04 02:53
Still happening. Doing some AI art rendering and basically all of the model files are 2GB+ which throws the warning.

> please update your notepad++ to the latest 64 bit version [Notepad++ 7.6.6](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below. if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.
> 
> thank you for your help and best regards.

This is still happening. Running 8.4.6. Can't see anything in settings that would affect a change on the dialog box.

![image](https://user-images.githubusercontent.com/44233670/205471812-1afcec2f-f343-4aae-adc1-54749271e5dd.png)

**Comment by adamzovits** [comment] 2023-02-26 11:48
This issue is still occurring in 8.4.8, it's in no way closed or completed.

**Comment by xomx** [comment] 2023-09-01 12:20
fixable by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf8ddc18c9833fb8f19df1c44dc769926a274d47 , will be in the upcoming v8.5.7

**Comment by donho** [comment] 2023-09-01 15:26
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf8ddc18c9833fb8f19df1c44dc769926a274d47

**Closed by donho** 2023-09-01 15:26 UTC
