### ISSUE TITLE
[BUG] Notepad++, when opened, freezes DirectX11 games

### ISSUE THREAD

**Issue by Drakonas** [notepad-plus-plus/notepad-plus-plus#1626] opened 2016-03-12 22:57 UTC
I originally wrote this off as a hardware fault, but I just replaced my motherboard and CPU, and my graphics card is fairly new. I'm still experiencing this problem.

If I open Notepad++ AFTER loading DirectX11 games (currently tested games are Dolphin and Final Fantasy XIV), the said game freezes and becomes unresponsive until I force close the game in Task Manager.

If, however, I open Notepad++ BEFORE running said game, the game runs fine.

**Comment by Xebtria** [comment] 2016-08-09 16:03
I have to dig up this issue, because I have the exact same issue. it is game independent (happens with Diablo 3, Path of Exile, FIFA16, Wolfenstein).

Open game, then open notepad++ => game freezes and has to be closed via task manager
open np++, then open the game => no problem.

extremely annoying

**Comment by joncppl** [comment] 2016-08-11 07:26
Can confirm that I am getting similar crashes with dx applications (currently I'm aware of it happening Black Desert Online and MPC-HC with madvr)

Will try to collect a crash dump the next time it happens.

**Comment by Thumli** [comment] 2016-10-14 09:55
I can confirm it with World of Warcraft in windowed and windowed fullscreen mode with DX11 enabled, switching to DX9 or fullscreen mode and it doesn't freeze.

This is with v7 32-bit (build time Sep 21 2016 - 22:00:56) of Notepad++ and Windows 10 Home 64bit.

**Comment by edunad** [comment] 2016-10-23 14:25
Same thing happens with CS:GO, Heroes of the Storm, Overwatch, etc

**Comment by serge-a** [comment] 2016-10-30 19:17
Same as Thumli (except i didn't try dx9)

**Comment by SpeedProg** [comment] 2016-11-04 18:41
Can confirm this happening in Eve Online with DX11 enabled too

**Comment by Pequito** [comment] 2016-11-04 23:45
Noticed the same with FFXIV and DX9 and DX11, did not attempt to open before the game as mentioned above but can confirm will crash the game if opened afterwards.

**Comment by Silvest89** [comment] 2016-11-07 19:40
I have the same issue with Guild Wars 2, thought it was because of GW2. Apparently not :P

**Comment by tony311** [comment] 2016-11-14 16:04
Adding another confirmation, with Windows 7 Professional, World of Warcraft and Overwatch both running in DX11, windowed borderless, and Notepad++ 7.1.

**Comment by tony311** [comment] 2016-11-14 16:16
Also happens with Notepad++ 7.2.

**Comment by ToastyEngineer** [comment] 2016-11-15 20:33
Same issue here with Warframe. It's quite annoying.
I do hope there is a solution for this.

**Comment by flatluigi** [comment] 2016-11-22 02:04
Confirming the issue on Windows 10 with World of Warcraft.

**Comment by twirpdk** [comment] 2016-12-10 12:27
Confirming as well.
Opening Notepad++ 7.22 while World of Warcraft in DX11 mode is running, will crash the game every time.
Tested a couple of other DX11 games with same result.
Open Notepad++ before the game works fine.

Windows 10 Enterprise 64 bit.

**Comment by thesymbol** [comment] 2016-12-10 21:45
Can also confirm this with games such as Trove, Warframe and Garrys Mod on windows 10 pro 64 bit

**Comment by dail8859** [comment] 2016-12-10 22:11
Does anyone know of a small, stand-alone application (DX11 demo or something) that can reproduce this issue with Notepad++?

**Comment by thesymbol** [comment] 2016-12-10 23:01
Well its nothing small but it does crash Unigine Heaven Benchmark 4.0 Basic. (i loaded it in in windowed mode). @dail8859

**Comment by dail8859** [comment] 2016-12-10 23:58
@thesymbol Thanks for the info. I tried it but opening/closing Notepad++ works fine for me. So it would be nice if some people could post some debug info and hardware info to try to narrow it down to OS, chipset, or maybe its a specific plugin. My debug info:

```
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll DoxyIt.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```
GeForce GTX 860M driver v375.95

**Comment by thesymbol** [comment] 2016-12-11 00:10
Notepad++ Debug:
```
Notepad++ v7.1   (32-bit)
Build time : Oct 15 2016 - 23:30:30
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll docMonitor.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppNetNote.dll NppTextFX.dll PluginManager.dll SpellChecker.dll 
```

System Info:
```
Asus Z97-P
Intel Core i5 4690K 3.5GHz
Kingston KHX1600C10D3/4G x4
Asus Strix GTX970 driver 376.19
```

**Comment by tony311** [comment] 2016-12-11 00:30
Debug info:

````Notepad++ v7.2   (32-bit)
Build time : Nov  2 2016 - 11:26:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : ComparePlugin.dll FingerText.dll mimeTools.dll NppColumnSort.dll NppConverter.dll NppExport.dll NppFTP.dll NPPGit.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextFX.dll PluginManager.dll SnippetPlus.dll

**Comment by joncppl** [comment] 2016-12-11 00:47
update since this thread has recently came to life.


Originally posted in August that this crash occurred to me with Black Desert Online and MPC-HC w/ madvr.
So for the last four months I took care to not open Notepad++ while any DX11 apps were running.


Tested today with the same applications and other DX11 applications, and can NOT reproduce this issue. ie. No crashes anymore. 


The only changes in hardware since then was going from 2 ram modules to 4 (16GB->32GB).
And restoring my (stable) overclock from 4.4GHz back to stock 3.5GHz. (AIO watercooler pump broke so I'm currently on stock cooler :( )


However I keep up to date with NVIDIA drivers, windows 10 updates, Notepad++ updates, and whatever else may have auto-updated in that time.


System specs:
```
Win 10 Pro
MSI z87-g45
4770k 3.5GHz (4.4GHz at time of crash)
G.Skill F3-12800CL 10-8GBXL x4 (x2 at time of crash)
EVGA GTX 1080 FTW (no overclock post factory)
   Driver: 376.19 (at time of crash: probably 368.81)
```

I doubt it has to do with the hardware changes (overclock issues typically lead to BSOD, not individual applications crashing and adding RAM modules would only add points of failure), but who knows. I don't have the capacity to isolate the cause ATM.

**Comment by Thumli** [comment] 2016-12-11 17:16
It seems to have something to do with the Nvidia graphics driver. I noticed that if you disable the "Share" feature in GeForce Experience the problem seems to go away.

**Comment by dail8859** [comment] 2016-12-11 17:21
> GeForce Experience

I stopped using this in v3.0+ when they *required* users to create an account. Just curious, what does that "Share" feature actually share?

**Comment by tony311** [comment] 2016-12-11 17:25
> I stopped using this in v3.0+ when they required users to create an account. Just curious, what does that "Share" feature actually share?

Allows the use of the streaming, screenshot, and video recording functions.

**Comment by Silvest89** [comment] 2016-12-11 17:26
It enables nVidia fps overlay etc. Allows you to record video using the hardware encoder, and even has an option for live streaming to twitch.

**Comment by tony311** [comment] 2016-12-11 17:27
As an aside, I don't believe the Share function is the culprit as I've experienced the crashes even with Share disabled. Not 100% certain on that, but I'm pretty sure.

**Comment by thesymbol** [comment] 2016-12-11 18:49
I too have the share feature turned on, i do get crashes almost all the time but in some rare occasion i can open notepad++ without the game crashing, i do nothing different compared to when it does crash.

**Comment by AndyFresh** [comment] 2016-12-19 15:22
I have the same issue with all games but with one detail: if a game is in full screen mode, there is no bug. But if a game is in windowed mode (full screen window or half screen) then bug appears. Predominantly I play games in windowed mode and because of this this bug is annoying.

```
Asus Z87-Deluxe
i7-4770k (overclocked)
GTX1070 (not overclocked) always with latest drivers
16 Gb 
Win10 x64
Notepad++ 7.1 x64 in admin mode without plugins (because Plugin Manager doesn't work with x64)
```

**Comment by thesymbol** [comment] 2016-12-19 16:19
I have also noticed that if you minimize the game it crashes less times than if you have the game opened up in the background.

**Comment by Albo1125** [comment] 2016-12-22 10:08
Is this still being investigated? It's literally a deal breaker for me :( Every time I open a file with notepad++ while running GTA V, my game freezes and I have to restart it. Hoping for a fix soon :)

**Comment by thesymbol** [comment] 2016-12-22 10:12
@Albo1125 also hoping it is going to be fixed soon, have you tried minimizing the game and then open notepad++?
That seems to fix the issue for me but its annoying to have to minimize the game every single time you want to open notepad++ or open a new window...

**Comment by Oniryck** [comment] 2016-12-22 22:06
@Thumli Thank you! This seems to have fixed the issue for me, it was driving me mad !

**Comment by Albo1125** [comment] 2016-12-25 19:06
@thesymbol this is really hard for me to do as it concerns a windowed borderless instance of GTA V. Thanks for the tip, though.

But yea, for such popular and normally very well-working software, I hope this has a high priority on the hotfix list by now.

**Comment by thesymbol** [comment] 2016-12-25 19:08
@Albo1125 actually the fix from @Thumli worked for me aswell, the nvidia share feature was the root cause of it, still annoying tho since some of us use it.

**Comment by AndyFresh** [comment] 2016-12-25 20:26
@thesymbol how to turn Nvidia Share off?

**Comment by thesymbol** [comment] 2016-12-25 20:27
@AndyFresh http://nvidia.custhelp.com/app/answers/detail/a_id/4228/~/how-to-disable-the-geforce-experience-share-in-game-overlay

**Comment by dail8859** [comment] 2016-12-25 21:40
I would love to track this issue down but I've not been able to. Has anyone been able to reproduce this with a version of GeForce Experience less than 3.0?

**Comment by AndyFresh** [comment] 2016-12-26 07:23
So I confirm the fix from @Thumli too: turning off Nvidia Share solves that bug.

**Comment by NetWin** [comment] 2017-01-06 14:15
I can confirm  the fix from @Thumli too. 👍

**Comment by Drakonas** [comment] 2017-01-12 04:49
This isn't exactly a fix. I use Nvidia Share.

**Comment by librarianrabbit** [comment] 2017-01-26 21:31
Same, use Nvidia Share. Notepad++ crashes the game.

**Comment by dail8859** [comment] 2017-01-26 22:43
I just updated GeForce, created an account (unfortunately), updated drivers, turned on share, but have not had any luck reproducing this. I guess it would be nice to narrow the bug down to an exact trigger (specific setting, hardware, software, etc).

**Comment by Arisae** [comment] 2017-09-14 03:34
In my case I suffered a **freezing issue with Nopad++ 7.5.1.** It was my **Windows 10 are freezing** due to a problem between **NVidia(385.41, and I do not use ~~fucking~~ GeForce Experience) container and nvsvc, Notepad++ process.**

While looking for the cause of the problem, I've confirmed that **my device's Notepad++ is x86 version(I use x64). So I removed it and reinstalled with x64 version.** And now, it seems to have been resolved. No more freezing occurs. Of course, it is just my case.

> Notepad++ v7.5.1   (64-bit)
> Build time : Aug 29 2017 - 02:38:44
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment] 2019-04-13 02:32
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:32 UTC
