### ISSUE TITLE
Is it a bug? Processing of Unix (.sh) heredocuments in Notepad++

### ISSUE THREAD

**Issue by Benqzq** [notepad-plus-plus/notepad-plus-plus#3189] opened 2017-04-20 15:24 UTC
We already discussed this in depth in the following link:

https://unix.stackexchange.com/questions/359910/heredocument-error-i-cant-understand-delimited-by-end-of-file/360000?noredirect=1#comment637932_360000

**Comment by dail8859** [comment] 2017-04-20 17:30
For the sake of condensing the conversation and for someone who isn't that familiar with heredo, can you post a set of reproducible steps, expected/actual behavior, and debug info?

**Comment by Benqzq** [comment] 2017-04-20 18:26
Reproducible steps:

1. Copy the code from the example (or from the following code example and paste it in a `.sh` file (make sure to change all leading spaces to tabs after you paste it).

```
bash /dev/fd/10 10<<-'SES'
⇨   # Setup LAMP environment and mod_rewrite:
⇨   ⇨   cat <<EMR > ~/tiesto
⇨   ⇨   text...
⇨   ⇨   EMR
SES
```

Note: Where there is an arrow - There should be a leading tab.

2. Copy and paste the edited code into your bash terminal and execute it by pressing enter (return).

The outcome should be a file named tiesto created in your home folder containing all content nested inside the cat heredoc (in this case, the string "text").

As I wrote in the thread the execution breaks and I get:

> warning: here-document at line 2 delimited by end-of-file (wanted `EMR')

**Comment by dail8859** [comment] 2017-04-20 19:02
This still doesn't tell me what is expected of *Notepad++* and what is actually happening. Step 2 is not applicable here.

**Comment by Benqzq** [comment] 2017-04-20 20:04
I expect Notepad++ not to add any hidden characters besides tabulations or `LF` (assuming something extra might be added). If something extra is added this is problematic and might break execution of the heredoc in Bash (I can't determine if that's the case and hence emphasized it's possible to do with Notepad++ but I don't strictly determine anything).

**Comment by dail8859** [comment] 2017-04-20 20:08
Notepad++ does not add any hidden characters. At most it will modify line endings to prevent mixing `\n` and `\r\n`. It sounds like you are just using incorrect line endings for the file.

**Comment by Benqzq** [comment] 2017-04-20 20:09
I use Unix EOLs (LF) if that's you mean, but what you mention might be different?

**Comment by dail8859** [comment] 2017-04-20 20:12
`Edit > EOL Conversions` can be used to set the end of line characters for the file. Also, Notepad++ will show invalid characters if there are some invalid ones in the file. For characters such as whitespace and newlines you can use `View > Show symbols > Show all characters`.

**Comment by Benqzq** [comment] 2017-04-20 20:37
Yes, but I assumed there are other things which aren't necessarily seen there? For example, I know that the encoding is a trait that isn't shown there and assumed some "anti-Unix" traits might cause the problem I have.

**Comment by dail8859** [comment] 2017-04-20 21:19
You can look in the bottom right of the screen and it will tell you the encoding. It is probably "ANSI" or "UTF-8" and since these are all common characters I suspect everything is fine. If you are that concerned you can use a hex editor (or the hex editor plugin) to verify it. If I had to guess it is likely that "pasting" it into the terminal could likely cause issues as it might do its own EOL conversions or encoding changes. Either way this doesn't seem to be N++ related at all.

**Comment by Benqzq** [comment] 2017-04-21 06:40
Actually it does seem to me as a bug in Notepadd++ and that NP++ doesn't interpret the heredocs right and doesn't delimit them correctly and it might effect how to data is pasted in the Unix shell itself (I checked that in two different Unix systems):

![1](https://cloud.githubusercontent.com/assets/13021900/25265587/7d34328c-2676-11e7-94f8-934d2c67ce13.PNG)

**Comment by MAPJe71** [comment] 2017-04-21 07:16
Your example:
```bash
bash /dev/fd/10 10<<-'SES'
⇨   # Setup LAMP environment and mod_rewrite:
⇨   ⇨   cat <<EMR > ~/tiesto
⇨   ⇨   text...
⇨   ⇨   EMR
SES
```
AFAIK:
1. HereDoc does not _remove_ any leading white space;
1. the HereDoc (Type 2) open identifier (`SES`) should not be enclosed in quotes;
1. the HereDoc (Type 1) close identifier (`EMR`) should not have leading white space;

Q:
1. Did you try the example using a different editor on Linux and what was the result?
1. Shouldn't the re-direct to file be after the HereDoc? E.g. with above knowledge applied:
```bash
bash /dev/fd/10 10<<-SES
⇨   # Setup LAMP environment and mod_rewrite:
⇨   ⇨   cat <<EMR
text...
EMR > ~/tiesto
SES
```

**Comment by Benqzq** [comment] 2017-04-21 07:28
If you use the `<<-` operator it should remove all leading tabs (I lead only with tabs). There is no problem enclosing it with quotes as it just prevents var substitution.

I don't have a Linux GUI here, in Nano it all looks the same (white text).

As far as I know the redirect should be in the opener, not the delimiter.

**Comment by MAPJe71** [comment] 2017-04-21 08:25
>  it should remove all leading tabs

N++ is a text editor, it does not interprete HereDoc.

**Comment by Benqzq** [comment] 2017-04-21 11:39
I know what it is and by interpret I meant to why it is represented in it behind the scenes: From the uniform coloring in the image above something seems not right. I've expanded on Unix stackExchange (please read the update there if you haven't already).

![aa](https://cloud.githubusercontent.com/assets/13021900/25275904/4bb64022-26a0-11e7-8bbe-fc869cfae926.PNG)

**Comment by dail8859** [comment] 2017-04-21 12:54
Some questions/observations:

1. Keep examples small. It helps to debug them.
1. Stop changing the original link back and forth. It makes it hard to keep referencing the same webpage each time. It appears you deleted your question on askubuntu for some reason.
1. Post the actual text as well as images (nobody wants to sit here retyping what you are showing in your images).
1. Post your debug info located under Notepad++'s `?` menu.
1. What theme are you using? Is it custom because my heredocs look very different (and ugly).

I am starting with a simple example:

```sh
cat <<EOF
	indented
EOF

echo Done
```

It looks like this:

![a](https://cloud.githubusercontent.com/assets/3694843/25278092/559d28a2-266f-11e7-871b-1136940d1788.png)

If I indent the closing `EOF` it looks like this:

![b](https://cloud.githubusercontent.com/assets/3694843/25278100/6396c7e2-266f-11e7-8324-920356f7e948.png)

Which according to the documentation for bash is correct. To make it work you have to use `<<-` to open the heredoc like this:

![c](https://cloud.githubusercontent.com/assets/3694843/25278114/7571e6c2-266f-11e7-92e5-b3a6a50fb4cd.png)

So I still don't understand the problem.

**Comment by MAPJe71** [comment] 2017-04-21 13:13
1. IMO you're adding an issue to the topic as it's unlikely that incorrect syntax highlighting is the cause of the initial issue i.e. getting the message "warning: here-document at line 2 delimited by end-of-file (wanted `EMR')" on script execution.
1. It would have saved us time if you had added the descriptive text to the image the first time you posted it.
1. Cross-check the syntax highlighting issue with the latest [SciTE](http://www.scintilla.org/), check whether the issue is already reported for the Bash lexer in the [Scintilla repository](https://sourceforge.net/p/scintilla/bugs/). When the coloring is also wrong in SciTE and not yet reported, add a bug or feature request ticket there.

------

From the Advanced Bash-Scripting [Guide Chapter 19. Here Documents](http://tldp.org/LDP/abs/html/here-docs.html):
> The - option to mark a here document limit string (<<-LimitString) _suppresses_ leading tabs (but not spaces) in the output.

It isn't mentioned/clear if it suppresses one indentation level or more/all levels.
Maybe use the - option for both the inner and the outer HereDoc:
```bash
bash /dev/fd/10 10<<-'SES'
⇨   # Setup LAMP environment and mod_rewrite:
⇨   ⇨   cat <<-EMR > ~/tiesto
⇨   ⇨   text...
⇨   ⇨   EMR
SES
```
------

> I don't have a Linux GUI here

From the Unix & Linux Stack Exchange link:
> This phenomena happens both in native Ubuntu and WSL Ubuntu.

Isn't Ubuntu the Linux GUI or at least based on Linux?

------

**Comment by MAPJe71** [comment] 2017-04-21 13:17
Sorry, saw post of @dail8859 only after I posted (i.e. page refresh).

**Comment by MAPJe71** [comment] 2017-04-21 13:44
Using default theme (yes very ugly, difficult to read).

w/o `-` option:
![capture-21-04-2017-15 36 57](https://cloud.githubusercontent.com/assets/6494038/25280081/f651bd4c-26a8-11e7-996c-4df6aa75f8fb.png)

w/ `-` option:
![capture-21-04-2017-15 35 17](https://cloud.githubusercontent.com/assets/6494038/25280089/fe731b56-26a8-11e7-8174-0dcd7d52350b.png)

[example.bsh](https://github.com/notepad-plus-plus/notepad-plus-plus/files/947203/example.bsh.txt)

**Comment by Benqzq** [comment] 2017-04-21 16:06
@dail8859 , I didn't change the link back and forth: At the start I pasted two questions (in Unix SE and AskUbuntu SE) and the question on AskUbuntu was deleted because there's no reason to assume this problem is particular to Ubuntu. I have no plans to further change this.

N++ Debug info:

```
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 
```

Yes, because the native heredocument graphics of Notepad++ are ugly, I changed them to something which is but less ugly (me and another user agreed it would be best to totally remove the heredoc styling for Notepad++ because it's [useless).](https://superuser.com/questions/1147461/removal-of-notepad-styles-possible-i-mean-to-the-style-configurators-langua)

Anyway, the code I used to reproduce the problem in my systems is the one I pasted in comment 3. I just copied it from N++ (when all leads are tabulation based) and executed in Bash with the Return (Enter) key. I did nothing else to get the reported error.

**Comment by dail8859** [comment] 2017-04-21 19:14
So I see only 2 things that could be related to Notepad++:

1. Notepad++ colorizing the text incorrectly -- However both I and @MAPJe71 have shown is working (albeit ugly by default) as expected.
2. There is some unknown character in the file -- You have not provided any indication Notepad++ is causing this. Your best option is to install the hex editor plugin to look at the file byte-by-byte.

Again as I stated above it is more likely that whatever you are doing to get it into Bash (copy/paste, X11 fowarding, virtual machine, terminal emulator, etc) is more likely the cause. 

If you have some specific information, or exact step-by-step details that relate to Notepad++ (and **only** Notepad++ (what Bash says is not relevant to what we can debug here)) then please reopen.

**Closed by dail8859** 2017-04-21 19:14 UTC

**Comment by Benqzq** [comment] 2017-04-21 22:31
The only indication as I see it (and I don't strictly determine anything) is the coloring issue I described which I assumed might be associated with byte change in the file. Now, after the answer in Unix SE by derobert, it does seem flaws of pasting in the current release of the relevant terminal emulator is the problem.
