### ISSUE TITLE
Find In Files, fails on big files

### ISSUE THREAD

**Issue by RudiHansen** [notepad-plus-plus/notepad-plus-plus#4131] opened 2018-02-01 14:24 UTC
When doing a Find in Files, you can get the error “File is too big to be opened by Notepad++” 
And every time you get that error the search stops, and does continue before you say OK to the error.

Perhaps you can have an option to skip large files in the search dialog?

**Comment by dail8859** [comment] 2018-02-01 14:30
Duplicate of #1889

**Comment by ramgarden** [comment] 2018-06-20 18:04
We tried to work on this issue yesterday but couldn't get the code to compile.  Need better instructions in the repo on how to compile for those of us that are VERY rusty on our C++.

**Comment by MetaChuh** [comment] 2019-05-01 22:32
please update your notepad++ to the latest 64 bit version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed** 2023-09-01 15:34 UTC
