### ISSUE TITLE
Dark Mode - muliline tabs ugly

### ISSUE THREAD

**Issue by end0r** [notepad-plus-plus/notepad-plus-plus#9957] opened 2021-06-07 07:12 UTC
### Description of the Issue
In Dark mode if you are using multi line tabs, the tabs look ugly, not adapting to dark mode.

### Steps to Reproduce the Issue
1.  Have multiline tabs setting on
2.  Make sure you have enough tabs open to fill several lines
3.  Switch on Dark Mode
![image](https://user-images.githubusercontent.com/14273069/120974384-5ae2a700-c770-11eb-8cc3-eb0b9122be6d.png)

### Expected Behavior
It should adapt to dark mode

### Actual Behavior
It doesn't adapt to dark mode.

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by sasumner** [comment] 2021-06-07 12:06
Turning on _Multi-line_ in the _Tab Bar_ settings will not reveal the bug if only a single line of tabs would be shown.
Easy replication for such a case:  Hold down Ctrl+n until enough new tabs are created such that it will go multiline -- them Boom, replicated! :-)

**Comment by end0r** [comment] 2021-06-07 12:46
That's right. Luckily the screenshot shows that quite clearly :)

**Comment by AngryGamer** [comment] 2021-06-07 15:29
I saw this 2 months ago, but I couldn't be bothered to test or figure out why one is forced on and other is implicit off.

[void drawItem(DRAWITEMSTRUCT *pDrawItemStruct, bool **isDarkMode = false**);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L985)

[drawItem((DRAWITEMSTRUCT *)lParam);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L826) // isDarkMode is implicit off, TCS_BUTTONS draws from here

[drawItem(&dis, true);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L959) // isDarkMode is explicit on, tabs draw from here

**Comment by AngryGamer** [comment] 2021-06-07 15:36
I saw this 2 months ago, but I couldn't be bothered to test or figure out the decision making here.

TCS_BUTTONS is pulling values from DarkModeDefault style due to implicit isDarkMode=false, whereas tabs has explicit isDarkMode=true and is always ignoring the styler's colors and loading hardcoded color values.

[void drawItem(DRAWITEMSTRUCT *pDrawItemStruct, bool **isDarkMode = false**);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L985)

[drawItem((DRAWITEMSTRUCT *)lParam);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L826) // isDarkMode is implicit off, TCS_BUTTONS draws from here

[drawItem(&dis, true);](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L959) // isDarkMode is explicit on, tabs draw from here

**Comment by butscharoni** [comment] 2021-06-08 08:46
Since it might be related, I would like to add that there are also problems with setting the tab colors via "Style Preferences". 
In Multi-Line Mode, the active tabs background color is ignored, and in single line mode, it's the inactive tabs text color as well. (The background on the active tab looks ok here since it is the same as the inactive ones, but notice that it should be black for the active tab) 
Though aside from the inactive tabs text color, this happens as well in light mode.

![npp01](https://user-images.githubusercontent.com/4222897/121152704-baf74d00-c845-11eb-8284-d3806d3dba1b.png)
![npp02](https://user-images.githubusercontent.com/4222897/121152724-be8ad400-c845-11eb-95fa-880814d0654c.png)

**Comment by AngryGamer** [comment] 2021-06-08 16:26
> In Multi-Line Mode, the active tabs background color is ignored

To be clear, **Background colour** in **Active tab text** _doesn't do anything_ and _never did anything_ regardless of single or multi-line. The field has never been retrieved or used by Npp from inception. The active tab's background is hardcoded to ::GetSysColor(COLOR_BTNFACE). I've known about this for years. Npp is littered with bugs or minor oversights such as these everywhere, but it's been nearly impossible to push through patches without them being arbitrarily rejected or rotting away unreviewed for months/years. So many people who tried to fix issues lost morale/interest and give up. Although, these days it's probably easier to have patches accepted because COVID19 made Don Ho somewhat active.

**Comment by AngryGamer** [comment] 2021-06-08 16:27
@butscharoni
> In Multi-Line Mode, the active tabs background color is ignored

To be clear, **Background colour** in **Active tab text** _doesn't do anything_ and _never did anything_ regardless of single or multi-line. The field has never been retrieved or used by Npp from inception. The active tab's background is hardcoded to ::GetSysColor(COLOR_BTNFACE). I've known about this for years. Npp is littered with bugs or minor oversights such as these everywhere, but it's been nearly impossible to push through patches without them being arbitrarily rejected or rotting away unreviewed for months/years. So many people who tried to fix issues lost morale/interest and give up. Although, these days it's probably easier to have patches accepted because COVID19 made Don Ho somewhat active.

**Comment by AngryGamer** [comment] 2021-06-08 16:29
@butscharoni
> In Multi-Line Mode, the active tabs background color is ignored

To be clear, **Background colour** in **Active tab text** _doesn't do anything_ and _never did anything_ regardless of single or multi-line. The field has never been retrieved or used by Npp from inception. The active tab's background is hardcoded to ::GetSysColor(COLOR_BTNFACE). I've known about this for years. Npp is littered with bugs or minor oversights such as these everywhere, but it's been nearly impossible to push through patches without them being arbitrarily rejected or rotting away unreviewed for months/years. So many people who tried to fix issues lost morale/interest and gave up. Although, these days it's probably easier to have patches accepted because COVID19 made Don Ho somewhat active.

**Comment by MarkusBodensee** [comment] 2021-06-19 08:12
@end0r @sasumner @AngryGamer 

I think this issue is fixed in v8.1 with acf91fc2c22dbf8d4d91f5df7e5f2bdfa084112a, since I cannot reproduce with v8.1.

Can anyone of you confirm this? If yes, than this issue can be closed.

**Comment by sasumner** [comment] 2021-06-19 10:31
I confirm this is no longer an issue in 8.1.

**Closed by sasumner** 2021-06-19 10:31 UTC
