### ISSUE TITLE
Bug: Function List parser require one additional whitespace after last '}', otherwise whole class's functions won't show

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#5546] opened 2019-04-18 03:42 UTC
Notepad++ version: 7.6.6 (64-bit) on Windows 10.

E.g. Function List show nothing, i.e. no class & functions, with this Java Code (The file's last character is '}'), unless you add a newline after the last '}':

```
public class A {
    void f1() {
    }
    void f2() {
    }
}
```

**Comment by MAPJe71** [comment] 2019-05-02 16:40
See of #1232, #1861, #2910 and #3095.

**Comment by ArkadiuszMichalski** [comment] 2020-09-20 12:32
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2910, maybe close this bug?

**Closed** 2020-09-20 15:22 UTC
Labels: verified
