### ISSUE TITLE
No print preview

### ISSUE THREAD

**Issue by Dan-Essin** [notepad-plus-plus/notepad-plus-plus#12977] opened 2023-01-28 20:48 UTC
### Description of the Issue
Since win 11 the print dialog has been replaced. The new one has big area that says "No preview available". Why is that?

### Steps to Reproduce the Issue

1. Choose print from file menu
2. 
3. 

### Expected Behavior

see a preview

### Actual Behavior

nothing

### Debug Information

Notepad++ v8.4.8   (32-bit)
Build time : Dec 24 2022 - 19:30:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Program Files (x86)\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1105
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

![2023-01-28_12h45_09](https://user-images.githubusercontent.com/1776053/215290471-6ed8f8ab-bc56-4f88-8ca6-8bebae37d2de.png)

**Comment by alankilborn** [comment] 2023-01-28 21:10
Has Notepad++ EVER offered "print preview"?

**Comment by donho** [comment] 2023-01-29 01:01
> Has Notepad++ EVER offered "print preview"?

No. Though it's "Nice to have" feature.

**Comment by rdipardo** [comment] 2023-01-29 01:06
Duplicate of [this community forum posting].

There's [a registry hack] to restore the old __*Windows system print dialog*__.

As already pointed out, there has never been a print preview dialog in Notepad++.


[this community forum posting]: https://community.notepad-plus-plus.org/topic/23972/what-is-this-horrible-print-dialog-in-windows-11/

[a registry hack]: https://www.winhelponline.com/blog/restore-legacy-print-dialog-windows-11/

**Comment by alankilborn** [comment] 2023-01-29 02:07
>>Has Notepad++ EVER offered "print preview"?

>No. Though it's "Nice to have" feature.

While I guess it is "nice to have", I don't want to see developers spending time on such things -- there are many better things to devote time to.
Really, I KNOW already what it will look like when printed.  The "editing" window pretty much tells that story.
If you REALLY want a preview, print to a PDF printer.

**Comment by tristengrant** [comment] 2023-01-31 03:27
Why would you need to print your code?

**Comment by CennoxX** [comment] 2023-02-08 20:47
Duplicate of  #4236

**Closed** 2024-12-24 12:50 UTC
Labels: duplicate
