### ISSUE TITLE
Feature request: make the F7 toggle Find Results window, not just open

### ISSUE THREAD

**Issue by greatspam** [notepad-plus-plus/notepad-plus-plus#7882] opened 2020-01-22 22:35 UTC
### Description of the Issue
F7 just opens the find results. would be nice if pressing again would close it. 
Alternatively, create a new shortcut so we can bind another key to close/hide the find results window

### Steps to Reproduce the Issue
1. Press F7 opens find  results
2. Press F7 again 

### Expected Behavior
Close the find results window

### Actual Behavior
changes focus back to editor

**Comment by sasumner** [comment] 2020-01-23 02:03
Closing as duplicate of #7766

**Closed by sasumner** 2020-01-23 02:03 UTC
