### ISSUE TITLE
Smart Highlighting - v.7.5.6 - Can't recognize the whole line selection

### ISSUE THREAD

**Issue by bnote** [notepad-plus-plus/notepad-plus-plus#4508] opened 2018-05-19 10:30 UTC
### Description of the Issue

Win 2003 EE SP2 32-bit

v.7.3.2 was updated by installer to 7.5.6 and the following issue of Smart Highlighting (SH) was discovered:

SH work OK when selection is made within a single pattern's source line. 

However, when the selection on the same line ..
- .. includes line-break or 
- .. the whole line is selected by LMB on the left field, 
SH can't recognize lines matching.

### Conditions of test's
For clear test both of bin 'Notepad++ zip packages 32-bit x86' of v. 7.3.2 and 7.5.6 was taken.

Both was installed in separate folders and was tuned identically:
- All extra tools was turned-Off by renaming its folders;
- Multiinstance was allowed always;
- 'New Document' settings was left as default: 
  'Win(CR LF)', 'UTF-8', 'Apply ANSY'-On;
- All SH options was cleared except 'Enable'-On only;
- 'Highlight Matching Tags' was left as default:
  'Enable'-On, 'Attributes'-On, 'Comments'-Off;
- 'Style Configurator' settings was left as default, but checked for equality.

In both of new created documets the similar test texts was typed.

The issue reproduced:
- in different encodings (Win-1251, f.e.);
- on saved or not files.

### Steps to Reproduce the Issue

See 'Description ..' & 'Conditions ..' above.

### Expected Behavior

Expected on higlighting the matches when the whole line is selected by:
- LMB dragging to end of line or
- LMB click on the left Npp-window area

### Actual Behavior

In both cases above the matches wasn't highlithed.

### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : E:\PRO\TextWork\NPP_732\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows Server 2003 (32-bit)
Plugins : none

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : E:\PRO\TextWork\NPP_756\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows Server 2003 (32-bit)
Plugins : none

![0519_084023](https://user-images.githubusercontent.com/26405324/40267517-47eec904-5b4d-11e8-8cc8-1fc0a58e4dab.png)

**Comment by sasumner** [comment] 2018-05-19 22:41
Seems to work as the OP says from 7.3.2 all the way thru and including 7.5.3.  Doesn't work from 7.5.4 onwards.

**Comment by sasumner** [comment] 2018-05-21 01:56
@bnote No need to add it to the title

**Comment by ArkadiuszMichalski** [comment] 2020-09-26 22:29
I can confirm this, works to 7.5.3 and stop in 7.5.4. In practice when we select single EOL the others EOL are not highlighted. So EOL is ignored, previouse behaviour also make sense. I wonder why this was changed (maybe intentional).

**Comment by sasumner** [comment] 2020-09-27 12:54
>I wonder why this was changed (maybe intentional).

I don't know the history, but I think it currently (e.g. 7.8.9) doesn't work because the intent is that it isn't supposed to work when the selected text is multiline.  Including a line-ending in the selection makes the data multiline.

So I'm closing this.

**Closed by sasumner** 2020-09-27 12:54 UTC
