### ISSUE TITLE
Serious Problems with Modifier Keys Remaining Active and with Shortcuts, Related with the User Being the Administrator or a Common User

### ISSUE THREAD

**Issue by Cambeiro** [notepad-plus-plus/notepad-plus-plus#2907] opened 2017-02-14 21:58 UTC
### Notepad++ is very frequently displaying the following problems, that seem related between themselves : 
=> Notepad is glueing the CTRL key (maybe also other modifier keys), which remains even in other programs, until I restart Windows 
=> To type a shortcut frequently does not trigger the defined action; instead, add a strange characters in the file, such as å, ETB and ENO in white letters on a black background, etc
=> Changes of the shortcuts in the 'Shortcup Mapper' dialog are not working. 
Note that these 3 problems involve the use of the modifier keys : Ctrl, Alt, Win, Shift. 

I have strong signals that these problems are also related with the condition of the user being the Windows administrator or a common user, for the following reasons : 
=> the glue of the CTRL key only happens, and frequently, when I use Notepad++ as a normal user, not when I use it as the Windows administrator. 
=> the replacement of the shortcut effect for the strange characters only happens when I use Notepad++ as the Windows administrator, but not when I use it as a normal user.

### Debug Information : 
All these problems are happening in the last versions of both 64-bit and 32-bit Notepad++, and only in it. 

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

I really hope you will find a solution to these problems, because I liked it very much, until these problems begun, about 3 or 4 month before, and who uses shortcuts can not work without them, what means that these problems are making the use of Notepad++ almost impossible.

**Comment by MetaChuh** [comment] 2019-04-11 22:56
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 22:56 UTC
