### ISSUE TITLE
[Enhancement] Scroll Preservation in Tabs

### ISSUE THREAD

**Issue by hppavilion1** [notepad-plus-plus/notepad-plus-plus#3408] opened 2017-06-18 03:43 UTC
### Scroll location not preserved on tab switch
When multiple tabs are open and one of them is long enough to require a scrollbar (but not longer than some value, it seems), going from a document with a scrollbar to another tab and back returns the scrollbar to the home position.

### Steps to Reproduce the Issue

1. Open 2 tabs in Notepad++, one of which must contain a document with enough lines to trigger a scrollbar but not be extraordinarily long.
2. Scroll down in the document with the scrollbar
3. Select the other tab
4. Go back to the first tab
5. Scrollbar has returned to the top position

### Expected Behavior

Optimally, the scrollbar would stay in the same location when the user changes tabs
### Actual Behavior

The scrollbar returns to the top (note that this doesn't seem to apply in longer documents, for some reason.)

**Comment by bahusoid** [comment] 2017-06-18 07:16
@hppavilion1  Define "with enough lines to trigger a scrollbar but not be extraordinarily long". How long your lines?  Can you reproduce the problem with empty lines?  Can you reproduce it with "Word Wrap" enabled/disabled? If you have document where problem is 100% reproducible - attach it.

**Comment by ei** [comment] 2017-06-18 07:46
I can't seem to be able to reproduce the problem. Could you provide your window size along with how many lines do you usually have when this problem occurs? Also post the debug info from the '?' menu.

Window size can be found in the `config.xml` file in `%USERPROFILE%\AppData\Roaming\Notepad++`. Go to the line that starts with `<GUIConfig name="AppPosition" ... />`

**Comment by hppavilion1** [comment] 2017-06-23 06:24
@bahusoid By "enough lines to trigger the scrollbar but not extraordinarily long" I mean that the number of lines in the document exceeds the number that can be displayed in one screen (so a scrollbar is visible), but the document is not several hundred lines long- I'm not sure where the boundary is, though I suspect it may have to do with word wrap being enabled (and this document having most every line wrap).

Unfortunately, I am suddenly unable to reproduce the issue and I'm kind of tired right now. This might be more effort than it's worth.

**Comment by hppavilion1** [comment] 2017-06-23 06:24
Um... oops. Didn't mean to close it.

**Comment by ArkadiuszMichalski** [comment] 2020-09-20 19:24
@donho @sasumner I can't reproduce this bug. Looks like even author cant (as wrote above), maybe close this bug?

**Closed** 2020-09-20 21:41 UTC
