### ISSUE TITLE
Visual glitch for toolbar icons

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#1697] opened 2016-03-31 16:36 UTC
Since version 6.9.0 (and now in 6.9.1) there is an ugly visual glitch when performing some actions. For example after using find&replace we end up with: http://oi65.tinypic.com/9qgwa9.jpg
Even more mess is when we open a new file and our tabbar goes to multiline: http://oi67.tinypic.com/10fnt7c.jpg
Looks like some issue with transparency.

OS: WinXP SP3 32b (yeah, yeah, I know, EoL, but clearly it's a regression)

**Comment by wilkowy** [comment] 2016-04-02 22:29
Just to update: it happens also on clean setup without any plugins installed.

**Comment by wilkowy** [comment] 2016-04-03 15:34
Bug introduced in 6.7.x (however for some reason I've found it since 6.9.x... I update regularly, weird) (6.6.9 ok, 6.7-6.7.2 crash, 6.7.3 broken)

**Comment by wilkowy** [comment] 2016-04-03 16:48
The bug is in SciLexer.dll. Using:
N++ 6.6.9 with SciLexer from N++ 6.6.9 - ok
N++ 6.6.9 with SciLexer from N++ 6.7.3 - bug appears (6.7-6.7.2 use SSE2 junk = crash)
Unfortunately I can't use newer N++ exe with older SciLexer.dll because find/replace won't work at all.

**Comment by MetaChuh** [comment] 2019-04-13 02:20
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:20 UTC
