### ISSUE TITLE
Search of long terms does not work any more in 7.7

### ISSUE THREAD

**Issue by papaschlumpf1** [notepad-plus-plus/notepad-plus-plus#5830] opened 2019-06-25 18:48 UTC
### Description of the Issue
Mark multible lines in a htm file, search and replace does not work any more since updated to 7.7
Was working great until 7.6.6

### Steps to Reproduce the Issue
1. I very often use notepad++ for editing htm files to search and replace wrong terms.
   Need to replace the same sh*t in multible files at the same time.
2. Therefore I mark the wrong lines in one file,
3. search and replace
4. replace by the right termin all in open files button
5. notepad does not find the term in the other files any more since update to 7.7
    but the exact term/code/text is present in the other files

### Expected Behavior
That it works as in 7.6.6
replace the multible lines of term/code/text in all open files

### Actual Behavior
nothing, does not find the term/code/text in the other files any more

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by papaschlumpf1** [comment] 2019-06-25 18:49
Short terms are still working !!!

**Comment by sasumner** [comment] 2019-06-25 19:01
I think you are going to have to provide examples for anyone to take your issue seriously.  For a sample of how to provide a good example, see how the poster of #5827 did it.

**Comment by dail8859** [comment] 2019-06-27 15:17
Closing due to insufficient information to reproduce the issue. Please provide detailed steps, such as an example file, and different search terms that show the issue.

**Comment by papaschlumpf1** [comment] 2019-06-27 15:48
here i have some example files

[example3.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3335524/example3.txt)
[example1.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3335525/example1.txt)
[example2.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3335526/example2.txt)

how I normally work:
+ open all 3 files with notepad++
+ mark the lines 18 - 89
+ Ctrl + H
+ replace with nothing
+ Button: Alle Funde in allen offenen Dateien ersetzen (replace all matches in all open files)

with 7.7 he find just 1 match
with 7.6.6 he find 3 matches (1 time in all files)


----------------------------------------------------------------------

if I mark just line 93 - 95
and do the same
replace with nothing
he can find 23 matches with 7.7
and 23 matches with 7.6.6


that facts make me think,
that there is a problem with the search function in 7.7

**Comment by sasumner** [comment] 2019-06-27 17:10
So the most text that can be put in the Find what box is 2046 characters.  In the example files, making the selection you indicate results in ~2066 characters being selected.  This seems to be the problem.

**Comment by papaschlumpf1** [comment] 2019-06-27 21:11
I know, 
   that after replacing, 
   there is still a rest of characters left
   =>i need to replace the rest with a second replace

but
if i just select lines 18 - 85 (1949 characters)
   it's not working too
   it just finds the characters in the current tab

and with the old version it was never a problem

+ if I find&replace the text in one tab
+ and then go to the next tab, Ctrl+H
    it finds the characters in this tab
+ and then go to the next tab, Ctrl+H
    it finds the characters in this tab

  => it don't want to find it with the button through all open tabs

and with just marking and replacing 3 lines
it's working

**Comment by sasumner** [comment] 2019-06-28 13:08
I can confirm @papaschlumpf1 's findings the provided example\*.txt files and using Notepad 7.7.1 (and also with a quick-check using 7.7 because that is the version this is reported under).  There *is* something odd going on with this, as 7.6.6 finds matches in all 3 files and 7.7+ doesn't.

**Comment by sasumner** [comment] 2019-06-28 13:09
@dail8859 , reopen?

**Comment by papaschlumpf1** [comment] 2019-10-05 20:43
yes, ekopalypse is right
searching for "ü, ä, ö, Ü, Ö, Ä" doesn't work any more

**Closed** 2020-06-21 00:18 UTC
