### ISSUE TITLE
[New Feature Request]  Multiline Find and Replace

### ISSUE THREAD

**Issue by wonkawilly** [notepad-plus-plus/notepad-plus-plus#4031] opened 2017-12-31 09:10 UTC
### Description of the New Feature Request
What about to Improve all the find and find and replace and find in file and mark dialogs by replacing the single line combo box with a multi line combo box /text box / text area field to allow a full multi line search and replace?

**Comment by ArkadiuszMichalski** [comment] 2023-02-24 01:18
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12834.

**Closed by ArkadiuszMichalski** 2023-02-24 01:18 UTC
