### ISSUE TITLE
Wrong Pascal highlighting

### ISSUE THREAD

**Issue by slypiggies** [notepad-plus-plus/notepad-plus-plus#2204] opened 2016-08-25 07:12 UTC
### Description of the Issue
Wrong Pascal highlighting

### Steps to Reproduce the Issue
1. Set "Language" to Pascal
2. Type something

### Expected Behavior
"for" is an instruction word obviously, so it should be blue.

### Actual Behavior
However, the colour of "for" in the editor is grey.

### Screenshot
![Bug](https://cloud.githubusercontent.com/assets/21236048/17959976/2756c61a-6ad6-11e6-87b7-f07dceab9f2b.png)

**Comment by dail8859** [comment] 2016-08-25 12:30
You are correct the styles were completely wrong for Pascal. PR #1912 has fixed the issue and will be in the next release of N++.

Duplicate of #249

**Closed by dail8859** 2016-08-25 12:30 UTC
