### ISSUE TITLE
Feature Request: Macro Menu - Sub-Menus

### ISSUE THREAD

**Issue by EVWeb** [notepad-plus-plus/notepad-plus-plus#3175] opened 2017-04-18 00:22 UTC
### Description of the Issue
I would like to see Notepad++ include an option to create sub-menus in the Macros menu to make managing a large number of Macros easier.

### Expected Behavior
The Macros Menu would be able to display a named sub-menu with several macros in it.

**Comment by ArkadiuszMichalski** [comment] 2021-12-29 01:46
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5349.

**Closed by ArkadiuszMichalski** 2021-12-29 01:46 UTC
