### ISSUE TITLE
Add Notepad++ to Default Programs

### ISSUE THREAD

**Issue by mohsentux** [notepad-plus-plus/notepad-plus-plus#1052] opened 2015-10-25 16:28 UTC
adding notepad++ to Control Panel\Programs\Default Programs\Set Default Programs helps a lot for users since it's file association is kinda broken on win 8/8.1/10

**Comment by United600** [comment] 2015-11-01 03:47
https://msdn.microsoft.com/library/cc144154%28v=VS.85%29.aspx

**Comment by meffect** [comment] 2016-11-07 19:44
What file extensions would you say should be program defaults? Just thinking out loud. ".txt", ".text", "[no extension]", ".xml", ".html", "html", ".css", ".json", ".js", ".crt", ".p12", ".key", ".ovpn", ".cmd", ".vbs", ".sh" . These are ones I set manually myself. I probably forgot some

**Comment by MetaChuh** [comment] 2019-04-10 23:37
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:37 UTC
