### ISSUE TITLE
Notepad++ 7.7 in ANSI encoding instead of Cyrillic characters "????????"

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5671] opened 2019-05-19 22:20 UTC
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Users\Uzeer\Downloads\npp.7.7.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : C:\Users\Uzeer\Downloads\npp.7.7.bin.minimalist.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none

![](https://i.imgur.com/oK4yEQ6.gif)

**Comment by rddim** [comment] 2019-05-21 20:35
Confirm

<details><summary>Click to expand</summary>

![](https://i.imgur.com/s9AZvWF.gif)
</details>

The screen is old, but the problem still exist

### Debug Info
Notepad++ v7.7   (64-bit)
Build time : May 19 2019 - 13:05:35
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AutoSave.dll ComparePlugin.dll ShtirlitzNppPlugin.dll TakeNotes.dll VisualStudioLineCopy.dll

**Comment by andrecool-68** [comment] 2019-05-23 07:42
@donho 
I have tested all versions of SciTE, starting with the version of Scintilla 3.6.7, problems with Cyrillic begin.

![Imgur](https://i.imgur.com/pvXRVek.png)

**Comment by donho** [comment] 2019-05-23 07:42
@rddim  & @andrecool-68 
So what's the native language of your OS ?

Is anyone can reproduce it under Windows 10 ?

**Comment by andrecool-68** [comment] 2019-05-23 07:44
@donho 
I have Win 7 x64 Russian version.

**Comment by MetaChuh** [comment] 2019-05-23 08:08
@donho 

just in case you see the same as i do:
this will be f. tricky to solve for a non native russian or bulgarian, if possible at all.

i was **never** able to insert cyrillic text to ansi files, on an english, spanish or german windows 10 and 7, regardless of the notepad++ version.
tested and re-tested on 7.5.5 to 7.7.
russian text to utf-8 works on all versions.
(see screencast below)

![7 6 6 cyrillic on ansi](https://user-images.githubusercontent.com/45773305/58235235-b8019080-7d40-11e9-81ef-6dec57de558b.gif)

greetings.

**Comment by donho** [comment] 2019-05-23 09:13
@andrecool-68 
> I have tested all versions of SciTE, starting with the version of Scintilla 3.6.7, problems with Cyrillic begin.

So Scintilla 3.6.6 works for you?
Typing Cyrillic in ANSI is broken in version 3.6.7 and later version, is that correct ?

**Comment by andrecool-68** [comment] 2019-05-23 10:06
@donho 
That's right, the problems start in version 3.6.7 and higher!

![333](https://user-images.githubusercontent.com/3471892/58244353-176c9a00-7d5b-11e9-9bd2-b7be8b1b38bc.gif)

**Comment by rddim** [comment] 2019-05-23 10:28
@donho 
Both machines (office laptop and home pc) are with **Win7 Pro x64 SP1 English**. I can not test on Win10.
Confirm that the problem start from `SciTE v3.6.7` and it is not broken in `SciTE v3.6.6`

**Comment by rddim** [comment] 2019-05-23 11:05
@donho 
I'm not sure is this will help you but: https://sourceforge.net/p/scintilla/bugs/2093/#3ee4

**Comment by andrecool-68** [comment] 2019-05-23 12:05
@donho 
I tried to make these changes, and Cyrillic appeared. But after each attempt to print a Cyrillic character, an error occurs)))
`+ case SC_CHARSET_DEFAULT: return documentCodePage; `
`- case SC_CHARSET_DEFAULT: вернуть documentCodePage? documentCodePage: 1252;`

**Comment by zufuliu** [comment] 2019-05-24 15:49
@andrecool-68 that's strange, `case SC_CHARSET_DEFAULT: return documentCodePage;` is the old code in Scintilla before 3.6.6 (used by npp before 7.7).

Can you test or debug Notepad2 (in both GDI and D2D mode, Settings -> Rendering Technology) at https://github.com/zufuliu/notepad2/releases
When debug assertion failed, choose to break, then look at the stacktrace, see where it failed.
With the stacktrace we may know how to fix it.

**Comment by ritmation** [comment] 2019-05-26 05:23
@donho I can confirm the bug also manifests itself on Windows 10 x64.
@zufuliu I've tested your Notepad2 builds and the text renders correctly in both D2D and GDI mode.

![image](https://user-images.githubusercontent.com/26736051/58377723-7b77a400-7f8f-11e9-8933-0dd410d25182.png)

**Comment by zufuliu** [comment] 2019-05-26 08:32
@rddim do select encoding to ANSI before typing? (via menu: File -> Encoding -> ANSI), because the default encoding is UTF-8. the status bar shows encoding name before EOL mode like CR+LF.

**Comment by rddim** [comment] 2019-05-26 11:54
@zufuliu 

Everything work as expected in Notepad2

![notepad2_ansi_cyrillic](https://user-images.githubusercontent.com/8998791/58381448-c44a4f80-7fc5-11e9-82f8-da21b32fac76.gif)

**Comment by zufuliu** [comment] 2019-05-26 13:09
@rddim thanks.

Screenshot from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-495190280 pointer to `_chvalidator` function. From the comment above the function, some ctype functions been called with out of range characters.
It's unknown where the call is, Scintilla it doesn't direct call ctype functions (except lexers).

@andrecool-68 can run your debug build of NPP under VS (click Local Windows Debugger), and take a screenshot of Call Stack when assertion failed?

**Comment by zufuliu** [comment] 2019-05-26 13:43
OK, I find out this code (already reported as issue #5280) cause assertion failure when typing non-ASCII characters (both ANSI and UTF-8 code page).

```cpp
static bool isAllDigits(const generic_string &str)
{
	return std::all_of(str.begin(), str.end(), ::isdigit);
}
```

**Comment by donho** [comment] 2019-05-26 13:49
@zufuliu
> OK, I find out this code (already reported as issue #5280) cause assertion failure when typing non-ASCII characters (both ANSI and UTF-8 code page).

It's used by Auto-completion of Notepad++, but nothing to do with the Russian input failure.
Any idea about the source of problem?

**Comment by donho** [comment] 2019-05-26 13:56
@andrecool-68 @rddim 
Could you disable auto-completion then try it again?

**Comment by rddim** [comment] 2019-05-26 14:07
@donho 

Same result - `кирилица` => `????????`

**Comment by zufuliu** [comment] 2019-05-26 14:12
I think the main reason is the change in Scintilla's CodePageFromCharSet:
```diff
-   case SC_CHARSET_DEFAULT: return documentCodePage;
+   case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;
```

Since SC_CHARSET_DEFAULT is used, so 1252 instead of 1251 is used to convert input Cyrillic characters, which maps to rubbish.

From discussion on bug https://sourceforge.net/p/scintilla/bugs/2093/#3ee4,
it's to suggested set font charset to SC_CHARSET_RUSSIAN in this case.
But from my experience, set locale depended charset need the font been used actual supporting the charset.
https://sourceforge.net/p/scintilla/bugs/2093/#263b/5bac/7f06

Revert back to `case SC_CHARSET_DEFAULT: return documentCodePage` is possible the simplest fix, because we known the code page we set to Scintilla are only UTF-8, DBCS ANSI code pages (932, 949, 950 and 1361) and SBCS ANSI code pages (0, CP_ACP).

@donho I suggest upgrade to 4.1.5, because the bug for tying DBCS https://sourceforge.net/p/scintilla/bugs/2093

**Comment by andrecool-68** [comment] 2019-05-26 19:26
@donho 
@zufuliu 

I compiled the original Scintilla 4.1.5, copied SciLexer.dll to the Notepad ++ directory. The result has not changed, instead of Cyrillic "?????"

![000](https://user-images.githubusercontent.com/3471892/58386133-f1b5ee00-8003-11e9-9881-ab26966a7d55.gif)

**Comment by zufuliu** [comment] 2019-05-26 23:12
@andrecool-68 with the change to Scintilla's CodePageFromCharSet (in ScintillaWin.cxx)?
```diff
+   case SC_CHARSET_DEFAULT: return documentCodePage;
-   case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;
```

The assertion failure is because auto-completion, you can disable auto-completion before testing.

**Comment by andrecool-68** [comment] 2019-05-26 23:17
@zufuliu I have not changed anything ... the original Scintilla downloaded from the official site

**Comment by zufuliu** [comment] 2019-05-27 00:08
@andrecool-68 please try changing CodePageFromCharSet  to `case SC_CHARSET_DEFAULT: return documentCodePage;`.

or add first line in `void ScintillaEditView::defineDocType(LangType typeDoc)` (line 1315 in PowerEditor\src\ScitillaComponent\ScintillaEditView.cpp)
```
    execute(SCI_STYLESETCHARACTERSET, STYLE_DEFAULT, SC_CHARSET_RUSSIAN);
    execute(SCI_STYLECLEARALL);
```

**Comment by andrecool-68** [comment] 2019-05-27 08:32
@donho
@zufuliu



> @andrecool-68 with the change to Scintilla's CodePageFromCharSet (in ScintillaWin.cxx)?
> 
> ```diff
> +   case SC_CHARSET_DEFAULT: return documentCodePage;
> -   case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;
> ```
> 
> The assertion failure is because auto-completion, you can disable auto-completion before testing.


In the debug build notepad ++ it worked!
Because it is not known how the second option will affect other languages.


> @andrecool-68 please try changing CodePageFromCharSet to `case SC_CHARSET_DEFAULT: return documentCodePage;`.
> 
> or add first line to `void ScintillaEditView::defineDocType(LangType typeDoc)` (line 1315 in PowerEditor\src\ScitillaComponent\ScintillaEditView.cpp)
> 
> ```
>     execute(SCI_STYLESETCHARACTERSET, STYLE_DEFAULT, SC_CHARSET_RUSSIAN);
>     execute(SCI_STYLECLEARALL);
> ```

Both options are working!
But I think it is better to make corrections in the file ScintillaWin.cxx ?!

![111](https://user-images.githubusercontent.com/3471892/58406523-75a6bf00-8072-11e9-8156-275446c71d62.gif)

**Comment by zufuliu** [comment] 2019-05-27 09:53
See my comment in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-496003800

I prefer to change Scintilla's CodePageFromCharSet.

**Comment by donho** [comment] 2019-05-27 10:39
@andrecool-68 @rddim 
Could you tried the new compiled Scilexer.dll (without boost's PCRE) ?
https://notepad-plus-plus.org/temp/

**Comment by andrecool-68** [comment] 2019-05-27 10:40
@zufuliu 
> See my comment in [#5671 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-496003800)
> 
> I prefer to change Scintilla's CodePageFromCharSet.

I said the same thing in the previous comment))

**Comment by donho** [comment] 2019-05-27 10:42
@zufuliu Thank you for your info.
Can you reproduce the bug (which is fixed in Scintilla 4.1.5) in Notepad++ 7.7 ?
If you can, could you provide the way to reproduce it?

**Comment by andrecool-68** [comment] 2019-05-27 10:50
@donho 
> @andrecool-68 @rddim
> Could you tried the new compiled Scilexer.dll (without boost's PCRE) ?
> https://notepad-plus-plus.org/temp/

With this file, Notepad ++ does not start at all, it gives an error "not found SciLexer.dll"

**Comment by zufuliu** [comment] 2019-05-27 10:56
@donho This is not fixed in 4.1.5, the line `case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;` has not changed since 2016.

Scintilla 4.1.5 fixed bug with typing DBSC characters in DBSC code pages.

**Comment by andrecool-68** [comment] 2019-05-27 11:00
namespace Scintilla {

	UINT CodePageFromCharSet(DWORD characterSet, UINT documentCodePage) {
		if (documentCodePage == SC_CP_UTF8) {
			return SC_CP_UTF8;
		}
		switch (characterSet) {
		case SC_CHARSET_ANSI: return 1252;
		case SC_CHARSET_DEFAULT: return documentCodePage;
		// case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;

C:\Users\Uzzer\Downloads\notepad-plus-plus-master\scintilla\win32\ScintillaWin.cxx

**Comment by donho** [comment] 2019-05-27 11:17
@zufuliu 
> Scintilla 4.1.5 fixed bug with typing DBSC characters in DBSC code pages.

I have tested Notepad++ 7.7 under Windows 7 Chinese version.
The Chinese input in ANSI mode works in v7.7.
So for me there's no DBSC issue - at least for Chinese.
Have you any steady way to produce DBSC issue in Notepad++ v7.7 ?

**Comment by rddim** [comment] 2019-05-27 11:20
@donho 

* With `v7.7` and `SciLexer.64.dll` renamed to `SciLexer.dll` gives certification error
* With https://notepad-plus-plus.org/pluginListTestTools/notepad++.debug.x64.zip gives:
![npp64_debug_scilexer_test](https://user-images.githubusercontent.com/8998791/58416501-721f3200-808a-11e9-8511-894d436f668f.png)

**Comment by zufuliu** [comment] 2019-05-27 11:22
@donho see the bug report at https://sourceforge.net/p/scintilla/bugs/2093/
It can be reproduced with NPP 7.7 binary.

**Comment by zufuliu** [comment] 2019-05-27 11:36
@donho the bug (Typing DBCS) at https://sourceforge.net/p/scintilla/bugs/2093/ and another bug (Inline IME) at https://sourceforge.net/p/scintilla/bugs/2038/ (not fixed) will affect auto-completion.
I think NPP can simply ignore any ch > 0x7F in DBCS code pages or when ch is input from IME, auto-completion for CJK words is meanness.

**Comment by donho** [comment] 2019-05-27 11:46
@andrecool-68  @rddim 
Please try this x64 build. Works only with Notepad++ debug mode, since it's not signed.

**Comment by rddim** [comment] 2019-05-27 12:05
@donho 

Another try this time with https://notepad-plus-plus.org/pluginListTestTools/notepad++.debug.x86.zip and `SciLexer.32.dll` gives me the same as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-495190280 screen

I don't know how to run N++ in debug mode. If you mean something like from VS, I don't have VS.

**Comment by andrecool-68** [comment] 2019-05-27 12:26
@donho 
![Безымянный](https://user-images.githubusercontent.com/3471892/58419404-3341aa00-8093-11e9-9e0a-6507bdb90f86.png)

![2](https://user-images.githubusercontent.com/3471892/58419605-c084fe80-8093-11e9-8228-022d7f8a2ff0.png)

**Comment by donho** [comment] 2019-05-27 12:35
@andrecool-68 @rddim 
Thank you for you test. It seems it's not the solution what @zufuliu has suggested:
```diff
+   case SC_CHARSET_DEFAULT: return documentCodePage;
-   case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;
```

**Comment by zufuliu** [comment] 2019-05-27 12:58
That's also interesting, it works in debug mode (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-496128852) but not release mode?

at least Notaped2 use the change https://github.com/zufuliu/notepad2/blob/master/scintilla/win32/ScintillaWin.cxx#L1292

**Comment by andrecool-68** [comment] 2019-05-27 12:59
@donho 
![Безымянный](https://user-images.githubusercontent.com/3471892/58421302-473bda80-8098-11e9-9246-6cb80c990c9a.png)

![222](https://user-images.githubusercontent.com/3471892/58421319-515dd900-8098-11e9-8329-c0472c4bfcaa.gif)

**Comment by zufuliu** [comment] 2019-05-27 13:11
@andrecool-68 first line of `execute(SCI_STYLECLEARALL);` can be omitted.

**Comment by andrecool-68** [comment] 2019-05-27 13:14
@zufuliu 
I did not notice the duplication of the line ... you need to make a smoke break)))

**Comment by rddim** [comment] 2019-05-27 13:38
@donho 

After a smoke break too with `notepad++.debug.x86.zip`, `SciLexer.32.dll` and **disabled** `Auto-Completion` everything work as expected. With enabled `Auto-Completion` it gives me the previously mentioned error

**Comment by andrecool-68** [comment] 2019-05-27 15:09
@donho How can I turn off the "scintilla" certificate verification ... so that can test the release builds

**Comment by donho** [comment] 2019-05-27 18:19
> After a smoke break too with notepad++.debug.x86.zip, SciLexer.32.dll and disabled Auto-Completion everything work as expected. With enabled Auto-Completion it gives me the previously mentioned error

So smoking is bad for the health, but good for program test ? :D

> How can I turn off the "scintilla" certificate verification?

You can't. I will provide you guys the 32 & 64 signed release binary to make sure everything is OK.

@zufuliu  So your solution works. Thank you. However, Does this modification create any side effect?

**Comment by andrecool-68** [comment] 2019-05-27 19:44
@donho Truth is born in any dispute

**Comment by andrecool-68** [comment] 2019-05-27 19:54
@zufuliu thanks for your help

**Comment by donho** [comment] 2019-05-27 20:03
@rddim @andrecool-68 
https://notepad-plus-plus.org/temp/

**Comment by andrecool-68** [comment] 2019-05-27 20:24
@donho 
while it works ... what fix did you do?

**Comment by rddim** [comment] 2019-05-27 20:42
Woohoo it's alive :D Now about 275 million peoples can type Cyrillic in ANSI
Thank you very much @andrecool-68 @rddim @donho @MetaChuh @zufuliu 

![npp_ansi_solved](https://user-images.githubusercontent.com/8998791/58438738-0adc9e80-80d9-11e9-8992-56f51967d655.gif)

**Comment by andrecool-68** [comment] 2019-05-27 20:56
It doesn't matter to me at all ... but my friends need 1255 and 1251.

**Comment by MetaChuh** [comment] 2019-05-27 21:03
@andrecool-68 
lol ... after what we have read today, it's better to put a black censor bar on your posted image, to make sure we don't offend anybody 😂

@rddim 
i'm the bad cop, so no need for any thanks towards me.
it is don's private initiative to pursue this issue with all your collective help, despite newer scintilla versions being the cause.

best regards.

**Comment by andrecool-68** [comment] 2019-05-27 21:15
@MetaChuh 
My dog is very tolerant to motorcycle drivers

**Comment by andrecool-68** [comment] 2019-05-27 21:21
@MetaChuh 
You are cunning ... you have something from a Jew

**Comment by zufuliu** [comment] 2019-05-27 22:20
> 
> 
> @zufuliu thanks for your help
> Your editor supports localization?

Sorry, no plan on i18n.

**Comment by zufuliu** [comment] 2019-05-27 22:24
> 
> 
> > After a smoke break too with notepad++.debug.x86.zip, SciLexer.32.dll and disabled Auto-Completion everything work as expected. With enabled Auto-Completion it gives me the previously mentioned error
> 
> So smoking is bad for the health, but good for program test ? :D
> 
> > How can I turn off the "scintilla" certificate verification?
> 
> You can't. I will provide you guys the 32 & 64 signed release binary to make sure everything is OK.
> 
> @zufuliu So your solution works. Thank you. However, Does this modification create any side effect?

What solution? change Scintilla's CodePageFromCharSet or using SCI_STYLESETCHARACTERSET? the former returns ACP (0), should has side effect, the later has, see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-496003800.

**Comment by Commander238** [comment] 2019-05-28 14:49
I had a simmilar issue with Notepad++ 7.7 32-bit, Czech language (windows-1250). 
I was unable to type or paste some Czech letters in ANSI encoding. 

Replacing the SciLexer.dll with the one provided (SciLexer32.signed.dll 27-May-2019 22:00) helped, the issue is gone.

**Comment by lehha** [comment] 2019-05-31 12:49
Will be an Update for npp?

**Comment by donho** [comment] 2019-06-02 15:05
@andrecool-68 & @rddim  
So the new Scilexer.dll works for you but you have to disable Auto-Completion right?

**Comment by andrecool-68** [comment] 2019-06-02 16:00
@donho 
With new Scilexer files.dll errors with Cyrillic I do not see and autocomplete works.
https://notepad-plus-plus.org/temp/cyrillacPb/
![000](https://user-images.githubusercontent.com/3471892/58763769-05170b00-8568-11e9-845b-f9223c1e0461.gif)

**Comment by lehha** [comment] 2019-06-03 12:46
Thanks! I cant see direct links above, so there is:

https://notepad-plus-plus.org/temp/cyrillacPb/SciLexer32.signed.dll
or
https://notepad-plus-plus.org/temp/cyrillacPb/SciLexer64.signed.dll

Must to be replaced SciLexer.dll in C:\Program Files (x86)\Notepad++

**Comment by rddim** [comment] 2019-06-04 11:01
@donho 

With the SciLexers from https://notepad-plus-plus.org/temp/cyrillacPb/ it works with enabled Auto-Completion, i.e. no problems. It doesn't work with combination from this comment https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5671#issuecomment-496189871 which is also the answer for `"previously mentioned error"`

**Comment by donho** [comment] 2019-06-04 11:08
@rddim  So for you  SciLexers from https://notepad-plus-plus.org/temp/cyrillacPb/ has fixed the problem without any side effect ?

**Comment by rddim** [comment] 2019-06-04 11:35
@donho I test it again to be sure and:
* the x64 SciLexer works perfect - no issues for now, cyrillic works and Auto-Completion works in ANSI
* the x32 - I can type in cyrillic, but Auto-Completion doesn't work, it work with latin chars

**Comment by andrecool-68** [comment] 2019-06-04 11:56
@rddim Restart your notepad ++ and re-open this file ... and what do you see?

**Comment by rddim** [comment] 2019-06-04 12:26
@andrecool-68 both x32 and x64 are readable asfter reopen

![npp_reopen](https://user-images.githubusercontent.com/8998791/58878925-1df4fd00-86dd-11e9-9b2e-3c3a45613d47.png)

**Comment by andrecool-68** [comment] 2019-06-04 12:35
@rddim `Autodetect character encoding` enabled&

**Comment by rddim** [comment] 2019-06-04 12:40
@andrecool-68 Yes, default settings, thats why it is `Windows-1251` but not `ANSI`

**Comment by rddim** [comment] 2019-06-04 14:03
@andrecool-68 @donho 
In x32 when the word begin with small letter `Auto-Completion` doesn't work for it, but not always (`new 3`). I think the other issues are with `Autodetect character encoding`

![npp_x32_cyr1](https://user-images.githubusercontent.com/8998791/58885199-6ff04f80-86ea-11e9-98f0-4f38c1b4f0ad.gif)

**Comment by andrecool-68** [comment] 2019-06-04 14:17
@rddim The fourth tab was obtained Hebrew))

**Comment by rddim** [comment] 2019-06-04 14:24
@andrecool-68 external clipboard manager - [CLCL](https://www.nakka.com/soft/clcl/index_eng.html)

**Comment by andrecool-68** [comment] 2019-06-05 06:24
@rddim 
How can I disable these lines, I can not find it in the settings

![Imgur](https://i.imgur.com/qDeBonJ.png)

**Comment by rddim** [comment] 2019-06-05 08:59
@andrecool-68 
Write me an email, you can find it in bulgarian.xml. I can answer you here of course, but this is an N++ issue, not for other programs :)

**Comment by patrickdrd** [comment] 2019-06-06 12:53
can somebody help me too?
I think my issue is similar,
I posted in npp community (in 7.7 version's thread) but I wasn't able to receive the support I requested, I never figured out why..

anyway, 
I'm re-posting here:

I’m receiving sql queries by email that I open with npp and 
I then copy the file content to sql manager program in order to execute them, 
well, with 7.7 Greek characters are displayed like Chinese, I rolled back to 7.6.6 and they display properly

**Comment by donho** [comment] 2019-06-09 22:00
@patrickdrd @rddim @andrecool-68 
Could you guys test the following binaries and confirm me the bug is fixed and without regression please?
32 bits:
https://notepad-plus-plus.org/temp/cyrillacPb/npp.7.7.bin.zip
64 bits:
https://notepad-plus-plus.org/temp/cyrillacPb/npp.7.7.bin.x64.zip

**Comment by patrickdrd** [comment] 2019-06-09 22:14
I've just tested the 32-bit and it looks good,
even though it will be some hours till I will be able to test the same scenario

**Comment by patrickdrd** [comment] 2019-06-10 07:24
ok, original scenario works too

**Comment by andrecool-68** [comment] 2019-06-10 10:19
@donho  When you reopen the file, the initial characters disappear.
 Most likely to blame "Auto-detect character encoding"
(`Autodetect character encoding`  and  `auto-completion`  Enable)

**Comment by donho** [comment] 2019-06-10 20:29
@andrecool-68  I need your confirmation after testing the both binaries I provide. This problem is another one. Let's fix problem one after another, otherwise you just confuse everybody and it doesn't help at all !

**Comment by andrecool-68** [comment] 2019-06-10 23:01
@donho Maybe my words you do not understand ... excuse me, but I write through translate.google))
 I wanted to say that I tested both files, and the Cyrillic alphabet was printed without errors.
And the fact that the artifacts when re-opening the file ... I myself do not know ... this is the continuation of the old or new error.
What I notice when testing ... then I inform you

**Closed** 2019-06-11 07:48 UTC

**Comment by andrecool-68** [comment] 2019-06-11 12:43
@donho 
I compiled the debug build Notepad ++ with "scintilla416" (with the same changes), 

	// case SC_CHARSET_DEFAULT: return documentCodePage ? documentCodePage : 1252;
	case SC_CHARSET_DEFAULT: return documentCodePage;

the automatic definition of the encoding is disabled ... then there are no problems with Cyrillic.

If "automatic encoding detection" is enabled, then exactly the same artifacts with the encoding as I wrote in the previous post.
![Безымянный](https://user-images.githubusercontent.com/3471892/59271532-b13dad80-8c5c-11e9-9a59-78e83a01bb84.png)

Maybe this will help you in some way.

**Comment by donho** [comment] 2019-06-12 08:33
> If "automatic encoding detection" is enabled, then exactly the same artifacts with the encoding as I wrote in the previous post.

So it's the issue of "automatic encoding detection". Please create a new issue for that.

**Comment by rddim** [comment] 2019-06-15 07:40
@donho sorry for the late answer, I was very busy and away from home.
The fix works perfect. Thanks

**Comment by patrickdrd** [comment] 2020-06-09 10:30
this problems still persists I'm afraid guys,
a text document with greek characters isn't displayed properly on my windows 7 32-bit desktop,
while it shows fine on windows 8 64-bit and if using another editor as well
