### ISSUE TITLE
"Default Directory" preference no longer works since the 7.95 release

### ISSUE THREAD

**Issue by Kimpa-Tammas** [notepad-plus-plus/notepad-plus-plus#9767] opened 2021-04-13 16:45 UTC
### Description of the Issue
I always use the "Default Directory" preference as "Remember last used directory", but since the 7.95 release, the location of the file selector is always the Notepad++ installation folder.

### Steps to Reproduce the Issue
1. Go to Settings > Preferences > Default Directory and set as "Remember last used directory". Close Preferences.
2. Open a file from another drive and folder.
3. Try to open a new file or Save As/Save a Copy As the current file.
or
1. Go to Settings > Preferences > Default Directory and set a custom path. Close Preferences.
2. Try to open a file from another drive and folder.

### Expected Behavior
If Default Directory is set as "Remember last used directory" and after to load or save a file from a specific directory, the location of the file selector must be the last used folder. Same thing with I set a custom path, the location of the file selector must be this one.

### Actual Behavior
The location of the file selector is always the Notepad++ installation folder.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\NotePad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1443
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll Explorer.dll HTMLTag.dll ImgTag.dll mimeTools.dll NppConverter.dll NppExport.dll NppSnippets.dll _CustomizeToolbar.dll

**Comment by mere-human** [comment] 2021-04-13 18:54
I can reproduce it. 
@sasumner Could you, please, assign to me?

**Comment by sasumner** [comment] 2021-04-13 20:12
Yes.  Is this another thing relating to new Open/Save dialogs?

**Comment by mere-human** [comment] 2021-04-13 20:16
> Yes. Is this another thing relating to new Open/Save dialogs?

Apparently yes. 
Turns out, the Common Item Dialog does the right thing and doesn't change the current directory. 
Unlike the old dialogs invoked by `Get­Save­File­Name()` or `GetOpenFileName()`.
Here is more info on this: https://devblogs.microsoft.com/oldnewthing/20101112-00/?p=12293

But the Notepad++ code relies on that here:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/OpenSaveFileDialog/CustomFileDialog.cpp#L184

**Comment by sasumner** [comment] 2021-04-13 20:23
Gotta love the old-new-thing. :-)

Can you also do an evaluation to see if this choice has any problems, as well?:

![image](https://user-images.githubusercontent.com/30118311/114616165-8bc4c500-9c74-11eb-91f2-7a9ada5d2ef5.png)

If so, could be fixed under this issue as well.

**Comment by mere-human** [comment] 2021-04-13 20:27
> Can you also do an evaluation to see if this choice has any problems, as well?:

This seems to be working fine.

**Comment by mere-human** [comment] 2021-04-15 19:09
I have a solution but I'll post it once #9732 gets approved to avoid unnecessary merge.

**Closed** 2021-04-22 17:20 UTC
Labels: accepted, bug

**Comment by aybe** [comment] 2022-09-09 14:28
Sorry to necro post but that still happens on version: 8.4.4

That option only works while the software is open, if you relaunch it, then it defaults to `C:\Program Files\Notepad++` again.

Additionally, couldn't it default to, say, `Desktop`, because `C:\Program Files\Notepad++` is read-only by nature?

Thank you 😀

**Comment by alankilborn** [comment] 2022-09-09 17:46
>That option only works while the software is open, if you relaunch it, then it defaults to...

It appears to do that "by design".  I'll initiate a clarification on this point for the user manual.

>Additionally, couldn't it default to, say, Desktop,...

That aspect deserves its own new issue; I'll let you handle creating that one if you choose to.

**Comment by aybe** [comment] 2022-09-09 20:44
> It appears to do that "by design". I'll initiate a clarification on this point for the user manual.
 
From user experience standpoint, just as there are recent files in File menu, it makes a lot of sense to keep track of last used directory.

This could maybe be a toggleable option for those who wish to retain the old behavior.

> That aspect deserves its own new issue; I'll let you handle creating that one if you choose to.

Yes, here it is: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12137
