### ISSUE TITLE
Feature Request: Don't remember last window position

### ISSUE THREAD

**Issue by MattAllison** [notepad-plus-plus/notepad-plus-plus#1059] opened 2015-10-27 18:16 UTC
I frequently switch between dual monitors and just my laptop screen.  Notepad++ has the (sometimes desirable) feature of remembering window position which is sometimes outside of the actual display area (e.g. on my 2nd monitor back at the office).

Behavior should be that the window is always within a displayable region, but as an alternative enable a setting that says "don't remember window position" and allow native OS window placement.

**Comment by TristisOris** [comment] 2018-06-14 10:08
trouble still persist.

NP launching on 2nd monitor even if it turned off and missing in the system.

**Comment by MetaChuh** [comment] 2019-04-10 23:34
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:34 UTC
