### ISSUE TITLE
Toggle search results window

### ISSUE THREAD

**Issue by KolyaKorruptis** [notepad-plus-plus/notepad-plus-plus#61] opened 2015-05-13 08:50 UTC
F7 opens the search results but does not close the window when it's open. 
Please make F7 a toggle or add a toggle as an extra function that can be assigned a shortcut. 
It would be much appreciated. :)

**Comment by Vinatorul** [comment] 2015-05-24 17:42
I think it is feature that F7 does not close the window. Pressing F7 you can fast switch between main windows and search window. 
May be it should be other hotkey to close it (Alt+F7 for example), or setting in MISC section.

By the way, I can do it as my first contribution to notepad++ :)

**Comment by MetaChuh** [comment] 2019-04-08 09:58
closed due to inactivity and being by design.
f7 will toggle focus between the search results and the editor window, to quickly switch between search results and editing with a key press.

**Closed by MetaChuh** 2019-04-08 09:58 UTC
