### ISSUE TITLE
Single quote escape in Shell syntax highlighter seems broken

### ISSUE THREAD

**Issue by mat-m** [notepad-plus-plus/notepad-plus-plus#3821] opened 2017-10-13 12:21 UTC
### Description of the Issue
When a string in shell is surrounded by double quotes, and you want to write the double quote symbol inside, you have to escape it with a backslash. The syntax highlighter (SH) detects it and continues to consider following text as part of the string
When a string in shell is surrounded by single quotes (to avoid variable expansion, e.g.), and you want to write the single quote symbol inside, you have to escape it with a backslash. But then, The syntax highlighter doesn't detect the bckslash ad considers the inside quote as the end of the string, breaking the highlighting.

### Steps to Reproduce the Issue

1. Open a new tab
2. Define Syntax as Shell
3. Paste: ````print 'this is a string but \'escaped quotes are not "detected"\''
print "it seems to me"```

### Expected Behavior

The second print should be in the same color as the first one (instruction and not string)

### Actual Behavior

![image](https://user-images.githubusercontent.com/1039753/31545507-f96264ae-b01f-11e7-80f6-de854fd51ff5.png)

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll 

BTW, naming is confusing:
* In status bar, we have **Unix script file**
* In Language menu, we have **shell**
* In Settings/Style Configurator, we have **bash**

**Comment by zaffinger** [comment] 2017-10-25 07:19
I claim this is not resetricted to Shell only. It seems this is an overall issue.

![image](https://user-images.githubusercontent.com/5217339/31985486-909cf4f8-b965-11e7-81df-4f124af52352.png)

**Comment by pingpong2011** [comment] 2017-11-10 20:26
Shell is behaving properly. If you tried your script you would even recognize print is not a shell command for _echo_ ing text.

This is a standard behavior in shells, with _languages_ having different behavior: shells use single quotes completely literally, and some languages (like Perl grumble grumble) letting you interpret variables or escapes within single quotes (why even have them if they can't do literal stuff?) . I'd wager it is truly this in all POSIX compliant shells.

To work around it, you usually have to do something like: echo 'This is a single' "'" 'quote.' or just use double quotes most of the time.

It's frustrating when you're going between a lot of things; one solution I found was repeatedly concatenating the string with STRING+='literal'stuff' and then STRING+="${interpretedthing}"

**Comment by mat-m** [comment] 2017-11-14 23:38
@pingpong2011 : that was not the point. Even if I replace print with echo there will be a failure in *syntax highlighting* with respect to escaped single quotes.

**Comment by immewnity** [comment] 2018-07-06 20:35
Bug still exists as of v6.9.1. I noticed it while editing PowerShell code with escaped double quotes. PowerShell uses the back tick (`) as the escape character - so, assuming GitHub doesn't mess with the formatting...

<code>Read-Host -Prompt "`"String`""</code> will give an output of "String", but Notepad++'s coloring will think that the String text isn't a string at all.

**Comment by wlfbck** [comment] 2019-04-23 13:27
Yeap, still broken, this line can trigger it:

> echo "some text \"other text\" `grep text $directory/var/lib/bla.txt | cut -d \\" -f 4`" >/tmp/blub.sh

If you remove the one of the \ from \\" the highlighting works again.

**Comment by sasumner** [comment] 2019-04-23 13:30
Isn't it a Scintilla issue?

**Comment by wlfbck** [comment] 2019-04-23 13:33
No idea - i have no idea what Scintilla even is ;) Just reporting that this issue still exists because i just encountered it in one of our old scripts.

**Comment by sasumner** [comment] 2019-04-23 13:38
Scintilla is the editing component that Notepad++ embeds.  It is a separate project.  Lexing ("syntax highlighting") such as you describe is handled by the Scintilla component.  All Notepad++ can do is tell the component what to do (at a high level).  If it is lexing something wrongly it is beyond Notepad++'s control.  That being said, Notepad++ embeds a very old Scintilla version.  A port to a new version is underway currently. Perhaps the newer version will fix this lexing bug. If it doesn't there really isn't anything Notepad++ can do about it.

**Comment by wlfbck** [comment] 2019-04-23 14:28
I see, thank you for the explanation! :)
Actually is a bug in Scintilla, i reported it there.

**Comment by duaneking** [comment] 2020-01-18 20:01
Bug still exists, its not detecting opening and closing " characters correctly.  Fully kills my ability to use notepad++ as an editor for most of the languages I had planned on working with today.

**Comment by ArkadiuszMichalski** [comment] 2020-10-01 22:41
This is not a bug, please use Google how you should escape single ' between single ' for bash or shell (related to highlighter we consider bash because Notepad++ use lexer for bash).

Code from OP:
```bash
echo 'this is a string but \'escaped quotes are not "detected"\''
echo "it seems to me"
```

After correct (one possibility, there are more):
```bash
echo $'this is a string but \'escaped quotes are not "detected"\''
echo "it seems to me"
```

Efect:
![a](https://user-images.githubusercontent.com/2730894/94869187-1c5c5600-0445-11eb-877f-5e3092d38f5a.gif)

For shell you can do some trick, but rule is: "A single quote may not occur betweeen single quotes even when preceded by a backslash' "
https://superuser.com/questions/481797/how-do-you-escape-apostrophe-in-single-quoted-string-in-bash
https://unix.stackexchange.com/questions/30903/how-to-escape-quotes-in-shell
https://stackoverflow.com/questions/8254120/how-to-escape-a-single-quote-in-single-quote-string-in-bash#

One of them is:
```bash
echo 'I'"'"'m a student'
```

Confusing with naming was discussed here https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8931.

**Comment by donho** [comment] 2020-10-02 13:10
As @pingpong2011 & @ArkadiuszMichalski pointed out, it's not a bug, so closing.

**Closed by donho** 2020-10-02 13:10 UTC
Labels: language-support
