### ISSUE TITLE
"Open File" dialog shows "Save" button

### ISSUE THREAD

**Issue by baumertjohn** [notepad-plus-plus/notepad-plus-plus#9966] opened 2021-06-08 02:46 UTC
### Description of the Issue
When Opening a file, the dialog box shows "Save" and "Cancel"

### Steps to Reproduce the Issue

1. Open Notepad ++
2. Select File / Open

### Expected Behavior
The window should show "Open" / "Cancel"

### Actual Behavior
(See description of the issue)

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.985
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/36886175/121114728-6b773980-c7d1-11eb-9d87-3a3bc91312a7.png)

**Comment by mere-human** [comment] 2021-06-08 08:15
I can confirm.
@sasumner Assign this to me, please.

**Comment by sasumner** [comment] 2021-06-08 11:42
Wow -- how could that have gone unnoticed for so long?? :-)

**Comment by mere-human** [comment] 2021-06-08 16:52
> Wow -- how could that have gone unnoticed for so long?? :-)

😔
I don't know. 
I think we are so used to the buttons and their locations, so that we're not really reading the labels.

Because we need unit tests and/or automation tests.
I have to do that ASAP.

> Just a side note...should a toggle of the Alt key with the dialog open underline the `O` in _Open_ ?

Sure, it should. It works with Save dialog. But there is a bug with Open dialog.
The file dialog sets the OK button label, then does a search of the button within a dialog to override its window procedure, then reverts the original label for button.
So the label is needed to differentiate from other buttons. File dialog has the same localization as OS, so we can't just compare it to `"&Save"`.
But for some unknown for me reason `IFileDialog::SetOkButtonLabel(nullptr)` returns the original label for save dialog and does nothing for open dialog.
So I'm thinking about alternative solution.

**Comment by donho** [comment] 2021-06-09 00:49
Damn!

**Closed** 2021-06-11 17:59 UTC
Labels: accepted, regression
