### ISSUE TITLE
COBOL comment on column 7

### ISSUE THREAD

**Issue by nunoperalta** [notepad-plus-plus/notepad-plus-plus#2805] opened 2017-01-19 19:19 UTC
### Description of the Issue
The COBOL parser doesn't make a comment green if there is a character just before the star `(*)`.
In my environment, we put tags everywhere, and most of them have 6 characters, so most of the COBOL comments are not correctly parsed in Notepad++, and this creates a big confusion sometimes.
It is perfectly valid to have a tag of 6 characters and a star `(*)` just after that, and that should be parsed as a comment.

### Steps to Reproduce the Issue
![sshot-2014-06-25-10-55-02-1](https://cloud.githubusercontent.com/assets/487079/22121411/d1312d06-de7b-11e6-93a8-c6917d1ce864.jpg)

### Debug Information
Notepad++ v7.3   (32-bit)
Build time : Jan  1 2017 - 20:04:42
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll CustomizeToolbar.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll

**Comment by dail8859** [comment] 2017-01-19 19:46
Duplicate of #280

This is a problem with Scintilla (and needs reported to that project). Here is a screenshot of SciTE v3.7.2

![capture](https://cloud.githubusercontent.com/assets/3694843/22122418/e7a51c26-de55-11e6-95bc-c0b95948e06e.PNG)

**Comment by nunoperalta** [comment] 2017-01-19 19:50
Oh - I didn't realize the issues were migrated from SourceForge :)
Thank you. I'll report to Scintilla.

**Comment by ArkadiuszMichalski** [comment] 2020-09-24 18:43
https://sourceforge.net/p/scintilla/bugs/1893/

**Comment by nunoperalta** [comment] 2020-09-24 19:44
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/280

**Closed** 2020-09-25 03:03 UTC
Labels: language-support
