### ISSUE TITLE
Double click a word is not working

### ISSUE THREAD

**Issue by ahmedhamdy90** [notepad-plus-plus/notepad-plus-plus#3895] opened 2017-11-17 15:52 UTC
### Description of the Issue

After the recent update, when I double click a word, it is no longer highlighted. I have to slow my double-click speed in order to select a word, or I use mouse dragging to select it.
Double click working fine in chrome, edge, eclipse, sublime, and even the default windows notepad!

### Steps to Reproduce the Issue

1. open notepad++
2. try to double-click any word with normal (as usual) speed

### Expected Behavior

Selecting the current word and highlight all its occurrences 

### Actual Behavior

Nothing is happening, no word highlighting, no occurrences highlighting

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Things I did to resolve the issue
1. I tried to uninstall and install the 64-bit version --> still not fixed
2. I tried to make a clean uninstall (plugins, setting, and config) and install the 64-bit version --> still not fixed
3. I tried to make a clean uninstall again and install the 32-bit version again --> still not fixed 

Kindly find a gif showing the issue, this gif contains 3 double clicks: normal, slow, and fast double click on a word.
Normal and fast double click is not working properly on Notepad++, but they work fine in any other program.
![issue](https://user-images.githubusercontent.com/252999/32956707-347321d8-cbc2-11e7-9898-717ab6e33eb8.gif)

**Comment by encore0117** [comment] 2017-11-21 04:13
Does this issue persists if running on other machines?

I just tried running the same version in the same system, but I could not replicate the issue.

**Comment by xv** [comment] 2017-11-22 08:33
Are you double clicking with a mouse or a touchpad? If it's a touchpad, you're not alone; however, this seems to be a Scintilla issue not a NP++ one. I tried multiple Scintilla-based editors and they all have the same problem. I don't recall having this issue few months ago. I assume it's caused either by a Windows 10 update or a Synaptics driver update.

**Comment by ahmedhamdy90** [comment] 2017-11-22 15:45
@xv yes, I am using the touchpad. My laptop is dell inspiron 7559.

**Comment by xv** [comment] 2017-11-22 18:14
@ahmedhamdy90 I have the exactly same laptop that is suffering from what you had described. Like I said, this is definitely not a Notepad++ issue. Double clicking works fine elsewhere, but on any Scintilla component, behavior is abnormal.

**Comment by ahmedhamdy90** [comment] 2017-11-22 18:23
@xv But I have all the other tools working fine, Notepad++ is the only one having a problem.

**Comment by xv** [comment] 2017-11-22 19:13
@ahmedhamdy90 That's what I'm saying. Notepad++ uses a text editing component called Scintilla. The issue you are describing seems to be **affecting all text editors that use Scintilla** as their text editing component.

You can download SciTE (editor part of the Scintilla project), or any other Scintilla-based editor such as Notepad2/3, Geany, etc and see for yourself.

I think it's more wise to [report this issue to the developers of Scintilla](https://sourceforge.net/p/scintilla/bugs/) itself.

**Comment by jatlast** [comment] 2017-12-03 08:44
I have the same problem.  Windows 10 on a Dell Inspiron 15 7000 Series 2-in-1 Tablet PC.

The issue only began after the most recent Windows 10 update (applied 12/02/2017).  Every other application appears unaffected, including EditPlus.  It is surprisingly difficult to double-click at the speed necessary to select a word in Notepad++.  So much so, I will not be using Notepad++ until this issue is resolved.

**Comment by jatlast** [comment] 2017-12-03 08:51
I forgot to mention, the double-click issue appears to be isolated to double-tapping the touchpad.  That is, using the actual touchpad buttons works correctly.  Unfortunately, this also expects a change in the way I interact with my computer I am unwilling to make.  Hence, Notepad++ is shelved until this issue is resolved.

**Comment by easypeas** [comment] 2017-12-07 20:39
Same issue here, I'm using a touchpad. @jatlast is correct, it's only affecting double-tapping, not double-clicking. Using an Acer Aspire E5-573, running Windows 10. "HID-compliant touch pad" driver from Microsoft version 10.0.16299.15 (latest). It's a very painful bug, I'm probably going to move to another editor if not fixed soon. Thank you.

**Comment by easypeas** [comment] 2017-12-07 21:31
Link to [Scintilla's bug](https://sourceforge.net/p/scintilla/bugs/1983/) on SourceForge. Please everyone weigh in. @ahmedhamdy90, thank you so much for this bug report.

**Comment by EyesOfAHawk** [comment] 2017-12-19 08:05
my mother fucking brothers
even after downgrading the issue persists
fuck windows updates

**Comment by ahmedhamdy90** [comment] 2017-12-19 11:45
@EyesOfAHawk Frustrating I know :(  I am using Sublime currently instead of Notepad++.
My Notepad++ even is now missing the plugin manager!!!!! I don't know what the hell happened to it!

**Comment by tbrannt** [comment] 2018-01-02 04:52
Experiencing the same on a windows 10 lenovo p51. Really annoying :/

**Comment by Far0n** [comment] 2018-01-23 19:15
fyi: disabling **"tap twice and drag to multi-select"** within Windows 10's touchpad settings resolved the problem for me.

**Comment by xv** [comment] 2018-01-24 04:23
@Far0n I can confirm it did solve it for me as well; however, it is only creating a new problem, as you won't be able to double-tap and drag to select anymore. A feature that is much more necessary than not being able to select a word in Scintilla via double-tap.

Good find nonetheless.

**Comment by EyesOfAHawk** [comment] 2018-01-24 05:35
haha...good find yes. as xv said, its a great feature whose benefits probably outweigh the problem.

**Comment by seanpar** [comment] 2018-01-25 02:55
@Far0n thanks for the solid workaround!  I rely on double tap selection far more than double tap and drag.

**Comment by laazaz** [comment] 2018-01-25 23:06
I have the same problem, tested on different NotePad++ versions with the latest Windows 10 update (01/2018).
I believe this is caused by Windows 10 update, there are also some other mouse problems, I hope they fix it asap.

**Comment by mitkoradev** [comment] 2018-02-05 00:23
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4147

I made a pull request.

I have uploaded custom builds for the ones that trust unknown executable 
Build with visual studio 2017 x64
https://games4friends.net/SciLexer.dll - here is the workaround. It's built without BOOST
https://games4friends.net/notepad_allowunsigned.exe - this is built to allow loading unsigned scintilla dll - it will still complain of the certificate, but let you continue

**Comment by mshajeehm** [comment] 2018-03-05 16:36
same issue here with double tap. Dell Inspiron 7559. Is there anyway to change or downgrade the scintilla driver?

**Comment by mitkoradev** [comment] 2018-03-05 17:03
it will probably be working when notepad gets sinchronized with scintila, the change is merged there.

https://sourceforge.net/p/scintilla/bugs/1983/  and their build of SciTE from 18 feb can double tap fine

**Comment by bradenroper** [comment] 2018-03-27 01:13
Just thought I would mention a "somewhat solution". I experience this issue on my ASUS Zenbook, but this might work for other trackpad users too:

I noticed, like many, that double tapping won't select a word. However, double tapping with each tap being in a different location on the pad, will select a word (for my trackpad, at least).

I'm assuming this is some work-around into tricking the trackpad into double tapping without it recognizing a double tap as a special gesture. It's a strange solution and is difficult to get used to, but it consistently works for me. This also works for triple tapping to select a whole line.

**Comment by ciaoarif** [comment] 2018-04-25 11:42
@bradenroper ... your solution works for a Surface Book too. Cheers! I have now perfected the 2 finger double tap where one finger drops slightly after the other to implement your tip :-)

**Comment by MetaChuh** [comment] 2019-04-16 09:35
not reproducible using a mouse or trackpad without custom enhancement drivers.
please deactivate any mouse or trackpad drivers which can produce this.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-16 09:35 UTC
Labels: not reproducible

**Comment by bWolfie** [comment] 2019-04-16 11:22
yea cause it got fixed AFAIK. been fine for me for maybe a year now?

**Comment by abieePabitwar** [comment] 2019-09-20 04:32
Hello Guys,

I am too facing the same issue, on double click on any word in Notepad++ the whole row was getting selected. I tried to many approaches. But there was no luck.

Then finally i have rebooted my laptop and tried once more, but the issue was no more.  Cheers...

I think it's because of windows problem.

Thanks
