### ISSUE TITLE
Add support for AutoHotkey language

### ISSUE THREAD

**Issue by stevoisiak** [notepad-plus-plus/notepad-plus-plus#3833] opened 2017-10-20 17:29 UTC
I would like to see syntax highlighting support added for [AutoHotkey scripts](https://autohotkey.com). (`.ahk`)

```AutoHotkey
; AutoHotkey: Typing "Hello, World!" in Notepad
^j::
    Run, Notepad.exe
    WinActivate, ahk_class Notepad
    WinWaitActive, ahk_class Notepad
    Send, Hello, World{!}
Return
```

There is a user-created [Syntax-Highlighting and Auto-Complete pack](https://github.com/jNizM/ahk_notepad-plus-plus) from jNizM which works pretty well, but it would be nice to see AutoHotkey support built-in with the default installation.

**Comment by dail8859** [comment] 2017-11-13 20:51
Duplicate of #3133, #1734

**Comment by MetaChuh** [comment] 2019-05-17 20:36
please use one of the existing autohotkey udls.

many thanks and best regards.

**Closed by MetaChuh** 2019-05-17 20:36 UTC
