### ISSUE TITLE
Notepad ++ closes randomly

### ISSUE THREAD

**Issue by margeregan** [notepad-plus-plus/notepad-plus-plus#14661] opened 2024-02-01 18:16 UTC
### Description of the Issue
Notepad ++ closes the program randomly throughout the day. This is happening to several other co-workers as well.

### Steps to Reproduce the Issue

1.  No steps taken or needed
2. 
3. 

### Expected Behavior
The program to stay open until I close it.

### Actual Behavior
Notepad ++ closes the program randomly throughout the day. Will look for Notepad++ program and see that it's closed and have to reopen. This happens several times a day and started within the past 5 days. 

### Debug Information
```
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by alankilborn** [comment] 2024-02-01 18:43
Supply _Debug Information_ or you risk having your issue closed without consideration.

**Comment by margeregan** [comment] 2024-02-01 18:48
I added it to my original case. Here it is again.
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3930
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment] 2024-02-02 13:55
> This is happening to several other co-workers as well.

> OS Name : Windows 10 Enterprise (64-bit)

Given that it seems that you are all on domain computers - maybe a domain GPO setting influencing N++?

Is that a N++ problem only or are there other apps randomly closing as well?
Sometimes that random closing of the apps is caused by the insufficient virtual memory (check Windows paging file setting: Settings > System > About > Advanced System Settings > Advanced tab > Performance - Settings > Advanced > Virtual memory - Change...).

Anyway, I would check the Windows logs for any suspicious stuff (Event Viewer > Windows Logs > Application), e.g. look for any "out of virtual memory" or Notepad++ app-crash events.

**Comment by xomx** [comment] 2024-02-06 13:29
> no issues with insufficient memory, also I was not able to find anything suspicious in event log

When it is not an app crash then something must be actively closing that app.

My 1st guess is an AV, e.g. for the MS Windows Defender check its log:
Windows Settings > Update & Security > Windows Security > Virus & threat protection > Protection history 
Especially look for some specific domain security SW or policy. 

Found one external old [similar report](https://superuser.com/questions/1219403/windows-programs-keep-randomly-closing) also mentioning N++ (together with Atom, Discord, Steam, Slack, SourceTree, and DevStax). What interested me - occurrence of the phenomenon in another text editor - Atom. A coincidence?

I know that there was a serious issue in between the mentioned Slack and N++ (look in the closed N++ issues, but it was reported that the Slack v4.28.171+ should solve that). Do you also have any SW installed from the above mentioned list, especially the Slack? Maybe there is still a problem...

**Comment by martin-hulka** [comment] 2024-02-07 17:03
protection history is empty, I do not have installed any of mentioned apps

**Comment by margeregan** [comment] 2024-02-07 20:39
Hello, we're still having the issue with Notepad++ randomly closing. No other apps are doing this. We've been using it for several years and this just started. Not all people in our organization are having this issue.

**Comment by xomx** [comment] 2024-02-07 23:30
Before I continue further - are you willing to test something more difficult on your computers?

1) Easier part could be to check for a possible N++ error/exception exit code via the [GetExitCodeProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess) WINAPI.
I can write a very simple N++ launcher/watch-dog app which will hold one outstanding N++ process handle while waiting for its termination, so even after that random termination, it will be still able to show us the N++:
  - exit value specified in the possible ExitProcess or TerminateProcess WINAPIs used
  - or usual return value from the N++ WinMain func
  - or exception code for an unhandled exception

2) It will be more difficult to find out which process is behind that random N++ termination (if any). There are so many ways how to do such process termination. You can even send the usual WM_CLOSE Windows message to the app and that app will not even know who sent it such a thing (and unfortunately in such case we will see only the usual ok exit code...). I think we can use for that purpose the event tracing stuff of the [Windows Performance Recorder](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/introduction-to-wpr) - WPR (& Analyzer - WPA). But this will need network installation of the Windows Assessment and Deployment Kit (Windows ADK), is that ok (it is not big in size)?

**Comment by xomx** [comment] 2024-02-08 02:28
Before anything else I found one more easy Windows inherent [way](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit) to try. Please extract two reg-files from the following archive:
[npp-silent-exit-mon-reg.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/14203421/npp-silent-exit-mon-reg.zip)

Import to the Registry the `npp-silent-exit-mon-ON.reg` file (doubleclick on it) and restart Windows for sure.
That file is preconfigured for the notepad++.exe cross-process termination only and for its exceptions logging.
Note1: That monitoring feature does not detect normal process termination that happens when the last thread of the process exits and does not detect process termination that is initiated by kernel-mode code, e.g. by a malicious driver.
Note2: Use the 2nd file `npp-silent-exit-mon-OFF.reg` to revert that Registry settings after.

Then launch single instance of Notepad++ and wait for that random termination to occur.

Then launch the Windows Event Viewer > Windows Logs > Application and look there for the `Process Exit Monitor` source.
Hopefully you will see something like: `The process 'C:\Program Files\Notepad++\notepad++.exe' was terminated by the process 'C:\Windows\System32\Taskmgr.exe' with termination code 1. The creation time for the exiting process was 0x01da5a3474a73c76.`

**Comment by martin-hulka** [comment] 2024-02-08 08:20
The process 'C:\Program Files\Notepad++\notepad++.exe' was terminated by the process 'C:\Windows\System32\taskkill.exe' with termination code 1. The creation time for the exiting process was 0x01da5a65d7d52b48.

**Comment by xomx** [comment] 2024-02-08 11:48
@martin-hulka 
Now the final step - finding who is launching that obtrusive taskkill process.

My 1st guess - a domain GPO set some Task Scheduler task causing this:
- run the Windows Task Scheduler
- click on the top item (Task Scheduler Library)
- check for any task there with the `Ready` or `Running` status having the `taskkill /im notepad++.exe /f` or similar in its `Actions` tab

Alternative - download the Sysinternals [Autoruns](https://learn.microsoft.com/cs-cz/sysinternals/downloads/autoruns) and run the `Autoruns64.exe` (better with admin-rights if you want to also make some changes after). 1st click there on the `Scheduled Tasks` tab only, if that does not help then you can try the other tabs there or simply click to `Everything` and investigate.

**Comment by martin-hulka** [comment] 2024-02-08 16:46
I am afraid it would not be that simple ;/ 
I was not able to identify any task related to notepad++.exe or having taskkill in it. 
It is not possible for me to run terminal in admin mode unfortunately so I tried git-bash
```
PS C:\Users\MartinHulka> schtasks /query /XML | Findstr /I taskill
PS C:\Users\MartinHulka>
PS C:\Users\MartinHulka> schtasks /query /XML | Findstr /I notepad
PS C:\Users\MartinHulka>
```

```
PS C:\Users\MartinHulka\Downloads\Autoruns> ./autorunsc64.exe /accepteula -a * -c -h -s '*' -nobanner |findstr /I notepad
Error loading profile for NT AUTHORITY\LOCAL SERVICEA required privilege is not held by the client.
Error loading profile for NT AUTHORITY\NETWORK SERVICEA required privilege is not held by the client.
Error loading profile for CARTON3\OVSvc-18-9576A required privilege is not held by the client.
Error loading profile for CARTON3\OVSvc3038222794-1668A required privilege is not held by the client.
PS C:\Users\MartinHulka\Downloads\Autoruns> ./autorunsc64.exe /accepteula -a * -c -h -s '*' -nobanner |findstr /I taskkill
Error loading profile for NT AUTHORITY\LOCAL SERVICEA required privilege is not held by the client.
Error loading profile for NT AUTHORITY\NETWORK SERVICEA required privilege is not held by the client.
Error loading profile for CARTON3\OVSvc-18-9576A required privilege is not held by the client.
Error loading profile for CARTON3\OVSvc3038222794-1668A required privilege is not held by the client.
PS C:\Users\MartinHulka\Downloads\Autoruns>
```

```
AzureAD+MartinHulka@carton3:~/Downloads/Autoruns$ ./autorunsc64 /accepteula -a "*" -c -h -s|grep -i notep
AzureAD+MartinHulka@carton3:~/Downloads/Autoruns$ ./autorunsc64 /accepteula -a "*" -c -h -s|grep -i taskkill
AzureAD+MartinHulka@carton3:~/Downloads/Autoruns$
```

**Comment by xomx** [comment] 2024-02-08 18:05
Hmm, it could also be just a side effect of some poorly planned maintaining task by the domain. Something like - when at idle, run some update-tasks, but make sure there are not any apps running that might disrupt it, etc. I do not think that there is somewhere a blacklist with N++ on it because of you have evidently N++ preinstalled on your domain computer...

If only you could have admin-rights for a while, the easiest thing would be to simply temporarily replace that taskkill.exe app file with another one, which would display some modal info-messagebox after launching, and thus effectively block app-exit of the original app/task that initialized that taskkill launching. You could then simply open any more advanced task manager where the parent-child process hierarchy is also displayed and found the source of the problem.

Anyway, since this apparently has nothing to do with N++, let me end it here on my end. If you find the origin of your problem, please let us know here, maybe it could interest not only me.

**Comment by martin-hulka** [comment] 2024-02-09 10:48
Thanks for hints, experiments with creating popup window and sort of breaking taskkill.exe were not that successful. At the end I found the culprit using process explorer from sysinternals. 
There I increased process highlight to 15 mins and waited. Fairly quickly following appeared: 

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/148529831/d1e650b6-204e-4d22-ad38-1214c1c29efa)

So it is quite clear that I need to take this to corporate food chain and find the expert responsible for this crap. 

Thank you for your time.

**Comment by xomx** [comment] 2024-02-09 12:33
Nice. So I assume that some genius uses his own copy of N++ (that n++.exe visible in your pic) to do something and then uses some kind of a generic kill command for any running instance of Notepad++... (maybe by using the N++ app process registered class name "Notepad++" instead of its PID or process name "notepad++.exe")

Now I got an idea to use the [ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) for that logging, where you can add 3 filters for processes creating, starting & exiting: 

![npp-killing-procmon](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/e983a396-0277-46f0-a482-cfd6e53e57be)

**Comment by martin-hulka** [comment] 2024-02-12 07:45
Managed to find the policy responsible for behavior, it was downloading latest version saving it as np++.exe and killing running instance, it seems that problem was with identification of running version. Once I talked to people responsible for policy the problem was gone. Now I passed 4th day without notepad++ getting closed...

**Comment by margeregan** [comment] 2024-02-13 02:59
I noticed better stability last Friday. Thank you so much for all your work on this issue. It is much appreciated!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xomx** [comment] 2024-02-13 09:33
@margeregan 
Ok, so now you should close this issue.
(you will still be able to add new comments here or reopen this issue if necessary and all the participants/subscribers will receive the necessary email notification)

**Comment by PeterPST** [comment] 2024-03-07 08:01
Nope, still crashes:


Crashing (a while ~15 s - 1min) when: 

a) starting after Installer
b) starting from fileassociation
c) a+b and scrolling down whith mousewheel

But:
starting from desktop-icon / link - desktop works  perfectly !
Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    AutoSave (1.6.1)
    BigFiles (0.1.3)
    BracketsCheck (1.2.2)
    ColumnTools (1.4.4.1)
    Comment Wrap (1.0.0.5)
    CSScriptNpp (2.0.2)
    CSVLint (0.4.6.2)
    CustomLineNumbers (1.1.7)
    DiscordRPC (1.5.389.1)
    Explorer (1.9.5)
    HexEditor (0.9.12)
    HTMLTag (1.3.5)
    ImgTag (2.0.1)
    IndentByFold (0.7.3)
    mimeTools (3.1)
    nppAutoDetectIndent (2.3)
    nppConverter (4.6)
    NppEditorConfig (0.4)
    NppExport (0.4)
    NPPJSONViewer (2.0.3)
    PreviewHTML (1.3.2)
    PythonScript (2)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

Anwendung: notepad++.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 00007FF60F09C660
Stapel:
----------
- System 
  - Provider 
   [ Name]  .NET Runtime 
  - EventID 1026 
   [ Qualifiers]  0 
   Version 0 
   Level 2 
   Task 0 
   Opcode 0 
   Keywords 0x80000000000000 
  - TimeCreated 
   [ SystemTime]  2024-03-07T07:41:17.6403845Z 
   EventRecordID 216292 
   Correlation 
  - Execution 
   [ ProcessID]  0 
   [ ThreadID]  0 
    Channel Application 
    Computer XXXX 
    Security 
- EventData 

   Anwendung: notepad++.exe Frameworkversion: v4.0.30319 Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet. Ausnahmeinformationen: Ausnahmecode c0000005, Ausnahmeadresse 00007FF60F09C660 Stapel:

**Comment by PeterPST** [comment] 2024-03-07 08:50
Add: event crashed, when adding a file to the open NP++ by double-click

**Comment by donho** [comment] 2024-03-28 00:25
@xomx 
Thank you for your psychic debugging!

@PeterPST 
Please remove all plugins and try again.
If it doesn't crash anymore - move back plugins one by one for identify the culprit one, then please report here.

@martin-hulka
> Managed to find the policy responsible for behavior, it was downloading latest version saving it as np++.exe and killing running instance, it seems that problem was with identification of running version. Once I talked to people responsible for policy the problem was gone. Now I passed 4th day without notepad++ getting closed.

So if I do understand the problem, it was a bad manipulation of Notepad++ deployment?

It seems the issue has solved, I will close this issue. We can keep talking here anyway.

**Closed by donho** 2024-03-28 00:25 UTC
