### ISSUE TITLE
The show more icon in tool bar is not clearly visible in dark mode

### ISSUE THREAD

**Issue by shockergit** [notepad-plus-plus/notepad-plus-plus#10325] opened 2021-08-04 11:22 UTC
![Screenshot 2021-08-04 164813](https://user-images.githubusercontent.com/63154802/128172569-bd476369-d810-4b7c-90e7-36d11d9d3f36.png)

**Comment by ozone10** [comment] 2021-08-04 11:33
maybe duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10103

**Closed** 2021-08-04 14:19 UTC
