### ISSUE TITLE
Feature Request: Install updates in background like Google Chrome

### ISSUE THREAD

**Issue by davidschwegler** [notepad-plus-plus/notepad-plus-plus#11525] opened 2022-04-12 03:22 UTC
I love that N++ has regular updates, and I want to keep it updated. 

However, the prompt to update is a blocking window when I'm opening the software -- often when I just want to jot something down -- and it's a multi-step process to install it.

Other software, such as browsers like Chrome, install in the background, and simply need to be re-launched to run the latest version. Could N++ do this too?

**Comment by dail8859** [comment] 2022-04-12 17:41
Closing as a duplicate of #8514

**Closed by dail8859** 2022-04-12 17:41 UTC
Labels: duplicate
