### ISSUE TITLE
Support for Ctrl+Backspace in COMBOBOX inputs?

### ISSUE THREAD

**Issue by evelance** [notepad-plus-plus/notepad-plus-plus#8363] opened 2020-06-02 15:44 UTC
### Description of the Issue
It seems there is no support for Ctrl+Backspace (ASCII 0x7F "Delete") in COMBOBOX dialogs such as "Find", "Replace with" etc. Are there plans to implement it? Would a pull request be welcome?

### Steps to Reproduce the Issue
1. Open Find dialog
2. Focus IDFINDWHAT input element
3. Press Ctrl+Backspace

### Expected Behavior
The word before the cursor gets deleted.

### Actual Behavior
A rectangular box is inserted (textual representation of 0x7F)

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Education N (64-bit) 
OS Version : 1909
OS Build : 18363.815
Plugins : none

**Comment by sasumner** [comment] 2020-06-03 18:10
Duplicate of #3809

**Comment by sasumner** [comment] 2020-06-03 20:53
>Would a pull request be welcome?

See the `CONTRIBUTING.md` file in the root folder of the project.

**Comment by evelance** [comment] 2020-06-04 01:53
> Duplicate of #3809
Thanks, I didn't see that one.
This feature would be quite nice, I've stumbled upon the boxes many times.

The messaging is not hard, the main problem is the Unicode handling.. is it possible to include Scintilla/Document.h? It would do the job.

For the implementation in Scintilla see:
https://github.com/mirror/scintilla/blob/a6d738543a0efd2d2ee3e985ab26c83eecbbd1a0/src/Editor.cxx#L3610
https://github.com/mirror/scintilla/blob/80edbd5ad163c72787b92c6cf7bb5ccef751adfd/src/Document.cxx#L1799

**Comment by evelance** [comment] 2020-06-04 08:13
A simple implementation would look like this.

In WM_CREATE, change the window process of the edit field of the combobox:
```
COMBOBOXINFO cbinfo = { sizeof(COMBOBOXINFO) };
if (GetComboBoxInfo(combobox_element, &cbinfo) == 0) {
    MessageBoxW(NULL, L"GetComboBoxInfo failed", L"Error", MB_ICONEXCLAMATION | MB_OK);
} else {
    combobox_edit_proc_old = (WNDPROC)SetWindowLongPtr(cbinfo.hwndItem,
        GWLP_WNDPROC, (LONG_PTR)combobox_edit_proc);
}
```
And the new window process has to handle the 0x7F:
```
LRESULT CALLBACK combobox_edit_proc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
    switch (msg) {
        case WM_CHAR: {
            switch (wParam) {
                case 0x7F: { // Ctrl + backspace: Delete word
                    #define FINDREPLACE_MAXLENGTH 2048
                    WCHAR str[FINDREPLACE_MAXLENGTH];
                    int len = GetWindowTextW(hwnd, str, FINDREPLACE_MAXLENGTH);
                    WORD start, end;
                    SendMessage(hwnd, EM_GETSEL, (WPARAM)&start, (LPARAM)&end);
                    WORD pos = start;
                    while (pos > 0) {
                        WCHAR c = str[pos - 1];
                        if (c != L' ' && c != L'\t')
                            break;
                        --pos;
                    }
                    while (pos > 0) {
                        WCHAR c = str[pos - 1];
                        if (c == L' ' || c == L'\t')
                            break;
                        --pos;
                    }
                    if (pos < start) {
                        memmove(str + pos, str + start, len - pos);
                        str[len - (start - pos)] = L'\0';
                        SetWindowTextW(hwnd, str);
                        SendMessage(hwnd, EM_SETSEL, (WPARAM) 0, (LPARAM)-1);
                        SendMessage(hwnd, EM_SETSEL, (WPARAM)pos, (LPARAM)pos);
                    }
                    return 0;
                }
            }
        }
    }
    return CallWindowProc(combobox_edit_proc_old, hwnd, msg, wParam, lParam);
}
```

**Comment by evelance** [comment] 2020-06-04 08:29
Here is a smal demo program:
https://github.com/evelance/win32_combobox_del

**Comment by evelance** [comment] 2020-06-06 04:19
I found a even simpler solution that works quite well.
It is already merged into my clone of Notepad++:
https://github.com/evelance/notepad-plus-plus/commit/157c938338e0c32ab997f3d0226b2e08a39c9d86
Although it doesn't check for Unicode character classes to determine the word start like Scintilla, it is enough for this case IMO.

**Comment by sasumner** [comment] 2020-06-06 10:53
> Here is a small demo program:
> https://github.com/evelance/win32_combobox_del

Wow. 
You don't see too many plain-Jane Charles-Petzold-type Win32 complete programs anymore.
I like it.

**Closed** 2020-06-16 01:06 UTC
