### ISSUE TITLE
File doesn't save as extension type

### ISSUE THREAD

**Issue by EatDesk** [notepad-plus-plus/notepad-plus-plus#9510] opened 2021-02-15 05:03 UTC
### Description of the Issue
In Notepad++ 7.9.2 I can do "Save as", file name: "lol" and "Save as type": "Normal text file (*.txt)" and the output file will be "lol.txt". Choosing the same options in 7.9.3 and the output file is named "lol" with no extension.

I don't have the option "Set Save dialog file extension filter to \*.\*" checked.

### Steps to Reproduce the Issue

Steps are above

### Expected Behavior
Above

### Actual Behavior
Above

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment] 2021-02-15 08:32
What do you use to confirm the save dialog? Do you press he Save button or hit the Enter key?
Are you able to reproduce it always or occasionally?
It could be nice to record a video if possible.

**Comment by EatDesk** [comment] 2021-02-15 09:02
Clicking the save button or pressing the enter key produces the same result and it happens 100% of the time. If I roll back to 7.9.2 it's fixed immediately.

Is a video necessary? It's fairly straightforward in explanation I think.

**Comment by Uhf7** [comment] 2021-02-15 09:16
There are at least four ways to leave the Save As menu with saving the file:
- Press return only: .txt is appended
- Click Save button: .txt is appended
- Press Alt-S: .txt is not append
- Press Tab until the Save button has the input focus, then press return: .txt is not appended.

**Comment by mere-human** [comment] 2021-02-15 10:19
> 
> Is a video necessary? It's fairly straightforward in explanation I think.

Probably, yes.
Because I see the problem only when I press Alt-S or select the Save button with the Tab key as @Uhf7 said.

**Comment by EatDesk** [comment] 2021-02-15 10:36
> > Is a video necessary? It's fairly straightforward in explanation I think.
> 
> Probably, yes.
> Because I see the problem only when I press Alt-S or select the Save button with the Tab key as @Uhf7 said.

Perhaps it's OS dependent? Note that I'm using Windows 7. A video won't tell you anything more than what I've explained but I'll try and add something later.

I've been using notepad++ for years and this is exclusive to 7.9.3

**Comment by mere-human** [comment] 2021-02-15 10:46
> Perhaps it's OS dependent? Note that I'm using Windows 7.

You're right. I can reproduce it on Windows 7 VM. Either pressing a button or the Enter key.
On Windows 10 the behavior is as I posted before.

**Comment by sasumner** [comment] 2021-02-15 17:41
>Press return only: .txt is appended
Click Save button: .txt is appended
Press Alt-S: .txt is not append
Press tab until the Save button has the input focus, then press return: .txt is not appended.

On the upside, if nothing is changed in the code for this, users have 2 ways to get either functionality (they should pick the one they want and use it).  :-)

**Comment by mere-human** [comment] 2021-02-15 18:47
@sasumner Could you, please, assign it on me? I want to fix it.

**Comment by donho** [comment] 2021-02-16 02:24
@mere-human 
Windows 7 is not supported OS by Notepad++, but if the fix is not complex, go ahead please.

**Comment by EatDesk** [comment] 2021-02-16 07:57
> 
> 
> @mere-human
> Windows 7 is not supported OS by Notepad++, but if the fix is not complex, go ahead please.

I didn't know that, that's really disappointing considering it's still much more popular than Windows 8 and still very widely in use. Should I no longer report any bugs on Windows 7 in that case?

**Comment by mere-human** [comment] 2021-02-16 08:54
Notepad++ now has a document with a list of supported OS: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md

Probably, the Windows 7 bugs can still be reported but the chances they will be fixed are lower.

**Comment by sasumner** [comment] 2021-02-16 12:31
I was under the impression that @Uhf7 's 4 bullet points above applied to both Win 7 and Win 10 (although that was never said).

Trying it now, under Win 10, I find...consistency :

* Press return only: **.txt is appended** on Win 10
* Click Save button: **.txt is appended** on Win 10
* Press Alt-S: **.txt is appended** on Win 10
* Press tab until the Save button has the input focus, then press return: **.txt is appended** on Win 10

@EatDesk Which of the 4 methods above (or some other way?) were you using when you opened this issue (on Win 7)?

**Comment by Uhf7** [comment] 2021-02-16 14:16
I tested

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Tools\Npp\Npp_793_64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

On my system the last two bullet points don't work. It's the same for the 32 bit version:

Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Tools\Npp\Npp_793\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

I did not test Windows 7.

**Comment by sasumner** [comment] 2021-02-16 15:01
Sorry, I'm a spreader of bad information.  I see the same result as Uhf7 's earlier table.  I'll edit out my misinformation above.

**Comment by sasumner** [comment] 2021-02-16 15:07
@donho said:

>Windows 7 is not supported OS by Notepad++, but if the fix is not complex, go ahead please.

The issue-creator reported the problem under Windows 7.
But @Uhf7 has shown problems exists under Windows 10.
So @mere-human should most-definitely proceed!  :-)

**Comment by EatDesk** [comment] 2021-02-16 18:21
> Notepad++ now has a document with a list of supported OS: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/SUPPORTED_SYSTEM.md
> 
> Probably, the Windows 7 bugs can still be reported but the chances they will be fixed are lower.

Thanks. I don't think I worded my question very well however, I should have said "should a user report bugs if they are using an unsupported operating system?"

From what I can gather it's ok to report bugs but if it turns out that the bug is exclusive to an unsupported OS then it will be down to the developer's discretion whether to fix the issue or not?

I see in this case the bug is present on Windows 10 anyway, although manifests itself only partly compared to Windows 7.

**Comment by sasumner** [comment] 2021-02-16 18:48
>From what I can gather it's ok to report bugs but if it turns out that the bug is exclusive to an unsupported OS then it will be down to the developer's discretion whether to fix the issue or not?

In my opinion this is accurate.

**Comment by Uhf7** [comment] 2021-02-16 19:59
What I wonder is (although it may not be the accurate place here to discuss it, and although I didn't watch the discussion carefully enough when the decision was made): Why do we jump from Windows XP  to Windows 8. Windows 8 was an intermediate step to Windows 10, which was as popular as Windows Vista, no one loved it. So, in my opinion, there should be supported 
- Windows 10 only 
or 
- Windows 7 and Windows 10.
Windows 8 makes no sense for me. It may be even more difficult to support, because only few users use it, there is no big pool of systems for testing available.

**Comment by mere-human** [comment] 2021-02-16 21:10
> What I wonder is (although it may not be the accurate place here to discuss it, and although I didn't watch the discussion carefully enough when the decision was made): Why do we jump from Windows XP to Windows 8. Windows 8 was an 

I guess because it is not officially supported by Microsoft:
```
Mainstream support ended on January 13, 2015.
Extended support ended on January 14, 2020.
```
https://en.wikipedia.org/wiki/Windows_7

Though, I think the most critical bugs in Notepad++ on Windows 7 should be fixed nonetheless. 
Because this OS is still widely used.
Of course, if that does no harm to Windows 10 support and doesn't make the code much worse.

**Comment by Uhf7** [comment] 2021-02-16 21:32
> Though, I think the most critical bugs in Notepad++ on Windows 7 should be fixed nonetheless.
Because this OS is still widely used.

We should be more driven here by user-friendliness than by non-liability like Microsoft seems to prefer. Although we cannot solve all problems which may occur with Windows 7. But I strongly support to keep compatibility as long as it is possible, at least as long as I own some Windows 7 systems too :-).

**Comment by sasumner** [comment] 2021-02-16 22:20
Keeping older OS is a great thing to do, as long as it doesn't hold the product itself back too much and for too long.  Case in point was the open/save/browse dialogs improvement that @mere-human made.

**Comment by Uhf7** [comment] 2021-02-16 22:53
@sasumner,
this is correct for abandoning XP, but in the moment, Windows 7 does not too much prevent the further development of Notepad++.

**Comment by sasumner** [comment] 2021-02-17 00:00
@Uhf7 Agree.  I think @donho's stance is that it is not too burdensome to keep fixing things relating to Windows 7 specific aspects, they'll be worked on.

**Comment by EatDesk** [comment] 2021-02-17 02:03
> 
> I didn't know that, that's really disappointing considering it's much more popular than Windows 8 and still very widely in use. It's also still supported by Microsoft's extended support updates until 2023.
> 

Since Microsft's Windows 7 extended support was mentioned I just want to correct what I wrote earlier (quoted above), I was actually talking about "Extended security updates" rather than extended support: https://docs.microsoft.com/en-us/troubleshoot/windows-client/windows-7-eos-faq/windows-7-extended-security-updates-faq

- Windows 7 Extended Security Updates 2021: January 13, 2021 - January 11, 2022

- Windows 7 Extended Security Updates 2022: January 12, 2022 - January 10, 2023


So even Microsoft still supports Win7 in some respect. Anyway thank you to all for the answers and some clarity.

**Comment by donho** [comment] 2021-02-19 03:42
> I think @donho's stance is that it is not too burdensome to keep fixing things relating to Windows 7 specific aspects, they'll be worked on.

I confirm. Generally there'll be no impact for the support on Windows 7, since Win32 API is trough all Windows systems. However, there are some rare situations that Windows 7 has the different behaviour from Windows 10 and it's hard to fix such bugs (2 OS have the different runtime systems). In this case, such issue will be ignored. But once again, such situation is rare, and I'm aware of a large amount of users are still under Windows 7.

**Closed** 2021-02-22 03:01 UTC
Labels: accepted
