### ISSUE TITLE
New saved or unsaved lines hilighting prints with a text background despite print settings

### ISSUE THREAD

**Issue by sbrackeen** [notepad-plus-plus/notepad-plus-plus#12349] opened 2022-10-17 19:29 UTC
### Description of the Issue
When NPP is highlighting saved or unsaved text lines, if a document is sent to the printer it will highlight in color on the printout regardless of the "No background color" or "black on white" background settings in Print Settings

### Steps to Reproduce the Issue

1. Have saved/unsaved line highlighting enabled [I actually don't know how to turn this off and I haven't been able to find how]
2. Type text and either leave it saved or unsaved
3. Print the document

### Expected Behavior
With the "no background color" or "black on white" Print setting, text should be printed with no background color.

### Actual Behavior
Text is sent to the printer with a orange background or a green background whether the text is saved or not saved, respectively.

### Debug Information

Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.674
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
[test2.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9803883/test2.pdf)
[test.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9803884/test.pdf)

Attached is 2 "print to pdf" documents that show that the background color has been forced.

**Comment by rddim** [comment] 2022-10-18 16:28
Already fixed in `Fix extra background colors on printing due to Change History` · notepad-plus-plus/notepad-plus-plus@9bec8f5

**Comment by pat-coyne** [comment] 2022-10-19 20:27
I had the same issue occur when I edited a text file, saved, then reload from the file tab.
Print came out with green background.
[files.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9824007/files.pdf)

**Comment by alankilborn** [comment] 2022-10-19 20:50
> I had the same issue occur

It is a known issue and the fix will be in the next release of Notepad++ after 8.4.6.

**Comment by pat-coyne** [comment] 2022-10-20 03:13
Thanks, I read more online and saw it was resolved. Looks like you’re very actively engaged. 
Much appreciated that you informed  me; I use the product daily at work as a civil engineering technician/designer. I’ve found many useful applications for it. I rarely use it for coding, if you can believe it!
Yes, I agree that you ought to get new enhancements in the user’s mind immediately. Never checked the product for a help/about for ‘what’s new’ but I do upgrades and review the listings that open automatically. 
Again, thanks for reaching out!
Pat Coyne
Fort Worth, TX

**Comment by DarthBOR** [comment] 2022-10-26 13:36
Got this [123.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9869955/123.pdf) with WYSIWYG print setting. Was expecting absence of highlighting. Been printing it directly to the monochromatic laser printer from TXT. Looks pretty shitty.

**Comment by ArkadiuszMichalski** [comment] 2022-10-28 10:33
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12281.

**Closed by ArkadiuszMichalski** 2022-10-28 10:33 UTC
