### ISSUE TITLE
Reload question should not be modal

### ISSUE THREAD

**Issue by rillig** [notepad-plus-plus/notepad-plus-plus#2431] opened 2016-10-16 22:08 UTC
### Description of the Issue

When I have a file opened in Notepad++ and the file changes in the background, notepad opens the Reload dialog, asking whether to reload the file.

In situations where I am about to close that editor tab anyway, this question is distracting. Instead of a modal dialog, this should rather be a small, non-modal notification inside each opened tab. Or the dialog should only prevent editing that one tab, but not closing it.

When I have multiple tabs with files that all have changed, I have to answer the question for each of the changed files before I can do anything else with Notepad++. This could be prevented by a [Yes to all] button.
### Steps to Reproduce the Issue
1. Open a file in Notepad++
2. Change the file outside of Notepad++, thereby switching the keyboard focus away from Notepad++
3. Focus Notepad++ again. The Reload question opens
4. Try to close the currently opened file or close the whole Notepad++ window.
### Expected Behavior

In step 4 above, closing the editor tab or the whole window should be possible.

**Comment by 42degrees** [comment] 2018-10-12 20:05
This is a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)

**Comment by donho** [comment] 2019-03-17 15:11
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ba60fbdd715d647aa5ce7be5b6b75182b4a52951

**Closed by donho** 2019-03-17 15:11 UTC
