### ISSUE TITLE
Function List doesn't show all functions when /* */ characters are used

### ISSUE THREAD

**Issue by Entretoize** [notepad-plus-plus/notepad-plus-plus#8910] opened 2020-09-27 08:04 UTC
There's many things that breaks the function list and the issue is still there, half of my class files doesn't show a complete function list or even a list at all.
Here an example:

```
<?php


class PARTENAIRE extends HEADLESS
{
	public function __construct()
	{
		curl_setopt($this->cs, CURLOPT_HTTPHEADER,array('Accept: */*; q=0.8');
	}


	function TraitementRDV()
	{
		if ($r && $r['timestamp']>$datestartlimit)		/*comment*/
		{

		}
	}
	
}

?>
```

_Originally posted by @Entretoize in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5110#issuecomment-699598806_

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 08:56
Duplicate of  https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4606 (and others).

**Closed** 2022-01-14 13:47 UTC
