### ISSUE TITLE
Drag to Reorder Within Document List

### ISSUE THREAD

**Issue by kaihangaverdener** [notepad-plus-plus/notepad-plus-plus#11906] opened 2022-07-12 09:01 UTC
Feature Request.

When I have many documents open in Notepad++ I use the Documents List feature to view them.

Reordering documents requires dragging document tabs horizontally which causes the Documents List to scroll to the top each time.

I think it would be easier to be able to reorder documents by dragging them up and down the Document List.

Many thanks.

**Comment by ArkadiuszMichalski** [comment] 2022-07-12 09:55
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7690.

**Closed by ArkadiuszMichalski** 2022-07-12 09:55 UTC

**Comment by kaihangaverdener** [comment] 2022-07-12 10:08
Thanks for pointing me at the open feature request. I searched for "Document List" before posting this as that's what the feature is referred to in Notepad++, not realising people were referring to it as "Doc Switcher".

Is it likely to be implemented any time soon do you know? It's been open 2.5 years now.
