### ISSUE TITLE
Program logic: "In selection" disabled in replace dialog

### ISSUE THREAD

**Issue by dodmi** [notepad-plus-plus/notepad-plus-plus#9656] opened 2021-03-14 17:08 UTC
### Description of the Issue
In some circumstances, the checkbox to do a search operation in the selected text is disabled, while it should be enabled

### Steps to Reproduce the Issue
1. Open Notepad, enter some lines of text, be sure nothing is selected
2. Click Search -> Replace...
3. As expected "In selection" is disabled; 
4. Do a replace operation and close the dialog
5. Now select some text
6. Click Search -> Replace...
7. "In selection" is still disabled, while it should be enabled
8. Switch to search tab and back to fix this
9. Do a replace operation and close the dialog
10. Click into the editor window, to remove the selection
11. Click Search -> Replace...
12. "In selection" is still enabled, while it should be disabled

### Expected Behavior
The "in selection check box" should be enabled if and only if text in the editor window is selected

### Actual Behavior
The state of the "in slection check box" is not synchronous to the text selection state (but will be synchronized on switching to the search tab)

### Debug Information
Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : C:\Program Files (x86)\Office\Notepad++\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 (64-bit) 
OS Version : 2009
OS Build : 19042.867
Current ANSI codepage : 1252
Plugins : none

**Comment by sasumner** [comment] 2021-03-14 18:28
Closing as duplicate of #9611 
Please search for existing issues before creating new ones, to keep the clutter minimized -- thanks.

**Closed by sasumner** 2021-03-14 18:28 UTC
