### ISSUE TITLE
Dark Mode Printing

### ISSUE THREAD

**Issue by true911m** [notepad-plus-plus/notepad-plus-plus#14113] opened 2023-09-07 16:34 UTC
Printing in Dark Mode

### Description of the Issue
When I have dark mode selected on the screen and print my file, it prints in dark mode, which I don't think was the intent.  It uses a ton of ink to cover the entire background of the page to show printed items with white lettering.

### Steps to Reproduce the Issue
1.  Turn on Dark Mode.
2.  Print your file.
3. 

### Expected Behavior
The text would appear normally (for a printer), with printed dark letters on a plain white background.

### Actual Behavior
As mentioned, it covered the background in ink in order to produce white letters on a black background.

### Debug Information

Notepad++ v8.5.3   (64-bit)
Build time : May 15 2023 - 06:09:36
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\Documents\Grocery Lists\!grocs_shortlist.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3324
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppLauncherPlugin ()

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/54151093/322ddada-a71e-4974-9659-cc14d57132ae)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/54151093/99d22e68-85f2-46bd-9f62-3862e9107680)

**Comment by rdipardo** [comment] 2023-09-07 19:37
Try selecting the option shown below.

<img width="375" alt="print colour mode=2" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/ad196fb6-aa77-4f1c-b8d9-a85fd86d2f8a">

---
P.S.

If this is __*not*__ already the application's default printing mode, consider opening a feature request asking to make it so.

**Comment by true911m** [comment] 2023-09-07 20:17
Okay, I set my screen to Dark Mode, then I went to the Print menu.  The
default was WYSIWYG.  I changed it to black on white.

That works for me and hopefully is useful feedback for you.  Thanks for a
great program!

**Comment by CennoxX** [comment] 2023-09-08 07:16
Duplicate of #13489

**Closed** 2023-09-08 17:34 UTC
