### ISSUE TITLE
Additional empty windows each time when i open Notepad++

### ISSUE THREAD

**Issue by kkrysztofczyk** [notepad-plus-plus/notepad-plus-plus#10747] opened 2021-11-04 15:24 UTC
### Description of the Issue
I have always two additional blank windows as it is on prnscr. that happens all time!

### Steps to Reproduce the Issue

1.  Hard to say, that happens all time when I open Notepad ++
2.  I tried everything including uninstall and installing the app again

### Expected Behavior
one window or more windows but with real files

### Actual Behavior
always i get some extra blank windows on top and on bottom

### Debug Information
Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![Blank Windows](https://user-images.githubusercontent.com/10938076/140350186-2db38a8e-f185-4981-be4a-57fbb1732417.png)

**Comment by kkrysztofczyk** [comment] 2021-11-04 15:26
that is the same as: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9760

**Comment by kkrysztofczyk** [comment] 2021-11-04 15:27
looks as the same problem: https://community.notepad-plus-plus.org/topic/21024/interface-display-boxes-that-i-cant-remove/3

**Comment by ArkadiuszMichalski** [comment] 2021-11-04 16:05
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed by ArkadiuszMichalski** 2021-11-04 16:05 UTC
