### ISSUE TITLE
Few CMake keywords aren't highlighted

### ISSUE THREAD

**Issue by ongamex** [notepad-plus-plus/notepad-plus-plus#1326] opened 2016-01-05 22:22 UTC
Those CMake keywords aren't highlighted by Notepad++: 
INTERNAL BOOL FILEPATH 

https://cmake.org/cmake/help/v3.0/command/set.html

**Comment by Croydon** [comment] 2016-01-06 02:35
Duplicate of #732.
Use the search.

**Comment by dail8859** [comment] 2016-06-23 01:26
Duplicate.

**Closed by dail8859** 2016-06-23 01:26 UTC
Labels: duplicate
