### ISSUE TITLE
Input characters might missing when encoding is ANSI

### ISSUE THREAD

**Issue by ahdung** [notepad-plus-plus/notepad-plus-plus#5822] opened 2019-06-24 01:22 UTC
### Steps to Reproduce the Issue
1. make sure current encoding is ANSI
2. type 立马

### Expected Behavior
get 立马

### Actual Behavior
only 立

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Users\Administrator\Desktop\npp.7.7.1.bin\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by donho** [comment] 2019-06-24 08:28
Could you test with Notepad++ v7.7 to see if the same bug is reproduced?

**Comment by zufuliu** [comment] 2019-06-24 10:10
@donho this was fixed in Scintilla 4.1.5, you need update Scintilla to 4.1.5 or later.

https://sourceforge.net/p/scintilla/bugs/2093/
https://www.scintilla.org/ScintillaHistory.html

**Comment by zufuliu** [comment] 2019-06-24 10:48
Simply fix without upgrade Scintilla is copy Editor::AddCharUTF() (the block above NotifyChar) from latest Scintilla release.

Related commits for this bug (other commits on [#2093](https://sourceforge.net/p/scintilla/bugs/2093/) is not critical for this bug):
https://sourceforge.net/p/scintilla/code/ci/a7d3bc738c23d87e109c88a049c3a2b0ddad8da0/
https://sourceforge.net/p/scintilla/code/ci/1dcd0ca936187fa6564f2d24df99765c7e9092fc/

**Comment by ahdung** [comment] 2019-06-25 06:36
@donho v7.7 occur too.
@zufuliu Thank you, but I don't know what is Scintilla, a npp plugin? what should I do?

**Comment by andrecool-68** [comment] 2019-06-26 08:46
@ahdung This is the library that the notepad ++ works with. (This file is SciLexer.dll)

**Comment by ahdung** [comment] 2019-06-26 09:31
@andrecool-68 So I just need wait for v7.7.2 ?

**Comment by zufuliu** [comment] 2019-06-26 09:54
Since no one seems working on the copy and paste, I made PR #5834 for this,

**Comment by ahdung** [comment] 2019-06-26 09:59
@zufuliu Thank you.

**Comment by donho** [comment] 2019-07-22 07:48
@ahdung  @zufuliu  I just upgraded Scintilla from 414 to 420:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5934

Could you test both 32 and 64 build here:
https://notepad-plus-plus.org/temp/

and confirm me the fix of this bug?
Thank you

**Comment by ahdung** [comment] 2019-07-22 08:26
@donho x64 is ok, but no 32bit zip in your url, I don't want install.

**Comment by zufuliu** [comment] 2019-07-22 10:18
It's OK.
Possible, auto-completion can be updated to use the new `characterSource` field in SCNotification.
Other issues about block caret can be fixed.

**Comment by zufuliu** [comment] 2019-07-22 10:25
@donho Can you help confirming whether https://sourceforge.net/p/scintilla/bugs/2118/ was fixed by Neil's patch? I don't known where to modify Notepad++'s DocumentMap.

**Closed** 2019-07-22 11:10 UTC

**Comment by ahdung** [comment] 2019-09-14 02:50
So you think this is a small problem, is it not worth releasing a new version?

**Comment by donho** [comment] 2019-09-30 14:01
@zufuliu  Sorry, I didn't see your post. What kind of patch should I apply and confirm?

**Comment by zufuliu** [comment] 2019-09-30 15:23
Neil's patch is at https://sourceforge.net/p/scintilla/bugs/2118/#403d
But need extra call `SCI_SETTABMINIMUMWIDTH` somewhere in Notepad++ to set minimum tab width for document map. See my comment at https://sourceforge.net/p/scintilla/bugs/2118/#40d0, hard-coded `tabWidthMinimumPixels` inside `EditView::EditView()` works.

**Comment by zufuliu** [comment] 2019-10-01 00:18
@donho Is the patch works?
