### ISSUE TITLE
Feature request: persistent bookmarks option

### ISSUE THREAD

**Issue by poulet67** [notepad-plus-plus/notepad-plus-plus#10864] opened 2021-11-30 21:09 UTC
Hi, I love NPP but I am currently annoyed with one particular facet of it:

I like to use NPP to write my main code, then I run it and debug it in my development environment. I can't help but sometimes make changes to it in the development environment, but I have become pretty well trained at saving them so I can keep my copy in NPP current. There is one problem however: my bookmarks (the blue circles I can add next to line numbers) disappear when I reload the file into NPP after a save. I understand that on a reload the lines are likely to change and no longer be relevant, but for my particular use case I'd like for them to persist, regardless of what has changed in the file.

It would help me greatly to have an option in the preferences or somewhere that would keep the bookmark in it's raw numerical line value persistent through reloads. I often make small enough changes that even this would at least get me to the right section in my code after which I can reposition them if needed.

Apologies if there is already such a feature, but my cursory google search seemed to indicate that this is not currently possible in NPP.

**Comment by ArkadiuszMichalski** [comment] 2021-12-03 08:49
@poulet67 Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10318. In future use the search option available here (top-left corner)

**Closed by ArkadiuszMichalski** 2021-12-03 08:49 UTC
