### ISSUE TITLE
For Linux Version

### ISSUE THREAD

**Issue by CGTDev53** [notepad-plus-plus/notepad-plus-plus#1364] opened 2016-01-14 04:54 UTC
Notepad-plus-plus is not available for Linux OS.

**Comment by Croydon** [comment] 2016-01-14 14:50
Please use the search.
Duplicate of #108 and #332. Related to #662

**Comment by linquize** [comment] 2016-01-14 14:51
You have to use wine if you need to use notepad++ on Linux.

**Comment by GitMensch** [comment] 2016-02-12 09:09
Please close as duplicate (making it easier to find the "real" one).

**Closed** 2016-06-28 04:51 UTC
Labels: duplicate
