### ISSUE TITLE
functionList.xml for markdown files

### ISSUE THREAD

**Issue by heckl** [notepad-plus-plus/notepad-plus-plus#5945] opened 2019-07-24 07:47 UTC
This is a feature request. It would be useful if the functionList.xml is created for markdown files. If headings is regarded as functions then it would be easy to navigate between them.

I have tried to do something similar before by editing  functionList.xml
https://stackoverflow.com/questions/57072559/how-to-fix-functionlist-xml-is-not-processed-problem   
without success.

**Comment by chcg** [comment] 2019-09-13 17:00
Also created https://github.com/nea/MarkdownViewerPlusPlus/issues/117 and https://github.com/Edditoria/markdown-plus-plus/issues/45

**Comment by MAPJe71** [comment] 2019-09-14 01:07
Uhm...
1. Simular to/Duplicate of #5986
2. Which flavour of Markdown ie. Markdown, CommonMark, GitHub Flavored Markdown (GFM), Markdown Extra or ...?
3. Due to a flaw in the implementation of the Function List engine an id-ext-association has to be combined with an id-userDefinedLangName-association e.g. 
```xml
			<association id=    "markdown_header"        userDefinedLangName="Markdown"           />
			<association id=    "markdown_header"        ext=".md"                                />
```

**Comment by DGrv** [comment] 2020-04-14 11:44
I could make it work for me with helped of post in the [Forum of Notepad++](https://community.notepad-plus-plus.org/topic/18458/display-markdown-outline-view-through-functionlist).

You have to modify your functionList.xml:
- associationMap part
  - it is important that your userDefinedLangName fit to the language used when your open your extension
- parser part
  - I modifiied the main expression in order to have before the # tag possibility to have 1 or several tabs (`|\t{1,5}`), because this is my way to structure my markdown file for lisibility : `"(?x)((?:^|\n|\t{1,5})[#]+\s+(.*?)(\r*|\n*)$)"`

Here what I mean regarding the tabs in my files
![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_2.jpg)
![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_3.jpg)


```xml
<associationMap>
	<association id=    "markdown_header"        userDefinedLangName="Md Drakula"           />
	<association id=    "markdown_header"        ext=".md"                                />
</associationMap>
```

```xml
<parsers>
	<!-- ======================================================== [ Markdown ] -->
	<!-- Based on code modified from https://community.notepad-plus-plus.org/topic/18458/display-markdown-outline-view-through-functionlist/7 -->
	<parser 
		displayName="Md Drakula" 
		id="markdown_header"
		commentExpr="">
		<function
			mainExpr="(?x)((?:^|\n|\t{1,5})[#]+\s+(.*?)(\r*|\n*)$)">
		</function>
	</parser>
</parsers>
```

Here the result:

![Picture2](https://dorian-gravier.com/assets/blog/20200414_functionList_markdown_1.jpg)

If someone knows how to use the `functionName` (example  below) to replace the \t with space in order that the hierarchy is more lisible in the function list it would be great. 

```xml
<functionName>
                        <nameExpr expr="(?:[#]+\s+)(.*)"/>
</functionName>
```

**Closed** 2022-08-25 11:11 UTC
