### ISSUE TITLE
Undesirable behaviour when incorrectly shutting down Windows with unsaved document open

### ISSUE THREAD

**Issue by nubbey** [notepad-plus-plus/notepad-plus-plus#1227] opened 2015-12-05 18:20 UTC
This bug causes severe data corruption when incorrectly shutting down while having a document containing unsaved changes opened.

To reproduce this you have to follow these simple steps:
1. Save a document from N++
2. Make some changes to it but don´t save
3. Force shutdown Windows by long pressing the power button. This bug first appeared when i pressed "Shutdown anyway" because there was just a simple Windows process (i.e. not N++) hindering shutdown.
4. Restart, open the file

The file now contains just a succession of the control character NULL. 
Desired behaviour would be either
a) Discard the changes made after the last save but keep the original file
b) Save a version containing the changes in a different location and offer to restore them

When killing N++ via Task Manager instead of step 3 it correctly keeps the saved version.

It would be great if this could be fixed!
Thanks.

**Comment by dail8859** [comment] 2015-12-05 18:26
Do you have backups enabled?

**Comment by nubbey** [comment] 2015-12-05 21:02
I just had a look at my backups folder under AppData/Roaming/Notepad++/backup and the backup saved there is full of NULLs as well.

**Comment by MetaChuh** [comment] 2019-04-11 00:45
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:45 UTC
