### ISSUE TITLE
7.5.1 Only installs as "Afrikaans"

### ISSUE THREAD

**Issue by rhisgen** [notepad-plus-plus/notepad-plus-plus#3844] opened 2017-10-24 17:11 UTC
### Description of the Issue
Installing ver 7.5.1, 32 or 64 on MS Server 2012 R2 Standard. I get (Dutch) as the language. My servers are set to English. Previous versions all installed as English. 
Attached screenshot is first screen after launching installer.  It does not matter what login is used, or if you choose Install as Administrator.
Last version I have loaded was 7.4.2

### Steps to Reproduce the Issue

1. download 7.5.1 32 or 64bit
2. try to install on MS Server 2012 R2 Standard
3. 

### Expected Behavior
Install in english or prompt for language

### Actual Behavior
starts install in Dutch, 

### Debug Information

![notepad_dutch](https://user-images.githubusercontent.com/33067443/31957341-127abf80-b8b4-11e7-8514-b038ea6053a7.png)

**Comment by nlsdg** [comment] 2017-11-10 02:17
This screenshot isn't Dutch, but Afrikaans, correct?
Is there any language pack or setting related to Dutch or Afrikaans on the server or in the user settings?
I mean is this a random language (it is also alphabetically first!) or there anything on the server/user that could it Dutch/Afrtikaans?

**Comment by rhisgen** [comment] 2017-11-10 02:25
No other languages have been used on the server. It is set to english. Many
previous versions have been installed with no language issue.  Np other
program has the issue.   I only say Dutch .. because thats what google
translate thought it was.

Rich


On Nov 9, 2017 8:17 PM, "Niels de Groot" <notifications@github.com> wrote:

This screenshot isn't Dutch, but Afrikaans, correct?
Is there any language pack or setting related to Dutch or Afrikaans on the
server or in the user settings?
I mean is this a random language (it is also alphabetically first!) or
there anything on the server/user that could it Dutch/Afrtikaans?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3844#issuecomment-343354940>,
or mute the thread

**Comment by rhisgen** [comment] 2018-05-04 19:11
As of 7.5.6  still having install language issues.  Corrected I believe it is Afrikaans,  the language selection screen does not come up.   I cannot use the -L command line switch, because English is not in the list of language codes because it is supposed to be default... it is not.  This is Windows 2012 R2 Datacenter.  All language options on the servers are set to English.  I have not seen this issue on any other installed program.  This seems to have started with the 7.5 versions.   Any Ideas ?

**Comment by rhisgen** [comment] 2018-05-04 19:48
I can install in Afrikkans and then use Settings -> Preferences -> General   and drop back to English. So not the best route... but since no one seems to read these from NotePad++   my only option

**Comment by nlsdg** [comment] 2018-05-05 21:43
I read your comments but I'm not familiar with the code. So I can't help directly. I could only clarify your issue and hope somebody with more knowledge is able to do something about it.

**Comment by SinghRajenM** [comment] 2018-07-21 20:38
Ideally you should get below screen (1) when you double click installer setup.exe

1. ![image](https://user-images.githubusercontent.com/14791461/43039869-f9873286-8d53-11e8-9910-28c248ea7297.png)
2. ![image](https://user-images.githubusercontent.com/14791461/43039873-07fea1c8-8d54-11e8-8182-246f93b200c8.png)
3. ![image](https://user-images.githubusercontent.com/14791461/43039876-10008bfc-8d54-11e8-8d8d-ef2dda9b834a.png)



and the screen shared by you is 3rd step of installer.

**Comment by rhisgen** [comment] 2018-07-23 14:11
Correct .. I never receive the language screen though.
It goes straight to the setup page (in a different language).

I just click through it now .. and change the language after install.

Thank You

**Comment by MetaChuh** [comment] 2019-05-02 14:32
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Comment by MalakymR** [comment] 2023-09-05 11:31
We've hit the same issue in npp.8.5.6.Installer.x64

**Comment by donho** [comment] 2023-09-05 12:05
@MalakymR & @levid0s 
Could you provide your Debug Info via menu `?  > Debug Info...` please?

**Comment by MalakymR** [comment] 2023-09-06 07:51
@donho 

> Notepad++ v8.5.6   (64-bit)
> Build time : Aug 15 2023 - 15:29:28
> Path : C:\Program Files\Notepad++\notepad++.exe
> Command Line : 
> Admin mode : ON
> Local Conf mode : OFF
> Cloud Config : OFF
> OS Name : Windows 10 Pro (64-bit)
> OS Version : 22H2
> OS Build : 19045.3324
> Current ANSI codepage : 1252
> Plugins : 
>     mimeTools (2.9)
>     NppConverter (4.5)
>     NppExport (0.4)

**Comment by donho** [comment] 2023-09-06 13:39
Sorry for the inconvenience. There must be some special/different configuration on your OS (Winows 10 pro and Windows Server 2016). I have no solution yet for the moment. In the mean while, please use workaround solution to remove `%APPDATA%\Notepad++\nativeLang.xml`.

**Comment by xomx** [comment] 2023-09-07 21:57
@MalakymR 

Could you post here a screenshot of your Windows  "Welcome screen and new user accounts settings" and  "Current language for non-Unicode programs"?

(click on the   Settings > Time & Language > Language > Administrative language settings > Copy settings...)

![AdminLangSettings](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/1a680f05-40b0-49cc-b24e-bf9b6be79c26)

@donho 
We could at least improve the state when a user suddenly never receives the installer language selecting screen. If NSIS decides somehow that the computer is only able to display one language (Registry errors, code page issues etc), it will not show that dialog at all. But we can override this with using the [MUI_LANGDLL_ALLLANGUAGES](https://nsis.sourceforge.io/Why_does_the_language_selection_dialog_hide_some_languages).

**Comment by mpheath** [comment] 2023-09-08 06:05
@xomx

> But we can override this with using the [MUI_LANGDLL_ALLLANGUAGES](https://nsis.sourceforge.io/Why_does_the_language_selection_dialog_hide_some_languages).

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5008b8a0cccfff255c5f48b5782ef993b6f9b631/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L20

is already defined.

---

Now, this documentation quote is interesting to the OP... as `Afrikaans` is the first language in the source.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5008b8a0cccfff255c5f48b5782ef993b6f9b631/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L23

though `English` should be the first language at line `23` ?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5008b8a0cccfff255c5f48b5782ef993b6f9b631/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L38

Quote From https://documentation.help/CTRE-NSIS/Section4.10.html#4.10.1

>4.10.1 Language Selection
>
>When the installer starts up it goes through these steps to select the interface language:
>
>    1. Get user's default Windows UI language
>    2. Find a perfect match for the language
>    3. If there is no perfect match, find a primary language match
>    4. If there is no match, use the first language defined in the script (***make sure your first language is a common one like English***)
>    5. If the language variable [$LANGUAGE](https://documentation.help/CTRE-NSIS/Section4.2.html#4.2.3) has changed during .onInit, ***NSIS goes through steps 2 to 4 again***.

I emphasised the important phrases! Step `5` might be causing a re-evaluation to ocurr, leading to no perfect match, so the first language is `Afrikaans` which is set as the install language.

OP stated:

> I get (Dutch) as the language.

https://en.wikipedia.org/wiki/Comparison_of_Afrikaans_and_Dutch

> Afrikaans is a daughter language of Dutch

IMO it is probably `Afrikaans` and was mistaken for `Dutch` .

---

A registry key and value that is not unregistered at uninstall is:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5008b8a0cccfff255c5f48b5782ef993b6f9b631/PowerEditor/installer/nppSetup.nsi#L193

Might be useful for remembering the language to upgrade though uninstall should remove it. Writes under the *WOW6432Node* key in X64.

**Comment by MalakymR** [comment] 2023-09-08 09:16
@xomx 

![Screenshot 2023-09-08 094809](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/7790536/5026686f-a67b-4089-af1c-beca4de17961)

**Comment by xomx** [comment] 2023-09-08 10:29
@mpheath 

> MUI_LANGDLL_ALLLANGUAGES...
> is already defined.

Thanks, I overlooked this.

> though `English` should be the first language at line `23` ?

IMO - this is definitely worth a try - you could try to create such PR and then ask the affected users here for testing ...



> A registry key and value that is not unregistered at uninstall is:
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5008b8a0cccfff255c5f48b5782ef993b6f9b631/PowerEditor/installer/nppSetup.nsi#L193
> Might be useful for remembering the language to upgrade though uninstall should remove it. Writes under the WOW6432Node key in X64.

Yes, I know about that RegKey remnant.
The question is whether we should even be trying to fix accidents like [this](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838).

**Comment by xomx** [comment] 2023-09-08 11:40
@MalakymR 
Thanks for the screenshot, it seems ok.
I asked for that because of I once had a similar Afrikaans-problem. I was doing too many things at once and was inattentive, so I accidentally clicked over the language selection screen during Windows installation, where the Afrikaans is the first item too. I repaired that later but then, when I e.g. created a new user account, it was back.

**Comment by mpheath** [comment] 2023-09-09 12:47
With testing a recompiled installer, I could not get the 1st language defined as English to be default as it kept defaulting to Afrikaans with an unsupported LCID. Seems the NSIS documentation is not reliable. So, I have added a PR to use a switch statement to detect if the LCID is supported by the installer and if not, set English as the value for `$LANGUAGE`.

**Comment by donho** [comment] 2023-09-16 10:59
The installer x86 & x64 which contains the fix of this issue (#14125) are available here:
http://download.notepad-plus-plus.org/repository/MISC/fixInstallLangIssue/

They are the latest version 8.5.7 and binaries are signed.
Please test the installer of your choice, and confirm me if this issue has been fixed.

**Comment by donho** [comment] 2023-09-20 21:20
@rhisgen @levid0s @MalakymR
Could you test the fix mentioned above please?

**Comment by donho** [comment] 2023-09-21 14:33
@MalakymR 
Thank you for testing.
Have you McAfee installed on the PC in question?
As posted here:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838

**Comment by donho** [comment] 2023-09-22 17:36
The problem seems to be caused by McAfee: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838

So the issue is closed.

**Comment by MalakymR** [comment] 2023-09-22 17:39
This isn't the case for us (Mcafee). All we use is defender.

I'll use the other as a reference to look further into this though.

**Comment by donho** [comment] 2023-09-22 17:45
@MalakymR 
Could you provide the value of key HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage please?
Does Notepad++ installer works better after removing this key?

**Comment by MalakymR** [comment] 2023-09-25 10:04
We found it as InstallerLanguage="InstallerLanguage".

Manually set back to 1033, though as soon as the installer is run it skips the language selection and shows Afrikaans... the registry key is changed back to "InstallerLanguage" without proceeding further.

**Comment by xomx** [comment] 2023-09-25 12:26
@MalakymR 
Interesting. So it is really like as in the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838 (except the McAfee AV).

I see a potential problem in the N++ installer code, I will try to test that.

**Comment by MalakymR** [comment] 2023-09-25 13:56
I have checked with processmonitor and the installer reads this key in correctly, then sets it to back to the text string a few steps later.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/7790536/d351d222-c0b6-4cb0-ae08-a8f08914ee35)

**Comment by xomx** [comment] 2023-09-25 14:02
And the preceding (yellow) RegQueryValue shows your previously manually added 1033, right?

**Comment by MalakymR** [comment] 2023-09-25 14:12
Yes sorry, changed to 1033 before running the installer.

**Comment by xomx** [comment] 2023-09-25 16:28
And the last possibility:
[npp.8.5.7.Installer.x64.test-msgboxes-hack-Afrikaans.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12717541/npp.8.5.7.Installer.x64.test-msgboxes-hack-Afrikaans.zip)

**Comment by MalakymR** [comment] 2023-09-26 08:31
Installers in order, reseting key to 1033 each time.

1. npp.8.5.7.Installer.x64.test-msgboxes
1033
1033
InstallerLanguage
(reg = InstallerLanguage)

2. npp.8.5.7.Installer.x64.test-msgboxes-disabled-x64redirector
1033
InstallerLanguage
InstallerLanguage
(reg = 1033)

3. npp.8.5.7.Installer.x64.test-msgboxes-hack-Afrikaans
1033
1033
InstallerLanguage
(reg = InstallerLanguage)

All show Afrikaans in the welcome window.

When running these on a _working_ system, I get 2 msgboxes before I am prompted for the installer language. On the problem system(s) this prompt is missing still.

**Comment by xomx** [comment] 2023-09-26 08:46
Is not that `InstallerLanguage` rather "Installer Language"? (even your ProcMon log shows that)

**Comment by MalakymR** [comment] 2023-09-26 08:48
Sorry just made an assumption when typing, it was "Installer Language" in the registry each time.

**Comment by xomx** [comment] 2023-09-26 08:50
So that is really weird result.
I will continue in this later, but it seems that N++ installer is not responsible for all of this. More later.

**Comment by donho** [comment] 2023-09-26 15:34
@MalakymR 
I have tried to set English as default value while the detection is failed. Could you try the following binaries please?
http://download.notepad-plus-plus.org/repository/MISC/setEnglishAsDefaultLang

**Comment by xomx** [comment] 2023-09-26 15:36
@MalakymR 
Ok, I think I got it. If I am right I will be able to fix all that weird things at once (defaulting to Afrikaans, not showing lang-selector dlg at all, writting that nonsence "Installer Language" etc...).

Could you please test one more installer?

1.test - delete completely the `HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage` RegKey before you start that installer.

2.test - create/update the above RegKey with that invalid value "Installer Language" and then start the installer

[npp.8.5.7.Installer.x64.MsgBoxes_InstallerLanguageFix_MUILangFixRegistryAndAlwaysShow_English1st.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12729350/npp.8.5.7.Installer.x64.MsgBoxes_InstallerLanguageFix_MUILangFixRegistryAndAlwaysShow_English1st.zip)

**Comment by xomx** [comment] 2023-09-26 15:44
@donho 
Your installer works ok, but it did not fix all the problems.
Did you use the "!define MUI_LANGDLL_ALWAYSSHOW"?

**Comment by donho** [comment] 2023-09-26 17:32
@xomx 
> Your installer works ok, 

That's a good news!

> but it did not fix all the problems.

Could you be more precise please?

> Did you use the "!define MUI_LANGDLL_ALWAYSSHOW"?

I just uncommented this line:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L19

and commented the following line;
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L38

**Comment by xomx** [comment] 2023-09-27 00:06
@donho 

These two fixes should be enough (I can do a PR but I rather wait for another test from @MalakymR):

1. nppSetup.nsi
Unfortunately some of the users already have wrong "Installer Language" value in their regkey HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage {which then can also lead to the Afrikaans problem later), so at NSIS .onInit N++ has to either check for that and possibly correct it to our factory default (1033 == English) or delete that regkey completely (simulating a fresh state).

2. langs4Installer.nsh
Moving English at the 1st position (default lang) + using the MUI_LANGDLL_ALWAYSSHOW, i.e.:

```
; Set languages (first is default language)
!define MUI_LANGDLL_ALWAYSSHOW ; do not skip the lang-selection dlg even when something fails
!define MUI_LANGDLL_ALLLANGUAGES
;Languages

  !insertmacro MUI_LANGUAGE "English"
  !insertmacro MUI_LANGUAGE "Afrikaans"
  !insertmacro MUI_LANGUAGE "Albanian"
  ...
```

3. nppSetup.nsi (unsure, I rather wait for another testing)
If the above two patches will not be enough, I will also additionally use the MUI_LANGDLL_REGISTRY_* way described below.
I think that this is not needed, but it has to be confirmed on that user's problematic computers.


There is also a 4th potential fix - disabling the x64 Registry redirection and use the HKLM\SOFTWARE\Notepad++\InstallerLanguage for the x64 N++ installations.
But this is not needed if we consider as ok sharing the same installation language selection between the x86 & x64 N++ installations (which is IMO ok).

@mpheath has already correctly described most of the problems and possible solutions. But his PR is not working because while he fixed the possibly wrong regkey/$LANGUAGE value before invoking that NSIS MUI_LANGDLL_DISPLAY at .onInit, if NSIS own lang-detection method of that MUI_LANGDLL_DISPLAY fails before displaying the lang-selection dlg, NSIS engine reaches rather for the statically predefined first member of the N++ lang-list than for the already correctly preset $LANGUAGE var. And then it updates the $LANGUAGE accordingly (currently either with that Afrikaans or with the complete nonsense value "Installer Language", more description below).

<tl;dr>

All the problems reported:

1. Some users get Afrikaans pre-selected as the default option in their N++ installer lang-selection dlg.
2. One reported similar problem when using automatic clickthrough install method via winget (got the N++ preinstalled with that Afrikaans lang, this is probably only a flavor of the previous No.1).
3. Some do not get that lang-selection dlg at all (they go straight to the installation Welcome Screen instead and with that wrong Afrikaans display-lang).
4. Users having the previous problem No.3 reported weird "Installer Language" value written in their regkey HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage 
5. One got that lang-selection dlg after all, but only when used the x86 N++ installer (and then there is again the wrong Afrikaans pre-selected).
4. Some even got that Afrikaans problem back at the next N++ installation even when they previously manually fixed that installer language to something else.

What is behind it:
- in Windows is used a locale like Icelandic, which has no counterpart in the N++ list of the supported langs for the NSIS installer
- or a possible failure/defect in detection of the current locale in Windows (a Registry corruption etc)
- or maybe a non-standard variant of Windows (server or a somehow customized Windows editions etc)

Current N++ installer:
- at .onInit N++ tries to find a previously used installer language in the regkey HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage
- if that regkey has been found, it then presets the NSIS $LANGUAGE (if not, the unmodified $LANGUAGE at this stage contains the NSIS default)
- then the .onInit continues with the line "!insertmacro MUI_LANGDLL_DISPLAY", which should invoke the NSIS lang-selection dlg
- but when Windows locale is e.g. Icelandic, NSIS cannot get a match inside the N++ lang-list in the langs4Installer.nsh and offers the 1st one in that lang-list instead (which is currently "!insertmacro MUI_LANGUAGE "Afrikaans")
- but if something failed in the NSIS logic for the MUI_LANGDLL_DISPLAY, the lang-selection dlg is then not showed at all and the 1st N++ lang Afrikaans is pre-selected directly and moreover the nonsense "Installer Language" value (evidently a NSIS default value somewhere) is then set to the NSIS $LANGUAGE and therefore that nonsense value is written in the regkey after!

</tl;dr>

**Comment by donho** [comment] 2023-09-28 11:10
@xomx 
Thank you for your explanation.
I let you create a PR for fixing this bug then.

**Comment by xomx** [comment] 2023-09-28 13:32
@MalakymR 
Thanks for all the testing. I am able to simulate e.g. that Icelandic Windows locale in a VM, but not such obvious NSIS lang-selector engine failures.

Good news:
- now we have at least a way how to force the English as the installer default instead of that Afrikaans

Bad news:
- even when the last test-installer uses the NSIS `MUI_LANGDLL_ALWAYSSHOW`, the lang-selection dlg is still not shown at all and that nonsense "Installer Language" value is still generated somehow!

What the test-installer in your last two attempts did:
- the 1st msgbox shows us in both cases the NSIS default for the NSIS `$LANGUAGE` variable at .onInit (which is probably the current Windows locale), so the 1st "1033" is expected on your machine
- 2nd "1033" is shown after we read a possible previous lang-regkey from the previous installation, the possible nonsence "Installer Language" value is corrected before (to our "factory default" == English)
- then there is that missing langs-selection dlg, which looks like as a total NSIS lang-engine selector failure
- then we got the last msgbox with "Installer Language", which looks also as the total NSIS failure because of it evidently uses that nonsense value for overwriting our `$LANGUAGE` variable at the end of the installer .onInit

What to do next:
- before I create at least a partial fix for this in N++ installer (and eventually fill a NSIS-bugreport), I need to be sure that this is not a N++ fault but a NSIS one (and for  a possible future NSIS-bugreport, I will also need a simple POC installer script)
- so the next test-installer is a only slightly modified NSIS example skript "C:\Program Files (x86)\NSIS\Examples\Modern UI\MultiLanguage.nsi":
[MultiLanguage-test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12749789/MultiLanguage-test.zip)
- please repeat the last two tests with it (this time always let the test-installer finish its installation and check for the NSIS default regkey "HKCR\SOFTWARE\Modern UI Test\Installer Language")

**Comment by xomx** [comment] 2023-09-28 23:27
@MalakymR 

I have one more idea after considering this report:

> @levid0s 
> Language selection dropdown is not coming up.
> Edit: The 32-bit installer (`npp.8.5.2.Installer.exe`) does give me the Language selection dropdown with `Afrikaans` selected by default.

So please try also these two test-installers (this time only check the lang-regkey value after the installer Welcome Screen shows up):
1) x86 installer, check the HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage :
[npp.8.5.7.Installer.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_usualX86NSIS.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12754501/npp.8.5.7.Installer.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_usualX86NSIS.zip)
2) native x64 NSIS installer, check the HKLM\SOFTWARE\Notepad++\InstallerLanguage :
[npp.8.5.7.Installer.x64.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_nativeX64NSIS.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12754509/npp.8.5.7.Installer.x64.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_nativeX64NSIS.zip)

Note to the "native x64 NSIS installer":
Nowadays the NSIS installers produced for x64-apps are still the 32-bit x86 binaries. This is because the official NSIS source code can be compiled as the 64-bit as well, but the System plug-in is still not fully functional. But there is an undocumented NSIS switch `Target AMD64-Unicode` and then one also needs 64-bit NSIS stubs and plugins (relevant binaries available e.g. from this fork: https://github.com/negrutiu/nsis/releases )

**Comment by donho** [comment] 2023-10-01 14:12
Any news about it?

**Comment by xomx** [comment] 2023-10-01 18:09
@donho 

If that bump is for me - I am  still waiting for another test by @MalakymR (or anyone else influenced), as I am not able to simulate all these NSIS error conditions myself. There is still a possibility that this is a N++ installer fault (and not a NSIS one).

If I do not get further answers (let's say for more than a week), I will prepare at least a partial fix (the following is valid only for the problematic computers):
- lang-selection installer dlg will be still missing, but now the automatically selected lang will be English and not the Afrikaans
- the above also means that any previously selected correct lang (stored in the N++ regkey) will be overridden to English 
- the possible wrong "Installer Language" value generated by NSIS for the `$LANGUAGE` var will be corrected to English too before writing to the regkey

**Comment by MalakymR** [comment] 2023-10-01 19:18
Should be able to test Monday or Tues.

**Comment by MalakymR** [comment] 2023-10-03 15:21
> @MalakymR
> 

> So please try also these two test-installers (this time only check the lang-regkey value after the installer Welcome Screen shows up):
> 
>     1. x86 installer, check the HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage :
>        [npp.8.5.7.Installer.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_usualX86NSIS.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12754501/npp.8.5.7.Installer.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_usualX86NSIS.zip)

1. Msgbox = 1033, 1033, Installer Language
Welcome = Afrikaans
Reg = Installer Language (in HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage)

>     2. native x64 NSIS installer, check the HKLM\SOFTWARE\Notepad++\InstallerLanguage :
>        [npp.8.5.7.Installer.x64.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_nativeX64NSIS.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12754509/npp.8.5.7.Installer.x64.MsgBoxes_InstLangRegFix_MUILangAlwaysShow_English1st_nativeX64NSIS.zip)

2. Msgbox = 1033, 1033, Installer Language
Welcome = English
Reg = Installer Language (in HKLM\SOFTWARE\Notepad++\InstallerLanguage)

**Comment by xomx** [comment] 2023-10-03 16:25
@MalakymR 
Thank you.
Can I ask also for the modified NSIS-example test [above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3844#issuecomment-1739192867) (in the file MultiLanguage-test.zip there...)?

**Comment by donho** [comment] 2023-10-04 21:28
@xomx 
I just have had the confirmation of fix here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1742135737
What do we need more for a PR for fixing this issue?

**Comment by xomx** [comment] 2023-10-05 10:23
@donho 
Users are experiencing different types of this Afrikaans-problem (note that in your mentioned https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1742135737 user was shown the lang-selection dlg while e.g. to the @MalakymR here was not).

A) Lang-selection dlg is shown but currently with invalid Afrikaans
- this type is better, we can/will fully fix that by that "English-1st-in-our-static-lang-list"
- it is caused either by a specific Windows locale like Icelandic or by a previous invalid N++ lang-regkey value

B) Lang-selection dlg is NOT shown at all, user goes directly to the Welcome Screen installer dlg with invalid Afrikaans pre-selected 
- this one is worse and currently not fully fixable, I can ensure forcing default English instead of that Afrikaans and pre/post-correction of the lang-regkey but nothing more
- with this type any previous correct lang-regkey is ignored totally and overwritten to the nonsense value "Installer Language" during the installation (the $LANGUAGE installer variable is overwritten at runtime automatically by NSIS-engine, then this is consequently also written to the lang-regkey later, even when I patched and forced that English for the Welcome Screen, which IS then in English...)
- this one seems to me as a NSIS fault (I need that one more test by @MalakymR for confirmation and for POC for a future possible NSIS bug-report...)


Anyway, I am going to create a PR for this probably on Saturday (sorry, not much free-time right now).
Is it ok or you need it earlier?

**Comment by donho** [comment] 2023-10-06 20:58
Thank you @xomx 
Just saw your comment and analysis.
I just reviewed your PR and let's talk there (in PR)

**Comment by donho** [comment] 2023-10-08 01:14
@MalakymR 
I have never got your answer for the test result of following binaries:
http://download.notepad-plus-plus.org/repository/MISC/setEnglishAsDefaultLang

 Could you try it and tell me if you have English as Installer language please?
 And especially, could you let me know the language of Notepad++ after installation?

**Closed** 2023-10-10 15:26 UTC

**Comment by MalakymR** [comment] 2024-02-28 09:55
> @MalakymR I have never got your answer for the test result of following binaries: http://download.notepad-plus-plus.org/repository/MISC/setEnglishAsDefaultLang
> 
> Could you try it and tell me if you have English as Installer language please? And especially, could you let me know the language of Notepad++ after installation?

Appologies, this was around the time github forced MFA on everyone and it failed to work and took this long to get the issue resolved. (imo MFA should have only been pushed to bigger/more important projects first).
