### ISSUE TITLE
Notepad++ page scrolls on changing tab

### ISSUE THREAD

**Issue by amsharma9** [notepad-plus-plus/notepad-plus-plus#2651] opened 2016-12-07 06:45 UTC
### Description of the Issue
I was using NPP 6.9.1 which had this issue. I upgraded to 7.2.2 and it still has this issue. This has been mentioned on[ stackoverflow](http://stackoverflow.com/questions/31810872/notepad-page-scroll-on-changing-tab). I have tried the solutions suggested on that and NPP forum but still whenever I change tab and come back to original tab the line number is about 10 lines above where I was. I am usually on the last line and when I change tab and come back I have to scroll down again to reach the last line.

I renamed the "plugins" directory but it hasn't helped. XML Plugin is not installed so  "Set XML type automatically"  (Plugins -> XML Tools -> Set XML type automatically) option is not visible to me.

### Steps to Reproduce the Issue
1. In version 7.2.2 Open two text files in tabs.
2. Go to last line of first tab. Switch to other tab where some other file can be loaded, come back to first tab.
3. You are no longer on the last line.

### Expected Behavior
Should stay on the last line of the first tab.

### Actual Behavior
Scrolled up on the first tab.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : none

**Comment by MetaChuh** [comment] 2019-04-11 23:10
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:10 UTC
