### ISSUE TITLE
Improve Python syntax highlighting

### ISSUE THREAD

**Issue by Vgr255** [notepad-plus-plus/notepad-plus-plus#1291] opened 2015-12-28 00:28 UTC
I have a few ideas to help improve the Python syntax highlighter, so here they are. Give or take as you wish, these are from a long-time user of both Notepad++ and Python (especially both together :)
- I like the new syntax for decorators (lines like `@something_like_this`), however, I think that making those italic hinders readability. I like the colouring of it, although I would make that another colour, possibly red since that's only used for numbers right now (or maybe brown, like C's preprocessor highlights wouldn't be bad either); the orange color is too confusing with the current `"""Triple-quoted strings"""` highlighting.
- Missing syntax highlighting for the `nonlocal` keyword.
- Possibly add a distinction between "Python 2" and "Python 3" - for example, `exec` and `print` are statements in Python 2 (and highlighted as such), while they're functions in Python 3, so they shouldn't be shown as if they were keywords.
- However, I would like to highlight built-in functions and names (such as `list`, `set`, `super` etc.) as well as exceptions (like `TypeError`, `ValueError` or even `RecursionError`, which is new in 3.5). I would make built-in exceptions a non-bold purple (like how C's `static`, `void`, `int` and friends are highlighted). I'm not too attached to built-in functions or exceptions gaining special highlighting (especially because I can't come up with a good colouring, although maybe using the same for everything in the `builtins` module wouldn't be so bad I guess), but thought I'd mention it anyway.
- About the separation between Python 2 and 3, Python 3.5 added "async" and "await" keywords -- they are not full keywords right now, but it is probably too much effort to parse and see whether they are keywords where they're used, so better to treat them as keywords no matter what. This might then ring some people's bells in that they might not want to use those as names.
- Python 3.6 (to be released mid-2016) will add f-strings, constructed like `f"Some stuff here"`, so it would be useful to highlight that `f` prefix before strings, as do with `b`, `u` and `r`. Even if 3.6 is not released yet, it wouldn't hurt to add that.
- Regarding separation between Python 2 and 3, they're syntactically equivalent, except for those three points above. It should be trivial to do at least the separation; just copy one preset to another, name the original "Python 2", the other "Python 3" and perform those changes. All of them (except possibly the "highlight functions" one) sound relatively trivial to me; I'm even ready to take a stab at it, although I couldn't find where this is done in the source code.

Useful piece of code to look at: The [pure Python keyword.py module](https://hg.python.org/cpython/file/3.5/Lib/keyword.py), which is present in any Python release (or source) holds all keywords of the language. However, `async` and `await` are not listed (as they are not yet full keywords).

I'll keep poking around the source and see if I can find a way to make at least some of those changes myself. I'll submit a PR referencing this issue if I do :)

**Comment by MetaChuh** [comment] 2019-04-13 02:04
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:04 UTC
