### ISSUE TITLE
Windows shutdown is prevented by "Reload"

### ISSUE THREAD

**Issue by thendarion** [notepad-plus-plus/notepad-plus-plus#8758] opened 2020-08-24 12:28 UTC
### Description of the Issue
Given there's a file opened in N++ that has been modified elsewhere
When Windows shutdown is initiated
Then shutdown is prevented by "Reload"

### Expected Behavior
Windows shuts down

### Actual Behavior
Windows shutdown hangs

**Comment by BadDaemon** [comment] 2020-08-25 13:37
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8714 ----> reload prevents application close -> application not closing prevents reboot/shutdown

**Comment by sasumner** [comment] 2020-08-25 21:54
Since it is a duplicate, let's close it.

**Closed by sasumner** 2020-08-25 21:54 UTC
