### ISSUE TITLE
Notepad++ is now dependent on the service "Application Information"

### ISSUE THREAD

**Issue by achtchaern** [notepad-plus-plus/notepad-plus-plus#13457] opened 2023-04-01 10:57 UTC
I have a hardened system with lots of services disabled. Since 8.5.1 (I'm using the portable version), NPP won't start unless the service "Application Information" ("AppInfo") is running. Otherwise, the error message "There are no more endpoints available from the endpoint mapper." is shown. 

I have never seen an app with this dependency before. Obviously, you can't support tweaked systems, but I'd like my favourite text editor not to be too much dependent on non-essential services. I like NPP because its small footprint and lack of dependencies, which means you know you can always rely on it, eg. when diagnosing a damaged / partly corrupt Windows machine.

**Comment by Yaron10** [comment] 2023-04-01 13:51
@GurliGebis & @donho,

Thank you for your recent work on the Windows 11 context menu. 👍 

I also consider the dependency on the `AppInfo` service a regression (caused by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce4d374a4782185f2e0dbaa2e6527ba7f8b9ad39). 
I get the following error:

![תמונה](https://user-images.githubusercontent.com/10229320/229292726-31f77a2a-139b-47b0-83fe-7947acb6c9e7.png)

Could you please look into it?

***

Notepad++ v8.5   (64-bit)
Build time : Mar 16 2023 - 18:34:52
Path : ---\Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1.1)
    HTMLTag (1.3.6)
    MenuIcons (2.0.2)
    PythonScript (2)
    _CustomizeToolbar (4.2)

***

@achtchaern,

Could you please post your Debug info?

**Comment by GurliGebis** [comment] 2023-04-01 14:12
@donho can you try and see if the new menu works if the msix tag is removed from the notepad++ manifest file.
I suspect it is causing the dependencies, so if the menu still works with it removed (it should), it should be safe to remove it.
From what I can see, it is the cause of those dependencies 🙂

**Comment by achtchaern** [comment] 2023-04-01 17:07
Debug Info, as requested:

Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : D:\Users\User\Downloads\npp.8.5.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by donho** [comment] 2023-04-01 17:19
@achtchaern 
Could you test the package of choice here:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST13/

We believe it's fixed in above binaries.

**Comment by donho** [comment] 2023-04-01 17:22
@GurliGebis 
> can you try and see if the new menu works if the msix tag is removed from the notepad++ manifest file.

Tested under Windows11 Home with TEST13 - there's no issue from my side.

**Comment by GurliGebis** [comment] 2023-04-01 17:51
@donho I can confirm it works without the MSIX tag on my machine as well.
I have tested with the Application Information service stopped, and it works on my machine.

@achtchaern can you confirm as well, that it is working?

**Closed** 2023-04-01 22:00 UTC

**Comment by achtchaern** [comment] 2023-04-02 08:32
Yes, the TEST13 build works for me as well. Thanks!

**Comment by Yaron10** [comment] 2023-04-02 18:17
@GurliGebis & @donho,

👍 
Great.
Thank you.
