### ISSUE TITLE
Feature request: Search tabs

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#11564] opened 2022-04-22 01:08 UTC
### Description of the feature request

Google chrome and firefox have a feature (for firefox, you have to have tons of tabs open across the screen or use the search bar and at the bottom of the "search suggest query" with one of them shoing the tab icon: ![image](https://user-images.githubusercontent.com/13095760/164576734-53362831-c532-42bd-8eb2-01650689d2f6.png) that lets you type in the search bar to find a tab with the matching header.
![image](https://user-images.githubusercontent.com/13095760/164576895-2891ed89-00a4-4d5d-8f13-f494fd8855f7.png)
)

I was thinking if notepad++ could have this feature, it would be nice.

**Comment by alankilborn** [comment] 2022-04-22 11:13
Have you tried _NavigateTo_ plugin?

**Comment by GhbSmwc** [comment] 2022-04-22 21:08
Have not, and do not see it on the plugins admin.

**Comment by CennoxX** [comment] 2022-04-26 10:09
> Have not, and do not see it on the plugins admin.

@GhbSmwc It should be there, except if you use Notepad++ for arm64. Have you clicked [Next] in plugins admin multiple times to get to the next occurences of your searched phrase (yes, that's not extremely intuitive)? Or scrolled to plugins starting with "N" and is there between the plugins MZC8051 and NewFileBrowser something for you?

**Comment by alankilborn** [comment] 2022-08-09 12:08
NavigateTo plugin performs the desired task admirably; no reason to have a native feature.
Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment] 2022-08-09 13:29
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11290.

**Closed by ArkadiuszMichalski** 2022-08-09 13:29 UTC
