### ISSUE TITLE
Always printing with background color

### ISSUE THREAD

**Issue by giftakis** [notepad-plus-plus/notepad-plus-plus#12373] opened 2022-10-22 00:09 UTC
### Description of the Issue
After upgrading from v8.4.5 to v8.4.6, all printing has an [orange?] background color.
A colour background prints regardless of what the background "colour options" setting is made (in Settings->Preferences->Print).
And it prints regardless of printer (physical printer or PDF).

### Steps to Reproduce the Issue
1.  Open a new document
2.  Type in something
3.  Print the document

### Expected Behavior
By default, no background colour should print.  Further, changing the preferences should adjust how "colours" print; no effect is seen.

### Actual Behavior
An [orange] background colour prints.

### Debug Information
Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.24)
    HTMLTag_unicode (1.3.5)
    IndentByFold (0.7.3)
    JSMinNPP (1.2205)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppJavaPlugin (0.4)
    NPPJSONViewer (1.41)
    NppXmlTreeviewPlugin (2)
    PyNPP (1.2)
    Python Indent (1.0.0.4)
    PythonScript (2)
    XMLTools (3.1.1.13)

**Comment by giftakis** [comment] 2022-10-22 00:12
After doing a deeper dive in the current issues, I see similar entries with slightly different wording.
As the author of this entry, I am closing to avoid confusions.

**Comment by ArkadiuszMichalski** [comment] 2022-10-22 22:05
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12281.

**Closed by ArkadiuszMichalski** 2022-10-22 22:05 UTC

**Comment by alankilborn** [comment] 2023-01-04 16:07
> Goto Preferences
> Margins/Boarder/Edge
> Uncheck Display Change History

Or simply use a newer version of Notepad++ than 8.4.6.

**Comment by rogerywoo** [comment] 2023-01-06 13:06
> > Goto Preferences
> > Margins/Boarder/Edge
> > Uncheck Display Change History
> 
> Or simply use a newer version of Notepad++ than 8.4.6.

That works.  Thank you
