### ISSUE TITLE
Feature request: navigate back and forwards without plugin

### ISSUE THREAD

**Issue by eepty** [notepad-plus-plus/notepad-plus-plus#1740] opened 2016-04-12 05:36 UTC
It helps a lot when we use notedpad++ as a viewer.

**Comment by igorm6387** [comment] 2016-04-13 06:45
Duplicate of #1733

**Comment by MetaChuh** [comment] 2019-05-01 22:37
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:37 UTC

**Comment by sasumner** [comment] 2019-05-02 12:18
Still not a native option in N++ 7.6.6, but LocationNavigate plugin is still a working option for 32-bit N++ users.
