### ISSUE TITLE
Functions starting with "for..." are not visisble in the functions list [PHP]

### ISSUE THREAD

**Issue by edgarolijar** [notepad-plus-plus/notepad-plus-plus#8664] opened 2020-08-05 13:10 UTC
### Description of the Issue
Functions starting with "for..." are not visisble in the functions list or only part of the function name is visible (language: PHP).

Notepad++ v7.8.7, 64-bit, Windows 10 Pro

![notepad++_bug01](https://user-images.githubusercontent.com/8299844/89416542-b34eaf80-d72d-11ea-8595-ccf2260e529b.png)

![notepad++_bug02](https://user-images.githubusercontent.com/8299844/89416585-c6617f80-d72d-11ea-8057-b9a57691f207.png)

**Comment by sasumner** [comment] 2020-08-05 13:16
Closing as a duplicate of #4627 .
Please search the open issues list before creating a new issue.
When you find an existing issue that is similar to the one you are inclined to create, just add any new information you have to the existing issue.

**Closed by sasumner** 2020-08-05 13:16 UTC
