### ISSUE TITLE
NP++ reverts file to old (pre-session) version of file instead of reloading current from disk.

### ISSUE THREAD

**Issue by interstellarjam** [notepad-plus-plus/notepad-plus-plus#3626] opened 2017-08-18 06:28 UTC
I have no idea how, but despite having two current *saved* versions of a file I am editing open in Notepad++, somehow, I have ended up with an old version on disk and two tabs with the old version open in Notepad++, and no backups.

This is probably a user issue somehow, but I feel like the flow leading to this was very confusing, and I'm reporting this so hopefully things can be improved. This is my first time losing work with Notepad++ in years.

### Steps to Reproduce the Issue
Mostly I am just left sitting here thinking 'sorry, how did that just happen?'

Here are some things that I did.
1. Edit a file in a single Notepad++ instance, and save the file when finished editing.
2. Rename project root folder above the folder the file is in.

Usually, I make sure to just close the document before doing this since I hate all the popups this triggers. This time I didn't.

3. In Explorer, open the file I was editing again, so I have a second tab in Notepad++
Now I am a little fuzzy on what happened next. Bear with me.

4. When Notepad++ opens (single same instance) I get a popup about the other tab, or I switch to that tab and get the popup. 'File no longer exists, do I want to keep this open?'
5. Yes? (I usually habitually say yes, since No can be bad)
6. Both files open are still current. Maybe make some minor changes to one of them, maybe it's the 'wrong' one.
7. Save the file. It throws up the 'save as' dialog but it has found the correct folder. Okay.
8. I am open on the 'current' tab in Notepad++. I get a popup 'file has been modified by another app, reload?' (It hasn't, no other app is working on this file).

I am stupid and I hit reload, because, well, Notepad++ is the only one that has this open, right? And I just saved it. Sure I'll reload.

Somehow it reloads the oldest original version of the file from 3 hours previous. This version shouldn't even exist on disk! But there it is.

Oh, and the other tab has also reverted to the old version. I have no undo history and no backups in Roaming.

I am guessing the issue is: after renaming the folder, when saving, it did not in fact save properly.

OR for some reason, it saved an old copy of the file from memory?

### Expected Behavior
- Better handling of all these popups. The popups stress me out and make bad things happen, like this. See issue:#3281
- Not reloading an old version of a file that doesn't exist, reloading the current file saved on disk :(

### Debug Information
Notepad++ v7.4.1   (32-bit)
Build time : May 18 2017 - 02:00:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 21:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:42 UTC
