### ISSUE TITLE
Inconsistent multi-line tab click activation behavior

### ISSUE THREAD

**Issue by balagansky** [notepad-plus-plus/notepad-plus-plus#6274] opened 2019-10-26 00:28 UTC
### Description of the Issue
When multi-line tabs are enabled, behavior when clicking on a tab is inconsistent depending on whether there is one row or more than one row of tabs.

When there is one row of tabs, mouse down activates an inactive tab. But when there multiple rows, inactive tabs only become active on mouse up.

### Steps to Reproduce the Issue
1. Enable multi-line tabs
2. Load up tabs such that there is more than one tab row
3. Click on an inactive tab

### Expected Behavior
Inactive tabs always become active on mouse down

### Actual Behavior
Inactive tabs only become active on mouse up when there are multiple tab rows

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Oct  7 2019 - 19:07:35
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1069
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Also reproducible on master/HEAD

![npptabclick](https://user-images.githubusercontent.com/56180447/67611182-bbb09d80-f74c-11e9-8866-9535c62c729c.gif)

**Comment by balagansky** [comment] 2019-10-28 01:14
The changes suggested by @AngryGamer here seem to fix this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6273#issuecomment-546753080

**Comment by donho** [comment] 2019-10-28 09:40
v7.7.1 is not head version and such issue could be fixed in v7.8
I cannot reproduce the issue you reported at all by using v7.8.

**Closed by donho** 2019-10-28 09:40 UTC

**Comment by balagansky** [comment] 2019-10-28 17:36
I can reproduce it just as easily on 7.8, on multiple machines.

I am truly baffled that you cannot.

**Comment by donho** [comment] 2019-11-06 00:40
Sorry. I read it again and it's not a bug to me.
