### ISSUE TITLE
Clipped text in 'Preferences' window

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#3058] opened 2017-03-17 14:58 UTC
### Description of the Issue

Some texts in `Settings` > `Preferences...` are clipped. This affect some of non-English language and most of translations that are in Cyrillic (Bulgarian, Russian etc.) I provide you some screenshots to see how it is now and how must be. I create the changes with Resource Hacker, so I can't provide you a fixes about this. Yes, I know that I can abbreviate some words, but not always it is good.

`Preferences` > `General` - **now**
![npp-10](https://cloud.githubusercontent.com/assets/8998791/24048267/fb73948c-0b30-11e7-9e91-32f4ffdea51f.png)
`Preferences` > `General` - **must be**
![npp-11](https://cloud.githubusercontent.com/assets/8998791/24048268/fb74102e-0b30-11e7-873e-9df5839b66fd.png)
`Preferences` > `New Document` - **now**
![npp-20](https://cloud.githubusercontent.com/assets/8998791/24048266/fb739554-0b30-11e7-9c5f-c1c9d6255c67.png)
`Preferences` > `New Document` - **must be**
![npp-21](https://cloud.githubusercontent.com/assets/8998791/24048269/fb75a498-0b30-11e7-897e-7cf88ebc13f3.png)
`Preferences` > `Recent Files History` - **now**
![npp-30](https://cloud.githubusercontent.com/assets/8998791/24048270/fb7876dc-0b30-11e7-85b3-54537aec9bfe.png)
`Preferences` > `Recent Files History` - **must be**
![npp-31](https://cloud.githubusercontent.com/assets/8998791/24048277/fb82f026-0b30-11e7-9cb9-2b8ce6e6b39b.png)
`Preferences` > `Auto Completion` - **now**
![npp-40](https://cloud.githubusercontent.com/assets/8998791/24048272/fb810414-0b30-11e7-91f3-bd70160c8ef5.png)
`Preferences` > `Auto Completion` - **must be**
![npp-41](https://cloud.githubusercontent.com/assets/8998791/24048271/fb7f87b0-0b30-11e7-89ef-a19b3fe12b59.png)
menu `Edit` > `Column Editor` - **now**
![npp-50](https://cloud.githubusercontent.com/assets/8998791/24048276/fb8216b0-0b30-11e7-87ab-90c7e2ecf5e7.png)
menu `Edit` > `Column Editor` -**must be**
![npp-51](https://cloud.githubusercontent.com/assets/8998791/24048275/fb817fd4-0b30-11e7-8abf-e9a0fe4c5f3f.png)
menu `Language` > `Define your language` - **now**
![npp-60](https://cloud.githubusercontent.com/assets/8998791/24048274/fb81a392-0b30-11e7-88a6-ac137d8d15d6.png)
menu `Language` > `Define your language` - **must be**
![npp-61](https://cloud.githubusercontent.com/assets/8998791/24048273/fb813966-0b30-11e7-9eb8-2167b387daf3.png)
menu `Language` > `Define your language` - **now**
![npp-70](https://cloud.githubusercontent.com/assets/8998791/24048278/fb87ff80-0b30-11e7-8c93-91cdd15c1a41.png)
menu `Language` > `Define your language` - **must be**
![npp-71](https://cloud.githubusercontent.com/assets/8998791/24048279/fbbbf1aa-0b30-11e7-99cc-885d5362e73b.png)

### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : D:\Install\Office Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppExport.dll NppHasher.dll NppTextFX.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 21:32
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Comment by rddim** [comment] 2019-04-12 20:44
@MetaChuh I really appreciated your supporting work, but did you verify this issue before closing it? I'm with the latest version of N++ and the problem explained in this issue still exist.

**Comment by donho** [comment] 2019-04-12 21:19
@rddim 
Sorry for the inconvenience.
Due to the very large amount of old outdated issues on issue tracker, we have to close then in mass and we don't have time to check one by one. 

Now regarding the issue you posted: 
I can do some effort to enlarge some string lengths, but I won't do it all for the UI aesthetic reason.
It's translator who should make translation suite.

**Closed** 2019-04-12 21:52 UTC

**Comment by rddim** [comment] 2019-04-13 15:57
@donho 
Thank you very much for the fix. Now it is better, except some things. For me the good looked translation is like the good coding for you :) I also, like you as maintainer and the others contributors spend a time to make everything better. Actually with this action and reaction was fixed two long waiting issues :) I don't know what kind of translator is that that makes a restrictions for the strings, but I think it must be fixed too :D
