### ISSUE TITLE
batch language issue

### ISSUE THREAD

**Issue by ultraic-space** [notepad-plus-plus/notepad-plus-plus#8017] opened 2020-03-07 04:49 UTC
![image](https://user-images.githubusercontent.com/61897277/76136928-02ef5900-6072-11ea-8418-2aedb02777f1.png)
&&ECHO not detected as batch command but as text

**Comment by sasumner** [comment] 2020-03-07 13:12
It is really challenging to lex batch language correctly. :-(

**Comment by ArkadiuszMichalski** [comment] 2020-10-04 13:45
Looks like it was fixed in Scintilla, so we are waiting for Notepad ++.

SciTE:
![aaa](https://user-images.githubusercontent.com/2730894/95017208-636e6500-0658-11eb-83ca-05ac0d759ca1.gif)

**Comment by vinsworldcom** [comment] 2021-02-22 14:15
@donho
@sasumner

I can confirm this is fixed in Notepad++ 7.9.3 Unicode Debug using the latest Scintilla 4.4.6 DLL.

Cheers.

**Comment by sasumner** [comment] 2021-02-22 14:21
Closing per @vinsworldcom 's effort at validation.

**Closed by sasumner** 2021-02-22 14:21 UTC
Labels: scintilla dependent
