### ISSUE TITLE
Error when resizing the result field -> GetLastError () returned 1428 

### ISSUE THREAD

**Issue by Artnforces** [notepad-plus-plus/notepad-plus-plus#1676] opened 2016-03-23 16:43 UTC
After that I have made a research of a string thru several folders, I got the result but as I would like resize the field where it has been dispayed, I got a *\* SetWindowsHookEx (Mouse)*\* failed with the message **GetLastError() returned 1428** .
![capture](https://cloud.githubusercontent.com/assets/2866191/13993025/d8f2574c-f0f4-11e5-851e-78358896bf32.JPG)

**Comment by donho** [comment] 2016-03-24 14:10
@Artnforces Please provide detail info from menu `?->Debug Info`

**Comment by Artnforces** [comment] 2016-03-24 14:31
Sorry, but I don't have this menu. What I can do to have it?

2016-03-24 10:10 GMT-04:00 Don HO <notifications@github.com>:

> @Artnforces <https://github.com/Artnforces> Please provide detail info
> from menu ?->Debug Info
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1676#issuecomment-200853628>
>



-- 
Artnforces - M.A.K (Mouveman Artistik Kréyol)

All our tracks in videos / Tous nos titres en vidéos  :
Youtube chanel : "Production Artnforces"
*http://tinyurl.com/cuxqk25 <http://tinyurl.com/cuxqk25>*

**Comment by ClaudiaFrank** [comment] 2016-03-24 19:43
>Sorry, but I don't have this menu. What I can do to have it?

Update npp to latest version.

**Comment by MetaChuh** [comment] 2019-04-13 02:22
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:22 UTC
