### ISSUE TITLE
Minor save/save as bug: a file does not exist on network volume anymore, but save as fails because "The file is already opened in Notepad++"

### ISSUE THREAD

**Issue by macks2008** [notepad-plus-plus/notepad-plus-plus#10965] opened 2021-12-29 04:33 UTC
### Description of the Issue
I have, or rather had, a file named "readme.txt" in a mapped network drive (technically a partition of my desktop's secondary disk that is entirely shared via Windows), and for some reason instead of asking me if I want to keep the file in Notepad++ after I deleted it from disk, I ended up with a catch 22 situation where I can't re-save it to disk, or at least not under the same exact name. Notepad++ seems to be a bit confused.

### Steps to Reproduce the Issue

1. create readme.txt in N:/folder/name/here, where N:/is a logical drive (i.e. partition) shared from another computer and "mapped as network drive"
> note: this may also happen with local drives, but I'm trying to make the reproduction steps exact to my situation for now. More generic test vectors can be added later
2. open readme.txt in Notepad++
3. add some text to the newly opened file tab, but do not save it
4. close NPP without saving
5. delete readme.txt from disk while Notepad++ was closed
6. unless I'm mistaken, opening NPP would normally (in most situations where network storage isn't involved, I think) cause it to notice the file no longer exists, right? Giving you the option to either dissociate the file from that path and treat it as a new file, or discard it. However, that didn't happen here. Instead what happened...:
7. When I realized I hadn't saved the file, I pressed "control + S", which caused "Save as" to be displayed
8. I attempted to leave the name as "readme.txt"
9. Error occurred: even though I'm saving the "readme.txt" tab, I'm told "The file is already opened in Notepad++"

### Expected Behavior
I should either be able to save the unsaved file under its own name, or I should get a more actionable error message. Most people probably wouldn't want a stacktrace, but at least tell me why I can't save the file as itself. It's like a small-scale identity crisis!
### Actual Behavior
readme.txt tab cannot be saved as readme.txt because it already exists.

### Debug Information

Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "N:\PDD\Toontown screenshots\.gitignore"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Additional info
fortunately, the workaround is quite simple. Simply:
1. change a single character in the file name you are saving as
2. It will save as that and the tab name will change
3. right click the tab and choose "rename" to resave as the original name.
4. no issue, so apparently it's just getting confused by the existing tab trying to duplicate itself.
### Screenshots
![directory state during save-as operation](https://user-images.githubusercontent.com/7110033/147627093-f2872080-288c-4dc7-a570-388acbabba6a.png)
![error (actual text of document is irrelevant, it seems)](https://user-images.githubusercontent.com/7110033/147627106-30265c44-e72e-4026-9b03-461935665578.png)

**Comment by alankilborn** [comment] 2021-12-29 12:16
It reproduces just fine using a local file.

**Comment by xomx** [comment] 2021-12-30 21:56
I agree with @alankilborn , it is a bug in common saving way.

It can be fixed by simple changing one line in .\PowerEditor\src\NppIO.cpp -> Notepad_plus::fileSaveAs():

```
...
if (!fn.empty())
{
	BufferID other = _pDocTab->findBufferByName(fn.c_str());
	if (other == BUFFER_INVALID)
		other = _pNonDocTab->findBufferByName(fn.c_str());

	if (other == BUFFER_INVALID)	//can save, as both (same and other) view don't contain buffer
...
```
to
```
	if ((other == BUFFER_INVALID) || other->isUntitled())	//can save, as both (same and other) view don't contain buffer
```
but I would like to ask @donho before proceeding to PR:

1) The more correct DocFileStatus `DOC_DELETED` in this case is changed in the `FileManager::loadFile()` to `DOC_UNNAMED` when the original filepath no longer exists. Why is that status change needed?

2) If my simple fix above is sufficient, how to handle the 'Save' without 'As' way? Now because of the buffer has status `DOC_UNNAMED`, the `Notepad_plus::fileSaveAs()` is called anyway - should I patch alike also the `Notepad_plus::fileSave()` or should i left this as is?

**Comment by Anklebitter** [comment] 2022-01-05 22:02
instead of 
![image](https://user-images.githubusercontent.com/18487412/148295360-7d067d92-34bb-4f0c-90b9-0116c904b692.png)
would this work instead?
![image](https://user-images.githubusercontent.com/18487412/148295464-c5b06a37-ad59-4be5-bef8-556395cc5b4d.png)

**Comment by xomx** [comment] 2022-01-06 20:57
@Anklebitter 
Yes, this will work as well.
But it is better, because it is more universal (it will work even for the `DOC_DELETED` status).

**Comment by donho** [comment] 2022-01-07 03:28
@Anklebitter 
Since it's your idea, do you want to create a PR?

**Comment by donho** [comment] 2022-01-07 18:22
@Anklebitter 
Never mind, I will do it (with a detailed comment).
Thank you for your hint!

**Comment by Anklebitter** [comment] 2022-01-07 19:31
Hey thanks, I thought you were referring to your fix. You can implement the fix I have no issue.

**Closed** 2022-01-07 20:05 UTC
Labels: bug, accepted

**Comment by macks2008** [comment] 2022-01-07 20:09
you guys work fast! Glad I could help catch this 🎉
