### ISSUE TITLE
Javascript lexer - escaping "grave accent" char is not working

### ISSUE THREAD

**Issue by oasisindesert** [notepad-plus-plus/notepad-plus-plus#12287] opened 2022-10-05 07:00 UTC
### Description of the Issue

Escaping special characters with back slash character allows to include to string literal the same character that is used to enclose the string.
When the string is well formed and all specific characters are escaped the string is highlighted as a string literal, and the rest of the code according to its function.
It works correctly with single and double quotation marks, but doesn't highlight correctly a string literal enclosed with grave accent char and containing escaped grave accent char.

### Steps to Reproduce the Issue

```javascript
  const a = 'hello\'' ; const aa = 123  // ok
  const b = "hello\"" ; const bb = 123  // ok
  const c = `hello\``; const cc = 123   // not ok, highlighted incorrectly, but the code is working
```

### Expected Behavior

When including grave accent (&#x60;) char escaped with back slash char in a string enclosed with grave accent char (`), it must be identified and highlighted by the lexer as a part of the literal string.

### Actual Behavior

Currently, the rest of the code out of the enclosed string is also highlighting like a string literal.

### Debug Information

Notepad++ v8.4.5   (64-bit)
Build time : Sep  3 2022 - 04:05:32
Path : ****
Command Line : "****"
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.24468
Current ANSI codepage : 1251
Plugins : 
    GitSCM (1.4.4.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppCrypt (1.0.1.6)
    NppExport (0.4)

**Comment by rdipardo** [comment] 2022-10-05 11:58
The lexer does not support JavaScript template strings (i.e., strings enclosed by "grave" accents): https://github.com/ScintillaOrg/lexilla/issues/94

Duplicate of, at least, #8421, #7879, #6193, #4007, #3822, #3331, and #1055.

**Closed** 2022-10-05 12:03 UTC
