### ISSUE TITLE
Double-clicking on first/last word of a line selects more than expected

### ISSUE THREAD

**Issue by NeimadG** [notepad-plus-plus/notepad-plus-plus#3140] opened 2017-04-06 15:43 UTC
### Description of the Issue

In a normal text file, double-clicking on first word of a line selects : 
- with \r\n (Windows) end of line, the word itself and the \r\n BEFORE it.
- with \n (UNIX) end of line, the word itself + the \n BEFORE it + until the last word of the previous non-empty line.

Double clicking on the last word of a line selects : 
- with \r\n (Windows) end of line, the word only (OK)
- with \n (UNIX) end of line, the word + \n + until the first word of the next non-empty line

Everything goes right with MAC end-of-line style

### Steps to Reproduce the Issue

1. Fresh install NP++ 7.3.3 64Bits French on Windows 10 64 Pro
2. Create a text file containing:
```
hello I am
another new line


No? line
```

2. Make sure end of line style is UNIX (\n)
3. double-click on the first word "line"

### Expected Behavior

the first word "line" should be highlighted and colored, the second word "line" should be colored

### Actual Behavior

The actual selection is : "line

No"

### Similar Manipulations
In UNIX end-of-line style :
Double-click on "another", the actual selection is "am
another"

In Windows end-of-line style :
Double-click on "another", the actual selection is "
another"
Double-click on "line", the selection is as expected

**Comment by joo7** [comment] 2017-04-09 12:06
I have the same issue (I can confirm issue, updated installation)

debug info:
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by Manuela-Fereira** [comment] 2017-04-09 14:43
I confirm.

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by joo7** [comment] 2017-04-13 06:44
Issue is gone/solved after windows update (creator). 
Debug info is the same. 
Before update I observed copy/paste-issues after closing libre office...

**Comment by Manuela-Fereira** [comment] 2017-04-15 09:40
Similarly, issue is gone after Win10 update. It seems to be a Windows bug.

**Closed** 2019-05-07 12:35 UTC
