### ISSUE TITLE
Can't type tab character

### ISSUE THREAD

**Issue by CTimmerman** [notepad-plus-plus/notepad-plus-plus#8902] opened 2020-09-26 11:23 UTC
### Description of the Issue

Tab settings have no effect. Pressing Tab always inserts 4 spaces.

### Steps to Reproduce the Issue

1.  Check Tab settings under Language (Python).
2.  Press Tab to insert the tab of specified size, optionally replaced by spaces.
3. See 4 spaces appear instead.

### Expected Behavior

Insert a tab or whatever the Language tab settings say.

### Actual Behavior

4 spaces were inserted instead.

### Debug Information

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1909
OS Build : 18363.1082
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll

**Comment by sasumner** [comment] 2020-09-26 11:40
Cannot reproduce in 7.8.9.

>See 4 spaces appear instead.

Do you have visible-whitespace turned on?
If not, then a tab will visually appear the same as 4 spaces.
Turn on via _View_ menu > _Show Symbol_ > _View White Space and TAB_

Closing as not-reproducible, will reopen with more solid evidence that this isn't working correctly.

**Closed by sasumner** 2020-09-26 11:40 UTC

**Comment by CTimmerman** [comment] 2020-09-26 21:34
It only happend in a .py file afaik. Visible whitespace is enabled and even after turning all spaces to tabs using blank ops tab keeps inserting spaces. 
![image](https://user-images.githubusercontent.com/9662163/94350677-de2ff280-0050-11eb-9d04-578c40d45843.png)

**Comment by sasumner** [comment] 2020-09-26 23:56
@ArkadiuszMichalski Can you attempt to replicate OP's problem?

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 00:06
@sasumner For me works fine, just to make sure.. @CTimmerman you select Python language in right side?

**Comment by CTimmerman** [comment] 2020-09-27 01:54
![image](https://user-images.githubusercontent.com/9662163/94353760-30830a80-0075-11eb-9d01-13bbe67e9421.png)

**Comment by CTimmerman** [comment] 2020-09-27 01:57
Tab works when a different language is selected. 
![image](https://user-images.githubusercontent.com/9662163/94353801-92dc0b00-0075-11eb-96f9-08be48eeba52.png)

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 08:59
@CTimmerman I mean this:
![a](https://user-images.githubusercontent.com/2730894/94360799-6abdcd80-00b0-11eb-81aa-f955f93d657e.gif)

**Comment by sasumner** [comment] 2020-09-27 12:01
Is the following relevant / helpful ? :
https://community.notepad-plus-plus.org/topic/20062/how-do-you-change-tab-to-insert-a-tab-character-instead-of-4-spaces

**Comment by CTimmerman** [comment] 2020-09-27 17:16
> Is the following relevant / helpful ? :
> https://community.notepad-plus-plus.org/topic/20062/how-do-you-change-tab-to-insert-a-tab-character-instead-of-4-spaces

No; see above.

**Comment by sasumner** [comment] 2020-09-27 18:10
At this point I'd have to recommend quitting Notepad++ and renaming/moving config.xml and langs.xml and then start up Notepad++ again (it will recreate virgin copies of those two files) and seeing if that produces any change.

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 19:35
@CTimmerman Once again show us (via image) how you set Tab for Python in Preferences window.

**Comment by sasumner** [comment] 2020-09-27 20:24
>Once again show us (via image) how you set Tab for Python in Preferences window.

True, that is a missing piece...

**Comment by CTimmerman** [comment] 2020-09-28 06:38
> > Once again show us (via image) how you set Tab for Python in Preferences window.
> 
> True, that is a missing piece...

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8902#issuecomment-699550689


As explained here i figured it out: THE SELECTED LANGUAGE HAS NOTHING TO DO WITH THE SELECTED TAB SETTING!!

**Comment by ArkadiuszMichalski** [comment] 2020-09-28 07:30
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8902#issuecomment-699607347

**Comment by sasumner** [comment] 2020-09-28 11:43
Wow.
I don't think I've ever seen such an interpretation of the UI for tab setup.
I think I'm glad this issue is over. :-)
