### ISSUE TITLE
npp 7 x64 crashes when recording macro and pressing "/"

### ISSUE THREAD

**Issue by albertogscotti** [notepad-plus-plus/notepad-plus-plus#2369] opened 2016-09-29 13:06 UTC
### Description of the Issue
Notepad++ 7 x64 stops working on Windows10 x64 (build 14393.187) when recording a macro and pressing "/" (slash)

### Steps to Reproduce the Issue
1. open npp
2. click "start recording"
3. press /

**Comment by albertogscotti** [comment] 2016-09-29 13:16
Here are the debug info

Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10
Plugins : none

**Comment by linquize** [comment] 2016-09-29 13:22
64-bit Notepad++ 7
Windows 10 x64 crash

Windows 7 x64 does not crash

**Comment by dail8859** [comment] 2016-09-29 13:30
Duplicate of #2310, #2331

This issue has been fixed in 8e9e8c04cd3a4fbc3556119cebfa9d4671eaf9b0 and will be available in the next release.

If you need a fix to this until then you can download this nightly release:

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.402/job/0rrtf2da6yxl7389/artifacts

and copy over your notepad++.exe.

**Closed** 2016-09-29 16:49 UTC
Labels: duplicate
