### ISSUE TITLE
When you press Enter, the "Plugin Management" window closes.

### ISSUE THREAD

**Issue by motivix** [notepad-plus-plus/notepad-plus-plus#11348] opened 2022-03-06 19:51 UTC
### Description of the Issue

When you press Enter in the Find field in the Menu-Plugins-Plugins Admin menu, the "Plugins Admin" window closes.

### Steps to Reproduce the Issue

1. Menu
2. Plugins
3. Plugins Admin
4. Find
5. Search query
6. Press Enter

### Expected Behavior

The search for plugins should begin

### Actual Behavior

The window "Plugins Admin" is close

**Comment by alankilborn** [comment] 2022-03-06 20:07
>When you press Enter, the "Plugin Management" window closes

There is no "Plugin Management" window, making it impossible for anyone to follow what you mean.
Please edit the information in your issue for accuracy or close the issue.

Also, supply all information requested.
Issues without all information will be closed without action.
(Your issue did not include "Debug Information")
(Hint: follow the issue template)

**Comment by rimrul** [comment] 2022-03-07 08:45
> >When you press Enter, the "Plugin Management" window closes
> 
> There is no "Plugin Management" window, making it impossible for anyone to follow what you mean.

You're being a smartass here and you know it. There's exactly one window they could mean. It's the "Plugins Admin" window (which the german localization calls "Plugin-Verwaltung" ("Plugin management")). The user is probably trying to translate their non-english UI back to english here.

> (Your issue did not include "Debug Information")

FWIW I can reproduce the reported behaviour with the following:

Notepad++ v8.2.1 (64-bit)
Build time : Jan 19 2022 - 18:43:05
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by motivix** [comment] 2022-03-07 09:24
Friends, I'm new to GitHub.  Forgive me.  If something is wrong just delete this branch.

**Comment by alankilborn** [comment] 2022-03-07 11:51
>You're being a smartass here and you know it. 

Umm, no...

**Comment by rimrul** [comment] 2022-03-07 13:02
If you say so.

**Comment by alankilborn** [comment] 2022-03-07 13:16
>If you say so.

I don't think someone with 7800 reputation points on the [Notepad++ support site](https://community.notepad-plus-plus.org/users?section=sort-reputation) is going to waste time being a smartass.

There are a lot of issues here, and if people submitting issues can't follow the template, and provide complete info (debug info is a key metric), an issue may not get looked at.  OK, in hindsight maybe this is an "easy one", but...

So...this raises an interesting question.  Should localization setting be part of the Debug info?
If users that don't provide screenshots but simply discuss a problem using localized text strings, can this be a source of confusion?  I was certainly confused by use of "Plugin Management" in this issue.

**Comment by vinsworldcom** [comment] 2022-03-07 15:29
@alankilborn , @rimrul @motivix Not to stir the pot, but I don't think @alankilborn is a "smartass" or even being overly pedantic.  It is possible to run the ancient, deprecated and no-longer-supported "Plugin Manager" in the current version of Notepad++:

![image](https://user-images.githubusercontent.com/9657169/157063637-1ba3dc0d-46e1-48b7-b548-bed1d8772519.png)

This this will install things incorrectly and probably wrong versions and this is certainly not recommended, but it is _possible_ and with an ancient Notepad++ install, it is _conceivable_ that someone could still have this installed.

You can see from the screenshot "Plugin Admin" is there and that is not only the **_preferred_** way, it is the **_only supported way_** (other than a manual install) of installing plugins to Notepad++.

That is why the issue template exists and it is important to use the **exact** terminology, and include screenshots when / if appropriate to effectively communicate the reported issue and avoid any assumptions.

Cheers.

**Comment by Yaron10** [comment] 2022-03-07 18:42
Another related case:
Select and check a plugin entry (the _Install/Uninstall_ button becomes active).
Press _Enter_.

**Result:**
The window is closed.

How about the following?
When the search edit-box gets focus, make the _Next_ button default.
When a plugin entry is selected and checked, make the _Install/Uninstall_ button default.
Make the _Close_ button default if the above mentioned elements don't have focus.

**Comment by xomx** [comment] 2022-03-07 23:17
@Yaron10 

> Another related case:
Select and check a plugin entry 

Good catch!
Selecting an item in the plugins listview control is enough to see that unwanted closing by ENTER (it is not necessary to check a plugin in that list to see that).

So I changed my patch to be more universal, though I am not completely satisfied with the current solution:
1) When one press ENTER, while keyboard focus is on the search editctrl, the focus moves to the 'Next' button (as you suggested).
2) When a plugin entry in the listviewctrl is selected (and/or checked/unchecked), the ENTER is simply swallowed (nothing happens). This is intended, but I would like to see another behavior - checking/unchecking the plugin-item checkbox.

If I find time, I will try the checking/unchecking by ENTER. Otherwise it stays as is.

**Comment by Yaron10** [comment] 2022-03-07 23:45
@xomx,

> Selecting an item in the plugins listview control is enough to see that unwanted closing by ENTER (it is not necessary to check a plugin in that list to see that).

👍 

> When one press ENTER, while keyboard focus is on the search editctrl, the focus moves to the 'Next' button (as you suggested).

My suggestion was to make the Next button default *before* pressing Enter.
Just like the Find dialog.
![תמונה](https://user-images.githubusercontent.com/10229320/157136713-b03fdaf2-7279-4a51-a267-076542c6eb25.png)

> When a plugin entry in the listviewctrl is selected (and/or checked/unchecked), the ENTER there is simply swallowed (nothing happens).

I think the Install button should be default once it's enabled.

> If I find time...

I can't say anything about that. :)

Thank you for your time and work. 👍 
It's certainly better with your PR.

**Comment by Yaron10** [comment] 2022-03-08 20:57
Thinking a bit more about it:

When the window is first displayed, give focus to the search box and make the Next button default.
If the user selects a plugin *without checking it*, Enter shouldn't trigger any action.
If an entry is checked, the Install button should be default.
If the user gives focus to the search box while an entry is selected and checked, make the Next button default.

The Close button can get focus and become default by using Tab.

**Comment by alankilborn** [comment] 2022-03-08 21:37
OFF-TOPIC:

@Yaron10 

Since you apparently like "Thinking a bit more about it", maybe you could offer some hints in a new issue about the behavior of the box that opens when you save a macro.  :-)

**Comment by Yaron10** [comment] 2022-03-08 22:13
@alankilborn,

Let's think a bit more together here, and if we're on the same page - we can open a new issue.

1. The Name field should have focus on displaying the dialog.
2. The OK button is not "selected" until switching from NPP to another program and back.
![תמונה](https://user-images.githubusercontent.com/10229320/157334238-5bd8a506-9a4e-48cc-9d07-11a222ea9e33.png)
I don't know if it's a Windows issue or NPP's.
4. It should be adapted to RTL (I'm pretty sure you didn't have that in mind :) ).

Anything else? Is that the only "problem-dialog"?

**Comment by Yaron10** [comment] 2022-03-08 22:17
And nothing happens on pressing Enter when the dialog is displayed.
Well, I'm a "mouse-oriented" user. :)

**Closed** 2022-03-09 02:44 UTC
Labels: accepted
