### ISSUE TITLE
[REQ] Can we pin/lock tabs?

### ISSUE THREAD

**Issue by worldor** [notepad-plus-plus/notepad-plus-plus#12806] opened 2023-01-14 23:34 UTC
Hello

[REQ] Can we pin/lock tabs?
I read online such request from 2015 but still cannot see any implementation.

Thanks!

**Comment by alankilborn** [comment] 2023-01-15 00:09
Duplicate of #5786 
Please close this issue.

**Comment by donho** [comment] 2024-11-21 20:02
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0

**Closed by donho** 2024-11-21 20:02 UTC
Labels: duplicate
