### ISSUE TITLE
Notepad++ does not 'Open in new instance' with default language

### ISSUE THREAD

**Issue by AaronBritton** [notepad-plus-plus/notepad-plus-plus#3131] opened 2017-04-04 09:24 UTC
### Description of the Issue
I have a user definable language, which is used whenever a d3b is opened. However, if I move an opened file to a new instance (both right-clicking, and selecting Move/Clone in New Instance as well as dragging a dropping the file on a separate window), this language is not automatically applied. I can manually apply the language, but I believe this should be automatic.

### Steps to Reproduce the Issue

1. Open 2 saves files where at least one of them has a 'default language'
2. Right click on that file within the currently opened tabs
3. Choose Move to new instance

### Expected Behavior
The file should be opened in the new instance with the language automatically applied.

### Actual Behavior
The file is opened in the new instance, but the language is not automatically applied.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll Demo.dll Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 22:00
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 22:00 UTC
