### ISSUE TITLE
File Open dialog has wrong text on Open button.

### ISSUE THREAD

**Issue by gunthre** [notepad-plus-plus/notepad-plus-plus#10031] opened 2021-06-18 16:22 UTC
### Description of the Issue

File --> Open.
The Open dialog pops up.  The Open button says Save instead.  The button works, just wrong text.

### Steps to Reproduce the Issue

See description. 

### Expected Behavior

Expected button to read "Open", not "Save."

### Actual Behavior

Button reads "Open."

### Debug Information

Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1556
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Still the best editor out there, been using it for years.  Thanks very much!!

**Comment by sasumner** [comment] 2021-06-18 17:48
Duplicate of #9966 and others.
This has been fixed in 8.1.
Please search for existing issues (open OR closed) before creating a new one -- thanks.
Closing.

**Closed by sasumner** 2021-06-18 17:48 UTC

**Comment by gunthre** [comment] 2021-06-18 18:03
I did search, but now I think I was only looking at Open issues.  Ugh, I'm an idiot.

My apologies for clogging the works!

**Comment by sasumner** [comment] 2021-06-18 18:40
>I was only looking at Open issues

I've done that myself.

>I'm an idiot

Nah...  No worries.
