### ISSUE TITLE
"Remove Duplicate Lines" did not find all duplicates

### ISSUE THREAD

**Issue by ReporterX** [notepad-plus-plus/notepad-plus-plus#11999] opened 2022-08-08 08:46 UTC
### Steps to Reproduce the Issue
1. Open the test file: [Dup line test.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9280278/Dup.line.test.txt)
2. Run "Remove Duplicate Lines" function

### Expected Behavior
All duplicate lines are removed.

### Actual Behavior
None is removed.

### Notes
They are correctly marked as duplicates in Microsoft Excel.

### Debug Information
Notepad++ v8.4.4   (32-bit)
Build time : Jul 15 2022 - 17:56:38
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
Current ANSI codepage : 65001
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment] 2022-08-08 12:56
The reason that no lines are removed is that no lines are duplicates of each other.
Opening your file in a hex editor where the raw data is shown, we see this clearly:

![image](https://user-images.githubusercontent.com/77065706/183422080-58257b17-8945-4bad-9a21-61074877e3ea.png)

Here I've highlighted in the same colors the lines that at first glance appear to be duplicates; if they were truly duplicates the two orange sections would be identical, the two yellow sections would be identical, etc.

What is really going on with your file is that you have several UTF-8 [LRE](https://www.compart.com/en/unicode/U+202A) characters embedded; in reality your file looks like this:

![image](https://user-images.githubusercontent.com/77065706/183422894-7f6e5f1d-46b8-45ba-84f0-a99ceaa5ef9e.png)

And from that you can clearly see that no line is a duplicate of any other line.

Recommend CLOSURE of this item.

**Comment by ArkadiuszMichalski** [comment] 2022-08-09 01:03
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11999.

**Closed by ArkadiuszMichalski** 2022-08-09 01:03 UTC
