### ISSUE TITLE
[Suggestion] Use Associated File Icon (tint or overlay for needs saving).

### ISSUE THREAD

**Issue by dbareis** [notepad-plus-plus/notepad-plus-plus#12374] opened 2022-10-22 03:24 UTC
### Description of the Issue
In SETTINGS, GENERAL there is an "alternate Icons" option, I want to have the CORRECT (associated) FILE CON for the file being edited displayed with some variation to show that it needs saving.  I do not want to set my own text icon as I've seen a lot of requests for.

If this is currently possible please let me know :-)

### Expected Behavior
To spell it out I want ".txt", ".c", ".html", ".GenealogyResearch" blah, blah text files to show their specific and different icons.

### Actual Behavior
There are two FIXED icon sets that don't vary by "file type".

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\DBAREIS\FamilyTree\FAG (cemetery visits)\Queensland\Drayton and Toowoomba Cemetery\Lindsay, Elsie Isabel “Elsie” Duffus (17 Nov 1908 ~ 26 Sep 1988), NickName=Elise.GenealogyResearch" -n9999
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro N (64-bit) 
OS Version : 22H2
OS Build : 19045.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    RunMe (1.4.1)
    SessionMgr (1.4.4)

**Comment by alankilborn** [comment] 2022-10-22 10:00
Suggest you use v2 of the MenuIcons plugin, see https://github.com/francostellari/NppPlugins/tree/main/MenuIcons

**Comment by dbareis** [comment] 2022-10-22 23:49
@alankilborn 

I copied the dll and text files to: "C:\Program Files\Notepad++\plugins\MenuIcons(v2, manually installed)" (and then "C:\Program Files\Notepad++\plugins") and restarted NPP but the plugin doesn't show under "Plugins Admin, Installed".  If there is a NPP way to install the plugin from zip, "install.txt" doesn't say so and I can't find one.

**Comment by alankilborn** [comment] 2022-10-23 00:17
The folder name under plugins must be the same as the DLL.

**Comment by ArkadiuszMichalski** [comment] 2022-10-28 13:34
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12231.

**Closed by ArkadiuszMichalski** 2022-10-28 13:34 UTC
