### ISSUE TITLE
Print marking, but printing without marking required

### ISSUE THREAD

**Issue by PeterMaria** [notepad-plus-plus/notepad-plus-plus#12033] opened 2022-08-24 12:03 UTC
### Description of the Issue
Print selected text, but printing without marking required

### Steps to Reproduce the Issue

1. Settings Preferences: ON: Print line numbers, SET: WYSIWIG
2. Use any text file
3. Select any text part
4. Print with option selected text

### Expected Behavior
The printout should always be WYSIWYG. 
But if you only want to print the selected text, which happens very often, it made no sense to print the mark. This disturbs enormously.
If the printout is limited to the mark, do not print the mark as a background. 

Printing the marker can be done when the whole text is printed. However, this is not desired by all users. Therefore possibly more settings to this topic.

### Actual Behavior
Printing the selected text leads to a printout, which also contains the marking. Gray background.

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    GitSCM (1.4.7.1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment] 2022-08-24 12:22
@PeterMaria 
By "mark" or "marking" are you by chance rereferring to "selected text"?
Please attempt to use correct terminology for best response to your report.

**Comment by InjAnnuity1** [comment] 2022-08-24 19:44
I can confirm that when text is selected, and you print the selected text (radio button "Selection" is automatically chosen), then the text is printed with a gray background.  This can make the text _very_ hard to read.

When radio button "Selection" is chosen, it also seems completely unnecessary.  Only the selected text will be printed, anyway.  It doesn't need to be distinguished, on the printout, from any unselected text.

I have observed this since at least v8.4.2, under Windows 10.

**Comment by rdipardo** [comment] 2022-08-24 20:51
> text is printed with a gray background.

Known issue: #11826

**Comment by InjAnnuity1** [comment] 2022-08-24 20:56
Thank you.  I had not yet scrolled down that far in the Issues list.

**Comment by rdipardo** [comment] 2022-08-27 20:32
@InjAnnuity1

This development build may resolve the issue with the unexpected gray background: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44597613/job/9mii1ux7a1w0w0ht/artifacts

**Comment by InjAnnuity1** [comment] 2022-08-28 20:42
Thanks!  I’ve run one test so far, and it seems to have solved that problem.  The printout is clear of any background color.

Phil Colbert
Director of Technology
InjAnnuity, Inc.

**Comment by ArkadiuszMichalski** [comment] 2022-08-29 10:54
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11826.

**Closed by ArkadiuszMichalski** 2022-08-29 10:54 UTC
