### ISSUE TITLE
Print document green

### ISSUE THREAD

**Issue by RalpManis** [notepad-plus-plus/notepad-plus-plus#12419] opened 2022-10-28 19:56 UTC
NP++ 8.4.6 With "Display Change History" enabled printing a document colors the "entire page" green with black text. It also prints the line numbers.

1. Default "Display Change History" settings
2. Create document with text.
3. Print in color, the page prints all green with black text.
4. Print in b&w , the page prints all dark gray with black text.
![notepad++](https://user-images.githubusercontent.com/49681015/198721562-564fce88-17af-40ae-80fc-e4dff2a9223f.jpg)

**Comment by RalpManis** [comment] 2022-10-28 19:58
Sorry for the bad color in photo but you will get the idea. When I turned off Display Change History in the settings, printing is normal except for the line numbers.

**Comment by alankilborn** [comment] 2022-10-28 20:03
This is a duplicate of many existing issues and can be closed.
Well be fixed in 8.4.7.

**Comment by RalpManis** [comment] 2022-10-28 20:19
Great, thanks!

**Closed** 2022-10-29 00:41 UTC
