### ISSUE TITLE
Random Grey areas appear on UI at startup

### ISSUE THREAD

**Issue by aghand0ur** [notepad-plus-plus/notepad-plus-plus#9717] opened 2021-03-29 15:45 UTC
### Description of the Issue

Hi,
On startup, grey areas appear as shown in the image below.
Even if I remove them, they appear again after launching the application.

![image](https://user-images.githubusercontent.com/14883982/112862751-c0564f80-90be-11eb-93dd-4aea625104ed.png)

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19042.870
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment] 2021-03-29 16:22
@aghand0ur What happens if you open some dock panel (e.g. _View > Folder as Workspace_)?
What if you close the panels? Will they appear again?

**Comment by aghand0ur** [comment] 2021-03-30 06:15
Thank you @mere-human for your feedback..
After restarting my machine, the above behavior (potential bug) is no more reproducible..

**Comment by aghand0ur** [comment] 2021-04-19 14:59
@mere-human I run again into the same issue...
+ Nothing happens when I opened a dock panel
+ i closed the panels and restarted notepad++ but they appeared again..
Any clues?
![image](https://user-images.githubusercontent.com/14883982/115257567-e2307880-a138-11eb-83d4-60b314d3e13f.png)

**Comment by sasumner** [comment] 2021-04-19 15:04
Seems the same as #9760 , which go rejected.
We can try reopening this one.

**Comment by pryrt** [comment] 2021-04-20 15:10
I'll post in this open issue, rather than the closed issue #9760.

The user from forum topic https://community.notepad-plus-plus.org/topic/21053/layout-breaks-after-a-few-days has given us the Debug Info, confirming the same Windows OS revision as the one from https://community.notepad-plus-plus.org/topic/20996/tabs-are-floating-after-upgrade-to-7-9-5 and this issue:
```
OS Version : 2009
OS Build : 19042.867
```

Another user today gave us even more info: https://community.notepad-plus-plus.org/topic/21056/window-layout-problems-after-update -- also on OS Version 2009.  And he tried downgrading Notepad++ from v7.9.5 to v7.9.4 (see the Debug Info's in his post) and the problem was still there, but when he switched to Admin Mode, the problem went away.  So it's not Notepad++\-version specific.

I have still never seen anyone complain about this issue with an older Win10 version.

I wonder if there's some combination of the way that Win10 changed -- maybe in how it handles storing window sizes, or some such.

**Comment by pryrt** [comment] 2021-04-20 20:53
@aghand0ur ,

Do you use nVidia video card or another brand?

Either way, could you try to update your video drivers and reboot?  There have been at least two instances of someone with nVidia claiming that the problem was fixed after driver update + reboot: [Dan Schreck 13 days ago](https://community.notepad-plus-plus.org/post/64735) and [DomWesker just today](https://community.notepad-plus-plus.org/post/65188)

**Comment by mmadziamcx** [comment] 2021-04-20 23:06
I'm having the same issue. npp is not the only application affected. I'm also having issues with other apps rendering panels inside of the application Window (MS SQL Management Studio) and some other apps are not restoring properly after being minimized. I actually get an error from SSMS stating "Failed to create window handle for pane '' (mscorlib)"

This appears to be due to a recent Windows update. Either:

OS Build 19042.928 - https://support.microsoft.com/en-us/topic/april-13-2021-kb5001330-os-builds-19041-928-and-19042-928-cead30cd-f284-4115-a42f-d67fec538490

OR

OS Build 19042.867 - https://support.microsoft.com/en-us/topic/march-9-2021-kb5000802-os-builds-19041-867-and-19042-867-63552d64-fe44-4132-8813-ef56d3626e14

I am attempting to remove these updates and see if it resolves the problem. Hopefully my Windows install survives the process. I will update the thread if I make it to the other side. Wishe me luck!

**Comment by mmadziamcx** [comment] 2021-04-20 23:35
Uninstalling the following Windows Update resolved the issue for me!

**2021-04 Cumulative Update for Windows 10 (KB5001330)** _OS Build 19042.928_ - https://support.microsoft.com/en-us/topic/april-13-2021-kb5001330-os-builds-19041-928-and-19042-928-cead30cd-f284-4115-a42f-d67fec538490

I am now running on the following and can no longer reproduce the rendering issues in npp or any of the other affected apps (Microsoft SSMS, Slack)

OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.870

**Comment by kvan** [comment] 2021-05-04 08:44
FWIW I'm seeing this on Intel integrated graphics (i7-8650U) on an older Windows version.

Seems to be fixed temporarily by a Windows restart. KB5001330 is not installed on this system.

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1500
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by mmadziamcx** [comment] 2021-05-04 13:59
I think the Windows Updates were a red herring , it was the associated reboot that appeared to be clearing the issue temporarily. 

I've now found the issue consistently happens after I use a web meeting app with screen sharing (RingCentral). I'm not sure if the problem is specific to this app, or more broadly any app that uses the same method for capturing screens. Either way, after every screenshare, npp stops rendering correctly until a reboot. 

I asked a co-worker of mine who also uses the same app for screen share and he said he is having similar problems with npp rendering after using the app, and again a reboot clears the issue until he uses the screen sharing again.

**Comment by Ekopalypse** [comment] 2021-05-05 10:59
another incident, was reported here
https://community.notepad-plus-plus.org/topic/21128/disintegrated-ui

**Comment by boviz** [comment] 2021-05-05 15:00
I can confirm that it happened after sharing one of my windows screen during a call.

**Comment by mmadziamcx** [comment] 2021-05-05 16:39
@boviz What app were you using for screen sharing? The one causing issues for me is called 'RingCentral' . I am interested to understand if the problem is only with this specific app or others as well.

**Comment by pryrt** [comment] 2021-05-12 16:23
Another user with the problem: https://community.notepad-plus-plus.org/topic/21154/panel-layout-corruption-after-power-loss

**Comment by Ekopalypse** [comment] 2021-06-21 10:59
and another one https://community.notepad-plus-plus.org/topic/21366/window-view-problem

**Comment by ArkadiuszMichalski** [comment] 2021-08-19 14:00
and another one https://community.notepad-plus-plus.org/topic/21691/strange-window-layout-in-new-installation-of-8-1-3

**Comment by MythicManiac** [comment] 2021-08-22 01:07
I just ran into this or a similar issue myself. Whenever I minimize notepad++ and attempt to bring it up again, it will not render any window at all. Once I shut down & relaunch it, it will havve scaled to a 0 height and minimum width window. The first time it happened, after dragging the window to a larger size, I saw the following:

**Comment by pryrt** [comment] 2021-08-23 13:16
and another
https://community.notepad-plus-plus.org/topic/21710/file-tab-on-menu-bar-suddenly-way-too-large

**Comment by mere-human** [comment] 2021-08-29 09:19
I wonder, what docked panels were opened before the bug had appeared?

**Comment by Nyt0x** [comment] 2021-08-30 21:47
Hi, sorry to bump this issue, I just had it and lucky enough I'm starting a new job so my computer is quite barren still, and I've used Notepad++ for years before without issues.

The only new thing in my setup (that was used when I experienced the issue) is that, I am now using both Teams and Slack, and used the screen sharing feature from both back to back. From what I can see from previous comment in this thread, it might be linked.

Interestingly enough I've used both Teams/Notepad++ and screen sharing without ever experiencing it, ever. 
So maybe something with Slack is the issue, or something with having multiple app used for screen sharing.

Deleting all AppData\Roaming\Notepad++ does not help, however closing all opened document in Notepad++ and restarting it with Admin rights does fix the issue, without having to reboot.

Hopefully this helps you. In any case thank you for this amazing tool!!

Additional info:
Notepad++ v8.1.4 (64-bit) (no plugin)
Windows 10 Pro (64bit) 19042.1165
Slack (Windows app desktop) MSQ 4.19.3 64-bit
Teams 1.4.00.22472 (64 bits)

**Comment by xclydes** [comment] 2021-08-30 23:07
I can confirm this is an issue related to Slack as I don't use Teams or Zoom, specifically after using their screensharing feature.
I don't think this is an issue with npp for two reasons.

1. It returns to normal once I relaunch npp with after closing slack without restarting.
2. I experience issues with virt-viewer whenever I use the Slack screen share feature.

Notepad++ v8.1.3
Windows 11 Enterprise - 22000.168 & Windows 10 (Laptop died)
Slack - Windows Store 4.18.0

**Comment by JohanEntur** [comment] 2021-09-03 11:35
I too confirm Slack as a potential source of the issue. I closed all running Slack processes and relaunched N++ and the sidepanels were gone. I did have some Slack calls today so that also matches. Starting Slack again does not disturb N++.

I believe there are some issues with Slack where sometimes there are processes that disrupt other applications, and even Slack itself. When in doubt, always look for the Slack-processes :)

Also, thanks Arkadisusz for connecting me to this issue. This solves it for me.

**Comment by mmadziamcx** [comment] 2021-09-10 13:48
My understanding of the problem is a bit of conjecture, but I am fairly confident in it. The issue is being triggered when a particular Windows API for screen capture is being invoked by an application. When the API is invoked, it is causing the npp app window to re-draw itself, and the internal UI panels in the npp app window are being redrawn with incorrect height/width/position values. I'm assuming there are probably multiple methods for capturing the display in Windows, so only screen-sharing apps using this particular API are triggering the problem.

This issue is independent of npp version, and the issue only started around March of this year. My assumption is that there was a Windows Update around this time that changed the screen capture API or the methods used in npp for drawing the UI panels. 

If this was a more widespread issue I think it would have been already identified or addressed from other applications. 
Ultimately I believe this means that npp is using a rarely used, deprecated, or unsupported method for drawing the UI panels in their app window that is no longer 100% compatible with the current version of Windows screen capture APIs.

**Comment by pryrt** [comment] 2021-09-23 13:44
Another: https://community.notepad-plus-plus.org/topic/21875/help-with-weird-startup-of-npp-showing-a-debug-window-and-broken-panels

**Comment by pryrt** [comment] 2021-09-27 15:26
another report https://community.notepad-plus-plus.org/post/70064, in the v8.1.5 release topic

**Comment by BOrnellas** [comment] 2021-10-08 15:44
I also have this issue however a "debug" window shows up when the application opens. And the issue is intermittent at best:
Debug Info:
Notepad++ v8.1.2 (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 2009
OS Build : 19042.1165
Current ANSI codepage : 1252
Plugins : AnalysePlugin.dll ComparePlugin.dll CsvQuery.dll DSpellCheck.dll HexEditor.dll HTMLTag.dll mimeTools.dll MusicPlayer.dll NppConverter.dll NppExport.dll NppFTP.dll QuickText.dll TakeNotes.dll XMLTools.dll

![image](https://user-images.githubusercontent.com/21068186/136585695-5dc06eca-4baf-4458-8350-ba0121a9ccd6.png)

**Comment by donho** [comment] 2021-10-21 00:12
@pryrt 

Thank you for your very detailed information.

>There is part of me that thinks it was a change on Microsoft's end in the March/April timeframe; this corresponds with the release of v7.9.4 and v7.9.5. And given that someone who had previously had it working, then upgraded to v7.9.5 and saw the problem, then downgraded back to v7.9.4 and still saw the problem, which makes me think that the OS update affected how Notepad++ GUI drawing occurs, rather than a change in the Notepad++ codebase. But the late-March timeframe was also when they started closing down things due to the pandemic in the US, so it's when a ton of people in the US started using all the screen-sharing video-conferencing apps.

I checked again on every single commit from v7.9.4 to v7.9.5 - there were only 2 modification about file open/save dialog on `notepad++.exe` binary:
https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master?after=0c2508d3d1264ae6cd96bda39d9a05163cb38f22+384&branch=master

So I really don't think it's the bug of Notepad++. Slack might be the culprit so I will install it on one of my PC, in order to reproduce it. 

Thank you again for all you have done on both Github repos and Notepad++ community forum.

**Comment by mmadziamcx** [comment] 2021-10-21 13:06
> So I really don't think it's the bug of Notepad++. Slack might be the culprit so I will install it on one of my PC, in order to reproduce it.

I can reproduce this issue consistently if needed @donho . Screen sharing in either Slack or another app I use called RingCentral Meetings (which is just a rebranded version of Zoom meetings) will trigger it for me.

My guess is that a windows update changed something in screen sharing APIs at the OS level. When screen sharing is started/stopped it causes a 'refresh' of the display. When that occurs the npp window is not redrawing itself correctly.

My further guess is that npp has some methods for rendering the application on screen that are either deprecated/unsupported, or just obscure, so it was overlooked by MS testing of the Windows update that started this whole mess.

**Comment by bitroniq** [comment] 2021-11-09 14:46
Same thing with latest version

![image](https://user-images.githubusercontent.com/1032724/140945626-dc736efb-9626-4049-bd02-353286f4f83b.png)

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19043 N/A Build 19043
```

**Comment by petenattress** [comment] 2021-11-17 14:58
I can also confirm that Slack is causing this issue for me. Closing Slack processes fixes the issue.

Windows version: `10.0.19041 Build 19041`
Display driver: `Intel(R) Iris(R) Plus Graphics 655`
Display driver version: `26.20.100.7372`

NPP debug info:

```Notepad++ v8.1.9.1   (64-bit)
Build time : Nov 13 2021 - 15:28:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.1288
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 
```

**Comment by donho** [comment] 2021-11-17 23:30
https://twitter.com/Notepad_plus/status/1461114260302573574

**Comment by bitroniq** [comment] 2021-11-21 19:27
@petenattress thank you for chasing this. It was sooo annoying for me for such a long time. I usually don't restart my Win10 Pro machine for 2 weeks (only when security upgrades are needed). And this issue was forcing me to reboot my machine.
Not only notepad++ was affected, but also zoom meetings.

**Comment by OranguTech** [comment] 2022-01-25 16:58
I too have/had the bug, mine with the extra debug window like @BOrnellas above. Quitting slack resolved the issue. (Subsequent launches with Slack running work fine.) Previously I had been using slack's screen sharing (specifically in "Huddles") extensively. 

Windows 10, 21H1

NPP 8.2.0/8.2.1
Slack 4.23.0 64 bit

Intel UHD 630, driver 30.0.101.1121

**Comment by Tydorius** [comment] 2022-01-27 15:49
I had the identical issue.

It occurred under my prior version this morning. I didn't think to grab the version name, as I went ahead and updated to the latest after not updating for 6+ months.

It still occurred after update, v8.1.9.3 64-bit.

This was after I remoted into the machine via Chrome Remote Desktop.

**Closing Slack and then restarting Notepad++ resolved the issue.**

I restarted Slack after the fact and then restarted Notepad++ again and there were no issues.

Slack version 4.23.0 64-bit.

**Comment by andrewjatnieks** [comment] 2022-02-02 20:24
> I think the Windows Updates were a red herring , it was the associated reboot that appeared to be clearing the issue temporarily.
> 
> I've now found the issue consistently happens after I use a web meeting app with screen sharing (RingCentral). I'm not sure if the problem is specific to this app, or more broadly any app that uses the same method for capturing screens. Either way, after every screenshare, npp stops rendering correctly until a reboot.
> 
> I asked a co-worker of mine who also uses the same app for screen share and he said he is having similar problems with npp rendering after using the app, and again a reboot clears the issue until he uses the screen sharing again.

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by dylandhall** [comment] 2022-02-24 07:32
I can confirm I was having this issue, reliably, until I closed slack. I have this issue semi-regularly and usually fix it by clicking the "x" in the corner of the side-panes.

**Comment by RonaldH** [comment] 2022-03-04 20:59
I can confirm I have the same issue with the latest Slack version (4.23.0) and latest Notepad++ version (v8.3.2) on Windows 11 (21H2 22000.527)

Uninstalling + Removing all settings of Notepad++ and then re-installing doesn't fix it.

Dragging the right side panel crashes notepad++

Restarting slack did fix it.

**Comment by senadjukic** [comment] 2022-03-22 15:33
> 

Same for me. Notepad++ v8.3.3 same behavior.

**Comment by OranguTech** [comment] 2022-03-22 16:16
One small thing to contribute, the Slack sharing  can reliably cause similar "random window/UI element re-aranging" issues w/ the F5 BigIP Edge Client.

Has anyone registered this issue w/ Slack?

**Comment by GrahamCP** [comment] 2022-03-25 02:42
> Has anyone registered this issue w/ Slack?

Today I sent an email to Slack feedback about this.

Today for the first time, I saw the strange behaviour in Notepad++ with panel alignment, as in the screenshot above:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717#issue-843501756

As others have noted, I fixed the problem by restarting Slack.

My system details:
- Surface Book
- Windows 10 Pro Version 21H2 (OS Build 19044.1586)
- Slack version: Production 4.24.0 64-bit
- Notepad++ v8.3.3 64-bit

Sequence of events:
1. Yesterday my laptop became unresponsive shortly after starting a Slack huddle. I was able to continue the audio discussion despite Windows not responding to the trackpad or keyboard.
1. I restarted Windows, started a new Slack huddle and shared a window (not screen). No apparent problems after the restart.
1. Laptop was closed (sleep mode), not powered off overnight.
1. Today after another huddle (no problems), I started Notepad++ and saw the strange UI behaviour.
1. I tried to quit Slack by right-clicking the Windows tray icon. But the popup menu showed up all black, then Slack was unresponsive. I used Task Manager to end the Slack process.

**Comment by GrahamCP** [comment] 2022-03-25 11:41
@OranguTech 

Someone on the Slack team replied to my email today, see below. This should be some comfort to people whose apps' UIs are awry.

> I'm afraid that you're running into a known bug on our end that the engineers are currently working on, wherein some apps malfunction after screen share and may also result in a frozen or crashed state. My apologies for this, I know it's not ideal. Moving forward, I've gone ahead and added this ticket to our internal tracker and we'll get in touch as soon as I hear of any updates.
> 
> In the meantime, as you've noted, the best workaround is to fully quit and restart Slack; that should alllow other apps to work as expected

**Comment by JohanEntur** [comment] 2022-03-25 11:53
I notified them last year: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717#issuecomment-912471331
I linked them to this thread.

**Comment by eliumoraes** [comment] 2022-07-19 21:07
I Had the same issue! Reading here found that was related to slack. I closed Notepad++ and closed slack using the Task Manager (there where multiple processes). Then opened Notepad++ and it did not had the problem.

**Comment by jstnlowe** [comment] 2022-07-21 17:23
Confirmed this on multiple Windows 10 machines w/ Slack and Notepad++ versions 8.3.3, 8.4.2, and 8.4.4. Killing all Slack processes and reopening NP++ and Slack resolved the issue (temporarily).

**Comment by jjj42** [comment] 2022-08-04 19:24
had the same error:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11978 
(notebook with ryzen 5000 apu and nvidia 3070 gpu, win11, latest updates.)

seems it was an issue of the windows explorer. (caused by...?)
letting the system run for some more hours, other programs (mpc-hc, open shell) started getting gui errors, too.
a restart cured the error.

**Comment by RonaldH** [comment] 2022-09-27 13:58
Seems slack has resolved this issue, I got this email a little while back, and I haven't had this issue anymore:

> Just emailing to let you know that the bug you raised with us, about when a window is selected for screen sharing, right-clicking the Slack icon in the taskbar notification area causes Slack to crash on Windows, back in March 2022 has been fixed.
> Please update to Slack version 4.28.171 to see this fix. If you are still seeing this issue please email us back so we can investigate this further.

**Comment by donho** [comment] 2023-01-17 18:34
@RonaldH 
That's a good news. 
Thank you for your confirmation!

**Closed by donho** 2023-01-17 18:34 UTC
