### ISSUE TITLE
Save dialog doesn't have access key shortcuts in v7.8.x

### ISSUE THREAD

**Issue by cganchev** [notepad-plus-plus/notepad-plus-plus#7691] opened 2019-12-04 02:37 UTC
### Description of the Issue
When you close a file which has been modified the Save dialog appears with the following buttons:
Yes, No, Cancel, Yes to all, No to all
Previously, it was possible to press the Y or N keys on the keyboard to quickly select the desired action, but this doesn't work anymore.
I often have a lot of untitled files and I close them one by one. My mouse cursor stays on the X button at the right end of the menu bar and I just press Y or N, but now I have to move my mouse for every single file. I don't need to save 90% of the untitled files.

### Steps to Reproduce the Issue

1. Open new file
2. Type something
3. Close the file

### Expected Behavior

Be able to press Y or N keys on the keyboard to select Yes or No.

### Actual Behavior

Nothing happens when you press Y or N, you need to click the button with the mouse.

**Comment by KoalaBear84** [comment] 2019-12-04 07:03
Yup, the workaround is revert to 7.7.1 and don't update:
https://notepad-plus-plus.org/downloads/v7.7.1/

**Comment by sasumner** [comment] 2019-12-04 12:55
Closing as duplicate of #6223

**Closed by sasumner** 2019-12-04 12:55 UTC
