### ISSUE TITLE
tabs lose synchrony with texts after messing with splitter

### ISSUE THREAD

**Issue by maemmott** [notepad-plus-plus/notepad-plus-plus#3914] opened 2017-11-23 11:47 UTC
### Description of the Issue
I commonly work with the 'other view' open (two panes side-by-side and a moveable divider running down between them).
Today, after revealing the left-hand view after a number of days working only with the right-hand view, the tab above the left-hand view didn't show the file-name for the content in the left-hand view.
This is more of a 'nuisance' than a 'disaster'.
It is, I suppose, possible that it is simply maintaining long-forgotten 'state' [in other words, I might have been hunting in the tabs (without selecting anything), before I shrunk down the left-hand pane, but that was so long ago that I don't remember it].
If that last interpretation is correct, this request might be a 'feature' request, to introduce a bias, to jump the tabs back to showing the one for the file on view, when one of the views ceases to be [hidden] 'unviewable' [why did I change this wording?  because I suspect 'hidden' might have a very particular meaning, and I suspect 'my not being able to read' a document is _not_ the same as it being 'hidden'].

### Steps to Reproduce the Issue

1. Recently, I focused on the right-hand side by clicking the <left-pointing-triangle> tool in the splitter.  And I've had notepad++ open and closed a few times, and it has retained this view configuration, over a few days, with hibernations, shutdowns-and-restarts, immediately before this bug 'event': return from hibernation.
2. Today, I had to work out how to get my 'side-by-side' view back.  I clicked on the <left-pointing-triangle> (in case it was a toggle).  I clicked on a <right-pointing-triangle> at the foot of the splitter: it swapped to 'the other view' (the left-hand side pane).  I looked in the menu.  Eventually I dragged the splitter back to approximately the middle ...
3. Then, I was confused:  in the left-hand pane was a todo-list of tasks, but in the single (of many) tab shown at the top, was a filename which wasn't my habitual 'todo-list' file name.  I didn't at first notice, but the tab was in the relatively-greyed-out state.  I cycled through the tabs, until I found the likely todo-list file name.  Then I noticed that that tab was emboldened (so, 'active').

### Expected Behavior

I expected a tab above the left-hand pane to show the file-name of the contents displayed in that pane.
### Actual Behavior

When the left-hand pane is revealed again, the tab chosen to display at the top doesn't match the content in the pane.
### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : NppTextFX.dll PluginManager.dll XMLTools.dll

**Comment by MetaChuh** [comment] 2019-04-11 21:59
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:59 UTC
