### ISSUE TITLE
Extend Documet List with filter like Function List

### ISSUE THREAD

**Issue by KlausiD** [notepad-plus-plus/notepad-plus-plus#10345] opened 2021-08-06 07:40 UTC
I use a lot of open files and therefore it is difficult to find a specific file in the document list.
My suggestion:
Extend Documet List with filter and a sort button like Function List.

**Comment by ArkadiuszMichalski** [comment] 2021-08-06 10:53
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7899.

**Closed by ArkadiuszMichalski** 2021-08-06 10:53 UTC
