### ISSUE TITLE
UDLs are not available when using cloud folder

### ISSUE THREAD

**Issue by rddim** [notepad-plus-plus/notepad-plus-plus#9715] opened 2021-03-28 18:23 UTC
### Description of the Issue

When I use a local folder for the cloud settings all the UDLs are not available in the `Language` menu.
### Steps to Reproduce the Issue

1. Download the latest fresh portable version of Notepad++
2. Create a new local folder for the cloud
3. Set the cloud location to that folder from `Settings` > `Preferences...` > `Cloud & Link` – in my case `\npp.7.9.5.portable.x64\_settings`
4. Restart Notepad++

### Expected Behavior

After step `4` I expect to see the custom UDL `Markdown (preinstalled)` available
### Actual Behavior

1. After step `4` click on the `Language` dropdown menu  – the `Markdown (preinstalled)` UDL is not available anymore.
2. Clicking `Open User Defined Language older...` from `Language` > `User Defined Language` do notning.
3. If I create a new UDL from `Language` > `User Defined Language` > `Define your language...` and restart Notepad++, the `userDefineLang.xml` file is available in the custom cloud folder and in the `Language` menu.
4. If I copy/move the `userDefineLangs` folder to the cloud folder everything is available and all works normal.
### Debug Information

```
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Users\Home\Downloads\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by ArkadiuszMichalski** [comment] 2021-03-28 21:18
Not duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8394?

**Closed** 2022-07-26 23:28 UTC
Labels: duplicate, udl
