### ISSUE TITLE
Notepad++ Macro doesn't process down button

### ISSUE THREAD

**Issue by JakeKoekemoer** [notepad-plus-plus/notepad-plus-plus#2553] opened 2016-11-09 06:40 UTC
I have written a Notepad++ Macro that will convert a SQL Query into a Vb string to paste into my VB code.

The principal is that you could just press Ctrl + Shift + E and the macro should convert the SQL line from something like SELECT a FROM b TO "SELECT a FROM b" & vbCrLf & _ and then the cursor should move to the next line.

This is what my Macro looks like:

<Macro name="VB Script" Ctrl="yes" Alt="no" Shift="yes" Key="69">
    <Action type="0" message="2453" wParam="0" lParam="0" sParam="" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam='&quot;' />
    <Action type="0" message="2451" wParam="0" lParam="0" sParam="" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam='&quot;' />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam=" " />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="&amp;" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam=" " />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="v" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="b" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="c" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="r" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="l" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="f" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam=" " />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="&amp;" />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam=" " />
    <Action type="1" message="2170" wParam="0" lParam="0" sParam="_" />
    <Action type="0" message="2300" wParam="0" lParam="0" sParam="" />
</Macro>
I have checked with a few different ways and determined that this line will move the cursor one line down:

<Action type="0" message="2300" wParam="0" lParam="0" sParam="" />

The problem is that only on the first line executes the entire macro and moves one line down. But any line after that it doesn't move down a line.

### Expected Behavior
I Expected the cursor to move down to the next line.

### Actual Behavior
The cursor doesnt move to the next line.

### How Did I resolve the issue:
Turning off Auto Complete could resolve the issue.

It would appear as though NotePad++ stops the execution of a Macro when the auto complete menu pops up.

IE: The Macro executes all the code as it would adding all the letters correctly. Then when it needs to activate the Down Arrow key it still executes the code, but on the dropdown that pops up as opposed to the line where the cursor is located.

My Entire stackoverflow discussion can be found here:
http://stackoverflow.com/questions/40481969/notepad-macro-doesnt-process-down-button/40501278

**Comment by dail8859** [comment] 2016-11-10 13:49
Duplicate of #2545

**Closed** 2016-11-12 16:22 UTC
