### ISSUE TITLE
Reload "Yes to all" option

### ISSUE THREAD

**Issue by akittino** [notepad-plus-plus/notepad-plus-plus#1484] opened 2016-02-16 21:55 UTC
When using GIT with switching between branches, I have many opened files in Notepad++.
After every switch, it asks one by one if I want to reload file. It would be useful to have "Yes to all" option there.

**Comment by emilioplatzer** [comment] 2016-07-27 18:42
+1

**Comment by Nightfirecat** [comment] 2016-08-04 17:59
Duplicate of #848?

**Comment by bbatt** [comment] 2018-11-08 14:33
Would love to see this as well.  It slows me down tremendously

![image](https://user-images.githubusercontent.com/2522397/48205016-f699a580-e330-11e8-8138-a06b46978f49.png)

**Comment by sasumner** [comment] 2018-11-08 14:37
@bbatt, Curious...how is `C:\Users\` a **_file_**...?

**Comment by bbatt** [comment] 2018-11-08 15:05
> @bbatt, Curious...how is `C:\Users\` a **_file_**...?

I hid the info.

**Comment by TeoTwawki** [comment] 2018-11-08 18:21
> Duplicate of #848?

Yes. And also of #1484  and (sort of) #2082 :cry:

This needs to happen.

**Comment by MetaChuh** [comment] 2019-04-18 02:19
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-18 02:19 UTC

**Comment by sasumner** [comment] 2019-10-15 12:09
Sort of a side note:  Notepad++ 7.8 adds the "No to All" and "Yes to All" functionality to the Save dialog, but not to the Reload dialog.
