### ISSUE TITLE
Document Map color is on other desktops

### ISSUE THREAD

**Issue by ManuelH95** [notepad-plus-plus/notepad-plus-plus#8215] opened 2020-05-05 10:25 UTC
### Description of the Issue

When you switch the desktop on Windows, the color from the Document Map stays.

### Steps to Reproduce the Issue

1. Activate Document Map
2. Switch the desktop
### Expected Behavior

Notepad++ should not shown

### Actual Behavior

The color of the Document Map persists
### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by dail8859** [comment] 2020-05-05 12:39
Duplicate of #5294 and others

**Closed** 2020-05-05 13:04 UTC
Labels: duplicate
