### ISSUE TITLE
DSpellCheck.dll

### ISSUE THREAD

**Issue by MrX-at-GitHub** [notepad-plus-plus/notepad-plus-plus#4241] opened 2018-02-28 00:02 UTC
Current DSpellCheck.dll version is 1.4.1 https://github.com/Predelnik/DSpellCheck/releases/tag/v1.4.1
You included iin notepad++ 7.5.5 an old version 1.3.5 which not works anymore when you try downloading a dictionary.

**Comment by donho** [comment] 2018-03-04 00:45
@Predelnik Do you confirm this issue in v1.3.5 ?

**Comment by Predelnik** [comment] 2018-03-04 07:43
@donho This is just a slight regression from 1.3.2 where it would not work for some people because I disabled passive mode for FTP. I could make 1.3.6 for that but I don't think it's that serious.

As for 1.4.x it would be nice to include this one eventually but I think thatit's better to wait at least for 1.4.2 where I will fix a couple of issues. I don't think it can't wait until next N++ release.

**Comment by dail8859** [comment] 2019-05-24 02:04
Closing since DSpellCheck is not included in the installer any more.

**Closed by dail8859** 2019-05-24 02:04 UTC
