### ISSUE TITLE
Feature request: Show finding results on scrollbar too

### ISSUE THREAD

**Issue by CraftedRO** [notepad-plus-plus/notepad-plus-plus#12262] opened 2022-09-30 10:02 UTC
### Description of the Issue

Woud be nice if notepad++ woud have this feature so after you search in a file , scrollbar to be highligted where the results are.
Something like :

![sqsq](https://user-images.githubusercontent.com/24683355/193246355-e2d90454-aa0f-4b29-a86b-f1e9e22566c0.PNG)

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior
When you find

**Comment by ArkadiuszMichalski** [comment] 2022-09-30 10:34
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3116.

**Closed by ArkadiuszMichalski** 2022-09-30 10:34 UTC
