### ISSUE TITLE
Changing Timezones is generating a popup that the file has been modified.

### ISSUE THREAD

**Issue by D3niz** [notepad-plus-plus/notepad-plus-plus#3969] opened 2017-12-07 03:01 UTC
### Description of the Issue
With Notepad++ open and any file open, changing the computers timezone then gives a warning in Notepad++ with a popup "This file has been modified by another program, Do you want to reload it and lose the changes made in Notepad++?" or "This file has been modified by another program, Do you want to reload it"

This becomes annoying since it hasn't been changed and the time hasn't changed (still the same time UTC) only the time zone has changed.

### Steps to Reproduce the Issue
1.  Change your computer Timezone, e.g. set to +10
2.  Open notepad++ and any text file (the file needs to be saved, not just new file within notepad++)
3.  Change the Timezone to UTC
4.  go back to notepad++
4.  this pop up comes up "This file has been modified by another program, Do you want to reload it and lose the changes made in Notepad++?" or "This file has been modified by another program, Do you want to reload it"

### Expected Behavior
Don't display pop up if it is just a timezone change and the file hasn't been modified.
Haven't looked at code but I guess it should be always looking at the UTC time so it is consistent and timezone changes become irrelevant.

### Debug Information
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment] 2017-12-07 12:19
Duplicate of #2535, #215

**Closed** 2018-06-24 22:36 UTC
