### ISSUE TITLE
comments and keywords are same color on Deep Black ;Mono Industrial ; Monokai ; Plastic Code Wrap themes

### ISSUE THREAD

**Issue by nadeesh19** [notepad-plus-plus/notepad-plus-plus#2218] opened 2016-08-27 18:49 UTC
### Description of the Issue

if we use pascal language with Deep Black theme ,we can't identify clearly comments and key words of pascal. 
### Steps to Reproduce the Issue

1. open Notepad++ V 6.9.2 on windows 10
2. change theme in the style configurator as  Deep Black ;
3. then we can see , key words and comments are same color 
4. this is happening in Mono Industrial ; Monokai ; Plastic Code Wrap themes also.

### Expected Behavior

the color of key words and comments color must be different . 
### Actual Behavior

the color of key words and comments colors are same on  Deep Black ;Mono Industrial ; Monokai ; Plastic Code Wrap themes.

![deepblacktheme](https://cloud.githubusercontent.com/assets/10229154/18029395/b0c89f7e-6cb4-11e6-8bab-d8d6b3972a7e.png)
![monoindustrial](https://cloud.githubusercontent.com/assets/10229154/18029397/b0d79204-6cb4-11e6-883d-5a7f5e287f7f.png)
![monokaitheme](https://cloud.githubusercontent.com/assets/10229154/18029396/b0d65cb8-6cb4-11e6-8fb6-d9610f2f3f70.png)
![plasticcodewraptheme](https://cloud.githubusercontent.com/assets/10229154/18029398/b1f030f6-6cb4-11e6-9dd5-2827ed5dc896.png)

**Comment by dail8859** [comment] 2016-08-27 20:49
PR #1912 has fixed the issue and will be in the next release of N++.

Duplicate of #249, #2204

**Closed by dail8859** 2016-08-27 20:49 UTC
Labels: duplicate
