### ISSUE TITLE
Darkmode: tabs not readable after changing theme

### ISSUE THREAD

**Issue by skeets23** [notepad-plus-plus/notepad-plus-plus#10153] opened 2021-07-14 07:35 UTC
### Description of the Issue
![14_16-31-784x62-c96dbd1d515 1](https://user-images.githubusercontent.com/13846271/125581761-5230ca84-0822-4abe-9f76-ca7c49bd4a76.png)

### Steps to Reproduce the Issue

1. Enable dark mode
2. Change theme to "Solarized"
3. Have multiple tabs open

### Expected Behavior
The theme shouldn't have any effect on the tab text color, since it doesn't have any effect on the tab background color.

### Actual Behavior
The theme had an effect on the tab text color (making it unreadable)

### Debug Information
Notepad++ v8.1.1   (32-bit)
Build time : Jul  1 2021 - 14:04:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1083
Current ANSI codepage : 932
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rasyidf** [comment] 2021-07-14 13:35
Have you restarted the app?

**Comment by ozone10** [comment] 2021-07-14 14:24
There seems to be issue with how dark mode modify text color,
but you can always change inactive tab text color
![image](https://user-images.githubusercontent.com/55940305/125638473-12ec20b9-bc06-4266-a791-d492eecddac0.png)

**Comment by tinsel-grumble** [comment] 2021-08-11 16:29
@ozone10 will this be official fixed in new release so it not user problem?

**Comment by ozone10** [comment] 2021-08-13 18:15
@tinsel-grumble 
I have not looked into it yet, as I am quite busy now.

Maybe @adzm can give more info.

**Comment by adzm** [comment] 2021-08-14 22:08
Unfortunately we'd have to either add an option to ignore the tab text color, override it, add alternative colors or theme parts for dark mode, or implement some sort of contrast detection and invert lightness automatically.

**Comment by tinsel-grumble** [comment] 2021-08-15 15:38
@adzm how not caught before release? seem big bug with access/use issue for user. should be part of dark mode otherwise dark mode useless as option.

**Comment by adzm** [comment] 2021-08-16 06:27
Originally I thought I had the tab colors hard coded in dark mode, ignoring
the theme. I think this might have changed afterwards. Regardless it's
worth looking into. Also of concern to me are styles that just don't work
right with dark backgrounds like the markdown one for example.

**Comment by tinsel-grumble** [comment] 2021-08-22 18:07
the md style is also broke in light mode if using solarized dark. nothing to do with ui for that separate issue

**Comment by Hashbrown777** [comment] 2022-09-30 03:56
> Unfortunately we'd have to either add an option to ignore the tab text color, override it, add alternative colors or theme parts for dark mode, or implement some sort of contrast detection and invert lightness automatically.

Actually it looks like the issue isn't so much the text colour and what NP++ does with it in dark mode, but that it's inverting the foreground colour AND ignoring the background colour.
Whichever dark mode does, use as-is, invert, or ignore the tab colour style setting; it should do it to BOTH fore- and background settings to avoid these issues.

With invert or as-is any glaring dark-mode/style visual clashes can be fixed in the Style Configurator, but the contrast itself will always be legible by default (just as they are in light mode).

**Closed** 2022-11-22 00:59 UTC
Labels: dark mode
