### ISSUE TITLE
Updates to the Deep Black theme

### ISSUE THREAD

**Issue by FarmGeek4Life** [notepad-plus-plus/notepad-plus-plus#1234] opened 2015-12-08 06:29 UTC
I want to get powershell syntax highlight support added to the Deep Black theme. I have part of the list from stylers.model.xml converted, but not the newest additions.
Also, the yaml coloring is a direct copy from stylers.model.xml, and needs to be converted (I don't use yaml, so probably not the person to change it).

I would also like to alphabetize the list of languages in the theme, but it appears that it will not be allowed (makes for a difficult pull request, since git doesn't do text moves); just annoying to find and change something in it right now.

**Comment by dail8859** [comment] 2015-12-08 17:55
There are actually quite a few styles (and even languages) missing in the non-default themes. I was looking into updating the styles programmatically (somehow) but that's not very straight-forward, and making something look "appealing" is not my forte.

**Comment by FarmGeek4Life** [comment] 2015-12-09 20:29
doing it programmatically would be easier if all of the changes from one font style and color to another were the same in a style, but even that isn't true; you would end up needing to have matching preferences for each language to other languages.

**Comment by MetaChuh** [comment] 2019-04-11 00:43
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:43 UTC
