### ISSUE TITLE
Notepad++ is not checking valid Regex text except for the Find next option feature.

### ISSUE THREAD

**Issue by abdulbadii** [notepad-plus-plus/notepad-plus-plus#8043] opened 2020-03-16 04:33 UTC
Notepad++ is not checking Regex validity on every search feature/option, except for checking the Find next option only.

How to help this to have important safety net for valid regex, esp. when doing Find in Files and every bulky, massive find/replace processing ?

**Comment by sasumner** [comment] 2020-03-16 10:54
Closing as duplicate of #6043

**Closed by sasumner** 2020-03-16 10:54 UTC
