### ISSUE TITLE
Session.xml emptied with Windows upgrade while PC left in Sleep mode with Notepad++ open

### ISSUE THREAD

**Issue by mpopejoy-dxc** [notepad-plus-plus/notepad-plus-plus#12389] opened 2022-10-24 06:05 UTC
### Description of the Issue
"Lost" my session during Windows updates that occurred when I left my PC in Sleep mode with Notepad++ (and other apps) open.

### Steps to Reproduce the Issue
1. Notepad++ open with dozens of open files (other apps also left open)
2. Windows -> Power -> Power -> Sleep
3. (me -> bed -> sleep)
4. (some hours later) Windows installed 2022-10 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5018410)
5. Powered on/woke up PC

### Expected Behavior
(Before knowing that a Windows update had occurred, I expected...) all apps and windows to be open and on the monitor (of 3) that I left them on - including Notepad++ with all the files I had open.
(Since a Windows update did occur, I'd expect...) have to log in to a fresh Windows session and potentially get a complaint from some Office apps that I hadn't saved or shut down properly. Upon opening Notepad++, I'd expect all the files I had open to be open.

### Actual Behavior
Windows re-logged me in and reopened all the windows and apps I had opened (Firefox - 2 windows, multiple tabs in main one, Chrome, Outlook - 3 folders and an open popped-out message, Teams, etc.)
Don't remember if Notepad++ was open with just new1 file or if it wasn't open so I launched it, then seeing only new1 file.

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\<maskedFolderName>\Notepad++\notepad++.exe
Command Line : "C:\<maskedFolderName>\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : C:\Users\<maskedUsername>\Dropbox
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Note: one posting I found indicated that reinstalling N++, but not deinstalling, solved their issue. Even though I didn't expect it to help, I tried that. That was before capturing the debug info above.

I found nppLogNulContentCorruptionIssue.log in Cloud Config folder with timestamp of Windows upgrade  so I know what time session.xml was overwritten with 193 bytes instead of the previous 374907. File attached.
[nppLogNulContentCorruptionIssue.log](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9849117/nppLogNulContentCorruptionIssue.log)

**Comment by xomx** [comment] 2022-10-24 17:50
Thanks for the log and sorry for the session lost.
Probably the same as the #9850 .

**Comment by ArkadiuszMichalski** [comment] 2022-10-28 09:56
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9850.

**Closed by ArkadiuszMichalski** 2022-10-28 09:56 UTC

**Comment by donho** [comment] 2022-11-01 13:46
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26
