### ISSUE TITLE
If some files was changed or deleted return to just opened file after all dialogs

### ISSUE THREAD

**Issue by CoruNethron** [notepad-plus-plus/notepad-plus-plus#2577] opened 2016-11-18 02:47 UTC
### Description of the Issue

If open any file, but one of the already opened files is changed or deleted - then focus will not be on just opened file tab.

### Steps to Reproduce the Issue
1. Open some files, say: 1.txt, 2.txt, 3.txt
2. Minimize NP++
3. Change file 2.txt in another software
4. Delete file 3.txt
5. Open file 4.txt, using context-menu in file manager

### Expected Behavior
After answering all dialogs about changed or deleted files - the last one opened file tab is in focus. I.e. tab with 4.txt is in focus and ready for work.

### Actual Behavior
The tab with one of changed files is in focus.
In case, that we have dozens of files opened, and for example, some of them updated with SVN or GIT, then we may have to scroll right to search just opened file, it's little-bit annoying.

**Comment by 42degrees** [comment] 2018-10-12 20:05
This is a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)

**Comment by MetaChuh** [comment] 2019-04-24 19:30
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-24 19:30 UTC
