### ISSUE TITLE
Find in Files - File is too big Messages annoy the User

### ISSUE THREAD

**Issue by Regda** [notepad-plus-plus/notepad-plus-plus#2154] opened 2016-08-08 21:36 UTC
### Description of the Issue

The "File open problem" Infobox with the Text "File is too big to be opened by Notepad++" pops up every time if notepad trys to open a file which is too huge by searching into multiple files.
The Problem is that the User need to click on "OK" every time it happens.
### Steps to Reproduce the Issue
1. Use "Find in Files"
2. Search an entire folder with files that are to large for notepad++ (2gb-3gb)
### Expected Behavior

Using another error handling that logs the files which can't be opend instead of forcing the user to click on an OK button.
### Actual Behavior

The same error handling as for opening files through the user is used.

**Comment by dail8859** [comment] 2016-08-09 12:47
Duplicate of #1889

**Comment by donho** [comment] 2023-09-01 15:41
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf8ddc18c9833fb8f19df1c44dc769926a274d47

**Closed by donho** 2023-09-01 15:41 UTC
Labels: duplicate
