### ISSUE TITLE
Group Tabs

### ISSUE THREAD

**Issue by KevinKrueger** [notepad-plus-plus/notepad-plus-plus#15515] opened 2024-08-05 08:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

-

### Describe the solution you'd like.

You can select your tabs with CTRL + Shift (hold down).
Once they are selected, you can use CTRL + G to create a group and give it a name.
Or you can right-click on a selected tab to create and name a group.

The group can also be folded out and folded in.
And you can drag and drop a tab into a group.

### Debug Information

```shell
-
```

### Anything else?

-

**Comment by alankilborn** [comment] 2024-08-07 19:00
Seems like rather than "closed as completed" this should be "closed as rejected".

**Closed** 2024-08-07 19:44 UTC

**Comment by ArkadiuszMichalski** [comment] 2024-08-08 00:49
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9517.
