### ISSUE TITLE
Renaming a file while "save as"

### ISSUE THREAD

**Issue by benobro7** [notepad-plus-plus/notepad-plus-plus#4957] opened 2018-10-24 15:13 UTC
### Description of the Issue
I happened to have issues when doing a "save as" of a new and unsaved document, and while i have the "save as" window open, i renamed another document, then i loose some unsaved documents, and some saved ones end up mixed up between each other.

### Steps to Reproduce the Issue
It happened few times already, but i can't seem to find the exact behavior to make it happen again when i want to.
It seems like :
1. I have a bunch of documents open in notepad++.
2. Some saved ones, some unsaved.
3. The document i will rename through the "save as" window is also opened in notepad++
4. When i save one of my unsaved document and do as stated in 3. it works fine, i save my txt into a new file, rename the other
5. close the save as window, goes back to notepad++ and i get prompted to save all my unsaved documents as well as the renamed one
6. at times i will loose at least one of the file on my opened docs, and some might be mixed up, as if it overwrites one to the other

It's a little complicated to explain with words, and i hope my description is clear enough to make sense...

All the best
-ben

**Comment by MetaChuh** [comment] 2019-04-11 22:37
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 22:37 UTC
