### ISSUE TITLE
Command Line Arguments Dialog box moves under window when navigating away from menu bar

### ISSUE THREAD

**Issue by alallier** [notepad-plus-plus/notepad-plus-plus#4422] opened 2018-04-17 18:19 UTC
Command Line Arguments Dialog box moves under window when navigating away from menu bar

### Steps to Reproduce the Issue

1. Click question mark
2. Select Command Line Arguments...
3. Move mouse off menu bar

### Expected Behavior
Dialog box stays on top of window

### Actual Behavior
Dialog box goes under window when mouse navigates away from menu bar

![notepadplusplus](https://user-images.githubusercontent.com/13004518/38888609-2c6bc586-424a-11e8-8a93-c1297da4aa22.gif)

**Comment by dail8859** [comment] 2018-04-17 22:27
Duplicate of #4067

**Comment by ArkadiuszMichalski** [comment] 2020-09-23 23:57
@donho was fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6027.

**Closed** 2020-09-24 13:18 UTC
