### ISSUE TITLE
Folder as Workspace panel reverts background theme when opening windows file explorer

### ISSUE THREAD

**Issue by Waffle3z** [notepad-plus-plus/notepad-plus-plus#8980] opened 2020-10-08 17:48 UTC
I'm using a dark theme. When I open file explorer, the "Folder as Workspace" background turns white.
![image](https://user-images.githubusercontent.com/4744353/95494665-3f6a9680-096c-11eb-8525-c90f2a5d330a.png)
![image](https://user-images.githubusercontent.com/4744353/95494694-472a3b00-096c-11eb-8cca-b39004517adc.png)
Dragging the right resize handle to hide and then unhide the window makes it dark again.
![image](https://user-images.githubusercontent.com/4744353/95495054-da637080-096c-11eb-86da-6cfa52a37cf6.png)

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 19:10
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2937 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5980.

**Closed** 2021-12-14 01:59 UTC
Labels: duplicate
