### ISSUE TITLE
[BUG] Iconlist::AddIcon

### ISSUE THREAD

**Issue by Gerundive** [notepad-plus-plus/notepad-plus-plus#15553] opened 2024-08-15 21:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When starting 8.6.9 on Windows 7 I get this message (see attached jpeg) and it fails to start
![npp 8 6 9_bug](https://github.com/user-attachments/assets/449822ab-52fe-402c-b182-f917d1096154)

### Steps To Reproduce

Starting Notepad++ 8.6.9

### Current Behavior

8.6.9 doesn't work for me, so continue to use 8.6.6

### Expected Behavior

8.6.9 to work on my old 32bit Windows 7

### Debug Information

```shell
Notepad++ 8.6.9 32-bit
```

### Anything else?

![image](https://github.com/user-attachments/assets/a8435982-c424-470f-8445-687bc73258b9)

**Comment by ozone10** [comment] 2024-08-25 08:10
duplicate of #15406
you could reopen it, instead of creating new issue.
Could you check that you have `IconCodecService.dll`
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15313#issuecomment-2248493059

**Comment by donho** [comment] 2024-08-30 13:54
@Gerundive 
Could you reply the question of @ozone10 to help us to identify the problem?
Otherwise, we cannot help you to solve your issue.

**Comment by donho** [comment] 2024-09-02 00:56
With no reply from the issue opener, the issue is closed.

**Closed by donho** 2024-09-02 00:56 UTC

**Comment by Gerundive** [comment] 2024-09-05 15:50
This is the reply I sent on 25th August, & 31st August:

Yes I have IconCodecService.dll  version 6.1.7600.16385
dated 14-July-2009 02:41
Windows 7

**Comment by ozone10** [comment] 2024-09-10 15:28
@Gerundive 
>This is the reply I sent on 25th August, & 31st August:

there are no replies from both days, or I have not found them.

Could you test if large or extra large icons are showing for you in explorer.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15313#issuecomment-2323226143

Could you also try to install latest [Visual C++ Redistributable](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version)

[direct link](https://aka.ms/vs/17/release/vc_redist.x86.exe)

**Comment by Gerundive** [comment] 2024-09-14 11:31
Icon size is 72

I applied the Visual C++ fix which made no difference

**Comment by pryrt** [comment] 2024-12-03 21:38
@Gerundive ,

I was originally going to reply in the [v8.7.3 Announcement](https://community.notepad-plus-plus.org/topic/26420/notepad-release-v8-7-3/6) until @xomx pointed to this Issue.

Earlier in this Issue, you stated that you had `IconCodecService.dll` ... but when I was researching a reply for the Community, I noticed [this comment in another similar issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15465#issuecomment-2317937421), where \@solo16 was able to fix their problem using [SysInternals AutoRuns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) to make sure that the DLL is enabled during startup.  You might want to try the same thing, and see if it fixes it for you.

**Comment by Gerundive** [comment] 2024-12-06 22:04
I have iconcodecservice.dll in C:\Windows\system32  version  6.1.7600.16385

It is not running and is not present either in task scheduler and services
nor disabled or enabled in services.

How do I run it please, I've tried registering it and get the message:
Entry-point DllRegisterServer was not found.
