### ISSUE TITLE
Moving text with keyboard shortcurts introduces garbage

### ISSUE THREAD

**Issue by bersbersbers** [notepad-plus-plus/notepad-plus-plus#2928] opened 2017-02-20 13:29 UTC
### Steps to Reproduce the Issue
1. Open the attached file ([Input.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/787542/Input.txt))
2. Enable word wrap, if you haven't
3. Make sure the file's second line is long enough to wrap; decrease the window's width if necessary.
4. Highlight the last "Y" in the second line (by mouse, Shift+Arrow-Left/Right, ...)
5. Hold Alt, Hold Shift, Press Arrow-Up, Release Everything
6. Hold Ctrl, Hold Shift, Press Arrow-Up, Release Everything

### Expected Behavior
I had expected line 2 to move in front of line 1.

### Actual Behavior
Part of line 2, and garbage, is moved in front of line 1 ([Output.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/787541/Output.txt))

### Debug Information
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\NotePad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by dail8859** [comment] 2017-02-21 20:58
Duplicate of #2007

**Comment by dail8859** [comment] 2019-05-23 15:14
The text corruption is fixed in Notepad v7.7 since it upgraded to a new version of Scintilla.

*Please note*: The fix does not give you the expected results of moving the lines (it simply just doesn't work with a rectangular selection)...this is something that would need addressed by the Scintilla project.

**Closed by dail8859** 2019-05-23 15:14 UTC
Labels: bug, verified

**Comment by bersbersbers** [comment] 2019-05-23 15:31
Sad to see that moving blocks is not possible any more (the example in #2007 seem to work fine except for added garbage), but better no feature than a bad feature :)

**Comment by dail8859** [comment] 2019-05-23 15:33
@bersbersbers Fully agree.
