### ISSUE TITLE
Word wrap occurs even if beginning of line is just whitespace

### ISSUE THREAD

**Issue by mylittleplaceholder** [notepad-plus-plus/notepad-plus-plus#10703] opened 2021-10-21 18:24 UTC
### Description of the Issue

If a line contains a long text string (such as a URL) that has whitespace in front of it, the text string will be wrapped to the next line (but still indented), making it look like there's an extra blank line.

### Steps to Reproduce the Issue

```
Example entry:
  http://www.example.com/very/long/path/here/will/wrap.pl
```
### Expected Behavior

It should split/wrap as normal except not when there's just whitespace left on the line.

### Actual Behavior

The initial whitespace is left behind but then wrapped as expected:
```
Example entry:
  <- original whitespace left behind
  http://www.example.com/ver
  y/long/path/here/will/wrap.pl
```

### Debug Information

Notepad++ v8.1.5   (32-bit)
Build time : Sep 26 2021 - 15:15:32
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll ElasticTabstops.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NppTextFX.dll 

![Example_wrap](https://user-images.githubusercontent.com/13429856/138335328-96c0d853-c386-4a26-b30b-4037a2cf2323.png)

**Comment by ArkadiuszMichalski** [comment] 2022-01-10 06:38
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5625.

**Closed by ArkadiuszMichalski** 2022-01-10 06:38 UTC
