### ISSUE TITLE
Add ability to 'pin' recent used files

### ISSUE THREAD

**Issue by federicoalvarez-github** [notepad-plus-plus/notepad-plus-plus#3244] opened 2017-05-04 15:20 UTC
if you go to "file" menu, you see your last opened files.

it would be nice to be able to pin some of them.

For exmaple: every once in a while I have to edit the 'hosts' file in my Windows. Maybe every 30 days or so. In this time, the 'hosts' file has been pushed off that list because I opened others, so I have to go to Windows Explorer, C:, Windows, System, etc, drivers, and then double click that file. If it was pinned in the recents list that would not be necesary.

Hope you find this useful too!

Best regards and congratulations on such a good tool!

Federico.

**Comment by dail8859** [comment] 2021-12-23 23:54
Closing as this is a duplicate of #3362 which has now also been closed.

**Comment by donho** [comment] 2024-11-21 19:59
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0

**Closed by donho** 2024-11-21 19:59 UTC
