### ISSUE TITLE
Document Map still visible when switching desktops in Windows 10

### ISSUE THREAD

**Issue by UrbanKocmut** [notepad-plus-plus/notepad-plus-plus#4740] opened 2018-08-04 18:39 UTC
### Description of the Issue

When I have Notepad++ open and I switch desktops in Windows 10 the "Document Map" is still visible on the other desktop. It is in the same position that it was on the previous desktop.
### Steps to Reproduce the Issue

1. Open notepad++ with visible document map
2. Switch to another desktop
3. 

### Expected Behavior

The document map is not visible on other desktops

### Actual Behavior

The document map is visible on other desktops
### Debug Information

Notepad++ v7.5.8   (32-bit)
Build time : Jul 23 2018 - 02:03:53
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : PluginManager.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![slika](https://user-images.githubusercontent.com/22871708/43679493-328facac-9826-11e8-8f4b-13fa07deabb0.png)

![slika](https://user-images.githubusercontent.com/22871708/43679502-5c503110-9826-11e8-98c8-a88a0994d0d0.png)

**Comment by CookiePLMonster** [comment] 2018-09-02 10:37
Duplicate of #1247, #2840, #4549

Related to #440, #1317, #2763, #3612

**Comment by chcg** [comment] 2018-11-24 21:02
Please check/contribute to #1247

**Closed by chcg** 2018-11-24 21:02 UTC
Labels: duplicate
