### ISSUE TITLE
Scroll and cursor position lost

### ISSUE THREAD

**Issue by bernard01** [notepad-plus-plus/notepad-plus-plus#4881] opened 2018-09-26 17:16 UTC
I edit a dozen of raw text files, with word wrap turned on. I switch between them back and forth using [Ctrl+Tab].

The files are small, each only 2 pages.

I expect that each file / tab maintains its scroll and cursor position. However that is not the case. Both are lost.

For some time, that is perhaps ok, and most users perhaps can't be bothered reporting this.

It gets really annoying and impossible to work with when a problem becomes complex and requires strong focus with a stable view.

The problem most often occurs at the bottom third of the page where the content becomes hidden because the page just scrolls back to the top.  I can reproduce the problem each time.

**Comment by sasumner** [comment] 2018-09-26 17:39
Possible duplicate of #4825 and probably others; please search open issues before creating new (better to add new or slightly different info to an open issue)

**Closed** 2020-01-06 09:29 UTC
