### ISSUE TITLE
Feature: Add a "CSS (embedded)" Language to the Style Configurator

### ISSUE THREAD

**Issue by webvia** [notepad-plus-plus/notepad-plus-plus#12774] opened 2023-01-07 19:10 UTC
Add a "CSS (embedded)" Language to the Style Configurator

**Comment by ArkadiuszMichalski** [comment] 2023-01-08 18:44
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5663.

**Closed by ArkadiuszMichalski** 2023-01-08 18:44 UTC
