### ISSUE TITLE
@donho Porting Notepad++ as UWP on Microsoft Store

### ISSUE THREAD

**Issue by duble0** [notepad-plus-plus/notepad-plus-plus#3221] opened 2017-04-28 07:49 UTC
Hi! @donho !
I'm Francesco Venuti and I founded UWP Open Source Community, I already tried to contact you, also on facebook, about UWP, so let me explain better ...
First to start I would clarify that we are a team of Windows lovers and developers without any scope of make money. We would only improve our OS ...
As first analysis we must consider the direction that could take computing in the next years: Windows will be released for ARM SoC, this mean that you could have a pc experience on a ultra mobile devices. Nowadays Microsoft with Continuum and Samsung with DeX showed that you could connect a smartphone to a display and use apps comfortably. But Microsoft on December event, showed that with Windows O ARM you could run software like Photoshop on mobile devices simply converting it in app with project Centennial, this allow run full software packaged inside a UWP app.
This operation transform the concept of software, adding to them simplicity and confort to the user. A software converted in UWP use a virtualized Registry and File System, so not spread files around PC that cause a general degradation of OS. Furthermore install and uninstall is easy, the developer could use telemetry for the app that report about what are problems and after correct it all app already installed will be update automatically. In other if there is a bug or malware in your software it can't compromise the OS because UWP run sandoboxed. Remember that  software converted in UWP could run on every normal Windows 10 PC, so you can change also your distribution method for take the advantages that I wrote.
In our opinion youngers users can easily discover your projects and addressed to the community support, so after could start become developers.
Furthermore distributing your software as UWP mean that your software run in a sandbox that don't compromise the OS if there are problems.

We tried the online tool made by Microsoft for convert win32 software to UWP app, if you would use our work to start your experience on Microsoft Store we are pleased to give you all materials and information.
Or if you prefer we can also publish for you. 
For us is important convert a large amount of open source softwares to be available for every one.
Let me know your intentions.
Scuse me for poor English an thank you you ...😉

**Comment by kristian-b** [comment] 2017-05-01 13:05
Notepad++ in the Windows Store would be great!

**Comment by donho** [comment] 2017-05-01 15:04
@duble0
> I'm Francesco Venuti and I founded UWP Open Source Community

Could you provide me the URL of uwp community that you have created ?

**Comment by duble0** [comment] 2017-05-02 22:18
I Don Ho,

This is the link: UWP-Open-Source-Community , as you can see, we had already made the porting with project Centennial. We prefer if you directly take care of publishing it because you can well support the development. But if you prefere we can do it for you or we can collaborate with you to do this porting.

If you would try our converted app, go here: github.com/UWP-Open-Source-Community/NotepadPlusPlusyou and download Notepad++.appx, auto-generated.pfx and auto-generated.cer

On w10 PC go to the settings > for developers > activate developer mode  -  in App and function allow apps from other sources
Install “auto-generated.pfx” > when is request a path, choose “auto-generated.cer” > and go on
You can now install appx > simply click “Notepad++.appx” and install.

We have a Telegram chat where Notepad++ was voted as one of the most interesting program to port on MS Store,

I hope that you are interested, let me know.

Have a nice day.

Francesco

Inviato da Posta per Windows 10

Da: Don HO
Inviato: lunedì 1 maggio 2017 17:04
A: notepad-plus-plus/notepad-plus-plus
Cc: duble0; Mention
Oggetto: Re: [notepad-plus-plus/notepad-plus-plus] @donho Porting Notepad++ asUWP on Microsoft Store (#3221)

@duble0
I'm Francesco Venuti and I founded UWP Open Source Community
Could you provide me the URL of uwp community that you have created ?

**Comment by duble0** [comment] 2017-05-02 22:23
I @donho ,

This is the link: [https://github.com/UWP-Open-Source-Community](url) , as you can see, we had already made the porting with project Centennial. We prefer if you directly take care of publishing it because you can well support the development. But if you prefere we can do it for you or we can collaborate with you to do this porting.

If you would try our converted app, go here: [github.com/UWP-Open-Source-Community/NotepadPlusPlusyou](url) and download Notepad++.appx, auto-generated.pfx and auto-generated.cer

On w10 PC go to the settings > for developers > activate developer mode  -  in App and function allow apps from other sources
Install “auto-generated.pfx” > when is request a path, choose “auto-generated.cer” > and go on
You can now install appx > simply click “Notepad++.appx” and install.

We have a Telegram chat where Notepad++ was voted as one of the most interesting program to port on MS Store,

I hope that you are interested, let me know.

Have a nice day.

Francesco

**Comment by strollingHeifer** [comment] 2017-05-08 09:11
This seems like a duplicate of issue #1896. Nonetheless, it would be great to see Notepad++ make its way to the Windows Store.

**Comment by duble0** [comment] 2017-05-08 09:36
@strollingHeifer 
Not exactly a duplicate, we offer our collaboration or directly the Notepad++.appx ready for the Store ;-)  , anyway we are in touch with @donho that he'll take care to do this porting.
We apreciating the energy inside open source movement, we already contacted Inkscape team to do the porting, and saturday they published on the MS Store:
https://www.microsoft.com/en-us/store/p/inkscape/9pd9bhglfc7h
So we hope to see soon also Ntepad++...we have a lot of requests about!

**Comment by xjamesb** [comment] 2017-07-22 15:33
I run the IT for a school and the Windows store will become the main way that school IT managers distribute software. Microsoft give us a Private Store free of charge and it is simple as me enabling our staff and pupils to download and install the software.

Putting Notepad++ in the Windows Store will be of great benefit to pupils and staff. Please do it as soon as you can.

**Comment by donho** [comment] 2017-07-22 19:03
I hear you :)

**Comment by raaomoka** [comment] 2017-08-05 19:10
Awesome! Really looking forward to getting this amazing software via the Windows Store 😁

**Comment by duble0** [comment] 2017-08-09 12:01
Hi Donho I know that you did progress with conversion, the publication on Store is near?thank you!

**Comment by donho** [comment] 2017-11-04 13:18
This task has been blocked, here is the further information:
https://notepad-plus-plus.org/community/topic/14734/notepad-uwp-package-in-windows-store-almost-there

Any idea is welcome.

**Comment by MetaChuh** [comment] 2019-05-05 09:24
as the available [unofficial notepad++ release](https://github.com/NightRi-se/notepad-plus-plus) at the microsoft store has unresolved issues, which do not happen at the regular installed versions, we will currently not pursue dealing with the same problems.

maybe some day in the future, but not now and not on demand.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-05 09:24 UTC
Labels: wontfix
