### ISSUE TITLE
[Feature Request] Column Mode Editing Behavior

### ISSUE THREAD

**Issue by NPPPFreak** [notepad-plus-plus/notepad-plus-plus#1414] opened 2016-01-27 01:52 UTC
To whom it may concern,

I have two feature requests for the functionality of column mode editing.

It would be nice if when you hold ALT, arrow keys worked for selection. It only appears to work with mouse drag at the moment.

Also, pressing enter only carries the first line down, it should IMO insert an enter per line, ie:

aaabbbccc
aaabbbccc
aaabbbccc

If i column mode select and place the cursor location before the first c in each line and press enter, i should get this:

aaabbb
ccc
aaabbb
ccc
aaabbb
ccc

But as it is now, i get this:

aaabbb
ccc
aaabbbccc
aaabbbccc

Thank you for reading and your consideration.

**Comment by NPPPFreak** [comment] 2016-01-27 01:58
Sorry, i ment to say if i column select from last c in line three, to first c in line one, so the cursor is before each c.

**Comment by aaaxx** [comment] 2016-01-28 03:14
Arrows work with Shift + Alt.

**Comment by NPPPFreak** [comment] 2016-01-28 03:21
Thank you very much for pointing this out to me aaaxx, this is good, or rather great, enough for me.

Still, the carriage return issue seems as an oversight imo. If you place the cursor between the first "bc" in line one, shift-alt down down, press enter, you end up with only 4 lines, instead of 6.

Thanks again for pointing that out to me!

**Comment by sasumner** [comment] 2017-09-27 17:17
@NPPPFreak 
Concerning the "carriage return" issue...where do you think the column-mode caret should end up after executing your scenario?

**Comment by tobsimon** [comment] 2017-09-27 18:27
not op, but I would say like this:

aaabbb
|ccc
aaabbb
|ccc
aaabbb
|ccc

One behind every inserted newline. Effectively transforming column mode to multi-editing mode (which is kind of the same anyway).

**Comment by MetaChuh** [comment] 2019-04-13 01:46
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:46 UTC
