### ISSUE TITLE
Feature Request: Make size of whitespace symbol configurable

### ISSUE THREAD

**Issue by TobiasKnauss** [notepad-plus-plus/notepad-plus-plus#3469] opened 2017-07-02 08:37 UTC
### Description of the Issue
I know there are workarounds to resize the tiny whitespace symbol by macro. But as you're still actively developing on Notepad++, please add an option to set the size of the whitespace symbol. The default 1px dot on white background is barely visible.

**Comment by SinghRajenM** [comment] 2017-07-02 16:26
Default size is changed to 2px (use latest version to see effect) which is visible enough. However, configurable setting is a nice idea.

**Comment by ptitvincent** [comment] 2017-11-27 13:27
Sorry, I jump on this one like a lazy cat. But now, what about those who found it too big and was happy with the little 1px one?

**Comment by ArkadiuszMichalski** [comment] 2022-01-14 11:06
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3925.

**Closed by ArkadiuszMichalski** 2022-01-14 11:06 UTC

**Comment by TobiasKnauss** [comment] 2022-01-14 11:52
@ArkadiuszMichalski Actually, the other issue should have been marked as a duplicate of mine...
