### ISSUE TITLE
Confusing selection by keyboard

### ISSUE THREAD

**Issue by WrongBit** [notepad-plus-plus/notepad-plus-plus#5833] opened 2019-06-26 08:29 UTC
My setup of N++ has "block" caret. I have problem when I select text with keyboard:
I hold [shift], press [right] - character under cursor is selected,  but cursor **DO NOT moves right**. This is improper behaviour, because cursor should stay above next character.

**Comment by sasumner** [comment] 2019-06-26 11:53
You didn't follow the template for submitting an issue.

**Comment by DavidHansen-0x454d43** [comment] 2019-06-26 13:15
I dunno @WrongBit, N++ has the same behavior as MS Word and Visual Studio in this regards... 
I don't really think anything is broken.

**Comment by sasumner** [comment] 2019-06-26 13:20
@DavidHansen-0x454d43 I have a sneaking suspicion that @WrongBit has the "Block" caret turned on, but I would like for him to elaborate on the problem he noticed, rather than guessing.

**Comment by DavidHansen-0x454d43** [comment] 2019-06-26 13:46
Perhaps... The "block" edit behavior is the same in N++ and Visual Studio though too. 

@WrongBit, please update your issue to use the template. I'm having trouble understanding exactly what behavior you think is wrong. Maybe tell us which application your are comparing the behavior to as well.

**Comment by WrongBit** [comment] 2019-06-26 17:00
@sasumner Yes, I have "block" caret.

**Comment by WrongBit** [comment] 2019-06-26 17:06
@DavidHansen-0x454d43  OK, fixed. I compare N++ to ANY editor - none of 'em behaves so confusing like N++.

**Comment by DavidHansen-0x454d43** [comment] 2019-06-26 19:25
Ahhh, ok. I was confusing block edit with overwrite mode (toggled by insert key). 

So if I understand you, you are using alt-left click to select a multi-line block of text, and then using shift-right to try and extend that selection... which doesn't work, because N++ reverts back to a single line selection.  Is this correct @WrongBit?

If so, them I agree that this behavior is non-standard and frustrating. I've hit it before and cursed under my breath. 

You'll want to listen to @sasumner though and use the issue template:
- Description of the Issue
- Steps to Reproduce the Issue
- Expected Behavior
- Actual Behavior
- Debug Information

It really clarifies the issue and will help prevent this back and forth trying to understand what you're asking for.

**Comment by Ekopalypse** [comment] 2019-06-26 19:46
I assume that OP is referring to **settings->preferences->editing->caret settings** select **width:block**
This results in a block caret. Now if you press shift and right arrow the current char is selected but the caret
is still on the same position as before. If you hit right arrow again, while still holding shift, the block caret moves to the next position.
At least I think this is was OP is questioning.

**Comment by WrongBit** [comment] 2019-06-26 20:56
@Ekopalypse  You guess right, but behaviour is not right. [right] key is direction of movement. If I hold [shift] or not, caret should MOVE.

**Comment by WrongBit** [comment] 2019-06-26 20:57
@DavidHansen-0x454d43 There is nothing to guess, text is absolutely clear. Just leave it if it's so hard to you.

**Comment by Ekopalypse** [comment] 2019-06-26 22:03
@WrongBit - Having so much different assumption is a good indicator that it wasn't obvious and any constructive reply is a good one as it might reveal a different view on some topic. 
As I first read your issue it wasn't clear to me either - therefore my **assume** statement.

Concerning your caret **should** move. Yes, one can see it this way but others see it different.
ATOM and VSCode due it like you want, Sublime and Npp do it different. 
However, I **assume**, that this is handled by the scintilla component anyways.

**Comment by DavidHansen-0x454d43** [comment] 2019-06-26 22:12
@Ekopalypse, thank you for that. 

@WrongBit there's a reason for the issues template, and its to cut down on the number of assumptions that the people volunteering to help you have to make. For example, I had to assume you are on the latest version of N++ because you didn't include any debug info. 

I honestly couldn't reproduce your issue so that's why I thought your were talking about block edit instead of block caret. 

However, there is something else going on...
I can reproduce your issue in 7.7.1, but I can not in 7.5.9. 
So it appears like the issue you are trying (poorly) to report is a regression.

**Comment by Ekopalypse** [comment] 2019-06-26 22:19
@DavidHansen-0x454d43 - can confirm, 7.5.9 seems to do it like @WrongBit wants it to behave.

**Comment by zufuliu** [comment] 2019-06-26 22:34
This a duplicate of #5716

**Comment by Ekopalypse** [comment] 2019-06-26 22:34
... seems that this was [done on purpose](https://groups.google.com/forum/#!searchin/scintilla-interest/block$20caret%7Csort:date/scintilla-interest/RHoyyj6027g/76okNdgNAAAJ) as far as I understand.

**Comment by zufuliu** [comment] 2019-06-27 09:45
This was fixed at https://sourceforge.net/p/scintilla/bugs/1924/
with new caret style `CARETSTYLE_BLOCK_AFTER`

**Comment by WrongBit** [comment] 2019-06-27 16:06
OK, I'm happy we spot the problem. I'm disappointed that somebody come and breaks behaviour existing for YEARS. Completely dilettantish work. Such things should at least be accompanied with appropriate settings, keeping OLD behaviour.
So my question is: is that possible to change settings for normal behaviour or this ugly mode will be completely cut?

**Comment by sasumner** [comment] 2019-06-27 16:59
@WrongBit , it's a Scintilla behavior.  Notepad++ can't (won't) do anything about it until it goes to a version of Scintilla where it is fixed.

**Comment by JesterDollar** [comment] 2019-07-10 01:29
> 
> 
> @DavidHansen-0x454d43 - can confirm, 7.5.9 seems to do it like @WrongBit wants it to behave.

This is a NEW issue starting with v7.7 - works "correctly" in v7.6.6.  To reproduce:
1) Position cursor on first char of line
2) Press shift-right
Result is cursor does NOT move, therefore you're not sure it's selected

ALSO
1) Position cursor on first char of line
2) Press shift-end
Result is cursor moves to last char on line but not PAST it - again unclear if last char selected

ALSO
1) Position cursor on first char of line
2) Press shift-down
Result is cursors move to end of PREVIOUS line - unclear if full line is selected WITH cr/lf

I'm a professional developer and use mostly keyboard and this is quite unsettling. Would be quite hard to get used to after MANY years of use.

**Comment by JesterDollar** [comment] 2019-07-10 01:30
> 
> 
> ... seems that this was [done on purpose](https://groups.google.com/forum/#!searchin/scintilla-interest/block$20caret%7Csort:date/scintilla-interest/RHoyyj6027g/76okNdgNAAAJ) as far as I understand.

Don't think that applies as it's from over 2 years ago.

**Comment by JesterDollar** [comment] 2019-07-10 01:32
> 
> 
> This was fixed at https://sourceforge.net/p/scintilla/bugs/1924/
> with new caret style `CARETSTYLE_BLOCK_AFTER`

Again, this is from over 2 years ago.

**Comment by ctubio** [comment] 2019-07-10 01:39
i can tell also the issue begins on v7.7; i feel dizzy since then (not since ancient upstream bugs of 2017)

**Comment by Ekopalypse** [comment] 2019-07-10 10:12
@JesterDollar and @ctubio 
I'm not a professional programmer, I'm not even a programmer, but I think both of you are wrong in the
assumption, that this issue isn't related to the posted links. 
Why? Starting from version 7.7 npp uses an updated scintilla control. Version 4.x 
The versions before 7.7 used scintilla 3.5.6 (afaik). 
So I still believe that the links are related.

**Comment by ctubio** [comment] 2019-07-10 11:34
@Ekopalypse thank you make sense, issues opened at 2017 but still alive in the wild on 2019 cos seems +v7.7 resurrected them

**Comment by zufuliu** [comment] 2019-07-10 11:45
The fix is available in Scintilla 4.2.0 (no 4.1.8).
https://www.scintilla.org/ScintillaHistory.html

**Comment by donho** [comment] 2019-07-10 13:29
my question is:
Is 4.2.0 stable enough?

**Comment by zufuliu** [comment] 2019-07-10 13:46
It's at least more stable than 4.1.4 with more bug fixes.

**Comment by ctubio** [comment] 2019-07-10 17:10
excuse me all, and sorry @donho, allow me to make a dream come true by saying hello to you; you are an example to me since i was a kid; much respect'''''

**Comment by donho** [comment] 2019-07-10 22:35
Hi @ctubio 
I'm flattered. If you wanna say hello to me because of Notepad++, in fact, thanks to the community that Notepad++ becomes an useful software. :)

**Comment by haikubox** [comment] 2019-10-16 09:08
The recent Notepad++ v7.8 has incorporated Scintilla 4.2.0. Could you please advise, if there is a way to enable ``CARETSTYLE_BLOCK_AFTER`` in N++ now?

**Comment by WrongBit** [comment] 2019-10-16 11:15
@haikubox Just checked - still the same stupid behaviour. Seems young people have no idea how editors with block cursor worked all the time since DOS.

**Comment by alankilborn** [comment] 2022-08-04 20:34
Since #11944 has been fixed with the addition of a new "Block After" choice in the Preferences, this issue can be CLOSED as well.

**Comment by LexaGV** [comment] 2022-08-05 00:38
@alankilborn : yes, AT LAST issue is fixed. GOOD LESSON to people who breaks normal behaviour and forces other people to follow his wrong way.
OK, #11944 is fixed. But release 8.4.4 still behaves improperly (and Settings has no "caret after" option). When we can expect new build?

**Comment by donho** [comment] 2022-08-05 01:59
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/70660eb608eea7a9c85a4bfb08761ffd6bfbc887

**Closed by donho** 2022-08-05 01:59 UTC

**Comment by alankilborn** [comment] 2022-08-05 11:41
>But release 8.4.4 still behaves improperly (and Settings has no "caret after" option). When we can expect new build?

There is NEVER any published date or schedule for new releases.
All we know is that this change will be in the first release after 8.4.4, presumably 8.4.5.
