### ISSUE TITLE
Dart files syntax highlight

### ISSUE THREAD

**Issue by Wdestroier** [notepad-plus-plus/notepad-plus-plus#10897] opened 2021-12-08 21:56 UTC
### Description of the Issue
Dart files (.dart) have no syntax highlight.

### Steps to Reproduce the Issue
1. Open a .dart file.
2. The text will be black and white.

### Expected Behavior
Dart files are expected to have the same syntax highlight as Java, it is the alternative that fits the best.

### Actual Behavior
Dart files have no syntax highlight.

### Debug Information
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.318
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Without highlight:
![Without highlight](https://user-images.githubusercontent.com/14764307/145290621-38ddfdeb-5932-4826-823a-7c0f5bbca7d4.jpg)

With Java syntax highlight:
![With highlight](https://user-images.githubusercontent.com/14764307/145290703-7a6efa68-fac7-4c9b-a3da-7202db0b353f.jpg)

**Comment by ArkadiuszMichalski** [comment] 2021-12-08 22:17
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/651.

**Closed by ArkadiuszMichalski** 2021-12-08 22:17 UTC
