### ISSUE TITLE
Icons are tiny

### ISSUE THREAD

**Issue by gjblajian** [notepad-plus-plus/notepad-plus-plus#14826] opened 2024-03-04 14:12 UTC
### Description of the Issue

Many of the icons in the tool bar are so small as to be unintelligible.

### Steps to Reproduce the Issue

1.  Install version 8.6.4
2. 
3. 

### Expected Behavior

Icons should all be a consistent size

### Actual Behavior

icons are not a consistent size [see screen shot]

### Debug Information

Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22635.3212
Current ANSI codepage : 1252
Plugins : 
    JsonTools (6.1.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    XMLTools (3.1.1.13)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/5183939/a90ddd9f-17b6-4525-91fe-aea594a5dc48)

**Comment by rdipardo** [comment] 2024-03-04 21:35
Duplicate of #14709 (except for UHD display, which is not the cause of the issue anyway)

**Comment by ArkadiuszMichalski** [comment] 2024-07-08 14:32
A temporary solution: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14709#issuecomment-1937004562
Maybe related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14959.

**Closed by ArkadiuszMichalski** 2024-07-08 14:32 UTC
Labels: duplicate
