### ISSUE TITLE
Saving with Notepad++ removes alternate data streams

### ISSUE THREAD

**Issue by NotepadPlusUser** [notepad-plus-plus/notepad-plus-plus#1498] opened 2016-02-18 00:36 UTC
[I posted this on Notepad++ Community](https://notepad-plus-plus.org/community/topic/11280/saving-with-notepad-removes-alternate-data-streams).  Claudia has confirmed it, and has advised me to post here.  I'm using Notepad++ 6.8.8 on Windows 7 Pro SP1. 

---

Suppose that a file Test.txt has two alternate data stream files associated with it. When I edit the file with Notepad++, and then save it (Ctrl + S), the ADS files have been removed.

This doesn’t happen with Notepad, and with UEStudio, there is a setting to prevent it.

QUESTION: How do I save a file in Notepad++ without removing the alternate data streams?

**Comment by NotepadPlusUser** [comment] 2016-05-18 00:39
This post has not been commented on, and the issue remains with the latest version 6.9.2.
 * Does anyone know how to preserve ADS files?
 * If it can't be done at the moment, does anyone know whether the developers intend to provide such an option in the future?

**Comment by LordMike** [comment] 2016-07-08 14:08
I'll just chime in here. I was intending to use ADS to store checksum/hashes on files, so that I from time to time could check if they've been corrupted (bit rot and whatnot).. But then I noticed that my test files kept losing their ADS when I changed them (due to NP++).

I assume it's because NP++ creates new files when saving, and then moves them into place. (to help alleviate saving failures leaving partial files)

**Comment by NotepadPlusUser** [comment] 2016-08-14 23:53
Thanks, LordMike, for confirming this.  I am using ADS files in a couple of difficult sync routines, where data in ADS files indicates which computers on my home network each file should be stored on.

I was pretty unimpressed that there was no acknowledgement by Notepad++ that there was a problem with ADS files, let alone any assurance that the problem was going to be fixed.  

I uninstalled Notepad++ a few months ago, having found far better text editors that have clear development procedures in place.

**Comment by FrankS77** [comment] 2017-04-16 20:11
For me, this is a bug.

**Comment by bmliam** [comment] 2018-01-10 13:30
This also happens with sublime editor. The problem is in some cases windows stores data in the ntfs alternative data stream. The problem I spent two hours looking at was specially for html files,. Where the Zone.Identifier steam the security zone is stored.

eg:
_index.html:Zone.Identifer:DATA$ contains:
[ZoneTransfer]
ZoneId=3_
(use **DIR /r** to see steams, use **notepad.exe index.html::Zone.Identifer** to see contents of steam)

If the stream isn't there IE 11 (depending on the security settings) IE will display a warning "Internet Explorer restricted this webpage from running scripts or ActiveX controls". This means if I edit an html file in notepad.exe or Visual Studio, I don't get the warning. If I edit it notepad+ (or sublime) I get the warning because the NTFS ADS Zone.Identifier:$DATA stream has been removed.

**Comment by donho** [comment] 2019-04-14 10:41
@NotepadPlusUser 
> Suppose that a file Test.txt has two alternate data stream files associated with it. When I edit the file with Notepad++, and then save it (Ctrl + S), the ADS files have been removed.

I don't get this part. Is there any online tutorial explains how a text file have 2 alternate data stream files associated with it?

**Comment by Ekopalypse** [comment] 2019-04-15 10:19
@donho - [Here](https://blogs.technet.microsoft.com/askcore/2013/03/24/alternate-data-streams-in-ntfs/)
an msdn article discussing the additional streams. As @bmlian pointed out, a dir /r reveals if a file has
additional streams assigned or not. 
Creating such a stream. 

`
D:\>type nul > test_ads.txt

D:\>dir /r test_ads.txt
 Volume in drive D is 4TB
 Volume Serial Number is 4CE0-68D4

 Directory of D:\

15.04.2019  12:16                 0 test_ads.txt
               1 File(s)              0 bytes
               0 Dir(s)  1.919.284.916.224 bytes free

D:\>echo "text1 in stream" > test_ads.txt:stream1

D:\>echo "text2 in stream" > test_ads.txt:stream2

D:\>dir /r test_ads.txt
 Volume in drive D is 4TB
 Volume Serial Number is 4CE0-68D4

 Directory of D:\

15.04.2019  12:17                 0 test_ads.txt
                                 20 test_ads.txt:stream1:$DATA
                                 20 test_ads.txt:stream2:$DATA
               1 File(s)              0 bytes
               0 Dir(s)  1.919.284.916.224 bytes free

D:\>more test_ads.txt

D:\>more test_ads.txt:stream1
Cannot access file D:\test_ads.txt:stream1

D:\>more < test_ads.txt:stream1
"text1 in stream"

D:\>more < test_ads.txt:stream2
"text2 in stream"
`

**Comment by dinkumoil** [comment] 2019-08-14 10:50
It seems like when calling `CreateFile` API, for parameter `dwCreationDisposition` currently the constant `CREATE_ALWAYS` is used. Using this constant causes ADS to be deleted. The issue could be fixed by using constant `OPEN_ALWAYS` instead.

**Comment by Ekopalypse** [comment] 2019-08-14 13:43
So I did some test and I assume I can confirm @dinkumoil 's finding.
Including
`#include <io.h>
#include <fcntl.h>`

into Utf8_16.cpp and modifying

`FILE * Utf8_16_Write::fopen(const TCHAR *_name, const TCHAR *_type)
{
	//m_pFile = ::generic_fopen(_name, _type);
	auto mode = (wcscmp(_type, L"wb") == 0);
	m_FileHandle = CreateFile(_name,
							  mode ? GENERIC_WRITE : GENERIC_READ,
							  mode ? FILE_SHARE_WRITE : FILE_SHARE_READ,
							  NULL,
							  OPEN_ALWAYS,
							  0,
							  NULL);

	if (m_FileHandle == INVALID_HANDLE_VALUE) {
		// failsafe
		m_pFile = ::generic_fopen(_name, _type);
	}
	else {
		auto nHandle = _open_osfhandle((intptr_t)m_FileHandle, mode ? _O_WTEXT : _O_RDONLY);
		if (nHandle == -1) {
			CloseHandle(m_FileHandle);
			// failsafe
			m_pFile = ::generic_fopen(_name, _type);
		}
		m_pFile = _wfdopen(nHandle, _type);
		if (!m_pFile) {
			CloseHandle(m_FileHandle);
			// failsafe
			m_pFile = ::generic_fopen(_name, _type);
		}
	}

	m_bFirstWrite = true;

	return m_pFile;
}`

and defining HANDLE m_FileHandle; in Utf8_16.h seems to preserve ads streams.

**Comment by dinkumoil** [comment] 2019-08-14 15:01
@Ekopalypse Thank you for testing!

What do you mean with

> it is buggy when using ANSI

BTW: Why is the `dwShareMode` parameter set like this?:

`mode ? FILE_SHARE_WRITE : FILE_SHARE_READ`

This allows other applications to write to the file in question while Notepad++ itself writes to it. IMO that makes no sense, it should **always** be set to `FILE_SHARE_READ`.

**Comment by Ekopalypse** [comment] 2019-08-14 15:55
@dinkumoil 
Always treat my c++ knowledge as insufficient because it is. 
You are right, this doesn't make sense it should be FILE_SHARE_READ.

While testing with utf8 and ansi files I discovered, that additional chars got added
to the ansi file while the utf8 file kept being correct.
The test files contained just the word Ärger. After saving and reload the ansi file showed Ärger3.

**Comment by vefatica** [comment] 2020-03-06 02:25
This affects me also.  Will it ever be fixed?  Thanks!

**Comment by leochou0729** [comment] 2020-06-12 06:25
This issue was posted in 2016 and still exists in the latest 7.8.7 version. :( It's definitely a bug. A text editor should not remove any data that it's not supposed to deal with.

**Comment by m4rv2n** [comment] 2021-06-24 12:30
Without being verbose: Yes, I also noticed this bug.
Bit weird that this bug has been around for 5 years now. :S

Debug info:
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by leochou0729** [comment] 2021-06-29 08:20
I just test the latest 8.1 version, this bug still exists. It's been for ages. What happened?  :(

**Comment by LqdBcnAtWork** [comment] 2022-12-07 19:24
I'm considering using ADS to add extra data to a file (namely a change log of sorts) to the data file I'm using for a personal project. I wanted to see if NPP could view alternate streams but came across this instead. I found the original post on the forum first. I tried the batch file test that someone wrote there and it's still broken.

I also tried it with VS Code, and it doesn't share this problem.

    Notepad++ v8.4.7   (64-bit)
    Build time : Nov  1 2022 - 23:31:11
    Path : C:\Program Files\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    Cloud Config : OFF
    OS Name : Windows 10 Home (64-bit) 
    OS Version : 21H2
    OS Build : 19044.2251
    Current ANSI codepage : 1252
    Plugins : 
        HexEditor (0.9.12)
        mimeTools (2.9)
        NppConverter (4.5)
        NppExport (0.4)
        NPPJSONViewer (1.40)
        XMLTools (3.1.1.13)

Might look into making a plugin for VSC to view alternate streams...

We'll see

**Comment by LUatWork** [comment] 2023-04-12 03:54
Can Notepad++ always store the ADS's when reading the file, and include them when saving the file?  I understand that the OS saves a file on filesystem by making a new one, renaming the old one away, and renaming the new one into place.  This would of course lose the ADS's.  The application has to take responsibility for preserving ADS's if the file is edited.

**Comment by LqdBcnAtWork** [comment] 2023-04-12 15:06
> Can Notepad++ be made to always store the ADS's when reading the file, and include them when saving the file? I understand that the OS saves a file on filesystem by making a new one, renaming the old one away, and renaming the new one into place. This would of course lose the ADS's. The application has to take responsibility for preserving ADS's if the file is edited.

VS code's solution was to open the file for reading/writing (mode:'r+') if it exists and truncating the contents.

I've had success copying this solution for my own Node projects.

I'm not sure how well this would work with npp's habit of creating a *.bak and saving a new file however.

**Comment by NotepadPlusUser** [comment] 2023-09-15 01:38
I made the original post on this issue in February 2016.  Despite the issue having being 'closed as completed', I have just tested 64-bit Notepad++V8.5.7 released on 2023-09-08, and the issue has not been solved.  Explicitly:
* I created a new text file with a few words in it. 
* I then added an ADS file to it and verified that the ADS file was there.
* I then opened it with Notepad++, added a full stop, and saved it.
* I then verified that there was now no attached ADS file.

I then performed the same steps with Microsoft Notepad, and verified that the attached ADS file was preserved.

I still want to use Notepad++ as a replacement for Notepad, but I can't, because after nearly 8 years, I am still waiting for this bug to be fixed.  With all Microsoft's recent clumsiness, it is strange that such a simple thing works in Notepad but apparently cannot be fixed in Notepad++.

I am not a techie, so I am not confident in testing the three binaries referred to in posts above.

**Comment by LqdBcnAtWork** [comment] 2023-09-18 12:14
I'd like to expand on @NotepadPlusUser 's comment.

I have a batch file that creates a file with ads content (just text), pauses and then tries to print the files content.

So I:

- create text file
- add ADS
- edit & save file with npp
- no more ADS

However, I tried checking with `dir /r` and the `.bak` file had the ADS. So I think what's happening, is npp is preserving the content. But it's renaming the file with a `.bak` extension. So the ads content is still there, just under the `.bak` file name. Which means, that saving the file _twice_ will result in data destruction.

Which lines up with my previous concerns about npp's habit of creating `.bak` files.

I'm not sure what the fix will be for this. Renaming files is an elegant solution to get around having to copy the data on save. But it evidentially doesn't respect ADS content.

Debug info:
Notepad++ v8.5.7   (64-bit)
Build time : Sep  6 2023 - 23:13:49

**Comment by xomx** [comment] 2023-09-18 16:39
@donho 
I can confirm the above finding, the ADS are still removed.

For better user ADS checking & manipulation - I have [uploaded](http://xomx.wz.cz/StrmExt/StrmExt_mod_1.0.0.5.7z) to my website my very old (but still fully functional) patched version of the MS StrmExt shell extension (manual installation required, instructions are in the included 'installation.txt' file). How it looks in action:
![ADS-Streams-shell-ext](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/c2cb0acb-3a8c-4d8c-a8c2-bf4f5b1cbd42)

**Comment by NotepadPlusUser** [comment] 2023-09-19 06:50
Thanks, @donho, for having another go at sorting this out.  I really do want to use NPP, but wisely or unwisely, I have created systems that require ADS files.

@LqdBcnAtWork, I can confirm that: 
 * I create a TXT file, then add a TXT ADS file.
 * I then edit the ordinary TXT file with NPP, and save it.
 * There is now no ADS file, of any name or extension, as confirmed by Nirsoft's 'Alternate Data Stream' tool, and by my own Directory Opus script tool.

**Comment by LqdBcnAtWork** [comment] 2023-09-19 10:41
C:\Users\<user>\Other\TestingEnv\Batch>dir /r
     Volume in drive C is Windows
     Volume Serial Number is 2CC0-FB52

     Directory of C:\Users\<user>\Other\TestingEnv\Batch

    2023-09-19  06:19    <DIR>          .
    2023-09-19  06:19    <DIR>          ..
    2023-09-19  06:18               334 ads.bat
                   1 File(s)            334 bytes
                   2 Dir(s)  594,371,887,104 bytes free

    C:\Users\<user>\Other\TestingEnv\Batch>ads.bat text.txt
     Volume in drive C is Windows
     Volume Serial Number is 2CC0-FB52

     Directory of C:\Users\<user>\Other\TestingEnv\Batch

    2023-09-19  06:19    <DIR>          .
    2023-09-19  06:19    <DIR>          ..
    2023-09-19  06:18               334 ads.bat
    2023-09-19  06:19                12 text.txt
                                     14 text.txt:ads_part.txt:$DATA
                   2 File(s)            346 bytes
                   2 Dir(s)  594,371,788,800 bytes free
    main content:
    some text

    ads content:
    hidden text

    open the file text.txt with npp, change it and save it.

    Press any key to continue . . .
     Volume in drive C is Windows
     Volume Serial Number is 2CC0-FB52

     Directory of C:\Users\<user>\Other\TestingEnv\Batch

    2023-09-19  06:19    <DIR>          .
    2023-09-19  06:19    <DIR>          ..
    2023-09-19  06:18               334 ads.bat
    2023-09-19  06:19                14 text.txt
    2023-09-19  06:19                12 text.txt.bak
                                     14 text.txt.bak:ads_part.txt:$DATA
                   3 File(s)            360 bytes
                   2 Dir(s)  594,376,290,304 bytes free
    main content:
    some text


    ads content:
    The system cannot find the file specified.

    C:\Users\<user>\Other\TestingEnv\Batch>

Above is a log of calling `dir /r` then my batch file. I updated it to also call `dir /r` before displaying the content.

- folder starts with only the batch file.
- batch file is started, folder now contains text file, and the ads on the text file.
- text file is opened in npp, altered, and saved _once._
- batch file is allowed to continue.
- folder now contains the text file, a `*.bak` file, and the `*.bak` file has the ads stream from the original text file.

Because I believe npp is renaming the current file to `*.bak` and then saving the new content into a file of the same name. A second save will destroy the ads content on the file it renamed. npp does not appear to ever overwrite a file.

Note: changing `Backup` -> `Backup on save` to `None` changes this behavior. I tested above a second time and it destroyed the ads on the first save. For reference I had it on `Simple backup`. Testing again, the Verbose option appears to do the same as Simple, to the ads that is.

**Comment by xomx** [comment] 2023-09-19 13:06
@donho 
I apologize for the 'false alarm', the fix works ok, now the ADS are left untouched by N++ when saving.

Their problem (and mine) was probably in this:
> , I have just tested 64-bit Notepad++V8.5.7 released on 2023-09-08, and the issue has not been solved

-> so they are testing with the latest N++ release binary, where the fix has not been committed yet... (they confused me enough that I tested with that wrong binary too)

So until a next N++ release (v8.5.8), one has to use these binaries for testing: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/47857747

**Comment by LqdBcnAtWork** [comment] 2023-09-19 18:16
> @donho I apologize for the 'false alarm', the fix works ok, now the ADS are left untouched by N++ when saving.
> 
> Their problem (and mine) was probably in this:
> 
> > , I have just tested 64-bit Notepad++V8.5.7 released on 2023-09-08, and the issue has not been solved
> 
> -> so they are testing with the latest N++ release binary, where the fix has not been committed yet... (they confused me enough that I tested with that wrong binary too)
> 
> So until a next N++ release (v8.5.8), one has to use these binaries for testing: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/47857747

Just checked `Binary 1` in #14085, and it preserves ADS. Looking forward to v8.5.8+ then. I suppose this was just a poor line up of 8.5.7 being released and this issue being closed.

**Comment by donho** [comment] 2023-09-19 19:47
[The issue has been fixed](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b068aa90335deefb0f383558df745bfae9ff7536) in the current master, so it will come with v8.5.8 (which will be available in next moth), but not in current release v8.5.7.

**Closed by donho** 2023-09-19 19:47 UTC

**Comment by NotepadPlusUser** [comment] 2023-10-19 04:28
I have installed V8,5,8, and tested it.  Now the ADS files are indeed preserved when the file is edited with Notepad++ and saved !

Thank you very much @donho for sorting this out.  I will now change Notepad to Notepad++ in my shortcuts, which will make editing a far more pleasant experience..
