### ISSUE TITLE
Feature request: Option to turn on analog scrolling

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8750] opened 2020-08-21 00:09 UTC
On browsers, pressing the scroll wheel enables you to scroll at custom speeds and very fast. Would like to have the same effect to apply to NP++ as well.

**Comment by ArkadiuszMichalski** [comment] 2020-09-22 09:08
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8275?

**Closed** 2020-09-22 11:45 UTC
