### ISSUE TITLE
MSI setups fail to upgrade SciLexer.dll because of unchanged file version

### ISSUE THREAD

**Issue by alexhass** [notepad-plus-plus/notepad-plus-plus#3676] opened 2017-08-30 08:17 UTC
As you know I'm the maintainer of MSI packages. Latest releases introduced a serious trouble.

### Description of the Issue
The file was digital signed, but the version of SciLexer.dll was not increased.

### Steps to Reproduce the Issue
1. Notepad++ software contains a SciLexer.dll that has a version of 3.5.6.0 since Notepad++ 6.7.9
2. Between Notepad 6.8.4 and 6.9.1 the SciLexer.dll was digitally signed.
3. In a Version later than 7.3.2 notpad++ started verifying the digital signature and fails to start if the signature does not exists.

What happened?

1. MSI setups are intelligent and not that stupid like NSIS.
2. Versions of files are compared. If a file version is the same the file is not overwritten on disk.
3. That means on computers where Notepad++ 6.7.9 has been installed with MSI installer in past and later upgraded to newer versions the file is SciLexer.dll file is still on disk WITHOUT a digital signature.

### Expected Behavior
1. **NEVER** change the digital signatue of files without increasing the file version number!!! I have no words.
2. The vendor of SciLexer.dll need to sign it's files, not notepad++ maintainer.
3. **Increase the file version of SciLexer.dll ASAP in next release.**

### Actual Behavior
Notepad++ stops working as the signature cannot verified.

### Debug Information
Simply install latest 7.5 and replace the SciLexer.dll with a non-digital signed version.

**Comment by SinghRajenM** [comment] 2017-08-30 09:32
> MSI setups are intelligent and not that stupid like NSIS.

Who told you that NSIS setups are stupid? In NSIS, there are ways to control the file before replacing it and I would say it is beauty of NSIS. It is controlled using ```SetOverwrite``` flag. Refer [nsis doc](http://nsis.sourceforge.net/Reference/SetOverwrite).

I feel there might be similar way with msi package as well. if not then I would say MSI is stupid.

**Comment by yamlfd** [comment] 2017-08-30 14:26
NSIS is biggest sh** ever and should RIP like InnoSetup. Both cannot deployed via Active directory. That is why i'm talking for several years with Don to take my MSI over and discontinue NSIS.

But this is not the point here. Changing a file (by adding a signature) without increasing the version is always wrong and bad practice. More bad practice is signing files from other sources.

The idea behind the MSI feature are ***faster*** running update setups. No file that has the correct version need to be replaced if the most important flag is already the same (file version). This improves setup speed in an extreme way.

There seems no way to stop this behavior. A file version need to be increased if the file is changed. This ist best practice.

**Comment by Ede123** [comment] 2017-08-30 18:30
* In practice I've never seen msi installs to be fast but whatever...
* What MSI installer are you talking about by the way? Is there a link? Is there source code?
*  For the Inkscape project I'm currently maintaining .exe (NSIS) and .msi (WiX) installers and the .msi installer is giving me a hard time over and over again. It's inferior in almost every respect (not because I would not want to make it better but simply because the *.msi format seems to be a pain in the a**) so I prefer the NSIS installer very much (even if it's ancient software).<br/>If you're knowledgebal about .msi/WiX - how do I at least get the MSI installer to uninstall old files (not present anymore in the new package) and properly update other files? I hope there's a possibility that does not require giving all files a version number...

**Comment by yamlfd** [comment] 2017-08-30 21:57
See https://www.hass.de/content/notepad-msi-package-enterprise-deployment-available

I have shared the source code of MSI installer for Notepad++ with Don. The version he has it outdated now, but if he is willingly I'm sharing it with him.

> If you're knowledgeable about .msi/WiX - how do I at least get the MSI installer to uninstall old files (not present anymore in the new package) and properly update other files?

Every of my installers has this feature embedded. It is very easy. WiX has a util feature named `RemoveFolderEx` that does all the cleanup magic. Please see my documenation at https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts.

I'm not sure what you mean with _update other files_. Every file that has a higher version number will be updated. If there is no version e.g. text files a hash compare will be done. Nothing need to be done by hand. Just create a new GUID with "*" for every release. If guids are static and only changed if the file really changed - you will see the extreme performance benefit... The "*" for GUID will cause the setup to run slower as every file need to be checked/updated again.

Aside - I offered the Inkscape team my help to create this installer (~3 years ago?) and than a very few months later I have seen it was already done. Thanks for this - it saved me a lot of time! Until today the AD deployment worked like a charm.

**Comment by yamlfd** [comment] 2017-11-07 10:24
@Ede123: Has this article helped you?

**Comment by Ede123** [comment] 2017-11-08 14:19
@yamlfd: Not really I'm afraid....
The specific issue is explained in a bit more detail in https://bugs.launchpad.net/inkscape/+bug/1653574 but I did not find the time for closer investigation yet. If you want to help out contributions are welcome...

**Comment by yamlfd** [comment] 2017-11-08 16:10
That is exactly what I have documented. Just copy and paste and delete the uninstall registry key of nsis. I have no account on the site, sorry.

**Comment by Ede123** [comment] 2017-11-08 23:38
Either I'm constantly reading over it or we have different ideas on how this should work...
I don't want to uninstall the whole folder (a user might have copied files there after installation), I want to uninstall everything the last MSI installer installed (if it's not updated) and I want to get rid of all old  uninstallation entries and program shortcuts.
At the very least the latter parts seems to fail (I have not yet confirmed the former part).

**Comment by alexhass** [comment] 2018-03-29 07:49
@Ede123 

> Either I'm constantly reading over it or we have different ideas on how this should work...
> I don't want to uninstall the whole folder (a user might have copied files there after installation),

Maybe. I think I maintain the installer and nobody is allowed to alter the base installation. Therefore it is save to remove/cleanup file no longer needed. RemoveEx does not uninstall the whole folder, it only uninstalls the differences so that no garbage or conflicting directories are left behind. I wonder how you are able to support customized program folders and this has never caused strange situations to happen. I guess you talk about plugins/addons that are manually copied into incscape. I also done this on my box, but this is clearly a design issue of incscape. I suggest to move this outside the main program folder as this prevent clean updates. One solution are the per user plugins in appdata we have in notepad. Another solution could be an installation of custom addon stuff to ProgramData folder to make it per machine.

> I want to uninstall everything the last MSI installer installed (if it's not updated) and I want to get rid of all old uninstallation entries and program shortcuts.

I'm using RemoveEx for so long now... I think what you want is the default behaviour, or what happens here?

**Comment by MetaChuh** [comment] 2019-04-16 09:32
closed as not related to the notepad++ source code or official packaging.
please use the official notepad++ installer.

while custom installation methods and modifications are possible, they are not supported at the notepad++ project.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-16 09:32 UTC
Labels: installer
