### ISSUE TITLE
Folder as workspace contents not listed alphabetically when using WSL.

### ISSUE THREAD

**Issue by logidwegmull** [notepad-plus-plus/notepad-plus-plus#15397] opened 2024-07-03 23:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When FAW points to a directory located within the Windows Subsystem for Linux (the path looks like: \\wsl.localhost\Ubuntu\home\testUser\project), the files are not in alphabetical order. On the same computer, files located in the native Windows directory are listed alphabetically.

### Steps To Reproduce

1.  Install WSL
2.  create a directory with files within the WSL Ubuntu virtual machine.
3.  Add a new FAW that is located within a Ubuntu directory \\wsl.localhost\Ubuntu\home\testUser\project

### Current Behavior

The files are listed out of order

### Expected Behavior

I expect the files to be in alphabetical order, like they are in FAW located within Windows native file system.

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.3737
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExec (0.8.4)
    NppExport (0.4)
    NppGTags (5.1.1)
    Python Indent (1.0.0.5)
```

**Comment by xomx** [comment] 2024-07-04 10:22
Probably duplicate of #10557 .

**Closed** 2024-07-20 12:37 UTC
