### ISSUE TITLE
NPP Export 0.2.8 doesn't work in version 7.7

### ISSUE THREAD

**Issue by swampthings** [notepad-plus-plus/notepad-plus-plus#5740] opened 2019-06-04 13:24 UTC
### Description of the Issue
NPP Export doesn't work on the latest version, 7.7. It copies monospace font, but no color formatting.

### Steps to Reproduce the Issue

1. Upgrade to v7.7 (I tried 32 bit and 64 bit)
2. Note that NPP Export doesn't work
3. Uninstall and reinstall v7.6
4. Note that NPP Export is working

Note that I tried copying all formats, RTF, and HTML. Also, exporting the file exports an unformatted file. I'm using Windows 10.

Picture of results pasting the exact same thing after being NPP Export copied from 7.7 and 7.6:
![image](https://user-images.githubusercontent.com/7899230/58882249-03834980-8706-11e9-861f-b8922859f72b.png)

**Comment by chcg** [comment] 2019-06-04 14:10
@swampthings npp export is a plugin, also bundled with N++ for the 32bit deliveries. The original version is not actively supported any longer, see https://sourceforge.net/projects/npp-plugins/files/NppExport/NppExport%20Plugin%20v0.2.8/. There is already a report at https://github.com/chcg/NPP_ExportPlugin/issues/7 which seems to be a duplicate of this one. 
Do you confirm? Then please contribute to that issue.

**Comment by swampthings** [comment] 2019-06-05 11:30
Wow, last updated in 2008...I never realized I relied so much on something that's probably going away soon.

Okay, I'll contribute to that issue. Is there another way to copy formatted text in Notepad++, or is the depreciated NPP Export the only way?

If it's the only way, I'd suggest to fix whatever broke the plugin between release 7.6.6 and 7.7.

**Comment by MetaChuh** [comment] 2019-06-06 13:22
@donho 

we didn't close this plugin issue yet, because NppExport is an included plugin.

maybe it's time to remove NppExport from the official release.
what do you think ?

**Comment by rcoxon** [comment] 2019-06-06 18:26
I make extensive use of the NppExport plugin.  I don't know of another way to copy from Npp to the clipboard and retain the syntax highlighting.
Just cloned the repo, and got it to compile with updated scintilla.h, but has the same issue with 7.7.

Not a cpp programmer, but may have to take a wack at it if no one else does

**Comment by chcg** [comment] 2019-06-24 10:42
See https://github.com/chcg/NPP_ExportPlugin/issues/7, fixed by release https://github.com/chcg/NPP_ExportPlugin/releases/tag/0.2.9.21.

**Closed** 2019-06-24 10:43 UTC
Labels: plugin

**Comment by paulshaffer** [comment] 2019-07-22 18:53
Thank you!!

**Comment by pgw333** [comment] 2019-08-29 11:36
Last release 0.2.9.21 solve the problem:
https://github.com/chcg/NPP_ExportPlugin/releases

**Comment by johnhorner** [comment] 2019-10-14 22:17
Thanks @chcg, this is a really useful feature, very glad to have it back.
