### ISSUE TITLE
When open NPP, a dialog will pop up asking open a bunch of files.

### ISSUE THREAD

**Issue by machinewu** [notepad-plus-plus/notepad-plus-plus#6211] opened 2019-10-12 09:14 UTC
### Description of the Issue

Each time you open it, a dialog will pop up asking if you want to open a bunch of files.
![snapshot20191012165131](https://user-images.githubusercontent.com/4166753/66698701-beee6700-ed12-11e9-9ab4-de4a695eca14.png)

### Steps to Reproduce the Issue

~~1. NPP portable version 7.8, extract to `D:\Program Files\notepad++`~~
~~2. open `notepad++.exe`~~
~~3. After click "No"，NPP will ask you create a `.txt` file in exacted path~~

1. NPP portable version 7.8, extract to `D:\Program Files\notepad++`
2. Follow the manual `https://npp-user-manual.org/docs/other-resources/`, set NPP replace original Windows Notepad.exe
3. double click open a `.txt` suffix file

**Update**:
If I don't modify the registry, it won't appear this issue. (NPP portable v7.8)
Only replaced original notepad by modifying the registry will appear this issue.
After I changed the path to `D:\notepad++`(path without whitespace) and registered again, it still appear the issue.

### Expected Behavior

Don't pop up the dialog.

### Actual Behavior

A dialog pop up asking if you want to open a bunch of files.

### Debug Information

Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : D:\Program Files\notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.316
Plugins : AutoCodepage.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll 

**NPP v7.7.1 doesn't have this issue, but NPP v7.8 has this issue.**

**Comment by Ekopalypse** [comment] 2019-10-12 11:26
I'm using portable versions exclusively and I don't see your reported behavior, so it must be a combination of things which makes this happen.
Using
Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.23934
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

my steps were. 
Downloaded 7.8 zipped
extracted to a directory
opened explorer, changed to that directory and double clicked on npp. 

You extracted the zip to D:\Program Files\, which I don't have on D:, but does that mean,
that this is your normal system program installation path?
If so, does the same happen if you do EXACTLY my steps using a different directory.
DO NOT USE ANY PREDEFINED SHORTCUTS you might have on your system.
Goto the directory via the explorer and double click on notepad++.exe.

**Comment by erocmiles** [comment] 2019-10-12 18:05
I can confirm this issue. I did not use portable version. I used the installer version.
I installed on default directory.
Did not happen with previos version.

**Comment by Ekopalypse** [comment] 2019-10-12 18:11
@erocmiles - and how did you start npp? Using a shortcut or by double clicking the exe?

**Comment by erocmiles** [comment] 2019-10-12 18:45
I replaced notepad with notepad++ by modifying the registry editor.
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f

When opening files with this was opening all the files on the directory.
I remove the parameter -notepadStyleCmdline seems to have fixed the issue.

Thank you for the hint @Ekopalypse

**Comment by sasumner** [comment] 2019-10-12 19:02
So...is there really an issue here?  Or is the answer "remove -notepadStyleCmdline" ?

**Comment by Ekopalypse** [comment] 2019-10-12 19:18
@CookiePLMonster did some research and PR on this, I'm quite unfamiliar what this is all about.

**Comment by cybermcm** [comment] 2019-10-12 20:19
I reported this in the release thread, happens too on my machine (portable version, using the registry entry to replace Windows notepad) while opening files with filename containing a white space character...

**Comment by machinewu** [comment] 2019-10-13 00:29
I feel that there is a issue with the white space characters in the path. Because I extact NPP to `Program Files`. The path contains a white space character.

**Comment by machinewu** [comment] 2019-10-13 00:54
> 
> 
> I replaced notepad with notepad++ by modifying the registry editor.
> reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d ""%ProgramFiles%\Notepad++\notepad++.exe" -notepadStyleCmdline -z" /f
> 
> When opening files with this was opening all the files on the directory.
> I remove the parameter -notepadStyleCmdline seems to have fixed the issue.
> 
> Thank you for the hint @Ekopalypse

For removing the parameter -notepadStyleCmdline:
1. If my NPP path without whitespace, such as `D:\notepad++`, it work.
2. If my NPP path have whitespace, such as `D:\Program Files\notepad++`, it doesn't work.

**Comment by SinghRajenM** [comment] 2019-10-13 07:15
I have figured the root cause for this regression...

When you double click a file (where NPP has already replaced original Windows Notepad.exe) command like something like below is generated - 

`-notepadStyleCmdline -z "C:\WINDOWS\system32\NOTEPAD.EXE" F:\FakePath\PowerEditor\bin\change.log`

After processing this command line, final command line is left as `" F:\FakePath\PowerEditor\bin\change.log` while others are ignored. **Notice, quote `"` here just before the actual file path.**

Later on, MS PAI `::PathIsRelative` treats it as relative path because of quote `"` rather considering single file. It is expected too as per input to this API.

Now, notepad++ tries to open all the file from path `F:\FakePath\PowerEditor\bin\` (in above case) along with file `F:\FakePath\PowerEditor\bin\change.log`.

This regression got introduced in dc6bd2a8d2fe84e511b3b6571a72818c709033cc. I will be submitting fix for this issue soon.

**Closed** 2019-10-14 00:24 UTC
Labels: accepted
