### ISSUE TITLE
Feature request: Instant search box and Ctrl+F4

### ISSUE THREAD

**Issue by kurienmathew** [notepad-plus-plus/notepad-plus-plus#1683] opened 2016-03-26 08:41 UTC
Hello,

Would it be possible to add the following features to the editor:
1. Instant search box (like in Outlook or Google search) - The editor should show lines that match the simple or regular expression specified in the search box
2. Ctrl+F4 to close a tab

Thanks

**Comment by leewz** [comment] 2016-03-27 12:20
1. I think Incremental Search is what you're looking for. Default shortcut is Ctrl+Alt+I. This can take a lot of processing power in a large file, and it'd be hard to undo the scroll, so it shouldn't be the default.
2. You can change shortcuts in (Menu) > Settings > Shortcut Mapper.

**Comment by kurienmathew** [comment] 2016-03-27 13:09
#1 - Incremental search just highlights the matched pattern. What I need is that the editor displays only the lines containing the specified pattern. All the other lines must be hidden. When the pattern in the instance search box is cleared, all the lines should be displayed as before. The instant search box would function like a real-time/instant filter/grep on the file.
#2 The Shortcut Mapper does the job. Thanks

**Comment by leewz** [comment] 2016-03-27 13:13
Oh, sorry. Check out the Linefilter2 plugin.

> A plugin for Notepad++ that allows you to filter a text for a search string :
> 
> - Display searchresult in new NPP window
> - Display linenr of original text
> - Hits can be highlighted
> - Display lines before and after a hit
> - Perl compatible regular expressions.
> Author: Heinz
> Homepage: http://www.scout-soft.com/linefilter
> Latest update: 31.05.2013 V 1.1 - minor fixes

P.S.: Use `1.` instead of `#1` to number your lists, as Github uses that syntax to link between issues. (If you click on issue 1, you'll see that you have linked it to this issue.)

**Comment by kurienmathew** [comment] 2016-03-27 13:28
Linefilter2 is kind of what I want. The drawbacks being that you have to go into a 3rd level menu to bring up the filter dialog and that the results show up in a new window. An instant search box integrated into the main window with results displayed instantaneously in-place would have been far more powerful.

**Comment by DaveBy** [comment] 2016-04-19 21:18
Ctrl+F4 is an industry standart for closing a MDI tab, i think it should be a default shortcut

**Comment by MetaChuh** [comment] 2019-04-13 02:22
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:22 UTC
