### ISSUE TITLE
UTF-8 encoding option goes wrong with file with misidentified encoding

### ISSUE THREAD

**Issue by johnmreynolds** [notepad-plus-plus/notepad-plus-plus#3188] opened 2017-04-20 14:43 UTC
### Description

I've got a file (will attach one which replicated this issue), which is almost entirely ASCII, but with a UTF-8 encoded character in it. This file does not have a leading BOM.

Notepad++ misidentifies the encoding as Thai TIS-620. By itself this is a minor inconvenience, but following this, the encoding options in the Encoding menu seem to end up broken.

### Steps to Reproduce the Issue

1. Open the file.
2. Notepad++ misidentifies the encoding as TIS-620.
3. Select Encode in UTF-8 from the Encoding menu.

### Expected Behavior

Change the encoding to UTF-8 and display the character correctly.

### Actual Behavior

Encoding at the bottom of the screen flickers, and reverts to TIS-620, and the character is not displayed correctly.

Selecting a different encoding from the Character Sets (e.g. ISO 8859-1) from the menu does change the encoding, but obviously ends up displaying the multiple characters. There doesn't seem to be any option under the Character Sets submenu for forcing 'Unicode' as the character set.

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

[test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/943687/test.zip)

**Comment by rddim** [comment] 2017-04-20 21:31
Try to disable the `Autodetect character encoding` in `Settings` > `Preferences...` > `MISC.`

**Comment by Marcono1234** [comment] 2017-06-05 13:24
This looks like a duplicate of #940. I was only able to reproduce this using the `§` character

**Comment by johnmreynolds** [comment] 2017-06-05 14:16
Sorry for the delay in commenting, but just to note that the setting change noted by rddim above does successfully work around this issue, thanks.

**Closed** 2021-12-27 19:19 UTC
