### ISSUE TITLE
When prompting to save on close, show me the tab that is closing.

### ISSUE THREAD

**Issue by stihl716** [notepad-plus-plus/notepad-plus-plus#9010] opened 2020-10-14 16:42 UTC
### Description of the Issue
When closing unsaved tabs the software prompts to save each unchanged tab in turn.  But it doesn't show the tab.  It would be helpful if it showed the tab so that I can decide if I want to save or not.

### Steps to Reproduce the Issue
See attached screen capture.

1.  Load NP++
2.  Create a new tab
3.  Enter some text
4.  Create a new tab
5.  Enter some text
6.  Select both of these the documents in Doc Switcher.
7.  Right click and choose Close Selected Files
8.  The software prompts to save the first unsaved file.

### Expected Behavior
Switch to the unsaved tab.

### Actual Behavior
Remains on the last edited tab.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1726
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSnippets.dll XMLTools.dll 

[2020-10-14_10-35-36.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5379663/2020-10-14_10-35-36.zip)

**Comment by sasumner** [comment] 2020-10-14 17:24
Closing as related-duplicate of #8283
See the second bullet point of the "Expected" behavior:
* For each unsaved file, the file gets the focus (comes to the foreground), so the user can see the content for the file she is going to save and select a new name for next.

**Closed by sasumner** 2020-10-14 17:24 UTC
