### ISSUE TITLE
Incorrect "File already exists" message

### ISSUE THREAD

**Issue by veechster** [notepad-plus-plus/notepad-plus-plus#9777] opened 2021-04-17 20:32 UTC
### Description of the Issue

When "saving as" a file, with multiple extensions (in my case 'test.env.dist') as "All types" and removing an extension (i.e. to 'test.env') notepad incorrectly returns an incorrect warning (File 'test.env.dist' already exists. Would you like to replace it?). If you select yes, you get the error: "File is already opened in notepad++". This can be circumvented by modifying and resetting the filename (i.e backspace the v and then retype it).

### Steps to Reproduce the Issue

1. Create a text file "test.env.txt" and open the file in notepad.
2. "Save As" the file and set "Save as type"="All types" from the dropdown. Note the filename is now "test.env"
3. Attempt to save. Notepad returns an error and will not save the file.
4. Repeat set 2 except this time backspace the v and then retype it. File saves.

### Expected Behavior

When saving the "test.env.txt" as "test.env" as type "All files" and the new file does not exist and is not open in notepad, this issue should not occur. Editing the filename to the same value should not change the behavior.

### Actual Behavior

It seems notepad++ is automatically re-adding the omitted file extension to the file name when you select all-types (i.e. test.env is actually saved as test.env.txt).

### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2021-04-17 21:12
Provide "Debug Information" to get your issue looked at.
Instructions were in original template.

**Comment by veechster** [comment] 2021-04-17 21:15
Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.928
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2021-04-18 01:12
In step 2, I cannot reproduce this part:  `Note the filename is now "test.env"`.
Mine says `test.env.txt`.

Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\\..........\npp.7.9.5.portable.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by veechster** [comment] 2021-04-18 01:19
Ah. If I change the Windows setting in explorer>View to show File name extensions, then the behavior is as you described.

With "File name extensions" turned off in windows, I get the issue.
In this case, when using "Save As..." for a filename that is only an extension, such as ".env", the filename is blank.

**Comment by sasumner** [comment] 2021-04-18 01:29
@mere-human
My head hurts...how's yours feeling? :-)

**Comment by sasumner** [comment] 2021-04-18 01:42
Error at step 3:

![image](https://user-images.githubusercontent.com/30118311/115131285-eb98d400-9fc4-11eb-8625-cffeadd0e8ef.png)

This is correct behavior as it is trying to _SaveAs_ the file to the original name -- this is not allowed as _SaveAs_ (to be a "save as") requires a different name.  Because we haven't changed the name, the dialog is probably aware of this and thinks/knows we mean `test.env.txt` instead of `test.env` even though the types is "all types".

It gets a bit trickier in step 4.  We delete off the `v` and retype it.  But we've probably (by virtue of the changing the content) reset the dialog's memory of the original name, and this time it takes into account that the types is "all types", and allows dropping of the final `.txt`.

**Comment by veechster** [comment] 2021-04-18 01:44
I thought I might be goofing a bit on this. I am used to overwriting my .env (prod) files with the .env.dist (repo) versions by just selecting all-types.

This behavior is new (7.9?); I tested on a remote PC and did not encounter the issue, the file saves normally in step 2.

Debug Information on that PC:

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.804
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2021-04-18 02:13
The standard file open/save dialogs were replaced in, IIRC, 7.9.3.  It turned out to be a larger change than first thought, actually ending support for Windows XP because of it.  The ramifications of this change are still being worked out; yours is yet another.

@mere-human The regression testing for the feature should add hiding extensions for known file types in Explorer.

**Comment by mere-human** [comment] 2021-04-18 08:20
@veechster So the expected behavior is something like Notepad++ 7.8.5 or Windows built-in Notepad, right?

@sasumner I will look into this one.
This is probably a side effect of processing of the file name to do forward slash path support, etc.
---

One of the things I do first when I install a Windows on a fresh PC is I turn off this option in _Folder Options > View > Hide extensions for know file types_.

**Comment by mere-human** [comment] 2021-04-18 08:47
> In this case, when using "Save As..." for a filename that is only an extension, such as ".env", the filename is blank.

What is the expected behavior in this case?
Windows built-in Notepad just sets the filename to `.env.txt` when I change to _All Files_ and then to _Text Documents_:
![image](https://user-images.githubusercontent.com/9664141/115139663-cc895900-a03b-11eb-92c3-0e95d3e1da4b.png)

**Comment by mere-human** [comment] 2021-04-18 09:37
I suppose we need to fix the case only when _Hide extensions for know file types_ is ON, right?

**Comment by sasumner** [comment] 2021-04-18 11:02
@mere-human 

>One of the things I do first when I install a Windows on a fresh PC is I turn off this option in Folder Options > View > Hide extensions for know file types.

Same here.
But...not everyone does that, and since the default is the way it is...we have to support it and support it well.

>The only thing that pleases me here is the number of this issue

???  The symmetry of some sevens? :-)

>What is the expected behavior in this case?
Windows built-in Notepad just sets the filename to .env.txt when I change to All Files and then to Text Documents

If it makes sense to mimic notepad.exe behavior, then I suppose that is a good starting poing.

>I suppose we need to fix the case only when Hide extensions for know file types is ON, right?

I suppose so as well. :-)

**Comment by mere-human** [comment] 2021-04-25 20:51
@veechster @sasumner Could you, please, try the steps in the Windows built-in Notepad?
For me, the behavior seems to be the same as described in Actual Behavior.

**Comment by sasumner** [comment] 2021-04-26 19:23
>Could you, please, try the steps in the Windows built-in Notepad?

Interested in extensions showing/hidden/both?

**Comment by veechster** [comment] 2021-04-26 19:48
It looks like windows built-in notepad shows the complete file name and extension in the save-as menu regardless of the windows 'Hide extensions for know file types' setting. 

So I guess that notepad++ should show the complete extension in the save-as menu even when the windows setting is to hide known extensions.

**Comment by mere-human** [comment] 2021-04-26 19:57
> 
> 
> > Could you, please, try the steps in the Windows built-in Notepad?
> 
> Interested in extensions showing/hidden/both?

@sasumner I'm interested in the case when the extensions are hidden.

**Comment by mere-human** [comment] 2021-04-26 20:02
> It looks like windows built-in notepad shows the complete file name and extension in the save-as menu regardless of the windows 'Hide extensions for know file types' setting.

Are you sure? Mine hides the extensions the same way as Notepad++ does:
![image](https://user-images.githubusercontent.com/9664141/116142711-e7666800-a6e2-11eb-9b92-93d31e570011.png)

And the behavior is actually the same in Windows Notepad:
* Open `test.abc.txt` and Save As
* Saves as `test.abc.txt`
* Remove and re-type `c` in the file name
* Saves as `test.abc`

And I think this is correct behavior. Because when it saves initially the file name should be the same as before e.g. `test.abc.txt`. But when you change it what is the difference between changing one letter vs. typing-in a completely new name?

**Comment by sasumner** [comment] 2021-04-26 21:19
I would like to do something to help, but what it is wanted for me to do is somewhat vague. :-)

**Comment by sasumner** [comment] 2021-04-27 13:30
I tried this test:

- Create a file "test.abc.txt"
- Explorer > View > Hide extensions
- Edit file with Notepad.exe
- File > Save As, select "All types" from the dropdown and press OK
- Warning that the file "test.abc.txt" already exists should appear
- Cancel the warning, back to the Save As dialog
- Delete the last letter "c" in the file name and then type it again
- Press OK

And the result was that the file saves as "test.abc" and appears like this:

![image](https://user-images.githubusercontent.com/30118311/116249257-a00bc600-a73a-11eb-92d0-50aff96e5f81.png)

The file with the icon that is like most of the others in the screenshot has the "hidden" `.txt` extension and was the starting point for this experiment.  The file with the differing icon is what resulted from the _SaveAs_.

Indeed, after turning extension-showing back on:

![image](https://user-images.githubusercontent.com/30118311/116249591-f842c800-a73a-11eb-83f9-6a9348e14043.png)

**Comment by mere-human** [comment] 2021-04-27 13:56
> The file with the icon that is like most of the others in the screenshot has the "hidden" `.txt` extension and was the starting point for this experiment. The file with the differing icon is what resulted from the _SaveAs_.

@sasumner Thank you!
This matches my results. 
So, it seems Notepad++ behavior in this case is the same as Windows Notepad. 
Mostly because Notepad++ use the same file dialog component.
So, I'm not sure whether we should fix it or not.

**Comment by sasumner** [comment] 2021-04-27 14:08
>I'm not sure whether we should fix it or not.

I would vote NO.
Unless, the "fix" is very easy, and "breakproof".
With Notepad++, although we obviously try to produce the `++` experience over notepad.exe, sometimes it is worth just citing the notepad.exe behavior as "it is how Microsoft wanted Windows to work" and leaving it at that.
My mouse hovers over the Close button, but I wait for @mere-human to tell me to click it or not.

**Comment by mere-human** [comment] 2021-04-27 14:14
> Unless, the "fix" is very easy, and "breakproof".

It's actually the opposite. 
I had a partially working hack. But to me it seems too dangerous. So I'd avoid it for now unless the issue is critical.

**Comment by sasumner** [comment] 2021-04-27 15:27
>So I'd avoid it for now unless the issue is critical.

Hard to call an issue "critical" when Windows' notepad.exe behaves the same.
Good enough for me -- closing.

**Closed by sasumner** 2021-04-27 15:27 UTC
