### ISSUE TITLE
Document peeking prevents save keyboard shortcut

### ISSUE THREAD

**Issue by OffLuffy** [notepad-plus-plus/notepad-plus-plus#3348] opened 2017-06-03 20:29 UTC
### Description of the Issue
When a document peek pane is active, using <kbd>Ctrl+S</kbd> will not save the active document.

### Steps to Reproduce the Issue
1. Have a document open with unsaved edits and another document in an inactive tab
2.  Mouse over an inactive tab to activate peek
3.  Press <kbd>Ctrl+S</kbd> to attempt to save the document

### Expected Behavior
I expect the file to be saved, as I've often left my mouse hovering over an inactive tab, not usually intentionally. I would expect the <kbd>S</kbd> key to scroll the peek to the top of the peeked document, but for <kbd>Ctrl+S</kbd> to save the active document regardless of a peek pane being open.

### Actual Behavior
The active document doesn't save. If the document you're peeking isn't already at the top and is scrolled down, pressing <kbd>S</kbd> or <kbd>Ctrl+S</kbd> will scroll the peek pane to the top of the document you're peeking.

### Other Notes
I'm unsure if this prevents other shortcuts or if this is applicable on other systems. I'm using Windows 10 x64.

**Comment by SinghRajenM** [comment] 2017-06-04 06:25
Similar to #3262

**Comment by SinghRajenM** [comment] 2019-04-13 04:01
@MetaChuh this is duplicate.

**Comment by MetaChuh** [comment] 2019-04-13 10:06
closed as duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3262

**Closed by MetaChuh** 2019-04-13 10:06 UTC
Labels: duplicate
