### ISSUE TITLE
Gap at the scrollbar

### ISSUE THREAD

**Issue by artenaki** [notepad-plus-plus/notepad-plus-plus#10733] opened 2021-10-30 03:07 UTC
Notepad++ has a small gap between the scrollbar and the edge of the screen when the application is maximized. As a result, it takes extra effort to aim the mouse cursor at the scrollbar. This cannot be done blindly by pointing the mouse to the right. Precise aiming is required.

See the explanatory screenshot. Sorry it's from another app, but it doesn't matter https://i.imgur.com/hCTRMRb.png

I've noticed that almost all text editors on Windows have an annoying gap: notepad, wordpad, akelpad, notepad++, openoffice, ms office, emeditor. It's just some kind of mania. Exception: libreoffice (if you disable the sidebar).

Unfortunately, XP users won't see your changes, even if you release a fix. But at least Vista+ and Wine users will be happy.

I wonder why no one has noticed this over the years and fixed it. My Mousepad (and Leafpad) text editor in Xubuntu 16.04 with the Clearlooks-Phenix theme has no gaps.

Abstract: Not many people think about it, but in fact, the problem of gaps exists in many applications (even Linux) and in many places. At "close, expand, minimize" buttons, taskbar, start menu. For example, in the classic theme in Windows XP-7, there is a gap at the taskbar. Old (very old) browsers and Windows 2000 had gaps almost everywhere.

I'll clarify that the gaps only cause a problem if the window is maximized. Otherwise, they don't bother, of course. If the window is non-maximized, "thin" scrollbars that are hard to reach with the mouse can be a problem. For example, like the gray thin scrollbars that Apple has introduced in fashion since Lion. And now they are found in many places, unfortunately. Fortunately, in Windows, the scrollbars are thick. In Xubuntu 16.04 with the Clearlooks-Phenix theme, too, I got lucky.

Also, apologies for the large number of "the" articles in my text. I hate them. The fact is that there are no articles in Russian and DeepL translator puts "the" everywhere.

**Comment by artenaki** [comment] 2021-10-30 03:15
By the way, another thing I don't like about your text editor (compared to Akelpad, for example): the "close" button in the internal "search/replace" dialogs is too small (smaller than the Windows system buttons). It is also hard to reach with the mouse. I think this is a limitation of your development environment.

I understand, Notepad++ is mostly used by programmers and they prefer keyboard (shortcuts) to mouse (as do Apple users because of the listed in the first post). But let's not forget the mouse? Otherwise, ignoring the mouse can be a preposition to go back to DOS/terminal mode/times.

**Comment by Docteh** [comment] 2021-10-31 05:45
Hi, I am taking liberty of posting the imgur image direct to github. please let me know if you want it taken down. 
![image](https://user-images.githubusercontent.com/190571/139569443-e40d781d-1b43-440d-855f-2cb5f2948a0b.png)
I feel it is better to have the screenshots just here.

If even notepad is doing it, it could be part of the "standard controls" that Microsoft makes available. Interesting quirk.

**Comment by artenaki** [comment] 2021-11-01 04:36
Windows has a long history. Apparently, scrollbars were among the first to be added to the development program. And then this code was not changed for years. The question is, will you "go against the grain", apply some kind of hack to get around the gaps?
That's why it's good to have alternatives.

**Comment by DanielSek** [comment] 2021-11-01 10:37
On Windows this gap is caused by two things:
1. Scintilla window has WS_EX_CLIENTEDGE extended style that adds 2 pixels thick recessed border around window.
2. Additional 2 pixels are used by Tab Control for it raised border.

Removing WS_EX_CLIENTEDGE and extending Scintilla window by 2 pixels in each direction would remove that borders and make it look flatter.

Notepad (at least on Windows 10) doesn't have any additional borders.

See also: Fitts's law

**Comment by artenaki** [comment] 2021-11-02 15:39
Yea, everything works. Even in Notepad++ 7.8.7 on Windows XP. Thanks for the information. Topic can be closed.

**Comment by donho** [comment] 2021-11-02 18:13
@artenaki 
You can close the issue you opened, do you know that?

**Closed by donho** 2021-11-02 18:13 UTC

**Comment by artenaki** [comment] 2022-01-17 19:49
If anyone is interested, I found a file manager for Windows (replacing Total Commander) that has no gap at the scrollbar. It is XYplorer 22.70.
