### ISSUE TITLE
Crash while deleting text

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#10193] opened 2021-07-19 15:02 UTC
### Steps to Reproduce the Issue

1. Open a html file (more than 10MBytes).
2. View -> checked "Word wrap"
3. After selecting some text, press DELETE
4. Program crashed.

### Debug Information
Notepad++ v8.1.2   (64-bit)
Build time : Jul 16 2021 - 01:59:50
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment] 2021-07-22 12:23
Can you provide some sample file?

**Comment by softmgr** [comment] 2021-07-30 02:54
@ArkadiuszMichalski 
See the link for sample file: https://wwa.lanzoui.com/i6PUis0xrbe

**Comment by mere-human** [comment] 2021-08-01 18:52
> @ArkadiuszMichalski
> See the link for sample file: https://wwa.lanzoui.com/i6PUis0xrbe

Can you attach the html file directly to your message without any 3rd party sites?
Just drag and drop it here.

**Comment by ArkadiuszMichalski** [comment] 2021-08-02 22:04
I can't reproduce:
[MUGEN_Manual.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6919866/MUGEN_Manual.zip)

**Comment by softmgr** [comment] 2021-09-01 04:01
> I can't reproduce. Here is above sample `MUGEN_Manual.html` (something around 10.1 MB):
> [MUGEN_Manual.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6919866/MUGEN_Manual.zip)

Checked "Word wrap", select lines 1 to 188 and press Delete.

**Comment by ArkadiuszMichalski** [comment] 2021-09-01 07:55
There seems to be a problem with the HTML lexer for large files, without formating (Normal Text) everything works fine.

**Comment by softmgr** [comment] 2021-09-02 00:26
> There seems to be a problem with the HTML lexer for large files, without formating (Normal Text) everything works fine.

Yes, we can only manually switch to "Normal Text" to prevent the crash, but this is not the default.

**Comment by softmgr** [comment] 2021-09-29 15:49
> There seems to be a problem with the HTML lexer for large files, without formating (Normal Text) everything works fine.

@ArkadiuszMichalski I have tested Notepad++ version 6.8 to the latest version 8.1.5, and all have this crash.

**Comment by softmgr** [comment] 2022-02-06 06:09
@ArkadiuszMichalski 

I found the cause of the problem as follows:

//ScintillaEditView.cpp: 
void ScintillaEditView::setXmlLexer(LangType type)
{
	//...
	//Remove the following code to fix the bug:
	//execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("fold"), reinterpret_cast<LPARAM>("1"));
	//execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("fold.compact"), reinterpret_cast<LPARAM>("0"));
	//execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("fold.html"), reinterpret_cast<LPARAM>("1"));
	// This allow to fold comment strem in php/javascript code
	//execute(SCI_SETPROPERTY, reinterpret_cast<WPARAM>("fold.hypertext.comment"), reinterpret_cast<LPARAM>("1"));
}

**Comment by rdipardo** [comment] 2022-02-07 02:38
> //execute(SCI_SETPROPERTY, reinterpret_cast("fold"), reinterpret_cast("1"));

That would disable code folding for __*every*__ language; it's a global setting.

> //execute(SCI_SETPROPERTY, reinterpret_cast("fold.compact"), reinterpret_cast("0"));

"fold.compact" does nothing when "fold" is already disabled.

> //execute(SCI_SETPROPERTY, reinterpret_cast("fold.hypertext.comment"), reinterpret_cast("1"));

Also does nothing when "fold" is already disabled. By itself, it may be effective in resolving the issue, assuming the sample file contains embedded JavaScript:

|                        |                                                                             |
| :--------------------- | :-------------------------------------------------------------------------- |
| fold.hypertext.comment | Allow folding for comments in scripts embedded in HTML. The default is off. |

Reference: <https://www.scintilla.org/SciTEDoc.html>

**Comment by rdipardo** [comment] 2022-02-07 02:50
My mistake: ` void ScintillaEditView::setXmlLexer(LangType type)` 

Of course the option can be scoped to one lexer at a time. But would users accept that XML markup can never fold?

**Comment by ArkadiuszMichalski** [comment] 2022-02-07 18:46
@donho 
I get two other big files for thest (HTML and DOM spec in one file + op file): [bifgiles.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8017747/bifgiles.zip)
 
A few observations:
 - For files around 2MB (DOM spec) turn of `Word wrap` would help (although the speed still depends on what we delete). I also check SciTE here and it work's fast regardles of `Word wrap`. Maybe in the new Scintilla they significantly improved it.
 - For bigger files turn of `fold` would help (regardles of `Word wrap`). Without this we hang NPP. SciTE treats such files as text files so there is no way to compare.
 
One another question: why when we start NPP with turned off `Word wrap` and turned it ON/OFF our NPP is so slow, it works like `Word wrap` is still ON? Try this with DOM spec file. This happend when we swith `Word wrap` option on oppened file. When we open file after switching all works fine.

**Comment by rdipardo** [comment] 2022-02-08 11:34
>  For files around 2MB (DOM spec) turn off `Word wrap` would help 

#10967

> Maybe in the new Scintilla they significantly improved it.

Of course! Scintilla 5.2.0 will support multi-threaded line layout: <https://groups.google.com/g/scintilla-interest/c/_W6NGQ5WNoE>

> SciTE treats such files as text files so there is no way to compare.

[Notepad2] runs like a dream with the [OP's example file], word wrapping and all:

![notepad2](https://user-images.githubusercontent.com/59004801/152974726-1ccad136-42a6-4055-b673-b2be42a801a3.png)

@zufuliu has already given some suggestions on how N++ could benefit from Notepad2's enhancements: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8802#issuecomment-687200365

[Notepad2]: https://github.com/zufuliu/notepad2/releases
[OP's example file]: https://github.com/notepad-plus-plus/notepad-plus-plus/files/6919866/MUGEN_Manual.zip

**Comment by donho** [comment] 2022-02-08 15:45
@ArkadiuszMichalski 
I cannot reproduce the crash with the files you provided, I will get my old laptop back to reproduce it.

@rdipardo 
Updating Scintilla is on the next revamp, after v8.3.X being stable.

**Comment by ArkadiuszMichalski** [comment] 2022-02-08 15:58
@donho 
Open `html_whatwg.html` or `MUGEN_Manual.html`, scroll file near the end, back to the beginning and try to remove the first few lines

**Comment by softmgr** [comment] 2022-04-29 05:54
@donho  @ArkadiuszMichalski @rdipardo The bug still exists in Notepad++ 8.4

**Comment by rdipardo** [comment] 2022-04-29 08:54
> The bug still exists in Notepad++ 8.4

Multi-threaded layout is not activated in Notepad++ yet: https://groups.google.com/g/scintilla-interest/c/_W6NGQ5WNoE

**Comment by donho** [comment] 2022-04-29 12:57
@ArkadiuszMichalski  Thank you for the hint. I can reproduce the hanging steadily now.

**Comment by donho** [comment] 2022-04-29 13:00
@rdipardo 

Adding `execute(SCI_SETLAYOUTTHREADS, 1000);` into `void ScintillaEditView::init(HINSTANCE hInst, HWND hPere)` doesn't remedy the hanging... (DirectWrite enabled). Maybe I am missing other calls to activate multithread in Scintilla?

**Comment by rdipardo** [comment] 2022-04-29 20:06
> Maybe I am missing other calls to activate multithread in Scintilla?

I only know what's been documented (*).
The developer of [textadept] seem to have [got it working][0] (for GTK on Windows, i.e., using [libwinpthread-1.dll] (**), so may be worthwhile to ask for help: https://github.com/orbitalquark


---
(*)
> [SCI_SETLAYOUTTHREADS] (int threads)
> SCI_GETLAYOUTTHREADS → int
> The time taken to measure text runs on wide lines can be improved by performing the task concurrently on multiple threads when [SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS] is available.
> 
> | | | |
> |:-- | --: | :-- |
> | SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS | 5 | Can text measurement be safely performed concurrently on multiple threads? Currently only true for macOS Cocoa, DirectWrite on Win32, and GTK on X or Wayland. |

(**)  GCC builds of N++ may have to distribute a [3rd party lib], or else use the POSIX-threaded version of MinGW

[SCI_SETLAYOUTTHREADS]: https://www.scintilla.org/ScintillaDoc.html#SCI_SETLAYOUTTHREADS
[SC_SUPPORTS_THREAD_SAFE_MEASURE_WIDTHS]: https://www.scintilla.org/ScintillaDoc.html#SCI_SUPPORTSFEATURE
[textadept]: https://github.com/orbitalquark/textadept
[libwinpthread-1.dll]: https://groups.google.com/g/scintilla-interest/c/zuIitlxjW0E/m/_kUPaaZuCAAJ
[3rd party lib]: https://github.com/meganz/mingw-std-threads
[0]: https://groups.google.com/g/scintilla-interest/c/_W6NGQ5WNoE/m/-iK-QgOgAAAJ

**Comment by zufuliu** [comment] 2022-04-29 22:16
`execute(SCI_SETLAYOUTTHREADS, 1000);` seems wrong (too many threads), `std::thread::hardware_concurrency()` or `GetNativeSystemInfo()` could be used to find max thread count.

**Comment by donho** [comment] 2022-04-30 02:12
@zufuliu 
> execute(SCI_SETLAYOUTTHREADS, 1000); seems wrong (too many threads)

From the [Scintilla document](https://www.scintilla.org/ScintillaDoc.html#SCI_SETLAYOUTTHREADS) : 
"If an application just wants maximum concurrency then call with a large number SCI_SETLAYOUTTHREADS(1000) and that will be reduced to a reasonable value."

OTOH, the following codes seem not better:
```cpp
	unsigned int n = std::thread::hardware_concurrency();
	execute(SCI_SETLAYOUTTHREADS, n);
```

**Comment by donho** [comment] 2022-04-30 02:16
@rdipardo 
Thank you for the info.
I will check the link you provided.

**Comment by softmgr** [comment] 2022-05-02 12:07
> > The bug still exists in Notepad++ 8.4
> 
> Multi-threaded layout is not activated in Notepad++ yet: https://groups.google.com/g/scintilla-interest/c/_W6NGQ5WNoE

I checked source code of Notepad2 and Notepad3. The keyword "SCI_SETLAYOUTTHREADS" was not found...

**Comment by zufuliu** [comment] 2022-05-02 13:00
Notepad2 use custom parallel layout implementation (as discussed at https://sourceforge.net/p/scintilla/feature-requests/1427/) to ensure Windows XP compatibility with VS 2022 (see https://github.com/microsoft/STL/issues/2286).

After test these files with multi-thread disabled in SciTE  (change `threads.layout` to 1 in SciTEGlobal.properties), it appears the problem here is not related to multi-thread layout.
Some checkpoints that I think would improve or fix the problem:
1. layout cache, https://www.scintilla.org/ScintillaDoc.html#SCI_SETLAYOUTCACHE
2. idle styling, https://www.scintilla.org/ScintillaDoc.html#SCI_SETIDLESTYLING
3. monospace ASCII optimization, https://www.scintilla.org/ScintillaDoc.html#SCI_STYLESETCHECKMONOSPACED

**Comment by donho** [comment] 2022-07-25 21:14
Hi guys, please check this PR and confirm me if this issue is fixed: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11946

**Closed** 2022-07-26 13:45 UTC
