### ISSUE TITLE
Supplementary Multilingual Plane

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#1360] opened 2016-01-12 19:36 UTC
Notepad++ seems to have poor support for Unicode characters in the Supplementary Multilingual Plane.

For example, if a file contains the localised language name for Gothic
𐌲𐌿𐍄𐌹𐍃𐌺𐌰 
and if this is converted by another program from UTF-8 to UTF-16LE, the result looks should like this:
𐌲𐌿𐍄𐌹𐍃𐌺𐌰
but when the UTF-16 encoded file is opened by Notepad++, the word is not displayed correctly, but appears as a string of 42 unrendered byte codes, 6 per Gothic character.

I can't show this here without a screenshot.
https://www.dropbox.com/s/x824epzmi04m148/Screenshot%202016-01-12%2019.34.59.png?dl=0

**Comment by xylographe** [comment] 2016-01-13 01:49
See #801 and #903

**Comment by cup** [comment] 2018-10-06 15:44
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1360
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1727
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/801
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/903

**Comment by MetaChuh** [comment] 2019-04-11 00:51
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:51 UTC
