### ISSUE TITLE
Ligature support

### ISSUE THREAD

**Issue by Graucsh** [notepad-plus-plus/notepad-plus-plus#2287] opened 2016-09-15 21:52 UTC
### Description of the Issue

Fonts that support ligatures are not drawn with them
### Steps to Reproduce the Issue
1. Select a font that supports ligatures, such as Fira Code
2. Select a C-based language
3. key in "!="
### Expected Behavior

a long equals sign with a slash through it
### Actual Behavior

discrete characters
### Suggestion

Set the Technology property of the Scintilla objects to DirectWrite, which draws with ligatures, or provide an option to turn it on.

![default](https://cloud.githubusercontent.com/assets/22226368/18569157/f666bb42-7b6e-11e6-96e8-cd6b940e3e6d.png)
![directwrite](https://cloud.githubusercontent.com/assets/22226368/18569193/28329178-7b6f-11e6-8013-28223d189218.png)

**Comment by dail8859** [comment] 2016-09-15 22:55
Duplicate of #1651 

I looked into this at one point and just using `SC_TECHNOLOGY_DIRECTWRITE` is not enough. Notepad++ uses Scintilla v3.5.6 and it seems that a newer version of Scintilla is required to support ligatures. So once Scintilla is updated internally this will most likely be possible.

**Comment by Graucsh** [comment] 2016-10-24 22:19
I added the following line to void Notepad_plus::loadBufferIntoView(BufferID id, int whichOne, bool dontClose):
::SendMessage(viewToOpen->getHSelf(), SCI_SETTECHNOLOGY, SC_TECHNOLOGY_DIRECTWRITE, 0);

I realize that's probably not the right place, but I got the following result using the Fira Code font:

![npp_ligatures](https://cloud.githubusercontent.com/assets/22226368/19666062/31076d1c-9a16-11e6-961d-01dac6ca62df.png)

**Comment by dail8859** [comment] 2016-10-24 23:05
That's interesting. I tried the exact same thing before without any success. Though I tried it on Win7 which might be a difference.

**Comment by Graucsh** [comment] 2016-10-25 14:57
Maybe it makes a difference where the message is sent?
![npp_ligatures_win7](https://cloud.githubusercontent.com/assets/22226368/19691255/a9898a32-9aa1-11e6-9862-0f669d243f42.png)

I put the code after:
MainFileManager->addBufferReference(id, viewToOpen);

**Comment by dail8859** [comment] 2016-10-25 15:01
This is what I tried:

- Install the Fira Code font (I think I used the medium)
- Set the global Notepad++ font to use Fira Code
- Type something like `!=` and nothing happens. (I can see the font is getting changed, it just doesn't seem to pick up on the character sequences at all.)

Can't remember where I put that call in that function, but I'll try exactly where you said and see if that works for me.

**Comment by Graucsh** [comment] 2016-10-25 15:22
I can confirm your results. Only Fira Code and Fira Code Retina draw with ligatures. Light and Medium do not.

**Comment by dail8859** [comment] 2016-10-25 15:36
Success! 

![capture](https://cloud.githubusercontent.com/assets/3694843/19692561/5d53f9f4-9aa6-11e6-98f1-0cdfe04aca64.PNG)

I found I had all the different fonts installed but *none* of them worked...however I installed them a while ago so I downloaded and installed the latest version of the regular Fira Code font and it worked perfectly.

On a side not I don't think it matters when `SCI_SETTECHNOLOGY` is set because I manually changed it by my scripting plugin while a files was already opened and it immediately worked. :)

**Comment by Graucsh** [comment] 2016-10-25 15:39
Fantastic! Thanks for staying with me on this. I really appreciate it!

**Comment by dail8859** [comment] 2016-10-25 15:43
> Only Fira Code and Fira Code Retina draw with ligatures. Light and Medium do not.

Is this something you discovered yourself or is it documented somewhere?

**Comment by Graucsh** [comment] 2016-10-25 15:56
Discovered myself. I just put a != in the editor and flipped through the 4 variants. Your mentioning that you tried the medium got me to thinking.

It may be worth noting that Windows Notepad only lists the regular and retina.  However, the Windows font previewer seems to like them all.

**Comment by wolfheart** [comment] 2016-10-27 07:50
Hmmm... sorry but maybe I'm confused: should this work right now on Windows 10 with Notepad++ v7.1, 32bit, build from Oct 15 2016? Or do I have to wait for an update?

**Comment by dail8859** [comment] 2016-10-27 13:18
It won't currently work "out of the box". The text rendering needs tweaked but you can do it with a plugin. Keep in mind support for ligatures is not officially supported so you might run into issues. 

This is the easiest way I know (without recompiling) to get ligatures to work in Notepad++:

1. Install a recent version of Fira Code (use either the normal font or the retina as those are the only ones that seem to work).
2. Install LuaScript via the Plugin Manager (you can also use PythonScript if you are more comfortable with it or want to use a 10 ton hammer).
3. Select the font via `Settings > Style Configurator > Global Styles > Global Override`. Select "Fira Code" for the font style and turn on `Enable global font`
4. Edit the LuaScript startup file by doing `Plugins > LuaScript > Edit Startup Script` and add the following code:
```
editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
```

Restart and enjoy.

**Comment by wolfheart** [comment] 2016-10-27 13:35
Thanks! Worked like a charm!

**Comment by limingjie** [comment] 2016-12-07 09:08
@dail8859 After using the workaround, font **Iosevka** works, but **Iosevka Light** not.

**Comment by treyharris** [comment] 2017-11-13 17:30
I don't know how OpenType rendering works on Windows, but from work on Mac and Linux I can say that this (standard weight of Fira Code and Iosevka works, nonstandard weights do not) is the expected (and _arguably_ correct) behavior.

In OpenType you specify weight not through font selection but through OpenType variations. Ligatures, too, are supported not through glyph selection (which would require Notepad++ to be aware that "->" becomes the → ligature, etc.) but through glyph variation.

Once you use a non-base weight directly via font selection rather than through variation, you've signaled that you're not using OpenType features (correctly) anyway, so the font doesn't enable them.

So, the solution if you want Fira Code Bold to be your default is to click the "Bold" checkbox in your Style Settings. (Ligatures _are_ preserved in boldface and bold italic text; if you've done the `SC_TECHNOLOGY_DIRECTWRITE` workaround above, you can check this for yourself, by checking Bold in your styles with plain Fira Code or Iosevka and not Light/Bold as your base font. Fira Code Retina is also a base font containing ligatures, bold weight and oblique (italic) variants, so it also works.)

There's no "Light" style checkbox, so there's no way to get that unfortunately, but the correct solution there is for Notepad++ to offer weight selection. The problem is that many (most) coding fonts do not have a Light variant, so the checkbox would do nothing in those cases.

I don't know what, if anything, is lost by making use of the `SC_TECHNOLOGY_DIRECTWRITE`. But if the answer is nothing, it should probably be enabled by default.

**Comment by dail8859** [comment] 2017-11-13 17:51
@treyharris The lower level text drawing is handled by [Scintilla](http://www.scintilla.org/) which is what Notepad++ uses internally. So any technical questions are probably best directed toward that project, especially regarding what `SC_TECHNOLOGY_DIRECTWRITE` does exactly.

> There's no "Light" style checkbox, so there's no way to get that unfortunately, but the correct solution there is for Notepad++ to offer weight selection.

You are correct that Notepad++ does not offer anything to set a "light" version, however the underlying Scintilla control does allow setting a font weight. You can use a scripting plugin (such as LuaScript referenced above) and set the font style to a lighter weight using the call to [`SCI_STYLESETWEIGHT`](http://www.scintilla.org/ScintillaDoc.html#SCI_STYLESETWEIGHT).

**Comment by treyharris** [comment] 2017-11-13 19:01
@dail8859 Then should this issue be closed? If using LuaScript is sufficient, then you can get ligatures and you can get weights, so Notepad++ has "ligature support".

But if using LuaScript _isn't_ sufficient to consider the issue closed, then my point stands—UI is needed or, if Light is not to be provided and it causes no other issues, `SC_TECHNOLOGY_DIRECTWRITE` should be set by default..

**Comment by dail8859** [comment] 2017-11-13 20:08
> Then should this issue be closed?

There isn't official support for ligatures as it stands so I would say this should still be left open.

> SC_TECHNOLOGY_DIRECTWRITE should be set by default

I know in the past there have been issues regarding the quality of the text rendering on certain systems and I'm not sure if changing this would cause any types of problems like that. Scintilla allows different technologies so I would assume there is a good reason why one is better than another in certain cases, but again these technical questions are probably best for the Scintilla project as I don't know how all this works on a detailed level.

**Comment by treyharris** [comment] 2017-11-13 21:26
@dail8859 — thanks. I appreciate the technical question, so I just did a little research into Scintilla.

I checked the [Scintilla bug tracker](http://sourceforge.net/p/scintilla/bugs/) for references to `SC_TECHNOLOGY_DIRECTWRITE`, and there were only a few, none of whose responses discouraged use of it and some of which suggested using it.

According to [the docs](http://www.scintilla.org/ScintillaDoc.html#SCI_SETTECHNOLOGY):

> The technology property allows choosing between different drawing APIs and options. On most platforms, the only choice is `SC_TECHNOLOGY_DEFAULT` (0). On Windows Vista or later, `SC_TECHNOLOGY_DIRECTWRITE` (1), `SC_TECHNOLOGY_DIRECTWRITERETAIN` (2), or `SC_TECHNOLOGY_DIRECTWRITEDC` (3) can be chosen to use the Direct2D and DirectWrite APIs for higher quality antialiased drawing. `SC_TECHNOLOGY_DIRECTWRITERETAIN` differs from `SC_TECHNOLOGY_DIRECTWRITE` by requesting that the frame is retained after being presented which may prevent drawing failures on some cards and drivers. `SC_TECHNOLOGY_DIRECTWRITEDC` differs from `SC_TECHNOLOGY_DIRECTWRITE` by using DirectWrite to draw into a GDI DC. Since Direct2D buffers drawing, Scintilla's buffering can be turned off with `SCI_SETBUFFEREDDRAW(0)`.

So: Scintilla doesn't make it the default because it needed to be unset on non-Windows and on pre-Vista versions of Windows, and it would break downstream clients of the API to make 1 the default now.

That being the case, it sounds like `SC_TECHNOLOGY_DIRECTWRITE` should always be used by Notepad++ on Windows Vista or later, perhaps with an option to disable.

----

By the way, on another note in what I wrote earlier: the difference between Fira Code and Fira Code Retina is that the latter simply has slightly increased weight across the entire spectrum. IOW, the Fira Code Retina 400 weight ("Normal", "Regular", or "Book") is closer to the Fira Code 500 weight ("Medium"), the Fire Code 400 weight is closer to Fira Code Retina's 300 ("Light"), and so on. (This is to address the reason many people set a Bold font as their default in the first place: Retina displays tend to look thinner, particularly for monospaced text mixed with proportional text, like ``SC_TECHNOLOGY_DIRECTWRITE` here.)

**Comment by dail8859** [comment] 2017-11-13 22:05
Thanks for the additional info.

**Comment by jefflomax** [comment] 2018-06-29 13:39
This should NOT have been closed.  Notepad++ should support ligatures out of the box, not thru hacks or adding plugins users neither need nor want.

**Comment by Graucsh** [comment] 2018-06-29 13:59
It wasn't closed. It's still marked as open at the top. It's the referencing articles that have been closed.

**Comment by LesterCovax** [comment] 2018-07-26 07:34
Just an FYI, a recent Windows 10 update ([KB-4340917](https://support.microsoft.com/en-us/help/4340917/windows-10-update-kb4340917)) was supposed to fix OpenType support for Win32 applications, but I tried removing the startup options and it still doesn't work.

**Comment by glen-84** [comment] 2019-02-18 17:36
Why hasn't this been closed as a duplicate of #1651?

**Comment by Flaxarn** [comment] 2019-08-25 12:31
I have a problem in getting Operator Mono Light / light italic ligatures to work.
Ive used kilimans script for making the operator mono font into a ligature font and have it working in sublime3 on macOS and have tested it in windows notepad where it also works.
With above solution to att LuaScript and editing startupscript with 
editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
i have FiraCode working with ligatures but with the operator font it will not make the ligatures + it will break my italic fonts ive selected for my tags.

**Comment by KOLANICH** [comment] 2019-08-28 22:30
https://gitlab.com/KOLANICH/nppDirectWriteEnable

**Comment by sigzero** [comment] 2020-03-23 15:27
Is there any movement on this? I just download the latest SciTE for Windows and it has ligatures on by default. Notepad++ should be on by default as well or at least an option to enable/disable.

**Comment by KOLANICH** [comment] 2020-03-23 20:20
@sigzero, just implement it.

**Comment by xmha97** [comment] 2020-06-08 22:49
> It won't currently work "out of the box". The text rendering needs tweaked but you can do it with a plugin. Keep in mind support for ligatures is not officially supported so you might run into issues.
> 
> This is the easiest way I know (without recompiling) to get ligatures to work in Notepad++:
> 
> 1. Install a recent version of Fira Code (use either the normal font or the retina as those are the only ones that seem to work).
> 2. Install LuaScript via the Plugin Manager (you can also use PythonScript if you are more comfortable with it or want to use a 10 ton hammer).
> 3. Select the font via `Settings > Style Configurator > Global Styles > Global Override`. Select "Fira Code" for the font style and turn on `Enable global font`
> 4. Edit the LuaScript startup file by doing `Plugins > LuaScript > Edit Startup Script` and add the following code:
> 
> ```
> editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
> editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
> ```
> 
> Restart and enjoy.



> It won't currently work "out of the box". The text rendering needs tweaked but you can do it with a plugin. Keep in mind support for ligatures is not officially supported so you might run into issues.
> 
> This is the easiest way I know (without recompiling) to get ligatures to work in Notepad++:
> 
> 1. Install a recent version of Fira Code (use either the normal font or the retina as those are the only ones that seem to work).
> 2. Install LuaScript via the Plugin Manager (you can also use PythonScript if you are more comfortable with it or want to use a 10 ton hammer).
> 3. Select the font via `Settings > Style Configurator > Global Styles > Global Override`. Select "Fira Code" for the font style and turn on `Enable global font`
> 4. Edit the LuaScript startup file by doing `Plugins > LuaScript > Edit Startup Script` and add the following code:
> 
> ```
> editor1.Technology = SC_TECHNOLOGY_DIRECTWRITE
> editor2.Technology = SC_TECHNOLOGY_DIRECTWRITE
> ```
> 
> Restart and enjoy.

It doesn't work, please help me.

**Comment by dail8859** [comment] 2020-06-08 23:01
@xmha97 Since you provide absolutely no additional details there is little-to-no chance someone can help you figure out why it "doesn't work"

**Comment by KOLANICH** [comment] 2020-06-09 20:30
>@KOLANICH Could you please provide a compiled version of you plugin? I'd need it for the x86 architecture. Implementing it yourself is great - if you're able to...

I can, but I don't think for such a **small** and **trivial** plugin it is beneficial. Please, download the source and build it yourself (use MinGW-w64, please, Visual Studio is not trusted after all the "adcidents") if it is feasible for you - you will get better trusted dll (it is a dll, it can contain code, so it can contain malware, so a malicious or hacked CDN or CI can insert malware into the dll you download!) this way. But if you still really want me to build it for you, just say, though don't expect the immediate response or any security or other guarantees.

I'm sorry for this late response, I was offline.

**Comment by Big--Mike** [comment] 2020-06-10 11:59
@KOLANICH Actually I tried that in a way, before posting.

For a small plugin 
- I downloaded Visual Studio Community Edition (several gb of code, bearing the same risks as downloading a compiled dll from github, ok the VS installer is digitally signed...)
- I didn't manage to get the small piece of code compiled and actually couldn't figure out, what was missing. The error messages were about something is wrong with my environment and my preferred search engine was not my friend.
- I uninstalled Visual Studio again and posted

For people who know, what they're doing and already have a working environment, it's for sure better to compile it from the source.
For the average user, it's way more comfortable to get a dll for their system. And at least for hacking the site or the connection to insert malicious code, the risk is the same. And the dll was built from someone who knows what she/he's doing and which compiler security features to enable and which not to reduce the dlls attack surface.

That said, I'm now using LuaScript plugin, which allows to set the settings in a script at startup as described above. It's working fine, but probably your plugin would need less resources. 

For other users, I'd guess, it would probably be a benefit if were providing a compiled version.

**Comment by Big--Mike** [comment] 2020-06-11 07:04
Thank you for the explanation and the instructions on how to build the dll.

**Closed** 2020-06-12 17:41 UTC
Labels: accepted

**Comment by KOLANICH** [comment] 2020-07-02 13:21
BTW, this is how (DAMN SLOW, but works, wine team has implemented ligatures) it works in Wine
[dwrite_npp.mp4.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4864491/dwrite_npp.mp4.zip)

May be somehow related to
```
00c0:fixme:d2d:d2d_device_context_Flush iface 000000000<something>, tag1 0000000000000000, tag2 0000000000000000 stub!
```

**Comment by ValZapod** [comment] 2020-07-29 16:53
> DAMN SLOW

It is not slow. Theu jusf do not flush it and thus it looks like it is slow.

**Comment by AlexBlandin** [comment] 2020-08-11 16:24
Just going to add that on _some_ systems the recommended `SC_TECHNOLOGY_DIRECTWRITE` (the setting used by both the luascript examples and @KOLANICH's plugin) actually makes it really slow and choppy (very low refresh rate and high latency) for some arcane reason I haven't had the time to figure out. Oh, and disabling Scintilla's own BufferedDraw made no discernable difference.

Fortunately, using `SC_TECHNOLOGY_DIRECTWRITEDC` works just fine. GDI to the rescue, I guess. At least I'm able to use ligatures again without wrecking my sanity.

Oh, and this isn't on Wine, this is normal Win10 (1903/18362.959), latest NVidia drivers etc set to prefer GPU for hw-accel. Yeah, a little bizarre, but as I said, I haven't had the time to delve into it. It might be the above flushing problem, it's quite likely to be Win10's fault... idk and honestly idc, I'm glad to finally have a workaround for this.

**Comment by rmmaniac** [comment] 2020-12-07 03:12
I use notepad++ version 7.8.8,  DireteWrite option is available.
from menu->Settinfs->Preferences->MISC->Use DireteWrite,
Use DireteWrite checkcked and I tested JetBrainsMono-Regular.ttf and FiraCode-Retina.ttf both work fine (no LuaScpipt plugins installed)....

**Comment by thomas-ashcraft** [comment] 2021-04-24 06:59
> from menu->Settings->Preferences->MISC->Use DireteWrite,

Note: restart is required to take effect.

**Comment by sasumner** [comment] 2021-04-24 11:32
@thomas-ashcraft 

>>from menu->Settings->Preferences->MISC->Use DireteWrite,

>Note: restart is required to take effect.

Is that unclear in any way?

![image](https://user-images.githubusercontent.com/30118311/115957248-291ec500-a4cf-11eb-93b2-2cd54b7bcee3.png)

**Comment by u01jmg3** [comment] 2021-06-07 19:14
Has anyone else experienced an issue enabling DirectWrite and using the font [Operator Mono](https://www.typography.com/fonts/operator/styles/multi)? The font doesn't appear correctly with this option enabled. It's an OpenType font.

- Top disabled, bottom enabled.

<img width="560" alt="operator" src="https://user-images.githubusercontent.com/1266205/121075283-e68a2100-c7cc-11eb-80d7-d747a21ecdf8.png">

**Comment by ValZapod** [comment] 2021-06-07 19:22
> Has anyone else experienced an issue enabling DirectWrite

Are those even the same font family (i.e how many otfs are there)? Just look into zero number, it is very different.

**Comment by u01jmg3** [comment] 2021-06-07 19:34
Both screenshots are using "Operator Mono Light". The only difference is DirectWrite has been enabled/disabled.

**Comment by mfaizsyahmi** [comment] 2022-03-09 11:46
> Has anyone else experienced an issue enabling DirectWrite and using the font [Operator Mono](https://www.typography.com/fonts/operator/styles/multi)? The font doesn't appear correctly with this option enabled.
> 
>     * Top disabled, bottom enabled.
> 
> 
> <img alt="operator" width="560" src="https://user-images.githubusercontent.com/1266205/121075283-e68a2100-c7cc-11eb-80d7-d747a21ecdf8.png">

I have this exact same problem. When DirectWrite is enabled scintilla just straight up revert to Arial, plus a whole slew of graphical and behaviour glitches.
Considering ligatures are just a "nice to have" and I got Fira Code to work on VSCodium, I'm just gonna cut my losses.

**Comment by Krzysiu** [comment] 2025-02-27 21:47
> Has anyone else experienced an issue enabling DirectWrite and using the font [Operator Mono](https://www.typography.com/fonts/operator/styles/multi)? The font doesn't appear correctly with this option enabled.

It's the same for me with open source Intel One Mono. Works for no-style, different font is used for Medium and Light - yet same for both. In non-DW, it works fine. Font in question is OTF, from https://github.com/intel/intel-one-mono/releases/tag/V1.4.0

Is there some way to get internal SCI message log? Maybe this setting should be market as "experimental"?

![Image](https://github.com/user-attachments/assets/d52fe021-e06e-4ab6-92b0-45bc16bbf8d5)
