### ISSUE TITLE
"#" character can't be written in css files

### ISSUE THREAD

**Issue by tartenpion** [notepad-plus-plus/notepad-plus-plus#3050] opened 2017-03-16 09:08 UTC
### Description of the Issue
When I edit/create a css file and I want to add color to my style, I use "#" before my color like #AFAFAF but in Notepad++, the "#" sign doesn't appear.
I try in a php file, and I saw that when I press "#", that it reduce a group of lines.

It appears with my new installation. Before, I used Notepad++ which was up-to-date and there was no problem. I had an issue with my OS and reinstalled it and now I can use "#" on Notepad++.

### Steps to Reproduce the Issue
1. Open/create a css file
2. Press # key  

### Expected Behavior
When I press # key, # character should appear

### Actual Behavior
In CSS files, nothing appear
In other files type, groups are reduced

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 23:00
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:00 UTC
