### ISSUE TITLE
Crash when recording a macro

### ISSUE THREAD

**Issue by iangunn** [notepad-plus-plus/notepad-plus-plus#2380] opened 2016-10-02 10:37 UTC
### Description of the Issue
In Notepad++ 7 (x64) when recording a macro the application crashes when pressing the comma (",") key. This also appears to happen with other symbol keys but I have not tested them all.

### Steps to Reproduce the Issue
1. Macro -> Start Recording
2. Press COMMA key (",")
3. Error message- "Notepad+++ .... has stopped working"

### Expected Behavior
I expected it not to crash and to continue recording the macro.

### Actual Behavior
It crashed.

### Debug Information
Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment] 2016-10-03 13:35
Duplicate of #2369, #2331, 2310.

This issue has been fixed in 8e9e8c0 and will be available in the next release.

If you need a fix to this until then you can download this nightly release:

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.402/job/0rrtf2da6yxl7389/artifacts

and copy over your notepad++.exe.

**Closed by dail8859** 2016-10-03 13:35 UTC
Labels: duplicate
