### ISSUE TITLE
Word boundary issue with a generic subpattern next to it

### ISSUE THREAD

**Issue by stribizhev** [notepad-plus-plus/notepad-plus-plus#1404] opened 2016-01-25 11:32 UTC
**Description**:

The word boundary as a BOW (beginning of word) does not work properly in Notepad++.

**Current Behavior**: 

Using `\b\w` as a regex pattern, I'd expect Notepad++ to match `h` and `w` in `hello world` string. However, all the letters are matched:

![image](https://cloud.githubusercontent.com/assets/13980887/12549596/96660e64-c35e-11e5-87ea-68c5c775daea.png)

The issue is repro with the following patterns:

```
\b[a-z]
\b\pL
\<[[:alpha:]]
\b[[:alpha:]]
\b[[:alnum:]]
```

I suspect the meaning of a BOW (beginning of word) is lost when there is only a word boundary followed by a generic subpattern (a character class, a shorthand character class, a POSIX character class.

If there is a literal symbol following the word boundary, all works as expected:

```
\bw
```

highlights `w` in `hello world`.

**Expected behavior**: `\b\w` should only match `h` and `w` in `hello world`.

**Note**: The end of word (EOW) meaning works right: `\w\b` matches `o` and `d` in `hello world` as expected.

**Notepad version**: v.6.8.8 Build time: Dec 2015 - 01:11:37

**Comment by MetaChuh** [comment] 2019-04-13 01:48
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:48 UTC

**Comment by stribizhev** [comment] 2019-05-26 14:13
Tried in Notepad++ v.7.7  - the issue still exists. There is no word boundary between `h` and `e`, why does `\b\w` find an `e` match? Try replacing `\b\w` with `x` against a `he` string, and it will be turned to `xx` instead of `xe`.

**Comment by OctaneTwisted** [comment] 2020-02-12 09:04
Issue still present in v7.8.4 64-bit on Windows.

**Comment by sasumner** [comment] 2020-02-12 12:26
Related: #6194

**Comment by sasumner** [comment] 2020-02-12 13:05
@OctaneTwisted This has to do with how multiple searches happen as each search is independent and happens with the starting point being the ending point of the last search.
