### ISSUE TITLE
losing unsaved data during auto-update

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#4729] opened 2018-08-01 15:04 UTC
### Description of the Issue
There have been two reports in the [Community Forum](https://notepad-plus-plus.org/community/) in the last month -- [here](https://notepad-plus-plus.org/community/topic/16031/how-to-recover-lost-unsaved-changes-in-n-and-are-there-any-cloud-backup-for-n) and [here](https://notepad-plus-plus.org/community/topic/16111/lost-unsaved-data-on-open-file-after-upgrade) -- where unsaved data was lost when an automatic upgrade occurred.

Based on the users' expectations, I believe that `☑ Enable session snapshot and periodic backup` was enabled (they expected unsaved data to persist).  In the first, it sounds like the data did persist, but then on reload, the message that changes were made by a foreign program was confusing, and the user chose the wrong selection, and thus lost data.  In the second, the user has confirmed that the backup _was_ enabled, and confirmed there were dialogs once Notepad++ restarted, but does not remember the text of the dialogs.

It would be good if the auto-update triggered a snapshot/periodic backup immediately (possibly even if that option isn't checked), and/or if it offered the option of "wait until I exit Notepad++ before applying update", or at least "do you want to save unsaved changes before updating?"

(I have not had this issue personally, because I save often, and postpone auto-updates until I've made sure files are saved.  I am reporting this as a service to the members of the community forum)

### Steps to Reproduce the Issue

1. be editing one or more files
2. have auto-update run
3. when program reloads, dialogs aren't clear, and the editing in progress is lost

### Expected Behavior

Have no lost data due to auto-update.

### Actual Behavior

Lost data.

**Comment by rmutalik** [comment] 2018-12-07 16:18
I too ran into this same issue. 

I used to have v7.3.3 and was updated to v7.5.9 on my corporate laptop, Windows 10 (64-bit) 1709 (Admin mode OFF).

I had about 18 tabs open and all of them were deleted when Notepad++ auto-updated. I checked Settings > Preferences > Backup for the backup location, ensured that both check boxes  were selected, and went to that location, but there were no files there. 

Is anyone actively trying to fix the issue? Does anyone have any updates on this issue?

Thanks.

**Comment by MetaChuh** [comment] 2019-04-24 22:33
@pryrt 

i can't reproduce an unsaved new tab data loss any more, when performing an update from 7.5.9 to 7.6.6
could you verify this ?

thx

**Comment by pryrt** [comment] 2019-04-24 23:01
I was just relaying the issue described in the forum.  Since I'm on portable now, I cannot try to replicate something triggered by auto-update.

My guess is that if you didn't see the problem, it's fixed...

Sorry I'm not more help.

**Comment by MetaChuh** [comment] 2019-04-24 23:10
ok thx.
i'll close it now as not reproducible as of version 7.6.6.
we can reopen it, if we get another community request.

**Closed by MetaChuh** 2019-04-24 23:10 UTC
Labels: not reproducible
