### ISSUE TITLE
Find previous not working

### ISSUE THREAD

**Issue by bobf32** [notepad-plus-plus/notepad-plus-plus#14438] opened 2023-12-01 21:12 UTC
### Steps to Reproduce the Issue

1. Load a text file
2. Ctrl-F to find some text
3. Enter text to find
4. Hit enter (next occurrence of text is found)
5. Hit Escape to dismiss Find dialog
6. S-F3 to find previous instance of search string

### Expected Behavior
Following the steps above, the prior instance of the seach string should be highlighted

### Actual Behavior
No previous instance is found, and what looks like a context menu pops up extrememly briefly before disappearing.

### Debug Information

Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : C:\Users\XXX\Apps\npp.8.6.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3693
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment] 2023-12-01 21:21
* from step 1: provide sample text file
* from step 3: provide the text
* show screenshot of the _Find_ window at step 4

**Comment by freezer2022** [comment] 2023-12-02 18:38
Probably a duplicate of : 
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14264

**Comment by donho** [comment] 2023-12-02 19:37
@bobf32 
Please provide all the info that @alankilborn asked, then this issue will be opened again, if it's really about a bug.

**Closed by donho** 2023-12-02 19:37 UTC

**Comment by bobf32** [comment] 2023-12-02 20:16
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/6544564/3a768a74-e3c1-404c-acfe-700dbf229ca8)

**Comment by donho** [comment] 2023-12-02 20:46
It does work for me.
