### ISSUE TITLE
Search/Replace Dialogue window bug

### ISSUE THREAD

**Issue by DarceyLloyd** [notepad-plus-plus/notepad-plus-plus#3461] opened 2017-06-30 09:11 UTC
### Description of the Issue
Location: Search window + Search in files window + Replace window.
Issue 1: Resize causes highlight / selection of all text in the input boxes

### Steps to Reproduce the Issue
Open search window

### Expected Behavior
No highlight of input boxes on window resize

### Actual Behavior
Input boxes text is highlighted / auto selected

### Debug Information
7.4.2 32bit

**Comment by irgendsontyp** [comment] 2017-07-01 20:11
I'd like to take a look at this but I cannot reproduce. I downloaded Notepad++ 7.4.2 32-bit 7-Zip edition [here](https://notepad-plus-plus.org/repository/7.x/7.4.2/npp.7.4.2.bin.7z). Neither in this nor the 64-bit version I previously installed via the installer any text within the search dialogs is selected after resizing them. (You're actually talking about resizing the dialogs, aren't you?)

I am running Windows 10, 64 bit.

**Comment by bahusoid** [comment] 2017-07-02 09:38
Suggested fix in #3416 
@irgendsontyp To reproduce it you need to have text saved in combo box list items.

**Comment by DarceyLloyd** [comment] 2017-07-02 10:40
Bug can be seen here: https://youtu.be/sVGGe4I3gjk

If you enter text to replace the auto highlight may not work, if your leaving some inputs as they were from previous session then they highlight.

**Comment by dail8859** [comment] 2017-07-14 20:27
Closed by 0d90ad13747da4f534312e912157a96efdf93151

**Closed by dail8859** 2017-07-14 20:27 UTC
