### ISSUE TITLE
Make all I/O asynchronous

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#913] opened 2015-09-14 07:50 UTC
All disk I/O operations should be made asynchronous. This means that the UI thread remains responsive when the disk access takes longer than an instant. Common cases are disk drives that are currently in standby and need a moment to wake up. My primary drive is an SSD and there's an additional hard disk (10 seconds to wake up) and a NAS drive (up to 30 seconds to wake up). Slow network connections (like a Windows folder share over DSL/UMTS) may also lead to this.

Notepad++ becomes unresponsive and will not update or even show the entire window as long as it's waiting for a disk drive. This includes saving changes to the file, and checking the file for modifications when the minimised window is restored.

I run into this situation every few days, sometimes also a few times a day, depending on my activity pattern.

While the disk operation is in progress, a non-modal (or at least a modal) activity indicator should be displayed. This might be in the status bar like for example in Microsoft Word. So at least the editor window will show up when it's still waiting for a device.

Saving or refreshing files in the background (i.e. allowing the user to continue typing while the snapshot is being saved or checked for updates) would be a welcome bonus but is not required in the first step.

**Comment by sanastasiou** [comment] 2015-09-14 14:53
+1

**Comment by mmetully** [comment] 2015-12-08 01:03
This relates to: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/741

**Comment by shehandavy** [comment] 2016-01-05 04:36
+1

When editing a file off a disk in a remote server, the UI is slow and is sometimes non-responsive.

**Comment by Borkason** [comment] 2016-01-07 08:36
+1

**Comment by javicaballero** [comment] 2017-05-12 15:04
2 years later, still waiting the solution... #1866

**Comment by DDSGooch** [comment] 2018-07-06 08:51
Agreed. Please can you fix this. It's very annoying. Great application otherwise :)

**Comment by MetaChuh** [comment] 2019-04-09 23:48
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:48 UTC

**Comment by ygoe** [comment] 2019-04-10 19:44
@MetaChuh Not fixed, still annoying! Please reopen and assign a priority so that it isn't forgotten about again for the next 3.5 years.

**Comment by Borkason** [comment] 2019-04-10 20:33
Why do you close the issue when it is still relevant? Old age is a weak argument *because* it is still relevant.

**Comment by sasumner** [comment] 2019-04-10 20:50
IMO closure relates to the fact that this isn't ever going to be something considered for Notepad++.  The current design just is the way it is wanted to be by the author and its development team.  Any number of issues can be opened regarding it, but if the design decision has been made they are for naught.  Bottom line, it is just a limitation.

**Comment by Borkason** [comment] 2019-04-10 20:51
@sasumner Until this is confirmed by the team -- which was not -- you are making assumptions.

**Comment by sasumner** [comment] 2019-04-10 22:27
@Borkason Dude, I said "IMO".  The "design decision" = closing of this ticket.

**Comment by MetaChuh** [comment] 2019-04-11 01:25
@sasumner is community team member, and he has the highest reputation of us all.
usually his "assumptions" are facts.

**Comment by mirh** [comment] 2019-04-12 10:19
Then he should do a better job at explaining these "design decisions". 
What kind of compromise would this entail? I cannot see why parallelizing threads and all would hamper anything else. Unless it is just "we haven't time to work on this" of course.

**Comment by Borkason** [comment] 2019-04-12 13:00
> usually his "assumptions" are facts.

@MetaChuh Then he should communicate them as design decisions.

> The "design decision" = closing of this ticket.

@sasumner He communicated something entirely different, though. And putting "IMO" in front of the rest of your sentence makes that ambiguous at best.
