### ISSUE TITLE
Not highlighted internal cmd.exe commands for BAT and CMD files.

### ISSUE THREAD

**Issue by npocmaka** [notepad-plus-plus/notepad-plus-plus#1658] opened 2016-03-19 12:27 UTC
When editing .bat or .cmd files the internal commands are bold and colored in blue (by default).

Though there some command missing ./ not highlighted 

1 . Mklink (available from vista and above)
2. KEYS
3. DPATH (command help message is buggy and  points to APPEND but this is another thing - the command works despite it has not so much uses)
4.PUSHD
5.POPD
6.SETLOCAL
7.ENDLOCAL
8.May be the CMD itself?
9.ASSOC
10.FTYPE
11.START
12.TITLE

Here's a list of internal cmd commands - http://ss64.com/nt/syntax-internal.html 

I suppose it's considering more COMMAND.COM internal commands though some of them are not already internal or are missing in CMD.EXE : https://en.wikipedia.org/wiki/COMMAND.COM

I don't think there are people using COMMAND.COM anymore despite it is still available in 32bit systems. It's time to move on :-) 

Here are the missing in CMD.EXE or not internal commands (and highlighted in notepad++):

1.CTTY
2.CHCP - available in recent Windows versions but not internal anymore.
3. LOADHIGH 
4. COUNTRY (I don't know about such program..)
5. CHOICE (external program - missing in windows XP)
6. LOADFIX (external available only in 32b systems)

As the devices like NUL and CON are highlighted may be conin$ and conout$ also should be highlighted ? ( http://ss64.com/nt/syntax-redirection.html )

PRN , AUX , LPT1 to LPT9 , COM1 to COM9 (lpt and com are highlighted but when used without number which will no cause problems if you try to delete such file)   are also a devices and CMD.exe cannot create a file with such name (try ECHO.>PRN)  despite there are no more com/parallel  port printers.

Some other word that might worth to be highlighted - may be with different WordsStyle (e.g. options)

IF comparators:
1.EQU
2.NEQ
3.GTR
4.GEQ
5.LSS
6.LEQ

FOR /F options

1.skip
2.delims
3.usebackq and useback
4.tokens
5.eol

**Comment by MetaChuh** [comment] 2019-04-13 02:25
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:25 UTC
