### ISSUE TITLE
Encoding when opening empty files

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2947] opened 2017-02-23 17:27 UTC
### Description of the Issue

When opening empty files, the encoding is always "ANSI", although Notepad++ ist set to UTF-8 as standard encoding.

### Steps to Reproduce the Issue

1. open an empty file

### Expected Behavior

When opening empty files, the encoding should be the same as when starting with a completely new file in the editor.

**Comment by vlakoff** [comment] 2017-03-08 22:50
Duplicate of #1874, possible fix in #2997.

**Closed** 2017-05-01 01:14 UTC
