### ISSUE TITLE
Please add keyboard shortcuts back to the "save before close?" pop-up

### ISSUE THREAD

**Issue by fmgppt** [notepad-plus-plus/notepad-plus-plus#7682] opened 2019-12-02 09:41 UTC
As this is my first issue here, please allow me to say how brilliant I find this tool and it is my favorite text/script/code editor to this date.

### Description of the Issue
The title says it all, please put keyboard shortcuts back to the pop-up that shows when closing an unsaved document.
On previous versions, as recent as this year the pop-up was different, however the key element here is that it always had keyboard shortcuts that really helped when handling source code & script experiments/labs and closing multiple tabs in sequence.

### Steps to Reproduce the Issue
1. Create a new document;
2. Type anything in it, for example "bla";
3. Close it (use ctrl+w or ctrl+F4 or just hit the cross )
4. On the pop-up, when I don't want to save changes, I can't use alt+n (for "No") or alt+y (for "Yes") nor any new keyboard shortcut to close it with/out saving.

### Expected Behavior
On step 4 doing the alt+n will trigger the "No" button, and possibly, same for the alt+y for "Yes" as the basics.

### Actual Behavior
Nothing happens, usually inspect if I keyed anything and either mouse click or tab my way to the button I want.

### Debug Information
N/A

Old dialog with shortcuts:
![image](https://user-images.githubusercontent.com/6438604/69948420-859ed000-14e7-11ea-8dfe-61494a7c53f9.png)

New dialog without shortcuts:
![image](https://user-images.githubusercontent.com/6438604/69948479-9cddbd80-14e7-11ea-93fb-b94899e527d7.png)

**Comment by xylographe** [comment] 2019-12-02 09:54
See #7673.

**Comment by sasumner** [comment] 2019-12-02 12:58
Closing as duplicate of #6223.

**Closed by sasumner** 2019-12-02 12:58 UTC
