### ISSUE TITLE
new "save all" dialog is ridiculous

### ISSUE THREAD

**Issue by george-tsiros** [notepad-plus-plus/notepad-plus-plus#10508] opened 2021-09-05 06:57 UTC
![image](https://user-images.githubusercontent.com/54522275/132118358-f56661fa-ba70-4fde-a1f9-1401a2469e14.png)

This is absolutely stupid.

**Comment by laloutre87** [comment] 2021-09-06 13:12
Is that really an appropriate phrasing for filing a bug report on an open source project (and a real one, not a multinational company backed one) ? "ridiculous" made me tick already, but "stupid" is plain rude.

**Comment by ArkadiuszMichalski** [comment] 2021-09-07 15:43
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10339. Will be fixed in 8.1.5.

**Closed by ArkadiuszMichalski** 2021-09-07 15:43 UTC
