### ISSUE TITLE
UTF-8 section symbol (0xC2A7) invokes TIS-620 decoding

### ISSUE THREAD

**Issue by caseif** [notepad-plus-plus/notepad-plus-plus#940] opened 2015-09-21 00:39 UTC
I noticed some strange behavior today with how Notepad++ handles encoding detection: if a file contains 1 or more section symbols (`§`) and no other non-ASCII characters, Notepad++ will decode the file using the [TIS-620](https://en.wikipedia.org/wiki/Thai_Industrial_Standard_620-2533) charset, resulting in each section symbol being decoded to `ยง`. This behavior is entirely inconsistent and does not seem to occur for any other non-ASCII Latin character, and will not occur if other non-ASCII symbols are present in the file.

Edit: I should mention this occurs on multiple machines. all with an English locale active.

**Comment by vladkosi** [comment] 2015-09-21 17:49
This happens for me too when "Autodetect character encoding" is enabled. UTF8 file with letter `á` (U+00E1) and no other non-ASCII characters.

**Comment by honda2** [comment] 2016-05-24 14:57
I have noticed the same problem with paragraph symbol ( § ) being only UTF-8 character in UTF-8 text file... file encoding changes to TIS-620 and wrong characters are displayed around position of original paragraph symbol.

**Comment by malonnnn** [comment] 2016-11-07 01:42
I'd like to maybe bump this thread as the issue is affecting me.

For what it's worth, the section symbol is important to because of minecraft. It is the symbol used to define chat color codes. I say this just to point out that this issue directly affects something that may affect a lot of people, clearly there aren't many comments on the issue so take it as you will.

But is there any chance we can have this fixed? It's currently a deal breaker for me. However, thanks to everyone who contributes, I don't want to sound unappreciative.

**Comment by Pokechu22** [comment] 2017-06-06 02:48
This seems to be a bug within uchardet (which Notepad++ uses for character detection); I've created https://bugs.freedesktop.org/show_bug.cgi?id=101310 for that.

**Comment by njohnson-una** [comment] 2019-01-25 15:39
Seems very broken.  Sometimes it comes up as Thai, sometimes as  ([NAK]).  When [NAK] it seems to believe it's utf-8, but I can still type the character, so it's clearly been read incorrectly.  When Thai it doesn't show the character set TIS-620 and doesn't allow you to switch to utf-8.  When typing a random character from Devanagari, it shows เค.  Does everyone experiences this with every encoding that has non-english characters?

**Comment by MetaChuh** [comment] 2019-04-09 23:43
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Comment by caseif** [comment] 2019-04-10 00:36
Still an issue in 7.6.6, reproducible by creating a file containing nothing but a section symbol with UTF-8 encoding. Surely this issue can be reopened?

**Comment by MetaChuh** [comment] 2019-04-10 00:56
@caseif 

my apologies about that.

this is caused by the uchardet autodetect character encoding routine.
even the latest version of ucardet (only working on linux, verified to be not functioning on windows) has the same issue.

we have not yet been able to find an implementable alternative, which is more reliable than the currently implemented autodetection system.

currently it is, as you know, necessary to disable autodetect character encoding on files like these.

we are sorry about your inconvenience .

**Comment by Gelunox** [comment] 2020-05-09 09:11
I have a UTF-8 file with this exact content:
```yaml
- platform: template
  sensors:
    sun_elevation:
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      friendly_name: 'Sun Elevation'
      unit_of_measurement: 'º'
```
And Notepad++'s autodetect character encoding turns it into TIS-620 on reopening:
```yaml
- platform: template
  sensors:
    sun_elevation:
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      friendly_name: 'Sun Elevation'
      unit_of_measurement: 'ยบ'
```
I'm on version 7.8.5

**Comment by xylographe** [comment] 2020-05-09 11:10
> ... going to [encoding] -> [UTF-8] does nothing ...

Verified with **Notepad++ v7.8.6 (32-bit)**.

**Comment by kleidt** [comment] 2021-08-19 12:51
Still an issue with v8.1.2 (64-bit).

**Closed** 2021-12-27 19:19 UTC
Labels: verified
