### ISSUE TITLE
Failed to save file - Not enough space on disk to save file

### ISSUE THREAD

**Issue by bnbaz** [notepad-plus-plus/notepad-plus-plus#11822] opened 2022-06-22 09:06 UTC
Saving any file to a G:/ location (Google Drive) gives me an error in Notepad++ since the latest version. Windows Notepad does save properly in the same location.

### Description of the Issue
"Failed to save file.
It seems there's not enough space on disk to save file."

### Steps to Reproduce the Issue
1. Install Google Drive App on Windows
2. Right click a folder inside G:/... to create a file
3. Save

### Expected Behavior
I expect the file to save.

### Actual Behavior
File doesn't save.

### Debug Information
Notepad++ v8.4.2   (32-bit)
Build time : May 29 2022 - 16:45:17
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : $COMMAND_LINE_PLACEHOLDER$
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.739
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.1)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppMarkdownPanel (0.5)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.1)

**Comment by M5rcury** [comment] 2022-06-22 17:21
I've just updated to latest, and I don't have Google Drive App running, yet also having these problems. About 25% of files I have open are showing this issue.

**Comment by kevinmcfarlane** [comment] 2022-07-05 10:44
> UPDATE:
> I believe my issue was MS's File Protection and Blocked Folder Access. Although no indications or warning of the blockage(s) were happening until this morning when one notified me. So, this one seems to be on a crappy implementation of Win Security and not NP++. Thanks.

Just happened to me and that fixed it. No popup from Windows but it was on my notifications tab. The same thing happened to me about a week ago with a Microsoft Visual Studio operation.

I think I'll now have to remember to check when something similar happens in other software. This has only started happening recently, so it could be a recent Windows Update at fault.

**Comment by neokeats** [comment] 2022-09-19 16:08
Hi, 
Same here with 8.4.5

**Comment by bnbaz** [comment] 2022-09-29 11:30
@M5rcury have you found a way around this issue? Running as admin doesn't work for me. After disabling Windows focus assist and enabling notifications, I do not see a notification.

@xomx on v8.4.5 now, the issue still persists, also when replacing the .exe with one from the v8.4.5 portable version. No error logs, unsure what the last working version was (v8.4.1 most likely).

**Comment by xomx** [comment] 2022-09-29 12:16
@bnbaz 

> on v8.4.5 now, the issue still persists, also when replacing the .exe with one from the v8.4.5 portable version

???
The "notepad++.exe" file included in a N++ installer and its corresponding portable archive is the same.

Or do you mean replacing it by my special patched 8.4.2 version (see [above](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11822#issuecomment-1164919623)) with enhanced logging capability?

> No error logs,

So you tried my special version and got no such "npplogWriteFileFailedX.log" files, right?

> M5rcury have you found a way around this issue?

Actually he seems to have found the culprit ("UPDATE:   I believe my issue was MS's File Protection and Blocked Folder Access...").

This is also what I think for now about these kind of issues - it is probably caused by an antivirus/firewall.

**Comment by bnbaz** [comment] 2022-09-29 13:09
@xomx sorry, misunderstood your comment. Used the patched version, npplogWriteFileFailed2.log was created:
`2022-09-29 15:00:22  G:\My Drive\bnbaz\file.txt  WriteFile WINAPI failed with ErrorCode: 5 - Access is denied.`
Location is G:\ is Google Drive's virtual drive mounted as G:\

M5rcury's solution doesn't seem to apply: there is no trace of MS File Protection blocking the file in my notifications. I'm not using third party antivirus/firewall, just default Windows 11 Virus & Threat protection.

**Comment by xomx** [comment] 2022-09-29 19:18
@bnbaz 

> 2022-09-29 15:00:22 G:\My Drive\bnbaz\file.txt WriteFile WINAPI failed with ErrorCode: 5 - Access is denied.

So your "Failed to save file. It seems there's not enough space on disk to save file." N++ message reported is misleading here. The real reason is that somebody/something has denied the filedata writing for N++ to that destination.

This log-result is really weird, it means that:
- the previous file-output opening call in N++ succeeded (CreateFile WINAPI with access parameter for both `GENERIC_READ` and `GENERIC_WRITE`)
- but then the real data writing with the WriteFile WINAPI is not allowed!?

I can think of the only way how to achieve this:
- the N++ app successfully opens the desired file-output for the writing
- but then an external app (AV/firewall/shell extension/system hook...) does not permit the file writing via the WriteFile WINAPI

Definitely an outside SW/condition that interferes with N++.

> I'm not using third party antivirus/firewall, just default Windows 11 Virus & Threat protection.

So I bet that this is the culprit here. Maybe you can try to temporarily disable its real-time protection and repeat the saving:
![real-time_protection_OFF](https://user-images.githubusercontent.com/13075183/193122164-7ffd0fe5-9bb7-418d-bf43-2d3507b84464.png)

Because of you are able to write to that destination with common Windows Notepad app, I do not think that this issue is about insufficient user rights. But for surety - you can try the same but with running the N++ as an admin (rightclick -> Run as administrator).

**Comment by bnbaz** [comment] 2022-09-30 06:41
Yes, that's it, in combination with storing the file on G:\

So:
Real-time protection OFF + C:\ -> works
Real-time protection ON + C:\ -> works
Real-time protection OFF + G:\ -> works
Real-time protection ON + G:\ -> fail

Doesn't matter whether I run nppp with admin privileges.

**Comment by xomx** [comment] 2022-09-30 08:51
Now you can try to add an exclusion (Settings -> Update & Security -> Windows Security -> Virus & threat protection -> Manage settings -> Add or remove exclusions -> + Add an exclusion ...) and switch the real-time protection back ON.

But there is also a possibility that it is a Microsoft or Google bug (it does not make any sense to me to allow "a potential threat" to write to C: but forbid writing to your G: ...). Could you also install & test some other similar solution (e.g. DropBox)?

**Comment by laf1043** [comment] 2022-10-30 17:59
In my case, because I have Controlled Folder Access turned on under Virus & threat protection in Windows Security for D: drive where my edited file is, making Notepad++ in the allowed list of apps did the trick for me. Try checking it.

![image](https://user-images.githubusercontent.com/33396955/198893540-4ba08d93-4b74-4c37-9cd3-f7b7d0b68227.png)
![image](https://user-images.githubusercontent.com/33396955/198893598-c3e2261d-131b-4a62-b7f0-dea30f992cae.png)
![image](https://user-images.githubusercontent.com/33396955/198893649-42c09633-1449-498d-9323-1c85969fa505.png)

**Comment by bigplayer-ai** [comment] 2023-01-10 13:01
> In my case, because I have Controlled Folder Access turned on under Virus & threat protection in Windows Security for D: drive where my edited file is, making Notepad++ in the allowed list of apps did the trick for me. Try checking it.
> 
> ![image](https://user-images.githubusercontent.com/33396955/198893540-4ba08d93-4b74-4c37-9cd3-f7b7d0b68227.png) ![image](https://user-images.githubusercontent.com/33396955/198893598-c3e2261d-131b-4a62-b7f0-dea30f992cae.png) ![image](https://user-images.githubusercontent.com/33396955/198893649-42c09633-1449-498d-9323-1c85969fa505.png)

man thanks, adding notepad++.exe in the allowed list saved me.

**Comment by laf1043** [comment] 2023-01-17 22:12
> > In my case, because I have Controlled Folder Access turned on under Virus & threat protection in Windows Security for D: drive where my edited file is, making Notepad++ in the allowed list of apps did the trick for me. Try checking it.
> > ![image](https://user-images.githubusercontent.com/33396955/198893540-4ba08d93-4b74-4c37-9cd3-f7b7d0b68227.png) ![image](https://user-images.githubusercontent.com/33396955/198893598-c3e2261d-131b-4a62-b7f0-dea30f992cae.png) ![image](https://user-images.githubusercontent.com/33396955/198893649-42c09633-1449-498d-9323-1c85969fa505.png)
> 
> man thanks, adding notepad++.exe in the allowed list saved me.

Oh my, so glad that it helped! Errors sometimes complicate things. Glad I remembered I had my folders restricted lol

**Comment by xomx** [comment] 2023-03-09 10:45
@bnbaz 
This issue is resolved, it has nothing to do with Notepad++, the culprit is improper Windows Security settings.
I recommend CLOSING of this issue.

**Comment by donho** [comment] 2023-08-31 23:52
Thank you @xomx for solving people's problem and identifying the cause.
This issue is closed.

**Closed by donho** 2023-08-31 23:52 UTC
