### ISSUE TITLE
Notepad++ generates popups. File not opened

### ISSUE THREAD

**Issue by dvdvideo1234** [notepad-plus-plus/notepad-plus-plus#8260] opened 2020-05-13 07:23 UTC
### Description of the Issue
Right click -> Open with Notepad++

### Steps to Reproduce the Issue

1. Right click on a file
2. Select `Open with Notepad++`
3. Popup appears. File is not opened

### Expected Behavior

The file must be opened

### Actual Behavior

Popup appears and file is not opened

### Debug Information

![image](https://user-images.githubusercontent.com/9112662/81783273-c4f43280-9503-11ea-951e-4c05ee6378ae.png)

**Comment by sasumner** [comment] 2020-05-13 11:56
Is there any reason you ignored the clear instructions in the issue template for providing `Debug Information` ?

```
<!--- In your Notepad++, click on the "?" menu (found to the right of "Window" in the menu bar) -->
<!--- In the menu that drops down, choose "Debug Info..." -->
<!--- A message box will open detailing specifics about your Notepad++ version, plugins, etc. -->
<!--- CLICK ON THE BLUE LINK with the text "Copy debug info into clipboard" -->
<!--- Do a PASTE HERE -->
```

**Comment by dvdvideo1234** [comment] 2020-05-14 07:35
@sasumner

Yes, it happens with every version of Notepad that I install, so I thought it was unnecessary.

Anyways, here you go if you need it:
```
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.267
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 
```

**Comment by ArkadiuszMichalski** [comment] 2021-07-28 13:30
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4368.

**Closed by ArkadiuszMichalski** 2021-07-28 13:30 UTC
