### ISSUE TITLE
Please note, an error stating "The installed version of HTML Tag requires Notepad++ 8.3 or newer.\nPlugin commands have been disabled." displays when starting Notepad++ 8.6 (64-bit) that was updated from previous version.

### ISSUE THREAD

**Issue by RonVorndam** [notepad-plus-plus/notepad-plus-plus#14549] opened 2024-01-05 14:00 UTC
### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by rdipardo** [comment] 2024-01-05 14:28
*Duplicate of #14479*

This only affects plugin versions older than 1.2.3, released in [April 2022](https://bitbucket.org/rdipardo/htmltag/src/v1.2.3/NEWS.textile).

You just need to upgrade the plugin:

![npp-admin](https://private-user-images.githubusercontent.com/59004801/290444896-a8f9c496-99ca-4d84-9cd8-d71ec4a3590c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjQ5MDksIm5iZiI6MTcwNDQ2NDYwOSwicGF0aCI6Ii81OTAwNDgwMS8yOTA0NDQ4OTYtYThmOWM0OTYtOTljYS00ZDg0LTljZDgtZDcxZWM0YTM1OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE0MjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhN2I0NWQyZGMyOWY0NzBlOWVlZGE2OWZiMTMzOWU4ZDNmYzI0MWYyZjNjMTA3ZTU2ZjBkNzAyZWE2N2RlYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6VMXMx2Gg8JcTIKviJxV4drr474yGggvqykuQnqOyG8)

**Closed** 2024-07-11 16:43 UTC
