### ISSUE TITLE
parenthesys missing in debug info

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#14987] opened 2024-04-12 19:34 UTC
### Description of the Issue

parenthesys missing in debug info

![immagine](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59116246/56a4d2d1-9b98-4c41-8ca1-b2ed22d0ed16)

Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Home (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.6)
    DSpellCheck (1.5)
    JsonTools (7.1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by rdipardo** [comment] 2024-04-13 03:56
Duplicate of #14921

**Closed** 2024-04-13 06:43 UTC
