### ISSUE TITLE
MsgBox "Command Line Arguments" not on top

### ISSUE THREAD

**Issue by aks2** [notepad-plus-plus/notepad-plus-plus#4067] opened 2018-01-10 13:41 UTC
### Description of the Issue
click Menu / ? / Command Line Arguments --> MsgBox disapears if Mouse is moved away from this (small) MsgBox-window,

### Steps to Reproduce the Issue
1. click Menu / ? / Command Line Arguments
2. move mouse over underlying (but usually larger) Full-NPP-window (it seems that perhaps "only" the Editor-field (where the file content is displayed) is catching this MouseOver-event, the Menu or Window-title seems to have no effect here).

### Expected Behavior
for "Debug Info" MsgBox it works as expected (not going behind NPP-MainWindow).

### Actual Behavior
Cmd Line Arg - MsgBos goes away (behind MainWindow).
Additionally it can be opened multiple times, which makes no sense at all. Again Debug-Info cannot be open multiple times, 

### Debug Information
Notepad++ v7.5.4   (32-bit)
Build time : Jan  1 2018 - 01:47:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by sasumner** [comment] 2018-01-10 14:22
I don't see the behavior discussed if it is merely a "move mouse over underlying..." action, but if I click on the underlying editor window the Command Line Arguments window definitely does go behind the editor window; whereas the Debug Info box does not (it stays on top) with similar actions performed.  Confirmed about the "opened multiple times" issue.

**Comment by aks2** [comment] 2018-01-10 15:14
I tried again and I have to adjust 1 detail: the magical ROI (region of interest) that causes the going behind. is not the menu-bar, it is the tab-area (where he different filename-tabs are). Please try this detail again (to confirm). I'm sorry that I was not precise in my observation.
Perhaps its addtionally related to Win7 (different Windows version seem to have not identical Mouse-Over behavior sometimes).

**Comment by sasumner** [comment] 2019-08-07 19:53
In addition to the problems already noted, if the `Notepad++ Command Argument Help` window remains open and the user returns to editing within a Notepad++ editor tab view, odd things happen.  

For an example of one, if the user presses ctrl+s to save the active document, it is not saved and a `DC3` character is placed at the current position in the editor buffer.  Another example is ctrl+w to close the active document; in this case an `ETB` character is inserted into the text instead.  Closing out the open `Notepad++ Command Argument Help` window restores normal functionalities for these two examples.

**Comment by xylographe** [comment] 2019-08-07 22:30
In `PowerEditor/src/NppCommands.cpp:2864` replace,
```cpp
::MessageBox(NULL, COMMAND_ARG_HELP, TEXT("Notepad++ Command Argument Help"), MB_OK);
```
with,
```cpp
::MessageBox(_pPublicInterface->getHSelf(), COMMAND_ARG_HELP, TEXT("Notepad++ Command Argument Help"), MB_OK);^M
```
This ONLY helps when the mbox is opened via the **?** menu, not when NPP is invoked with the `--help` argument (see `PowerEditor/src/winmain.cpp:409`).

**Comment by xylographe** [comment] 2019-08-07 23:48
A bit of testing: with `notepad++ --help` in a shell you can still open a new Command Argument Help window with each invocation. However, Ctrl+S and Ctrl+W are not affected.

**Comment by sasumner** [comment] 2019-08-08 12:51
@xylographe How about doing a PR? [Note however that I can't guarantee acceptance because I don't control that.]

OT: Based on your username, do you perhaps use XYPlorer ( https://www.xyplorer.com/ ) as an Explorer replacement?  I do. :)

**Comment by xylographe** [comment] 2019-08-08 18:38
@sasumner Done.

OT: This is the first time I have heard about XYPlorer.

**Comment by sasumner** [comment] 2019-08-08 19:25
@xylographe I don't understand your comments above about invoking with `--help`.  When I do this, all I get is the "Help" dialog box, so there is no possibility for ctrl+s, etc. not to work in the editor window (there is no editor window).  What don't I understand about it?

**Comment by xylographe** [comment] 2019-08-08 20:31
Start NPP without arguments to open the saved session (if any).

Execute `notepad++.exe newfile.txt` in a shell. A new instance of NPP is started, which will pass the file name to the already running NPP instance (unless you set "Multi-instance mode" in Preferences). The first NPP instance will ask you if it should create `newfile.txt`, etc. The second NPP instance will have exited.

Execute `notepad++.exe --help` in the shell. Again, a new instance of NPP will be started, but this time the argument (`--help`) will not be passed to the already running NPP instance. The second instance will open the Help dialogue itself ([winmain.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ab4cf883367eb3818fc0e6dea57d39d21f9ec618/PowerEditor/src/winmain.cpp#L408)). Hence, the first NPP instance will not be affected.

**Closed** 2019-08-10 11:24 UTC
