### ISSUE TITLE
Updater is very annoying

### ISSUE THREAD

**Issue by FlorinAndrei** [notepad-plus-plus/notepad-plus-plus#1916] opened 2016-06-01 17:15 UTC
It happened so many times: I open N++ to do a quick edit, something that should only take a few seconds. But I get a pop-up saying an update is available. I dismiss it. Next time I do a quick update, I get the pop-up again. Next time, again. And again. And again.

Folks, this is wrong. This is an app that is often used for a quick half-minute edit. You can't allow the updater to get in the way like this.

At the minimum, the updater should trigger after a delay. Only if the app has been running for a while (maybe 10 minutes, maybe 1 hour, I don't know), only then trigger the updater.

But ideally the app should run the update in the background. Like Chrome, or other apps that update themselves without bothering the user. I mean, this is the 21st century, why should I, a mere user, have to worry about housekeeping duties like updating every app on my system?

Please - get the updater out of the way. This is a great editor, but the updater is extremely annoying.

Thank you.

**Comment by cmeriaux** [comment] 2016-06-02 05:27
You may read that : 
http://superuser.com/questions/132797/disable-auto-update-in-notepad

**Comment by dail8859** [comment] 2016-06-02 10:51
Duplicate of #1730, #1624

**Comment by FlorinAndrei** [comment] 2016-06-02 17:40
Well, I don't want to turn off auto-updates. I'd like the app to keep being updated. It's just that prompting the user for a house-keeping task, and doing it often, is annoying.

**Closed** 2016-06-29 04:29 UTC
Labels: duplicate, installer

**Comment by FlorinAndrei** [comment] 2016-06-30 17:25
Please note that this is not a duplicate of #1624 or #1730 - those are different topics.

#1624 refers to a simplified update process, but the update is still user-driven, and still requires some reaction from the user.

#1730 is just a one-click user driven update.

What I'm really talking about is a zero-click update. The app should update itself in the background, requiring no attention whatsoever from the user. Don't ask for any click. Don't prompt the user. Do not restart the app. Just look at how Google Chrome is handling updates, and do the same for N++.
