### ISSUE TITLE
French accented characters in find in files

### ISSUE THREAD

**Issue by fasau** [notepad-plus-plus/notepad-plus-plus#7668] opened 2019-11-26 15:17 UTC
### Description of the Issue

With find in files, the accented french characters in files are not found. If I search without thoses accented characters and find the string, accented characters are display with hyphen in search results

### Steps to Reproduce the Issue

1. Create a text file with accented characters
![np1](https://user-images.githubusercontent.com/58222789/69645302-421b1080-1066-11ea-86e9-f664a58ab092.png)

2. **Close Notepad++**. Open it and search in files a string with accented characters. Nothing is found
![np2](https://user-images.githubusercontent.com/58222789/69645365-5bbc5800-1066-11ea-9df8-424c0aed4b12.png)

3. Search in files a string without accented characters. String is found but accented characters are not displayed in search results
![np3](https://user-images.githubusercontent.com/58222789/69645605-b48bf080-1066-11ea-8bcc-1277a938126d.png)

4. If I open the file once in Notepad++ then the search works fine
![np4](https://user-images.githubusercontent.com/58222789/69645926-40058180-1067-11ea-820c-9c94a53bbb91.png)

### Expected Behavior

Finding accented characters at the first attempt

### Actual Behavior

Needing to open the file once for the search to works

### Debug Information

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24002
Plugins : ComparePlugin.dll JsMapParser.NppPlugin.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

Problem also with v7.8, but not with 7.7

**Comment by sasumner** [comment] 2019-11-26 15:24
Does changing this `Preferences` setting do anything to affect the result?:

![image](https://user-images.githubusercontent.com/30118311/69647019-c9509000-1036-11ea-9fd4-5e3676c2404b.png)

**Comment by fasau** [comment] 2019-11-26 15:28
No. Check or unchecked get the same issue

**Comment by xylographe** [comment] 2019-11-26 21:49
@fasau 
Perhaps, disable "Autodetect character encoding"? (also in **Preferences > Misc**)

But the best way to avoid problems with fixed-width 8-bit character encodings is to save all text files in utf8 (**Encoding > Convert to UTF-8**) or utf8-bom (**Encoding > Convert to UTF-8-BOM**) encoding.

**Comment by fasau** [comment] 2019-11-27 09:22
Disable "Autodetect" : same issue

Encoding : it works for this file but it is not a solution for me... I have thousands of files of code in ANSI and I need to keep this encoding.

Thanks

**Comment by fasau** [comment] 2019-12-11 07:36
I don't find any solutions, except convert all my files from ANSI to UTF-8 but it's not possible in my case (too many border effects to check...)
I rollback to version 7.6.6 which works fine.

**Comment by ungesundes-halbwissen** [comment] 2019-12-30 11:15
may be related to #5825 and #5830

**Comment by RyleFury** [comment] 2020-06-17 14:08
We are 3 people to have exactly the same issue on Windows 7 and Windows 10 with the 32 et 64-bit program versions. We don't have another choice than to remain in the version 7.6.6.

The bug occurs only if Notepad++ searches in "not opened" files which are encoded into ANSI. If it searches into UTF-8 (without BOM) "not opened" files with the proper UTF-8 encoding for the accented characters (so real UTF-8 and not ANSI), all the accented characters are recognized without any problem.

So, for me, the "not opened" files are recognized with the UTF-8 (without BOM) format and never in ANSI if there is not a BOM, that’s why Notepad++ can’t understand the encoding of these characters.

Please, this is a major issue which is really nasty and must bother a lot of people using the extended ASCII table. For now, we just can't update Notepad++ because of that.

**Comment by guy038** [comment] 2020-06-17 20:20
Hello, @don-ho, **contributors** and **All**,

### Description of the Issue

In the **Find result** panel, resulting of a **Find in Files** search, **all** lines, of an **`ANSI`** **encoded** file, **not** presently **opened** in current N++ **session**, which **match** the search expression, are displayed **without** any **accentuated** characters, part of these lines !

---

### Steps to Reproduce the Issue

1. Open a **new** document  ( **`Ctrl + N`** )

2. Convert this empty file to **ANSI** encoding (  **`Encoding > convert to ANSI`** )

3. Paste this **French test** sentence : **`Phrase de Test : C'est là, près de la forêt, dans un gîte, où régnait un grand capharnaüm, que l'aïeul ôta la flûte et le bâton de son canoë**

4. Hit the **Enter** key

5. Save it on any location ( **`Ctrl + S`** )

6. Close this file ( **`Ctrl + W`** ) ( IMPORTANT )

7. Open the **Find in Files** dialog ( **`Ctrl + Shift + F`** )

8. Type in the word **`test`** in the **Find what:** zone

9. Type the **complete** filename in the **Filters:** zone

10. Type the **absolute path** to this file in the **Directory:** zone

11. Click on the **`Find All`** button

=> The **`Find result`** panel pops up

---

### Expected Behaviour

The line displayed should be :

Line 1: Phrase de **`Test`** : C'est là, près de la forêt, dans un gîte, où régnait un grand capharnaüm, que l'aïeul ôta la flûte et le bâton de son canoë

### Actual Behaviour

The **present** line displayed is :

Line 1: Phrase de **`Test`** : C'est l, prs de la fort, dans un gte, o rgnait un grand capharnam, que l'aeul ta la flte et le bton de son cano

**Conclusion** : All accentuated characters are **omitted** !

On the picture, below, showing **four** files with **different** encodings, displayed in the **Find Result** panel, *ONLY* text of the **`ANSI`** encoded file is erroneous :-(

![image](https://user-images.githubusercontent.com/12977727/84946226-a5df5680-b0e8-11ea-878b-651ceb051a7b.png)

---

**Remarks** :

- This **only** happens under **three** conditions :

    - A search has been **successful** and the file is **currently** seen in the **`Search result`** panel

    - The file is presently **not opened** in a Notepad++ session ( neither the **main** session nor the **secondary** session )

    - The file must be **`ANSI`** encoded ( **All** tests with other **`Unicode`** encodings are **OK** ! )

---

- In addition, if the search, itself, contained **accentuated** characters, the **Find result** panel did **not** show this **`ANSI`** encoded file !

- It does **not** depend on the **search** mode  ( **`Normal`**, **`Extended`**, **`Regular expression`** )

- It does **not** depend whether the **`Autodetect character encoding`** option is **checked** or **not**

- It does **not** depend whether the **`Use Monospaced font in Find dialog`** option is **checked** or **not**

- This bug occurred, **first**, with N++ version **`7.7`**. So, it could related to the **upgrade** of **Scintilla**, from version **`v3.5.6`** to **`v4.1.4`** ?

---

A work-out, a bit tedious, could be :

- Double click on the **test phrase**, in the **Find result** panel in order to **open** this file in **current** N++ session

- Then, re-run the **previous** **`Find in Files`** search

But that's **out** of the question if you're working with a **lot** of **`ANSI`** files, simultaneously !

---

### My Debug Information

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : D:\@@\787\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Microsoft Windows XP (32-bit) 
OS Build : 2600.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

---

In this regard, you may **refer** also to my post, on **N++ Community** :

https://community.notepad-plus-plus.org/post/55054

Best Regards,

guy038

**Comment by sasumner** [comment] 2020-06-17 20:36
@guy038 
My result from following your steps (except I searched for `Phrase`) are a bit different:  Where you saw _missing_ accentuated characters, I see _boxes_:
![image](https://user-images.githubusercontent.com/30118311/84947710-a7912600-b0b8-11ea-965d-b51264a70449.png)

**Comment by guy038** [comment] 2020-06-18 09:01
Hello @sasumner,

How are you ? Fine, I hope !

Yes, your scrren looks **identical** to the **@atelier-traduction's** one, below :

https://community.notepad-plus-plus.org/post/55038

Don't know why I have **this** bug ... in the bug  ;-)) Surely related to my **`Win XP SP3`** OS !

---

I did further tests and the problem occurs with **any** character between **`\x{0080}`** and **`\x{00FF}`** ( **not** pure **`ASCII`**), in **ANSI** files, **not** presently **opened** in a N++ session !

Best Regards,

guy038

**Comment by donho** [comment] 2020-06-19 15:11
It's a regression of 7.7 (not working) from 7.6.6 (working).
Probably it's due to the Upgrade Scintilla from v3.56 to v4.14.
I'll see what I can do for it.

**Comment by donho** [comment] 2020-06-20 00:27
FYI: It's sure that this bug is due to the upgrade of Scintilla from v3.56 to v4.14.
I just replace SciLexer.dll (4.20) of Notepad++ v7.8.7 by the one (3.56) of of Notepad++ v7.6.6.
The bug disappears.
So far I have no idea to fix it.
If anyone has any idea, please let me know.

**Comment by ungesundes-halbwissen** [comment] 2020-06-20 06:33
All the similar sounding and perhaps related problems reported here (#5825 #5830 #7668 #7773 and perhaos others I haven't found yet) may also be related to Scintilla bugs 2034 and 2151 (https://sourceforge.net/p/scintilla/bugs/2151/ ) - as the latter one was fixed in Scintilla 4.3.1 it might be worth trying replacing the SciLexer.dll with a version >4.3.1 before anything else :-)

**Closed** 2020-06-21 00:18 UTC
Labels: accepted
