### ISSUE TITLE
JS syntax highlight crashes at string template contained `/`

### ISSUE THREAD

**Issue by WinterSilence** [notepad-plus-plus/notepad-plus-plus#11056] opened 2022-01-19 02:24 UTC
**Updated**

### Description of the Issue
JS syntax highlight crashes at string template contained `/` ( for example, in closing tag).

### Steps to Reproduce the Issue

1.  Select HTML syntax
2. Write code:
~~~html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
    <script>
        const text = '...';
        let html = `<div>${text}</div>`;
        document.getElementById('foo').innerHTML = html;
    </script>
</body>
</html>
~~~

### Expected Behavior
JS syntax highlight

### Actual Behavior
syntax highlight crashes at `<div>${text}</div>`

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1466
Current ANSI codepage : 1251
Plugins : mimeTools.dll NppConverter.dll NppExec.dll XMLTools.dll

**Comment by dfs-** [comment] 2022-01-19 07:03
Having no issues in 8.2 with the snippet you provided:
![image](https://user-images.githubusercontent.com/6563013/150080453-245cf940-c9bd-4c73-b0ac-955f901bae06.png)

Can you please try again using a portable build of Notepad++?

**Comment by WinterSilence** [comment] 2022-01-19 08:59
@dfs- thanks, my fail, I'm simplified example and missed an important moment

**Comment by ArkadiuszMichalski** [comment] 2022-01-19 10:00
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822.

**Closed by ArkadiuszMichalski** 2022-01-19 10:00 UTC
