### ISSUE TITLE
Open double extension files with syntax highlighting

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#3366] opened 2017-06-06 08:53 UTC
I can't set notepad to open files with double extension as one of languages (using style configurator).
Example: c.m4, xml.m4...

**Comment by kirsan31** [comment] 2018-03-23 11:10
Yea, it's very annoying, for example in log files:

> log.20180323.log

Strange to have this bug so long...

**Comment by ArkadiuszMichalski** [comment] 2021-08-19 10:23
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10405.

**Closed by ArkadiuszMichalski** 2021-08-19 10:23 UTC
