### ISSUE TITLE
Sorting or searching for a language in the style configurator

### ISSUE THREAD

**Issue by wanderinformatiker** [notepad-plus-plus/notepad-plus-plus#11421] opened 2022-03-21 09:00 UTC
### Description of the Feature Request
I had an idea for improving the style configurator.

I thought that the language list could be sorted alphabetically. This would be helpful to find your language. Currently for example asp is below of JavaScript in my list.

So if you search for not so common language you are not sure if you overlooked it, or if it just does not exist in the list.

Alternatively a search function would also help.

### Debug Information
Notepad++ v8.3.3 (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

![styleConfigurator](https://user-images.githubusercontent.com/46416013/159230383-55c9c3d2-56d5-4e26-b08d-d09fae98b47d.png)

**Comment by CennoxX** [comment] 2022-03-21 12:16
duplicate of #11337

**Closed** 2022-03-21 12:52 UTC
Labels: duplicate
