### ISSUE TITLE
Replace dialog [x] In selection checkbox greyed out

### ISSUE THREAD

**Issue by icefront** [notepad-plus-plus/notepad-plus-plus#9904] opened 2021-05-24 14:21 UTC
### Description of the Issue

Replace dialog [x] In selection checkbox greyed out.

### Steps to Reproduce the Issue

1. Open Notepad++, open a file
2. Select multiple lines
3. Hit Ctrl+H to open the Replace dialog. The main Notepad++ window has to be clicked and then again the Replace dialog in order to enable the [x] In selection checkbox.

### Expected Behavior
When a selection is present in the editor, [x] In selection should be enabled.

### Actual Behavior
[x] In selection is disabled when first opening the dialog.

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : E:\Tools\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppSnippets.dll XMLTools.dll 

### I was working several versions ago

This behavior is accidentally introduced withing a few versions back. In the past it was working as expected.

**Comment by sasumner** [comment] 2021-05-24 14:54
Closing as duplicate of #9611

**Closed by sasumner** 2021-05-24 14:54 UTC
