### ISSUE TITLE
Bookmarking lines by searching marks wrong lines

### ISSUE THREAD

**Issue by farosch** [notepad-plus-plus/notepad-plus-plus#6087] opened 2019-08-22 12:35 UTC
![image](https://user-images.githubusercontent.com/22905106/63514880-ee8aab00-c4e9-11e9-97cf-9d331ec8d0c2.png)

When searching and setting bookmarks at the same time the bookmarks are put at the wrong line.

### Steps to Reproduce the Issue

1. Open search
2. Search for something and automatically bookmark lines
3. Every line x that contains the keyword is being marked in red
4. Bookmarks are not set at line x, but line x-1 instead

**Comment by sasumner** [comment] 2019-08-22 13:03
Not reproducible in N++ 7.7.1.

Follow the template; provide your debug info so we can tell for sure what version you are running on.

Provide a real snippet of copyable text (not just a screenshot) that this will reproduce on for you, so that others can attempt to duplicate.  (The screenshot is good though to see your other settings!)

**Comment by Ekopalypse** [comment] 2019-08-22 13:04
Does not happen to me
![image](https://user-images.githubusercontent.com/47723516/63516724-0dcf0b80-c4dd-11e9-847e-cbf0f0aa20fe.png)

using
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

I guess there is a need to have more information which could be used to replicate your behavior.

**Comment by sasumner** [comment] 2019-08-23 12:30
Closing because 2 users that tried can't replicate the problem behavior, and because OP has had ~24 hours to produce a more complete example that replicates and hasn't done so.  Remaining flexible to reopen if more info is provided...

**Closed by sasumner** 2019-08-23 12:30 UTC
