### ISSUE TITLE
no foreground color options in selected text color style

### ISSUE THREAD

**Issue by jbrosecity** [notepad-plus-plus/notepad-plus-plus#1314] opened 2016-01-03 01:20 UTC
I am new to Notepad++. I have been using Textpad for many years but I recently got fed up with them because they have never taken the rather obvious suggestion of allowing one to scroll font size up and down like almost every other Windows application. For aging eyes this is a must. I found Notepad++ does this and a whole lot more. I have spent some time in Style Configurator and am pretty happy with all the options, except that for some reason when I highlight or select any given text the font color or foreground remains the same. In most applications, as in Textpad, when you select text this applies the background color and the foreground goes to white. Even in the Style Configurator window itself, when any item under Style is selected the item is highlighted in blue and the text changes to white. It would be almost impossible to read it if it remained black. Even as I type this request, if I select a word the black font changes to white under the blue selection color. I’m working around this in NPP by using a fairly light color for highlighting, so I can still read the black through it, but I would prefer a darker highlighting with white font or foreground. Hope someone adds this rather obvious option soon.

**Comment by MetaChuh** [comment] 2019-04-11 01:10
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 01:10 UTC

**Comment by sasumner** [comment] 2021-04-30 12:02
So this issue and others of its type will no longer be considered as the Notepad++ author has made a final decision not to support it.  That decision is documented here:  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9817#issuecomment-829785774

Any new issues on this topic will be immediately closed with a link to the final decision.
