### ISSUE TITLE
Does not display some unicode characters unless another unicode character is on the line

### ISSUE THREAD

**Issue by vividn** [notepad-plus-plus/notepad-plus-plus#1621] opened 2016-03-12 05:54 UTC
Very bizarre behavior. Some unicode characters are not displayed in NP++ (working in UTF-8 encoding). However, if another unicode character that is normally displayed (but still a special character) is entered somewhere on the missing character's line, the original non-displayed character is rendered. The effect is entirely line specific.

For example
"∈" appears as "▯"
but "∈→" appears as "∈→"

The characters I've found to display this behavior (by no means an exhaustive list):
⌊⌋⌈⌉⊋⊃⊆⊂∉∈∃☞↳

**Comment by Marcono1234** [comment] 2016-11-15 14:27
Can confirm for Windows 10 Notepad++ v6.7.3

Looks like it affects characters between U+2000 and U+2FFF (both inclusive), but could be more as well.

Here are some characters I found:

- ∧ (U+2227) to ∫(U+222B) are displayed
- ∧ (U+2227) to ∪ (U+222A) are displayed and display characters in front of them
- ← (U+2190) to ↕ (U+2195) are displayed
- ← (U+2190) to ↓ (U+2193) are displayed and display characters in front of them
- ⿰ (U+2FF0) to ⿻ (U+2FFB) are displayed and display characters in front of them

When brackets are highlited characters which render because they have one of the characters listed above behind them stop rendering again. Try for example moving the cursor between the following characters:
`∦(∦{∦[⿰`
You will see that every time a bracket is highlited the characters in front of it stop rendering.

**Comment by caseif** [comment] 2018-02-27 19:28
Confirming the exact behavior @Marcono1234 described for v7.5.4 on Windows 10 1709.

**Comment by MetaChuh** [comment] 2019-04-13 02:32
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:32 UTC

**Comment by Marcono1234** [comment] 2019-04-20 21:26
@MetaChuh can you please reopen this issue. The behavior I described in my comment from 2016 is still (mostly?) the case in 7.6.6.

E.g. writing `∦(∦{∦[⿰` and then moving the cursor through the string causes the characters to not render. Additionally some character like `⁇` do not render, however when combined with another character (`⁇⿰`) they are rendered correctly.
