### ISSUE TITLE
Regexp search for empty line works, but not Count

### ISSUE THREAD

**Issue by ciufudean** [notepad-plus-plus/notepad-plus-plus#5661] opened 2019-05-16 12:37 UTC
### Description of the Issue
Regexp search for empty line using pattern `^$` works, but Count returns 0.

### Steps to Reproduce the Issue
self explanatory

### Expected Behavior
Count should work

### Actual Behavior
Count returns 0

### Debug Information

![image](https://user-images.githubusercontent.com/19208954/57854251-775dc080-77f0-11e9-9ca6-e3abf23e5525.png)

**Comment by sasumner** [comment] 2019-05-16 12:48
For some reason zero-length matches (another example `(?=.)`) do not contribute to the count.

Workaround For the OP's specific example, do a Find-what of `^\R` and press Count button.

**Comment by sasumner** [comment] 2020-06-09 15:25
Closing as duplicate of #7896
It was a judgement call on which one to close and which one to leave open.
This one was earlier but there was more conversation into the other one...

**Closed by sasumner** 2020-06-09 15:25 UTC
