### ISSUE TITLE
Multi-line Tab Bar - move a Tab 

### ISSUE THREAD

**Issue by Eld0r** [notepad-plus-plus/notepad-plus-plus#917] opened 2015-09-15 09:44 UTC
Hi,

dragging the active Tab to another line causes the lines to swap places.
Dropping at a specific location is difficult cause this happens each time the mouse pointer moves.

Eld0r

**Comment by h-h-h-h** [comment] 2015-09-17 00:31
I can reproduce this bug (v6.8.3). It looks like a kind of flicker.

**Comment by dail8859** [comment] 2017-02-21 20:46
Closed by 9967c59912a05bfac57854e583d573877fdcb787

**Closed by dail8859** 2017-02-21 20:46 UTC
