### ISSUE TITLE
Plugins->Mime Tools->Base64 Encode and Decode not working correctly

### ISSUE THREAD

**Issue by mfoldbjerg** [notepad-plus-plus/notepad-plus-plus#11690] opened 2022-05-18 10:21 UTC
### Steps to Reproduce the Issue

1.  E.g. insert text: test_test in empty document
2. Select all text. Choose Plugins->Mime Tools->Base64 Encode. Result: dGVzdF90ZXM
3. Try reversing the encoding. Choose Plugins->Mime Tools->Base64 Decode. Result: test_te

### Expected Behavior

That base64 encode followed by base64 decode would result in the original text

### Actual Behavior

See above

### Debug Information

Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by tarkett2018** [comment] 2022-05-18 11:00
Duplicate #11661

**Comment by dail8859** [comment] 2022-05-18 12:04
Closing as a duplicate of #11661. Additional information or questions can be posted on that issue.

**Closed by dail8859** 2022-05-18 12:04 UTC
