### ISSUE TITLE
localization.cpp: "{ 0, 12, -1, "file-closeMore" }," to "{ 0, 13, -1, "file-closeMore" },"

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#3629] opened 2017-08-18 20:37 UTC
For localizing `Close More` in 7.5.

Thank you.

**Comment by SinghRajenM** [comment] 2017-08-20 15:00
@Yaron10 ,
As you already know the root cause and solution too, why don't you create a PR for this?

**Comment by Yaron10** [comment] 2017-08-20 17:07
Hello @SinghRajenM,

I once tried to submit a PR and the procedure was quite a mess.
I should find some time to look into it.
Could you please submit this one?
Thank you.

And may I seize the opportunity and refer you to an [old forgotten issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3396#issuecomment-308406769)? :) :)

Best regards.

**Comment by rddim** [comment] 2017-08-20 19:56
`Close More`, `Recent Files` and sometimes `Restore Recent Closed File` are not showed as translated

**Comment by Yaron10** [comment] 2017-08-20 20:40
@rddim,

`Recent Files` and `Restore Recent Closed File` are an older and more complex issue.

**Comment by SinghRajenM** [comment] 2017-08-21 18:30
>Could you please submit this one?

Sure, I will do it.

> And may I seize the opportunity and refer you to an old forgotten issue? :) :)

Oh sorry, I completely forgot this one. I will check it soon.

**Comment by Yaron10** [comment] 2017-08-22 00:14
@SinghRajenM,

Thank you for submitting the PR.
And special thanks for looking into the other issue. I appreciate that.

Best regards.

**Comment by dail8859** [comment] 2017-08-22 21:54
Closed by 2efd5682e8be6426767dc5c1fbd36ac2b601dff1

**Closed by dail8859** 2017-08-22 21:55 UTC
