### ISSUE TITLE
Display of UNICODE characters is inconsistent

### ISSUE THREAD

**Issue by brewmanz** [notepad-plus-plus/notepad-plus-plus#5513] opened 2019-04-10 19:36 UTC
This is a repost of #813 which was incorrectly (in my opinion) closed.

Testing with ⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙ , UTF-8 Encoding and various fonts (via Settings - Style - Theme Default - Language Global - Style Default Style - Font Style - Font name ...

### Expected Behaviour
Consistent display of UNICODE characters for all fonts (not just MS Gothic)

### Actual Behaviour
With Lucida Console, splitting in middle (5 - 5) then the second line becomes 5 blocks
Splitting 4 - 6 then both lines ok
Splitting 2 - 8 then FIRST line becomes 2 blocks
I can split it anywhere, when using MS Gothic, and it displays properly before and after line split.

### Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by AgostinoSturaro** [comment] 2019-04-10 21:15
_How to reproduce_
Open a new Notepad++ file, set the encoding to UTF-8 and paste these symbols ([Double Arrow Unicode](http://unicode-table.com/en/search/?q=Double+Arrow) characters) on the first empty line
⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙
Position the cursor before the last two characters and enter a newline, like this
⇐⇑⇒⇓⇔⇕⇖⇗
⇘⇙
The last two characters should turn into blocks.
![notepad unicode character corruptuion](https://cloud.githubusercontent.com/assets/1441393/9518640/924a17f2-4cb8-11e5-8613-74012a88d8dd.png)

**Comment by Ekopalypse** [comment] 2019-04-10 21:39
Is this really an npp issue? If a font can't provide a glyph and the possible fallback fonts can't either
how could npp be blamed? I must admit, that I don't really understand this fallback font mechanism completely.
![image](https://user-images.githubusercontent.com/47723516/55915257-cc4a5d80-5bd8-11e9-9f9c-2b393f1011a7.png)

**Comment by brewmanz** [comment] 2019-04-11 00:33
@Ekopalypse the font can, and does, display the glyph. IOW this problem is not because the font cannot display the character. It may well be a fallback font that IS displaying it, but again, sometimes it does and sometimes it doesn't. FWIW with this example, MS Gothic seems to ALWAYS work. 
But, when the line is split, either first few, or last few, characters are replaced with the block character, as shown in @AgostinoSturaro post.
It might be related to #4056 which also has "now you see it, now you don't" behaviour (I have not investigated it, only seen the post).

**Comment by Ekopalypse** [comment] 2019-04-11 09:08
@brewmanz @AgostinoSturaro 
Sorry for the confusion, I think I got it now. 
By using the same font, the missing glyphs are not representable in certain combinations of usage,
like @AgostinoSturaro showed, but otherwise it works. Very strange, indeed.

**Comment by MetaChuh** [comment] 2019-04-12 19:53
@brewmanz 

thank you for your detailed information. 

verified and reproducible on 7.6.6.
(see screencast below)

* open up the attached file: [#5513 brewmanz, Display of UNICODE characters is inconsistent.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/3073709/5513.brewmanz.Display.of.UNICODE.characters.is.inconsistent.txt)
* position the cursor e.g. before the last two characters and press <kbd>enter</kbd>.

the characters in the second line will now be displayed as a square.
if the line feed is removed, all characters will be displayed correctly again.

notes:
* reloading of the file or reopening notepad++ does not make any difference.
* fonts like ms gothic do not produce this issue.

![#5513 brewmanz, Display of UNICODE characters is inconsistent](https://user-images.githubusercontent.com/45773305/56044548-aee3d380-5d3f-11e9-8436-3b1eb461eb58.gif)

<kbd>Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Users\User\Desktop\npp.7.6.6.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll</kbd>

<kbd>Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Users\User\Desktop\npp.7.6.6.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll</kbd>

ps: our apologies for closing the original issue, and thanks for your help by testing this on 7.6.6. and re-filing this issue.

**Comment by ValZapod** [comment] 2020-05-26 03:49
This is just continuation of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3747

**Comment by AgostinoSturaro** [comment] 2020-05-26 10:07
@ValZapod This is actually the reincarnation of #813 which was closed "due to its age" a.k.a. "so old it must have fixed itself".
It's old but it was never fixed.

**Comment by sasumner** [comment] 2020-09-25 20:36
Closing as it seems to be working in N++ 7.8.9 with the "direct write" preference enabled.

**Closed by sasumner** 2020-09-25 20:36 UTC
Labels: verified

**Comment by AgostinoSturaro** [comment] 2020-09-28 19:53
@sasumner Where can I find this preference you speak of?
Why should this bug be present when it's not enabled?

**Comment by sasumner** [comment] 2020-09-28 20:11
@AgostinoSturaro 

It's not hidden if you care to look around the Preferences:
![image](https://user-images.githubusercontent.com/30118311/94480666-a4700080-01a4-11eb-8ea8-0b6f5d310ecd.png)

>Why should this bug be present when it's not enabled?

Changing times, changing technologies...
When this bug was filed, Direct Write wasn't available in Notepad++.

**Comment by AgostinoSturaro** [comment] 2020-10-11 15:43
I'd like to reopen this.
The characters render correctly without the option too.
They still go bad when a newline is added.
This is not a simple rendering problem.

_How to reproduce_
Open a new Notepad++ file, set the encoding to UTF-8 and paste these symbols ([Double Arrow Unicode](http://unicode-table.com/en/search/?q=Double+Arrow) characters) on the first empty line
⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙
Position the cursor before the last two characters and enter a newline, like this
⇐⇑⇒⇓⇔⇕⇖⇗
⇘⇙
The last two characters should turn into blocks.
![notepad unicode character corruptuion](https://cloud.githubusercontent.com/assets/1441393/9518640/924a17f2-4cb8-11e5-8613-74012a88d8dd.png)

**Comment by ValZapod** [comment] 2020-10-11 15:46
@AgostinoSturaro This is a duplicate of #3747 that is still open.

**Comment by AgostinoSturaro** [comment] 2020-10-11 15:50
@ValZapod I first reported this with #813 (a long time ago)
Thanks for the tip. I'll add my comment it there.

**Comment by ValZapod** [comment] 2020-10-11 15:52
#813 is also a duplicate of #3747. As well as 12 other issues.

**Comment by donho** [comment] 2020-10-12 03:38
@AgostinoSturaro 
After applying the solution provided by @sasumner, it does work for me:

![image](https://user-images.githubusercontent.com/90293/95702591-0f154780-0c4d-11eb-93f0-17d61936af3b.png)

**Comment by sasumner** [comment] 2020-10-12 11:35
It is probably tied to font choice, but at the end of the things isn't it going to be "Scintilla dependent", that is, nothing that Notepad++ itself can do about it?

**Comment by charliehoward4dp** [comment] 2020-10-19 03:13
Yes, this fixed the problem.  (I'm one of the people who reported it several years ago.)  Thank you!
