### ISSUE TITLE
Open Unsaved File in New Instance

### ISSUE THREAD

**Issue by markvincentcaro** [notepad-plus-plus/notepad-plus-plus#4423] opened 2018-04-18 01:10 UTC
Being able to Move a file to a new instance of Notepad++ is very useful when working with dual monitors.

However, you are only able to do so with a Saved file (the file already exists on your machine).

With Newly Created files, you first have to Save them before you can open them in a new instance of Notepad++, which is a bit cumbersome when you do not plan to keep said files in the first place.

Can this feature be implemented in the future?

**Comment by SinghRajenM** [comment] 2018-11-10 16:04
Somewhat duplicate of #4396

**Comment by donho** [comment] 2019-04-10 15:01
Unfortunately, such limit cannot be removed.

**Closed by donho** 2019-04-10 15:01 UTC
