### ISSUE TITLE
regex counts error: pattern ^ or $ counts 0 but can be found and replaced

### ISSUE THREAD

**Issue by noisnemid** [notepad-plus-plus/notepad-plus-plus#3078] opened 2017-03-20 05:31 UTC
version 7.3.3 x64, win10x64
try to input 

^

or 

$

in "find" dialog box, and press "count", you got:

0 matches

but, if you try

^.*$

you got the number of the lines.

and, if you try replace them(^ or $) with some strings, of course it will be successful.

btw, in 'mark' dialog tab, the 0 width positions would not be displayed. if you don't consider this as a bug or feature, just ignore this 'mark,find-all' one.

plz check it.

**Comment by nplusplus** [comment] 2017-03-21 11:19
Npp 7.3.3, 32-bit on MS Windows 7, 64-bit

To clarify this a bit (per my experience):

In the "Find" dialog, entering ^$ in the "Find what:" field followed by clicking "Find Next" yields a response of "^ zero length match".  Clicking "Count" yields "Count: 0 matches" at the bottom of the Find dialog.

This is the first time I have actually tried to use Count, so I am unsure if the above attempted use ever worked, and if so, when it broke.

Thank you,
Nathan

**Comment by sasumner** [comment] 2020-06-09 15:27
Closing as duplicate of #7896
It was a judgement call on which one to close and which one to leave open.
This one was earlier but there was more conversation into the other one...

**Closed by sasumner** 2020-06-09 15:27 UTC
