### ISSUE TITLE
Seachrched empty lines with regex are not counted properly

### ISSUE THREAD

**Issue by martinrotter** [notepad-plus-plus/notepad-plus-plus#4051] opened 2018-01-05 13:04 UTC
### Description of the Issue
Notepad++ does not properly find empty lines when regex "^$" is used.

### Steps to Reproduce the Issue
1. Open fil with some blank lines (no characters on line except for EOL).
2. Open "find" dialog, switch to regex mode, enter "^$" as search phrase, hit "Count" button.
3. Notepad++ reports that count of found strings is 0, which is wrong.

**Comment by DavidHansen-0x454d43** [comment] 2018-01-05 13:24
I'd maybe describe this as "Notepad++ does not properly **count** empty lines when regex "^$" is used."

In my testing, the lines are found (with 'Find Next' or 'Find All'), they just are not counted (when clicking on the 'Count' button). 

As a possible workaround @martinrotter, you could click 'Find All in Current Document', and then the results window will have the count. e.g. 'n hits in 1 file'

**Comment by sasumner** [comment] 2018-01-06 13:34
Without commenting on the issue itself, I'd say the proper way to do this search/count is with the regular expression `^\R`

**Comment by sasumner** [comment] 2018-01-06 14:10
I think the overall "problem" is that the Count feature doesn't count a match if if has zero-length.  Since matches to `^$` are purely assertions, they are zero-length matches (you can see the little popup that is shown for that when doing an interactive find).  So for instance if one searches for `\b` (word boundary assertion) a similar thing occurs.  I don't know if this an intentional way for the Count feature to work or not.  I can live with it working the way it does (think of it as "Count non-zero length matches" -- maybe that was considered and discarded because it wouldn't fit on the button.  :-D

**Comment by sasumner** [comment] 2020-06-09 15:26
Closing as duplicate of #7896

**Closed by sasumner** 2020-06-09 15:26 UTC
