### ISSUE TITLE
changing timezone causes all files to appear changed

### ISSUE THREAD

**Issue by ennorehling** [notepad-plus-plus/notepad-plus-plus#215] opened 2015-06-14 20:47 UTC
changing the windows timezone brings up the "this file has been changed by an external program" dialog for every open file. it looks like the timestamp comparison is not taking timezones into account?

**Comment by donho** [comment] 2015-09-20 14:48
Have you the instructions to reproduce this bug?

**Comment by milipili** [comment] 2016-06-24 02:20
Indeed the timezone is not taken into consideration. To avoid that n++ should work with UTC timestamps.
#792 show the way to fix the problem, even if I don't think that calling `_tzset` each time is the best way to fix that.

**Comment by fplatel** [comment] 2017-03-05 21:49
I have the same issue : I travel a lot for my job, and I don't often shutdown my laptop : I only use hibernation. Each time I change my timezone, notepad++ ask me to reload each file, I suppose it sees that the local time for last modified is different, it should perform checking against universal time, not local time.

**Comment by mzso** [comment] 2017-03-06 08:05
I think it shouldn't be based on time at all, but actual changes. Time is
unreliable, and accurate time is not always available.

2017. márc. 5. 22:49 ezt írta ("fplatel" <notifications@github.com>):

I have the same issue : I travel a lot for my job, and I don't often
shutdown my laptop : I only use hibernation. Each time I change my
timezone, notepad++ ask me to reload each file, I suppose it sees that the
local time for last modified is different, it should perform checking
against universal time, not local time.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/215#issuecomment-284265796>,
or mute the thread

**Comment by milipili** [comment] 2017-03-06 09:59
I don't think you want that n++ spends its time performing checksums, especially when the opened files are big. However, n++ should definitively take the timezone into consideration when comparing timestamps. It does not matter if the timestamp is correct or not, the only thing that matters is that it has changed or not.

**Comment by ColColonCleaner** [comment] 2017-12-11 05:04
Just hit this today as I changed timezones. If this could be looked at I would be grateful.

**Comment by HorizonNL** [comment] 2018-03-14 02:56
I produced the issue and i want to fix it, what is the file name that i should work on it ?

**Comment by HorizonNL** [comment] 2018-04-04 16:08
This is my fix i hope it works with you.

`#pragma once
#include <vector>
#include <string>
#include <sstream>
#include <windows.h>
#include <iso646.h>
#include <cstdint>
#include <time.h>

const bool dirUp = true;
const bool dirDown = false;

#define NPP_CP_WIN_1252           1252
#define NPP_CP_DOS_437            437
#define NPP_CP_BIG5               950

#define LINKTRIGGERED WM_USER+555

#define BCKGRD_COLOR (RGB(255,102,102))
#define TXT_COLOR    (RGB(255,255,255))

#define generic_strtol wcstol
#define generic_strncpy wcsncpy
#define generic_stricmp wcsicmp
#define generic_strncmp wcsncmp
#define generic_strnicmp wcsnicmp
#define generic_strncat wcsncat
#define generic_strchr wcschr
#define generic_atoi _wtoi
#define generic_itoa _itow
#define generic_atof _wtof
#define generic_strtok wcstok
#define generic_strftime wcsftime
#define generic_fprintf fwprintf
#define generic_sprintf swprintf
#define generic_sscanf swscanf
#define generic_fopen _wfopen
#define generic_fgets fgetws
#define basic_generic_stat _wstat
#define COPYDATA_FILENAMES COPYDATA_FILENAMESW


#define generic_stat(path, dataStruct) (_tzset(), basic_generic_stat(path, dataStruct)) 

typedef std::basic_string<TCHAR> generic_string;
typedef std::basic_stringstream<TCHAR> generic_stringstream;

generic_string folderBrowser(HWND parent, const generic_string & title = TEXT(""), int outputCtrlID = 0, const TCHAR *defaultStr = NULL);
generic_string getFolderName(HWND parent, const TCHAR *defaultDir = NULL);

void printInt(int int2print);
void printStr(const TCHAR *str2print);
generic_string commafyInt(size_t n);

void writeLog(const TCHAR *logFileName, const char *log2write);
int filter(unsigned int code, struct _EXCEPTION_POINTERS *ep);
generic_string purgeMenuItemString(const TCHAR * menuItemStr, bool keepAmpersand = false);
std::vector<generic_string> tokenizeString(const generic_string & tokenString, const char delim);

void ClientRectToScreenRect(HWND hWnd, RECT* rect);
void ScreenRectToClientRect(HWND hWnd, RECT* rect);

std::wstring string2wstring(const std::string & rString, UINT codepage);
std::string wstring2string(const std::wstring & rwString, UINT codepage);
bool isInList(const TCHAR *token, const TCHAR *list);
generic_string BuildMenuFileName(int filenameLen, unsigned int pos, const generic_string &filename);

std::string getFileContent(const TCHAR *file2read);
generic_string relativeFilePathToFullFilePath(const TCHAR *relativeFilePath);
void writeFileContent(const TCHAR *file2write, const char *content2write);
bool matchInList(const TCHAR *fileName, const std::vector<generic_string> & patterns);

class WcharMbcsConvertor final
{
public:
	static WcharMbcsConvertor * getInstance() {return _pSelf;}
	static void destroyInstance() {delete _pSelf;}

	const wchar_t * char2wchar(const char *mbStr, UINT codepage, int lenIn=-1, int *pLenOut=NULL, int *pBytesNotProcessed=NULL);
	const wchar_t * char2wchar(const char *mbcs2Convert, UINT codepage, int *mstart, int *mend);
	const char * wchar2char(const wchar_t *wcStr, UINT codepage, int lenIn = -1, int *pLenOut = NULL);
	const char * wchar2char(const wchar_t *wcStr, UINT codepage, long *mstart, long *mend);

	const char * encode(UINT fromCodepage, UINT toCodepage, const char *txt2Encode, int lenIn=-1, int *pLenOut=NULL, int *pBytesNotProcessed=NULL)
	{
		int lenWc = 0;
        const wchar_t * strW = char2wchar(txt2Encode, fromCodepage, lenIn, &lenWc, pBytesNotProcessed);
        return wchar2char(strW, toCodepage, lenWc, pLenOut);
    }

protected:
	WcharMbcsConvertor() {}
	~WcharMbcsConvertor() {}

	// Since there's no public ctor, we need to void the default assignment operator and copy ctor.
	// Since these are marked as deleted does not matter under which access specifier are kept
	WcharMbcsConvertor(const WcharMbcsConvertor&) = delete;
	WcharMbcsConvertor& operator= (const WcharMbcsConvertor&) = delete;

	static WcharMbcsConvertor* _pSelf;

	template <class T>
	class StringBuffer final
	{
	public:
		~StringBuffer() { if(_allocLen) delete[] _str; }

		void sizeTo(size_t size)
		{
			if (_allocLen < size)
			{
				if (_allocLen)
					delete[] _str;
				_allocLen = max(size, initSize);
				_str = new T[_allocLen];
			}
		}

		void empty()
		{
			static T nullStr = 0; // routines may return an empty string, with null terminator, without allocating memory; a pointer to this null character will be returned in that case
			if (_allocLen == 0)
				_str = &nullStr;
			else
				_str[0] = 0;
		}

		operator T* () { return _str; }
		operator const T* () const { return _str; }

	protected:
		static const int initSize = 1024;
		size_t _allocLen = 0;
		T* _str = nullptr;
	};

	StringBuffer<char> _multiByteStr;
	StringBuffer<wchar_t> _wideCharStr;
};



#define MACRO_RECORDING_IN_PROGRESS 1
#define MACRO_RECORDING_HAS_STOPPED 2

#define REBARBAND_SIZE sizeof(REBARBANDINFO)

generic_string PathRemoveFileSpec(generic_string & path);
generic_string PathAppend(generic_string &strDest, const generic_string & str2append);
COLORREF getCtrlBgColor(HWND hWnd);
generic_string stringToUpper(generic_string strToConvert);
generic_string stringReplace(generic_string subject, const generic_string& search, const generic_string& replace);
std::vector<generic_string> stringSplit(const generic_string& input, const generic_string& delimiter);
generic_string stringJoin(const std::vector<generic_string>& strings, const generic_string& separator);
generic_string stringTakeWhileAdmissable(const generic_string& input, const generic_string& admissable);
double stodLocale(const generic_string& str, _locale_t loc, size_t* idx = NULL);

int OrdinalIgnoreCaseCompareStrings(LPCTSTR sz1, LPCTSTR sz2);

bool str2Clipboard(const generic_string &str2cpy, HWND hwnd);

generic_string GetLastErrorAsString(DWORD errorCode = 0);

generic_string intToString(int val);
generic_string uintToString(unsigned int val);

HWND CreateToolTip(int toolID, HWND hDlg, HINSTANCE hInst, const PTSTR pszText);

bool isCertificateValidated(const generic_string & fullFilePath, const generic_string & subjectName2check);
bool isAssoCommandExisting(LPCTSTR FullPathName);`

**Comment by EugenNY** [comment] 2018-04-27 13:00
I have the same issue since years. 
Do not take timezone'd timestamps while comparing, use UTC timestamps. I'm using NTFS.

relevant link:
https://msdn.microsoft.com/en-us/en-en/library/windows/desktop/ms724290(v=vs.85).aspx?f=255&MSPPError=-2147217396

> The NTFS file system stores time values in UTC format, so they are not affected by changes in time zone or daylight saving time. The FAT file system stores time values based on the local time of the computer. For example, a file that is saved at 3:00pm PST in Washington is seen as 6:00pm EST in New York on an NTFS volume, but it is seen as 3:00pm EST in New York on a FAT volume.

Please fix it :-)

**Closed** 2018-06-24 22:36 UTC
Labels: bug

**Comment by ColColonCleaner** [comment] 2018-06-24 22:37
@donho Excellent! Glad this was changed. Cheers.
