### ISSUE TITLE
FindAll of long-lines text-overflow clipped

### ISSUE THREAD

**Issue by cmrdt** [notepad-plus-plus/notepad-plus-plus#2670] opened 2016-12-12 02:18 UTC
### Description of the Issue

when text files containing very long lines almost 1024 length when parsed into list
so that it's in form of `Line #: ___search-text___...`
but if the search term is fount after, it gets cut off

### Steps to Reproduce the Issue

1. text file with very long lines
2. Ctrl+F
3. find all on current/opened documents

### Expected Behavior

maybe better to have optional 
a) wrap long line
b) have it in form or `...____search-text____...` and have it centered
c) if several terms on one line, group all of the list entries into one

### Actual Behavior

cant see exact search term found or nearby surrounding text for context

### Debug Information

![02](https://cloud.githubusercontent.com/assets/24411108/21538983/5c853126-cd70-11e6-9c6b-58f36fd12f5a.png)

![01](https://cloud.githubusercontent.com/assets/24411108/21538986/61c86892-cd70-11e6-988a-5f0252011cea.png)

**Comment by MetaChuh** [comment] 2019-04-11 21:35
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:35 UTC
