### ISSUE TITLE
[BUG] 'Open Folder as Workspace' won't sort files when opening a folder inside WSL.

### ISSUE THREAD

**Issue by kalil-camera** [notepad-plus-plus/notepad-plus-plus#15875] opened 2024-11-29 03:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When opening a folder as workspace, if the folder is inside a WSL machine, it won't sort the files. The WSL dir already has chmod 777 applied, it can rename, update, delete files alright, but won't sort.

### Steps To Reproduce

1.  Create a WSL machine (see ms doc, its 3 commands in terminal)
2.  Access WSL with Win Explorer, create a folder inside your /home
3.  Open notepad++ and open the created folder as workspace 

### Current Behavior

it won't sort the files.

### Expected Behavior

it will sort the files by name

### Debug Information

```shell
Notepad++ v8.6.8   (64-bit)
Build time : Jun  4 2024 - 00:30:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\user\Desktop\TODO.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4460
Current ANSI codepage : 1252
Plugins : 
    AutoSave (2)
    GitSCM (1.4.9.1)
    JsonTools (7.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    XBrackets (1.3.1)
```

### Anything else?

![Captura de tela 2024-11-28 235717](https://github.com/user-attachments/assets/72ab7f14-977f-4dbf-b320-3af40029125b)

**Comment by xomx** [comment] 2024-11-29 18:49
Duplicate of #15397 and #10557 .
Already fixed in N++ v8.7+
Please close this issue.

**Closed** 2024-11-29 19:17 UTC
