### ISSUE TITLE
Line ending changes are not detected in reloaded changed files

### ISSUE THREAD

**Issue by Dan-Ilan** [notepad-plus-plus/notepad-plus-plus#4033] opened 2018-01-01 16:20 UTC
### Description of the Issue
When reloading a changed file, Notepad++ does not detect a change in Windows/Unix line ending type (LF/CR LF)

### Steps to Reproduce the Issue

1. Create a file, i.e. c:\1\2.txt and type some text
2. Change the line endings to Unix and save
3. Use another text editor to edit the file with Windows line endings. For example use cmd.exe to do "echo blah > c:\1\2.txt"
4. Notepad++ detects the file was changed, but when it reloads it the file is still shown as using Unix line endings
5. Only closing the file and reopening will show it correctly as a file with Windows line endings

### Expected Behavior
Notepad++ would detect the changed line ending types

### Actual Behavior
The line ending type was not updated

### Debug Information
Notepad++ v7.5.3   (64-bit)
Build time : Dec  5 2017 - 10:47:54
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment] 2018-01-03 02:41
Duplicate of 3557

**Closed** 2018-01-28 21:40 UTC
