### ISSUE TITLE
Text Direction RTL/LTR

### ISSUE THREAD

**Issue by Stamimail** [notepad-plus-plus/notepad-plus-plus#1188] opened 2015-11-26 22:27 UTC
Those commands are at bottom of View, but the Keyboard Shorcuts are the problem.
Ctrl+Alt+R/L shouldn't be the default Keyboard Shorcuts for this.
The RTL users are already very fimiliar with other Keyboard Shorcuts, using in all apps and OS:
LeftCtrl+LeftShift           for LTR
 & 
RightCtrl+RightShift       for RTL
Please change the default Keyboard Shorcuts.

**Comment by Stamimail** [comment] 2018-03-07 14:04
I looked at
BabelPad | Version 10.0.0.6 (2017-12-02)
http://www.babelstone.co.uk/Software/BabelPad.html

The same problem there.
BabelPad use

Left to Right Layout    Ctrl+Shift+L
Right to Left Layout    Ctrl+Shift+R

NPP use

Left to Right Layout    Ctrl+Alt+L
Right to Left Layout    Ctrl+Alt+R

Both are wrong.
Should be:

Left to Right Layout    LeftCtrl+LeftShift
Right to Left Layout    RightCtrl+RighShift

**Comment by erikleo** [comment] 2019-01-23 15:47
There is another issue with the current RTL and LTR defaults.  Microsoft has used for a very long time the standard ctl-alt plus a key to globally launch applications.  (you set it from right clicking on a shortcut and setting shortcut key)

The current default fro RTL, LTR violates this standard. I have seen that when a user has ctl-alt-r for example set to launch an application and they happen to have np++ open as the foreground app they end up accidentally changing the text alignment and have no idea how to change it back. 

Therefore I agree is should be changed

@Stamimail, I see you have been researching a better key combination.  The issue i see with using what you propose:

> Left to Right Layout LeftCtrl+LeftShift
> Right to Left Layout RightCtrl+RighShift

is that users can not use "LeftCtrl+LeftShift + any other key"  for any other shortcuts since as soon as you press the the control and shift key the text will move.

Since there are already a lot of presets that use ctl shift, it does not look like it will be possible to change to what you are requesting.  

Also BabelPad Preset of Ctrl+Shift+R has a conflict with the current default of run macro
Microsoft word uses simply ctl-r and ctl-l, but ctl-l already has been assigned delete line in np++

Anyone have a better combination?

**Comment by 5j9** [comment] 2019-01-23 16:03
> The issue i see with using what you propose:
> 
> > Left to Right Layout LeftCtrl+LeftShift
> > Right to Left Layout RightCtrl+RighShift
> 
> is that users can not use "LeftCtrl+LeftShift + any other key" for any other shortcuts since as soon as you press the the control and shift key the text will move.

In `notepad.exe` the shortcut is `(LCtrl|RCtrl)+LShift` for LTR and `(RCtrl|LCtrl)+RShitf` for RTL, the layout change is triggered at KeyUp event, i.e. it won't change the layout until the shift key is released. Also, if another key is used after the `Ctrl+Shift` then no layout change will occure, e.g. pressing `LCtrl+LShift+U` won't do anything in notepad.exe. I don't know how hard it would be for notepad++ to replicate that behaviour though.

**Comment by chcg** [comment] 2019-01-23 17:30
@Stamimail @erikleo @5j9 In any case in the meantime you could change the key shortcut to your needs via settings->keyboard...
@Yaron10 Any thoughts on this?

**Comment by Stamimail** [comment] 2019-01-23 19:48
I confirm what @5j9 wrote.
Also, to be noticed, this combination that me and @5j9 mentioned, are applied to every TextBox in RTL OS, and also MS-Word.

Also, you can consider to assign this hotkeys only for RTL users, by cheking the Keyboard Input Language.
If there is a RTL Keyboard Language in the User Languages Inputs, then these hotkeys will appear.
Non RTL users will be able to set hotkey by
settings->keyboard...

**Comment by Yaron10** [comment] 2019-01-23 21:07
Hello @chcg and all,

> There is another issue with the current RTL and LTR defaults. Microsoft has used for a very long time the standard ctl-alt plus a key to globally launch applications. (you set it from right clicking on a shortcut and setting shortcut key)

I've never used that.
So the problem is with any Ctr+Alt+Key. Alt+Key may also conflict with Windows convention of opening a menu (in Compare Plugin @pnedev replaced Alt+Key with Ctr+Alt+Key because of that).
Unfortunately there aren't many available combinations.

LCtrl/RCtrl+LShift/RShift are indeed the conventional combinations for changing the text direction.

**Comment by donho** [comment] 2019-04-10 15:14
It's hard to implement such feature, so it won't be implemented.

**Closed by donho** 2019-04-10 15:14 UTC

**Comment by Stamimail** [comment] 2019-04-16 21:45
Can you supply more details, why is it so hard to implement?
