### ISSUE TITLE
The translation for "restore recent closed file" cannot load automatically

### ISSUE THREAD

**Issue by popcorner** [notepad-plus-plus/notepad-plus-plus#2644] opened 2016-12-04 17:45 UTC
### Description of the Issue
When the language of Notepad++ isn't English, the translation for "restore recent closed file" disappeared.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Click File button on the Menu bar

### Expected Behavior

the translated string should appear

### Actual Behavior

"restore recent closed file" still appears in English
and I have to set the language manually once to load the translated string.
![image](https://cloud.githubusercontent.com/assets/6312791/20868013/62dfad2c-ba8c-11e6-802e-956e78825e81.png)

**Comment by dail8859** [comment] 2016-12-04 17:49
Related to, or duplicate of: #203, #820, #1476, #1487

**Closed** 2017-01-06 09:14 UTC
