### ISSUE TITLE
Search directory path isn't retained

### ISSUE THREAD

**Issue by JThurman** [notepad-plus-plus/notepad-plus-plus#9141] opened 2020-11-12 18:29 UTC
### Description of the Issue
Notepad ++ doesn't retain the directory path used in last search

### Steps to Reproduce the Issue
1. Perform a find-in-files search selecting any directory
2. Perform another search. Default directory will not be the same if there is more than 1 directory in previous list

### Expected Behavior
Wanted it to stay at the directory path of the previous search

### Actual Behavior
Picks another directory from the list. Not sure how it determines which one to use.

**Comment by sasumner** [comment] 2020-11-12 18:50
Closing as duplicate of #9140

**Closed by sasumner** 2020-11-12 18:50 UTC
