### ISSUE TITLE
SQL formatting problem if using \ character in file

### ISSUE THREAD

**Issue by ertankucukoglu** [notepad-plus-plus/notepad-plus-plus#3862] opened 2017-10-30 23:10 UTC
Hello,

I seem to hit some formatting problem with SQL files. If there is "\" character in a quoted text it seems to be used as some other means. For better understanding, please use below text in any file with .sql extension.
```
insert into params(paramname, valuetxt) values('KeyboardKey_47', '.');
insert into params(paramname, valuetxt) values('KeyboardKey_48', '>');
insert into params(paramname, valuetxt) values('KeyboardKey_49', '_');
insert into params(paramname, valuetxt) values('KeyboardKey_50', '/');
insert into params(paramname, valuetxt) values('KeyboardKey_51', '\');
insert into params(paramname, valuetxt) values('KeyboardKey_52', '[');
insert into params(paramname, valuetxt) values('KeyboardKey_53', ']');
insert into params(paramname, valuetxt) values('KeyboardKey_54', '(');
insert into params(paramname, valuetxt) values('KeyboardKey_55', ')');
insert into params(paramname, valuetxt) values('KeyboardKey_56', '%');
```
You should have a formatting change starting with line having "KeyboardKey_51".
My screen look like: http://i65.tinypic.com/350j97m.png
Version I am using is: 7.5.1 (32bits) on Windows 10 64bit OS.
Build time: Aug 29 2017 - 02:35:41

**Comment by dail8859** [comment] 2017-11-01 21:59
`Settings > Preferences > MISC. > Treat backslash as escape character for SQL`

Duplicate of #3816, #3187, #2451 and probably others.
![capture](https://user-images.githubusercontent.com/3694843/32300078-5085f33c-bf2e-11e7-8379-67d117388581.PNG)

**Closed by dail8859** 2017-11-01 21:59 UTC
