### ISSUE TITLE
Display style reverts to html within  embedded Javascript when html end tag appears inside template literal

### ISSUE THREAD

**Issue by dave-hirschman** [notepad-plus-plus/notepad-plus-plus#11021] opened 2022-01-10 18:29 UTC
Display incorrect after html end tag in template literal in embedded Javascript. See snapshot below.

### Debug Information
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 22000.376
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![snip](https://user-images.githubusercontent.com/33360900/148819170-3d14f081-1e38-411f-b153-49cd635629ae.png)

**Comment by ArkadiuszMichalski** [comment] 2022-01-11 10:54
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822.

**Closed by ArkadiuszMichalski** 2022-01-11 10:54 UTC
