### ISSUE TITLE
[Discussion] The new URL parser

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#8975] opened 2020-10-07 17:25 UTC
Continued from https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8921#discussion_r501056092.

@Uhf7,

> the correct way would be `file:///C:/Test%201.txt`. I added the special handling for the file scheme with quotes to allow really spaces in file names, but it seems not to be too intuitively.
...
Some ways to go here:

Thinking a bit more about it...

I'm assuming the common use of the `INTERNET_SCHEME_FILE` would be in files which already contain that scheme.
Do you agree? Or is it probable that NPP users would manually edit any `file:///---` lines?.

If my assumption is correct, the question should be how the scheme is represented in such files. 
Creating a bookmark in Firefox for `file:///C:/Test 1.txt`, it's indeed saved as `file:///C:/Test%201.txt`.
Do you have any other files using `INTERNET_SCHEME_FILE`?.

**Comment by ArkadiuszMichalski** [comment] 2020-10-07 18:11
Browser (like Firefox) do sth like this:
- URL bar display explicity space (or any other), but when copy always make percent encoding. And it accept URL with explicit space (maybe when navigate to this URL make convert to propper format, but we still see orginal value), 
- in bookmark its name can display explicity space but href is always percent encoding (when we make drag&drop bookmark), even when we manually set href with explicity space it will be percent encoding after save bookmark.

Even in Visual Studio Code I see that space is not specially treated (does not recognize addresses with explicit spaces). Enclosing an URL in "" might be an option, but, in fact, weird.

Looks like only Windows Explorer operate on explicity space, but its bar contains only the address, and here it is not a problem to detect it (no surrounding other text).

I'm wondering if Scintilla offers some mechanizm to display text above the current one, where you could display the URL value after decoding (because many % sequences are not readable) Thats why browsers display decoded URL, even when you past to URL bar some encoded URL, its display decoded variant. In its simplest form, a regular tooltip would also be useful, and maybe some command to copy URL (encoded or decoded after hovering and recognized them as URL).

Detecting an explicit space as part of the URL it will probably introduce too much complexity, there will be too many cases later that will not be covered (bug, bug, bug..). Some characters just need to be encoded, that's it. But a easy way to preview the decoded URL format (as mention above) may make this process a bit easier.

**Comment by sasumner** [comment] 2020-10-07 18:54
>Browser (like Firefox) do sth like this:

What is "sth" ?

**Comment by ArkadiuszMichalski** [comment] 2020-10-07 18:59
Something... maybe I'm too lazy:)

**Comment by sasumner** [comment] 2020-10-07 19:07
Your laziness makes me do more mental work to figure out what you're saying. :-)
Do what you will, but I'd appreciate you not doing that kind of thing in the future.

**Comment by ArkadiuszMichalski** [comment] 2020-10-07 19:18
Because of these 315, each additional one hurts :) But seriously, often when analyzing or discussing the W3C / WHATWG documentation or browser bugs, or other technicall space, they often use such abbreviations, and I started using them, although they were not so obvious to me. Don't be so restrictive, I noticed that even Don Ho uses some abbreviations:)

**Comment by ArkadiuszMichalski** [comment] 2020-10-07 20:40
Other thoughts: give the possibility to define your own start / end delimiter for URL, everything in between will be treated as URL. For example when my delimiters start/end is `URL_` and `_URL`, I put `URL_file:///D:/some folder/_URL` or even `URL_D:/some folder/_URL`. Only content beetwen them will be URL. As mentioned above, limiting this to only "" may not work in some contexts and only custom delimiters can resolve this. Such delimiter can be easy removed from source in tools chain (if necessary).

On the other site, even custom delimiters (just one) may not always work in some contexts. A plugin would probably be better here, with the possibility of setting them for each lexer or extension separately (including even some global for all lexers).

I still think dealing with explicit spaces (without some unique delimiters) is a waste of time (you won't cover every bug reported for this in the future). Although I can always be wrong.

**Comment by Uhf7** [comment] 2020-10-08 10:57
Thank you for your comments. 

I agree, that it is impossible to detect URLs containing literal spaces within text files. The special solution with quotes for the `file:` scheme was probably not my best idea, although in the test files, @Yaron10 provided, all hrefs were enclosed in quotes (html, see https://github.com/notepad-plus-plus/notepad-plus-plus/files/5021684/Test.zip from https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8634#issuecomment-668541115).

Perhaps we should accept, that a `file:` scheme URL is not a file name. Although everyone expects it to be so, as soon as I write a file:/// before something, than a file name follows, this approach I tried to rescue with the special handling for the `file:` scheme.

Self-defined delimiters for all languages in common (in settings or so) seem to be strange. A user defines an own world, and the files produced with this self-defined delimiters can only be used in this world. This may work for users editing files of one type only. So the minimum would be language-dependent delimiters, but the relatively small number of problems solved with this may not be worth the effort. Not to mention the new problems which could arise.

There is no magic  Scintilla way to display percent-encoded URLs decoded. It's actually not the task of Scintilla. In theory, a tool tip showing the decoded URL would be possible, but this has nothing to do with the URL detection

So concerning the `file:` scheme, I repeat the possible solutions I can imagine right now:
- Remove `file:` scheme completely.
- Remove special handling for `file:` scheme, then
  - Spaces have always to be coded as `%20`
  - It is possible to construct invalid file names, at least, if this method is used to open local files
- Allow the percent-encoding in the special handling for file scheme, then the spaces would work in quotes and the percent-encoding would work too.

My current favorite is to remove the special handling, but I'm open for everything, including easy-to-implement better ideas.

What I would like to include in this discussion are the following two link examples:

- Issue #7845: https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={"id":"0123456789","first":100}
- Issue #8376: \href{https://thisisaweblink.com/}{click me}

I believe to have a solution for both, but I await the discussion about the `file:` scheme before doing anything.

----

> it probable that NPP users would manually edit any file:///--- lines?

It is a source code editor, so it should be possible to create/modify the files with such links with Notepad++.

> Do you have any other files using INTERNET_SCHEME_FILE?.

No. I don't even have Firefox bookmark files.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 12:03
> My current favorite is to remove the special handling, but I'm open for everything, including easy-to-implement better ideas.
So this means the second solution in your list? It's fine for me, if someone wants to use `file:`  then should make the correct names themselves. 

If self-defined delimiters is not good solution, then why use `""`?. For HTML / XML (ass attr value) it will be convenient, but not for others. It is worth doing for a narrow group of languages? In general I'm not for self-defined delimiters, maybe by the plugin, but `""` even for `file:` also have limited usage. And if it appears, the option to disable it would be useful.

**Comment by Uhf7** [comment] 2020-10-08 13:15
> One question, this "" and space you consider only for `file:`, not for all URLs?

- Because of this: `https://duckduckgo.com/?q=windows+delete+"GameBarPresenceWriter.exe"` (would end after delete+). Or, in words, double quotes are allowed in URLs, but are forbidden in local file names.
- I assumed, local file names generally have a more limited character set then the rest of the supported URLs.
- Spaces seemed more probable to me in local file names.
- My original intention was, to handle the `file:` scheme basically like the other schemes (not accepting spaces), with one exception: If there is an opening `"` immediately before it, then the `file:` URL can contain spaces (until line end or the `"`). This was inspired by the command line syntax.
To implement this fully, I would need to include the percent encoding here.

**Comment by Yaron10** [comment] 2020-10-08 13:19
@Uhf7,

Thank you for the detailed explanation.

I don't need the `file:` detection for my personal use. But @donho requested to include it.

> It is a source code editor, so it should be possible to create/modify the files with such links with Notepad++.

Correct. But the question is what the common use of the `file:` parsing would be.

At first I copied `file:///C:/Test 1.txt` from Firefox URL bar, pasted it in NPP and *manually removed the `%20`*. 
Seeing that `file:///C:/Test 1.txt` was not fully marked as URL, I thought it might cause some confusion and suggested to remove `INTERNET_SCHEME_FILE` altogether.

But then I thought that the main use of `file:` would be in files generated by Firefox (as an example).
And if we assume that in those files `file:///C:/Test 1.txt` would be `file:///C:/Test%201.txt`, I'd suggest to parse `%20`.

Regarding `"file:///C:/Test 1.txt"`: if this is a common format or some users might want to (manually) have it that way - then the `""` handling would be useful.

***

@donho,

We'd appreciate your opinion.

**Comment by Uhf7** [comment] 2020-10-08 14:22
> But @donho requested to include it.

@donho didn't request a special handling for the `file:` scheme, I dashed forward here a little, so the problems coming from this are on me.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 14:37
But in some context I can't use `"file:///C:/Test 1.txt"`, I can use `'file:///C:/Test 1.txt'` (or with backticks `), or escape it with some char like  \\"file:///C:/Test 1.txt\\", then what? Directly using percent encoding will always work.

**Comment by Uhf7** [comment] 2020-10-08 15:09
@ArkadiuszMichalski,

**\`** and **'** cannot be used as delimiters for file names, because they are allowed in file names.

The 3rd example is interesting. This cannot be handled even as `http:` scheme: \\"http://Test.com\". The final escape-backslash is always regarded as part of the link. This is no regression compared to the regex version.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 15:34
Yes, and different context may use different escape character, so... using just `%20` will solve all problems.

**Comment by Uhf7** [comment] 2020-10-08 15:41
> using just %20 will solve all problems.

Not that with with enclosing the link in escaped double quotes (\\"). This has nothing to do with the spaces and the percent-encoding. But some other problems.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 15:45
Yes, I mean solution 2 is better in that case, but if you really want 3 such bug/question will come up.

**Comment by Yaron10** [comment] 2020-10-08 16:36
@Uhf7,

> @donho didn't request a special handling for the file: scheme.

I had not realized that and it's important. :)

Adding `case INTERNET_SCHEME_FILE:` to `isUrlSchemeSupported(INTERNET_SCHEME s)` without the extra `file:` handling  - `file:///C:/Test%201.txt` is fully marked as URL.

Assuming the main use of `file:` would be in files generated by Firefox, this (`%20`) seems more important than handling explicit spaces.
And it requires less code.

What do you think?

**Comment by Uhf7** [comment] 2020-10-08 16:56
@Yaron10,

yes, I already said, I would prefer this in the moment.

But, including the percent-encoding in the special handling for the `file:` scheme  would have nearly the same effect: accepting percent-encoding and `file:`-URLs with real spaces in quotes.

But given that my preceding-double-quote-detection solution doesn't seem to be such a great success, it would be better for the code to remove it. I designed it to be easily removable :-). 

I bet, your first question (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8921#discussion_r500961005) will occur quite frequently, the only solution for that is percent-encoding then.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 17:04
@Uhf7 So maybe 2+3? If someone wants "" and using them does not disturb other things. Of course this is just another concept.

**Comment by Yaron10** [comment] 2020-10-08 17:13
@Uhf7,

Due to my initial misunderstanding I thought "My current favorite is to remove the special handling" meant removing `INTERNET_SCHEME_FILE` completely.

Well, keeping `INTERNET_SCHEME_FILE`  and removing the extra handling seems the best solution.

> I bet, your first question (#8921 (comment)) will occur quite frequently, the only solution for that is percent-encoding then.

Thinking about it again, I realized the main use would be in auto-generated files. 

Typing it, I see @ArkadiuszMichalski's comment.
Do you want the `""` for your personal use?
In MS VS explicit spaces are not parsed as part of the URL.

**Comment by Uhf7** [comment] 2020-10-08 17:47
> Have you seen any editors or tools that support explicit spaces in URL?

No text editors, but MS Outlook, for example can do it under certain circumstances. If you edit a new mail message and the mail is in html format, then you can type `"file://foo 1.txt`. Nothing is highlighted until now. Then you type the closing `"` and a space or new line, and in this moment, Outlook converts `"file://foo 1.txt"` into a link without quotes, but keeping the space in it. But they can do this because of the underlying html-message.

> Do you want the "" for your personal use?

No, I can cope with the percent-encoding too.

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 18:55
>No text editors, but MS Outlook,...

I see that MS Word do the same, but it convert this to internal state/format, so it can even handle other quirks. I still prefer to use % for proglematic characters rather than wait for fix the parser to handle all cases correctly.

**Comment by Yaron10** [comment] 2020-10-08 19:31
> Do you want the "" for your personal use?
...
No, I can cope with the percent-encoding too.

@Uhf7,
Thanks for replying. I was actually addressing @ArkadiuszMichalski who suggested "So maybe 2+3?". :)

Reading your (both) last comments - the extra `file:` handling should be removed. Is that correct?

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 19:50
@Yaron10 I wrote above a few times that for me this "" is unnecessary, and even sometimes it can't be used, so yes, I vote to option 2 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8975#issuecomment-705493431. I thought you want possibility to  put explicity space (which of course requires some delimiters, like ""). But in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8975#issuecomment-705707950 you clarified that also prefer 2 option.

**Comment by Uhf7** [comment] 2020-10-08 20:10
OK, let's wait a little. If no one else wants spaces in file names, I will try a PR to remove the special `file:`-scheme handling and to improve the handling of URLs with curly brackets around it and with curly brackets in the query part.

**Comment by Yaron10** [comment] 2020-10-08 20:12
@ArkadiuszMichalski,

OK. Thanks for clarifying it.

***

>    https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={"id":"0123456789","first":100}
>
 >   \href{https://thisisaweblink.com/}{click me}
..
I believe to have a solution for both

That would be great. :+1: 
Interestingly, both links are not parsed correctly in MS VS.

**Comment by Yaron10** [comment] 2020-10-08 20:14
@Uhf7,

Just seen your last comment. :+1:

**Comment by ArkadiuszMichalski** [comment] 2020-10-08 20:34
@Yaron10

Because it requires that after ? some characters must be encoded, like for @Uhf7 example https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8975#issuecomment-705559903
```
 https://duckduckgo.com/?q=windows+delete+"GameBarPresenceWriter.exe"
```
VSC stuck before first ", but even when we past/copy to browser URL bar we get:
```
https://duckduckgo.com/?q=windows+delete+%22GameBarPresenceWriter.exe%22
```

For some reason browsers still require encoding some chars, but in general, the " in URL is not restricted. Same is for your example (second is recognized in VSC):
```
https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={"id":"0123456789","first":100}
https://www.instagram.com/graphql/query/?query_hash=c76146de99bb02f6447853be841dd25a&variables={%22id%22:%220123456789%22,%22first%22:100}
```

This `\href{https://thisisaweblink.com/}{click me}` can be fix by checking one char before scheme, and I closing for this char exist after scheme you have pair (inside is URL). But once again, explicity using closing in URL will be forbiden.  In future you can extend it to other pairs if needed, e.g. (), [], {}, etc. Unless you have any other idea for handling this?

**Comment by Yaron10** [comment] 2020-10-08 20:48
@ArkadiuszMichalski,

Those are actually your links. :)

Regarding the preferred way to parse them: I have no clue whatsoever. I trust @Uhf7 to come up with the best solution and I think he might find your ideas helpful.

Thank you.

**Comment by donho** [comment] 2020-10-11 16:09
@Yaron10 
> @donho,
> We'd appreciate your opinion.

Sorry for the late reply, I was busy on the other feature.
Well, for me in the perfect world, file scheme should recognize both:
`file:///C:/Test%201.txt`
`"file:///C:/Test 1.txt"`

But if it's hard to maintain for the system file path treatment, I would choose the favorite option of @Uhf7 :
> Remove special handling for file: scheme, then
Spaces have always to be coded as %20
It is possible to construct invalid file names, at least, if this method is used to open local files

My reason is: from the viewpoint of users' usage, they type rarely the forbidding characters by system to form a file scheme. And such file scheme is often copied from the browsers.

**Comment by Yaron10** [comment] 2020-10-11 19:22
@donho,

Thanks for replying.

> My reason is: from the viewpoint of users' usage, they type rarely the forbidding characters by system to form a file scheme. And such file scheme is often copied from the browsers.

:+1: 
I'm glad we've all come to the same conclusion.

**Comment by Yaron10** [comment] 2020-10-12 11:59
@Uhf7,

Thank you for 8994.
Great! :+1:

**Closed** 2020-10-14 21:21 UTC

**Comment by Yaron10** [comment] 2020-10-18 13:53
A minor issue (**existed in older NPP version.** NOT caused by the new parser or `addHotSpot`):

Open the "Find Results" window.
Open [this](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5397584/Test.txt) file.
Close the "Find Results" window.

Result:
The lines revealed after closing the "Find Results" window are not marked as links.

![תמונה](https://user-images.githubusercontent.com/10229320/96369318-d223e600-1161-11eb-9938-578d6e4b4ff7.png)

Possibly related: https://community.notepad-plus-plus.org/post/58293.

Thank you.

**Comment by Uhf7** [comment] 2020-10-18 14:12
I can confirm this. It is more an update problem, an `addHotSpot` call is necessary after increasing the number of visible lines. I will see what I can do ...

**Comment by Yaron10** [comment] 2020-10-18 17:42
@Uhf7,

:+1: 
Thank you.

**Comment by Yaron10** [comment] 2020-11-12 20:29
@Uhf7,

Another interesting case. If you think it's important. :)

I've found the following link in an old Firefox file.
<RDF:RDF xmlns:NC="http://home.netscape.com/NC-rdf#"

And also:
https://www.ivory.co.il/catalog.php?id=34565#

NOTE: `=` at the end is parsed as part of the link.

Thank you.

**Comment by Uhf7** [comment] 2020-11-15 01:41
@Yaron10, thank you for the interesting examples.

----

Your first link has an empty fragment at the end. Fragments are usually used as a kind of bookmark within the web page opened.

 Example:
- Link 1: https://en.wikipedia.org/wiki/Notepad%2B%2B brings you to the start of the page.
- Link 2: https://en.wikipedia.org/wiki/Notepad%2B%2B#External_links brings you to the "External links" chapter of the page. 

An empty fragment makes no sense:
- Link 3: https://en.wikipedia.org/wiki/Notepad%2B%2B# brings you to the same point as the Link 1.

----

Your second link is the same thing. Here, the empty fragment comes after the query. I land on the same page with or without `#`. 

----

The theory behind is, that the fragment part of the URL is not sent to the web server. Instead, the browser fetches the whole web page, and then jumps to the "bookmark" specified after the `#`.

**Comment by ArkadiuszMichalski** [comment] 2020-11-15 02:26
@Uhf7 
Empty hash fragment is correct and means scroll document to the top (without reload), at least in browsers world. When we open new tab it's doesn't really make a difference because we always land on document top (with empty # or without #).
But still this address is valid and it might be nice to recognize it (if it doesn't collide with some delimiters) and does not require many corrections.

I also checked this for example in Visual Studio Code and URL is recognized with empty #.

**Comment by Yaron10** [comment] 2020-11-15 14:30
@Uhf7,

Thank you for the detailed reply.

One usually does not edit URLs in files.
You either get a file containing them or copy some from a browser and paste them in a file.
I recently happened to copy and paste several links with an empty `#`, and they looked a bit weird: most of the lines are underlined except for the last `#`.

Also, an empty `=` *is* parsed as part of the link. Why should there be a difference between the two?

And we'll end up with slightly optimized code if the '#' special treatment is removed. :)

After reading @ArkadiuszMichalski's comment, it makes even more sense to parse empty `#` as part of the links.

***

@ArkadiuszMichalski,

Thank you for the important info.
Have you encountered any links with `?` at the end? - It is NOT parsed as part of the link here on GitHub.

**Comment by ArkadiuszMichalski** [comment] 2020-11-15 17:04
>Have you encountered any links with ? at the end? - It is NOT parsed as part of the link here on GitHub.

No, just saw that in Visual Studio Code it is also considered as part of the URL (even empty ?). Empty # on the end it's more popular because pages often use `<a href="#">Go Top</a>` instead of JS to go to the document beginning, and after jump people often copy those addresses (with includes empty #) and share it.

**Comment by Yaron10** [comment] 2020-11-15 18:40
@ArkadiuszMichalski,

Thank you.
