### ISSUE TITLE
Context menu does not work after find in files

### ISSUE THREAD

**Issue by lonavera** [notepad-plus-plus/notepad-plus-plus#383] opened 2015-07-02 08:32 UTC
Environment: Notepad++ 6.9.7.2, Windows 7 x64 SP1

When I use the find in files function, the context menu does no longer work. I saw that there is an notepad++ changelog entry for 6.9.7 that such an error was fixed, but for me it does not work with the most recent version.

To verify the problem and to ensure that it is not triggered through my special environment I downloaded the portable-apps version of notepad++. The error occurs there too. I tried the portable version 6.9.7 and 6.9.7.2.

**Comment by pnedev** [comment] 2015-07-13 13:55
If you disable the ***DSpellCheck*** plugin (you can simply move the plugin dll to ***plugins/disabled*** folder) the problem will disappear. You can use that as a temporal solution until the problem is fixed.

**Comment by Predelnik** [comment] 2015-07-15 18:49
So I've made a quick-fix of my plugin which should solve aforementioned problem. It could be included in next Notepad++ version I guess.
https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.2/DSpellCheck.zip

**Comment by ariccio** [comment] 2015-07-16 07:24
@predelnik for clarity: What was the problem?

**Comment by Predelnik** [comment] 2015-07-16 09:01
The problem was that I was incorrectly handly NPPM_GETCURRENTSCINTILLA message result which should be 0 when main scintilla editor/ view is active and 1 when adittional one. Sometimes it also equals -1, by the way it isn't mentioned on "Messages And Notifications" page but looks like I knew it from N++ source, I don't know in which cases exactly it happens but I accidentally treated it as the fact that N++ already closing and killed my worker thread which is part of context menu handling in current design.

**Closed** 2015-07-20 11:23 UTC
Labels: bug, regression
