### ISSUE TITLE
Weird modal windows and debug window

### ISSUE THREAD

**Issue by kbalint** [notepad-plus-plus/notepad-plus-plus#11636] opened 2022-05-04 09:54 UTC
Installed notepad++ 4.8 via winget, got this

![image](https://user-images.githubusercontent.com/4146263/166659920-e291a647-bc3b-4dcb-90e0-7092090deb1b.png)

what could cause this layout, and how to get rid of the inline windows? (some of them can't be closed, but eventually all returns on restart)

Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 2009
OS Build : 22610.1
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by dfs-** [comment] 2022-05-04 10:38
Could be Slack.

**Comment by alankilborn** [comment] 2022-05-04 11:41
See [HERE](https://community.notepad-plus-plus.org/topic/21895/faq-desk-huge-gaps-blank-areas-in-the-ui-borders/1)

**Comment by MarkusEberlein** [comment] 2022-05-16 09:00
same here, just win 10 and slack running

**Comment by ArkadiuszMichalski** [comment] 2022-07-27 00:09
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed by ArkadiuszMichalski** 2022-07-27 00:09 UTC
