### ISSUE TITLE
crashes when trying to open 'Settings' - 'Preferences'

### ISSUE THREAD

**Issue by MlCHEL1234** [notepad-plus-plus/notepad-plus-plus#12128] opened 2022-09-08 13:58 UTC
### Description of the Issue

I'm Linux-User and want to run notepad++ with wine. npp++ V8.4.4 works as expected but crashes, when trying to open Settings-Preferenves with a access-violation.

### Steps to Reproduce the Issue

1. Run rpp++
2. Open menu Settings
3. Click to Preferences

### Expected Behavior

A Configuration-window should open

### Actual Behavior

A little window opens

### Debug Information

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files (x86)\npp.8.4.4.portable.x64\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
WINE : 7.0-rc3
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

OpenSuSE Tumbleweed, wine 7.0

**Comment by ArkadiuszMichalski** [comment] 2022-09-08 14:02
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11941.
Try manually update to 8.4.5.

**Closed by ArkadiuszMichalski** 2022-09-08 14:02 UTC

**Comment by MlCHEL1234** [comment] 2022-09-08 20:46
Thanks for fast response. Your hint works. npp doesn't crash no more.
Have a nice time.
Bye 
Michael
