### ISSUE TITLE
NPP Websit - secure connection failed

### ISSUE THREAD

**Issue by dogslife** [notepad-plus-plus/notepad-plus-plus#14892] opened 2024-03-21 13:59 UTC
### Description of the Issue
When visiting - https://notepad-plus-plus.org/ I get
Secure Connection Failed
An error occurred during a connection to notepad-plus-plus.org. The OCSP response does not include a status for the certificate being verified.
Error code: MOZILLA_PKIX_ERROR_OCSP_RESPONSE_FOR_CERT_MISSING

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.

![npp](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17161419/94a390be-6a40-4b76-9a04-8c4f4589eb47)

Appreciate its not an notepad app issue but nowhere else to report it

**Comment by xomx** [comment] 2024-03-21 15:31
Duplicate of #14890 .

**Comment by donho** [comment] 2024-03-21 16:00
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14890#issuecomment-2012777908

**Closed by donho** 2024-03-21 16:00 UTC
