### ISSUE TITLE
Without any warning, the updater deletes all unsaved files

### ISSUE THREAD

**Issue by EnSec4Git** [notepad-plus-plus/notepad-plus-plus#4983] opened 2018-11-02 10:58 UTC
### Description of the Issue
With the last update, Notepad++ silently deletes any files that were not saved from the open session.
This causes severe data loss.

### Steps to Reproduce the Issue

1. Create a new tab (Ctrl+N)
2. Type something and quit Notepad++ without saving
3. Upgrade to latest version
4. Open Notepad++

### Expected Behavior
Have unsaved files re-opened in the editor just like always up until now.

### Actual Behavior
The unsaved files are closed. I think backups can be found in the usual Notepad++ location.

### Debug Information

Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

As a loyal user for more than 10 years, I'm devastated by this sucker punch.
Notepad++ used to be a program that I trusted to not "surprise" me in this way.

**Comment by sasumner** [comment] 2018-11-02 11:44
Time has shown that this kind of thing happens with Notepad++.  The real solution is to name your files (and also have an independent backup method).  Should what you've described happen?--definitely not.  Sorry, man, that sucks if you lost data this way.

**Comment by SinghRajenM** [comment] 2018-11-10 14:16
Duplicate of  #4729

**Comment by rmutalik** [comment] 2019-04-24 19:26
@EnSec4Git I posted a comment a few months ago. I just followed the steps for reproducing the issue, updating from v7.3.3 32-bit to v7.6.6 32-bit. The files are still there when I reopen Notepad++. It seems that the issue has been fixed with the latest update.

Please retest and confirm. Thanks.

**Comment by MetaChuh** [comment] 2019-04-24 22:29
@EnSec4Git 

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-24 22:29 UTC
