### ISSUE TITLE
Feature request - Put full path in File Explorer for Open File / Save File menu options

### ISSUE THREAD

**Issue by j2associates** [notepad-plus-plus/notepad-plus-plus#5252] opened 2019-01-21 22:10 UTC
### Use WIndows 10 style File Browser for File Open and File Save As menu items
When opening a file or saving a file as in NotePad++, old style File Explorers are shown, with each sub folder displayed as a node in a tree. This makes it difficult to copy and paste full paths while loading or saving a file. Alternatively, a Right Click option for copy full path would be acceptable

### Steps to Reproduce the Issue

1. Open NotePad++
2. From the File menu, click Open.. or Save As...
3. Navigate 3 or 4 sub folders deep
4. Try to copy the full path 

### Expected Behavior

Full path is available for copying similarly to a Windows 10 File Explorer
![image](https://user-images.githubusercontent.com/31308677/51501004-37388500-1d9e-11e9-825a-5da218390510.png)

### Actual Behavior

Path is displayed as individual nodes on a tree
![image](https://user-images.githubusercontent.com/31308677/51501144-b75eea80-1d9e-11e9-8c80-f719d41f33f4.png)

### Debug Information

![image](https://user-images.githubusercontent.com/31308677/51501252-19b7eb00-1d9f-11e9-9aad-cd754493b848.png)

**Comment by hexiyou** [comment] 2019-01-23 05:06
In the "Open" File dialog, you can put the full path in the text box after the "File name" and press Enter key.

![image](https://user-images.githubusercontent.com/1593944/51584271-a2559900-1f0f-11e9-9650-c9062541db17.png)

**Comment by j2associates** [comment] 2019-01-23 21:35
Thanks, that is helpful to know. But there is still no way to copy the path if you do a save as to a different location.

**Comment by j2associates** [comment] 2019-01-23 21:38
Sorry, did not mean to close the issue.

**Comment by SinghRajenM** [comment] 2019-04-12 16:25
It can be changed from setting menu...
`Settings->Default Directory->Use new style dialog`

@MetaChuh, we are ok to close this ticket.

**Closed** 2019-04-12 19:19 UTC

**Comment by inbay** [comment] 2019-04-24 20:26
Is there a reason this feature is not implemented in an address bar with [back], [forward] and [up] directory links, as well as a user input pane at the top of the menu, and most importantly, the Navigation pane on the left, as provided in the screen captures above?
These work-arounds are not conducive to the 'Windows' experience, nor are they particularly useful for average users, and utilize more time with advanced users.  While notepad++ can be used in many advanced ways it's knowledge entry level is quite low, and are quite conducive for environments without a keyboard.  I believe these functions have been created in C++ as the 'OpenFileDialog' function;
https://forums.whirlpool.net.au/archive/413992
http://forums.codeguru.com/showthread.php?428840-How-to-use-the-openFileDialog

**Comment by sasumner** [comment] 2019-04-24 20:36
@inbay, do your comments take into account what you see if you tick the `Use new style dialog` setting per @SinghRajenM above?  I'm on Windows 7 which apparently doesn't have the back/forward/up stuff, but appears to have everything else desired.

**Comment by inbay** [comment] 2019-04-24 20:45
@sasumner 
I stand corrected;
I did not review the comment you mentioned, as it appeared to reference an item in the menu which did not exist; This item appears @ [Settings] > [Preferences...] > Default Directory [X] Use new style dialog.
This provides exactly what I wanted, my apologies.

**[SOLUTION]
To provide the expected behavior of the OP:
Select 'Settings' from the file menu,
Select 'Preferences...' from this sub-menu
Select the 'Default Directory' heading in the left-hand menu
And check the box at the bottom labelled 'Use new style dialog (without file extension feature & Unix style path capacity)'**

**Comment by MetaChuh** [comment] 2019-04-24 20:51
@inbay 

thanks for your understanding, as well as for your summary guide.
here is a screenshot of the new style dialog of notepad++ version 7.6.6:

<img width="969" alt="Bildschirmfoto 2019-04-24 um 22 40 12" src="https://user-images.githubusercontent.com/45773305/56692355-4ce18180-66e2-11e9-9ca1-36031c64d0ba.png">

best regards.

**Comment by sasumner** [comment] 2019-04-25 11:38
@MetaChuh 

old style / new style ... seems to be the #1 support question generator

It would be best if "old style" could head to the retirement home, but I'm sure if it disappeared the complaints would really start pouring in.

Perhaps Peter will choose that topic as his # 1 when revamping the docs. :)

**Comment by j2associates** [comment] 2019-04-25 11:53
Hello,

Perhaps the alternate setting could be changed to the default setting since
that is the standard Windows OS setting. Just a thought.

**Comment by sasumner** [comment] 2019-04-25 12:08
@j2associates Yes, but we are back to being bound by history: People don't like it when you eliminate features or change default settings. :)

**Comment by MetaChuh** [comment] 2019-04-25 12:09
@j2associates 

yes, you are correct.

the setting `use new style dialog` already is the default setting of a fresh notepad++ install since 7.6.4.
but since the installer is, by design, not allowed to alter existing user settings, an update can not activate new style dialog automatically.

our apologies for that.

**Comment by j2associates** [comment] 2019-04-25 12:12
I requested the same thing earlier because I didn't know about the
alternate setting. That might be a good topic for a short FAQ. I would be
happy to write one for you as a small contribution if outsiders have that
capability. Just let me know.

Have a great day!
