### ISSUE TITLE
Files cannot be saved sometimes for no reason

### ISSUE THREAD

**Issue by SamweisWeb** [notepad-plus-plus/notepad-plus-plus#10751] opened 2021-11-06 15:41 UTC
### Description of the Issue

As of the latest release 8.1.9 of NP++ 64bit, more than occasionally I'm being prompted with a strange message while trying to save a file. The message informs me about not being able to save the file and asks me whether to restart NP++ in the administrator mode.

### Steps to Reproduce the Issue

None, for it is occasionally.

### Expected Behavior

File saving without this strange message.

### Actual Behavior

See above.

### Debug Information

None.

None.

**Comment by donho** [comment] 2021-11-06 22:56
What"s the file's path? Files are protected in some location (folder), user needs Admin privilege to modify/delete these files.

**Comment by blackraz** [comment] 2021-11-07 14:08
> ### Description of the Issue
> As of the latest release 8.1.9 of NP++ 64bit, more than occasionally I'm being prompted with a strange message while trying to save a file. The message informs me about not being able to save the file and asks me whether to restart NP++ in the administrator mode.
> 
> ### Steps to Reproduce the Issue
> None, for it is occasionally.
> 
> ### Expected Behavior
> File saving without this strange message.
> 
> ### Actual Behavior
> See above.
> 
> ### Debug Information
> None.
> 
> None.

I also have this problem :(

**Comment by Docteh** [comment] 2021-11-08 03:21
@blackraz got any debug information? I've been running 8.1.9 x64 on Windows 10, haven't seen this pop up yet.

Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Users\Kyle\Downloads\npp.8.1.9.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by blackraz** [comment] 2021-11-08 09:19
I've been running np++ 8.1.9  x64 on Windows 11 and I have prompted, that file cannot be saved.
 I have downgraded np++ 8.1.8, 8.1.7, 8.1.6 and no luck, after downgrading np++ to 8.1.5 the problem has been solved

**Comment by SamweisWeb** [comment] 2021-11-08 16:59
@donho
The file is in no special folder. I use it for years, no Admin privileges..

**Comment by donho** [comment] 2021-11-08 17:25
@blackraz @SamweisWeb 
Could you provide your debug info please?
You can get the debug info via menu `?->Debug Info...`.

**Comment by SamweisWeb** [comment] 2021-11-08 17:33
@donho
Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1320
Current ANSI codepage : 1252
Plugins : BetterMultiSelection.dll CodeAlignmentNpp.dll Linter.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppEditorConfig.dll NppExport.dll NppSnippets.dll PreviewHTML.dll RunMe.dll SQLinFormNpp64.dll

**Comment by donho** [comment] 2021-11-08 17:38
@SamweisWeb 
I'm not sure if it's plugin issue. 
Could you please remove all plugins to make sure this issue doesn't come from one of your plugins?

**Comment by CNCHoward** [comment] 2021-11-08 19:35
> ### Description of the Issue
> As of the latest release 8.1.9 of NP++ 64bit, more than occasionally I'm being prompted with a strange message while trying to save a file. The message informs me about not being able to save the file and asks me whether to restart NP++ in the administrator mode.
> 
> ### Steps to Reproduce the Issue
> None, for it is occasionally.
> 
> ### Expected Behavior
> File saving without this strange message.
> 
> ### Actual Behavior
> See above.
> 
> ### Debug Information
> None.
> 
> None.


We have been having the same issue since the 8.1.9 update.  when we have a program file open in notepad++ while the program is also open in out CNC verification software we get the same error from above.  when the CNC software is closed we no longer are prompted with that warning and can proceed to save normally.  we reverted to version 8.1.5 and the problem dissapeared.

**Comment by donho** [comment] 2021-11-08 19:42
@CNCHoward 
What it is CNC verification software? Where can I get it to reproduce such issue?

@SamweisWeb 
Do you use CNC verification software or somethings similar?

**Comment by CNCHoward** [comment] 2021-11-08 19:46
The Verification software is called Vericut made by CG Tech.   software will open the program file and run our part in a simulation setting.  we will simultaneously have the same file open in Notepad++ to edit as we go if needed.

**Comment by xomx** [comment] 2021-11-08 21:05
@donho 
I can reproduce problematic sharing violation by opening the same text file both in N++ and MS Word.
1. create a txt-file in N++, save it and leave it opened in N++
2. open the saved file simultaneously in MS Word
3. switch back to N++, edit the file a bit and try to save the changes = Save failed dlg (The file cannot be saved and it may be protected. Do you want to launch Notepad++ in Administrator mode?)

I think that the N++ has somewhere invalid setting for the file sharing mode as it allows other programs to lock the already opened file for writing.

**Comment by donho** [comment] 2021-11-08 22:00
@xomx 
> 1. create a txt-file in N++, save it and leave it opened in N++
2.  open the saved file simultaneously in MS Word
3.  switch back to N++, edit the file a bit and try to save the changes = Save failed dlg (The file cannot be saved and it may be protected. Do you want to launch Notepad++ in Administrator mode?)

I can reproduce in both v8.1.9 & v7.9.5 - so it's a normal behaviour for the scenario you provided.

**Comment by donho** [comment] 2021-11-08 22:09
@CNCHoward 
> The Verification software is called Vericut made by CG Tech. software will open the program file and run our part in a simulation setting. we will simultaneously have the same file open in Notepad++ to edit as we go if needed.

Thank you for the info. So if I do understand you well, the same file is opened by both Vericut  & Notepad++, and if user modified the file in Notepad++ and try to save, v8.1.9 ALWAYS complains and wants to launch in Admin mode, whereas v8.1.5 saves the file without any problem. Is my description is accurate?

**Comment by CNCHoward** [comment] 2021-11-08 22:12
that is an accurate depiction.  i did open a file in both MSWord and N++ as described above using v8.1.5 and encountered the same problem they listed.  

We are NOT however having any problems between Vericut and N++ using 8.1.5

**Comment by donho** [comment] 2021-11-08 23:25
@CNCHoward 
Thank you for your confirmation.
The problem is the software Vericut - I went to their site and find nowhere to download the trial version.
Without reproducing on dev machine there's little chance to fix this bug.

**Comment by donho** [comment] 2021-11-08 23:27
@pnedev 
Maybe you have any idea for this issue come from?

**Comment by SamweisWeb** [comment] 2021-11-09 01:03
@donho 
No, I don't use any CNC verification software or something similar.
I guess the last Notepad++ release I used was 8.1.7, and it worked well. No other app has been installed since that release.

**Comment by donho** [comment] 2021-11-09 01:28
@SamweisWeb 
> As of the latest release 8.1.9 of NP++ 64bit, more than occasionally I'm being prompted with a strange message while trying to save a file. The message informs me about not being able to save the file and asks me whether to restart NP++ in the administrator mode.

So when the message came, what did you do? Launch Notepad++ in Admin mode and save the file? Or you deny it then save file again? What's the result of saving file?

**Comment by SamweisWeb** [comment] 2021-11-09 01:30
@donho 
I denied the message -- for I haven't seen it ever and there was no other access to this file by another program or other restrictions -- and tried to save the file, which worked: the file was saved okay.

**Comment by donho** [comment] 2021-11-09 01:42
@SamweisWeb 
So it's a random behaviour to you. I've checked saving routine but cannot see any problem on it. The only explanation for your case to me is that some plugins could have incompatibility with v8.1.9. Please run your v8.1.9 without plugin and let me know the final result in a few days (or as soon as the issue happens again).

**Comment by CNCHoward** [comment] 2021-11-09 13:20
@donho    I hear what your saying about the problem being Vericut. I have a little bit of a hard time with that since the ONLY thing that changed for us was the N++ update.  There must be something there since we are able to operate normally with v8.1.5.  

Vericut is pretty stingy, i cant imagine they would have a "trial" version of their software for download considering what they charge us for the real thing.

**Comment by pnedev** [comment] 2021-11-09 13:54
> @pnedev Maybe you have some idea for where this issue come from?
> 
> _**Edit: I'm wondering if the following line:**_ https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/MISC/Common/FileInterface.cpp#L135 _**`share = 0;` should be `share = FILE_SHARE_READ | FILE_SHARE_WRITE;` for fixing this issue.**_ _**What do you think?**_

@donho , @SamweisWeb , All,

Yes, this is the root cause for the issue.
When I made the file access class using Win32 API I intentionally disabled the sharing file flag when the file is to be modified. That seemed the right decision to me at the time because if you try to save and some other program had opened the file at the same time collisions might occur. The old file API didn't care for the sharing violations and the concurrent file write access so no such problems back then.

In my opinion the behavior should be what you have reported about 8.1.9 - do not write file if sharing violation occurs.
If you think this is not the correct behavior then yes, @donho please modify the sharing flag as you have pointed out so we disregard the share collision.
But if you modify the share flag I think it's better to set it to FILE_SHARE_READ only so we write the file ONLY if it is already opened by another program with read access. If it is opened by another program for writing as well then this is surely something that can potentially lead to messed content.

**Comment by donho** [comment] 2021-11-09 13:59
@CNCHoward 
> I hear what your saying about the problem being Vericut. I have a little bit of a hard time with that since the ONLY thing that changed for us was the N++ update. There must be something there since we are able to operate normally with v8.1.5.

Yes I confirm that. The most important modification from v8.1.5 to v8.1.9 is saving (writing file on disk) function: In order to fix [loosing data critical bug](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133), the saving function was rewritten with win32 native API (for replacing the POSIX routines), therefore though the change of file accessing behaviour is not desirable (with the interaction of other application), there is little thing I can do about it - especially I have no Vericut for reproducing the issue.

OTOH, what @SamweisWeb has experienced is a different issue - it's surely due to the important modification in v8.1.9, but it could be the plugins' incompatibility.

**Comment by xomx** [comment] 2021-11-09 14:14
@donho 
You are right, the file sharing behavior mentioned by me is a standard N++ one, I just tried the older versions too.

@pnedev 
I just run a N++ debugging session and it looks like that N++ does not keep the file handle of the opened file! So for every other file saving it calls the CreateFile API again (and obtains a new file handle and then it closes it again). If it is so, it does not matter what is _share_ variable set to! This also explains my test results with MS Word above.

Also the current setting share=0 means no sharing at all, see the MSDN for the CreateFileA:

dwShareMode ... If this parameter is zero and CreateFile succeeds, the file or device cannot be shared and cannot be opened again until the handle to the file or device is closed.

But because the file handle opened with share=0 is not held, anyone can do anything with the file currently opened in N++.

Or am I wrong?

**Comment by CNCHoward** [comment] 2021-11-09 14:14
@donho  @pnedev ,

Could I hypothetically, reinstall 8.1.9, change the code on the share line and test the problem my self with Vericut?

**Comment by pnedev** [comment] 2021-11-09 14:54
@xomx ,

You are right - Notepad++ does NOT keep the file handle because it operates with the file contents in memory.
So first it opens the file with read access, reads the content in memory, frees the handle, the user does his/hers changes and then on save N++ opens the file again with write access to store modify the file. That is not bad since the file change by the user might take long time but, well that's how the things are currently.

About the sharing - when Notepad++ tries to write the file it tries to open it for writing. If at that moment it is already opened by other program and the share flag is zero, then IMO the system is instructed to deny opening the file on share conflict and the open fails. So IMO the share flag is what type of sharing is tolerable.
As an example if ProgramA has open handle to our file for reading and we from Notepad++ try saving the file with share = 0 then the system sees that another program is currently reading the file and thus denies our CreateFile call since we are not tolerating sharing. Same goes for the case when ProgramA has open handle for writing and our share flag says to the system what kind of sharing we accept.

So here it is a matter of who gets the file handle first - Notepad++ or ProgramA. And when ProgramA releases the handle then Notepad++ can save the file again.

@CNCHoward ,

Yes, if you can make the changes to Notepad++ source changing the file share flag pointed by @donho , compile it and replace the original notepad.exe with the one build by you, you can test the scenario again to see if that helps in your case.
I'm pretty sure it will. But my suggestion is to set the flag to read sharing permission ONLY to avoid collisions so
`share = FILE_SHARE_READ;`

**Comment by CNCHoward** [comment] 2021-11-09 15:08
@pnedev  ive never done anything like this before and im not sure where i would even start as to edit the file or compile.  ive only in the last couple weeks started learning C++.   if its not to big of a deal could you direct me how to edit this? if youre busy i understand.  i do have visual studio as ive just started learning that platform....  im prety green here.  thanks again.

**Comment by CNCHoward** [comment] 2021-11-09 15:23
@pnedev  you know what i realised thats quite the how to session youd be in for.  dont worry about it.  ill wait for you guys to hopefully rectify the problem and send and update.. Thanks!

**Comment by donho** [comment] 2021-11-09 15:30
@CNCHoward 
>> Could I hypothetically, reinstall 8.1.9, change the code on the share line and test the problem my self with Vericut?
> Yes, if you can make the changes to Notepad++ source changing the file share flag pointed by @donho , compile it and replace the original notepad.exe with the one build by you,

I can at least modify the source & compile the binary for you. And you can test the binary.

**Comment by CNCHoward** [comment] 2021-11-09 15:31
@donho lets try that!  thanks!

**Comment by pnedev** [comment] 2021-11-09 15:32
> @pnedev you know what i realised thats quite the how to session youd be in for. dont worry about it. ill wait for you guys to hopefully rectify the problem and send and update.. Thanks!

Better, it is not rocket science but is a lot to explain all the specifics.

@donho , if you can build a test binary for him that would be great. But let me suggest again to set only FILE_SHARE_READ.
And the @CNCHoward  can verify if the problem persists.

**Comment by CNCHoward** [comment] 2021-11-09 16:06
@donho  @pnedev   I ran the new binary that was provided and it fixed the problem we were having between N++ and Vericut.  Thanks for looking into it! now that we all have an answer our office is going to stick with 8.1.5 (which works currently) till you guys send a new update that fixes the problem.  Thanks!

**Comment by donho** [comment] 2021-11-09 16:22
@CNCHoward 
That's a good news - thank @pnedev & @xomx 's help!

@pnedev 
Do you think this fixes also the problem of @SamweisWeb ?

**Comment by pnedev** [comment] 2021-11-09 16:45
@donho ,

I suspect it will fix also that problem but let me check again first.
Later tonight, I don't have time right now.

**Comment by SamweisWeb** [comment] 2021-11-09 19:23
@donho 
Having the plugins removed, until now I don't receive the issue again. I stick with N++ latest release, for it provides other fixes, and am looking forward for an updated N++ release covering the fix discussed here. Then I intend to install my plugins one by one to watch the effects.

**Comment by mere-human** [comment] 2021-11-09 21:39
Hi all,
I have the same problem with v8.1.9.
This occurs with a file that is stored on Google Drive. It is a simple .txt file that is opened in Notepad++. When I edit it and save often, the mentioned dialog about reopening as admin appears.

**Comment by donho** [comment] 2021-11-09 21:59
@mere-human 
Can you reproduce with the fix:
http://download.notepad-plus-plus.org/repository/MISC/
?

**Comment by pnedev** [comment] 2021-11-10 03:05
> 
> 
> @CNCHoward That's a good news - thank @pnedev & @xomx 's help!
> 
> @pnedev Do you think this fixes also the problem of @SamweisWeb ?

@donho ,

The fix https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10765 you did should also solve the problem of @SamweisWeb .
Perhaps some of the linter plugins or the HTML preview plugin are accessing the file for reading IDK for sure.

It should fix it also for @mere-human 's problem but he needs to confirm that to be sure.

**Comment by mere-human** [comment] 2021-11-10 11:41
> @mere-human Can you reproduce with the fix: http://download.notepad-plus-plus.org/repository/MISC/ ?

I don't the the issue with the provided version of Notepad++.

**Comment by donho** [comment] 2021-11-10 13:15
@pnedev @mere-human 
Thank you for your confirmation!
There'll be a new version soon for remedy this issue.

**Comment by donho** [comment] 2021-11-10 13:31
@SamweisWeb 
> Having the plugins removed, until now I don't receive the issue again. I stick with N++ latest release, for it provides other fixes, and am looking forward for an updated N++ release covering the fix discussed here. Then I intend to install my plugins one by one to watch the effects.

It's indeed a regression of Notepad++:
Obviously, one of plugins you installed opens the editing file, that Notepad++ tries to save but no sharing access to this file - it makes saving failed. I will do a new release in few days. In the mean time, you can use the binary here (with all your plugins restored): 
http://download.notepad-plus-plus.org/repository/MISC/

Thank you for the reporting bug and testing.

**Comment by btanner2** [comment] 2021-11-15 07:54
Hi,

I have exactly the same issue. I worked with notepad++ for years now always in the same files. These files are log files from a local test/debug server, which writes log entries into this file. To reproduce issues, I clean the file with notepad++ and reproduce the issue with local server. This worked like a charm until the new version:

notepad++ 8.1.5 works
notepad++ 8.1.9 works not

With the new version, I got the screen “the file cannot be saved”.

your fix here:
http://download.notepad-plus-plus.org/repository/MISC/

Does NOT solve the problem. I guess the reason is, the server application has write access to this log file. Please, make the behavior of notepad++ is choosable via settings for this situation. Other editors like ultraedit can save this file without any problem. I do not want to change from notepad++ to something else, but I have to, since I cannot work anymore with the new version.

Could you help me out here?

Thanks a lot
brian

**Comment by CarlosMOGoncalves** [comment] 2021-11-16 12:56
Hello there,

I would just like to second here btanner2.
I have just updated to the latest version of notepad++ (8.1.9.1) and it will still say "the file cannot be saved" and whether I would like to open Npp as Admin. If I do, however, I still cannot save the file.

Just like btanner2, I am also doing this on log files (Postgres log files to be more specific). Sometimes I just want to fully erase them so they can be rewritten again, but it won't be possible in the latest two versions of Npp. These log files are being written by Postgres at the same time, so there probably lies the problem.

I hope this clue can help.

Thanks

**Comment by donho** [comment] 2021-11-16 16:29
@CarlosMOGoncalves & @btanner2 
It's not the same problem.
Could you please open a new issue about your problem? I'll assign to myself for finding the solution.

**Comment by donho** [comment] 2021-11-16 17:13
@btanner2 

> your fix here: http://download.notepad-plus-plus.org/repository/MISC/
> 
> Does NOT solve the problem.

The link has been changed: http://download.notepad-plus-plus.org/repository/MISC/NewFix/
Did you tried the latest version v8.1.9.1 ?

**Comment by pnedev** [comment] 2021-11-17 00:43
@donho ,

From the additionally reported issues by @btanner2 and @CarlosMOGoncalves it seems that for their use cases the flag `FILE_SHARE_WRITE` will also need to be added to `share` file param.

**Comment by donho** [comment] 2021-11-17 03:35
@pnedev 
Thank you for the hint.

@btanner2 & @CarlosMOGoncalves 
I just did a quick fix with @pnedev 's suggestion here:
http://download.notepad-plus-plus.org/repository/MISC/NewFix2/

Could you test the binary please ?

**Comment by btanner2** [comment] 2021-11-17 10:00
> 
> 
> @pnedev Thank you for the hint.
> 
> @btanner2 & @CarlosMOGoncalves I just did a quick fix with @pnedev 's suggestion here: http://download.notepad-plus-plus.org/repository/MISC/NewFix2/
> 
> Could you test the binary please ?

@pnedev
great suggestion

@donho
Works like a charme! Problem solved. 

If you just would rollout v8.1.9.2, you would made my day! (not in the way, like Dirty Harry meant it :-D)

Brian

**Comment by CarlosMOGoncalves** [comment] 2021-11-17 10:46
Hello everyone,

I would just like to confirm that this fix indeed does the trick and works perfectly.
The files are saved without hesitation or prompt. Great work.

Thanks a lot for your very quick fix.

**Comment by GTR8000** [comment] 2021-11-18 19:33
I was experiencing an issue saving files to Box Drive with some of the recent x64 releases. After editing a file (XML, for example) it would save a weird version that contained both my edits as well as some of the original contents of the file that I deleted before saving. No error messages or prompts popped up, it simply did not save the contents of the files correctly.

I rolled back to x64 8.1.5, and that seems to have cleared up the issue. I subsequently updated to 8.1.9.1 last night, and the issue resurfaced.

A few minutes ago I grabbed the updated exe from the NewFix2 npp.x64.newFixNetworkDriveShare.zip file, and that seems to have fixed the issue for the time being.

I see that there is a newer exe in NewFix4 npp.x64.zeroShare.zip, so I'll give that a try as well.

**Comment by donho** [comment] 2021-11-18 23:19
@GTR8000 
> A few minutes ago I grabbed the updated exe from the NewFix2 npp.x64.newFixNetworkDriveShare.zip file, and that seems to have fixed the issue for the time being.

Thank you for your confirmation.

> I see that there is a newer exe in NewFix4 npp.x64.zeroShare.zip, so I'll give that a try as well.

This binary revert some fixes for a isolated case, so it is not necessary for trying it. Please stick on the NewFix2.

**Comment by jacobwatkinsgit** [comment] 2021-11-21 06:42
I had the problem of a write-lock that appeared with 8.1.9.1, and the game Factorio. The file is factorio-current.log and is 100% reproducible while the game is open. Confirming npp.8.1.9.2.portable.x64 in http://download.notepad-plus-plus.org/repository/8.x/8.1.9.2/ solved my problem

Thanks!

**Comment by GTR8000** [comment] 2021-11-25 04:10
> @GTR8000
> 
> > A few minutes ago I grabbed the updated exe from the NewFix2 npp.x64.newFixNetworkDriveShare.zip file, and that seems to have fixed the issue for the time being.
> 
> Thank you for your confirmation.
> 
> > I see that there is a newer exe in NewFix4 npp.x64.zeroShare.zip, so I'll give that a try as well.
> 
> This binary revert some fixes for a isolated case, so it is not necessary for trying it. Please stick on the NewFix2.

Unfortunately I am still experiencing issues saving files in Box Drive with 8.1.9.2 x64. I performed an upgrade as well as a clean install. Files are still being saved incorrectly, and I'm not quite sure what to do about that, aside from rolling all the way back to 8.1.5 which seems to be the last good working version.

For those unaware of what Box Drive is, it's a sync cloud service similar to Dropbox or Sync.com, however the local files are stored in a mounted volume, not a physical directory. Whenever the software is running, the volume is mounted.

https://support.box.com/hc/en-us/articles/360043695894-Technical-Information-for-Box-Drive-Administrators

**Comment by pnedev** [comment] 2021-11-25 08:39
@GTR8000 ,

Can you try something please?
Try increasing the file size (editing by adding some new lines and changing some of the existing content). The save should be working fine in that case IMO.
Try then changing some of the existing content but reducing the file size (deleting some lines). The save now will probably not work as expected leaving the file to its previous size and you'll have your deleted lines still there.
Could you confirm that please or share what is the result from the test?
Thanks.

**Comment by GTR8000** [comment] 2021-11-25 16:51
> @GTR8000 ,
> 
> Can you try something please? Try increasing the file size (editing by adding some new lines and changing some of the existing content). The save should be working fine in that case IMO. Try then changing some of the existing content but reducing the file size (deleting some lines). The save now will probably not work as expected leaving the file to its previous size and you'll have your deleted lines still there. Could you confirm that please or share what is the result from the test? Thanks.

That is exactly the behavior I'm experiencing. Bear with me while I briefly explain:

I keep an XML file in a directory in Box Drive. The file is normally very small, under 250 KB. Once a week the file gets overwritten by other software, resulting in a larger XML file that contains many lines, and can be as large as 5 MB. I open that larger file in Notepad++ and run a macro on it, which prunes it back down to the much smaller size after it removes many lines from the file, and leaves only the bare minimum text that I need.

So for example the file might go from 50,000 lines @ 2.5 MB down to 1,600 lines @ 30 KB after running the macro and saving.

That's where the trouble begins. As soon as I save the file post-macro, the file size in Box Drive remains much larger than it should be. If I open that file in another text editor, I still see the deleted lines in the file.

One workaround I've been using is to run the macro, save the file (observing that the file size in the directory is incorrect), then I will jump to the end of the file and add an empty line, re-saving the file. That seems to force the file to save correctly.

I hope this is helpful, thank you!

**Comment by pnedev** [comment] 2021-11-27 09:01
@GTR8000 ,

Thank you for the thorough explanation it certainly helps 👍 !

**Comment by donho** [comment] 2021-11-29 04:49
@pnedev 
Do you think the log of #10847 will help us for this issue?

**Comment by GTR8000** [comment] 2021-11-29 04:53
Note that I have reverted back to 8.1.5 x64, which seems to be the last version working well for me, but I'm following this thread and am more than happy to test out any subsequent releases or test files. Thank you!

**Comment by donho** [comment] 2021-11-29 05:03
@GTR8000 
Thank you!
Please use the following binary (Not necessary to replace your current Notepad++): [Notepad++ x86](https://ci.appveyor.com/api/buildjobs/l55mssnvg431a717/artifacts/Notepad%2B%2B.Win32.Release.exe) or [Notepad++ x64](https://ci.appveyor.com/api/buildjobs/50e43knu62r917mq/artifacts/Notepad%2B%2B.x64.Release.exe).

The binary contains the writing log ability in case of problem. To activate log, you should:

1.    Add an empty "nppLogNetworkDriveIssue.xml" file beside of notepad++.exe, or if you have no admin privilege, you can add this file into `%APPDATA%\Notepad++\`.
2.    Create `C:\temp\` directory, if it doesn't exist yet.
3.    Start notepad++.exe, and wait for the error happens from the network drive. If the errors occur, there should be some trace in "C:\temp\nppLogNetworkDriveIssue.log". Please provide nppLogNetworkDriveIssue.log to us.

With the information you provide, there might be better chance to fix it finally.
Thank you in advance!

**Comment by GTR8000** [comment] 2021-11-29 05:22
I just ran my macro against two separate files, saved them both to Box Drive, and got the following two errors logged. I've obscured some of the personal info in the filenames.

Note that no other process had either file open aside from perhaps the Box Drive sync program, which is normal. As previously noted, this was never an issue with release 8.1.5 or older, only started recently with 8.1.6 and newer.


**2021-11-29 00:14:51  C:\Users\XXXX\Box\UCL\XXXX.xml  SetEndOfFile call failed: The process cannot access the file because it is being used by another process.

2021-11-29 00:16:09  C:\Users\XXXX\Box\UCL\YYYY.xml  SetEndOfFile call failed: The process cannot access the file because it is being used by another process.**

**Comment by donho** [comment] 2021-11-29 14:32
@GTR8000 
Could you try the fix: [32 bits](https://ci.appveyor.com/api/buildjobs/36xeeoeu68fh6jen/artifacts/Notepad%2B%2B.Win32.Release.exe) or [64 bits](https://ci.appveyor.com/api/buildjobs/hui4t4w7t6ni265m/artifacts/Notepad%2B%2B.x64.Release.exe)
Please remove the old log file before testing.

**Comment by GTR8000** [comment] 2021-11-29 14:40
Same result...

SetEndOfFile call failed: The process cannot access the file because it is being used by another process.

Just curious...if we know this behavior started between 8.1.5 and 8.1.6, couldn't you simply revert whatever code is causing this issue?

**Comment by GTR8000** [comment] 2021-11-29 14:46
Update: I was testing the 64 bit fix, which still has the issue. I tested the 32 bit fix, and that seems to be working correctly with two files modified and no errors logged.

Did you apply the fix correctly to the 64 bit fix file so that it will work correctly on 64 bit Windows?

**Comment by donho** [comment] 2021-11-29 16:26
@GTR8000 
> Did you apply the fix correctly to the 64 bit fix file so that it will work correctly on 64 bit Windows?

Just checked again the URL of the binary I provided, I confirm the fix has been applied to both binaries.
The explanation I can imagine for the different behaviours is, the execution performance of x86 is slower slightly, that leaves the file got enough time to be available.

> Just curious...if we know this behavior started between 8.1.5 and 8.1.6, couldn't you simply revert whatever code is causing this issue?

We've got a [critical issue](#6133) which makes data lost after MS update restarting windows or after PC restarting a power loss brutally.
To remedy this issue we have change the saving method in v8.1.6 - v8.1.9.2. We don't revert to v8.1.5 for the following reasons:
1.  The replacing saving method is MS Windows native API, there's no reason that it doesn't work.
2.  Since the saving method is the core function, it's not trivial to revert it and reverting could cause the other regression.
3.  We are still collecting the info of data loosing issue in order to fix it.

Thank you for your testing!

**Comment by xomx** [comment] 2021-11-29 17:18
@GTR8000 
Could you also test the vanilla 8.1.9.2 32-bit version? (to be sure that the different bitness behavior is not caused by the current fix at all...)
E.g. use the N++ executable from this archive:
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.1.9.2/npp.8.1.9.2.portable.7z
Thanks!

**Comment by GTR8000** [comment] 2021-11-29 18:21
Tested the portable versions of 8.1.9.2, both 32 bit and 64 bit, and am only seeing the issue with the 64 bit version.

**Comment by donho** [comment] 2021-11-29 20:38
So the fix (reverse the order in which SetEndOfFile and FlushFileBuffers) doesn't work to you at all.
Maybe the REAL FIX is stop releasing x64... :)

Joke aside, @pnedev , should I use `CREATE_ALWAYS` instead of `OPEN_ALWAYS` and remove  `SetEndOfFile` call for testing?
Do you think it's worth to try?

**Comment by pnedev** [comment] 2021-11-29 22:29
> Joke aside, @pnedev , should I use `CREATE_ALWAYS` instead of `OPEN_ALWAYS` and remove `SetEndOfFile` call for testing?
> Do you think it's worth to try?

@donho ,

Yes, I think it will fix the issue but will bring back this problem: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5664#
Anyway, maybe its better to have the issue 5664 than the network file write problems and we can find another solution to 5664 later.

**Comment by pnedev** [comment] 2021-11-29 22:33
@mere-human ,

I think `LockFileEx` will not help in our case but maybe we can try using `WriteFile` asynchronously and wait for the OS to signal us when ready.

**Comment by donho** [comment] 2021-11-29 23:08
@pnedev 
> Yes, I think it will fix the issue but will bring back this problem: #5664
> Anyway, maybe its better to have the issue 5664 than the network file write problems and we can find another solution to 5664 later.

Yes, agree with you.
Will it also fix the false alert after saving?

**Comment by donho** [comment] 2021-11-30 00:07
@GTR8000 
Could you test these both binaries please: [x86](https://ci.appveyor.com/api/buildjobs/lvqrv5ubw3dptmty/artifacts/Notepad%2B%2B.Win32.Release.exe) and [x64](https://ci.appveyor.com/api/buildjobs/r6pwcniyn0i6tfcm/artifacts/Notepad%2B%2B.x64.Release.exe)

**Comment by GTR8000** [comment] 2021-11-30 03:32
> @GTR8000 Could you please test these both binaries with new fix: [x86](https://ci.appveyor.com/api/buildjobs/lvqrv5ubw3dptmty/artifacts/Notepad%2B%2B.Win32.Release.exe) and [x64](https://ci.appveyor.com/api/buildjobs/r6pwcniyn0i6tfcm/artifacts/Notepad%2B%2B.x64.Release.exe)

Both seem to be working as expected.

**Comment by pnedev** [comment] 2021-11-30 08:46
> Will it also fix the false alert after saving?

@donho ,

I'm not sure about that but it is possible. Can someone test that?

@GTR8000 ,

Thank you once again for helping with testing. :+1:

**Comment by donho** [comment] 2021-11-30 14:37
@pnedev
> I'm not sure about that but it is possible. Can someone test that?

The request has been done:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10688#issuecomment-982288227

Let's wait & see.

**Comment by xomx** [comment] 2021-12-01 14:25
@pnedev 
> I think `LockFileEx` will not help in our case but maybe we can try using `WriteFile` asynchronously and wait for the OS to signal us when ready.

I agree with that the LockFileEx will not help us, but I think the same about the asynchronous WriteFileEx. I suspect that the problem is that on some network storage places its network layer implementation (eg SAMBA) "lies" to us or it has some incompatible implementation for the SetEndOfFile. The current N++ WriteFile call is synchronous, so it should NOT return, until all the data is written (or an error occurs, I suppose we are not using a read-buffer for a pipe in N++ - that is another possibility). Maybe their network storage (eg under higher load) only queues the requested write operation, but its answer to our WriteFile operation is 'it is done'. Then for some reason it cannot follow the same procedure for our SetEndOfFile operation (in fact another synchronous write op).

I hope that in the future we will find better solution than this CREATE_ALWAYS. The whole thing with replacing the POSIX IO has been undertaken to increase reliability under some circumstances (reboots, BSODs, power outages...). Otherwise there will be soon users asking, why theirs file has now zero size or similar...

**Comment by donho** [comment] 2021-12-01 17:14
@pnedev 

> I wanted just to point out again that `Mode::APPEND` will not be working anymore since file is wiped on `CreateFile` with `CREATE_ALWAYS` mode. This means that `writeLog` function from `Common.cpp` will not be working anymore (it is the only place where `Win32_IO_File` is used in `APPEND` mode). Currently `writeLog` is not used anywhere but maybe it's safer to delete it.
> So basically `Win32_IO_File` becomes now simple file writer (`WRITE` mode is the only one left) making `enum class Mode` obsolete and the `read` method also unnecessary.

Yes, I'm aware of it.  In #10847 the Mode in Win32_IO_File is removed (so it's Mode::WRITE only now) and writeLog has been rewritten (OPEN_ALWAYS) for being able to log trace in Win32_IO_File.

 @xomx 
> I hope that in the future we will find better solution than this CREATE_ALWAYS. The whole thing with replacing the POSIX IO has been undertaken to increase reliability under some circumstances (reboots, BSODs, power outages...). Otherwise there will be soon users asking, why theirs file has now zero size or similar...

Maybe the up-coming release will prove me wrong - `CREATE_ALWAYS` seems to me the right parameter (of Win32 API) for the usual saving file usage of a code/text editor. We've got some feedback of users who have still experienced the null content file corruption and session file loose, so I wonder if the usage of native Win32 writing API has fixed these issues. The problem could come from somewhere-else. Let's wait and see in 2 or 3 months.

**Comment by xomx** [comment] 2021-12-01 17:30
@donho 
I had in mind that when we successfully call the CreateFile with CREATE_ALWAYS, the file will be immediately truncated to zero length. If then something happens in between CreateFile and WriteFile, users will have zero sized files.

**Comment by donho** [comment] 2021-12-01 18:00
@xomx 
OK, I see your point.

**Closed** 2021-12-01 19:42 UTC
Labels: accepted, regression

**Comment by GTR8000** [comment] 2021-12-01 22:29
So what's the bottom line here, folks? Is 8.1.9.3 going to contain the permanent fix for the issue I'm experiencing with saving files to Box Drive?

**Comment by donho** [comment] 2021-12-01 23:23
@GTR8000 

v8.1.9.3 will contains this fix and more logs for the nul content file corruption and for 0 length mentioned by @xomx .

**Comment by pnedev** [comment] 2021-12-02 14:14
@xomx ,

I totally agree with you.
The Win32 file access class was needed for two reasons:
1) To remedy problem #5664 by using `OPEN_ALWAYS` to not destroy file contents on open before write.
2) To be able to specify the `FILE_FLAG_WRITE_THROUGH` so the Windows lazy writes is bypassed and on `FlushFileBuffers()` call the cache is directly flushed to disk without delay. This is to remedy the NUL file contents problem reported so many times in the past.

Now when `OPEN_ALWAYS` is replaced by `CREATE_ALWAYS` the first reason is not addressed directly by our Win32 API but unfortunately we cannot go back to using `OPEN_ALWAYS` because it seems it is working flawlessly only on Windows. On network accessed files it is not behaving reliably as described and there is nothing we can do about that. I wondered why the CRT file API (`fopen`, `fwrite`, etc) didn't have the option to open file for writing without first truncating it to zero and now it seems that it is not straightforward and reliable thing.

So we should stick to using `CREATE_ALWAYS` but still the second reason for our Win32 API is addressed because of the `FILE_FLAG_WRITE_THROUGH` flag and the `FlushFileBuffers` call on close.
Your concern about possible problems between `CreateFile` and `WriteFile` although very reasonable have practical effect and create real problems only in case of #5664 or every other situation when `WriteFile` fails. But NUL problem is actually happening AFTER a successful file save (so no between `CreateFile` and `WriteFile`) and thus is not and will not be affected by `CREATE_ALWAYS` use.
I agree it is good idea to make further network file save investigations and tests and try remedying the problem we have with `OPEN_ALWAYS` as it is surely the safest possible approach.

@donho ,

Please reopen #5664 . The only way left we can fix it is by checking if the available disk space is enough before writing the file .

**Comment by donho** [comment] 2021-12-02 15:01
@pnedev 
> Please reopen #5664 . The only way left we can fix it is by checking if the available disk space is enough before writing the file .Done.

**Comment by julienn25** [comment] 2026-04-16 11:28
This happens to me when i do the following:

- Search for a file in windows search box (Windows 11)
- From the searchresult Open the file in notepad++ 
- Make a change in the file and try to save

Solution for me is to kill explorer.exe and then start it again. (for some weird reason "Restarting explorer.exe does not solve the problem)
