### ISSUE TITLE
Add keyboard shortcuts to Save Question Dialog

### ISSUE THREAD

**Issue by BiNZGi** [notepad-plus-plus/notepad-plus-plus#7579] opened 2019-11-15 10:49 UTC
Feature Request follow up to #5835

### Description
With #5835 a new Save Question Dialog was introduced. It has  buttons without keyboard shortcuts specified. To work a bit faster with keyboard it would be nice to have shortcuts.

### Steps to Reproduce
1. File > New
2. Write random text
3. File > Close
4. Appearing dialog don't has buttons with keyboard shortcuts specified.

### Actual Behavior
Dialog has buttons without keyboard shortcuts specified.

### Proposed Behavior
Dialog buttons have keyboard shortcuts specified, e.g.
(Y)es
(N)o
(C)ancel
Yes to (a)ll
No to a(l)l

I think this could easily made with changes in xml files, e.g.
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5ac062e731808d9fa09cfef3102d626610116686/PowerEditor/installer/nativeLang/english.xml#L992
to this:

                <Item id="6" name="&amp;Yes"/>

**Comment by sasumner** [comment] 2019-11-15 12:57
Closing as duplicate of #6223

**Closed by sasumner** 2019-11-15 12:57 UTC

**Comment by BiNZGi** [comment] 2019-11-15 15:26
@sasumner Thanks, I didn't found the mentioned one.
