### ISSUE TITLE
.vue extension support is missing

### ISSUE THREAD

**Issue by arunkumar-arjunan** [notepad-plus-plus/notepad-plus-plus#9996] opened 2021-06-13 06:36 UTC
### Description of the Issue
.vue extension support is missing

### Steps to Reproduce the Issue
1. Open a file with .vue format file  and you will see the vuejs code syntax highlight is missing

### Expected Behavior
1. When I open a .vue format file and the vuejs code syntax highlight show be  present

### Actual Behavior
1. When I open a file with .vue format file  and you will see the vuejs code syntax highlight is missing

**Comment by ArkadiuszMichalski** [comment] 2021-12-29 01:17
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4757.

**Closed by ArkadiuszMichalski** 2021-12-29 01:17 UTC
