### ISSUE TITLE
Suggestion: Add menu option and if possible a keyb shortcut to hide/show search results window.

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#3766] opened 2017-09-21 23:54 UTC
Hello,

I would like to suggest adding a menu option and if possible a keyb shortcut to hide/show search results window.

Thanks,

JM

**Comment by jcrmatos** [comment] 2017-09-22 07:57
Hello,

At least in my system F7 only shows (doesn't hide) the results window.
My suggestion was for hide/show.

Pressing F7 the 1st time changes focus to the results window and the 2nd time changes focus to inside the results window (and after that it cycles between those 2). Maybe adding a 3rd time to hide it?

Thanks,

JM

**Comment by sasumner** [comment] 2020-05-04 12:33
Closing as duplicate of the earlier #2946

**Closed by sasumner** 2020-05-04 12:33 UTC
