### ISSUE TITLE
removed User Defined Language reappears after relaunching Notepad++

### ISSUE THREAD

**Issue by superbonaci** [notepad-plus-plus/notepad-plus-plus#8101] opened 2020-04-09 23:04 UTC
### Description of the Issue

Installed awk highlight for Notepad++, tried to uninstall it but after restarting the editor it bounces back.

### Steps to Reproduce the Issue

1. Download and install [AWK.xml](https://raw.githubusercontent.com/mrharmonies/nppp-awk-highlighter/master/AWK.xml) and install from `Language -> User Defined Language -> Define your language... -> Import...`
2. Now remove `Awk` from `User Defined Language` and dissapears. In Language there's no Awk at the bottom.
3. Close Notepad++
4.Reopen Notepad++. In Language there's Awk at the bottom again.

### Expected Behavior

Be able to remove any language xml
### Actual Behavior

After closing and reopening npp all removed xml reappear.
### Debug Information

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.752
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2020-06-19 18:30
Using 7.8.7, I'm not able to replicate this behavior.
Awk disappears and does not reappear.

**Comment by denisbider** [comment] 2020-07-04 07:22
I have this problem with 7.8.7. The language is "removed" but reappears when Notepad++ is restarted. I can make changes to the language, and they are saved: for example I can rename it to "Bad Language" and change the extension to ".bad-lang" and this will be preserved when Notepad++ is restarted. However, removal is not preserved, the language is still there.

**Comment by superbonaci** [comment] 2020-07-04 08:27
@denisbider thanks for confirming.

**Comment by itandyrays** [comment] 2021-03-31 13:31
Same on 7.9.1
Solved removing language manually from %APPDATA%/Notepad++/userDefineLang.xml

**Comment by thjubeck** [comment] 2021-04-13 21:43
Had this same problem when setting up a custom language. The issue ended up being that the import file I was using had an XML error. It looks like when there is an error in the import file, Notepad++ cannot remove the language. Not sure if this is what happened here but it causes the same issue as reported.

**Comment by LucasBraunX** [comment] 2021-11-03 22:45
Same problem on v8.1.5

**Comment by DCaedus** [comment] 2022-02-23 02:18
Same issue on Notepad++ 8.2.1 64 bit

Can delete user defined language, either via 

`Language -> User Defined Language -> Define your language... -> Remove
`
Or by deleting the files from `%AppData%\Notepad++\userDefineLangs`

But after restarting NP++ the languages are back in the menu, they function just the same, even when there's no files on `%AppData%\Notepad++\userDefineLangs`

Idk if this has anything to do, but if the languages are installed by placing the files in `%AppData%\Notepad++\userDefineLangs` they show twice in the Language menu, and deleting the files from `%AppData%\Notepad++\userDefineLangs` makes them show only once (not repeated).

**Comment by white-gthb** [comment] 2022-12-25 10:03
Merry Christmas :)

Problem confirmed with Notepad++ v8.4.7 (64-bit).

The problem is that if there is only 1 imported UDL (User Defined Language), it cannot be removed.

Imported UDLs are stored in 1 file:
`%APPDATA%\Notepad++\userDefineLang.xml`

Additional UDLs in separate files are stored in the folder:
`%APPDATA%\Notepad++\userDefineLangs\`

My analysis:
* Open dialog `Language -> User Defined Language -> Define your language...`
* Use the dropdownbox `User language` to select a language to remove
* Click the `Remove` button
* In Notepad++, it appears as though the removal was successful.
* Close Notepad++
During closing the UDL is physically removed. Either the separate file in the folder `%APPDATA%\Notepad++\userDefineLangs\` is deleted or the UDL is removed from the file `%APPDATA%\Notepad++\userDefineLang.xml`.
  * If the UDL was stored in a separate file in the folder `%APPDATA%\Notepad++\userDefineLangs\`, the removal was indeed successful.
  * If the removed UDL was an imported UDL and there were 2 or more UDLs in the file `%APPDATA%\Notepad++\userDefineLang.xml`, then the removal was indeed successful. 
  * If the removed UDL was an imported UDL and there was only 1 UDL in the file `%APPDATA%\Notepad++\userDefineLang.xml`, then the UDL was not physically removed from the file. So if you start Notepad++ again, the UDL reappears.

**Comment by white-gthb** [comment] 2022-12-26 14:18
@superbonaci What are you confused about?

**Comment by superbonaci** [comment] 2022-12-27 22:42
@white-gthb let's see if the dev fixes it.

**Comment by white-gthb** [comment] 2023-01-17 09:00
Perhaps someone with the right permissions can label this issue with the "bug" label?

**Comment by d1nuc0m** [comment] 2023-04-04 13:26
Still relevant as of Notepad++ v8.5.1 (build date 2023-03-21).
If there is only one user defined language, it is saved to `%APPDATA%\Notepad++\userDefineLang.xml` and removal through `Language -> User Defined Language -> Define your language...` has no effect - to remove the UDL the user has to manually delete the file.

Ping @dail8859 @donho for labeling

**Comment by donho** [comment] 2023-04-04 16:09
@superbonaci 
With your instructions, I cannot reproduce the bug with v8.5.1:
```
1. Download and install [AWK.xml](https://raw.githubusercontent.com/mrharmonies/nppp-awk-highlighter/master/AWK.xml) and install from Language -> User Defined Language -> Define your language... -> Import...
2. Now remove Awk from User Defined Language and dissapears. In Language there's no Awk at the bottom.
3. Close Notepad++
4.Reopen Notepad++. In Language there's Awk at the bottom again.
```

Can anyone provide the step by step instructions for reproducing the bug steadily?

**Comment by donho** [comment] 2023-04-04 16:16
@white-gthb 
> If the removed UDL was an imported UDL and there was only 1 UDL in the file %APPDATA%\Notepad++\userDefineLang.xml, then the UDL was not physically removed from the file. So if you start Notepad++ again, the UDL reappears.

It's the case for my test. But it's removed correctly (after restarting Notepad++ v8.5.1).
So I cannot reproduce the bug.

**Comment by donho** [comment] 2023-04-04 16:26
@d1nuc0m 
Please provide the step by step instructions and your Debug Info via menu `?->Debug Info...`

Once I can reproduce the bug, this issue will be reopened.

**Comment by white-gthb** [comment] 2023-04-07 10:02
> ... I cannot reproduce the bug with v8.5.1:
> 
> ```
> 1. Download and install [AWK.xml](https://raw.githubusercontent.com/mrharmonies/nppp-awk-highlighter/master/AWK.xml) and install from Language -> User Defined Language -> Define your language... -> Import...
> 2. Now remove Awk from User Defined Language and dissapears. In Language there's no Awk at the bottom.
> 3. Close Notepad++
> 4.Reopen Notepad++. In Language there's Awk at the bottom again.
> ```
> 
> Can anyone provide the step by step instructions for reproducing the bug steadily?

Add step:
```
0. Make sure there are no imported languages in `%APPDATA%\Notepad++\userDefineLang.xml`
```
And after step 1 add step:
```
1b. Restart Notepad++
```
> **Edit: Please provide your Debug Info via menu `?->Debug Info...`**

Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.1485
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.5)
    HexEditor (0.9.12)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by d1nuc0m** [comment] 2023-04-08 18:53
@donho for reproducibility, I tried this in a VM with a brand new install of Windows 10 and Notepad++, to be sure there aren't old config files etc.

**Steps**

1. Install Notepad++ (used [x64 v8.5.2](https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.5.2/npp.8.5.2.Installer.x64.exe) with default install settings)
2. Download _one_ UDL such as [Asciidoc](https://raw.githubusercontent.com/edusantana/asciidoc-highlight/master/notepad%2B%2B/userDefineLang.xml) and install it through ` Language -> User Defined Language -> Define your language... -> Import... ` _(select the downloaded userDefineLang.xml)_ ` -> Open -> Import successful `
3. Close Notepad++: the file `%APPDATA%\Notepad++\userDefineLang.xml` is created on exit
4. Reopen Notepad++, the new language is now listed under `Language` 
5. Remove the UDL through `Language -> User Defined Language -> Define your language...` _(select it in the dropdown)_ `-> Remove -> Yes`
6. The language has now apparently been removed, it is no longer listed under the `Language` dropdown
7. Close Notepad++ and reopen it
8. The deleted language is now back under the `Language` dropdown


**Debug Info**
```
Notepad++ v8.5.2 (64-bit)
Build time : Apr 4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line :
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home N (64-bit)
OS Version : 22H2
OS Build : 19045.2006
Current ANSI codepage : 1252
Plugins :
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by donho** [comment] 2023-04-09 18:20
@white-gthb 
`0. Make sure there are no imported languages in %APPDATA%\Notepad++\userDefineLang.xml`
has been done, no `%APPDATA%\Notepad++\userDefineLang.xml`

Restart Notepad++, import AWK -> import successful, choose AWK via UDL dialog (however no AWK language on the buttom of Language menu), Remove->Are you sure?->Yes, exit Notepad++, restart Notepad++ 
Result: No AWK in Notepad++ UDL.

Same procedure applied to [Asciidoc](https://raw.githubusercontent.com/edusantana/asciidoc-highlight/master/notepad%2B%2B/userDefineLang.xml), the result is the same.

```
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by donho** [comment] 2023-04-09 18:32
@d1nuc0m 
I can reproduce it with your instruction.
I will see what I can do about it.
Thank you.

**Comment by white-gthb** [comment] 2023-04-09 18:36
@donho 
I see you figured it out already. You didn't follow the step to restart Notepad++ after importing the UDL so `%APPDATA%\Notepad++\userDefineLang.xml` is created.

**Comment by d1nuc0m** [comment] 2023-04-10 13:53
>  I will see what I can do about it. Thank you.

Thank you for the attention, I understand this is a corner case

**Comment by donho** [comment] 2023-04-12 14:26
Could anyone check PR #13513 and confirm me the issue is fixed?

**Closed** 2023-04-13 03:11 UTC
Labels: accepted, udl

**Comment by superbonaci** [comment] 2023-04-14 21:37
Great!
