### ISSUE TITLE
Save As dialog allows for restricted characters ( \ / : * ? " <> | ) in the filename.

### ISSUE THREAD

**Issue by FillerInfo** [notepad-plus-plus/notepad-plus-plus#4956] opened 2018-10-24 14:03 UTC
### Description of the Issue

When a user saves their file, it allows the user to type restricted characters in a filename. This causes the file to become empty (saying it has 0 bytes) after being saved. It will only be available in notepad++ until the file is closed in the editor, then it is permanently removed.

TLDR: Restricted characters allowed, file does not save properly.
### Steps to Reproduce the Issue

1. Create new file (Hotkey: Ctrl + n).
2. Type anything.
3. Attempt to save the file as (Ctrl + Alt + s).
4. Type any name with restricted character ( \ / : * ? " <> | ) in the "File name" text field.
5. Click "Save" button.
6. View the file in File Explorer and it is empty.

### Expected Behavior

Save the file with all information with restricted filename character.
### Actual Behavior

File has 0 bytes and name is all characters before restricted character.
### Debug Information

N/A

![image](https://user-images.githubusercontent.com/39528443/47435443-404b9300-d76a-11e8-9346-67a5ecc7b29e.png)
New file with text

![image](https://user-images.githubusercontent.com/39528443/47435559-7b4dc680-d76a-11e8-8cc3-07390756a4df.png)
Save as with restricted filename character

![image](https://user-images.githubusercontent.com/39528443/47435595-8dc80000-d76a-11e8-8aa3-a54b87d7e4ad.png)
Appears to be saved here

![image](https://user-images.githubusercontent.com/39528443/47435740-d2ec3200-d76a-11e8-86a0-278ccb8784aa.png)
Results in a blank file

![image](https://user-images.githubusercontent.com/39528443/47435915-134bb000-d76b-11e8-9ab6-db92dcdbf41b.png)
Extra information if useful

Thank you for taking the time to look at my bug report as this has been the result of some notes in class being lost, and I would not like that to happen to anybody else.

**Comment by sasumner** [comment] 2018-10-24 14:19
Your complaint is valid and should be addressed.  However I will suggest as a workaround: ticking the `Use new style dialog...` option in `Preferences -> Default Directory`.  If you do this Notepad++, will tell you your filename is invalid at save time.

**Comment by SinghRajenM** [comment] 2018-10-24 14:48
Below statement in file [FileDialog.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/519fecbb827eb011e6da6d546e5da1d22fb982a8/PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp#L266) causes this issue.

```C++
_ofn.Flags |= OFN_ENABLEHOOK | OFN_NOVALIDATE;
```

As per [MSDN](https://docs.microsoft.com/en-us/windows/desktop/dlgbox/open-and-save-as-dialog-boxes)
>  The dialog box automatically validates file names typed by the user to ensure that the names contain only valid characters. To override the file name character validation, set the OFN_NOVALIDATE flag.

@donho must be knowing if there was any reason to disable this automatic filename validation.

**Comment by SinghRajenM** [comment] 2018-10-24 14:56
>This causes the file to become empty (saying it has 0 bytes) after being saved.

@FillerInfo , if you lost your content, then there is way which might recover your context (but only if that particular file present in the recent file history). Then you can open it by clicking on it.

**Comment by mere-human** [comment] 2021-02-22 21:15
I cannot reproduce this.
File dialogs have been changed in v.7.9.3.
Current behavior:
![image](https://user-images.githubusercontent.com/9664141/108770945-a11a4e80-7563-11eb-9e29-8a29d603c256.png)

![image](https://user-images.githubusercontent.com/9664141/108770993-abd4e380-7563-11eb-92de-424687966105.png)

**Debug info:**
Notepad++ v7.9.3   (64-bit)
Build time : Feb 22 2021 - 22:47:45
Path : E:\Development\notepad-plus-plus\PowerEditor\visual.net\x64\Unicode Debug\Notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1252
Plugins : none

**Comment by mere-human** [comment] 2021-02-22 21:15
@sasumner Could you, please, close this issue?

**Closed** 2021-02-22 21:21 UTC
