### ISSUE TITLE
Doc comments break code folding in embedded javascript

### ISSUE THREAD

**Issue by LMLB** [notepad-plus-plus/notepad-plus-plus#3792] opened 2017-10-01 15:26 UTC
### Description of the Issue
Code folding gets confused upon seeing doc comments (`/** … */`) in embedded javascript.

### Steps to Reproduce the Issue
Paste this in a file with language set to HTML:
```
<div>

  <script>

      /**

      */

  </script>

</div>
```

### Expected Behavior
Code folding ends the comment on `*/`.

### Actual Behavior
Code folding doesn't end the comment on `*/`, but on `</script>`, and code folding after it gets shifted as well, for example, the `<script>` ends on the `</div>`.

This is what the example above looks like for me:
![Image demonstrating the bug](https://user-images.githubusercontent.com/6322603/31055918-89b7bf04-a6ca-11e7-905e-0d7d93459ec5.png)

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : none

(also tested on a fresh install with no previous config files, no difference)

**Comment by MetaChuh** [comment] 2019-04-11 23:57
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:57 UTC
