### ISSUE TITLE
Number of open files and tab visibility with large amount of open files

### ISSUE THREAD

**Issue by jporter-sdl** [notepad-plus-plus/notepad-plus-plus#1342] opened 2016-01-08 12:52 UTC
Hi guys!

Daily user of Notepad++ and I'm incredibly happy with the work you have done!

I have two small issues/suggestions I'd like to report regarding having a lot of files open so here it goes:
1. There is no quick view of the number of files you have open in Notepad++.  I suggest adding it to the status bar at the bottom.
2. When I have a lot of files open and close some I am left with only 1 tab. What it should do is fill up the remaining slots with tabs of files you have open.

Regards,
Jaimy

**Comment by MetaChuh** [comment] 2019-04-11 01:01
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 01:01 UTC
