### ISSUE TITLE
Color in jsp code in versión 7.7

### ISSUE THREAD

**Issue by gtmagus** [notepad-plus-plus/notepad-plus-plus#5749] opened 2019-06-05 23:02 UTC
### Description of the Issue
My jsp code remains black

### Steps to Reproduce the Issue
1.  Openjsp file
2. Search for jsp code
3. Just black code

### Expected Behavior
Colored code

### Actual Behavior
Black code

**Comment by dail8859** [comment] 2019-06-06 12:15
Already fixed and will be in the next release.

Duplicate of #5677

**Closed by dail8859** 2019-06-06 12:15 UTC
Labels: duplicate
