### ISSUE TITLE
Request to make clickable links support protocol relative URLs

### ISSUE THREAD

**Issue by SteveTheTechie** [notepad-plus-plus/notepad-plus-plus#3093] opened 2017-03-25 04:57 UTC
### Description of the Issue
I love the clickable links in Notepad++.   Unfortunately, in my project, I have had to move to using protocol relative URLs (URLs without http: or https: explicitly specified), which do not seem to be recognized as valid links by NPP.    For the uninitiated, the benefits of using protocol relative URLs is explained pretty well here:
[https://blog.httpwatch.com/2010/02/10/using-protocol-relative-urls-to-switch-between-http-and-https/](url)

### Steps to Reproduce the Issue
Type any URL with the beginning http: or https: (still is valid) and it is no longer clickable.

### Expected Behavior
I thought maybe NPP would still recognize the URL as valid.

### Actual Behavior
Was not recognized as valid URL that could be made clickable.

**Comment by MetaChuh** [comment] 2019-04-11 21:58
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:58 UTC
