### ISSUE TITLE
Document List Panel -> Show  (doc switcher window) is reset when opening new instance in Multi Instance mode

### ISSUE THREAD

**Issue by JimwJ05** [notepad-plus-plus/notepad-plus-plus#9762] opened 2021-04-12 19:51 UTC
### Description of the Issue
Recently upgraded from 7.9.1 to 7.9.5 and when I am in multi Instance mode, the Doc Switcher window is not opened in any follow on instances.  When I check Preferences - General - Document List Panel - Show is unchecked.  If I change it for the new instance it is ok for that instance.

After some research it appears that this problem started with the 7.9.2 release.

Version 7.9.1 and earlier work as expected.

### Steps to Reproduce the Issue
1. Bring up NotePad++
2. Went to General - Document List Panel made sure Show was checked
3. Went to Preferences - Misc. and under Document Switcher, Enable and Enable MRU behaviour were both checked. 
4. Went to Multi-Instance - Made sure Always in multi-instance mode was set
5. Bounced NotePad++
6. Opened a second instance  and the Doc Switcher window was not there.

### Expected Behavior
Doc Switcher would show up for all instances (this was the behavior for 7.9.1 and earlier)

### Actual Behavior
Doc Switcher window showed up on first instance, but not on subsequent instances and the Show check box was unchecked.

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1440
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll MultiClipboard.dll NppCalc.dll NppConverter.dll NppExport.dll NppFavorites.dll NppJumpList.dll SessionMgr.dll _CustomizeToolbar.dll 

[NotePad++_Screenshots.docx](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6299434/NotePad%2B%2B_Screenshots.docx)

**Comment by ArkadiuszMichalski** [comment] 2021-04-15 13:23
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9710.

**Comment by sasumner** [comment] 2021-04-15 13:32
Let's just keep the earlier one.

**Closed by sasumner** 2021-04-15 13:32 UTC

**Comment by JimwJ05** [comment] 2021-04-15 15:39
Sorry that I missed the earlier one and it sound good.
