### ISSUE TITLE
#php comment + start/end block of code

### ISSUE THREAD

**Issue by TALANTO** [notepad-plus-plus/notepad-plus-plus#1235] opened 2015-12-08 12:38 UTC
Look the red line on left, it marks the block but if there is a comment starting with #if or # if this red line goes wrong.  Also code shrinking is wrong.
Version 6.8.7

![issue](https://cloud.githubusercontent.com/assets/16134110/11656502/58be8ade-9dbe-11e5-8621-4667ec301108.png)
No issues with // or /\* */.

**Comment by TALANTO** [comment] 2015-12-08 12:41
No issues with // or /* */. Also code shrinking is wrong.

**Comment by MetaChuh** [comment] 2019-04-11 00:43
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:43 UTC
