### ISSUE TITLE
Will open the same file for editing more than once

### ISSUE THREAD

**Issue by JeffStuy** [notepad-plus-plus/notepad-plus-plus#1285] opened 2015-12-24 14:33 UTC
I use notepad++ in multi-instance mode.  If I double click on a file that is already open for editing in notepad++, it will open the file for editing a second time (and third time and fourth time, etc.)  
  Once a file is open for editing, notepad++ should realize that is is open and not re-open the file for editing.  Instead, it should bring the window with that file to the front / top / current.
  Notepad++ should not open files for editing if they are open by other programs as well.

**Comment by Shaggygoblin** [comment] 2015-12-25 14:28
Agree with point 1) Bring to front rather than second, third,... instance of same file.

Disagree on point 2) This 'feature' to open/edit 'in-use' files is why I use NP++.

I use 'live editing' daily, and see changes reflected instantly or on a quick reload of the instance or scene change in whatever application I'm using.  This is a HUGE time-saver.  I make single line/char edits 50+ times an hour.  The applications take ~3 to 5 minutes to start/load.  Having to close the application and restart/load it to see the effect/result of a single edit would become  2+ to 8+ HOURS to see the results of those same 50 edits!!!  Disabling this 'feature' would devastate many coders using NP++...
Perhaps a 'check if open elsewhere and notify via dialog box' via a open handle/thread check against the file, but do not disable this 'feature.'

**Comment by JeffStuy** [comment] 2015-12-27 19:57
I understand your concern.  However, I want to make sure that the same file is modified from tow different sources creating a conflict.

**Comment by Shaggygoblin** [comment] 2015-12-27 22:39
I'm pretty sure that can be handled by the suggestion I made above about the open handle or thread check. There is also an option that exists to make a file read only by right clicking on its tab, but I don't use single instance and I don't know if you actually have tabs in single instance.  It sounds to me as if you want to intentionally create conflict when two or more sources access the file. If that's the case it should most definitely be put in as an optional feature as it would contradict the current functionality which I believe the majority of current users rely on.
I would consider that enabled by default as breaking the application as it currently is and I would start looking for another editor, and I'm fairly certain that most of my colleagues would as well.  That's only a small group of 100+ out of the large number of users of NP++.  But how many small groups like mine comprise the current user base, and of those, how many will stay after a major feature they use is removed?  Just my thoughts...  Make it an option or plugin...

**Comment by Yay295** [comment] 2016-02-09 00:28
> ...I don't know if you actually have tabs in single instance.

You do.

NP++ will go to an already opened file if the file you are opening is in the last instance of NP++ you looked at. That said, I shouldn't have to make sure this is the case for NP++ to switch to an already open file.

**Comment by MetaChuh** [comment] 2019-04-13 02:06
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:06 UTC

**Comment by Yay295** [comment] 2019-04-13 17:31
reopened #5526
