### ISSUE TITLE
Reload dialog does not get back to the opened file

### ISSUE THREAD

**Issue by aaradhanas** [notepad-plus-plus/notepad-plus-plus#4189] opened 2018-02-15 14:02 UTC
### Description of the Issue
A file is open in Notepad++ (v7.4.2) and is changed using some other editor. While trying to open another file using Notepad++, the save dialog for the changed file pops up. On clicking No, the editor does not change focus to the recently opened file. This is very difficult if there are number of files.

Platform: Windows 7 (64-bit)
![image](https://user-images.githubusercontent.com/9712116/36260285-e21baf66-1286-11e8-9d62-0485fec09712.png)

### Steps to Reproduce the Issue

1.  Open a file "File1.txt" in Notepad++.
2.  Make some changes in the file in some other editor.
3.  Open another file "File2.txt" in Notepad++.
4.  The reload dialog appears since the "File1.txt" has been modified by another program.

![image](https://user-images.githubusercontent.com/9712116/36260143-81760cf6-1286-11e8-9d55-5cfd50e2ce81.png)

5. Click "Yes" to reload.
6. The focus in placed on "File1.txt" instead of "File2.txt".

![image](https://user-images.githubusercontent.com/9712116/36260099-5bee12da-1286-11e8-8e4f-5f6ad065f0aa.png)

### Expected Behavior
"File2.txt" should be opened and in focus.

### Actual Behavior
"File1.txt" is in focus.

**Comment by sasumner** [comment] 2018-02-16 12:34
Hmmm... seems to be a "judgement call" on which file should have focus in this scenario.  I can see the logic of either way..

**Comment by 42degrees** [comment] 2018-10-12 19:50
I agree with the OP.  I have specifically requested a new file be opened.  Having it switch to a previously loaded file is quite annoying.  I have to go searching to find the file that I just opened (this is especially annoying if I'm "reopening" a file that was previously loaded as it won't be the last file in the list).

**Comment by 42degrees** [comment] 2018-10-12 19:54
Duplicate of issue [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)

**Closed** 2019-03-17 12:05 UTC
