### ISSUE TITLE
Add Notepad++ option in the (immediate) right-click context menu in Windows 11

### ISSUE THREAD

**Issue by egvijayanand** [notepad-plus-plus/notepad-plus-plus#11138] opened 2022-02-07 06:08 UTC
### Description of the Issue

Add Notepad++ option in the (immediate) right-click context menu in Windows 11 as now the user has to select `Show more options` and then `Edit with Notepad++` and I see few 3rd party apps started to provide direct access to their apps from the immediate right-click context menu. Refer attached screenshot.

### Steps to Reproduce the Issue

1. Using v8.2.1 on Windows 11
2. For opening a file from File Explorer, have to click twice every single time (Right-click -> Show more options -> Edit with Notepad++)
3. As described, request to add `Notepad++` option in the immediate context menu so that it's directly accessible and saves time

### Expected Behavior

Notepad++ option is available directly in the immediate context menu.

### Actual Behavior

Available only in the detailed `Show more options` menu.

### Debug Information

<img width="246" alt="Updated-Context-Menu" src="https://user-images.githubusercontent.com/81947404/152733577-37173ebd-c9ff-4049-8a81-01fb5c3aad99.png">

**Comment by rimrul** [comment] 2022-02-08 14:39
Duplicate of #10320, #10565, #10628, #10652.

**Comment by donho** [comment] 2022-07-24 17:13
I have googled the way to add an entry on context menu under Windows 11, however, found nothing.
If anyone here knows the way to do, please let me know.

**Closed by donho** 2022-07-24 17:13 UTC
Labels: accepted

**Comment by rimrul** [comment] 2022-07-25 11:06
@donho 

https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

**Comment by vcdwelt** [comment] 2022-09-27 12:20
This worked for me:

Create a .reg file with following content (maybe the Path needs to be adjusted):

`Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\pintohome]
"MUIVerb"="Edit with Notepad++"

[HKEY_CLASSES_ROOT\*\shell\pintohome\command]
@="\"C:\\Program Files\\Notepad++\\notepad++.exe\" \"%1\""`

![grafik](https://user-images.githubusercontent.com/7173074/192524564-fdd86040-dc76-4d85-9526-cf89301ae4c9.png)

**Comment by obarak** [comment] 2022-12-17 14:18
> I have googled the way to add an entry on context menu under Windows 11, however, found nothing. If anyone here knows the way to do, please let me know.

@donho 
You can find an example of how this is done here:
https://github.com/microsoft/AppModelSamples/tree/master/Samples/SparsePackages

And more details in this blog post:
https://blogs.windows.com/blog/2021/07/19/extending-the-context-menu-and-share-dialog-in-windows-11/

**Comment by fdalsotto** [comment] 2023-08-25 10:54
shift+right click opens up the full menu. Once I selected "Edit with Notepad++" there, it came up in the initial context menu from then on.
