### ISSUE TITLE
Text does not scroll into view after pasting

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#1413] opened 2016-01-26 20:12 UTC
After pasting a long text (more lines than are currently visible below the insertion point), the text cursor/caret disappears out of view after the pasted text. That causes some confusion about the pasted text because it is not completely visible at first, like in all other editor applications.

After pasting, the caret should be visible and scrolled into view.

The view does scroll somewhat, but not enough to bring the caret into view.

NPP v6.8.8

**Comment by dail8859** [comment] 2016-01-26 22:20
Seems to be working fine for me. Plugin causing it perhaps?

**Comment by dg9ngf** [comment] 2016-02-02 19:15
Works today. Must have been one of these random neutrinos.

**Comment by dg9ngf** [comment] 2016-02-22 21:18
It comes from the word wrap. Enable it and you can see it.

**Comment by MetaChuh** [comment] 2019-04-13 01:47
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:47 UTC

**Comment by ygoe** [comment] 2019-04-13 07:30
@MetaChuh Still not fixed, still annoying. As is your mass destruction of this issue tracker. If you (or some official of this project) is no longer interested in bug reports, please let us know. An appropriate measure to show this would be closing down the issue tracker entirely. This would at least clearly state your disinterest in community participation and avoid much of the confusion your recent actions have caused.

Here's another try to make you understand that closing this is not the correct action to take.

To easily reproduce:

1. Enable line warpping
2. Get some text in a single line that wraps over half the window height
3. Copy that complete line of text
4. Go to the end of the document
5. Paste

Expected behaviour: The cursor is at the end of the pasted text and still visible.

Actual behaviour: The cursor is not vislbe anymore, only a small part of the pasted text (at the beginning) can be seen without further scrolling.

Additional info: Every. Other*. Editor. Can. Do. This. Really.

*) Editors that support line wrapping.
