### ISSUE TITLE
NotePad++ 8.4 Highlights every Instance of the first word in the document after clicking HELP | ABOUT

### ISSUE THREAD

**Issue by mastervbguru** [notepad-plus-plus/notepad-plus-plus#11639] opened 2022-05-05 10:48 UTC
### Description of the Issue

When you open a document in NotePad++ 8.4 and click HELP ABOUT, every instance of the first word of the current document is highlighted.  This behavior did NOT occur in 8.3.3 and previous versions.

### Steps to Reproduce the Issue

1.   Open NotePad++.
2.   Press CTRL + HOME to move the cursor to the beginning of the file.
3.   Click HELP | ABOUT.
4.   Notice that every instance of the first word is highlighted in the current document
5.   Re-Install 8.3.3 and repeat steps 1-3; step 4 does NOT happen.

### Expected Behavior

I would not expect NotePad++ to highlight every instance of the first word of my document

### Actual Behavior

NotePad++ highlights every instance of the first word in the current document.

### Debug Information

Notepad++ v8.4   (64-bit)
Build time : Apr 20 2022 - 03:31:06
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1645
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by DarkNami** [comment] 2022-05-05 11:42
## Steps to Reproduce the Issue

* Launch Notepad++.
* Type some words.
* Click any word (move cursor to any word.)
* Click HELP (?) | About Notepad++.
* Word highlights.

![issue](https://user-images.githubusercontent.com/5100919/166916048-d5f4ff24-1dac-4ad6-ba0c-b4297f324e80.gif)

**Comment by mastervbguru** [comment] 2022-05-05 12:47
Look at ScreenShot1.jpg.  Nothing is highlighted.  I press CTRL + HOME to move the cursor to the beginning of the file.

Then I click on HELP + ABOUT.  Now look at ScreenShot2.jpg Notice that "ECR" is not only highlighted on the first row but on EVERY instance in the current window.

For your example, take the first line of your file and **_copy it 3-4 times in your document_**.  Then press CTRL + HOME to move the cursor to the beginning of the document; then HELP + About.

![ScreenShot1](https://user-images.githubusercontent.com/65287381/166924864-a9bb1d32-be57-4425-8288-51c390b2e08f.jpg)
![ScreenShot2](https://user-images.githubusercontent.com/65287381/166924901-68afc984-8010-405d-85b5-6a39fac92634.jpg)

In your example, you only have one line in your document.  You need to have MULTIPLE lines of text in your document with the SAME word as the first word in the document.  Look at ScreenShot3.jpg (Before) and ScreenShot4.jpg (after clicking HELP | ABOUT. 
![ScreenShot3](https://user-images.githubusercontent.com/65287381/166926096-f24cc587-c1a9-4f33-a324-150493632814.jpg)
![ScreenShot4](https://user-images.githubusercontent.com/65287381/166926127-4acec869-f7d8-426b-92ec-2c34037e912d.jpg)

**Comment by mastervbguru** [comment] 2022-05-05 12:58
I have also been able to duplicate it if I put the cursor just in front of any word on the first line.  So, in the second screen print examples, if I put the cursor just BEFORE the word "instance" and then click HELP | ABOUT, the word "instance" is then highlighted everywhere in the current document.

This does NOT happen on ANY version PRIOR to 8.4

**Comment by alankilborn** [comment] 2022-05-05 13:09
@mastervbguru I don't think @DarkNami was trying to show that this isn't happening, but the fact that he presented an example where there was only one occurrence of the word under the caret really didn't help to emphasize your original point.

Never fear, though, as I can reproduce your original issue, as you stated it.  It's real! :-)

**Comment by mastervbguru** [comment] 2022-05-05 13:14
Thanks for the clarification and confirmation!  The issue arises when the SAME word is **repeated** in the current document and the cursor is placed immediately to the left of that word prior to clicking HELP + ABOUT.

**Comment by alankilborn** [comment] 2022-05-05 13:27
@mastervbguru The way you are stating it makes me think that you don't know what is happening -- do you know the _Smart Highlighting_ feature?.  What is happening is that the word at the caret is getting selected (somehow!) when input focus leaves the editor window to open the About box, and the _Smart Highlighting_ feature is (somehow!) kicking in and highlighting all occurrences of the word in the light green coloring.

**Comment by mastervbguru** [comment] 2022-05-05 15:22
I am not familiar with the Smart Highlighting feature;  thanks for mentioning it.  I will look into that!

**Comment by rdipardo** [comment] 2022-05-05 16:53
> This does NOT happen on ANY version PRIOR to 8.4

8.4 is the first release using Scintilla version 5. 

It's been reported that "8.4 changes the background color of selected text if not in focus": #11595. A fix for that issue has already been committed: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/3b0d5242acd23b4a727560ea98139cc5f4a8b88a

@mastervbguru, try running the development version found [here] and see if it still has the problem.

[here]: https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/43369853/job/32rl9xf5ejtk26hp/artifacts

**Comment by mastervbguru** [comment] 2022-05-06 13:13
I just tested that build, but it did the same thing the current (production) 8.4 version did.

**Comment by DarkNami** [comment] 2022-05-09 12:00
I can’t speak English very well.

This issue was caused by line 3163. `_pEditView->execute(SCI_GETSELTEXT, 0, 0)`
command `SCI_GETSELTEXT` select the text on caret, and 'Smart Highlighting' highlight it.

This is same behavior when you put caret on any text and press 'Ctrl + F' or 'Ctrl + H'.

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/a1eed779539de0e428c4d1f5b1e3dfad8336ece4/PowerEditor/src/NppCommands.cpp#L3161-L3167

**Comment by shriprem** [comment] 2022-05-13 17:39
Removing the `- 1` on line 3163 will fix the issue, as in:
```C++
auto textLen = _pEditView->execute(SCI_GETSELTEXT, 0, 0);
```

However, @donho will know if there are any side effects that may arise from this small change.

**Comment by shriprem** [comment] 2022-05-13 18:03
Some additional clarification may be necessary.

When no text is selected, `SCI_GETSELTEXT` will return 0 with the Scintilla upgrade. So, `textLen` will get set to -1 if `- 1` stays on line 3163. With a non-zero value, the `if (textLen) doAboutDlg = true;` will not execute and lead to the execution of the easter egg code. Within the easter egg code, line 3172 is calling `getSelectedText()` function. And, within this function, the call on`expandWordSelection()` is what is actually causing the automatic word selections reported in this issue.

An alternative way of fixing this issue would be to change line 3164 to: `if (textLen < 1)` (with or without removing the `-1` on the preceding line).

**Comment by Yaron10** [comment] 2022-05-14 12:24
See https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11671.

**Comment by mastervbguru** [comment] 2022-05-17 10:20
I downloaded version 8.4.1, but the problem still persists.  To reproduce:

Open the 8.4.1 Change.log file.  Press CTRL + HOME to move the cursor to the beginning of the file.  Nothing is highlighted.
Click on HELP + ABOUT.  The word "Notepad" will be highlighted throughout the document.

**Closed** 2022-05-17 15:09 UTC
