### ISSUE TITLE
arrows text cursor in Arabic RTL MODE is reversed 

### ISSUE THREAD

**Issue by q8fft** [notepad-plus-plus/notepad-plus-plus#7678] opened 2019-11-30 09:27 UTC
Write in Arabic and move the left and right arrows reversed, after switch to RTL.

The text cursor is supposed to go in the right direction but is reversed when i using RTL MODE.

if i press right arrow he gone to left, vice versa.

as you see here i press left arrow but he gone right !?
https://imgbbb.com/images/2019/11/30/arrr.gif

**Comment by Stamimail** [comment] 2020-01-26 13:04
Come to report about the same problem.

Also for RTL mode :
You should enable for RTL OS, the shortkeys:
RightCrtl+RightShift ==  Text Direction RTL	Ctrl+Alt+R
LeftCtrl+LeftShift == Text Direction LTR	Ctrl+Alt+L

The best experience for testing, is to install RTL OS in VM, and trying Notepad and Word.

**Comment by xuvatilavv** [comment] 2020-12-26 12:05
I noticed this too, after looking at the issue history here this is a problem with Scintilla and not directly fixable in Notepad++. See #5605, #2749, and others

Currently open duplicates and related issues: #8553 #8051 #7834

Posting this here since this is the oldest open issue I see for it. I can't close these but I hope it helps.

**Comment by Bip901** [comment] 2021-04-06 12:13
Apparently my issue, #9730 is a duplicate of this.
In my report I noted that this bug occurs in all languages, not just Arabic and even not just RTL languages.

**Closed** 2021-12-29 17:37 UTC
