### ISSUE TITLE
Unicode characters corruption 

### ISSUE THREAD

**Issue by AgostinoSturaro** [notepad-plus-plus/notepad-plus-plus#813] opened 2015-08-27 10:46 UTC
Here are two problems afflicting some Unicode characters in a Notepad++ document set to UTF-8 encoding (with or without BOM).
Tested on Notepad++ 6.8.2, with all default Style settings (Courier New font), on Windows 7 x64 SP1.
Also found in Notepad++ 6.3.3 and 6.4.1.

_Corruption when copy-pasting Unicode characters_
Some Unicode characters get corrupted when pasted from an external UTF-8 document to a Notepad++ UTF-8 document (with or without BOM).

_How to reproduce_
Open a new Notepad++ file, set the encoding to UTF-8 and paste the symbol from a website using UTF-8. I suggest the "natural numbers" character ℕ from [Unicode character table](http://unicode-table.com/en/2115/) or from [Wikipedia](http://en.wikipedia.org/wiki/Natural_number).
The problem appears most often when the character is pasted on a new empty line.

_Corruption when editing a line containing Unicode characters_
Some Unicode characters can be copy-pasted in Notepad++, but they turn to blocks when entering a newline between them.

_How to reproduce_
Open a new Notepad++ file, set the encoding to UTF-8 and paste these symbols ([Double Arrow Unicode](http://unicode-table.com/en/search/?q=Double+Arrow) characters) on the first empty line
⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙
Position the cursor before the last two characters and enter a newline, like this
⇐⇑⇒⇓⇔⇕⇖⇗
⇘⇙
The last two characters should turn into blocks.
![notepad unicode character corruptuion](https://cloud.githubusercontent.com/assets/1441393/9518640/924a17f2-4cb8-11e5-8613-74012a88d8dd.png)

**Comment by h-h-h-h** [comment] 2015-08-27 13:05
There are the same or few problems with different fonts defining the characters. For instance, I could not reproduce the problems with Arial Unicode MS. The font Source Code Pro doesn't define the N character told of, but also has the problem with a line break in the line of arrows. In the text `⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙` the problem occurs starting from the 6th character (half of the line) when inserting a line break.

**Comment by AgostinoSturaro** [comment] 2015-08-27 14:24
Thanks.
I can confirm that using the font Arial Unicode MS the arrows work.
However, with that font the ℕ symbol appears rotated.
![2015-08-27 16_22_49-_new 1 - notepad](https://cloud.githubusercontent.com/assets/1441393/9522976/f56e4168-4cd7-11e5-81ff-580b18753fe8.png)

Did you try with Courier New too? It was the default font before 6.8, then it was briefly replaced by Source Code Pro, and it's the default again in 6.8.2?

**Comment by h-h-h-h** [comment] 2015-08-27 18:50
- Arial Unicode MS doesn't rotate ℕ here (the character is defined by the font)
- Courier New doesn't define any of the mentioned characters here, although Notepad++ displays the arrows when being on one line. There's also the problem of not displaying the first two characters of the arrows when putting a line break after them. ℕ is not displayed in general.

So it is related to taking glyphs from another font ([reference article](https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx)). Windows' Notepad does this, too.

**Comment by girtsl** [comment] 2017-08-02 05:51
I just got bit by this. FWIW, it seems that the rightwards double arrow is somehow affecting things - as long as you have it on the line, the characters are displayed.
![2017-08-02_08-48-44](https://user-images.githubusercontent.com/6348534/28859391-9cf9db46-775f-11e7-963a-26bdf7d23037.png)

**Comment by brewmanz** [comment] 2019-03-26 19:10
Testing with ⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙ , UTF-8 Encoding and various fonts (via Settings - Style - Theme Default - Language Global - Style Default Style - Font Style - Font name ...
With Lucida Console, splitting in middle (5 - 5) then the second line becomes 5 blocks
Splitting 4 - 6 then both lines ok
Splitting 2 - 8 then FIRST line becomes 2 blocks
I can split it anywhere, when using MS Gothic, and it displays properly before and after line split.
===
Notepad++ v7.5.1   (64-bit)
Build time : Aug 29 2017 - 02:38:44
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by h-h-h-h** [comment] 2019-03-26 22:06
Did you try to create a separator line with dashes? It makes for a heading with a big font instead, if you don't surround it with empty lines.

**Comment by AgostinoSturaro** [comment] 2019-03-26 22:12
> 
> # Testing with ⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙ , UTF-8 Encoding and various fonts (via Settings - Style - Theme Default - Language Global - Style Default Style - Font Style - Font name ...
> With Lucida Console, splitting in middle (5 - 5) then the second line becomes 5 blocks
> Splitting 4 - 6 then both lines ok
> Splitting 2 - 8 then FIRST line becomes 2 blocks
> I can split it anywhere, when using MS Gothic, and it displays properly before and after line split.
> (Sorry about huge font - not sure why)
> 
> Notepad++ v7.5.1 (64-bit)
> Build time : Aug 29 2017 - 02:38:44
> Path : C:\Program Files\Notepad++\notepad++.exe
> Admin mode : OFF
> Local Conf mode : OFF
> OS : Windows 10 (64-bit)
> Plugins : mimeTools.dll NppConverter.dll

**Comment by AgostinoSturaro** [comment] 2019-03-26 22:13
Sorry for the close, I hit the wrong button.
I can still reproduce this, on Windows 10.
@brewmanz Your font is huge because your text starts with a `#`

**Comment by MetaChuh** [comment] 2019-04-09 23:34
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:34 UTC
