### ISSUE TITLE
Visual block + insert key

### ISSUE THREAD

**Issue by tciops** [notepad-plus-plus/notepad-plus-plus#3966] opened 2017-12-06 20:17 UTC
### Description of the Issue
N++ crashes when visual block is marked and insert key pressed

### Steps to Reproduce the Issue
1. Mark visual block with Alt+Click and drag
2. Press insert key
3. N++ crashes

### Expected Behavior
Certainly not a crash :)

### Debug Information
v 7.5.1 32b

**Comment by dail8859** [comment] 2017-12-06 20:21
Please post your debug info as it might be a plugin causing the crash (or also disable your plugins). You can also try the latest [v7.5.3](https://notepad-plus-plus.org/news/notepad-7.5.3-released.html).

I can't reproduce it with:

```
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Users\username\Desktop\npp.7.5.3.bin.minimalist\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none
```

**Comment by tciops** [comment] 2017-12-06 21:19
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll XMLTools.dll 

You were right, disabling plugins hepled

**Comment by dail8859** [comment] 2017-12-06 23:00
By "helped" I'll assume you mean it doesn't happen any more so I'll close this.

**Closed by dail8859** 2017-12-06 23:01 UTC
