### ISSUE TITLE
64 bit version is not registering itself in "Open with" menu

### ISSUE THREAD

**Issue by deadrow** [notepad-plus-plus/notepad-plus-plus#2454] opened 2016-10-20 17:55 UTC
### Description of the Issue

Notepad++ 64-bit version's icon is not showing when using "Open with" context menu.
### Steps to Reproduce the Issue

1. Right click on any file and go to Open With
2. Choose default program -> This opens new dialog with suggested applications
3. Browse for Notepad++ and select notepad++.exe.
4. The dialog still doesn't show notepad++ and you can't open a file with notepad++.
### Expected Behaviour

The complete process should show notepad++ icon and users should be able to open any file with app.
### Actual Behaviour

Not able to open any file with notepad++

**Comment by sympo** [comment] 2016-10-24 11:27
I'm experiencing the same issue on Windows 7 x64. neither manually adding the program to the open with menu nor changing the default programs works. Notepad++ x64 simply does not show up.

**Comment by LeadManPL** [comment] 2016-10-25 12:57
There is a workaround for this:
1. Start NPP as admin
2. Go to Settings>Preferences>File Association
3. Add your file extension to "Registered extensions"
4. Click "Close" button
5. Exit NPP

After that NPP should be visible, when you right-click on your file, in a menu itself or under:
"Open with" > "Choose default program"

**Comment by MathewCNichols** [comment] 2017-12-18 17:20
I had this problem on Windows 7 x64 after uninstalling the 32 bit Notepad++ and installing the 64 bit version. Some files (.conf) could not be set to open with Notepad++ as default. Notepad++ didn't even show up in the "Recommended Programs."

The registry values had to be updated. I actually did the inverse of Gusgus01's referenced issue above since I have x64 version installed:

Pop open regedit > search for ""C:\Program Files (x86)\Notepad++\notepad++.exe" and replace with the updated x64 directory "C:\Program Files\Notepad++\notepad++.exe."

Now the 64bit Notepad++ programs appears in "Open With" > "Choose a default program" > "Recommended Programs."

Hope it helps someone!

**Comment by ash3taunk** [comment] 2017-12-19 08:56
thanks, @MathewCNichols. It worked for me.

**Comment by abhiganta** [comment] 2017-12-21 09:02
I faced the same issue. I previously used the portable version which was in my D:\ drive and it worked fine. But when I installed the installer version, which by default installed in program files and then it did not show up in suggestions. 
After googling modified the (Default) registry key in below path with correct installed location:
HKEY_CURRENT_USER/software/classes/applications/notepad++.exe/shell/open/command

Hope this change will work for you.

**Comment by devm2r2** [comment] 2018-01-14 18:20
I had this issue with a fresh installation of  x64 Windows Server 2008 R2
This should apply to fresh installations of Windows 7 or older (x64) too

I solved by installing (Microsoft Visual C++ 2008 Redistributable Package) **(very important)**
Link = https://www.microsoft.com/en-us/download/details.aspx?id=15336

Then open CMD and type this: 
`cd C:\program files\notepad++`
`regsvr32 NppShell_06.dll`

if NppShell_06.dll is not found, check for NppShell_05 or _07 or whatever version you have in there.
Then, tadaa, right click on files should instantly work, no reboot required !

![screen](https://user-images.githubusercontent.com/31595078/34919174-63d0535e-f95f-11e7-8069-68d61d3ac788.png)

**Comment by mikebk** [comment] 2018-01-19 16:23
I also was unable to have NotePad++ show in the list of applications that could handle the format. I did a bit of Googling and tried various possible solutions.

I found abhiganta's post and looked in the registry. I could see that the path in the open command was wrong - I didn't even have an executable in the "C:\Program Files (x86)\Notepad++" folder.

I made abhiganta's and presto, NotePad++ showed up in the Other Programs list!

There are a number of issues with having NotePad++ set as the default program for a file type and I had a couple. I had earlier needed to add the extension to the File Association configuration in NotePad++'s preferences.

**Comment by samirsoman** [comment] 2018-03-29 15:25
This helps ! thank you !

**Comment by gunkaragoz** [comment] 2018-05-13 21:13
I am unable to open npp window if I try opening npp without administrator rights, but once I run npp as administrator, i am able to double-click on files,

After googling a bit, this resolved my problem only for once:
- Open %appdata%\Notepad++
- Rename config.xml to sth else e.g. config1.xml
- Open npp > ok it works
- Close npp, open again - same problem occurs since new config.xml is generated.  
- Whenever I delete config.xml i am able to open npp.

There is something wrong with this config file (maybe with a plugin), but couldn't find yet.
[config.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1998936/config.txt)

**Comment by tom23rd** [comment] 2018-11-29 09:48
I was just having the same issue, until i unset "run as administrator" in the compatability tab.  i guess that portion of the registry does not launch an elevated shell context.

**Comment by PremRanjanDev** [comment] 2018-12-14 04:03
I was having the same issue and found out it is because the '++' sign in name of installation folder and executable so I replaced '++' with 'pp'.
Follow these steps.
### 1. Rename Notepad++
1. Rename the installation folder Notepad++ to **Notepadpp**
2. Go inside the folder and rename notepas++.exe to **notepadpp.exe**

### 2. Make default program
1. Right click on file -> open with -> choose default program...
2. Click browse -> select **notepadpp.exe** -> (**check** Always use option if haven't already) and click OK
This worked for Win 7 x64 and Notepad++ x64.

Thanks!

**Comment by ScamCast** [comment] 2020-03-01 16:29
Just had this same issue after upgrading to the latest version: 7.8.4 

**Renamed:** "C:\Program Files\Notepad++\notepad++.exe"
**To:** "C:\Program Files\Notepad++\notepadpp.exe"

Then replaced all the paths in the registry with the new notepadpp.exe path and it fixed it.

**Comment by donho** [comment] 2020-04-04 15:16
It seems it's an issue Windows 7 only, I cannot reproduce in Windows 8 or Windows 10.
Since Microsoft ended mainstream support for Windows 7 in January 2015, this issue won't be fixed.

**Closed by donho** 2020-04-04 15:16 UTC
Labels: enhancement

**Comment by donho** [comment] 2020-04-04 15:28
Keep a track on Notepad++ Community:
https://community.notepad-plus-plus.org/topic/19158/faq-desk-make-notepad-x64-open-with-menu-work-in-win7

**Comment by dbocruzin** [comment] 2022-08-15 14:14
One work around is to 'right click on a .sql file > Open With > Choose another app > More Apps > Look for another app on this PC > select notepad++.exe > Check "Always use this app for .SQL files" > OK'

I tried doing this by just going to the "default apps by file type" section within windows before trying the above but Notepad++ wasn't an option. It shows up now for the .sql file extension but only for that file extension. I went to .txt just to see if I could default it here for other extensions and its still not an option so would have to do the above for any other defaults.
