### ISSUE TITLE
AppPosition config.xml AppPosition tag cloud sync issues

### ISSUE THREAD

**Issue by mcduck76** [notepad-plus-plus/notepad-plus-plus#2289] opened 2016-09-16 12:56 UTC
### Description of the Issue

Syncing the config.xml file over a cloud service potentially leads to serious issues with the AppPosition tag. For example, saving the config.xml file from a PC with a high resolution screen and then loading it from a PC with a regular resolution screen produces a huge main window (or plain renders the main window off screen).
The same issue occurs with the positioning if the config file is saved and then loaded from setups with a different number of attached monitors.
### Fix proposal no 1
1. When saving the AppPosition attributes, account for the screen dpi (using the existing DPIManager class to scaleX/Y).
2. When loading the AppPosition attributes perform the opposite conversion.
3. When loading the AppPosition attributes, check that the window position being loaded is visible in the current setup (if not, use default size/position).
### Fix proposal no 2

When cloud syncing is enabled, do not persist the AppPosition in config.xml.

**Comment by u01jmg3** [comment] 2017-02-14 13:34
Duplicate of #1121

**Comment by MetaChuh** [comment] 2019-05-01 21:51
many thanks for your cloud sync ideas.

please do the following, if you have 2 or more machines, where you would like to backup your settings e.g. to dropbox or onedrive, without syncing the recent file list or windows position to the other machine:

(note: we do not have any information about your setup, so we can only provide an example, using onedrive, one notebook and one stationary pc)

* open your OneDrive folder.
* create one folder called e.g. Notepad++ PC and one folder called e.g. Notepad++ NoteBook.
* go to both machines, open up notepad++ and go to settings > preferences > cloud.
* on the stationary pc set your cloud location path to Notepad++ PC.
* on the notebook set your cloud location path to Notepad++ NoteBook.
* close notepad++ on both machines for the changes to take effect.

after that, both notepad++ installs will not use the recent file list, or the last window position of the respective other install, but you will still have your settings backed up and reachable as files for comparison at both machines.

there is currently no need to change the behaviour of the cloud feature, as it works as designed.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 21:51 UTC
