### ISSUE TITLE
File Save Dialog does not change directories

### ISSUE THREAD

**Issue by TomB2** [notepad-plus-plus/notepad-plus-plus#4698] opened 2018-07-25 12:14 UTC
### Description of the Issue
FileSaveAsDialog does no longer change directory.

### Steps to Reproduce the Issue
1. Open File SaveAs Dialog
2. Enter path without file name and without trailing back slash in file name text box
3. Press Enter

Reproducable on Windows 7 and 10. It is not Microsoft related!

### Expected Behavior
Dialog should change to that directory and populate file name text box with
original proposed value.
This was definitly working with version 7.4.1

### Actual Behavior
Dialog complains that the file (directory) is already present and if it should be replaced.
If the path of Step 2) has a trailing back slash the dialog changes to that directory but does
no longer populate text box with original value

**Comment by sasumner** [comment] 2018-07-26 11:49
Have you tried this setting (see below)?  It may change your mind about your issue, or perhaps make you modify it to consider the different possible setups users may employ.

I'm unclear about your references to "original proposed value" and "original value".  How does this reconcile with your step 2 where you say "without file name...".  (I'm thinking that "original value" would be something like `*.txt` but since you said what you said in step 2 I am confused.)

![image](https://user-images.githubusercontent.com/30118311/43260761-5ec3022c-90a8-11e8-90ac-213aa621e5d2.png)

**Comment by TomB2** [comment] 2018-07-26 15:31
No, I did not. Checking that box resolves the issue.

Thanks for the tip.

 

Since it worked in earlier versions I think it should be enabled as default to maintain compatibility.

 

 

Gesendet: Donnerstag, 26. Juli 2018 um 13:49 Uhr
Von: sasumner <notifications@github.com>
An: notepad-plus-plus/notepad-plus-plus <notepad-plus-plus@noreply.github.com>
Cc: TomB2 <Tom.Becker@gmx.org>, Author <author@noreply.github.com>
Betreff: Re: [notepad-plus-plus/notepad-plus-plus] File Save Dialog does not change directories (#4698)


Have you tried this setting (see below)? It may change your mind about your issue, or perhaps make you modify it to consider the different possible setups users may employ.

I'm unclear about your references to "original proposed value" and "original value". How does this reconcile with your step 2 where you say "without file name...". (I'm thinking that "original value" would be something like *.txt but since you said what you said in step 2 I am confused.)

**Comment by mere-human** [comment] 2021-02-22 21:26
In version 7.9.3 file dialogs have been updated so this problem isn't reproducible anymore.
@sasumner Could you, please, close this issue?

**Closed** 2021-02-22 21:58 UTC
