### ISSUE TITLE
Only open one prompt for modified document

### ISSUE THREAD

**Issue by RandomRhythm** [notepad-plus-plus/notepad-plus-plus#3349] opened 2017-06-04 01:53 UTC
### Description of the Issue

If an open document is modified multiple times a new message box is opened each time. I had an automated process editing a file I had open and came back to 10 prompts about reloading the modified file.
### Steps to Reproduce the Issue

1. open an empty file
2. modify the open file in Windows notepad
3. put focus back to notepad++
4. repeat steps 1-3

### Expected Behavior

No need to open more than one prompt about reloading the file. Open one prompt and suppress any further prompts about reloading the file. 

### Actual Behavior

Multiple reload prompts layer leaving you to deal with each one to get back to editing your document.

### Debug Information

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

![reload](https://cloud.githubusercontent.com/assets/18624368/26758252/0bbc79d8-4896-11e7-9393-34cbf6a341ff.png)

**Comment by eike-r** [comment] 2017-08-17 07:22
I totally agree, for me all the relaod-clicking it a major drawback of Notepad++.

**Comment by 42degrees** [comment] 2018-10-12 20:02
This is essentially a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087) with the difference that the solution proposed there is to a) only ask the person to reload the file if the tab is chosen for the changed file, and b) that the reload is put into a banner on the file rather than a MessageBox yes/no dialog.

**Closed** 2019-03-17 12:05 UTC
