### ISSUE TITLE
Column Editor insert text not only within selected lines

### ISSUE THREAD

**Issue by AshPriya** [notepad-plus-plus/notepad-plus-plus#2206] opened 2016-08-25 10:20 UTC
**Description of the Issue**

No matter the document has text selection or not, Column Editor always insert text from current line up to the end of the document.

A more intuitive and friendly behavior is to insert only for the selected lines when there is a selection.

**Steps to Reproduce the Issue**

Open a normal text document of over 10 or more lines.
Forward select the lines from the some rows
Menu -> Edit -> Column Editor..., then input

**Debug Information**

Notepad++ version 6.9.2 on Windows 8.1

**Error Result photo**
when we use column editor -> text to insert or number to insert.. all columns added text or number.change below all rows.
![error_pic](https://cloud.githubusercontent.com/assets/10189621/17965687/73f8c568-6adb-11e6-846f-dad498b06702.png)

**Comment by dail8859** [comment] 2016-08-25 12:14
Duplicate of #2139 which I'm sure you are aware since you copy/pasted text from there.

**Closed by dail8859** 2016-08-25 12:14 UTC
Labels: duplicate
