### ISSUE TITLE
Compare Plugin

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#1375] opened 2016-01-16 00:52 UTC
Hello,

Jean Sebastien Leroy, [Compare Plugin](http://sourceforge.net/projects/npp-compare/?source=recommended)'s creator, abandoned the project a long time ago.
UFO has fixed some bugs and added many [improvements](https://bitbucket.org/uph0/compare/downloads). 
Unfortunately, he has probably quit as well. We miss you UFO. :)

UFO's v1.5.6.7 has not been completed.
In some cases this version throws an exception and crashes.
(Uncheck "Ignore Spacing" and compare the files in Test.zip).

Changing 
~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define VARRAY_INIT_SIZE 16
~~~~~~~~~~~~~~~~~~~~~~~~~~~
 to
~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #define VARRAY_INIT_SIZE 5
~~~~~~~~~~~~~~~~~~~~~~~~~~~
 (in varray.h) seems to solve the problem.

I've also made the following changes:
- Remove the Progress Bar introduced in v1.5.6.7.
- Some minor improvements in comparing with Wrap mode on.
- Fix the shortcuts for Next, Prev, etc..
- An option to close the compared files if they match.

***

I've made a version with new images for the Compare margin.

![better images](http://s28.postimg.org/dtj6zbab1/New_Images.png)

The background is set to my "Line Number Margin" background color: RGB 228 228 228.
If anyone knows how to change the XPM images background to transparent, I'd appreciate it.
(The relevant files are: icon_add_16.h, icon_moved_16.h, icon_sub_16.h and icon_warning_16.h).
** The menu items and toolbar buttons are never disabled in this version.

***
I'm sure many users would appreciate an experienced developer willing to continue the work on this useful plugin. 
***

Regards.

[ComparePlugin NewImages.v1.5.6.7.bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/92712/ComparePlugin.NewImages.v1.5.6.7.bin.zip)
[ComparePlugin.v1.5.6.7.bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/92713/ComparePlugin.v1.5.6.7.bin.zip)
[Test.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/92711/Test.zip)

**Comment by Yaron10** [comment] 2016-01-17 00:36
See guy038's [comments](https://notepad-plus-plus.org/community/topic/11116/compare-plugin).

[ComparePlugin.v1.5.6.7 NewImages NoDefault.bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/93150/ComparePlugin.v1.5.6.7.NewImages.NoDefault.bin.zip)
[ComparePlugin.v1.5.6.7 OldImages NoDefault.bin.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/93149/ComparePlugin.v1.5.6.7.OldImages.NoDefault.bin.zip)

**Comment by Ede123** [comment] 2016-01-17 02:30
Please note that while @jsleroy might not actively contribute code to the compare plugin anymore he's very much "alive" and has recently merged @ufo's changes into his GitHub repository of the Compare plugin located at [jsleroy/compare-plugin](https://github.com/jsleroy/compare-plugin).

Also he expressed his interest at joining efforts and centralize all development at this (official) repository when I asked him about the future of the Compare plugin (see jsleroy/compare-plugin#2). There's also some more input on what could be done for the Compare plugin in the future (we didn't proceed any further yet because ufo never answered, but the idea is not yet shelved)

So in any case I'd suggest you to submit a merge request with your changes, so they won't be lost.
Also in the near future a current version of the plugin (preferably built from the official source) should be made available via plugin manager since it currently ships an outdated and buggy version.
Maybe we could even get @pnedev to finish the work on the progress bar which would be a very welcome improvement for large files.

**Comment by Yaron10** [comment] 2016-01-17 03:06
Hi Ede123,

That's great news. Thank you so much.

I have to retire now.
I'll write tomorrow in more detail.

Best regards.

**Comment by Yaron10** [comment] 2016-01-17 20:36
Hello Ede123,

The current state of the Compare Plugin is indeed a mess and has to change.
Thanks again for referring me to jsleroy's repo. 

I'm not an experienced developer.
I first installed VS 2013 about a year ago in order to add an option to close the compared files.

Apart from that, I concentrated on slightly improving the Scroll Sync and Wrap management.
It works well, but the structure of the code is not very elegant. It was written as a proposed draft for UFO.
I'd highly appreciate it if you could review it.
(Compare the original compare.cpp and my modified file; I've added "// Yaron" to my changes and some (alas, too) short comments).

More important is finding the cause of the crash when comparing the files in Test.zip and testing my proposed fix.

I'll open some new issues (for the above mentioned points and more) in jsleroy's repo, and we could continue our discussion there.

I'll also ask jsleroy to have a look and guy038 to contribute.

Some references to related discussions on SourceForge:
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/1ed3f576/
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/f035f7b6/
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/30c87332/   

Best regards.  

[Compare Original and Modified.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/93585/Compare.Original.and.Modified.zip)

**Comment by Ede123** [comment] 2016-01-17 21:26
@Yaron10 I Don't consider myself very experienced either, so I can't really comment on code quality, but I'd certainly be happy to help with testing and some of the points listed in the issue I linked as necessary and as time permits!

**Comment by Yaron10** [comment] 2016-01-17 21:39
OK. :)
Any help would be appreciated.

Could you try and ask Pavel to join in?

I'll open some more issues in the coming days (it seems to be more difficult than I thought ; apart from the crash issue I discovered recently, I haven't dealt with the other issues during the last year).
Let's hope jsleroy does find some free time to help.

Regards.

**Comment by pnedev** [comment] 2016-01-18 09:19
Hi guys,

I also don't have that much experience in Windows development and I haven't looked at the Compare plugin code so far. I simply provided Ufo with a generic progress bar class.

Having said that, I'm willing to help, it would be a pleasure
but I'm not aware of the Compare plugin problems at the moment.

Can you tell me what are you trying to accomplish?

Regards,
Pavel

**Comment by Yaron10** [comment] 2016-01-18 21:53
Hi Pavel,

Great to have you aboard. Thank you so much.

The ultimate goal, as Ede123 has mentioned, is have an updated stable version provided to users via the Plugin Manager.

I've opened some [issues](https://github.com/jsleroy/compare-plugin/issues). Here is my triage (I trust your judgment):
1) [v1.5.6.7: Occasional crashes and a proposed fix](https://github.com/jsleroy/compare-plugin/issues/5).
2) [Compare results are cleared when a THIRD file is closed](https://github.com/jsleroy/compare-plugin/issues/7).
3) [Compare and NPP Recent Files list](https://github.com/jsleroy/compare-plugin/issues/6).
4) ["nul" is added when comparing a cloned empty file](https://github.com/jsleroy/compare-plugin/issues/8).
5) [[Review Request] Some modifications in compare.cpp](https://github.com/jsleroy/compare-plugin/issues/10).
6) [[Suggestion] A new extra Status Bar for Compare](https://github.com/jsleroy/compare-plugin/issues/9).

We would appreciate any help. :)

Best regards.

**Comment by sanastasiou** [comment] 2016-01-18 23:31
Would it make sense to move this discussion to Compare Plugin Git repo? :) As far it seems it has nothing to do with NPP directly.

**Comment by pnedev** [comment] 2016-01-20 16:11
Hi again,

And Thanks for the kind welcome :)
I'll take a closer look when I have more time and write you back.

BR,
Pavel

-----Original Message-----

**Comment by Yaron10** [comment] 2016-01-20 19:50
Hello Pavel,

Sure. At your leisure.
Thanks again and best of luck. :)

Regards.

**Comment by jsleroy** [comment] 2016-01-21 08:09
Hi Yaron,

Would you mind forking the Compare plugin github repository, and then send
a merge request ?

The repository is located here: https://github.com/jsleroy/compare-plugin

Merge request process on github is explained here:
https://help.github.com/articles/using-pull-requests/

Best regards,
JS

**Comment by jsleroy** [comment] 2016-01-21 08:10
Hi Stefanos,

Good point here for moving discussion to Compare git repository.

I hope to find some time to entirely move Compare to github.

Best regards,
Jean-Sebastien

**Comment by Yaron10** [comment] 2016-01-21 20:42
Hello,

I owe UFO an apology.
What I thought was an improvement in comparing with Wrap mode, is actually a regression (back to v1.5.6.3 behavior) in many cases.
(Compare the files in [Test2.zip](https://github.com/jsleroy/compare-plugin/files/99571/Test2.zip)).

We shouldn't use NPP vertical scroll sync but rather UFO's "case SCN_UPDATEUI:".
***
NPP enabling and disabling the Sync Scroll commands is somewhat inconsistent.
Therefore my changes relating to restoring the Sync Scroll state are too complex and not worth it.
Back to UFO's Restore Sync Scroll.

See guy038's [comment](http://sourceforge.net/p/notepad-plus/discussion/482781/thread/1ed3f576/#c9a2) and UFO's [reply](http://sourceforge.net/p/notepad-plus/discussion/482781/thread/1ed3f576/#72ef).

Best regards.

[ComparePlugin.v1.5.6.7.NewImages.NoDefault.bin.zip](https://github.com/jsleroy/compare-plugin/files/99845/ComparePlugin.v1.5.6.7.NewImages.NoDefault.bin.zip)
[ComparePlugin.v1.5.6.7.OldImages.NoDefault.bin.zip](https://github.com/jsleroy/compare-plugin/files/99844/ComparePlugin.v1.5.6.7.OldImages.NoDefault.bin.zip)
***
Hopefully, the last post here. :)

**Comment by shadinaif** [comment] 2016-02-24 09:22
Hello,

It is a great tool. But I am facing a problem with files containing more than 16384 lines (2^14). The screen gets black, I have to press Alt+F4 to close notepad++ to retrieve the desktop

Do you have a solution without splitting the file into many?

Best Regards,

**Comment by Tmp341** [comment] 2016-02-24 10:42
@shadinaif Your problem might be about memory. How much ram your computer using? I don't know if it's Compare has a bug larger files like 2^14. But i know large files consumes more memory in general.

**Comment by shadinaif** [comment] 2016-02-24 12:12
Thank you @Tmp341 ,

I don't have a RAM problem. The issue is in the number of lines; it is not even about the size of the file.

Unfortunately; it is some kind of a limitation in the plugin.

Best Regards,

**Comment by pnedev** [comment] 2016-02-24 15:09
Hi, @shadinaif ,

Please post any issues to the Compare Plugin project repository:
https://github.com/jsleroy/compare-plugin

BR,
Pavel

**Comment by shadinaif** [comment] 2016-02-24 17:15
Thank you @pnedev

**Comment by dail8859** [comment] 2016-07-21 23:36
Since this discussion has moved elsewhere I'll go ahead and close.

**Closed by dail8859** 2016-07-21 23:36 UTC
Labels: plugin
