### ISSUE TITLE
Auto-insert not working correctly (7.x and 6.9.x)

### ISSUE THREAD

**Issue by devnull69** [notepad-plus-plus/notepad-plus-plus#2634] opened 2016-12-01 08:20 UTC
### Description of the Issue
Auto-insert for me (as a developer) is a very important feature. But since 6.9.x it isn't working correctly any more. I still have version 6.8 of NPP installed on a different PC, where it is still working flawlessly.

### Steps to Reproduce the Issue
1. Set Auto-Completion/Auto-Insert in Preferences to include () [] {} "" and '' 
2. Type the following app.listen(
3. The closing ) is added correctly
4. Continue typing 8080, (
5. The closing ) is NOT added. There is still only one closing ) from step 3
6. Continue typing )
7. The closing ) of step 3 is overwritten by the closing ) of step 6. So there is still only one closing ) present
8. Continue typing )
9. Go one step to the left and insert => {
10. The closing } is NOT added

### Expected Behavior
2. Type app.listen(
3. The closing ) is added correctly
4. Continue typing 8080, (
5. The closing ) should be added
8. Continue typing ) => {
10. The closing } should be added

Is it just me? It's really annoying ... I've even been thinking about switching editor after several years of happily using NPP

**Comment by simon33-2** [comment] 2016-12-14 02:47
Adding to this the auto insert should be able to do more than inserting a single character. For languages with block closing delimiters, these should be able to be inserted automatically. EditPlus can do this.

In my main language "then" must always follow "if". Why would you want to type it? Similarly with the "endif;" and indent of the intervening line.

**Comment by simon33-2** [comment] 2016-12-14 02:48
Note also bash which requires "then" and "fi" after an "if" and "do" and "done" after a while, until or for.

**Comment by eight04** [comment] 2017-02-24 02:10
I found that there is a plugin called "XBrackets Lite" working as intended.

**Comment by MetaChuh** [comment] 2019-05-01 19:57
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 19:57 UTC
