### ISSUE TITLE
[BUG] 8.7.1 introduced a network file modification detection bug.

### ISSUE THREAD

**Issue by cmanley** [notepad-plus-plus/notepad-plus-plus#15819] opened 2024-11-18 15:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

This release as introduced a new bug that didn't exist in v8.7.0 and prior:

I open/edit files on network drives (rclone SFTP mount), and now I'm frequently getting popup messages that the underlying file has been modified with the question if I want to reload it. I choose no, and then it says the file has gone missing with the question if I want to keep it open in my editor. I choose yes, and then save it. This process keeps on repeating. It's so annoying. I suspect that it was introduced by one of the network bug fixes listed in the release notes for 8.7.1

### Steps To Reproduce

1.  Install 8.7.1
2.  Install and configure a rclone SFTP mount in Windows
3.  Open and save a file on that mount.
4. Wait for the annoying popup dialog.

### Current Behavior

Much annoyance.

### Expected Behavior

No annoyance as in 8.7.0 and prior.

### Debug Information

```shell
I downgraded in order to work so I don't have this anymore.
```

**Comment by xomx** [comment] 2024-11-18 19:43
@cmanley 

Please add to your 1st post the requested Notepad++ `menu > ? > Debug Info...`.

> I open/edit files on network drives (rclone SFTP mount), and now I'm frequently getting popup messages that the underlying file has been modified with the question if I want to reload it. I choose no, and then it says the file has gone missing with the question if I want to keep it open in my editor.

From your description it looks like the N++ file checking code gets info from the OS that the file is not present anymore. I am wondering if it cannot be some type of a SFTP connection timeout? (I know you said the v8.7.0 has not the same problem, so this is probably not so relevant here).

How is the exact sequence of your steps and at which stage you have got the 1st message?
- right after the file opening
- after some specific time while still working with the opened network file in the N++
- do you need to switch to another app (or another N++ tab) and back to N++ (or to the previously opened problematic network file tab in N++) before the 1st message


> 2\. Install and configure a rclone SFTP mount in Windows

Can you replicate your network saving problem without this specific rclone network storage usage (I mean mount/reach your network storage in another way to exclude the rclone influence to narrow down the possibilities...)?
If not, to be able to debug your possible bug in the N++, one 1st need to replicate your situation. I for example know nothing about rclone, is it [this](https://rclone.org/downloads/)? Then I would appreciate a simple STR how to setup this for. a DropBox or FTP account etc... Or better, is it there an accessible network place where you can replicate the problem and I can access it via your way?

And what exactly is your network storage? (if you can share that info, of course)

**Comment by cmanley** [comment] 2024-11-18 21:40
Here's the debug info from 8.7.0 (not 8.7,1 since I've downgraded):
```
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : C:\Users\secret\Downloads\script.pl
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4460
Current ANSI codepage : 1252
Plugins :
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    HTMLTag (1.4.4)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExec (0.8.8)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    NppMarkdownPanel (0.7.3)
    XMLTools (3.1.1.13)
```
The message appears some time after opening, but I haven't measured it.
Switching focus away from npp could be a trigger as that is something I often do, but I can't confirm that now.
The network storage is a Debian 12 server that only allows SSH access (no samba, nfs, or anything else).

**Comment by cmanley** [comment] 2024-11-25 08:06
I downloaded 8.7.1 portable version and measured the time until I get the message: it's about 3 minutes after saving when npp receives focus back from another window.
Debug info:
`Notepad++ v8.7.1   (64-bit)
Build time : Oct 31 2024 - 00:48:56
Path : C:\Users\secret\Downloads\npp.8.7.1.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4460
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
`

**Comment by cmanley** [comment] 2024-11-29 20:45
When I tried the portable version of npp (3 posts above), it did not have the MarkdownViewerPlusPlus plugin, yet the bug was still  present.

**Comment by xomx** [comment] 2024-11-30 20:03
@cmanley @samuelspiza 

I'd like to verify, if this issue is the same as in the # 14103. Could you please create an empty file named `nppLogNetworkDriveIssue.xml` in your Notepad++ installation folder (where your `notepad++.exe` file is...) before the next try?

That file is logging trigger for some N++ network ops. After your issue manifests again, you should obtain the `nppLogNetworkDriveIssue.log` file (in your `%APPDATA%\Notepad++\` folder or for portable N++ where the `notepad++.exe` is), with some hints for us. Then please paste content of this log-file here, it will look like:
`2024-07-29 12:07:44  ...yourfilepath...\file.txt  in checkFileState(): attributes.ftLastWriteTime (633099392/31121823) < _timeStamp (641551785/31121823)`

**Comment by xomx** [comment] 2024-11-30 20:45
@cmanley 
> Does the portable version perhaps write log files elsewhere?
No. But in your case, it could also be a sign that your problem is not the same as in the # 14103.

Did you get that N++ file modification/reload msg in your previous attempt?

**Comment by cmanley** [comment] 2024-11-30 20:47
@xomx  yes, exactly the same messages.

**Comment by xomx** [comment] 2024-11-30 22:00
@cmanley @samuelspiza 
Can you download patched test N++ binary, replace your `notepad++.exe` with it and repeat your test (with the `nppLogNetworkDriveIssue.xml` trigger present)?

x64 Release: https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/12099755495/artifacts/2257117608

**Comment by cmanley** [comment] 2024-11-30 22:09
Ok I just tried it. As I opened notepad++, I closed .gitlab-ci.yml from the previous session, then opened and editted S3.txt and pipeline.txt, then moved focus to something else for a while and then back. Then I got the popup messages for pipeline.txt.
Logging:
```
2024-11-30 23:03:30  I:\work\bla\.gitlab-ci.yml  res==-1 in updateTimeStamp(): timeStampLive (977040256/31146864) < _timeStamp (0/0)
2024-11-30 23:03:30  C:\Users\cmanley\AppData\Local\rclone\vfsMeta\imta-dev{HK82T}\home\cmanley\work\bla\.gitlab-ci.yml  res==-1 in updateTimeStamp(): timeStampLive (2970145516/31146867) < _timeStamp (0/0)
2024-11-30 23:03:41  I:\S3.txt  res==-1 in updateTimeStamp(): timeStampLive (496615680/31126670) < _timeStamp (0/0)
2024-11-30 23:03:45  I:\S3.txt  res==-1 in updateTimeStamp(): timeStampLive (3112138368/31146867) < _timeStamp (496615680/31126670)
2024-11-30 23:03:48  i:\pipeline.txt  res==-1 in updateTimeStamp(): timeStampLive (4068576000/31037750) < _timeStamp (0/0)
2024-11-30 23:03:56  i:\pipeline.txt  res==-1 in updateTimeStamp(): timeStampLive (3222138368/31146867) < _timeStamp (4068576000/31037750)
```

**Comment by xomx** [comment] 2024-11-30 22:51
@cmanley 
So this issue is something completely different than the # 14103 for sure.

Here is the human readable form of your log:
```
translated:
2024-11-30 23:03:30  I:\work\bla\.gitlab-ci.yml  res==-1 in updateTimeStamp(): timeStampLive (2024/11/30 22:38:43.000) < _timeStamp (0/0)
2024-11-30 23:03:30  C:\Users\cmanley\AppData\Local\rclone\vfsMeta\imta-dev{HK82T}\home\cmanley\work\bla\.gitlab-ci.yml  res==-1 in updateTimeStamp(): timeStampLive (2024/11/30 23:03:30.800) < _timeStamp (0/0)
2024-11-30 23:03:41  I:\S3.txt  res==-1 in updateTimeStamp(): timeStampLive (2024/08/22 14:23:38.000) < _timeStamp (0/0)
2024-11-30 23:03:45  I:\S3.txt  res==-1 in updateTimeStamp(): timeStampLive (2024/11/30 23:03:45.000) < _timeStamp (2024/08/22 14:23:38.000)
2024-11-30 23:03:48  i:\pipeline.txt  res==-1 in updateTimeStamp(): timeStampLive (2023/06/07 13:55:26.000) < _timeStamp (0/0)
2024-11-30 23:03:56  i:\pipeline.txt  res==-1 in updateTimeStamp(): timeStampLive (2024/11/30 23:03:56.000) < _timeStamp (2023/06/07 13:55:26.000)
```

I don't really understand what's going on yet but one thing from your log is outstanding - except for the write to the drive C: (2nd line), all other writes have the millisecond part of the timestamp set to zero. It probably means that your network storage does not support/report more precise time resolution.

**Comment by xomx** [comment] 2024-11-30 23:52
@cmanley
I do not understand how it is possible, that you do not have a line in the log above with `checkFileState()`. When I tried (with my patched N++ binary above) opening a txt-file in N++, switching to Win Notepad and edit that file, then switching back to N++, I've got this log when the Reload-dlg appeared (is it this the dialog you see?):

![npp-Reload-dlg-on-modification](https://github.com/user-attachments/assets/8acf3e63-90ae-49fa-9b80-eefbf3297d99)

```
2024-12-01 00:05:09  C:\TEMP\NPP\test.txt  res==-1 in updateTimeStamp(): timeStampLive (3784867603/31146862) < _timeStamp (0/0)
2024-12-01 00:05:51  C:\TEMP\NPP\test.txt  res==-1 in checkFileState(): attributes.ftLastWriteTime (1682988794/31146876) < _timeStamp (3784867603/31146862)
```

But if I leave this mystery aside, the essence of this issue will be IMO again the missing sub-second time resolution of the network storage timestamp. It is visible in the first two lines of the log that the `.gitlab-ci.yml` file is stored on the local `C:` drive with the milliseconds precision (2024/11/30 23:03:30.`800`) while its network counterpart not (2024/11/30 22:38:43.`000`).

So I think that my previous proposal https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14103#issuecomment-2280782760 could fix even this issue.

**Comment by cmanley** [comment] 2024-12-01 10:59
@xomx your previous proposal may help (ignoring the subseconds), but perhaps that could still cause issues with rounding. I think a safer approach will be to configure a configurable mtime difference tolerance window with a default value of 0. In my case I could enter a value of 1.0s or 1.5s for example.

**Comment by xomx** [comment] 2024-12-02 10:37
@samuelspiza 
Interesting, your network storage is able to report timestamps in milliseconds:

```
translated:
2024-12-01 11:27:34  \\narberal.local\archive\d05f471e-b68a-494e-abf4-d94a6df4aa24\d05f471e-b68a-494e-abf4-d94a6df4aa24.md  res==-1 in updateTimeStamp(): timeStampLive (2024/11/30 23:35:09.258) < _timeStamp (0/0)
2024-12-01 11:27:39  \\narberal.local\archive\d05f471e-b68a-494e-abf4-d94a6df4aa24\d05f471e-b68a-494e-abf4-d94a6df4aa24.md  res==-1 in updateTimeStamp(): timeStampLive (2024/12/01 11:27:37.871) < _timeStamp (2024/11/30 23:35:09.258)
2024-12-01 11:27:43  \\narberal.local\archive\d05f471e-b68a-494e-abf4-d94a6df4aa24\d05f471e-b68a-494e-abf4-d94a6df4aa24.md  res==-1 in updateTimeStamp(): timeStampLive (2024/12/01 11:27:42.145) < _timeStamp (2024/12/01 11:27:37.871)
2024-12-01 11:42:24  C:\Users\s1234567\AppData\Roaming\Notepad++\nppLogNetworkDriveIssue.log  res==-1 in updateTimeStamp(): timeStampLive (2024/12/01 11:27:43.703) < _timeStamp (0/0)
2024-12-01 11:42:24  C:\Users\s1234567\AppData\Roaming\Notepad++\nppLogNetworkDriveIssue.log  res==-1 in updateTimeStamp(): timeStampLive (2024/12/01 11:42:24.560) < _timeStamp (2024/12/01 11:27:43.703)
2024-12-01 11:42:24  C:\Users\s1234567\AppData\Roaming\Notepad++\nppLogNetworkDriveIssue.log  res==-1 in checkFileState(): attributes.ftLastWriteTime (2024/12/01 11:42:24.571) < _timeStamp (2024/12/01 11:42:24.560)
2024-12-01 11:42:24  C:\Users\s1234567\AppData\Roaming\Notepad++\nppLogNetworkDriveIssue.log  res==-1 in checkFileState(): attributes.ftLastWriteTime (2024/12/01 11:42:24.582) < _timeStamp (2024/12/01 11:42:24.571)
2024-12-01 11:42:24  C:\Users\s1234567\AppData\Roaming\Notepad++\nppLogNetworkDriveIssue.log  res==-1 in checkFileState(): attributes.ftLastWriteTime (2024/12/01 11:42:24.602) < _timeStamp (2024/12/01 11:42:24.582)
```

> the dialogs I see.

Thanks, especially for the 2nd one. I forgot that the original report mentioned that "Keep non existing file" dlg:
> getting popup messages that the underlying file has been modified with the question if I want to reload it. I choose no, `and then it says the file has gone missing with the question if I want to keep it open` in my editor. 

This changes my view on what the essence of this issue could be. Do you remember if you saved your md-file once or twice before closing it (from the log it seems it was twice)? Do you know if there could be any special delay-writing/caching setting at your network storage side?

**Comment by cmanley** [comment] 2024-12-03 19:23
@xomx The latest binary (3 Dec 1:51) seems to be working for me too. So far, so good.

**Comment by xomx** [comment] 2024-12-08 20:29
Since there have been no further reports of this problem, I assume that the solution in the latest testing binary is ok and therefore I will close the current test-PR and create its final version without the excessive debug code.

**Comment by igtbap** [comment] 2024-12-09 16:05
This bug still exists for me, I updated it to 8.7.4

**Comment by xomx** [comment] 2024-12-09 16:53
@igtbap 
In the meantime, you can try the [aforementioned](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15819#issuecomment-2513367678) testing Notepad++.exe binary and see if it solves your problem.

**Comment by igtbap** [comment] 2024-12-10 00:59
Thanks!

**Comment by xomx** [comment] 2024-12-11 08:43
@igtbap 
If I understand it right from your description, it is not the same issue as this one.
If so, please create a separate new issue, put there your description with details, steps to reproduce and N++ menu > ? > Debug Info.

**Closed** 2024-12-19 04:21 UTC

**Comment by marklakata** [comment] 2025-01-29 19:13
I have this problem with v8.7.5 (64-bit).

My file is on a SMB share.  I get the same phenotype: first Notepad++ says that the file has been modified outside of the editor (I click no) then it says would I like to keep the file (I click yes) then immediately save it with Ctrl-S.

The only program that is using my text file is Notepad++.

Yesterday, the pop-up happened unexpectedly while I was typing and I think I hit "y" or "Enter" and it threw away all the changes I made since I last saved!

**Comment by xomx** [comment] 2025-01-30 08:52
@marklakata 

> I have been using the patched 8.7.3 binary and have not have this error for the last 4 hours

That's odd because my fix from that patched v8.7.3 (I assume that you dl it from [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15819#issuecomment-2513367678) (?)) has been fully incorporated to the v8.7.5+.

The only thing that I think of now is that the subsequent modifications affected something badly, namely the commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cb1172e2a4581732a82fdc9ec35aac0fa9a357a1

Are you willing to try some testing Notepad++.exe builds?

In the meantime, you could also try to get the relevant log as is described in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15819#issuecomment-2509181907

**Comment by cmanley** [comment] 2025-01-30 11:33
I must add, that I'm still experiencing the issue but much less the originally was the case. Perhaps it could be related to periodic network lag as the SSH server I use is (now) in another EU country. It'd be nice if we could tune the timeout parameters in the npp configuration.

**Comment by xomx** [comment] 2025-01-31 00:34
@cmanley 
> I'm still experiencing the issue but much less than originally

Could you get that `nppLogNetworkDriveIssue.log` as before and paste its content here?

**Comment by cmanley** [comment] 2025-01-31 10:08
@xomx here it is (this is for a typical full day of work):
`2025-01-30 11:19:14  q:\work\bla\lib\php\site\t\t_FooClient.php  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 11:19:21  q:\work\bla\lib\php\site\t\t_FooClient.php  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 11:19:28  q:\work\bla\lib\php\site\t\t_FooClient.php  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 11:20:40  q:\work\bla\lib\php\site\t\t_FooClient.php  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 12:29:33  r:\work\bla\index.html  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 13:26:09  r:\work\bla\index.html  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 13:29:18  r:\work\bla\index.html  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 14:40:26  r:\work\bla\index.html  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 15:24:01  i:\work\foo\app\lib\perl\Acme\FOO\Services\Inet.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 15:44:10  i:\work\foo\app\lib\perl\Acme\FOO\P\R\E.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 15:54:19  i:\work\foo\app\lib\perl\Acme\FOO\Services\Inet.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:03:33  i:\work\foo\app\lib\perl\Acme\FOO\P\R\A.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:16:25  i:\work\foo\app\lib\perl\Acme\FOO\P\R\A.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:19:37  i:\work\foo\app\lib\perl\Acme\FOO\P\R\A.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:23:43  i:\work\foo\app\lib\perl\Acme\FOO\P\R\A.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:27:21  i:\work\foo\app\lib\perl\Acme\FOO\P\R\E.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 16:38:29  i:\work\foo\app\lib\perl\Acme\FOO\ES\Client\t\M.integration.t  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 17:10:50  i:\work\foo\app\lib\perl\Acme\FOO\ES\Client\M.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 17:15:19  i:\work\foo\app\lib\perl\Acme\FOO\P\R\A.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
2025-01-30 17:48:30  i:\work\foo\app\lib\perl\Acme\FOO\ES\Client\M.pm  in Buffer::checkFileState(), getFileAttributesExWithTimeout returned FALSE, its worker thread had to be forcefully terminated due to timeout reached!
`

**Comment by xomx** [comment] 2025-02-03 11:55
> tune the timeout parameters in the npp configuration.

I'll see what I can do, but no promises (low spare time).
I'd like to link this possible new functionality also with this new option: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14103#issuecomment-2280782760
Possible mock-up then:

![Image](https://github.com/user-attachments/assets/de49fee7-8d56-48e8-be37-912f5f4c5170)
