### ISSUE TITLE
[Feature request] Tab color customization

### ISSUE THREAD

**Issue by ryehamstrawberry** [notepad-plus-plus/notepad-plus-plus#15232] opened 2024-06-01 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Lack of tab color options, only 5 available to choose.

### Describe the solution you'd like.

Implement a custom color picker option for user's to set their own RGB per tab and if nothing else, add more preset color choices.

If more color presets are added, the menu can become unwieldy, at which point I'd suggest implementing the ability to allow user's to set their own color menu (allows user to organize their own color menu of presets).

### Debug Information

```shell
N/A
```

**Comment by sXNA** [comment] 2024-06-02 07:48
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12156

**Closed** 2024-07-08 13:44 UTC
Labels: duplicate
