### ISSUE TITLE
Default directory setting works inconsistently

### ISSUE THREAD

**Issue by ccompletion** [notepad-plus-plus/notepad-plus-plus#1602] opened 2016-03-08 11:53 UTC
This setting: Preferences -> Default Directory -> Follow current document
often does not work.

As long as I keep opening files in the same directory, it works. However, I have many projects open. Often, I trigger the Open File dialog in one directory, and then browse to another directory.

It is such sessions, that often fail to properly respect the setting. When I later trigger the Open File dialog, it no longer follows the setting, but opens in that directory to which I browsed. Even though the file from which I open is not located in that directory.

It is as if the setting changed to the second option, "Remember last used directory".

This is very bothersome, because I only occasionally browse to another folder, but then I find myself needing to browse around for all other files where I shouldn't need to.

Restarting Notepad++ resolves the issue. I do not know how to consistently reproduce the issue, but this happens almost on a daily basis for me (when I browse to other folders).

**Comment by sng843ndf86nd8** [comment] 2016-03-09 12:32
I have similar problems, when I save session to some folder. Then click Load session it opens me in some totally other folder. Then other day, also in different other folder.
Simply when I want open Load session I better open damn files manually, because it does not remember ANY folder for anything. Sadly

**Comment by MetaChuh** [comment] 2019-04-13 02:36
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:36 UTC
