### ISSUE TITLE
Function not shown in functionlist

### ISSUE THREAD

**Issue by ErHaMep** [notepad-plus-plus/notepad-plus-plus#12434] opened 2022-10-31 14:04 UTC
### Description of the Issue

When a function-name is followed by some comment, the function is not listed in the function-list.
u32 getmLuxR(int fd)                            // Lees milli lux in
{

    blabla....
    .......
 
}   // getmLuxR
When I delete the comment the function is shown in the list

### Debug Information

Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\O\Nestkast\Software\20221028\NK-IR-AanUit.c"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Screenshot with comment
![NK-IR-AanUit c - Notepad++](https://user-images.githubusercontent.com/36822889/199025838-3b00f445-36a6-4b0c-bb7c-323699c8c438.jpg)

Screenshot without comment
![NK-IR-AanUit c - Notepad++-NoComment](https://user-images.githubusercontent.com/36822889/199026415-1b25022b-63d1-45ed-9e2b-9f8eb61480fc.jpg)

**Comment by ArkadiuszMichalski** [comment] 2022-10-31 16:15
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3685.

**Closed by ArkadiuszMichalski** 2022-10-31 16:15 UTC
