### ISSUE TITLE
Error(604) while editing

### ISSUE THREAD

**Issue by noetus** [notepad-plus-plus/notepad-plus-plus#982] opened 2015-10-02 08:11 UTC
Pressing the escape key while editing often produces the following error popup:

Error(604)

ErrorLevel=0
NPPM= 0xFBA

Clicking OK makes it go away.  Nothing bad seems to happen.

Windows 8.1 x64 VM on Mac OS host

**Comment by donho** [comment] 2015-10-02 11:11
what is your plugin list?

**Comment by noetus** [comment] 2015-10-02 13:37
It's the default install, no additional plugins.

**Comment by donho** [comment] 2015-10-02 15:47
Can you reproduce it steadily?

**Comment by noetus** [comment] 2015-10-03 02:14
Yes - whenever the pop-up displays if editing some word that gives me options, if I press escape instead of selecting one of the words from the list on offer, I get the error.  Consistently.  If I select one of the words on offer by scrolling and pressing enter, I do not get the error.  Consistently.

**Comment by donho** [comment] 2015-10-06 15:34
Your Notepad++ version?

**Comment by noetus** [comment] 2015-10-09 07:55
It's version 6.8.3

**Comment by MetaChuh** [comment] 2019-04-10 01:07
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 01:07 UTC
