### ISSUE TITLE
Update Scintilla/SciTE/TinyXML to latest version

### ISSUE THREAD

**Issue by vgturtle127** [notepad-plus-plus/notepad-plus-plus#1126] opened 2015-11-11 07:05 UTC
We are a few versions behind (well, more than a few, I guess).

Many new features, bug fixes, and improvements have been made.

I'm not sure if you customize Scintilla/SciTE at all for Notepad++ (I hope not, since that would make upgrading a pain), but if you don't then you should upgrade ASAP. Especially since we are coming up on 7.0. :smiley: 

TinyXML should also be upgraded, I believe some bugs were fixed and I think some improvements were made as well.

**Comment by ariccio** [comment] 2015-11-18 20:31
+1

**Comment by mchels** [comment] 2015-12-10 19:10
+1

**Comment by vgturtle127** [comment] 2015-12-10 20:56
@donho 

Also, we should update TinyXML. :smile:

**Comment by MetaChuh** [comment] 2019-04-10 23:14
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:14 UTC
