### ISSUE TITLE
notepad ++ doesnt return focus to previous program when closed! 

### ISSUE THREAD

**Issue by minsikau** [notepad-plus-plus/notepad-plus-plus#1108] opened 2015-11-08 00:09 UTC
Notepadd++ 6.8.6 and most previous version has the annoying habbit of not returning focus to the previous program in windows 10 64bit desktop.

other programs work fine, 

ie in explorer 
click open a text file which opens in notepad++, close notepad++ 
focus does not return to previous program, doesnt focus on anything i can see! 

open a picture in explorer with xnviewmp for instance, 
close picture view and focus returns to previous program explorer.

**Comment by David-Hari** [comment] 2016-06-22 03:01
I've been having that issue too, and it's annoyed me for such a long time.
I just found [this post](https://notepad-plus-plus.org/community/topic/11167/focus-does-not-return-to-previous-app-when-closing) on their forums about it. The guy who reported it found that it was caused by the "Compare" plugin. Disabling it fixes the problem.

**Closed** 2016-06-22 05:53 UTC
Labels: invalid
