### ISSUE TITLE
Shortcuts grid gets smaller on every page change

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#878] opened 2015-09-09 17:38 UTC
Notepad++ version 6.8.3 on Windows 7

Open the keyboard shortcuts window and watch the size of the grid control in the middle. Now switch tabs/pages between the different sections. With every page change the grid gets a bit smaller until it cannot be used anymore.

Switching between "Main menu" and either one of "Plugins" or "Scintilla commands" does not resize the grid. Other transitions cause varying changes in size. Looks like a code mess fighting strange symptoms instead of doing it right in the first place.

**Comment by h-h-h-h** [comment] 2015-09-11 22:42
I can't reproduce the bug (Notepad++ 6.8.3, Windows 8.1).

**Comment by dg9ngf** [comment] 2015-09-13 16:47
Here's a [screen recording](http://unclassified.de/tmp/videos/npp-shortcut-mapper-win8.mp4) (MP4 H.264, 850 kB) in a clean Windows 8.1 environment. It behaves differently from my Windows 7 work machine. On Windows 7 the control additionally decreases in height massively. On Windows 8 only the width decreases.

**Comment by h-h-h-h** [comment] 2015-09-13 21:33
Now I see. I can reproduce this bug.

Also, look how funny the dialog looks with 200 % scaling:
![shortcut mapper](https://cloud.githubusercontent.com/assets/13482553/9839116/a319905c-5a6f-11e5-8870-a3fdf9e137b8.png)

**Comment by dg9ngf** [comment] 2015-09-14 05:41
That dialog is the most broken thing I've seen in a very long time, really!

**Comment by dail8859** [comment] 2016-07-31 23:56
Closed by 1abac157993685c4f6345443f6256403526858ad

**Closed by dail8859** 2016-07-31 23:56 UTC
