### ISSUE TITLE
Npp text selection highlighting isnt working in v6.8.6

### ISSUE THREAD

**Issue by b3wii** [notepad-plus-plus/notepad-plus-plus#1135] opened 2015-11-12 09:43 UTC
The highlighted text loses the highlight color when scrolling and does only randomly show when a word is double clicked. Here a video of the bug(8MB): http://www.filedropper.com/12-11-201510-39-39

**Comment by AleWin32** [comment] 2015-11-12 11:14
Yes, this also happened to me when scrolling some weeks ago.
I created a similar ticket refering to this, but ocurred to me without doing scrolling:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1082

**Comment by donho** [comment] 2015-11-12 13:28
@b3wii & @AleWin32 Could you provide your plugin list?

**Comment by b3wii** [comment] 2015-11-12 13:44
@donho https://goo.gl/h4cAm0

Fyi the highlighting somehow started working again.. after closing npp. I report back if it happens again.

**Comment by AleWin32** [comment] 2015-11-13 00:02
It's difficult to reproduce, it only hapenned once to me... But it is exactly like the video in the first post. When scrolling, sometime words are highlighted, sometimes not, and selecting a word sometimes it does not highlight the others...

My plugin list:

Compare 1.5.6.2
Converter 3.0
HTML Tag 0.5
MIME Tools 1.9
NppExport 0.2.8
NppFTP 0.26.3
Plugin Manager 1.3.5
TextFX Characters 0.2.6
Tidy2 0.2

**Comment by MetaChuh** [comment] 2019-04-10 21:33
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 21:33 UTC
