### ISSUE TITLE
Opening Multiple Files In Explorer.exe Simultaneously Causes Windows To Hang/Freeze.

### ISSUE THREAD

**Issue by pike168** [notepad-plus-plus/notepad-plus-plus#5181] opened 2018-12-31 21:42 UTC
### Description of the Issue
When i select multiple files in an explorer.exe window and press enter to attempt open all the files simultaneously, the system goes into a type of loop where is becomes completely unresponsive. 
I can press CTRL+Alt+Delete and then switch to another account where the system works fine, but when i switch back to the original faulting account, the system is still in this hang/looping freeze which doesny allow me to open a task manager and kill the notepad++.exe.

I tested that notepad++ was the problem by first starting the provided batch script and then selecting multiple text files in an explorer.exe window open trying to simultaneously open them. the system does hang, but when the taskkill ends the process, the freeze stops completley and i can work again.

timeout 20
taskkill /f /im "notepad++.exe" /t

I have also noticed something rather strange, if i select multipe files in explorer.exe using a drag-and-hold action with the mouse, explorer can open these files. However, when i instead select multiple files by holding down CTRL key and then clicking the desired files, this will cause notepad++.exe to crash when i try to open them with enter.

When i do not kill the hanging notepad++.exe process with the above batch file, and just instead just try to let the hang/freeze continue, Windows 10 will produce a "UNEXPECTED_KERNEL_MODE_TRAP". I have two minidump .dmp files that were produced that can be opened with WinDbg[x64].

[notepad++_minidumps.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2718968/notepad%2B%2B_minidumps.zip)

I have tried this with multiple versions of Notepad++, included different versions, builds [x86/x64], and with and without plugins.

### Steps to Reproduce the Issue

1. Navigate an explorer.exe window to a folder containing text files
2. Select multiple files by holding the Ctrl key and then left clicking files chosen for editing
3. Press Enter key to try and open these multiple files

### Expected Behavior
Notepad++ Should open these selected multiple files in a single window, ready for editing.

### Actual Behavior
Windows completely freezes/hangs.

### Debug Information
Notepad++ v7.5.9   (32-bit)
Build time : Oct 14 2018 - 15:02:52
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll CustomizeToolbar.dll PluginManager.dll SherloXplorer.dll 

Thanks for any help.

**Comment by Big--Mike** [comment] 2019-01-26 11:13
I made a [similar report already](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4447) in April 2018. I was using version 7.5.6 x86 at this time, which had the issue.

**Comment by rebusx** [comment] 2019-01-26 16:06
#4447

**Comment by SinghRajenM** [comment] 2019-04-21 11:52
Not able to reproduce with both 32 bit and 64 bit on V7.6.6. Is there an easy way to reproduce?

It is duplicate of #4447 (For tracking).

**Comment by MetaChuh** [comment] 2019-04-21 12:22
@pike168 

we can not reproduce a freeze, when opening multiple files in notepad++ 7.6.6 x86 and x64, via windows explorer on win7 pro x64 and win10 pro x64 (build 1809).

we can only see a normal lag, if a local or network drive is hibernated, while trying to open files located on that drive/share.

if your issue persists, please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if possible, conduct a uninstall and clean install, preferably with the 64 bit version of notepad++, if you don't need any old plugins that do not exist for 64 bit, as notepad++ x64 can also deal with larger files.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-21 12:22 UTC
Labels: not reproducible

**Comment by MrChebur** [comment] 2020-07-29 09:34
I face the same problem here with fresh installation without plugins.
