### ISSUE TITLE
Open file explorer window button says Save

### ISSUE THREAD

**Issue by AlexOnGit** [notepad-plus-plus/notepad-plus-plus#10137] opened 2021-07-09 21:28 UTC
### Description of the Issue

When you click Open from the Toolbar or File menu, the buttons are Save and Cancel instead of Open and Cancel. Just noticed it in NP++ 8, can't remember if it was always that way all these years.
### Steps to Reproduce the Issue

1. Click 'Open'

### Expected Behavior

The open window should have an Open button like in MS Paint
### Debug Information

![image](https://user-images.githubusercontent.com/87209518/125137267-59433080-e0da-11eb-9b98-fdc04e1a73b0.png)
![image](https://user-images.githubusercontent.com/87209518/125137532-e25a6780-e0da-11eb-8b06-cad2180d8ee0.png)

**Comment by mere-human** [comment] 2021-07-10 05:46
Duplicate of #9966 #10030 #10031 #10047 and possibly others.
This has been fixed in 8.1.
Please search for existing issues (open OR closed) before creating a new one -- thanks.

Citing @sasumner 

I don't know, maybe, it would be easier to create a bot that searches for duplicates☺️

**Closed** 2021-07-14 00:12 UTC
