### ISSUE TITLE
File modification watcher self-clobbers save in same tab and destroys all trace of file

### ISSUE THREAD

**Issue by TuggyNE** [notepad-plus-plus/notepad-plus-plus#394] opened 2015-07-03 00:59 UTC
Just now I made a minor edit to a userscript and saved it, then immediately switched windows; a bit later, I switched back to N++, which had a dialog asking if I wanted to reload the changed file. I wasn't paying enough attention and hit yes, whereupon an error message came up to tell me that for some reason the save had failed, and to make sure I had enough disk space. (I did.)

Naturally, the file was zeroed and the undo history lost. It's unrecoverable, all because of some sort of race condition.

The file was not being modified by any other program, and Firefox doesn't lock userscripts when running them.

**Comment by milipili** [comment] 2015-07-03 08:12
The file modification watcher must be revamped

**Comment by johnhaire89** [comment] 2015-08-23 07:11
I also noticed an issue with the modification watcher
I had a logging file open
went to plugin manager to install document watcher
clicked install and it told me to update plugin manager
Not sure if I clicked yes before the document manager came over the top and rendered everything unresponsive

**Comment by jurko-gospodnetic** [comment] 2018-12-16 17:53
I've also seen occurrences of Notepad++ crashes on save operations where after it restarts, the file that was getting saved is loaded with the right size (or at least approximately so), but filled with all zero bytes.

Could be related to the `MoveFileEx()` Windows API problems mentioned in the following link https://stackoverflow.com/questions/6525943/cause-of-corrupted-file-contents. And if that is the case, and the problem is happening with some temporary file moves, we should likely be explicitly flushing the OS write buffers (e.g. `FlushFileBuffers()` Windows API - https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-flushfilebuffers) after finished writing to the temporary file and before moving/renaming that file.

**Comment by MetaChuh** [comment] 2019-04-09 23:24
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:24 UTC
Labels: bug
