### ISSUE TITLE
[Feature request] Anchor/Lock the position of the Find/Replace window

### ISSUE THREAD

**Issue by jethro951** [notepad-plus-plus/notepad-plus-plus#15754] opened 2024-11-03 00:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When working on projects, I rely heavily on find/replace using the Find window. I will move/drag the Find wind out of my way, usually top-right corner of the window, just below the tab row, but not overlapping the vertical scrollbar. The next time I press CTRL+F to find/replace, it repositions the Find window to the center of my NotePad++ window.

### Describe the solution you'd like.

Create an "Anchor" or "Lock position" checkbox on the Find window so that when you position the Find window, you click the Anchor checkbox and the Find window is locked in place. Even if you press CTRL+F, the Find window will remain anchored irregardless if the window is resized. If you manually move the anchored/locked Find window around, it should remember that location within the NotePad++ window and remain anchored/locked.

### Debug Information

```shell
N/A
```

**Comment by alankilborn** [comment] 2024-11-03 11:47
>The next time I press CTRL+F to find/replace, it repositions the Find window to the center of my NotePad++ window.

In general terms, it will do this if you press Ctrl+f twice in succession.  Meaning, if the Find tab already has input focus and you (for some reason) press Ctrl+f (which would be unnecessary to do).  Solution: Don't do that action sequence.

Otherwise, it is impossible to evaluate as "Debug Information", a requirement for submitting an issue, was not provided.
Please provide it or close this issue.

**Comment by jethro951** [comment] 2024-11-03 19:37
Hi,

I did give it a try (pressing CTRL+f one time) and the F8nd window does
remain, pressing CTRL+f twice focuses the Find window to the center of the
NotePad++ window.

I submitted this as a feature request (suggestion) to create a checkbox to
anchor/lock that Find window so it cannot move unless it were moved
intentionally. There are times where the Find window just moves yo the
center and I know I'm not double pressing CTRL+F because I don't develop
habits like that. It'd be nice to eliminate the possability of that window
moving from where I like to have it positioned.

It just seems like a feature that should be there. =)

Thanks for the reply.

**Comment by alankilborn** [comment] 2024-11-03 21:41
Maybe it isn't a bad idea, for those that can't recall that they already have input focus in the _Find_ window, and press Ctrl+f again.

**Comment by Coises** [comment] 2024-11-04 02:59
It sounds like the solution — if this is possible — would be to make it so that the repositioning occurs only when Ctrl+F is pressed twice with no intervening activity, rather than whenever Ctrl+F is pressed when the dialog already has focus. That would retain the desired function and resolve the request without introducing a new setting.

**Comment by alankilborn** [comment] 2024-11-04 11:49
>with no intervening activity

What's the definition for that?

**Comment by donho** [comment] 2024-11-04 11:57
As the code & GUI are cluttered for find dialog, except there are a lot of similar request, this feature is unlikely to be implemented.

**Closed by donho** 2024-11-04 11:57 UTC

**Comment by alankilborn** [comment] 2024-11-04 12:19
>reject 

Well, I think @Coises might have had some idea for achieving it without GUI changes, but hasn't had time yet to express his thinking.  It might be nice to hear that before applying the big reject stamp.  :-)

**Comment by donho** [comment] 2024-11-04 12:50
> only when Ctrl+F is pressed twice with no intervening activity, rather than whenever Ctrl+F is pressed when the dialog already has focus. That would retain the desired function and resolve the request without introducing a new setting.

I don't think it's trivial or even possible to be implemented. 
@Coises you're welcome to create a PR for it. If the code is small and concise, I will accept it.

**Comment by Coises** [comment] 2024-11-04 17:38
@alankilborn asked:
> > with no intervening activity
> 
> What's the definition for that?

My “definition” was whatever would fall in the category of @jethro951 saying:
> I know I'm not double pressing CTRL+F because I don't develop habits like that.

Of course, if someone can demonstrate a reproducible case in which using a find/replace dialog shortcut (Ctrl+F, Ctrl+H, Ctrl+Shift+F, etc.) causes the dialog position and size to be reset to default when the dialog did not previously have focus *or* the tab corresponding to the shortcut was not the active tab, that would be a bug.

I suspect, though, that the dialog did have focus, the Find tab was active, and the original poster was going on “muscle memory” — hence, in his mind, not pressing Ctrl+F *twice*.

I wrote “if it is possible” because, without having examined the code (I still haven’t), I suspected what @donho asserts: that such a thing is likely to be difficult, error-prone, or impossible.

I was simply noting that a user’s sense of “pressing Ctrl+F twice” is not the same thing as what is implemented, which is “pressing Ctrl+F when it would be redundant if we didn’t make it do something other than what it usually does”; and that if what were implemented were closer to what users expect, the requested feature would be unnecessary.

**Comment by jethro951** [comment] 2024-11-04 19:19
Thank you everyone for your efforts and your time.

**Comment by alankilborn** [comment] 2024-11-04 19:52
>I was simply noting that a user’s sense of “pressing Ctrl+F twice” is not the same thing as what is implemented, which is “pressing Ctrl+F when it would be redundant if we didn’t make it do something other than what it usually does”; and that if what were implemented were closer to what users expect, the requested feature would be unnecessary.

Ouch.

---

>I know I'm not double pressing CTRL+F because I don't develop habits like that.

User is confusing two presses in quick succession with one press and then later another press while _Find_ tab has input focus.

---

>My “definition” was whatever would fall in the category of...

Hmm, okay, no real ideas then...

---

I'm thinking reject and closure was the right course of action.

**Comment by Coises** [comment] 2024-11-04 20:33
@alankilborn:
> User is confusing two presses in quick succession with one press and then later another press while _Find_ tab has input focus.
> User is doing it, just doesn't realize it.

You don’t have to press Ctrl+F twice at all:

Open Notepad++.
Select **Search** | **Replace...**.
Move the dialog somewhere other than default location.
Click on the **Find** tab.
Press Ctrl+F.
Dialog resets to default position.

All the find/replace dialog shortcuts (Ctrl+F, Ctrl+H, etc.) open the dialog if it isn’t already open, focus the dialog if it isn’t already focused, and select the appropriate tab if it isn’t already selected — unless the dialog is already opened and focused and the appropriate tab is already selected, in which case they reset the dialog position. There’s no “press twice” about it.

I haven’t looked it up, but my memory is that this was added as a way to retrieve a “lost dialog” that was opened off-screen (usually because screen configuration had changed). So the instruction is to press the key combination twice, since the first press will open the dialog and give it focus on the correct tab, even if you can’t see it; then the second press will move it to a visible location. Pressing it twice isn’t how it works, though, it’s just how it can be used to solve a particular problem.

**Comment by alankilborn** [comment] 2024-11-04 21:46
> You don’t have to press Ctrl+F twice at all

I already said that, in my FIRST posting in this thread:

>meaning, if the Find tab already has input focus and you (for some reason) press Ctrl+f...

Saying "press the keycombo twice" is just a faster way to say it (and to demo the centering behavior, from a closed Find window); hope everyone understands that.  

I honestly think we're all confused (the discussion, not the issue) due to the nature of talking about it here, via typing, rather than sitting around a conference table at Notepad++ Inc. headquarters, live-discussing it  :-)

---

>...this was added as a way to retrieve a “lost dialog” that was opened off-screen

Correct.

>the instruction is to press the key combination twice, since the first press will open the dialog and give it focus on the correct tab, even if you can’t see it; then the second press will move it to a visible location.

It's because user is confused because they don't see anything and they think they should.  At the time of problem they've already pressed Ctrl+f (because that's how EVERYONE invokes the Find dialog, but it could have been from e.g. the main menu).  So really the instruction is "if you don't see the Find window right after you've  invoked it, press Ctrl+f".  This "press Ctrl+f" MUST be the keycombo, not the main menu (because doing the menu method would cause the Find window to lose focus and the centering logic only works when the command is invoked when the Find window has the focus.

---

I think the horse has been beaten to death.
Especially for an issue that is going to result in no action.  :-)
