### ISSUE TITLE
File status auto-detection ONLY for active tab #feature

### ISSUE THREAD

**Issue by adiiik** [notepad-plus-plus/notepad-plus-plus#3971] opened 2017-12-07 13:33 UTC
### Description of the Issue

Messages like "“Keep this file in editor?” or “File has been modified by another program. Would you like to reload it?” are very annoing if I have opened a lot of documents. When I return to the program window, I sometimes have to go through a dozen such messages. On the other hand, I need the file status auto-detection option, but only on currently displayed document.

### Steps to Reproduce the Issue

1. Minimize NPP window.
2. Delete or edit opened in NPP files.
3. Restore NPP window.

### Actual Behavior

When I return to the program window, I sometimes have to go through a dozen such messages.

### Expected Behavior

Why not add the file status auto-detection option ONLY for the currently displayed file? This would eliminate the problem of clicking dozens of messages when returning to the program window. At the moment I’m not interested in what happens to 30 files that I have open in the background, and I’m interested in only one that is displayed.

### Debug Information

![nppefat](https://user-images.githubusercontent.com/14057976/33717813-9185e34e-db5b-11e7-878f-c0d851b24707.png)

**Comment by CaverBruce** [comment] 2018-01-13 18:45
Absolutely. I want to know when file(s) have been updated, but only when I a) open Notepad++ and it is restoring a session, or b) during routine editing, only when I activate an existing tab, or c) if the file in the active tab is updated.  ie, just as Adiiik describes.
I tick 'Enable', and have trialled 'update silently' but it is unsafe, as I can by accident edit in another dominant application.  With 'update silently' unticked, workflow is necessarily disrupted in 95% of cases.

**Comment by marceloramires** [comment] 2018-03-18 22:44
This annoys me a lot as well. I'd volunteer to implement if I knew the change would be approved (provided that it works as intended, of course).

**Comment by 42degrees** [comment] 2018-10-12 19:59
Duplicate of issue [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)

**Closed** 2019-03-17 12:05 UTC

**Comment by cuchisavila** [comment] 2022-02-28 22:13
IS there a way to recover a older version I was working on that got accidentally replaced by this feature? I accidentally hit yes and now all my notes are gone
The undo option does not work and i checked in the backup folder and cannot find it there.
