### ISSUE TITLE
Saving a file with more than one file stream deletes them

### ISSUE THREAD

**Issue by NicoDerp** [notepad-plus-plus/notepad-plus-plus#8451] opened 2020-06-22 22:01 UTC
# Description of the Issue
If you have a file with an alternate data stream, make some changes to the main one, then save. All the other data streams will disappear.

### Steps to Reproduce the Issue
1. Create an alternate data stream on a file. ( In cmd: 'echo something > myfile.txt:secondstream' )
2. Open up myfile normally by just double-clicking it.
3. Do some changes and hit save.
4. The 'secondstream' you created is now gone.

### Expected Behavior
The expected behaviour is that all of the file's streams won't disappear.

### Actual Behavior
What happens is that all of the file's streams disappear.

### Debug Information

Notepad++ v7.8.5   (64-bit)
Build time : Mar  4 2020 - 11:08:34
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1903
OS Build : 18362.900
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

To show what happens, in the command prompt you can use the command 'dir /r' to see files including other streams.

Setup:
![setup](https://user-images.githubusercontent.com/52355359/85339344-42886680-b4e4-11ea-9140-b4e163f4b8fc.PNG)

Before saving with Notepad++:
![before](https://user-images.githubusercontent.com/52355359/85339392-559b3680-b4e4-11ea-87f4-ba09daf9d3ca.PNG)

After saving with Notepad++:
![after](https://user-images.githubusercontent.com/52355359/85339406-5cc24480-b4e4-11ea-81da-18a42e160255.PNG)

**Comment by sasumner** [comment] 2020-06-22 23:02
Closing as duplicate of #1498

**Closed** 2023-09-14 11:54 UTC
