### ISSUE TITLE
Suggestion: sticky settings when updating to new version

### ISSUE THREAD

**Issue by tastyratz** [notepad-plus-plus/notepad-plus-plus#1638] opened 2016-03-16 15:35 UTC
One thing that always got me with NPP and the frequency with which it updates is that my customized settings are not referenced for defaults when installing the new updates. If I choose to allow loading of plugins and not use the appdata directory then shouldn't that persist as default check every time the software is updated? If it's intelligent enough to know it's open or already exists, those common configs should be read on installer launch so I don't accidentally install an update and disable plugins, etc.

**Comment by tastyratz** [comment] 2016-03-16 15:40
alternatively, intelligent snapshotting and timeline on rock-on updates might be worthwhile. You could just install a new rock on and if there are any problems, roll it back. Snapshots could be made at install and have a default timeline of say 48 hours (provided individual rock-on's could be snapshotted).

**Comment by MetaChuh** [comment] 2019-04-13 02:30
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:30 UTC
