### ISSUE TITLE
Crash (exception Access violation) on Settings Preferences under Ubuntu (Wine)

### ISSUE THREAD

**Issue by LucMorizur** [notepad-plus-plus/notepad-plus-plus#12021] opened 2022-08-18 06:36 UTC
Hi; _**many thanks**_ for Notepad++!

### Description of the Issue
On Ubuntu, I've not found so far a so nice text editor as Notepad++ on Windows, so I'm using NPP on Ubuntu, thanks to Wine, which allows to run Windows applications on Linux-based operating systems. Most of the time it works fine.

I currently have NPP 8.4.4, Linux 5.15, Ubuntu 20.04, Xfce 4.14. When I try to display Preferences dialogue of Settings menu in NPP, a crash dialogue pops up, showing:

An exception occured. Notepad++ cannot recover
and must be shut down.
The exception details are as follows:
Code: 0xC0000005
Type: Access violation
Exception address: 0x000000006CA57458

This happens systematically.

### Steps to Reproduce the Issue
Ask for Preferences in Settings menu

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 10 (64-bit) _(This is what Wine declares)_
OS Build : 17763.0
Current ANSI codepage : 1252
WINE : 7.0
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Attached the crash dialogue, and the dump file.

Of course I guess that already plenty of work is to be done for NPP under a "normal" (Windows) environment. But, well, in case this issue is easy to fix... many thanks again!

--
Luc

![Image](https://user-images.githubusercontent.com/24322102/185309850-5deaa3c9-2d08-4e1d-aa44-c7192fa4b465.png)
[Document.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9368188/Document.zip)

**Comment by CennoxX** [comment] 2022-08-19 11:13
Duplicate of #11941, this should be solved with https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11961 and will probably be released with 8.4.5. Could you test this version https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/44463978/job/1cw6oegx7trik8rm/artifacts

**Comment by LucMorizur** [comment] 2022-08-19 16:43
Hi; sorry for not having found #11941.
Tested the version mentioned, the Style configurator dialogue pops up properly.
Many thanks and success!

**Closed** 2022-08-31 01:03 UTC

**Comment by LucMorizur** [comment] 2022-09-28 06:52
Hi; I confirm that in version 8.4.5 this bug is fixed. Many thanks!
