### ISSUE TITLE
NPPN_DOCORDERCHANGED is never fired when opening files or moving files between views.

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#1236] opened 2015-12-09 11:33 UTC
Hi,

using 6.8.7, windows 10..

This notification is never fired, regardless what I do. I've tried following.

Change tab order, move documents from main view to sub view and vice versa.

Open, close random documents.

Please verify and fix - or explain when this notification is supposed to be fired..

**Comment by dail8859** [comment] 2015-12-09 23:04
It seems to be working for me. I stepped through Notepad++ with a debugger, and even modified one of my plugins to catch it.

To make it fire I open 2 or more files, and drag and drop the tabs to reorder them. Is this how you are doing it?

**Comment by sanastasiou** [comment] 2015-12-09 23:11
Hm, did you try a release version? I'll try it myself then with the source.

Yeah, that's what I have been trying however in my case I had both views open - don't know if his plays  a role.

I tried what you tried and also moving a file from one view to another.

I'll try with the source and let you know. Might be, that the NppMsg which I've been using is old..

**Comment by sanastasiou** [comment] 2015-12-09 23:18
Ehm : starting the debugger with 2015 VS without upgrading the compiler version does this:

Exception thrown at 0x00007ffe51611f08 (KernelBase.dll) in Notepad++.exe: Microsoft C++ exception: std::exception at memory location 0x000000488e8818c0.

= lol

**Comment by sanastasiou** [comment] 2015-12-09 23:22
So, problem reproduce with most actual version using VS2013 and debug.

Just open up 4 files, place two on each view and move files from one view to another.

Event never fires - which probably could lead to unexpected behavior of clients ( plugins ).

**Comment by dail8859** [comment] 2015-12-10 01:18
I stepped through the current master branch with VS 2013. I caught the notification with a plug in using v6.8.7 official release.

**Comment by sanastasiou** [comment] 2015-12-10 07:40
Even when moving files from one view to another? Never fires for me.. Also tested the current master..

**Comment by dail8859** [comment] 2015-12-10 12:35
When I get a chance later today I'll dig into it more and let you know.

**Comment by dail8859** [comment] 2015-12-10 22:01
Tried a default install of v6.8.8 with a test plugin to catch this notification:
* Moving files between the same view does send the message
* Moving files between views does *not* send the message
* Opening or closing files does *not* send the message

I can't say whether this is the expected behavior or not. @sanastasiou Is this the same result you are seeing?

**Comment by sanastasiou** [comment] 2015-12-10 22:05
Hi @dail8859 . Yes, it's exactly the same. 

How is this not a bug? If e.g. someone has a "cache" of opened files and listens to this event to update this cache he will fail, because if you move some file from one view to another between some opened tabs you are practically changing the order right ? So that would lead to crashes.

Of course there are workarounds, like listening to "buffer activated" events and updating your list of files then. However this makes this event NPPN_DOCORDERCHANGED unusable in my opinion.

**Comment by dail8859** [comment] 2015-12-10 22:10
I've never had a need for this notification so I've never really looked into how it's used, but from the sounds of it, it does appear to be a bug.

**Comment by MetaChuh** [comment] 2019-04-11 00:43
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:43 UTC
