### ISSUE TITLE
Upgrade Message is incorrect

### ISSUE THREAD

**Issue by asashour** [notepad-plus-plus/notepad-plus-plus#2184] opened 2016-08-18 12:35 UTC
### The text message is incorrect during upgrading

![image](https://cloud.githubusercontent.com/assets/2410127/17773848/ac0223fe-6550-11e6-961a-a433c1f39aeb.png)

### Steps to Reproduce the Issue
1. Have an older version
2. Upgrade to the latest version
3. 

### Expected Behavior
The message "Choose Cancel to it this installation" should be "Choose Yes to keep it in this installation"

**Comment by dail8859** [comment] 2016-08-18 17:50
Duplicate of #1614.

**Closed by dail8859** 2016-08-18 17:50 UTC
Labels: duplicate
