### ISSUE TITLE
I have made a notepad++ theme generator

### ISSUE THREAD

**Issue by ZoomDomain** [notepad-plus-plus/notepad-plus-plus#1671] opened 2016-03-22 18:16 UTC
I have just written a notepad++ theme RANDOM GENERATOR :DDD it runs in unity3d compiler at the moment and it can generate 1000ds of xml templates from one template which is faster than searching online and DLing them, you have to specify roughly the brightness of bg and fg and it will generate the random colors, you can change the code to add some random saturation and value on top of the base values which are the brightness darkness preferences. 

It takes previous themes and changes all the colors only. you can mod the code to change also the font, it just rewrites the colors on preexisting xml theme files.

For reference, here is code of the N++ random theme generator, run it in unity3 and change the file paths. If you run it in a loop of 100 it will make 100 themes every time, it requires a notepad theme example file in the first path.

also here is the file for the first 200 generated random themes. it's based on HSV colorspace.
JS:
[code]
            var darks = 0.2; //base contrast , for the moment it's high contrast.
            var brights = 0.8;//base contrast , for the moment it's high contrast.
            var sat = 0.7; //  Saturation
            //  hue will be random
            var mediums = //base contrast , for the moment it's high contrast.

```
        var sourcexml :  String = "C:/Users/WorkStation/Documents/audiow/Assets/codes/Black board.xml";
        var savetopath : String = "C:/Users/WorkStation/Documents/audiow/Assets/codes/" ;   //these are both paths

        function Start(){

        lineChanger();

        }

            function lineChanger()
                {
                    var gobalDarkColor = RGBToHex(HSVtoRGB( Vector3( Random.value , sat , darks ) ) ) ;
                    var arrLine : String[] = File.ReadAllLines(sourcexml);

                    var globalCommentColor = RGBToHex(HSVtoRGB( Vector3( Random.value , sat , brights*.75 )  ) ); // make comments a bit less bright with a multiplier on the value

                    for(s in arrLine ){ //  All colors in this loop will be different except using global defined prior to loop

                        if ( s.Contains("WordsStyle") && !s.Contains("COMMENT")){// general random colors and a background color

                            var randomColor = RGBToHex(HSVtoRGB( Vector3( Random.value , sat , brights )  ) );
                            var pos = s.IndexOf( "bgColor=" );
                            s= s.Remove(pos+9, 6).Insert(pos+9, gobalDarkColor);
                            pos = s.IndexOf( "fgColor=" );

                            s= s.Remove(pos+9, 6).Insert(pos+9, randomColor);


                        }

                        if ( s.Contains("WordsStyle") && s.Contains("COMMENT")){

                 // general random all same comment colors. can be less bright



                        }
                        if ( s.Contains("WidgetStyle") && s.Contains("Global")){// has to be same background as uniform background from wordstyles

                   //this is for tabs and selected lines, marked lines, and so forth in notepad, will perhaps finish this afterwards.
                   //global color should be light or dark and it's the background of page outside of lines and spaces
                        }

                        if ( s.Contains("WidgetStyle") && !s.Contains("Global")){// general random all same comment colors can be les bright



                        }

                    }
                    File.WriteAllLines(savetopath+"ThemeGenV1_"+ Random.Range(0,60000).ToString() +".xml", arrLine);


            }


        function Hue( H: float ): Vector3
        {
            var R : float= Mathf.Abs(H * 6 - 3) - 1;
            var G : float= 2 - Mathf.Abs(H * 6 - 2);
            var B : float= 2 - Mathf.Abs(H * 6 - 4);
            return Vector3( Mathf.Clamp01(R),Mathf.Clamp01(G),Mathf.Clamp01(B) );
        }

        function HSVtoRGB( HSV: Vector3): Vector4
        {
            //return Vector4(((Hue(HSV.x) - 1) * HSV.y + 1) * HSV.z,1);
            var H = Hue(HSV.x) ;
            H= Vector3 (H.x-1, H.y-1, H.z-1)* HSV.y ;
            H= Vector3 (H.x + 1, H.y + 1, H.z + 1)* HSV.z;
            return Vector4(H.x, H.y, H.z,1);
                // return Vector4(Mathf.Floor(H.x*255), Mathf.Floor(H.y*255), Mathf.Floor(H.z*255),1);
        }

        function rgb2hex(C:Vector4):String{

            var rByte  = System.BitConverter.GetBytes(C.x * 256);
            var gByte = System.BitConverter.GetBytes(C.y * 256);
            var bByte = System.BitConverter.GetBytes(C.z * 256);

            var rgb :String = rByte.ToString() + gByte.ToString() + bByte.ToString();
        }


        function GetHex (decimal : int) {
            alpha = "0123456789ABCDEF8";
                //print("val " + decimal);
            out = "" + alpha[decimal];
            return out;
        };

        function HexToInt (hexChar : char) {
            var hex : String = "" + hexChar;
            switch (hex) {
                case "0": return 0;
                case "1": return 1;
                case "2": return 2;
                case "3": return 3;
                case "4": return 4;
                case "5": return 5;
                case "6": return 6;
                case "7": return 7;
                case "8": return 8;
                case "9": return 9;
                case "A": return 10;
                case "B": return 11;
                case "C": return 12;
                case "D": return 13;
                case "E": return 14;
                case "F": return 15;
            }
        };

        function RGBToHex (color : Color):String {
          red = color.r * 255;
          green = color.g * 255;
          blue = color.b * 255;

          a = GetHex(Mathf.Floor(red / 16));
          b = GetHex(Mathf.Round(red % 16));
          c = GetHex(Mathf.Floor(green / 16));
          d = GetHex(Mathf.Round(green % 16));
          e = GetHex(Mathf.Floor(blue / 16));
          f = GetHex(Mathf.Round(blue % 16));

          z = a + b + c + d + e + f;

          return z;
        };[/code]
```

**Comment by MetaChuh** [comment] 2019-04-13 02:23
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:23 UTC
