### ISSUE TITLE
Notepad++ dialog shrinks and moves after text is copied using the right-click context menu

### ISSUE THREAD

**Issue by BPKasper** [notepad-plus-plus/notepad-plus-plus#2279] opened 2016-09-14 12:45 UTC
### Description of the Issue
If I select text in Notepad++, right-click on the selected text, and choose "Copy" from the pop-up context menu, the text is copied, but the Notepad++ dialog immediately shrinks to essentially zero height and width.  The dialog ends up displaying none of my text and is only wide enough to display the system menu icon, the minimize icon, the maximize icon, and the close icon (see the image at the end of this bug report).  The resulting shrunken dialog also jumps to the top-left of my primary desktop monitor.

### Steps to Reproduce the Issue
1. Enter some text
2. Select a portion of the text
3. Right-click on the selected text
4. Click on "Copy" in the pop-up context dialog

### Expected Behavior
Text should have been copied and Notepad++ dialog size and position should have remained unchanged

### Actual Behavior
Text was copied and Notepad++ dialog shrank as described, then jumped to the upper-left corner of the primary desktop monitor of my three-monitor Windows desktop.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 

Note:  My Windows desktop is extended across three monitors.  This behavior occurs when the Notepad++ dialog is located anywhere on the desktop, but the shrunken dialog always jumps to the top-left corner of my primary monitor.

The Notepad++ dialog ends up looking like this:

![image](https://cloud.githubusercontent.com/assets/22195404/18512385/dadaef88-7a56-11e6-8aa4-d2eb5296d0cc.png)

**Comment by dail8859** [comment] 2016-09-14 13:11
Duplicate of #2155. There is a work around described in that issue.

**Closed** 2016-09-21 18:51 UTC
Labels: duplicate
