### ISSUE TITLE
Close/save dialog with keyboard shortcuts

### ISSUE THREAD

**Issue by Commander238** [notepad-plus-plus/notepad-plus-plus#7683] opened 2019-12-02 10:00 UTC
Hi,
I have been used to close Notepad++ using the keyboard.
When I close Notepad++, a dialog shows up asking "Save file "new 1" ?"
In NPP version 7.7.1, I could answer the dialog by pressing a letter on the keyboard (Y/N), 
or in my native language, which is Czech, this would be (A/N). The letter would be underlined.
This is the usual behavior in all windows applications, for example Notepad.exe.
Please notice, that the labels change with different language.
I suggest, you automatically underline the first unused letter on the button. (& stands before the underlined letter).
English: &Yes, &No, &Cancel, Y&es to all, N&o to all
Czech: &Ano, &Ne, &Storno, An&o pro všechny, N&e pro všechny
If that is too complicated, you could simply listen to (Y/N) in all languages without underlining anything. 
<img width="216" alt="NPPSave771" src="https://user-images.githubusercontent.com/1488749/69950029-e5e73f00-14f2-11ea-8c93-c58a4f29813a.png">
<img width="352" alt="NPPSave781" src="https://user-images.githubusercontent.com/1488749/69950037-eaabf300-14f2-11ea-81db-0fe6f20111c8.png">

**Comment by sasumner** [comment] 2019-12-02 13:00
Closing as duplicate of #6223

**Closed by sasumner** 2019-12-02 13:00 UTC
