### ISSUE TITLE
Suggestion: don't duplicate lines with multiple hits in "find results"

### ISSUE THREAD

**Issue by Layarion** [notepad-plus-plus/notepad-plus-plus#4525] opened 2018-05-25 17:39 UTC
This is how I would like multiple hits to be handled on Notepad++.
https://i.imgur.com/43NPong.png
The above image in EditPad Pro 7.6.4

It's not though. Instead, lines with multiple hits get duplicated. I feel that this makes it harder to scroll through and read. like so: https://i.imgur.com/AfjlI35.png

If you feel that this would be a problem with the general public, make it optional.

**Comment by sasumner** [comment] 2018-05-25 20:01
Duplicate of #2987.  Please spend some time searching for existing issues before creating new ones.

**Comment by Layarion** [comment] 2018-05-25 20:38
I don't remember if I did. I probably couldn't think of the keywords that person was using if I did.

That post was made in 2017, and I feel like my images deliver a clearer image (no pun intended) of what's wanted.

though it's saddening, to see proof that it likely won't happen.

**Comment by weirdalsuperfan** [comment] 2019-04-11 08:26
Man I wish this was an option

**Comment by sasumner** [comment] 2020-11-01 13:18
This feature-request is REJECTED by the author of Notepad++ ( https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9088#issuecomment-720016310 )
It will not be reconsidered.
Please do not open any new issues on this topic as they will be immediately closed.

The suggestion is to use this workaround:
* Set your _Search mode_ to _Regular expression_.
* Add the following to the end of your _Find what_ expression:  `(?-s).*`

Example 1: To show only the first hit on a line for `foo`, make your _Find what_ expression `foo(?-s).*`

If the literal text you are intending to search for contains regular expression metacharacters, add `\Q` to its start and `\E(?-s).*` at its end.

Example 2: To show only the first hit on a line for `*foo*`, make your _Find what_ expression `\Q*foo*\E(?-s).*`

**Comment by Layarion** [comment] 2020-11-01 17:14
"To show only the first hit on a line" I do not think you understand what we asked for, because that's not anything close to what we wanted. Please read it again, because it is obvious you did not understand what is being asked for.

**Comment by sasumner** [comment] 2020-11-01 18:00
@Layarion 

It is 100% obvious you are...

My response and closure of this some hours ago was because this issue is one of a number of similar ones, and that closure comment was boilerplate used in the closure of all of them.  Apologies if it doesn't exactly "fit" with your issue.

**Closed** 2022-06-26 17:01 UTC
Labels: accepted
