### ISSUE TITLE
-n doesn't work

### ISSUE THREAD

**Issue by wvxwxvw** [notepad-plus-plus/notepad-plus-plus#11131] opened 2022-02-04 21:15 UTC
8.3
-n doesn't work. For example from grepWin. But the faggots will love the banner.

**Comment by alankilborn** [comment] 2022-02-04 21:19
Not a great issue report.
Can you do it again but fill in the template?

**Comment by wvxwxvw** [comment] 2022-02-04 23:00
Transmission of -n from another program does not work.  What should I fill in there? It works in 8.2.1, but not in 8.3.

**Comment by xomx** [comment] 2022-02-05 00:57
@wvxwxvw 
I can reproduce that, so thanks for your report, I will look at it.

> faggots will love the banner

A communist fan or you just do not like politics in SW?

**Comment by xomx** [comment] 2022-02-05 01:52
@donho 

I think that it will need more fixes. I mean:
- int lineNumber (& perhaps the columnNumber too) should be changed to intptr_t in `Notepad_plus::loadCommandlineParams`
- `CmdLineParamsDTO` & `CmdLineParams` structs from the ".\PowerEditor\src\Parameters.h" needs also the 2GB+ adaptation

**Comment by donho** [comment] 2022-02-05 03:33
@wvxwxvw 
> -n doesn't work. For example from grepWin

This issue will be fixed, thank you for your report.

> faggots will love the banner

You like it or not, this banner will stay anyway.

**Comment by wvxwxvw** [comment] 2022-02-05 10:13
Yes, for God's sake. I just think it's better to deal with the code, not the propaganda of what they lie to you about.

**Comment by xomx** [comment] 2022-02-05 12:15
@wvxwxvw 

> There is only one name left of communism, make no mistake.

I do not understand the meaning here.

> "There were those, but these came."

I think I do understand this. In my (post-communist) country are some people disillusioned too. They thought that after overthrowing communists everything will be ok, Heaven on Earth etc. But there is a price for the freedom. Living in the freedom is sometimes more difficult. There are new ways how to be bad. And the biggest problem - people are now responsible for their own lives, there is no "these/they" anymore to blame for everything.

I do not like politics either. I am glad that the SW is almost apolitical. But in this I stand up for DonHo, because of evil will remain evil regardless of its propaganda.

**Closed** 2022-02-05 18:30 UTC

**Comment by donho** [comment] 2022-02-05 22:17
@wvxwxvw 
The human rights are not political issues to me. It's about the justice in our heart deeply, when we see a human being like us is being oppressed by another human-being, then we have to act.  
So I don't think that speaking out for the voiceless people is political. If yes, then everything is political.

I consider myself as part of left wing politically since I'm in France. But unfortunately, when we check all the communist countries, they are all with dictatorship, no exception. As @xomx said (if I don't misunderstand what he said), "evil will remain evil regardless of its propaganda"

**Comment by wvxwxvw** [comment] 2022-02-25 13:04
Anticipating a new minor release, a couple of links for you.
[https://www.startpage.com/sp/search?query=в+донецке+снаряд+убил+детей&t=blak&lui=english&language=russian&prfe=0c66e7f6013aa97e3edc1f4c9bfc6de7e251ce73dcfa4378bf7413dd0140fed7cb2af8d9190412aae0c2c5961ce6b4aced4434d0e4de0c6322dce43e3747b12f9c51eeb394990d34ad5614d6a563&abp=-1&cat=web&sc=INHD35AksBYA20&abp=-1](url)  
[https://www.startpage.com/sp/search?query=a+shell+killed+children+in+Donetsk&lui=english&t=blak&abp=-1&prfe=0c66e7f6013aa97e3edc1f4c9bfc6de7e251ce73dcfa4378bf7413dd0140fed7cb2af8d9190412aae0c2c5961ce6b4aced4434d0e4de0c6322dce43e3747b12f9c51eeb394990d34ad5614d6a563&language=russian&cat=web&sc=OtrzTLopfttF20&abp=-1](url)

**Comment by wvxwxvw** [comment] 2022-02-25 13:23
I recommend reading the first link, via Google Translate. Translate, copy the translation into notepad and "search and replace" replace Russian, Russian, etc. in the name of their own nation.

**Comment by xomx** [comment] 2022-02-25 13:32
@wvxwxvw 
Thanks for this Putler propaganda.

I am using the "Putler" here, as this is a perfect copy of what did Adolf Hitler to my country in 1938, see e.g.:
https://en.wikipedia.org/wiki/Fall_Gr%C3%BCn_(Czechoslovakia)
https://en.wikipedia.org/wiki/Munich_Agreement#Sudeten_crisis

And the "invitation" from the Doneck & Luhansk "separatists" - that is the same cover-up for the open-invasion as was for my country in 1968 this (many thanks for that Russia!):
https://en.wikipedia.org/wiki/Warsaw_Pact_invasion_of_Czechoslovakia#Letter_of_invitation

And I can even read in Russian, thanks to being once their slave (no more!).

**Comment by wvxwxvw** [comment] 2022-02-25 13:42
So the killing of children has passed you by? That is, the fact that the Russians liberated Europe from the Nazis you mentioned... I don't think it's worth "throwing beads in front of a pig".

**Comment by wvxwxvw** [comment] 2022-02-25 13:46
There is a Russian proverb, and in it the phrase is "a pig who does not remember good."

**Comment by alankilborn** [comment] 2022-02-25 13:48
@xomx @wvxwxvw Can you take your discussion to here https://community.notepad-plus-plus.org/category/8/boycott-notepad or somewhere else appropriate?

**Comment by wvxwxvw** [comment] 2022-02-25 14:31
You're right. But I don't want to, see above.   
The latest on ukrofashists:
![external-content duckduckgo com2](https://user-images.githubusercontent.com/13194155/155732221-13f45196-94ba-493f-9487-4d8d2199f52d.jpg)  
Wait, soon in the cities of Europe.

**Comment by alankilborn** [comment] 2022-02-25 14:34
@wvxwxvw Upvotes my "move it" post, but doesn't move.  Hmmmmm...
