### ISSUE TITLE
Incorrect text color when adding ` in some strings

### ISSUE THREAD

**Issue by lulu5239** [notepad-plus-plus/notepad-plus-plus#11412] opened 2022-03-19 21:57 UTC
### Description of the Issue
A part of the JavaScript syntax is about using `${}` structures in string created with some `, but Notepad++ seems to not really support it.

### Steps to Reproduce the Issue
Create a new tab, set the language to JavaScript, and paste (add the characters from the image that got removed by Markdown) :
`Normal text${" but I've put ` in it"}`
![image](https://user-images.githubusercontent.com/32999164/159139448-edeec98a-5129-4283-b37f-3d5ff5aa08ec.png)

### Expected Behavior
The entire text should be red.
![image](https://user-images.githubusercontent.com/32999164/159139521-38943f0d-9866-42df-9939-02797c04ddec.png)

### Actual Behavior
A part of the string became white and has been parsed like normal JavaScript code.
At some points in a bigger script, the colors were inverted (red when JavaScript and white/others in strings).
![image](https://user-images.githubusercontent.com/32999164/159139662-43c3308e-8a20-4b33-b975-626d1e17ec7a.png)

### Debug Information
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1586
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rdipardo** [comment] 2022-03-20 03:36
Duplicate of #3822, #1055, and https://sourceforge.net/p/scintilla/feature-requests/1112

**Closed** 2022-03-20 14:03 UTC
Labels: duplicate
