### ISSUE TITLE
Closing tabs on 4-monitor setup causes window to shrink or crash

### ISSUE THREAD

**Issue by artesyn** [notepad-plus-plus/notepad-plus-plus#1282] opened 2015-12-22 23:48 UTC
I have a Windows 7, 4-monitor setup, which is a laptop connected to 3 external monitors. This creates an irregular shaped workspace. Whenever I right-click a tab and close it in Notepad++, the entire window shrinks to just a little tiny rectangle and it moves to the top-left corner of the main monitor. This happens regardless of how I arrange the monitors, or whether I am using Windows Aero or Classic themes. It does NOT happen if I disconnect the external monitors. The rectangle contains:
- Notepad++ icon
- Several characters of the title (in windows classic theme)
- minimize, maximize, and close boxes

If I am maximized when I close a tab, it seems to crash Notepad++. I can no longer control the window at all when this happens and I have to force it closed with Task Manager.

Shrunken window:
![shrunken_window](https://cloud.githubusercontent.com/assets/16407299/11968617/d10616fe-a8d3-11e5-9ddd-483d937e3bc0.png)

Monitor Setup (Main monitor is #4, Laptop monitor is #1):
![monitor layout](https://cloud.githubusercontent.com/assets/16407299/11968619/d68740bc-a8d3-11e5-983f-d56323465896.png)

**Comment by donho** [comment] 2016-01-30 12:15
@artesyn could you provide debug info via menu "?->Debug Info" ?

**Comment by artesyn** [comment] 2016-02-15 18:52
Sorry for the delayed response.  Here is the Debug info:

Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll SpellChecker.dll

**Comment by chcg** [comment] 2017-08-18 21:46
@artesyn Is still an open issue with a current version of N++, like 7.4.2 or the currently release 7.5?

**Comment by MetaChuh** [comment] 2019-04-13 02:07
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:07 UTC
