### ISSUE TITLE
crash while recording macro, then type after character after finding <>

### ISSUE THREAD

**Issue by andrew-james-heard** [notepad-plus-plus/notepad-plus-plus#2331] opened 2016-09-24 22:54 UTC
Enable macro recording, find 2 characters "<>", type any character, crash.

1. open any file containing "<>"
2. ctrl+shift+R - enable macro recording
3. ctrl+F "<>"
4. Esc
5. type any character - crash

### Expected Behavior
Expect character to be inserted at cursor.

### Actual Behavior
crash when any key pressed after finding "<>"

### Debug Information
Notepad++ v7   (64-bit)
Build time : Sep 21 2016 - 22:07:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : none

**Comment by dail8859** [comment] 2016-09-24 23:05
Since you didn't post any debug info I'm assuming you are on v7 64bit. Duplicate of #2310 which has been fixed.

**Comment by andrew-james-heard** [comment] 2016-09-24 23:42
Sorry for not posting debug info, now added. Yes sounds the same as #2310 although more general that the summary. I'm new to github.

**Comment by dail8859** [comment] 2016-09-25 01:22
To make sure it is the same bug you can download the nightly build from 

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.402/job/0rrtf2da6yxl7389/artifacts

and copy over your `notepad++.exe`.

**Comment by andrew-james-heard** [comment] 2016-09-25 01:40
I followed your instructions. That fixed the bug. Thanks.

**Comment by dail8859** [comment] 2016-09-25 01:40
Glad to hear it is working for you now!

**Closed by dail8859** 2016-09-25 01:40 UTC
Labels: duplicate
