### ISSUE TITLE
Current language is neved selected

### ISSUE THREAD

**Issue by AleWin32** [notepad-plus-plus/notepad-plus-plus#1920] opened 2016-06-02 11:08 UTC
The current language is never selected in Language menu item (the check icon on the left side of the language name is never shown).

**Comment by dail8859** [comment] 2016-06-02 11:42
Please do not repost issues. There is PR #1677 that fixes it but has never been merged yet.

**Comment by dail8859** [comment] 2016-07-18 19:47
Duplicate of #1095

**Closed by dail8859** 2016-07-18 19:47 UTC
Labels: duplicate
