### ISSUE TITLE
Character U+21B2 ("↲")

### ISSUE THREAD

**Issue by gluehbirne** [notepad-plus-plus/notepad-plus-plus#675] opened 2015-08-07 15:00 UTC
Hello

When looking at a text file that contains nothing but the character U+21B2 ("↲"), only a rectangle is shown (looking like this "▯", as if the character was unknown). But for a text file that contains the two characters U+21B2 ("↲") and U+21BC ("▼") Notepad++ correctly shows an arrow and a triangle.

This is how strings are displayed:

| File Content | Expected Result | Displayed in Notepad++ |
| --- | --- | --- |
| "\u21B2" | "↲" | "▯" |
| "\u25BC\u21B2" | "▼↲" | "▼↲" |
| "\u21B2\u25BC" | "↲▼" | "↲▼" |
| "A\u21B2" | "A↲" | "A▯" |
| "\u25BCA\u21B2" | "▼A↲" | "▼A↲" |

I noticed that if I copy the rectangle and paste it (f.e. to this text area), I correctly see an arrow.

I am using Notepad++ v6.8.1 on Windows 8.1.

Bye

**Comment by donho** [comment] 2015-08-09 23:01
@gluehbirne Could you check this version:
https://notepad-plus-plus.org/repository/6.x/6.7.9.2/npp.6.7.9.2.bin.minimalist.7z

and confirm me that you can still reproduce this issue?

**Comment by gluehbirne** [comment] 2015-08-19 12:14
Hello

I have tested the version in the link and I am still experciencing this issue. I am on Windows 10 now.

I have noted one more thing: Notepad++ is not the only editor showing this behavior: [PSPad](http://www.pspad.com/) behaves exactly the same way. I have tested also Eclipse and the standard Windows text editor. They work fine (even when using Source Code Pro as font).

I have no idea what causes this problem. Therefore I can't say if this is really a Notepad++ problem. If this occurs generally on Windows and if there is an easy way of handling it, it would be nice if you could fix it. It is confusing and no one suspects the OS or the text editor at fault if they are confronted with this behavior (I have blamed the Java program that generated the text file for more than an hour before I figured out that typing/copying lead to the same result).

Bye

**Comment by chcg** [comment] 2015-09-13 18:00
Also happens with various other symbols,e.g.

⚘,  ⚑, ⛷, ⛸, ⛂, ⛇, ⚐, ⌛, ⌚
, but it is ok, if ○ is added:
○⚘, ⚑, ⛷, ⛸, ⛂, ⛇, ⚐, ⌛, ⌚

**Comment by ksmyth** [comment] 2017-11-15 20:19
Still an issue with 7.5.1. I ran into it with right triangle ▶, which is fixed by adding down triangle ▼

**Comment by chcg** [comment] 2018-01-10 22:58
Also with 7.5.4 for the edit part, but it is ok e.g in the search dialog field. Seems to be a scintilla.

**Comment by MetaChuh** [comment] 2019-05-01 22:41
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:41 UTC
Labels: bug
