### ISSUE TITLE
If you leave a delimiter off the end of a path, then Notepad++ will ask you if you want overwrite a directory. Notepad++ could easily append the missing delimiter

### ISSUE THREAD

**Issue by GalacticStarfish** [notepad-plus-plus/notepad-plus-plus#4520] opened 2018-05-24 20:39 UTC
### Description of the Issue

User often want `notepad++` to overwrite a `.txt`, or a `.dat` or a `.whatever`. However you pretty much never want to overwrite a directory with a text file open in `notepad++`. However, overwriting a directory is exactly what notepad++ will prompt you about if you forget a backslash at the end of a path (backslash, because using Windows).

for example, we might write:
`E:\dir\sub\sub_sub\waz_sup`

instead of:
`E:\dir\sub\sub_sub\waz_sup\`

I know that some text files do not have an extension at the end of their name. However, the operating system knows which files without extensions at the end of their name are directories and which are not directories.

As such, it would be pretty simple to introduce some code which looks something like the following:

```
is_dir = ask_the_os_if_path_is_dir(path)
if (is_dir):
    call this function with (path + "\") as input instead of path
```

### Steps to Reproduce the Issue

0.  Run MS Windows
1.  Open a new text file in `notepad++`
2.  type some garbage into the text file
3.  File > Save As
4. type in some sort of path, but omit the trailing delimiter (backslash) 
5.  Observe the prompt asking if you want to replace the directory

want to navigate to the directory, not overwrite it.

Can nav to directory if you append a backslash character at the end of the path

### Debug Information
```
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)  service pack 1
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
```

**Comment by sasumner** [comment] 2018-05-25 11:54
Note that this behavior (the overwrite prompting) only occurs if this setting is unticked:
Preferences -> Default Directory -> Use new style dialog...

Even though you get prompted, confirming the "replace" doesn't destroy anything...you find yourself changed to the desired directory and now the complete path to the directory (including a trailing backslash) is in the File name box (and it is selected so a keypress wipes it out).

But yeah, the prompt IS confusing.

@GalacticStarfish Suggest you change to "new style dialog" and never look back.  :)

**Comment by Laban1** [comment] 2018-10-17 19:58
I have the same request - the prompt is very confusing and when using Notepad++ on a very large number of machines, it gets quite tedious to change this setting on all of them + on all future installs.  Please fix!

**Comment by bersbersbers** [comment] 2019-08-22 07:48
The "new style dialog" has other drawbacks compared to the standard one: e.g., it does not automatically add a `.txt` file extension when saving new files. Should I report this as a separate bug?

Currently, I find myself torn between the "overwrite-directory" bug and the "missing-extension" bug, and I am unsure which one I hate least :)

**Comment by bersbersbers** [comment] 2019-08-22 07:53
Duplicate of #4926

**Comment by mere-human** [comment] 2021-02-22 21:32
In version 7.9.3 file dialogs have been upgraded so this problem isn't reproducible anymore.
@sasumner Could you, please, close this issue?

**Closed** 2021-02-22 21:56 UTC
