### ISSUE TITLE
Keyboard shortcuts no longer work on save dialog

### ISSUE THREAD

**Issue by hujhax** [notepad-plus-plus/notepad-plus-plus#7705] opened 2019-12-06 15:45 UTC
### Description of the Issue
Previous to the latest version, we could use the "Y" and "N" to activate the "Yes" and "No" buttons on the "Save" dialog.  Now that no longer works.

### Steps to Reproduce the Issue
1. Open a new file
2. Type some text into it
3. Close the new file
4. Type "N"

### Expected Behavior
I expect the "N" key to press the "No" button and dismiss the save dialog.

### Actual Behavior
Nothing happens.

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2019-12-06 15:58
Closing as duplicate of #6223 ; working in Notepad++ version 7.8.2

**Closed by sasumner** 2019-12-06 15:58 UTC
