### ISSUE TITLE
WORD HIGHLIGHT DOES NOT WORK RELIABLY IN CLONE VIEW (BUG)

### ISSUE THREAD

**Issue by RFImages** [notepad-plus-plus/notepad-plus-plus#12227] opened 2022-09-24 11:49 UTC
### Description of the Issue
When using clone view (Right click tab > Clone to other view), double clicking a word to select itin the original pane will highlight all occurrences  of that word in green as it should. It will also highlight the word in the cloned view as it should, BUT ONLY OCCURRENCES THAT ARE ON SCREEN in the cloned pane at the time of word selection. If the cloned view is then scrolled, any occurrences that were off screen at the time of word selection will NOT be highlighted. This makes the feature useless, dangerous and unreliable for comparing to a reference point in the original pane.

### Steps to Reproduce the Issue

1. Open a file with multiple occurrences of a word off screen. 
2. Clone to other view.
3. Double click the word to select it and highlight it in green. Occurrences that are on screen will highlight in green as well as all occurences that were off screen in the original view.
4. Scroll cloned view to find that occurrences in the cloned view that were off screen did not get highlighted.

### Expected Behavior
I expect all occurrences of a word that is highlighted (selected) in green to be highlighted all the time in both views, whether or not they are on screen.

### Actual Behavior
What actually happens is that occurrences that are off screen at the time of word selection will be shown to NOT be highlighted when scrolling the cloned view. In the screen shot below, it can be seen that occurrences of the signal 'rd' are highlighted in the cloned view (right pane ) on  line 359 and 361 which were on screen at the time of selection in the original left pane (see screen shot below). Occurrences of 'rd' on line 344 and 345 which were off screen at the time of selection are NOT highlighted in the cloned view.

![image](https://user-images.githubusercontent.com/18133626/192098368-7b774521-3a4f-4cef-9c42-75868c27ba45.png)

### Debug InformationNotepad++ v8.4.5   (32-bit)
Build time : Sep  3 2022 - 03:56:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.1)
    HexEditor (0.9.12)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment] 2022-09-24 12:37
Duplicate of #6176, possibly others...

**Closed** 2022-09-24 17:33 UTC

**Comment by RFImages** [comment] 2022-09-30 13:50
According to the noted post above, this is a duplicate of an issue that has been ignored since 2019 it appears.

**Comment by jofon** [comment] 2023-07-16 00:25
@RFImages 
Repeating my comment from #6176: Do you have Settings->Preferences->Highlighting->Smart Hightlighting->Highlight another view checked? This needs to be checked for the hightlight to work "correctly" on the cloned view. If it's not checked, then the clone only clones the highlights of the other view, and doesn't do it's own highlighting.

**Comment by RFImages** [comment] 2023-07-22 14:42
@jofon I did not. Thank you this seems to resolve the issue. However it should be checked as the default rather than something people have to start multiple posts in here for.
