### ISSUE TITLE
XML file type hang

### ISSUE THREAD

**Issue by pedrojs-sapo** [notepad-plus-plus/notepad-plus-plus#329] opened 2015-06-25 09:40 UTC
Hi guys

Having 4 or 5 XML files open (language set as XML) sometimes NPP hangs while naviganting between TABS.
The files are not big enough to hang npp and is only occurs if language for the file is set to XML.
It seems to be related to higlighting or something like that.
I have XML Plugin installed but woth all auto stuff unchecked.

Thanks

**Comment by jonandr** [comment] 2015-06-25 15:34
Please see if the problem remains even if you turn off all plugins (rename C:\Program Files (x86)\Notepad++\plugins to something else temporarily). The vast majority of issues like these are caused by plugins.

**Comment by BrainJelly** [comment] 2015-06-25 19:13
Do you have XML folded?
If so, this is a known issue. #236 
Issue #236 has been resolved in pull request. #168 

You can test this by unfolding all the XML in all the open files.
:smile:

**Comment by donho** [comment] 2015-10-04 10:46
Fixed: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f02e567c9eccade8b56d372b2865788e0651f8a2

**Closed by donho** 2015-10-04 10:46 UTC
Labels: bug
