### ISSUE TITLE
Plugins Admin: selecting more than one plugin to install at once does not work

### ISSUE THREAD

**Issue by Donnerknispel** [notepad-plus-plus/notepad-plus-plus#5477] opened 2019-04-02 08:37 UTC
### Description of the Issue
When selecting more than one plugin to install at once, the installation process does not work

### Steps to Reproduce the Issue
1. selecting more than one plugin to install
2. klicking install
3. the plugins are not installed

### Expected Behavior
plugins are beeing installed

### Actual Behavior
plugins are not beeing installed

### Debug Information
Notepad++ v7.6.5   (32-bit)
Build time : Mar 29 2019 - 02:46:18
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFavorites.dll NPPJSONViewer.dll NppTextFX.dll NppXmlTreeviewPlugin.dll

**Comment by MetaChuh** [comment] 2019-04-02 10:44
welcome to the notepad++ issue tracker, @Donnerknispel 
and thank you for your detailed and complete issue information. 👍

unfortunately (or fortunately) i can not reproduce any issues when multi-installing plugins, using plugins admin on a stable internet connection.

i've just tested this by installing all your current plugins at once, on a fresh and clean notepad++ 7.6.5. 32bit release. (see the real time screencast below)

![Imgur](https://i.imgur.com/OLBf7sD.gif)

here's the test machine's debug info after multi-installing all your plugins:

Notepad++ v7.6.5   (32-bit)
Build time : Mar 29 2019 - 02:46:18
Path : C:\Users\User\Desktop\npp.7.6.5.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : AnalysePlugin.dll ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NppFavorites.dll NPPJSONViewer.dll NppTextFX.dll NppXmlTreeviewPlugin.dll 

at the moment i can not really tell, whether your experience was caused by a coincidental dropout at your local internet connection, or it was triggered by a coincidental temporary outage of github, or any other location where one of the selected plugins is hosted.

ps: my apologies for currently not having a more satisfying answer for your experience.
best regards

-----

```
general notes:

please close your issue as soon as you are satisfied,
to help keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and first
search if a related topics exists. you are welcome to post at either an eventually similar
topic, or create a new topic at Help Wanted or General Discussion of your choice.

```
<kbd>https://notepad-plus-plus.org/community/</kbd>

**Comment by Donnerknispel** [comment] 2019-04-02 12:25
Thanx for the fast reply.
I have no idea why this does not work for me. Installing the individual plugins works. If I have selected more, then the message does not appear that the program is restarted after the installation.

Now I've tried to delete plugins via the administration. Unfortunately, this does not work, either for individual plugins, or for several plugins.

Since everything seems to work for you, is a propably something special in my environment.

best regards

**Comment by MetaChuh** [comment] 2019-04-02 13:14
@Donnerknispel 

thank you for your reply.

> Now I've tried to delete plugins via the administration. Unfortunately, this does not work, either for individual plugins, or for several plugins.

now this is really very strange, as removing plugins usually works and does not require an internet connection at all.

i have now tried to reproduce plugin multi install, and multi + single uninstall on windows 10 and 7, with all four notepad++ 7.6.5 releases, x64 and x86, portable and installed, and all versions work as expected.

could you please try to open notepad++ with right click > run as administrator, then retry removing one or more plugins ?
(this is the workaround, if there's a permission problem at one of the notepad++ folders)

if that does not work, next step would be to try a re-install of notepad++ on top of your existing notepad++.

**if that does not work either, maybe a complete clean install might help:**

* make sure you have saved all documents, closed notepad++, and you don't need any specific settings or customisations you have made at your notepad++ 32 bit.
* uninstall your existing notepad++ 32 bit.

* open `%ProgramFiles(x86)%` in windows explorer, and delete the folder  `Notepad++`, if it still exists.
* open `%ProgramFiles%` in windows explorer, and delete the folder  `Notepad++`, if it exists from a previous x64 version.
* open `%AppData%` in windows explorer, and delete the folder `Notepad++`, if it still exists.
* open `%LocalAppData%` in windows explorer, and delete the folder `Don_HO_don.h@free.fr`, if it exists from a very old notepad++ version.
* open `%ProgramData%` in windows explorer, and delete the folder `Notepad++`, if it exists.

* re-download the npp.7.6.5.Installer.exe from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.5/npp.7.6.5.Installer.exe) and install it.

**last hope note**: i also recall one user, that experienced a strange behaviour with various different 32 bit applications on one of his specific pc's.
he succeeded to get notepad++ to work on his specific configuration without reinstalling windows, by installing the 64 bit version instead of the 32 bit version (he didn't need any plugins that are only available for 32 bit).
so if you run out of options, and you want to try this out, you can uninstall and remove all notepad++ folders mentioned above, and install the x64 version from here:
https://notepad-plus-plus.org/repository/7.x/7.6.5/npp.7.6.5.Installer.x64.exe

i'm very curious, what could cause this on your system, as this issue is completely new.
please keep us updated if you are successful, or if you discover anything else, or if you have a theory what might be the culprit.

best regards

**Comment by MetaChuh** [comment] 2019-04-06 23:06
@Donnerknispel 

we are closing this issue, as we have not been able to reproduce this, and no similar issues were reported.

if you still experience that you can not install more than one plugin at a time on your pc, please visit us at the [<kbd>Notepad++ Community Forum</kbd>](https://notepad-plus-plus.org/community/) and post your issue to a wider range of devs and power users, to find the culprit on your specific machine.

best regards

**Closed by MetaChuh** 2019-04-06 23:06 UTC
