### ISSUE TITLE
Background color printed

### ISSUE THREAD

**Issue by Antonio-52** [notepad-plus-plus/notepad-plus-plus#12422] opened 2022-10-29 11:08 UTC
### Description of the Issue
NPP Configuration >Preferences >Print > Do not print background colors
NPP Configuration >Styles >Theme Black-board
Printing a text (not saved to a file) I have white text on dark background.

### Steps to Reproduce the Issue

1. NPP Configuration >Preferences >Print > Do not print background colors
2. NPP Configuration >Styles >Theme Black-board
3. NPP File >New
4. edit some text
5. NPP File >Print

### Expected Behavior

I expected to get the text printed on a blank backgroud (not the same dark background of NPP).
### Actual Behavior

The printed text was white on dark background (similar to the dark background of NPP).
### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : 
    BracketsCheck (1.2.2)
    CsvQuery (1.2.9)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    OpenSelection (1.1.3)
    SQLinFormNpp64 (5.3.35)
    urlPlugin (1.2)

printer: 
![NotepadPP_preferencesPrint](https://user-images.githubusercontent.com/46651541/198828038-67a634b2-4cf6-4fca-8166-6c1271b8a4ba.jpg)
![NotepadPP_styles](https://user-images.githubusercontent.com/46651541/198828042-4308e40b-2bb6-4c68-81f6-0ed16ba57018.jpg)

**Comment by alankilborn** [comment] 2022-10-29 11:14
Duplicate of other issue(s).
Please search for existing issues before bothering to create new one.
Will be fixed in 8.4.7.

**Closed** 2022-10-29 12:19 UTC
