### ISSUE TITLE
Brackets do not match.

### ISSUE THREAD

**Issue by MonstreCharmant** [notepad-plus-plus/notepad-plus-plus#1512] opened 2016-02-20 20:31 UTC
I'm using Notepad++v6.8.8 on Win10 pro
. When I used "Python" in "Language", I typed a sentence with two pairs of brackets, but the brackets generated automatically didn't match. Was that a bug or I used it in a wrong way?
Can't upload the picture...Here is the code. I input the first two brackets, the third one was generated automatically.
`x = int(input("what is x?\n")`

**Comment by codynguyen1116** [comment] 2016-02-20 20:34
The `int` function needs to be wrapped in an ending bracket, it should look like this:
```python
x = int(input("what is x?\n"))
```

**Comment by dail8859** [comment] 2016-02-20 21:07
@codynguyen1116 The issue means if you type out that code from the very beginning the auto-completion of the parenthesis is not correct. The problem is when you type the second `(` it assumes it doesn't need to auto-insert the closing parenthesis because a `)` is directly after it.

**Comment by codynguyen1116** [comment] 2016-02-20 21:10
@dail8859 Ah that makes sense, I apologize then! I misread the ticket, feel free to ignore me. :P

**Comment by MonstreCharmant** [comment] 2016-02-20 22:12
Thank you guys. So here comes the question, when I directly input two pairs of brackets, it just works well. But if I use int and input together, it occurs, missing a second bracket. Seems the auto-completion has a little problem?
`x = int(())
y = int(input()
z = int((input())`

**Closed** 2016-02-27 11:25 UTC
