### ISSUE TITLE
Can scroll horizontally to the right forever 

### ISSUE THREAD

**Issue by AXDOOMER** [notepad-plus-plus/notepad-plus-plus#1196] opened 2015-11-29 01:38 UTC
Just open a text file and press the right arrow to scroll the page to the right. You must have a line that's larger than your window. 

![untitled](https://cloud.githubusercontent.com/assets/6194072/11454913/e8eb3d98-960f-11e5-801d-359975b01ea1.jpg)

![untitled2](https://cloud.githubusercontent.com/assets/6194072/11454914/eb5f48da-960f-11e5-8807-dfcaba2f16cb.jpg)

**Comment by sanastasiou** [comment] 2015-11-29 03:16
Probably a scintilla bug...

**Comment by Rainald62** [comment] 2015-12-04 15:41
May be seen as a feature. Think of block-pasting a column past the end of the previously longest line.

**Comment by MetaChuh** [comment] 2019-04-13 02:16
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:16 UTC
