### ISSUE TITLE
Return to last spot

### ISSUE THREAD

**Issue by alubenfeld883** [notepad-plus-plus/notepad-plus-plus#10473] opened 2021-08-31 07:03 UTC
### Description of the Issue

Return to last spot.

### Steps to Reproduce the Issue

1. If the program is very long (as it would be in Cobol) you can accidentally press, say <CTRL>end and move to the end of the file.
2. Going back to where you were is quite a process.
3. 

### Expected Behavior

Some editors have something like <Shift>F5 to return to where you just left. I have not found any such quick key, nor can have I found anyone else you knows how to do this.

I know that you can set a marker, but it's a bit late when it happens, (Some of my programs cant get into the 10's of thousands of lines.)

If there is indeed a function to do this, I know a number of people who would love to know. :-)

**Comment by mere-human** [comment] 2021-08-31 14:34
There was a similar feature request on the community forum:
https://community.notepad-plus-plus.org/topic/21673/need-button-back-and-forward-for-placed-coursor-to-previous-position

**Comment by ArkadiuszMichalski** [comment] 2021-08-31 15:54
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1733, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8468, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4587.

**Closed by ArkadiuszMichalski** 2021-08-31 15:54 UTC
