### ISSUE TITLE
right-click menu, labels not traslated

### ISSUE THREAD

**Issue by conky77** [notepad-plus-plus/notepad-plus-plus#10980] opened 2022-01-02 14:49 UTC
### Description of the Issue
Right-click menu, labels not traslated 
* Style All occurences of Token
* Style one token
*  Clear Style

### Steps to Reproduce the Issue

1. open a document
2. right click
3. you see the labels not translated

### Expected Behavior
Fix the missing translations

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 

![image](https://user-images.githubusercontent.com/59116246/147878987-636eeabd-fafb-472a-8798-27230fba26b2.png)

**Comment by conky77** [comment] 2022-01-02 14:50
#8972

**Comment by ArkadiuszMichalski** [comment] 2022-01-03 16:12
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9713.

**Closed by ArkadiuszMichalski** 2022-01-03 16:12 UTC
