### ISSUE TITLE
UDL + Fold by indent

### ISSUE THREAD

**Issue by MateuszZarkowski** [notepad-plus-plus/notepad-plus-plus#1610] opened 2016-03-09 20:51 UTC
Hey! Great work on NPP!

The issue is coming with UDL + Fold by indent plugin.
I specify my own language and use  { } as separators.
When writing  if - else statement and trying indent I get:
(the result on the right)

![asd](https://cloud.githubusercontent.com/assets/8105383/13650008/e664f466-e640-11e5-8f5c-c7eaa49e2a3b.PNG)

I'm guessing the problem is multiple separators on the same line.
Is there a way to fix this?

**Comment by MateuszZarkowski** [comment] 2016-03-11 00:41
Well, I fixed it in the plugin in pull request:
https://github.com/ffes/indentbyfold/pull/4

Keep up the good work :)

**Comment by MetaChuh** [comment] 2019-04-13 02:34
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:34 UTC
