### ISSUE TITLE
File change detection does not work if shown in "other" pane

### ISSUE THREAD

**Issue by RobPearce** [notepad-plus-plus/notepad-plus-plus#8861] opened 2020-09-15 16:47 UTC
There was a change a few versions back to reduce the slew of nag boxes when several files had been updated in the background (e.g. committed to a VCS that updates keywords). Since then, the file changed "do you want to reload" dialogue doesn't always appear when it should.

The specific sequence I have identified is:
1. Open a few files and split the view, with different files left and right
2. Put the active cursor in one of the panes, let's say left for argument's sake
3. Using a different program (so NP++ loses focus) change the file in the other (e.g. right-hand) view
4. Return to NP++, on the left file. No notification appears
5. Click in the other (right) pane.

At this point, the file changed notification should have appeared, because the visible and now in focus file has changed.
It doesn't. Instead, it's necessary to de-focus NP++ (e.g. ALT-TAB) and then re-focus it to get the change.
This also applies to detection of changed status, such as clearing a read-only flag

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Enterprise (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

I also see the same issue on a Windows 10 box with, I think, the 64-bit version

**Comment by sasumner** [comment] 2020-09-15 17:12
Closing as duplicate of #7581
If you have further information, please comment in that issue.

**Closed by sasumner** 2020-09-15 17:12 UTC
