### ISSUE TITLE
'Find in Files' return blank results when the keyword lines start with NULL

### ISSUE THREAD

**Issue by abagoforgans** [notepad-plus-plus/notepad-plus-plus#8986] opened 2020-10-10 03:32 UTC
### Description of the Issue
If the lines where the keyword is starts with NULL \x00, then the lines will not be shown

### Steps to Reproduce the Issue
1. Open a file containing lines starts with NULL \x00, eg.   <NUL>AAAAAA
2. Open 'Find in Files', and search for 'AAA' in the file's directory
3. Return blank results

### Expected Behavior
The results should be shown as same as the original code

### Actual Behavior
![image](https://user-images.githubusercontent.com/11257140/95644854-18d36980-0aec-11eb-95f8-bc7d377a7045.png)
![image](https://user-images.githubusercontent.com/11257140/95644864-3ef90980-0aec-11eb-95d9-4b1eacf696fa.png)

**Comment by sasumner** [comment] 2020-10-10 10:56
Closing as duplicate of #6281 

In general, though, Notepad++ is a _text_ editor, and .exe files are not text files.
Perhaps there are better choices for this type of searching.

**Closed by sasumner** 2020-10-10 10:56 UTC

**Comment by sasumner** [comment] 2020-10-11 12:56
@abagoforgans 

Why did you delete the content and change the title?
Because I can still see the original title, I have restored it.
I can't, however, restore the bulk of the content that you deleted.

Even though it is a duplicate and was closed, retaining your data gives more "weight" to the problem so that it can be looked at sooner (if developers know that multiple users are experiencing the same problem, it gets more attention).

Because I mentioned "6281" in my closing comment, that creates an automatic link from 6281 to here, so that your exact problem can be referenced by someone working on 6281.
