### ISSUE TITLE
MINIBUG – search in all navigation cannot navigate to “new 1”

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [notepad-plus-plus/notepad-plus-plus#7914] opened 2020-02-03 10:13 UTC
### Description of the Issue
When one want to navigate from find in all documents results to “_new 1_” file, it does not work.

### Steps to Reproduce the Issue
1. Open some existing text file with text.
2. Copy some portion of text.
3. Create 2 new tabs (files) (Ctrl + N) and paste there that text.
4. Switch to step 1 file.
5. Ctrl + F and use _Find All in All Opened Documents_ with pasted text.
6. Try navigate from search results.

### Expected Behavior
It can be navigated to both new tab/files.

### Actual Behavior
Only to second tab (“_new 2_”) can be navigated.

### Debug Information
Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.592
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2020-02-03 14:46
Works as expected for me:

Notepad++ v7.8.4   (64-bit)
Build time : Jan 29 2020 - 01:31:03
Path : C:\...........\npp.7.8.4.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1565
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

Closing for now, pending any future evidence provided.

**Comment by JiriCepelkaFirstLineSoftware** [comment] 2020-02-03 14:57
I have to disagree. See [video](http://software919.cz/__other/TEST%20-%20Notepad++%202020-02-03%2015-52-17.mp4).

For me it is important to start NPP with opened file from last session. When it is started with empty file it works as expected.

**Comment by sasumner** [comment] 2020-02-03 15:05
>pending any future evidence provided

>it is important to start NPP with opened file from last session

and there it is!  With that additional info I can now reproduce it.

**Comment by donho** [comment] 2020-03-23 18:39
The source of bug is in `BufferID FileManager::getBufferFromName(const TCHAR* name)`.
While searching `new 1`, there are at least 4 `new 1` in `_buffers`, and this function return the 1st one it found. I have no solution for this problem so far.

**Comment by donho** [comment] 2020-03-24 03:40
I tried to use BufferID instead of filename in FindInfo to fix this bug. 
But in this case there will create a huge regression that won't open the result of Find in file.
This bug is created due to a flaw of design, but since it's minor, I won't fix it.

**Closed by donho** 2020-03-24 03:40 UTC
Labels: verified
