### ISSUE TITLE
Creating a new file does not automatically enable syntax highlighting

### ISSUE THREAD

**Issue by hoff121324** [notepad-plus-plus/notepad-plus-plus#931] opened 2015-09-17 20:58 UTC
I have a batch file called np.bat with the following contents:
```
start "" "C:\Program Files (x86)\Notepad++\notepad++.exe" %*
```
This allows me to enter the following on the command line (assuming the file does not exist)
```
np newfile.java
```
I am then given a message telling me the file does not exist and asking if I would like to create it.  The file is created without a problem, but syntax highlighting is not enabled.  I need to close and reopen the file in order for my code to be highlighted (imports are blue, public class is purple, etc).

As a slightly related note, if I have a file called NewFile.java and I run
```
np newfile.java
```
Then the lowercase text is displayed on the tab instead of the correct upper case version

**Comment by Porkenstein** [comment] 2016-04-19 09:40
I've noticed this as well.  It's terribly annoying.

**Comment by xylographe** [comment] 2016-04-19 12:03
Duplicate of #752

**Comment by dail8859** [comment] 2016-06-23 01:28
Duplicate.

**Closed by dail8859** 2016-06-23 01:28 UTC
Labels: duplicate
