### ISSUE TITLE
Undo after Replace All in All Opened Documents will result in exception

### ISSUE THREAD

**Issue by UnPrioritized** [notepad-plus-plus/notepad-plus-plus#12381] opened 2022-10-23 05:34 UTC
### Description of the Issue
Undo after Replace All in All Opened Documents will result in exception.

### Steps to Reproduce the Issue
1. Open any documents
2. Drag and drop other documents without viewing them
3. Replace All in All Opened Documents
4. This will result in Change History not being displayed but file has been changed
5. Hit undo will crash

### Expected Behavior
Change History showing that line been modified and be able to do undo just fine without exception.

### Actual Behavior
Notepad++ crashed with an error message.

Win32Exception
An exception occured. Notepad++ cannot recover and must be shut down.
The exception details are as follows:
Code:	0xC0000005
Type:	Access violation
Exception address: 0x00007FF7194D1A60

Demonstration Video
https://b.catgirlsare.sexy/lQwURXNG-0h1.avi

This won't result in exception if you disabled "Display Change History".

### Debug Information
Notepad++ v8.4.6   (64-bit)
Build time : Sep 25 2022 - 19:51:39
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 21H2
OS Build : 19044.1766
Current ANSI codepage : 932
Plugins : 
    ComparePlugin (2.0.2)
    HexEditor (0.9.12)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    RegexTrainer (1)

Dump file
https://b.catgirlsare.sexy/A1iHgYat0qrq.dmp

**Comment by alankilborn** [comment] 2022-10-24 19:11
I can reproduce this.

Add this step, though, to be executed between original step 4 and 5:

4a. Switch to a tab that has a replacement, but hasn't been made active yet during this run of N++

![image](https://user-images.githubusercontent.com/77065706/197606439-c0e0df59-ede4-4e35-b9e5-e2de8bfc1212.png)

**Comment by Yaron10** [comment] 2022-10-24 21:15
@alankilborn,

Could you please list the exact STR?

I haven't been able to reproduce the crash.

**STR:**
Open 3 files _by Drag&Drop_.
Do not switch tabs.
Replace all.
Switch to the tab before current.

**Result:**
Undo is enabled.
Pressing Undo has no effect.
No Changed History.

**Comment by alankilborn** [comment] 2022-10-24 21:34
@Yaron10 

I couldn't repro the crash with the exact STR, so I modified it with my `4a` to get the same exception details crash.

**Comment by Yaron10** [comment] 2022-10-24 22:09
@alankilborn,

I meant *your* exact STR. :)
How many files do you open? How do you open them?

**Comment by alankilborn** [comment] 2022-10-25 11:43
@Yaron10

My STR:

1) Start fresh N++ portable; contains 1 doc `new 1`
2) Add `t` to doc
3) Ctrl+n to make a new doc `new 2`
4) Add `t` to this doc
5) Repeat steps 3 and 4 enough times to obtain and modify `new 6`
5) Leaving `new 1` as the active doc, restart N++
6) After restart (`new 1` is still the active doc), do a _Replace All in All Opened Documents_ for `t` with `T`
7) Switch active tab to `new 6`
8) Press Ctrl+z (undo)

**Comment by Yaron10** [comment] 2022-10-25 15:14
@alankilborn,

Thank you for the detailed STR.

This is weird. - I still can not reproduce the crash.
There's certainly a problem (pressing Undo has no effect, no Changed History), but no crash.

**Comment by alankilborn** [comment] 2022-10-25 15:21
> I still can not reproduce the crash.

Maybe try dozens of `new X` tabs?

**Comment by ArkadiuszMichalski** [comment] 2022-10-28 12:30
STR:
1. Open Notepad++.
2. Open `change.log license.txt readme.txt` files via select them and drag and drop (or open it separately and run Notepad++ again, files will be loaded from the session).
3.  Press `Ctrl+H` and change something (for example `a` to `b`) for all opened files.
4. Jump over the tabs and make undo (Ctrl+Z).

![image](https://user-images.githubusercontent.com/2730894/198586814-50ff6719-e482-4df4-aa6f-bb43c987e747.png)

**Comment by donho** [comment] 2023-01-29 18:49
I cannot reproduce the crash with [v8.4.9 RC](https://community.notepad-plus-plus.org/topic/24066/notepad-v8-4-9-release-candidate-2), even use the scenario provided by @ArkadiuszMichalski.

I do believe the crash bug has been fixed in v8.4.7 or  v8.4.8 - in both releases Scintilla has been upgraded to 5.3.1 & 5.3.2 respectively.

**Closed by donho** 2023-01-29 18:49 UTC
Labels: not reproducible, crash
