### ISSUE TITLE
Formatting lost when line to long

### ISSUE THREAD

**Issue by tvanees-ohpen-com** [notepad-plus-plus/notepad-plus-plus#11980] opened 2022-08-05 07:14 UTC
Version 8.4.4 (64 bit) on Windows 10 pro
Use json viewer plugin. When I have the plugin format the json file, All json keys turn orange except 1. That one is black. This key is very long and when I shorten it to less than 100 chars, it turns orange.

![image](https://user-images.githubusercontent.com/96059237/183022867-0e8b0ff2-8364-49fe-ba29-dcefa79243a3.png)

**Comment by tvanees-ohpen-com** [comment] 2022-08-05 07:14
I think the black one should also be orange

**Comment by tvanees-ohpen-com** [comment] 2022-08-05 07:15
First I thought it was an issue related to the json VIEWER plugin, but that seems not to be the case.

**Comment by ArkadiuszMichalski** [comment] 2022-08-05 11:34
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7938.

**Closed by ArkadiuszMichalski** 2022-08-05 11:34 UTC
