### ISSUE TITLE
The Read Only icon is not distinguishable when a tab becomes inactive.

### ISSUE THREAD

**Issue by dyura** [notepad-plus-plus/notepad-plus-plus#5666] opened 2019-05-17 19:21 UTC
NPP uses one of 3 icons inside the tabs. All 3 have the same drawing but different colors: red for unsaved buffer, blue for a saved buffer, and grey for read-only.   When a buffer is  inactive the icon is dim. It is almost impossible to distinguish between dim blue and grey icons. I just would suggest using another drawing for Read-Only. For example, I re-compiled  using readonly.ico.old from Notepad++ repository, and the visibility in my version is perfect now.  readonly.ico.old  is already in the repository

**Comment by SinghRajenM** [comment] 2019-07-05 20:33
Duplicate of #4492 and #3170. A try was given at https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5097.

An another try here https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5890

**Comment by dyura** [comment] 2019-07-15 03:58
Thanks for the links to these duplicates. I see that at least four more people pointed to this bug. However, this bug still exists, and we still cannot distinguish inactive tabs as read-only. I understand that this is not a critical bug, but it is VERY EASY to correct.
What is the problem? All 3 icons, read-only, saved, and unsaved, have the same style, but different colors. Practically the difference between gray and blue, when the icon is darkened, is not noticeable . My suggestion is to change the read-only icon, while preserving the accepted style as much as possible. Let's make the upper right corner black. You can see my attached example of this icon.
![readonly ](https://user-images.githubusercontent.com/39743460/61194890-ab3f5000-a692-11e9-8875-14d0ba6ea7bb.png)
 My graphic design skills are bad. But even with my bad skills, I believe that the current icon style symbolizes a floppy disk. Let's think that the black corner symbolizes a write-protected floppy disk. Look at the screenshot when I used this icon. As for me, the style is almost the same, but the black spot in the upper corner allows us to perfectly distinguish read-only tabs.
![unnamed](https://user-images.githubusercontent.com/39743460/61194894-b1cdc780-a692-11e9-9908-d14cb0d05684.png)

**Comment by dyura** [comment] 2020-01-08 19:08
My previous post was not answered. After my post, I noticed  that  there was another pull request, [#5890](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5890 ) , intending to change the read only icon. This request was rejected with a comment: “The colour looks weird.”
Previously, there was one pull request related to the visibility of the read-only icon, https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5097  , that was rejected with a reason: “It's very clear about the indication. However the style of icon has changed completely - which doesn't go with the others at all. Hence this PR is not accepted.”.
Thus, it is still  impossible to visually distinguish between “read-only” and “saved” icons in inactive tabs without using “Doc switcher” as a ridiculous workaround. The read-only icon can only be identified in the active buffer. But, for read-only indication exclusively in the active buffer, we don’t need any advanced design with icons in the tab bar. A simple letter “R” in the status bar will be quite enough. Thus, we have an absurd situation, when the feature was developed, but it cannot be used properly only because the icon, which can be a graphical masterpiece, cannot achieve the desired goal. 
I will not discuss which is more important: graphical style or functionality. I just once again looked at this problem. There are three icons: blue, red and gray. But, why is read-only.ico gray? Black color is much more contrast. So, I carefully changed the color of read-only.ico to make it darker, completely preserving the style as I believe. Now I use this icon in my binary copies, and I don’t have problems to distinguish, and also I don’t see problems with the style consistency.  I attached two screenshots: with a standard icon and with a darker icon. I also attached an updated read-only.ico.
I can create a pull request if necessary.
![readonly_darker](https://user-images.githubusercontent.com/39743460/72007455-b6c59b00-321f-11ea-9312-1767fc39f931.png)
![Screenshot from 2020-01-04 12-31-55](https://user-images.githubusercontent.com/39743460/72007456-b6c59b00-321f-11ea-85ef-738a4962f50c.png)
![Screenshot from 2020-01-04 12-32-51](https://user-images.githubusercontent.com/39743460/72007457-b6c59b00-321f-11ea-8cd0-3d67fd06a8b3.png)

**Comment by sasumner** [comment] 2020-09-30 17:44
Choose the `Alternate icons` for the tab-bar, in the _Preferences_ :

![image](https://user-images.githubusercontent.com/30118311/94720882-06567480-0323-11eb-995f-b3a9f2ee441a.png)

Closing.

**Closed by sasumner** 2020-09-30 17:44 UTC
