### ISSUE TITLE
[Feature Request]: Copy only bookmarked words matched in a regex

### ISSUE THREAD

**Issue by jhonatan4878** [notepad-plus-plus/notepad-plus-plus#1246] opened 2015-12-14 13:25 UTC
I'm an user of regular expressions on Notepad++. In my codes, sometimes, I need to get the name of all words in a group matched in the regex to export somewhere. 

For example: I want to copy the name of all variables that start with the prefix "WRK", using the regex "(WRK[\w-]+)" and I want to copy only the bookmarked words (in grey) in other tab. Currently I need to copy the entire line found with the bookmark and edit in other file with find&replace.

![case](https://cloud.githubusercontent.com/assets/8593768/11781353/6d138c64-a250-11e5-9d58-b17d93de803a.png)

So, the feature I'd like on Notepad++ is: Allowing copy only the bookmarked words in the same way I copy the bookmarked lines. In the case of the picture, 54 matches and I want to copy these 54 matched words with or without repetition when (for instance) I click on the right click on the word bookmarked.

Thanks
%JH%

**Comment by cmeriaux** [comment] 2015-12-14 16:51
Hello,
you may consider using the "PythonScript Plugin " 
You'll be able to do a regexp search on the text, then get all your result and process it as you want

**Comment by cmeriaux** [comment] 2015-12-18 09:53
Hello,
Some people wrote a python script that uses "PythonScript Plugin "  to select everythings they wants.
Here is the script : https://sourceforge.net/p/npppythonscript/discussion/1199074/thread/cfa88e16/

```python
matches = []

def refound(m):
    global matches
    # append the match (start, end) positions to the matches array
    matches.append(m.span(0))

regex = notepad.prompt('Search for:', 'Select all results')
if regex:
    editor.setMultipleSelection(True)
    lines = editor.getUserLineSelection()
    editor.research(regex, refound, 0, editor.positionFromLine(lines[0]), editor.positionFromLine(lines[1]))
    first = True
    for (match_start_pos, match_end_pos) in matches:
        if first:
            first = False
            editor.setSelection(match_start_pos, match_end_pos)
        else:
            editor.addSelection(match_start_pos, match_end_pos)
```
then do a copy of selected elements :

```python
editor.copy()
```

**Comment by MetaChuh** [comment] 2019-04-11 00:37
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:37 UTC
