### ISSUE TITLE
Proposal for VS project files

### ISSUE THREAD

**Issue by Rikk** [notepad-plus-plus/notepad-plus-plus#648] opened 2015-08-05 08:40 UTC
I was wondering what you guys think about these changes in VS project files:
1. Removal of "Unicode" part of configuration names in VS project files. Reason: we only support Unicode, and there are clear tags `<CharacterSet>Unicode</CharacterSet>` below them.
2. Set `GenerateDebugInformation` to `false` for releases (Release|Win32 and Release|x64). Reason: what other program includes debug things in production-ready releases?
3. Set `ProgramDatabaseFile` of Debug versions to `$(OutDir)notepad++.pdb` instead of `$(OutDir)notepadPlus.pdb`, so it matches main executable name. Question: Any reason we use that name?
4. Set "nppNewIcon.ico" as default icon, so we don't need to call "vistaIconTool\ChangeIcon" hack every time, but only when user wants the old icon during installer. Question: Any reason we need the old icon? (looks odd, imo)
5. Remove `<Version>1.0</Version>`. Question: Any use for that optional tag?

With a green flag I can work on a PR.

**Comment by ariccio** [comment] 2015-08-05 21:07
> Removal of "Unicode" part of configuration names in VS project files. 

+1

> Set GenerateDebugInformation to false for releases

Please don't. Debug information is always helpful. There's minimal cost here - so at least provide numbers to convince/back this up.

> what other program includes debug things in production-ready releases?
Set ProgramDatabaseFile of Debug versions to `$(OutDir)notepad++.exe` instead of `$(OutDir)notepadPlus.pdb`, so it matches main executable name. Question: Any reason we use that name?

I think you mean `notepad++.pdb`, else we'd overwrite the binary!

**Comment by Rikk** [comment] 2015-08-05 21:14
Thanks, fixed the .pbd (was a copy-paste typo).
About Debug thing, really I don't know what is being included, in reality my binary sized increased by aprox. 1kb when I **disabled** it (sic).

**Comment by ariccio** [comment] 2015-08-05 22:31
lfmao..... try something like [radiff2](https://github.com/radare/radare2/wiki/Radiff2) or [KDiff3](http://kdiff3.sourceforge.net/)?

**Comment by Rikk** [comment] 2015-08-06 03:25
I guess it's better just post Issues and Pulls, because who cares at all?

None of the devs do commits to their own repositories before publishing to main project, instead just pushes bugs and flaws.

Goodbye this issue.

**Comment by milipili** [comment] 2015-08-06 08:18
This ticket is reopened because there are good ideas and should be implemented with cmake.

**Comment by Rikk** [comment] 2015-08-06 22:14
Thanks for at least one line of feedback.
Anyway I'm thinking/testing more proposals.
And finding a way to fix building Scilexer for x64 and with boost in vc++14.

**Comment by ariccio** [comment] 2015-08-07 00:23
> And finding a way to fix building Scilexer for x64 and with boost in vc++14.

There's a problem with boost?

**Comment by Rikk** [comment] 2015-08-07 01:11
oh forgot to edit... I mean with the one from nuget
btw, do you know if only the .lib file from boost_regex is needed, or we need also the boost package?

**Comment by ariccio** [comment] 2015-08-07 02:52
Short answer: No. 

I do, *however*, know that boost has become *much* more modular over the past year, and thus generally easier to use.

**Comment by MetaChuh** [comment] 2019-04-11 00:11
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:11 UTC
Labels: build / code, enhancement
