### ISSUE TITLE
Unicode Characters & Font Fallback Support

### ISSUE THREAD

**Issue by AceFrahm** [notepad-plus-plus/notepad-plus-plus#870] opened 2015-09-07 20:14 UTC
Some weirdness with viewing Unicode glyphs, even on a machine with fallback fonts.  

A font with full fallback for every Unicode code point still won't show anything but a square for some things.

Try pasting this into Notepad++

---

Interobangs on one line:‽‽
Upper unicode characters (16 or 32-bits? not just 8-bit from the Basic Multilingual Plane) on a separate line: [  🔊, 🎥, 📕 ]
Interobangs followed by some upper Unicode characters on the same line:  ‽‽ , [ 🔊, 🎥, 📕 ]

arrows on the same line : ↑↓↙↘. 

arrows on 2 lines : ↑↓
↙↘. 

---

Now, a user should have some fallback fonts setup, as described here with "Font Linking" (which is different than straight-up 'fallback font'), it uses GDI
[https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx]

HKEY_LOCAL_MACHINE\SOFTWARE\Micrrosoft\Windows NT\CurrentVersion\FontLink\SystemLink

Here is a list of "Font Linked" fonts I'm using with Arial Unicode MS under that registry setting.
unifont_csur-7.0.06.ttf, Unifont CSUR
unifont_upper_csur-7.0.06.ttf, Unifont Upper CSUR
Constructium.ttf, Constructium
Nuvenon.ttf, Nuvenon
LastResort.ttf, LastResort
UnicodeBMPFallback.ttf, Unicode BMP Fallback SIL

This Font Linked list ought to cover every single Unicode code point with SOME glyph, but it seems Notepad++ can't handle Unicode well or doesn't take advantage of GDI ?  

the problem is also described here:
[http://stackoverflow.com/questions/20749958/unicode-characters-messed-up-after-linebreak]

!‽???‽!!! , 🔊, 🎥, 📕

**Comment by h-h-h-h** [comment] 2015-09-08 14:13
Related issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/813

**Comment by Kemipso** [comment] 2018-05-02 15:05
Following your example (but with different fonts for my own needs) worked fine, and I could not reproduce the issue on Notepad++.

Here is how it looks on my end:
![2018-05-02 - 001055](https://user-images.githubusercontent.com/2519325/39531176-e95cab24-4e2a-11e8-9ebc-c6f307893ca7.png)

And here is my setup, based on Inconsolata/Consolas for most common characters, and a bunch of weird fonts for other symbols.

**Path:**
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`

**New multi-string, with value name:**
`Inconsolata`

**Value data:** 
```
CONSOLA.TTF,Consolas Regular
SEGOEUISL.TTF,Segoe UI Semilight
MSJH.TTC,Microsoft Jhenghei UI
MSYH.TTC,Microsoft YaHei
MALGUNSL.TTF,Malgun Gothic Semilight
SEGUISYM.TTF,Segoe UI Symbol

```

**Comment by MetaChuh** [comment] 2019-04-09 23:39
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:39 UTC

**Comment by IzzySoft** [comment] 2019-07-23 15:19
Problem seems still to exist in 7.7.1 (just tested with the portable version which unfortunately is only 32bit; as your download site curently cannot be reached, I cannot check with the "official" 64bit version). Related issue: #3747
