### ISSUE TITLE
bug report: opened file while other files not refreshed looses focus 

### ISSUE THREAD

**Issue by adellarovere** [notepad-plus-plus/notepad-plus-plus#4914] opened 2018-10-11 09:57 UTC
### Description of the Issue

Hi, i noticed an annoying behavior of notepad++
If you have several tabs open with files which are not yet refreshed (say *.map file which is modified by the compiler for example...) and you just want to open another file, notepad++ asks you to refresh the file and switches tab to this file. The file which you were interested in is opened in a tab, but not brought in foreground. This can be annoying if you have several tabs opened, as you have to search for your file in the windows list...

### Steps to Reproduce the Issue

1. have several tabs open
2. modify one of those files by other editor
3. open another file for editing

### Expected Behavior

opened file should be always brought on the foreground.
### Actual Behavior

the refreshed file is brought on the foreground.

**Comment by GoverLabs** [comment] 2018-10-12 11:09
You can change that in preferences -> "File status Auto-Detection"
![image](https://user-images.githubusercontent.com/37362815/46866001-4f584a00-ce28-11e8-8ccf-bdad02bab21f.png)

**Comment by 42degrees** [comment] 2018-10-12 19:51
Duplicate of issue [4189](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4189)

**Comment by ArkadiuszMichalski** [comment] 2020-09-20 20:05
@donho @sasumner This probably was fix in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5389.

**Closed** 2020-09-21 10:58 UTC

**Comment by weibostone** [comment] 2020-09-21 11:04
---Original---
