### ISSUE TITLE
Resizing two-view mode gets stuck if you resize search view near intersection

### ISSUE THREAD

**Issue by kutluguzhin-g-soft** [notepad-plus-plus/notepad-plus-plus#2097] opened 2016-07-18 12:21 UTC
Title says it all: if you have two-view mode and search view and try to resize search view and grab it at exact intersection of two views resizing for views gets stuck and follows your mouse when you are nearby.

**Comment by andrewlvaldez** [comment] 2017-09-12 21:27
I believe this might be a duplicate of issue #680.

**Comment by MetaChuh** [comment] 2019-05-01 22:04
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:04 UTC
