### ISSUE TITLE
Make Plugins Admin dialog resizable.

### ISSUE THREAD

**Issue by garydgregory** [notepad-plus-plus/notepad-plus-plus#7810] opened 2020-01-03 13:35 UTC
Please make the Plugins Admin dialog resizable.

```
Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll 

```

**Comment by xylographe** [comment] 2020-01-03 18:16
PR #5785

**Comment by andrecool-68** [comment] 2020-01-03 18:17
How many such requests have already been ... but for some reason the author does not want such changes)))

**Comment by sasumner** [comment] 2020-01-03 21:07
> but for some reason the author does not want such changes

There are often deeper reasons...

**Comment by ArkadiuszMichalski** [comment] 2020-10-06 22:15
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5680..

**Comment by sasumner** [comment] 2020-10-07 00:36
Closing as duplicate

**Closed by sasumner** 2020-10-07 00:36 UTC
