### ISSUE TITLE
Show NUL in textdocument

### ISSUE THREAD

**Issue by KL7000F** [notepad-plus-plus/notepad-plus-plus#12305] opened 2022-10-08 16:11 UTC
In the current version, Notepad++ always shows me NUL. It was not before. I assume this is a bug.
Version 8.4.5

![image](https://user-images.githubusercontent.com/16374462/194716917-d9e2c345-2b5d-4f9f-8460-3470853a0079.png)

**Comment by alankilborn** [comment] 2022-10-09 11:16
Check for a `nppLogNulContentCorruptionIssue.xml` file on your system; if you have one and it is not zero length, please attach it to this issue.

**Comment by KL7000F** [comment] 2022-10-09 11:21
This file is emty.

**Comment by ArkadiuszMichalski** [comment] 2022-10-09 12:38
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6133.

**Comment by alankilborn** [comment] 2022-10-09 12:43
@ArkadiuszMichalski I don't know...closing this probably doesn't get any new attention on a critical old problem, that likely seems still happening on a very recent release, despite "recent" fix attempts.  Of course, maybe it isn't the exact same problem, but it appears to be a serious data corruption issue.

**Comment by KL7000F** [comment] 2022-10-09 14:44
Can i help or testing anything to solve the problem?

**Comment by ArkadiuszMichalski** [comment] 2022-10-09 14:59
@KL7000F If you can find steps on how to reproduce this bug, it would certainly help to fix it.

**Comment by KL7000F** [comment] 2022-10-09 15:42
Basically, I didn't actively do anything. The files have existed for many years. In Editor / Wordpad the files show some "Space" (see screenshot).
I can't say for sure, but I think it was after resetting a Windows restore point. Win11 Upgrade 22H2 back to 21H2. A connection?

![image](https://user-images.githubusercontent.com/16374462/194765829-0bee4c2e-9b50-435a-b9d6-7d730b3997c5.png)

Debug Info:

Notepad++ v8.4.5   (64-bit)
Build time : Sep  3 2022 - 04:05:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\kl7000f\Desktop\testfile.txt"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.1042
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

[testfile.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9741925/testfile.txt)

**Comment by xomx** [comment] 2022-10-09 20:04
@KL7000F 

> In the current version, Notepad++ always shows me NUL. It was not before.

Did you try to get back to your previous N++ version and reproduce the same problem?

> Basically, I didn't actively do anything. The files have existed for many years. In Editor / Wordpad the files show some "Space" (see screenshot).
> I can't say for sure, but I think it was after resetting a Windows restore point. Win11 Upgrade 22H2 back to 21H2. A connection?

Do I understand it right that after some system restore operation your files suddenly have got NULs inside? If so, this has nothing to do with the Notepad++. Simply saying - the system restore corrupted these files and the N++ then just showing you that there is a problem in your file (the spaces in the Wordpad is its graphical representation of these NUL-bytes). 

Or did you have some files opened in Notepad++ and there was a problem (crash/forced system reboot/etc...) and when you tried to reopen them later, these files have been corrupted with the NUL-bytes?


> Check for a nppLogNulContentCorruptionIssue.xml file on your system;

The file in question is "nppLogNulContentCorruptionIssue.log" and for the installed N++ it should reside in the 
current logged user %APPDATA%\Notepad++\ directory, e.g. in:
C:\Users\login-name\AppData\Roaming\Notepad++\


@ArkadiuszMichalski 

Maybe I am on track to fix the long standing problem with the emptied session.xml file after forced Windows restart/shutdown. If I am right it has nothing to do with the NUL-bytes corruptions reported.

**Comment by KL7000F** [comment] 2022-10-10 07:03
> Did you try to get back to your previous N++ version and reproduce the same problem?

I also tested it on my work PC. Also there NUL with this file. Other versions (v8.4) also show this error.

> Do I understand it right that after some system restore operation your files suddenly have got NULs inside? If so, this has nothing to do with the Notepad++. Simply saying - the system restore corrupted these files and the N++ then just showing you that there is a problem in your file (the spaces in the Wordpad is its graphical representation of these NUL-bytes).

Right. But I also remember that months ago I had a problem with the NAS. The file system there was corrupt and I had to restore the data using a rescue tool. I think that will be the cause of the broken files!(?). Speak no error in Notepad++.

> Or did you have some files opened in Notepad++ and there was a problem (crash/forced system reboot/etc...) and when you tried to reopen them later, these files have been corrupted with the NUL-bytes?

No.

> The file in question is "nppLogNulContentCorruptionIssue.log" and for the installed N++ it should reside in the current logged user %APPDATA%\Notepad++\ directory, e.g. in: C:\Users\login-name\AppData\Roaming\Notepad++\

`2022-09-29 11:49:04  WM_QUERYENDSESSION =====================================
2022-09-29 11:49:04  C:\Users\user1\AppData\Roaming\Notepad++\config.xml is opened.
2022-09-29 11:49:04  C:\Users\user1\AppData\Roaming\Notepad++\config.xml  8972/8972 bytes are written.
2022-09-29 11:49:04  C:\Users\user1\AppData\Roaming\Notepad++\config.xml is closed.
2022-09-29 11:49:04  WM_ENDSESSION
2022-09-29 11:49:04  WM_DESTROY
`

**Comment by pnedev** [comment] 2022-10-10 08:14
I second what @xomx has written.
The problem seems to be more related to file system corruption and not to the Notepad++ NUL issue of the old days. Back then the whole file was gone (all NULs).

@KL7000F ,
Thank you for the feedback and the detailed description. The content of the `nppLogNulContentCorruptionIssue.log` file looks OK.
It is probably a good idea for you at this point to do some disk checks for consistency and bad sectors and think of duplicating your critical data to another disk as this one might be progressively breaking and more data loss is possible.

Or this file might be simply not fully recovered after the file system corruption of your NAS - maybe this is the most probable scenario, IDK for sure.
Have you opened this file before since the NAS problems and the recovery happened? If you open it for the first time now after the NAS file system problems then it simply had not been properly recovered back then.

**Comment by donho** [comment] 2022-10-10 23:24
It seems NUL are not "written" by Notepad++.
This issue can be closed.

**Closed by donho** 2022-10-10 23:24 UTC

**Comment by SDRTGT45** [comment] 2023-06-11 15:09
I ran into a problem when a large file with the work of three whole years turned into one big NULL text, when trying to restore it, everything happens, the file is restored, but its contents turn into hieroglyphs, and an attempt to change the encoding does not lead to anything, please tell me what to do?
![2023-06-11_17-48-37](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/98409327/b4313194-8c70-4afe-9509-1adbe1cbe8b4)
![2023-06-11_17-48-22](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/98409327/59a24998-6583-419d-a723-4affcb5526ed)
