### ISSUE TITLE
List of PHP functions not working

### ISSUE THREAD

**Issue by rafasashi** [notepad-plus-plus/notepad-plus-plus#3095] opened 2017-03-25 15:49 UTC
Im just reporting a bug related to the question asked here:

http://stackoverflow.com/a/35102532/2456038

The list of php functions sometimes doesn't work.

The solution is to add enter/add new line after close the class or function tag.

**Comment by MAPJe71** [comment] 2017-03-26 20:48
Duplicate of #1232, #1861 and #2910.

**Closed** 2022-01-11 10:45 UTC
Labels: duplicate, language-support
