### ISSUE TITLE
N++ restores default language after switching to another tab and back

### ISSUE THREAD

**Issue by sirzooro** [notepad-plus-plus/notepad-plus-plus#1984] opened 2016-06-20 15:02 UTC
Steps to reproduce:
- open two `.xsl` files;
- change language of 1st one to C++;
- switch to tab with 2nd file;
- switch to 1st tab again;

Expected result: 1st file still uses C++ highlighting
Actual: N++ switched highlighting to XML

Notepad++ 6.9.2, windows

**Comment by dail8859** [comment] 2016-06-22 23:12
Duplicate of  #1681

**Comment by dail8859** [comment] 2016-06-26 15:04
Can't duplicate the result. Can you post your debug info (located under the `?` menu). It may be a plugin (e.g. XMLTools) trying to auto-detect the language.

**Comment by abzalov** [comment] 2016-06-26 15:12
Yes you are right. After remove the XMLTools plugin, syntax highlighting is not loss.
But plugin XMLTools is very useful for me. What can be done?

Debug info:
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppCCompletionPlugin.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll PluginManager.dll XMLTools.dll

**Comment by dail8859** [comment] 2016-06-26 15:14
> What can be done?

Report it to the author of the plugin.

**Comment by abzalov** [comment] 2016-06-26 15:27
> Report it to the author of the plugin.
Ok, i try to find the contacts.

To sirzooro:
I [found](https://sourceforge.net/p/npp-plugins/bugs/270/) a workaround for this problem:
  Disabling the option "Set XML type automatically" in XML Tools menu - fix this side effect.

**Comment by sirzooro** [comment] 2016-06-26 18:47
@abzalov thanks, I will try it. I also use this plugin so probably this is the case.

**Comment by SinghRajenM** [comment] 2017-02-24 18:39
@dail8859  I think this ticket can be closed as it is related to plugin.

**Closed** 2017-02-24 18:43 UTC
Labels: plugin
