### ISSUE TITLE
Some shortcuts works in all tabs, some not

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#3699] opened 2017-09-04 21:17 UTC
If i have this shortcut:
`<Item id="1641" name="&amp;Find alle i aktuelle dokument"/>`

I can use the shortcut from inside the Find tab (Ctrl+F).
But i can also use it when inside the Replace tab (Ctrl+H).

But if i have this shortcut:
`<Item id="1609" name="&amp;Erstat alle"/>`

I can't use it inside the Find tab, only the Replace tab.

I guess it should be that the shortcuts either works in all tabs or only the tabs they appear in and not as it is now a mixture.

**Comment by krilbe** [comment] 2019-04-18 06:21
I think this issue should be fixed. It's not expected behavior from a user's perspective that shortcuts from other tabs can be activated. I also think that this would solve issue #3539,  #2276 and possibly other shortcut issues in the find/replace dialogs.

I have a similar hitherto unreported issue. With Swedish language setting, A is underlined for "Antal sökträffar" (number of matches) on the find tab, and also for "Ersätt alla" (replace all) in the replace dialog. Alt+A does trigger number of matches if the find tab is active, but if the replace tab is active, nothing happens, presumably because it triggers the number of matches command which is not available with the replace tab being active (but apparently it swallows the Alt+A shortcut keypress).

**Comment by krilbe** [comment] 2019-04-18 06:28
I just confirmed that this is the cause of the issue, because if I remove &amp; from "Antal sökträffar" in swedish.xml makes "Ersätt alla" starts working, i.e. Alt+A now does trigger "Ersätt alla" as it should.

So, I strongly urge you to make sure that all dialogs in Notepad++ with multiple tabs start working as expected: Alt key shortcuts should only trigger command that are on the currently active/visible tab, and commands on other tabs with the same shortcut letter should not block anything on the active tab.

The issue is particularly problematic in the Find dialog and its four tabs, because it's frequently used and has lots of commands, making it difficult to find shortcut letters that are unique across all tabs.

**Comment by sasumner** [comment] 2019-04-18 12:18
@scootergrisen Keycombos defined in Shortcut Mapper only work in editing tab windows, NOT in other areas of the user interface, e.g. Find family of windows.  This is by design and I can't see it being changed.  So your citing of Shortcut Mapper config file entries and the Find window is totally invalid.

**Comment by krilbe** [comment] 2019-04-18 12:39
@sasumner I can't see any mention of "Shortcut Mapper". The XML items mentioned seem to come from the language.xml configuration file, which specifies command camptions as well as Alt + key shortcuts, by use of &amp; before the desired key.

The problem is that in the Find dialog, any such shortcuts ON DIFFERENT TABS should, from a user perspective work just fine, but in fact does not. For example, if both "Count" in the Find tab and "Replace" in the Replace tab were to have C as shortcut key ("&amp;Count" and "Repla&amp;ce"), only one of those commands will actually react to Alt+C, probably "Count". If the Replace tab is active, the "Count" command is not available, but will still catch the Alt+C keypress, resulting in "nothing happens". Expected behavior would be that Alt+C on the Replace tab should activate the "Replace" command.

I have tried this by modifying swedish.xml for the Swedish versions of "Count" and "Replace All", as mentioned above, so there's no question that this non optimal (buggy?) behavior exists, and I doubt that anyone could sensibly argue that it's intended or desirable behavior.

The question is if anyone is willing to invest time into fixing it. I hope so.

**Comment by sasumner** [comment] 2019-04-18 12:57
> I can't see any mention of "Shortcut Mapper".

Oops. Totally disregard my prior comment.  There have been previous expectations where Shortcut Mapper keys should work in all areas of the app, so in my mind I just grabbed onto that for this issue.

**Comment by MetaChuh** [comment] 2019-04-21 19:09
@scootergrisen 

this is in the design of the find/replace window tabs.
functions that are present, but hidden from a tab's gui, will function with their shortcuts.
if they are not present, the shortcut will have no function.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-04-21 19:09 UTC

**Comment by krilbe** [comment] 2019-04-22 06:00
@MetaChuh Isn't that design rather silly? Commands that are hidden are, for the most part, hidden because they are irrelevant in the currently visible tab. If they ARE relevant, they should also be visible, like e.g. "Match case", which is both relevant and visible on all tabs.

From a user perspective, for an Alt+key shortcut that's not visible to actually do something scares me and goes against how it works i just about any other Windows app. I would be very surprised if you can find any Microsoft design guidelines that supports that design. If you find it, please point me to it.

In addition, it NPP team persists in keeping this strange design, they should at least look for shortcut clashes, and give preference to the command that's visible. If multiple ones are visible, the general approach is to not _activate_ any of the clashing commands, but simply _move focus_ to the next one in tab order, to give the user the ability to navigate to the desired command using repeated Alt+key presses, and then activate the command using Space or whatever applies.
