### ISSUE TITLE
"Apply UTF-8 to opened ANSI files" doesn't work with empty files

### ISSUE THREAD

**Issue by vrubleg** [notepad-plus-plus/notepad-plus-plus#3235] opened 2017-05-02 18:31 UTC
### Description of the Issue
"Apply UTF-8 to opened ANSI files" setting doesn't work with empty files.

### Steps to Reproduce the Issue
1. Open Preferences → New Document.
2. Set default encoding to UTF-8, enable the "Apply to opened ANSI files" setting.
3. Create a new empty text file.
4. Try to open this file using Notepad++. Check current encoding. It is ANSI.

### Expected Behavior
Default encoding has to be Unicode.

### Actual Behavior
It is ANSI.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Apps\Develop\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll docMonitor.dll LightExplorer.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppNetNote.dll NppTextFX.dll PluginManager.dll SelectNLaunch.dll SpellChecker.dll

**Comment by vrubleg** [comment] 2017-05-10 13:08
Just several use cases:
1. We create a new text file using Shift+F4 in Total Commander. It creates a new file and opens it in the Notepad++. But encoding is ANSI.
2. We create a new file using N++ FTP plugin. But when we open this file, it will be treated as ANSI.
3. We create a new text file using Explorer's New → Text Document. But when we open it in Notepad++, it is opened as ANSI, not UTF-8.
This bug is really very annoying for people who would like to use UTF-8 by default.

**Comment by dail8859** [comment] 2017-05-10 14:08
Duplicate of #2947 #1874

Closed by a9de79a55062b02b7736ecd409a7bcc8f699bf6f

This will be fixed in the next release.

**Closed by dail8859** 2017-05-10 14:08 UTC
