### ISSUE TITLE
Key shortcuts removed in save dialogue?

### ISSUE THREAD

**Issue by mjmatthiesen** [notepad-plus-plus/notepad-plus-plus#7645] opened 2019-11-22 20:26 UTC
### Description of the Issue
When closing an unsaved document the resulting dialogue that ask you to save does not accept common keys for selection any more. y/n
![image](https://user-images.githubusercontent.com/16603906/69458053-b8003e80-0d2b-11ea-8967-05280c049bf3.png)

### Steps to Reproduce the Issue
1. Open n++
2. create new doc
3. type anything
4. close doc
5. press n

### Expected Behavior
Hitting n should cause the dialogue to accept it as no, y as yes, the normal win behaviour

### Actual Behavior
Nothing happens. You have to use tab or arrow keys, or if you're bad, your mouse.

### Debug Information
n/a

**Comment by sasumner** [comment] 2019-11-22 21:46
Please search for existing issues before creating new ones.  Closing as duplicate of #6223 .

**Closed by sasumner** 2019-11-22 21:46 UTC

**Comment by mjmatthiesen** [comment] 2019-11-22 22:28
> Please search for existing issues before creating new ones. Closing as duplicate of #6223 .

[I did](https://github.com/notepad-plus-plus/notepad-plus-plus/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyboard+save+dialogue). Shocked it was empty. More variations, also empty. Looked through a few pages, found nothing.

I'm glad the issue is already being addressed.

**Comment by sasumner** [comment] 2019-11-22 23:15
> I did

You only searched open issues.  It has been fixed and closed, and is pending release in the next Notepad++ version.
