### ISSUE TITLE
Unattended update?

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#1730] opened 2016-04-07 14:17 UTC
Since it is reasonable to assume that I don't really want to change stuff when I update Notepad++ (from when I updated it a couple weeks ago, and a couple weeks before that) an unattended update would be nice. "Would you like to update?" Yes, _click_, done, back to work.

**Comment by dail8859** [comment] 2016-04-07 15:38
Duplicate of #1624

**Comment by FlorinAndrei** [comment] 2016-06-30 17:27
Issue #1916 has been marked as a duplicate of this one, but that's incorrect. This issue talks about a one-click update. #1916 talks about a zero-click update, completely transparent to the user (like Google Chrome).

**Comment by Pilskalns** [comment] 2016-07-07 08:40
Yes, this would be most user friendly for day to day use. We have a lot of win servers under our watch and every now and then have to check logfiles or change few config lines on most of them.

Preferable options would be like "**Now**" or "**In background**"
When allowing for update in background, it can download installer in background, and then, when N++ gets closed, then perform silent / background installation. So, when you come back, new version would be there.
In most cases, you won't need this minor version update right now, but keeping on latest is good practise. But if you do need, you can always click Now.

**Comment by donho** [comment] 2019-04-19 00:35
It'll make installer logic more complicated, therefore it won't be implemented.

**Closed by donho** 2019-04-19 00:35 UTC
Labels: installer
