### ISSUE TITLE
In Python the variable "def" not working correctly in Function List.

### ISSUE THREAD

**Issue by Longhorn99** [notepad-plus-plus/notepad-plus-plus#3645] opened 2017-08-23 16:32 UTC
When the word "def" is used as part of a variable, it shows up as a "function" in the Function List.

example:

USER_DEF = 1000

def test():
    print("hello")

will show up as:

= 1000def test()

**Comment by MAPJe71** [comment] 2017-08-29 22:43
Duplicate of #3136.

**Closed** 2020-08-28 12:39 UTC
