### ISSUE TITLE
opening and closing parenthesis do not highlight correctly in batch file

### ISSUE THREAD

**Issue by camusichc** [notepad-plus-plus/notepad-plus-plus#4933] opened 2018-10-17 20:57 UTC
Dear Notepad++ team

### Description of the Issue
I am working with v7.5.8 and I found that opening and closing parenthesis are not highlighted correctly in if statements.

### Steps to Reproduce the Issue
1. open/create .bat file in Notepad++ v7.5.8
2. write some dummy code including cycles and if statements
3. when you set the cursor besides a parenthesis it will not show where it closes

### Expected Behavior
It is expected to highlight both, opening and closing matching parenthesis

### Actual Behavior
parenthesis are not highlighted

**Comment by sasumner** [comment] 2018-10-18 11:46
@camusichc Suggestion: Don't make people write some "dummy code".  Include a concrete example here clearly illustrating the problem you see.

**Comment by dinkumoil** [comment] 2018-10-18 14:19
Yes, this is (at least for me) a well known and annoying bug because I use batch script quite often.

I provide a screenshot of the code above to make it more clear:

![grafik](https://user-images.githubusercontent.com/24699812/47161036-75329280-d2f1-11e8-8b7c-c048d72beb03.png)

**Comment by ArkadiuszMichalski** [comment] 2020-09-18 23:19
I can confirm this in Notepad++ 7.9 RC, get same results as above picture.

**Comment by ArkadiuszMichalski** [comment] 2021-11-07 00:52
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d7819cf601051510b7fa1640ca17fedad297e1f8.

**Closed by ArkadiuszMichalski** 2021-11-07 00:52 UTC
