### ISSUE TITLE
[Feature Request] Add context menu for encoding in status bar

### ISSUE THREAD

**Issue by ozone10** [notepad-plus-plus/notepad-plus-plus#9998] opened 2021-06-13 15:56 UTC
Currently if you want to change encoding you need to go to Encoding menu.
Sometimes I need to change both EOL and encoding so to not move mouse much, I would like to have this feature.

**Comment by sasumner** [comment] 2021-06-13 23:24
I can't find the issue, but I know this has been suggested and rejected by @donho before.

**Comment by ArkadiuszMichalski** [comment] 2021-06-14 00:00
This https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5523#issuecomment-517956714?

**Comment by mere-human** [comment] 2021-06-14 07:06
It seems a bit inconsistent that there is a context menu for line endings in the status bar but not for encoding.

**Comment by sasumner** [comment] 2021-06-14 12:52
It is inconsistent but it is what the author wants, so that's it.  I'm closing.

**Comment by sasumner** [comment] 2021-06-14 12:54
BTW, duplicate of #5523

**Comment by sXNA** [comment] 2022-05-15 14:50
@donho 
Could this be reopened.

**Closed** 2022-05-16 12:47 UTC
