### ISSUE TITLE
Save dialog keyboard shortcuts

### ISSUE THREAD

**Issue by jan-marten** [notepad-plus-plus/notepad-plus-plus#7686] opened 2019-12-03 10:24 UTC
### Keyboard shortcuts (Y/N) in the new save dialog are not working
When you close a dirty file you get the new Save-dialog with default option being Yes.

### Steps to Reproduce the Issue
1. Open Notepad++ (version 7.8 or 7.8.1)
2. Enter some text
3. Press Ctrl+W
4. Press N for "No, I do not want to save it"

### Expected Behavior
Window closes, changes are discarded.

### Actual Behavior
Nothing, save dialog doesn't react on keyboard press.

### Debug Information
n/a

**Comment by ikkentim** [comment] 2019-12-03 12:10
I think this was already fixed in cf7e373dca890d65ecc86489fe9cce1bcc7597f7

**Comment by sasumner** [comment] 2019-12-03 12:48
Closed as duplicate of #6223

**Closed by sasumner** 2019-12-03 12:48 UTC
