### ISSUE TITLE
Notepad++ changes text file encoding so that the file is unreadable

### ISSUE THREAD

**Issue by BernieStn** [notepad-plus-plus/notepad-plus-plus#5451] opened 2019-03-22 19:32 UTC
### Description of the Issue
When using special characters, Notepad++ changes the file encoding during save and when reopening the file, the content is no longer readable.

### Steps to Reproduce the Issue
- Open Notepad++
- In the status bar, the encoding is UTF-8. That is ok.
- Enter the following text: abc
- Save the file
- Close Notepad++
- Open the file
- In the status bar, the encoding is still UTF-8. That is ok.
- Change the text from abc to abcä
- Save the file
- Close Notepad++
- Open the file
- In the status bar, the encoding is still UTF-8. That is ok.
- Change the text from abcä to abc, then hit enter to go to the next line, there enter ä so that the file has the following content:
abc 
ä
- Save the file
- Close Notepad++
- Open the file.
-->In the status bar, the encoding is now TIS-620.
--> The file content is not readable anymore. It looks like this:
abc
รค

### Expected Behavior
UTF-8 encoding should always remain.

### Actual Behavior
Encoding is changed to TIS-620

### Debug Information
Notepad++ v7.6.4   (64-bit)
Build time : Mar  6 2019 - 02:58:24
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by MetaChuh** [comment] 2019-03-22 20:50
**Referenced to:**
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/bfb7e863cc6cd20f9f32389bee289607a212b12b , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5126 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5299 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5310 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5202 , https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5414 , https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5440

note to @donho : i guess i'm very annoying to you, and i'm getting on your nerves a lot lately, but
**this seems a serious issue and is beginning to escalate in frequency, even without auto updates to 7.6.4**

@BernieStn

i can reproduce your issue perfectly.
thank you for your detailed step by step procedure.

unfortunately autodetect character encoding is broken since notepad++ version 7.6.
the implementation of UCharDet 0.0.6 since version 7.6 has caused this.
a [rollback fix has been submitted](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5414), but is currently (hopefully) under final investigation and (hopefully) getting fixed before the next 7.6.5. release.

**currently, until the broken auto detect character encoding is fixed, you will have to:**
* go to `settings > preferences > misc` and **disable** `auto detect character encoding` as seen at the screenshot below.

![settings - auto detect character encoding](https://i.imgur.com/9SZ5ufh.png)

* then go to `settings > preferences > new document` and set your preferred default encoding to e.g utf-8, as seen at the screenshot below.

![Imgur](https://i.imgur.com/AarYeSx.png)

after that you will be able to edit your utf-8 files without data corruption.
please note, that you have to switch to e.g. ansi manually, if you edit ansi encoded files from time to time.

test file created from your specifications: 
[ger, utf-8, detected as tis-620 (#5451, abcä).txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2998253/ger.utf-8.detected.as.tis-620.5451.abca.txt)

**Comment by sasumner** [comment] 2019-03-23 12:38
>note to @donho : i guess i'm very annoying to you, and i'm getting on your nerves a lot lately, but
this seems a serious issue and is beginning to escalate in frequency, even without auto updates to 7.6.4

For someone that doesn't do support, this doesn't really matter.  For people needing support on it, isn't there already enough Q-&-A here and other places that people should be able to find their own help via searching?  You've stated your bit, maybe just safe to leave it all lie and don't deal with this issue any more? Only my 2c.

**Comment by MetaChuh** [comment] 2019-03-23 16:37
@sasumner 
agreed.
ps: i miss your 2 cents a day. they've somehow helped to keep both a logical and emotional balance, especially in cases of dealing with one's own helplessness, while coping with the inner urge to be of service.

**Comment by sasumner** [comment] 2019-03-23 20:29
@MetaChuh , did you take note that "For someone that doesn't do support, this doesn't really matter." was not at all directed at you, but rather someone else? :)

Hmmm.  I feel that I am too quick to annoyance. You have infinite patience. Don't change. :)

**Comment by MetaChuh** [comment] 2019-03-24 09:20
@sasumner 

> did you take note that ...

i have read and understood every single word you wrote, and i have understood every word that was omitted.
my answer was free of any sarcasm, and everything is meant to be in your favour.
i suppose the heart emoji was the "a bit too much" trigger causing this reaction. my apologies.

clarifying summary:
* i agree that this does not matter to someone who doesn't do support.
this excludes all people who support the way i and others do, which also excludes you, supporting the way you did and do, for sometimes more or less ungrateful, and always vastly time consuming, ages.

* i agree to leave it all lie, as it does not make sense to pursue anything, that bounces off deaf ears since its introduction. but i needed your trigger to accept that and to cease persisting.

* i miss your 2 cents a day every day at the community, as you've also support(ed) the supporters, like supporting me, claudia, peter and many others in many ways, keeping most of us together and giving us a personal reason to continue.
(note: this might be a long time ago for you, but it's like yesterday to me)

> You have infinite patience. Don't change. :)

i guess we all change, and every change might be a good change, if our surrounding cares and takes the time to understand why we changed, sometimes eventually also leading to a change of surroundings.

with sincere and best regards
(note: no emojis, nor any meta-sarcasm)

**Comment by MetaChuh** [comment] 2019-04-06 22:28
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/486e2188b2d4f5e897d5ffffa9b3dcd23b3ae2d6

**Closed by MetaChuh** 2019-04-06 22:28 UTC
