### ISSUE TITLE
Foreground colour in "Selected text colour" has no effect

### ISSUE THREAD

**Issue by savchenko** [notepad-plus-plus/notepad-plus-plus#8177] opened 2020-04-26 12:11 UTC
### Description of the Issue
Changing foreground colour of selected text in "Style configurator" makes no difference.

### Steps to Reproduce the Issue
1. Open Style Configurator
2. Change background of selected text to a dark tone
3. Change foreground of selected text to white (255, 255, 255)

### Expected Behavior
Colour of selected text changes as per setting

### Actual Behavior
See below:
![image](https://user-images.githubusercontent.com/300146/80307175-9f2e1480-8806-11ea-9d89-d0aa5ae15285.png)

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.778
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2020-04-26 13:33
Duplicate of #3397

**Comment by asvc** [comment] 2020-04-27 10:55
Looked for Bountysource page, instead found the https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4488

Shrugged, sent a token via PayPal.

Not a major issue anyway, workaround &mdash; set slightly brighter selection colour.

**Comment by alankilborn** [comment] 2022-08-05 15:10
This has been addressed in Notepad++ 8.0.
See #3397 for more information.
Also see user manual [HERE](https://npp-user-manual.org/docs/config-files/#:~:text=enableSelectFgColor.xml)
Recommend CLOSURE of this issue.

**Closed** 2022-08-05 15:18 UTC
