### ISSUE TITLE
[Feature Request] filter to remove binary files from 'find in files'

### ISSUE THREAD

**Issue by AartBluestoke** [notepad-plus-plus/notepad-plus-plus#8982] opened 2020-10-09 01:32 UTC
### Description of the Issue
Search for text values within files spends too much time searching binary files. Searching 

### Steps to Reproduce the Issue

1. clone npp repo (or basically any other software), and build the software
2. do an all files search for the word 'text' 
3. note that a moderate amount of time is spent searching .ico, .dll, the /obj and /bin folders, and other binary files, and that the results show that NppShell.dll is a match

### Expected Behavior
when I search for a text value, I only spend time searching through and find text.

### Actual Behavior
binary files are also considered. (in my situation there are a few large media files within some directories, and .obj/.bin files are quite large)

It would would be quite nice if there was a 'exclude binary files' checkbox in the find in files search window, where 'binary' could be defined as 80% of first 100 chars are not ascii/valid unicode, there is space below the directory text box.

![image](https://user-images.githubusercontent.com/1892829/95531092-689e2c00-0a2b-11eb-802b-afe081f88a9f.png)

**Comment by vinsworldcom** [comment] 2020-10-09 02:36
Can't you just use the existing Filters?  I use them like this:

![image](https://user-images.githubusercontent.com/9657169/95535404-6057d980-09b6-11eb-9bfd-274d2e154373.png)

Which I think is matching for "DEFAULT:" - which will most likely never match anything, but it acts like a name for me to identify the filter string which I can keep adding to:

```
!*.exe !*.dll !*.pyc !tags !*.*db !*.*obj *.*
```

You can find [syntax for the filters](https://npp-user-manual.org/docs/searching/#find-in-files) on the documentation site.

Cheers.

**Comment by ArkadiuszMichalski** [comment] 2020-10-09 08:23
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8857.

**Comment by sasumner** [comment] 2020-10-09 12:22
@vinsworldcom 

At first I thought your `DEFAULT:` was a great waste of space, but reading further I saw how it helps you find it when you dropdown the _Filters:_ combobox.  Nice one!

BTW, you _can_ save a bit of space in your filters string by NOT putting \*.\* at the end.
As of Notepad++ 7.8.7, doing that shouldn't be necessary.

**Comment by sasumner** [comment] 2020-10-09 12:23
Closing as the aformentioned duplicate.

**Closed by sasumner** 2020-10-09 12:23 UTC
