### ISSUE TITLE
multi-language support for HTML

### ISSUE THREAD

**Issue by wikiwiggs** [notepad-plus-plus/notepad-plus-plus#4469] opened 2018-05-02 13:53 UTC
### HTML CSS & Javascript
is their multi-language support for HTML.

Meaning, I would like to manually select areas of an HTML document, and be able to mark it as a particular language, similar to how you would mark a whole document via Language >> J >> Javascript OR Language >> C >> CSS

Even markdown supports this, and I was hoping that there is something similar in np++

##Javascript Support
```javascript
var myVariable = "SomeValue";
```

##CSS Support
```css
.className {
    display: block;
    font-weight: bold;
}
```

##Full HTML with Nested CSS + Javascript Support
```html
    <html>
    <head>
        <style type="text/css">
            .className {
                display: block;
                font-weight: bold;
            }
        </style>
        <script type="text/javascript">
            var myVariable = "SomeValue";
        </script>
    </head>
    <body>
    </body>
</html>
```

----

##What I would Like to See:

```html
<html>
    <head>
        <style type="text/css">
```
```css
            .className {
                display: block;
                font-weight: bold;
            }
```
```html
        </style>
        <script type="text/javascript">
```
```javascript
            var myVariable = "SomeValue";
```
```html
        </script>
    </head>
    <body>
    </body>
</html>
```

Better yet, if the language selection were based on the tags (<style type="text/css"></style> && <script type="text/javascript"></script>) this would be even better, you could make the detection default to something like this, but allow the user to change this via the option, or get it back to default some how.

Anyway, I just find myself constantly wishing that I feel continuity here.

Thanks for looking

**Comment by MetaChuh** [comment] 2019-04-11 23:50
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)


###################################
2019.04.10:

we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:50 UTC
