### ISSUE TITLE
Highlight Matching Bracket Problem

### ISSUE THREAD

**Issue by Terror3333** [notepad-plus-plus/notepad-plus-plus#2865] opened 2017-02-03 21:49 UTC
### Description of the Issue
Matching brackets are not highlighted properly.
Sometimes they do match and sometimes they don't match.

### Steps to Reproduce the Issue
1. Jump around my file

### Expected Behavior
I'd expect the brackets to be highlighted properly regardless of their number or indentation.

### Debug Information
I think this has to do with:
- high number of brackets
- bad indentation

I have attached a few screenshots and the file I'm working on.
I tried opening the same file with a program named "Brackets" and the brackets are highlighted properly.

the .txt file was originally a .bat file.
I'd recommend changing it to .bat and opening it with Notepad++.

### Attached files

The file I'm working on [declaratii v4.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/751630/declaratii.v4.txt)

Screenshots
![npp ok](https://cloud.githubusercontent.com/assets/25427527/22609752/1c906776-ea6b-11e6-9b9a-5c87e4038166.jpg)
![npp not ok](https://cloud.githubusercontent.com/assets/25427527/22609754/1c962bde-ea6b-11e6-93e1-557eaaedfc3d.jpg)
![brackets ok](https://cloud.githubusercontent.com/assets/25427527/22609753/1c9402d2-ea6b-11e6-8454-190a807d9bbf.jpg)

###
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment] 2017-02-04 00:29
The way brace matching works is that it only looks at braces in the *same* style. There appears to be a bug in the lexer for Batch because the opening `(` on line 41 is not in the correct style. This bug would need reported to the [Scintilla project page](https://sourceforge.net/projects/scintilla/).

**Comment by Terror3333** [comment] 2017-02-04 08:59
Thank you for you answer.
I have just posted it there, here's the link.
https://sourceforge.net/p/scintilla/bugs/1906/

**Comment by RobMahn** [comment] 2018-06-17 01:05
https://sourceforge.net/p/scintilla/bugs/1906/ is a duplicate of https://sourceforge.net/p/scintilla/bugs/1624/

I reported this problem on Scintilla bug 1624 yesterday.  Look for "Rob Mahn". 

Neil Hodgson  replied back and forth with me and describes how to fix this problem.

I would like to get out of the middle of this finger pointing contest.  Please see if you can work with Neil to fix this problem.

**Comment by MetaChuh** [comment] 2019-05-01 15:21
this can't be fixed as long as it is an open scintilla bug

**Closed by MetaChuh** 2019-05-01 15:21 UTC
