### ISSUE TITLE
css syntax problem

### ISSUE THREAD

**Issue by gerard-durand** [notepad-plus-plus/notepad-plus-plus#5207] opened 2019-01-07 16:27 UTC
### Description of the Issue

On some css file, syntax colouring stops after some lines. 
### Steps to Reproduce the Issue

1. On this css file (in Notepad 7.6.2, but may have been there before !) :
[attachmentList_noia_3.53.css.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/2733431/attachmentList_noia_3.53.css.zip)
colouring stops at line 40.

2. Click on the + in the margin and the colouring is here again.

**Comment by gurikbal** [comment] 2019-01-07 16:37
![capture-20190105-221601](https://user-images.githubusercontent.com/36083297/50780213-5cba8e80-12c8-11e9-87f8-49ccac9f7596.png)

**Comment by gerard-durand** [comment] 2019-01-07 18:25
Here is what I obtain when I open this css file (top image) and after a clic on the + sign in the margin (bottom image) :+1: 
![before_and_after](https://user-images.githubusercontent.com/46453025/50785655-9cc24700-12b1-11e9-86eb-693422b9ac38.jpg)
May be I should precise that I am on Windows 7, home edition, 64 bits. Not sure, it's important.

**Comment by ArkadiuszMichalski** [comment] 2020-09-19 00:26
@gerard-durand You still have this problem? I can't reproduce in NPP 7.9 RC, get same results as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5207#issuecomment-451996249.

**Comment by gerard-durand** [comment] 2020-09-19 06:28
This is an old problem. I can't see/reproduce it with my last npp program (7.8.8). So, may be it has been solved...

**Comment by ArkadiuszMichalski** [comment] 2020-09-19 09:37
@gerard-durand If the problem does not occur so please close this bug.

**Comment by gerard-durand** [comment] 2020-09-19 10:57
OK, closed

**Closed** 2020-09-19 10:56 UTC
