### ISSUE TITLE
Shortcut CTRL+SHIFT+A not working

### ISSUE THREAD

**Issue by emi-le** [notepad-plus-plus/notepad-plus-plus#8052] opened 2020-03-19 11:41 UTC
### Description of the Issue
I had a shortcut on CTRL+SHIFT+A  (show all symbols - GERMAN VERSION "Alle Zeichen anzeigen"). I noticed, it didn't work anymore. I tried different combinations. They worked.
When I selected CTRL+SHIFT+A again as the shortcut it showed no conflicts.
I tried assigning this shortcut to other options (didn't work). So there is a workaround (do not use CTRL+SHIFT+A).

Another thing I noticed here, that when I select any given shortcut that is already defined, it shows a conflict with itself (until I change the shortcut). 

### Steps to Reproduce the Issue
1. Set CTRL+SHIFT+A as a shortcut for "show all symbols" (or something else)
2. Use the shortcut

### Expected Behavior
I expected to switch between showing all symbols and not

### Actual Behavior
Nothing happend

### Debug Information
Notepad++ v7.8.5   (32-bit)
Build time : Mar  4 2020 - 11:04:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.693
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by emi-le** [comment] 2020-03-19 11:43
By the way (I tried CTRL-SHIFT on both sides of the keyboard so its not like the keys are not working). Also I tried CTRL+SHIFT+B (that worked).

**Comment by sasumner** [comment] 2020-03-19 11:53
>show all symbols 

There is no (in English) command called "Show All Symbols".  There is "Show All Characters" which is, I presume, what you meant.

Assigning Ctrl+Shift+A to "Show All Characters" and then attempting to use it, showed no defect for me (it worked).

>when I select any given shortcut that is already defined, it shows a conflict with itself

It isn't really showing a "conflict with itself", but regardless, the behavior you are seeing is by design.

Closing unless and until further evidence of a problem is provided.

**Closed by sasumner** 2020-03-19 11:53 UTC
