### ISSUE TITLE
Additional feature for C language synthax hilighting

### ISSUE THREAD

**Issue by dolbnya** [notepad-plus-plus/notepad-plus-plus#1365] opened 2016-01-14 06:16 UTC
It would be awesome if notepad++ hilighted C-code fragments between **#if 0** and **#endif** like a commentary/ Thank you in advance!

**Comment by dail8859** [comment] 2016-01-16 20:25
I agree this would be awesome to have. The problem is if you turn that feature on in the C/C++ lexer then any time you have a **#if var** statement it will not highlight it unless **var** was defined *in that same file*.

**Comment by dolbnya** [comment] 2016-01-18 05:10
Ofcourse it wouldn't be perfect if *#if 0* was correctly highlighted and *#if variable* wasn't, but there are a lot of people who use exactly *#if 0* (not *#if some_variable*) to comment big C-code fragments (usually temporarily), because in these cases there wouldn't be problem with commenting of fragments with multiline comments. So *#if 0* ... *#endif* could be handled as a special case. Thank you any case.

**Comment by dail8859** [comment] 2016-01-18 13:35
I agree it would be nice for *#if 0* to be handled specifically, but that feature request would need to be made to the Scintilla developers.

**Comment by dolbnya** [comment] 2016-01-19 08:37
Scintilla developers: This is already implmented with the lexer.cpp.track.preprocessor property.
http://www.scintilla.org/SciTEDoc.html#property-lexer.cpp.track.preprocessor

**Comment by dail8859** [comment] 2016-01-19 16:22
@dolbnya That is what I was *originally* talking about. The problem is if you have:

```C
#if DEBUG
    puts("error");
#endif
```

And turn on that preprocessor property, then it will not highlight it because `DEBUG` has not been defined. There is also [`lexer.cpp.update.preprocessor`](http://www.scintilla.org/SciTEDoc.html#property-lexer.cpp.update.preprocessor) however many times when editing C/C++ code the defines are defined in headers which Scintilla won't know about.

There is no way to tell the lexer to only disable **#if 0** but not any other blocks.

**Comment by MetaChuh** [comment] 2019-04-11 00:51
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:51 UTC
