### ISSUE TITLE
Scintilla 5.3.0: "URL Hovered" only affects links' underline

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#12219] opened 2022-09-23 00:57 UTC
**STR:**
"Preferences -> Cloud & Link -> Clickable Link Settings": check only "Enable".
Paste https://github.com/notepad-plus-plus/notepad-plus-plus.
Hover over the link.

**Result:**
Only the link underline changes color.
![תמונה](https://user-images.githubusercontent.com/10229320/191874755-717ac9e7-91b3-47a8-9698-5315f8f621e8.png)

**Preferred:**
Both link and underline change color.
(The behavior prior to Scintilla 5.3.0).
![תמונה](https://user-images.githubusercontent.com/10229320/191874947-826c3c36-1f9e-47b0-9b60-f6d1e5b1cf34.png)

***

Notepad++ v8.4.5   (64-bit)
Build time : Sep 12 2022 - 18:38:40
Path : C:---\Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 20H2
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : 
    ComparePlus (1)
    HTMLTag (1.3.2)
    MenuIcons (1.2.5)
    PythonScript (2)
    _CustomizeToolbar (4.2)

**Comment by rdipardo** [comment] 2022-09-23 01:55
>      Plugins : 
>         . . . 
>         HTMLTag (1.3.2)
>         . . . 

Time to upgrade(?) https://bitbucket.org/rdipardo/htmltag/src/v1.3.5/NEWS.textile

**Comment by Yaron10** [comment] 2022-09-23 02:15
@rdipardo,

👍 
Thank you for your ongoing work. I appreciate that.

I thought you'd post new-release-announcements on https://community.notepad-plus-plus.org/category/5/plugin-development. :)

**Comment by rdipardo** [comment] 2022-09-23 05:45
> I thought you'd post new-release-announcements on https://community.notepad-plus-plus.org/category/5/plugin-development. :)

For major version bumps and fixes to user-reported bugs, yes. But there's been so many point releases since I got the bright idea of porting to Free Pascal (*1) that you'd get tired of hearing from me.

---
(*1) Long story short, Delphi is UTF-16, just like Windows, the only platform it was ever seriously intended for. Free Pascal is (optionally) UTF-8, because it has to run on Linux, PowerPC, [and even Game Boys][0]. 

Mind you, [CudaText] (*2) is purely Free Pascal, and runs faster than anything I've used on any platform. They just didn't have Win32 interop in mind when they wrote the FPC runtime library . . .

(*2) Pronounced /ʧuda tɛkst/ "chew-dah text"


[0]: https://wiki.freepascal.org/Platform_list
[CudaText]: https://cudatext.github.io


[0]: https://wiki.freepascal.org/Platform_list

**Comment by alankilborn** [comment] 2022-09-23 11:42
Reading the comments, at first I thought this issue was caused because OP hadn't upgraded his HTMLTag plugin.
But then I tried the STR in N++ 8.4.5 and 8.4.6(RC) and I see that it truly IS an issue with the base software, and HTMLTag related comments had nothing to do with it (I think).
So updating the HTMLTag won't solve the issue (again, that is my current thinking after some amount of pondering).

Long story short:  It really confuses things when issues turn into advertisements for new plugins, just because someone notices from an OP's Debug Info that a plugin is older.  If you feel compelled to do this kind of thing, PLEASE flag it with "off-topic" and also explain WHY you are mentioning it, i.e., "this has nothing whatsoever to do with the current issue, but I noticed the blahblah plugin is out of date and you might want to try a newer one".

**Comment by Yaron10** [comment] 2022-09-23 13:49
@rdipardo,

I'll briefly conclude the HTMLTag comments: I've updated and I'll visit your bitbucket page more frequently.
Thanks again. 👍

**Comment by Yaron10** [comment] 2022-09-23 18:26
@donho,

How about reverting the following lines?

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/466053dc99a9de543eb955cfabe01e67c4193f4a/scintilla/src/EditView.cxx#L2139
and
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/466053dc99a9de543eb955cfabe01e67c4193f4a/scintilla/src/EditView.cxx#L2143

to 

`if (indicator.sacHover.style == IndicatorStyle::TextFore || (indicator.sacHover.style == IndicatorStyle::ExplorerLink)) {` 

and

`if (indicator.sacNormal.style == IndicatorStyle::TextFore || (indicator.sacNormal.style == IndicatorStyle::ExplorerLink)) {`

NOTE: if you check "No Underline", there's no underline in normal state but it does appear on hover.
IMO it's actually better.

**Comment by donho** [comment] 2022-09-23 23:28
@Yaron10 
It's rather the Scintilla part - will these changes that you suggested be part of next release of Scintilla?

**Comment by Yaron10** [comment] 2022-09-24 00:26
@donho,

I merely suggested to revert the Scintilla code change in v5.3.0 to the code used in previous versions.

This is the original Scintilla code prior to v5.3.0:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9455684b429449f668c1aedb77ec9dcb1642c244/scintilla/src/EditView.cxx#L2108

MOTE: if you only change that line, you get the exact behavior as in previous NPP versions.

***

If you are reluctant to modify the Scintilla part, I suppose the old behavior can be restored by modifying the code in NPP.
I haven't looked into it.

**Comment by donho** [comment] 2022-09-24 13:11
@Yaron10 
I'm not reluctant to modify the Scintilla part - I am careful about that because of Scintilla update.
Obviously it's a regression in Scintilla. I've no problem for integrating the Scintilla's official fix of its future version into Notepad++ Scintilla code, but I am not for fixing Scintilla code only in Notepad++ - that will create regression/unexpected behaviour while/after updating Scintilla code.

**Comment by Yaron10** [comment] 2022-09-24 13:24
@donho,

I understand that.

https://sourceforge.net/p/scintilla/bugs/2355/.

**Comment by ArkadiuszMichalski** [comment] 2022-09-24 23:11
@donho It was Notepad++  modification https://github.com/notepad-plus-plus/notepad-plus-plus/commit/84430809df2f6607a3bc5b9f05866149842f2bd9. Unfortunately the proposed path was not included.
https://sourceforge.net/p/scintilla/feature-requests/1371/

Looks like this can be still achieved without Scintilla modification:
>Is there any reason not to place 2 indicators (1 INDIC_PLAIN; 1 INDIC_TEXTFORE) over the URL to produce the desired visual effect?

**Comment by donho** [comment] 2022-09-25 00:20
@Yaron10 

You have mentioned

> How about reverting the following lines?
> 
> [notepad-plus-plus/scintilla/src/EditView.cxx](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/466053dc99a9de543eb955cfabe01e67c4193f4a/scintilla/src/EditView.cxx#L2139)
>
> Line 2139 in [466053d](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/466053dc99a9de543eb955cfabe01e67c4193f4a)
> if (indicator.sacHover.style == IndicatorStyle::TextFore) { 
>
> and
> 
> [notepad-plus-plus/scintilla/src/EditView.cxx](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/466053dc99a9de543eb955cfabe01e67c4193f4a/scintilla/src/EditView.cxx#L2143)
>
>  Line 2143 in [466053d](https://github.com/notepad-plus-plus/notepad-plus-plus/commit> /466053dc99a9de543eb955cfabe01e67c4193f4a)
> if (indicator.sacNormal.style == IndicatorStyle::TextFore) { 
>
> to
>
>  if (indicator.sacHover.style == IndicatorStyle::TextFore || (indicator.sacHover.style == IndicatorStyle::ExplorerLink)) {
>
> and
>
> if (indicator.sacNormal.style == IndicatorStyle::TextFore || (indicator.sacNormal.style == IndicatorStyle::ExplorerLink)) {
>
>  NOTE: if you check "No Underline", there's no underline in normal state but it does appear on hover.
>  IMO it's actually better.


I just checked the current code, its current state is want you wanted above:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/scintilla/src/EditView.cxx#L2139

The file `EditView.cxx` in Notepad++ master is exact the same one of Scintilla 5.3.0
So I don't see what can I do about it for you.

**Comment by Yaron10** [comment] 2022-09-25 00:41
@donho,

I'm not sure I understand what you mean.

I've suggested to replace
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/32b6cae4bfa52cf12101933d1e9d7bd4a128583a/scintilla/src/EditView.cxx#L2139
with
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9455684b429449f668c1aedb77ec9dcb1642c244/scintilla/src/EditView.cxx#L2108

**Comment by donho** [comment] 2022-09-25 01:11
@ArkadiuszMichalski 
Thank you for your very useful reminder and the link.
Indeed, the patch provided by @Uhf7 was accepted and merged into Scintilla.

@Yaron10 
My bad! Sorry about misreading your message. It was modified in the Notepad++'s Scintilla code only and this feature will be maintained.
Thank you for your heads up. I'll do a PR for this issue.

**Comment by Yaron10** [comment] 2022-09-25 12:44
@donho,

No problem at all. :)

Thank you. 👍

**Closed** 2022-09-25 17:46 UTC
Labels: accepted, regression
