### ISSUE TITLE
Notepad++ as preview handler

### ISSUE THREAD

**Issue by bveldkamp** [notepad-plus-plus/notepad-plus-plus#1056] opened 2015-10-26 12:28 UTC
This is a feature request

I would love to have NP++ configured as a preview handler in Windows Explorer for all / most filetypes it can handle. I am now using http://previewhandlers.codeplex.com/ but it is rather limited in both the number of supported filetypes, and it's configuration.

**Comment by MetaChuh** [comment] 2019-04-10 23:35
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:35 UTC

**Comment by burak-tarhanli** [comment] 2019-06-15 12:49
I'm using Notepad++ 7.7 on Windows 7, but I can't get any syntax highlighted preview pane. It's just displaying as plain text. Is this normal?

![Capture](https://user-images.githubusercontent.com/18482904/59551602-c8460d80-8f84-11e9-8bb0-8662cac8c117.PNG)

**Comment by cognociente** [comment] 2019-07-12 08:19
I would also like to use Notepad++ as a preview handler
