### ISSUE TITLE
when to support less and sass ?

### ISSUE THREAD

**Issue by ljxiong313** [notepad-plus-plus/notepad-plus-plus#4273] opened 2018-03-07 08:15 UTC
As you know that is less and sass are more and more popular for front-end developers, and I am  very like notepad++ editor for my job. So i hope it will be support less and sass in a shortly future.

**Comment by ArkadiuszMichalski** [comment] 2022-01-14 11:57
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5621.

**Closed by ArkadiuszMichalski** 2022-01-14 11:57 UTC
