### ISSUE TITLE
"Function List" does not work with some PHP class file

### ISSUE THREAD

**Issue by pippototaro** [notepad-plus-plus/notepad-plus-plus#9243] opened 2020-12-09 19:47 UTC
### Description of the Issue
I found this issue because notepad++ 7.9.1 can not list functions in my php class file.

Example:
```php
namespace atspower\gas;
require_once ABSPATH_PRIVATE . "fpdf/fpdf.php";
use Allamene\core\M;

class Invoice extends \FPDF { 

  private function pixelAMM($v) {
    $mm_inch = 25.4;
    $dpi = 96;

    return ($v * $mm_inch) / $dpi;
  }

  ...

}
```
![immagine_2020-12-09_204210](https://user-images.githubusercontent.com/75753022/101678983-02e81380-3a5f-11eb-8352-d306b5a09414.png)

### Debug Information
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1803
OS Build : 17134.1304
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment] 2020-12-09 22:55
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8814, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3095, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2910.

**Comment by pippototaro** [comment] 2020-12-10 07:44
Working! Thank you so much!

**Closed** 2020-12-10 12:02 UTC
