### ISSUE TITLE
[feature request] Move tab to beginning / end

### ISSUE THREAD

**Issue by Blastocystis** [notepad-plus-plus/notepad-plus-plus#13982] opened 2023-08-08 16:13 UTC
### Description of the Issue
I would like a way to quickly select a tab and move it to the end of the tabs list.  The "end" (right end) of the tabs list is my "most recently used" and is where I'm working.  I suppose for consistency there should be a "move tab to beginning", but I'd never use it.

Extra points if I could CTRL-CLICK or SHIFT-CLICK to select multiple tabs and move those tabs to the end of the tabs list.

### Steps to Reproduce the Issue
1.  Select a single tab or multiple tabs
2.  Activate key combo to move tab(s) to end of tab list

### Expected Behavior
Selected tab(s) move to the right end of the tabs list.

**Comment by victorel-petrovich** [comment] 2023-08-08 21:17
You could implement it yourself, in case of a single tab, by using scripting (tried) or macro (haven't tried).

It requires just a sequence of 2 commands: close current tab, and Restore Recent Closed File. 

PythonScript script:
```py
def main():
    notepad.close()
    notepad.menuCommand(MENUCOMMAND.FILE_RESTORELASTCLOSEDFILE)

main()
```

I suspect you're new to scripting in N++ (I was too not long ago ), https://community.notepad-plus-plus.org/topic/23039/faq-desk-how-to-install-and-run-a-script-in-pythonscript 

As to the other solution, a macro: it would be first time me trying to create a macro; I tried with the above 2 actions, using respective shortcuts, didn't work for some reason.

**Comment by alankilborn** [comment] 2023-08-08 22:08
>notepad.menuCommand(MENUCOMMAND.FILE_RESTORELASTCLOSEDFILE)

Note that this was is "unclean" as it loses any undo/change history of a file, as well as current caret position.

**Comment by alankilborn** [comment] 2023-08-08 22:10
See https://community.notepad-plus-plus.org/topic/24799

**Comment by freezer2022** [comment] 2023-10-19 21:16
Duplicate of :
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9525

**Closed** 2023-12-15 18:48 UTC
Labels: accepted
