### ISSUE TITLE
I would like to have permission to publish your app on the Windows Store

### ISSUE THREAD

**Issue by dgsimone15** [notepad-plus-plus/notepad-plus-plus#3196] opened 2017-04-21 20:33 UTC
Hi, I'm part of the UWP Open Source Community (https://github.com/UWP-Open-Source-Community). Our intent is to take Win32 Open Source applications and convert them into UWP apps through the Windows Bridge (Project Centennial).
We like your app and that's why we decided to convert it.
In case you would like to take charge of this app and publish it yourself on the store (make us very pleased) contact us the first possible please! Otherwise, we may be responsible for publishing your app.
If you do not want to take over the publication on the Store, can you give us permission to do so?
P.S.
Sorry for my poor English. Sorry if I wrote here but had no idea where to ask it :(
Thanks for your help.

**Comment by strollingHeifer** [comment] 2017-05-22 18:42
#3221

**Comment by strollingHeifer** [comment] 2017-05-22 18:46
Duplicate of #3221

**Comment by donho** [comment] 2017-11-04 13:26
@dgsimone15  Thank you for your help.
It's important to me that Notepad++ in Windows Store can be updated on each official release. Therefore we need a stable environment to be able to build UWP package and that depends on Microsoft:
https://notepad-plus-plus.org/community/topic/14734/notepad-uwp-package-in-windows-store-almost-there
I will do it myself once we have a stable configuration, Notepad++ UWP will be availabe in Windows Store. But before that, we have to wait until Microsoft get their job done.

**Closed by donho** 2017-11-04 13:26 UTC
