### ISSUE TITLE
Backups cause corruption for any long-running edit operations

### ISSUE THREAD

**Issue by krilbe** [notepad-plus-plus/notepad-plus-plus#1700] opened 2016-04-02 08:28 UTC
There has been problems with file corruption caused by backups during long-running macros. I think this has been fixed (#1044). Now it has come to my attention that similar problems exist with EOL conversion (#1371).

I suspect that ANY long-running edit operation will risk file corruption with backups active.

If this is the case (i.e. if it cannot be confirmed that it's **not** the case) I'd suggest that the backups feature be **disabled** until it has been rewritten in a more robust and reliable way.

**Comment by MetaChuh** [comment] 2019-04-18 01:36
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-18 01:36 UTC

**Comment by krilbe** [comment] 2019-04-18 06:04
Thanks, I haven't noticed any problems since some versions back. I did some explicit testing with large files now and couldn't find any issues.

I thought you would close issues when you fix them, but maybe this was fixed as a side effect of fixing other issues.

**Comment by eight04** [comment] 2019-04-18 07:21
Probably this PR: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/4803
