### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by teknopaul** [notepad-plus-plus/notepad-plus-plus#1695] opened 2016-03-31 12:36 UTC
The syntax highlighter contribution link is dead. I tried to create one, but using the current options this is hard / impossible.  I found no way to deal with, for example underscores, that are not part of a language syntax.  You can only escap inside a syntax block you cant seem to escape to indicate that the underscore does not denot special highlighting.  highlighiting the line above three underrscores also seems to be impossible.

This issue indicates it might be possible in scintilla.

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1258

**Comment by imbrish** [comment] 2016-03-31 13:50
Recently I got onto it as well, but quickly realized that it is not that easy. I hope it gets implemented.

**Comment by dail8859** [comment] 2016-03-31 20:24
There is a markdown lexer already in Scintilla. It's just not "wired up".  Which is what that issue you referred to is about.

**Comment by sasumner** [comment] 2018-08-28 19:47
@mal0ki How about the Markdown plugin for the time being?

**Comment by mal0ki** [comment] 2018-08-28 20:48
@sasumner yeah I was looking at that too. Ended up opting for StackEdit in this particular case though.

**Comment by nota-bene** [comment] 2018-09-20 05:43
I would love to see this as well. I've been using other editors only for Markdown.

**Comment by wwarriner** [comment] 2018-11-29 00:41
I would enjoy having Markdown support as well. Thanks for your consideration!

**Comment by MetaChuh** [comment] 2019-04-13 02:21
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:21 UTC

**Comment by DJCrashdummy** [comment] 2019-12-10 11:28
there is still no native Markdown/CommonMark support... :disappointed: so this issue still exists!
would it make sense to reopen this one or create a new issue?

**Comment by MetaChuh** [comment] 2019-12-10 12:45
@DJCrashdummy 

> would it make sense to reopen this one or create a new issue?

besides of the incorporated markdown user defined language, there are various, very well developed markdown plugins available.

the corresponding plugin authors have more time and fun, to focus on perfectioning markdown implementations, as a single and specific task, for the current users needs, than the little time frame, which would be possible to spend on the main notepad++ code, by the core dev team, due to the vast amount of past and current features and requests.

many thanks for your understanding and many thanks for using notepad++.

**Comment by DJCrashdummy** [comment] 2019-12-10 14:04
hmm... i [just found one](https://github.com/Edditoria/markdown-plus-plus), and it still has its issues. :frowning_face: 

i'm not asking for a plugin manager, but is there a list or something (even unofficial) where users can easily find the various UDLs and not have to search the whole web and then trail&error?

**Comment by teknopaul** [comment] 2021-06-02 10:37
Not sure why this got closed?

I cant see a plugin for syntax highlighting.  I see _Markdown Panel_ and _MarkdownViewer++_

Is https://github.com/Edditoria/markdown-plus-plus provides UDL but its not compatible with the scheme selector and missing bullets.
There seems to be reference to mark down in UDL but it does not result in a selectable Markdown option in the Languages list.  

What am I missing?

BTW probably we should rename the requirement to [CommonMark](https://commonmark.org/).
