### ISSUE TITLE
File Association - allow multi-select or select all when registering extensions

### ISSUE THREAD

**Issue by inertiap** [notepad-plus-plus/notepad-plus-plus#1281] opened 2015-12-22 07:27 UTC
I want Notepad++ to be associated with almost anything text oriented. Registering file extensions is extremely cumbersome at the moment. 

It's a continuous 2 click process since the extension pane does not automatically select the next item each time an extension is added.

Ability to multi-select with shift/control key would be a start. I'd also like to see "add all" buttons under the supported extension panes so I can easily add everything or just add all from the selected group.

The ability to quickly remove extensions in a similar fashion would be good, but less important.

I know this seems like a "one time" job but I use Notepad++ on every computer I own plus at the office and since I am reinstalling machines every now and then it would be a considerable addition.

**Comment by GoodNike** [comment] 2015-12-25 05:20
I believe that the proposed idea is good and think the enhancement of Preferences->File Association dialog should consist of:
1) registration / removal of new file extensions is not only by clicking a add / delete button, but also double click on the extension;
2) adding processing of shift and ctrl buttons in their usual application use for selection;
3) adding a button "Add all", "Add a group".

To prevent wasted effort, ready to implement after the administration of the project approves an enhancement.

**Comment by brendankehoe** [comment] 2016-04-23 10:43
Notepad++ is great. Thank you to everybody involved.

Please approve this enhancement. Add all extensions is available in so many applications. Why would you not want that option? I fully agree with original poster.

Thanks very much

**Comment by MetaChuh** [comment] 2019-04-13 02:07
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:07 UTC
