### ISSUE TITLE
Accessibility keyboard compatibility issue 

### ISSUE THREAD

**Issue by narcolepticinsomniac** [notepad-plus-plus/notepad-plus-plus#1688] opened 2016-03-29 09:47 UTC
Notepad++ doesn't work well with Windows built in On-Screen Keyboard. The autocomplete suggestions flicker and reset after each keypress which makes them useless and distracting.

It's not an issue in any other editor (Notepad, Sublime, Brackets) but I prefer Notepad++. Hopefully this is only an issue because you weren't aware.

Notepad++ 6.9, Win 8.1

**Comment by fishmad** [comment] 2016-07-12 01:58
I have the same issue on Windows 10 Surface, I can t get the native on screen touch keyboard to auto open when I touch the notepad++ open page texts, so I can type or edit, bit of a bummer. the normal windows notepad works with touch no problems.

Continually having to manually find and open the onscreen keyboard is getting old very quickely

**Comment by eRadicant** [comment] 2016-09-26 23:46
To add to this, emoji input via the Win10 touch keyboard does not work. Works fine in other text editors and applications.

**Comment by MetaChuh** [comment] 2019-04-13 02:22
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:22 UTC

**Comment by cdmeillon** [comment] 2020-09-23 13:47
FYI, 
For the benefit of anyone still plagued by this issue (which persists in v7.8.7)
I have found that the workaround is to:  
Go To: Settings -> Preferences -> Auto-Completion and un-tick "Enable auto-completion on each input".

------------------------

Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll
