### ISSUE TITLE
Monitoring doesn't keep scrollbar at bottom with word wrap turned on

### ISSUE THREAD

**Issue by idolpx** [notepad-plus-plus/notepad-plus-plus#3173] opened 2017-04-17 20:40 UTC
### Description of the Issue
If you are monitoring a file and word wrap is turned on the scroll bar doesn't stay completely at the bottom when new lines are added.

### Steps to Reproduce the Issue

1. Open a log file
2. Enable Monitoring
3. Enable word wrap
4. Resize window so that some lines wrap
5. Scroll to bottom and wait for new lines

### Expected Behavior
The view should keep the the scrollbar at the bottom so the new lines are in view.

### Actual Behavior
The scrollbar is a few lines or so up from the bottom.

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by MetaChuh** [comment] 2019-04-11 22:59
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 22:59 UTC
