### ISSUE TITLE
Split Lines does not work with Show Vertical Edge set

### ISSUE THREAD

**Issue by helpdata** [notepad-plus-plus/notepad-plus-plus#5841] opened 2019-06-26 23:12 UTC
### Steps to Reproduce the Issue

1.  Use "show vertical edge" in preferences
2. Resize window to quite small, smaller than vertical edge
3. Split lines (Ctrl+I)
4. Does not work, lines are not split at size of window, but at width of page as set by vertical edge
5. Turn off "show vertical edge"
6. Repeat 2 and 3 above
7. Lines are split correctly.

### Expected Behavior
Expected lines to be split at window edge, as advertised.

### Actual Behavior
Lines split at vertical edge

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by sasumner** [comment] 2019-06-27 12:55
Verified, with:

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\..........\npp.7.7.1.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : ColumnTools.dll Explorer.dll LocationNavigate.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll 

I'm not sure where the way this works is "advertised" (@helpdata , do you know?), but I also have come to expect that it works the way the OP wants.

**Comment by helpdata** [comment] 2019-06-27 23:41
Just something I read. There are no official Help documents, so this may be expected behaviour

**Comment by sasumner** [comment] 2020-02-25 20:55
I'm going to close this, citing lack of evidence that it isn't working as intended.

I think the intent is:  "If there is a vertical edge set, split lines at that vertical edge column.  If no vertical edge is set, split lines using the current editor window width."

**Closed by sasumner** 2020-02-25 20:55 UTC
