### ISSUE TITLE
About cmake

### ISSUE THREAD

**Issue by zxmrlc** [notepad-plus-plus/notepad-plus-plus#4635] opened 2018-07-05 03:53 UTC
Hope to support parsing multiline annotations in CMakeLists.txt

**Comment by ArkadiuszMichalski** [comment] 2021-12-29 01:07
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2709.

**Closed by ArkadiuszMichalski** 2021-12-29 01:07 UTC
