### ISSUE TITLE
Win64 7.4 ver. installer  slow-slow starting

### ISSUE THREAD

**Issue by arolyer** [notepad-plus-plus/notepad-plus-plus#3275] opened 2017-05-15 14:34 UTC
Win64 7.4 ver. installer  slow-slow starting on win2016 (7.33 same OK)

**Comment by philippbeckmann** [comment] 2017-05-16 05:49
It seems the problem is related to commit e2329fd15c21e30013689d1911b464d34c7ddadd
NPP 7.4/Windows tries to download a certificate pack from ctldl.windowsupdate.com, which is blocked on our network.

**Comment by AngryGamer** [comment] 2017-05-18 04:28
Fixed in [v7.4.1](https://notepad-plus-plus.org/news/notepad-7.4.1-released.html)

**Closed** 2017-05-19 09:49 UTC
