### ISSUE TITLE
Scrollbar changes positions swapping tabs with word wrap

### ISSUE THREAD

**Issue by error17** [notepad-plus-plus/notepad-plus-plus#4825] opened 2018-09-05 04:37 UTC
### Description of the Issue

With word wrap on, and a document with lines that are split due to word wrap, with many lines so there is a scroll bar, if you swap to another tab and back, the scroll bar will be in a different position than where it was left.

### Steps to Reproduce the Issue

1. create a document with long lines and many lines.
2. scroll somewhere in the middle. Make sure the top is not on the starting line, but one of the split word-wrapped lines (best to have line number enabled so you can see starting lines).
3. swap tabs.

### Expected Behavior

The scroll bar should not move, should stay in the same position.

### Actual Behavior

The scroll bar will change where it is. If the top line is a new line, there is no issue; but if the top line is on a word-wrapped line, it will snap to starting line on tab switch, can be disorientating on very long lines that have been split into many word-wrapped lines.

**Comment by vertigo220** [comment] 2018-09-22 17:56
Came here to report this as well. It should ideally stay exactly where it was when switching, e.g. if it's showing lines 30-60, switching to another tab and back it should still be showing lines 30-60, not 24-54 or whatever. I'm constantly switching back and forth and this is constantly causing me to have scroll back to where I was. Otherwise, this is an amazing program, so thank you for it!

**Comment by Antti29** [comment] 2019-02-19 10:43
I think this was at one point fixed but a later update regressed it.

**Comment by bersbersbers** [comment] 2019-08-23 06:15
I agree: that earlier bug was #4571 (which itself was #2078, #2576, #264, #3261, #3570, #3015), and a current open duplicate is #4881.

**Comment by xylographe** [comment] 2019-08-23 09:50
The cause of this behaviour has been explained in [this comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4571#issuecomment-396406247).

It was fixed in commit 40192bda0ccbd18077abb02fac30292dfe8e62f4, and reverted in commit fdf954f714325b41a86b745f3e3525277ba17ca4, because the ‘cure’ caused [a serious permance issue](https://notepad-plus-plus.org/community/topic/16468/notepad-7-5-9-release/16).

**Comment by bersbersbers** [comment] 2019-08-23 12:10
Thanks for investigating! Would someone care to organize the heap of duplicates (see my previous post)? Because that list includes several open issues and even a closed, apparently fixed one (#4571).

**Closed** 2020-01-06 09:29 UTC
