### ISSUE TITLE
Reload file message - Google drive file stream

### ISSUE THREAD

**Issue by sandynayak** [notepad-plus-plus/notepad-plus-plus#5211] opened 2019-01-08 15:57 UTC
### Description of the Issue
Seeing a message to reload the file every time I save the file, thus disabling the action history (i.e. undo)

Here is a sample message:
---------------------------
Reload
---------------------------
"G:\My Drive\SomeTextFile.txt"

This file has been modified by another program.
Do you want to reload it?
---------------------------
Yes   No   
---------------------------
I think this is related to Google Drive File Stream (GDFS). 
It is possible that GDFS may be marking some meta data of the file making it appear that the file is modified outside Notepad++environment. 
I know I can disable the check of newer version. But that's not what I needed. The data within the file itself is not changed at all.

I have tried reinstalling from scratch (including removal of all plugins). But I think this has to do with GDFS adding some metadata so that the file is synced to the cloud.
If there is a way to identify such metadata changes by syncing apps, we might avoid seeing the redundant message box.

The files saved locally (without using Google drive File Stream) are not affected.

### Steps to Reproduce the Issue
1. Keep Google Drive File Stream (GDFS) open
2. Find any file saved in GDFS and open in Notepad++
3. Make any simple change in the file (as simple as adding a new line)
4. Save the file

### Expected Behavior
1. Save action would save the file. 
2. I should be able to undo previous actions (whatever I have edited).

### Actual Behavior
1. Save action saves the file. But prompts an extra message to reload the file
2. No previous action available for UNDO

### Debug Information
Notepad++ v7.6.1   (32-bit)
Build time : Dec 12 2018 - 01:24:22
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll XMLTools.dll

**Comment by SinghRajenM** [comment] 2019-04-12 16:33
@MetaChuh commit 198cf90c164814802cf25e1bb68942adf43e4b7c implements undo for reloaded files too. So I feel, we are ok to close this issue.

**Comment by sandynayak** [comment] 2019-04-12 16:45
Thanks, I verified that UNDO works now with v7.6.6. 
The cursor doesn't seem to be in the same place though, but I don't think it's a big deal

**Comment by paulbays** [comment] 2019-08-15 11:00
I am having precisely this issue using Notepad++ v7.7.1 (32-bit). When I save a file on GDFS I get a prompt to reload it. If I click Yes, the undo history is lost. In what sense was this resolved? Thanks.

**Comment by xylographe** [comment] 2019-08-15 11:51
I think, the undo for reloaded files was reverted, because it turned out to be a memory clog.

**Comment by paulbays** [comment] 2019-08-16 08:57
I can confirm xylographe's response - reverting to v7.6.6 and enabling "quiet" re-loads in preferences makes the warnings disappear and preserves undo history after save. Obviously this isn't a long-term solution and doesn't address the root cause. Does anyone know what is at the root of this problem? At a guess, GDFS in some way treats file tags differently from the regular Windows file system, causing Notepad++ to believe its own save operation is a change to the file made by another user. I've seen the same problem with just one or two other applications (e.g. TeXworks), but the vast majority work fine with File Stream, so it seems that Notepad++ could and should be patched to fix this. Thanks.

**Comment by insane4sure** [comment] 2019-09-20 11:29
Version 7.7.1, same behavior (reading above, it seems this issue was resolved, then the resolution was reverted).  I request @sandynayak reopen this issue please, as it perfectly describes the problem and steps to reproduce.

**Comment by sandynayak** [comment] 2019-09-20 13:43
reopening as per @insane4sure

**Comment by repl-raymond-bolander** [comment] 2019-12-04 17:25
I've also observed this happening with GFS. 

**Steps**

- Create a text file
- Write some content to the file in Np++
- Save it
- Prompt that the file has been modified

**Comment by sasumner** [comment] 2020-09-29 17:04
Closed, refer to #5863

**Closed by sasumner** 2020-09-29 17:04 UTC
