### ISSUE TITLE
Cannot move tabs with mouse any more in 7.3.3

### ISSUE THREAD

**Issue by SimonSteinberger** [notepad-plus-plus/notepad-plus-plus#3194] opened 2017-04-21 11:15 UTC
Having opened multiple files, as of version 7.3.3, I can no longer move tabs by dragging them with the mouse to a new position.

OS: Windows 10 (64 bit)
Notepad++: 7.3.3 (32 bit)

**Comment by AngryGamer** [comment] 2017-04-21 15:02
Dupe [#3108](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3108) [#3055](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3055) [#3016](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3016)

Already fixed in future versions. Use the build I posted [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3108#issuecomment-290947032) until v7.3.4 is released.

**Comment by MetaChuh** [comment] 2019-05-01 22:46
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:46 UTC
