### ISSUE TITLE
Find In Files dialog: Alt + R - keyboard shortcuts do not work.  

### ISSUE THREAD

**Issue by CarlosOnline** [notepad-plus-plus/notepad-plus-plus#7638] opened 2019-11-21 19:50 UTC
### Description of the Issue
Find In Files dialog: Alt + R - keyboard shortcuts do not work.  

**Not a duplicate** of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6223

### Steps to Reproduce the Issue
1. Ctrl + Shift + F to bring up Find In Files dialog
2. Click on **Find In Files** tab
3. Alt + R - **Replace in Files**

![image](https://user-images.githubusercontent.com/3691895/69371305-73ee3a80-0c54-11ea-89eb-d9b44d114300.png)

### Expected Behavior
Expect replace in files to be clicked.

### Actual Behavior
Nothing happens

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2019-11-21 20:32
Thank you for creating a new issue for the second half of your earlier issue (#7614).  It is best when reporting issues to break them down for easier handling.  Of course, your opinion may be that you should pack as many keyboard-related things as you can into one issue. :-)  But it I think it might be clear to most Notepad++ users that your original two issues were unrelated.

The reason this doesn't work is because alt+r is also mapped to the `Replace` button in the `Replace` tab.  The 4 tabs of this window all _share_ the accelerator key functionality so there can be no duplication across the tabs, or, as you've found, certain things won't work.  Unfortunately, all of the characters in `Replace in Files` are already used as accelerator keys for other functions across the 4 tabs of the window, so an obvious replacement and easy correction is not, well, easy.

Important (and thankful) note:  Pressing alt+r while viewing the `Find in Files` tab will NOT run the `Replace` function on the `Replace` tab.

The "best" correction for this issue might be to remove `&amp;` in front of the R in `Replace in Files` in english.xml.  However, that would leave that function with no accelerator key (so it is only a slight improvement over existing behavior -- which is misleading because a user will _think_ it will work -- but there would still be no keyboard accelerator for this function).

The best advice to help a user befuddled by this is my earlier advice in the other issue: `...you can follow the procedure in the comments of the referenced issue to add/change keyboard shortcuts` yourself.  What this means in more detail is that you can open english.xml and search for `&amp;Replace in Files`.  You can then change this text to something else that makes sense, perhaps `Replace&amp;-in-Files`, and then the button will appear like this:

![image](https://user-images.githubusercontent.com/30118311/69374077-4bc20400-0c73-11ea-81e3-979e8a0e723a.png)

and when you press alt+- it will run the function (after following the further details about user-changes of keyboard accelerators in the referenced issue -- I don't want to repeat all that minutiae here).

**Comment by sasumner** [comment] 2019-11-21 20:44
My response should have been:  "Closing as duplicate of #3539".  :-)

**Closed by sasumner** 2019-11-21 20:44 UTC
