### ISSUE TITLE
Notepad++ goes to default state after restarting

### ISSUE THREAD

**Issue by Nhalrath** [notepad-plus-plus/notepad-plus-plus#10097] opened 2021-07-02 13:38 UTC
### Description of the Issue
(A) - Preference does not apply after restarting the program.
(B) - Directory/Workspace are not opened automatically after restarting.

### Steps to Reproduce the Issue
(A)
1. Set the options on the preference tab.
2. Close the application and open it again.

(B)
1. Open a directory as a workspace.
2. Close the application and open it again.

### Expected Behavior
(A) - Preference are applied after restarting. Opened in fullscreen(maximize) mode if it was closed in the same state.
(B) - Folders/Workspaces that are opened before closing are automatically reopened after
opening the application.

### Actual Behavior
(A) - Notepad++ has the same theme and behavior as the first time it was opened. Windowed screen.
(B) - No Folder/Workspace nor files are opened, but the works can be saved just fine.

### Debug Information
Notepad++ v8.1   (64-bit)
Build time : Jul  2 2021 - 20:01:05
Path : C:\Program Files\Notepad++\NotepadPP.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home Single Language (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 932
Plugins : none

### Additional notes
Built Notepad++ with MinGW-GNU Make 4.2.1 as instructed [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/BUILD.md#build-64-bits-binaries-with-gcc).

**Comment by ArkadiuszMichalski** [comment] 2021-07-02 13:49
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9163.

**Closed by ArkadiuszMichalski** 2021-07-02 13:49 UTC
