### ISSUE TITLE
File is erased on save when there is no free space left on disk

### ISSUE THREAD

**Issue by pnedev** [notepad-plus-plus/notepad-plus-plus#5664] opened 2019-05-17 08:34 UTC
### Description of the Issue

Saving file when there is no free space left on disk leads to erasing it and data loss.

### Steps to Reproduce the Issue

1. Open existing text file from completely full disk (no free space left)
2. Add several lines.
3. Save the file.

### Expected Behavior

The expected behavior is to report error while saving (`Save failed` or `No space left on disk`) but to retain the initial file data (just as it was before opening and editing it).

### Actual Behavior

The save fails but the file is emptied so all its data before the edit is lost.

### Root cause
The problem is caused by
`FILE *fp = UnicodeConvertor.fopen(fullpath, TEXT("wb"))`
in `FileManager::saveBuffer`

`fopen` with `wb` mode opens the file for writing but if the file exists ERASES ALL ITS DATA.

On the following `fwrite` failure the erased data is not recovered, the file is closed and left with zero size (data is lost).

### Possible solutions
1) Try saving the file under different name in the same folder. Only when the save is successful erase the original file and rename the new one to the original name.

2) Examine the free space left on disk BEFORE opening the file for writing with `fopen`. If there is not enough space DO NOT open the file and immediately return with error `Not enough space`. `GetDiskFreeSpaceEx` WinAPI function can be used to get the remaining free space.

### Notes on solutions
Solution 1 requires enough free disk space to save the copy of the file and this might be a problem in some cases (saving very big file in almost full disk).
For example if the disk is full, we open file from it for editing, we delete portion of it (actually reducing its size) and try saving it, solution 1 will fail (no space on disk for new copy) but solution 2 might be implemented to work in that case.

**Comment by gstavi** [comment] 2020-03-19 06:27
The solution of "Try saving the file under different name ..." will introduce another problem: the new file may will be created with default permissions while the old one may had specific permissions.

Duplicating permissions into the new file is very tricky, especially over network shares that may bring other operating systems into the problem. It may even be possible that the user is not allowed to create a new file with the exact permissions even though it is allowed to modify the original file.

Specific case is when working on unix-like files, e.g. via SAMBA, and editing script files that need the "execution" flag set.

Thinking as i write, the file must be in the same directory to stress the same file system and it may even be possible that a user is allowed to create new files but not to delete them afterward.

So I guess a good approach would be:
1. Calculate the required new size.
2. Open file for modification.
3. Enlarge/shrink the existing file to the new size.
4. Set file pointer to 0 and write the new content

**Comment by donho** [comment] 2020-10-12 19:55
> Steps to Reproduce the Issue
1. Open existing text file from completely full disk (no free space left)
2. Add several lines.
3. Save the file.

Is there any way to build such extreme environment for reproducing the bug?

**Comment by ArkadiuszMichalski** [comment] 2020-10-12 20:00
A small flash memory that will be full? I'll check it later.

**Comment by donho** [comment] 2020-10-12 21:45
@ArkadiuszMichalski Hard to find a "small" usb drive nowadays.

**Comment by ArkadiuszMichalski** [comment] 2020-10-12 22:27
Yes, but it's not invasive, you don't need to create/change partition in your live system (maybe a virtual machine be a solution). OK, I test this on 8GB flash and can confirm, the file is cleared on saving (when flash is full).

**Comment by donho** [comment] 2020-10-12 23:43
I managed to have a small drive and after saving failure, I don't have empty file but a file trunked - so indeed it's a critical bug.

**Comment by pnedev** [comment] 2020-10-13 08:52
I also tested it on my side (both the bug and the fix) using small size ramdrive.

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 08:59
@pnedev @donho I still have this USB for testing, so I can verify the PR (if working or not), but give me a link to the .zip package.

**Comment by sasumner** [comment] 2020-10-14 11:36
@ArkadiuszMichalski 

>but give me a link to the .zip package.

There is no "zip package".

Click the checkmark here:
![image](https://user-images.githubusercontent.com/30118311/95983472-a9ad8c00-0def-11eb-92d9-64b764d874c3.png)
and then click Details
and go from there....

Get the exe (no need for DLL) and put the exe in a folder with a freshly unzipped portable 7.9.

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 11:53
Thanks, I did not know about such a possibility. For this PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8992 it works for me, when I try add something to file (and there is no more space in flash) then after save my file doesn't change (still has its original content).

**Comment by sasumner** [comment] 2020-10-14 11:55
>after save my file doesn't change (still has its original content).

Is there indication to the user that such a thing has happened?

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 12:04
Currently no, and that's the problem, because the buffer shows the changed / saved content, but when I close the tab and reopen my file, I have the previous content.

**Comment by pnedev** [comment] 2020-10-14 12:41
Thanks @sasumner ,
Thanks for helping @ArkadiuszMichalski .

@ArkadiuszMichalski ,
Thanks for testing on your side.
So you confirm that https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6e857923579a4244e69f69009e7a49588e44bc6b works OK in your test?

**Comment by pnedev** [comment] 2020-10-14 12:43
@ArkadiuszMichalski ,

One more thing.

> Currently no, and that's the problem ...

You mean that when there is no space left on device you don't get dialog popup saying that the file save was unsuccessful?

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 12:48
Yes, for flash/usb your fix works fine. Some dialog would be helpful, because now when I press save then red icon became blue, and this suggests that the changes have been saved, but after reloading (or closing/open file once again) we have old content. Well, at least it's not empty right now.

In the case of RAM disks, network disks or partitions, I do not know, it should also be checked.

**Comment by pnedev** [comment] 2020-10-14 13:16
Thanks.
I tested with RAM disk, it showed notification dialog that disk was full and the file tab remained marked 'red' (like unsaved document in Notepad++. After a while Notepad++ also popped-up a prompt to reload file because it appeared modified outside the editor.
The strange thing is that even without the change on RAM disk the behavior is the same.

**Comment by pnedev** [comment] 2020-10-14 13:31
What should happen is:
1) If you add additional data to the file and you hit 'Save' then if no error is reported the new file contents should be OK (written successufy)
2) If there is no more space left on device you should get error pop-up and the file should remain as if unsaved (red tab). The original file shouldn't be erased.

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 14:01
@pnedev For your fix I still can reproduce empty file, look for my 2. case above. I see this cases (let say that our test file is empty when open for edit):
- when I add less data and when they can be saved they are saved
- when I add maximum data that can be saved they are saved
- when I add maximum data + some more (one, two, three...) I get empty file.
- when I add maximum data + 7x maximum data I get prompt.

Maximum data in my test case is:
```
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbccccccccccccccccccccdefgaaaa
```

And I also get different results when my test file is not empty when load them to Notepad++.  Sometimes I can get truncated file, like @donho mention above. But I haven't tested this case precisely.

**Comment by pnedev** [comment] 2020-10-14 14:09
@ArkadiuszMichalski ,

> let say that our test file is empty when open for edit

What do you mean by that?
The file didn't exist at all or it had zero size?

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 14:11
File exist, but it's empty, it's important, because for not-empty file I don't see this bug.

**Comment by pnedev** [comment] 2020-10-14 14:17
I have to test this on native Windows.
My tests on Linux under Wine always show the file contents are preserved.

**Comment by donho** [comment] 2020-10-14 14:26
I use VeraCrypt to create a disk, then mount it as a drive, I have the different result - file truncated.
I tried Notepad, when it cannot save, it pop up save as dialog and keep the file intact - I think it'll be good to not modify file and pop up a no more room warning.

**Comment by ArkadiuszMichalski** [comment] 2020-10-14 16:23
@donho For your https://github.com/notepad-plus-plus/notepad-plus-plus/commit/469fa62c0ebc438c8003c735e6a801c6d098df7 I still get an empty file. Let say we have test file with small content (one char), then: 
1. when I add less data and when they can be saved they are saved
2. when I add maximum data that can be saved they are saved
3. when I add maximum data + some more (one, two, three...) I get empty file, without any prompt.
4. when I add maximum data + 7x maximum data I get prompt (the file is not cleaned).

So it works less correctly than https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8992 (which only doesn't display the prompt for 3. case).

**Comment by pnedev** [comment] 2020-10-14 21:29
@ArkadiuszMichalski ,

Good idea to test several other well known editors, thanks. 👍

**Comment by donho** [comment] 2020-10-17 02:19
@ArkadiuszMichalski 
> For your 469fa62 I still get an empty file. Let say we have test file with small content (one char)

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/469fa62c0ebc438c8003c735e6a801c6d098df7 has fixed absolutely nothing. I tried to clean up this function and make it more readable.

> in SciTE we get prompt that file can't be save, but after click OK our file is also cleans!

I have tested SciTE and the file was truncated as well.  I'm not surprised the same behaviour for the other editors  - it's a dilemma such situation.

>  in Notepad we get prompt that file can't be save and we can save it in other place, but our file is not clean.

If you open the same file in both Notepad++ and Notepad, then modify the file only in Notepad and save it - Notepad++ will tell you the file has been modified outside and ask you to reload it. It means Notepad has saved the file but failed, then it restore the file (with a backup?).

**Comment by pnedev** [comment] 2020-10-17 09:15
@donho ,

> If you open the same file in both Notepad++ and Notepad, then modify the file only in Notepad and save it - Notepad++ will tell you the file has been modified outside and ask you to reload it. It means Notepad has saved the file but failed, then it restore the file (with a backup?).

I tried this scenario on Windows 10 with full USB flash drive and couldn't reproduce it.
MS Notepad simply prompts you to save the file elsewhere and that's it. File is not erased and Notepad++ does not ask you to reload the file because it is modified outside.
Maybe something in your test setup is happening in the background that is hidden from you. Virtual drive might have some specifics (buffering or internal sync-up, I have no idea).

But you are right - my PR (https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8992) didn't work on my native Win10 test either.

**Comment by ArkadiuszMichalski** [comment] 2020-10-17 10:58
@donho @pnedev
OK, I see that Win7 and Win10 has differen behaviour. When I switched to Win10 my full flash drive suddenly got 3.5MB more space, some magic, but let's go back to testing.

In fact, in Win10, the file is truncated, but it still depend how many data you add (above maximum), if you add less data is truncated, if you add to much you get prompt and file is cleaned.

And yes @pnedev , in Win10 your fix  didn't work. 

@ donho
>If you open the same file in both Notepad++ and Notepad, then modify the file only in Notepad and save it - Notepad++ will tell you...

I also can't reproduce this (in both Win10/Win7), I get prompt in Notepad but nothing in Notepad++ (maybe your prompt in Notepad++ came from other changes?) Are you sure Notepad performed a file change when a dialog box appeared? It is worth checking the last modification date of the file. Well, but it can also result from the container in Verracrypt.

A potential repair (if it ever appears) must be tested in various scenarios. If necessary, I still have virtual machines with WinXP, Win7 and Win10 (I can investigate the behavior on small partitions).

**Comment by donho** [comment] 2020-10-17 11:38
> Are you sure Notepad performed a file change when a dialog box appeared?

Yes. Switching back to Notepad++ **before** canceling "Save as" of Notepad gives the following screenshot:

![image](https://user-images.githubusercontent.com/90293/96335745-040e4d00-107b-11eb-97ce-f4f8ee344e56.png)

>  It is worth checking the last modification date of the file.

Yes, the modification date has been changed:
Before: 
‎Saturday, ‎October ‎17, ‎2020, ‏‎1:19:44 PM
After:
‎Saturday, ‎October ‎17, ‎2020, ‏‎1:32:18 PM

>  Well, but it can also result from the container in Verracrypt.

I don't think so. The disk is mounted as a normal disk. Verracrypt does the encrypt stuffs before the disk is unmounted.

**Comment by ArkadiuszMichalski** [comment] 2020-10-17 12:00
@donho But we consider the situation in Notepad when we add too much data and the dialog pops up to save elsewhere? Not when do we modify the current data that can be saved?

**Comment by donho** [comment] 2020-10-17 13:35
@ArkadiuszMichalski 
Here's what's happening when Notepad++ writes data on a no more room disk:
`Save command -> write to disk -> error -> close -> POSIX function alters the content`

No idea which API for file IO in Notepad is used.
But if it use the same API (POSIX) as Notepad++, I guess the scenario is:
`Save command -> backup the file -> write to disk -> error -> close -> POSIX function alters the content.-> restore the backup`

**Comment by ArkadiuszMichalski** [comment] 2020-10-17 13:48
I'm trying to reproduce this prompt in Notepad++ when in Notepad we are trying save to much data, but without result. My original file is not modified (recreated), I still see same create/modified date for this file. Some other factor must influence this, like the system version or medium with a file.

**Comment by pnedev** [comment] 2020-10-17 19:53
@donho ,

> Switching back to Notepad++ before canceling "Save as" of Notepad gives the following screenshot:

Hm, I'll have to test this as you suggest **before** closing the save dialog.

Anyway,
I created another PR that is working fine now:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9024

It is based on https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8992 because I believe it is the right approach to deal with this problem but I tested it with Notepad++ 7.9 32bit on Win10 (64bit) and on my setup behaves exactly as supposed to.

@donho ,
`_chsize_s` is called ONLY when it needs to be called (when the file is shortened/shrunk).

**Comment by donho** [comment] 2020-10-18 08:40
Thank you @pnedev. I will check your PR.

**Comment by pnedev** [comment] 2020-10-18 09:48
> I'm trying to reproduce this prompt in Notepad++ when in Notepad we are trying save to much data, but without result.

I get the same behaviour as @ArkadiuszMichalski (tried on full USB drive with Notepad++ 7.9 32bit, PR https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9024 on Win10 64bit).

**Comment by ArkadiuszMichalski** [comment] 2020-10-21 14:06
@pnedev I check your last fix in Win10 with flash and see this:
- when I add less data (above maximum) file is still truncated. I don't like this, because if new data will be added before the end of the file, then data from the end of the file will be lost.
- when I add more data (above maximum) then I get prompt and  original file on the flash is not changed.

**Comment by pnedev** [comment] 2020-10-23 13:34
@ArkadiuszMichalski ,

I couldn't reproduce the issue you experience.
Could you tell me what is your test setup?

On Win10 64bit with Notepad++ 7.9 32bit when I add a little more data to the file on the almost full USB stick and I save it,
it looks like the file is saved but when I reload it, it appears not all new data is there. The file is definitely not zero, it is just written to the maximum capacity of the disk.
It appears that the system not always returns write error if you surpass the disk capacity slightly. Maybe the data is written in clusters (of 1KB maybe?). There is nothing I can do about that - it is the system and the API that do not report that not all the bytes were written.
But the file is NOT wiped to zero size no matter how much you enlarge the file. At least in my test.

Thanks for testing.

**Comment by ArkadiuszMichalski** [comment] 2020-10-23 14:05
I use this steps https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5664#issuecomment-708513160. In detail:
- take small USB and full it (with zip or audio/video and small files from NPP folders)
- now when I can create only one file I create it, and add some data to easy test, but max that can be saved without any problem, like:
```
aaaaa
bbbbb
ccccc
ddddd
````
- Now I test your PRs with this case:
  - add some chars after `ddddd` (even one) << this doesn't generate prompt
  - add more data after `dddd`, just few times copy/past all actuall data << this generate prompt
  - add some chars before last `ddddd` << this make truncated in Win10, we don't get prompt and we lost data from the end of the file (depending on how much we add before).

When you create this full file for test then copy it somewhere to restore it quickly when NPP will clean this file in USB.

Maybe is worth also test situtation where we remove `ddddd` and we add somore more data, like 2x`ddddd`. Generally, I only test it on the full file, but it is worth extending the test.

The interesting thing is that Notepad somehow works in any case, and in my case it doesn't do it with buckup/restore file.

**Comment by sasumner** [comment] 2020-10-24 10:30
FYI, a recent, related user experience:
![image](https://user-images.githubusercontent.com/30118311/97079500-69ee5d80-15c2-11eb-9074-b4c984e607b4.png)

**Comment by pnedev** [comment] 2020-10-26 15:24
@ArkadiuszMichalski .

> add some chars before last ddddd << this make truncated in Win10, we don't get prompt and we lost data from the end of the file (depending on how much we add before).

So the file is not 0 size but the data that didn't fit in the remaining disk size got lost. Unfortunately that is something we cannot prevent. At least not with the approach used in this PR. We'll need to make additional copy (which is overkill IMO).
So the current PR works well in preventing the zero size problem (preserving the data that fitted in the remaining disk size).

> The interesting thing is that Notepad somehow works in any case, and in my case it doesn't do it with buckup/restore file.

I suppose Notepad uses directly Win32 API (no CRT - as in my first PR fixing this issue) and perhaps also checks remaining disk size before writting the new data.

Thank you for testing 👍 

@sasumner ,

> FYI, a recent, related user experience

Yes, that is a nasty problem but unfortunately I cannot do anything more.

Maybe I'll try one last approach (very ugly one but probably it will have a chance to pass @donho 's criterion of "_don't touch anything that is supposedly working_"). If it works it will be better than nothing I suppose.

**Comment by KnIfER** [comment] 2021-06-16 10:13
如果用“边读边写”的模式打开并写入文件（比如`fopen(..., "r+c")`），那么将总能得到正常或被截断的数据。

如果使用“先清除，后写入”的方式打开文件（比如`fopen(..., "wbc")`），向已满的U盘写入更多数据时，在我的笔记本电脑上，会导致文件大小突然变成零，不仅NPP，VSCODE也如此。

___

If you open and write a file using  `fopen(..., "r+c")`, you will always be able to get the normal or truncated data saved.

If you open and write a file using `fopen(..., "wbc")`, and write more data (8kb for an example) to a full disk storage, On my laptop, the file will suddenly become empty (zero byte).

**Comment by donho** [comment] 2021-09-19 15:00
@KnIfER 

The fix with `c` argument has been added since 1 year ago:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a1031517742c7ef600b825bf9f193b3f2740dff6

But it doesn't fix the problem completely.

**Comment by donho** [comment] 2021-09-19 15:11
@pnedev 
Does this bug still persist ?

**Comment by pnedev** [comment] 2021-09-20 07:20
@donho ,
Yes, this bug is NOT fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/a1031517742c7ef600b825bf9f193b3f2740dff6

@KnIfER  is not talking about the `c` flag but about `wb` vs. `r+` - open in 'write' vs. 'append' mode.

**Comment by donho** [comment] 2021-09-28 14:06
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/9aa9ecb664bd03f3a61cc42891f125492767e066

**Comment by Nico128** [comment] 2021-11-20 08:38
I had this bug today. I lost my python script. Is it possible to recover it ? There is no backup in the backup folder.

Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1165
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll

**Comment by pnedev** [comment] 2021-11-20 23:14
@Nico128 ,

Unfortunately you cannot recover your file, at least I'm not aware of such possibility.
I am sorry for your lost work. This bug is fixed after Notepad++ v8.1.5 (I would recommend you to get the latest possible version - it is 8.1.9.1 at the moment of writing this post).

**Comment by Nico128** [comment] 2021-11-30 21:28
> @Nico128 ,
> 
> Unfortunately you cannot recover your file, at least I'm not aware of such possibility. I am sorry for your lost work. This bug is fixed after Notepad++ v8.1.5 (I would recommend you to get the latest possible version - it is 8.1.9.1 at the moment of writing this post).

Thank you I installed the new version.
The different applications I use to find erased files didn't find anything...unfortunately.
When a document is modified but not saved yet, there is a copy in the notepad/backup/ folder every x seconds. When the document is saved, the backup is removed. That's strange because with the tools to find erased file, I wasn't able to find anything in the backup folder neither...

**Comment by donho** [comment] 2021-12-02 15:01
Due to https://github.com/notepad-plus-plus/notepad-plus-plus/commit/12a13b1c0a276cef0a101d5ada1f98ad878012d5 which has reverted the fix of this issue, it's reopened.

**Comment by xomx** [comment] 2023-09-09 00:38
Another report: #14089

**Comment by donho** [comment] 2023-09-10 21:01
Fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14134

**Closed** 2023-09-12 12:51 UTC
Labels: bug, accepted
