### ISSUE TITLE
C# syntax color, string literal formatted as VERBATIM style

### ISSUE THREAD

**Issue by wardboumans** [notepad-plus-plus/notepad-plus-plus#641] opened 2015-08-04 13:45 UTC
string x = "test";  // is formatted as STRING style
string y = @"test"; // is formatted as VERBATIM style

**Comment by dail8859** [comment] 2015-08-04 13:54
Looks like this issue also shows up in SciTE, meaning it is a problem with Scintilla.

![capture](https://cloud.githubusercontent.com/assets/3694843/9062157/9183316e-3a8e-11e5-86a5-9a285db297f6.PNG)

You might want to file that bug over [here](http://sourceforge.net/p/scintilla/bugs/) if it has not been reported yet.

**Comment by JustFogMaxi** [comment] 2015-08-05 05:41
Ow god, sourceforge. Im not signing up out just for that, im sorry.

**Comment by dail8859** [comment] 2015-08-05 10:39
I don't blame you. Not sure if they have a mailing list or something  you could use in instead.

**Comment by milipili** [comment] 2016-06-24 02:11
Fixed in the latest version maybe ?

**Comment by dail8859** [comment] 2016-07-19 02:08
@milipili Issue is still present in Scintilla v3.6.6

**Comment by MetaChuh** [comment] 2019-04-11 00:11
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:11 UTC
Labels: enhancement, language-support
