### ISSUE TITLE
Open dialog: when pasting a complete UNC (\\server\share\...) path into the file name box, all but one leading backslash are removed when pressing enter.

### ISSUE THREAD

**Issue by notYetLost** [notepad-plus-plus/notepad-plus-plus#9582] opened 2021-02-25 20:22 UTC
### Steps to Reproduce the Issue

1. Ctrl-o (Open dialog)
2. Enter UNC path to some file on some file share (\\myServer\myShare\folderx\myFile.xml)
3. Press ENTER: 
### Expected Behavior

File is opened from server.

### Actual Behavior

you see one leading backslash removed, followed by an error message

### Debug Information

Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.804
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll HexEditor.dll HTMLTag.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll NppQrCode64.dll NppXmlTreeviewPlugin.dll RegexTrainer.dll SQLinFormNpp64.dll XMLTools.dll

**Comment by sasumner** [comment] 2021-02-25 20:36
Known issue: #9527
To be fixed in next release.

**Closed by sasumner** 2021-02-25 20:36 UTC

**Comment by jonnyt1978** [comment] 2021-03-15 11:59
@sasumner Just tested in 7.9.4 (64-bit official release) and the issue @notYetLost still occurs

**Comment by sasumner** [comment] 2021-03-15 12:10
@jonnyt1978 

I can't agree; what I try works for me to open a file.
Here's what I tried:

![image](https://user-images.githubusercontent.com/30118311/111151417-d19f4800-8565-11eb-8389-fca3a7e099fe.png)

Maybe it helps to show exactly what isn't working for you.

**Comment by jonnyt1978** [comment] 2021-03-15 12:51
> @jonnyt1978
> 
> I can't agree; what I try works for me to open a file.
> Here's what I tried:
> 
> ![image](https://user-images.githubusercontent.com/30118311/111151417-d19f4800-8565-11eb-8389-fca3a7e099fe.png)
> 
> Maybe it helps to show exactly what isn't working for you.

Hello @sasumner, thanks for your reply. I've performed some additional testing and can be more specific:

If the full path I copy & paste into the 'File name:' text box is enclosed in quotes (I have tried " ' and ` ) then the first backslash of the path is removed, and the error dialog appears reflecting this, as per the original issue.

**Comment by jonnyt1978** [comment] 2021-03-15 12:54
Screenshot of error:

![notepad error 2](https://user-images.githubusercontent.com/71005706/111156409-9d3f8200-858d-11eb-92a7-0cbdc73984a6.png)

**Comment by sasumner** [comment] 2021-03-15 13:02
@jonnyt1978

Yes, that I can confirm; here's mine:

Input right before error:

![image](https://user-images.githubusercontent.com/30118311/111156645-5e4d0480-856c-11eb-91c9-68caec6e41cb.png)

What happens after attempting to open the `Junk` (folder):

![image](https://user-images.githubusercontent.com/30118311/111156744-791f7900-856c-11eb-8a40-eca9a9b9c0de.png)

Curious, though, why does yours stop at `change` and not show the `.log"` part (in the _File name_ box).

The obvious workaround for now is to NOT use any double-quoting in the argument value.  It isn't necessary in the _File name_ box anyway.

@mere-human Is the best course of action here to reopen this specific issue and assign to you?  (I know you love all the fallout from the dialog changes).

**Comment by jonnyt1978** [comment] 2021-03-15 13:30
@sasumner Thanks for confirming. Additional feedback:

If I try to open:
"\\127.0.0.1\c$\Program Files\Notepad++\change.log"

It changes to:
"\127.0.0.1\c$\Program Files\Notepad++\change
(note the lack of a trailing " )

If I try to open browse to:
"\\127.0.0.1\c$\Program Files\Notepad++\"

It changes to:
"\127.0.0.1\c$\Program Files\Notepad++\"

Both work ok without quotes

**Comment by mere-human** [comment] 2021-03-15 20:16
@sasumner @jonnyt1978 
So, what causes trouble here is the fix for #5368 which I carefully ported to the new dialog.
The issue says that the Notepad++ (version 7.9.1 or earlier) is stuck when trying to open a path like `C:\\` . 
Note this _Preferences > Default Directory > Use new style dialog_ is ON for the mentioned issue.

What if we won't try to do anything to double backslash? And follow the behavior of the "new style" dialogs more strictly?
Notepad refuses to open `C:\\`. The behavior in Notepad++ 7.9.1 with _Use new style dialog_ OFF is the same.

![image](https://user-images.githubusercontent.com/9664141/111215008-4cef1100-85db-11eb-9a86-d18d5c85a20f.png)

I can fix this one more time. But honestly, this weird hack for double backslash causes more trouble than value as for me.
And in the original issue the intended behavior wasn't even specified. So everything that is "not stuck" seems good to me.

**Comment by sasumner** [comment] 2021-03-15 20:59
@mere-human 

If I were you, I'd get rid of the "weird hack"  :-)
