### ISSUE TITLE
Save 'Folder as workspace' in session

### ISSUE THREAD

**Issue by nelisse** [notepad-plus-plus/notepad-plus-plus#9165] opened 2020-11-16 07:11 UTC
### Save 'Folder as workspace' in session
When saving a session the 'Folder as Workspace' items are not saved in the session

### Steps to Reproduce the Issue

1. Add some 'Folder as workspace' items
2. Save the session
3. Remove some 'Folder as workspace' items
2. Load the recently saved session

### Expected Behavior
Same 'Folder as workspace' items present after a loading session, as when the session was saved

### Actual Behavior
The  'Folder as workspace' items as when the session was saved are not present when the session is loaded.

**Comment by donho** [comment] 2020-12-21 23:18
I'm not sure it's a expected behaviour for some people.
Some users may only want the last state of Folder as workspace, without being interfered by session.

**Comment by mere-human** [comment] 2020-12-24 17:01
> I'm not sure it's an expected behaviour for some people.
> Some users may only want the last state of Folder as workspace, without being interfered by session.

We might customize a "Save As" session dialog and add a checkbox that says "Include workspace" ☑
It could be off by default.

**Comment by donho** [comment] 2020-12-24 18:24
@mere-human 
> We might customize a "Save As" session dialog and add a checkbox that says "Include workspace" ☑
It could be off by default.

That's an acceptable solution. But the "Save As" dialog for session is the system dialog, I wonder if it's easy to add a checkbox.

**Comment by mere-human** [comment] 2020-12-26 22:40
@donho 

> @mere-human
> 
> > We might customize a "Save As" session dialog and add a checkbox that says "Include workspace" ☑
> > It could be off by default.
> 
> That's an acceptable (and good) solution. But the "Save As" dialog for session is the system dialog, I wonder if it's easy to add a checkbox.

I can see that Notepad++ [uses ](https://github.com/notepad-plus-plus/notepad-plus-plus/tree/master/PowerEditor/src/WinControls/OpenSaveFileDialog/FileDialog.cpp) GetOpenFileName() and GetSaveFileName() functions along with OPENFILENAME struct.
I didn't find a way to customize that otherwise than show/hide some of the predefined parts (like directory tree).

However, there is an option to do the customization with a [Common Item Dialog API](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb776913(v=vs.85)) that is available starting from Windows Vista.
It allows adding custom controls to the file dialog.

The customized dialog looks like this on Windows 10:
![image](https://user-images.githubusercontent.com/9664141/103160214-b3357600-47da-11eb-9254-754bc5f47a38.png)
Here I created a sample dialog and added a checkbox to it.

Compare it to the Notepad++ save session dialog:
![image](https://user-images.githubusercontent.com/9664141/103160217-bcbede00-47da-11eb-9b67-fe9a8b69307c.png)

It makes sense to rewrite FileDialog class to use new Common Item Dialog API IMHO. That might solve some of the existing and future issues. Microsoft [recommends](https://docs.microsoft.com/en-us/windows/win32/dlgbox/open-and-save-as-dialog-boxes) to use this new API going forward:

> Starting with Windows Vista, the Open and Save As common dialog boxes have been superseded by the Common Item Dialog. We recommended that you use the Common Item Dialog API instead of these dialog boxes from the Common Dialog Box Library.

I understand, that there might be some other concerns like supporting versions before Windows Vista or something else.

**Comment by donho** [comment] 2020-12-27 02:54
@mere-human 
> It makes sense to rewrite FileDialog class to use new Common Item Dialog API IMHO. 

That's good.

I just checked your [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9286) again, and realized 2 incoherent behaviour (so far) in your implement:
1. I save a session with 3 opened files a, b & c + FaW (Folder as Workspace) with 2 folders X & Y opened.
2. Then I close 3 opened files, remove X & Y from FaW and add Z in FaW. 
3. Close FaW.
4. Reload Save Session.

You will observe these 2 incoherent behaviours: 
1. FaW is not reopened automatically with X & Y
2. even you open FaW manually, Z is opened instead of X & Y

That's the incoherence we (at least I) cannot solve, if we save FaW's info in both config.xml and saved session's xml files.
What's your solution about such incoherence?

**Comment by sasumner** [comment] 2020-12-27 12:44
@mere-human said:

>Compare it to the Notepad++ save session dialog:

Your comparison is a bit "apples & oranges".  Meaning that if you go to _Settings_ > _Preferences_ > _Default Directory_ and tick the box for _Use new style..._, you'd get a much more "apples & apples" comparison, example:

![image](https://user-images.githubusercontent.com/30118311/103171031-ebf34080-4816-11eb-8c9b-9457b365554e.png)

This in no way invalidates your statement:

>It makes sense to rewrite FileDialog class to use new Common Item Dialog API IMHO. That might solve some of the existing and future issues. Microsoft recommends to use this new API going forward...

But I just wanted to point out that the "old style" dialog as shown can lead one to believe that Notepad++ is years (decades?) out of date when related to open/save boxes.

**Comment by mere-human** [comment] 2020-12-27 17:21
> 
> > It makes sense to rewrite FileDialog class to use new Common Item Dialog API IMHO.
> 
> That's good. But even this problem is solved, there's another one:
> I just checked your [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9286) again, and realized 2 incoherent behaviours (so far) in your implementation:
> 
> 1. I save a session with 3 opened files a, b & c + FaW (Folder as Workspace) with 2 folders X & Y opened.
> 2. Then I close 3 opened files, remove X & Y from FaW and add Z in FaW.
> 3. Close FaW.
> 4. Reload Save Session.
> 
> You will observe these 2 incoherent behaviours:
> 
> 1. a, b & c are reoped, but FaW is not reopened automatically with X & Y
> 2. even you open FaW manually, Z is opened instead of X & Y
> 
> That's the incoherence we (at least I) cannot solve, if we save FaW's info in both config.xml and saved session's xml files.
> What's your solution about such incoherence?

I see, workspace folders are saved to config.xml.

So session might be loaded either automatically on app startup (session.xml) or manually from the menu.
When loading session.xml automatically, I would ignore workspace files from it and load them only from config.xml.
When loading a session manually, we could let user decide ("Include workspace" checkbox).
If "Include workspace" is checked, then launch Folder as Workspace and load files from a saved session.

I solved that issue in a second commit.
Let me know, if I should squash them into a single commit and/or create a separate PR.

**Comment by mere-human** [comment] 2020-12-27 17:24
@sasumner 

> @mere-human said:
> 
> > Compare it to the Notepad++ save session dialog:
> 
> Your comparison is a bit "apples & oranges". Meaning that if you go to _Settings_ > _Preferences_ > _Default Directory_ and tick the box for _Use new style..._, you'd get a much more "apples & apples" comparison, example:
> 
> ![image](https://user-images.githubusercontent.com/30118311/103171101-75a30e00-4817-11eb-9c65-e028093b1e7b.png)
> 

Sorry, I didn't know that.
I wonder, what is the intent of that option? Was it for compatibility or are there another reason?

Yes, my main point was that Common Item Dialog is a recommended way and it also allows customization.

**Comment by sasumner** [comment] 2020-12-27 17:33
>what is the intent of that option? Was it for compatibility or are there another reason?

Apparently "old style" is used by those that deal a lot with paths that use `/` instead of `\`.
Or perhaps by those that just hate change and cling to "old style".
At least "new style" is the default (for new installs).

**Comment by mere-human** [comment] 2020-12-27 17:45
> > what is the intent of that option? Was it for compatibility or are there another reason?
> 
> Apparently "old style" is used by those that deal a lot with paths that use `/` instead of `\`.

OK, I've just checked: new Common Item Dialog handles the `/` pretty fine:
![image](https://user-images.githubusercontent.com/9664141/103176603-c77d7f80-487b-11eb-896e-8adcb007460a.png)
![image](https://user-images.githubusercontent.com/9664141/103176606-c9dfd980-487b-11eb-8c78-940191a91ec6.png)

> Or perhaps by those that just hate change and cling to "old style".

Maybe, it is worth to check whether new dialogs support the "old style" for those who like it.

**Comment by sasumner** [comment] 2020-12-27 18:42
>Maybe, it is worth to check whether new dialogs support the "old style" for those who like it.

Or, let's just move them into something modern and nice. :-)

**Comment by ArkadiuszMichalski** [comment] 2020-12-28 02:29
@donho
>I'm not sure it's an expected behaviour for some people.
Some users may only want the last state of Folder as workspace, without being interfered by session.

One person mentioned it, but it was for different reasons https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8005.

Wouldn't it take less work to add a toggle somewhere in Pref than playing with a dialog? What will happen with plugins that operate on sessions, will include FAW when saving or not (if the switch would be placed in a dialog)? Will the decision made be remembered or will it have to be marked every time?

**Comment by donho** [comment] 2020-12-28 14:08
@ArkadiuszMichalski 
> Wouldn't it take less work to add a toggle somewhere in Pref than playing with a dialog? 

It will always take less work if we code less, and as I'm a lazy dev, I'm always for that :) 
The thing is, one's feature to another could be a bug. So coding more can prevent from such situation.

> What will happen with plugins that operate on sessions, will include FAW when saving or not (if the switch would be placed in a dialog)?

By default it should be OFF, so it's doesn't change the life of plugins. We could add this option in concerning API if plugins devs request.

> Will the decision made be remembered or will it have to be marked every time?

I guess the correct behaviour is: when the saved session xml contains FaW node, and it's loaded, then FaW will be launched (if it's not yet) and folders will be loaded in it. Otherwise, on the startup, FaW is launched (or not) according the settings in `config.xml`.

**Comment by donho** [comment] 2020-12-28 19:27
@mere-human 
> I solved that issue in a second commit. I didn't touch the file dialogs though.
Let me know, if I should squash them into a single commit and/or create a separate PR.

Thank you. Its behaviour is good to me now. There are some stuffs to tune in your PR though. I'll do the request on your PR.

**Comment by mere-human** [comment] 2020-12-28 22:53
> @mere-human
> 
> > I solved that issue in a second commit. I didn't touch the file dialogs though.
> > Let me know, if I should squash them into a single commit and/or create a separate PR.
> 
> Thank you. Its behaviour is good to me now. There are some stuffs to tune in your PR though. I'll do the request on your PR.

Ok, sure.
What about the dialog with checkbox? Are we gonna make it? Or maybe we should add it to the preferences?
Maybe a separate issue should be created for that. I'm relatively new to the process.

**Comment by donho** [comment] 2020-12-29 00:13
> What about the dialog with checkbox? Are we gonna make it? Or maybe we should add it to the preferences?

Yes, the checkbox has to be done, and it should be in saveSession dialog, but not in the preferences dialog.

> Maybe a separate issue should be created for that. I'm relatively new to the process. Let me know if there is something I can do.

It will be in this PR, you can start it if you want. My request is rather some small details.

**Comment by ArkadiuszMichalski** [comment] 2020-12-29 13:02
@donho 
>Will the decision made be remembered or will it have to be marked every time?

>>I guess the correct behaviour is: when the saved session xml contains FaW node, and it's loaded, then FaW will be launched (if it's not yet) and folders will be loaded in it. Otherwise, on the startup, FaW is launched (or not) according the settings in config.xml.

Here I mean the saving session, what if we select a checkbox in a dialog box once, the decision will be remembered when we once again open this dialog box? Or we have to click this switch on every session saving?

**Comment by donho** [comment] 2020-12-29 13:34
> Here I mean the saving session, what if we select a checkbox in a dialog box once, the decision will be remembered when we once again open this dialog box? Or we have to click this switch on every session saving?

Hmm... good question. I would say on everytime user has to check this option if he/she wants to save the settings of FaW, just as he/she has to provide the filename to write.

**Closed** 2021-01-07 23:10 UTC

**Comment by KnIfER** [comment] 2021-04-01 05:51
I prefer "Save Window Layout to Session" :  ![image](https://user-images.githubusercontent.com/11593903/113249178-3c3bdc00-92f9-11eb-92f2-ab55933dcf25.jpg), when it's checked, dockable window layout along with the FaW data is saved in the session.

**Comment by mere-human** [comment] 2021-04-01 08:00
> I prefer "Save Window Layout to Session"

The mentioned checkbox affects only Folder as Workspace.

**Comment by KnIfER** [comment] 2021-04-01 11:09
I know that. Actually I've writted a simple fucntion called `reInitDockingSystem` on my branch, and the layout could be loaded dynamically ( including FaW and other dockable panels ) , just like many real IDEs.

**Comment by KnIfER** [comment] 2021-04-16 15:42
Drop XP? Embrace Linux-WINE!

![image](https://user-images.githubusercontent.com/11593903/115049390-a2d61200-9f15-11eb-99fc-8bba5271ffe2.png)

**Comment by mere-human** [comment] 2021-04-16 16:46
> Drop XP? Embrace Linux-WINE!

What does it mean?

**Comment by KnIfER** [comment] 2021-09-21 07:13
With [One-Core-API](https://github.com/Skulltrail192/One-Core-API-Binaries), you can run NPP v8 on XP, but the custom dialog won't show, and the toolbar is disappeared.
