### ISSUE TITLE
[Feature Request] Show search results in scrollbar (like in chrome)

### ISSUE THREAD

**Issue by sbormann** [notepad-plus-plus/notepad-plus-plus#8778] opened 2020-08-29 10:18 UTC
Is it possible to implement a chrome like scrollbar wich shows position of search-results?

Many thanks for this great software!!!

**Comment by ArkadiuszMichalski** [comment] 2020-09-15 13:14
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3116.

**Closed** 2020-09-15 13:16 UTC
