### ISSUE TITLE
[Find Result] go to wrong tab when file is temporary

### ISSUE THREAD

**Issue by Tequiller** [notepad-plus-plus/notepad-plus-plus#8461] opened 2020-06-24 02:43 UTC
### Description of the Issue
When we have several files open which many temporary (never saved), and we wish to reach at a research result line from the "Find result", if this line is from a temporary file the NPP go to the equivalent line to the tab already opened.

### Steps to Reproduce the Issue
1. Open saved files
2. Copy to the clipboard one of those text
3. Open new file
4. Write several lines in the temporary file
5. Then, paste text from the clipboard to this temporary file
6. Search a word that appear in both files thanks to [Find All in All Opened Documents]
7. From the [Find result], double click on the result from the saved file (should go into the good tab)
8. From the [Find result], double click on the result from the temporary file (if before the double click you were to the saved file, NPP keep this tab opened, and show you the equivalent characters position of the temporary file.

### Expected Behavior
NPP should recognised the good one tab and go to it even if it is temporary.

### Actual Behavior
NPP keep the actual tab open in the case of line result is from a temporary file.

### Debug Information
Notepad++ v7.8.6   (32-bit)
Build time : Apr 21 2020 - 15:17:06
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 8 (64-bit) 
OS Build : 9200.0
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2020-06-24 11:41
Can't reproduce with N++ 7.8.7 -- closing.
@Tequiller If you can provide a more specific example where it _does_ reproduce, of course we will reopen.

**Comment by Tequiller** [comment] 2020-06-24 12:00
Thanks for your reponse...
Indeed there is a 7.8.7 version... strangely my NPP don't tell me there's a new version... (bug ???)
I go to update it manually

![image](https://user-images.githubusercontent.com/46250710/85552064-e8da8600-b622-11ea-8812-3d38d68b8c72.png)

**Comment by sasumner** [comment] 2020-06-24 12:03
>strangely my NPP don't tell me there's a new version

At this point in time, that's expected.
New versions always have some "settling time" to see if early adopters have any critical problems.

>Is it possible I'had click one time in "update it later" that desables the [Update Notepad++] option?

No.

More importantly, does your issue not appear in 7.8.7?  Or can you provide more-specific example that will cause it to appear for maybe more than just you?

**Comment by Tequiller** [comment] 2020-06-24 13:11
I just make same test with the NPP 7.8.7
Bug is actual yet.

I've only follow step that are proposed in "Reproduce the Issue".
I've test it with only one instance or several, with only one panel or with "other view" panel, with or without Language selected, there's always the problem... at home...

For information I've deactivated the plugin [DSpellCheck] (spoken in other report ticket).

What do you need more I might forgotten? ^^
May be a picture could help you to find the litlle thing I forget to mention?

![image](https://user-images.githubusercontent.com/46250710/85560029-8e452800-b62a-11ea-927c-b438bdc533a2.png)


### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 8 (64-bit) 
OS Build : 9200.0
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 


### Hypothetical Incompatibility
Perhaps potentially an incompatibility with my Logiteck keyboard tool??? I explain:
Logiteck look for actual window to activate some appropriate macro keys.
Problem with this tool is when I change of window focus, it annoyingly deactivate instant the focus to "null window" (Logitech don't want to recognise their bug... try to explain it is from their tool, I'm not so good to catch them in the act! ^^ )
Is it possible that when double click on Find result there's something in NPP that quickly open and close to operate the selection, and my logiteck tool perturb it? (I've no more idea of what could do that...)

**Comment by sasumner** [comment] 2020-06-24 13:26
Your screenshot adds information that your earlier description did not include: that you have the unsaved file in one view, and the saved file in the other view.  However, my new testing still shows no problem with this.

>Perhaps potentially an incompatibility with my Logiteck keyboard tool???

One way to definitely see if it has an effect:  Disable it and retest.
Personally, if it has bugs, I would leave it disabled permanently.

**Comment by Tequiller** [comment] 2020-06-24 14:24
>  Disable it and retest
After the test, bug is staying here.
Thank's for the Idea Sasumner, about Logitech you permit me to have "taken them in the act"! (didn't have this idea to report their bug)

I spoken about "temporary file"... may be a vocabulary problem from me :) I wish to mean a new file that was **never** saved.
It's not necessary the same structure that the other file, I do it for the example, that why I had other lines in step 4 to have an equivalent of two different files. (or you speak about other thing I've difficult to translate - If you didn't recognised my writing accent, I'm french ^^)
If we save the file and modify it just after, there's no problem, as if the fact file was never saved at all (what I designated as "temporary"), its tab seem to not be correctly referenced by the [Find result].

**Comment by sasumner** [comment] 2020-06-24 14:42
>I spoken about "temporary file"... may be a vocabulary problem from me :) I wish to mean a new file that was never saved.

Understood.  There really isn't an official name for these types of files.  Maybe "never user-saved" is best as a name, because that can be true and yet N++ has actually saved them somewhere. 

At this point I really don't have any ideas about your issue, because everything I try as an experiment works fine for me.

**Comment by Tequiller** [comment] 2020-06-24 16:33
Ok, thanks for your attention.
I've used all my bugs are originals, I'm known as bad-luck charm with high-tech ^^

**Comment by Yaron10** [comment] 2020-06-26 19:38
I've mentioned this issue a long time ago and it's still valid.

**STR:**
Save the following lines to `Test.txt`.
```
user_pref("accessibility.typeaheadfind", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("accessibility.typeaheadfind.timeout", 85000);
```
Open `Test.txt` in NPP.
Open a new file and paste `user_pref`.
Switch back to `Test.txt`.
Select `user_pref`.
Open the Find dialog.
Find in All Opened Documents.
In the `Find result` window double-click the line under `new 1`.

**Result:**
NPP highlights the _first_ `user_pref` in `Test.txt`.

(You'd get the same behavior with two new files).
***
Tested with a fresh NPP portable.

Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\---\Downloads\npp.7.8.7.bin.minimalist\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Enterprise (32-bit) 
OS Build : 7601.23964
Current ANSI codepage : 1255
Plugins : none

**Comment by sasumner** [comment] 2020-06-26 20:01
@Yaron10 

With your "STR" I can make it "R".

>I've mentioned this issue a long time ago and it's still valid.

No link to that issue?
If you can provide a link, we'll keep this one closed (as a duplicate).

**Comment by Yaron10** [comment] 2020-06-26 20:04
@sasumner,

> No link to that issue?

Sorry.

**Comment by Yaron10** [comment] 2020-06-27 13:22
@sasumner,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5419

**Comment by sasumner** [comment] 2020-06-28 01:40
So when the code goes looking for a tab buffer to open after the d-click in _Find result_, it does so by name, and calls this function with name = `new 1`:

`BufferID FileManager::getBufferFromName(const TCHAR* name)`

See [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/1314af7d6f88a75a2bc9f8839c0dbb676ac76b22/PowerEditor/src/ScitillaComponent/Buffer.cpp#L1467) to show this function.

When this part of the function executes:

`for (size_t i = 0; i < _buffers.size(); i++)`

_buffers.size() is 6, which is rather strange since, following @Yaron10's STR, I just have `test.txt` open as my first tab, and `new 1` open as my second tab -- a total of 2 tabs/buffers.

So what are the names of the 6 buffers?  (_Why_ are there 6 is also a good question!)
Well:

```
[0] : new 1
[1] : new 1
[2] : new 1
[3] : (complete path of) test.txt
[4] : new 1
[5] : new 2
```

So what happens is that the code matches the name on the [0] buffer and returns it.  But, because it isn't the correct `new 1`, when future code tries to switch to the buffer id that was returned, it can't find it, so it can't activate the real `new 1` and thus no tab switch occurs and the user is left sitting at `test.txt` (remember, one of the STR was to have `test.txt` as the active tab when d-clicking the `new 1` hit in the _Find result` window).

So at this point, a really good question is why are there FOUR buffers named `new 1`, why is there a `new 2` buffer, and why are they in the order they are in?

buffer [4] is the real and correct `new 1`, but the code can't get there for a name match due to the earlier `new 1` buffers.

**Comment by Yaron10** [comment] 2020-06-28 11:29
@sasumner,

I still have to learn how to use the Debugger. Bear with my comments. :)

Open NPP (so that only `New 1` exists).
Paste `user_pref` there.
Open `Test.txt`.
Repeat the steps (search etc.).

Would you still have more than one `New 1`?

`::SendMessage(::GetParent(_hParent), WM_DOOPEN, 0, reinterpret_cast<LPARAM>(fInfo._fullPath.c_str()));`
(`gotoFoundLine()` in `FindReplaceDlg.cpp`).

Does `New 1` have a `fullPath`?

**Comment by sasumner** [comment] 2020-06-28 12:12
>I still have to learn how to use the Debugger. 

If you are building N++ code successfully, using the debugger is just a tiny step forward.  Take that step.

>Bear with my comments.

No worry, I like comments.  It shows that people are interested.

>Open NPP (so that only New 1 exists).
Paste user_pref there.
Open Test.txt.
Repeat the steps (search etc.).

In _THIS_ scenario (and with `test.txt` the active tab) N++ correctly switches to the _new 1_ tab when d-clicking on the _new 1_ area of the _Find result_ window.

This time the 6 buffers are still there with the same "file"names in the same order as shown above, but now I suspect that buffer [0] is the one for our real `new 1` file, not buffer [4] as it was before.  Why? Because the code works and the proper tab is switched to.

>Does New 1 have a fullPath?

No.  At the point you are showing, `fInfo._fullPath.c_str()` is equal to `new 1`.  Any calls later on that try to get a full path from the O.S. for something called `new x` fail (and that failure is handled).  Not quite sure what you are getting at with this question, if more than the obvious :-).  The only time a `new x` file might have a fullpath in the file system is when N++ does a periodic backup on it, but that use isn't relevant here.

**Comment by Yaron10** [comment] 2020-06-28 16:49
I do build NPP successfully. And yes, I should try the Debugger.

> In THIS scenario...

:+1: 

> Not quite sure what you are getting at with this question
...
> (and that failure is handled)

I didn't delve into the code and wondered how `New x` was handled without a path.

I'll seize the opportunity and thank you for your important contribution during the past months.
I have made quite a lot of changes to the Find dialog and the Incremental bar, and I need to find the time (and mood) to adapt my 7.8.3 code to the current one.
I suppose I'll wait for a few more imminent PRs by @sasumner related to those components. :)

**Comment by Ekopalypse** [comment] 2020-06-28 20:42
I remember that I read some comments in code that old buffer ids do not get deleted but reused to avoid to recreate them.
Maybe that is related?

**Comment by sasumner** [comment] 2020-06-29 00:57
@Yaron10 
Things can get worse.
Create two additional new documents.
Rename each (by right-clicking tab, choose _Rename_) to `foo`.
Paste `user_pref` in each of the two `foo`.
Repeat the _Find All in All Opened Documents_ (searching for `user_pref`).
Double-click the lines relating to the `foo`s in _Find result_.
Notice that it is always the **_first_** `foo` that it goes to.
Perhaps user shouldn't name two files with the same name; nothing to prevent it, though.
But this is very similar to going (or attempting to go) to the first `new 1` document when there are more than one.

**Comment by Yaron10** [comment] 2020-06-29 11:05
Interesting.
Regardless, the problem exists with `Find All in Current Document` as well.

**Comment by sasumner** [comment] 2020-06-29 11:28
>the problem exists with Find All in Current Document as well.

There is no issue with _Find All in Current Document_ or _Find All in All Opened Documents_.

This issue begins with trying to jump to a match in a source file from a `Line :` in the _Find result_ window.  Because this is done by "file"name, if there are multiple tabs with the same name, this action will always cause a jump to the first tab in existence with the same name.

If that first tab isn't shown to the user (our analysis of `new 1` above), the active tab isn't changed (our earlier case).

Of course this will not apply to results from a _Find in Files_ search, because that one does not consider "unsaved" files when searching.

>Interesting.

I think it goes beyond "interesting". :-)
I've wondered before if the renaming of unsaved tabs (a dubious thing in my mind) would generate trouble.  It seems that, for the case of renaming two tabs to the same value, it has.

This calls into question any calls to the `getBufferFromName` function.  If there aren't going to be unique names for all buffers, is this really a "reasonable" function?

**Comment by Yaron10** [comment] 2020-06-29 21:28
FWIW, even if you *close* `New 1`, `if (OrdinalIgnoreCaseCompareStrings(name, _buffers.at(i)->getFullPathName()) == 0)` still returns `_buffers[i]->_id;`

**Comment by Yaron10** [comment] 2020-06-29 21:38
Which means that @Ekopalypse's [comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8461#issuecomment-650819067) is very important.

**Comment by sasumner** [comment] 2020-06-30 15:47
>Which means that @Ekopalypse's comment is very important.

So that's kind of a vague statement (Yaron10's).
Buffer ids getting reused is not a problem in and of itself, but of course it has to be done properly.
The bigger problem might be, as I pointed out before, is having multiple buffers with the exact same "name" and then trying to differentiate between them using only a name.

**Comment by Yaron10** [comment] 2020-06-30 20:54
If NPP only kept buffer ids for the currently opened documents, we wouldn't have the problem with `New 1` in our case.
And not allowing the user to assign duplicate names to new tabs (rename) would be perfectly legit.

If the benefits of reusing buffer ids are significant, you're right: "it has to be done properly".

**Comment by sasumner** [comment] 2020-06-30 22:51
>If NPP only kept buffer ids for the currently opened documents

I'm not sure yet what the idea is for the extra buffers, but TBH I've not gotten back to this.
I will probably open an issue for the renaming of unsaved tabs being allowed to have the same name.

**Comment by Yaron10** [comment] 2020-06-30 23:03
I suppose it would be better to grasp the extra buffers point and then deal with renaming of unsaved tabs, wouldn't it?

**Comment by donho** [comment] 2020-11-06 21:50
@Yaron10 
I cannot reproduce the bug with your description:
I've mentioned this issue a long time ago and it's still valid.

>Save the following lines to Test.txt.
```
user_pref("accessibility.typeaheadfind", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("accessibility.typeaheadfind.timeout", 85000);
```
>Open Test.txt in NPP.
Open a new file and paste user_pref.
Switch back to Test.txt.
Select user_pref.
Open the Find dialog.
Find in All Opened Documents.
In the Find result window double-click the line under new 1.

@sasumner Am I missing something?
Result:
NPP highlights the first user_pref in Test.txt.

**Comment by sasumner** [comment] 2020-11-06 21:58
@donho 

>am I missing something?

Yes, probably. :-)
Make sure you follow those steps exactly.
The important one might be "Switch back to test.txt"

**Comment by donho** [comment] 2020-11-06 22:03
@sasumner  I did "switch back Test.txt file".

Reproduced - I need to close all files then copy and save the untitled document.
Thank you for your resistance.

**Comment by Yaron10** [comment] 2020-11-06 23:40
@donho,

Thank you for looking into it.

@sasumner,

Thank you for clarifying it.

**Closed** 2020-11-07 02:00 UTC
Labels: bug, verified
