### ISSUE TITLE
Bug/Unfriendy behavior: Column Editor insert text not only within selected lines, nor to the whole document

### ISSUE THREAD

**Issue by johnnytemp** [notepad-plus-plus/notepad-plus-plus#2139] opened 2016-08-03 07:18 UTC
### Description of the Issue

No matter the document has text selection or not, Column Editor always insert text from current line up to the end of the document.

A more intuitive and friendly behavior is to insert only for the selected lines when there is a selection.
### Steps to Reproduce the Issue
1. Open a normal text document of over 10 lines.
2. Forward select the lines from the 4th to 6th.
3. Menu -> Edit -> Column Editor..., then input "// " into "Text to insert" and press OK.
### Expected Behavior

"// " is inserted to the beginning of line 4, 5 and 6.
### Actual Behavior

"// " is inserted to the beginning of line 7, 8, 9 and so on unto the end.
### Debug Information

Notepad++ version 6.9.1 on Windows 10

**Comment by MetaChuh** [comment] 2019-04-11 21:29
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:29 UTC
