### ISSUE TITLE
Crash: Starting Post-It mode when using "Split-Screen"

### ISSUE THREAD

**Issue by LxWolfgang** [notepad-plus-plus/notepad-plus-plus#6269] opened 2019-10-25 09:22 UTC
### Description of the Issue
Starting Fullscreen/Post-It mode when using Split-Screen results in crash

### Steps to Reproduce the Issue
1. Start with no Files/Tabs open (new 1)
2. Create a second empty tab (new 2)
3. Right Click on the new tab and select "Move to Other View"
4. Then activate the Post-It View (F12)
5. Notepad++ Crashes

**Comment by donho** [comment] 2019-10-25 13:23
@LxWolfgang 
Can you reproduce the crash steadily?
Could you provide your debug info via menu `? -> Debug Info...` ?

**Comment by sasumner** [comment] 2019-10-25 13:51
Unable to reproduce with:

Notepad++ v7.8   (64-bit)
Build time : Oct  7 2019 - 00:55:55
Path : C:\......\npp.7.8.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1387
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by LxWolfgang** [comment] 2019-10-25 13:53
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by Big--Mike** [comment] 2019-10-25 14:03
I can reproduce this with HexEditor plugin enabled. Can you try to disable HexEditor and look if the crash still occurs (it doesn't happen after disabling HexEditor here...)

**Comment by donho** [comment] 2019-10-25 16:39
@LxWolfgang Please remove HexEditor plugin and test again.
Please keep us posted.

**Comment by xylographe** [comment] 2019-10-25 17:37
Unable to reproduce with:

Notepad++ v7.8   **(32-bit)**
Build time : Oct 25 2019 - 19:20:01
Path : C:\Program Files (x86)\Notepad++\npp.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Plugins : BetterMultiSelection.dll ComparePlugin.dll DSpellCheck.dll ElasticTabstops.dll **HexEditor.dll** LuaScript.dll mimeTools.dll MultiClipboard.dll NotepadStarterPlugin.dll NppConverter.dll NppExport.dll NppQCP.dll NppSaveAsAdmin.dll NppXmlTreeviewPlugin.dll XMLTools.dll

**Comment by LxWolfgang** [comment] 2019-10-28 07:40
I have now removed the HexEditor plugin and now it is working fine.
So it seems like the plugin is causing the problems.

**Comment by Ekopalypse** [comment] 2019-10-28 11:11
I can't see reported behavior with nearly same configuration. 
OS and Local Conf mode are different.

Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll HexEditor.dll JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

**Comment by sasumner** [comment] 2019-10-28 11:41
>I have now removed the HexEditor plugin and now it is working fine.

Let's call this a HexEditor problem and close this.

**Closed by sasumner** 2019-10-28 11:41 UTC

**Comment by Ekopalypse** [comment] 2019-10-28 11:57
Although I understand the reason to close this problem as it is not an npp problem, 
I don't think one can "simply" call it a hex editor problem.
During my tests with all provided plugins I found out that different combinations of plugins,
and perhaps settings of these plugins can cause serious problems for the stability of npp.
Considering that each plugin has full access to npp and has the message queue via subclassing,
it is no longer difficult to accept that a single plugin causes problems due to misbehavior.
HexEditor could only be the victim of another plugin.

**Comment by sasumner** [comment] 2019-10-28 12:02
@Ekopalypse 

So I'm not sure what to do for that...  :-)

**Comment by Ekopalypse** [comment] 2019-10-28 12:08
I just wanted to let future readers know that the HexEditor plugin does not necessarily 
have to be the problem. We've been using the plugin for years without ever really seeing a problem.

How to make sure that plugins don't get in each other's way, I honestly don't know.
