### ISSUE TITLE
Search-Results: NPP does not switch to new unsaved files

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#5419] opened 2019-03-12 23:19 UTC
**STR:**
Open a saved file.
Open a new file, type `abc` and run search.
Switch to the saved file/tab.
Double-click `abc` in the Search-Results window.

**Result:**
NPP does not switch to the new unsaved file but rather selects the first three characters in the saved file.

**Comment by SinghRajenM** [comment] 2019-03-14 17:34
@Yaron10 This seems to be very special case. I can reproduce this issue in 7.6.1 as well.

Steps to reproduce in v7.6.1:
1. Open "New 1" and type `asasasa`
2. Open "New 2" and type `as as as`
3. Open a saved file.
4. Now switch to "New 1" and perform "find all in current document' for `a`
5. Switch to 3rd tab which is saved file
6. Now click on search result

Result is after step 6: it highlights on 3rd tab instead of switching to 1st tab.

**Comment by SinghRajenM** [comment] 2019-03-14 17:41
Further more, it comes only when tab Name is "New 1" (as per my test results).

**Comment by sasumner** [comment] 2020-06-27 15:07
Let's close this one as a duplicate and continue working #8461

**Closed by sasumner** 2020-06-27 15:07 UTC
Labels: bug, verified
