### ISSUE TITLE
Unexpected behavior in custom color selector (style configurator)

### ISSUE THREAD

**Issue by RafaelLVX** [notepad-plus-plus/notepad-plus-plus#1037] opened 2015-10-22 02:02 UTC
When customizing a style in the style configurator (I'm sorry if I'm using the wrong names, my app is in portuguese), there is unexpected behavior, or at least some things could be improved.

See image attached.
![custom colors style configurator](https://cloud.githubusercontent.com/assets/909214/10653711/01e15130-7841-11e5-9580-17134beaf56f.png)

Normally, to start creating a new color, I'd start clicking on some of the colors from basic colors (1) or color picker (2). Then I fine tune it in color picker (2), and click button "Add to custom colors" (5) to save that color for later use. Color is saved in the first position by default (3). So far so good. 

Now if I need to create a new color based on the first custom color I created (say, make a darker shade of the same color), I click on the custom color (3), make changes in color picker (2), then to save I click button "Add to custom colors" (5). But that overwrites the old color. it could be a different process: I select a different position (4) and copy the hexadecimal code of the old color (3) to the new position, then save (5), if only there was such a field and the hexadecimal code of the color was present in the screen. But since it has three separate values for RGB, I need to write down the three values somewhere and re-write when I start over, and that's a waste of time.

If I create another color after closing the dialog, that also overwrites the first position (3) by default. Perhaps it could add the new color to the rest of the empty panel (4). I understand adding new colors to all empty positions will eventually lead to overwriting anyway (because the number of positions is finite). The optimal solution would be a way to always choose the color position on save, or make a different system where you can add and remove as many new colors as you want.

If you want to add a custom color to one the empty positions (4) based on the basic colors (1), that actually works, one must click on an empty position (4), then on a basic color (1), edit on color picker (2), and save (5). However, if you just click on an empty position (4) and go straight to the color picker (2) to pick a completely new color right off, when you save (5), it adds the new color to completely different adjacent positions. I don't know if it's random, but I think it just picks the next position, then another if you change and save again. It does not save to the empty position you had selected earlier.

So to me that dialog is kind of broken.

Hope it helps.

**Comment by MetaChuh** [comment] 2019-04-10 23:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:42 UTC
