### ISSUE TITLE
[BUG] Links no longer clickable after restart, and Word Wrap enabled.

### ISSUE THREAD

**Issue by BlackSails7** [notepad-plus-plus/notepad-plus-plus#5503] opened 2019-04-09 18:09 UTC
### Description of the Issue
Since ever.. I've been having this bug with Notepad++

The bug is simple. Some of the links are no longer clickable (unrecognized as links) after closing and re-opening the text document, while having Word Wrap enabled.

### Steps to Reproduce the Issue

1. Open Notepad++

2. Make sure you have **Clickable Links** enabled, and "**No Underline**" _unchecked._
(_Settings → Preferences → MISC. → **Clickable Link Settings**_)

3. Make sure you have Word Wrap _enabled_ (_View → Word Wrap_)

4. Paste _long_ links, while having **Word Wrap** enabled. (long enough to see the word wrapping)

5. Close and Re-open the text file you pasted the links in, with Notepad++

### Expected Behavior
ALL the links should be Clickable & Underlined (always)

### Actual Behavior
Some of the links are no longer clickable/underlined after restart.

### Debug Information

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

### Screens:

Word Wrap **enabled**

1. https://i.imgur.com/Ho4H0W2.png

Word Wrap **disabled**

2. https://i.imgur.com/OJ5dVhz.png

### NOTE:

1. Had this bug on previous versions. (was hoping it would be fixed by now)

2. The bug doesn't seem to occur when having Word Wrap disabled.

3. Have reproduced the bug on multiple computers. (Win10Pro only)

4. The non-clickable links are **not** always the last ones. (sometimes it's random, but usually it's the last 3 links)

5. Doesn't really matter whether you have "**No Underline**" unchecked.

6. Quickly toggling Word Wrap _doesn't_ deal with the issue.

---

EDIT:

1. Doesn't really matter having Word Wrap enabled.. Even when having it enabled, if you full screen Notepad++ and the links aren't long enough to text wrap.. then this bug doesn't occur.

2. It's not _actually_ the last 3 links.. it depends.

3. Adding text further (spamming with 'Enter' for example) seems to "refresh" the links, and get them fixed.

**Comment by donho** [comment] 2020-06-30 17:43
@Uhf7 @BlackSails7  Cannot reproduce it.
Is there a stable way to reproduce it in v7.8.8 ?

**Comment by Uhf7** [comment] 2020-06-30 19:23
On my system, it goes as follows:

- Copy the content of the `npp.7.8.8.bin.minimalist.7z` to a new directory.
- Start the `Notepad++.exe` from there.
- A **new1** edit window appears.
- Make sure, that the height of the edit window is big enough to show about 25 lines.
- Create 10 text lines, each consisting of a single word, each same length, about 60 characters.
- Make sure, that the text is no longer than this 10 lines.
- Turn on word wrapping.
- Reduce the width of the Notepad++ window, until all 10 lines are wrapped one time, so that the original 10 text lines now occupy 20 lines on the screen.
- Now, go to the end (line 11) and type http://test.url. It is not marked as URL.
- End Notepad++ (session will be saved automatically).
- Reopen Notepad++. The last line is now marked as URL. This is merely because the effect is hidden after restart by PR #8409 (f657618887ecb2382472f459a7fa32838c30f612). All versions before did not mark the last line as URL after restart in this situation.

So, you cannot reproduce it anymore after restart, but this is not, because the effect is gone completely. The current description of the easy repeatable effect would be: Newly typed URL links at end of files are not highlighted, if
- Word wrap is on
- The lines above the link occupy more lines on the screen than there actual line count (or: they are really wrapped). 

An picture of the effect is in PR #8467.

**Comment by donho** [comment] 2020-06-30 22:53
Thank you for your instructions.
I can reproduce the bug now.

**Closed** 2020-06-30 23:08 UTC
Labels: accepted
