### ISSUE TITLE
Line-sorting not working if on "Other view"

### ISSUE THREAD

**Issue by taffit** [notepad-plus-plus/notepad-plus-plus#8821] opened 2020-09-07 07:42 UTC
### Description of the Issue
If you try to use the line-sorting function from `Edit` -> `Line Operations` -> `Sort Lines Lexicographically Ascending' (or `... Descending` while the active window is on the "Other View" (by right clicking a tab -> `Move to Other View`), nothing happens.

### Steps to Reproduce the Issue
1. Right click on a tab and select `Move to Other View`
2. Select the whole text in the split window by pressing `Ctrl-A`
3. Select  `Edit` -> `Line Operations` -> `Sort Lines Lexicographically Ascending'

### Expected Behavior
The lines are sorted alphabetically in ascending order.

### Actual Behavior
Nothing

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.487
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextViz.dll XMLTools.dll 

### Additional important information
Thank you so much for Notepad++ and all the work you put into this! Much appreciated by a whole lotta people all around the world! Thank you!

**Comment by sasumner** [comment] 2020-09-07 11:55
Cannot reproduce in:

Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\\...............\npp.7.8.9.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1397
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PythonScript.dll 

Closing for now but open to reopening with further information.

BTW, in step 2 you don't have to do ctrl+a to select all text.  A sort operation with nothing selected will sort the entire document.

**Closed by sasumner** 2020-09-07 11:55 UTC

**Comment by taffit** [comment] 2020-09-07 12:23
@sasumner Thank you for checking the issue.

I tried to reproduce it with the newest version, downloaded from the website (didn't do it before as the `Update`-function in the Help-menu didn't report any newer version) and found out, that it doesn't have to do with the `Other View`, but rather with the newline characters. If we have *nux line endings `\n`, then the sorting doesn't work. With Windows line endings `\r\n`, sorting works without a problem.

### Steps to Reproduce the Issue
1. `Search` -> `Replace...` (`Ctrl-H`)
2. `Search mode` -> `Extended`
3. `Find what` -> `\r\n`
4. `Replace with` -> `\n`
5. `Replace All`
6. `Edit` -> `Line Operations` -> `Sort Lines Lexicographically Ascending'

### Debug information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.487
Current ANSI codepage : 1252
Plugins : JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppSaveAsAdmin.dll NppTextViz.dll XMLTools.dll

**Comment by sasumner** [comment] 2020-09-07 12:42
Sorting is conducted based upon what the file's line-ending type is.  See your N++ status bar for this info (one way to check it); example:
![image](https://user-images.githubusercontent.com/30118311/92388161-d5e53700-f0e4-11ea-87d1-3a3a5c4ad2f3.png)

So for my file from the example screenshot, for sorting to be done correctly, all lines in the file must have a CR+LF ending.

Instead of doing your replacement operation, you should just double-click the section of the status bar I show in the example, and choose the different line-ending type.  Then N++ is aware of a change to the file's line-ending type.  Sadly, it is possible to have N++ think the line-ending type is one thing, and some/all of the lines in the file be different.

Somewhat related:  #7735 which discusses allowing N++ to sort a file where line-endings are not all uniform.

**Comment by taffit** [comment] 2020-09-07 20:25
Ah, I think I got it. Thank you for the clarification, @sasumner !
I just didn't expect this behavior that replacement is related to EOLs.

Now I know. 👍
