### ISSUE TITLE
6.7.9 doesn't exit but hangs

### ISSUE THREAD

**Issue by odysseuscm** [notepad-plus-plus/notepad-plus-plus#239] opened 2015-06-16 17:40 UTC
On Windows 8.1 x64 Notepad++ 6.7.9 doesn't exit when you try to close it but hangs. It doesn't matter if you try to close it by X, ALT+F4 or from the file menu.
This did not happen with 6.7.8.2 (or any version before).

P.S. Also tried this after a clean install (so not over a previous version). Same result.

**Comment by Predelnik** [comment] 2015-06-16 20:23
Can you confirm that moving DSpellCheck.dll from plugins to disabled folder resolves the issue?

**Comment by Rikk** [comment] 2015-06-17 02:56
I also saw it happening a few times, but I don't know how to reproduce it.

**Comment by odysseuscm** [comment] 2015-06-17 05:22
@Predelnik: yes. If I move DSpellCheck.dll to "disabled" the program exists correctly.
Don't know if it's related, but my system language is German.

**Comment by donho** [comment] 2015-06-17 13:26
Further info: notepad++.exe in v6.7.9 is built on 64 bits machine, whereas notepad++.exe in v6.7.8.2 is built on 32 bits machine.This changement makes DSpellCheck's behaviour changed. But still, it shouldn't hang.

**Comment by randyxxl** [comment] 2015-06-17 15:28
Same problem at my machine. If I shutdown Notepad++ it will hang. A right click on the taskbar and 'Close window' will eventually do.

This problem is not new to me. Version 6.7.8.2 showed the same freezing at a close of the program, not always, but every now and then. 

The behaviour of Version 6.7.9 is much more annoying because it is never not possible to close it the normal way. For now I don't have any clues other than that disabling spellcheck prevents the problem from arising. I have moved `DSpellCheck.dll` from `C:\Program Files (x86)\Notepad++\plugins` to `C:\Program Files (x86)\Notepad++\plugins\disabled`. This seems to be a solution to prevent the application from hanging when I close it. I don't need spellcheck so it's ok to me....

**Comment by Predelnik** [comment] 2015-06-17 17:06
On one of machines I have access too it seems I am able to reproduce it but looks like it happens only in case I close Notepad++ approx. in 5 seconds or less after I started it.
The reason is poor design of my plugin which should actually be rewritten for the most part but it didn't cause many issues before so I was hesitating.

However since rewriting is not a fast process anyway I've done some quick mending, it seems to resolve the issue at least in my case. It will be good if someone will check if it fixes problems in his/her case:
https://dl.dropbox.com/s/acguqdqcxyyc846/DSpellCheck.dll
But if issue happens not only in close proximity of npp start then maybe I need to investigate further.

**Comment by odysseuscm** [comment] 2015-06-17 17:16
@Predelnik: I just tried your new dll. Unfortunately Notepad++ crashes instantly upon launch while it's in the plug-in folder... If I can send you any log files to help out, let me know.

**Comment by Predelnik** [comment] 2015-06-17 18:14
Ok apparently it was some derp by compiler, try this one:
https://dl.dropbox.com/s/acguqdqcxyyc846/DSpellCheck.dll

**Comment by odysseuscm** [comment] 2015-06-18 01:25
@Predelnik Yes, that one seems to solve the problem.

**Comment by donho** [comment] 2015-06-18 09:48
Thank you @odysseuscm  for testing.
@Predelnik Strangely, the binary you provide doesn't solve the hanging for an user on live support:
https://gitter.im/notepad-plus-plus/notepad-plus-plus

**Comment by dail8859** [comment] 2015-06-18 18:18
User on gitter reported that the new DLL fixed their issue

**Comment by donho** [comment] 2015-06-18 18:40
Thank you @dail8859 !

@Predelnik Will you release a new version of DSpellCheck ?

**Comment by Predelnik** [comment] 2015-06-18 18:42
@donho sure I will make a new version right away then.

**Comment by Predelnik** [comment] 2015-06-18 19:02
I've done it + updated link on plugins admin system
https://github.com/Predelnik/DSpellCheck/releases/tag/1.2.14.1

**Comment by donho** [comment] 2015-06-18 20:17
Thank you @Predelnik !
Just curious, what did make Notepad++ hanging and what is your solution?

**Comment by Predelnik** [comment] 2015-06-18 21:11
Ok apparently I accidentally broken quite a few things in plugin with my initial fix so I had to update it and it would be good if someone who was having the problems before will recheck it with version from here (from my side it's fine):
https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.1/DSpellCheck.zip

As for the reason - it's because of some messages being sent from worker thread to GUI in plugin which technically may lead to hanging in case if application exits and waiting for threads to exit. Most of such things are luckily done based on user actions so it's not easy to reproduce. However some were (incorrectly) done on `NPPN_READY` notification, I just excluded those `SendMessage` calls for now. I haven't exactly figured why `NPPN_READY` behavior changed since the previous version of N++ though.

**Comment by mrcookies** [comment] 2015-06-18 21:15
8.1 hang - new .dll fixed it.  Thx Predelnik

**Comment by donho** [comment] 2015-06-18 21:37
@Predelnik Damn! I have to rebuild the release
Could you confirm that https://github.com/Predelnik/DSpellCheck/releases/download/1.2.14.1/DSpellCheck.zip
Is correct for good?

**Comment by odysseuscm** [comment] 2015-06-19 06:27
@donho That version works fine for me.

**Comment by randyxxl** [comment] 2015-06-19 10:19
" ...  I haven't exactly figured why |NPPN_READY| behavior changed since 
the previous version of N++ though. ..."

My NPP 6.7.8.2 was showing the same problem. It was not problematic 
enough for me to post a reply in this thread at that time.
So I think the problem has been there for a longer time. Maybe it's a 
regression form an earlier release.
This weekend I will install and test the new version. The posts of the 
other users of a successful test give hope.  :-)

**Comment by donho** [comment] 2015-06-19 17:52
@randyxxl Do you mean in 6.7.8.2 Notepad++ hangs also on quit?
How can I reproduce that?

**Comment by randyxxl** [comment] 2015-06-19 17:56
>How can I reproduce that?

Don't know. ... It just happens every now and then. Default install on Win8 64bit.

**Comment by donho** [comment] 2015-06-19 18:46
@odysseuscm Are you talking about v6.7.8.2 right?
If you remove DSpellCheck.dll, is the hanging problem solved?

**Comment by randyxxl** [comment] 2015-06-19 19:00
Sorry, Not tested.
Upgraded first and moved file afterwards.

**Comment by donho** [comment] 2015-06-20 11:26
Sergey ( @Predelnik , the author of DSpellCheck) has done some fixes. For people who got the problem Notepad++ hangs on close, Could you try this build?
https://notepad-plus-plus.org/repository/6.x/6.7.9.1.prerelease/npp.6.7.9.1.Installer.exe

**Comment by odysseuscm** [comment] 2015-06-20 11:59
No problems with 6.7.9.1 on a few quick test runs.

**Comment by randyxxl** [comment] 2015-06-20 12:58
Found time to do some testing. Tested on Win 8.1 64-bit. 

Approach:
- Opening NPP++
- Open new file
- Type some text, normal text combined with some gibberish. 
- Check for spellcheck to do it's work.
- Do not save file
- Try to close NPP++
Remark: during previous tests I also found the `DSpellCheck.dll` in `%appdata%\Roaming\Notepad++\plugins`. I removed it to be sure.

Tested
* Install 6.7.9
  * Default install -> hanging application
  * Removing `DSpellCheck.dll` from `C:\Program Files (x86)\Notepad++\plugins` -> no hanging
  * Installing patch from @Predelnik -> no hanging
* Downgrade from 6.7.9 to 6.7.8.2
  * Default install -> hanging application
  * Removing `DSpellCheck.dll` from `C:\Program Files (x86)\Notepad++\plugins` -> no hanging
  * Installing patch from @Predelnik -> no hanging
* Install prerelease `npp.6.7.9.1.Installer.exe` from link above
  * Default install -> no hanging

The patch and new build seem OK to me. Thanks all!

**Comment by donho** [comment] 2015-06-24 23:10
Fixed in v6.7.9.1

**Closed by donho** 2015-06-24 23:10 UTC
Labels: bug

**Comment by XaserAcheron** [comment] 2017-03-20 22:29
This seems to be back on v7.3.3 -- same symptoms, same workaround (disable DSpellCheck).
