### ISSUE TITLE
bug: Change History - print problems

### ISSUE THREAD

**Issue by ifknot** [notepad-plus-plus/notepad-plus-plus#12383] opened 2022-10-23 09:47 UTC
### Description of the Issue

The new Change History feature is turned on by default - unfortunately it is broken when printing in colour on Windows 10 us an HP colour printer!

### Steps to Reproduce the Issue

1.  Have an HP Color Laser Jet Pro
2.  Use Windows 10 Notepad++ latest update version to change a syntax highlighted file
3.  Observe the new green vertical bar next to the line numbers and wonder why?
4.  Print the changed file to your HP Color Laser Jet Pro
5.  See that the printout every changed line has a dark green background the entire width of the line
6.  Be unable to read the text on those printed linea - especially if they are syntax highlighted green comments

### Expected Behavior

Be able to print out changed sytax highlighted files in colour on my HP Color Laser Jet Pro and be able to read the text on each line

### Actual Behavior

Be unable to read the printed lines of  the changed sytax highlighted lines in colour from my HP Color Laser Jet Pro due to each changed line having a dark green background

+  Upgrading and suddenly confronted with a new feature that was already turned on.
+  Not being able to identify where it came from? 
+  Discover that feature is broken!

I’m all for new features but turning them on by default, unexplained and for them then to be broken is not good practice.

### Debug Information

Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2130
Current ANSI codepage : 1252
Plugins : none

**Comment by UnPrioritized** [comment] 2022-10-23 09:59
Duplicate #12349

**Comment by ArkadiuszMichalski** [comment] 2022-10-23 11:03
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12281.

**Closed by ArkadiuszMichalski** 2022-10-23 11:03 UTC
