### ISSUE TITLE
Make find in files not freeze the entire editor while in progress

### ISSUE THREAD

**Issue by robotboy655** [notepad-plus-plus/notepad-plus-plus#1465] opened 2016-02-12 14:15 UTC
This is one of the most annoying things right now.
You cannot use Notepad++ while "Find in Files" is in progress.

This is especially annoying when when you are searching for extremely large repositories.

I am not asking for being able to run multiple "Find In File"s, that would be a bad idea.

**Comment by dail8859** [comment] 2016-02-12 14:58
Duplicate of #1190

**Closed** 2016-02-12 17:56 UTC
