### ISSUE TITLE
Encoding problems - changes symbols on re-opening file

### ISSUE THREAD

**Issue by Cysign** [notepad-plus-plus/notepad-plus-plus#3172] opened 2017-04-17 19:45 UTC
Hi,
I figured out n++ has some issues saving files properly.
I just lost an important password using a simple txt-file as some special characters changed when reopening the file.

As I'm using npp for more than 5 years now and never noticed this behavior before, I wonder what changed.
Might this be a buggy release? (7.3.3 32bit)
Or might there be a maleous plugin?

Installed plugins are:
-compare
-converter
-customize toolbar
-falling bricks
-indent by fold
-mime tools
-npp export
-nppFtp

**Comment by Cysign** [comment] 2017-04-23 02:09
Reinstallint npp didn't help.

**Comment by Cysign** [comment] 2017-04-23 02:22
I copied the changed symbols to google and it looks like the German characters are transformet to hebrew.
I already deletes the %APPDATA%/notepad++ directory to reset settings. No changes here.

**Comment by Cysign** [comment] 2017-06-08 13:30
Still nobody any idea?
I stopped using N++ - as it still was my absolute favorite texteditor for many, many years! :(

**Comment by dinkumoil** [comment] 2017-06-23 13:28
I can confirm this odd behaviour. It seems to be an issue with the automatic encoding detection of Notepad++.

Steps to reproduce (Notepad++ v7.4.2 32bit):

1. Open Notepad++ and set the default encoding for new files to ANSI. On a german Windows installation this means codepage Windows-1252.
2. Close Notepad++.
3. Open Notepad++
4. Type only the german umlaut characters äöüßÄÖÜ.
5. Save the document.
6. Close Notepad++
7. Open the document with Notepad++.

The file's content is displayed wrong, one can see some hebrew characters and some symbols for undisplayable characters (it's something like הצִײ).

In the status line one can see that Notepad++'s automatic encoding detection has considered the file to be encoded with codepage Windows-1255. That's the codepage for hebrew characters.

After switching the encoding to ANSI (menu Encoding -> ANSI) the file's content is displayed as ×”×¦ï¢•ï¢“Ö´×²ï¢

After switching encoding to Windows-1252 (menu Encoding -> Character Set -> Western European -> Windows-1252) the file's content is diplayed correct.

@Cysign : A workaround for you would be to store your password document with encoding UCS2-Little Endian. To achieve this you have to switch to this encoding schema via menu Encoding -> UCS-2 Little Endian **before** writing content to the document. You can confirm to be on the right encoding schema by looking at the right side of the status line at the lower edge of Notepad++'s window. It has to show UCS-2 LE BOM.

**Comment by webracer999** [comment] 2021-07-04 13:36
I've got a similiar issue.

I've simplified the test case for my issue: When I create a new file only with "ö" as UTF-8, save it, close it, load it again - then Notepad++ opens it with codepage TIS-620: "รถ".

[utf8 with german umlaut.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6759938/utf8.with.german.umlaut.txt)

**Closed** 2021-12-27 19:19 UTC
