### ISSUE TITLE
don't switch to modified document 

### ISSUE THREAD

**Issue by KlausiD** [notepad-plus-plus/notepad-plus-plus#3599] opened 2017-08-04 15:20 UTC
### Steps to Reproduce the Issue
1. open Document A in notepad++
2. working on Document B in notepad++

If the document A is modified outside notepad++, a Message box is opened.
The notepad++ switch automatical to Document A. 

### Expected Behavior
This is very annoying!
I must then always change to document B first to work further
I have the appropriate lines out.
Perhaps one can rewrite this, that one can select the behavior through settings.

void Notepad_plus::prepareBufferChangedDialog(Buffer * buffer)
{
	// immediately show window if it was minimized before
	if (::IsIconic(_pPublicInterface->getHSelf()))
		::ShowWindow(_pPublicInterface->getHSelf(), SW_RESTORE);

	// switch to the file that changed
#if 0
	int index = _pDocTab->getIndexByBuffer(buffer->getID());
	int iView = currentView();
	if (index == -1)
		iView = otherView();
	activateBuffer(buffer->getID(), iView);	//activate the buffer in the first view possible

	// prevent flickering issue by "manually" clicking and activating the _pEditView
	// (mouse events seem to get lost / improperly handled when showing the dialog)
	auto curPos = _pEditView->execute(SCI_GETCURRENTPOS);
	::PostMessage(_pEditView->getHSelf(), WM_LBUTTONDOWN, 0, 0);
	::PostMessage(_pEditView->getHSelf(), WM_LBUTTONUP, 0, 0);
	::PostMessage(_pEditView->getHSelf(), SCI_SETSEL, curPos, curPos);
#endif
}

**Comment by neoncube2** [comment] 2017-08-05 21:34
I agree; it would be very nice if Notepad++ didn't automatically change tabs when a file is modified.

**Comment by protector1990** [comment] 2017-08-07 23:39
I agree that sometimes it is annoying, especially if multiple files have changed. But what do you think about having a "return to original document after modified files are reloaded" check box in that dialog when user is asked wheather to reload the file?

**Comment by neoncube2** [comment] 2017-08-08 02:45
@protector1990, IMHO, I think that would probably be overcomplicating things.

I actually just had this happen to me again not long ago, and I think that the current behaviour is that whether you press "OK" or "Cancel", you're switched to the tab for the file that Notepad++ was asking you if you wanted to reload or not. Changing it so if you pressed "OK", the new tab was focused and if you pressed "Cancel" seems like a good move to me.

It's also really annoying when you do something like, say, do a pull from Git and then you have a ton of prompts in Notepad++ that you have to click through.

One solution to this might be to have the prompt appear when the tab for a file that had changed is focused, instead of just when Notepad++ is focused.

**Comment by protector1990** [comment] 2017-08-10 18:15
Well, there are obviously multiple ways for approaching this problem, and anyway you go about it, application behavior will be changed. Now the question is what behavior is the best one, and we are not the ones to decide on it. Personally, I think that notepad++ should alert the user when a file was changed on the disk, but switching to that file by default isn't the best option.

Your suggestions seems like a good option, too, where n++ alerts user only when they switch to the affected file.

**Comment by KlausiD** [comment] 2017-08-11 07:24
I also find that this is the best idea. So you will not unnecessarily disturbed at work.
Until this is implemented, I help with my patch.

**Comment by 42degrees** [comment] 2018-10-12 20:00
This is a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087)

**Closed** 2019-03-17 12:05 UTC
