### ISSUE TITLE
Document peek windows steal focus from the main window

### ISSUE THREAD

**Issue by chrisaverage** [notepad-plus-plus/notepad-plus-plus#3324] opened 2017-05-27 17:34 UTC
### Description of the Issue
Document peek windows steal focus from the main window. This causes annoying flashing of the main window frame when moving mouse over and out of the document tabs. This is extremely annoying when you have a dark frame color set, as it causes to flash from the default inactive white to the dark active color.

### Steps to Reproduce the Issue
1.  Enable document peek feature.
2.  Hover the cursor over a tab of any inactive document to trigger the document peek.
3.  Hover the cursor off the tab bar.

### Expected Behavior
The main window should keep focus.

### Actual Behavior
The main window looses focus which causes the window frame to change colors.

### Debug Information
Here's what it looks like:

![notepadpp](https://cloud.githubusercontent.com/assets/5970808/26523225/248e6a12-4313-11e7-8c5d-160f299b3305.gif)

**Comment by SinghRajenM** [comment] 2017-05-27 17:54
Similar to #3262

**Comment by Hadakajime** [comment] 2017-12-06 01:41
Steals focus from the Find window to the main window too, as of v7.5.1

**Comment by SinghRajenM** [comment] 2019-04-13 04:01
@MetaChuh this is duplicate.

**Comment by MetaChuh** [comment] 2019-04-13 10:07
closed as duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3262

**Closed by MetaChuh** 2019-04-13 10:07 UTC
