### ISSUE TITLE
Open dialog says "Save" instead of "Open" on the bottom right button

### ISSUE THREAD

**Issue by nphull** [notepad-plus-plus/notepad-plus-plus#10118] opened 2021-07-07 13:15 UTC
### Description of the Issue
The file open dialog's confirmation button at the bottom right says "Save" instead of "Open".

### Steps to Reproduce the Issue
Open the file open dialog (File -> Open or click the Open... icon). This is also true of the Open Folder As Workspace... dialog.

### Expected Behavior
Button says "Open".

### Actual Behavior
Button says "Save".

### Debug Information
Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/34524794/124764838-61954300-df03-11eb-93f6-3fb02e4748de.png)

**Comment by sasumner** [comment] 2021-07-07 13:24
Duplicate of #9966 #10030 #10031 #10047 and possibly others.
This has been fixed in 8.1.
Please search for existing issues (open OR closed) before creating a new one -- thanks.
Closing.

**Closed by sasumner** 2021-07-07 13:24 UTC
