### ISSUE TITLE
UDL support for number-containing keywords inside delimiters

### ISSUE THREAD

**Issue by icalebwilliams** [notepad-plus-plus/notepad-plus-plus#677] opened 2015-08-07 17:38 UTC
In the UDL module, keywords which contain numbers take on correct format outside of delimiters such as parentheses. However, inside parentheses number formatting seems to override keyword formatting if both are allowed to be nested.

![code example](https://cloud.githubusercontent.com/assets/13697650/9141596/8b89fbee-3cff-11e5-8e2f-c8abbd1fc16d.PNG)
This segment should format the keyword $3 the same as $1, both are explicitly listed in the same keyword group and $3 formats just fine outside of parentheses. Both the keyword group and numbers are checked in the parentheses delimiter nesting options.

![code example2](https://cloud.githubusercontent.com/assets/13697650/9141664/0a432910-3d00-11e5-9a26-95bde372c3aa.PNG)
The above segment shows $3 formatted correctly outside of parentheses with a number correctly formatted inside the parentheses.

The issue seems to come down to keywords taking priority over numbers outside of delimiters while numbers take priority over keywords inside delimiters. 

![code example3](https://cloud.githubusercontent.com/assets/13697650/9141775/b043dbde-3d00-11e5-9902-717f3d0a92d8.PNG)
Setting the keyword group on prefix mode formats the keywords such as $3 correctly inside parentheses as show in the above segment. However it formats any adjacent following symbol as a number (such as the comma in this segment) and tends to break code folding as delimiters and operators are turned into numbers.

![code example4](https://cloud.githubusercontent.com/assets/13697650/9141816/0cfefaa2-3d01-11e5-91ca-c5c0c7fe6f86.PNG)
This final line of code shows all components formatted as they should be with both keywords and numbers nested inside parentheses.

**Comment by MetaChuh** [comment] 2019-04-11 00:10
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:10 UTC
Labels: enhancement, language-support
