### ISSUE TITLE
[Bug report] recurrance bug with regex

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8554] opened 2020-07-12 03:28 UTC
Create a document with 4453 lines each containing a URL: 
[RecurranceBug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/4907960/RecurranceBug.txt)

Then try to use this regular expression to add a double line break every 500 lines (the first 500 are at lines 1-500, then 502-1001, and so on):

Find what: `((^https://.*?$\R){500})`
Replace with: `\1\n`
Wrap around: checked
Search mode: Regular expression
. matches newline: unchecked

and press “replace all”. After that, if you try to find `https` and hit “find all in current document”, there are 4388 results, therefore 65 URLs have been deleted (4453 total links - 4388 links after the replace function).

Also, 4453/500 should find **8** groups of 500, (because there are 8 complete groups, plus a fraction of 500 being 453), not 9.

**Comment by astrosofista** [comment] 2020-07-12 22:17
Developpers will tell you if it's a bug or not, but in the meantime, try this S/R regex instead:

Find what: `(?-s)(.*\R){500}\K`
Replace with: `\n`
Wrap around: checked
Search mode: Regular expression
Click only in "Replace All"

Tested on Notepad++ v7.8.7   (64-bit)

**Comment by sasumner** [comment] 2020-07-12 23:44
Interesting.
If you uncheck _Wrap around_ and move caret to start-of-file and repeatedly press the _Replace_ button (not _Replace All_), on the ninth press the entire file will become selected.
This reminds me of #4761 but this needs more investigation.

**Comment by sasumner** [comment] 2020-07-12 23:59
I can confirm the same conditions of #4761 occur here.
If we look at the `processFindNext` function, here:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/acb4e5ae1848c921a016bf348b698ca4ff779a9b/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L1595
It calls `SCI_SEARCHINTARGET` via this:  https://github.com/notepad-plus-plus/notepad-plus-plus/blob/acb4e5ae1848c921a016bf348b698ca4ff779a9b/PowerEditor/src/ScitillaComponent/FindReplaceDlg.cpp#L1688
If I add a call to `SCI_GETSTATUS` after the search-in-target, and then walk through @GhbSmwc 's example using repetitive _Replace_ button presses, I'll get to the point where the get-status returns 1 indicating a catastrophic failure of the regular expression engine.
There isn't much to be done with such a failure, except Notepad++ needs to report it to the user, not fail quietly by selecting all the text in a document.
Closing this because this issue is known and will be dealt with in 4761.

**Closed by sasumner** 2020-07-12 23:59 UTC

**Comment by GhbSmwc** [comment] 2020-07-13 00:24
> Developpers will tell you if it's a bug or not, but in the meantime, try this S/R regex instead:
> 
> Find what: `(?-s)(.*\R){500}\K`
> Replace with: `\n`
> Wrap around: checked
> Search mode: Regular expression
> Click only in "Replace All"
> 
> Tested on Notepad++ v7.8.7 (64-bit)

Wait, how did this not select any text (zero length match)?

**Comment by sasumner** [comment] 2020-07-13 11:40
>Wait, how did this not select any text (zero length match)?

Your testing scenario was a _Replace All_.
I altered the scenario a bit so that I could more easily see the failure, as I suspected its type.
