### ISSUE TITLE
Feature Request : Default character set when auto-detect encoding fails

### ISSUE THREAD

**Issue by rudibr78** [notepad-plus-plus/notepad-plus-plus#1031] opened 2015-10-20 13:11 UTC
When auto-detect encoding fails to detect the encoding, non-utf8 files will get their characters garbaged.
This is a very common occurance for us. Everytime we open a file that notepad++ fails to detect encoding, we have to manually set character sets->ISO-8859-1 to unscramble the punctuation chars, etc.

It would be great if we could set this to a default configurable option.

**Comment by RafaelLVX** [comment] 2015-10-22 03:31
I know this doesn't help you, but I just wanted to share that in my end I also use ISO-8859-1 files which it many times detects as ANSI, but special characters display correctly, I don't know how.

**Comment by aaaxx** [comment] 2015-10-31 07:01
Rafael, ANSI is a misnomer for your system's codepage (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/987), which is probably Windows-1252, which mostly coincides with ISO-8859-1.

**Comment by MetaChuh** [comment] 2019-04-10 23:43
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:43 UTC
