### ISSUE TITLE
Open links only when holding Ctrl

### ISSUE THREAD

**Issue by justanotheranonymoususer** [notepad-plus-plus/notepad-plus-plus#3437] opened 2017-06-24 11:16 UTC
Hi,

Sometimes I'd like to double click to select a word which is a part of a link. Sometimes I'd like to open that link in a browser. Currently, only the one or the other can be done.
Please allow to open the link only when the Ctrl key is pressed. Thanks!

**Comment by ArkadiuszMichalski** [comment] 2021-11-11 00:04
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9993.

**Closed by ArkadiuszMichalski** 2021-11-11 00:04 UTC
