### ISSUE TITLE
New save confirmation lacks keyboard shortcuts

### ISSUE THREAD

**Issue by tkbletsc** [notepad-plus-plus/notepad-plus-plus#7656] opened 2019-11-24 19:45 UTC
### Description of the Issue

The recent update to Notepad++ 7.8.1 introduced a new save confirmation dialog on close. The old dialog was a Windows native one that allowed keyboard shortcuts "Y" and "N"; the new one does not, and requires you to click on the actual buttons. This is a painful impediment to quickly dealing with temporary files. 

### Steps to Reproduce the Issue

1. Create a new file and add content
2. Close the file
3. Save confirmation dialog appears
4. Attempt to press "N" to quickly dismiss it with a "no" answer
5. Keyboard input is ignored.

### Expected Behavior

That pressing "Y" and "N" would answer the question as has been the case for a long time.

### Actual Behavior

Keyboard input is ingored.

### Debug Information

Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.239
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

Screenshot with annotated change request: 
![image](https://user-images.githubusercontent.com/1093292/69500432-0ac32d00-0ec9-11ea-8fa3-db4034526870.png)

**Comment by xylographe** [comment] 2019-11-24 20:50
Fixed in commit f780e22d6117dbc4b5ebf83b594505874ac3fc68. Will be available in next release. If you don't want to wait for next release, download **`Notepad++.Win32.Unicode Release.exe`** from [AppVeyor Artifacts](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/29066798/job/x47ssndfb67way2x/artifacts), and replace **`notepad++.exe`**.

**Comment by xylographe** [comment] 2019-11-24 21:00
Replace **`C:\Program Files (x86)\Notepad++\localization\english.xml`** with [the updated engish.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml). Start NPP, open **Preferences** dialogue, change to different language, change language back to Enlish.

**Comment by ChristianGfK** [comment] 2019-11-25 20:22
Thanks @xylographe, saved my day. :+1:

**Comment by sasumner** [comment] 2019-11-25 20:55
Closing as duplicate of #6223

**Closed by sasumner** 2019-11-25 20:55 UTC
