### ISSUE TITLE
Restore opened file tabs for temporarly unavailable file paths

### ISSUE THREAD

**Issue by znik3040** [notepad-plus-plus/notepad-plus-plus#13696] opened 2023-05-24 11:05 UTC
### Description of the Issue
When I forgot map network drive or mount crypted volume, or any else with logical hard drive letter is unavailable (E:\ F:\ to Z:\.) and run notepad++, then editor silently drops all opened files for that drive(s) without additional info, because paths are unavailable.

### Steps to Reproduce the Issue
1. in command line emulate network drive or crypted volume
1a. **run cmd.exe**
1b. **mkdir C:\W**  (subdir for emulation **W:\** drive, of course if **W:\** is free on your system)
1c. **subst W: C:\W**  (at now you have drive W  . please do not close cmd.exe, it will be helpful later
2. open notepad++ , create new tab for text file, and write any text inside this tab
3. write this file for example as **W:\testfile.txt**
4. close notepad++ and run it again. you will see opened file **testfile.txt** , this is OK
5. close notepad++
6. click again cmd.exe window, and delete emulated drive by run **subst W: /D**
7. open notepad++ again.
8. this is all. you will not be noticed about lost path to **W:\testfile.txt** , and tab will not be open again.

### Expected Behavior
I need some configuration for this one, by selecting between:
1. **silent** do not open unavailable paths
2. **warning window**, with info about unavailable paths, short info similar to 'please map network or crypto drives W:, X: etc.... and or select below...', with two buttons 'Do not open listed files' , and second 'Try again'.
3. continuation to ad.2 , if still any paths are unavailable, do corrected list again described at point 2

### Actual Behavior
currently default is silently abort opening tabs for unavailable paths

### Debug Information
There is no debug. This behavior exist on all available versions notepad++

**Comment by alankilborn** [comment] 2023-05-24 11:28
Duplicate of #12079.
Please search already-existing issues for your topic before creating new.

**Comment by alankilborn** [comment] 2023-05-25 11:04
For same dysfunction, only ONE issue should exist.  In the comments of that one issue can be discussed many different approaches to solving.  That way, someone that is going to solve it has all data in one place.

**Comment by ArkadiuszMichalski** [comment] 2023-09-30 12:14
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12079 and other.

**Closed** 2023-10-22 22:08 UTC
Labels: duplicate
