### ISSUE TITLE
UTF-8 encoding does not display non-printable characters

### ISSUE THREAD

**Issue by XelaNimed** [notepad-plus-plus/notepad-plus-plus#12289] opened 2022-10-05 17:18 UTC
### Description of the Issue

When pasting text from the clipboard, non-printable characters are not displayed when the document encoding is set to UTF-8.  
When you switch the document encoding to ANSI, non-printable characters are displayed. 

This further leads to errors when processing the copied text, for example, in various IDEs or source code editors - in general, in cases where the text is processed character by character.

### Steps to Reproduce the Issue

1. Copy the following text to clipboard (in this case text contains [Zero Width Spaces](https://unicode-table.com/en/200B/)): `this is test​;​ `
2. Open Notepad++, create a new document and set encoding to UTF-8 ("Encoding"->"UTF-8")
3. Set to display all characters ("View"->"Show Symbol"->"Show all characters")
4. Paste the contents of the clipboard into the document - only printable characters are displayed.
5. Switch Document Encoding to ANSI ("Encoding"->"ANSI")
6. Previously invisible characters are displayed

### Expected Behavior

When the menu item "View"->"Show Symbol"->"Show all characters" is activated, it is expected to see non-printable characters in some form.

### Actual Behavior

When using UTF-8 encoding, non-printable characters are not displayed.

![UTF-8-ANSI](https://user-images.githubusercontent.com/685832/194121898-5e4ec3f6-b591-429e-a487-ea6d285479b5.gif)

### Debug Information

Notepad++ v8.4.6   (32-bit)
Build time : Sep 25 2022 - 19:55:26
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : "C:\Program Files (x86)\Notepad++\change.log" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.2006
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    CSScriptNpp (2.0.2)
    FileSwitcher (1.0.3)
    JSLintNpp (0.8.3.119)
    JSMinNPP (1.2205)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (2.8)
    MultiClipboard (2.1)
    NppConverter (4.4)
    nppcrypt (1.0.1.6)
    NppExec (0.8)
    NppExport (0.4)
    NppHasher (1)
    NppJavaPlugin (0.4)
    NPPJSONViewer (1.40)
    NppQrCode32 (0.0.0.1)
    NppUISpy (1.0.4)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

**Comment by alankilborn** [comment] 2022-10-05 17:26
Basically a duplicate of #8284 (that one had a limited title, but the comments expanded it to include making characters that had no visual component visible).  I believe it is still the master issue for such related topics.

BTW, changing the encoding to ANSI in the example serves to make invisible UTF-8 characters visible, but it really isn't a valid thing to do.

>"View"->"Show Symbol"->"Show all characters"

Historically, the meaning of that was to show spaces (of the U+0020 variety), tabs (U+0009), CR (U+000D) and LF (U+000A) with a visual component.

**Comment by ArkadiuszMichalski** [comment] 2022-10-05 22:16
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8284.

**Closed by ArkadiuszMichalski** 2022-10-05 22:16 UTC
