### ISSUE TITLE
Theme bug in portable version

### ISSUE THREAD

**Issue by qx87** [notepad-plus-plus/notepad-plus-plus#1344] opened 2016-01-09 07:18 UTC
I use portable version of NP++ on my USB flash stick. And I use non-default theme (Settings->Style configurator). Almost every time when I insert USB flash into another computer, I do not see my chosen theme.

That is because theme setting uses absolute file name. As far as I can see it is located in config.xml. Something like this:

`<GUIConfig name="stylerTheme" path="H:\Programs\Notepad++\themes\Deep Black.xml" />`

And of course after inserting USB flash into a computer its hosting OS imperatively assigns random drive letter for USB flash. Then NP++ fails finding selected theme and uses default one.

But portable version must avoid using absolute names anywhere. I think whether this setting should use relative name starting from NP++ path, such as

`<GUIConfig name="stylerTheme" path="themes\Deep Black.xml" />`

or portable NP++ should provide some environment variable like COMMANDER_PATH in Total Commander.

**Comment by ClaudiaFrank** [comment] 2016-01-13 05:06
temporary workaround
<GUIConfig name="stylerTheme" path=".\themes\Deep Black.xml" /> seems to work.

**Comment by qx87** [comment] 2016-01-13 07:31
Yes, it does, unless one changes the options in GUI. Thank you.

**Comment by MetaChuh** [comment] 2019-04-11 00:59
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:59 UTC

**Comment by clonsberry** [comment] 2022-11-01 13:24
For others who are searching: I wrote [workaround instructions](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9409#issuecomment-1298496463) in 9409.
