### ISSUE TITLE
"Style token" regression - adjusting case in/sensitivity and whole word match options

### ISSUE THREAD

**Issue by bmcdonnell** [notepad-plus-plus/notepad-plus-plus#10431] opened 2021-08-23 04:13 UTC
### Description of the Issue
Previous behavior of the "Style token" matching was that its case sensitivity and whole/partial word behavior would be set according to those options in the "Find" dialog. Since some recent versions (at least since 8.1.2, maybe earlier; and still in the latest, 8.1.3), these options no longer control the "Style token" matching behavior.

It seems these controls have been moved to `Settings` &rarr; `Preferences...` &rarr; `Highlighting` &rarr; `Mark All`. I think this is worse behavior for 2 reasons:

1. It takes longer to access. I use and adjust those settings frequently. I used to be able to do so quickly with `Ctrl+F`, `Alt+[CW]`, `Esc`. Now it's `Alt+T`, `Enter`, `H`, and then either [tabbing to get to the desired fields, `space` to (de)select, and tabbing again to get to `Close`, and space/Enter], or [using the mouse for all of that].

2. The wording doesn't match (`Style token` vs `Mark all`), so it's unclear that it's controlling that. (Granted, this was arguably true of the previous behavior, too.)

Please make these options quick and easy to adjust with keyboard navigation. Reverting to the previous behavior would be OK with me, but IDK how others would feel about that, and there's probably a better, clearer way.

### Debug Information
```
Notepad++ v8.1.3   (64-bit)
Build time : Aug 10 2021 - 00:29:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Program Files\Notepad++\change.log" 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.985
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll SessionMgr.dll XMLTools.dll 
```

**Comment by mere-human** [comment] 2021-08-23 07:34
@bmcdonnell Have you tried the preference "Use find dialog settings"?
![image](https://user-images.githubusercontent.com/9664141/130408395-ab7fd52c-669f-4bc3-be65-b20bc7eba578.png)

**Comment by ArkadiuszMichalski** [comment] 2021-08-23 11:06
>2. The wording doesn't match (Style token vs Mark all), so it's unclear that it's controlling that. (Granted, this was arguably true of the previous behavior, too.)

Will be fixed in next release, see this https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10195#issuecomment-899269922.

Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10195#issuecomment-899269922. if you really want to control `Style All` through the Find dialog.

**Closed by ArkadiuszMichalski** 2021-08-23 11:06 UTC
