### ISSUE TITLE
can you please re-add informations about all notepad++ versions in its website?

### ISSUE THREAD

**Issue by zahra21** [notepad-plus-plus/notepad-plus-plus#9745] opened 2021-04-08 08:23 UTC
hello every one.
in the previous version of notepad++ website, informations about all new features, changes, and bug fixes of notepad++ was available.
i could find any version which i wanted to know about, open and read the informations, and download any version which i wanted to download.
unfortunately, this great opportunity is not available now.
i cant find news and read whats'new of notepad++ especially previous versions.
i wish that i can read all informations and have download links for all versions in the way that i love and used previously.
even in the download page of version 7.5.6 and 7.6.2, all informations about new features and changes and bug fixes are the same!
https://notepad-plus-plus.org/downloads/v7.6.2
https://notepad-plus-plus.org/downloads/v7.5.6

**Comment by mere-human** [comment] 2021-04-08 08:28
It is present below on the download page:
https://notepad-plus-plus.org/downloads/v7.9.5/
> Notepad++ v7.9.5 Enhancements & bug-fixes:

**Comment by zahra21** [comment] 2021-04-08 09:18
yes, i know that current version of notepad++ website, has informations about newer versions of program.
but informations about previous versions are missing.
for example: version 7.6.1 and previous ones.
for example: i did not find informations about 6.5.2 or 6.9.2 or version 5 and previous versions.
i know that the old website had informations about all notepad++ versions.

**Comment by ArkadiuszMichalski** [comment] 2021-04-08 09:40
You can try with web.archive.org:
http://web.archive.org/web/20190727112423/https://notepad-plus-plus.org/download/all-versions.html

**Comment by sasumner** [comment] 2021-04-08 11:25
Another good way to get this information might be to look on the Community site, at the announcements.  An advantage to this is not only do you get a list of the changes, but (for relatively recent versions) you also get github links to the issues that were implemented.

Example:  https://community.notepad-plus-plus.org/topic/20883/notepad-v7-9-4-released

**Comment by zahra21** [comment] 2021-04-08 11:48
> 
> 
> You can try with web.archive.org:
> http://web.archive.org/web/20190727112423/https://notepad-plus-plus.org/download/all-versions.html

archive.org
its a great website.
i should test it, but one of the advantages of opensource programs is having choice for us.
read all informations about all versions,
and download any version that we need.
i really wish to read these informations about notepad++ website.
thanks and God bless you for your help!

**Comment by zahra21** [comment] 2021-04-08 12:07
H

> 
> 
> Another good way to get this information might be to look on the Community site, at the announcements. An advantage to this is not only do you get a list of the changes, but (for relatively recent versions) you also get github links to the issues that were implemented.
> 
> Example: https://community.notepad-plus-plus.org/topic/20883/notepad-v7-9-4-released

yes, i am very glad that notepad++ informations and github links are all available in both its main website and community site.
but how about previous versions?
many versions informations about their new features, changes and bug fixes are not available, in your new website,
and for notepad++ 7.9 and previous versions, (the versions that i can only read their change.log or download them in the website, but github link is not available.
i found many new features and bug fixed which i want to find their github link and read the details.
how can i find?
thanks for your help and quick response and God bless you!

**Comment by sasumner** [comment] 2021-04-08 12:12
>how can i find?

The true answer is that you'd have to dig into the github history for the code.

**Comment by zahra21** [comment] 2021-04-08 12:14
0 

> 
> 
> > how can i find?
> 
> The true answer is that you'd have to dig into the github history for the code.

can you please send the suitable link for me please?

**Comment by sasumner** [comment] 2021-04-08 12:47
>can you please send the suitable link for me please?

https://github.com/notepad-plus-plus/notepad-plus-plus

**Comment by pryrt** [comment] 2021-04-08 13:54
The OP also [asked about it in the forum](https://community.notepad-plus-plus.org/topic/21003), and Alan provided a condensed list from all of the versions that he had archived over the years.

Thinking about it, it might be nice to have, and it would not be difficult to maintain once we got the initial history imported.  Other projects, such as Scintilla, do have a [Version History page](https://www.scintilla.org/ScintillaHistory.html) on their website, so this isn't a desire unique to one person.

And even for getting the initial history: it wouldn't go back to the very earliest versions, but traversing the [github history on `change.log`](https://github.com/notepad-plus-plus/notepad-plus-plus/commits/4399c1343b96aee0c5419f130ddd984dc86f02d7/PowerEditor/bin/change.log) should be able to extract most of the history -- it looks like it goes back to v5.4... so not quite as far as @zahra21 was asking about.

**Comment by zahra21** [comment] 2021-04-08 14:27
> 
> 
> > can you please send the suitable link for me please?
> 
> https://github.com/notepad-plus-plus/notepad-plus-plus

i opened the link that you mentioned.
the only helpful linkwhich i found was related to 7.9.5, (current version).
https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.9.5
i change 7.9.5 to 7.5.9.
then, i found a link in your main website which does not work.
https://notepad-plus-plus.org/news/notepad-7.5.9-released.html
i recieve error message.
Oops, looks like the page is lost.
This is not a fault, just an accident that was not intentional.
i expect that i can read informations about all notepad++ versions like 7.5.9 and even previous versions that not available in notepad++ main website anymore.

**Comment by sasumner** [comment] 2021-04-08 14:45
Scintilla was mentioned.  Its history contains links to issues in their bug tracker.  It would be nice if such a page for N++ could do the same.  @donho has been doing this only very recently in the announcement postings on the Community site.

**Comment by guy038** [comment] 2021-04-08 18:00
Hello, @zahra21, @sasumner, @ArkadiuszMichalski, @mere-human and **All**,

The **magic** link is :

http://download.notepad-plus-plus.org/repository/

---

- Explore each main **sub-folder**, then each **sub-folder** N++ **version**

- Click on a **`installer`** link to download any **installer** version

- Open this **`.exe`** with **`7-zip`**

- **Extract** the **`change.log`** file

- Repeat these operations  to get **all** the **`change.log`** files, from **`Notepad_plus.10.bin.zip`** till **`Npp.7.9.5.Installer.exe`** ;-))

Best Regards,

guy038

**Comment by donho** [comment] 2021-04-09 04:01
I wish all the change log info could be kept on the Notepad++ page. However each change of home page lost some history.

> The magic link is :
> http://download.notepad-plus-plus.org/repository/
> ...
> Repeat these operations to get all the change.log files, from Notepad_plus.10.bin.zip till Npp.7.9.5.Installer.exe ;-))

@guy038  is right. That's the only way to get the whole history.

@zahra21 If you rebuild this history, then I will find a place to store it, and continue to maintain it on every release.

**Comment by zahra21** [comment] 2021-04-09 06:34
> 
> 
> I wish all the change log info could be kept on the Notepad++ page. However each change of home page lost some history.
> 
> > The magic link is :
> > http://download.notepad-plus-plus.org/repository/
> > ...
> > Repeat these operations to get all the change.log files, from Notepad_plus.10.bin.zip till Npp.7.9.5.Installer.exe ;-))
> 
> @guy038 is right. That's the only way to get the whole history.
> 
> @zahra21 If you rebuild this history, then I will find a place to store it, and continue to maintain it on every release.

i am very glad to do this.
how can i start?
should i make html format or txt file is enough?
also, i dont know their link on github.
but its very great if notepad++ website has history page with relevant github link like scintilla website and history page.
can i correct misspeled words also?
i found many different many misspeled words in various change.log of notepad++

**Comment by zahra21** [comment] 2021-04-09 06:37
0

> 
> 
> Hello, @zahra21, @sasumner, @ArkadiuszMichalski, @mere-human and **All**,
> 
> The **magic** link is :
> 
> http://download.notepad-plus-plus.org/repository/
> 
>     * Explore each main **sub-folder**, then each **sub-folder** N++ **version**
> 
>     * Click on a **`installer`** link to download any **installer** version
> 
>     * Open this **`.exe`** with **`7-zip`**
> 
>     * **Extract** the **`change.log`** file
> 
>     * Repeat these operations  to get **all** the **`change.log`** files, from **`Notepad_plus.10.bin.zip`** till **`Npp.7.9.5.Installer.exe`** ;-))
> 
> 
> Best Regards,
> 
> guy038

hello.
thanks so much for your great advice.
is it possible that i can extract all change.logs of notepad++ without downloading all versions?

**Comment by guy038** [comment] 2021-04-09 11:06
Hi, @zahra21, @sasumner, @ArkadiuszMichalski, @mere-human and **All**,

Oooups ! The **installer** package exists **only** since N++ v1.8 !

Anyway, you don't have to do anything else ! @vinsworldcom did it for you ;-)) Refer to :

https://gist.github.com/vinsworldcom/3fe7d0cd9c11745e4cb6d0095b4d94c5

BR

guy038

**Comment by zahra21** [comment] 2021-04-09 11:27
> 
> 
> Hi, @zahra21, @sasumner, @ArkadiuszMichalski, @mere-human and **All**,
> 
> Oooups ! The **installer** package exists **only** since N++ v1.8 !
> 
> Anyway, you don't have to do anything else ! @vinsworldcom did it for you ;-)) Refer to :
> 
> https://gist.github.com/vinsworldcom/3fe7d0cd9c11745e4cb6d0095b4d94c5
> 
> BR
> 
> guy038

hi.
i really wished to have even one contribution in my favorite program.
i thought that i download all versions of notepad++ and extract change.log files and put all of them in one txt file and attach the file here.
i did not want to download installer files, because of confliction between various different versions that maybe i lose my files or daily usage.
for example: i downloaded version 5.0 and it could not open my txt files.
my laptop is very old from 2006.
when i opened the link that you mentioned, i observed immediate unresponsiveness of my firefox and my entire system frozed.
i could not use my keyboard and my screen reader after that. i killed firefox in task manager to continue to use my laptop again.

**Comment by ArkadiuszMichalski** [comment] 2021-04-09 11:27
Oh, I didn't know anyone had already started doing this.  I just finished mine :) 
https://github.com/ArkadiuszMichalski/NPP_tools/tree/main/_change
https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md

I used the reverse order (newest to oldest). More information can be added in the file `change.md` (link to download, release date, etc.). I also extracted all the `change.txt` files so anyone can download all and make a list in own format. 

@donho 
Where do you want to put such a condensed list? On main page or here in Wiki? And what format do you prefer? A few versions, for example, would be enough to follow this pattern.

**Comment by vinsworldcom** [comment] 2021-04-09 12:20
Might as well chime in with mine complete that was reference above.

oldest to newest = https://gist.github.com/vinsworldcom/3fe7d0cd9c11745e4cb6d0095b4d94c5
newest to oldest = https://gist.github.com/vinsworldcom/2e03bc9dc58390841ab0e0b236b3d305

Cheers.

**Comment by donho** [comment] 2021-04-09 21:01
Change logs from v1.0 - v5.3.1 in `News` section:
https://web.archive.org/web/20100114201550/http://notepad-plus.sourceforge.net/uk/site.htm

Good luck.

**Comment by donho** [comment] 2021-04-09 21:14
@ArkadiuszMichalski 
> Where do you want to put such a condensed list? On main page or here in Wiki? And what format do you prefer? A few versions, for example, would be enough to follow this pattern.

Good question. The whole page won't be in notepad-plus-plus.og - there'll be a link to point to this history page in [resources page](https://notepad-plus-plus.org/resources/).
And yes, why not in wiki? So the format will be in Markdown.

**Comment by donho** [comment] 2021-04-09 23:35
Just saw change logs done by @vinsworldcom 👍 
Can [newest to oldest](https://gist.github.com/vinsworldcom/2e03bc9dc58390841ab0e0b236b3d305) go to Wiki ?

**Comment by vinsworldcom** [comment] 2021-04-10 01:31
Fine with me!  Someone with access feel free to copy it there.

Cheers.

**Comment by ArkadiuszMichalski** [comment] 2021-04-10 12:09
This is just a initial version. Now it will be corrected.
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Change.

@donho On the top I add links to all oryginal `.log` files. and to one `.zip` (with all of them). But the links point to my repo. Delete it, leave it, or will there be some official place where such things (files) can be placed?

A few questions about the format:
- I think the version numbers might be a link to the download location http://download.notepad-plus-plus.org, for example [7.0](http://download.notepad-plus-plus.org/repository/7.x/7.0/). Everyone can then choose what exactly to download.
- It is also worth adding the release date, but where, to the right of the version number, like 7.9 (date) or below the version number?

Something like that will be enough?

## [7.9.5](http://download.notepad-plus-plus.org/repository/7.x/7.9.5/)
2021-03-22

Notepad++ v7.9.4 Enhancements & bug-fixes:

1.  Fix Notepad++ not starting up due to SaveAsAdmin plugin (for installer package).
2.  Fix UNC path with quotes handling in folder & file Open/Save dialog.
3.  Fix file doesn't save as extension type on Windows 7.

More fixes & implementations detail:
https://notepad-plus-plus.org/downloads/v7.9.5/

Included plugins:

1.  NppExport v0.2.9
2.  Converter 4.2.1
3.  Mime Tool 2.5

Updater (Installer only):

* WinGup (for Notepad++) v5.1.3

 
Any additional comments or information that should be included? Or do you prefer some other pattern?

**Comment by sasumner** [comment] 2021-04-10 13:24
>Any additional comments or information should be included?

I'll reiterate my request for links to issues for recent versions to be included; see original comment here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9745#issuecomment-815883527

**Comment by ArkadiuszMichalski** [comment] 2021-04-10 13:48
OK, I take them from https://notepad-plus-plus.org/downloads/ (but the first is 7.9.1). Maybe on forum some earlier also had a links to issues. Well, this can be gradually supplemented later, if someone has time.

**Comment by donho** [comment] 2021-04-12 00:16
Just took time to check both @vinsworldcom and @ArkadiuszMichalski closely.
@vinsworldcom text based change log contains very complete information from the beginning. In fact, all we need is 
1. version number
2. release date
3. download link
4. change log


And I like the idea of @ArkadiuszMichalski to have the major version link. I wonder if there's an easy way to combined both logs (@ArkadiuszMichalski's Markdown format and @vinsworldcom's complete info) with the essential above.

## [1.7](http://download.notepad-plus-plus.org/repository/1.x/1.7/npp.1.7.bin.zip)
2004-03-07

Notepad++ v1.7 enhancements and bug-fixes (from v1.6) :

1. Syntax folding for MS ini file is added
2. Improve the asp language support
3. Style Configurator is added. From now on Notepad++ is configurable completely!!!v1.8 new features (from v1.7) :

## [1.6](http://download.notepad-plus-plus.org/repository/1.x/1.6/npp.1.6.bin.zip)
2004-02-11

Notepad++ v1.6 enhancements and bug-fixes (from v1.5) :

1. Support now the hot key Ctrl+Tab / Ctrl+Shift+Tab to switch to the next / previous document.
2. Current Line Highlighting is added (to enable/disable : Menu View -> Current Line Highlighting).
3. Recent File History is now enhanced (eliminate non-available file path before loading Recent File History).
4. go to line # Dialog Box is added (access to it by Ctrl+G or Menu Search->Go to line...)
5. Status Bar is enhanced :
    a. display the current position Ln & Col of caret - double click on this zone will launch "go to line # Dialog Box"
    b. display the insertion mode INS|OVR -  simple click on this zone will switch the alternative insertion mode (The same effect of key stroke Insert)
6. Fixed bug : The focus wasn't restored after switching back to Notepad++.v1.7 new features and fixed bugs (from v1.6) :

## [1.5](http://download.notepad-plus-plus.org/repository/1.x/1.5/npp.1.5.bin.zip)
2004-01-18

Notepad++ v1.5 enhancements and bug-fixes (from v1.4) :


1. Brace and Indent guideline Highlight : When the caret stay beside of one of those symbol "{ } [ ] ( )" the symbol beside of caret and its symetric opposite symbole will be highlighted, as well as the indent guideline in order to locate the bloc more easily.
2. A fixed bug : the incorrect display of line number margin by doing the zoom is corrected.
3. The tooltips for the tool bar are added.
4.  Another fixed bug : The position of the document wasn't restored correctly after closing or drag-and-droping a document.
5. fixed bug again : the Find text dialog didn't memorize the searched words.
6. Syntax HighLighting of asp file is added

**Comment by donho** [comment] 2021-04-12 00:30
@ArkadiuszMichalski 
> On the top I add links to all oryginal .log files. and to one .zip (with all of them). But the links point to my repo. Delete it, leave it, or will there be some official place where such things (files) can be placed?

I don't see the advantage to provide such info, since users have more complete info in this page, so I think we can remove the link from this page.

> I think the version numbers might be a link to the download location http://download.notepad-plus-plus.org/repository/, for example 7.0. Everyone can then choose what exactly to download.
It is also worth adding the release date, but where, to the right of the version number, like 7.9 (date) or below the version number?
Something like that will be enough?

Yes, it's enough - simple and efficient.

> I can also make these headlines more descriptive, like we have in https://notepad-plus-plus.org/downloads/v7.9.5/:

I prefer the 1st one :)

> OK, I take them from https://notepad-plus-plus.org/downloads/ (but the first is 7.9.1). Maybe on forum some earlier also had a links to issues. Well, this can be gradually supplemented later, if someone has time.

If the contributors (including you) have the time to add such info, why not? My point is let's go into the easiest maintaining way - because it could be you who maintain this change log list ;)

**Comment by ArkadiuszMichalski** [comment] 2021-04-12 00:37
@donho
Those mine (especially the first ones) were only from the .log file. Later I will add more detailed info (also from @vinsworldcom or older pages). Although the above is identical to what I have now.

>I don't see the advantage to provide such info, since users have more complete info in this page, so I think we can remove the link from this page.

Ok, in the next update I will remove these links.

I started to correct this list as follows. When I finish the whole 7.x I will update the Wiki for review. 

## [7.x](http://download.notepad-plus-plus.org/repository/7.x/)

### [7.9.5](http://download.notepad-plus-plus.org/repository/7.x/7.9.5/)
2021-03-23

Notepad++ v7.9.5 bug-fixes:

1.  Fix Notepad++ not starting up due to SaveAsAdmin plugin (for installer package). (Fix [#9514](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514))
2.  Fix UNC path with quotes handling in folder & file Open/Save dialog. (Fix [#9582](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9582))
3.  Fix file doesn't save as extension type on Windows 7. (Fix [#9657](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9657))

Included plugins:

1.  NppExport v0.2.9
2.  Converter 4.2.1
3.  Mime Tool 2.5

Updater (Installer only):

* WinGup (for Notepad++) v5.1.3

### [7.9.4](http://download.notepad-plus-plus.org/repository/7.x/7.9.4/)
2021-03-15

Notepad++ v7.9.4 Enhancements & bug-fixes:

1.  Upgrade Scintilla from v4.2.0 to v4.4.6. (Fix [#9550](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9550))
2.  Fix DPI scaling broken while dragging Notepad++ into the 2nd monitor regression. (Fix [#9513](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9513), [#9579](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9579))
3.  Add "Find in Projects" feature. (Fix [#8125](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8125))
4.	Fix project workspace changes lost on save cancel issue. (Fix [#9605](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9605))
5.  Fix folder picker not being launched issue because provided directory is invalid. (Fix [#9569](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9569))
6.  Fix network path (UNC path) not working in file dialog. (Fix [#9527](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9527))
7.  Fix shortcut name more than 64 characters makes a menu entry empty name issue. (Fix [#9556](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9556))
8.  Fix extension appending issue in file dialog. (Fix [#9510](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9510))
9.  Fix file not turning to modified state (with Session Manager plugin) bug after its content being changed. (Fix [#9475](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9475))
10. Add an option to mute all sounds in preferences dialog. (Fix [#7950](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7950))
11. Make JSON auto-indent for brace. (Fix [#9499](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9499))

More fixes & implementations detail:
https://notepad-plus-plus.org/downloads/v7.9.4/

Included plugins:

1.  NppExport v0.2.9
2.  Converter 4.2.1
3.  Mime Tool 2.5

Updater (Installer only):

* WinGup (for Notepad++) v5.1.3

**Comment by zahra21** [comment] 2021-04-12 11:26
> 
> 
> @donho
> Those mine (especially the first ones) were only from the .log file. Later I will add more detailed info (also from @vinsworldcom or older pages). Although the above is identical to what I have now.
> 
> > I don't see the advantage to provide such info, since users have more complete info in this page, so I think we can remove the link from this page.
> 
> Ok, in the next update I will remove these links.
> 
> I started to correct this list as follows. When I finish the whole 7.x I will update the Wiki for review.
> ## [7.x](http://download.notepad-plus-plus.org/repository/7.x/)
> ### [7.9.5](http://download.notepad-plus-plus.org/repository/7.x/7.9.5/)
> 
> 2021-03-23
> 
> Notepad++ v7.9.5 bug-fixes:
> 
>     1. Fix Notepad++ not starting up due to SaveAsAdmin plugin (for installer package). (Fix [#9514](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514))
> 
>     2. Fix UNC path with quotes handling in folder & file Open/Save dialog. (Fix [#9582](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9582))
> 
>     3. Fix file doesn't save as extension type on Windows 7. (Fix [#9657](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9657))
> 
> 
> Included plugins:
> 
>     1. NppExport v0.2.9
> 
>     2. Converter 4.2.1
> 
>     3. Mime Tool 2.5
> 
> 
> Updater (Installer only):
> 
>     * WinGup (for Notepad++) v5.1.3
> 
> 
> ### [7.9.4](http://download.notepad-plus-plus.org/repository/7.x/7.9.4/)
> 
> 2021-03-15
> 
> Notepad++ v7.9.4 Enhancements & bug-fixes:
> 
>     1. Upgrade Scintilla from v4.2.0 to v4.4.6. (Fix [#9550](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9550))
> 
>     2. Fix DPI scaling broken while dragging Notepad++ into the 2nd monitor regression. (Fix [#9513](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9513), [#9579](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9579))
> 
>     3. Add "Find in Projects" feature. (Fix [#8125](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8125))
> 
>     4. Fix project workspace changes lost on save cancel issue. (Fix [#9605](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9605))
> 
>     5. Fix folder picker not being launched issue because provided directory is invalid. (Fix [#9569](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9569))
> 
>     6. Fix network path (UNC path) not working in file dialog. (Fix [#9527](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9527))
> 
>     7. Fix shortcut name more than 64 characters makes a menu entry empty name issue. (Fix [#9556](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9556))
> 
>     8. Fix extension appending issue in file dialog. (Fix [#9510](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9510))
> 
>     9. Fix file not turning to modified state (with Session Manager plugin) bug after its content being changed. (Fix [#9475](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9475))
> 
>     10. Add an option to mute all sounds in preferences dialog. (Fix [#7950](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7950))
> 
>     11. Make JSON auto-indent for brace. (Fix [#9499](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9499))
> 
> 
> More fixes & implementations detail:
> https://notepad-plus-plus.org/downloads/v7.9.4/
> 
> Included plugins:
> 
>     1. NppExport v0.2.9
> 
>     2. Converter 4.2.1
> 
>     3. Mime Tool 2.5
> 
> 
> Updater (Installer only):
> 
>     * WinGup (for Notepad++) v5.1.3

its very great, exactly the helpful informations which i needed.
however, how about finding links for related issues on github before version 7.9.1?
how can we find the links for bug fixes, new features and changes in previous version than 7.9.1?

**Comment by sasumner** [comment] 2021-04-12 11:47
>how about finding links for related issues on github before version 7.9.1?

As stated before, this information does not exist in a pre-compiled form.
And nobody will be going back to compile it now, as it would be considered a waste of time.

**Comment by zahra21** [comment] 2021-04-12 12:39
> 
> 
> The OP also [asked about it in the forum](https://community.notepad-plus-plus.org/topic/21003), and Alan provided a condensed list from all of the versions that he had archived over the years.
> 
> Thinking about it, it might be nice to have, and it would not be difficult to maintain once we got the initial history imported. Other projects, such as Scintilla, do have a [Version History page](https://www.scintilla.org/ScintillaHistory.html) on their website, so this isn't a desire unique to one person.
> 
> And even for getting the initial history: it wouldn't go back to the very earliest versions, but traversing the [github history on `change.log`](https://github.com/notepad-plus-plus/notepad-plus-plus/commits/4399c1343b96aee0c5419f130ddd984dc86f02d7/PowerEditor/bin/change.log) should be able to extract most of the history -- it looks like it goes back to v5.4... so not quite as far as @zahra21 was asking about.

exactly, thanks so much and God bless you!

**Comment by zahra21** [comment] 2021-04-12 12:52
> 
> 
> I wish all the change log info could be kept on the Notepad++ page. However each change of home page lost some history.
> 
> > The magic link is :
> > http://download.notepad-plus-plus.org/repository/
> > ...
> > Repeat these operations to get all the change.log files, from Notepad_plus.10.bin.zip till Npp.7.9.5.Installer.exe ;-))
> 
> @guy038 is right. That's the only way to get the whole history.
> 
> @zahra21 If you rebuild this history, then I will find a place to store it, and continue to maintain it on every release.



> 
> 
> I wish all the change log info could be kept on the Notepad++ page. However each change of home page lost some history.
> 
> > The magic link is :
> > http://download.notepad-plus-plus.org/repository/
> > ...
> > Repeat these operations to get all the change.log files, from Notepad_plus.10.bin.zip till Npp.7.9.5.Installer.exe ;-))
> 
> @guy038 is right. That's the only way to get the whole history.
> 
> @zahra21 If you rebuild this history, then I will find a place to store it, and continue to maintain it on every release.

how can i help you in this regard?
i answered quickly and wish to support my favorite program, but i did not recieve your reply.
yes, i wish so.
i wish that you did not lose your history.
your previous website was very accessible and easy to use with all informations that i needed.
but i dont know why you moved to new website, while the address of both are the same!

**Comment by zahra21** [comment] 2021-04-12 12:56
> 
> 
> Oh, I didn't know anyone had already started doing this. I just finished mine :)
> https://github.com/ArkadiuszMichalski/NPP_tools/tree/main/_change
> https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md
> 
> I used the reverse order (newest to oldest). More information can be added in the file `change.md` (link to download, release date, etc.). I also extracted all the `change.txt` files so anyone can download all and make a list in own format.
> 
> @donho
> Where do you want to put such a condensed list? On main page or here in Wiki? And what format do you prefer? A few versions, for example, would be enough to follow this pattern.

thanks, maybe i can only correct misspelled words. am i right?

**Comment by zahra21** [comment] 2021-04-12 13:01
> 
> 
> Might as well chime in with mine complete that was reference above.
> 
> oldest to newest = https://gist.github.com/vinsworldcom/3fe7d0cd9c11745e4cb6d0095b4d94c5
> newest to oldest = https://gist.github.com/vinsworldcom/2e03bc9dc58390841ab0e0b236b3d305
> 
> I included the download link to the 32-bit ZIP and a release date on each entry.
> 
> Cheers.

i really appreciate your great work.
i saved your information from oldest to newest in html only format.
i could open it after one or two minute unresponsivness of my firefox successfully and i could read the informations without any problem.
i really appreciate you, God bless you and His infinite mercy i pray for you.

**Comment by zahra21** [comment] 2021-04-12 13:07
> 
> 
> @ArkadiuszMichalski
> 
> > Where do you want to put such a condensed list? On main page or here in Wiki? And what format do you prefer? A few versions, for example, would be enough to follow this pattern.
> 
> Good question. The whole page won't be in notepad-plus-plus.og - there'll be a link to point to this history page in [resources page](https://notepad-plus-plus.org/resources/).
> And yes, why not in wiki? So the format will be in Markdown.

may i express my attitude in this regard?
i dont know what is markdown.
but i myself, prefer html format that i can read easily with my firefox and nvda screen reader.
i did not visit wiki or i dont remember if i visited wiki before, but i believe that beeing such informations about different versions of notepad++ in your main  website is very great.

**Comment by zahra21** [comment] 2021-04-12 13:17
> 
> 
> Oh, I didn't know anyone had already started doing this. I just finished mine :)
> https://github.com/ArkadiuszMichalski/NPP_tools/tree/main/_change
> https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md
> 
> I used the reverse order (newest to oldest). More information can be added in the file `change.md` (link to download, release date, etc.). I also extracted all the `change.txt` files so anyone can download all and make a list in own format.
> 
> @donho
> Where do you want to put such a condensed list? On main page or here in Wiki? And what format do you prefer? A few versions, for example, would be enough to follow this pattern.

your link
https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md
was the greatest link which i found until now.
because i could open and test it in html format only.
all the informations are in just one link! in html format! it has heading for each version!
the best and easiest method for screen reader users!
i really appreciate your great work, God bless you and His special mercy i pray for you!

**Comment by zahra21** [comment] 2021-04-12 13:22
> 
> 
> > how about finding links for related issues on github before version 7.9.1?
> 
> As stated before, this information does not exist in a pre-compiled form.
> And nobody will be going back to compile it now, as it would be considered a waste of time.

i need link for my important bug fixes or new features which i need.
how can i find informations that i need for myself that i can easily select the best version of notepad++ that is the best for me?
please email me off list.
i have questions about other issues which i reported that are unrelated to this one and i cant post here.

**Comment by ArkadiuszMichalski** [comment] 2021-04-14 18:52
>@sasumner 
>As stated before, this information does not exist in a pre-compiled form.
>And nobody will be going back to compile it now, as it would be considered a waste of time.

I added a reference for all bugs in 7.x versions. but I don't plan doing this for the rest. If anyone want,  fell free to add the rest. The place where I"m done:
https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master?before=90016a8dc0c470882c698c396d1b7e04c38cac0b+1855&branch=master

@zahra21
>your link https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md
was the greatest link which i found until now.

The official place for this file is here on the [Wiki](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki):
https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes

**Comment by sasumner** [comment] 2021-04-14 19:15
>>And nobody will be going back to compile it now, as it would be considered a waste of time.

>I added a reference for all bugs in 7.x versions. but I don't plan doing this for the rest.

Wow, that's an amazing amount of work you did.
As I said, I didn't expect anyone to do it, because it is so much.
It's easy to include it going forward, as new releases come out, but to go back in time to do it...amazing.

**Comment by zahra21** [comment] 2021-04-15 12:36
> 
> 
> > @sasumner
> > As stated before, this information does not exist in a pre-compiled form.
> > And nobody will be going back to compile it now, as it would be considered a waste of time.
> 
> I added a reference for all bugs in 7.x versions. but I don't plan doing this for the rest. If anyone want, fell free to add the rest. The place where I"m done:
> https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master?before=90016a8dc0c470882c698c396d1b7e04c38cac0b+1855&branch=master
> 
> @zahra21
> 
> > your link https://github.com/ArkadiuszMichalski/NPP_tools/blob/main/_change/change.md
> > was the greatest link which i found until now.
> 
> The official place for this file is here on the [Wiki](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki):
> https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Changes

today i tested your link from the wiki and it worked for me.
its exactly the version that i needed.
it contains everything which i wish to read including version number, date, new features, bug fixes, and github link in version 7.0 and later.
its a very valuable work and quick implement my favorite feature.
again, God bless you and His infinite mercy i pray for you for your great work!

**Closed** 2021-04-15 12:39 UTC
