### ISSUE TITLE
Function List: not working for JavaScript after update to v7.5.7

### ISSUE THREAD

**Issue by Skrol29** [notepad-plus-plus/notepad-plus-plus#4697] opened 2018-07-25 10:32 UTC
### Description of the Issue

Since my Notepad++ is upgraded to 7.5.7 using the auto update, the Function List panel is always totaly empty for JavaScript code. Even if the open file is «.js» or if I select myself the language from the menu.
### Steps to Reproduce the Issue

1. Open a .js file or select J/Javascript from the Language menu.
2. 
3. 

### Expected Behavior

See some items in the Function List panel when opened.
### Actual Behavior

Function List panel is empty.
### Debug Information

Windows 10 64-bits, French, Notepad++ 7.5.7 32-bits.

**Comment by Skrol29** [comment] 2018-07-25 10:41
It works again if I delete the file « functionList.xml » in the folder « C:\Users\UserMeMyself\AppData\Roaming\Notepad++ »

**Comment by sasumner** [comment] 2018-07-25 11:30
The author of Notepad++ explains here https://notepad-plus-plus.org/community/topic/15981/notepad-7-5-7-release/32 (or close to that) with the post that starts "OK, I guess I figur out your problem".

**Comment by dinkumoil** [comment] 2018-07-25 11:39
In the case somebody else stumbles upon this issue:

The problem is caused by a fix related to the internal id of the Javascript language since the file `C:\Users\<UserName>\AppData\Roaming\Notepad++` stays unchanged when Notepad++ gets updated.

To fix the problem:

1. Open the file mentioned above in Notepad++ and search the following line

    `<association id="javascript_function"     langID="19"/>`

2. Replace the number 19 with 58.

**Comment by sasumner** [comment] 2018-07-25 11:44
@dinkumoil I don't use Javascript but this problem (19 vs. 58) feels ages old (based upon forum postings I recall...).  I wonder if now it is fixed once and for all...except for this type of upgrade thing...

**Comment by dinkumoil** [comment] 2018-07-25 11:55
@sasumner Seems the fix was brought by [this](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/985fa654b97036a9ec15f50d22e95dff556d7eb9) commit. Don Ho states that it fixes a regression introduced in 2016. So yes, it's rather old.

**Comment by jabcreations** [comment] 2019-03-09 06:16
> It works again if I delete the file « functionList.xml » in the folder « C:\Users\[User]\AppData\Roaming\Notepad++ it works.

Seconded. My best guess is that it's likely a leftover from an older version. I also port many files from the Windows AppData directory when I have to do a fresh install of Windows so that is a second potential source of this file appearing. I have not confirmed if the file in Roaming is added by the installer though. I'm on the latest 7.6.3 as of March 9th, 2019. If something works for you please thumbs-up a comment on here so others know that it worked.

**Comment by ArkadiuszMichalski** [comment] 2020-09-21 01:54
@Skrol29 do you still have this problem in latest Notepad++ version?

**Closed** 2020-09-21 02:00 UTC

**Comment by BGMcoder** [comment] 2020-11-09 23:09
I copied the javascript_function parser from the program files file functionlist.xml to the one in my user folder and added the 58 association as well.
Now I have both assocations and both parsers and it worked after I added the 58.
			<association langID = "19" id="js_function"/>
			<association langID = "58" id="javascript_function"/>
