### ISSUE TITLE
Scroll down in editor stops working for large files

### ISSUE THREAD

**Issue by tswright** [notepad-plus-plus/notepad-plus-plus#1238] opened 2015-12-09 18:56 UTC
Found in version 6.8.6

In the editor I have several different files, one of which is large log file from a server I work on (2,158,628 lines).  While scrolling down in the smaller files I see expected behavior, even in one file that is also large (709,543 lines).  However, in the largest file scrolling down becomes disabled after an unknown point.  At first I thought it was my keyboard, but this behavior does not occur in the smaller files, or in other editors that I use.

I also observed that when this behavior occurs it follows a pattern.  If I jump to the top of the file, scrolling down works again.  When near the bottom and scrolling down is not working, if I scroll up one or two lines within the visible frame then I can scroll down one or two lines before it stops working; but if I scroll up three lines it jumps up an extra line and won't scroll down.  Also, if I scroll up enough to bring the first line above the visible frame to come into view, then scrolling down begins working again until I scroll down enough to expose the second line below the visible frame.

I created a test file that shows the problem.  Open the file, jump the the bottom, scroll up several lines, then try scrolling down.

[bigFile.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/57215/bigFile.txt)

**Comment by sanastasiou** [comment] 2015-12-09 20:11
Any chance your pc or the process is running out of memory?

**Comment by tswright** [comment] 2015-12-09 20:20
Definitely not the box (using only 40% of 16 GB physical memory).  What's the best way to tell if the process is running out of memory?

**Comment by dail8859** [comment] 2015-12-09 20:22
Two suggestions:
* Do you have backups enabled? If so disable that.
* Try disabling your plugins.

**Comment by tswright** [comment] 2015-12-09 20:30
I disabled all plugins, and turned off file backup (was set to 7 seconds).  Still seeing the problem.

**Comment by dail8859** [comment] 2015-12-09 20:30
Ok thanks.

**Comment by MetaChuh** [comment] 2019-04-11 00:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:42 UTC

**Comment by Wyer-Byter** [comment] 2019-04-15 13:52
I have seen this is current version Notepad++ 7.6.6
