### ISSUE TITLE
Notepad++ hangs when opening attached file

### ISSUE THREAD

**Issue by kotenok2000** [notepad-plus-plus/notepad-plus-plus#11940] opened 2022-07-23 21:01 UTC
### Steps to Reproduce the Issue

1. Enable word wrap
2. Open attached file
3. Minimize notepad++ window. 
4. Maximize notepad++ window.

### Expected Behavior

Notepad++ doesn't hang when opening attached file
### Actual Behavior

Notepad++ hangs when opening attached file
### Debug Information

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.795
Current ANSI codepage : 1251
Plugins : 
    ComparePlugin (2.0.2)
    DSpellCheck (1.4.23)
    HexEditor (0.9.12)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

[bitburnerSave_1658609616_BN4x1.json.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9174644/bitburnerSave_1658609616_BN4x1.json.txt)

**Comment by rdipardo** [comment] 2022-07-23 22:36
Duplicate of, at least, #11075, #10967, #8747 and #5267

> Enable word wrap

Bingo. 
Turn that off until they figure out [how to do line layout efficiently](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10193#issuecomment-1114819246).

**Comment by ArkadiuszMichalski** [comment] 2022-07-26 22:55
Duplicate as mentioned above.

**Closed by ArkadiuszMichalski** 2022-07-26 22:55 UTC
