### ISSUE TITLE
Feature Request: Native Code Snippet

### ISSUE THREAD

**Issue by malix0** [notepad-plus-plus/notepad-plus-plus#4702] opened 2018-07-26 12:12 UTC
I really like working with Notepad++, is a really excelent editor, but I want to suggest a native feature, a Code Snippet. I know there are plugins, but I tried all of them and, in my opinion, the best one is SnippetPlus, because you can associate a tag with a snippet, digit that tag and just press Ctrl+Shift+Enter to insert snippet in the code, but this plugin is really old and has some annoing bug, despite the fact that it is open source, the source code is not available. Having native snippet feature inside Notepad++ will be the best.

**Comment by ArkadiuszMichalski** [comment] 2021-12-29 01:14
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9540.

**Closed by ArkadiuszMichalski** 2021-12-29 01:14 UTC
