### ISSUE TITLE
Double click on a line in "find results" does not go to that line in an unsaved document

### ISSUE THREAD

**Issue by DavidHaslam** [notepad-plus-plus/notepad-plus-plus#5668] opened 2019-05-18 14:01 UTC
### Description of the Issue
With the **Find results** window, the function of double click does not work for an _unsaved_ new document.

### Steps to Reproduce the Issue

1. Open a new document and paste multiple lines in from another document.
2. Open the **Find** dialog and enter a pattern to find.
3. **Find All in Current Document**
4. Choose one line in the results pane and double click.
5. Nothing happens!

### Expected Behavior
This should cause that line in the new document to be selected in the same way as for a saved one.
It should be displayed immediately after using F7 to hide the results window.
That is still one of the most useful aspects of the Find function in **Notepad++**.

### Actual Behavior
Nothing happens!
Evidently, the fact that the new document has never been saved prevents this feature from working.

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : BracketsCheck.dll ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll LightExplorer.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppDocShare.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppTextFX.dll NppXmlTreeviewPlugin.dll SpellChecker.dll XMLTools.dll

**Comment by Ekopalypse** [comment] 2019-05-18 14:10
Seems to work for me

Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : D:\...\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : PythonScript.dll

**Comment by MetaChuh** [comment] 2019-05-18 22:16
@DavidHaslam 

we can not reproduce this on currently 3 different tested machines.

**please test the following, to verify, if a clean notepad++ would do the same on your system.**

* download the notepad++ 7.6.6. 64 bit portable version from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.x64.zip).
(the portable version does not require any installation and runs completely independent and isolated from your installed version. all custom settings, as well as any stuff you might want to try at the portable version, will not modify your installed version)

* extract `npp.7.6.6.bin.x64.zip` to e.g. your desktop.

* **important note:** make sure to close all instances of notepad++ that might be running, before starting the portable version at the next step, to be sure you are using the portable version for this test.

* open the extracted `npp.7.6.6.bin.x64` folder and start this portable version by double-clicking on `notepad++.exe` inside this folder.
(note: notepad++.exe will just be seen as notepad++, if you have enabled to hide all known file extensions at your explorer settings)

* test double-clicking on any of your find results on a new [x] tabs.

* optionally: repeat above with notepad++ 7.6.6. 32 bit portable from [>>> here <<<](https://notepad-plus-plus.org/repository/7.x/7.6.6/npp.7.6.6.bin.zip).

after trying the portable version(s), please visit us at the notepad++ community (link at the bottom), open a topic at `help wanted` with a link to this issue, and we will give our best to help you on your current experience more extensively over there.
(no extra account is needed, just use your github account to sign in)

note: as your issue is not directly related to the notepad++ source code we will close this issue.

thank you for your help and best regards.

-----
```
general notes:

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-05-18 22:16 UTC
Labels: not reproducible

**Comment by polluks** [comment] 2019-06-05 14:20
@MetaChuh I have a similar issue with 7.7 64 bit:
Sometimes if I click on a find result the cursor jumps to the wrong line (three lines above).
After a restart it's gone...

**Comment by sasumner** [comment] 2019-06-05 14:24
@polluks Have you changed the file since you did the search that populated the Find result panel?  This is known to yield results like you've seen, since the file positions recorded by the search are not changed as the file is modified, post-search...

**Comment by polluks** [comment] 2019-06-06 16:15
@sasumner Indeed, but I have File Status Auto-Detection enabled...

**Comment by sasumner** [comment] 2019-06-06 16:57
@polluks I don't think there is anything to be done for that case.
