### ISSUE TITLE
Why is 8.3.2 labeled as the latest release?

### ISSUE THREAD

**Issue by christoph-schneegans** [notepad-plus-plus/notepad-plus-plus#11654] opened 2022-05-10 01:08 UTC
In https://github.com/notepad-plus-plus/notepad-plus-plus/releases, **8.3.2** is labeled as the latest release, while **8.4** is only listed in https://github.com/notepad-plus-plus/notepad-plus-plus/tags as a tag. Any explanation for this?

**Comment by bryce-lynch** [comment] 2022-05-10 07:28
I noticed something similar with other projects like magisk and yt-dlp. Maybe an issue with Github servers?

**Comment by alankilborn** [comment] 2022-05-10 10:11
Probably because 8.3.2 is judged to be the latest stable release?

**Comment by PierreCsn** [comment] 2022-05-10 10:23
unlikely when they say Due to the crash issue & regressions found in v8.3.2, all the packages are removed. Please download v8.3.3 instead.

**Comment by donho** [comment] 2022-05-10 10:31
v8.3.3 & v8.4 should be listed, and v8.4 should be as the latest release.
I believe that it's a bug from Github. Otherwise it was me who have done something wrong.

**Comment by alankilborn** [comment] 2022-05-10 11:43
>Probably because 8.3.2 is judged to be the latest stable release?

I guess I was wrong about it.  It's the usual answer to the original question, that gets asked over and over and over...

**Comment by ozone10** [comment] 2022-05-10 13:03
related https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11651

This is github issue, several other repositories are also affected.

Until github fix it, use direct link to get current "true" latest https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.4

**Comment by cp2004** [comment] 2022-05-10 19:16
For a temporary workaround, whoever has write access can re-save the release notes of the tag and it will re-sync and be 'fixed'. GitHub have acknowledged the problem in a support ticket I opened when we were first impacted yesterday, and are prioritizing a fix.

**Comment by Gitoffthelawn** [comment] 2022-05-11 03:34
I hope GitHub finally fixes their bug.  It's messing up a bunch of automated processes for me in multiple repositories.  The releases simply disappear.

**Comment by donho** [comment] 2022-05-11 10:43
It seems this issue has been fixed by Github.

**Closed by donho** 2022-05-11 10:43 UTC
