### ISSUE TITLE
Reload dialog changes focused tab

### ISSUE THREAD

**Issue by roozbehid-ic** [notepad-plus-plus/notepad-plus-plus#1995] opened 2016-06-21 15:59 UTC
When a file changes outside of Notepad++, the reload dialog keeps bugging that this tab page was changes outside , do you want to reload it?

The problem is, I have 20+ tabs open and when this happens, it takes some time for me to go and find which tab I was working on.
If you can save current focused tab and after all those reloads dialog poped up, get back to focused tabs that would be awesome!

**Comment by chcg** [comment] 2017-12-08 16:41
This might be a duplicate of #1087 (Do not switch tab on file modification).

**Closed** 2019-03-17 12:05 UTC
