### ISSUE TITLE
Markdown as UDL works bad with dark themes

### ISSUE THREAD

**Issue by oldherl** [notepad-plus-plus/notepad-plus-plus#5600] opened 2019-04-29 02:56 UTC
### Description of the Issue
Default Markdown UDL provided in Notepad++ 7.6.6 doesn't work well with dark themes.

### Steps to Reproduce the Issue
1. Use a dark theme, "black board" for example.
2. Type some markdown
3. Use "Markdown (Default)" from "Language" menu

### Expected Behavior
Words with dark background in dark theme.

### Actual Behavior
Words with white background in dark theme.
![dark-markdown](https://user-images.githubusercontent.com/172495/56874509-e0ada780-6a6c-11e9-8171-66f25d89e117.png)

### Debug Information
Notepad++ v7.6.6   (64-bit)
Build time : Apr  3 2019 - 23:52:32
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by rddim** [comment] 2019-04-29 07:51
The default markdown UDL is a part of this project: https://github.com/Edditoria/markdown-plus-plus. There are also a dark ones.

**Comment by Androkai** [comment] 2019-05-16 12:53
The problem is a missing option for transparent background color in UDL. Sadly it's not just adding it, see this issue for more information: https://github.com/ivan-radic/udl-documentation/issues/1

**Comment by snow8gaia** [comment] 2019-06-12 16:52
present in notepad++ 7.7

**Comment by arhidavid** [comment] 2019-08-04 08:13
Same... Any suggestions if it can be fixed by using another dark theme?
I'm using "Obsidian" from standard pack and it looks just as bad.

**Comment by ffes** [comment] 2020-04-06 13:05
This is the reason why I always delete the UDL for markdown after every N++ update. Very annoying indeed.

Especially when you know that Scintilla has markdown support builtin for ages. And then suddenly markdown was implemented as a UDL instead of utilizing what was already within reach.

**Comment by klepp0906** [comment] 2020-05-20 18:35
> This is the reason why I always delete the UDL for markdown after every N++ update. Very annoying indeed.
> 
> Especially when you know that Scintilla has markdown support builtin for ages. And then suddenly markdown was implemented as a UDL instead of utilizing what was already within reach.

This.   I use twilight and i use portable.  There is already plenty to manage when updating portable that could be improved on (integrated updater that downloads the zip and extracts to the current dir and does not overwrite xmls would be major) 

having to delete this every time is another annoyance that keeps me from updating as often as i ought to : P

**Comment by AntonioNoack** [comment] 2020-12-30 13:44
Could you please explain, where the file is, that you need delete?
(also very annoying, that it still is not fixed after 20 months)

**Comment by ffes** [comment] 2020-12-30 14:42
From the top of my head:

To delete the definition, open a markdown file, open the "syntax" menu and at the bottom is "User defined". There open the UDL for markdown and from that dialog you can delete the definition.

Note I use the Dutch translation, the menu item names maybe differ a bit.

**Comment by AntonioNoack** [comment] 2020-12-30 15:12
Thank you, it worked :D

**Comment by AntonioNoack** [comment] 2021-06-05 14:45
ping, any updates on this? this is an obvious, and really annoying bug

**Comment by donho** [comment] 2021-12-26 02:53
This issue has been fixed.

**Closed by donho** 2021-12-26 02:53 UTC
Labels: udl
