### ISSUE TITLE
Move to Other View sometimes swaps panes on first use

### ISSUE THREAD

**Issue by JCSheeron** [notepad-plus-plus/notepad-plus-plus#1161] opened 2015-11-18 19:22 UTC
Occasionally after opening several documents, when I right click a document tab, and select 'Move to Other View', the document I selected stays in the left pane, and all the other documents go to the right pane.  Most of the time, the behavior is what I would expect, since the selected option uses the language 'other view': The selected document move to the right (new) pane, and all the other documents stay on the left.

I cannot reproduce this at will. If it is going to happen, it seems to only happen when going from a single pane, and selecting 'Move to Other View', which causes a new pane to be opened  Once there are two panes open, I think the behavior is always as expected.  

Moving tab order around within the single pane before selecting 'Move to Other View' seems to make it less likely, but does not eliminate the behavior.  

I am using version 6.8.5 on Windows 7 64-bit, service pack 1.  I  have noticed this behavior for at least a handful of earlier versions as well.

**Comment by MetaChuh** [comment] 2019-04-13 02:17
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:17 UTC
