### ISSUE TITLE
[Language] Rust is not detected in Notepad++

### ISSUE THREAD

**Issue by AraHaan** [notepad-plus-plus/notepad-plus-plus#2658] opened 2016-12-10 03:01 UTC
### Description of the Issue
Notepad++ does not recognize rust code files.

### Steps to Reproduce the Issue
1. Install Rust.
2. use Cargo to create a new library in rust.
3. Open a rust source code file (`*.rs`)

### Expected Behavior
Syntax Highlighting and a Display on status bar saying `rust Source File`.

### Actual Behavior
Rust Source Files being treated like normal text files.

### Debug Information
```
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : E:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : MenuIcons.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll NppSaveAsAdmin.dll PluginManager.dll PyNPP.dll Python Indent.dll PythonScript.dll ReloadButton.dll Translate.dll ZenCoding-Python.dll zoomdisabler.dll 
```

**Comment by FrankSpitulski** [comment] 2016-12-14 08:17
Rust is not officially supported by notepad++. You have to use a plugin if you want that feature.

**Comment by redmanmale** [comment] 2017-06-07 10:12
@AraHaan 
Highlighting support for all languages are provided by Scintilla.
You shoud ask about it at [Scintilla's feature requests page](https://sourceforge.net/p/scintilla/feature-requests/search).
Or you could write your own custom language definition.

**Comment by dail8859** [comment] 2017-07-24 18:44
Closed by 02bdd11700e6fb225157aa59f1f5f1a453865cee

**Closed by dail8859** 2017-07-24 18:44 UTC

**Comment by Moth-Tolias** [comment] 2019-04-25 16:25
seems to be an issue as of this writing - a regression?

**Comment by spakecdk** [comment] 2020-05-11 18:04
Still unsolved

**Comment by dail8859** [comment] 2020-05-11 18:18
@spakecdk 

 Works for me. Please open an issue a new issue.

![image](https://user-images.githubusercontent.com/3694843/81596476-285e5300-9392-11ea-8eb5-5f49832c0c36.png)

**Comment by spakecdk** [comment] 2020-05-11 19:47
my bad, somehow the issue is my theme (solarized light)
