### ISSUE TITLE
AppPosition check on startup

### ISSUE THREAD

**Issue by sxsong1207** [notepad-plus-plus/notepad-plus-plus#1331] opened 2016-01-07 02:42 UTC
I always work with multi-screen in office and with single screen in my home.Some times when I exit notepad++ on the other screen and restart after unplug it,I can't see the window of notepad++ although progress is running.I think notepad++ was draw out of screen.
I found the "<GUIConfig name="AppPosition" x="1950" y="56" width="1070" height="1071" isMaximized="no" />" this line in config.xml.So I think notepad++ should make some check when startup to determine if the position is out of screen.

**Comment by MetaChuh** [comment] 2019-04-11 01:06
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 01:06 UTC
