### ISSUE TITLE
Feature request:  Add "Save As" button between "Save" and "Save All" buttons.  Thanks.

### ISSUE THREAD

**Issue by somebadhat** [notepad-plus-plus/notepad-plus-plus#5056] opened 2018-11-25 15:59 UTC
Feature request:  Add "Save As" button between "Save" and "Save All" buttons.  Thanks.

**Comment by sasumner** [comment] 2018-11-26 00:35
"Customize Toolbar" plugin will allow you to do this.  Unlikely to be changed in Notepad++ itself due to the existence of this plugin.  Probably best to CLOSE this issue.

**Comment by dinkumoil** [comment] 2018-11-26 16:09
I have to second @somebadhat  - there is no "Save **As**" button in Notepad++. Also the latest release of the _CustomizeToolbar_ plugin (v4.1) doesn't include such a button.

**Comment by dinkumoil** [comment] 2018-11-26 21:02
> is there any reason a "custom" ... button for SaveAs can't be made (by the end-user) in the CustomizeToolbar plugin?

Well, it is possible to create custom buttons with this plugin. But I found it is not working reliably.

Often the buttons are greyed out after starting Notepad++, but if you start it via Explorer context menu (Edit with Notepad++) the buttons work.

Furthermore, adding buttons depends on the UI language since buttons have to be connected to a menu item using a chain of the texts of all menu entries involved.

Finally the buttons have to be in a special BMP format (256 colors i.e. 8 bits per pixel). This format is not very common, the only program I know which can convert normal BMPs to 8 BPP is IrvanView.

But besides all that mentioned before - regardless that there is a plugin which let users define own buttons the feature request of @somebadhat is a valid one. To decline that would be the same like saying "You miss a feature in Notepad++? Oh, there is the Python plugin, you can write a script to get the functionality you want, no need to integrate it in Notepad++ itself".

Let the developers decide if someone wants to invest the effort for the requested button.

**Comment by sasumner** [comment] 2018-11-26 23:37
If I'd have remembered about SaveAs and the Customize Toolbar plugin...I would have approached it differently with my comments.  At the time of writing I thought it was pretty much plug-and-play, with maybe a tad bit of customization (setting up a button).  I guess it isn't, which is a shame because here we have a dedicated plugin to do something (that is likely never to get attention in Notepad++ itself) and it is apparently working poorly.  :(  And if it *were* working, this discussion would likely be over.  :-)

Sure, this issue can stay open.  I don't see it getting mainline attention, but that's a different thing.

If it *was* working properly, however, I think (from observation) that the Notepad++ credo is "hey that functionality is in a plugin, we never have to do that in the main code".  And that works, as long as the plugin works and is maintained in perpetuity by its author.  But we've seen counter-examples (e.g. TextFX).  Ideally, yes, the best text editing features would best be mainlined.  Something like toolbar buttons is more debatable.  I'd rather see dev time spent on known bugs and text editing features.

>"You miss a feature in Notepad++? Oh, there is the Python plugin, you can write a script to get the functionality you want, no need to integrate it in Notepad++ itself".

Surely there is a difference.  Scripting is one thing, but that takes it to a different level.  That is likening a (probably) one line configuration file entry to something like a many-dozens-plus lines of script code.  Well, one could even argue that both are "coding". :-)

Good discussion; thanks.

**Comment by dinkumoil** [comment] 2018-11-27 06:57
> which is a shame because here we have a dedicated plugin to do something ... and it is apparently working poorly.

Nevertheless it is a useful plugin. I like it very much, it has become one of my standard plugins which I use in every Notepad++ installation. Without that plugin the toolbar is a whole mess and it takes from me the burden to remember a lot of keyboard shortcuts of frequently used Notepad++ functionalities.

> Good discussion; thanks.

Ditto

**Comment by Endor8** [comment] 2019-09-07 13:47
Just my opinion: if one like me, use mostly only the mouse he will miss this Button absolutely  
and the above mentioned plugin not works god in other languages then English.
So I am also asking you, please add a Save As Button. Your mentioned keyboard shortcut helps
but it can not replace a proper button. I hope to see it in a future release. Thanks.

**Comment by donho** [comment] 2019-12-13 23:51
I don't like this feature personally, but I do understand the needs.
Instead of this feature request, I would say "customize toolbar feature" is needed.
I'll see what can I do about "customize toolbar feature".

**Closed by donho** 2019-12-13 23:51 UTC
Labels: enhancement

**Comment by chcg** [comment] 2019-12-27 11:32
@somebadhat Maybe the plugin https://sourceforge.net/projects/npp-customize/files/Customize%20Toolbar%20v4.2/ already fulfills your needs.

**Comment by sasumner** [comment] 2019-12-27 12:47
@donho said:

>I'll see what can I do about "customize toolbar feature".

Since you closed _this_ issue (5056), have you opened another one to track the "customize toolbar feature" work?  I could not find any.

**Comment by sasumner** [comment] 2019-12-27 12:50
@chcg said:

>...CustomizeToolbar...

I think I recall some discussion somewhere about it not being possible to add a SaveAs command with the CustomizeToolbar plugin, although it seems like a perfect task for that plugin.  Is it actively being developed? Maybe the developer can look into whatever the problem is with SaveAs, while we wait for @donho 's native version of toolbar customizing.
