### ISSUE TITLE
idea on improvement: search by tabs

### ISSUE THREAD

**Issue by mikeai686** [notepad-plus-plus/notepad-plus-plus#8485] opened 2020-06-27 05:42 UTC
1. Why not to add a feature: search in tabs? If you open a few dozens of files, it will be nice to quickly find a right tab by its name by search line.

2. Another idea: Search/replace (ctrl-F) fields are too small for multiline text. It's often you may want to find or replace a multiline text. Now you can do it, but you can't see it as it is and in full.

**Comment by wonkawilly** [comment] 2021-03-17 02:46
Sorry for the OT, I'm also really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and spread the word asking others to partecipate as well. More opinions are welcome. Thank you all.

**Comment by ArkadiuszMichalski** [comment] 2021-09-10 15:06
For 1 you can you can try [nppNavigateTo](https://github.com/young-developer/nppNavigateTo/) plugin.
2 is duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4031.

**Closed by ArkadiuszMichalski** 2021-09-10 15:06 UTC
