### ISSUE TITLE
Feature Request: User-Preference to disable whole-line cut/copy/del (when no selection)

### ISSUE THREAD

**Issue by kjosib** [notepad-plus-plus/notepad-plus-plus#14733] opened 2024-02-15 04:16 UTC
### Description of the Issue
As a fat-fingered touch-typist, I'll periodically hit ^C by mistake when I mean to hit ^V. In the good old days, that would leave the clipboard unchanged and I could just realign my fingers. These days NP++ will instead trash the hard work I did to fill clipboard and instead replace it with a copy of the very line I'm trying to modify. That harshes my groove.

I understand some svelte-fingered keyboard artists consider the present behavior to be a feature. That is why I would like to propose a checkbox on the editor tab of the settings/preferences dialog to turn this behavior on or off.

### Steps to Reproduce the Issue
1. Go get some valuable text into the clipboard that you want to paste into NP++.
2. Position the cursor in the NP++ document somewhere in the middle of a line.
3. Attempt to touch-type ctrl-V, but miss and hit the next letter to the left.
4. Realize your mistake and actually press ctrl-V this time.

### Expected Behavior
Absolutely nothing; clipboard contents left intact.

### Actual Behavior
Intended clipboard contents were destroyed in step 3 and replaced by a copy of the destination line, thus undermining the effort to perform steps 1 and 2.
The destination line is duplicated in step 4.
Loud cursing is then often heard in the vicinity.

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment] 2024-02-15 04:33
Duplicate of #14638

Fixed in the forthcoming release: <https://community.notepad-plus-plus.org/topic/25469/notepad-v8-6-3-release-candidate>

**Comment by kjosib** [comment] 2024-02-15 04:39
> Duplicate of #14638
> 
> Fixed in the forthcoming release: https://community.notepad-plus-plus.org/topic/25469/notepad-v8-6-3-release-candidate

That would explain why I didn't find an open issue for it when I searched. (It's already marked "closed".)

**Comment by donho** [comment] 2024-02-15 18:53
https://github.com/donho/notepad-plus-plus/commit/b3a08f8f09850251200334949129a1bc43dfdc71

**Closed by donho** 2024-02-15 18:53 UTC
