### ISSUE TITLE
Document Map - background is showing in the wrong place

### ISSUE THREAD

**Issue by ArgyleTrees** [notepad-plus-plus/notepad-plus-plus#12120] opened 2022-09-08 00:11 UTC
![image](https://user-images.githubusercontent.com/113072765/189006078-e19e0ba9-1d05-4ef5-b848-80d6ec6a50cd.png)

### Description of the Issue
select document map. the color background of the map panel is showing at the wrong place. (see screenshot).

I use Dell 4K screen. Deault scale is set at 150%..  Change to 100% scale makes notepad++ look right. But 100% scale on 4K screen makes everything too small to read.

**Comment by ArkadiuszMichalski** [comment] 2022-09-08 01:19
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8575.

**Closed by ArkadiuszMichalski** 2022-09-08 01:19 UTC
