### ISSUE TITLE
"Copy Text with Syntax Highlighting" is no longer working in v7.7

### ISSUE THREAD

**Issue by bsacheri** [notepad-plus-plus/notepad-plus-plus#5790] opened 2019-06-15 03:37 UTC
The right-click context menu "Plugin commands | **Copy Text with Syntax Highlighting**" is no longer copying the formatting. In some cases it is copying the font but never the colors.

I have tested pasting in 
- Outlook
- Word
- OneNote

I have also tested with the options on the **NppExport** plugin menu with the same results.

Here is an image that shows an example:
![Show Example](https://drive.google.com/uc?id=1CIdcDSNgTfnoEJt3bW31HR-ARQjgWH18)

**Comment by MetaChuh** [comment] 2019-06-15 07:04
@bsacheri 

this is a known issue with the nppexport plugin, but while nppexport is still shipped with notepad++ 7.7, it's not part of the notepad++ core code.

please see here: https://github.com/chcg/NPP_ExportPlugin/issues/7
duplicate of: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5740

many thanks and best regards.

**Closed by MetaChuh** 2019-06-15 07:04 UTC
Labels: duplicate, wontfix
