### ISSUE TITLE
crashes when going to fullscreen with split screen

### ISSUE THREAD

**Issue by ultrabear** [notepad-plus-plus/notepad-plus-plus#5318] opened 2019-02-15 07:34 UTC
whenever i use the vertical split screen in np++ and attempt to go to fullscreen with F11 it crashes, changing to split screen while in fullscreen works but then if i exit fullscreen with F11 it crashes, the only way i found to be able to switch to and from fullscreen is when not in splitscreen
the splitscreen i stated is called "move to other view" in the program

Notepad++ v7.6.2 (32bit)

**Comment by SinghRajenM** [comment] 2019-02-17 05:42
What do you mean by vertical split?

Do you mean "Settings->Preferences->Edit->Show Vertical Edge", then I'm not able to reproduce.

**Comment by sasumner** [comment] 2019-02-17 13:20
I'm guessing "vertical split" means having both views open (via **Move/Clone to Other View**) so that there is a splitter control between them.

**Comment by SinghRajenM** [comment] 2019-02-17 13:33
> (via **Move/Clone to Other View**)

This way also no crash.  There are no concrete steps given to reproduce, it is better to close the issue.

@ultrabear 
That is the reason the bug reporting template is given. Please follow to help community and get help from community. Thank you!

**Comment by Faq** [comment] 2019-02-17 15:26
I'd say all new reports without using template should be closed.

**Comment by SinghRajenM** [comment] 2019-04-12 16:17
@MetaChuh it can be closed as no response from reporter...

**Closed** 2019-04-12 19:19 UTC

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 18:58
@dail8859 @donho

Still happens, also take off those guys moderation ability due closing issues due not understanding english.
It's clearly said that we should open both split's and press f11...

**Comment by dail8859** [comment] 2020-08-29 19:39
@afwn90cj93201nixr2e1re 

Please open a new issue since this one uses an older version of Notepad++ and does not follow the template. Thanks.

**Comment by sasumner** [comment] 2020-08-29 20:50
>also take off those guys moderation ability due closing issues due not understanding english.

All of the moderators I can think of have a good understanding of English.  The onus is on the reporter to make themselves understood by using the template, and using correct verbage when reporting issues.  Effort out is going to be proportional to effort in.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 22:08
i don't see any difference between template and first post.
![изображение](https://user-images.githubusercontent.com/9306996/91646920-0e7d7480-ea44-11ea-93ed-9afd402afe43.png)


Reopen this issue and then i could provide more info.

@dail8859

**Comment by dail8859** [comment] 2020-08-29 22:12
The original post does not provide a minimal reproducible example, it also does not have the user's debug information which can be critical when tracking down issues. This issue will not be reopened. Please open a new one.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 22:17
I also can't provide debug info coz it's just crashing. And it's crashing in legal way, just seems like closing and that's all. Ofc i can just give u ready PR with fixes, btw i don't wanna waste my time on exploring this repo for my self.
Np, if it's not gonna reopenned then the bug doesn't exist, whatever. Anyway thanks for response.

**Comment by dail8859** [comment] 2020-08-29 22:22
> I also can't provide debug info coz it's just crashing

You can't even start Notepad++? That's all you need to do to provide debug info.

> i don't wanna waste my time on exploring this repo for my self

What are you inferring you need to explore it for?

> then the bug doesn't exist

I never said it didn't, but I and at least 2 other very experienced users's can not reproduce the issue.

> Just instruction for you,

Also tried this and cannot reproduce it.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 22:37
> Also tried this and cannot reproduce it.

That's strange

> You can't event start Notepad++?

```
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\TestDir\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.657
Current ANSI codepage : 1251
Plugins : NppConverter.dll NppExport.dll 
```

That's not gonna be helpful for u.

> What are you inferring you need to explore it for?

Hm, how software work, how to build it for making PR, idk, just for getting some context.

**Comment by dail8859** [comment] 2020-08-29 22:45
> That's not gonna be helpful for u.

That helps to illuminate possible reasons that your system is different than others.

> Hm, how software work, how to build it for making PR, idk, just for getting some context.

All we were asking for is a simple set of steps to reproduce it.

As a side note, earlier you said "btw im using latest version" when in reality according to your debug info you are not on the latest version. This is one of the reasons why we ask for a user's debug information so we have specifics.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 22:49
I understand that, but im not another one stupid guy which just picking up old issue just for fun, you can't check it, right, btw as you said i said that im using the latest version.

https://youtu.be/3B4wcwjqni8

Btw there's video.
https://youtu.be/3B4wcwjqni8

> All we were asking for is a simple set of steps to reproduce it.

As you can see you aren't able to reproduce this issue, that's why i said that i can just debug it for myself on my pc and make PR with fixes.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-08-29 22:52
Oh, and `Выполняется` meaning is `Running/Executing`, `Приостановлено` meaning is `Paused`.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-01 23:20
> As a side note, earlier you said "btw im using latest version" when in reality according to your debug info you are not on the latest version.

I runned autoupdater and seem's like that's latest version for it, but on site yes, 2 more.

Ok, i tested it with 7.8.9, same.

@dail8859

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-02 12:42
Bruh
@dail8859 
https://notepad-plus-plus.org/update/getDownloadUrl.php
checkout

**Comment by dail8859** [comment] 2020-09-02 12:44
@afwn90cj93201nixr2e1re Just because the auto-updater has not been triggered does not mean v7.8.7 is the latest version.

Also, since I cannot reproduce your issue, I cannot help further.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-02 12:46
I meant update it.

**Comment by sasumner** [comment] 2020-09-02 13:04
>I meant update it.

There are reasons why it is set to what it is.

Bruh.  LOL

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-02 19:01
em, whatever, that's not my buisness at all.
But if someone releasing some stuff and have autoupdater, at least it's should have options to download beta/stable channel.
![изображение](https://user-images.githubusercontent.com/9306996/92025158-a3d37e00-ed4e-11ea-84b9-cde0fbcb8e32.png)
Seems like u never heard about pre release. Whatever, that's pretty enough for making some decision about ur level.

> Bruh. LOL

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-02 19:07
And second one issue which was closed by same moderator:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4090#issuecomment-489885774

I downloaded 7.8.6 x64 and got 7.8.7 x86 version, after running GUP, very funny.
```
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\programs\Notepad++\notepad++.exe
```

**Comment by sasumner** [comment] 2020-09-02 19:21
@afwn90cj93201nixr2e1re

Bruh, you aren't making much sense.

**Comment by sasumner** [comment] 2020-09-02 19:33
Hmm, well, it appears now he's deleted ALL of his contributions from this thread.
Cleaned up the thread substantially.
Nice.

**Comment by afwn90cj93201nixr2e1re** [comment] 2020-09-02 22:44
anyway thanks for answers
