### ISSUE TITLE
Recent Update causes unusable window layout

### ISSUE THREAD

**Issue by CaseAlexander** [notepad-plus-plus/notepad-plus-plus#9988] opened 2021-06-10 11:48 UTC
### Description of the Issue
After a recent update, the window layout is unusable. 

### Steps to Reproduce the Issue
1. Just open Notepad++
2. 
3. 

### Expected Behavior
It should open with a usable layout

### Actual Behavior
It opens with ~80% of the layout unusable (see attached image)

### Debug Information
Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1052
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/26043082/121519826-c79bb280-c9b7-11eb-86ea-2dc8ce7266bb.png)

**Comment by ArkadiuszMichalski** [comment] 2021-06-10 12:00
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed by ArkadiuszMichalski** 2021-06-10 12:00 UTC
