### ISSUE TITLE
Feature Request: Standard Icons: Large.

### ISSUE THREAD

**Issue by Kasey13** [notepad-plus-plus/notepad-plus-plus#10133] opened 2021-07-09 12:08 UTC
Not really an issue, but something I would like to see considering the other icon options offer it.

**Comment by ArkadiuszMichalski** [comment] 2021-07-09 12:20
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9913.

**Closed by ArkadiuszMichalski** 2021-07-09 12:20 UTC
