### ISSUE TITLE
Function list won't detect zero-arg function defs followed by comment

### ISSUE THREAD

**Issue by ArdNut** [notepad-plus-plus/notepad-plus-plus#7963] opened 2020-02-20 22:56 UTC
### Description of the Issue
A function definition with no args is not picked up and shown in the function list if it is followed by a comment on the same line.

Example:

    bool USBIface::USBOpenOutput()       // [PRIVATE]
    {
    ... code and stuff
    }

will not appear in the function list, but

    bool USBIface::USBOpenOutput()
    {
    ... code and stuff
    }

will appear.

**Comment by MAPJe71** [comment] 2020-02-21 22:18
Duplicate of #344

**Comment by dail8859** [comment] 2020-03-29 12:43
Closing as duplicate

**Closed by dail8859** 2020-03-29 12:43 UTC
