### ISSUE TITLE
Find and Replace in Column Selection Mode in Notepad++ is NOT WORKING

### ISSUE THREAD

**Issue by misc-cpu** [notepad-plus-plus/notepad-plus-plus#9584] opened 2021-02-26 08:08 UTC
### Description of the Issue
**In Column Selection Mode in Notepad++ Find & Replace is NOT WORKING.**
I think to stay in the race this feature should be included in the next update of Notepad++, because EditPad Lite 8 already has this cute feature and is working fine !?!

_Please provide Find and Replace in Column Selection Mode in Notepad++ in the next updated version as soon as possible!_

**Comment by sasumner** [comment] 2021-02-26 12:37
It is "NOT WORKING" because it is currently "NOT SUPPORTED".

**Comment by wonkawilly** [comment] 2021-03-17 02:27
I'm really sorry if I'm bothering you all, but maybe the participants to this thread would want to give their opinion about this new and rich proposal about the improvement of the Find and Replace dialog at this link: #9627. Which will be a great improvement and perhaps even a real game changer for all of us that use N++ for more advanced uses than just editing the shopping list.
Please partecipate and ask others to. More opinion are welcome. Thank you all.

**Comment by sasumner** [comment] 2021-06-30 17:29
Duplicate of the currently-open #8450

**Closed by sasumner** 2021-06-30 17:29 UTC
