### ISSUE TITLE
focusing on changed file issue

### ISSUE THREAD

**Issue by cempolat** [notepad-plus-plus/notepad-plus-plus#3160] opened 2017-04-13 12:08 UTC
### Description of the Issue
Notepad++ does not focus on the last opened file tab when previously opened files are changed outside. 

### Steps to Reproduce the Issue

1. Open multiple files on Notepad++
2. Lose focus on the Notepad++ window (minimize or put another application's window on top)
3. Change one of the previously opened files by another editor (i.e notepad)
4. Open a new file with the explorer context menu "Edit with Notepad++"

### Expected Behavior

I believe that the correct behaviour must be to set the focus to the tab of the new opened file. If I want to open a file I want to see it on the editor at the end of the open file action.

### Actual Behavior

At this moment, "Reload" messagebox appears since the previously opened file is modified by another program. Regardless of your reload choice, the tab of the modified file is focused.  The new file is opened in a new tab (if it is not already opened) however it does not get the focus.

**Comment by fml2** [comment] 2017-04-15 22:58
This might be a duplicate of #1087 (Do not switch tab on file modification).

**Comment by Rajas-Git** [comment] 2017-04-19 17:17
I will say that correct behavior should be to ask for reloading a file ONLY when user switches to its tab.

**Comment by cempolat** [comment] 2017-04-19 17:30
Reasonable. Also highlighting the changed file's tab would be great.

iPhone'umdan gönderildi

19 Nis 2017 tarihinde 20:17 saatinde, Rajas-Git <notifications@github.com> şunları yazdı:

**Comment by chcg** [comment] 2017-12-08 16:39
Seems to be a duplicate to #1995

**Comment by sagarphadkule** [comment] 2018-05-23 13:49
Please let this be addressed soon with a higher priority. On a daily basis, I am annoyed when I open up a new file only to lose focus to some old tab for which this prompt(s) are shown. I think this is a super inconvenient bug for any power user of notepad++ who has many tabs open perpetually and some of the files change.

**Comment by Cerno-b** [comment] 2018-06-06 08:39
There is a commit which resolves this issue in #1087, but it's not in the release yet

**Closed** 2019-03-17 12:05 UTC
