### ISSUE TITLE
[feature request & thanks]

### ISSUE THREAD

**Issue by perlsol** [notepad-plus-plus/notepad-plus-plus#11968] opened 2022-08-01 18:37 UTC
Thank you for all your time and effort in making this awesome tool, it handles 'any' task with great ease.
One small feature request If I could be so cheeky to ask... minimise to tray on exit (PLEASE ;))

KInd regards

**Comment by alankilborn** [comment] 2022-08-01 18:42
Duplicate of #11627 #4075

This behavior can be scripted.

**Closed** 2022-08-01 18:49 UTC
