### ISSUE TITLE
Quit after closing last document

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#2146] opened 2016-08-05 19:02 UTC
I'd like to have an option to quit Notepad++ entirely when the last document has been closed. I'm using the "session restore" feature that always opens the documents at start that were open when Notepad++ was last closed. Much like my web browsers do. But when I don't need any documents permanently open, when I open one document and then close it again, I don't need Notepad++ staying around anymore. It should be closed then.

Right now I need to press Ctrl+W and then Alt+F4 to achieve this. Ctrl+W should be enough.

Another option would be not to close it but to minimise the window. I've seen this in TextPad but wouldn't use it today.

**Comment by MAPJe71** [comment] 2016-08-05 19:21
Possibly a duplicate of #1006 which was solved with pull request for #1923.

**Comment by ygoe** [comment] 2016-08-05 19:23
The issue itself is a duplicate but the solution is not. What should I do with a command line parameter? Nothing will ever specify that. It must be an option in the application itself to be useful.

**Comment by SanyaWaffles** [comment] 2016-08-06 02:07
@ygoe ygoe, are you using Windows 10 by chance.

**Comment by ygoe** [comment] 2016-08-06 09:00
I have indeed upgraded my computers to Windows 10 by now but the issue already existed on Windows 7 before. I don't think it's related to the Windows version, it should be purely application behaviour.

**Comment by dail8859** [comment] 2016-09-22 13:20
Closed by e31e37ebc3bdd8d34b0cb61f1e3b81477fcdfbaf

**Closed by dail8859** 2016-09-22 13:20 UTC
