### ISSUE TITLE
Close unsaved prompt accelerators

### ISSUE THREAD

**Issue by justanotheranonymoususer** [notepad-plus-plus/notepad-plus-plus#7644] opened 2019-11-22 20:24 UTC
In previous versions I could close an unsaved document (Ctrl+W) and quickly say No by clicking Alt+N or just N. Now it doesn't work, since it was replaced by a custom dialog. Please add accelerators to the new prompt dialog so that Alt+N or N (or Alt+Y for Yes) work.

**Comment by sasumner** [comment] 2019-11-22 21:47
Please search for existing issues before creating new ones.  Closing as duplicate of #6223 .

**Closed by sasumner** 2019-11-22 21:47 UTC
