### ISSUE TITLE
Incorrect syntax highlighting in JavaScript with backtrick (`) in code

### ISSUE THREAD

**Issue by starsolaris** [notepad-plus-plus/notepad-plus-plus#14539] opened 2024-01-01 15:07 UTC
### Description of the Issue
Incorrect syntax highlighting in JavaScript with backtrick (`) in code

### Steps to Reproduce the Issue
```javascript
const a = () => /`/;
```

### Expected Behavior
Text should not be with grey background after backtrick (`) symbol.

### Actual Behavior
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/715636/ba6c8b17-695f-4b38-a317-1761a8363dfe)

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.3803
Current ANSI codepage : 1251
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment] 2024-01-03 02:57
Lexilla bug: ScintillaOrg/lexilla#94

Duplicate of, at least:
- #3252
- #3331
- #4007
- #4106
- #6193
- #7879
- #8421
- #9812
- #11056
- #11412
- #11562
- #12287

**Comment by donho** [comment] 2024-03-11 01:44
Duplicate also of:  #3822

**Comment by donho** [comment] 2024-07-27 09:26
![image](https://github.com/user-attachments/assets/af20c77c-e80a-441a-b766-2e94cef5e303)

**Closed by donho** 2024-07-27 09:26 UTC
Labels: lexilla dependent
