### ISSUE TITLE
Gridsplitter moving depending on mouse move..

### ISSUE THREAD

**Issue by sanastasiou** [notepad-plus-plus/notepad-plus-plus#881] opened 2015-09-09 22:08 UTC
Found a very funny bug.

To reproduce do the following:

Open up document map. Place it on the right.

Open up a document.

Open up another document and move it to the "other" view.

Drag document map gridsplitter to the right or left. Release mouse button.

Move mouse button on the "views" gridsplitter.

Notice that the splitter moves, even if the mouse button is not pressed.

Giving focus to the editor fixes the issue.

**Comment by h-h-h-h** [comment] 2015-09-11 22:34
I can reproduce this bug (Notepad++ 6.8.3, Windows 8.1).

**Comment by MetaChuh** [comment] 2019-04-09 23:38
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:38 UTC
