### ISSUE TITLE
Add an option to toggle the "Search Results Window"

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#2946] opened 2017-02-23 08:07 UTC
### Description of the Issue
After a search or when press F7 the search results window is opened. It would be nice to close it again with F7. Maybe an option to allow this toggle can be added. At the moment I use a Autohotkey script for this, but it would be nice if this is integrated already

### Expected Behavior
Press F7 toggle the search window. If shown, then close it. If closed, then open it.

### Actual Behavior
F7 only show the window. When it is already there, nothing happened.

### Debug Information
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll 

The link to the autohotkey script: http://superuser.com/questions/700357/create-a-hotkey-keyboard-shortcut-to-close-the-notepad-find-results-window

**Comment by HerbM** [comment] 2018-05-19 00:30
Second and bump this please.

The AutoHotKey solution is not a great choice (even though I habitually run AHK) because it is very difficult to get it to run (with same key) through a wide variety of remote desktop and screen sharing software.

Please, this would be small but constantly significantly useful feature.

Close search without breaking flow by moving hands from keyboard.

**Comment by JJT319** [comment] 2020-05-03 18:25
Same as #3766. 
I would think we do not want to change the existing now expected behaviour of the menu item 'Search Results Window' Default map 'F7'.
I would suggest a workable solution would be to add a menu item 'Hide Results Window' Default map 'Ctrl+F7'.
I would happily code this if the admin approves the issue.

**Comment by sasumner** [comment] 2020-05-04 12:36
@JJT319 Does your proposal consider adding keyboard-based closure of the "Search Results Window" (aka the window with **_Find result_** in its title bar -- not sure why this window had/needs two different names) when input focus is in THAT window?

**Comment by JJT319** [comment] 2020-05-05 17:20
@sasumner apologies, I am not quite sure exactly what you are asking. (New to codeTriage, hope I am doing this right)

First of all yes I am not sure why it has two different names, probably would be nice to have one consistent name and also in the code. 
Adding to that, it is strange that the menu item 'Search Results Window' is clickable before the window is created. This is probably a topic for another issue, but essentially the object is not created until a search in all files is performed and so the menu item should be greyed out until this has happened or it should open an empty window. Whereas currently prior to a search nothing happens on menu click, or 'F7', 

Back on this topic.
For my proposal, as there exists only one instance of the 'Search Results Window' I personally do not think it necessary that the input focus is in THAT window when the user presses the keyboard-based closure request. This is of course IF we use a new shortcut/menu item. 

If we were to use the original request of extending the current behaviour of overloading 'F7' to bring focus and also close, then I would agree it is important that this is maintained. 
I.e. Assuming window has been created and closed previously.
'F7' event -> Open and focus -> 'F7' event, if (hasFocus) { close } else { giveFocus } 

I hope that clarifies and answers your question.

**Comment by sasumner** [comment] 2020-05-05 18:00
>why it has two different names, probably would be nice to have one consistent name and also in the code.

That kind of change would almost certainly be rejected.

>strange that the menu item 'Search Results Window' is clickable before the window is created. This is probably a topic for another issue, but essentially the object is not created until a search in all files is performed and so the menu item should be greyed out until this has happened or it should open an empty window. Whereas currently prior to a search nothing happens on menu click,

Yea; not a huge problem though.  But not the greatest thing.

>one instance of the 'Search Results Window' I personally do not think it necessary that the input focus is in THAT window when the user presses the keyboard-based closure request

Which is not what I was asking.  I was asking "If the focus is already IN the *Find result* window, do you have a consideration for a keyboard way of closing it from there?"  It just seems rather strange that if a means to close it from somewhere else is to be added, that it wouldn't also be closeable from itself.  Certainly the mouse can do it (`X` in the upper right corner), but this issue is all about the keyboard.

>...'F7' event, if (hasFocus) { close }

Ah, so you kind of get to it here.  A potential sticking point is that when focus is in the editor window, all of the keycombos are remappable.  So, say user likes F7 for something else and has remapped the search window functionality to F9 (or whatever weird combo the user likes).  Then, with input focus in the search window (your `hasFocus` above), there is no great way to know this and to act on this F9 keypress (to keep it the same as when pressed in the editor.  Well, maybe figuring that out is in-scope for this issue. :-)

>overloading 'F7' to bring focus and also close

Which is sort of a "toggle" functionality.  Another thing is that people like to automate things, potentially with other software.  In this instance, "toggle" functionality is not the greatest because it requires knowledge of current state, so it complicates things -- first you have to know "where you are" and what a toggle will do.  I don't know if that is a consideration here, but it is the first thing that comes to my mind when someone suggests a "toggle".  Not that we are necessarily coding everything in this project with this type of automation in mind....

So for at first what seems a fairly simple thing, it may in the end be somewhat complicated. :-)

**Comment by JJT319** [comment] 2020-05-05 19:22
Okay I see your points and I agree the more you think the less simple it is.

So, with my proposed solution of adding a new menu item and a corresponding keyboard shortcut.
The window is modal(contained inside the parent application, clarity for my sake if I misuse the term) so this means that the key mappings can be applied globally. Event is also handled globally, so it always has the ability to open/close the search results window regardless of where the focus is.
Meaning if the user changes the key mapping, then it will still work with the new key combo selected. 
If the user is in focus of main editor or in focus of the 'Search Result Window' the mapped combo will be able to close the window.

I have coded and tested these scenarios if you would like to compile and try it out for yourself? (How best to share this?) 
I would also then suggest the current menu item 'Search Results Window' be renamed 'Show Search Results Window' for clarity. 
And another thing I will acknowledge is that similarly to as stated previously the new 'Search'->'Hide Search Results Window' in an ideal world would be greyed out when it is not already displayed. Or even not be contained in the menu, but left as a nice keyboard shortcut. The issue then is that the current code does not allow (that I see) a key mapping without a menu item. Well, it does, but the text for the name of the shortcut is taken from the menu list and would be empty without a corresponding menu item, which of course is not good.

**Comment by sasumner** [comment] 2020-05-05 19:40
So we've had some good dialogue here, back and forth, but I hope I haven't misled you, in that **_I'm_** not the one that will accept or reject your contribution.  The project owner ( @donho ) is that guy.

With that being said, I can certainly try out your changes and offer additional opinions.  The best way for this to happen is that you create a Pull Request (PR) from your fork of the code back to the master.  This will cause an auto-build of your changes and an .exe to be created and put on a server somewhere.  From there, I or anyone that wants to try it out can easily grab a copy.

The PR process will also "put it in the list" of the project owner for review (which takes a bit of time until its gotten to), so if you just want to share your changes without really having them considered for integration (perhaps they're not in final/best form), you can close your PR and then it will be removed from the review list.  I'm pretty sure the .exe will remain available for something like 6 months, though.

**Comment by JJT319** [comment] 2020-05-10 12:27
Thanks for the help and good discussion. I wasn't sure if there were multiple admin for this project. 
I have now created a PR and will wait to hear of any feedback from yourself or the project owner.

**Comment by sasumner** [comment] 2020-05-10 12:47
@JJT319 One thing I guess I forgot to mention is, what is the proposed action for this when there are more than one **_Find Result_** windows open?  For example, in this case where I have FOUR open?:

![image](https://user-images.githubusercontent.com/30118311/81499610-cb33a600-929a-11ea-996e-0267b06fbec2.png)

**Comment by JJT319** [comment] 2020-05-16 13:25
@sasumner I would think this is fine, as the code added reflects the current code. I.e Open vs Hide.
But, to be honest, I had not seen an option to have more than one 'Find Result' window. In fact, I still don't :( 
Please can you explain how that is possible and I can test this. 
The PR is now up if you would like to try for yourself. 
Thanks again for a good comment.

**Comment by sasumner** [comment] 2020-05-16 13:45
@JJT319 said:

>I had not seen an option to have more than one 'Find Result' window.
>can you explain how that is possible

Right-click in the original _Find result_ window.
On the popup that appears there will be a choice called _Find in these found results_ ; choose that
Run a secondary search via the window that opens at that point
After the secondary search runs you will have a second _Find result_ tab similar to what I show above in my screenshot (except the screenshot shows 4 not 2).
You can repeat this process a few times to generate my exact screenshot.

**Comment by JJT319** [comment] 2020-05-16 14:20
Okay...Interesting.
So it does not behave as I expected, but i'd say this is a separate bug. The current released behaviour is such that pressing the keyboard shortcut, 'F7' by default, opens/focuses in and out of only 'Find Result 1'. That means my enhancement only Hides 'Find Result 1'.
'Find Result n' Where n is greater than 1. Does not have a keyboard shortcut mapped. 
I am not sure there is a simple solution to this. A solution(my previous expectation) would be that there is one 'Find Result' window and within this it has the potential for 'sub' windows 'Result n'.

My suggestion would be to wait and see if this PR is accepted in its current form, then decide whether to raise a new issue for this new problem.
Do you agree?

**Comment by sasumner** [comment] 2020-05-16 15:15
It (the PR) is your football.  
Meaning that you get to decide what to do.
I was just the "assistant coach", pointing out this, pointing out that...
:-)

**Comment by donho** [comment] 2020-06-16 21:58
@JJT319 
I don't like the idea to add a new command just for that. Let's make ESC key to hide Search Results Window when it is focused..

**Comment by HerbM** [comment] 2020-07-08 20:17
Any of these (that don't break anything else) would be fine as long as the following is true:

**The Search Results Windows could be closed (after mapping) using 1 or a couple of keystrokes without touching mouse, whether focused on Search Results or Edit window etc.**

I would probably use this 50+ times per day and be happy to create a macro for myself if it's more than a key or two to execute.

I could live with it being somewhat different depening on which window is focused.

Thanks to anyone willing to comment or work on this....

**Comment by JJT319** [comment] 2020-07-08 21:08
@donho Thanks for your time. Sorry for slow reply, been busy with other things. 
I will take another look soon. 

@HerbM I hope the ESC Key solution will be sufficient. 
It means it will either be one keystroke or two. 
If the search results window is not focused you would need to press ‘F7’, default key bind, to focus on the search results window. Then ESC to close.

**Comment by HerbM** [comment] 2020-07-09 21:44
@JJT319 
That's find (2 keys:  F7 ESC).

Even better if a macro works but 2 keys is fine.

Thanks so much if you have time to implement.

**Comment by jtgithubuser** [comment] 2020-07-14 03:30
I've been in love with notepad++ for many years.

So strange... I just searched on this toggle issue today, because of another problem I have.  I will explain both...
I wish there was a confirm close tab option.  I close a tab by mistake and lose all of my bookmarks.

So, I was tediously trying to put them back in by searching a term, then clicking to the edit window, adding a bookmark, searching, repeat repeat repeat...

After reading the start of this thread, something clicked, I went back to what I was doing and saw that ESC is the answer.

Then I came back to the thread and read from the bottom and see that ESC is the recommended solution.

Wasn't it always there?

But lastly...  is there a way to force a confirm close on a tab?  Or a way to easily keep bookmarks saved somewhere?  I know, wrong thread, but can someone please point me to it?  I make this mistake a lot.

**Comment by vinsworldcom** [comment] 2020-09-23 18:39
I would love to see Escape key close the active Search Results Window (i.e., when it has focus).  I tried.

I've done some testing in the FindReplaceDlg.cpp file, but I don't understand the code well enough.

notepad-plus-plus\PowerEditor\src\ScitillaComponent\FindReplaceDlg.cpp
3192:	LRESULT FAR PASCAL FindReplaceDlg::finderProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
3193:	{
3194:		if (message == WM_KEYDOWN && (wParam == VK_DELETE || wParam == VK_RETURN || wParam == VK_ESCAPE))
3195:		{
3196:			ScintillaEditView *pScint = (ScintillaEditView *)(::GetWindowLongPtr(hwnd, GWLP_USERDATA));
3197:			Finder *pFinder = (Finder *)(::GetWindowLongPtr(pScint->getHParent(), GWLP_USERDATA));
3198:			if (wParam == VK_RETURN)
3199:				pFinder->gotoFoundLine();
     				else if (wParam == VK_ESCAPE)
     				{
     					pFinder->setClosed(TRUE);
     					pFinder->destroy();
     				}
3200:			else // VK_DELETE
3201:				pFinder->deleteResult();
3202:			return 0;
3203:		}

Does not work.

But eager to see Escape key close the active Search Results Window.

Cheers.

**Comment by JJT319** [comment] 2020-09-23 19:14
Sorry for excuses, but I can’t believe how long it’s been since I last looked at this. 

Anyways I will take a look tomorrow and let’s see if we can get this done.

**Comment by vinsworldcom** [comment] 2020-09-23 20:09
@JJT319 Thanks!  I took a [stab](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2946#issuecomment-697860715) at using the Escape key to close the window but I don't have deep C++ chops.

Cheers.

**Comment by JJT319** [comment] 2020-09-24 20:05
@vinsworldcom You were close. Thanks for pointing me straight to where to handle the ESC key. 
Where you went wrong is that the 'pFinder' is the object contained within the window. For this we want to close the window or the parent of the 'pFinder'.
The window handling can be seen in other areas of the code, but is generally handled with messages. In this case we are not looking to destroy the object because the user may reopen it straight after. Instead the window is hidden.

Hopefully my change will be accepted. Again apologies for the delay.

**Closed** 2020-09-28 16:46 UTC
Labels: enhancement
