### ISSUE TITLE
Strange UI bug that I cant describe in words

### ISSUE THREAD

**Issue by JohanEntur** [notepad-plus-plus/notepad-plus-plus#10495] opened 2021-09-03 08:11 UTC
![image](https://user-images.githubusercontent.com/33256409/131971488-3c3e8fb5-625e-4ad9-a53c-ed539ba7ccdc.png)

### Description of the Issue
I usually put my computer in sleep mode leaving all apps running. Today when I started up I needed to look at some XML files, so I tried to double click them to open in N++. Nothing happened and I couldnt get N++ to appear on the screen at all so i killed the process. Now N++ is what I can only describe as a lonely box of content surrounded by blank panels. Restarting didnt work, re-installing didnt work (i kept custom settings).

### Steps to Reproduce the Issue
Sorry, no clue.
I wish i could give better information. What I'm looking for is hints, ideas and clues to maybe resolve the issue. If I find a solution, I'll post it here.

### What does not help
- Reinstall from 32 bit to 64 bit (keep settings)
- Reinstall (do not keep settings)
- Change theme
- Closing or moving the boxes around the central content box (closing works but doesnt help, trying to drag-move them crashes the application).
- Maximize, minimize, window resize

### Debug Information
Notepad++ v8.1.4   (64-bit)
Build time : Aug 21 2021 - 13:04:59
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1903
OS Build : 18362.592
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment] 2021-09-03 10:11
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed by ArkadiuszMichalski** 2021-09-03 10:11 UTC
