### ISSUE TITLE
Map whole filenames to languages

### ISSUE THREAD

**Issue by rcdailey** [notepad-plus-plus/notepad-plus-plus#1611] opened 2016-03-09 21:22 UTC
Using the Style Configurator, I am not able to map whole filenames to languages. For example, a file named `COMMIT_EDITMSG` cannot be mapped to the "DIFF" language. Note that this file is created by Git when editing a commit message. If you use `git commit -v`, it essentially puts the patch file of the changes in the commit message file. It's useful to have this file colored using DIFF by default.

**Comment by patricknelson** [comment] 2016-04-19 21:45
This is still an issue and would love to see a fix for this. There used to be a fairly convoluted method of accomplishing this for those who were a little more determined, by installing first a Python Script plugin and then manually installing some python scripts which would then automatically parse out vi-style modelines. That method now, however, no longer works since the plugin is no longer updated: http://stackoverflow.com/questions/11786906/how-to-associate-languages-with-files-without-extensions-in-notepad/16268995#16268995

More and more files now have special formatting but no file extension, for example, `Vagrantfile` and `hosts` in my case and also `COMMIT_EDITMSG` in OP's case.

**Comment by MetaChuh** [comment] 2019-04-13 02:34
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:34 UTC
