### ISSUE TITLE
Find Previous behavior is different than Find Next when finding a sequence of identical characters

### ISSUE THREAD

**Issue by bl-ue** [notepad-plus-plus/notepad-plus-plus#8913] opened 2020-09-27 17:52 UTC
### Description of the Issue
In the Find window, the Find Next behavior is different than the Find Previous behavior when the text to find is a sequence of identical characters and there is larger sequences of the same character in the file.
Find Next selects the next group of characters starting immediately after the last character group, whereas Find Previous selects the previous group of characters, but instead of selecting the group ending immediately before the last character group, it selects a group of characters ending with the second last character of the last group.

For example, when finding `***` in a file with the contents of `******`, Find Next only selects 2 groups, but Find Previous selects 4 groups.

### Steps to Reproduce the Issue
1. Create a new empty file.
2. Type 6 asterisks (`******`)
3. Open the Find Window (Ctrl+F)
4. Search for 3 asterisks (`***`).  Press enter a few times.  Notice how only two groups are selected.
5. Press shift+enter a few times.  Notice how four groups are selected.

### Expected Behavior
I expect the Find Previous behavior to be the same as that of the Find Next.

### Actual Behavior
See above.

### Debug Information
```
Notepad++ v7.8.9   (32-bit)
Build time : Jul 15 2020 - 20:26:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by sasumner** [comment] 2020-09-27 18:13
Probable duplicate of #8661

@bl-ue Try it in Windows' `notepad.exe`

**Comment by bl-ue** [comment] 2020-09-27 22:29
Interesting.  The same thing happens in `notepad.exe`.

**Comment by sasumner** [comment] 2020-09-27 23:39
>The same thing happens in notepad.exe

Yes, that was my point. :-)

**Comment by sasumner** [comment] 2020-09-27 23:39
Anyway, closing as 8661 has this covered.

**Closed by sasumner** 2020-09-27 23:39 UTC
