### ISSUE TITLE
[BUG] Drag and dropping folders onto NP++ does not open the files within them but ask to create file for the folder instead

### ISSUE THREAD

**Issue by blockberd** [notepad-plus-plus/notepad-plus-plus#15666] opened 2024-10-01 10:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

When drag and droppening one or more folders onto the Notepad++ main window does not open the files within these folders anymore but ask if a new file for such a folder should be created:
![Notepad++ create new file for folder](https://github.com/user-attachments/assets/41b5d4ba-b53f-488f-b3ce-68ff10c3db9c)

### Steps To Reproduce

1.  Open Notepad++
2.  Make sure "Open all files of folders instead of launching Folder as Workspace on folder dropping" in "Default Directory" is enabled.
3.  Drag and drop multiple folders with files in them onto the Notepad++ main window

### Current Behavior

Notepad++ wants to create files for the folders instead of opening the files of that folder.

### Expected Behavior

It should open all files of all selected folders in Notepad++.

### Debug Information

```shell
Notepad++ v8.7   (32-bit)
Build time : Sep 17 2024 - 17:07:51
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows Server 2019 Standard (64-bit)
OS Version : 1809
OS Build : 17763.6292
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2312)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (2.0.7)
    XMLTools (3.1.1.13)
```

**Comment by xomx** [comment] 2024-10-01 21:34
Duplicate of #15645 , already fixed (for the next version, probably v8.7.1).

**Closed** 2024-10-02 02:23 UTC
