### ISSUE TITLE
Replace window has disabled option in_selection for the first run

### ISSUE THREAD

**Issue by sebastian-czarnecki** [notepad-plus-plus/notepad-plus-plus#9851] opened 2021-05-11 13:13 UTC
### Description of the Issue

Search and replace function / "in selected text" not working and first time of use this function

### Steps to Reproduce the Issue

1. Open Notepad++
2. Put some text
3. Select some text
4. Go to Replace function (Ctrl+H)
5. Field "in selection" is disabled
6. Close Replace window
7. Open Replace window (Ctrl+H)
8. You see field "in selection" is enabled

### Expected Behavior

The enabled already at the first start of the Replace function

### Actual Behavior

The field is disabled the first time the Replace function is run

### Debug Information

YT: https://youtu.be/gt77Sm-5Qks

**Comment by sasumner** [comment] 2021-05-11 13:16
Duplicate of #9611

**Closed by sasumner** 2021-05-11 13:16 UTC
