### ISSUE TITLE
Minimize to system tray and back will see the closed sidebar (both left and right) re-appeared

### ISSUE THREAD

**Issue by xzs217** [notepad-plus-plus/notepad-plus-plus#10743] opened 2021-11-02 09:58 UTC
### Description of the Issue

If minimize to system tray and back, one will see the closed sidebar (both left and right) re-appeared
### Steps to Reproduce the Issue

1. Enable "Preference" -> "MISC." -> "Minimize to system tray"
2. Open sidebar by "View" -> "Function List" or "View" -> "Folder as Workspace"
3. Close sidebar by click on the close button at top right corn of the sidebar
4. Minimize NPP, note NPP is now in the system tray
5. Maximize NPP
6. Observe sidebar

### Expected Behavior

Step6: Sidebar remains in closed state, i.e. does not appear
### Actual Behavior

Step6: Sidebar re-appears
### Debug Information

Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : E:\Program Files\npp.8.1.9.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.1593
Current ANSI codepage : 936
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFavorites.dll 

![image](https://user-images.githubusercontent.com/34054892/139825360-6844b72d-d0a7-4329-9800-71e106581a43.png)

**Comment by ArkadiuszMichalski** [comment] 2021-11-03 11:59
In fact, the same for me:
```
Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : D:\_test\NPPClean\notepad++.exe
Command Line : -multiInst
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll
```

**Comment by xomx** [comment] 2021-11-03 13:58
I have already fixed this bug, fix will be included in the next N++ release.
If you do not want to wait you can try this appveyor build:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/41294974

**Comment by ArkadiuszMichalski** [comment] 2021-11-03 14:36
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10512.

**Closed by ArkadiuszMichalski** 2021-11-03 14:36 UTC
