### ISSUE TITLE
"Alternate Icons" are gone after restart

### ISSUE THREAD

**Issue by Moonsilence** [notepad-plus-plus/notepad-plus-plus#10858] opened 2021-11-30 10:46 UTC
Hi!

I wan't to use the "alternate icons" on the tabs instead of the "default icons" which do not show an icon on unedited and saved files. When activating the option "alternate icons", the icons instantly appear on the tabs. However after a restart, they revert to the default icons. The checkbox "alternative icons" is still checked. Unchecking and re-checking restores the desired icons, but again, this does not persist across restarts.
Using v8.1.9.2 (32-bit) and Darkmode.
This latest version's release notes specifically stated that some issue in this regard was fixed.

Kind regards!

**Comment by ArkadiuszMichalski** [comment] 2021-11-30 11:13
This happend when Dark mode is on.

**Comment by ArkadiuszMichalski** [comment] 2021-11-30 11:15
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10159.

**Closed by ArkadiuszMichalski** 2021-11-30 11:15 UTC
Labels: bug, duplicate, dark mode
