### ISSUE TITLE
Add function Copy\Cut current line.

### ISSUE THREAD

**Issue by GOLEM777** [notepad-plus-plus/notepad-plus-plus#8954] opened 2020-10-05 17:16 UTC
Add function **Copy** and **Cut** the current line where the caret is.
And additional function, insert line below the caret or above.

It is automation and simplification of actions:
1 - 3-х clicks on line
2 - Copy or Cut (Ctrl-C or Ctrl-X)
3 - Select **beginning** of needed line
4 - Paste (Ctrl-V)

-------
I was unable to implement this in a macro.

**Comment by sasumner** [comment] 2020-10-05 17:47
Closing as duplicate of #18

**Closed by sasumner** 2020-10-05 17:47 UTC
