### ISSUE TITLE
blank language in the language menu

### ISSUE THREAD

**Issue by MaDill** [notepad-plus-plus/notepad-plus-plus#3009] opened 2017-03-09 07:40 UTC
### Description of the Issue
In the language menu is a blank language without text

### Steps to Reproduce the Issue
![notepad _language_blank](https://cloud.githubusercontent.com/assets/7298934/23740439/dcf3d9ba-04a3-11e7-92fb-10336eb49ddf.png)
Between JSON and BaanC

### Expected Behavior
update the text

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Users\mdill\Downloads\_PortablePrograms\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll Explorer.dll LanguageHelp.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 23:57
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:57 UTC
