### ISSUE TITLE
Enable Movement Keys (Arrow Keys) and Return (Enter) in Column Mode / Multi-Editing Mode

### ISSUE THREAD

**Issue by tobsimon** [notepad-plus-plus/notepad-plus-plus#1711] opened 2016-04-04 16:30 UTC
I really like column mode. It gives a huge productivity boost in ad hoc situations, where devising a working regex replace would take too long. I think no editor is complete without it.

Notepad++ has two different but similar modes, column mode (Alt + drag / Alt + Shift + click / Alt + Shift + movement keys) and multi-editing (Ctrl + click / Ctrl + drag).

I suggest enabling the movement keys and return to work in both modes as expected. Currently they reset the respective mode and only work on the last cursor position.
## 

Current situation:

It is possible to insert a return character at every cursor position with its ascii code (NumLock: Alt + 013), see [http://superuser.com/questions/763132/notepad-how-to-insert-a-new-line-when-multi-editing](url), or by pasting a previously copied one. The result of consecutive edits is different in column mode and multi-editing. While multi-editing has no problem with disjoint cursor positions and works as expected, in column mode the cursor gets re-adjusted after the first input to span all lines without gaps.

In column mode, when deleting a tab character with backspace, which spanns different lengths on different lines, the cursor is positioned according to the line where the column mode was started, regardless the other lines, where the cursor now sits in arbitrary relative position.
#1775 discovered that column mode does not play well with line wrapping turned on.

It is possible to upgrad a column mode selection to a multi-editing one by adding another cursor position with Ctrl + click. Partly overlapping selections are not merged automaticly, their replacement works on every part separately. The column editor (Alt + C) works in multi-editing mode.
## 

Desired situation:

Fusion of column mode and multi-editing into one alt-mode, including extended editing capabilities.

I think the re-adjusting of the cursor in column mode is of no desirable use and that breaking it into several cursors would be the expected result.

Inserting Return, deleting tabulators and line wrapping should work as expected and break the relative cursor positions when applicable but not exit alt-mode

Enter alt-mode by holding Alt + click, Alt + movement keys to create a new cursor at the new position, Alt + drag, Alt + Shift + click, Alt + Shift + movement keys to span a selection.
Edit alt-mode with all the above inputs, but also Ctrl + click to delete a cursor, Ctrl + movement keys to move the last cursor without the other cursors or selections and remove those cursors in the way, Ctrl + Alt + drag, Ctrl + Alt + Shift + click, Ctrl + Alt + Shift + movement keys to remove (part of) a selection. (This behaviour is very close to selections in graphics applications.)
Exit alt-mode with Esc or a click.

The movement keys should move the whole construct of cursors. The right and bottom border (line endings and file end) should be expanded dynamicly (and padded with spaces upon edits) to accomondate cursors moving there. At the top and left border, the cursors should fall of the border and disappear without reappearing, when moving back. Pos1 and End should break the relative alignment of the cursors. End should choose a position, such that no affected line extends it, and expand shorter ones accordingly.

Backspace and Del need to behave differently, when line endings are concerned. They should only delete line endings, if every cursor would delete a line ending, so if every cursor sits at the start or end of a (possibly expanded) line. This automatic padding sets it apart from Ctrl + J.
## 

I reformulated the request after discovering the possibilities and side-effects of multi-editing.
#1414 is a subset of this request.

**Comment by MetaChuh** [comment] 2019-04-18 01:31
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your support and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-18 01:31 UTC
