### ISSUE TITLE
Notepad++ 7.3.1 64-bit, use new style dialog always checked

### ISSUE THREAD

**Issue by marb99** [notepad-plus-plus/notepad-plus-plus#2845] opened 2017-01-30 05:54 UTC
### Description of the Issue

Use new style dialog always checked when open Notepad++ even if you uncheck when you close and open Notepad++ again the  Use new style dialog option is checked.

On Notepad++ 7.3 does not happen works as expected to work its a bug on 7.3.1 version

**Comment by dail8859** [comment] 2017-01-30 14:24
Duplicate of #2814, #2829

Fixed by 1a0e6d7

This will be fixed in the next release.

**Closed by dail8859** 2017-01-30 14:24 UTC
Labels: duplicate
