### ISSUE TITLE
NP++  7.9.4 File doesn't save as extension type (win 7)

### ISSUE THREAD

**Issue by EatDesk** [notepad-plus-plus/notepad-plus-plus#9657] opened 2021-03-15 04:15 UTC
### Description of the Issue

Same issue as https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9510

Should have been fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/f96d81af11de99fd48e4ef37e0265aa5e45033fd unless I misunderstand?

Unfortunately the commit did not fix the issue on win 7 at least.

In Notepad++ 7.9.2 I can do "Save as", file name: "lol" and "Save as type": "Normal text file (*.txt)" and the output file will be "lol.txt". Choosing the same options in 7.9.4 and the output file is named "lol" with no extension.

I don't have the option "Set Save dialog file extension filter to \*.\*" checked.

### Steps to Reproduce the Issue
Edit for exact steps:
ALT -> F -> A -> this for for the "Save As..." menu, then I type my filename and hit Return.

The CTRL+ALT+S shortcut will also replicate the issue.

### Expected Behavior
Above

### Actual Behavior
Above

### Debug Information
Notepad++ v7.9.4   (64-bit)
Build time : Mar 15 2021 - 01:03:10
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment] 2021-03-15 09:16
Yes, it should have been fixed.
I've just tried on Windows 7 VM and I can't reproduce it. Unless, you didn't specify some important steps.
Here is what I did:

https://user-images.githubusercontent.com/9664141/111130362-ce18ba80-857f-11eb-910d-8de72875e8bd.mp4



Could you, please, record a video?

**Comment by EatDesk** [comment] 2021-03-15 13:38
> 
> 
> Yes, it should have been fixed.
> I've just tried on Windows 7 VM and I can't reproduce it. Unless, you didn't specify some important steps.
> 

Apologies, I should have noted the exact process. I always use keyboard shortcuts so the exact process to reproduce is:

ALT -> F -> A -> this for for the "Save As..." menu, then I type my filename and hit Return.

**Comment by ArkadiuszMichalski** [comment] 2021-03-15 14:20
@EatDesk Can you try with [fresh portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad)? Maybe something is wrong with the settings. I can't reproduce in:
```
Notepad++ v7.9.4   (32-bit)
Build time : Mar 15 2021 - 01:00:14
Path : D:\_test\NPPClean\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 7 Ultimate (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1250
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

**Comment by EatDesk** [comment] 2021-03-15 15:24
> 
> 
> @EatDesk Can you try with [fresh portable version](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad)? Maybe something is wrong with the settings. I can't reproduce in:
> 
> ```
> Notepad++ v7.9.4   (32-bit)
> Build time : Mar 15 2021 - 01:00:14
> Path : D:\_test\NPPClean\notepad++.exe
> Admin mode : ON
> Local Conf mode : ON
> OS Name : Windows 7 Ultimate (64-bit) 
> OS Build : 7601.0
> Current ANSI codepage : 1250
> Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
> ```

You're right it doesn't occur with a fresh portable version. However that allowed me to find the setting that was causing this, it was the default save file directory apparently: Settings > Preferences > Default Directory: C:\Users\EatDesk\Desktop

If I switch portable to that directory the bug also occurs as it does with my installed version.

If I change the Default Directory to C:\Users\EatDesk\Desktop\Test the bug doesn't occur in either my installed version or portable.

**Comment by mere-human** [comment] 2021-03-15 19:06
I've just tried the scenario with setting Desktop as the Default Directory locally.
I don't see the issue on Windows 10.
But I see the same issue on Windows 7.

Looking into it...

**Comment by mere-human** [comment] 2021-03-19 08:46
@EatDesk One more question. 
Could you, please, check if the issue occurs when you:
- Open a save dialog by any means (e.g. _Alt > F > S_)
- Instead of pressing _Return_ key, press _Alt + S_ or press _Save_ button with a mouse?

Because for me the issue occurs only when I press _Return_ key.

**Comment by mere-human** [comment] 2021-03-19 20:24
@EatDesk You can check the issue again with the build artifacts from the PR above (if you want).
The process is described here: https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing

**Comment by EatDesk** [comment] 2021-03-19 21:44
> 
> 
> @EatDesk You can check the issue again with the build artifacts from the PR above (if you want).
> The process is described here: https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing

I tested the build and it is resolved from my testing, thanks for looking into it. It''s quite amusing that my normal usage was the perfect chain to trigger the bug.



> 
> 
> @EatDesk One more question.
> Could you, please, check if the issue occurs when you:
> 
>     * Open a save dialog by any means (e.g. _Alt > F > S_)
> 
>     * Instead of pressing _Return_ key, press _Alt + S_ or press _Save_ button with a mouse?
> 
> 
> Because for me the issue occurs only when I press _Return_ key.

I don't know if you needed an answer to this anymore but yes I have the same findings.

**Comment by mere-human** [comment] 2021-03-19 21:46
Thanks for confirmation.
But I think this issue should be closed after the PR got merged.

**Comment by sasumner** [comment] 2021-03-19 23:13
Yes, if/when the change is accepted via the PR (and it should be), this issue will get closed as well.

**Closed** 2021-03-20 22:18 UTC
