### ISSUE TITLE
\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_US.usr: cannot open

### ISSUE THREAD

**Issue by IvanUrwin** [notepad-plus-plus/notepad-plus-plus#5301] opened 2019-02-08 11:17 UTC
### Description of the Issue

\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_US.usr: cannot open

### Steps to Reproduce the Issue

1. git rebase --interactive  HEAD~7
2. 
3. 

### Expected Behavior

No error messages, Notepadd++ opens to edit the Git TO-DO file

### Actual Behavior

Notepad++ error message 
\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_US.usr: cannot open

### Debug Information

![image](https://user-images.githubusercontent.com/10991603/52475307-07a5bd00-2b93-11e9-836c-aa4723fcb866.png)

**Comment by IvanUrwin** [comment] 2019-02-08 11:19
![image](https://user-images.githubusercontent.com/10991603/52475422-56535700-2b93-11e9-8682-6ca1cef14d39.png)

**Comment by IvanUrwin** [comment] 2019-02-08 11:21
![image](https://user-images.githubusercontent.com/10991603/52475536-afbb8600-2b93-11e9-91a6-e2cb6e4071e0.png)

**Comment by IvanUrwin** [comment] 2019-02-08 11:22
![image](https://user-images.githubusercontent.com/10991603/52475578-ca8dfa80-2b93-11e9-925d-d8d4c43b3add.png)

**Comment by IvanUrwin** [comment] 2019-02-08 11:29
Note1. The problem started recently after Notepad++ suggested I "upgrade" to the latest version. It was bug free until then, so it was a downgrade really.

Note2. Updating the plugins didn't fix the problem. 
I declined the option of replacing a system pthread DLL with some hack for notepad++!

**Comment by chcg** [comment] 2019-02-11 20:08
@IvanUrwin Did you update N++? To which version? 7.5.9 like seen above or a newer one after 7.6.x?
Or did you update one of the plugins?

**Comment by Sebourg** [comment] 2019-02-14 11:18
I had the same issue when opening npp (v 7.6.3). I used a fresh Notepad++ install from the 7z archive.
I managed to remove the error message by creating an empty file named "en_US.usr" in the directory named "Hunspell".

Cheers

**Comment by oakio** [comment] 2019-02-21 15:08
Steps to Reproduce the Issue: Just run `notepad++` from cmd:

```
$ "C:\Program Files (x86)\Notepad++\notepad++.exe"
error: C:\Users\user\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_GB.usr: cannot open
error: C:\Users\user\AppData\Roaming\Notepad++\plugins\Config\Hunspell\en_US.usr: cannot open
error: C:\Users\user\AppData\Roaming\Notepad++\plugins\Config\Hunspell\UserDic.dic: cannot open
error: C:\Users\user\AppData\Roaming\Notepad++\plugins\Config\Hunspell\ru_RU.usr: cannot open
```

Notepad++ version 7.5.9 (latest), OS: Windows 7.

**Comment by Faq** [comment] 2019-02-21 17:44
@oakio latest is 7.6.3

**Comment by oakio** [comment] 2019-02-22 09:14
@Faq thanks. After update to 7.3.6 bug still reproduced.

**Comment by IvanUrwin** [comment] 2019-02-22 10:33
![image](https://user-images.githubusercontent.com/10991603/53236508-51f76580-368c-11e9-923b-32182b8cbda2.png)

Today the problem annoyed me sufficiently that I checked back here. I updated to 7.6.3 and can confirm that the problem is still present. @chcg Yes I previously tried updating all of the plugins and the problem was still there. Today I noticed that there was a new version of a plugin called DSpell so I installed that. I think it was 1.4.7 (from memory). That didn't fix things either. But with the word SPELL appearing in both the problem and the plugin I was still suspicious and tried removing the DSPELL plugin.

**That solved the problem - removing the DSPELL plugin.**

**Comment by passingmagic** [comment] 2019-02-25 05:39
The plugin seems to be looking for the default dictionary file en_US.usr. It should be a Warning rather than an error.

### Workaround/Solution:
Open any text file (or create one). Type in a word that is not in the standard dictionary; Right click the word and select "Add ... to dictionary". This creates the en_US.usr file, and the Error no longer appears.

Note, if you don't have auto spell check turned on, run a spell check, and then you will see the red squiggly line underneath the word that is not found in the dictionary.

**Comment by DCamarena5** [comment] 2019-03-09 01:44
Im brand new to all this and am getting this error message. I created a word doc on my computer and added some new words to dictionary but  I am still getting the error message. Is there something Im doing wrong?

**Comment by mfreema5** [comment] 2019-03-09 15:02
> Im brand new to all this and am getting this error message. I created a word doc on my computer and added some new words to dictionary but I am still getting the error message. Is there something Im doing wrong?

Open a **text file** using Notepad++.  Type some words into it.  Misspell at least one.  Then right-click, etc.

**Comment by MetaChuh** [comment] 2019-04-21 19:40
closed as being plugin related to dspellcheck.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-21 19:40 UTC
Labels: plugin

**Comment by nouinou** [comment] 2019-07-11 19:50
I managed to fix this by going to Plugins -> DSpellCheck -> Settings and clicking on "Remove Dictionaries..." and then removing everything on that list

![image](https://user-images.githubusercontent.com/11968907/61080151-4e3a6480-a41c-11e9-8fbd-62b7da482709.png)

![image](https://user-images.githubusercontent.com/11968907/61080607-59da5b00-a41d-11e9-970e-5a17658f0eba.png)
