### ISSUE TITLE
Cannot press 'y' or 'n' on keyboard to indicate whether I want to save the file I am closing 

### ISSUE THREAD

**Issue by jakeb1996** [notepad-plus-plus/notepad-plus-plus#7670] opened 2019-11-26 23:11 UTC
### Description of the Issue

When I close a file, I want to be able to press `y` or `n` on the keyboard to indicate whether the file should be saved.

### Steps to Reproduce the Issue

1. Open a blank document
2. Type something into the blank doc
3. Close the doc
4. Press 'y' or 'n' on the keyboard

### Expected Behavior

Pressing `y` will save the document, and `n` will not save the document. After pressing either keys, the file will also close.

### Actual Behavior

Nothing happens

### Debug Information

Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xylographe** [comment] 2019-11-26 23:29
Replace **`C:\Program Files (x86)\Notepad++\localization\english.xml`** with [the updated engish.xml](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/english.xml). Start NPP, open **Preferences** dialogue, change to different language, change language back to English.

**Comment by sasumner** [comment] 2019-11-26 23:57
Please search for possible duplicate issues before creating a new one; this type of issue has been opened what feels like dozens of times.  Closing as duplicate of #6223

**Closed by sasumner** 2019-11-26 23:57 UTC
