### ISSUE TITLE
feature request: insert timestamp in any format

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8184] opened 2020-04-28 20:03 UTC
While textfx already does have that feature, it only have the timezone of using the system's time, and the format is:
```
3:58 PM 4/28/2020
```
Or
```
3:58 PM Tuesday, April 28, 2020
```

However, it lacks these features:
- Which timezone, for example UTC
- 12/24-hour format (1:00pm is 13:00)
- Which format, like have it in descending units order: YYYY-MM-DD HH:MM:SS
- If you want or don't want the day names to be shown
- If you want the month to be displayed as numbers instead of names (so instead of [jan 1, 2020], will display [01/01/2020])
- Display seconds

**Comment by dail8859** [comment] 2020-04-28 20:13
Duplicate of #2821 and #497

**Comment by sasumner** [comment] 2020-04-28 23:04
I'll go out a limb and say that Notepad++ developers aren't going to write a super flexible timestamp insertion thingy, when existing scripting plugins do a better job at providing an easy way to do it.

That being said, I'll refer the OP here to the PythonScript way of doing it, an example of which may be found here:  https://community.notepad-plus-plus.org/post/44128

**Comment by GhbSmwc** [comment] 2020-04-30 21:25
Ok, how do I get that python thing into my notepad++'s extension?

**Comment by sasumner** [comment] 2020-05-05 21:04
@GhbSmwc 

- Install Pythonscript from PluginsAdmin (not clear if you did this already or not)
- *Plugins* menu > *Python Script* > *New Script*
- Type name, e.g. `InsertTimestamp` and press *Save*

To run:
- *Plugins* menu > *Python Script* > *Scripts*
- Pick your script

**Closed** 2021-08-18 10:50 UTC
Labels: accepted
