### ISSUE TITLE
Scintilla always gets focus after alt-tabbing

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#378] opened 2015-07-01 18:55 UTC
Have tried to fix this myself, but couldn't find the problem. Any ideas?

Open N++.
Open find dialog.
Use Alt-Tab to go to some other program.
Use Alt-Tab to go back to N++.
=>
Actual result: Scintilla has focus.
Expected result: Find dialog has focus.

In my tests, the Find dialog does receive focus if you switch back and forth between programs using the task bar.

**Comment by Tmp341** [comment] 2015-07-01 19:02
Well, with alt+tab i got the same problem but when i changed the program with mouse, there was no problem.

**Comment by jsuar** [comment] 2015-07-02 11:26
My tests show that neither alt-tab or change of program by mouse keep the Find dialog in focus. This happens even if you alt-tab straight back to N++ without selecting another program. Running Win7. 

Also, is the OP requested action the most usable design? For instance, [this SO question asks](http://stackoverflow.com/questions/22398298/shortcut-in-notepad-to-switch-between-search-box-and-main-window-windows-7) specifically for alt-tab to switch between programs, not between a program and another program find dialog.

**Comment by jonandr** [comment] 2015-07-02 15:40
> My tests show that neither alt-tab or change of program by mouse keep the Find dialog in focus.

I am sometimes able to get it focus on Scintilla after switching with the mouse. Sometimes it goes to the Find dialog. This leads me to believe that this is a pure bug.

> Also, is the OP requested action the most usable design?

Yes, of course ;) Switching back and forth between programs using Alt-Tab should not upset the program state (not by default, anyway). Imagine working in Excel and finding that Alt-Tab caused Excel to jump to another cell.

**Comment by jsuar** [comment] 2015-07-02 16:01
Good point about usable design. The SO question got me wondering if that was the best design approach. Interesting enough, I tried the same steps with other programs to see how alt-tab was handled. Excel's find dialog becomes another window so tabbing to it is no issue. Other programs (Word, IE) have inline find dialogs, but alt-tab does not preserve the find dialog focus. They seem to do the opposite of what you're requesting. Chrome preserves the find dialog focus, however.

**Comment by jonandr** [comment] 2015-07-02 16:05
Another data point: Visual Studio preserves focus on the Find window.

TBH it doesn't matter so much for me what happens in the official N++ version, since I will simply change the behavior in my own fork (if I only knew how!).

**Comment by dail8859** [comment] 2015-07-02 17:30
This issue has annoyed me for a while.

**Comment by milipili** [comment] 2015-07-02 18:08
There is no good reason to not keep the focus on the same component and the same window. So it is obvioulsy a bug in the UI if it behaves otherwise.

**Comment by jonandr** [comment] 2015-07-02 18:19
The quick and dirty solution is to replace this piece in the big switch (obviously only works with the find and replace dialog):

```c++
case WM_ACTIVATE :
	_pEditView->getFocus();
	return TRUE;
```

with:

```c++
case WM_ACTIVATE:
{
	if (_findReplaceDlg.isVisible())
	{
		_findReplaceDlg.getFocus();
	}
	else
	{
		_pEditView->getFocus();
	}
	return TRUE;
}
```

I can see by tracing that if you *don't* set the focus somewhere manually on WM_ACTIVATE, no window at all will have focus when you Alt-Tab back into N++. Does Windows really expect you to manage this yourself? I assumed that it did the obvious thing, unless the program specifically overrides it.

**Comment by dail8859** [comment] 2015-07-02 18:24
The problem with that code however is that the Dialog will *always* get focus, even when it wasn't focused when Alt+Tabbing away from N++. 

Could you use the wParam (to know when it is deactivated) and save a flag whether the dialog had focus or not, and then restore it once activated again?

**Comment by milipili** [comment] 2015-07-02 18:29
Would not be possible to simply keep the handle of the current control with `GetFocus()` and to restore it with `SetFocus` ?

**Comment by jonandr** [comment] 2015-07-02 18:57
Let us continue this disucssion in #393 where there is some code along @milipili's lines, it seems to work okay.

**Comment by milipili** [comment] 2015-07-02 21:30
Sorry i reopen the issue since the problem is still not resolved in the n++ source code.

**Comment by h-h-h-h** [comment] 2015-08-18 02:42
:+1:

**Comment by donho** [comment] 2017-11-16 08:30
Not reproduced in v7.5.1

**Closed by donho** 2017-11-16 08:30 UTC
Labels: accepted, bug
