### ISSUE TITLE
 Foreigners usually treat China with double standards

### ISSUE THREAD

**Issue by HuChundong** [notepad-plus-plus/notepad-plus-plus#7470] opened 2019-10-30 15:49 UTC
Foreigners usually treat China with double standards

**Comment by littlefinger42** [comment] 2019-10-30 16:01
You must be proud to support ethnic cleansing :)

**Comment by mmitic-lotusflare** [comment] 2019-10-30 16:04
Can you give an example please?

**Comment by vxid** [comment] 2019-10-30 16:18
> > Can you give an example please?
> 
> Catalonia and Hong Kong

Oh yes, the famous concentration camps of Catalonia.

**Comment by impala2** [comment] 2019-10-30 16:23
@HuChundong Spain is not an Orwellian police state.

**Comment by mmitic-lotusflare** [comment] 2019-10-30 16:23
> Catalonia and Hong Kong

Can't reproduce the double standard, we can close the issue

**Comment by dongyingt** [comment] 2019-10-30 16:52
> You must be proud to support ethnic cleansing :)

美国人对待黑人很不友好

**Comment by dongyingt** [comment] 2019-10-30 16:54
> > independent
> 
> California also can be independent? do you think so?

琉球可以独立，北爱尔兰也可以独立

**Comment by tkmmot321** [comment] 2019-10-30 17:40
> 
> 
> > > Pretty sure if California residents do agree, they can.
> > 
> > 
> > They can vote on it (unlike some)
> 
> 我们几千年来的理念是统一，美国的这种投票独立很好，虽然现在支持加州独立的人很好，那我们就支持他们吧。看来我们的理念不一样，我们无法改变你们的想法，也不会去影响你们，请不要拿你们那一套来招惹我们。

建議你可以去找微軟施加壓力
畢竟微軟收購了github了，你囯最喜歡就是做小動作不是嗎？
如果微軟不表態那麼不要用windows和office了，學華爲筆記本換成deepin不就好了
git服務又不是不能夠自己架，如果你怕別人招惹你的話可以使用你囯的託管服務。
這是你自己的選擇自由，既然你想用github麻煩你就尊重github不會自我閹割政策

**Comment by Loys** [comment] 2019-10-30 18:45
> Catalonia and Hong Kong

What did you understand about Catalonia?
Do you read the paper in Europe, or in Spain?
Or... Do you think all westerners are the same country? 😂
I am joking, but lately, i found that many Chinese persons (mostly Mainlanders) are not really aware on how the world is doing outside the Communist Party of China (CPC).
If you check at the posts in the issues section of the notepad-plus-plus you will find what i am talking about : Some people are "complaining" about Taiwan ! 
Could you explain, what does Taiwan have to do with Uyghur?
You see what i am talking about right?
All mixed up? (open your mouth) Ready to eat? Propaganda?

**Comment by ghostmummy** [comment] 2019-10-30 18:52
Re: California 

No, they can’t vote and leave. The us civil war showed that, also the Supreme Court has always said that there is no legal basis for secession. Of course, they could start a war about it, but I don’t think California would win.

**Comment by NinKenDo64** [comment] 2019-10-30 20:57
Chinese people be like "Mum says it's MY turn to commit ethnic cleansing."

中国人说的就是这样 “妈妈说这次就是我会进行种族灭绝的！“

**Comment by rrttyyu** [comment] 2019-10-30 22:04
> > > Pretty sure if California residents do agree, they can.
> > 
> > 
> > They can vote on it (unlike some)
> 
> 我们几千年来的理念是统一，美国的这种投票独立很好，虽然现在支持加州独立的人很好，那我们就支持他们吧。看来我们的理念不一样，我们无法改变你们的想法，也不会去影响你们，请不要拿你们那一套来招惹我们。

你们有投票权么?傻逼支那猪,而且美国又没说你不可以支持加州啊,你们支那猪的网站允许发香港独立的言论么? 还双标,双标你妈逼的支那杂种

**Comment by rrttyyu** [comment] 2019-10-30 22:07
> > Catalonia and Hong Kong
> 
> What did you understand about Catalonia?
> Do you read the paper in Europe, or in Spain?
> Or... Do you think all westerners are the same country? 
> I am joking, but lately, i found that many Chinese persons (mostly Mainlanders) are not really aware on how the world is doing outside the Communist Party of China (CPC).
> If you check at the posts in the issues section of the notepad-plus-plus you will find what i am talking about : Some people are "complaining" about Taiwan !
> Could you explain, what does Taiwan have to do with Uyghur?
> You see what i am talking about right?
> All mixed up? (open your mouth) Ready to eat? Propaganda?

The double standard is we can talk about California independence here, without worry about getting arrested because of our speeches, but Mainland Chinese can' t talk about HK independence on social network because they gonna get fucked up by the CCP (Big Brother Xi is watching you).

**Closed** 2019-10-31 01:55 UTC
