### ISSUE TITLE
[Feature request] Add some options to the project manager to make it really good

### ISSUE THREAD

**Issue by manuel-di-iorio** [notepad-plus-plus/notepad-plus-plus#1240] opened 2015-12-10 14:29 UTC
1) Right now, you have to create the file with the system file explorer and then add the file created with the "Add files" option through a File Dialog. Too many steps.

Instead, this option should be inside Notepad++, just put this option before "Add files.." when you right-click the file, maybe named "Create empty file" or "Create file" and obviously, when the file is just created (or maybe before) show the rename box on that file.

Actually notepad++ should automatically add/rename/move/delete files and folders when using the system file explorer, instead to do these changes per every single file/folder manually.

---

2) Add the option "Open file location in the File Explorer" or something like that.

---

3) Add the "Duplicate file" option.

---

4) Is the "Reload Workspace" option, useful at all? Why not just automatically apply updates on the structure like I wrote in the latest part of the first point?

The project manager should not make a local copy of the project folder but to work directly with the file system, the other plugins doesn't do well their job, you can make this really good

**Comment by MetaChuh** [comment] 2019-04-11 00:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:42 UTC
