### ISSUE TITLE
NotePad 7.9.3 not start after has been installed (Plugin conflict : NppSaveAsAdmin)

### ISSUE THREAD

**Issue by alphacentauris44** [notepad-plus-plus/notepad-plus-plus#9554] opened 2021-02-21 21:09 UTC
### Description of the Issue
After installing the 64 bit version of notepad ++ 7.9.3, the application will fail to start without prompting immediately.

I tried uninstalling keeping the configuration, restarting, but nothing helped.

I had to go back to 7.9.2 for now for check all plugins, one by one.

I have finally removed NppSaveAsAdmin plugin, now notepad 7.9.3 may be start.

### Steps to Reproduce the Issue

1.  Update 7.9.2 with addon NppSaveAsAdmin
2.  Upgrade 7.9.2 to 7.9.3
3.  Attempt to launch notepad++
4. Remove NppSaveAsAdmin from plugin directory
5. Launch notepad++

### Expected Behavior
The product start.

### Actual Behavior
Do nothings.

**Comment by mere-human** [comment] 2021-02-22 09:41
Duplicate of #9528

**Comment by vertigo220** [comment] 2021-03-01 17:12
Don't see how it's a duplicate, the user that created that issue isn't using NppSaveAsAdmin plugin, which was the cause of the issue for both myself and @alphacentauris44.

**Comment by dodmi** [comment] 2021-03-01 17:35
But it's a duplicate of my issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9514
Get the [new version of NPP Save As Admin](https://github.com/Hsilgos/nppsaveasadmin/releases/tag/1.0.211) (at the moment, lacking the Save As (Admin) feature):

**Comment by vertigo220** [comment] 2021-03-01 17:46
Thanks. I'd actually tried updating it via N++, which didn't work. Just did it manually and it's working.

**Closed** 2021-03-01 17:56 UTC
