### ISSUE TITLE
Is there a key combination to cancel column mode (or multi-edit) since v8.6?

### ISSUE THREAD

**Issue by cmanley** [notepad-plus-plus/notepad-plus-plus#14464] opened 2023-12-08 19:34 UTC
I use column mode a lot with the simple shift-Alt key combination.
But since v8.6 I'm getting stuck in column mode  (or multi-edit or whatever this new feature is called) and can't get out. 
I can't find any preference to re-enable the pre-8.6 behavior and can't find a key combination to cancel column mode.
All I can do now is change my selection into 1 line and only then does column mode seem to cancel itself. It seems very unintuitive.

**Comment by alankilborn** [comment] 2023-12-08 19:47
<kbd>Esc</kbd>

**Comment by cmanley** [comment] 2023-12-08 21:18
It seems that Esc only works if I move the cursor up or down after some vertical editing (e.g. adding some indent spaces) and then press Esc. So that seems like a bug.

**Comment by rdipardo** [comment] 2023-12-08 23:42
@cmanley 

Here is the N++ code that may provide a more definitive answer to your question:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/bf37d4714f572efa13088863ef6e8ef0132c4021/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp#L615-L633

The story of how this code got there is on Scintilla's bug tracker: https://sourceforge.net/p/scintilla/bugs/2412

**Comment by Coises** [comment] 2023-12-09 18:44
Based on Issue #14266 , it appears this behavior is by design. What I believe will always work in 8.6 is to press an arrow key and then press the Escape key.

This is annoying for people who use rectangular selections often but rarely if ever use stream multi-selection. Pressing an arrow key is a pretty routine behavior which will take some retraining of “muscle memory” to replace, for no gain at all.

It also seems, to me, counter-intuitive to have arrow keys convert the rectangular selection into an empty multiple stream selection instead of a zero-width rectangular selection. Although both are forms of multiple selection to Scintilla, they behave rather differently.

What I would *expect* would be that, with a rectangular selection active, arrow keys would behave as they did before 8.6 (though rectangular selections are multiple selections to Scintilla, to a user they are typically conceptualized as single selections); Shift+arrow and Alt+Shift+Arrow would behave as they do in 8.6 (Shift+arrow converts to multiple and extends/contracts, Alt+Shift+arrow leaves as rectangular and extends/contracts). (Perhaps Ctrl+(Shift+)arrow could convert to a multiple stream selection — empty without Shift, in place with Shift; the current behavior, fragmenting by skipping to the next word, feels really bizarre coming from a rectangular selection.)

All this probably seems like foolish babble to people who are focused on the usability of multiple stream selections; but for folks who use rectangular selections regularly and rarely or never use multiple stream selections, the change is disorienting and counter-productive. We don’t expect cursors to suddenly appear scattered all over the place (as they do if the rectangular selection includes virtual space and virtual space is not enabled in editing preferences — enabling that has its own pain, because it’s no longer easy to place the cursor at the end of a line by clicking past the end). We think of a rectangular selection as a single selection and expect an arrow key to work like it would on any other single selection.

**Comment by donho** [comment] 2023-12-12 16:10
ref: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14296#issuecomment-1848076816

**Comment by donho** [comment] 2023-12-12 16:40
This issue is fixed in the PR #14476.

**Closed** 2023-12-13 02:26 UTC

**Comment by BobKnip** [comment] 2024-01-08 10:32
This does not seem to work for Notepad++ Portable 8.6.1 (i.e. via the PortableApps platform). After adding an (empty) file "noColumnToMultiSelect.xml" to (in my case) directory "C:\Users\<USER_NAME>\Software\PortableApps\Notepad++Portable", I notice no difference in behavior. 

BTW: I was also eagerly awaiting this change, because I very often use a block selection, but almost never the "current" (8.6[.0]) behavior (apparently called "stream multi-selection"?).

**Comment by Coises** [comment] 2024-01-08 16:35
@BobKnip:
> via the PortableApps platform

The correct portable version of Notepad++ can be found on the page for the desired version (usually the first one listed) linked from [the Downloads page](https://notepad-plus-plus.org/downloads/) of the official site. Other versions may have been built incorrectly.

**Comment by networkproblemsolver** [comment] 2024-01-19 14:31
(am I allowed to "comment" on a "closed issue" ???)

I just tried v8.6.2, and it still stays stuck in "large cursor mode" when I do a SHIFT+ALT+ArrowKeys and DEL... I expect that the "large cursor mode" would turn "off" when I press DEL to remove what I have selected.  It does not.  I hope no one says "that is by design."

**Comment by michaelcsikos** [comment] 2024-04-23 03:35
The `noColumnToMultiSelect.xml` workaround isn't working for me anymore.

**Comment by michaelcsikos** [comment] 2024-04-23 03:41
OK, there's a new option in `Settings` > `Preferences` > `Editing 2` > `Enable Column Selection to Multi-Editing`

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/21806535/78506f95-970d-464f-99b4-cea76adc2dc8)


The `noColumnToMultiSelect.xml` file is now ignored.
