### ISSUE TITLE
It does not refresh language in the information buttons (possible bug)

### ISSUE THREAD

**Issue by P0rsche-911** [notepad-plus-plus/notepad-plus-plus#13422] opened 2023-03-25 22:46 UTC
### Description of the Issue

Question:
Is this working correctly or is something wrong?

It does not refresh the language in the AppData folder. It is necessary to close and reopen the program. It does it in all the information buttons.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Change language
3. Select Editing and place the cursor on an information button
4. Language change is not complete

### Expected Behavior

You should change the language to the one selected in General

### Actual Behavior

View captures
### Debug Information

Notepad++ v8.5.1   (64-bit)
Build time : Mar 21 2023 - 19:16:10
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Ultimate (64-bit)
OS Build : 7601.24546
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)
![Notepad ++ 1](https://user-images.githubusercontent.com/93552629/227745785-a8bb749e-a191-45ac-9922-7a34d36dbb29.png)

**Comment by alankilborn** [comment] 2023-03-25 23:21
I believe that popup hints require a restart before a localization (language) change will take effect.  It is normal.

**Comment by ArkadiuszMichalski** [comment] 2023-03-26 08:14
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13286.
Was done and reject.

**Closed by ArkadiuszMichalski** 2023-03-26 08:14 UTC
