### ISSUE TITLE
Open dialog shows Save button

### ISSUE THREAD

**Issue by jslegers73** [notepad-plus-plus/notepad-plus-plus#9987] opened 2021-06-10 11:44 UTC
Hello when I want to open a file via the File - Open I see a little "bug" 

In the Open dialog the Open button is called Save.

![Notepad Open](https://user-images.githubusercontent.com/6212673/121519359-e9b22680-c9f1-11eb-9ab0-93fbc1dbe913.png)

**Comment by sasumner** [comment] 2021-06-10 11:50
Duplicate of #9966

**Closed by sasumner** 2021-06-10 11:50 UTC
