### ISSUE TITLE
Notepad++ should make a record for every time a file is opened or closed.

### ISSUE THREAD

**Issue by hackwrench** [notepad-plus-plus/notepad-plus-plus#1356] opened 2016-01-12 06:58 UTC
I don't know how NPP keeps track of when to update the record now, but it results in NPP forgetting which files it has open when Windows encounters a situation that results in it not shutting down properly. For some reason, at https://notepad-plus-plus.org/community/topic/11089/when-windows-is-shut-down-improperly-npp-forgets-files/4 misgivings about such a feature were expressed, but Claudia Frank wasn't too forthcoming on why she has misgivings. I have asked her to clarify though. I have both remember current session for next launch and Enable session snapshot and periodic backup enabled, but apparently the way that it is implemented still results in NPP forgetting that it had files open.

"Recent file history" sounds like it might have something to do with the "MRU" (Most recently used list, but the "?" menu doesn't appear to have an entry for feature description help, and a web search turned up nothing on the first page of results.

https://notepad-plus-plus.org/community/topic/5324/now-to-disable-recent-opend-files-list-in-menu-window
says something about a file not showing up again when after opening a file and "closing it immediately" it won't show up again, but does the operating system shutting down count as a "close"? How about the definition of "immediately"? Personally I could do without NPP completely forgetting about a file until it gets knocked off the MRU list. These days, everything is poorly documented, so it's not just you. I may be a little bit guilty myself and my circumstances don't absolve me of fault. Microsoft's been guilty of it for quite some time, only they have the problem of Windows 10 being the worst Windows OS ever currently, but at least they have a structure in place for accepting feedback, but I don't know how long it will take for Windows to be made whole again. But I digress.

**Comment by xylographe** [comment] 2016-01-12 16:28
I think, the problem is that the session is only saved when NPP is exited properly.
Saving the session after a new file has been opened and also after a file has been closed, would limit the chance that information is lost after a crash.

**Comment by adventuretc** [comment] 2016-02-05 13:06
I am bothered by this problem as well.

I even asked a question on stackoverflow if there was a plugin that solves this, but the question mysteriously disappeared.

**Comment by hackwrench** [comment] 2016-02-06 15:14
Stackoverflow has very narrow areas of topics that they rather strictly
enforce.

**Comment by MetaChuh** [comment] 2019-04-11 00:53
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:53 UTC
