### ISSUE TITLE
Building Notepad++

### ISSUE THREAD

**Issue by DuraKeonangphane** [notepad-plus-plus/notepad-plus-plus#4474] opened 2018-05-03 16:51 UTC
### Description of the Issue

When building Notepad++ an error display “Scintilla Error cannot load the dynamic library”.

### Steps to Reproduce the Issue

1. Download the source code from Github
2. Follow the instruction using Boost
3. Build notepad++

### Expected Behavior

 Success in building Notepad++ in Visual Studio
### Actual Behavior

The error pop up.

**Comment by MAPJe71** [comment] 2018-05-03 18:56
I know everyone has to start somewhere but when you're not able to diagnose and solve build/link issues, start with a different/other project.

Please close this issue as it's more a question for help and thus more suitable to be posted in the [Community Forum](https://notepad-plus-plus.org/community/category/4/help-wanted).

**Comment by SinghRajenM** [comment] 2018-05-04 05:45
Are you using release version? If so, then you need notepad++ digital signature

If you use debug version, then this error should not appear. Refer file "ScintillaEditView.cpp".

```
HMODULE loadSciLexerDll()
{
	generic_string sciLexerPath = getSciLexerFullPathName(moduleFileName, 1024);

	// Do not check dll signature if npp is running in debug mode
	// This is helpful for developers to skip signature checking
	// while analyzing issue or modifying the lexer dll
#ifndef _DEBUG
	bool isOK = VerifySignedLibrary(sciLexerPath, SCINTILLA_SIGNER_KEY_ID, SCINTILLA_SIGNER_SUBJECT, SCINTILLA_SIGNER_DISPLAY_NAME, false, false);

	if (!isOK)
	{
		::MessageBox(NULL,
			TEXT("Authenticode check failed: signature or signing certificate are not recognized"),
			TEXT("Library verification failed"),
			MB_OK | MB_ICONERROR);
		return nullptr;
	}
#endif // !_DEBUG

	return ::LoadLibrary(sciLexerPath.c_str());
}
```

**Comment by bfridkis** [comment] 2018-05-16 21:31
Perhaps [this](https://github.com/bfridkis/Building-Notepad-Plus-Plus-from-Source-A-Beginners-Guide) could be of some use to you. It basically expands on the instructions provided [here](https://github.com/notepad-plus-plus/notepad-plus-plus).

**Comment by bfridkis** [comment] 2018-05-16 23:44
Rather, see steps [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1228#issuecomment-388978543) by @ClaudiaFrank. Very helpful!

**Comment by SinghRajenM** [comment] 2018-07-21 11:29
@DuraKeonangphane as this is not an issue, bug should be closed.

**Comment by ganego** [comment] 2019-05-16 17:02
Another thing I just stumbled upon - if you make a debug build, PluginAdmin will no longer be there. This is because with a debug build, it no longer expects the nppPluginList.dll file, but instead a nppPluginList.json file. With this file missing, PluginAdmin will not show. See https://notepad-plus-plus.org/features/plugin-admin.html

Or you could make a release build and patch ScintillaEditView.cpp & pluginsAdmin.cpp. Maybe any other files?

**Comment by MetaChuh** [comment] 2019-05-16 17:40
@ganego 

> with a debug build, it no longer expects the nppPluginList.dll file, but instead a nppPluginList.json file. With this file missing, PluginAdmin will not show.

yes, this is expected behaviour, so you have to use nppPluginList.json for these builds.

many thanks and best regards.

**Closed by MetaChuh** 2019-05-16 17:40 UTC
Labels: build / code, question
