### ISSUE TITLE
[Feature Request] STOP deleting file from recent files history when it was 'Saved As'

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#9673] opened 2021-03-19 15:02 UTC
### Description of the Issue
File - Save As drops the original file from the recent files history.
I know there is File - Save A Copy As, but that is not my desire.

### Steps to Reproduce the Issue
1. File - Save As
2. Look for original File in recent files history.
3. It is gone.

### Expected Behavior
I want recent files history to respect all files opened regardless of renaming events.

### Actual Behavior
Recent files history drops renamed files from its list.

### Debug Information
Notepad++ v7.9.3   (64-bit)
Build time : Feb 14 2021 - 03:15:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19042.804
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2021-03-19 15:31
> regardless of renaming events

In a true renaming event (which _Save As..._ and _Save a Copy As..._ are NOT), there is nothing left of the original file, so there is nothing to put in the recent-files history, until the file with the new name is closed.

However, it is reasonable that _Save As_ should leave the original file in the history, as the original file gets closed in this case.  _Save a Copy As..._ should do nothing with the recent-files history.

**Comment by sky5walk** [comment] 2021-03-19 16:26
Then this is a BUG report?

**Comment by mere-human** [comment] 2021-03-19 17:12
I can't reproduce this issue in 7.9.4.
What I've tried:
* _File > New_ (new 1)
* _File > Save as_, then pick a folder and press _Save_
* _File > New_ (new 1) and again _File > New_ (new 2)
* Select "new 2" and _File > Save as_
* Click on dropdown - you can see "new 1.txt" with the full path to it

If that's not what you did, then please update the description.
Or better, record a screen capture.

**Comment by sasumner** [comment] 2021-03-19 17:16
@mere-human 

My thought was that OP is talking about THIS history, not one provided in the _Save As_ dialog (although that one I didn't think about in the past for usefulness!):

![image](https://user-images.githubusercontent.com/30118311/111818144-3be12100-88b5-11eb-8412-7c7ef4f2a4cb.png)

**Comment by sasumner** [comment] 2021-03-19 17:17
@sky5walk

>Then this is a BUG report?

I suppose you can think of it as you like, "feature request" or "bug report".  Is the distinction in any way at all important in this case?

**Comment by sky5walk** [comment] 2021-03-19 17:22
Of course distinction matters.
BUG reports should have higher priority and more likely to be implemented.
To be honest, I lived with this "bug" sooo long and finally got around to posting it.

**Comment by sasumner** [comment] 2021-03-19 17:38
@sky5walk 

You seem to be a bit of a different kind of thinker; I've had this thought every time I've read one of your posts.

I have been a Notepad++ user for a long time, and I've never seen a complaint of this nature, in any forum.
So... how important is it?  Answer: Not very.
So I would tend to treat it as a "feature request" rather than a "bug report".
I don't think a distinction here is going to matter much for the possibility of implementation.

**Comment by sky5walk** [comment] 2021-03-19 21:34
Compliments aside, I will await either solution. Be they bug fix or new feature.

**Comment by sasumner** [comment] 2021-03-20 23:07
#### "Improved" STR:

1. Start from a fresh portable N++ install of 7.9.4; the _File_ menu, when dropped, appears as:
![image](https://user-images.githubusercontent.com/30118311/111887817-f94f3f80-89ad-11eb-9a85-7f9e94016850.png)
2. Create, modify and save a new file with path e.g. `D:\test1.txt`; then close it.
3. Drop _File_ menu and see that the bottom part shows:
![image](https://user-images.githubusercontent.com/30118311/111887875-577c2280-89ae-11eb-8119-985067afdc2e.png)
4. Select the `1: D:\test1.txt` entry from the menu to reopen the file.
5. Press Ctrl+Alt+S to "save as" the file.  Specify `D:\test2.txt` as the name and click OK.
6. Open the _File_ menu and observe the bottom part.

#### Actual behavior:

_File_ menu appears as shown in step 1, i.e., no recent files shown.

#### Expected behavior:

_File_ menu should appear as shown in step 3, because `D:\test1.txt` still exists and was effectively closed when the "save as" was executed.

**Comment by KnIfER** [comment] 2021-03-24 11:18
I wish we could have database-supported file history & session history in NPP  ……

**Closed** 2021-03-26 13:03 UTC
Labels: accepted, enhancement
