### ISSUE TITLE
[BUG] Toolbar disappear and only show vertical lines

### ISSUE THREAD

**Issue by vanmorden** [notepad-plus-plus/notepad-plus-plus#15542] opened 2024-08-12 23:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

I changed to Dark Mode and the toolbar disappeared and only show vertical lines. If I change the icon toolbar size from preferences, the program try to do it but finally only show vertical lines.

### Steps To Reproduce

1.  Change to dark mode

### Current Behavior

I changed to Dark Mode and the toolbar disappeared and only show vertical lines. If I change the icon toolbar size from preferences, the program try to do it but finally only show vertical lines.

### Expected Behavior

Npp show the toolbar correctly

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 23H2
OS Build : 22631.3880
Current ANSI codepage : 1252
Plugins : 
    ComparePlus (1.2)
    JsonTools (8)
    LuaScript (0.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppFTP (0.29.13)
    NPPJSONViewer (2.0.7)
    PythonScript (3.0.12)
    QuickText (0.2.5.1)
    _CustomizeToolbar (5.3)
```

### Anything else?

I take a screenshot and a video.
[Video with the issue](https://1drv.ms/v/s!AmXnKj3f5QjViaAV3FfooIxgtGxiUQ?e=bux58b)

![Captura de pantalla 2024-08-13 012300](https://github.com/user-attachments/assets/64d15ad4-4038-48bd-9cc2-a062a84d8270)

**Comment by ArkadiuszMichalski** [comment] 2024-08-19 10:55
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15440. Try turn off/reinstall _CustomizeToolbar plugin

**Closed by ArkadiuszMichalski** 2024-08-19 10:55 UTC
