### ISSUE TITLE
highlighting comments in shell is incorrect when using unix lines

### ISSUE THREAD

**Issue by aviv-clover** [notepad-plus-plus/notepad-plus-plus#1397] opened 2016-01-20 18:58 UTC
When using unix endlines in a bash file, and a comment line is ended by `\`, the next line is colored as comment:
![image](https://cloud.githubusercontent.com/assets/11358052/12459567/4ebc27c2-bf64-11e5-9a81-dfb4bd52522c.png)

When using Windows newlines, coloring is correct:
![image](https://cloud.githubusercontent.com/assets/11358052/12459577/5ee09ad4-bf64-11e5-9db8-bf5f43c5da50.png)

Both dash and bash interpret the next line as "not a comment", so npp (6.8.8) is wrong here.

**Comment by MetaChuh** [comment] 2019-04-13 01:49
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:49 UTC
