### ISSUE TITLE
notepad.exe replacement

### ISSUE THREAD

**Issue by vladtepesch** [notepad-plus-plus/notepad-plus-plus#7620] opened 2019-11-19 14:44 UTC
i tried to use the notepad replacement feature by registering it like mentioned here:

https://winaero.com/blog/replace-notepad-notepad-plus-plus/

`reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles(x86)%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f`

### Description of the Issue
It mostly works but if it comes to files without extension like the notepad++ own `LICENSE` file then notepad++ opens a error box that it could not find `LICENSE.txt`

### Steps to Reproduce the Issue
I updated the commands according to how they may be actually issued by the windows shell `Image File Execution Options`. See my later posts.

I leave this here for reference:

```
execute `"C:\Program Files (x86)\Notepad++\notepad++.exe" "C:\Program Files (x86)\Notepad++\LICENSE"`
--> works

execute `"C:\Program Files (x86)\Notepad++\notepad++.exe" -notepadStyleCmdline -z "C:\Program Files (x86)\Notepad++\LICENSE"`
--> nothing happens (beseide setting focus on notepad++)

execute `"C:\Program Files (x86)\Notepad++\notepad++.exe" -notepadStyleCmdline -z C:\Program Files (x86)\Notepad++\LICENSE` (without quotes around the filename)
it gives this box: 
![image](https://user-images.githubusercontent.com/1601159/69156109-34541100-0ae3-11ea-847a-c1a9c4c16457.png)
```

### Expected Behavior
open the file correctly without asking to create files with different name
### Actual Behavior
see above

**Comment by sasumner** [comment] 2019-11-19 14:58
It seems dubious that your info in the "Cannot open file" box image is coming from the command line you specified just above it.  `C:` drive, `E:` drive ??

**Comment by vladtepesch** [comment] 2019-11-19 15:24
working directory was `E:\`.

But using that registry tweak to replace notepad.exe and clicking on an extensionless file seems to produce similar box, while clicking on file with extension opens.   
(but using the above command line with a file with extension also produces this box if no quotes are used - so i do not know that windows actually provides as parameter to notepad++)

**Comment by Ekopalypse** [comment] 2019-11-19 15:39
Which npp version are you using, due to [this commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/c16f7bbc1e59e86b4d7650f63a10b8fe47fdaac0), if I understand correctly, it should be fixed since npp 7.8.1.

**Comment by vladtepesch** [comment] 2019-11-20 08:07
I have notepad v7.8.1

**Comment by vladtepesch** [comment] 2019-11-20 08:22
but i currently understand the "Image File Execution Option" a bit better. that it does is it calls the given command with original program as first parameter. so my test calls are wrong: they should look like:

`"C:\Program Files (x86)\Notepad++\notepad++.exe" -notepadStyleCmdline -z "C:\Windows\System32\notepad.exe" "C:\Program Files (x86)\Notepad++\change.log"`    
`"C:\Program Files (x86)\Notepad++\notepad++.exe" -notepadStyleCmdline -z "C:\Windows\System32\notepad.exe" C:\Program Files (x86)\Notepad++\change.log`  

--> both works


`"C:\Program Files (x86)\Notepad++\notepad++.exe"  "C:\Windows\System32\notepad.exe" "C:\Program Files (x86)\Notepad++\LICENSE"`  (with quotes)  
--> opens file in np++ but brings this window:
![image](https://user-images.githubusercontent.com/1601159/69221111-ca854700-0b76-11ea-9c4a-25fd01fb8e20.png)

`"C:\Program Files (x86)\Notepad++\notepad++.exe"  "C:\Windows\System32\notepad.exe" C:\Program Files (x86)\Notepad++\LICENSE` (without quotes)  
--> don't works, brings this window:
![image](https://user-images.githubusercontent.com/1601159/69221253-1afca480-0b77-11ea-8b06-fe90e27d7b91.png)

The last command has the same result as clicking on the file so i guess this is the way how it will be invoked by Windows Shell

**Comment by xylographe** [comment] 2019-11-20 11:50
If invoked as notepad, NPP will try to be compatible with Microsoft Notepad, meaning it will add .txt to a file name that has no extension (see [PowerEditor/src/winmain.cpp](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/ab4cf883367eb3818fc0e6dea57d39d21f9ec618/PowerEditor/src/winmain.cpp#L119)).

The **`-notepadStyleCmdline`** parameter makes NPP behave like notepad (see [this comment](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6030#issuecomment-519942525)).

**Comment by vladtepesch** [comment] 2019-11-20 12:43
but it does not, notepad opens the extensionless file without problems.

**Comment by vladtepesch** [comment] 2019-11-20 12:54
maybe the comment in the linked code applies to other versions of notepad (my is from win10 1803).
Maybe a good way would be to test if the file exists and if not then try to add a ".txt" extension and test again.

**Comment by xylographe** [comment] 2019-11-20 12:55
@vladtepesch 
Microsoft changed this behaviour in Win10. NPP emulates the earlier (XP, Vista, Win7) notepad behaviour. Perhaps, it is time to drop this ‘archaic’ behaviour in NPP as well?

**Comment by vladtepesch** [comment] 2019-11-20 13:00
indeed `c:\windows\notepad.exe "C:\Program Files (x86)\Notepad++\readme"`  opens the `readme.txt`
and `c:\windows\notepad.exe "C:\Program Files (x86)\Notepad++\change"` complains about missing `change.txt` file. So it seems that notepad acts in the same way that i suggested:
test if file exists, if not, add `.txt`
Note: `test.txt.txt` is not opened if `test.txt` is provided as argument. It only added `.txt` if no extension was found

**Comment by wanderleihuttel** [comment] 2019-11-20 14:49
If you want to always open .txt files in notepad++ I suggest you open Notepad++ as administrator, and go to "Settings => Preferences => File Association" and click on Notepad option an register .txt file.

**Comment by vladtepesch** [comment] 2019-11-20 16:07
@wanderleihuttel  that is not the same

**Comment by kapsiR** [comment] 2019-12-06 07:15
I can reproduce this behavior in v7.8.2 too.
It even opens the wrong file, if it's available! (Same folder `README` and `README.txt` => txt-File gets opened)

**Comment by donho** [comment] 2019-12-26 19:32
Cannot reproduce it either.

**Closed by donho** 2019-12-26 19:32 UTC

**Comment by kapsiR** [comment] 2020-01-11 20:12
@donho:
Steps to reproduce:

1. Replace default notepad.exe with Notepad++ (See [Notepad Replacement](https://npp-user-manual.org/docs/other-resources/))
2. Create a file **without** an extension, e.g. README
3. Try to open that file with the default notepad.exe
4. Error (it seems that Notepad++ tries to add `.txt` if ther is no file extension?!)

**Comment by kapsiR** [comment] 2020-01-16 07:09
@donho I reproduced that on v7.8.3 too. May I open a new issue or can you reopen that one?

**Comment by garfieldbanks** [comment] 2021-03-10 18:18
![image](https://user-images.githubusercontent.com/12904270/110677308-418e8680-8192-11eb-8e07-26a7bb235cbf.png)
![image](https://user-images.githubusercontent.com/12904270/110677316-44897700-8192-11eb-9134-0788172e2808.png)
![image](https://user-images.githubusercontent.com/12904270/110677343-4c491b80-8192-11eb-9489-0218e50b335e.png)
![image](https://user-images.githubusercontent.com/12904270/110677360-510dcf80-8192-11eb-8c60-36ece97ccb08.png)

**Comment by garfieldbanks** [comment] 2021-03-10 18:20
This only happens after setting notepad++ setting this reg key to use the new notepadStyleCmdline switch:

reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "<insert_your_path_here>\notepad++.exe -notepadStyleCmdline -z" /f

**Comment by garfieldbanks** [comment] 2021-03-10 18:21
This only happens after using this reg key to set up notepad++ to use the new notepadStyleCmdline switch:

reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "<insert_your_path_here>\notepad++.exe -notepadStyleCmdline -z" /f

**Comment by garfieldbanks** [comment] 2021-03-10 18:23
@kapsiR Did you ever get any response or make a new issue or anything?

**Comment by garfieldbanks** [comment] 2021-03-10 18:33
Just seems strange that nobody has any idea why a random .txt is being added to files without extensions.

**Comment by sasumner** [comment] 2021-03-10 18:49
@garfieldbanks Are you gaining a big advantage by using `-notepadStyleCmdline`.  I find that, if removing that part from such a command line, a file without an extension loads well in 7.9.3.

**Comment by garfieldbanks** [comment] 2021-03-10 18:55
I tried removing -notepadStyleCmdline but now it fails to open files with spaces.

I ran:
reg delete "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /f

and then:
reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "<insert_your_path_here>\notepad++.exe -z" /f

**Comment by sasumner** [comment] 2021-03-10 19:30
>I tried removing -notepadStyleCmdline but now it fails to open files with spaces.

For the spaces situation you're probably going to need a `"%1"` on your command line.  The `"` are the important part.

**Comment by garfieldbanks** [comment] 2021-03-10 19:41
@sasumner Would you mind giving me a command to run? I've tried adding "%1" in several ways but can't seem to get it to work.

**Comment by sasumner** [comment] 2021-03-10 20:14
@garfieldbanks 

I do it as `"c:\path_to_npp\notepad++.exe" "%1"`

**Comment by sasumner** [comment] 2021-03-10 20:29
Well, I was hesitant to answer with my last post above, because clearly I'm doing things in a different manner than you are.  But I don't fully understand what you are really trying to do.  So probably I shouldn't have answered.  

But I will give it a "last try":  the `-z` command line option tells N++ to not process anything after it, so you may want to try `"%1"` between the `notepad++.exe` part and the `-z` part (really not sure what you're needing `-z` for anyway).

If that doesn't help you, probably the best thing you can do is to post on the Community site where there are a lot of readers and probably someone has done exactly what you are doing and needing.  https://community.notepad-plus-plus.org/

**Comment by kapsiR** [comment] 2021-03-10 20:39
> @kapsiR Did you ever get any response or make a new issue or anything?

Yes. Look at https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7902

I hope this makes it more clear what the actual issue is 😉

**Comment by sasumner** [comment] 2021-03-10 21:11
@garfieldbanks Please tell me you don't really have the exact text `<insert_your_path_here>` in your registry "Value data"...

**Comment by kapsiR** [comment] 2021-03-11 08:19
> 
> 
> @kapsiR
> 
> Did you ever figure out any sort of hack to get it to work nicely?

@garfieldbanks The only issue I have when I use the configuration [from the docs](https://npp-user-manual.org/docs/other-resources/) is, that I can't open files without a file extension.  
As workaround I use the context menu in such cases. (Right click => "Edit with Notepad++")

I hope the issue gets fixed some time ... 😉

**Comment by garfieldbanks** [comment] 2021-03-11 15:52
@kapsiR 
Yeah, I've just gone back to the basic command as presented in the ("official"?) user manual / docs. It works well for most things. Just have to be careful when opening files without extensions. But yeah, I just find it kinda strange that no one seems at all interested in fixing an obvious bug even though, as you've pointed out, it's something included in the official user manual / docs.

**Comment by dartraiden** [comment] 2021-09-14 12:30
https://www.binaryfortress.com/NotepadReplacer does this job cleanly
It uses Image File Execution Options too, but opens files without extension correctly

**Comment by kapsiR** [comment] 2021-09-14 13:47
@dartraiden Yes, but it puts itself into the registry:
![grafik](https://user-images.githubusercontent.com/7165033/133269093-ffe6c0b1-99f5-4de4-a924-9788711ee58d.png)

**Comment by dartraiden** [comment] 2021-09-14 15:50
Some more tests:

**Windows 10**
-  [manual method](https://winaero.com/blog/replace-notepad-notepad-plus-plus/)
files with extension - OK
files without extension - FAIL
- Notepad Replacer:
files with extension - OK
files without extension - OK

**Windows 11**
-  [manual method](https://winaero.com/blog/replace-notepad-notepad-plus-plus/)
files with extension - FAIL
files without extension - FAIL

- Notepad Replacer:
files with extension - FAIL
files without extension - FAIL

**Working method on Windows 11**
1) uninstall Windows Notepad via Apps and Features (DO NOT remove Notepad entirely via Optional Features!)
2) delete C:\Windows\notepad.exe, C:\Windows\System32\notepad.exe, and C:\Windows\SySWOW64\notepad.exe
3) create symlinks
```
mklink C:\Windows\notepad.exe "C:\Program Files\Notepad++\notepad++.exe"
mklink C:\Windows\System32\notepad.exe "C:\Program Files\Notepad++\notepad++.exe"
mklink C:\Windows\SySWOW64\notepad.exe "C:\Program Files\Notepad++\notepad++.exe"
```
4) install Notepad Replacer
