### ISSUE TITLE
Error uninstalling v8.5.1 under Win10 22H2

### ISSUE THREAD

**Issue by ChrisPS5** [notepad-plus-plus/notepad-plus-plus#13440] opened 2023-03-29 12:18 UTC
When uninstalling v8.5.1 under Win10 22H2 the following error message comes up:
![error](https://user-images.githubusercontent.com/111854279/228532321-8c7cc6a1-fbb7-4b99-9d19-157c4186321b.jpg)

And the file "NppModernShell.dll" is indeed mssing in the folder:
![folder](https://user-images.githubusercontent.com/111854279/228532720-2984fdd6-7617-4d69-94ff-1b3e5d3c9da2.jpg)

**Comment by bshiznit** [comment] 2023-03-30 14:50
Second this:
![image](https://user-images.githubusercontent.com/10135006/228875844-c08dc21b-48b3-48d1-9df4-ac4eb4f26409.png)

My concern being more for when the 8.5.2 update drops and tries to overwrite this file - will we get this error? I suspect so unless it can be silenced somehow

**Comment by bshiznit** [comment] 2023-03-30 14:54
I can see @GurliGebis already has some stuff in-work regarding this:
https://github.com/notepad-plus-plus/notepad-plus-plus/compare/33e8d0ca4a12484b16afad70c133e9b4af66ec53..9ebd7c5ac388763608e6b38eefae578744a3a191

We shall see how it shakes out. @GurliGebis I wonder if there is also a rundll32 parameter to silence any wayward prompts? I will report back if I find something...

**Comment by GurliGebis** [comment] 2023-03-30 15:56
@donho I saw this one myself.
It is a bug in 8.5.1, but the cleanup we do in 8.5.2 fixes it all.
So the solution is just upgrading to 8.5.2 (with my changes from TEST9), then uninstalling works cleanly 🙂

**Comment by bshiznit** [comment] 2023-03-30 16:20
> @donho I saw this one myself. It is a bug in 8.5.1, but the cleanup we do in 8.5.2 fixes it all. So the solution is just upgrading to 8.5.2 (with my changes from TEST9), then uninstalling works cleanly 🙂

Many thanks to both of you!

**Comment by donho** [comment] 2023-03-30 19:14
@GurliGebis 
> It is a bug in 8.5.1, but the cleanup we do in 8.5.2 fixes it all.
> So the solution is just upgrading to 8.5.2 (with my changes from TEST9), then uninstalling works cleanly

v8.5.2 is not planed to include the [newest nppShell](https://github.com/notepad-plus-plus/nppShell/) because of the [regression ](https://github.com/notepad-plus-plus/nppShell/issues/2) in the new version.

**Comment by GurliGebis** [comment] 2023-03-30 19:39
@donho I have found the issue, it is mentioned here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13411#issuecomment-1490584552

**Comment by GurliGebis** [comment] 2023-03-30 19:41
long story short, the uninstall of the old dll has to happen before we install the new dll 🙂

**Comment by GurliGebis** [comment] 2023-03-30 19:50
@donho, No, my bad - that issue is already fixed in TEST9 - I'm going to suggest it to him to test.

**Comment by donho** [comment] 2023-03-30 19:53
@GurliGebis 
> long story short, the uninstall of the old dll has to happen before we install the new dll 🙂

Yes, I'm aware of this part. But old dll should be uninstalled anyway.
The problem is, the registration of old dll makes appear the context menu immediately, whereas the new dll needs to restart Explorer (which is a hack) or restart Windows.

It's event not OK for Windows 11 because some (a lot of ?) people still use the transitional context menu, but when they upgrade to a new version, the context menu is gone (only for the current windows session - but still, people don't restart their PC nowadays).

**Comment by GurliGebis** [comment] 2023-03-30 20:37
@donho it should hopefully be fixed with the installer does it in the right order

**Comment by GurliGebis** [comment] 2023-03-30 23:10
@donho only if the old dll has been unregistered as part of the installation.
See my comment here: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/13448#issuecomment-1491073098
If it is a clean install, it works fine, since the old dll isn't loaded into Explorer.
The problem comes up when the old dll is unloaded (which Explorer really doesn't like) and the new dll is loaded (Unloading a DLL from Explorer (which is really not supported), causes the context menu to not update, so it never notices the changes).

**Comment by donho** [comment] 2023-03-31 00:21
> If it is a clean install, it works fine, since the old dll isn't loaded into Explorer.


A lot of people install new version over on old version, and I'm not even talking about triggering auto-updater - it would be tens of thousands if it's not millions PC involved. 

So clean install working fine is good, but not good enough.

**Comment by GurliGebis** [comment] 2023-04-01 18:10
@donho since this has been fixed in the TEST versions, should we close this issue?

**Closed** 2023-04-01 23:48 UTC
