### ISSUE TITLE
When you change the styles of the program there is a long saving and hanging

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#10678] opened 2021-10-16 16:31 UTC
Notepad++ v8.1.7   (32-bit)
Build time : Oct 15 2021 - 01:17:20
Path : E:\Users\Uzzer\Desktop\allTools\Редакторы\Текст\Notepad++\npp.8.1.7x32\notepad++.exe
Command Line : -noPlugin
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1251
Plugins : none

https://user-images.githubusercontent.com/3471892/137594939-1ad39fe4-665b-4414-a627-000d1a0e853b.mp4

**Comment by Yaron10** [comment] 2021-10-16 22:31
Unfortunately, I've still not been able to pinpoint the exact STR.
But it seems to be more frequent when Firefox and NPP have been open for a while (~ an hour), and then closing both programs one after the other (Firefox and then NPP).

**Comment by andrecool-68** [comment] 2021-10-17 03:48
@Yaron10 I use Chromium and I don't have Firefox installed.

**Comment by Yaron10** [comment] 2021-10-17 10:40
@andrecool-68,

I didn't think that Firefox in particular was the culprit.
I thought the system was slightly busier after closing one program, and therefore the NPP problem occurred more frequently.

Thank you.

**Comment by andrecool-68** [comment] 2021-10-17 16:52
@Yaron10 Browser and Windows have nothing to do with it at all

**Comment by Yaron10** [comment] 2021-10-17 18:21
@andrecool-68,

I was just sharing the results on my machine in case someone would want to reproduce it.

**Comment by Yaron10** [comment] 2021-10-17 18:43
Yes, the saving method has been changed. The new one fixes some old bugs.
It's above my level, but this issue might be caused by the `tinyxml` modifications (since there's no problem with saving files opened in NPP).

**Closed** 2021-10-19 13:39 UTC
Labels: accepted
