### ISSUE TITLE
A suggestion for nopepad++

### ISSUE THREAD

**Issue by yunfan188** [notepad-plus-plus/notepad-plus-plus#6077] opened 2019-08-20 03:07 UTC
I hope to support go language sytax.

**Comment by ArkadiuszMichalski** [comment] 2020-09-20 12:47
@donho @sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8090, maybe close this because of the short description and leaving only the newer one.

**Closed** 2020-09-20 14:39 UTC
