### ISSUE TITLE
Find and replace dialog breaks with large strings

### ISSUE THREAD

**Issue by badon** [notepad-plus-plus/notepad-plus-plus#1270] opened 2015-12-19 00:32 UTC
The Find and replace dialog consistently fails to work when using large strings. I tried a string with over 6300 characters, and it will not even display in the "Replace with:" field. The string is large, but not crazy-large. In other words, normal strings do not work properly. In some cases, the replace operation succeeds, but the string is truncated without warning. If there are size limits, the user should be warned that the replace operation will fail instead of failing silently.

**Comment by linquize** [comment] 2015-12-19 14:13
I tested that the max limit is 5459 in Find Combo box
I use Notepad++ v6.8.7

**Comment by badon** [comment] 2015-12-20 02:09
Thanks for that test, linquize. I just tested the find-and-replace dialog, and my replace is cut-off at 2046 characters, so only about a third of what I needed to replace was actually replaced. I'm using NPP 6.8.6 in the PortableApps Suite.

**Comment by MetaChuh** [comment] 2019-04-13 02:08
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:08 UTC
