### ISSUE TITLE
Hiding contents of a statement, then deleting it causes text to act wonky.

### ISSUE THREAD

**Issue by dabigf5** [notepad-plus-plus/notepad-plus-plus#11246] opened 2022-02-20 10:26 UTC
### Description of the Issue
Whenever I add an if-statement (or any statement that starts and ends like for-loop), hide it, then delete the text that's still there, the document starts acting quite buggy around the area I deleted.

### Steps to Reproduce the Issue

1. Set language to any programming language with an if statement. Works with any statement that starts and ends, like a for-loop or while-loop. For my example I'll be using Lua.

2. Type in something like:
```lua

if true then

end

```
(add an extra line at start and end)

3. Click on the button that appears next to it, which then hides it.
4. Select the text that's still there and delete it. This causes the text to act quite weird, and line numbers to become incorrect.

### Expected Behavior
Line numbers to fix themselves when deleting the text that's still there after hiding contents of statement

### Actual Behavior
Line numbers are incorrect, backspacing into the removed line somehow hides the text cursor.

### Debug Information
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll 

### Some screenshots I took
Normal
![image](https://user-images.githubusercontent.com/50565510/154837969-1a71a93b-5346-4a3d-83e9-ce62df7bc711.png)
After pressing the button, still correct
![image](https://user-images.githubusercontent.com/50565510/154837994-4a3d9248-7b72-4a40-bdbd-ff0a06762014.png)
Deleting it
![image](https://user-images.githubusercontent.com/50565510/154838007-c62d4794-5145-4d1b-81bf-1c2995f30916.png)
What happens when adding a new line
![image](https://user-images.githubusercontent.com/50565510/154838026-440eac62-0ac2-473f-ac75-a7eac868fe8d.png)
After backspacing on the line below the glitchy one, it makes the text cursor disappear.
![image](https://user-images.githubusercontent.com/50565510/154838065-9f2a3524-016b-4de1-9a3d-f97e411a523c.png)

**Comment by thomassmith311** [comment] 2022-02-21 19:22
Duplicated on Windows 11, 64-bit, 8.3.1. Ctrl+A and backspace removes even line numbers.

https://user-images.githubusercontent.com/19561856/155015360-acbdffe5-75f6-4ef9-952d-e386b07e521e.mp4

**Comment by xomx** [comment] 2022-02-23 19:15
First thanks for finding this problem. It can even lead to an assert/crash ("Assertion [model.pcs->GetVisible(lineDoc)] failed at .\notepad-plus-plus\scintilla\src\marginview.cxx 265") under some circumstances.

Now this issue has two parts:

1)
There is a N++ problem (I have found a solution and I am going to do a PR for it - it will solve the most critical parts of this issue, e.g. no more crashing, no hidden cursor or lines, etc... )
- probably a longer time ago, Scintilla team had similar problems, they solved it by unfolding the relevant lines first before modifying the content on that lines, e.g. see [here](https://sourceforge.net/p/scintilla/bugs/1796/) or [here](https://sourceforge.net/p/scintilla/bugs/1896/)
- anyway, maybe from that fixes arisen the Scintilla flag `SC_AUTOMATICFOLD_CHANGE`, but N++ probably has not been aware of it
- when I applied the above flag, most of the problems in this issue are fixed, but not the one described below (that one will probably need to create a Scintilla [bug-ticket](https://sourceforge.net/p/scintilla/bugs/))

2)
The Scintilla/SciTe has its own problem, which probably needs to be fixed at their side.
- dl (& rename back to "test1.lua") this test-file: [test1.lua.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8126956/test1.lua.txt)
- dl the current N++ [equivalent SciTe](https://sourceforge.net/projects/scintilla/files/SciTE/4.4.6/Sc446.exe/download) (or a [latest one](https://www.scintilla.org/Sc520.exe), the problem is the same)
- run the SciTe, check in the menu -> View -> 'Line Numbers', open the "test1.lua"
![SciTe-test1-unfolded](https://user-images.githubusercontent.com/13075183/155388812-d11a9b74-fc27-42bd-860c-dbdb6a9ef382.png)
- fold (click at the folder margin - line No. 2)
![SciTe-test1-folded](https://user-images.githubusercontent.com/13075183/155389065-f1e4f96f-140c-4417-9cde-1375be3d539c.png)
- select and delete the whole line No. 2 content, there will be this error-result after:
![SciTe-test1-deleted-error](https://user-images.githubusercontent.com/13075183/155389416-a7b5d467-f255-4919-90fa-01d146d175e8.png)

**Comment by xomx** [comment] 2022-02-23 21:41
@donho 

If the PR will be accepted, the most critical parts of this issue will be fixed.
But some invalid behavior remains (see my point No.2 above - this is a Scintilla issue, not a N++ one).

**Comment by donho** [comment] 2022-03-01 23:44
> Maybe the No.2 is their desired behavior (deleting only the content on that fold-head-line, then unfolding the rest for further deleting...).

@xomx
Yes, it looks a desired behaviour to me. At least it's what I expect.

**Closed** 2022-03-01 23:55 UTC
Labels: bug, accepted
