### ISSUE TITLE
The Windows dialog (Window menu, Windows) doesn't remember the size of the Name column

### ISSUE THREAD

**Issue by BobBob9999** [notepad-plus-plus/notepad-plus-plus#8852] opened 2020-09-12 03:14 UTC
### Description of the Issue
I have files with somewhat long filenames.  When using the Windows dialog box, while it remembers the size of the entire box if I resize it, it doesn't remember the size of the Name column (all extra horizontal size gets allocated to the Path column).  As a result, every time I want to change to a file in this list with a longer name (and my project has lots of files that are grouped by having similar name prefixes), I have to resize this column first. 

### Steps to Reproduce the Issue
1. Click the Window menu, then Windows
2. Resize the Name column so that I can see the full name of the longer-named files
3. Click Ok
4. Repeat for every time you want to choose a different file.

### Expected Behavior
Clicking Ok in the Window dialog saves not only the size of the window, but also the size of the columns, particularly the Name column.

### Actual Behavior
Only the Window dialog size is remembered.

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2004
OS Build : 19041.508
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll SpellChecker.dll

**Comment by ArkadiuszMichalski** [comment] 2020-09-17 16:00
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8602, on of them can be close.

**Comment by sasumner** [comment] 2020-09-17 17:30
Closing this one in favor of the earlier 8602

**Closed by sasumner** 2020-09-17 17:30 UTC
