### ISSUE TITLE
Are gcc debug builds and PluginAdmin incompatible?

### ISSUE THREAD

**Issue by Ekopalypse** [notepad-plus-plus/notepad-plus-plus#11687] opened 2022-05-17 13:56 UTC
The use of a gcc debug build does not seem to be recognised by the plugin admin.
Can this be changed?
More detailed information about the problem has been posted as an [issue](https://github.com/notepad-plus-plus/nppPluginList/issues/454) in the nppPluginList repo.

If this issue makes no sense or is invalid, please feel free to close it.
Thank you.

**Comment by rdipardo** [comment] 2022-05-19 01:02
That you even got a GCC build to load Plugins Admin is an improvement on #10185.
 
> Neither toolbar nor Plugin Admin to be seen. [ . . . ]
> I even tried downloading the “Plugin Manager” plugin manually also with no success — it just doesn't show up anywhere.

Otherwise, I would close this as a duplicate of #10185 and (more tangentially) #9163.

As discussed in the [linked issue], the real problem is that no DEBUG compiler def is passed to GCC by [the makefile][1], so JSON loading is disabled in the [Plugins Admin module][3]. When the def *is* passed, GCC [fails to compile the module][2]. The git history does not suggest the DEBUG def was suppressed on purpose; it was just [added that way][0], and nobody noticed until now.

[0]: https://github.com/chcg/notepad-plus-plus/commit/f428fbab13c6bbea673b57457b35d9a4a9aa1f09#diff-81078873c7192ded6b5a93da2d62b0e6f86a5516905529f465fa5b7c33bb2df4R47
[1]: https://github.com/chcg/notepad-plus-plus/blob/master/PowerEditor/gcc/makefile#L63
[linked issue]: https://github.com/notepad-plus-plus/nppPluginList/issues/454
[2]: https://github.com/notepad-plus-plus/nppPluginList/issues/454#issuecomment-1130670309
[3]: https://github.com/chcg/notepad-plus-plus/blob/a577564699c993508d959304730e334fbc83d208/PowerEditor/src/WinControls/PluginsAdmin/pluginsAdmin.cpp#L706-L711

**Comment by Ekopalypse** [comment] 2022-05-19 07:05
Has been fixed, details in linked issue - thank you very much.

**Comment by Ekopalypse** [comment] 2022-05-19 07:10
Since the other issues mentioned are already closed, I am reopening this one so that a needed PR can link to an issue.

**Closed** 2022-05-25 16:37 UTC
Labels: build / code
