### ISSUE TITLE
Keyboard shortcut for "Open Containing Folder in Explorer" is partially broken

### ISSUE THREAD

**Issue by GrumpyCamel** [notepad-plus-plus/notepad-plus-plus#7895] opened 2020-01-27 20:55 UTC
### Description of the Issue
When setting ALT+ENTER as a shortcut for "Open Containing Folder in Explorer" it seems to only work correctly when the caret is on an empty line or not surrounded by text characters. If there is so much as a single character touching either side of the caret when the combination ALT+ENTER is pressed then the shortcut breaks.

### Steps to Reproduce the Issue
IIRC, there are no keys mapped as a shortcut for "Open Containing Folder in Explorer" by default so steps 1-4 are instructions on creating this mapping.
1. From the toolbar, go to Settings > Shortcut mapper.
2. Scroll to "Open Containing Folder in Explorer" (row 78).
3. Click Modify and set ALT+ENTER as the shortcut.
4. Ok > Close.
5. Type "foo bar" into the editor (we'll call this line 1), followed by a new line (line 2).
6. Save this file somewhere on your machine.
7. Try placing the caret anywhere on line 1 then try the shortcut ALT+ENTER (does not work).
8. Place the caret on line 2 then try again (works).

### Expected Behavior
An instance of Windows Explorer should open at the directory where the file was saved from step 6.

### Actual Behavior
An instance of Windows Explorer opens at the top "This PC" level.

### Additional Notes
- The shortcut seems to work when the caret is surrounded by space characters.
- When the caret is touching a character/word, ALT+ENTER results in said character/word to be highlighted. I'm guessing some wires got crossed somewhere.

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppJumpList.dll PluginManager.dll PreviewHTML.dll ScrollPastEOFUni.dll XMLTools.dll

**Comment by sasumner** [comment] 2020-01-27 21:31
I don't think it matters that it is tied to a keycombo at all.  Invoking the *Edit* menu's *On Selection* equivalent command, it acts the same way.  The "on selection" part may give us a clue...

I think it is trying to open what it expects to see as a textual path at the caret.  In my experimentation, if I have a valid pathname at the caret, it will select only a part (odd) of the path, then it will open a not-totally unexpected thing (based upon that textual path) in Explorer.

Invoking what one would think is the same exact command via a tab's right-click menu option, however, yields different, and totally expected results, with no text being automatically selected around the caret.

If you have a file pathname in text in the file and you select that in its entirety before running the command from the *Edit* menu, it seems you get totally predicted results (Explorer opens the the containing folder of that text pathname).

**Comment by ranjwarrior** [comment] 2020-02-15 01:29
Hoping this pull request fixes this issue - https://github.com/notepad-plus-plus/notepad-plus-plus/pull/7947

**Comment by donho** [comment] 2020-02-22 11:56
> 2. Scroll to "Open Containing Folder in Explorer" (row 78).

In my case (v7.8.2) it's "Explorer" (row 3).
After adding shortcut "Alt+ENTER", I tested 2 cases you mentioned above, everything works as expected and I cannot reproduce what you described.
I notice that you've got a older version (7.2.2), could you update your Notepad++ to the latest version, then test it again?

**Comment by donho** [comment] 2020-02-22 12:02
@GrumpyCamel 
I will close this issue.
Please recreate a new one if you can reproduce it in the v7.8.4.

Thank you

**Closed by donho** 2020-02-22 12:02 UTC
Labels: not reproducible

**Comment by sasumner** [comment] 2020-02-23 02:19
I think the difficulty for @GrumpyCamel is with the naming in Shortcut Mapper.

The naming for "Explorer" is the way it is because it is the ending part of this submenu cascade:

`File` > `Open Containing Folder` > **Explorer**

Because of this submenuing, only `Explorer` shows in Shortcut Mapper, not `Open Containing Folder in Explorer`.

So, @GrumpyCamel did not recognize this as what he wanted, but saw the Edit menu's version because its shortcut mapper text was exactly what was wanted:

`Edit` > `On Selection` > **Open Containing Folder in Explorer**

But what @GrumpyCamel didn't realize is that this command attempts to do something using the current selection due to the "On Selection" part.  If there is a selection of zero length, then the current word at the caret is used.  This is not right for the user's intent, but it is user's error for using the wrong command.

BTW, while looking into this I found that the File menu's version of the command can be looked up via the tag `IDM_FILE_OPEN_FOLDER` and the Edit menu's command via the tag `IDM_EDIT_OPENINFOLDER`.

**Comment by ranjwarrior** [comment] 2020-02-23 02:37
Sorry, am new here, so looked only at the master branch for the issue, didn't realize was fixed in the newer code base (Tag 7.8.4). Will re-test the open folder for selected file and also the open file (if a valid filename) where the caret is currently on with the latest release...

**Comment by sasumner** [comment] 2020-02-23 11:27
@ranjwarrior said:

>didn't realize was fixed in the newer code base 

Nothing was fixed.  Nothing was broken.  The issue was reported based upon a user misunderstanding of which shortcut to map (see my previous explanation).

**Comment by ranjwarrior** [comment] 2020-02-23 22:40
Ok, got it.
