### ISSUE TITLE
Problem with Toolbar

### ISSUE THREAD

**Issue by VFederau** [notepad-plus-plus/notepad-plus-plus#11359] opened 2022-03-09 10:53 UTC
### Description of the Issue
After Switching in Option to "Dark Mode" he changes the icon at the toolbar. When you disable later the "Dark Mode" he switches everything to normal - except for the Toolbar Icons.

### Steps to Reproduce the Issue
1. Click to Options
2. Enable the "Dark Mode" 
3. Disable the "Dark Mode"

### Expected Behavior
After deactive the "Dark Mode" i would see the normal icons - not the "Dark Mode" Icons any more.

### Actual Behavior
After Switching in Option to "Dark Mode" he changes the icon at the toolbar. When you disable later the "Dark Mode" he switches everything to normal - except for the Toolbar Icons.

### Debug Information
Notepad++ v8.2.1   (32-bit)
Build time : Jan 19 2022 - 18:38:49
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.1526
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![BugNotepadPlusPlus](https://user-images.githubusercontent.com/10497094/157427709-d7ef1d0d-8ef4-4473-b28d-a812259598e1.PNG)

**Comment by VFederau** [comment] 2022-03-09 11:23
Found a workaround - he Switches in "Dark Mode" the Toolbar to "Fluent UI: little symbols". Here in the Menu (unter Options the first point in the list) you can change it back to "little default symbols" (last entry in list).
![NppWorkaround](https://user-images.githubusercontent.com/10497094/157432195-ae19a60c-3ac8-44fa-a7d2-32c339dc1eb6.png)

**Comment by ArkadiuszMichalski** [comment] 2022-04-04 11:52
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10544.

**Closed by ArkadiuszMichalski** 2022-04-04 11:52 UTC
Labels: dark mode
