### ISSUE TITLE
[BUG] Opening a collection of files that includes a folder, errors on the folder with message "{foldername}" doesn't exist. Create it?

### ISSUE THREAD

**Issue by MarkCranness** [notepad-plus-plus/notepad-plus-plus#15672] opened 2024-10-04 03:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

Opening a collection of files that includes a folder, errors on the folder with message "{foldername}" doesn't exist. Create it?
(The "Yes No" message box is titled "Create new file".)

### Steps To Reproduce

1.  Have editable files like so:
File1.txt
Folder\File2.txt
Folder\File3.txt

2. In Windows Explorer, Ctrl+A select File1.txt and the Folder folder. Right click: "Edit with Notepad++"

3.  File1.txt opens, and observe error message as above.

4. This used to work in a recent previous version of Notepad++, and would open File2.txt and File3.txt in the folder, opening 3 files in total.

### Current Behavior

File1.txt is opened, but File2.txt and File3.txt are not opened, and Notepad++ displays an error message:
---------------------------
Create new file
---------------------------
"{folder name}" doesn't exist. Create it?
---------------------------
Yes   No   
---------------------------

If I choose No, then nothing further happens. If I choose Yes, then a further error occurs:
"Cannot create the file "{folder name}"

### Expected Behavior

File1.txt, File2.txt & File3.txt should be opened in Notepad++

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "F:\Migrations\{redacted}\!Configs (V4.2.0, copy over client name folder)\connection.config" "F:\Migrations\{redacted}\!Configs (V4.2.0, copy over client name folder)\dbimport" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : OFF
OS Name : Windows Server 2022 Standard (64-bit)
OS Version : 21H2
OS Build : 20348.2700
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

**Comment by xomx** [comment] 2024-10-04 10:33
Duplicate of #15666 & #15645.
Please close this issue.

**Closed** 2024-10-05 02:15 UTC
Labels: duplicate
