### ISSUE TITLE
Alt+<letter> hotkeys are missing when exiting or closing a modified document

### ISSUE THREAD

**Issue by silvaran** [notepad-plus-plus/notepad-plus-plus#7612] opened 2019-11-18 16:58 UTC
### Description of the Issue
I can no longer hit Alt+N on Windows to discard changes when closing a modified document.

### Steps to Reproduce the Issue

1. Start a new document
2. Type some content
3. Close the document (Alt+W or click the [x] icon)
4. Hit Alt+N to say "No" to the "Save [Yes] [No] [Cancel] [Yes to all] [No to all]" confirmation dialog.

### Expected Behavior
Alt+N should select the "No" button.

### Actual Behavior
Nothing happens; it doesn't look like there is an Alt+ shortcut in the dialog button resource anymore.

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise N (64-bit) 
OS Version : 1903
OS Build : 18362.476
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2019-11-18 18:18
Closing as duplicate of #6223

**Closed by sasumner** 2019-11-18 18:18 UTC
