### ISSUE TITLE
Auto-Completion of "html/xml close tag" does not work for e.g. normal text documents

### ISSUE THREAD

**Issue by Ede123** [notepad-plus-plus/notepad-plus-plus#1177] opened 2015-11-24 20:52 UTC
There seem to be at least three distinct cases (depending on document type) that show different (and often erratic) behavior depending on the setting of `Settings -> Preferences -> Auto-Completion -> html/xml close tag`
<s>
- **XML** documents (choose `Language -> XML`)
  - with _"html/xml close tag" enabled_ type `<test>`<br>
    The result is `<test></test></test>` which is **obviously wrong**, the closing tag is inserted twice
  - with _"html/xml close tag" disabled_ type `<test>`<br>
    The result is `<test></test>` which is correct but **does not reflect the setting** - there's obviously a second code path the auto-completes tags for XML documents exclusively but is redundant to the the setting's functionality
    </s>
- **HTML** documents (choose `Language -> HTML`)
  - with _"html/xml close tag" enabled_ type `<test>`<br>
    The result is `<test></test>` which is **correct**
  - with _"html/xml close tag" disabled_ type `<test>`<br>
    The result is `<test>` which is **correct**
- **Text documents** (choose `Language -> Normal Text`)
  - with _"html/xml close tag" enabled_ type `<test>`<br>
    The result is simply `<test>` which is not wrong but **does not reflect the setting**  and could be improved to being automatically closed (as for example braces/quotes are when the relevant setting is enabled)
  - with _"html/xml close tag" disabled_ type `<test>`<br>
    The result is `<test>` which is **correct**

Sorry, forgot to mention:
This was tested in Notepad++ 6.8.6 on Windows 7
Just to be sure I also deleted all my user settings once before performing the tests, but the results were the same.

**Comment by dail8859** [comment] 2015-11-24 20:54
What version are you using?

**Comment by Ede123** [comment] 2015-11-24 20:56
OK, I think I know the culprit: The plugin "XML Tools". Let me verify by disabling...

**Comment by Ede123** [comment] 2015-11-24 21:03
Indeed, at one point in the past (when there wasn't auto-completion for XML-tags available in Notepad++ natively yet) I had enabled the option *"Tag auto-close* in "XML tools". This messed up the test results for XML files.

Therefore the only open question is if we want to auto-close tags also for non-XML/HTML files (the "Text documents" example with "html/xml close tag" enabled in the initial comment).
Apart from that question this issue is resolved.

**Comment by dail8859** [comment] 2015-11-24 21:09
According to [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/986492e47b6a13a9b55f59e9327a880dc45574d3/PowerEditor/src/ScitillaComponent/AutoCompletion.cpp#L616) section of code it *should* only be doing it for HTML and XML.

**Comment by Ede123** [comment] 2015-11-24 21:16
Yes, I assumed so, but it could be useful for any document to autoclose HTML tags e.g. for writing Markdown (GitHub actually supports <b>bolding</b> text wit `<b>` tags as an example)

On the other hand it's surely not necessary, I just think we auto-complete all the other stuff in all document types - why not also the HTML/XML tags?
It would be more consistent and therefore would probably better match user expectations

**Comment by MetaChuh** [comment] 2019-04-13 02:17
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:17 UTC
