### ISSUE TITLE
'dead' areas in GUI around the editor

### ISSUE THREAD

**Issue by jjj42** [notepad-plus-plus/notepad-plus-plus#11978] opened 2022-08-03 13:34 UTC
### Description of the Issue

when opening my (old) notepad++ installation, suddenly there are areas around the editor, that seemingly supposed to show gui widgets, but are empty.  Some can be closed with their corrisponding x icons, others don´t show these.
![notepad++_3Mi8Uw9nBc](https://user-images.githubusercontent.com/10906589/182618187-9ac78692-eff1-41ea-800a-7ca0b43a81c6.jpg)

already fiddled with the configuration:
1.1.) renamed one configuration .xml file after the other, started notepad++. always showed up same error.
1.2.) renamed configuration file back its original name. 
1.3.) renamed next one...

2.1.) renamed whole configuration folder.
2.2.) new got created at startup
2.3.) showed same error
2.4.) replaced new configuration folder with old one

3.1.) installed older 'unhappy users edition' 8.4.3
3.2.) same error
3.3.) felt unhappy, so it felt kind of right
3.4.) installed 8.4.4, happy users edition, again.
3.5.) same error
3.6.) still feelin unhappy

-> is it my own fault?
seems my unhappy 'negative refund' actually paid off ... 
https://community.notepad-plus-plus.org/topic/23214/regarding-notepad-v8-4-3-unhappy-users-edition/4

### Steps to Reproduce the Issue
1. start np++

### Expected Behavior
not showing unused, empty gui elements

### Actual Behavior
gui is shown damaged

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 21H2
OS Build : 22000.795
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by alankilborn** [comment] 2022-08-03 13:40
See https://community.notepad-plus-plus.org/topic/21895/faq-desk-huge-gaps-blank-areas-in-the-ui-borders/1

>-> is it my own fault?
seems my unhappy 'negative refund' actually paid off ...

LOL

**Comment by jjj42** [comment] 2022-08-03 13:48
... and it crashes without comment, when clicking & fiddling with empty boxes titles.

Just kind of 'fixed' (most of) it:

When the left box is closed, the editor frame still has the padding to the window border, but can be dragged to the left window edge, so the dead area is eliminated.
The right box can´t be closed, because it does not show an x-icon. Still the editor area can be resized to the window edge by dragging it´s right border.
Same with bottom one, but...
when doing it to that one on top, the bottom-one shows up again and can´t be closed.
So now there´s just one left.

Stays like this on restart too. 

Not the worst.

**Comment by ArkadiuszMichalski** [comment] 2022-08-03 23:12
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed by ArkadiuszMichalski** 2022-08-03 23:12 UTC

**Comment by jjj42** [comment] 2022-08-04 19:19
seems it was an issue of the windows explorer. 
letting the system run for some more hours, other programs started getting gui errors, too.
a restart cured the error.
