### ISSUE TITLE
Notepad++ hangs when network files are unreachable

### ISSUE THREAD

**Issue by pudrik** [notepad-plus-plus/notepad-plus-plus#12553] opened 2022-11-22 15:57 UTC
### Description of the Issue
If you have a networked file open and you close notepad++, then disconnect the resource of the file notepad++ will crash in an infinity loop when you try to open the program. (White screen)

### Steps to Reproduce the Issue
1. Open for instance a smb networked file
2. Close notepad++
3. disconnect the smb resource
4. open notepad++

### Expected Behavior
Should open normaly and maybe give a message saying the files cant be reached and if it should discard them 

### Actual Behavior
Program hangs with white screen, never reached a timeout.

### Debug Information
not possible.

**Comment by osnofa** [comment] 2023-01-17 18:46
Having a problem with that as well, but its also when closing notepad++ with a networked file open.

### Steps to reproduce:
1. Open a file over the network
2. Open a file locally (and don't change back to the tab where the networked file is)
3. Shut down the computer where the file is hosted
4. Try closing notepad++ (it then crashes)

**Comment by pudrik** [comment] 2023-04-05 08:45
I can confirm the same issue on close if server is disconnected.

**Comment by schmurtzm** [comment] 2023-10-04 00:35
I confirm too, this is really annoying for editing files on SMB shares. It totally freeze, it seems that there is a timeout but it's very long !

**Comment by schmurtzm** [comment] 2023-10-04 14:22
On my side the problem is more when you go back to Notepad++ UI (I suppose that it checks if the file has changed).
30 seconds of freeze stills a lot too long when all the the other tabs are freezed too 😅
To reproduce : open 5 SMB files disconnect network share then go back to Notepad++ and you will freeze.
On vscode there is no freeze : a little toaster warn that the save cannot be done when you press ctrl+s.

**Comment by pudrik** [comment] 2023-10-04 14:33
@xomx the problem is easy to reproduce open a networked document (doesnt matter which one) close notepad++ disconnect from the network by plugging the cable / or disable wifi. Open notepad++ it should appear like it hung.

**Comment by xomx** [comment] 2023-10-04 18:50
As I said above - I got such delays/hungs during my tests too, but what I tried to say:
- this is not a CRASH (as the name of this issue says...), I have been able to always continue after that annoying delay
- this delay not inherently originates from the N++, this is how the OS handles such network resources sudden unavailability (maybe that 30 secs can be changed to a lower value somewhere in the Windows OS settings, IDK)

> On vscode there is no freeze : a little toaster warn that the save cannot be done when you press ctrl+s.

If your objections are only against the N++ UI responsibility in such cases - yes, theoretically you can rewrite the file checking part to some multi-threaded variant, but IMO - this will never happen.  (Even if I try to create such PR, most probably it will not be accepted because of this will bring an excessive increase in the N++ code complexity together with increased susceptibility to errors incoming from the possible race conditions etc...)

Or do you know what the vscode solution in such situation looks like (in its source code, not only visually)?
(If it is something relatively easy, maybe it would be worth thinking about such implementation here too.)

Possible workaround:
If you are often exposed to such annoying-delay situations, I recommend switching OFF this option in the N++ Preferences (if acceptable to your situation, of course):

![npp--Preferences-disable_file_checking](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/03a2da40-1050-4d2b-93d7-f6bab852f195)

**Comment by pudrik** [comment] 2023-10-05 06:09
@xomx youre are correct its not a crash and yes its a os thing, but that being said N++ should have an overriding handler for file operations with a reasonable timeout. 

the OS doesnt make it recover after 30s maybe thats how long it takes if the file becomes available.

i have no idea how vscode handles the same problem but considering it crashes all the time due to memory leaks i would say its the least of their problems, unlike N++ which i find as an almost perfect program.

i will try the workaround. Thank you.

**Comment by osnofa** [comment] 2023-10-12 10:31
Is it possible to have a property to disable file status auto-detection just for remote files?

**Comment by XK9274** [comment] 2023-12-11 23:48
Confirmed, I have this issue on 8.6 when network shares drop off - can be very frustrating. A shorter/customisable timeout would be great.

**Comment by schmurtzm** [comment] 2024-01-08 23:28
This notepad++ bug even impacts explorer.exe. Meny times when Notepad++ is trying to refresh a file explorer doesn't answer anymore. File status Auto-detection is a major functionality of Notepad++ we can't imagine to disable it.
Auto-detection feature is for sure responsible of most of this problem. So it could be great to be able to disable it just for UNC paths may be. Or for the UNC path only avoid to try to refresh other tabs than the current one , with a reasonable delay of 10 or 15 seconds.

**Comment by xomx** [comment] 2024-01-12 11:01
Workaround2 (try in cmd-window with admin-rights):

`netsh interface tcp set global initialRto=300`

This sets the Windows initial timeout (in milisecs) for any new TCP/IP connection (effective immediately, no restarting needed). The default value is 3000, the 300 is the minimum. This value is doubled with each subsequent retry, so with typical 2 retries and the default value it takes 3+6+12 = 21 secs before a connection attempt definitely fails. (Beware - setting this to the 300 msecs minimum may cause connection failures on slow networks.)

For the SMB mapped drives there is the Registry `SessTimeout` DWORD value to manipulate with in `\HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters\`.

**Comment by xomx** [comment] 2024-08-09 10:03
@nil-ref 
> [rizonesoft/Notepad3#5050 (comment)](https://github.com/rizonesoft/Notepad3/issues/5050#issuecomment-1817720444)

That's true but one can use the cancellable WIN32 IO approach (at least I hope so). I have that [in progress](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8055#issuecomment-2209258194) for the N++ but no promises or ETA here.

**Comment by schmurtzm** [comment] 2024-08-10 09:53
It's a very good news because due to these hangs (which also impact other apps) I start to give up with notepad++ which is really a shame. So 🤞🏻

**Comment by donho** [comment] 2024-09-11 17:45
@schmurtzm @XK9274 @osnofa @pudrik 

This issue might be fixed in Notepad++ v8.7:
https://community.notepad-plus-plus.org/topic/26105/notepad-v8-7-release-candidate

Could you guys try v8.7 and confirm the bug is fixed?

**Comment by pudrik** [comment] 2024-09-13 11:45
@donho nope still not fixed.

**Comment by donho** [comment] 2024-09-13 12:19
@pudrik 
Thank you for your test.
We will see what we can do about it.

**Comment by osnofa** [comment] 2024-09-19 09:43
Just tried 8.7.

For the problem I mentioned, it first said it was not responding (for 5seconds, maybe?), but then it didn't crash.
It then said the file no longer existed and asked if I wanted to keep the file in the editor.

I also tried closing Notepad++ with the file in one of the tabs, and when reopening, the file was not there, so no problems with waiting for the application to respond.

For me it's fixed. Thank you.

**Comment by pudrik** [comment] 2024-09-19 10:18
@donho i stand corrected it takes maybe 60s then it just ignores the files which it cant access and closes them to make the software operational, however if you loose connection while software is open it asks if you want to keep the file or not but doesnt seem to store it localy when closing the software as its gone when you reopen the software. im using a \\server\path not a mapped drive.

**Comment by xomx** [comment] 2024-09-19 15:03
@osnofa 
> I also tried closing Notepad++ with the file in one of the tabs, and when reopening, the file was not there,

@pudrik 
> if you loose connection while software is open it asks if you want to keep the file or not but doesnt seem to store it localy when closing the software as its gone when you reopen the software

N++ does not work like the cloud SW (e.g. Google drive in offline mode), so it does not keep a local cache/copy of the network file opened in it (with one exception, which I will mention below).

You can use these N++ features here:
- N++ session placeholders for temporarily inaccessible files: https://npp-user-manual.org/docs/session/#inaccessible-files
  (for more details how it looks and behaves, look e.g. in the issue #15628 )
- use the N++ session snapshot & backup (Preferences > Backup > Enable session snapshot and periodic backup), but you have to always get your file dirty (edited in N++ somehow, even by adding and then removing back one char in the opened N++ file/tab...) before exiting the N++ app, because in that case the N++ will keep its own unsaved copy of your network file in its local backup folder...

**Comment by pudrik** [comment] 2024-09-20 07:21
@xomx \\server\mapping is a standard samba mapping with netbios names. you can manually mapp a drive or use direct share pointers like shown this only means mapping is a name of a shared folder on server. on all Windows systems you even have the built in admin mapping where all disks have a hitten mappen ie \\servver\c$ which allows full browsing but requires admin access. Anyway this behavior used to keep the file but now it discards the file. If you can solve that problem i think most people would see it as an ok compromise to wait 60s for a timeout.

**Comment by donho** [comment] 2024-09-20 14:51
I'm gonna fix it.
However, I've got no similar environment. I guess I should have a Linux VM with samba. Is there any way easier to reproduce the issue?

**Comment by donho** [comment] 2024-09-28 02:20
@schmurtzm @XK9274 @osnofa @pudrik
Please check the fix (x64):
https://github.com/notepad-plus-plus/notepad-plus-plus/actions/runs/11079115559/artifacts/1989748610

**Comment by donho** [comment] 2024-09-30 18:09
@pudrik 
> files that where networked on close where gone on reopen when no connection

It's the normal behaviour, since the original file cannot be opened.

**Closed** 2024-10-02 02:52 UTC

**Comment by pudrik** [comment] 2024-10-02 07:01
I can confirm that it hangs for maybe less then 10s and networked files that arent accessable show their last open copy.

Great job!
