### ISSUE TITLE
Bugged CSS Syntax highlighting

### ISSUE THREAD

**Issue by skaro41** [notepad-plus-plus/notepad-plus-plus#2485] opened 2016-10-26 15:53 UTC
### Description of the Issue
Bugged CSS Syntax highlighting

### Steps to Reproduce the Issue
@-webkit-keyframes show-logo {
	0% {
		opacity: 1;
	}
	75% {
		opacity: 0.8;
	}
	100% {
		opacity: 0;
	}
}
@keyframes show-logo {
	0% {
		opacity: 1;
	}
	75% {
		opacity: 0.8;
	}
	100% {
		opacity: 0;
	}
}

### Expected Behavior
proper syntax highlighting

### Actual Behavior
0% declaration is not highlighting

**Comment by MAPJe71** [comment] 2016-10-26 17:27
After fiddling around with the `Style Configurator` it appears that ...
- the first `TAG` (i.e. `0%`, SciTE's `style.css.1` a.k.a. "Selector (HTML tag)") is styled as an `UNKNOWN_IDENTIFIER` (i.e. SciTE's `style.css.7` a.k.a. "Unknown Property");
- the first `IDENTIFIER` (i.e. `opacity`, SciTE's `style.css.6` a.k.a. "CSS1 Property") is styled as an `OPERATOR` (i.e. SciTE's `style.css.5` a.k.a. "Operator").

I suspect the Scintilla CSS lexer is causing the problem.

![capture-2016-10-26-19 09 07](https://cloud.githubusercontent.com/assets/6494038/19736923/a96bd274-9bb1-11e6-9a48-ce3be8ac5b31.png)

**Comment by dail8859** [comment] 2016-10-26 17:56
Duplicate of #2292.

Yes this appears to be a Scintilla issue and needs reported to their sourceforge project.

**Closed** 2016-10-26 18:43 UTC
Labels: duplicate
