### ISSUE TITLE
Alt+N and Alt+Y accelerators no longer available when asked to save dirty file

### ISSUE THREAD

**Issue by fabioz** [notepad-plus-plus/notepad-plus-plus#7726] opened 2019-12-12 11:18 UTC
I just upgraded to `notepad 7.8.1`.

When closing a dirty file it seems it has a new dialog. Previously it was possible to close a dirty file and then use `Alt+N` to say that I didn't want to save the file and apparently this option is now gone (and `Alt+Y` which would save the file seems to have suffered the same fate).

### Debug Information
Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 1809
OS Build : 17763.914
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by bjxrn** [comment] 2019-12-12 12:49
Previously you could use just `Y` or `N`. They've stopped working too. 
This goes for the 32-bit version as well.

**Comment by sasumner** [comment] 2019-12-12 13:11
Closing as duplicate of #6223 

Try version 6.8.2 or apply manual fix to 6.8.1

**Closed by sasumner** 2019-12-12 13:11 UTC
