### ISSUE TITLE
'Open User Defined Language Folder...' does nothing

### ISSUE THREAD

**Issue by SenseiJoe** [notepad-plus-plus/notepad-plus-plus#11679] opened 2022-05-16 14:03 UTC
### Description of the Issue
Open User Defined Language Folder nothing happens.  

### Steps to Reproduce the Issue

1.  Select Language
2.  Select User Defined Language
3.  Click 'Open User Defined Language Folder...'

### Expected Behavior
I would expect explorer to open and be left in the correct location.

### Actual Behavior
Nothing

### Debug Information
Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\Program Files\notepad++\notepad++.exe
Command Line : deploy.ps1
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\sherwoodj\OneDrive - Unitil Service Corporation
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 1252
Plugins : MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll nppplugin_ofis2.dll NppSaveAsAdmin.dll PreviewHTML.dll

**Comment by WinterSilence** [comment] 2022-05-17 04:24
+1

**Comment by rddim** [comment] 2022-05-17 07:38
This issue is because of cloud config. If you copy/move the `userDefineLangs` folder to the `C:\Users\sherwoodj\OneDrive - Unitil Service Corporation` it will work.

**Comment by SenseiJoe** [comment] 2022-05-17 18:21
Thank you, didn’t realize it was set to that folder.

Sorry for the idiot user ☺
Joe

**Comment by ArkadiuszMichalski** [comment] 2022-07-26 23:28
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8394.

**Closed by ArkadiuszMichalski** 2022-07-26 23:28 UTC
