### ISSUE TITLE
JavaScript template strings are unreadable

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#4007] opened 2017-12-16 12:17 UTC
### Description of the Issue
JavaScript template strings with backticks are supported since #1055. But they're displayed in white on light-grey for the current line. Completely unreadable. There's no style option to change that dark colour to something more reasonable. If it's hard-coded, I'm asking you for a configuration change to make it usable. If it's a hidden config, please tell me where it is and also make it accessible in the UI.

### Debug Information
```
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

![unbenannt](https://user-images.githubusercontent.com/868315/34070257-25e94e46-e263-11e7-881e-54dc30c090e0.png)

**Comment by SinghRajenM** [comment] 2017-12-21 18:57
Could not reproduce. 
1. Please try uninstall and then install again 
2. or just move file "%appdata\Notepad++\stylers.xml" temporary (keep backup if you have ever customized it) and just run the notepad++ installer again.

Also share the content of javascript if problem continue to persist.

![image](https://user-images.githubusercontent.com/14791461/34270217-6e6a0400-e6ad-11e7-9849-11de44318dc4.png)

**Comment by ygoe** [comment] 2017-12-23 11:23
I've updated my stylers.xml from the default generated file. That includes a lot more LexerType entries and if they're not there, they cannot be configured in the UI. This looks like a problem with the application upgrade strategy. Any new version of Notepad++ will not update this file so that new features are not available in old updated installations. And the built-it default seems to use unreadable colours, whereas the default stylers.xml file has readable colours set. This is why I reported this issue as unresolvable be the user (through the UI). The resolution involves patching a file in a hidden system directory. Is that what you recommend to users?

I'm adding this to my repro steps:

* Edit your stylers.xml file to not include the STRINGRAW entries for any JavaScript section.

**Comment by SinghRajenM** [comment] 2017-12-23 12:14
Correct, you are right. In case of upgrade lexer xml is not upgraded. But in fresh installation it is copied from installed directory.

I'm not sure why this behavior exists. One possible reason, I can think of is: If a user has customized this styler.xml, then on upgrade he/she will lost the customization if upgrade replaces this file.

**Comment by ygoe** [comment] 2017-12-23 12:25
Yeah, that's not the problem. Any new style options should be available in the UI anyway, regardless of the contents of the user file, and then it should use the values from the template file. This doesn't seem to be the case.

**Comment by dail8859** [comment] 2017-12-23 13:57
See #1205

**Comment by ArkadiuszMichalski** [comment] 2020-09-23 10:10
@ygoe You still have this problem in latest Notepad++ version or get what we see in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4007#issuecomment-353429308:

**Comment by donho** [comment] 2020-09-24 20:53
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822#issuecomment-697275450

**Comment by teal2** [comment] 2021-01-02 10:29
Looks like this problem is eternal. In 2015, I left NPP for Sublime because of it. Now, five years later, nothing has changed.

**Comment by ArkadiuszMichalski** [comment] 2022-01-11 10:53
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822.

**Closed by ArkadiuszMichalski** 2022-01-11 10:53 UTC
