### ISSUE TITLE
"Save all" does not write files to "backup on save"

### ISSUE THREAD

**Issue by vanzanden** [notepad-plus-plus/notepad-plus-plus#7578] opened 2019-11-15 08:54 UTC
### Description of the Issue

When using "save all" functionality no .x..bak files are written to the custom backupdirectory, where save (one file) does write the backup file  to disk

### Steps to Reproduce the Issue

My settings regarding Preferences/backup:
  session snapshot and periodic backup:
    remember current version for next launch ENABLED
     enable session snapshot and periodic backup DISABLED
  backup on save
     simple backup SELECTED
     custom backup directory  ENABLED
     directory on local harddrive filled

have multiple files opened and apply changes to them
hit file/save all   or  ctrl-shift-s

### Expected Behavior

I should expect a .x.bak file in my custom backupdirectory for each of the saved files

### Actual Behavior
no backupfiles are created

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : F:\programfilesF\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll HTMLTag_unicode.dll mimeTools.dll MultiClipboard.dll NppConverter.dll NppExec.dll NppExport.dll NPPJSONViewer.dll NppMenuSearch.dll NppTextViz.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment] 2019-11-15 13:13
Unable to reproduce with these settings:

![image](https://user-images.githubusercontent.com/30118311/68945864-69790000-077f-11ea-9e53-70150c6ff072.png)

Having multiple dirty (i.e., modified) files and invoking SaveAll creates backup files for multiple files (the dirty ones) in the specified backup folder.

Notepad++ v7.8.1   (64-bit)
Build time : Oct 27 2019 - 22:57:19
Path : C:\........\npp.7.8.1\npp.7.8.1.bin.x64\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1451
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 


Closing until further substantiating information is supplied.

**Closed by sasumner** 2019-11-15 13:13 UTC
