### ISSUE TITLE
Crash when using right-click and mouse wheel to change files in Windows 10

### ISSUE THREAD

**Issue by tothedur** [notepad-plus-plus/notepad-plus-plus#2129] opened 2016-07-28 16:03 UTC
### Description of the Issue

I'm using Notepad ++ version 6.9.2, and since upgrading to Windows 10 the right-click/mousewheel function to change files is causing NP++ to lock up or crash.  On 2 machines here, the first is intermittent and simply stops responding, while the second is every time with a hard crash.  Both systems were upgrades of Windows 7.
### Steps to Reproduce the Issue
1. Open multiple files
2. Hold right mouse button and use the mouse wheel to select another file
3. Seems to occur more frequently if the mouse is over NP++, but not specifically over the file list that displays.
### Debug Information

Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by esabaliauskas** [comment] 2016-10-03 13:30
Well it happens for me always when i do the following:
 1 . Open multiple files
 2. Hold right mouse button
 3. Move the mouse away from the popup
 4. Keep scrolling until it crashes

![crash](https://cloud.githubusercontent.com/assets/17822510/19038935/7f63acbe-8986-11e6-8eb2-6b0379b733d0.gif)

also take a note of the increasing shadow :)

**Comment by SinghRajenM** [comment] 2017-07-15 13:50
@tothedur The issue is fixed in one of the later version. Please use latest version.

**Comment by MetaChuh** [comment] 2019-04-24 19:05
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-24 19:05 UTC
