### ISSUE TITLE
There is a problem with auto completion

### ISSUE THREAD

**Issue by andrecool-68** [notepad-plus-plus/notepad-plus-plus#5731] opened 2019-06-03 06:34 UTC
Here is a small example of problematic strings:

`!DOCTYPE html`
`@charset`
`:link`

The problem occurs (autocomplete does not work) when there is:

exclamation point
 spaces
colon
`@` 

...that's what I noticed.
Who knows how to fix it?

**Comment by andrecool-68** [comment] 2019-06-04 19:47
Does nobody notice this problem?

**Comment by MetaChuh** [comment] 2019-06-06 19:11
@andrecool-68 

i don't see any issue, the word parts do autocomplete as designed.
it is of course not possible to autocomplete whole sentences, separated by spaces, or operator characters.

do you experience something different ?

**Comment by andrecool-68** [comment] 2019-06-06 19:40
@MetaChuh Try writing "! DOCTYPE html" ... this is missing in auto-complete! The same is true of the other symbols about which I spoke above.

**Comment by Ekopalypse** [comment] 2019-06-06 20:08
Looks like autocompletion is done with word character list in mind because, if you add
!: to that list it is working. (settings->preferences->delimiter->Add your character ...)
Btw. not a 7.7 issue as I see the same problem with 7.6.6

**Comment by MetaChuh** [comment] 2019-06-06 20:32
@andrecool-68 

if you add `!:@` to your delimiters, as suggested by @Ekopalypse , the autocompletion will work for single word and non space separated entries.

however, one day i do have to look up, who committed the space separated multi word `!DOCTYPE html` a long time ago, without testing 😉

are you satisfied with @Ekopalypse 's solution ?

**Comment by andrecool-68** [comment] 2019-06-06 20:58
@Ekopalypse Hooray! Earned!

**Comment by MetaChuh** [comment] 2019-06-06 21:09
@andrecool-68 

yes, and if you find who contributed this space separated entry to html.xml i will put him on the watch list 😉

ps: if you are satisfied, please close this issue for us, also to help me not being the bad cop all the time.
many thanks and best regards.

**Closed** 2019-06-06 21:11 UTC

**Comment by sasumner** [comment] 2019-06-06 21:13
>"bad cop"

Never. I like to think of myself (rogue non-team member that I am) as the "bad cop" to your "good cop".  Keep up the good work, BTW.

**Comment by MetaChuh** [comment] 2019-06-06 21:37
@sasumner 

you are a team member to me, and you have been for all the past years you have endured and still continue to do so, and you are far away from being the bad cop.
and if you don't consider yourself as a team member yet, consider yourself as an influencer, that has contributed to shape notepad++ to where it is today 👍

ps, just in case: don't you dare to revenge tell me to be less chatty at the issue tracker, as our community is the place for that 😉

**Comment by andrecool-68** [comment] 2019-06-07 22:36
@MetaChuh @Ekopalypse 
Friends ... there is a problem! if there is no space before the colon, auto-completion does not work)))

![Imgur](https://i.imgur.com/w39nXe1.gif)

**Comment by sasumner** [comment] 2019-06-08 12:27
@andrecool-68 If "apple" was in the autocomplete list and you typed "redapp" into your document, would you expect autocomplete to pop up and suggest "apple" after you put a space after "redapp"?

**Comment by Ekopalypse** [comment] 2019-06-08 13:20
@andrecool-68, yes that is expected. 
As soon as you've added !: to the word char list, it is no longer a separator.
Something like a:hover would be seen as a complete word a NOT as **a** followed by **colon** followed by **hover**

Yes, you can add a:hover to the xml to make it work but as far as I remember it should be a sorted list,
means put it right after the keyword **a**.
