### ISSUE TITLE
Tab color red even after save

### ISSUE THREAD

**Issue by elicym** [notepad-plus-plus/notepad-plus-plus#579] opened 2015-07-27 07:11 UTC
1. Open a file
2. Make a change without saving so the tab goes red
3. Close Notepad++
4. Open Notepad++ so the file automatically opens ('Remember current session' option is ON)
5. CTRL-S to save
6. The tab remains red, although the file is saved

The issue is not just about tab color - if you click Reload, you get a warning 'Are you sure you want to reload the current file and lose the changed made?' If you click Yes, it reloads, and the tab is still red. Clicking Reload again repeats.

(v6.8, Windows 7)

**Comment by sanastasiou** [comment] 2015-07-28 16:22
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/173 I believe.

**Comment by donho** [comment] 2015-07-30 20:26
Close due to the duplication.

**Closed by donho** 2015-07-30 20:26 UTC
Labels: accepted, bug
