### ISSUE TITLE
Installer language is Afrikaans instead of English on Windows Server 2016.

### ISSUE THREAD

**Issue by rbarte** [notepad-plus-plus/notepad-plus-plus#7574] opened 2019-11-14 09:35 UTC
### Description of the Issue

The Notepad++ installer instead of English is shown in Afrikaans. Afterwards also the notepad++ is shown in this language.
Language and regional settings on Windows 2016 OS are set to US (English).

Found similar closed bug: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3844
and 
https://community.notepad-plus-plus.org/topic/14564/dutch-as-install-language-instead-of-english

### Steps to Reproduce the Issue

1. Double click  on the "npp.7.8.1.Installer.x64.exe".
2. Confirm UAC.
3. Installer is shown in Afrikaans.
4. After installation the Notepad++ application is also in Afrikaans.

### Expected Behavior

Installer is shown in English (like other installers on US/English OS).
### Actual Behavior

Installer is shown in Afrikaans, also the installed application defaults to it.

### Debug Information

Windows Device Guard is active on this system.

![2019-11-14 10_21_25-NotepadPP](https://user-images.githubusercontent.com/31691084/68844140-9d91e980-06c9-11ea-92d8-bf7cbfdb73af.png)
![2019-11-14 10_30_37-Windows-Regional1](https://user-images.githubusercontent.com/31691084/68844567-4d675700-06ca-11ea-8f8f-6067fa57b4c4.png)
![2019-11-14 10_31_00-Windows-Regional2](https://user-images.githubusercontent.com/31691084/68844568-4d675700-06ca-11ea-88d2-b3f88619d530.png)
![2019-11-14 10_31_00-Windows-Regional3](https://user-images.githubusercontent.com/31691084/68844569-4dffed80-06ca-11ea-9869-582cce505ed9.png)
![2019-11-14 10_31_00-Windows-Regional4](https://user-images.githubusercontent.com/31691084/68844570-4dffed80-06ca-11ea-8384-d8043ab78840.png)
![2019-11-14 10_37_09-notepadpp-gui](https://user-images.githubusercontent.com/31691084/68844909-d41c3400-06ca-11ea-94df-65af7fb25009.png)

**Comment by aaimaai** [comment] 2019-11-24 12:38
That's not Dutch but Afrikaans. Because of its name (or its iso-code "af") it's probably the first language in the language list.

**Comment by rbarte** [comment] 2019-12-07 18:52
> 
> 
> That's not Dutch but Afrikaans. Because of its name (or its iso-code "af") it's probably the first language in the language list.

Thank you - I've changed the description and title.

**Comment by TotiTolvukall** [comment] 2022-12-06 08:21
I wish to add to this instead of filing another duplicate.

Locale is Icelandic, display language is Icelandic, I used winget to install Notepad++ 8.4.7 and it installed with an Afrikaans display language. Which of course is useless to me ( and 99.999% of the people in Iceland as we don't speak Afrikaans - in favor of Icelandic, English, Swedish and Danish.)

And this has been the case as long as I can remember. Notepad++ does not have a sane default in the installer - instead it's "select your poison or suffer the consequences" - which would be quite all right if the default demographic was South Africa. It is the same if you aimlessly click through the GUI installer (which is in fact what winget does - which is WHY the default MUST be fixed.)

**Comment by llamaonaskateboard** [comment] 2023-03-29 04:37
I experienced this issue today with 8.5.1 x64 on Windows 10 - the installer skipped the language selection and jumped straight into Afrikaans.
The culprit ended up being McAfee Endpoint Security which somehow causes `HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage` to end up with the value `Installer Language`.
Deleting that registry key and disabling Access Protection whilst running the installer fixes the issue.

**Comment by donho** [comment] 2023-09-16 11:00
The installer x86 & x64 which contain the fix of this issue (#14125) are available here:
http://download.notepad-plus-plus.org/repository/MISC/fixInstallLangIssue/

They are the latest version 8.5.7 and binaries are signed.
Please test the installer of your choice, and confirm me if this issue has been fixed.

**Comment by TotiTolvukall** [comment] 2023-09-20 12:57
I am not sure how I would go about verifying the EXE installer as it is an interactive installer, but the default it pops up with is Afrikaans regardless of the installed language or the selected language of the already installed NPP
<img width="218" alt="image" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51100612/a0c1754f-9b67-4552-846f-fbbf6824748d">

On a server I would install the MSI (which requires a downloadable MSI) or via winget (which requires the fix to be deployed live - which I'm not so sure would be a good idea unless tested already).

**Comment by donho** [comment] 2023-09-22 17:37
The problem seems to be caused by McAfee: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7574#issuecomment-1487933838

So the issue is closed.

**Comment by TotiTolvukall** [comment] 2023-09-22 22:22
I appreciate the effort you put into this product for such a long time, but seriously, 👆that part needs some work.

No, the bug isn't caused by McAfee - you are pretending causation by correlation. I don't have McAfee or any other third-party virus scanner on any of my machines - so it would have been prudent to at least ask others in this thread if they used McAfee or not - and if they (everybody) did, re-try without McAfee active.

But whatever, this bug hindered using winget to install and thus hindered automatic updates. And that was almost a year ago. As I'm not inclined on offering NPP in Afrikaans to my clients or users, I simply solved it by using VS Code wherever and it turned out for the better. So don't lose a beat on my account.

**Comment by donho** [comment] 2023-09-22 23:08
@TotiTolvukall 
I see your points.
I would like to do a walk-around by shooting in the dark, since I cannot reproduce the bug. 
I will try to set English as default language while the language detection failure and there's no language selector.
Could you try this installer?

**Comment by TotiTolvukall** [comment] 2023-09-23 00:21
I already did - 2 days ago, and you said it was due to a registry key.

Here I re-did on a machine that already has NPP 8.4.6 installed with the English language chosen.
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51100612/5c5fb006-7b24-4fd8-b092-abc6c5631cad)

Same result - language chosen is Afrikaans - and because of that, the automatic clickthrough install method winget uses will fail (install the wrong language).

Here's what is already installed:
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51100612/cc029b74-7f29-47f7-a2f8-babb18bfd634)

**Comment by mpheath** [comment] 2023-09-23 11:34
@donho 

> I will try to set English as default language while the language detection failure and there's no language selector.

I would not call it a failure of the language selector as it is intended behaviour. It's default mode is automatic and so it decides to show or not show based on conditions. The installer can force the language selector to show by defining `MUI_LANGDLL_ALWAYSSHOW` . The language selector does not show for silent installs. IMO, the McAfee comment is an unproven guess as a cause.

> I would like to do a walk-around by shooting in the dark, since I cannot reproduce the bug.

A minimal test script may help to show some light.

<details>

<summary>Click to view test script</summary>

```nsis
;!define FIX

; Include Modern UI
!include "MUI.nsh"

; Properly display all languages
Unicode true

; Name and file
!ifdef FIX
  Name "Fix"
  OutFile "LanguageFix.exe"
!else
  Name "Bug"
  OutFile "LanguageBug.exe"
!endif

; Request application privileges
RequestExecutionLevel user

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

; Languages
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "Afrikaans"
!insertmacro MUI_RESERVEFILE_LANGDLL

Section "Install"
SectionEnd

Function .onInit
  ; debug: *** set UK English as unsupported language ***
  StrCpy $LANGUAGE "2057"
  MessageBox MB_OK "Before: $LANGUAGE (UK English)"

  !ifdef FIX
    Call unsupportedLanguageToEnglish
  !endif

  !define MUI_LANGDLL_ALWAYSSHOW
  !insertmacro MUI_LANGDLL_DISPLAY

  ; debug: *** Display language to use ***
  MessageBox MB_OK "After: $LANGUAGE"
FunctionEnd

!ifdef FIX
Function unsupportedLanguageToEnglish
  ${Switch} $LANGUAGE
    ${Case} ${LANG_AFRIKAANS}
    ${Case} ${LANG_ENGLISH}
      ; language is supported
      ${Break}
    ${Default}
      ; set language to English
      StrCpy $LANGUAGE ${LANG_ENGLISH}
      ; debug: *** Alert language unsupported ***
      MessageBox MB_OK "Language is unsupported.$\nChanged language to English"
      ${Break}
  ${EndSwitch}
FunctionEnd
!endif
```

<hr>

</details>

The 1st line of the script has a commented `;define FIX`. Compile the script and then uncomment that line, save and compile again to get 2 installers to test.

`$LANGUAGE` is set early in the script to UK English (2057) as an unsupported installer language.

 * Compiled without defining `FIX` displays *Africaans* in the language selector.
 * Compiled with defining `FIX` displays *English* in the language selector.

Can you to reproduce this behaviour?

As for the saved language in the registry from previous Notepad++ installs, that is a symptom from the installer that failed to handle unsupported languages and as a result defaulted to *Afrikaans*. Once done, how to recognize *Afrikaans* mistake from *Afrikaans* actual with the installer. The solution to correct by the installer might be a temporary brutal fix, though perhaps it may be needed to close this issue.

Something like this for several releases to clear the registry value

<details>

<summary>Click to view code excerpt</summary>

```nsis
	ReadRegStr $tempLng HKLM "SOFTWARE\${APPNAME}" 'InstallerLanguage'
	${IfNot} ${Errors}
		${If} "$LANGUAGE" != "${LANG_AFRIKAANS}"
		${AndIf} "$tempLng" == "${LANG_AFRIKAANS}"
			DeleteRegValue HKLM "SOFTWARE\${APPNAME}" 'InstallerLanguage' ; tmp fix
		${Else}
			StrCpy $LANGUAGE "$tempLng" ; set default language
		${EndIf}
	${EndIf}
```

</details>

and then revert it back so that the users who prefer the *Afrikaans* language get control back.

**Comment by TotiTolvukall** [comment] 2023-09-25 08:46
I couldn't - and moreover, I found that although NPP had been installed with English as the primary language, it still pointed to Afrikaans in the registry.

I do however have a suggestion that _might_ mitigate the problem for those that use winget or other auto-click installation methods - allow a "--language=[language token]" like "--language=en" and if someone tries "--language=unsupported_language" then you'd exit with error and "Unsupported language" message to the user.

That might at least (if supported by the installation framework) take the cap off of the problem.

**Comment by llamaonaskateboard** [comment] 2023-09-25 09:16
I can't reproduce McAfee causing issues on 8.5.1 or 8.5.7 anymore, guessing something changed in newer McAfee definitions.

As a test for @TotiTolvukall's issue, I installed the Icelandic language pack on a test Windows 10 VM, changed the current user and system language to Icelandic and can reproduce getting Afrikaans as the initial language selection on the installer. This is reproducible on both 8.5.1 and 8.5.7.
This is also without `HKLM\SOFTWARE\WOW6432Node\Notepad++\InstallerLanguage` existing yet.

Could this be because Icelandic is specifically commented out here for some reason and so isn't being considered a valid installer language?
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/v8.5.7/PowerEditor/installer/nsisInclude/langs4Installer.nsh#L50

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/31365608/c5cef1bc-77ce-4361-af12-e3dc91aeef6c)
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/31365608/c52b4dbe-653d-4370-86c6-0af5e6dade8b)

**Comment by donho** [comment] 2023-09-26 15:28
@TotiTolvukall 

I have tried to set English as default value while the detection is failed. Could you try the following binaries please?
http://download.notepad-plus-plus.org/repository/MISC/setEnglishAsDefaultLang

**Comment by donho** [comment] 2023-10-01 14:12
Any news about it?

**Comment by TotiTolvukall** [comment] 2023-10-01 16:46
Sorry, being busy has me forgetting things.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51100612/8b63ef28-a6f9-4c0a-97e7-182caf7155e9)

This seems to have proper behaviour ( WS2019 )

And on W11
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/51100612/0b2462f2-3008-4c78-b142-ec989422be50)

**Comment by donho** [comment] 2023-10-04 21:21
@TotiTolvukall 
Thank you for your testing.
Nice to learn that this issue will be fixed.

**Closed** 2023-10-10 15:26 UTC
