### ISSUE TITLE
Highlighting some words no longer highlights the same word elsewhere in document

### ISSUE THREAD

**Issue by Marshallx** [notepad-plus-plus/notepad-plus-plus#1213] opened 2015-12-02 10:16 UTC
Example document:
$aaa ${bbb}
$aaa ${bbb}

Highlight the first "bbb" and the second one is also highlighted. This is good.
Highlight the first "aaa". The second one is not highlighted. This is bad.
It used to be highlighted before the recent update.

**Comment by Marshallx** [comment] 2015-12-02 10:25
It seems that scrolling around the document while the word is highlighted will cause the other words' highlights to appear and disappear at random. But mostly the other highlights are not shown.

**Comment by rascob** [comment] 2015-12-02 13:06
Same here, v. 6.8.6.
It seems this appears at random; other times other occurrences of the selected word will be highlighted in the text, other times it won't.
The bug does NOT apply in v. 6.8.5.

**Comment by sanastasiou** [comment] 2015-12-02 14:24
I can confirm as well.

**Comment by brandpeter** [comment] 2015-12-08 20:46
Seems to be fixed in 6.8.7, working fine.

**Comment by rascob** [comment] 2015-12-14 13:05
Haven't seen it appearing in 6.8.8 (yet).
Note: The specific bug is not mentioned on v. 6.8.7 & 6.8.8 release notes

**Comment by MetaChuh** [comment] 2019-04-13 02:12
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:12 UTC
