### ISSUE TITLE
UNICODE-support broken for characters outside the BMP

### ISSUE THREAD

**Issue by stackflows** [notepad-plus-plus/notepad-plus-plus#801] opened 2015-08-25 11:15 UTC
I am trying to save a file containing UNICODE-characters like "𤽜" or "𤭢", both of which should be stored as surrogate pairs with two 16-bit-wide characters each, by setting the encoding to UCS-2 LE, but the characters are stored wrongly. Even on immediate "Reload from Disk", the then-displayed characters are messed up. After inspection of the generated file with a hex-editor, the storage representation generated by Notepad++ for those characters is too short (only two bytes instead of the required four per character).
If I enter the correct representation via the hex-editor (𤽜 --> `53 D8 5C DF`, 𤭢 --> `52 D8 62 DF`), Notepad++ displays **six (!) bytes** each instead of **one character**, namely
- 𤽜 --> `xED xA1 x93 xED xBD x9C`
- 𤭢 --> `xED xA1 x92 xED xBD xA2`

with encoding still set (and automatically detected) as UCS-2 LE BOM, which is correct, as e.g. Visual Studio and other applications show the correct character when displaying the file, but not Notepad++. It looks as if Notepad++ would not support UNICODE outside the BMP.

**Comment by xylographe** [comment] 2015-09-13 13:37
You are trying to encode code points outside the BMP with UCS-2 encoding. It is **impossible**. Use UCS-4 or UTF-8 instead.

Obviously, Notepad++ should have told you it is impossible to do what you want instead of creating garbage.

**Comment by stackflows** [comment] 2016-10-06 11:49
I did not try: Notepad++ does. It should support UTF-16, as Windows does out-of-the-box, since UTF-16 very well supports the whole UNICODE range, while the outdated UCS-2 does not.

**Comment by digitalentity** [comment] 2017-02-27 02:31
I also vote for UTF-16 support - Windows use it natively

**Comment by stackflows** [comment] 2017-04-04 13:30
Full UTF-16-support is a central feature required for any text editor; Vim has it, Emacs has it - both since a _really_ long time. Will Notepad++ follow?

**Comment by byzod** [comment] 2017-09-02 13:05
Yeah I have a file that have a character from plane 2: `𠀄`, it's annoying that npp can't edit this file, I have to ask help from Notepad

Most browser can display it correctly (looks similar to 卫 or 工)
Even Microsoft Notepad can render it perfectly
While Notepad **Plus Plus** can't. How ironic😂

**Comment by jay** [comment] 2017-12-04 00:09
Even if it won't display or save the UTF-16 characters that are surrogate pairs I think it would be helpful not to modify the existing bytes if the data is unmodified and moved or copied via drag and drop. For example I have a file not created in Notepad++ that uses UTF-16:

![draganddrop_utf16_surrogate_npp](https://user-images.githubusercontent.com/965580/33531506-0764fd28-d85c-11e7-8838-8140d47443ba.gif)

The chinese character is what you would expect to see, however as noted it won't save as utf-16, for reasons already described (it saves as 2D09 A200 2C00 2000). The existing bytes (ie no drag and drop) do save correctly, but I can understand if that's not was intended.

**Comment by stackflows** [comment] 2018-02-19 13:37
@xylographe: Is there anything planned for proper UTF-16 support?

**Comment by cup** [comment] 2018-10-06 15:44
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1360
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1727
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/801
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/903

**Comment by MetaChuh** [comment] 2019-04-09 23:35
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:35 UTC
