### ISSUE TITLE
Add "No to all" option on close dialogue

### ISSUE THREAD

**Issue by sattaman** [notepad-plus-plus/notepad-plus-plus#2100] opened 2016-07-19 08:04 UTC
Please can a "No to all" option be added to the close dialogue? This must be an easy thing to add, yet is painful without , especially since the button locations change and I invariably click no lots of times followed by a yes.

**Comment by Croydon** [comment] 2016-07-28 14:52
I would say that is a duplicate of #325.
When implementing a "save all" option there should also be a "no to all" option.

**Comment by MetaChuh** [comment] 2019-05-01 22:04
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:04 UTC

**Comment by sasumner** [comment] 2019-05-02 12:50
So like if you don't have "Enable session snapshot" ticked, and you have multiple unsaved but modified files open when you quit, you expect to see a "No to all" option? Makes sense to me.  Tested that scenario in 7.6.6 and no choice for that:

![image](https://user-images.githubusercontent.com/30118311/57076302-51e09b00-6cb7-11e9-8621-c3a72a52266b.png)
