### ISSUE TITLE
Search resets the colours for panels

### ISSUE THREAD

**Issue by blinkok** [notepad-plus-plus/notepad-plus-plus#9905] opened 2021-05-24 19:24 UTC
### Description of the Issue
In my experience, when NppExec is installed, using Search All causes panels (Like function list/workspace) colours to reset.

### Steps to Reproduce the Issue
The behavior is documented here
https://community.notepad-plus-plus.org/topic/21197/search-resets-the-colour-setting-for-panels

### Debug Information
Notepad++ v7.9.5   (64-bit)
Build time : Mar 21 2021 - 02:13:17
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : LocationNavigate.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll PythonScript.dll _CustomizeToolbar.dll

**Comment by ArkadiuszMichalski** [comment] 2021-07-23 23:07
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2937.

**Closed** 2021-12-14 01:59 UTC
Labels: duplicate
