### ISSUE TITLE
Tabs not coming back after close and reopen

### ISSUE THREAD

**Issue by krispeez** [notepad-plus-plus/notepad-plus-plus#12433] opened 2022-10-31 13:53 UTC
### Description of the Issue
I always have multiple Notepad++ tabs open, sometimes they are saved, sometimes they aren't.  I've always reopened the app to find all of my tabs safe and sound sitting there waiting for me just as I left them.  Except this morning.  I shut down my laptop last night the same as usual and when I opened my Notepad++ this morning, all of my tabs were gone!  Is this a 'bug' or a new 'feature'?  One of my favorite things about notepad++ was that I could always count of having my tabs open right back up to where I left off.  What happened?

### Steps to Reproduce the Issue
1. Close notepad++
2. Open Notepad++
3. Find all old tabs gone and only one new tab open
4.*This does not happen all the time and the first time it happened was this morning.

### Expected Behavior
I expected my tabs to open right back up to where i left off the day before - whether they were saved or not.

### Actual Behavior
All tabs closed, I lost my work and notes. I don't know how to recover.

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.674
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    XMLTools (3.1.1.12)

**Comment by ArkadiuszMichalski** [comment] 2022-10-31 16:20
Looks like duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9850. This was fixed and will appear on the next release.

**Closed by ArkadiuszMichalski** 2022-10-31 16:20 UTC
