### ISSUE TITLE
Update Scintilla to 3.7.6 long term?

### ISSUE THREAD

**Issue by informatorius** [notepad-plus-plus/notepad-plus-plus#4921] opened 2018-10-14 09:31 UTC
https://www.scintilla.org/LongTermDownload.html
C++11 is used and GCC 4.8 and MSVC 2015 are supported. 
It only needs adaptation for some deprecated defines.

**Comment by chcg** [comment] 2018-10-14 22:36
See https://github.com/cmeriaux/scintilla/tree/npp-3-7-0 for a patched version of scintilla for N++.

**Comment by historicbruno** [comment] 2018-12-22 05:11
This is a duplicate of #1126.

**Comment by chcg** [comment] 2018-12-26 21:32
@donho Any plans to update the scintilla base to the current LTS version any time soon?

**Comment by jmbockhorst** [comment] 2019-03-22 20:51
@donho Is there anything that can be done to help with this upgrade?

**Comment by sasumner** [comment] 2019-03-23 12:40
@jmbockhorst , Don's previous comments on this topic have been, "only I update Notepad++'s Scintilla". That would seem to imply that offers of help or even a PR that does the job...are pointless.  Nice that you offered however.

**Comment by donho** [comment] 2019-04-18 23:22
to 4.1.4 in progress

**Closed by donho** 2019-04-18 23:22 UTC
Labels: question

**Comment by LordNyriox** [comment] 2019-04-20 06:12
@donho:  FYI, Scintilla `4.1.5` was released a few days ago. 

[<https://www.scintilla.org/ScintillaHistory.html>]

**Comment by sasumner** [comment] 2019-04-20 12:14
@donho From my (limited!) understanding a jump to Scintilla 4.x is a bit difficult.  I think the Notepad++ user masses would be happy with an initial move to a late 3.x version if it makes things easier.  Of course if you decide to go for it all with a 4.x move, I think that is super as well.

**Comment by LordNyriox** [comment] 2019-04-20 14:24
@sasumner, @donho: 

>From my (limited!) understanding a jump to Scintilla 4.x is a bit difficult. 

You are not wrong.  Scintilla `4.0.0` switched to a minimum of C++14 (MSVC 2017), and Scintilla `4.0.3` upped that requirement to C++17 (MSVC 2017.5).  

The Scintilla `3.7.x` long-term branch, on the other hand, only requires C++11.

**Comment by LordNyriox** [comment] 2019-04-20 14:34
@sasumner, @donho: 

>From my (limited!) understanding a jump to Scintilla 4.x is a bit difficult. 

You are not wrong.  Scintilla `4.0.0` switched to a minimum of C++14 (MSVC 2017), and Scintilla `4.0.3` upped that requirement to C++17 (MSVC 2017.5).  

The Scintilla `3.7.x` long-term branch, on the other hand, only requires C++11. 

**P.S.**  It may be worth noting, however, that the `master` branch of @cmeriaux's Notepad++ optimized Scintilla fork, was made using Scintilla `4.1.0` as a base.  

[<https://github.com/cmeriaux/scintilla/blob/master/version.txt>] 

[<https://github.com/cmeriaux/notepad-plus-plus/tree/scintilla>]
