### ISSUE TITLE
Close All Saved

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#335] opened 2015-06-25 23:32 UTC
When right-clicking a tab, it would be useful to have a command 'Close All Saved'.

**Comment by drakosvlad** [comment] 2015-07-04 19:26
Pull request with this feature was sent

**Comment by VVelda** [comment] 2015-08-24 17:54
And what about Close All? (For situation, when you open Notepad++ and previous session isn't important)

**Comment by MetaChuh** [comment] 2019-04-08 21:57
closed as duplicate of rejected https://github.com/notepad-plus-plus/notepad-plus-plus/pull/404 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2500

**Closed by MetaChuh** 2019-04-08 21:57 UTC
