### ISSUE TITLE
Wrong rendering of index finger characters

### ISSUE THREAD

**Issue by ysmartin** [notepad-plus-plus/notepad-plus-plus#4490] opened 2018-05-09 10:30 UTC
### Steps to Reproduce the Issue

1. Paste the following text into a blank document in Notepad++
````
☞
☞☛
````

### Expected Behavior

In the first line, a WHITE RIGHT POINTING INDEX glyph is displayed, for the Unicode character U+261E
In the second line, the same glyph is displayed, followed by a BLACK RIGHT POINTING INDEX (U+261B)

### Actual Behavior

In the first line, an empty square is rendered.
The second line is properly displayed. In fact, if a U+261B is appended to any sequence of U+261E, then all of them are rendered correctly; if the former is removed again, then the empty squares appear again.

### Debug Information

Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

### More info
Default font is Courier New
I guess this issue is not constrained to those characters, but it may be a symptom of a wider issue with higher-block Unicode characters.

### Screenshot
![2018-05-09 12_17_57-notepad](https://user-images.githubusercontent.com/3438868/39809796-29c6be7c-5383-11e8-9cc0-d1338f4c0d39.png)

**Comment by ClaudiaFrank** [comment] 2018-05-09 11:10
Don't have reported behavior, anything you see that is different to your setup other than OS?

![issue4490](https://user-images.githubusercontent.com/16170444/39811733-228a057c-538a-11e8-88ca-50077c6e04d4.PNG)

**Comment by SinghRajenM** [comment] 2018-05-09 16:43
Duplicate of #870, #813, #4086, #4056, #675, #1621, #3458 may be many more.

BTW, npp is text editor. Why do we need special characters in it?

**Comment by MetaChuh** [comment] 2019-05-02 14:43
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

<img width="315" alt="" src="https://user-images.githubusercontent.com/45773305/57083813-6f365900-6cf9-11e9-925e-13cfe6cc4761.png">

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-02 14:43 UTC
Labels: not reproducible
