### ISSUE TITLE
Bogus empty window panes appear when clicking on document title

### ISSUE THREAD

**Issue by tjstjsgt** [notepad-plus-plus/notepad-plus-plus#10764] opened 2021-11-09 14:54 UTC
### Description of the Issue
![image](https://user-images.githubusercontent.com/44301488/140946369-a107a7bc-d368-40f4-a975-e5825d2b0fdf.png)

The window panes appear to go haywire when doing anything like clicking on a document or opening an existing document. Trying to move these weird panes crashes the program

### Steps to Reproduce the Issue
1.  Open Notepad++
2. Click File -> new
3. Observe window panes
4. Try clicking and dragging on the bar of one of these bogus panes

### Expected Behavior
New document appears maximize; no weird bogus panes appear

### Actual Behavior
Existing and new document appear small in middle of the screen, and subwindows with nothing in them appear. I cannot completely close these windows. If you click and hold on the empty "title bar" of the sub window, it crashes Notepad++ with no error message.

### Debug Information
Notepad++ v8.1.9   (32-bit)
Build time : Oct 21 2021 - 23:32:04
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by tjstjsgt** [comment] 2021-11-09 14:54
I tried deleting all Notepad++ data from my machine (uninstalled, deleted AppData, shortcuts, etc) and reinstalling the program and the same result occurred. In all cases I used the default installation settings.

**Comment by tjstjsgt** [comment] 2021-11-09 14:55
![image](https://user-images.githubusercontent.com/44301488/140947355-12cf9826-1c0d-4964-89f8-c317b59c83f4.png)

**Comment by ArkadiuszMichalski** [comment] 2021-11-09 17:00
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717#issuecomment-964219313.

**Closed by ArkadiuszMichalski** 2021-11-09 17:00 UTC
