### ISSUE TITLE
Character Count wrong

### ISSUE THREAD

**Issue by buggalicious** [notepad-plus-plus/notepad-plus-plus#3849] opened 2017-10-26 08:49 UTC
### Description of the Issue

The character count in the summary reads it is counted without space, while in fact it also does count the spaces.

### Steps to Reproduce the Issue
1. Type 123 123
2. Double click the word "length" on the status bar or go to View/Summary
3. Read the first line of the summary "Character: (without blanks) and see the number "7"

### Expected Behavior
The number should be 6 without the white space

### Actual Behavior
The number is 7, because the blank space is counted despite the preceding statement describing the result

### Debug Information
none
The plugin TextFX/Tools/Word Count displays the correct values.
Besides, it would be great if one could have the actual value of "Character: (without blanks)" displayed on the status bar.

**Comment by Sinhov** [comment] 2017-10-26 11:10
Hello, new contributor here. I want to work on this issue. Could someone please guide me on how to get started? I don't know where to look for in the codebase to fix this issue.
Thanks.

**Comment by sasumner** [comment] 2017-10-26 11:36
It appears that the "Characters (without blanks)" value being reported is actually "Characters (without line-endings)".

**Proof** (for a document with multiple lines):
**Step 1:** Do a regular expression COUNT search on   (?s).   and note the value is same as "Current document length" value
**Step 2:**  Do a regular expression COUNT search on   (?-s).   and note the value is same as "Characters (without blanks)" value
The difference in the searches is the Step1 search will count line-ending characters and the Step2 will exclude line-ending characters

**Comment by sasumner** [comment] 2017-10-26 11:41
@Sinhov 
I would start by doing a "find-in-files" on the codebase for some text that appears in the View (menu) -> Summary popup window.  For example, search for `(without blanks):`.  This would get you quickly to the area of code that does this processing and you can study it and decide how to change it.  Good luck.

**Comment by buggalicious** [comment] 2017-11-13 18:55
Thank you, guys, for your interest in this matter. Is there any update on this?
I think this is something that should be correct as to the way the software handles it, it is part of it's reliability.
Best regards.

**Comment by sasumner** [comment] 2017-11-13 20:31
Sometimes changes are slow to be adopted.  It is possible to obtain your desired count by doing a Find-Count in regular expression search mode for `\S`:
![image](https://user-images.githubusercontent.com/30118311/32747723-a645aae4-c887-11e7-8fe3-bdea34c4bf84.png)

It is also possible to script a solution and have a running count of non-blank characters in the status bar.

But these are workarounds, not cures.

**Comment by encore0117** [comment] 2017-11-21 07:23
Working on this issue right now

**Comment by encore0117** [comment] 2017-11-22 01:38
I just split the char count into 2 cases.

If the text is encoded in UTF-8, the summary will include another measure showing the number of characters excluding white spaces.

Otherwise, the summary will only show the number of characters.

**Comment by buggalicious** [comment] 2017-11-22 07:30
The character count should leave the two choices of "with/without spaces" to the user and then provide the correct figure regardless of the encoding.

**Comment by encore0117** [comment] 2017-11-22 13:01
Here is the reason:
For non-UTF-8 encoding, the editor used scintilla, and it does not provide a method to count characters without counting whitespaces.

**Comment by SinghRajenM** [comment] 2019-07-05 15:17
@donho @MetaChuh , this is fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/5037.

**Comment by donho** [comment] 2019-08-04 18:29
Not a bug to me.

**Closed by donho** 2019-08-04 18:29 UTC
Labels: reject

**Comment by buggalicious** [comment] 2022-08-09 14:48
When I copy/paste text from Word 2013 (UTF-8, Arial Unicode), I get a higher character count in Notepad++(latest as of August 9, 2022).
I can copy/paste text from Notepad++ into Word and back, and the character count will be higher.
Attached, there is a file with three times the exact same text. The first counts 117, the second 119, and the third 120 characters.
There is no visible difference.
[differing character counts.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9291812/differing.character.counts.txt)

Regards

**Comment by alankilborn** [comment] 2022-08-09 14:58
@buggalicious 

>I can copy/paste text from Notepad++ into Word and back, and the character count will be higher.
>There is no visible difference.

I see why; perhaps you can see it too:

![image](https://user-images.githubusercontent.com/77065706/183682076-21665237-d3b6-49a0-8dc0-d1f494f97693.png)

Word is putting extra non-viewable characters into your data.

For Notepad++ to show you this easily, it is waiting for issue #8284 to be implemented.

**Comment by buggalicious** [comment] 2022-08-09 15:07
Thank you so much for so quickly clarifying the issue!
This poses a major problem to me and my workflow as a translator, as I need to abide exact character limits.
Is there any way of stripping those characters from the text?

**Comment by alankilborn** [comment] 2022-08-09 15:20
> Is there any way of stripping those characters from the text?

Well, if it were me, I'd do it with a replacement operation:

![image](https://user-images.githubusercontent.com/77065706/183689149-1ee21888-93d2-488f-a85f-fd63bf29c824.png)

The _Find what_ expression shown is `[^\r\n\t\x20-\x7E]+`.

**Comment by buggalicious** [comment] 2022-08-09 15:26
Hot damn, I was just researching that and trying to find the RegEx string!
I just used yours and, Bam! - every line is 115 characters long!
Fantastic, thank you so much!

This is a very cryptic issue I'm sure a lot of people are affected by in their daily work.

**Comment by buggalicious** [comment] 2022-08-09 16:36
[^\r\n\t\x20-\x7E(?:\u00c4,\u00e4,\u00d6,\u00f6,\u00dc,\u00fc,\u00df)]+
and replace with whitespace.
This seems to work all right for German, retaining umlauts and ß, although the first line still has one character less than the second and third.

**Comment by alankilborn** [comment] 2022-08-09 17:16
My regular expression was based on an ignorance of your data, because I didn't know your data.  Probably you should attack (i.e., match) the characters you want to eliminate directly.  If it is only the LRM character, you can regex search for it with `\x{200E}`, or extended mode search for it with `\u200E`.

**Comment by buggalicious** [comment] 2022-08-09 17:42
I tried that before, but only now I've gotten it to work:
search: \x{200E}+
replace with nothing
This makes all lines 117 characters long, which is perfect.

Thank you so much for all your help!

**Comment by alankilborn** [comment] 2022-08-09 17:49
@buggalicious Glad to help.  Note that our back-and-forth conversation here today has nothing to do with this current issue.  In the future you might find the N++ Community valuable for getting help:  https://community.notepad-plus-plus.org/
