### ISSUE TITLE
Word Counting

### ISSUE THREAD

**Issue by osgaldor** [notepad-plus-plus/notepad-plus-plus#13841] opened 2023-06-29 00:37 UTC
I use N++ as a plain text editor for producing story treatments.  It would be very  helpful  for me to have a word count function to help me monitor my text output  I'm an experienced developer and if I could find some good guidance I would take a go at developing this myself.

### Steps to Reproduce the Issue

1. 
2. 
3.

**Comment by molsonkiko** [comment] 2023-06-29 01:29
Duplicate of #1136.

**Comment by alankilborn** [comment] 2023-06-29 01:32
Not really a duplicate of 1136; that's more about putting it on the status bar.

A count of words is already available in the _View_ menu's _Summary_ command.

**Comment by donho** [comment] 2023-06-30 00:02
RTFM

**Closed by donho** 2023-06-30 00:02 UTC
