### ISSUE TITLE
Double click on empty line opens the 1st URL link in the Notepad tab

### ISSUE THREAD

**Issue by sunnymishra** [notepad-plus-plus/notepad-plus-plus#8860] opened 2020-09-15 11:03 UTC
### Description of the Issue
Double click on empty line opens the 1st URL link in the Notepad tab

### Steps to Reproduce the Issue
1. Notepad++ v7.8.9 on Windows 10 laptop
2. Open a new tab enter any URL in the 1st line
3. Add several more lines of general text below the 1st line
4. Take the cursor to a line that is empty. It can be an empty line in between 2 lines of text or it can be an empty line as the last line of the opened tab
5. Double click on the Empty line

### Expected Behavior
Notepad should only open the URL in the browser if I am double-clicking the URL in the Notepad tab, not while double-clicking on an empty line

### Actual Behavior
Notice Notepad tries to open the URL in my Chrome browser. This is the same URL which is mentioned in the 1st line of the opened tab in Notepad

### Debug Information
Notepad++ v7.8.9 on Windows 10 laptop

**Comment by sasumner** [comment] 2020-09-15 11:15
Duplicate of #8581

**Closed by sasumner** 2020-09-15 11:15 UTC
