### ISSUE TITLE
Style colors are not inverted for dark themes

### ISSUE THREAD

**Issue by hgdagon** [notepad-plus-plus/notepad-plus-plus#9687] opened 2021-03-23 07:48 UTC
### Description of the Issue

Certain filetypes aren't readable when using a dark theme (noticed on Markdown files with Twilight theme)

### Steps to Reproduce the Issue

1. Set theme to Twilight
2. Open a Markdown file

### Expected Behavior

Darker color fonts should be inverted on dark themes.

### Actual Behavior

This is how a Markdown file shows up:
![MD](https://user-images.githubusercontent.com/15173076/112111236-29930b80-8b71-11eb-8bf3-d286c34bf20e.png)
Looks slightly better with global background color enabled, but still not entirely readable:
![MD_GlobalBackground](https://user-images.githubusercontent.com/15173076/112111340-4c252480-8b71-11eb-818f-7328c7596caa.png)

**Comment by mere-human** [comment] 2021-03-23 17:24
Seems a duplicate of #9649

**Comment by sasumner** [comment] 2021-03-23 17:58
Closing as duplicate

**Closed by sasumner** 2021-03-23 17:58 UTC
