### ISSUE TITLE
Redirection error when editing a file in c:\windows\system32  on Win7/64

### ISSUE THREAD

**Issue by jpsamson** [notepad-plus-plus/notepad-plus-plus#1168] opened 2015-11-20 11:16 UTC
Have test text file file in c:\windows\system32.  ( mine is hello.cmd )
Edit it with notepad++, then save it.

The edited result is in c:\windows\syswow64.
The file in c:\windows\system32 is unchanged.

You may have to check the problem in other redirected locations ( c:\program files for instance ) 

Notepad++ 6.8.6  ( same problem with earlier versions)
Windows 7 sp1 64 bits

**Comment by linquize** [comment] 2015-11-20 14:16
Notepad++ is a 32-bit executable, so Windows automatically redirects to `C:\Windows\SysWOW64`

**Comment by jpsamson** [comment] 2015-11-26 14:55
Yes, but Notepad++ can call Wow64DisableWow64FsRedirection()  and then Wow64RevertWow64FsRedirection()

See sample code on https://msdn.microsoft.com/en-us/library/windows/desktop/aa365743(v=vs.85).aspx

**Comment by kejones999** [comment] 2015-11-30 17:42
Hi,

 I just noticed this too. It would be soooo cool if the above was implemented.

  As an Interesting addendum to this, after saving the file, NPP (v6.8.6 on Win7SP1, x64) subsequently only opens the version in the Wow64 directory regardless of attempts to open the version in SYSTEM32. That had me scratching my head this afternoon :-)

  I'm not sure if I should bug that separately but I guess if there's matching file open routines, they could benefit from the same calls to balance the situation out :-} 

Regards,

Keith

**Comment by YueLinHo** [comment] 2016-02-22 09:32
> That had me scratching my head this afternoon.

Me, too. Few hours gone!

**Comment by MetaChuh** [comment] 2019-04-11 00:34
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:34 UTC
Labels: enhancement
