### ISSUE TITLE
Doc comments break code folding in embedded JavaScript

### ISSUE THREAD

**Issue by LMLB** [notepad-plus-plus/notepad-plus-plus#5581] opened 2019-04-24 14:26 UTC
### Description of the Issue
Code folding gets confused upon seeing doc comments (`/** … */`) in embedded JavaScript.

### Steps to Reproduce the Issue
Paste the following code in a file with the language set to HTML:

```
<div>

  <script>

      /**

      */

  </script>

</div>
```

### Expected Behavior
Code folding for the comment ends on `*/`.

### Actual Behavior
Code folding for the comment doesn't end on `*/`, but on `</script>`, and code folding after that gets shifted as well (for the example above, the `<script>` ends on the `</div>`).

![screenshot](https://user-images.githubusercontent.com/6322603/56666880-0291dd80-66ad-11e9-89ee-dc0cd9548872.png)

### Debug Information
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment] 2020-09-22 11:38
Same/similar to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4560 and https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7796.

**Comment by rdipardo** [comment] 2022-01-20 02:48
To clarify, the HTML lexer does not to fold [documentation comments] ([`SCE_HJ_COMMENTDOC`]) because __*it was designed to ignore them*__: 

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/234941c180548f5d39503a057feccedd01b4c453/scintilla/lexers/LexHTML.cxx#L1094

This is not a bug; it's a feature request to include documentation comment folding in embedded scripts.


[`SCE_HJ_COMMENTDOC`]: https://github.com/notepad-plus-plus/notepad-plus-plus/blob/234941c180548f5d39503a057feccedd01b4c453/scintilla/lexers/LexHTML.cxx#L704
[documentation comments]: https://www.doxygen.nl/manual/docblocks.html

**Comment by rdipardo** [comment] 2022-04-08 03:21
Fixed in https://github.com/ScintillaOrg/lexilla/commit/0bd13d84b3fef7a72553ab95c43d0d4c9677f70f

**Closed** 2022-07-24 01:50 UTC
Labels: scintilla dependent
