### ISSUE TITLE
Complete loss of opened file content after a crash

### ISSUE THREAD

**Issue by pdelorenzo974** [notepad-plus-plus/notepad-plus-plus#4346] opened 2018-03-26 13:54 UTC
### Description of the Issue
When Notepad++ crashes, every file with a RED TAB (modified & not saved state) is losing ALL it's content! When you restart Notepad++ it automatically reopen it completely empty!!!
I'm using latest version but this behavior exist for a long time and it's getting REALLY troublesome!
Do you really know what is it to lose a lot of work and not beeing able to recover it????
For now I just kept using Notepad++ because it doesn't crash OFTEN but now when it does it's a NIGTHMARE!!!

### Steps to Reproduce the Issue
1.  Open a file inside Notepad++
2.  Modify the file
3.  DO NOT save the file
4. Crash Notepad++
5. Re-start Notepad++
6. See for yourself!

### Expected Behavior
THE BEST EXPECTED BEHAVIOR: do not lose anything EVEN MODIFIED FILES AND FILE STATUS
THE MINIMUM EXPECTED BEHAVIOR YET TO BE: ALL SOFTWARE ARE ABLE TO AT LEAST RECOVER THE LATEST CONTENT SAVED ON DISK BUT THIS IS NOT EVEN TRUE WITH YOUR NOTEPAD++ ALL CONTENT IS WIPED OUT!!!!

### Actual Behavior
Each and every opened files with RED TAB (modified not yet saved) COMPLETELY WIPED OUT!!!!
EMPTY!!!! NOT MORE CONTENT!!!!!! COMPLETELY BLANK!!!!!!!

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (32-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll

**Comment by stantonium** [comment] 2018-04-29 15:37
This happened to me with the v7.5.6 64 bit version, could not get the debug info.  Unacceptable risk. Deleting npp++ until this bug is fixed.

**Comment by stantonium** [comment] 2018-04-29 15:44
duplicate of issue 2883?

**Closed** 2018-10-03 00:38 UTC
