### ISSUE TITLE
A weird Find dialog glitch 

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#10511] opened 2021-09-06 17:40 UTC
**STR:**
Download a portable NPP 8.14.
Download [Notepad++.Win32.Release.exe](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40651601/job/708pabs0b2886x10/artifacts) (https://github.com/notepad-plus-plus/notepad-plus-plus/commit/156784722a46fd250128ef415d6813a8171de5c7) and place it in the portable NPP 8.14 folder.
Run Notepad++.Win32.Release.exe.
Open the Find dialog.
Move/Resize the Find dialog.
Close NPP.
*Delete config.xml in the portable NPP 8.14 folder.*
Restart NPP.
Open the Find dialog.

**Result:**
![תמונה](https://user-images.githubusercontent.com/10229320/132248674-2bfc45f1-6833-4fef-9e98-53536abf8b91.png)

![תמונה](https://user-images.githubusercontent.com/10229320/132249670-60851578-7bb0-4ed1-b83a-7680d4c784a1.png)

**NOTE:** If the problem doesn't happen after the first time, repeat the STR.
I've encountered the issue in other scenarios too, but the above STR are relatively consistent.
I *suppose* other similar issues might pop up.

***

Notepad++ v8.1.4   (32-bit)
Build time : Sep  5 2021 - 14:35:33
Path : C:\Users\---\Downloads\npp.8.1.4.portable\Notepad++.Win32.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1255
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ivan-u7n** [comment] 2021-09-06 19:17
The commit and the bug are not related, I was able to reproduce the bug with [a build from the previous commit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40650714/job/v9sgys2c8vg0l4t9/artifacts) too:
![image](https://user-images.githubusercontent.com/81974034/132254316-0a92c445-1981-4509-8704-a167070a6f2d.png)
```
Notepad++ v8.1.4   (32-bit)
Build time : Sep  5 2021 - 11:30:28
Path : F:\develop\git\notepad-plus-plus\PowerEditor\bin\Notepad++.Win32.Release.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2114
Current ANSI codepage : 1251
Plugins : none
```

Moreover 64-bit builds seem unaffected. At least I wasn't able to get something like this in 64-bit builds done by GCC, but 32-bit ones not often, but sometimes do show something wierd:
![image](https://user-images.githubusercontent.com/81974034/132254680-0b7ae118-35c5-46a5-add2-c50808922ff7.png)
```
Notepad++ v8.1.4   (32-bit)
Build time : Sep  6 2021 - 21:37:23
Built with : GCC 8.1.0
Path : F:\develop\git\notepad-plus-plus\PowerEditor\bin\NotepadPP-release.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2114
Current ANSI codepage : 1251
Plugins : none
```

**Comment by Yaron10** [comment] 2021-09-06 20:27
@ivan-u7n,

> The commit and the bug are not related, I was able to reproduce the bug with a build from the previous commit too:

My sincere apologies. I've been able to reproduce it with the previous commit too.

But - 
I had tested it many times with the previous commit before posting the issue, and did not encounter the problem.
And I have repeatedly tested it again after reading your reply.
- With the previous commit the issue occurred in 1 out of 30 tries.
Whereas with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/156784722a46fd250128ef415d6813a8171de5c7 - the ratio is 8 out of 10 tries. 

So the root cause is probably not https://github.com/notepad-plus-plus/notepad-plus-plus/commit/156784722a46fd250128ef415d6813a8171de5c7, but it seems to trigger and make the problem much more frequent.

What do you think?
When you encounter the problem - _could you please switch between the builds and note the ratio_?

Thank you for your work and for looking into it. 👍 

***

I was not able to reproduce the issue on Win 7 32-bit.
But on Win 10 64-bit, the problem exists with NPP 64-bit as well.

![תמונה](https://user-images.githubusercontent.com/10229320/132258566-275bbae3-f966-4602-9b4d-ff3d5b94a2bf.png)

**Comment by ivan-u7n** [comment] 2021-09-06 21:38
Hm, I'm getting this wierd behaviour in MSC compiled Notepad++ almost every time I launch it. (I'm testing on [a far away build](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40604219).)

Moreover for me the steps to reproduce are even simpler:
1. Delete `config.xml`.
2. Start Notepad++.
3. Open Find dialog.
4. Try to resize it.

It looks like some strange (for it doesn't show in 64-bit GCC build) bug in the resizing function of this dialog. Or maybe something fishy is going on with HiDPI support. And GCC build currently doesn't support this feature.

**Comment by Yaron10** [comment] 2021-09-06 22:21
I've been using the "resize" functionality for years and never encountered a problem.
I was not even "testing" the latest commit. It just happened during a normal use.

I can not reproduce your case with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40604219.

On my machine the issue (my STR) frequency is consistent.

> With the previous commit the issue occurred in 1 out of 30 tries.
Whereas with 1567847 - the ratio is 8 out of 10 tries.

Interesting. :)

Can you reproduce it with 8.14 release?

I'll continue tomorrow. Thanks again.

**Comment by ivan-u7n** [comment] 2021-09-07 11:29
I also wasn't able to reproduce the bug using 8.1.4 32-bit release, but in builds from AppVeyor it is rather easy.

**Comment by donho** [comment] 2021-09-07 11:39
@ivan-u7n Indeed. I'm pretty sure it's link to the configuration of Appeveyor.
Any idea about this bug @chcg  ?

**Comment by ivan-u7n** [comment] 2021-09-07 11:44
I noticed that they recently updated Visual Studio in their 2019 image, maybe that is the culprit… However I'm no expert here.

**Comment by Yaron10** [comment] 2021-09-07 12:06
Can you reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40581479/job/g6jekcrm1aj06b6a/artifacts?

I can not. But I've learned it's tricky and I should be careful.

@donho,

The first time I encountered the issue was with a Visual Studio build.

That build had some modifications for my personal use. But I doubt they are the cause.
I'll be by a PC with Visual Studio later today. I can build the master as is and test it.

**Comment by donho** [comment] 2021-09-07 12:19
After a serial tests, the culprit is 156784722a46fd250128ef415d6813a8171de5c7 (Make number of languages and and styles unlimited and independent), which make the difference - at least it made difference "at this moment of commit". I just don't see why the modification of this PR will cause the result of Find dialog.

> I noticed that they recently updated Visual Studio in their 2019 image

@ivan-u7n By "They" what do you mean? And when has it changed? From my memory, we have used VS2019 in Appveyor for a while.

> I'll be by a PC with Visual Studio later today. I can build the master as is and test it.

@Yaron10 Thank you, but I think it's not necessary. @ivan-u7n and I we both cannot reproduce it from our local build so I guess it's clearly it's an environment issue to me.
I'll do a PR to revert the commit in question, the behaviour of revert binary will give us a more clear picture.

**Comment by Yaron10** [comment] 2021-09-07 12:30
@donho,

> After a serial tests, the culprit is 156784722a46fd250128ef415d6813a8171de5c7 (Make number of languages and and styles unlimited and independent),

That was my initial assumption too.
But later both @ivan-u7n and myself were able to reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40650714/job/v9sgys2c8vg0l4t9/artifacts.
(As I've mentioned, it's not as easy to reproduce with that build).

**Comment by ivan-u7n** [comment] 2021-09-07 12:31
@Yaron10
> Can you reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40581479/job/g6jekcrm1aj06b6a/artifacts?
>
> I can not. But I've learned it's tricky and I should be careful.

With both 32-bit and 64-bit binaries from this build I can't, or at least it's so infrequent that I too can't catch it too.

@donho 
> By "They" what do you mean? And when has it changed? From my memory, we have used VS2019 in Appveyor for a while.

By "they" I mean the AppVeyor team. I noticed it by [this commit](https://github.com/appveyor/website/commit/cecf8eeec975aec5148ea4f7fa98431afda3c4a4). I was looking for LLVM version available, but noticed an update to Visual Studio too.

**Comment by chcg** [comment] 2021-09-07 12:32
@donho VS2019 is updated from time to time (see https://www.appveyor.com/docs/build-environment/#image-updates) to the current patch level currently it is at 16.11.2 (https://www.appveyor.com/docs/windows-images-software/#visual-studio-2019 and https://www.appveyor.com/updates/). 
See also https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-history and https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes on the updates available from microsoft.

Is there a difference between debug and release builds? Maybe a VS2019 build with V142 + Address sanitizer could help here if it is a memory corruption issue.

**Comment by Yaron10** [comment] 2021-09-07 12:37
@ivan-u7n,

>  Can you reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40581479/job/g6jekcrm1aj06b6a/artifacts?
I can not. But I've learned it's tricky and I should be careful.
>> With both 32-bit and 64-bit binaries from this build I can't, or at least it's so infrequent that I too can't catch it too.

Does that mean it's not AppVeyor vs. Visual Studio?

**Comment by ivan-u7n** [comment] 2021-09-07 12:43
@donho the binary from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40674060/job/oommfcsda12g6k7r/artifacts still exhibits this behaviour:
![image](https://user-images.githubusercontent.com/81974034/132346229-f24383a0-b2f6-4146-a5c6-2b363db31f69.png)

**Comment by donho** [comment] 2021-09-07 12:44
The revert culprit commit 32bit release binary is available here:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40674060/job/oommfcsda12g6k7r/artifacts

Apparently the bug is fixed by reverting this commit.

**Comment by donho** [comment] 2021-09-07 12:49
@ivan-u7n 
> the binary from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40674060/job/oommfcsda12g6k7r/artifacts still exhibits this behaviour:

That's strange... I cannot reproduce it anymore. Are you sure that you're using the same binary?

@Yaron10 Could you test it from your side please?

**Comment by Yaron10** [comment] 2021-09-07 12:58
@donho,

Yes, I can reproduce it.

![תמונה](https://user-images.githubusercontent.com/10229320/132348569-9c8a110b-5993-4afb-aa1f-a88565c7007f.png)

**Comment by donho** [comment] 2021-09-07 13:00
@Yaron10 
> But later both @ivan-u7n and myself were able to reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40650714/job/v9sgys2c8vg0l4t9/artifacts.

Wired, I did test it. And I do test it again, this version works to me.

**Comment by Yaron10** [comment] 2021-09-07 13:03
@donho,

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10511#issuecomment-913842531

> My sincere apologies. I've been able to reproduce it with the previous commit too.
But -
I had tested it many times with the previous commit before posting the issue, and did not encounter the problem.
And I have repeatedly tested it again after reading your reply.
    With the previous commit the issue occurred in 1 out of 30 tries.
    Whereas with 1567847 - the ratio is 8 out of 10 tries.
So the root cause is probably not 1567847, but it seems to trigger and make the problem much more frequent.

**Comment by ivan-u7n** [comment] 2021-09-07 13:09
I'm not so sure, even if I close all instances of Notepad++ running and start the testing binary, it's still about 2 out of 3 runs that exhibit the bug.

**Comment by ozone10** [comment] 2021-09-07 14:07
I can reproduce this starting with commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a (https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40582212/job/b5ty66fibor0rukx/artifacts)

**Comment by Yaron10** [comment] 2021-09-07 14:20
> I can reproduce this starting with commit 88ee2ed (https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40582212/job/b5ty66fibor0rukx/artifacts)

👍 

That's why I asked (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10511#issuecomment-914247955):
> Can you reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40581479/job/g6jekcrm1aj06b6a/artifacts?
I can not. But I've learned it's tricky and I should be careful.

**Comment by donho** [comment] 2021-09-07 14:29
I just changed a laptop, the first test is abkhazian.xml commit - let's say commit 0-1.
I could reproduce only once commit 0-1, then I cannot reproduce anymore after +10 times of relaunch.

Then I download the binary of php DarkMode commit  let's say commit 0-2. I cannot reproduce the bug at all.

The 3rd try is the binary of commit about style Unlimited (supposed culprit one initially), let's say commit 0, I can reproduce only once, in another look:

![image](https://user-images.githubusercontent.com/90293/132360346-4cd8ae69-1e79-4bd4-9385-69af6fccb6f6.png)

**Comment by donho** [comment] 2021-09-07 14:37
> I can reproduce this starting with commit [88ee2ed](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a) (https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40582212/job/b5ty66fibor0rukx/artifacts)

Ah! With this binary, I don't even need to delete `config.xml` :
![image](https://user-images.githubusercontent.com/90293/132363376-923a812b-1eef-4905-8d40-72e32262a2ef.png)

**Comment by Yaron10** [comment] 2021-09-07 14:41
@donho,

> Ah! With this binary, I don't even need to delete config.xml.

👍 

Yes, it sometime happens without deleting config.xml.

> I've encountered the issue in other scenarios too, but the above STR are relatively consistent.
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10511#issue-989352678

**Comment by donho** [comment] 2021-09-07 14:45
@Yaron10 

> Can you reproduce it with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40581479/job/g6jekcrm1aj06b6a/artifacts?
I can not. But I've learned it's tricky and I should be careful.

So from these 2 commits:

![image](https://user-images.githubusercontent.com/90293/132364011-6205d40e-bbb3-47af-a30f-4e32c11f7cb6.png)

You think "Fix crash regression..." is the culprit one because you cannot reproduce in "Fix build system error" ?

**Comment by Yaron10** [comment] 2021-09-07 14:49
> You think "Fix crash regression..." is the culprit one because you cannot reproduce in "Fix build system error"

Yes, "Fix crash regression..." seems to be the culprit.
But we have learned this issue is tricky and illusive. So I'd take it with some grain of salt. :)

**Comment by donho** [comment] 2021-09-07 14:55
I cannot reproduce the bug (at least so far) in the binary of  "Fix crash regression...".
I can revert "Fix crash regression..." manually in my new create PR. We can take time and try this binary.

**Comment by donho** [comment] 2021-09-07 15:06
> Does that mean reverting [1567847](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/156784722a46fd250128ef415d6813a8171de5c7) as well?

Yes. Both of them.

**Comment by Yaron10** [comment] 2021-09-07 15:07
👍 
Just seen it in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10515.

**Comment by donho** [comment] 2021-09-07 15:12
FYI:
https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40676481/job/dahhwpnw77k0t4hw/artifacts

Please test this binary for reproducing Find dialog glitch (Hopefully it's fixed in it).
Note that revert the fixes of #10454 and #10206

**Comment by ivan-u7n** [comment] 2021-09-07 15:25
I can't reproduce this bug in the 32-bit build from https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40676481, but the 64-bit one now crashes on opening files.

However for the life of me, I can't fathom what in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a can cause this strange behaviour.

**Comment by Yaron10** [comment] 2021-09-07 15:31
I can't reproduce it either with https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40676481/job/dahhwpnw77k0t4hw/artifacts. I'll keep testing it.

Thank you all.

@ivan-u7n,

My apologies again.

**Comment by Yaron10** [comment] 2021-09-07 15:57
> I mean it seems like a concurrency issue, but creating a bunch of styles and resizing elements of a window seems so unrelated that it's not funny.

I *suppose* that resizing the Find dialog is not the only affected functionality.

**Comment by donho** [comment] 2021-09-07 17:04
@ivan-u7n 
> However for the life of me, I can't fathom what in [88ee2ed](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a) can cause this strange behaviour.
> 
> EDIT: I mean it seems like a concurrency issue, but creating a bunch of styles and resizing elements of a window seems so unrelated that it's not funny.

It seems the corrupted stack state which made x64 binary opening file crash, still exist after "Make number of languages and and styles unlimited and independent" commit. Such corrupted state made File dialog layout mess up in some circumstance.

**Comment by ivan-u7n** [comment] 2021-09-07 17:46
@donho

> It seems the corrupted stack state which made x64 binary opening file crash, still exist after "Make number of languages and and styles unlimited and independent" commit. Such corrupted state made File dialog layout mess up in some circumstance.

But https://github.com/notepad-plus-plus/notepad-plus-plus/commit/88ee2eddb043193a1162957a862394dfa620781a (Fix the crash regression due to the array size increase) removed a possible reason for the corruption — huge-sized objects.

However this bug seems to be a rather strange one, because I wasn't able to reproduce it in 64-bit GCC build at all. Thus it seems to be also compiler dependent (and non-debugable by me). And that's scary, for it can appear again anytime…

By the way, maybe I missed it, but did a build done by you (as opposite to AppVeyor) has this bug?

**Comment by donho** [comment] 2021-09-07 20:43
Even the usage of dynamic allocation on all the object of StylerArray (based on the latest master), this bug is present:

![image](https://user-images.githubusercontent.com/90293/132407833-6dd14d94-7912-4860-ab26-6d22d2df782d.png)

I have really no idea.

**Comment by donho** [comment] 2021-09-07 20:50
@ivan-u7n 
> By the way, maybe I missed it, but did a build done by you (as opposite to AppVeyor) show this bug?

All the tests I done before are used the Appveyor's builds, except this one: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10511#issuecomment-914617113

**Comment by donho** [comment] 2021-09-07 21:17
For what it's worth: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/10522

**Comment by ivan-u7n** [comment] 2021-09-07 21:39
Hm, I skimmed through the source code and haven't found any allocations of this potentially huge objects on the stack. The main big object (NppParameters) is created using **new** as a singleton.

Why then it were crashing in the first place. I certainly remember my debugging session with `gdb` and an attempt to get backtrace after a crash giving nothing useful with a message about a possible stack corruption…

**Comment by ivan-u7n** [comment] 2021-09-08 21:10
@Yaron10 Can you also check that both 32- and 64-bit binaries from #10524 ([AppVeyor build](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/40695497)) don't have this bug? I tested them myself and can't reproduce it anymore, but two sets of eyes are better than one.

And if you know of any other dialogs that behave this way, let me know so they too can be fixed, for the cause of this bug was in part the code of the Find dialog itself.

**Comment by Yaron10** [comment] 2021-09-08 22:49
@ivan-u7n,

👍 
I've tested it with both AppVeyor and VS builds, and I can not reproduce the glitch.
I'm glad you've found it.

Thank you.

@donho,

👍 
Thank you.

**Closed** 2021-09-09 10:46 UTC

**Comment by donho** [comment] 2021-09-10 11:39
@Yaron10 
Thank you for discovering this display glitch - many users (including us) didn't see it.

@ivan-u7n 
The bug cannot be reproduced anymore with PR you provide. Thank you for finding the real cause for this nasty bug.

**Comment by Yaron10** [comment] 2021-09-10 12:01
@donho,

I'm glad it was found and solved.
Thank you and @ivan-u7n for the perseverance and dedication.

**Comment by ivan-u7n** [comment] 2021-09-10 21:18
And the bug is over 4 years old: https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0d90ad13747da4f534312e912157a96efdf93151. It seems strange that it didn't appear before…

I'm also glad that the bug was found and fixed, because it's abnormal when small changes cause strange behaviour in unrelated areas. I'd call finding the reason of this bug to be the matter of prestige. 😎
