### ISSUE TITLE
Scintilla 5: A glitch in Search Results

### ISSUE THREAD

**Issue by Yaron10** [notepad-plus-plus/notepad-plus-plus#11995] opened 2022-08-06 23:16 UTC
**REF:**
https://community.notepad-plus-plus.org/post/78903

**STR:**
Paste `Test` in a new document.
Open the Find dialog and search for `AAA`.
Search for `Test`.
Search for `AAA`.
Search for `Test`.
Uncollapse (Unfold) all (_BTW, Uncollapse is confusing IMO_).

This is what you should see at this stage:
![תמונה](https://user-images.githubusercontent.com/10229320/183268049-c1a2f84d-19a0-4b94-a7ec-ebcb001fa938.png)

Delete the line I've marked in red:
![תמונה](https://user-images.githubusercontent.com/10229320/183268079-009635f5-e36d-49e4-b2ed-417807ac32e8.png)

Click on the red-marked line in the following screenshot:
![תמונה](https://user-images.githubusercontent.com/10229320/183268278-70a2c364-5d9f-4c8b-81ca-781b53e2d9ca.png)

**Result:**
The fold image is missing in the second `Test` results.
![תמונה](https://user-images.githubusercontent.com/10229320/183268233-ef11fea8-974b-4ed0-bdd3-07d1ca3d3af6.png)

**NOTE:**
Introduced in NPP 8.4 (Scintilla 5).
The issue is not specific to "Find in Files".

**Comment by alankilborn** [comment] 2022-08-07 11:50
>BTW, Uncollapse is confusing IMO

Other programs pair "Expand" with "Collapse".
"Uncollapse" here probably doesn't bother me too much.

It is elsewhere as well, as I'm sure you know:

![image](https://user-images.githubusercontent.com/77065706/183289136-37313f6c-72ae-4841-9e4f-e9e53e5085ff.png)

Although curiously, in that, "Fold" and "Unfold" are introduced as well.

**Comment by Yaron10** [comment] 2022-08-07 12:17
I usually do not use the English interface.

https://community.notepad-plus-plus.org/post/78903
> 6. Collapse all the results.

The OP must have meant "**Uncollapse**".

So "Collapse/Uncollapse" is not clear enough. Especially for non-native English speakers. 

> Other programs pair "Expand" with "Collapse".

That's better. 
Or "Fold/Unfold".

And obviously it should be consistent.

**Comment by alankilborn** [comment] 2022-08-07 12:25
@Yaron10 

>And obviously it should be consistent.

Another part of the inconsistency:

![image](https://user-images.githubusercontent.com/77065706/183290394-090bedc8-1820-464b-ad77-25338c436b78.png)

And this one adds a new bad twist:  A user's first thought might be of "folders" in the Windows file system!  :-)

**Comment by Yaron10** [comment] 2022-08-07 12:35
> A user's first thought might be of "folders" in the Windows file system! :-)

If I remember correctly, the original NPP Hebrew translator indeed confused/mixed those completely different terms. :)

"Folding Margin Style" would probably be better.

**Comment by donho** [comment] 2022-08-24 14:08
@alankilborn 
> And, indeed, it seems as if "Fold" and "Unfold" _EVERYWHERE_ would be the best choice.
> Banish "Collapse" and "Uncollapse"!

This subject deserves another issue. Could you open an issue for it please?

**Comment by alankilborn** [comment] 2022-08-24 14:50
> This subject deserves another issue. Could you open an issue for it please?

Done, in #12035

**Comment by donho** [comment] 2024-08-04 12:58
Cannot reproduce in v8.6.9.
It seems the bug has been fixed in the newest version of Scintilla.

**Closed by donho** 2024-08-04 12:58 UTC
