### ISSUE TITLE
[BUG v6.9] StatusBar field's contents are clipped.

### ISSUE THREAD

**Issue by sky5walk** [notepad-plus-plus/notepad-plus-plus#1536] opened 2016-02-23 16:57 UTC
The first StatusBar field is too wide and takes too much horizontal space, causing the remaining fields to clip their rightmost information. Notice 2nd & 3rd fields are clipped when selecting multiple lines from a large file. This is troublesome when selecting lines in a large text file and I cannot see how many are selected, nor see the total number of lines in the file. Of course I can scroll to the bottom to see the line count, but that is a waste of time.
My previous post(#356) on this bug was incorrectly labeled as an enhancement?!!

**Comment by dail8859** [comment] 2016-02-24 13:44
Please do not repost issues you have already posted. I agree that this is certainly an issue that needs fixed which is likely due to the DPI scaling. 

Duplicate of #356, #366, #539, #1447

**Comment by sky5walk** [comment] 2016-02-25 03:33
Ordinarily I would not repost, but my prior bug report was mislabeled as enhancement and no one would reply. And I do not agree this is DPI related? The statusbar fields are fixed length and cannot contain enough characters. It is a design bug. Allow the fields to resize or allot an even amount of space between them.

**Closed** 2016-05-16 16:20 UTC

**Comment by sky5walk** [comment] 2016-08-11 18:51
How many times must I resubmit this BUG report?! It is still broken as of v6.9.2.
![bug_notepad v692_statusbar](https://cloud.githubusercontent.com/assets/13093122/17600781/163a34e2-5fd3-11e6-8888-d1d4972c646f.PNG)
[BUG_Notepad++v692_statusbar.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/413963/BUG_Notepad.v692_statusbar.txt)
