### ISSUE TITLE
Find Previous not working in version 8.5.8

### ISSUE THREAD

**Issue by NoahAndrews** [notepad-plus-plus/notepad-plus-plus#14264] opened 2023-10-24 18:44 UTC
### Description of the Issue
Pressing Shift-Enter when using Find no longer does anything. When the checkbox next to the Find Next button is checked, the Find Previous (up arrow) button is grayed out. I believe this behavior is new with the 8.5.8 update I had just installed (though I'm not 100% sure which version I was using prior).

### Steps to Reproduce the Issue

1. Press Control-F
2. Enter text that occurs multiple times in the current document
3. Press Enter a few times
4. Press Shift-Enter

### Expected Behavior

The previous occurrence of the text should be highlighted

### Actual Behavior

Nothing happens

### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Users\Noah\AppData\Local\Temp\e64ec4df-93a5-4a7a-a4cf-060cd7d6fb59_cf28396a-9d23-4655-b8ee-b8f24318e591.zip.b59\robotControllerLog.txt.4"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2428
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by alankilborn** [comment] 2023-10-24 23:13
You're probably in Regular Expression for the Search Mode.
This doesn't work in the Backward direction, due to unusual results obtained with certain expressions; i.e., it is intentionally disabled.

**Comment by freezer2022** [comment] 2023-10-25 05:24
> Find Previous not working

Read manual before reporting issue: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10712#issuecomment-951392169

Duplicate of :
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10712
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10476
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9184
- https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3533

**Comment by donho** [comment] 2023-10-30 18:01
It works for me.
As @alankilborn have said: 
You're probably in Regular Expression for the Search Mode.

**Closed by donho** 2023-10-30 18:01 UTC

**Comment by NoahAndrews** [comment] 2023-10-31 17:57
That was it, thanks
