### ISSUE TITLE
installer: "start NPP now" leads to "This file does not have a program associated with it for performing this action" (lnk file)

### ISSUE THREAD

**Issue by GitMensch** [notepad-plus-plus/notepad-plus-plus#2969] opened 2017-02-28 08:43 UTC
### Description of the Issue
After installing with the "start NPP now" option enabled I get the error

> This file does not have a program associated with it for performing this action. Please install a program or, if one is already installed, create an association in the Default Programs control panel.

This happened when updating NPP on two PCs today: Windows 10 and Windows 2012 Server RC2. Looks like an installer problem, likely in combination of some MS security update ?!?

### Steps to Reproduce the Issue
1. start NPP as normal user (may not necessary but was done in both cases)
2. use help->update NPP
3. NPP must be closed ... "yes"
4. enter admin credentials in UAC prompt
5. install with default options, including "start NPP now"
6. get error message (instead of a started NPP - NPP can be started via created desktop link without any issue)

**Comment by SinghRajenM** [comment] 2017-02-28 19:03
Mostly look like OS issue. I could reproduce the issue on Win10.

Please try [Microsoft link](https://social.technet.microsoft.com/Forums/en-US/65707d36-8680-4043-9cb0-1da08767d476/this-file-does-not-have-a-program-associated-with-it-for-performing-this-action-please-install-a?forum=win10itproapps) and let us know problem continue to persist.

**Comment by GitMensch** [comment] 2017-02-28 19:11
While I think that the issue roots in the OS (actually two OS with the same architecture: client+server) it is obviously an issue that happens with the installer. I guess the solution is to run the program after the installation different than the current version does.

@SinghRajenM The link you've provided is specific to "opening system settings raise this error" but the issue here is "open a lnk file raises the error" (which is done by the installer).

**Comment by SinghRajenM** [comment] 2017-02-28 19:17
1. Are you able to open it from start menu? Start->Notepad++->Notepad++
2. Also are you able to open it by double clicking on "%allusersprofile%\Microsoft\Windows\Start Menu\Programs\Notepad++\Notepad++"

**Comment by GitMensch** [comment] 2017-02-28 19:36
Yes, both.

**Comment by SinghRajenM** [comment] 2017-02-28 19:38
Please paste debug info from Notepad++ -> ? -> Debug Info...
Will check it tomorrow. Thank you.

**Comment by GitMensch** [comment] 2017-03-01 07:36
```
Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll LocationNavigate.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll SourceCookifier.dll
```

As this is only a post-install one-time issue created by the installer the plugins are not really interesting. The one thing that is currently missing in the Debug info and which is *very*  important on Windows 10 is the build number which seems to be available in `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuildNumber`. It is 14393 on this system.
Should I open an issue for output the build number if the registry key can be read?

**Comment by SinghRajenM** [comment] 2017-03-02 18:44
@GitMensch I've tried to reproduce this issue. Even after multiple tries on multiple system, I could not reproduce. I feel this is more n less related to OS only.

FYI, installer just try to execute the lnk (actually shortcut) file kept in %temp% folder which **MUST** be executed if you're able to execute "%allusersprofile%\Microsoft\Windows\Start Menu\Programs\Notepad++\Notepad++" manually.

**Comment by GitMensch** [comment] 2017-03-02 19:13
It *is* an OS issue. The tested system just don't start any lnk files directly. The installer part here is that a direct execution of `%allusersprofile%\Microsoft\Windows\Start Menu\Programs\Notepad++\Notepad++` would work and would be preferable to creating and executing `%temp%\npp.lnk`.

**Comment by alexandroid** [comment] 2017-04-06 15:34
I just hit the same issue at the end of the update installer (Win10). I am able to 100% reproduce it by re-running `C:\Users\Alex\AppData\Local\Temp\npp.7.3.3.Installer.x64.exe` manually.

Copy-paste of the dialog at the end:

```
[Window Title]
C:\Users\admin\AppData\Local\Temp\notepad++.lnk

[Content]
This file does not have a program associated with it for performing this action.
Please install a program or, if one is already installed, create an association in the
Default Programs control panel.

[OK]
```

Perhaps the problem is that it tried to launch Notepad++ after elevation to 'admin' and Windows blocks it, because only installer itself is allowed to be elevated? Shouldn't the installer run the Notepad++ using the user account instead?

The `.lnk` file is present, so it is not a simply 'missing file' problem. Here are the shortcut files I have:

```
"C:\Users\admin\AppData\Local\Temp\notepad++.lnk" 
"C:\Users\admin\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk" 

"C:\Users\Alex\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Accessories\Notepad.lnk" 
```

**Comment by SinghRajenM** [comment] 2017-06-01 16:47
Now, notepad++ launching way has been changed. Please check the latest version (V7.4.1)

**Comment by SinghRajenM** [comment] 2018-11-09 17:03
@GitMensch If this issue does not occur, then please close this issue. Thank you!

**Comment by alexandroid** [comment] 2018-11-11 07:07
I personally cannot reproduce it anymore.

**Comment by SinghRajenM** [comment] 2018-11-27 06:01
@chcg, I feel this ticket can be closed.

**Closed** 2018-11-27 07:47 UTC
