### ISSUE TITLE
Using "Move to other view" on unsaved, blank documents destroys tab

### ISSUE THREAD

**Issue by mmseng** [notepad-plus-plus/notepad-plus-plus#10909] opened 2021-12-13 01:54 UTC
### Description of the Issue

When I have a few unsaved tabs open, including a new blank one, moving them back and forth between the left and right views can destroy a blank tab. Doesn't seem to happen with tabs which contain content, or which are blank but have undo history.

### Steps to Reproduce the Issue

1. Open Notepad++ with no tabs (except the default "new 1" tab with no content).
2. Open 2 more new tabs with no content, for a total of 3 all in the "full" view.
3. Move "new 3" tab to other view, splitting the full view into left and right views, with "new 1" and "new 2" on the left and "new 3" on the right. Works fine.
4. Move "new 2" tab to other view. The "new 2" tab moves over, but the "new 3" tab disappears.

### Expected Behavior

Expected "new 3" tab to persist in right view.

### Actual Behavior

"new 3" tab disappeared entirely.

### Debug Information

Notepad++ v8.1.9.3   (32-bit)
Build time : Dec  6 2021 - 19:16:45
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19044.1387
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll Remove Duplicate Lines.dll XMLTools.dll

**Comment by xomx** [comment] 2021-12-14 22:24
Hmm, it is apparently intended so, but I do not know why, sorry. Relevant code in the `Notepad_plus::loadBufferIntoView()`:

```
...
//Check if the tab has a single clean buffer. Close it if so
if (!dontClose && tabToOpen->nbItem() == 1)
{
	idToClose = tabToOpen->getBufferByIndex(0);
	Buffer * buf = MainFileManager.getBufferByID(idToClose);
	if (buf->isDirty() || !buf->isUntitled())
	{
		idToClose = BUFFER_INVALID;
	}
}
...
```

So when there are two or more the "new x" clean tabs opened in the view, where you move the tab, this 'bug' does not occur.
And as you described, a single tab will not be closed there in case, when it is marked as dirty, but also in case that its current status is not `DOC_UNNAMED`.

**Comment by donho** [comment] 2021-12-14 23:54
By default Notepad++ opens one blank clean document, if there's no session. So if a existing file opened, this  blank clean document is closed automatically.
So it's an expected behaviour for a new blank clean document, even in thr special case you mentioned above.

**Closed by donho** 2021-12-14 23:54 UTC
