### ISSUE TITLE
Function List parser for Python files gets confused by comments

### ISSUE THREAD

**Issue by zslane** [notepad-plus-plus/notepad-plus-plus#1359] opened 2016-01-12 19:04 UTC
The code below causes the Function List to lose track of function definition boundaries:

```
def foo(x):
    return x * 10
#-- end def foo

def bar(y):
    return y / 10
#-- end def bar
```

The comments that mark the end of the function bodies appear to get parsed as actual code, and since the keyword def appears in the comment, the Function List parser gets confused.

**Comment by ClaudiaFrank** [comment] 2016-01-13 03:12
There is an updated one created by itraveller and THEVENOT Guy. 
http://sourceforge.net/p/notepad-plus/discussion/482781/thread/515001cd/#b5d2
Just update the functionlist.xml and restart npp.
Cheers
Claudia

**Comment by GitMensch** [comment] 2016-01-26 21:03
@milipili Do you know of any reason the updated definition is not in? I'm no python guy, but wondered about this old *maybe* enhancement not being in.

**Comment by MetaChuh** [comment] 2019-04-11 00:52
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:52 UTC

**Comment by GitMensch** [comment] 2019-04-11 21:18
I can reproduce the bug with NPP 7.6.6:

![grafik](https://user-images.githubusercontent.com/6699539/55993411-5b29a980-5caf-11e9-9d72-e9279e76911b.png)

so this issue *is not fixed* (functionlist should only have the second function name "bar").

Debug info:
~~~
Notepad++ v7.6.6   (32-bit)
Build time : Apr  3 2019 - 23:49:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
~~~

Again: a possible fix *may* be laying around at the old SF discussion pages since 2015, see link above.
