### ISSUE TITLE
"Find Next" Button non working properly with regular expression \t{0,5}

### ISSUE THREAD

**Issue by albgen** [notepad-plus-plus/notepad-plus-plus#12032] opened 2022-08-24 10:49 UTC
Create a new doc with some random text.
Open the search dialog and enter regular expression \t{0,5}
Hit find next...

**Comment by alankilborn** [comment] 2022-08-24 11:52
@albgen That's not much of a bug report; why didn't you follow the template for creating an issue?

As it stands, from what I can tell of your "steps to reproduce", there is no problem in Notepad++ 8.4.4 (current version as of this writing).

Recommend CLOSURE of this issue unless more info provided.

**Comment by albgen** [comment] 2022-08-24 12:00
No time :)
Latest version of course.
Btw hit "find next" several times...
Try to replace also. Strange behaviours...

**Comment by alankilborn** [comment] 2022-08-24 12:20
@albgen You're kidding, right?

Moderator: Please close this issue.

**Comment by CennoxX** [comment] 2022-08-25 07:57
@albgen You'll have to write what you are doing, what the result exactly is, and what result you expect at least. There is no way to tell, what is not working, or if you just don't understand how regular expressions work.

**Comment by alankilborn** [comment] 2022-08-25 11:39
@CennoxX OP had "no time" for trivialities like that!

**Comment by albgen** [comment] 2022-08-25 11:46
> @CennoxX In other words your advice to @albgen when reporting an issue is to "follow the prompting of the issue template". This is a GREAT idea; unfortunately @albgen had "no time" for such action.

Hey, calm down. If you do not like the discussion and how prople write, simply mind your business :) have a nice day and don't waste people time

**Comment by alankilborn** [comment] 2022-08-25 11:56
@albgen Are you going to provide the information requested from you about this issue?  You could have used the "time" it took you to write your "calm down" post to provide it, instead.

If not, can you close this issue?

**Comment by dail8859** [comment] 2022-08-25 18:20
@albgen I'll close this issue for now. Please reopen a new issue and follow the provided template. The entire purpose is to not waste the time of people willing to look into the issue for you. If you do not have the time to fill it out, then the issue isn't that important.

**Closed by dail8859** 2022-08-25 18:20 UTC
