### ISSUE TITLE
Linespacing bug when changing Theme/Style

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#1043] opened 2015-10-23 12:10 UTC
There is a bug where the line spacing is not getting set correctly when changing between different themes/styles.

To demonstrate the problem, I've taken 4 screenshots. In this example I've done the following:
1. Opened the Style Configurator, which is currently configured to use the Default theme. See the first screenshot. Notice that 56 lines of text are visible in the editor window.
2. Clicked on 'Obsidian' in the theme dropdown. See the second screenshot. Notice that 63 lines of text are now visible in the editor window.
3. Clicked on 'Bespin' in the theme dropdown. See the third screenshot. Notice that 67 lines of text are now visible in the editor window.
4. Clicked on 'Obsidian' in the theme dropdown. See the fourth screenshot. Notice that 67 lines of text are still visible in the editor window.

In step 2, with 'Obsidian' selected, there are 63 lines of text, and in step 4, with 'Obsidian' selected again, there are now 67 lines of text. I'm sure this is a bug. Something is not getting updated/set correctly when switching between the different themes. The difference in the number of lines displayed is even more pronounced when a file with code folding is open, but I just went with a simple example here.

Also, the same font is used by 'Default' and 'Obsidian' (Courier New, size 10), so I'm not sure why the number of lines is changing from 56 to 63 between step 1 and step 2. Maybe this is also a bug.

![01_default](https://cloud.githubusercontent.com/assets/3789849/10692141/2a48bca2-7987-11e5-804c-fd1008064a63.png)
![02_obsidian](https://cloud.githubusercontent.com/assets/3789849/10692140/2a474624-7987-11e5-86b2-6ff8c33ed6f7.png)
![03_bespin](https://cloud.githubusercontent.com/assets/3789849/10692139/2a469800-7987-11e5-856f-ad822bfc443b.png)
![04_obsidian](https://cloud.githubusercontent.com/assets/3789849/10692142/2a4bb0ec-7987-11e5-8938-9073061507cd.png)

**Comment by MetaChuh** [comment] 2019-04-10 23:41
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:41 UTC
