### ISSUE TITLE
JS file styling

### ISSUE THREAD

**Issue by Traik** [notepad-plus-plus/notepad-plus-plus#1272] opened 2015-12-19 13:23 UTC
I updated my Notepad++ from some 2013 version and I noticed that JS files are not styled the way they were.

I'm working with HTML, XML, PHP, CSS and JS files and it was always nice to have JS and PHP code styled differently. PHP files still have light orange background color which is good but JS files don't have light blue background color.

I tried to update stylers.model.xml and settings in "Style Configurator..." but I couldn't restore all of the previous style.

What I'm asking for is restoring the previous look or more settings in style configurator to be able to restore the previous look.

**Comment by Croydon** [comment] 2016-01-02 23:41
Afaik that is a duplicate of #1266. Please use the search first.

**Comment by MetaChuh** [comment] 2019-04-13 02:08
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:08 UTC
