### ISSUE TITLE
"A cast to a smaller data type has caused a loss of data" when accessing Delimiter preferences

### ISSUE THREAD

**Issue by Eldaw** [notepad-plus-plus/notepad-plus-plus#826] opened 2015-08-29 10:44 UTC
I'm currently running a debug build of the executable as I built/compiled from the source myself.

I notice that when I go into Preferences and then click on 'Delimiter' in the list on the left, I get the following error:

![image](https://cloud.githubusercontent.com/assets/3789849/9561584/19146374-4e43-11e5-8ad1-6a5be9da1c52.png)

**Comment by ariccio** [comment] 2015-09-09 00:33
Ummm... this is not *terribly* useful, as there's no information on *where* the problem is.

**Comment by Eldaw** [comment] 2016-02-26 17:46
I see that Don Ho has just committed a fix for an issue when accessing the Delimiter preferences.
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/19476bbbaed6a0421d2f234839d8dbe40e663b37

Does that fix this problem that I reported? If so, it would have been nice of him to acknowledge my bug report.

**Comment by donho** [comment] 2016-02-26 18:47
@Eldaw Yes, I confirm that this issue is fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/19476bbbaed6a0421d2f234839d8dbe40e663b37

**Closed by donho** 2016-02-26 18:47 UTC
