### ISSUE TITLE
Context Menu in Windows 11

### ISSUE THREAD

**Issue by JeffIDavies** [notepad-plus-plus/notepad-plus-plus#13434] opened 2023-03-28 00:20 UTC
### Description of the Issue

Notepad++ does not appear in the context menu for Windows 11.   

### Steps to Reproduce the Issue

1.  In Windows 11 Right Click a file you want to open in Notepad++
2. 'Edit with Notepad++' does not appear until you click 'Show Other Options'

### Expected Behavior

'Edit with Notepad++'  should appear immediately

### Actual Behavior

'Edit with Notepad++' does not appear in Context Menu

### Debug Information

TortoisGIT has recently found a way of adding their context menu directly in Windows 11.  Notepad++ should do the same.

**Comment by donho** [comment] 2023-03-28 05:50
Please restart your windows.

**Comment by kervala** [comment] 2023-03-28 08:59
I don't know what happened with latest Notepad++ version, but indeed the installer doesn't register anymore the "Open with Notepad++" item in Windows context menu. I had to add it myself using RegEdit in HKEY_CLASSES_ROOT\*\shell\Open with Notepad++

I uninstalled and reinstalled Notepad++, nothing is added.

I would add that I'm using ExplorerPatcher to enable Windows 10 context menus under Windows 11.

I checked the commits of the NSI file and the fixes introduced the issue ;p

**Comment by JeffIDavies** [comment] 2023-03-28 23:14
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "F:\Repos\Forecasting\.vs\Forecasting\config\applicationhost.config"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 (64-bit) 
OS Version : 22H2
OS Build : 22621.1413
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    XMLTools (3.1.1.13)

**Comment by LUatWork** [comment] 2023-03-31 01:56
Was this done before? If so, it's been lost.
Notepad++ 8.5.1 on Windows 11.
Missing now in both the Windows 11 right-click menu, and also missing in the 'show more options' legacy menu.
Some other 3rd party apps have managed to get themselves onto the menu below a break line, on my PC.

**Comment by ppgriffith** [comment] 2023-03-31 13:10
I have also lost the option in the basic right-click menu as well as under Show More Options (8.5.1), was working in both in the previous version.

**Comment by ctp9** [comment] 2023-04-02 11:03
Here to confirm that I also, just noticed... the context menu is missing (Windows 11 Version 10.0.22621 Build 22621).

**Comment by GurliGebis** [comment] 2023-04-03 12:07
Can you all try with 8.5.2 RC from here: https://community.notepad-plus-plus.org/topic/24328/notepad-v8-5-2-release-candidate

**Comment by ageorge95** [comment] 2023-04-03 14:00
Same for me, v8.5.1 messed up the context menu entry for notepad++; will go back to v8.5 until this is fixed.

**Comment by ppgriffith** [comment] 2023-04-03 15:45
Same, went back to 8.5 and all is as it should be.

**Comment by GurliGebis** [comment] 2023-04-03 15:47
Looking at #13399, it seems like there is a bug in Windows regarding the old menu

**Comment by oberschmuh** [comment] 2023-04-03 16:51
For me 8.5.2 RC bring back context menu in Windows 11

**Comment by FadeMind** [comment] 2023-04-03 17:16
> Looking at #13399, it seems like there is a bug in Windows regarding the old menu

> For me 8.5.2 RC bring back context menu in Windows 11

Yes and no. 

![20230403-1680541908](https://user-images.githubusercontent.com/9846948/229580919-d7f4d139-3ca0-4f3b-843a-a3eb3eb99d08.png)
![20230403-1680541885](https://user-images.githubusercontent.com/9846948/229580924-85e976be-bcfb-4e3f-b873-64d4562de4f8.png)

@GurliGebis Maybe you should clean up installer and move it integration directly to App?

**Comment by GurliGebis** [comment] 2023-04-03 17:39
@FadeMind that would Mean that everyone who is upgrading will be missing it, until they go into settings

**Comment by FadeMind** [comment] 2023-04-03 17:42
@GurliGebis for WinMerge works like a charm - but need to be investigate by user standalone. No prompt about it in Wizard Setup. OFC it is option for skip shell extension, but after install it - you have to self enable it legacy.

**Comment by GurliGebis** [comment] 2023-04-03 21:16
@donho can we closed this one?
It is a duplicate of the other issue, and having two threads just makes it difficult to followed and manage?

**Comment by donho** [comment] 2023-04-03 22:42
duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13399

**Closed by donho** 2023-04-03 22:42 UTC

**Comment by donho** [comment] 2023-04-04 22:51
@kervala 
> I removed the context menu entry I added in Registry, uninstalled the previous version and installed the new one (v8.5.2 Release Candidate). For me, it didn't change anything, the context menu is still missing :)

Thank you for your report.
It seems your issue has been solved by:
http://download.notepad-plus-plus.org/repository/MISC/nppShell.TEST14/

Could you test it and let us know if it's fixed for you?

**Comment by JeffIDavies** [comment] 2023-04-05 02:21
Yes- It works a treat.

Many thanks to everyone who contributed :)

**Comment by kervala** [comment] 2023-04-05 06:57
It works perfectly now, thank you so much :)
