### ISSUE TITLE
Function List does not Show the Current Function housing the Insertion Cursor

### ISSUE THREAD

**Issue by GaryBloom** [notepad-plus-plus/notepad-plus-plus#4054] opened 2018-01-06 23:55 UTC
### Description of the Issue

Although the Function List is a superb way of quickly navigating to a function in the open tab, the reverse is not true. The Function List can be made more useful by changing two things:
(1) The Function List's highlighted selection can change as the user navigates within the editing tab, and
(2) The Function List's highlighted selection should be visible, even when the Function List is not the selected pane.

The above can be very useful when the code being edited has very long functions.  This would allow the user to easily see in which function the cursor is located without having to scroll. If the Function List pane is open, it should be useful all the time.

### Steps to Reproduce the Issue

1. Open Function List
2. Use Function List to select first function
3. Click in editing tab anywhere in first function
4. Click in editing tab anywhere in the second function

### Expected Behavior

I expected to see the Function name still highlighted in the Function List.
When I click in the second function, I expect to see the second function name now visibly highlighted in the Function List

### Actual Behavior

When I click in the editing tab in step 3 above, the Function List selection is no longer easily visible.
When I click in the next function, the Function list selection does not change to the new function.

**Comment by MAPJe71** [comment] 2018-01-07 00:33
Duplicate of #715.

**Comment by dail8859** [comment] 2018-03-26 12:55
Closed by a724cc49a663f336b0a124c2a5969c489b70da62

**Closed by dail8859** 2018-03-26 12:55 UTC
