### ISSUE TITLE
Feature Request: Find All to return only unique lines even if some lines have multiple matches of the text or expression

### ISSUE THREAD

**Issue by celticvalley** [notepad-plus-plus/notepad-plus-plus#2987] opened 2017-03-03 04:32 UTC
### Current Behavior
When using Normal or RegEx expressions to "Find All" in current or all documents, one will end up with duplicated lines in the find results if the search text or expression appears 2 or more times in a line.   I fully understand that this could be considered normal and expected as a matter of how the search mechanism works.  However, for us regular human beings, we want to see only one line returned for each expression matched, even for lines that are matched multiple times.

### Current Work-around
There are a few RegEx ways to return only one line.  I provide one example here.  The problem with these work-arounds is they nullify a nice feature of Notepad++ where Notepad++ highlights the text matched in the find results.  The highlighting feature is nice because it draws my attention to the text I am searching for.  But the RegEx work-arounds causes Notepad++ to either highlight much more text than what I am interested in (one method), or to highlight only the first matching text I search for in the line, not all of the matching text (another method which I show here).

Example work-around:
^.*?\Ktargetword  (this returns only unique lines, but also only highlights the first occurrence of "targetword".

### Desired Behavior for new feature
Ideally Notepad++ would have a check box for whether to return only unique lines.  If unchecked, behavior is as it is now.  But if checked, when Find All is used only unique lines are returned and every instance of the found text is highlighted, even if 2 or more instances of the text is found in a line.  This desired feature would be available for both Normal and RegEx searches.  Stated another way, Notepad++ would do the work of consolidating what would have been multiple lines into a unique line in the background on my behalf.  This would be so much more intuitive than what we have today.

Thanks!

**Comment by nikunjbhatt** [comment] 2020-01-23 11:21
Duplicate of #3224

**Comment by sasumner** [comment] 2020-11-01 13:17
This feature-request is REJECTED by the author of Notepad++ ( https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9088#issuecomment-720016310 )
It will not be reconsidered.
Please do not open any new issues on this topic as they will be immediately closed.

The suggestion is to use this workaround:
* Set your _Search mode_ to _Regular expression_.
* Add the following to the end of your _Find what_ expression:  `(?-s).*`

Example 1: To show only the first hit on a line for `foo`, make your _Find what_ expression `foo(?-s).*`

If the literal text you are intending to search for contains regular expression metacharacters, add `\Q` to its start and `\E(?-s).*` at its end.

Example 2: To show only the first hit on a line for `*foo*`, make your _Find what_ expression `\Q*foo*\E(?-s).*`

**Closed** 2022-06-26 17:01 UTC
Labels: accepted

**Comment by celticvalley** [comment] 2022-07-28 19:35
Dear, donho, thank you, thank you!  I'm glad you didn't take "It will not be reconsidered" too seriously, LOL.  This addition will definitely make my line of support work easier because I use Search All every day on logs.  Have a great day!
