### ISSUE TITLE
Syntax highlighting disappeared after column 1024 in "Properties" Language comment line

### ISSUE THREAD

**Issue by creambun** [notepad-plus-plus/notepad-plus-plus#3150] opened 2017-04-10 07:54 UTC
In Notepad++ v7.3.3 (64-bit Windows version) English UI interface, the syntax highlighting disappeared after column 1024 in "Properties" language comment line

### Description of the Issue
The syntax highlighting disappeared after column 1024 in "Properties" language comment line. It is expected to have the comment highlighted applied to the rest of the same comment line. With "WordWrap" on, the 1025-th character is wrapped to the next line

### Steps to Reproduce the Issue
1. Open Notepad++, create a new file by "Ctrl + N"
2. Switch on "Word Wrap" by "Alt + V, W"
3. Change the Language to "Properties" by "Alt + L, P" and then selects "Properties"
4. Type "#0123456789"
5. Highlight "0123456789" and press "Ctrl + C"
6. Make sure cursor is at the end of the line and press "Ctrl + V" repeatedly until the line has more than 1024 characters

### Expected Behavior
It is expected to have the comment highlighted applied to the rest of the same comment line and the 1025-th character is shown without word wrap

### Actual Behavior
Check that the first 1024 characters are shown with syntax highlight (in green) and from the 1025 characters onward, syntax highlight seems to disappear. Letters are shown in black from the 1025-th character onward and are wrapped into another line

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

### Screen Shot
![untitled](https://cloud.githubusercontent.com/assets/12812168/24851345/e4208208-1e05-11e7-9dce-8dc3e8168c54.png)

**Comment by hugonmelo** [comment] 2017-04-11 22:29
1 - I tried to reproduce this bug and found that it doesn't have to do with Notepad++'s word wrap. If you write a line with more than 1024 characters and try to comment it, only the first 1024 will be highlighted.
The thing is: the same bug that affects the comments also affect Notepad++'s word wrapping.

2 - Looks like the problem is inside the Scintilla project. There is a buffer allocated with a hardcoded size (happens to be 1024, see the first screenshot). I downloaded the project and built it, testing a buffer with a bigger allocated size and both comments and word wrapping were fixed for .properties files (see the second screenshot).

3- I don't know what to do, since the issue is outside Notepad++'s project.

![problem](https://cloud.githubusercontent.com/assets/3393479/24933526/24d07f0a-1eed-11e7-9de9-8822a2cd153b.png)
![solved](https://cloud.githubusercontent.com/assets/3393479/24933525/24cbfc78-1eed-11e7-9b10-70414fa9ef02.png)

**Comment by MAPJe71** [comment] 2017-04-11 23:06
Notify the Scintilla project?

**Comment by hugonmelo** [comment] 2017-04-12 00:03
@MAPJe71 Done!
I created an issue on their sourceforge project: https://sourceforge.net/p/scintilla/bugs/1933/
I will try to look into it and send a fix for them, ok?

**Comment by creambun** [comment] 2017-04-12 08:35
Thanks a lot for the issue creation Scintilla. I didn't realize this is an issue stem from Scintilla

Now should I request to close the issue here? Please advise. Thanks

**Comment by hugonmelo** [comment] 2017-04-12 12:11
@creambun There is one more step. Even if the bug is fixed on the Scintilla project, Scilexer.dll still have to be built and replaced inside the Notepad++ folder.

**Comment by MetaChuh** [comment] 2019-05-17 20:52
we still can not do anything about it, as long as it is not fixed at the scintilla project.

many thanks and our apologies.

**Closed by MetaChuh** 2019-05-17 20:52 UTC
Labels: language-support, wontfix

**Comment by fakoor** [comment] 2023-08-01 05:13
Reopen.
The bug in scintilla [has been fixed](https://sourceforge.net/p/scintilla/code/ci/56b648377c237a5a5510d2c302f23f06c8e472c6/) now (actually ~ 7 months after closure of this issue).
Since the current release of npp still suffers from this issue, it might be a good time to return to this issue.
Note that I use syntax highlighting for a batch file.  It is interesting to note that highlighting tries to resume partially from column 2047 but it appears to fail to resume! (see the blue "--clean" word there in the screenshot)

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/11645244/42e9e3bc-21d5-41f8-b2c0-af9a837d7d2e)
