### ISSUE TITLE
Cannot reset transparency

### ISSUE THREAD

**Issue by nesc58** [notepad-plus-plus/notepad-plus-plus#1502] opened 2016-02-18 13:57 UTC
Hello,
is this a bug?

I slide the bar to left (95% transparency), and check the checkbox. Now the problem: I cannot slide back to right.

Is the problem reproducable?

Is this a bug or a handling mistake by me?

Thanks

Debug Information:
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\latex\Programs\npp\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7
Plugins : autosave2.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll HexEditor.dll NppCrypt.dll NppExec.dll NppFTP.dll PluginManager.dll

**Comment by MetaChuh** [comment] 2019-04-11 21:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 21:42 UTC
