### ISSUE TITLE
Cannot install plugins from Plugins Admin

### ISSUE THREAD

**Issue by CruzMarcio** [notepad-plus-plus/notepad-plus-plus#5206] opened 2019-01-07 14:18 UTC
### Description of the Issue
Cannot install plugins, when trying to install a plugin like Compare (it is happening to all I tried), I restarts Notepad but does not install.

### Steps to Reproduce the Issue
1. Open Plugins Admin
2. Select the checkbox on the Compare plugin
3. Click install
4. Confirm to restart Notepad

### Expected Behavior
After notepad restarts there should be a Compare option on the Plugins menu

### Actual Behavior
Compare option is not appearing

### Debug Information
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll 

I noticed that the plugin zip file is downloaded to the Temp folder but the size is 0. 
![image](https://user-images.githubusercontent.com/40072316/50772610-84343b80-1275-11e9-96c2-35963fa78ab6.png)

**Comment by chcg** [comment] 2019-01-09 20:38
@CompactFactor Couldn't reproduce the issue on win10 64bit.
Did you try to install or update other plugins from the list and facing the same problem? E.g. update DSpellCheck.

**Comment by CompactFactor** [comment] 2019-01-10 16:11
I think this has to do with corporate proxy. I tried from my home and it works, but from work on the corporate proxy it doesn`t. 
Does plugins admin support proxies with windows authentication?

**Comment by CompactFactor** [comment] 2019-01-10 16:14
Closed issue by mistake

**Comment by chcg** [comment] 2019-01-10 23:42
See https://github.com/notepad-plus-plus/wingup/tree/master/src/ConfigFiles, proxy should be possible by adding it via ?->Set Updater Proxy...

**Comment by jackmort37** [comment] 2019-01-16 11:11
I tried setting the updater proxy, but my corporate proxy requires windows authentication. How can I enter my credentials as it is not asking anything ?
However, closing notepad++ and reopening it, my proxy option is correctly saved unlike CompactFactor.

**Comment by speedoops** [comment] 2019-03-01 22:15
Same issue here.
This is my home computer. I'm not behand any proxy, but also got a zero byte size file "LightExplorer_2_0_dll.zip". But I believe the problem is due to bad network situation.
Whilst for my company computer, I can do install plugin with the same Notepad++ version.

As for the plugins-admin:
- Currently it close the app firstly and then try to download and install, while there is a network issue, it will leads to bad user experience.
- So, I suggest: Plugins-admin first try to download files, if download is not succeed,it should tell user that there is a problem and better to show the detail logs. (In this way, it will not close the app even though not succeed to install new plugins.)

**Comment by chcg** [comment] 2020-12-26 08:25
See also #5652 on the missing notification for the user on plugin download issues.

**Comment by donho** [comment] 2024-07-23 23:40
I believe this issue has been solved.

**Closed by donho** 2024-07-23 23:40 UTC
Labels: pluginAdmin
