### ISSUE TITLE
Function list

### ISSUE THREAD

**Issue by inczenorbi** [notepad-plus-plus/notepad-plus-plus#4845] opened 2018-09-13 09:48 UTC
### Description of the Issue
In C source file not all the functions are shown in the function list.
When I have comment[s] between the function's definition and it's very first opening bracelet than 
the function is not shown in the function list.
I am using v7.5.3

### Steps to Reproduce the Issue
1.  Enter the following code:
int f(void) /* */ {
	return 0;
}
2. Save the file with .c extension.

### Expected Behavior
The f() function appears in the function list.

### Actual Behavior
The function does not appears in the function list.

**Comment by SuperUserNameMan** [comment] 2019-02-04 15:34
similar or related to #4208

**Comment by MAPJe71** [comment] 2019-02-04 17:00
As a result of the implementation of the function-definition-detection-engine, "embedded" comment is not supported. Changing the regular expression(s) of the parser won't make a difference e.g. removing the `start of function body` detection will lead to false positives (i.e. show entries in the function list that are not function definitions).

Put the comment before the header (i.e. before `int f(void)`) or after the function-body-open-brace (i.e. after `{`).

**Comment by ruudgithub** [comment] 2019-05-17 10:34
I found the same problem with a .php file in notepad++. It only seems to happen with functions that start with the letter f, see attached screenshot. I'm using the latest version (at this moment ;)) 7.6.6 (32-bit).

![notepadpp_bug](https://user-images.githubusercontent.com/5908404/57922401-f65e0200-789f-11e9-840d-56ff9cf038f6.png)

**Comment by ArkadiuszMichalski** [comment] 2020-09-18 22:38
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4094.

**Closed** 2021-03-18 18:08 UTC
