### ISSUE TITLE
[Feature requests] Option to clear 'Change history margin' when reloading file from disk

### ISSUE THREAD

**Issue by szlaufmyca** [notepad-plus-plus/notepad-plus-plus#13735] opened 2023-06-03 14:09 UTC
Please add option to clear/reset 'Change history margin' after file is reloaded from disk.

**Comment by alankilborn** [comment] 2023-06-03 15:11
Duplicate of #12261 
Please look for existing issues before creating new ones.

**Closed** 2023-07-04 01:13 UTC
Labels: accepted
