### ISSUE TITLE
Fine-tune behavior of Ctrl+Backspace

### ISSUE THREAD

**Issue by h-h-h-h** [notepad-plus-plus/notepad-plus-plus#726] opened 2015-08-15 12:40 UTC
Hello,

with <kbd>Ctrl</kbd>+<kbd>Backspace</kbd> you can delete a number of characters at once. I would like to get only horizontal whitespaces deleted (spaces, tabs ...) if there are more than one to the left of the cursor.

The current behavior is (lines showing progress):

```
abc def          ghi¶
abc def          ¶
abc ¶
¶
```

Desired behavior:

```
abc def          ghi¶
abc def          ¶
abc def¶
abc ¶
¶
```

The new behavior would be useful, e.g., when deleting the spaces again that were added with the functionality of issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/724. It would also be useful when doing the same manually.

**Comment by johnnytemp** [comment] 2016-05-10 04:06
Hi, actually you can Ctrl-/ then Ctrl-Delete, in order to delete only spaces to the right.

Ctrl-Backspace to delete both spaces and last word may still have it use, e.g. typing a paragraph and want to delete the last typed word.  Thus, changing an old behavior may not suit the others.

**Comment by h-h-h-h** [comment] 2016-05-10 11:18
I didn't know this, but the spaces to the right will remain, then. Additionally, the request is about an easy way to get the expected results without thinking much about the structure of the document.

**Comment by johnnytemp** [comment] 2016-05-13 02:52
Yes, many editors Ctrl-Backspace & Ctrl-Delete do not remove both word and whitespace at a time.  But I think both approachs (delete both word and whitespace at a time, or not) is valid and useful behavior.

For those who desire the convenience of the behavior as described in this "ticket", I suggest Recording a macro, with two actions: Ctrl-Shift-/, then Backspace, and assign it with Shortcut Alt-Backspace.  This shortcut could completely reproduce what the original poster here want.  :)

**Comment by johnnytemp** [comment] 2016-05-13 03:17
Oh, h-h-h-h, I overlooked one of your point.  It is that "abc " become "", instead of become "abc", after a Ctrl-Backspace.  To me, its a bit strange behavior since it treat one & more than one whitespaces differently (but perfectly "smart" and ok).  However, I just care at how to fine tune to delete only the many whitespaces "          " at one time only.  Thanks.  :)

**Comment by h-h-h-h** [comment] 2016-05-14 00:01
@johnnytemp:

As I understand you,

```
abc def          ¶
abc def¶
```

is the only relevant thing for you, but you don't care if a case with *one* space is handled differently:

```
abc ¶
¶
```

I think this one-space-thing deserves attention because this is a kind of default number of spaces.

**Comment by johnnytemp** [comment] 2016-08-03 07:34
As a conclusion, if adopting the mentioned behavior of Ctrl+Backspace, then the behavior of Ctrl+Delete, Ctrl+Left, Ctrl+Right also need to be changed consistently.  I think the change is too big and is against Scintilla's default.  Moreover, changing such behavior could make some previously written PythonScript breaks.

**Comment by johnnytemp** [comment] 2016-08-03 07:36
In my opinion, better use Macro recording, or write your own PythonScript for such behavior fine tune.  Thank you for listening.

**Comment by MetaChuh** [comment] 2019-04-09 23:30
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:30 UTC
Labels: enhancement
