### ISSUE TITLE
Folder as Workspace doesn't update as new files or folders are created.

### ISSUE THREAD

**Issue by warg0x4e** [notepad-plus-plus/notepad-plus-plus#4644] opened 2018-07-06 03:31 UTC
### Description of the Issue
**Notepad++ version 7.5.7**
_Folder as Workspace_ doesn't update as new files or folders are created.

### Steps to Reproduce the Issue
The following steps are demonstrated at [https://youtu.be/nCy_MT46enY](https://youtu.be/nCy_MT46enY).
1.  Add a folder to _Folder as Workspace_.
2.  Create new files or folders in the folder.

### Expected Behavior
I expect to see the new files and folders in the _Folder as Workspace_.

### Actual Behavior
New files and folders aren't displayed in the _Folder as Workspace_.
![36704631_10216348229560021_4575886293489156096_n](https://user-images.githubusercontent.com/2155010/42358345-2a8b0f3a-80aa-11e8-9490-132f654c272a.png)

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by pryrt** [comment] 2018-07-19 21:41
Confirmation: see https://notepad-plus-plus.org/community/topic/16040/folder-in-workspace/9 for more users who are seeing the same bug

For me (PeterJones in forum), it worked just fine in installed 7.5.6 32bit, but behaved as @warg0x4e reported in portable 7.5.7 64bit.

\--------
![](https://i.imgur.com/CmOoTNI.gif)

    Notepad++ v7.5.6   (32-bit)
    Build time : Mar 19 2018 - 00:26:59
    Path : C:\Program Files (x86)\Notepad++\notepad++.exe
    Admin mode : OFF
    Local Conf mode : OFF
    OS : Windows 10 (64-bit)
    Plugins : ComparePlugin.dll dbgpPlugin.dll DSpellCheck.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll PluginManager.dll PreviewHTML.dll PythonScript.dll XMLTools.dll

\--------
![](https://i.imgur.com/GiDb7Tv.gif)

	Notepad++ v7.5.7   (64-bit)
	Build time : Jun 29 2018 - 00:53:58
	Path : C:\usr\local\apps\npp64.7.5.7\notepad++.exe
	Admin mode : OFF
	Local Conf mode : ON
	OS : Windows 10 (64-bit)
	Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by warg0x4e** [comment] 2018-07-19 22:31
Thank you, @pryrt.

**Comment by SinghRajenM** [comment] 2018-07-21 17:37
duplicate of  #4379

**Closed** 2018-07-22 01:09 UTC
Labels: accepted

**Comment by timvdh** [comment] 2021-02-24 07:09
I still see the exact same issue in v7.9.3 64bit

**Comment by timvdh** [comment] 2021-03-11 07:33
I noticed that "no refresh" only occurs with network drives (DFS in my case). I guess it could be more challenging are even impossible to monitor file changes on those, not sure. However, a manually refresh feature (button and/or context menu) would be of great help here. Or maybe is is already possible to refresh without restarting Notepad++?

**Comment by panvicka** [comment] 2021-03-11 14:20
Same here, I still see the exact same issue in v7.9.2 32bit (portable edition). The only solution seems to be to close and open Notepad++ again.

**Comment by timvdh** [comment] 2021-03-11 14:22
@panvicka I opened a feature request for this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9638 Maybe the manual refresh that I am suggesting would be helpful for you, too.

**Comment by PerthGoat** [comment] 2021-06-21 08:06
Seeing the issue on 7.9.5

**Comment by trevrr** [comment] 2022-01-07 17:03
I'm seeing this again in 8.2 64-bit

**Comment by smokesmoke** [comment] 2022-08-18 17:48
Not refreshing when using \\\\wsl$\ folders on Windows 11, but works for local (i.e.  C:\...) folders though.
Notepad++ v.8.4.4 (64-bit)
