### ISSUE TITLE
Show "Yes to All" and "No to All" only when Applicable on Exit

### ISSUE THREAD

**Issue by RealityRipple** [notepad-plus-plus/notepad-plus-plus#7518] opened 2019-11-06 16:21 UTC
### Show "Yes to All" and "No to all" only when Applicable on Exit
If you only have one tab open, or multiple tabs with only one unchanged file among them, the new "* to All" buttons do not functionally make sense. I suggest hiding them under such circumstances, both for interface simplicity and as a passive source of information on what's been changed and might be lost - one or multiple, basically.

### Steps to Reproduce the Issue
1. Disable the session feature under Backup.
2. Create a new document and type text.
3. Attempt to close Notepad++

### Expected Behavior
The "* to All" buttons should be disabled or hidden.

### Actual Behavior
The buttons are enabled and functional.

**Comment by sasumner** [comment] 2019-11-06 16:25
You had to delete the issue template out to complete your issue; it would have been better to fill it in.

Assuming you are talking about version 7.8 or 7.8.1, aren't the "to all" buttons greyed out in your described scenario?  You don't think that is enough?

**Comment by RealityRipple** [comment] 2019-11-06 18:02
No, they're not grayed out. They're clickable and functional.

**Comment by sasumner** [comment] 2019-11-06 18:04
@donho Can you cite an issue number that this is a duplicate of?

@RealityRipple You example scenario isn't complete.  What action are you doing that provokes the dialog that comes up with the "to all" buttons enabled?

**Comment by RealityRipple** [comment] 2019-11-06 18:10
I see, I see. It happens when you hit the Window's X as opposed to the X in the menu bar. I never use that X because I don't use the tab feature.

**Comment by sasumner** [comment] 2019-11-06 18:25
@RealityRipple 

Using the X on an editor *tab* (which seems to be what you mean--the little X I've circled in green below), I do not see the "to all" buttons as "clickable and functional".  Barring more info, I'm leaving this issue CLOSED.

![image](https://user-images.githubusercontent.com/30118311/68326125-d7933800-0098-11ea-8656-75fe4408ee35.png)

**Comment by RealityRipple** [comment] 2019-11-06 18:49
No, I mean the whole window. Like you go to close the program.

**Comment by sasumner** [comment] 2019-11-06 19:26
Ah, okay, I see it now. Functionally I suppose it does no harm, but really these buttons should be at least greyed/disabled in this circumstance.  I will reopen unless/until @donho provides reference to a prior existing duplicate.

![image](https://user-images.githubusercontent.com/30118311/68330307-07463e00-00a1-11ea-8db6-f33c5d3c0031.png)

**Comment by sasumner** [comment] 2019-11-06 19:30
Using *File* > *Close All* menu item produces the same behavior.

**Comment by donho** [comment] 2019-11-06 20:56
@sasumner 
> @donho Can you cite an issue number that this is a duplicate of?

Don't see it anymore. Is it closed?

**Comment by donho** [comment] 2019-11-06 20:58
Indeed, it does no harm,

**Closed by donho** 2019-11-06 20:58 UTC
Labels: reject

**Comment by sasumner** [comment] 2019-12-20 13:58
@RealityRipple 

The author said:

>Indeed, it does no harm,

But apparently has changed his mind.  See #7762 and the commit mentioned there.
