### ISSUE TITLE
link to UDL 2.1 documentation is outdated

### ISSUE THREAD

**Issue by pryrt** [notepad-plus-plus/notepad-plus-plus#2713] opened 2016-12-22 18:50 UTC
![](http://i.imgur.com/WBdNGxY.png)
UDL 2.1.0.12 dialog box still links to the old "temporary" [http://udl20.weebly.com/](http://udl20.weebly.com/), which is a UDL 2.0 description.

The newer [http://ivan-radic.github.io/udl-documentation/delimiters/](http://ivan-radic.github.io/udl-documentation/delimiters/) more fully describes UDL 2.1 (including some of the changes between UDL 2.0 and UDL 2.1).  

Could the link in the dialog box be updated to the newer documentation site; or, if there's a documentation site even newer than that, could the dialog box link be set to whatever most fully covers 2.1.0.12?

Thanks

**Comment by chcg** [comment] 2016-12-29 10:24
@ivan-radic
Is this the official docu side for UDL2.1?

At https://sourceforge.net/p/notepad-plus/discussion/331753/thread/01f8c28f/?page=26
there is some dicussion on udl3, any news on this task?

The link needs also to be updated here:
http://docs.notepad-plus-plus.org/index.php/User_Defined_Languages

**Comment by ivan-radic** [comment] 2017-01-07 21:13
Hi,

new site (http://ivan-radic.github.io/udl-documentation/delimiters/) was my attempt to learn how github pages work. I never published it because I wanted to integrate it into official Notepad++ documentation site, not keep it as separate page/repository. I never did it due to lack of time and some health issues that affected my productivity.

Since I recently resumed my work on UDL, I am OK with putting new link into into UDL GUI. Check with Don Ho if that's OK with him too.

Here are relevant source files (search for 'weebly' string):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/UserDefineDialog.cpp
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/ScitillaComponent/UserDefineDialog.rc

Best regards
Ivan Radic

**Comment by ivan-radic** [comment] 2017-01-07 21:19
Regarding UDL3. This is an ongoing task (recently resumed after longer break caused by burnout and health issues), that is kept in unpublished private repository.
There won't be any news or updates about it until I finish it.

Best regards
Ivan Radic

**Comment by chcg** [comment] 2017-01-08 18:24
Thanks Ivan for the update on this topic. Do you wanna provide a PR and checkback with Don Ho?

Best wishes,
 Christian

**Comment by donho** [comment] 2017-02-28 21:13
@ivan-radic Hi Loreia, hope you're well :)
My question is ; since it's called v2.1, is there a v2.1 UDL existe?
If not why the increase of version?

**Comment by chcg** [comment] 2017-03-01 06:22
Should be v2.1 according to checin

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d60466eed348e1d61577225fd260abeb5d061095

[BUG_FIXED] (Author: Ivan Radić - aka Loreia) UDL 2.1.
git-svn-id: svn://svn.tuxfamily.org/svnroot/notepadplus/repository/trunk@1012 f5eea248-9336-0410-98b8-ebc06183d4e3

**Comment by chcg** [comment] 2018-01-05 21:25
@pryrt Could you please close this issue as it is resolved since https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v7.3.3

**Closed** 2018-01-05 23:34 UTC
