### ISSUE TITLE
Style token lost on file reload

### ISSUE THREAD

**Issue by sonnin** [notepad-plus-plus/notepad-plus-plus#4808] opened 2018-08-30 09:17 UTC
### Description of the Issue
Having defines style tokens on a document and reloading the file the style token setup is lost.

### Steps to Reproduce the Issue
1. Open a file
2. enable style token 1 
3. reload from disk
4. no style tokens are highlighted

### Expected Behavior
Style tokens to persist and be applied after reload from disk

### Actual Behavior
Style token are reset

**Comment by sasumner** [comment] 2018-08-30 11:33
The described behavior is how it was designed to work.

**Comment by ClaudiaFrank** [comment] 2018-08-30 15:41
Imho issue should be closed as it works as designed and because even if you think about it how should
npp know which part needs to be styled and how if the file does not contain any information what has been styled before. Let's assume for a moment that the file has the content **Hello World** and one modifies
it to **Hello Walter** and styles the word **Walter** - how should a reload act on this?

**Comment by sonnin** [comment] 2018-08-30 17:55
In my case i am looking at a log file for a running program which appends to the file.

If the style token was not lost on reload the worst that could happen was that no snips would matched the tokens, which is kind of how it already works. 
But in my use case I may highlight a thead id and some other tag in the file which links the line together. Reloading the same file I have to start over and over again. Which means that I may decide not to use the feature because it feels like a waste of time. 

If it truely is per design, perhaps you could make it configurable if style tokens are to be reset on file reload or not.

**Comment by ClaudiaFrank** [comment] 2018-08-30 18:33
It is designed this way - reloading a file means creating a new scintilla document.
I see and agree that this might be a nice feature for your use case but technically you are looking for 
a lexer like those in the language menu. 
So it only remains for me to wish you luck that this will be implemented. :-)

**Comment by mcmillab** [comment] 2020-06-08 06:09
This may well be how it's designed to work, but could we have an option to apply styles on reload?

**Comment by sasumner** [comment] 2021-04-25 22:37
After some discussion with @donho offline, he confirmed that he wants this feature to remain the way it currently is (ref. point -- 7.9.5) so this issue will now be closed.

**Closed by sasumner** 2021-04-25 22:37 UTC

**Comment by donho** [comment] 2021-04-26 00:20
Thank you @sasumner for involving me into this issue.

Just want to keep a track about the arguments of decision, here is my reply:

> To store the info of styled tokens, the intuitive & efficient way is using offset/length. But there will be a bug on restoring if document is modified outside before Notepad++ starts and opens the document.
>
> The other more consist way is store whole styled string in xml file and redo find & style the token while Notepad++ load the  document. It will cause the performance issue if the loaded document is large:
You may notice that smart highlighting doesn't style the whole document but only on the visual page (the part displayed to user). This walkaround was made after a lot people complaining about smart highlighting performance on a large document, and it's about only styling one token.
>
> I don't want the option for turning ON/OFF this feature for 1. KISS principle & 2. once the performance occurs it's too late.
I use freeware and free software as everyone, and once it doesn't work (or does not work well), I won't brother to notify the author or the community. I just remove it and use another one.

**Comment by gersteba** [comment] 2023-11-09 13:01
I am using the bookmark feature to find code lines more easy in files on an FTP server, that do not change.
The problem is: When - for any reason - the FTP connection is lost and reestablished, NP++ is asking me for updating the file. Doing this, all the bookmarks are gone. To prevent this, I have to keep the FTP client open and I may not shut down my computer all days I need the file containing the bookmarks.
Therefore I sincerely agree with all participants above, who are wishing at least a feature to turn on/off keeping bookmarks on reloading an opened file - ideally for each file separately.
Thank you for your understanding and all your efforts to keep NP++ a great tool!
