### ISSUE TITLE
Black vertical line appears in left side of text editor after switching to Light mode from Dark mode

### ISSUE THREAD

**Issue by mshingote** [notepad-plus-plus/notepad-plus-plus#13593] opened 2023-04-25 09:09 UTC
### Description of the Issue
Black strip is visiable near number line in text editor.

### Steps to Reproduce the Issue
1.  Open text editor and select "Settings -> Preferences -> Dark Mode -> Dark mode"
2.  Without closing above dialogue select "Light mode"
3. See there is black strip visible near left side, previously it was not there.

### Expected Behavior
Black vertical line should not appear after selecting Light mode.

### Actual Behavior
Black vertical line appears after selecting Light mode.

### Debug Information
Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.2846
Current ANSI codepage : 1252
Plugins : 
    DSpellCheck (1.4.24)
    JSMinNPP (1.2205)
    JsonTools (3.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NPPJSONViewer (1.41)
    NppXmlTreeviewPlugin (2)
    XMLTools (3.1.1.13)

It may be scintilla dependant but needs to confirm.
![image](https://user-images.githubusercontent.com/8279344/234229595-0d613ab3-273b-45c4-83ca-d7ec91560b51.png)

**Comment by alankilborn** [comment] 2023-04-25 11:21
Cannot reproduce on:

Notepad++ v8.5.2   (64-bit)
Build time : Apr  4 2023 - 19:55:32
Path : W:\npp.misc\_NoBackup\Releases\npp.8.5.2\npp.8.5.2.portable.x64\notepad++.exe
Command Line : -titleAdd="8.5.2 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.2728
Current ANSI codepage : 1252
Plugins : 
    ColumnsPlusPlus (0.2.0.6)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
    NppPluginDemo (4.3)
    PythonScript (2)

**Comment by mshingote** [comment] 2023-04-25 14:10
Thats surprising @alankilborn !!
I have 2 machines one is this one win10 and other is win11 with latest npp version, this issue is seen on both machines and both has same plugins, so it seems one of these plugin might be causing the issue.

**Comment by alankilborn** [comment] 2023-04-25 14:22
>so it seems one of these plugin might be causing the issue.

If I were you, I'd try disabling all that you have that I don't.  If that works, reenable one at a time until you get the failure again.

**Comment by ozone10** [comment] 2023-04-25 15:28
duplicate of #12764

@mshingote 
your theme is missing `Change History margin` style

**Closed** 2023-05-04 03:07 UTC
