### ISSUE TITLE
Grave accent (`) is included in the name

### ISSUE THREAD

**Issue by EnginePod** [notepad-plus-plus/notepad-plus-plus#1606] opened 2016-03-09 11:04 UTC
This bug has caused a lot of issues with MYSQL queries so I thought it was finally time to report it.

Basically the feature that remembers names that you've typed (very useful feature btw), also remembers the grave accent in the name so the next time I want to type the name the grave accent comes with it.

For example: if you type **`testVariable`** (used for column names) - the next time that you type **testVa** the "remember feature" has **testVariable`** as the first option and if you select it without noticing the trailing grave accent then it'll cause some problems (as it's done for me numerous times).

It's a bit difficult to explain the situation so if anyone has difficulty understanding what I mean, then please ask and I'll be glad to provide a few more examples.
Also, thanks for the amazing work that's put into Notepad++!

**Comment by ClaudiaFrank** [comment] 2016-03-09 16:31
I guess I understand what you posted but I don't see what's your question/wish.
Doesn't npp offer the "correct" testVariable or do you always want to have the suggested words sorted
in the way that non-accent words get listed first?

**Comment by EnginePod** [comment] 2016-03-10 10:26
My post didn't get through (network problems) or it was removed, I'll post my reply again:

----

The problem is that the remember word only contains an accent in the end (no accent in the start).
For example, the remembered word looks like **testVariable`**, instead of **`testVariable`**

The best solution would be to fix this and have the grave accent both in the start and end of the word and then simply sorting the grave accent lower than the alphanumeric characters which would place them lower in the list (reducing the risk of selecting them by mistake).

**Comment by MetaChuh** [comment] 2019-04-13 02:35
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:35 UTC
