### ISSUE TITLE
Erroneous Multi-line tab single row click/drag tab swap

### ISSUE THREAD

**Issue by balagansky** [notepad-plus-plus/notepad-plus-plus#6273] opened 2019-10-25 23:42 UTC
### Description of the Issue
When using multi-line tabs, sometimes clicking and then dragging only slightly will cause tabs to swap even if the mouse is barely moved.

### Steps to Reproduce the Issue
1. Enable multi-line tabs
2. Open multiple tabs
3. Make sure the active tab is not the first tab
4. Re-open Notepad++, restoring the session
5. Click (and maybe hold a bit) an inactive tab
6. Move mouse slightly

### Expected Behavior
Nothing

### Actual Behavior
Previously active tab is swapped with clicked tab.

### Debug Information
Notepad++ v7.7.1   (32-bit)
Build time : Jun 16 2019 - 21:14:50
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![npptabs](https://user-images.githubusercontent.com/56180447/67610259-62de0680-f746-11e9-8162-c3f5ee38f1ad.gif)

**Comment by balagansky** [comment] 2019-10-26 00:24
Removing these blocks of code seems to avoid the issue, but that alone may not be the right fix:

	// TCM_SETCURFOCUS is busted on WINE/ReactOS for single line (non-TCS_BUTTONS) tabs...
	// We need it on Windows for multi-line tabs or multiple tabs can appear pressed.
	if (::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)
	{
		::SendMessage(_hSelf, TCM_SETCURFOCUS, index, 0);
	}

**Comment by AngryGamer** [comment] 2019-10-26 07:50
@balagansky
> Removing these blocks of code seems to avoid the issue, but that alone may not be the right fix:
> 
> ```
> // TCM_SETCURFOCUS is busted on WINE/ReactOS for single line (non-TCS_BUTTONS) tabs...
> // We need it on Windows for multi-line tabs or multiple tabs can appear pressed.
> if (::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)
> {
> 	::SendMessage(_hSelf, TCM_SETCURFOCUS, index, 0);
> }
> ```

This section of code shouldn't impact single line/row of tabs at all.

Can you check whether `(::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)` is evaluating true for you with a single row of tabs?

**Comment by balagansky** [comment] 2019-10-26 18:47
It is. I can't check right now, but I remember this being true, which is why removing that block makes a difference.

I debugged somewhat deep into that initially last week before switching focus to drag state logic and found that the TCM_SETCURFOCUS message being sent from this block was causing problems. I just ended up eventually erroneously thinking that the problems could be avoided by changing the drag state logic. I posted about this also here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4339#issuecomment-539260320

I don't know, though, whether the problems stem solely from that message send or whether there are deeper issues, perhaps with input state management.

**Comment by AngryGamer** [comment] 2019-10-27 12:32
I can't investigate this problem due to being unable to replicate. This makes me reliant on your debugging.

I'm puzzled by that [code block](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L1153) firing because you can visibly see that your example's tabs are non-TCS_BUTTONS tabs. The TCS_BUTTONS look uglier with space between them and 3D. If you carefully compare a single tab row vs 2+ tab row, then the difference between TCS_BUTTONS is readily apparent.

Some old screenshots comparing:

![1 row](https://cloud.githubusercontent.com/assets/23553210/24300681/8be748a2-10ad-11e7-8ab4-1d39b99813af.png)

![2 row](https://cloud.githubusercontent.com/assets/23553210/24300741/b3348bc2-10ad-11e7-91a0-d7561650fd2b.png)

So the question becomes whether `(::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)` is _always_ returning faulty data and if so whether this is a Microsoft issue.

What you could try doing is adding a global variable `bool isTCSBUTTONS = false` and [tracking its state here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L233) and then replacing all instances of `(::GetWindowLongPtr(_hSelf, GWL_STYLE) & TCS_BUTTONS)` with `(isTCSBUTTONS)`

**Comment by AngryGamer** [comment] 2019-10-27 13:02
I wonder whether SetActiveTab is called before any tabs are loaded and while rowCount==0. I imagine setting an invalid tab would cause memory corruption that may manifest itself later.

Another test to run is adding this logic to [TabBarPlus::setActiveTab(int tabIndex)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L1153) and [TabBar::activateAt(int index)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L1153)

`if (index <= static_cast<int32_t>(::SendMessage(_hSelf, TCM_GETITEMCOUNT, 0, 0) - 1)) return;`

**Comment by balagansky** [comment] 2019-10-27 19:44
Yes, that sounds like what I saw from my debugging a few weeks ago. That's why I specified the step:

3. Make sure the active tab is not the first tab

**Comment by balagansky** [comment] 2019-10-27 20:01
A complete repro gif using only npp files from the 7.8 installer:

![npptabclick](https://user-images.githubusercontent.com/56180447/67640808-ee2bd900-f8b9-11e9-85dc-51ba09e51d85.gif)

**Comment by balagansky** [comment] 2019-10-28 00:15
I'm low on spare time, but managed to spend a bit of time to chase down your leads, @AngryGamer.

Again, to confirm what I said earlier, activateAt gets called on session load, which is when TCM_SETCURFOCUS gets sent.

>	notepad++.exe!TabBar::activateAt(int index) Line 161	C++
 	notepad++.exe!DocTabView::activateBuffer(Buffer * buffer) Line 78	C++
 	notepad++.exe!Notepad_plus::activateBuffer(Buffer * id, int whichOne) Line 3766	C++
 	notepad++.exe!Notepad_plus::loadSession(Session & session, bool isSnapshotMode) Line 1983	C++
 	notepad++.exe!Notepad_plus::loadLastSession() Line 1750	C++

Now, even though after npp finishes starting up and loading the previous session, there is only one tab row, during the call to activateAt, getRowCount() returns 2. So essentially for whatever reason on load time, it really is using TCS_BUTTONS.

Maybe there's some kind of timing/ordering issue there.

This logic:

if (index < 0 || lastTabIndex < 0 || index > lastTabIndex)

Doesn't seem to make a difference because at least at load time, that condition is false. lastTabIndex is equal to index, which is the index of the active tab in the session being restored. All good as far as that goes.

When I first started looking at this a few weeks back, I initially submitted a PR that, iirc, does not send that message during session load, but then, iirc, I reverted it upon encountering the issue again. I think what my initial PR did is prevent the problem from being triggered during initial load, but it was possible to re-trigger again later, e.g. when tab rows were added and then removed.

Regarding your idea to manually track TCS_BUTTONS state - I tried that. Apparently what happens in my repro steps on load is that first TCS_BUTTONS is set to on, and then it's set to off, and then activateAt is called, but activateAt still thinks it's on. So, using a global var instead avoids that message being sent on initial session load, and avoids the tab swap weirdness at first. Unfortunately, when I then followed the rest of the repro steps for the crashing issues (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4339), I still got corruption and crashing. Whereas if I completely remove that message send, I do not get the issues. So it looks like this change is about as effective as my initial/deleted PR.

I think all this has something to do with timing / multiple messages being sent in a single update. The problem may be in update steps when TCS_BUTTONS state switches. I'm not sure how we could address that. Maybe I'll look a little deeper, but I'm quite low on spare time.

**Comment by AngryGamer** [comment] 2019-10-28 00:45
I figured out the cause of this problem:

non-TCS_BUTTONS tabs no longer utilize CURFOCUS due to incompatibility with WINE, however, TCS_BUTTONS uses CURFOCUS and the "garbage" value will linger when it switches to non-TCS_BUTTONS. This causes problems [with this code block](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L649). Fortunately, that code block can be removed entirely if the setActiveTab logic in RBUTTONDOWN is copied to LBUTTONDOWN.

**Comment by balagansky** [comment] 2019-10-28 00:57
That's exactly the code block I was looking while debugging initially.

I tried copying the setActiveTab logic to LBUTTONDOWN and removing the block in MOUSEMOVE. That actually seems to somehow incidentally solve this other issue I reported: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6274

However, following the repro steps, I still get the tab corruption.

**Comment by balagansky** [comment] 2019-10-28 01:00
Have you been able to actually reproduce any of this on your end?

**Comment by balagansky** [comment] 2019-10-28 01:15
Is there a reason that with your suggested setActiveTab changes, we couldn't just always use TCS_BUTTONS when multi-line is enabled? That would seem to avoid the issues.

**Comment by balagansky** [comment] 2019-10-28 01:16
I tried always using TCS_BUTTONS in multi-line, even for single rows, and seeing if under this, I could still repro the corruption by toggling the Multi-Line preference. I could not repro the issues that way, so always using TCS_BUTTONS seems safe.

**Comment by AngryGamer** [comment] 2019-10-28 01:21
> Have you been able to actually reproduce any of this on your end?

I was able to replicate the issues by following your instructions. I haven't been able to reproduce the crashes after fixing this problem. Did you change this line `_nSrcTab = _nTabDragged = tabFocused;` in your copy from tabFocused to tabSelected?

> Is there a reason that with your suggested setActiveTab changes, we couldn't just always use TCS_BUTTONS when multi-line is enabled? That would seem to avoid the issues.

Cosmetics. People whined a lot about how ugly it looks. So avoided using if possible. 😋

**Comment by balagansky** [comment] 2019-10-28 01:23
Actually, I made a mistake while testing - turns out even if you manually toggle TCS_BUTTONS via preferences, the SETCURFOCUS thing will still bleed over and cause problems. Blech.

**Comment by balagansky** [comment] 2019-10-28 01:26
> > Have you been able to actually reproduce any of this on your end?
> 
> I was able to replicate the issues by following your instructions. I haven't been able to reproduce the crashes after fixing this problem. Did you change this line `_nSrcTab = _nTabDragged = tabFocused;` in your copy from tabFocused to tabSelected?

Nope. I didn't change that since you didn't explicitly mention it, but now that I look at it, yeah, that makes sense :)

Once I made that change, everything seems to be working flawlessly... so far.

**Comment by balagansky** [comment] 2019-10-28 01:28
Ok, so it does appear that it was in particular TCM_GETCURFOCUS that was causing the issues. That call was odd anyway because it was unconditional - done even if we're not using TCS_BUTTONS.

**Comment by balagansky** [comment] 2019-10-28 01:31
I undid all my other changes (except the MOUSEMOVE PR changes that not directly related) and applied only the changes you mentioned above. Everything seems to work fine that way.

**Comment by donho** [comment] 2019-10-28 09:49
Use Notepad++ v7.7.1 to reproduce the bug and fix it upon v7.8 source code is the wrong practice.
BTW, I cannot reproduce such bug at all on v7.8.

**Comment by AngryGamer** [comment] 2019-10-28 12:15
> Use Notepad++ v7.7.1 to reproduce the bug and fix it upon v7.8 source code is the wrong practice.
> BTW, I cannot reproduce such bug at all on v7.8.

@donho This is an old bug which impacts both versions.

The key to triggering this bug is to select 2+ row tabs without clicking them (such as hotkeys that utilize SetActiveTab or activateAt functions) and then close enough tabs to make them single row tabs. After this is accomplished, you can reproduce the bug by dragging the tabs.

@balagansky reproduces the bug by closing Npp with a single row of tabs and then re-opening Npp. This causes Npp to re-open the tabs and select them using [TabBar::activateAt(int index)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L152). This normally wouldn't trigger the bug, but at launch Npp inaccurately detects rowCount==2 (which opens and selects tabs as TCS_BUTTONS) and subsequently detects rowCount==1 switching them to non-TCS_BUTTONS

The WINE fixes made the bug slightly less rare by synchronizing the logic in  [TabBarPlus::setActiveTab(int tabIndex)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L1149) with [TabBar::activateAt(int index)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L152). CURFOCUS was never sent by [TabBar::activateAt(int index)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L152) and in v7.8 it's not sent in [TabBarPlus::setActiveTab(int tabIndex)](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/06db9ee338ac9659b01b960325486a1791b249b0/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L1149) either. This causes CURFOCUS's garbage data to [select the wrong tab for dragging](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/src/WinControls/TabBar/TabBar.cpp#L649).

[Issue #6278](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/6278) fixes the problem by ensuring the proper tab is already selected which makes the problematic CURFOCUS logic redundant.

**Comment by balagansky** [comment] 2019-10-28 17:46
We seem to continue to miscommunicate, @donho. Let me try to be as clear as I can.

I have reproduced all 3 of the bugs I've reported on 7.8/master/head, after encountering them initially on 7.7. I have debugged them and developed fixes on master, initially before you updated the version to 7.8. So at first using 7.8 was not even possible since it did not exist yet.

The reason I provided Debug Info with 7.7.1 is because it was usually easier, I thought you wanted debug info from the latest auto-update release, which was 7.7.1 last I checked, and I thought you were primarily interested in the other information besides the version.

Sorry if I was not being entirely clear earlier. Please consider the fixes I've submitted. I am confident they are valid.

Unfortunately I have no idea why you cannot reproduce the behavior described, but luckily I am not alone in noticing and identifying these issues. Thanks @AngryGamer for the help.

**Comment by donho** [comment] 2019-11-03 00:47
@AngryGamer 
> @donho This is an old bug which impacts both versions.

So can you reproduce it with v7.8.1 ? Curiously, I've got no bug report about it recently.
If you can, could you provide your debug info ?

**Comment by AngryGamer** [comment] 2019-11-03 04:42
> @AngryGamer
> Curiously, I've got no bug report about it recently.

This bug was always quite rare. In v7.8 and v7.8.1 there will be more ways to trigger it. Fortunately, v7.8 and v7.8.1 are not that that widely used yet. The v7.8 release was never pushed by updater and usage of v7.8.1 is artificially depressed by Chinese DDoSing with the updater also still spitting GUP errors.

> @AngryGamer
> So can you reproduce it with v7.8.1 ? 
> If you can, could you provide your debug info ?

Yes, this can be reproduced in v7.8.1 along with years worth of older releases. At first, I also had difficulty reproducing it until I eventually copied everything I saw in @balagansky 's video (window length, tab length, tab reduce).

**The key is to have tabs/window length customized to where the TAB_REDUCE setting toggles multi-line.**

Here's a gif reproducing the bug which is easier to follow:

![npp](https://user-images.githubusercontent.com/4331362/68080457-0b304280-fdb9-11e9-8374-bf78ed97bdad.gif)

**Comment by AngryGamer** [comment] 2019-11-03 05:42
@donho

**Comment by AngryGamer** [comment] 2019-11-04 19:19
@donho

**Comment by AngryGamer** [comment] 2019-11-05 06:09
@donho

**Comment by donho** [comment] 2019-11-17 23:00
Indeed I reproduce now in v7.8.1 
Thank you for the instructions for reproducing it.

**Closed** 2019-11-18 01:08 UTC
