### ISSUE TITLE
Add kotlin to Language selection

### ISSUE THREAD

**Issue by pgbutchart-gmail** [notepad-plus-plus/notepad-plus-plus#13700] opened 2023-05-24 18:04 UTC
### Description of the Issue
In the language selection list kotlin is not available. The closest I can get is using Java.

### Steps to Reproduce the Issue
1. Click on Language in function list
2. Search for 'K'
3. Not found - 'KIXtart' is only language starting with 'k'

### Expected Behavior
Expected code to format as kotlin

### Actual Behavior
Nothing, had to choose semi-compatible language

### Debug Information
No debug info applicable.

**Comment by ArkadiuszMichalski** [comment] 2023-05-24 22:43
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3266.

**Closed by ArkadiuszMichalski** 2023-05-24 22:43 UTC
