### ISSUE TITLE
Regex replace with \K doesn't work, unless wrap around is used

### ISSUE THREAD

**Issue by Ryoshuga** [notepad-plus-plus/notepad-plus-plus#4035] opened 2018-01-01 19:18 UTC
### Description of the Issue

Regex matches with \K are able to be found, but not replaced, unless wrap around is used

Replace error: no occurrence was found

### Steps to Reproduce the Issue

1. Write the text "foobar"
2. Open the replace dialog (CTRL+H)
3. Search mode: Regular expression
4. Find text "foo\Kbar"
5. Replace text "cat"
6. Attempt to replace the text

### Expected Behavior

With wrap around disabled: To replace the "bar" in "foobar" with "cat"

With wrap around enabled: It works as expected

### Actual Behavior

With wrap around disabled: It is able to find the string but not replace it

### Debug Information

Notepad++ v7.5.4   (64-bit)
Build time : Jan  1 2018 - 01:50:29
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll PluginManager.dll 

As I understand it, wrap around simply searches the entire file from the current position to the end, then from the beginning back to the current position, it shouldn't have any effect on whether a replacement is possible or not

**Comment by sasumner** [comment] 2018-01-02 12:35
Your issue is perfectly valid.  It has long been a known problem that using `\K` in a regex replace has bugs, but usually the case is where "Replace" doesn't work and "Replace All" works fine.  This is the first time I've seen where the wrap-around option makes a difference when doing a simple "Replace".  Interesting.

**Comment by bumbaras** [comment] 2020-01-24 16:30
How to fix it? I was playing with (?<=) look behind construction (replacing worked that time), someone suggested to use \b \K switches, but i wasn't been able to make it works so returned to look behind and now replace button is no longer working when i use look behind construction. Even my previous attempts which worked then, now are not working as well. Replace button behaves like search next. Replace all works. How to fix it? Reopen notepad++ or reopen file doesn't help.

**Comment by sasumner** [comment] 2020-01-24 17:09
@bumbaras `Replace` button can't ever work in this situation, because the only text it looks at is from the point of the caret down to the end of doc.  So a positive look-behind won't work at the caret position.

**Comment by bumbaras** [comment] 2020-01-24 17:27
Not quite understood it, and now i am not even sure I was using replace step by step, and not replace all. I started using look behind yesterday. Now I have installed newest version 7.8.3 and found out that replace with look behind construction works but only if there is only 1 occurence of searching phrase. If there is more which matches patter then replace works like search next.

**Comment by bumbaras** [comment] 2020-01-24 17:28
Are there plans to fix it? Or maybe it is feature, not bug?

**Comment by sasumner** [comment] 2020-01-24 18:35
>works but only if there is only 1 occurence of searching phrase

Can you show an example?

**Comment by bumbaras** [comment] 2020-01-24 23:34
Is it so hard to check it?
" foo bar lorem ipsum"
F: (?<=foo )bar lorem
R: calamity
Wrap and RegExp enabled. Replace button changes bar lorem to calamity.
Duplicate the main line. Now replace button works like search next.

**Comment by bumbaras** [comment] 2020-01-24 23:36
I think it is just very old bug in npp, wonder why no one fixed it yet.
Sorry, for no edit previous, but in my current browser edit post is not working.

**Comment by sasumner** [comment] 2020-01-25 01:31
>Is it so hard to check it?

It's hard to read your mind about what you mean with a phrase like "replace with look behind construction works but only if there is only 1 occurence of searching phrase".  An example is much better.

**Comment by sasumner** [comment] 2020-01-25 01:32
>I think it is just very old bug in npp, wonder why no one fixed it yet.

It is not trivial to change it.  If you think it is, maybe you should try your hand at fixing it and submitting a PR.

**Comment by sasumner** [comment] 2020-09-25 20:42
Closing as duplicate of the more-recent #8434

**Closed by sasumner** 2020-09-25 20:42 UTC
