### ISSUE TITLE
More marked colors of the "save state" icons inside the opened file tabs

### ISSUE THREAD

**Issue by Nicero** [notepad-plus-plus/notepad-plus-plus#1130] opened 2015-11-11 16:51 UTC
I'm a NotePad++ donor. I would greatly appreciate this simple improvement. I normally wear glasses. As you may see from the picture below the difference between icon **-1-** and icon **-2-**, which indicate the "saved state" of the loaded file, is very little and barely perceptible. Would you please consider to rethink the appearence of these icons with some more evident and visible for i.e. changing the icon itself with a new drawing? Regards.

![immagine 1](https://cloud.githubusercontent.com/assets/408118/11096465/7d4aadda-889a-11e5-9742-152abb57edb8.png)

**Comment by Housema** [comment] 2016-06-04 11:51
# Similar request: Highlight a modified document more
Hello, I have prepared a similar question and now have found the request from Nicero.
I would like to recognize a modified doument more clearer in the editor. Surely, the modification is indicated by an asterisk at the top, but is it possible to highlight the status "modified" even more clearly by using a color or something similar?
And could the tab of a modified document be indicated too, by highlighting it with a color or something like that? I have attached a picture to show what I mean. By the way: The icons which Nicero mentioned I just was not aware of! (I will use the advice with the icons in the future.)

The reason why I consider this feature important:
In my daily work, I often edit multiple files with source code (scripts) in Notepad++. Then, when I execute the source code in the window of the other program, it often happens that I've forgot to save
one of the modified files beforehand. A noticeable highlighting would remind me not to forget saving and also would give me a save feeling that I actually have saved all my files (it is sometimes a little tiresome to look at the asterisk in the title bar).
![npp_feature_request_unsaved_files](https://cloud.githubusercontent.com/assets/19745357/15799379/fc6f9ca8-2a5a-11e6-97af-9c15d80796cf.png)

Anyway, Notepad++ already helps me a lot! Thanks and best regards

**Comment by MetaChuh** [comment] 2019-04-10 23:14
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:14 UTC
