### ISSUE TITLE
Possibility to filter Monospaced Fonts in global settings dialog

### ISSUE THREAD

**Issue by markmarques** [notepad-plus-plus/notepad-plus-plus#639] opened 2015-08-04 08:43 UTC
As the title suggests, a good enhancement for Notepad++ would be the possibility to filter the selecting  fonts  with an "Monospaced  Only" available font in the combo box ...

Thanks in advance ..

**Comment by aaaxx** [comment] 2015-08-06 16:19
That would be a nice touch, but it would probably be better to just put them at the top of the list instead of filter them (there are some heretics who code in proportional fonts).

The way it can be done is to use PANOSE classification metadata within a font, but I don't know if Windows can access it natively.

**Comment by MetaChuh** [comment] 2019-04-11 00:12
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:12 UTC
Labels: enhancement
