### ISSUE TITLE
Notepad ++ not highlighting comments properly for YAML files

### ISSUE THREAD

**Issue by protonpacks** [notepad-plus-plus/notepad-plus-plus#4485] opened 2018-05-08 13:19 UTC
### Description of the Issue
Syntax highlighting for comments in YAML files will only work if the comment is put on a separate line on it's own. If any code is put in front of the comment then the comment will be highlighted as plain text.

Comments on the same line as code will also remove syntax highlighting from instruction words on that line.

This is not an issue with the style configurator as it knows how to highlight comments already. This must be some issue with the lexer files for yaml but I don't know how to access/change them.

### Steps to Reproduce the Issue

1. In a YAML file on notepad++ type a line of code followed by a comment on the same line

### Expected Behavior
The comment should be highlighted as per instructions in the style configurator 

### Actual Behavior
The comment is highlighted as plain text

**Comment by dail8859** [comment] 2019-05-23 16:05
Duplicate of  #4640

Please do not open issues multiple times.

**Closed by dail8859** 2019-05-23 16:05 UTC
