### ISSUE TITLE
Restart As Regular User After Installation

### ISSUE THREAD

**Issue by AtmaX** [notepad-plus-plus/notepad-plus-plus#556] opened 2015-07-24 04:44 UTC
Can Notepad++ restart itself as the regular logged on user after installing/updating itself, instead of as admin?

**Comment by ariccio** [comment] 2015-07-24 05:27
Duplicate of: [#159: Installer should drop privs when executing the installed binary](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/159)

Related: [#334: Notepad++ elevated save privileges](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/334)

**Closed** 2015-07-27 09:58 UTC
