### ISSUE TITLE
Bookmarked/Non-bookmarked lines don't get removed

### ISSUE THREAD

**Issue by agstod** [notepad-plus-plus/notepad-plus-plus#14188] opened 2023-09-27 23:36 UTC
### Description of the Issue

Non-marked lines were not removed after multiple tries.

### Steps to Reproduce the Issue

1.  Version 8.5.2
2. Create a .log file with text on 455000 lines; Ensure at least 3000 lines have some unique character string
3. Bookmark those lines
4. Remove unmarked lines
5. Repeat the process with the same file during the same session of Notepad++

### Expected Behavior

I expected the unmarked lines to be removed

### Actual Behavior

The unmarked lines stayed (nothing happened)

### Debug Information

Notepad++ v8.5.2 (64-bit)
Build time : Apr 4 2023 - 19:55:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\Documents\sample.log" -multiInst -nosession -x-746 -y622 -Inormal -n1 -c1
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 21H2
OS Build : 19044.3448

**Comment by Yaron10** [comment] 2023-09-28 19:18
@agstod,

Can you reproduce it with a small file? - If not, what's the min-size the problem starts manifesting itself?

**Comment by agstod** [comment] 2023-09-28 21:44
Upon further testing, it looks like some of the non-bookmarked lines get removed of the 450000. Narrowing down, if I have a file of 120000 lines, then they all get removed correctly, but if the file has 150000 lines, there are still 4000 lines that don't get removed...

**Comment by Yaron10** [comment] 2023-09-28 22:05
Can you upload the 150000-lines file?
Also, please list the exact steps to reproduce the issue.

I must leave now. I'll be back next Sunday.
Someone else might test it earlier.

**Comment by agstod** [comment] 2023-09-28 22:37
Steps to reproduce:
** Also present in current version 8.5.7 **
1. Open the attached file: "npp_bug.txt" into notepad++ [npp_bug.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/12754400/npp_bug.txt)
2. Search for "green" under Mark tab. Check the box "Bookmark Line". Mark All
3. Search->Remove Non-Bookmarked lines

Notice how not all of the "Non-Bookmarked" lines were removed...

**Comment by Yaron10** [comment] 2023-09-30 22:46
@agstod,

Using v8.5.7 - NPP hangs and eventually crashes (as reported in https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13442).
Using an older NPP version (I tried it with v8.2.0) - NPP hangs for ~20 seconds, but then it gets stable and _all of the "Non-Bookmarked" lines are removed_.

I'm wondering how you got your results. :)

**Comment by xomx** [comment] 2023-10-01 09:49
with fresh N++ v8.5.7 x64 portable:

![npp-#14188-STR_1 2](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/2cb04314-1ae3-4c51-b3bb-463efe174f44)

![npp-#14188-STR_3](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/a2c60ffc-00b0-4905-bbd8-f031a8f9764b)

![npp-#14188-STR_final_result](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/122b6ea8-9c01-4613-a895-d92298e745f3)

**Comment by Yaron10** [comment] 2023-10-01 15:40
@xomx,

👍 
Thank you for testing it too.

Re-testing it now with v8.5.7, I get your & @agstod's results.
But I'm positive that on testing it yesterday, NPP did crash.

@agstod,

My apologies.

**Comment by xomx** [comment] 2023-10-01 17:16
@Yaron10 
> But I'm positive that on testing it yesterday, NPP did crash.

Because this is obviously a malfunction, everything is possible, even the crash of the N++.

**Comment by agstod** [comment] 2023-10-01 19:52
@Yaron10 and @xomx 

Thank you both for testing this. I am just relieved you can reproduce the error. I should note: my npp has never crashed but certainly stalls for awhile and takes up high cpu usage.

FWIW, I've used this feature many times in versions long past and never had an issue with large files (as far as deleting all the non-bookmarked lines). That is why seeing it not work all of a sudden is very strange to me.

**Comment by Yaron10** [comment] 2023-10-01 20:26
@agstod,

You're welcome.
Both the performance and the wrong results are major issues that should be fixed.

**Comment by Yaron10** [comment] 2023-10-01 20:43
I suppose that other commands should be tested as well.
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/12739#issuecomment-1374567753.

**Comment by xomx** [comment] 2023-10-01 21:34
@agstod 
> FWIW, I've used this feature many times in versions long past and never had an issue with large files (as far as deleting all the non-bookmarked lines). That is why seeing it not work all of a sudden is very strange to me.

And that was the missing important part of your issue report.
The last working N++ version is 8.4.5:
![npp-#14188-v845-ok](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/5ae993a2-a9c5-42dc-8991-df53f91d6ab5)

Processing takes a while but definitely not as long as from the v8.4.6 onward. And what is more important - the N++ process memory consumption is not get sky-high as in any of the v8.4.6+ - e.g. the v8.4.6 tried to allocate ~32GB of system memory at runtime only for this!!!:
![npp-#14188-v846-bad-alloc32GB](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/2a83a91c-513b-4bdc-8ccb-7376917d8814)

From the [v8.4.6 release info](https://community.notepad-plus-plus.org/topic/23541/notepad-v8-4-6-release) I bet on the No.1 - "Add Change History markers for document saved/unsaved/undone modification.".

**Comment by xomx** [comment] 2023-10-01 21:49
@donho 
There is a serious regression in v8.4.6+. I have not time for further testing (which commit exactly caused that) but I bet on the added "Change History Markers". More in my previous comments.

And now I see that the problem is confirmed also here: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13442#issuecomment-1739656891

**Comment by donho** [comment] 2023-11-07 16:06
Test procedure: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14188#issuecomment-1740088956
**Result:**
* Before #14320: 10 minutes 21 sec. (for getting job done on a Gamer PC)
* After #14320: 32 seconds

**Closed** 2023-11-07 16:07 UTC
