### ISSUE TITLE
Replace Dialog Box: Shortcut Key for "Find Next" Button

### ISSUE THREAD

**Issue by JediSQL** [notepad-plus-plus/notepad-plus-plus#10863] opened 2021-11-30 19:25 UTC
In the Notepad++ "Replace" dialog box there is a "Find Next" button. It does not have a shortcut key assigned to it. I wish it did. I do some text processing where I have to do many selective replacements.

### Steps to Reproduce the Issue
As it is now, I have to click with my mouse to do Find Next. That means that I need to keep jumping my eyes back and forth between the text and the "Replace" dialog box. After I use my eyes to find and click the "Find Next" button, I have to jump my eyes over to the text and see if the find is an instance I need to replace. If it is, I need to jump my eyes back over to the "Replace" dialog box to find and click the "Replace" button. When doing dozens of selective replaces, this really slows things down having to jump my eyes back and forth between the text and the dialog box, and keep re-aiming the mouse between the two buttons.

### Expected Behavior
I have two parallel suggestions:
1) Add a shortcut key to the "Find Next" (Alt-D would be good). Then I could hold down the Alt key with my left hand and type DDRDRDDDRDRDDDRDRDRDDDRD with the index and middle fingers of my right hand while keeping my eyes on the text. That would allow me to quickly see each find and decide whether to Replace of Find Next.
2) When in the text editor, F3 does a Find Next that remembers the last "Find what" from the Find/Replace dialog box. It would be cool if Notepad++ had a command something like "Replace Again" that remembers the last "Replace with" from the Replace dialog box and replaces the selected text (or inserts at the cursor) with the remembered text. Then in the Shortcut mapper I could add a convenient Shortcut key.

Thank you for the excellent text editor, and I hope you find this suggestion useful.

**Comment by ArkadiuszMichalski** [comment] 2021-12-03 08:57
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7999. 
The shortcut for "Find Next" is `Enter`, "Find Previous" is `Shift + Enter`.

**Closed by ArkadiuszMichalski** 2021-12-03 08:57 UTC
Labels: duplicate
