### ISSUE TITLE
[BUG] Save wrong filename

### ISSUE THREAD

**Issue by bero** [notepad-plus-plus/notepad-plus-plus#15841] opened 2024-11-22 12:38 UTC
### Description of the Issue
I want to generate a new file with name config.
In same folder there was already a file named config.txt
Whatever I do it try to overwrite config.txt

### Steps to Reproduce the Issue
1.  Save  file config.txt
2.  Choose new write some text and try to save it as config without file-extension. It try to overwrite config.txt all the time
3.  Note that the checkbox Append extension is NOT checked.

### Expected Behavior
I expect the file is saved with the name I wrote without add any extension

### Actual Behavior
The file config is saved and txt extension is added to file config.txt
![image](https://github.com/user-attachments/assets/11707867-4287-409c-995d-4069f29df44c)

**Comment by xomx** [comment] 2024-11-23 22:19
Cannot reproduce in the current v8.7.1.
Please add the requested Debug Info or close this issue.

**Comment by donho** [comment] 2024-11-29 20:39
Close for missing the response of PO.
Ping me when we have more (enough) info, I'll reopen it.

**Closed by donho** 2024-11-29 20:39 UTC
