### ISSUE TITLE
Language Menu stuck on XML when .xml file open

### ISSUE THREAD

**Issue by boris-999** [notepad-plus-plus/notepad-plus-plus#10939] opened 2021-12-23 13:41 UTC
### Steps to Reproduce the Issue

1.  open a .xml file
2. select any other language from the Language Menu
3. nothing changes :(

### Expected Behavior
other syntax highlighting (langauge) selected.

### Actual Behavior
nothing.

### Debug Information
v 8.1.9.3  32bit

**Comment by dail8859** [comment] 2021-12-23 19:34
Cannot reproduce this. Please post your entire debug information. 

For reference, this is mine:

```
Notepad++ v8.1.9.3   (64-bit)
Build time : Dec  6 2021 - 19:21:37
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19044.1415
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll ElasticTabstops.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NppMenuSearch.dll 
```

**Comment by boris-999** [comment] 2021-12-24 02:04
fresh download of src.   built, x64.   run it from /bin isolated from any of my previous installs..   No issue.

re downloaded  github-built x64 installer, installs to (C:/Program Files/Note...)   issue present.   (possibly my old config)
same again x32,  re downloaded github built x32 installer, installs to C:/Program Files (x86)/Note..   issue present.

downloaded github-built x64 portable.. stick in C:/foo/Note..64/..  config.xml is from the download (not my own)..  No issue.
same again.. x32 portable ,  stick it in C:/foo/Note..32/   config.xml is from the download ( not my own).. No issue.

found a old v8.1.1-portable on another machine, config.xml unknown..  No Issue.


So it's looking a lot like it's a config option.  So which config options prevent Language selectino changes?

.. and before you say it, No i don't want to just throw out my config and start again.. it took a long time to find the right settings, and i don't want to throw it away cause of a bug that should not exist.

**Comment by dail8859** [comment] 2021-12-24 02:13
> so it's not the Notepad.exe issue.

Then I would guess a plugin issue. Most likely XMLTools. Try disabling plugins via command line.

`C:\Program Files\Notepad++\notepad++.exe -noPlugin`

**Comment by dail8859** [comment] 2021-12-24 02:13
Oh...just saw your edit. Yeah definitely sounds like XMLTools

**Comment by boris-999** [comment] 2021-12-24 02:22
updated XMLTools plugin.    issue persists.      removed XMLTools, No issue.    Looks like we found the culprit!

filing an issue with that plugin's github.

**Comment by dail8859** [comment] 2021-12-24 02:24
> Looks like we found the culprit!

Good news. Will close this issue then since it is not Notepad++ related.

**Closed by dail8859** 2021-12-24 02:24 UTC
