### ISSUE TITLE
No syntax highlighting when N++ started from command line

### ISSUE THREAD

**Issue by n9r** [notepad-plus-plus/notepad-plus-plus#2174] opened 2016-08-15 07:53 UTC
### Description of the Issue

When Notepad++ is started from a command line with non existing file as parameter there is no syntax highlighting on.

### Steps to Reproduce the Issue
1. start cmd.exe
2. enter: start notepad++ testfile.js
3. enter var i = 0 and press enter key;

### Expected Behavior
Syntax highlighting on by default according to the file extension.

### Actual Behavior
No highlighting.

### Debug Information
Notepad++ v6.9.2
Build time : May 18 2016 - 00:34:05
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : JSLintNpp.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NPPJSONViewer.dll PluginManager.dll RefreshBrowser.dll XBrackets.dll XMLTools.dll

**Comment by dail8859** [comment] 2016-08-15 13:25
Duplicate of #2016 and already fixed by #2018. This will be available in the next release.

**Closed** 2016-08-15 13:26 UTC
Labels: duplicate
