### ISSUE TITLE
Nodepad++ compiled with mingw-w64 GCC 8.1 x64 is almost unusable

### ISSUE THREAD

**Issue by ivan-u7n** [notepad-plus-plus/notepad-plus-plus#10185] opened 2021-07-18 13:56 UTC
### Description of the Issue
While there seems to be the working instruction for building Notepad++ with gcc, the result is almost unusable: no toolbar, no Plugin Admin, unsaved preferences.

### Steps to Reproduce the Issue
1. Compile Notepad++ with mingw-w64 GCC 8.1 using BUILD.md as a guide.
2. Run it

### Expected Behavior
A usable version of Notepad++.

### Actual Behavior
![notepadpp-gcc](https://user-images.githubusercontent.com/81974034/126069308-b06ebe3c-1406-4e82-ac6f-2f3394246fac.png)
Neither toolbar nor Plugin Admin to be seen. The opened file is the saved upon closing the application config.xml and is the reason why preferences aren't saved.
I event tried downloading the “Plugin Manager” plugin manually also with no success — it just doesn't show up anywhere.

### Debug Information
Notepad++ v8.1.1   (64-bit)
Build time : Jul 18 2021 - 14:09:15
Path : F:\develop\notepad-plus-plus-master\PowerEditor\bin\NotepadPP.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.2061
Current ANSI codepage : 1251
Plugins : none

**Comment by mere-human** [comment] 2021-07-18 13:57
What for do you need MinGW version?

**Comment by ivan-u7n** [comment] 2021-07-18 14:16
For a temporary replacement of the current version build with my patches applied to the bundled Scintilla (see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5264) as I have no desire to install full-blown Microsoft Visual Studio just for this.

I saw the build instructions and thought it will be ideal temporary solution, but alas Notepad++, while compiles with GCC and even starts, isn't usable as a replacement of the official build, thus the bug report. Otherwise there is no sense in making a piece of software buildable by a toolchain, but crippled in its functionality.

**Comment by mere-human** [comment] 2021-07-18 16:05
As far as I know, the MinGW build exists rather for verification purpose, something like "sanity check". Also, MinGW build could provide some useful compiler checks.
For example: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9403#issuecomment-766347210
I don't think it was designed to be a fully-functional product. But I might be wrong.
You may find more info in git history.

**Comment by ArkadiuszMichalski** [comment] 2021-07-18 16:31
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9163. It is possible that repairing proper XML handling would eliminate most of these errors.

**Comment by ozone10** [comment] 2021-07-18 20:34
Some controls have "classic" style. 

Seems like issue with common controls loading.  IIRC mingw require some additional way to include manifest to use common controls in version 6.

btw Npp can be compiled with LLVM/clang (with more than 3000 warning).

**Comment by ivan-u7n** [comment] 2021-07-19 10:04
Some progress was made:
![notepadpp-gcc-2](https://user-images.githubusercontent.com/81974034/126142412-6e47d60b-2923-401b-80be-b1917519976a.png)
However I'm not sure that the changes I've made won't break builds with MS Visual Studio, for I had to replace printf specifiers in tinyxml.cpp with standard ones to not rely on behaviour of MSVC runtime absent in mingw-w64 runtime.

**Comment by ivan-u7n** [comment] 2021-07-20 20:22
@ArkadiuszMichalski if you want to give it a try, here's [master.patch.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6850964/master.patch.txt) which I'm using to build Notepad++ with GCC. This patch will give you a working static build (the dynamic one is disabled in makefile by the patch). Beware, the patch also includes my changes to the bundled Scintilla.

Plugin Admin requires some external files to work, I take them from the official build of Notepad++.

**Closed** 2021-09-01 09:54 UTC
