### ISSUE TITLE
Feature Request: Remember read-only status of opened files

### ISSUE THREAD

**Issue by Lokiare** [notepad-plus-plus/notepad-plus-plus#4872] opened 2018-09-23 16:37 UTC
### Description of the Issue

NPP fails to remember the manually set read-only status (set from the context menu for each tab/file), when re-opened.

### Steps to Reproduce the Issue

1. Open a file in NPP
2. Right-click on tab/file set read-only status
3. Close NPP
4. Re-open NPP

### Expected Behavior

It's expected that the tab/file opens and remembers whether it was set to read-only or not.

### Actual Behavior

The tab/file does not remember that it was set to read-only.

### Debug Information

N/A

**Comment by dinkumoil** [comment] 2018-09-25 20:37
Duplicate of #4409.

**Closed** 2019-03-27 21:26 UTC
Labels: feature
