### ISSUE TITLE
[Feature Request] Add a feature for transforming the column mode to multi-caret on HOME/END/Arrow keys

### ISSUE THREAD

**Issue by nrv-96** [notepad-plus-plus/notepad-plus-plus#14266] opened 2023-10-25 07:17 UTC
### Description of the Feature

Please incorporate a feature similar to VS Code, as demonstrated in the attached video, enabling the editing of the selected line at the end of the line.

### Expected Behavior
At present, this particular feature is absent in Notepad++. Could you kindly consider integrating this functionality into the application?

https://github.com/notepad-plus-plus/notepad-plus-plus/assets/62826272/bbfab116-db6e-4e54-83f0-9cfc299c12c1

**Comment by Ekopalypse** [comment] 2023-10-25 07:26
There is a plugin called [BetterMultiSelection](https://github.com/dail8859/BetterMultiSelection/) which then allows Npp to do this kind of editing.

**Comment by nrv-96** [comment] 2023-10-25 07:30
@Ekopalypse , can we add it as core functionality? This would be helpful to everyone.

**Comment by Ekopalypse** [comment] 2023-10-25 07:39
@nrv-96 - it's up to @donho to decide, but in the past the policy has tended to be - "if there's a plugin that can do this, it's more likely not to be included in core".
Personally, I would like to see this as a core feature as well.

**Comment by nrv-96** [comment] 2023-10-25 09:25
I agree with you @Ekopalypse . While I understand the policy about plugins, having this as a core feature could greatly enhance the overall functionality. It's up to @donho  to decide, but considering its potential benefits, I also support the idea of incorporating it into the core. Everyone can enjoy a seamless and integrated experience without the need for external plugins.

@donho, I kindly request you to consider incorporating  **BetterMultiSelection** as a core feature instead of an external plugin.

**Comment by alankilborn** [comment] 2023-10-25 11:16
>this plugin (BetterMultiselection) was last updated in 2022

There's not much value in that statement, as 2022 is hardly ancient history.

**Comment by alankilborn** [comment] 2023-10-25 11:17
I'd think that a "problem" with adding this as a "core" feature is that these types of functions are really Scintilla owned, and not Notepad++ owned.  Thus, shouldn't something like this be in Scintilla's careting support?

**Comment by Ekopalypse** [comment] 2023-10-25 11:35
In general, I agree that Scintilla would be the best place to ask for such a feature, but if I'm not mistaken, there was already such a request and it was rejected (I hope I don't remember wrong - I'm going to research scintillas FRs).
Npp would be the next best option.

**Comment by donho** [comment] 2023-10-25 13:18
Frankly, I kind of like this feature. If it's not hard/complex for implementing, it will be great to include it in Notepad++.
I will see what I can do about it.

@nrv-96 
What's the shorcut in VSCode to move the cursor from the begin of the lines to the end?

@Ekopalypse 
> but if I'm not mistaken, there was already such a request and it was rejected (I hope I don't remember wrong - I'm going to research scintillas FRs).

If you find the link, you're more than welcome to post here.

@alankilborn 
> Yes, but this is where the author of N++ (possibly) thinks "hmm, functionality that should be in Scintilla...but hmm, there's a plugin that already does it......no way am I spending time on implementing that natively, I have other things to do".

I don't think you do really know me :)

**Comment by nrv-96** [comment] 2023-10-25 13:24
@donho There is a shortcut in Visual Studio Code to select multiple lines: Alt + Ctrl. To go to the end of the line, you can simply press the END button.

Note: In Notepad++, Alt+Shift to select multiple lines.

**Comment by rdipardo** [comment] 2023-10-25 14:23
@Ekopalypse

> I agree that Scintilla would be the best place to ask for such a feature, but if I'm not mistaken, there was already such a request and it was rejected

You may be thinking of this: https://sourceforge.net/p/scintilla/feature-requests/1275

As you will read on that thread, Scintilla already implements multiple caret editing via the [`SCI_ADDSELECTION`](https://www.scintilla.org/ScintillaDoc.html#SCI_ADDSELECTION) API (hence the "Completed" disposition of the ticket).

See what SciTE does when you press <kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>↓</kbd> after making a selection; the up arrow key works the same.

![scite-538-multi-caret-editing](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/dd7b77f8-61b0-4789-a02b-21a7de6b0265)

**Comment by alankilborn** [comment] 2023-10-25 15:25
@donho says:

>I don't think you do really know me :)

I don't claim to; I said "possibly".  :-)
And, it is how _I_ would think about it, and it has been demonstrated so many times that we are _different_ thinkers. :-)  Sometimes maybe in the end, changes are better with contributions from such different thinkers...

But I don't know...on this current issue...perhaps Scintilla comes to its senses :-) and _does_ implement it -- maybe it needs to then be undone in Notepad++ (so, more effort).
I'd just stick with the plugin for now, as it meets the need, and is an easy solution.

**Comment by alankilborn** [comment] 2023-10-25 15:27
@rdipardo said:

> SCI_MULTIPLESELECTADDNEXT

Reference currently-open https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8203

**Comment by rdipardo** [comment] 2023-10-25 23:55
So it looks like <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>↑/↓</kbd> already works in N++ in "Multi Editing" mode, assuming that key combo has no custom mapping (a fresh portable is best for experimenting).

The scope of this request can be narrowed down to "Allow `SCI_SWAPMAINANCHORCARET` or similar to move *all the carets* to the end position of a rectangular multi caret selection (*à la* VS Code)" Currently it's just *the most recently added caret* that gets moved. That may end up being something that Scintilla needs to implement...

### To reproduce

First make sure the caret is thick enough to see easily:

1. `Settings` > `Preferences` > `Editing` > `Caret Settings`
2. `Width: Block`

Enable multiple carets

1. `Settings` > `Preferences` > `Editing`
2. `[X] Enable Multi-Editing ...`
3. Confirm that <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>↑/↓</kbd> creates a rectangular selection with multiple carets

Now go to `Settings` > `Shortcut Mapper` > `Scintilla commands` and map `SCI_SWAPMAINANCHORCARET` to a free combo, e.g. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>.</kbd>.

1. Make a selection
2. Extend the selection with <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>↑/↓</kbd>
3. Release the keys
4. Execute the `SCI_SWAPMAINANCHORCARET` key combo
5. Confirm that only the most recent caret swaps position, i.e. the topmost, if you extended from the bottom, or *vice versa*

![npp-858-sci-swap-caret](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/1460fb12-8006-4e28-821c-fd05ad044cd8)

**Comment by donho** [comment] 2023-11-04 00:58
FYI: Just submitted a FR/Support Request on Scintilla here:
https://sourceforge.net/p/scintilla/bugs/2412/

Hope we can have a simple solution.

**Comment by donho** [comment] 2023-11-04 12:31
> Hope we can have a simple solution.

Thank @nyamatongwe for his help, a simple solution has been implemented in #14313.

@nrv-96 
Could you check PR #14313 to see if it meets your need?

**Comment by Ekopalypse** [comment] 2023-11-04 12:48
Creating the selection works as expected, but when copying/pasting the selected content, everything is merged as one string.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/47723516/f759bc62-2d42-47de-8d8d-1b0c021eb626)

I would have expected the following

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/47723516/f30ebb5d-eab0-4006-a07c-4afe33ffa862)

**Comment by nrv-96** [comment] 2023-11-04 14:33
@donho, thank you very much for making my feature add in NPP 🫡 . I really appreciate your and every contributor's hard work in adding as many features as possible to Notepad++.

P.S. I've checked my feature in the downloaded [artifact ](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/48442343/artifacts)and verified it.

**Comment by donho** [comment] 2023-11-04 23:52
@Ekopalypse 
> Creating the selection works as expected, but when copying/pasting the selected content, everything is merged as one string.

It's the behaviour of multi-selection in Scintilla. Unfortunately I have no solution for it yet.
I will see what I can do for it in Scintilla source. But I cannot promise anything.

**Closed** 2023-11-06 12:44 UTC

**Comment by vinsworldcom** [comment] 2023-11-07 16:56
@donho 
>  >@Ekopalypse 
> >
> >Creating the selection works as expected, but when copying/pasting the selected content, everything is merged as one string.
>
> It's the behaviour of multi-selection in Scintilla. Unfortunately I have no solution for it yet.

The [BetterMultiSelection](https://github.com/dail8859/BetterMultiSelection) plugin handles this correctly.  For that reason I'll keep it installed.

Wonder if looking through the logic of cut/paste in that plugin code would shed some light on how to handle it and then make a decision as to whether to port that logic into this Notepad++ feature?

Cheers.

**Comment by donho** [comment] 2023-11-09 16:25
Please check PR #14338 for Multi-select **paste** enhancement.

**Comment by wsteinford** [comment] 2023-12-05 15:09
How does one **disable** this new behavior for column-mode selections so that the multi-line selection gets cancelled when the user hits an up or down arrow? This (the multi-line selection cancelling on up/down arrow) was one of the main behaviors that kept me using Notepad++ instead of switching to VSCode, whose multi-caret selection is "sticky" (and now N++ feels "sticky" too).

**Comment by vinsworldcom** [comment] 2023-12-05 15:23
@wsteinford 
> and now N++ feels "sticky" too

It should be. That's the beauty of multi-carat mode.

Try the `ESC` key, it works wonders!

Cheers.

**Comment by alankilborn** [comment] 2023-12-05 16:07
> How does one **disable** this new behavior

It is not possible to disable.
As @vinsworldcom said, used the Esc key (or click with the mouse in a new position).
