### ISSUE TITLE
Wrong XML syntax in localization/chineseSimplified.xml

### ISSUE THREAD

**Issue by HarryTMa** [notepad-plus-plus/notepad-plus-plus#9402] opened 2021-01-17 05:10 UTC
### Dear Team:
I'm Harry from China.
When I attempted to set the native language to Chinese(Simplified) it will automatically become English rather than Chinese, but Taiwanese(Traditional) or Cantonese(Traditional) are both available. Then I checked "localization/chineseSimplified.xml" and found a syntax error: (about line 850)
```XML
                <MarginsBorderEdge title="边距/边框/边缘">
                    <Item id="6201" name="代码折叠标志"/>
                    <Item id="6202" name="简洁"/>
                    <Item id="6203" name="箭头"/>
                    <Item id="6204" name="圆圈"/>
                    <Item id="6205" name="方框"/>
                    <Item id="6226" name="无"/>
                    <Item id="6291" name="行号"/>
                    <Item id="6206" name="显示"/>
                    <Item id="6292" name="变宽"/>
                    <Item id="6293" name="等宽"/>
                    <Item id="6207" name="显示标签栏"/>
                    <Item id="6211" name="列边界设置"/>
                    <Item id="6213" name="背景色模式"/>
                    <Item id="6237" name="想要添加列标记，可用数字指示其列位置。
用空格分隔不同数字以定义多个列标记。"/>
                    <Item id="6231" name="边框宽度"/>
                    <Item id="6235" name="无边框"/>
                </Scintillas>
```
Here, it **should** be `</MarginsBorderEdge>`, and after I modified it, NPP worked correrctly.
I really hope that your team would find this issue and fix it.

Sincerely,
Harry

**Comment by sasumner** [comment] 2021-01-17 12:38
Duplicate of #9329

**Closed by sasumner** 2021-01-17 12:38 UTC

**Comment by pilaoyao** [comment] 2021-12-01 01:09
yyds

**Comment by 7964133** [comment] 2022-07-09 10:09
**be grateful to you**
