### ISSUE TITLE
Live filter and/or search field for Document List

### ISSUE THREAD

**Issue by korpx** [notepad-plus-plus/notepad-plus-plus#12493] opened 2022-11-11 08:21 UTC
It would be extremely helpful with a live search text field to quickly filter the Document List on file name.
With some hundred files open there is alot of scrolling and time spent locating the right file.

![image](https://user-images.githubusercontent.com/1850308/201297564-c014ad48-4afe-41b1-9d05-615da85fdf07.png)

I am aware of the NavigateTo plugin which is somewhat similar i functionality but not really there in usability.

**Comment by ArkadiuszMichalski** [comment] 2022-11-12 13:32
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7899, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3973.

**Closed by ArkadiuszMichalski** 2022-11-12 13:32 UTC
