### ISSUE TITLE
When Shutting Down Pop Up Window: "Error of saving session file".

### ISSUE THREAD

**Issue by mckinnon** [notepad-plus-plus/notepad-plus-plus#14444] opened 2023-12-04 08:55 UTC
### Description of the Issue
Permissions issue with v8.6 prohibits Notepad++ from writing to its own directory which causes errors when using the application directory for session data instead of %APPDATA%.

### Steps to Reproduce the Issue

1. Use Notepad++ v8.6 on Windows 11 Pro.
2. When installing, choose "Don't use %APPDATA%" option.
3. Start then close Notepad++ session.
4. Get "Error of saving session file" like [issue #13859](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13859)
5. When re-starting Notepad++ restores last session.

### Expected Behavior
Close without errors. Restores last session when re-starting Notepad++.

### Actual Behavior
Close with errors. Restores last session when re-starting Notepad++(??).

### Debug Information
Notepad++ v8.6   (64-bit)
Build time : Nov 23 2023 - 16:58:44
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

### Users' Dirty Fix
Change application folder's Security settings to grant Users "modify" and "write" permissions.

### Discussion and Suggestion
When run as a normal user (not Admin),  Notepad++ does not have write permissions to the installed default non-%APPDATA% directory. The Dirty Fix is insecure for multi-user environments because all users load the same session.xml, allowing one user to load the previous session of another.

Suggest the default non-%APPDATA% location for session.xml, config.xml, &etc be moved to a `/Users/` or `/Documents/` directory.

**Comment by xomx** [comment] 2023-12-04 10:11
Duplicate of #14421 .

**Closed** 2023-12-04 15:14 UTC
