### ISSUE TITLE
Double click selects the whole sentence not just the word

### ISSUE THREAD

**Issue by xcitedk** [notepad-plus-plus/notepad-plus-plus#3192] opened 2017-04-21 08:12 UTC
### Description of the Issue
Double click selects the whole sentence not just the word

### Steps to Reproduce the Issue
Double click a word in a sentence

### Expected Behavior
The word is selected (highlighted)

### Actual Behavior
The sentence is selected (highlighted)

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by Yaron10** [comment] 2017-04-28 13:25
@xcitedk,

Is this behavior consistent on your machine?

**Comment by dail8859** [comment] 2017-04-28 14:04
I merged PR #3139 which *potentially* fixes this issue but since I can't consistently reproduce it I am not sure. At the bottom of that pull request there is a link to the appveyor build if anyone wants to give it a try.

**Comment by Yaron10** [comment] 2017-04-28 14:30
Hello dail,

Thank you very much for https://github.com/notepad-plus-plus/notepad-plus-plus/pull/3139. Thanks also for the reference here.

As for your build: the problem is inconsistent on my machine; it happened today after some 10 "good days".
I hope your assumption is correct and I wish someone on whose machine the problem is consistent would test it.

Best regards.

**Comment by hiphiphiphiphip** [comment] 2017-05-08 04:43
Same (annoying) issue here. It probably happened after last update but not sure.

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : HTMLTag_unicode.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll print.dll XMLTools.dll

**Comment by dail8859** [comment] 2017-08-29 12:44
This bug hasn't been reported in a while and hopefully c63673a1d8f4774bfcbd01c11d7cb4fc09b9fb2c was the actual fix to it in v7.4 and afterwards. If you run into this issue again please reopen.

**Closed by dail8859** 2017-08-29 12:44 UTC
