### ISSUE TITLE
Saving as using forbidden character

### ISSUE THREAD

**Issue by MacWarrior** [notepad-plus-plus/notepad-plus-plus#5032] opened 2018-11-19 10:38 UTC
### Description of the Issue
Under Windows 10 PRO x64 (1809 - 17763.134), with Notepad++ x64 7.6
Saving to a new file allow the use of ":" character which is forbidden as file name on windows.
This action generate a file with a wrong name "test" instead of "test : test" ; this file is empty, not editable and not deletable

### Steps to Reproduce the Issue
1. Type something in new tab
2. Use save as function
3. Specify a name with the character ":", example : "Test : file.txt"

### Expected Behavior
The character ":" must be forbidden (And some others, I guess), or replaced

### Actual Behavior
The character is allowed, generating an incorrect file which is empty (0ko), not editable, not deletable in the specified directory

### Debug Information
Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by MacWarrior** [comment] 2018-11-19 10:39
I'm also taking any information about how to delete the generated files ; when trying to delete from explorer or from command prompt (as admin), the file seems to not exists

**Comment by MacWarrior** [comment] 2018-11-19 10:56
To delete therse file : 
- Open command prompt with admin rights
- Type : del "\\?\FILEPATH"

In my case, I used the autocompletion for filename (in command prompt, it was the displayed filename + space)

**Comment by SinghRajenM** [comment] 2018-11-20 15:11
Duplicate of #4956

**Closed** 2018-11-20 23:10 UTC
Labels: duplicate
