### ISSUE TITLE
Support kotlin programming language if possible

### ISSUE THREAD

**Issue by wo4chenkewen** [notepad-plus-plus/notepad-plus-plus#9818] opened 2021-04-30 01:50 UTC
As kotlin programming language becomes more and more popular, so I wish the notepad++ can support kotlin language. 
                                                                                                                                                         Many thanks to notepad++ team

**Comment by mere-human** [comment] 2021-04-30 08:11
There is no syntax highlighting for Kotlin in Scintilla (a component that is used in Notepad++). I've checked in SciTE 5.0.
So it seems, the only way to add it is to use [UDL](https://npp-user-manual.org/docs/user-defined-language-system/).

**Closed** 2021-04-30 12:04 UTC

**Comment by ArkadiuszMichalski** [comment] 2021-04-30 12:57
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3266.
