### ISSUE TITLE
Anomoly with Column Mode Editing when Right-Aligned

### ISSUE THREAD

**Issue by ESHughes** [notepad-plus-plus/notepad-plus-plus#1635] opened 2016-03-15 22:34 UTC
If you right align the editor, then use column mode to select text in multiple columns (alt + mouse drag), it appears to affect text in the wrong column (as though it were left aligned).

Steps to reproduce:
1. Right align the editor (control + alt + R)
2. Add multiple lines containing e.g. 0123456789.
3. Use column select to select 789 in multiple columns by holding alt, clicking and dragging to affect multiple lines.  (note: this affects all editing via column select, e.g. plain insertion or deletion via column select).
4. Start typing replacement text e.g. "abc".

Expected result:
0123456abc in each line
Actual result:
abc3456789 in each line

**Comment by MetaChuh** [comment] 2019-04-13 02:30
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:30 UTC
