### ISSUE TITLE
smart highlighting fails if complete last line is selected

### ISSUE THREAD

**Issue by ebmoll** [notepad-plus-plus/notepad-plus-plus#6280] opened 2019-10-28 14:27 UTC
### Description of the Issue
Smart highlighting (SH) does not highlight occurences of the selected word if the selected word is alone on the last line. If it is followed by a newline, SH works again.

### Steps to Reproduce the Issue
- Enable "Smart Highlighting"
- Open a new document 
- type
```
hello
hello
```
(no newline after the second hello)
- double-click the second "hello" to mark it

### Expected Behavior
The first hello should now be smart-highlighted

### Actual Behavior
SH fails to highlight the first "hello". If you select the first hello, SH works as expected.

### Debug Information
Notepad++ v7.6   (64-bit)
Build time : Nov 13 2018 - 00:12:05
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

Might be related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4508

PS: Thanks for the great software! NP++ is definitely my favorite editor on Windows!

**Comment by sasumner** [comment] 2019-11-20 19:54
Step 3 really makes the whole thing nonsensical:  `type hellohello (no newline after the second hello! means newline)`

Why don't you just show the text inside a code block, something like this:

```
I'm line 1
I'm line 2
```

If you do that it might be possible to understand this.

**Comment by ebmoll** [comment] 2019-11-21 11:21
@sasumner: Sorry, the GitHub-flavored markdown removed my `<Enter>`... didn't know that you had to escape angled brackets, and forgot to check the result. Now it should be understandable.

I can't reproduce the issue in Notepad v7.8.1 (64bit), so I tried to reinstall an older Version; I couldn't reproduce it in 7.6.3 (64bit) either, nor in v7.5.6; Couldn't find an installer for 7.6., so I couldn't retest it.

**Comment by sasumner** [comment] 2019-11-21 13:58
Thanks for clarifying.  I tested in 7.6 and could not reproduce.  I also cannot reproduce in 7.8.1 so I'm going to close this issue.

**Closed by sasumner** 2019-11-21 13:58 UTC

**Comment by sasumner** [comment] 2020-09-27 12:55
This was reproducible by the very similar #8908 in 7.8.9 ; not sure why I couldn't reproduce it, above.
