### ISSUE TITLE
Crash after Closing all Unchanged in other view

### ISSUE THREAD

**Issue by hodderr1** [notepad-plus-plus/notepad-plus-plus#7897] opened 2020-01-28 13:15 UTC
### Description of the Issue
Notepad++ Crashes after closing all unchanged in other view whether the tabs are currently in other view, or if first view is closed first and then closing all unchanged with remaining tabs that came from other view.

Any help would be helpful or if somehow this could get to author.

**Comment by sasumner** [comment] 2020-01-28 13:33
Please set up a simple step-by-step reproduction technique.  Reference the issue template that you had to ignore to create the issue you did.

**Comment by hodderr1** [comment] 2020-01-28 14:09
### Description of the Issue
Notepad++ Crashes after closing all unchanged in other view whether the tabs are currently in other view, or if first view is closed first and then closing all unchanged with remaining tabs that came from other view.

### Steps to Reproduce the Issue

1. Open four files.
2. Move two to other view.
3. Close All Unchanged in first(Left) view.
4. Close All Unchanged of remaining files (Now fullscreen).

### Expected Behavior
Close all unchanged files leaving a blank _new_ tab.

### Actual Behavior

![image](https://user-images.githubusercontent.com/60391638/73270849-84b7b100-41ad-11ea-8fee-d290699ddb64.png)

Closes Application

### Debug Information
.dmp file type not supported however can provide via other means

**Comment by Ekopalypse** [comment] 2020-01-28 14:22
Seems to be a problem with 7.8.2 but not with 7.8.3, at least for me on Win7 and x64

**Comment by xylographe** [comment] 2020-01-28 14:26
Duplicate of #7708, which has been fixed in commit 9729fa749057b89e7e3459f794b74306c229c814.

**Comment by donho** [comment] 2020-01-28 16:10
Since you didn't post the version number, I suppose that you use an old version of Notepad++
This issue has been fixed.

**Closed by donho** 2020-01-28 16:10 UTC

**Comment by sasumner** [comment] 2020-01-28 16:18
@donho said:

>Since you didn't post the version number

Don, maybe there is value in changing the issue template from:

```
### Debug Information
<!--- Debug Info can be found under under the "?" menu -->

```
to:

```
### Debug Information
<!--- "Debug Info..." can be found under under the "?" menu -->
<!--- Please choose that, then click "Copy debug info into clipboard", and then PASTE HERE!
```

??

**Comment by xylographe** [comment] 2020-01-28 20:39
@sasumner You're amazingly optimistic. :-)

**Comment by sasumner** [comment] 2020-01-28 20:56
@xylographe 

I'm overly optimistic that Don will actually change the template? ;)

Or that people might actually follow the template for submitting an issue when it is (apparently) very easy to ignore it? ;)

No, I think you are meaning specifically the "Debug Info" pasting into an issue.  But...I think a lot of people are confused as to what "Debug Info" really means (in the Notepad++ sense).  I think if it were called "Version and other info" people would understand it better, and would gladly provide it.

Plus, maybe some are confused by the `?` menu.  Perhaps (as some have stated) it would be better to be in a more conventional `Help` > `About...` menu.  BUT, I'm not advocating for that kind of change, just perhaps a slight improvement to the template, so we don't have to drag out of issue submitters the basics, including what version they are reporting an issue against.  Of course it is always going to be "the latest", but an issue can get quite old before it is dealt with.  (I know you already know all this).

**Comment by xylographe** [comment] 2020-01-28 21:20
I believe, replacing "?" with "Help" (and "Notepad++ Online Document" with "Notepad++ User Manual") would be a positive development in general. But in regard to following the issue template, I'm afraid nothing can be done. If it requires more than clicking a button in the web browser, at least 4 out of 5 posters can't be bothered.

**Comment by sasumner** [comment] 2020-01-28 21:36
Perhaps moving forward the policy should be "no debug info" means instant rejection and closure of issue?

**Comment by xylographe** [comment] 2020-01-28 21:46
Yes, if it is a bug report, it is meaningless without the debug info. Perhaps, always close with a default reply, smth like,
```
Closing, due to missing debug info.
Feel free to reopen when you're ready to disclose the missing info.
```
Obviously, enhancement requests, etc. do not require debug info.
