### ISSUE TITLE
Remove non-bookmarked lines feature loops itself badly

### ISSUE THREAD

**Issue by Dum4G** [notepad-plus-plus/notepad-plus-plus#14288] opened 2023-10-28 23:43 UTC
### Description of the Issue
If you try this feature on a large file you will see an expanentional growth in RAM consumption, at some point it will fail and do nothing but keep hogging your memory

### Steps to Reproduce the Issue

1. Download http://5.9.147.111/epg/epg_1.xml.gz
2. Set your Mark querry as follows
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/5430116/8d2ded2c-265a-4add-b948-b0acb7d499b8)
3. Mark dem all
4. Choose "Remove Non-Bookmarked Lines"
5. Enjoy the turmoil
![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/5430116/f9bb8963-709b-49ba-a558-242f9f92fd18)

### Expected Behavior

1. To save all marked lines in memory (copying and cutting them works just fine)
2. To clean every line
3. To paste querried lines from memory
4. RAM gets cleaned from remnants of the task
### Actual Behavior
Either some unnecessary loop or huge memory leak happens. Even after it fails ands gets responsive again memory is being hogged until you close Notepad++
### Debug Information

Notepad++ v8.5.8   (64-bit)
Build time : Oct 15 2023 - 21:43:56
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 21H1
OS Build : 19043.1526
Current ANSI codepage : 1251
Plugins : 
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.5)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by xomx** [comment] 2023-10-29 00:08
Duplicate of #14188 & #13442 .
Workaround: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13442#issuecomment-1500444647

**Closed** 2023-11-07 16:07 UTC

**Comment by Dum4G** [comment] 2023-11-07 17:48
Can someone tell me what's the essential usecase of Display change history? maybe there's some vibe going around having those feature? Repeated my test with exactly the same file under the same circumstances with an artifact from https://github.com/notepad-plus-plus/notepad-plus-plus/commit/69998ab7dec86c2fcf4f8381ce10f5a7d09574de: it took
29 (!) minutes of time and additional 1.5gb of additional RAM to acomplish this. Also 16% of i7 6700k processing time which is still far from potatoest CPUs that available. Even funnier to watch how it's going to take the same amount of time to undo the change that was supposed to happen as a single action. Isn't it effective to just keep in memory previous version as is or compile a diff?

**Comment by donho** [comment] 2023-11-08 00:00
@Dum4G 
I tested with the file & the instructions you provided. Here are the results: 
* 13 minutes on build with #14288 (my local build x64 release mode), all non-marked lines are removed.
* ~20 minutes on v8.5.8 official release (x64 release mode), some non-marked lines are removed (total lines before the operation: 5637429, remained lines after operation:  5535091)

**Comment by Dum4G** [comment] 2023-11-08 00:48
@donho but shouldn't that happen in a blink of an eye? I can't imagine someone deciding to be like: I removed 5535091 lines out of 5637429, now i expect to return to an intermediate state where it was 234665 lines left. Speaking of having a history, I went to sleep and did not wait for the process to undo the change to happen, that's not even dramatizing

**Comment by Dum4G** [comment] 2023-11-08 01:02
I just realized it acts the same even with Display history being disabled

**Comment by Dum4G** [comment] 2023-11-11 21:41
@donho Is there a chance that the feature behaviour would be reconsidered or some fast and intuitive option would be provided? As of now I don't think we've got a proper fix for the issue IMO
