### ISSUE TITLE
<Feature Request> Golang Support

### ISSUE THREAD

**Issue by reezius** [notepad-plus-plus/notepad-plus-plus#3037] opened 2017-03-14 16:26 UTC
### Steps to Reproduce the Issue

1. Support .go file format like all current file formats

**Comment by MAPJe71** [comment] 2017-03-14 19:11
This is probably only going to happen when someone is willing to implement a Go/Golang lexer for Scintilla (see [its feature request](https://sourceforge.net/p/scintilla/feature-requests/750/)) or implement an external lexer as a Notepad++ plugin.

**Comment by dail8859** [comment] 2017-03-14 22:10
It looks like SciTE has some sort of [Go support](https://sourceforge.net/p/scintilla/scite/ci/default/tree/src/cpp.properties#l18) and it just reuses the Cpp lexer but I've never tried it.

Duplicate of #2574 and #1222

**Comment by MetaChuh** [comment] 2019-05-01 20:14
please use one of the golang udls like: https://gist.github.com/blinksmith/99e5234ea601af8ba8bfab35c8fbebef

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 20:14 UTC
