### ISSUE TITLE
Build failing with WinLibs (problem with mingw32-make)

### ISSUE THREAD

**Issue by samyarkhafan** [notepad-plus-plus/notepad-plus-plus#14902] opened 2024-03-24 09:49 UTC
### Description of the Issue
Even with both of the path variables pointing to the bin folder of my mingw64 installation, the build fails because it cannot find the path, what's more interesting is that it tries to go to D:/Prog/winlibs64ucrt_stage/mingw64/bin/x86_64-w64-mingw32-g++.exe
even though the path variable I set is D:\Apps\mingw64\bin

### Steps to Reproduce the Issue
1. Clone the repo and cd into PowerEditor and then to gcc (I am using winlibs with posix threads and ucrt without llvm and clang with gcc 13.2.0, its the version above all the others if you go to winlibs.com).
2. Run mingw32-make.
3. Tries to go to a "Prog" folder which I do not have and throws error 2.

### Expected Behavior
Build finishing without errors.

### Actual Behavior
Tries to go to a non existing folder and throws error 2.

### Debug Information
+ creating BUILD_DIRECTORY bin.x86_64-debug.build
+ creating SCINTILLA_BUILD_DIRECTORY bin.x86_64-debug.build/_scintilla.build
process_begin: CreateProcess(NULL, D:/Prog/winlibs64ucrt_stage/mingw64/bin/x86_64-w64-mingw32-g++.exe -DDEBUG -I ../include -I ../src -I ../../boostregex --std=c++17 -Wpedantic -Wall -Wextra -g -DSCI_OWNREGEX -c ../src/AutoComplete.cxx -o ../../PowerEditor/gcc/bin.x86_64-debug.build/_scintilla.build/AutoComplete.o, ...) failed.
make (e=2): The system cannot find the file specified.
D:/Prog/winlibs64ucrt_stage/mingw64/bin/x86_64-w64-mingw32-g++.exe -DDEBUG -I ../include -I ../src -I ../../boostregex --std=c++17 -Wpedantic -Wall -Wextra -g -DSCI_OWNREGEX 
-c ../src/AutoComplete.cxx -o ../../PowerEditor/gcc/bin.x86_64-debug.build/_scintilla.build/AutoComplete.o
mingw32-make[1]: *** [makefile:74: ../../PowerEditor/gcc/bin.x86_64-debug.build/_scintilla.build/AutoComplete.o] Error 2
mingw32-make: *** [makefile:228: bin.x86_64-debug.build/libscintilla.a] Error 2

**Comment by rdipardo** [comment] 2024-04-07 21:02
I can reproduce exactly and it seems the WinLibs distribution [is broken](https://github.com/brechtsanders/winlibs_mingw/issues/183).

As a workaround, you would have to:

1. unpack the toolchain into the hard-coded directory path, e.g, by first mounting a `D:` drive:

<details>
<summary>dir /b D:\Prog\winlibs64ucrt_stage\mingw64\bin</summary>
<pre>
<code>
addr2line.exe
ar.exe
as.exe
c++.exe
c++filt.exe
ccache.exe
cmake.exe
cmcldeps.exe
cpack.exe
cpp.exe
ctest.exe
dlltool.exe
dllwrap.exe
dos2unix.exe
doxygen.exe
elfedit.exe
g++.exe
gcc-ar.exe
gcc-nm.exe
gcc-ranlib.exe
gcc.exe
gcov-dump.exe
gcov-tool.exe
gcov.exe
gdb-add-index
gdb.exe
gdbserver.exe
gendef.exe
genidl.exe
gfortran.exe
gprof.exe
iconv.exe
jwasm.exe
ld.bfd.exe
ld.exe
libarchive-13.dll
libatomic-1.dll
libbz2.dll
libcurl-4.dll
libdl.dll
libexpat-1.dll
libgcc_s_seh-1.dll
libgcrypt-20.dll
libgfortran-5.dll
libgmp-10.dll
libgnutls-30.dll
libgomp-1.dll
libgomp-plugin-nvptx-1.dll
libgpg-error6-0.dll
libgss-3.dll
libhiredis.dll
libhogweed-6.dll
libiconv-2.dll
libidn-12.dll
libidn2-0.dll
libintl-8.dll
libisl-23.dll
liblzma-5.dll
liblzo2-2.dll
libmpc-3.dll
libmpfr-6.dll
libncursesw6.dll
libnettle-8.dll
libpsl-5.dll
libpython3.9.dll
libquadmath-0.dll
librhash.dll
librtmp-1.dll
libshishi-0.dll
libsource-highlight-4.dll
libssh2-1.dll
libssp-0.dll
libstdc++-6.dll
libtasn1-6.dll
libunistring-5.dll
libuv-1.dll
libwinpthread-1.dll
libzstd.dll
lto-dump.exe
lz4-1.dll
mac2unix.exe
mingw32-make.exe
mman-win.dll
nasm.exe
ndisasm.exe
ninja.exe
nm.exe
objcopy.exe
objdump.exe
pexports.exe
ranlib.exe
readelf.exe
size.exe
strings.exe
strip.exe
unix2dos.exe
unix2mac.exe
vsyasm.exe
widl.exe
windmc.exe
windres.exe
x86_64-w64-mingw32-c++.exe
x86_64-w64-mingw32-g++.exe
x86_64-w64-mingw32-gcc-13.2.0.exe
x86_64-w64-mingw32-gcc-ar.exe
x86_64-w64-mingw32-gcc-nm.exe
x86_64-w64-mingw32-gcc-ranlib.exe
x86_64-w64-mingw32-gcc.exe
x86_64-w64-mingw32-gfortran.exe
xxhash.dll
yasm.exe
ytasm.exe
zlib1.dll
</code>
</pre>
</details>


2. start a terminal session in [MSYS2](https://www.msys2.org/#installation) or [Git for Windows](https://gitforwindows.org/) (there __*must*__ be a `sh.exe` program on the `PATH`); then build:

~~~sh-session
$ export PATH="/d/Prog/winlibs64ucrt_stage/mingw64/bin;$PATH"
$ export VERBOSE=1
$ mingw32-make.exe
+ creating BUILD_DIRECTORY bin.x86_64.build
C:/git/2.44.0.windows.1/usr/bin/mkdir.exe -p bin.x86_64.build bin.x86_64.build/DarkMode bin.x86_64.build/MISC/Common bin.x86_64.build/MISC/Exception bin.x86_64.build/MISC/PluginsManager bin.x86_64.build/MISC/Process bin.x86_64.build/MISC/RegExt bin.x86_64.build/MISC/md5 bin.x86_64.build/MISC/sha1 bin.x86_64.build/MISC/sha2 bin.x86_64.build/MISC/sha512 bin.x86_64.build/ScintillaComponent bin.x86_64.build/TinyXml bin.x86_64.build/TinyXml/tinyXmlA bin.x86_64.build/WinControls/AboutDlg bin.x86_64.build/WinControls/AnsiCharPanel bin.x86_64.build/WinControls/ClipboardHistory bin.x86_64.build/WinControls/ColourPicker bin.x86_64.build/WinControls/ContextMenu bin.x86_64.build/WinControls/DockingWnd bin.x86_64.build/WinControls/DocumentMap bin.x86_64.build/WinControls/FileBrowser bin.x86_64.build/WinControls/FindCharsInRange bin.x86_64.build/WinControls/FunctionList bin.x86_64.build/WinControls/Grid bin.x86_64.build/WinControls/ImageListSet bin.x86_64.build/WinControls/OpenSaveFileDialog bin.x86_64.build/WinControls/PluginsAdmin bin.x86_64.build/WinControls/Preference bin.x86_64.build/WinControls/ProjectPanel bin.x86_64.build/WinControls/ReadDirectoryChanges bin.x86_64.build/WinControls/SplitterContainer bin.x86_64.build/WinControls/StaticDialog bin.x86_64.build/WinControls/StaticDialog/RunDlg bin.x86_64.build/WinControls/StatusBar bin.x86_64.build/WinControls/TaskList bin.x86_64.build/WinControls/ToolTip bin.x86_64.build/WinControls/TrayIcon bin.x86_64.build/WinControls/TreeView bin.x86_64.build/WinControls/VerticalFileSwitcher bin.x86_64.build/WinControls/WindowsDlg bin.x86_64.build/WinControls/shortcut bin.x86_64.build/WinControls/tabbar bin.x86_64.build/WinControls/toolbar bin.x86_64.build/uchardet
+ creating SCINTILLA_BUILD_DIRECTORY bin.x86_64.build/_scintilla.build
C:/git/2.44.0.windows.1/usr/bin/mkdir.exe -p bin.x86_64.build/_scintilla.build
D:/Prog/winlibs64ucrt_stage/mingw64/bin/mingw32-make.exe -O --no-print-directory -j4 -C ../../scintilla/win32 -f makefile -f ../../boostregex/nppSpecifics_mingw.mak DIR_O=../../PowerEditor/gcc/bin.x86_64.build/_scintilla.build LIBSCI=../../PowerEditor/gcc/bin.x86_64.build/libscintilla.a ../../PowerEditor/gcc/bin.x86_64.build/libscintilla.a
# [...]
~~~

**Comment by samyarkhafan** [comment] 2024-04-13 13:21
sorry for the late reply. glad to know it ain't something on my end.

**Comment by brechtsanders** [comment] 2024-06-08 17:25
You shouldn't need MSYS2 shell for running `mingw32-make`.

The way to make it use the correct compiler path is by setting environment variable `CXX` to the full path of `x86_64-w64-mingw32-g++.exe` (and `CC` for `x86_64-w64-mingw32-gcc.exe`).

Environment variables is usually how IDE's specify the compiler tools when they call `make` (or `mingw32-make` in this case). For example that is what the Code::Blocks settings mentioned [here](https://winlibs.com/#usage-codeblocks) are for.

Does Notepad++ have this option?

**Comment by ArkadiuszMichalski** [comment] 2024-07-04 12:10
I just lost some time due to this problem so I'm reopening this issue. I noticed that something in `mingw32-make.exe` has changed and this problem occurs in newer versions, if we use the one with `WinLibs GCC 13.1.0` everything works fine (we can even copy this working version to newer Winlibs). Here more details https://github.com/brechtsanders/winlibs_mingw/issues/183#issuecomment-2208798394.

I will try to check the make repo later whether this change for default CXX detection is intentional or not.

**Comment by brechtsanders** [comment] 2024-07-10 09:40
The issue reported [here](https://github.com/brechtsanders/winlibs_mingw/issues/183) has been resolved in the latest [winlibs.com](https://winlibs.com/) builds at:
- https://github.com/brechtsanders/winlibs_mingw/releases/download/14.1.0posix-18.1.8-12.0.0-msvcrt-r3
- https://github.com/brechtsanders/winlibs_mingw/releases/download/14.1.0posix-18.1.8-12.0.0-ucrt-r3

Can anyone confirm this issue is also gone using one of those releases?

**Comment by ArkadiuszMichalski** [comment] 2024-07-10 09:46
@brechtsanders Yes, it was fixed.

**Closed by ArkadiuszMichalski** 2024-07-10 09:46 UTC
Labels: build / code
