### ISSUE TITLE
folding issue with user defined language

### ISSUE THREAD

**Issue by Nicolas-withANumberAtTheEnd** [notepad-plus-plus/notepad-plus-plus#1423] opened 2016-01-28 10:16 UTC
Hello,

I try to fold a code according a user defined language. The keywords used to define the beginning and the end of the folding are a sequence of two words (namely BEGIN CASE and END CASE). The middle keyword is CASE. As described in the UDL2.0 website ([http://udl20.weebly.com/folding-in-code.html]), I use the quotation mark (") to enclose the beginning and ending keywords.
Nevertheless, the folding does not behave as expected as can be seen with the following example :
`bla`
`BEGIN CASE`
`CASE cond1`
`__IF cond11 THEN`
`____blah`
`__END`
`__foo`
`CASE cond2`
`__some`
`__code`
`END CASE`
`foo`

I don't know how if it is a scintilla bug or a notepad++ bug, so I hope I didn't post in the wrong place.

Note that I also tried without the quotation mark, and I tried to use the two folding style (forward and backward) but it does not solve the issue.

I use the last version of Notepad++ (v6.8.8).

Best,

**Comment by Nicolas-withANumberAtTheEnd** [comment] 2016-02-03 08:34
Hello, I guess it's not the right place to post. I will ask in the Scintilla bug tracker.

**Comment by dFxed** [comment] 2018-02-20 08:54
Not a bug,

please use folding 2

`Example 3
Use of multi-part keywords is supported in Folder in code 2, as you can see in this example.`

**Comment by ilegacy** [comment] 2018-03-13 14:05
I searched a long time and still didn't find a solution. I want to fold form { to } and this just doesn't work in my user defined language. It DOES work when I define a word like "proc" or "function" but NOT when I define { or } as start/end of the fold.

Does anyone know how this works? The only threads I can find is full of people having the same issue but nobody has a solution :(

![image](https://user-images.githubusercontent.com/12360416/37346596-0065bc84-26d0-11e8-867e-61f04f95a21c.png)

**Comment by ilegacy** [comment] 2018-03-13 14:10
Note: I think I found the solution. As long as { and } are defined as Operators, the folding does NOT work:

![image](https://user-images.githubusercontent.com/12360416/37346756-8330e1f2-26d0-11e8-970f-9589ed71c38a.png)

As soon as you remove the symbols there, the folding starts working :)

**Comment by MetaChuh** [comment] 2019-04-13 01:43
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:43 UTC
