### ISSUE TITLE
Notes for updating N++'s Scintilla beyond 5.x

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [notepad-plus-plus/notepad-plus-plus#10504] opened 2021-09-04 10:58 UTC
Notepad++ 8.1.4 (current version as of this writing) uses Scintilla version 4.4.6. Starting from Scintilla 5.0.0 we have:
>First version that separates Lexilla from Scintilla. Each of the 3 projects now has a separate history page but history before 5.0.0 remains combined.

https://github.com/ScintillaOrg/lexilla
https://www.scintilla.org/Lexilla.html
https://www.scintilla.org/LexillaDoc.html
https://www.scintilla.org/ScintillaDoc.html#alpha

Issues fixed after the update:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10925
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10651
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10908
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10706
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10065
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10423
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3858
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9229
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8359
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8087
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/63
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5264
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5805, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5750

Issues that can be fixed after the update:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11413
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10171
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10991
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11014
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10301
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1260

Even some early version (Notepad++ with new Scintilla/Lexilla) for testing would be advisable to catch possible problems.

**Comment by ivan-u7n** [comment] 2021-09-04 14:42
> Notepad++ 8.4 (current version as of this writing) uses Scintilla version 4.4.6. Starting from Scintilla 5.0.0 we have:

A time traveller! :) In my time it's still `8.1.4`.

> Even some early version (Notepad++ with new Scintilla/Lexilla) for testing would be advisable to catch possible problems.

I wanted to wait for a next release of Lexilla (which will include my latest patch) and then to try the update. However I have no idea whether it will succeed, for I'm not that good at GUI coding.

**Comment by ozone10** [comment] 2021-09-04 18:44
This will also allow autocomplete to be dark (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10171)

**Comment by dail8859** [comment] 2021-09-07 11:37
In one of my projects I moved from Scintilla v4.x to v5.x and found that overall no _major_ changes are needed, but alot of code will need touched.

Setting lexers is different now. You have to use Lexilla to instantiate the lexer by name (not by a SCI_xxx constant). Not sure if the names in the Notepad++ config files have the proper lexer names or not...I think they are close if not completely accurate.

The interface to Scintilla has changed (not sure if the old interface is still available in Win32). From the release notes for v5.0.3:
> A more type-safe binding of Scintilla's API that can be used from C++ is implemented in the ScintillaTypes.h, ScintillaMessages.h, and ScintillaStructures.h headers.

And v5.1:
> Add more type-safe wrappers to the API. These are defined in include/ScintillaCall.h and implemented in call/ScintillaCall.cxx. ScintillaCall throws Scintilla::Failure exceptions when a call fails.

This adds a strongly typed interface which makes the code safer and more readable, but potentially a bit more verbose (not always a bad thing).

My biggest concerns for Notepad++ would be plugin compatibility and external lexers.

**Comment by Kered13** [comment] 2021-10-16 11:15
> The interface to Scintilla has changed (not sure if the old interface is still available in Win32).

It is:
https://sourceforge.net/p/scintilla/code/ci/default/tree/include/Scintilla.h
https://sourceforge.net/p/scintilla/code/ci/default/tree/win32/ScintillaWin.cxx

This means that plugins should mostly still be compatible.

**Comment by ArkadiuszMichalski** [comment] 2021-11-03 13:44
@donho Any approximate time when it will be updated?

**Comment by donho** [comment] 2021-11-03 16:05
@ArkadiuszMichalski 
I cannot estimate the approximate time, but it's for sure that update Scintilla to v5.x will be in v8.2 (next release) if there's no critical regression/bug in v8.1.9 (after auto-update being triggered for v8.1.9).

**Comment by alankilborn** [comment] 2022-01-03 20:51
>but it's for sure that updating Scintilla to v5.x will be in v8.2

I must have missed the change.log entry for this.  :-(

A long-time user (me!) would like to see a N++ release that integrates Scintilla 5.1.2 or later.  :-)

**Comment by chcg** [comment] 2022-01-06 00:10
@donho Do you have an updated timeframe for the move to scintilla 5?
I created a test branch for the integration at https://github.com/chcg/notepad-plus-plus/tree/scintilla5 with the current versions 
- https://www.scintilla.org/scintilla515.zip
- https://www.scintilla.org/lexilla514.zip

Testbinaries could be found at https://ci.appveyor.com/project/chcg/notepad-plus-plus/builds/42099721.

Seems it is mostly working.
Known issues:
- More rework is necessary for usage of CreateLexer with lexer names without deprecated ID interface
- Some code is still commented out as there seems to be no direct replacement for SCI_LOADLEXERLIBRARY.  
- Searchresult window seems to have a problem with highlighting the search phrase.
- makefile changes needs to be checked
- ...

**Comment by ArkadiuszMichalski** [comment] 2022-01-06 01:19
Maybe Lexilla itself could be updated more often, because now we have to wait a long time for small corrections in lexers.

**Comment by donho** [comment] 2022-01-06 17:44
@chcg 
> I created a test branch for the integration at https://github.com/chcg/notepad-plus-plus/tree/scintilla5 with the current versions

Nice job! Though you have already built a branch for that. I still want to do it myself - not because of the lack of trust for your work, but for learning the new Scintilla component, by benefiting from your experience of course.

> Do you have an updated timeframe for the move to scintilla 5?

It was planned to be done earlier (and as I said in v8.2). Due to the several regressions from v8.1.6 to v8.1.9.3, I have had no time to do it. 
It "seems" v8.2 is stabilized (*knocking on wood very hard*), I would like take this chance to do one more release in order to include some bug-fixes and enhancements from the long time old issue tickets.
OTOH, I will move in January; I am surely less present in this month. As a result I guess I will be able to start this task on the beginning of February.  
Do you think this Scintilla updated time frame is reasonable?

**Comment by chcg** [comment] 2022-01-06 17:53
@donho As stated above there a still some obstacles in the way. So it seems fine for me to have a stabilisation phase for the current version. In parallel the problems with scintilla 5 could be analysed and hopefully fixed. The time frame is fine for me.

**Comment by ArkadiuszMichalski** [comment] 2022-01-11 18:40
This was a problem at Geany: [SCI_GETTEXT & friends API change in Scintilla 5.1.5](https://sourceforge.net/p/scintilla/bugs/2308/).

**Comment by rdipardo** [comment] 2022-01-11 19:34
> This was a problem at Geany: [SCI_GETTEXT & friends API change in Scintilla 5.1.5](https://sourceforge.net/p/scintilla/bugs/2308/).

### Some additional context

Scintilla 5.1.5 changed the return value of the SCI_GETTEXT, SCI_GETSELTEXT and SCI_GETCURLINE APIs, which now "pass the whole string __*including any NUL bytes*__": <https://groups.google.com/g/scintilla-interest/c/DoRE5t2vihE>

Without refactoring [^1], copy/paste functions can result in fatal allocation errors: https://github.com/geany/geany/issues/3095
The regression is serious enough that Geany's maintainers have asked Scintilla to consider reverting the APIs


[^1]: The [Scintilla mailing list](https://groups.google.com/g/scintilla-interest/c/DoRE5t2vihE) offers some guidance on how to refactor:  "The normal technique is to call the Scintilla API with NULL as the string argument which returns the length. Then allocate a string of length+1 bytes (the +1 may be set to NUL). Then call the API with this allocated string. Use the resulting string in a way that ignores the trailing NUL. If using the C++ std::string type, an extra NUL byte is automatically allocated at the end which is not counted in std::string::length() so works without problems."

**Comment by kugel-** [comment] 2022-01-11 20:38
@rdipardo Wrong! The new return values do **not** include the NUL terminator.

> When calling SCI_GETTEXT, SCI_GETSELTEXT, and SCI_GETCURLINE with a NULL buffer argument to discover the length that should be allocated, do not include the terminating NUL in the returned value

**Comment by rdipardo** [comment] 2022-01-11 20:56
@kugel-, 
thanks; I see now the mailing list thread is actually a retrospective on the former API. 
Bullet 3 of the [v5.1.5 change log](https://www.scintilla.org/ScintillaHistory.html) should have been the point of reference

**Comment by alankilborn** [comment] 2022-01-11 21:08
>SCI_GETTEXT & friends API change in Scintilla 5.1.5.

Avoid any pain from that for the near term, and target something earlier than 5.1.5 for Notepad++ inclusion?

**Comment by alankilborn** [comment] 2022-01-11 22:01
>Don't forget the plugins

LOL.  Well, yes, my main concern (already thought about) is the PythonScript plugin.  Quite frankly, I would pick another text editor if I didn't have this.  But its interface to the new APIs is probably quite "wrapped" and thus necessary changes would be tightly localized.

But, yes, a concern for all plugins that might use these Scintilla APIs.

Perhaps not a ton of usage in the plugins either?  
Maybe I'm grossly underestimating... :)

**Comment by chcg** [comment] 2022-01-12 05:40
From a first look at least N++ itself is not affected by this change as N++ already allocated a buffer +1 in case of the changed apis, but at e.g. https://github.com/notepad-plus-plus/notepad-plus-plus/blob/68d339d224eba0fa7aeb2e0f7526b3311cc02c5a/PowerEditor/src/NppNotification.cpp#L700 in the understanding of version 5.1.5 we are trying to request one byte to much. In this case the requested length is not available and at
https://github.com/chcg/notepad-plus-plus/blob/scintilla5/scintilla/src/Editor.cxx#L5893
restricted to the document length (=requested one via wparam -1). So this will likely cause no direct issue of writing data beyond the buffer, but anyhow should be checked and adapted.

**Comment by rdipardo** [comment] 2022-02-03 01:02
Big news:

> The parallel layout feature has been committed. The application has to ask for it with the SCI_SETLAYOUTTHREADS(int threads) API as the default is single threaded. The number of threads is capped by the hardware concurrency of the CPU = number of cores, doubled if hyper-threaded.

> Sometimes it is faster to use fewer than the maximum number of threads but this is mostly in cases which are very fast anyway, such as when the file is (almost) all ASCII and the ASCII Monospace feature is active.

<https://groups.google.com/g/scintilla-interest/c/_W6NGQ5WNoE>

**Comment by donho** [comment] 2022-03-19 00:56
@chcg 
I just checked your branch https://github.com/chcg/notepad-plus-plus/tree/scintilla5 and compared the interface between v4.66 & v5.2.1. The change you've brought looks good and binary seems work fine - bravo!

In order to refine what you have done so far, could you please create a PR based on the branch, so the community could work on it together?

**Comment by DietmarSchwertberger** [comment] 2022-03-19 14:34
Recent Scintilla versions have support for displaying e.g. CR/LF in a different colour.

Search https://www.scintilla.org/ScintillaDoc.html for SC_REPRESENTATION_COLOUR and SCI_SETREPRESENTATIONCOLOUR

It would be great if this feature makes it into N++ as well.



The now closed feature request for Scintilla: https://sourceforge.net/p/scintilla/feature-requests/1129/

**Comment by donho** [comment] 2022-03-19 22:57
@DietmarSchwertberger 
Thank you for the information.
Could you open an issue for this feature request in Notepad++?
I will consider it.

**Comment by DietmarSchwertberger** [comment] 2022-03-20 14:01
@donho : Submitted as **https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11413**
Thanks a lot.

**Closed** 2022-03-27 15:13 UTC
Labels: scintilla dependent

**Comment by DietmarSchwertberger** [comment] 2022-04-02 19:21
Thanks a lot. Looking forward to the release.
I followed your donation recommendations.
