### ISSUE TITLE
Autocompletion v 6.8.5

### ISSUE THREAD

**Issue by lewispham** [notepad-plus-plus/notepad-plus-plus#1038] opened 2015-10-22 11:33 UTC
I feel quite uncomfortable with the autocompletion on v6.8.5 . Does Notepad++ have an option for using the v6.8.3 instead?

**Comment by sanastasiou** [comment] 2015-10-23 08:00
Agree. This has to be optional. It messes up with my DSL, and with someone's coding style in general.

**Comment by donho** [comment] 2015-10-25 01:09
Could you provide more info about the difference of auto-completion between 6.8.3 and 6.8.5?

**Comment by tresdin** [comment] 2015-10-25 03:52
Here are two differences that makes me feel uncomfortable.
```
//insert brackets inside brackets
    v6.8.3   (()),([]),({})
    v6.8.5   ((),([),({)
//Press enter inside blank curly brackets
v6.8.3
{
     //auto insert a tab
}
v6.8.5
{
//start at same position
}

**Comment by donho** [comment] 2015-10-26 10:08
@tresdin Thank you for your explanation.
About autocompletion part:
```
v6.8.3
{
     //auto insert a tab
}
v6.8.5
{
//start at same position
}
```
Could you confirm me that it's a javascript file that it doesn't work?

Regarding auto-insert part:
```
    v6.8.3   (()),([]),({})
    v6.8.5   ((),([),({)
```
There's no way back to the old behaviour, but I can always enhance it.
Could you give me exactly what you want (with the sequence of characters), I will see what can I do for it.

**Comment by tresdin** [comment] 2015-10-26 11:51
@donho 
- I've tested on several extensions including `js py cc css htm noextension` and this autocompletion only works on `css` and files without extension. I think this autocompletion should also be applied on these characters ```() [] "" '' `` ```.
- ```{ ( [ " ' ` ``` should be auto-close whether or not they are being inserted inside each others. This feature should not be applied inside string context (*inside ``` "" '' `` ```*).

*Backticks `` are used for defining [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings) in Javascript. It's part of ES6 standard.*

**Comment by donho** [comment] 2015-10-26 16:15
> ```{ ( [ " ' ` ``` should be auto-close whether or not they are being inserted inside each others. This feature should not be applied inside string context (*inside ``` "" '' `` ```*).

It's in the case already.

**Comment by tresdin** [comment] 2015-10-26 16:53
I have no further expectations at this time. My suggestion is actually a mix of v 6.8.3 and v6.8.5, plus the *backticks* support.

**Comment by ganego** [comment] 2015-10-26 18:59
Got the same problem also with 6.8.4/5 for normal text files.
I often need to write several brackets inside one another. But autocmplete does not do that anymore.

> There's no way back to the old behaviour, but I can always enhance it.
Could you give me what you expect exactly (with the sequence of characters), I will see what can I do for it.

I simply expect to add a closing bracket whenever I type an opening bracket, even if nested like three times in another bracket. This worked perfectly fine in 6.8.3. 
Thank you.

**Comment by donho** [comment] 2015-10-26 20:38
@ganego  v6.8.5 handle it quite good: [[[{{(([[""]]))}}]]]

**Comment by ganego** [comment] 2015-10-26 20:49
Ok this is strange. It did not work for me (tested several times) - then I made a new profile and it worked there. Then I removed the new profile (\appdata\roaming\) and used the old one again - now it works fine. No idea why. Anyway it works with 6.8.5 now as expected :)

**Comment by ganego** [comment] 2015-10-26 21:16
I had to delete my comment from a few minutes ago. 
I made a fresh profile (renamed the old \appdata\roamind\notepad++ folder). With 6.8.5.
Now enter the following:
(a(
What I expect: (a()) - what I get: (a().
With 6.8.3 I get what I would expect.

**Comment by ganego** [comment] 2015-10-30 09:19
Error is also in 6.8.6 for me when typing (a(.

**Comment by DarkNexusNR** [comment] 2015-12-06 03:13
This is still an issue with 6.8.7.
I type in (a["
Expect to see (a[""])
Instead see (a[")
This inconsistent behaviour breaks my workflow.

**Comment by sanastasiou** [comment] 2015-12-06 14:18
@DarkNexusNR Since we cannot reopen a ticket, I'd suggest you create a new one and link to this one.

**Comment by DarkNexusNR** [comment] 2015-12-07 00:22
@sanastasiou This ticket (Autocompletion v 6.8.5 #1038) is still open. Or is this being cloned somewhere else and this wasn't properly marked as closed?

**Comment by sanastasiou** [comment] 2015-12-07 00:25
@DarkNexusNR Ah my bad, it's ok. I saw the Closed of #1012 and mistook it for this one.

**Comment by vux777** [comment] 2015-12-07 13:46
agree with @DarkNexusNR 
pleas, bring back old behavior, inserting brackets and quotes at ANY point should auto-complete (if opt in)
[also here](https://notepad-plus-plus.org/community/topic/10915/auto-insert-is-not-working-if-there-is-following-char)

**Comment by DarkNexusNR** [comment] 2015-12-16 06:48
v6.8.8 is better but still not correct.
I type in (a(
Expect to see (a())
Instead see (a()
There is another mismatch with {'a':'}
It should be auto completing unless there is a unmatched closing bracket/brace. When typing brackets inside strings I would prefer it close except when I first escape it with backslash. The current string behaviour works well with single quotes.

**Comment by DarkNexusNR** [comment] 2016-02-15 01:44
This is still an issue with 6.9RC but I have a workaround.
Disable the auto complete and create macros which do the same thing.
You won't be able to save the macro with shift+9 but you can modify the shortcuts.xml afterwards to use the correct shortcut keys.

**Comment by devnull69** [comment] 2016-12-01 08:41
Still an issue with 7.1. Really annoying ... :-1:

**Comment by ganego** [comment] 2017-01-02 14:13
Ok I was annoyed enough that I was stuck on the old version to do something.
The problem lies in [THIS file](https://github.com/notepad-plus-plus/notepad-plus-plus/commits/master/PowerEditor/src/ScitillaComponent/AutoCompletion.cpp). Mainly those three "enhancements":
35adb1910ba98897ad3a935fa7d712a986289bd3, e81ac898c0d6703f943d4e12b65fea435c974f10, 65717312369588cbe2bfe356e912ae36645d76b3
Before the "enhancements" it would simply write the matching bracket if you typed one. The patches introduced some logic.
I patched the file based on the master from yesterday (so it includes the patches to this file after the ones breaking autocomplete). You can get the .cpp file [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/4ee9e35f619787535dfcbdb81fdfd848dc2156b3/PowerEditor/src/ScitillaComponent/AutoCompletion.cpp).
Sadly it does not compile with a small compiler like mingw so you have to download the VisualStudio monster that (at least for me) took more than 10GB for only the C compiler.
Download the official master and replace the file. 
If you never used VS before, after loading the project at the top choose Unicode Release and x86 (this is the 32bit version (npp website says 64bit might have problems with plugins). Then go to "Debugging" -> "Settings for Notepad++" -> "C/C++" and in the right window choose to not treat warnings as errors (/WX-). Then you can compile it. The .exe is in the source\PowerEditor\bin folder. Install newest notepad++, take this exe and replace the original one.

**Comment by MetaChuh** [comment] 2019-04-10 23:42
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:42 UTC
