### ISSUE TITLE
JS code highlight doesn't understand \` escaping from ES6

### ISSUE THREAD

**Issue by grumd** [notepad-plus-plus/notepad-plus-plus#2169] opened 2016-08-14 10:28 UTC
When using Javascript ES6 string with `` quotes, escaping a quote as \` will break the highlighting.
This makes all the following code highlight as a string.
[Screenshot](http://i.imgur.com/G3Buwmk.png)

Nodepad++ 6.9.2

**Comment by MetaChuh** [comment] 2019-04-12 00:00
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-12 00:00 UTC

**Comment by grumd** [comment] 2019-05-21 21:10
This is still reproducible in the latest vanilla version, no plugins installed.

![](https://puu.sh/Dvq2r.png)

Use this text and Javascript language setting, code highlighting will be broken:

```js
const string = `template string \` something`;

function getPage() {
	
}

const str = `class text const`;
```
