### ISSUE TITLE
The Update window menu is in English language only...

### ISSUE THREAD

**Issue by pboulerie** [notepad-plus-plus/notepad-plus-plus#3450] opened 2017-06-28 08:05 UTC
### Description of the Issue
The Update window menu is not internationalized ...
La fenêtre "Notepad++ update" n'est pas traduite en français...

> Notepad++ update
>
> An update package is available, do you want to download it?
>
> Oui / Non

### Expected Behavior

Should be translated into French as / Il faudrait afficher :
"Mise à jour de Notepad++"

Un paquetage de mise à jour est disponible, voulez-vous le télécharger et l'installer ?

**Comment by pboulerie** [comment] 2017-06-28 08:11
Other untranslated messages during the whole update and update installation process :

Downloading
button "Cancel"

Notepad++ is opened.
Updater will close it in order to process the installation.
Continue?
Oui / Non




Installer Language
Please select a language
(please note that "Français" is already selected on my computer...)
OK / Cancel







Missing translations also in :

Choisissez les composants

> Don't use %APPDATA%
> Allow plugins
> Create Shortcut



Size / Files / Folders


The rest of the menus and messages are OK, being already translated in French...

**Comment by ArkadiuszMichalski** [comment] 2023-02-13 10:54
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/13107.

**Closed by ArkadiuszMichalski** 2023-02-13 10:54 UTC
Labels: translation
