### ISSUE TITLE
Default Directory No Longer Remembered (Regression)

### ISSUE THREAD

**Issue by markofbrandon** [notepad-plus-plus/notepad-plus-plus#9863] opened 2021-05-13 23:13 UTC
### Description of the Issue

Settings / Preferences / Default Directory is not being remembered
### Steps to Reproduce the Issue

1.  Open a file, for example, G:\PROJ1\myfile.txt
2.  Try and open another file in the same folder.  The "last used directory" is not remembered.

### Expected Behavior

I expected the previous folder that I was working in to be remembered, so that other files could be easily opened from that same location.
### Actual Behavior

Attempting to open a file defaults back to the directory that NP++ is installed in instead of G:\PROJ1 in this example.
### Debug Information

Notepad++ v7.9.5   (32-bit)
Build time : Mar 21 2021 - 02:09:07
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (32-bit) 
OS Version : 2009
OS Build : 19042.985
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

This just started happening after upgrading to v7.9.5.  It was working fine earlier today.

**Comment by mere-human** [comment] 2021-05-14 07:22
This is a duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9767
It's been already fixed. In the next released version it should work fine.

**Closed** 2021-05-14 09:44 UTC
