### ISSUE TITLE
UI scaling for high-resolution desktop displays

### ISSUE THREAD

**Issue by milipili** [notepad-plus-plus/notepad-plus-plus#629] opened 2015-08-02 20:12 UTC
**DPI scaling for QVGA displays** {#147} 

> I've just received a Lenova Yoga 3 with QVGA display - after loading Notepad++ the toolbar shows very small. My understanding is that if applications have not used DPI scaling then it will not scale properly for higher resolutions. Now these displays are becoming popular it would be worth checking.

**Icon size problems** {#568}

> On a 4K monitor some icons are too small:
> - The X icon on a tab
> - Icons of plug-ins on the toolbar that exist only as small icons are not scaled up
> 
> You should be able to make icons in general larger (ideally in steps of 1 px).

**Icons in tabs don't scale up on high pixel density screens** {#610}

> So I just started using Notepad++ on a 4K screen (on Windows 8). Most elements work great, but the close (cross) icons in the top right of tabs don't scale up. They're so small that they're pretty much unusable on a 4K monitor.

**Font size of UI elements** {#562}

> Notepad++ doesn't go along with an increased font size of Windows 8.1, although it scales correctly. Especially important in the search-and-replace dialog.

**Adjust the individual segments to the (scaled) string size on HiDPI systems** {#539}

> When using a monitor with a higher DPI than the usual 96 DPI and Windows 8.1 scaling set to >100%, Notepad++ typically scales rather well.
> 
> The status bar segments for the line ending type and the encoding are too small, however, and the labels "Dos/Windows" and "UTF8 w/o BOM" are cut off, see the attached screenshot. Other status bar labels may be affected as well, I have only seen it for these two, though.

**Comment by h-h-h-h** [comment] 2015-08-11 13:20
Also the caption bars of dockable dialogs and their UI elements are not scaled up.

**Comment by ccompletion** [comment] 2015-09-21 18:40
Status bar indeed does not scale well. I have many medium-sized source files >10 KiB and on my DPI, nothing after "lines:" is displayed. So I have to use workarounds to learn number of lines instead of just having it displayed.

**Comment by ccompletion** [comment] 2015-09-29 06:37
This is how I've had it for years... it really is time to fix this.
![untitled](https://cloud.githubusercontent.com/assets/14614800/10156851/3565d62a-6685-11e5-91aa-0f04c2be28f7.png)

**Comment by nsgundy** [comment] 2015-10-28 13:36
Tab labels are really tiny (200% scaling set in windows): 
![image](https://cloud.githubusercontent.com/assets/3865838/10790034/537302ee-7d57-11e5-900d-44b734a7850c.png)

**Comment by h-h-h-h** [comment] 2015-10-28 14:02
> @nsgundy:
> Tab labels are really tiny (200% scaling set in windows):

I can agree the font is too small when having the system setting increased, but here, it's not *that* small! That's very strange! Here, it's just as small as, for instance, the text in the find-and-replace dialog.

**Comment by MTphilclothier** [comment] 2016-01-22 20:16
Yeah, same problems for me on 4k Dell XPS15.  Not unusable, but I need to put my good glasses on ;)

**Comment by thezoggy** [comment] 2016-02-18 11:40
first thing I noticed when launching notepad++ on 4k dell xps 13 was that the toolbar icons just arent as crisp as the other ui elements. :(

**Comment by rjbanker** [comment] 2016-03-17 16:40
I can confirm this behavior on a Surface Pro 4 with Windows 10 (4K screen and auto-DPI scaling which is default configuration).  Extending to 1080p external monitors and moving the Notepad++ to said monitors worsens the behavior.

**Comment by BoostHungry** [comment] 2016-04-07 01:48
++1 The font is fine but things like the text in the tab labels and the + icons in the left margin to collapse and expand code sections are minuscule and unreadable on my 4k Lenovo Y50.

**Comment by Koshmaar** [comment] 2016-05-07 02:40
Same thing here - n++ 6.9.1  has way too small UI text on 4k screen. I don't want to change windows scaling, because on win 7 all monitors will have same scaling, so that would make other monitors unusable. Best would be if n++ itself could scale the Ui text.

**Comment by h-h-h-h** [comment] 2016-05-07 21:33
Try it with this setting (Windows 10, translated from German, find your way): "Settings" > "System" > "Extended Display Settings" > "Extended Size Settings for Text and Other Elements". Then change the size for every list item. Check if the items remain changed after applying. This changes just the text, although the taskbar text doesn't want to change.

**Comment by dg9ngf** [comment] 2016-06-05 20:44
The text cursor is also too thin. It's a single device pixel whereas (at 200%) it should be 2 device pixels like in every other application. I can barely see it between the text. Should I open a new issue for this?

**Comment by h-h-h-h** [comment] 2016-06-06 03:01
> The text cursor is also too thin. It's a single device pixel whereas (at 200%) it should be 2 device pixels like in every other application. I can barely see it between the text. Should I open a new issue for this?

Mine is wider than 1 device pixel. I think there's an option for this in Notepad++.

**Comment by dg9ngf** [comment] 2016-06-06 07:29
Great, thanks! I just copied my config over from the PC where 1 is a good value. Now I can even select 3 pixels, which would be 1.5 on a regular monitor. :-) Everybody should have a 200% scaled monitor!

**Comment by aterzi** [comment] 2016-07-06 07:01
![screenshot_1](https://cloud.githubusercontent.com/assets/15159309/16609939/7d1d56f6-4360-11e6-8162-72036d0a50fa.png)
I have laptop with high-resolution display and second monitor with 1920x1200 and I have such kind of bug.

**Comment by JoelRSimpson** [comment] 2016-07-07 23:49
Same issue as aterzi above.  I have a 4k laptop display and 4 external monitors. The 4k display is set to 200% scaling.  All the other monitors are 1920x1200, 2 are set portrait, and all are set to 100% scaling.  The tab font shows big regardless of which monitor the application is displaying on.

**Comment by h-h-h-h** [comment] 2016-07-08 02:59
> I have a 4k laptop display and 4 external monitors.

Then you can go take a walk with your mouse cursor.

**Comment by jorrit** [comment] 2016-08-12 07:06
@aterzi 's issue happens to me when I connect my laptop with a 4k display to a regular monitor via a docking station and not use the laptop screen.

**Comment by h-h-h-h** [comment] 2016-08-12 14:35
It might have to do with *different* DPI scaling factors on different monitors.

**Comment by AdrianHordyk** [comment] 2016-08-26 06:42
any tips on how to deal with the issue that @aterzi describes?
I'm experiencing same problem with Dell XPS 15 with an external monitor. Perfectly usable, but would be great to have this fixed

**Comment by cvcnsprakash** [comment] 2016-11-09 13:45
Any Solution to the above Scenario? Facing the same issue.

**Comment by ksadralodabai** [comment] 2016-11-29 22:59
Any news on the tiny labels listed on the tabs for N++?

**Comment by hmtamim** [comment] 2017-01-06 16:12
You can easily fix this issue by creating a manifest file and putting it in the Program files/Notepad++. Here's a article on it [https://tricklio.com/fix-notepad-plus-plus-scaling-in-high-dpi-displays/](url)

**Comment by ouned** [comment] 2017-01-09 10:38
What about [Per-Monitor DPI scaling](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx#comparison_of_dpi_awareness_levels)?

I recently made some tests and it seems promising. If there is interest I may spend some time doing it.
Is using newer API's like [EnableNonClientDpiScaling](https://msdn.microsoft.com/en-us/library/windows/desktop/mt748621.aspx) allowed? It would be a requirement for it to actually work properly.

**Comment by tomhunter-gh** [comment] 2017-01-11 15:09
Tab labels look good when I run the program locally:

![](http://i.imgur.com/7YXsOUt.png)

But tab label font size is too small when I run on a remote machine via remote desktop connection:

![](http://i.imgur.com/l0l4x4i.png)

I'm on a Surface Book with 175% scaling.

**Comment by hmtamim** [comment] 2017-01-11 15:20
Hi tomhunter-gh,

You can easily fix this. Just go to Notepadd++ > Settings > Performances > Now mark on **Reduce** and finally click Close to save it. Hope it helps :)

If you have scaling problem then check my earlier comments. There's a fix for it.

**Comment by tomhunter-gh** [comment] 2017-01-11 15:47
Hi @hmtamim, thanks for the tip but that doesn't quite fix the tab labels on remote desktop connection I'm afraid.

Reduce on:

![](http://i.imgur.com/Qwk03Bi.png)

Reduce off:

![](http://i.imgur.com/TmBllrI.png)

Still looks a bit different to when I run the program on my local machine.

**Comment by gstavi** [comment] 2017-01-12 11:27
The tab font problem is at least partially due to the use of GetStockObject API in TabBarPlus::init.
Microsoft considers it obsolete.
The recommended approach is (to use Menu font for example):

NONCLIENTMETRICS ncmat;
ncmat.cbSize = sizeof(ncmat);
::SystemParametersInfo(SPI_GETNONCLIENTMETRICS, sizeof(NONCLIENTMETRICS), &ncmat, 0);
_hFont = ::CreateFontIndirect(&ncmat.lfMenuFont);

**Comment by chulai** [comment] 2017-01-19 15:14
It's been a year and a half since this issue was originally reported. Last comment suggests Notepad++ is using a deprecated API and a possible solution. Any plan to resolve this? Any workaround? I'm not sure under what conditions this issue does show up. I also use an external monitor but this happens in both monitors. Sometime it appears sometime it doesn't. Restarting Notepad++ doesn't help, neither does using the 'Reduce' option as explained above.

**Comment by carlos-quintero** [comment] 2017-01-20 12:15
Can you verify if the Windows Updates of January 2017 fix the bug of big font size in Notepad++ tabs with external monitors? Something seems to have fixed the problem for me and another user

**Comment by chulai** [comment] 2017-01-20 14:16
I have a 2-monitor setup (laptop and external monitor) at work where, unfortunately, I can't update Windows due to Group Policies. However, I just got an external monitor for home so I'll try to update Windows and use Notepad++ with a similar setup for a while to see if the issue got resolved by the Windows January updates or not. I will post my findings here. Thanks.

**Comment by M-Jup** [comment] 2017-01-31 08:22
My laptop and docked monitor have different DPI scaling. I need to logout / login to Windows every time after screen change because otherwise Notepad++ is blurry. Very annoying!!

I can also reproduce the tab font size problem. Size of the font is huge and no setting fixes it.

I have the latest Windows 10 from Windows Update.

**Comment by chulai** [comment] 2017-02-02 23:50
@M-Jup the blurry thing is a dpi scaling issue that affects to many Windows application when you have a monitor configuration with at least one being high DPI. It's not the issue reported here.

**Comment by chulai** [comment] 2017-02-02 23:51
So I tested with Windows 10 Anniversary update and latest updates and with 2 different monitor configurations, both with multiple monitors. The issue is still around.

**Comment by M-Jup** [comment] 2017-02-03 08:52
Should I then create a separate issue about the blurry thing? At least Firefox, Chrome and most of the bundled Win10 apps don't have this problem so there should be a way to fix it?

**Comment by h-h-h-h** [comment] 2017-02-04 04:31
@M-Jup:

Might have to do with per-monitor DPI-awareness not being present.

**Comment by M-Jup** [comment] 2017-02-05 08:35
Created #2871 for PM support in Notepad++

**Comment by Fenrirthviti** [comment] 2017-06-06 19:16
Also having this issue on a clean install of Windows 10 and NP++ 64bit. Tab font size is too large. Unchecking "Reduce" for the tab bar settings doesn't do anything but make the icon in the tab bigger. Anyone have any actual solutions to this, or is this something that needs to be patched in the program itself?

**Comment by SnoringFrog** [comment] 2018-02-12 18:16
I've just begun having this issue as well. Unchecking Reduce changes the font size slighty, but does not correct it.

**Comment by MarkCanada** [comment] 2018-03-11 21:56
Just switched a 4K laptop as well.
The text in tabs is quite small - doesn't seem to scale.
The main icons - New, Open ... seem right, but the icons of Plugins are very small either and don't seem to scale either.
The tab icons for document and close seem a bit large and are clipping the tab, but otherwise it seems nice.
![screenshot](https://user-images.githubusercontent.com/5258515/37258911-5b3ebd3a-253c-11e8-96a6-f4e8a13637e0.png)

**Comment by CommanderBond** [comment] 2019-04-09 11:18
Notepad++ shows as DPI Awareness "System Aware" in Process Explorer. That's better than not being able to handle high DPI settings, but when using more than one screen with different scaling factors, everything is messed up again, when it's running on the non-primary screen. Could you please move on to "Per-Monitor Aware"?

**Comment by donho** [comment] 2019-04-09 17:25
I believe this issue has been implemented since long time ago.
Update your Notepad++ to the latest version (v7.6.6).
If the issue persists, please create a new issue for it.
Thank you.

**Closed by donho** 2019-04-09 17:25 UTC
Labels: enhancement

**Comment by ygoe** [comment] 2019-04-09 17:47
Not quite, but almost.

![NPP2x](https://user-images.githubusercontent.com/868315/55822489-0136b180-5b00-11e9-9f35-ec79749c25b7.png)

Some toolbar icons are still tiny at 200% scaling.

NPP is not per-monitor DPI-aware which results in a totally blurry appearance on a secondary monitor with a different scaling. Just tested it on a Surface Pro (200%) with attached monitor (100%).

This is NPP 7.5.9 32-bit on Windows 10.1803.

**Comment by Faq** [comment] 2019-04-09 18:03
@ygoe you didnt check with v7.6.6

**Comment by ygoe** [comment] 2019-04-09 18:16
I've used the update check and it said I have the current version. Is that one broken, too?

**Comment by sasumner** [comment] 2019-04-09 18:19
There is no automated update path from 7.5.x to 7.6.x due to the plugins architecture change.  Try again in 7.6.6 because that's what you were asked to do, but your display issue will be the same.

**Comment by ygoe** [comment] 2019-04-09 18:20
Same issue with NPP 7.6.6. It only disabled my Customize Toolbar plugin which I had to install again from the plugin list. This seems to add the tiny icons. Now there are even 4 more icons at the end. I didn't order those.

**Comment by Fenrirthviti** [comment] 2019-04-09 22:06
I can also confirm this is not fixed in 7.6.6:

![bug](https://pub.rachni.com/img/2019-04-09_17-06-00.png)

**Comment by MarkCanada** [comment] 2019-04-10 05:15
If you have lots of plugins then stay away from 7.6 until the plugins issues are fixed/stabilized.
I just made the mistake of just updating manually and lost all the plugins I had installed.
The dlls were still in the folder but nothing was loading.
Most of them I found in the new plugin manager since I could guess the plugin names from the file names but I still can't get "TakeNotes" to work. And I used that a lot.
There's some others missing but they are not as bad for me as this one.
So only update if you have a lot of time re-installing all your plugins - and make a list beforehand.
Worst Notepadd++ "update" ever. (Actually by reading 7.6.0 was worse)

**Comment by CommanderBond** [comment] 2019-04-10 05:16
Sorry, I forgot to mention that i am using 7.6.6, since I am always using latest versions.

**Comment by MarkCanada** [comment] 2019-04-10 05:17
Oh and as for toolbar icons - it seems that many plugin developers don't include hi-res toolbar buttons and that's why they are tiny. 
Maybe the base code could just stretch toolbar buttons that are too small?

**Comment by ygoe** [comment] 2019-04-10 06:59
Why should any plugin contain high resolution icons when the core doesn't even have them? Scaling would be expected here. And by the host, not the plugin.

**Comment by ygoe** [comment] 2019-04-10 07:15
> Not broken: there is no automated update path from 7.5.x to 7.6.x due to the plugins architecture change. 

Yes, broken. On my main PC I have 7.6.4 installed and yet the update check says there is no update available. So to be more precise: There is not auto-update path to 7.6 from anywhere. Does this mean it's a pre-release version? Wouldn't it need to be declared as such in the version id?

**Comment by sasumner** [comment] 2019-04-10 12:04
(Still) not broken.  There is a time delay after a release in this feature before it is a true update path.  I presume so that if critical bugs are found not a large amount of users will update to a critically bad version.  So it is only a "pre-release" if such bugs are found. :)  Recently there was an effort made to go to a "release candidate" scheme.  Time will tell how well that works out.  But the RC thing isn't tied into update notifications at all (I just mention it as an aside).

**Comment by MarkCanada** [comment] 2019-04-11 21:56
@ygoe
Well - I guess the built-in buttons are not high res (some do look quite blocky), but at least they are bigger than most plugin buttons.
Here is the toolbar I have. The big ones are mostly from the core and the smaller ones to the right plugins buttons. So other than the spell check everything is tiny.
![toolbar](https://user-images.githubusercontent.com/5258515/55995498-7f629780-5c69-11e9-8128-4942a9d9fe67.png)

**Comment by satovey** [comment] 2019-05-27 20:25
The font size in the TAB bar TABS is controlled by the following WidgetStyle lines in the stylers.xml.

If you decide to edit your stylers.xml file to see if it will affect your Notepad++ tab bars, be sure to make a backup copy in case you mess up the xml and need to return to the original code file.
Just be sure that there is a space between the last parameter and /> otherwise you may find that something else broke and Notepad++ is not listening to your instructions.

Just to be clear; I did not find the following modifications to have an affect on the text size of the TAB BAR.

The 4 lines to edit are as follows:

        <WidgetStyle name="Active tab focused indicator" styleID="0" fgColor="FAAA3C" />
        <WidgetStyle name="Active tab unfocused indicator" styleID="0" fgColor="FFCAB0" />
        <WidgetStyle name="Active tab text" styleID="0" fgColor="000000" />
        <WidgetStyle name="Inactive tabs" styleID="0" fgColor="000000" bgColor="C0C0C0" />

As you can see, there is no fontsize = "" parameter and that needs to be added as follows.

To make the change, add fontsize= to each of the lines as follows. 

        <WidgetStyle name="Active tab focused indicator" styleID="0" fgColor="FAAA3C" fontSize="14" />
        <WidgetStyle name="Active tab unfocused indicator" styleID="0" fgColor="FFCAB0" fontSize="14" />
        <WidgetStyle name="Active tab text" styleID="0" fgColor="000000" fontSize="14" />
        <WidgetStyle name="Inactive tabs" styleID="0" fgColor="000000" bgColor="C0C0C0" fontSize="14" />

Just another disclaimer; 
I found that making the changes in this post had no affect on the size of the texts displayed in the Notepad++ TAB Bar.

Quite honestly, I would like the text size of the entire GUI to be adjustable as the higher the resolution of a monitor, the smaller every thing becomes and Operating systems, including open source OSes such as Linux, do an extremely poor job of dealing with that problem. The end result is that as the quality of one's eyesight degrades, the more difficult it is for one to see what's on the monitor and to easily utilize one's computer. 

What's worse, the harder it is for one to see what's on the monitor,  the more one's eyes strain, and the more one's eyes strain, the more one's eyesight degrades.

As far as the magnifier tool that Microsoft put in Windows is concerned, that tool is a complete joke as it totally messes up the layout of the desktop every time it is started. After it is shut off, you have to go through and rearrange the desktop because it won't do that for you.

**Comment by satovey** [comment] 2019-05-27 20:30
The font size in the TAB bar TABS is controlled by the following WidgetStyle lines in the stylers.xml.

If you decide to edit your stylers.xml file to see if it will affect your Notepad++ tab bars, be sure to make a backup copy in case you mess up the xml and need to return to the original code file.
Just be sure that there is a space between the last parameter and /> otherwise you may find that something else broke and Notepad++ is not listening to your instructions.

Just to be clear; I did not find the following modifications to have an affect on the text size of the TAB BAR.

The 4 lines to edit are as follows:

        <WidgetStyle name="Active tab focused indicator" styleID="0" fgColor="FAAA3C" />
        <WidgetStyle name="Active tab unfocused indicator" styleID="0" fgColor="FFCAB0" />
        <WidgetStyle name="Active tab text" styleID="0" fgColor="000000" />
        <WidgetStyle name="Inactive tabs" styleID="0" fgColor="000000" bgColor="C0C0C0" />

As you can see, there is no fontsize = "" parameter and that needs to be added as follows.

To make the change, add fontsize= to each of the lines as follows. 

        <WidgetStyle name="Active tab focused indicator" styleID="0" fgColor="FAAA3C" fontSize="14" />
        <WidgetStyle name="Active tab unfocused indicator" styleID="0" fgColor="FFCAB0" fontSize="14" />
        <WidgetStyle name="Active tab text" styleID="0" fgColor="000000" fontSize="14" />
        <WidgetStyle name="Inactive tabs" styleID="0" fgColor="000000" bgColor="C0C0C0" fontSize="14" />

Just another disclaimer; 
I found that making the changes in this post had no affect on the size of the texts displayed in the Notepad++ TAB Bar.

Quite honestly, I would like the text size of the entire GUI to be adjustable as the higher the resolution of a monitor, the smaller every thing becomes and Operating systems, including open source OSes such as Linux, do an extremely poor job of dealing with that problem. The end result is that as the quality of one's eyesight degrades, the more difficult it is for one to see what's on the monitor and to easily utilize one's computer.  What's worse, the harder it is for one to see what's on the monitor,  the more one's eyes strain, and the more one's eyes strain, the more one's eyesight degrades.

Can you imagine the pain one goes through that suffers migraines when they are under stress such as squinting at the computer monitor? This is not just a usability issue, it is also a health issue and needs to be addressed.

**Comment by JamesIV4** [comment] 2019-08-15 19:56
Just chiming in to say I'm experiencing this issue on my multi-monitor setup on NP++ 7.7.1. Most of the interface is blurry when I pull the window over to my laptop's high res 1440p screen.

Including screenshot for example:
![blurry_np++](https://user-images.githubusercontent.com/10490279/63122620-31da9c00-bf75-11e9-88f0-639a006bae9e.png)

**Comment by davidc86** [comment] 2022-09-09 02:03
I have a Lenovo Yoga C940 with a 4K screen (set to 200%) and an 1080p external monitor (set to 100%).

The latest version of Notepad++ (v8.4.4) gives unreadable filenames in the tabs: 

![image](https://user-images.githubusercontent.com/65363206/189256418-34ec6c93-41bd-4694-b813-dd9910d13365.png)

If I drag it on to the external monitor, it is not much better. 

Also, the "document peak" feature is nearly unusable as the text is so small.

This is Sept 2022. Has this issue from 2015 not yet been solved? Or is this a regression issue?

**Comment by alankilborn** [comment] 2022-09-09 11:41
@davidc86 

>gives unreadable filenames in the tabs

For your specific problem, suggest **UNTICKING** _Reduce_ :

![image](https://user-images.githubusercontent.com/77065706/189341892-9fe75c89-890e-412a-82b2-d80baa242115.png)

**Comment by davidc86** [comment] 2022-09-09 16:01
Thanks for this suggestion.
Interesting though it has the OPPOSITE effect.
Here are two screen shots: 
![image](https://user-images.githubusercontent.com/65363206/189392567-6c7222af-12a2-43d7-bcb3-946b72ee7d5a.png)

![image](https://user-images.githubusercontent.com/65363206/189392693-bdf7f8f5-1174-45b8-91bc-15f491e6d4d8.png)

NOTE that the one WITHOUT the "Reduce" checked actually has SMALLER text in the tabs than the one with the Reduce option checked!

Any other clues?

**Comment by alankilborn** [comment] 2022-09-09 16:09
>the one WITHOUT the "Reduce" checked actually has SMALLER text in the tabs than the one with the Reduce option checked!

Wow, that's interesting.

**Comment by thezoggy** [comment] 2022-09-09 20:52
> Thanks for this suggestion. Interesting though it has the OPPOSITE effect. Here are two screen shots: ![image](https://user-images.githubusercontent.com/65363206/189392567-6c7222af-12a2-43d7-bcb3-946b72ee7d5a.png)
> 
> ![image](https://user-images.githubusercontent.com/65363206/189392693-bdf7f8f5-1174-45b8-91bc-15f491e6d4d8.png)
> 
> NOTE that the one WITHOUT the "Reduce" checked actually has SMALLER text in the tabs than the one with the Reduce option checked!
> 
> Any other clues?

whats your scaling and layout in windows set to?  and are you logging in to a remote machine using remote desktop or something (where the source has 4k but the dest doesnt)

**Comment by davidc86** [comment] 2022-09-10 02:22
The Windows 11 display setting is this:

![image](https://user-images.githubusercontent.com/65363206/189464799-d3d68d41-f235-4116-9c6d-7b78fd311a74.png)

The screen resolution is 3840x2160 (4K) but I've scaled it to 200% so the letters are crisp but readable. Screen Font size is set to 100%.
I also have an external 1080p monitor. 
The screen shots are from the laptop's 4K screen. Moving the Notepad++ window to the external monitor does not change the look any.
