### ISSUE TITLE
[Bug] Pasting text past end of window does not autoscroll down

### ISSUE THREAD

**Issue by dmoreno78** [notepad-plus-plus/notepad-plus-plus#6144] opened 2019-09-13 18:59 UTC
### Description of the Issue
When pasting text past the end of the bottom of the window, Notepad++ does not autoscroll down to the end of it and therefore you have to manually press the down arrow key or page down.  This occurs when pasting a paragraph of a few sentences exceeding 350 characters total, for example.

### Steps to Reproduce the Issue

1. Copy a paragraph containing 300+ characters with no line breaks.
2. Place cursor at the very end of the document, at the bottom of the window.
3. Paste.

### Expected Behavior
The editor should autoscroll the window to the end of the newly-pasted content.

### Actual Behavior
The editor pastes the new content but it overflows offscreen with no autoscrolling (including the cursor) which is awkward.

### Debug Information
Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll 

Thanks!

**Comment by sasumner** [comment] 2019-09-17 14:05
Can't reproduce on same version.  Closing for now; reopen possible with further substantiation.

**Closed by sasumner** 2019-09-17 14:05 UTC
