### ISSUE TITLE
Saved session behavior causes confusion regarding current file contents

### ISSUE THREAD

**Issue by JohnCalin** [notepad-plus-plus/notepad-plus-plus#3667] opened 2017-08-28 20:10 UTC
### Description of the Issue

When 'Remember current session for next launch' is enabled, the user is not prompted to save changes when closing npp.  The changes are loaded from the saved session the next time the file is opened in npp.  This caused quite a bit of confusion as I was helping a user with a configuration problem in a text file that had been edited with npp.  It seemed as though the config was wrong, but when the user pulled up the file in npp I could see that it was correct.  Eventually by happenstance we had the file open in another tool, which showed the actual file contents (which were, of course, incorrect).  On investigating, we saw that npp did show an enabled Save icon, allowing us to save the changes.
Certainly this could be filed as a user training issue and closed.  I believe that the standard user expectation is that 1) when you close an application in which you have modified a file, you are prompted to save your changes, and 2) when you open a file you are shown the current contents of that file.

An appropriate remedy could include two new dialogs:
First, when closing npp with modified files (and remember session enabled), show a dialog allowing the user to Save, Discard, or Remember changes.
Second, when opening a file that has Remembered changes, show a dialog allowing the user to keep existing changes, or reload from disk.

The second of these is more important.  If only the first were implemented, a user may still be confused when opening a file and seeing Remembered changes, possibly LONG after the changes were made.
If only the second is implemented, a user may forget to save changes... but on re-opening the file to see what went wrong they would immediately be notified about what was going on.

**Comment by MetaChuh** [comment] 2019-04-11 23:53
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)


###################################
2019.04.10:

we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:53 UTC
