### ISSUE TITLE
No mnemonics anymore in "yes no cancel yes-to-all no-to-all" message since NPP version 7.8.1

### ISSUE THREAD

**Issue by geertsj** [notepad-plus-plus/notepad-plus-plus#7529] opened 2019-11-08 12:09 UTC
### Description
No mnemonics anymore in "yes no cancel yes-to-all no-to-all" message since NPP version 7.8.1

### Steps to Reproduce the Issue

1. Open more than 1 file, change 1 or more files (do not save them)
2. Close one of these files
3. Message "Save file '<file>'" appears with 5 buttons: "yes no cancel yes-to-all no-to-all" since NPP version 7.8.1 (before that version 2 buttons appears).

### Expected Behavior
If I do not want to save this file I choose button 'No', formerly I could immediately choose N and it's close the file. For all then 5 buttons I do excpect 5 shortcuts: 'Y' for 'Yes', 'N' for 'No', 'C' for 'Cancel', 'e' for 'Yes to all' and 'o' for 'No to all'.

### Actual Behavior
I choose N: it does not close the file anymore

### Debug Information
I dont havent

See screenshot
![error](https://user-images.githubusercontent.com/46344013/68475424-fe2fab00-021f-11ea-8d9d-0f01437de896.jpg)

**Comment by sasumner** [comment] 2019-11-08 13:23
Duplicate of #6223.  Please search for your issue to be already existing before creating a new issue.  Also, the comment chain of #6223 shows you how you can restore keyboard functionality to this.

CLOSED AS A DUPLICATE.

**Closed by sasumner** 2019-11-08 13:23 UTC
