### ISSUE TITLE
Usability Improvement via "Express Update" 

### ISSUE THREAD

**Issue by colin-kiegel** [notepad-plus-plus/notepad-plus-plus#1624] opened 2016-03-12 16:08 UTC
Current Situation:
- If Notepad++ offers to install an update, it takes **a lot of confirmations** to go through the process.

Proposal:
- It would be nice to have an additional Button "**Express Update**" at the very beginning.
- The express update should minimize user interaction _as much as possible_ - ideally to just one click. The express update should silently keep all the installation choices from the previous run of the installer.
- If the installer options changed in an incompatible manner, the "Express Update" could be disabled to force the user making new choices.

**Comment by FlorinAndrei** [comment] 2016-06-30 17:27
Issue #1916 has been marked as a duplicate of this one, but that's incorrect. This issue talks about a one-click update. #1916 talks about a zero-click update, completely transparent to the user (like Google Chrome).

**Comment by MetaChuh** [comment] 2019-05-17 21:31
we want users to be aware of all installer options when updating.
it's only six clicks to skip them, so it does not consume a relevant amount of time.

many thanks and best regards.

**Closed by MetaChuh** 2019-05-17 21:31 UTC
Labels: enhancement, installer, reject

**Comment by FlorinAndrei** [comment] 2019-08-23 00:17
@MetaChuh This is a text editor, not a rocket launch system. If Chrome can do updates transparently, in the background, with absolutely no user interaction, why can't this app do the same?

The update notifications are the single most annoying thing about this app. I fire it up to quickly jot down some notes, and BANG! the first thing that pops up is an update notification. Are you serious?

Put that stuff in the background, it's super-distracting.

**Comment by dail8859** [comment] 2019-08-23 01:45
@FlorianAndrei We look forward to your future pull request implementing background updates.

**Comment by colin-kiegel** [comment] 2019-08-23 05:54
Would you accept a Pull Request?

Not that I could do it myself, but maybe someone else. MetaChuhs response sounded differently.

Each screen and click that can be saved on updates would be a huge improvement. Note that I am not someone who usually clicks on 'express update', yet I am suggesting it here. But there is a difference in timing. I do most updates, when I am idle, but I usually update notepad++ when I really want to focus on something.

Another big improvement would be to add a button 'ask me again, when I close notepad++' (something like that). When I close it I am usually much more in an idle state, ready to make six clicks and scan the Dialogs for new information. :-)

**Comment by colin-kiegel** [comment] 2019-08-23 05:55
Just trying to find a good compromise that's less distracting and easy to implement

**Comment by FlorinAndrei** [comment] 2019-08-23 07:23
@dail8859 The point to take home is that you're annoying your users with your poorly timed, intrusive update pop-up.

**Comment by colin-kiegel** [comment] 2020-01-24 14:37
The GIT Updater has a checkbox [X] only show new options (checked by default)

This is a good compromise IMO. :-)

![2020-01-24 15_34_40-Git 2 25 0 Setup](https://user-images.githubusercontent.com/7691186/73076881-4ffedd80-3ebf-11ea-9699-a642e1d1c6ca.png)
