### ISSUE TITLE
Getting double Javascript entries in Language menu

### ISSUE THREAD

**Issue by ZappyScript** [notepad-plus-plus/notepad-plus-plus#3712] opened 2017-09-07 13:01 UTC
I've been editing my settings just recently and I noticed there's 2 "Javascript" under Language, with none of them defining the difference between themselves. However, there's only 1 javascript listed under Language on the toolbar.

http://i.imgur.com/W0ZwRwX.png

### Steps to Reproduce the Issue
1. Settings ->preferences -> Language

I think the issue is to do with this file: 
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/854acae4a1f149624aba0d4637f9fa50c3d49a1e/PowerEditor/src/stylers.model.xml

Line 580 & 593.

I tried to google the issue and find what the spare Javascript language is for but there is no result.

**Comment by ArkadiuszMichalski** [comment] 2022-01-14 11:26
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4521.

**Closed by ArkadiuszMichalski** 2022-01-14 11:26 UTC
