### ISSUE TITLE
Hidden Files/Folders, explorer settings not honored.

### ISSUE THREAD

**Issue by cchar** [notepad-plus-plus/notepad-plus-plus#1250] opened 2015-12-14 19:49 UTC
My config:
Win10, Notepad++ 6.7.9.2

I discovered this when trying to open/edit my hosts file on Win10. The 'etc' file wasn't showing up in c:\windows\system32\drivers\etc.

It seems to be something like either that it's set as hidden (which it doesn't appear to be) or because it's flagged as a "operating system folder". In either case, when I click open file from Notepad++, and navigate to c:\windows\system32\drivers, the 'etc' folder doesn't even show.

I tried from Windows built-in notepad, and it shows the folder.

I do have my explorer settings set to "show hidden files/folders" and also "show operating system files/folders", so I would think that these settings would govern whether those were hidden or not.

So, just a note to verify that Notepad++ properly shows hidden/OS files and folders.

**Comment by YueLinHo** [comment] 2016-02-22 09:35
Suppose this issue is a duplicate one, see #1168.

**Comment by MetaChuh** [comment] 2019-04-11 00:34
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:34 UTC
