### ISSUE TITLE
Replace in files crashes with many files

### ISSUE THREAD

**Issue by espirit** [notepad-plus-plus/notepad-plus-plus#10518] opened 2021-09-07 13:42 UTC
### Remark
I am very happy with Notepad++ and admire your work. I hope you can reproduce this issue, and it would be great if it can be fixed. Thanks.

### Description of the Issue
Using replace in Files on a directory with some 12 sub directories with a total of 73 files, the replace action crashes Notepad++.

### Steps to Reproduce the Issue
1.  Select Find-In-Files
2.  Set the what and replace string and directory
3.  Set *Regular expression*

### Actual Behavior
Does a part of the replaces, then crashes.

### Debug Information
Notepad++ v8.1.3   (64-bit)
Build time : Aug 10 2021 - 00:29:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : CodeAlignmentNpp.dll CSScriptNpp.dll HTMLTag.dll ImgTag.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextViz.dll PreviewHTML.dll XMLTools.dll

**Comment by xomx** [comment] 2021-09-08 10:53
Cannot reproduce (8.1.4 x64 fresh portable, set with 201 files in 12 subdirs).

Try to append an exact test case (zip your fileset with subfolders structure).

Also the exact searching phrase could help to identify the culprit.

**Comment by dail8859** [comment] 2021-09-20 11:53
Closing for now. Please reopen with more details if the issue persists.

**Closed by dail8859** 2021-09-20 11:53 UTC
Labels: not reproducible
