### ISSUE TITLE
Open NP++ with File argument and Line # - Cursor is at line # but outside of display area.

### ISSUE THREAD

**Issue by krptodr** [notepad-plus-plus/notepad-plus-plus#7909] opened 2020-01-31 19:25 UTC
### Description of the Issue

Opening NP++ from command line, while passing in file number and line number, will no longer scroll the editor to the line number, but moves the cursor to that line.

### Steps to Reproduce the Issue - on windows 10

Have a text file with a length long enough to cause the user to scroll down the file when viewing it.

1. open command prompt
2. execute: F:\Program Files (x86)\Notepad++\notepad++.exe [file] [line number towards end of file]
3. OBSERVE: do not used mouse, but use your keyboard arrow keys to move the cursor from it's current position. This will cause the editor to move to the cursor.

Running NP++ v7.8.3 32-bit with Build time: Jan 12 2020 - 19:05:42

**Comment by sasumner** [comment] 2020-02-02 00:19
Closing as not reproducible (see below).  If further instructions can be provided, will consider reopening.

-----------------------

Works fine for me with same version; specified line number is in the view and caret right there and blinking:

Notepad++ v7.8.3   (32-bit)
Build time : Jan 12 2020 - 19:05:42
Path : C:\..........\npp.7.8.3.bin\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1709
OS Build : 16299.1565
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Closed by sasumner** 2020-02-02 00:19 UTC

**Comment by roelschroeven** [comment] 2020-03-04 08:47
I have the same issue, but using 7.8.4. Sometimes it works as it should, but most of the time not. 

(https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8007 is a duplicate of this)
