### ISSUE TITLE
Find Prev (Shift-F3) enabled in menu but not working when using regex

### ISSUE THREAD

**Issue by dttrian** [notepad-plus-plus/notepad-plus-plus#8515] opened 2020-07-03 11:20 UTC
### Description of the Issue
(I'm sorry if the command/menu item names are wrong, but I'm using the italian localization and I do not exactly know the name of the menus and command in the english localization)

Since 7.8.7, when searching with regular expressions, trying to "Find Prev" (Shift-F3) does nothing, even if the related menu item under Search menu is enabled.

I now know about the changes in 7.8.7 about backward search with regular expressions, but it took me a while to guess why I wasn't able anymore to search backward even if the menu item was enabled.

I'm not about to solve my problem simply setting regexBackward4PowerUser to "yes", but I'm convinced that either Shift-F3 should work or the menu item should be disabled.

### Steps to Reproduce the Issue
1.  Find something using a regular expression
2.  Press Shift-F3 to search backwards or click the Search / Find Prev menu item
3.  Nothing happens

### Expected Behavior
I expect the Shift-F3 to work or the menu item to be disabled.

### Actual Behavior
Nothing happens

### Debug Information
Notepad++ v7.8.7   (32-bit)
Build time : Jun  5 2020 - 02:34:28
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.900
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll

**Comment by malix0** [comment] 2020-12-28 10:23
I can conform this bug exists and that this is a regression, because it worked before, but I don't remember up to which version it worked. Now I have the 7.9.1 (64-bit) and still doesn't work.

**Comment by maliger** [comment] 2021-03-12 12:13
+1.
Also would be nice if F3 and Shift+F3 works even inside Find Window (as well as Enter and Shift+Enter).
I'm on 7.9.2 (64bit).

**Comment by sasumner** [comment] 2021-03-12 12:41
>I'm not about to solve my problem simply setting regexBackward4PowerUser to "yes"

OK.

>but I'm convinced that either Shift-F3 should work or the menu item should be disabled.

It's (the menu item) a minor thing, so it's ok for now; will become a non-issue with an upcoming change to regex searching.  (So I'm closing this)

>Also would be nice if F3 and Shift+F3 works even inside Find Window

F3 and Shift+F3 are not hardcoded and are changeable by the user.
Thus I would predict you'd never have the flexibility of these types of functions from the Find window.
But never say never.  :-)

**Closed by sasumner** 2021-03-12 12:41 UTC
