### ISSUE TITLE
Save As - Navigating to a Folder

### ISSUE THREAD

**Issue by thecliguy** [notepad-plus-plus/notepad-plus-plus#4522] opened 2018-05-24 23:12 UTC
### Environment details
  * Windows 10 Professional, Verion 1709, OS Build: 16299.431
  * Notepad++ v7.5.6 (32-bit).

### Description of the Issue
Entering a folder path into the `File name:` field of the Save As dialogue produces
a message box advising that `<FOLDER NAME> already exists. Do you want to replace it?`

This is not standard behaviour for a Windows application, the expectation is that
entering a path into a Save As dialogue will simply place you into that path. 

I was previously using Notepad++ V7.3.3 (32-bit) which did not exhibited this problem.

### Steps to Reproduce the Issue

  * Open Notepad++ 
  * Navigate to `File` > `Save As`.
  * Enter a folder path into the `File name:` field, EG: `C:\Windows`.
  * A message box will appear as follows:
    ![image](https://user-images.githubusercontent.com/23440389/40517788-0d5e9420-5faf-11e8-9b0a-7a4641616f95.png)

### Debug Information
Notepad++ v7.5.6   (32-bit)
Build time : Mar 19 2018 - 00:26:59
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll XMLTools.dll 

### Misc
I see that issue #4449 refers to a problem with entering folder paths into the Save As dialogue. The issue is not quite the same as mine, as it states that Notepad++ produces a file named after that of the path entered, I do not experience that behaviour.

**Comment by sasumner** [comment] 2018-05-25 11:43
Preferences -> Default Directory -> Use new style dialog...
If you tick that option, your problem seems to go away when I test it.

Not sure who likes the "old style" dialog but I guess backward compatibility in user-interface changes is a concept that never dies (unless you are Microsoft).

Anyway, it appears that a recent change (being able to use "/" where you would normally have to use "\\" in pathnames isn't compatible with the "new style" save dialog...I am stunned.

**Comment by thecliguy** [comment] 2018-05-27 00:48
@sasumner Thank you for the information and the workaround.

To be sure which version of Notepad++ first introduced this regression, I have tested 7.5.6, 7.5.5 and 7.5.4. My testing reveals that the regression was introduced in 7.5.5. The problem is **not** present in 7.5.4.

As you mentioned, a change was made to support Unix style paths and this appears to have inadvertently broken navigation to folders using Windows style paths.

[Make Unix style path (slashes) work in open file dialog (optional)](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/556901b83b1d71e47c861413ab7577693fdf5c9a)

Perhaps @ihnorton can verify this?

So to summarise the current situation...

```
+---------------------------------------+------------------------------------+------------------------------------+
|                                       | "Old Style" Open/Save Dialog Box   | "New Style" Open/Save Dialog Box   |
+---------------------------------------+------------------------------------+------------------------------------+
| Navigating to a folder path using     | Produces a message box:            |         Works as expected          |
| backslashes "\" (Windows convention)  | "<FOLDER NAME> already exists. Do  |                                    |
|                                       | you want to replace it?"           |                                    |
+---------------------------------------+------------------------------------+------------------------------------+
| Navigating to a folder path using     |            Implemented             |          Not implemented           |
| forward slashes "/" (Unix convention) |                                    |                                    |
+---------------------------------------+------------------------------------+------------------------------------+
```

At a minimum, the ability to navigate to folders using Windows style paths should be reinstated into the "old style" dialogue.

Ideally, the "old style" and "new style" dialogs would support both Windows and Unix style paths. @ihnorton Is there any technical reason why Unix style path support was only implemented in the "old style" dialog and not the "new style" dialog so the functionality is consistent?

**Comment by Cooeeee** [comment] 2019-01-16 06:51
I'm a software developer and use the "Save a copy as" feature multiple times a day. I update my repository version of the file and then use "Save a copy as" feature to export the change into my project as well.

I think this bug affects that feature since the point of the "Save a copy as" feature is to redirect the file into another location. Ideally I want to be taken to the folder name entered and retain the original file name. Cheers.

**Comment by sasumner** [comment] 2019-01-16 13:01
@Cooeeee said:

>I think this bug

Is it a bug, or a feature (aka just the way it works)?

**Comment by mere-human** [comment] 2021-02-22 21:28
In version 7.9.3 file dialogs have been updated so this problem isn't reproducible anymore.
@sasumner Could you, please, close this issue?

**Closed** 2021-02-22 21:57 UTC
