### ISSUE TITLE
publish Notepad++ to Microsoft Store with windows 11

### ISSUE THREAD

**Issue by sheikalthaf** [notepad-plus-plus/notepad-plus-plus#10532] opened 2021-09-09 14:39 UTC
Now it is possible to publish any type of application to microsoft store with their [new store policies](https://aka.ms/newstore). It will be great to see notepad++ in windows 11 store for easy installation.

Thanks in advance

**Comment by ArkadiuszMichalski** [comment] 2021-09-09 14:53
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9221. Read last comment https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9221#issuecomment-908273992.

**Closed by ArkadiuszMichalski** 2021-09-09 14:53 UTC
