### ISSUE TITLE
[BUG] The stringReplace function will miss the BUG of replacing adjacent strings

### ISSUE THREAD

**Issue by softmgr** [notepad-plus-plus/notepad-plus-plus#15804] opened 2024-11-15 13:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

For example:
```cpp
wstring str = L"abc          abc          abc          ";
str = stringReplace(str, L"  ", L" ");
```

Before the code fixes:
```cpp
str = L"abc     abc     abc     ";
```

After the code fixed:
```cpp
str = L"abc abc abc ";
```

code:

```cpp
wstring stringReplace(wstring subject, const wstring& search, const wstring& replace)
{
	size_t pos = 0;
	while ((pos = subject.find(search, pos)) != std::string::npos)
	{
		subject.replace(pos, search.length(), replace);
		pos += replace.length();

		// If the replace string is shorter than the search string,
		// move pos back by one character to handle consecutive matches
		if (pos > 0 && replace.length() < search.length()) {
			pos--; // Step back to ensure overlapping matches are caught
		}
	}
	return subject;
}
```

### Steps To Reproduce

none

### Current Behavior

Before the code fixes:
`str = L"abc     abc     abc     ";`

### Expected Behavior

After the code fix:
`str = L"abc abc abc ";`

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.7\npp.8.7.portable.x64\notepad++.exe
Command Line : -titleAdd="8.7 64-bit" -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4317
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    PythonScript (3.0.16)
```

**Comment by pawelzwronek** [comment] 2024-11-16 19:43
For me it seems to work as expected. In your case it replace all double spaces with single space. So 10 spaces is replaced with 5 spaces. You are expecting extra job, which might be unexpected for most users. Check for example Python ` 'aa      '.replace('  ', ' ')` => `'aa  '`. The same behaviour you can see in JS. If you  agree, please close this issue.

**Comment by softmgr** [comment] 2024-11-17 02:43
> For me it seems to work as expected. In your case it replace all double spaces with single space. So 10 spaces is replaced with 5 spaces. You are expecting extra job, which might be unexpected for most users. Check for example Python ` 'aa '.replace(' ', ' ')` => `'aa '`. The same behaviour you can see in JS. If you agree, please close this issue.

Indeed, in related functions of other languages, the implementation of the `replace` string function often misses replacing adjacent substrings. To achieve `replace all`, you need to use:
```
﻿
	while (str.find(L"  ") != std::wstring::npos) {
		str = stringReplace(str, L"  ", L" ");
	}
﻿
```
﻿
However, it seems that in all instances where `stringReplace` is called in this project, its purpose is always to `replaceAll`. If we don’t want to modify the implementation of this function, I personally think that all the relevant code should be changed to use the above `while` loop instead.

**Comment by alankilborn** [comment] 2024-11-17 13:01
@softmgr Can you provide (N++ user level) Steps To Reproduce a situation where this "bug" appears?

**Comment by softmgr** [comment] 2024-11-17 13:57
> @softmgr Can you provide (N++ user level) Steps To Reproduce a situation where this "bug" appears?

Not at the moment. It only occurs in some extreme cases.

**Comment by alankilborn** [comment] 2024-11-17 14:00
In case of no demonstrable defect, suggest closure of this issue.

**Comment by pawelzwronek** [comment] 2024-11-17 15:26
@softmgr `stringReplace` is internal function of N++ and it's working as intended. Changing it's behaviour can lead to unexpected effects. To get the behaviour you are suggesting we can add a flag, say `bool adjacent` or create new function say `stringReplaceAdjacent`. But if there is no need right now for such feature, I suggest to leave it as it is. As @alankilborn said, if you can provide an example of such bug then we can think further.

**Comment by pawelzwronek** [comment] 2024-11-17 22:20
I agree. Where is the bug? Or am I missing some reference to the "BUG of replacing adjacent strings" from another issue. This function works as every Python, Js programmer would expect, or other languages have other implementations?

**Comment by alankilborn** [comment] 2024-11-17 23:07
Windows' `notepad.exe` replaces this way as well.

**Comment by softmgr** [comment] 2024-11-18 05:04
> @pawelzwronek @alankilborn The project might have some policies not friendly toward to the contributors, such as "fix typo" or "refactoring code" that has no benefit to the project. These unfriendly policies are there to prevent the "fake" contributors who do their code "contribution" for adding their name into the repository (trust me, they are many). Merging a PR takes more time than I do the commit directly so I don't want these "contributors". Also people fixing typos or doing some so called refactoring don't deserve to leave their name/email in the repo.
> 
> I don't think @softmgr is one of them and his [suggestion](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14839) was ignored/rejected by me, but the time proves he was right about it.
> 
> For these reasons, I think it's worth to check the issues opened by @softmgr even the issues may be rejected. Hope I express clearly my arguments :)

Thank you for your affirmation of me.



@pawelzwronek @alankilborn 
I have, of course, tested other editors, such as Windows Notepad, UltraEdit, Notepad3, Notepad4, and so on. Their `Replace All` functionality often misses adjacent strings.
In fact, over the years, people have gotten used to clicking the `Replace All` button multiple times until the interface shows `0 occurrences were replaced`, which then truly indicates that all replacements have been made.
However, when it comes to `Find in Files`, is there really a `Replace All`? Do you have to press `Replace in Files` multiple times? Otherwise, if you only execute `Replace All` once, there’s no certainty that everything has indeed been replaced.
﻿

**Comment by pawelzwronek** [comment] 2024-11-18 11:31
@softmgr Thx for giving more context, now I get it. You want to enhance gui function in the Replace window. At first I thought, you want only to refactor the code of N++. After rethinking the idea, I come to the same conclusion, that you are proposing to make an extra job  where it might be unexpected and even unwanted. For example, when I would like to change all 4 spaces intentions to 2 spaces, then using new implementation of replaceString, I would end with every line to start with 2 spaces only and whole document intends would be ruined. I understand that in some or even most cases this implementation might cover with the intension of the user, but as you can see the are some real world usecases where it would not, and hard to achieved another way. I think that we need to follow the rule "most of the time". What's the expected behaviour for a common user and redesing the functionality acording, but also leaving an option to use former implementation. For your proposal, one of the idea would be for example holding Alt or a checkbox that replace all adjacents occurrences. Or make Replace All works this way by default and the Alt or the checkbox would restore original(no adjacent) implementation.

**Comment by alankilborn** [comment] 2024-11-18 11:39
>You want to enhance gui function in the Replace window.

If that's truly what is meant, why didn't the opening comment in the issue discuss it from that perspective?
In a few cases, opening an issue with a specific point about source code is fine, but the vast majority should be opened following the issue template, which is geared toward what the user experiences when they use the software.

**Comment by pawelzwronek** [comment] 2024-11-18 13:17
@alankilborn yeah. We could benefit from adding more templates when opening new issue, like:

- Bug - GUI/frontend
- Bug - code/backend
- Bug - translation/localization
- Bug - others

**Comment by softmgr** [comment] 2024-11-18 14:12
So far, it seems that there isn’t any editor software that can reliably complete a "Replace All" operation in just one go. If we want to maintain the user habits of traditional software, perhaps adding a checkbox option could be a good solution, right?

The reason I’m bringing up this issue is simply to make the software more user-friendly and to make my work more efficient. That’s all. If anyone feels offended by this suggestion, then I’ll just work on improving it for my own use. Thank you.

**Closed** 2024-11-18 14:12 UTC

**Comment by pawelzwronek** [comment] 2024-11-18 15:14
@softmgr could you give more examples when new implementation would be expected and desired by common user? The example with clearing all multi spaces to one is interesting but it's only one situation (this can be achieved with very short "` +`" regexp, but most users IMHO dont know what regexp is).

**Comment by softmgr** [comment] 2024-12-01 06:34
The following function is the final optimized version.

```
wstring stringReplace(wstring subject, const wstring& search, const wstring& replace)
{
	const bool flag = (replace.length() > 0 && replace.length() < search.length());
	size_t pos = 0;
	while ((pos = subject.find(search, pos)) != std::string::npos)
	{
		subject.replace(pos, search.length(), replace);
		pos += replace.length();

		// If the replace string is shorter than the search string,
		// move pos back by one character to handle consecutive matches
		if (flag) {
			pos--; // Step back to ensure overlapping matches are caught
		}
	}
	return subject;
}
```
