### ISSUE TITLE
Suggestion: wheel support to scroll menus

### ISSUE THREAD

**Issue by Mrnofish** [notepad-plus-plus/notepad-plus-plus#10204] opened 2021-07-20 17:14 UTC
### Description of the Issue
When the length of a menu exceeds the available vertical room, the menu gains arrows in order to be scrolled.

Scrolling the menu with the wheel is currently impossible.

**Comment by ArkadiuszMichalski** [comment] 2021-07-21 11:37
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8401.

**Closed by ArkadiuszMichalski** 2021-07-21 11:37 UTC
