### ISSUE TITLE
middle-click = continuous scroll (and more...)

### ISSUE THREAD

**Issue by vmdsb** [notepad-plus-plus/notepad-plus-plus#695] opened 2015-08-10 16:08 UTC
1) greater gap between margin and leftmost cursos position, to easy placement at the beginning of line
2) middle-click = continuous scroll
3) split window horizontally, (instead of vertically), to view distant parts of file (such as MS Excel, Word)
4) dragging the selected text beyond window limits triggers scroll (such as MS Excel, Word)

Thanks for all!!!!

**Comment by CTimmerman** [comment] 2015-09-17 15:56
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/465
Also requested on http://sourceforge.net/p/notepad-plus/discussion/331754/thread/14463060 and http://sourceforge.net/p/notepad-plus/discussion/331754/thread/d02b0a99/ which notes that the NppExec console already supports middle mouse button auto scrolling.

**Comment by MetaChuh** [comment] 2019-04-11 00:06
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:06 UTC
Labels: enhancement
