### ISSUE TITLE
PowerShell code is shown as commented out / grey

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#4000] opened 2017-12-13 09:35 UTC
Version 7.5.3

### Steps to Reproduce the Issue
Create a .ps1 file and enter:
```
Param(
	$endString = "`"",
	[Switch]$decode
)
```
### Expected Behavior
Code not being commented out / being grey.

### Actual Behavior
Code after $endString is desplayed as commented out, but code works.

**Comment by dail8859** [comment] 2017-12-13 14:01
Duplicate of #1394

See Scintilla bug [1929](https://sourceforge.net/p/scintilla/bugs/1929/)

This is fixed in Scintilla version 3.7.5 however Notepad++ is still using Scintilla version 3.5.6

**Comment by passboltUser** [comment] 2017-12-14 14:46
Thanks. Hope Notepad++ updates to the newer version.

**Comment by adipiciu** [comment] 2018-03-13 16:07
Scintilla version 3.5.6 is 2 years old.  Can you update just the LexPowerShell.cxx to add the escape character? Or you need to update all the Scintilla dll? This is really an old annoying powershell lex bug and can be fixed very easy.

**Comment by passboltUser** [comment] 2018-07-18 13:10
Recently v7.5.7 was released, but this patch wasn't merged? Why?

**Comment by dail8859** [comment] 2019-05-23 15:52
Fixed in Notepad++ v7.7 since it updated to Scintilla v4.1.4

**Closed by dail8859** 2019-05-23 15:52 UTC
