### ISSUE TITLE
AutoCompletion From X th char ping

### ISSUE THREAD

**Issue by DancingQuanta** [notepad-plus-plus/notepad-plus-plus#690] opened 2015-08-09 12:39 UTC
I have been stuck with this bug for a number of versions up to the current 6.8.1

I have been trying to set the number of characters typed before the Auto-completion of words and functions is triggered.

In the preferences... on the Auto-completion page I clicked on a hyper linked number between the strings "From" and "th character" and a small dialog opened with the string "Nb char :" and a text box right next to it.

I could not enter any number into this text box, neither from the number row or numpad of the real keyboard or onscreen keyboard. Neither pasting a number into this text box work. Every attempt to enter any number into this text box results in a ping.

The only thing that work in this dialog is refusing any alphabet letter which results in an error "Unacceptable character" popup.

Uninstalling and reinstalling does not help.

Has this happened to anyone else?

**Comment by Doryforos** [comment] 2015-08-10 02:41
Same here!

**Comment by DancingQuanta** [comment] 2015-08-13 18:26
I think the best way to deal with this is to remove the hyperlink and minidialog and instead use a textbox like the others in the same window to accept integers.
I do not know the programming language behind NPP so I couldn't contribute.

**Comment by WSiaB** [comment] 2016-04-04 04:06
This may have been fixed. I am able to change this value in version 6.8.8.
![screenshot 2016-04-03 21 03 08](https://cloud.githubusercontent.com/assets/1976258/14237969/ca231f82-f9df-11e5-8b67-37ce9a98b900.png)
![screenshot 2016-04-03 21 03 17](https://cloud.githubusercontent.com/assets/1976258/14237977/d35d4a46-f9df-11e5-9a74-06e3d22ce78e.png)
![screenshot 2016-04-03 21 03 24](https://cloud.githubusercontent.com/assets/1976258/14237978/d9834d12-f9df-11e5-9011-8635826961a8.png)

**Comment by MetaChuh** [comment] 2019-04-11 00:06
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:06 UTC
Labels: help wanted, question
