### ISSUE TITLE
An idea for "replacement" function

### ISSUE THREAD

**Issue by ghost** [notepad-plus-plus/notepad-plus-plus#2392] opened 2016-10-05 02:31 UTC
Sorry if i am wrong when posting this as an issue, please redirect me to another place if so. 

The idea is about one small button which changes lines content between them. 
There's also could be a hotkey like Ctrl+X (photoshop style) for that. 

An image i've made in paint (sorry for russian language interface). 
![github screen](https://cloud.githubusercontent.com/assets/22619187/19099166/fc74d234-8add-11e6-9cd7-2db4c18c6d9f.png)

**Comment by Yashwanth-jarvian** [comment] 2016-10-12 18:16
Wow....Good feature....how do we know whether this is added to the latest np++ build or not

**Comment by ArkadiuszMichalski** [comment] 2020-09-24 18:01
@sasumner Duplicate of newest https://github.com/notepad-plus-plus/notepad-plus-plus/issues/6010.

**Comment by sasumner** [comment] 2020-09-24 18:03
Closing as duplicate.
There does seem to be long-term interest in this (going back 4 years).
I did do some code for this, maybe I should submit it...

**Closed by sasumner** 2020-09-24 18:03 UTC

**Comment by davidalayachew** [comment] 2024-09-15 18:48
@sasumner Any chance that a key-combo could be added for this too?
