### ISSUE TITLE
Exiting (closing) Notepad++ does not always result in previous window getting focus

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#9502] opened 2021-02-12 07:47 UTC
### Description of the Issue
Exiting (closing) Notepad++ does not always result in previous window getting focus.

### Steps to Reproduce the Issue
This is my least favorite type of bug to report, because it only happens sporadically.  But I'm hoping it is appreciated that I'm spending my time to write a report, rather than not.  **UPDATE: After many hours of testing, I was able to generate screen recordings of this behavior happening consistently!**

STR 1:
1. Create a file association to load text files in Notepad++.
2. Open a bunch of different applications.
3. Open a file explorer, and double click on a text file to open it in Notepad++.
4. Edit the file in Notepad++ and scroll around in it.
5. Exit (close) Notepad++.
6. Notice that the window receiving focus when Notepad++ is closed is not the file explorer.

***UPDATE: Screen recording of this exact behavior now available!***

STR 2:
1. Create a shortcut to Notepad++ in the Windows taskbar.
2. Open Windows 7 File Explorer (aka Windows Explorer) and Windows 7 Calculator.
3. Click on the Windows File Explorer window to bring it to the front.
4. Click on the Notepad++ shortcut in the taskbar.
5. Exit (close) Notepad++.
6. Notice that the window receiving focus when Notepad++ closes is often the calculator and not the Windows File Explorer.

***UPDATE: Screen recording of this exact behavior now available!***

I've been able to reproduce this issue, but not 100% consistently, with several file managers including the default Window 7 File Explorer and [FreeCommander](https://freecommander.com/en/downloads/).

### Expected Behavior
The window of the application from which Notepad++ was launched always receiving focus when Notepad++ is closed.

### Actual Behavior
A different application window sometimes receives focus when Notepad++ is closed.

### Debug Information when Originally Reported
Notepad++ v7.9.2   (32-bit)
Build time : Dec 31 2020 - 03:58:36
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 (64-bit) 
Plugins : ColorPicker.dll DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll _CustomizeToolbar.dll 

### Debug Information when STR 1 & 2 Screen Recordings Successfully Generated
Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 (64-bit) 
Plugins : ColorPicker.dll DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppMenuSearch.dll NppQrCode32.dll nppRegEx.dll NppTextFx.dll Remove Duplicate Lines.dll SecurePad.dll TopMost.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by Ekopalypse** [comment] 2021-02-12 14:14
I don't think this is an npp issue at all because I can't find any indication that the closing application MUST do something to keep the Windows internal "last used application" intact.
On the other hand, what would it mean if npp had such functionality?
It has to keep track of what the user is doing? Not desirable.

**Comment by sasumner** [comment] 2021-02-12 14:44
>I don't think this is an npp issue at all

Agree.

>keep the Windows internal "last used application" intact.

How would an application even do this?

**Comment by Ekopalypse** [comment] 2021-02-12 15:01
I think by putting the focus on the application that npp believes needs to have it before shutting down.

**Comment by mere-human** [comment] 2021-02-12 19:26
> I've been able to reproduce this issue, but not consistently, with several file managers including [FreeCommander](https://freecommander.com/en/downloads/).

1. What is your Multi-Instance setting?
![image](https://user-images.githubusercontent.com/9664141/107812768-bf6c9700-6d78-11eb-878f-00e82eaf6142.png)

2. Is the behavior different if you change the editor program in the file manager to be Notepad++ and then edit a file with F4?
![image](https://user-images.githubusercontent.com/9664141/107813371-0195d880-6d79-11eb-9558-91a79ce03ad4.png)

**Comment by Gitoffthelawn** [comment] 2021-02-13 07:59
@mere-human

Great questions.  For the first question, the answer is "Default (mono instance)".

For the second question, I can definitely try that.  The frustrating thing about this issue is that it does not happen most of the time, and I have yet to narrow down the exact STR that will generate this issue 100% of the time.  It happens often enough, though, that I get the sense that there is possibly some condition in which it always occurs.

**Comment by sasumner** [comment] 2021-02-13 13:00
@Ekopalypse said:

>I think by putting the focus on the application that npp believes needs to have it before shutting down.

That's the obvious answer to a badly-asked question. :-P
Of course N++ could do that.
But I meant, barring doing it intentionally, how could it happen (the OP's problem, in a generic sense, with any app)?
It's mostly a rhetoric question, no need to answer. :-)

**Comment by sasumner** [comment] 2021-02-13 13:03
@Gitoffthelawn Is there a pattern, perhaps during your normal use (and not specifically when you are trying to force it to reproduce) as to a consistent or more-likely unexpected app to get activated when this manifests?  Or is it totally random and could be any app?
I presume you have a workflow which is somewhat repetitive, but maybe not.

**Comment by Gitoffthelawn** [comment] 2021-02-13 14:31
@sasumner More good questions! Exactly what you wrote is what is causing me frustration in diagnosing it.  When I take 15 minutes out of my workflow to try all sorts of things to intentionally make it happen, I have _- so far -_ not experienced the issue.  Yet, when I'm in the middle of 5 different things, it happens very frequently.  At those times, though, I'm super busy, and I don't have time to stop and write down everything I was doing.  I think you're spot on that it's some sort of pattern (sequence of events) that causes this unwanted behaviour.

I use many different applications, and none of the other applications ever cause this behaviour.  And this behaviour didn't start until fairly recently... about 2-3 months ago, perhaps (very rough approximate, as I thought I was just slowly losing my mind at first!).

Your question asking if another particular app gets activated when this manifests is an excellent question.  I wish I had the answer at this time, but unfortunately I don't.  I've never noticed a *particular* application that comes to the foreground instead of the last used application, and its definitely not some weird obscure application that does, as my typical workflow involves rather mainstream/popular applications.  I also typically work with very few applications running at one time: typically 2-5 primary applications.  I do also have some system tray applications whose windows are almost never open.

My best guesses, at this point, based on my workflow is that it is one or the following (in no particular order):

1. An issue with Notepad++
2. An issue with an interaction between Notepad++ and [FreeCommander](https://freecommander.com/en/downloads/) and/or [CopyQ](https://github.com/hluk/CopyQ/releases)
3. An issue with an interaction between Notepad++ and another piece of software
4. An issue with FreeCommander or CopyQ

The issue only manifests with Notepad++ (hence my issue report here), but unless other people start chiming in with *"yes, that happens to me too"*, I think it's most likely to be possibility 2.  That begs the question, "is there something unique about Notepad++ that could possibly cause the issue, or something that changed in Notepad++ recently?".

I singled-out FreeCommander and CopyQ (lol... that's a bit of an oxymoron... is there an English expression for singling out two items? doubled-out? lol) because those are the two pieces of software I currently use that interact the most with Notepad++.  FreeCommander is typically responsible for launching Notepad++ and CopyQ handles advanced clipboard functionality.

**Comment by mere-human** [comment] 2021-02-13 18:23
Also, which way do you close the Notepad++? Alt+F4 or X button?

**Comment by Gitoffthelawn** [comment] 2021-02-13 20:19
@mere-human I always use the X button.  I *never* use Alt+F4, so that does narrow it down a touch. :)

**Comment by Marmotian** [comment] 2021-02-14 03:27
I did some experimenting and it seems to me that what Windows does if return focus to the most recently focussed window other than the one you are closing. To me, this is perfectly reasonable behaviour.

To test:
Open a bunch of non-maximized windows from various applications
click on one of them to focus it (window 1)
click on a different window to focus it and then close that window
Result-> focus always returns to window 1 regardless of the applications running, UNLESS you close it from the Taskbar and then the Taskbar is focussed (still last app, technically)

**Comment by Gitoffthelawn** [comment] 2021-02-14 14:27
@Marmotian Thanks for the testing.  Yes, I agree... everything you wrote is how it *should* work, and how it does work for everything except for ***recently*** with Notepad++.  That, of course, doesn't mean it has to be Notepad++ contributing to the issue.  I doubt it's Windows 7, as it has been around for so many years that it would (hopefully) be well-documented if this was a Windows 7 issue.  Now, with Windows 10, nothing would surprise me!

I suppose it's possible that it could be Windows if Notepad++ is doing something real unique when it closes, and thus there isn't any other popular software that triggers the issue.  I think the odds are slim, but not zero.

The mouse bounce idea is definitely a good *"thinking outside the box"* idea.  But, in this case, that's definitely not the issue as my pointing device has a very obvious tactile and audible response when clicked.  Also, the issue only appears when exiting Notepad++, and not any other apps.  That said, kudos for thinking of that clever possibility.

**Comment by Gitoffthelawn** [comment] 2021-02-21 12:48
@donho 

Hi Don! After many, many hours of testing, I have concluded this is almost certainly a bug in Notepad++ v7.9.3.

I tested launching Notepad++ from multiple file managers, including the default Windows Explorer in Windows 7.  I also tested with many different text editors.  The only application to have this problem was Notepad++, and it was independent of the file manager used.

I captured a comprehensive screen recording for you that conclusively demonstrates this issue.  It is in GIF format and is over 1MB in size.  Kindly let me know how to send you the screen recording privately if you think it will help you resolve this issue.

**Comment by Gitoffthelawn** [comment] 2021-02-21 14:41
After even more time spent testing, I am able to successfully influence the *frequency* of this issue revealing its ugly head by modifying the plugins being used by Notepad++.

With the following plugins installed, I was able to reproduce the issue 91% of the time (# tests run = 500):
***Plugins :*** ColorPicker.dll DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppMenuSearch.dll NppQrCode32.dll nppRegEx.dll NppTextFx.dll Remove Duplicate Lines.dll SecurePad.dll TopMost.dll XMLTools.dll _CustomizeToolbar.dll

With just the following plugins installed (which involves removing all the plugins included by default), I was able to reproduce the issue 81% of the time (# tests run = 200):
***Plugins :*** ColorPicker.dll DSpellCheck.dll HexEditor.dll NppMenuSearch.dll

With just the following plugins installed (which involves removing all the plugins included by default), I was able to reproduce the issue 77% of the time (# tests run = 200):
***Plugins :*** ColorPicker.dll HexEditor.dll NppMenuSearch.dll _CustomizeToolbar.dll 

With only the following plugins installed, I was able to reproduce the issue 46% of the time (# tests run = 200):
***Plugins :*** ColorPicker.dll HexEditor.dll NppMenuSearch.dll

Removing any of those last 3 plugins resulted in reducing bug reproducibility to 6%  (# tests run = 500).

If you appreciate my efforts, please take a moment to thank me and make a donation to a charity of your choice.  If you can't afford to feed 1000 strangers, please start with 1.  Everyone needs to eat and have access to clean drinking water.

**Comment by mere-human** [comment] 2021-02-21 14:45
> Removing any of those last 3 plugins resulted in reducing bug reproducibility to 6% (# tests run = 500).

It would be nice to see the video capture you mentioned earlier for this case.

> I captured two comprehensive screen recordings for you that conclusively demonstrate this issue. They are in GIF format and each is over 1MB in size.

This probably could be attached here:
https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests#:~:text=The%20maximum%20size%20for%20files,size%20for%20images%20is%2010MB.
>_The maximum size for files is 25MB and the maximum size for images is 10MB._

**Comment by sasumner** [comment] 2021-02-21 15:26
I was unclear from the "plugins" report if the configuration for only the plugins shipped with Notepad++ was tested?

**Comment by sasumner** [comment] 2021-02-21 16:27
@Gitoffthelawn When @mere-human said:

>This probably could be attached here:

I think he means right HERE...right in this thread's comments.  
Go ahead and attempt to attach it please.

**Comment by Ekopalypse** [comment] 2021-02-23 10:51
@Gitoffthelawn - from where did you install NppTextFx.dll and nppRegEx.dll.
I'm going to try your 91% setup.
Another question - your debug information looks a bit different from mine.

Notepad++ v7.9.3   (32-bit)
Build time : Feb 14 2021 - 03:12:31
Path : D:\Tests\npp\_latest\x32_clean\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : ColorPicker.dll DSpellCheck.dll HexEditor.dll LuaScript.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppMenuSearch.dll NppQrCode32.dll Remove Duplicate Lines.dll SecurePad.dll TopMost.dll XMLTools.dll _CustomizeToolbar.dll 

Any idea why this is the case?

**Comment by Gitoffthelawn** [comment] 2021-02-23 11:52
@Ekopalypse Thank you so much for performing more tests!

Great questions! Here are the answers:

> from where did you install NppTextFx.dll and nppRegEx.dll ?

From my recollection, NppTextFx.dll was included with Notepad++ for many years, and my copy of it was from the latest portable release of Notepad++ that included it.  I am using v2.6.0 of that plugin.  I was also able to find it on SourceForge here: https://sourceforge.net/projects/npp-plugins/files/TextFX/

It is averaging over 2500 downloads per week, so it still must be very popular!

nppRegEx.dll is available on GitHub here:  
https://github.com/larryb82/npp-regexhelper/tree/master/bin
and on SourceForge here:  
https://sourceforge.net/projects/nppregexhelper/files/

The debug information looks a bit different because I removed the path due to lack of relevancy (and privacy), and I tested on 3 different codepages to likely rule out that being an influential factor.  One of the codepages I tested on was codepage 1252, so you're all good there.

**Comment by Ekopalypse** [comment] 2021-02-23 14:10
Ok, I can confirm the reported behaviour when using the list of plugins with 7.9.3 by following the steps listed in STR 2. 
BUT, I do not have this behaviour when using Npp without any third party plugin.
100 out of 100 resulted in the expected behaviour.

Curious as to what could be the cause, I did further research and found that once I remove the NppMenuSearch plugin, it works as expected (20 out of 20).

But if I use NppMenuSearch on its own, then it works. The minimum combination of plugins I've found that shows the unexpected behaviour is using HexEditor, NppMenuSearch and NppQrCode32.

So it seems like it could occur when certain plugins are used together, but I'm sticking with the idea that it's not an Npp problem. Why? Because I did some tests with native Windows applications, namely Explorer, Notepad and Calculator, and found that when using Notepad and Calculator and pressing ALT+F4 to close them, sometimes the shutdown dialogue appears instead of closing Calculator.

**Comment by Gitoffthelawn** [comment] 2021-02-23 15:46
@Ekopalypse  Thank you for performing that testing.  Your efforts are appreciated (at least by me, I can't speak for others) and very helpful.

> Ok, I can confirm the reported behaviour when using the list of plugins with 7.9.3 by following the steps listed in STR 2.

Yea.  We have additional confirmation!

> Curious as to what could be the cause, I did further research and found that once I remove the NppMenuSearch plugin, it works as expected (20 out of 20).
> 
> But if I use NppMenuSearch on its own, then it works.

Yes. This is my experience too.

> The minimum combination of plugins I've found that shows the unexpected behaviour is using HexEditor, NppMenuSearch and NppQrCode32.

I also experience it with just these plugins:  
*ColorPicker.dll DSpellCheck.dll HexEditor.dll NppMenuSearch.dll*
or just these:  
*ColorPicker.dll HexEditor.dll NppMenuSearch.dll _CustomizeToolbar.dll*
or even just these (but significantly less frequently):  
*ColorPicker.dll HexEditor.dll NppMenuSearch.dll*

Since the number of permutations and combinations of all the different Notepad++ plugins exceeds 100 trillion, I elected not to test all of them. ;)


> So it seems like it could occur when certain plugins are used together, but I'm sticking with the idea that it's not an Npp problem. Why? Because I did some tests with native Windows applications, namely Explorer, Notepad and Calculator, and found that when using Notepad and Calculator and pressing ALT+F4 to close them, sometimes the shutdown dialogue appears instead of closing Calculator.

To what "shutdown dialogue" do you refer?  Neither Windows Notepad nor Calculator have any shutdown UI that I'm aware of.  I generally don't use ALT+F4 to close windows (and it's my pleasure to now meet the first person who actually does!), but I can say that neither Windows Notepad nor Calculator have every displayed this undesired behavior for me when closing them with the close button in the upper-right corner of the window.

**Comment by sasumner** [comment] 2021-02-23 15:57
>...pressing ALT+F4 to close them, sometimes the shutdown dialogue ...

Presume what was meant by that is the "Shutdown Windows" dialog.

**Comment by Ekopalypse** [comment] 2021-02-23 16:08
@Gitoffthelawn - as @sasumner already guessed, it is the "Windows Shutdown Dialogue".
Close all applications and then press ALT+F4 and this dialogue appears.
I used ALT+F4, to close the applications, on purpose to see if Windows itself always gives focus to the "most recent window" and this test shows, at least on my machine, that it does not. 
The conclusion I draw from this is that the 6% errors you mentioned earlier may also be Windows problems, and as mentioned in my very first post, I have found nothing in the MSDN to indicate that an application needs to do anything to keep this "most recent window" feature intact.
Sorry, but I can't see how Npp, without snooping on what a user is doing, can meet your requirement.

**Comment by sasumner** [comment] 2021-02-23 16:12
I like @Ekopalypse 's analysis ... so ... Closing!

**Closed by sasumner** 2021-02-23 16:12 UTC

**Comment by Gitoffthelawn** [comment] 2021-02-23 18:27
@donho As the developer, do ***you*** want this closed?  With just 3 plugins installed, Notepad++ clearly has this bug that seriously impacts workflow.  No other applications are known to have this issue.

I realize probably no one cares at all, but I'm going to have to find a different text editor, because this bug interrupts workflow too often to continue using (or recommending) Notepad++.

**Comment by Gitoffthelawn** [comment] 2021-02-23 18:31
@Ekopalypse I believe your conclusion is completely erroneous.  Notepad++ has this problem, and other applications do not.  Even if we learn, in the end, the bug happens to be with Windows, since no other applications exhibit this problem, it's obviously something Notepad++ is doing differently than all other applications that exacerbates the issue.  We likely can't fix Windows, but we can fix Notepad++.

**Comment by sasumner** [comment] 2021-02-23 18:33
@Gitoffthelawn I always recommend Sublime to those that have decided to leave the Notepad++ fold.  It's a solid choice in a text editor.

**Comment by Ekopalypse** [comment] 2021-02-23 19:06
@Gitoffthelawn - Npp, without third-party plugins installed, doesn't show this behaviour, at least not for me, but with a combination of certain plugins it does. I suspect that these plugins hook into npp's window procedure and one does not return correctly when npp is closed. See https://docs.microsoft.com/en-us/windows/win32/winmsg/about-hooks for more information.
What can npp do in such a case? Nothing. (It could, of course, forbid plugin loading or, as I said, snooping - but neither seems desirable). To me, it's more likely that the culprit is the way plugins hook and unhook the window procedure.

Other applications you have tested may not be affected in this way, as they either do not allow plugins to be loaded, or in a more restrictive way only "allow" connection to a predefined plugin API.
Other applications may have a different "unexpected" behaviour, such as when closing Sublime, the desktop always seems to get the focus.
