### ISSUE TITLE
[Feature request]: Allow markdown "code folding"

### ISSUE THREAD

**Issue by GwenaelQ** [notepad-plus-plus/notepad-plus-plus#11804] opened 2022-06-15 22:30 UTC
Hi,

Nothing new. This is an [old request](https://superuser.com/questions/563270/foldable-collapsable-notepad-markdown-syntax)... But seems to me that after years of (very) frustrating waiting we are near from a solution: 

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10670:  

> Awesome, thanks. Would be nice if it was included in the default installer too though.

But https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10670 already closed.

So opening this duplicate to ask for the integration of @ArkadiuszMichalsk's code in the default installer

Another wonderful feature for markdown writers would be adding a heading list view (TOC view) on the side pane.

Thanks for the good work and for listening

**Comment by ArkadiuszMichalski** [comment] 2022-06-16 19:35
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9473. You can try with this code https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9734#issuecomment-830658640 (but need compile by yourself).

**Closed by ArkadiuszMichalski** 2022-06-16 19:35 UTC

**Comment by justsome12** [comment] 2026-04-20 07:56
is there a solution by now?
