### ISSUE TITLE
New instance of NPP starts with NppFTP window hidden

### ISSUE THREAD

**Issue by icefront** [notepad-plus-plus/notepad-plus-plus#11111] opened 2022-01-31 17:53 UTC
### Description of the Issue
There is an issue when opening a new instance of Notepad++. The NppFTP dockable window is hidden, it has to be turned on again and again.

### Steps to Reproduce the Issue
1. Open Notepad++
2. Make sure, the NppFTP windows is visible and it is docked
3. Hit Alt+F6 to open a new instance of Notepad++

### Expected Behavior
Keep the docked NppFTP window

### Actual Behavior
The NppFTP window is hidden, its icon on the toolbar has to be clicked to reveal the docked window.

**Comment by ArkadiuszMichalski** [comment] 2022-01-31 18:41
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9710.

**Closed by ArkadiuszMichalski** 2022-01-31 18:41 UTC
