### ISSUE TITLE
Find All in All open documents / Find All in Current Documents

### ISSUE THREAD

**Issue by jitsnotepad** [notepad-plus-plus/notepad-plus-plus#1649] opened 2016-03-18 07:22 UTC
![2016-03-18_12h40_28](https://cloud.githubusercontent.com/assets/17921794/13871083/a183ce94-ed07-11e5-8f86-4362a08664be.png)

"Find All in All open documents / Find All in Current Documents " function not working in Notepadd latest version 'Notepad++ 6.9' while its works correctly in version 'notepad++ 6.8.8'..

Can development team look  into this please?

**Comment by dail8859** [comment] 2016-03-28 21:28
Define "not working"! Does this just mean it is not finding anything? Does it give errors? It works fine for me using v6.9.

**Comment by MetaChuh** [comment] 2019-04-13 02:26
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:26 UTC
