### ISSUE TITLE
Keyboard shortcuts don't work in new modal dialogs

### ISSUE THREAD

**Issue by mladenb** [notepad-plus-plus/notepad-plus-plus#7635] opened 2019-11-21 15:09 UTC
### Description of the Issue
When closing NPP with pending changes in an open file, a modal dialog pops up asking to save a file with buttons: Yes, No, Cancel, Yes to All, No to All. Previous version of NPP had only buttons: Yes, No, Cancel. In this new modal dialog, with 5 buttons, there are no keyboard shortcuts mapped, so I cannot for example press, on the keyboard: Ctrl+W (close tab), N (don't want to save the file), which I previously was able to.

### Steps to Reproduce the Issue

1. Open NPP, start typing something
2. Press Ctrl+W, a modal dialog will pop up asking you to save a file
3. Try pressing 'N' on your keyboard

### Expected Behavior
A button with title 'No' gets triggered/pushed.

### Actual Behavior
Nothing happens.

Since the latest update, this stopped working, but was working before.

**Comment by sasumner** [comment] 2019-11-21 15:49
Closed as duplicate of #6223

**Closed by sasumner** 2019-11-21 15:49 UTC
