### ISSUE TITLE
[BUG] <title>Selecting a folder does not open underlying files anymore.

### ISSUE THREAD

**Issue by RobTillaart** [notepad-plus-plus/notepad-plus-plus#15688] opened 2024-10-10 12:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

(Windows 10)
In a pre 8.7 version I used to select a text file and some folders which contain txt files (a level deeper).

When selecting OPEN it opened all files recursively.

Since 8.7 It does not open the files under the folders anymore, and I have to open them one by one.

A popup appears about creating the file.

### Steps To Reproduce

1.  See above
2.  
3.  

### Current Behavior

See above

### Expected Behavior

I was hoping NPP would open all editable files in the selected folders.

### Debug Information

```shell
Notepad++ v8.7   (64-bit)
Build time : Sep 17 2024 - 17:06:31
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "D:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\Wire.cpp" "D:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\Wire.h" "D:\Program Files (x86)\Arduino\hardware\arduino\avr\libraries\Wire\src\utility" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.5011
Current ANSI codepage : 1252
Plugins : 
    ColumnsPlusPlus (1.0.6)
    ComparePlugin (2.0.2)
    CSVLint (0.4.6.6)
    CsvQuery (1.2.9)
    DSpellCheck (1.4.23)
    Linter (0.1)
    MarkdownViewerPlusPlus (0.8.2)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NPPJSONViewer (1.40)
    NppMarkdownPanel (0.5)
    NppXmlTreeviewPlugin (2)
```

**Comment by xomx** [comment] 2024-10-11 21:46
Duplicate of #15645 and more, please close this issue.
The problem will be fixed in the next N++ version.

**Comment by RobTillaart** [comment] 2024-10-12 04:35
Sorry, did miss that one as duplicate.

**Closed** 2024-10-12 04:36 UTC
