### ISSUE TITLE
Horizontal scrollbar length doesn't update on document line length change

### ISSUE THREAD

**Issue by jukkamaljanen** [notepad-plus-plus/notepad-plus-plus#926] opened 2015-09-17 06:31 UTC
If I have a long line of text and then reform it to many short lines, the horizontal scrollbar is not updated. Scrolling horizontally becomes stupid. The only workaround I have found is to reopen the file.

**Comment by kraint** [comment] 2016-08-15 23:41
Reproduced with N++ 6.9.2 on Win8.1 64b. 

Window horizontal size is increased as needed when the file column count increases(pasting text, typing), but is not decreased when column count is reduced.

**Comment by christino156** [comment] 2016-11-28 00:47
Also happens to me with v7.2 of Notepad++ on Windows 10 64-bit.

**Comment by MetaChuh** [comment] 2019-04-09 23:47
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:47 UTC
