### ISSUE TITLE
[Feature Request] Add command to toggle block comments

### ISSUE THREAD

**Issue by Gitoffthelawn** [notepad-plus-plus/notepad-plus-plus#9086] opened 2020-10-31 16:05 UTC
Notepad++ features a useful command to toggle line comments, but not one to toggle block comments.  Can such a feature be added?

**Comment by ArkadiuszMichalski** [comment] 2020-10-31 16:31
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8300.

**Comment by sasumner** [comment] 2020-10-31 17:56
Closing due to duplication; one is enough.

**Closed by sasumner** 2020-10-31 17:56 UTC
