### ISSUE TITLE
Editable document area not filling available area

### ISSUE THREAD

**Issue by JRoughan** [notepad-plus-plus/notepad-plus-plus#11018] opened 2022-01-10 10:10 UTC
### Description of the Issue
Notepad++ is no longer usable as it opens it's document windows in tiny areas within the main interface (as if there were 2 inch margins on all sides). There are also floating 'tool window' style widgets with no content. These can be closed; Closing some affects the layout, others do not, but it's not possible to get back into a working state. I delete all settings and restarted NP++ and had the same issue. I reinstalled NP++ and it looked fine until I resized the main window at which point I was in exactly the same situation as before.

### Steps to Reproduce the Issue

1.  Open NP++

(the only other information which may be relevant is that I have a two monitors with different resolutions and different scaling. This has been the case for several years of using NP++ without incident but may be something to consider)

### Expected Behavior
I expected to see the editable document area to be directly under the menu and fill the entire remaining window area (above the status bar).

### Actual Behavior
Editable document window is in an inmovable and non-resizable area which is much less than the entire available area

### Debug Information
Notepad++ v8.2   (64-bit)
Build time : Dec 30 2021 - 03:40:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1415
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/75117/148748583-246de26d-6836-4f5b-9fd5-2d8b9c1546d1.png)

**Comment by ArkadiuszMichalski** [comment] 2022-01-10 11:02
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9717.

**Closed** 2022-01-10 11:03 UTC
Labels: duplicate
