### ISSUE TITLE
Feature Request: Assign Tab Color based on file extension

### ISSUE THREAD

**Issue by jim-j** [notepad-plus-plus/notepad-plus-plus#13077] opened 2023-02-08 17:14 UTC
### Proposed

Is it possible to have Notepad++ automatically assign a tab color based on the file extension? That way it would be easier to select tabs when you have many tabs open. It would be nice to see source code, log files, text files, etc.

**Comment by VsevolodGolovanov** [comment] 2023-02-17 14:00
Duplicate of  #12223?

**Closed** 2023-02-17 15:23 UTC

**Comment by jim-j** [comment] 2023-02-17 15:29
Sorry didn't find that. I closed my request.

At 08:00 2/17/2023, you wrote:
