### ISSUE TITLE
Autosave modified documents when Notepad++ window loses focus

### ISSUE THREAD

**Issue by cosuwi** [notepad-plus-plus/notepad-plus-plus#8729] opened 2020-08-17 20:30 UTC
Please add this feature to Notepad++. _Autosave_ plugin does this, but it switches all tabs, which takes much time on minimizing and restoring Notepad++ window.

**Comment by sasumner** [comment] 2020-08-17 20:33
Duplicate of #8728.
Please don't duplicate issues.
Add any further comments you have to existing issues.

**Closed by sasumner** 2020-08-17 20:33 UTC

**Comment by cosuwi** [comment] 2020-08-17 20:42
@sasumner May the issue #8728 be reopened?

**Comment by cosuwi** [comment] 2020-08-18 00:10
@donho Please reply.
