### ISSUE TITLE
NPP with Wine, menu selection crash

### ISSUE THREAD

**Issue by jim-rosenvelt** [notepad-plus-plus/notepad-plus-plus#11941] opened 2022-07-24 09:56 UTC
### Description of the Isue
I run NPP version 8.4.4 with Wine version 7.0 on Linux Debian 10.5. 
When I select Settings -> Style Configurator, NPP crashes right away. 
This happens with NPP 8.4.3 as well, but NPP 8.4.2 works fine.

### Steps to Reproduce the Issue

1. Install NPP on Linux with Wine
2. select Settings -> Style Configurator

### Expected Behavior
selecting a style configuration

### Actual Behavior
crash, see attached NppDump.dmp file

### Debug Information
Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
WINE : 7.0
Plugins : none
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9175524/NppDump.zip)

**Comment by pribeirojtm** [comment] 2022-07-25 08:40
Same here. Problem started with last upgrade to 8.4.4 . Also a crash is happening when trying to access Plugin Admin...
![Screenshot from 2022-07-25 09-40-23](https://user-images.githubusercontent.com/18724236/180735404-10f8bfb2-a1f9-4a6a-b049-4cbaade911b3.png)

**Comment by xomx** [comment] 2022-07-25 08:51
It seems from the above crashdump that it is crashing in the ComCtl32.dll (MS Common Control library) call.

**Comment by donho** [comment] 2022-07-25 15:06
@xomx  
> It seems from the above crashdump that it is crashing in the ComCtl32.dll (MS Common Control library) call.

From the provided dump by @jim-rosenvelt, I saw the same problem. Regarding the change of Styler Configurator, I've checked the following commits:
79e766755d9d466704c535f99eb3ce99ffbbb1bf , 5c6fbd33103f3cde666c48a6a6ce0bcc8a90ff0e and 67ab4d55276ae99e632f19d1035de70cc022e3b9
But non of them seems causing the crash.

According the description of @pribeirojtm , now there's a crash on another dialog, I'm wondering it's due to d1347d501451e10c5d988282ca681760d2c2abff
 
@pribeirojtm @jim-rosenvelt 
Could you try other dialogs please?

**Comment by pribeirojtm** [comment] 2022-07-25 15:42
It was also happening when I was opening the program with Npp Snippets plugin, that was a bit more stresses since that way I couldn't use the program. Then I removed the Plugin manually, then the only problem for now is when I try to access Plugins admin dialog so as the one reported initially in here. Just  to add that I also use Wine 6.0.1 (Windows 7 kernel) on a ubuntu 20.04.
Other dialogs seems ok for now.

**Comment by donho** [comment] 2022-07-25 19:10
@pribeirojtm 
> It was also happening when I was opening the program with Npp Snippets plugin, that was a bit more stresses since that way I couldn't use the program. Then I removed the Plugin manually, then the only problem for now is when I try to access Plugins admin dialog so as the one reported initially in here. Just to add that I also use Wine 6.0.1 (Windows 7 kernel) on a ubuntu 20.04.
> Other dialogs seems ok for now.

Could you provide the Debug Info please (via menu `?->Debug Info...`)?

**Comment by donho** [comment] 2022-07-25 19:12
@xomx 
I'll try to build a VM to reproduce the crash.

**Comment by kalomakac** [comment] 2022-07-29 09:03
Same happens to me.
Output from Debug Info:

Notepad++ v8.4.4   (64-bit)
Build time : Jul 15 2022 - 17:54:42
Path : Z:\home\user\snap\notepad-plus-plus\369\notepad-plus-plus\notepad-plus-plus.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
WINE : 6.0.4
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)

Fails as soon I open Plugin Admin with error Access violation. This is fresh installation on latest Ubuntu 22.04 from snap.
**Win32Exception**
An exception occured. Notepad++ cannot recover and must be shut down.
The exception details are as follows:
Code: 0xC0000005
Type: Access violation
Exception address: 0x000000006CA571F8

**Comment by xomx** [comment] 2022-07-29 09:41
I have got access to a WINE set-up (WINE 6, openSUSE), so I can confirm this Win32Exception. I will see what I can do.

**Comment by xomx** [comment] 2022-07-30 01:52
@donho 

The culprit is probably the following DarkMode commit:  https://github.com/notepad-plus-plus/notepad-plus-plus/commit/d3b026bfeb96eb39e0402673d68dd04e640e2e1e

The following callstack is from a WINE6 crashdump (N++ 8.4.3 x86 Debug, just invoking the N++ menu Settings->Preferences...) with N++ functions calls decrypted:
![npp_WINE_crash_callstack](https://user-images.githubusercontent.com/13075183/181864995-13528310-7d4e-46c0-8472-a57083e078d6.png)

To confirm my suspicion, I replaced the red-marked callstack func (in the ".\PowerEditor\src\NppDarkMode.cpp") with this stub and the crash has gone and everything works again:

```
	void autoSubclassAndThemeChildControls(HWND hwndParent, bool subclass, bool theme)
	{
		UNREFERENCED_PARAMETER(hwndParent);
		UNREFERENCED_PARAMETER(subclass);
		UNREFERENCED_PARAMETER(theme);

		/* ... */
	}
```

The real problem could be the use of lambda [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/7d5516e0a8ef69d04165926255828cc70c0c3811/PowerEditor/src/NppDarkMode.cpp#L1787).

**Comment by donho** [comment] 2022-07-30 12:37
@xomx 
I'm away from home, and won't be at home before 3 weeks. Could you do a PR for fixing this issue please?

**Comment by xomx** [comment] 2022-07-30 12:58
@donho 

Ok, enjoy your holiday.

As for the PR - I can try, but I rather invite @ozone10 to do it.

For now I am going to do a simple PR with just the above stub-replacement for the other WINE user to be able to confirm my findings. Then it can be replaced with a proper fix.

**Comment by donho** [comment] 2022-07-30 13:21
> As for the PR - I can try, but I rather invite @ozone10 to do it.

Yes, sounds great. Thank you!

**Comment by xomx** [comment] 2022-07-30 16:10
@jim-rosenvelt @pribeirojtm @kalomakac 
Could you please test patched N++ binaries?

[32-bit](https://ci.appveyor.com/api/buildjobs/if9dwbn60gvwldaa/artifacts/Notepad%2B%2B.Win32.Release.exe)
[64-bit](https://ci.appveyor.com/api/buildjobs/6mp7rcfrsrp13im5/artifacts/Notepad%2B%2B.x64.Release.exe)

Just download an appropriate binary and replace your "notepad++.exe" installed.

(it is not a final fix, this cripples the N++ DarkMode stuff somehow, but the N++ should be fully functional otherwise)

**Comment by jim-rosenvelt** [comment] 2022-07-30 18:10
@xomx 

I moved my mouse through the whole menu structure without any crashes or error messages and my Obsidian theme (c code selection) looks flawless, so well done sir!

I will replace my current 8.4.1 executable with this one and will update you on any crashes or error messages.

Thank you!
 


Notepad++ v8.4.4   (64-bit)
Build time : Jul 30 2022 - 15:49:47
Path : Z:\home\administrator\Downloads\Notepad++.x64.Release.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 10 (64-bit) 
OS Build : 18362.0
Current ANSI codepage : 1252
WINE : 7.13
Plugins : none

**Comment by jim-rosenvelt** [comment] 2022-07-31 07:42
@xomx

One small visual flaw I've noticed are the symbols on the tab buttons in the top right corner. From a functional standpoint they work fine.

[screenshot](https://i.postimg.cc/rF65ksVP/npp8-4-4.png)

**Comment by xomx** [comment] 2022-07-31 09:21
@jim-rosenvelt 
Yes, I have noticed that too. But this is not influenced by my temporary DM-patch, it is a separate font issue caused by the https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2c0134ef5ade677e427400c6684f34edd55c4fd0 . N++ resources have been [changed to use Unicode](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11757#issuecomment-1145072901) and WINE evidently has problem to translate that correctly. As my patched binaries use the latest [commit](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/7d5516e0a8ef69d04165926255828cc70c0c3811), you can hide this visual glitch if you want to:
![npp_pref-hide_right_top_shortcuts](https://user-images.githubusercontent.com/13075183/182019541-50d48c5b-6299-4fe3-a4a7-bc74ea24dccd.png)

**Comment by donho** [comment] 2022-08-02 03:02
@jim-rosenvelt & @kalomakac 
Could you try this [pr](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11961) and confirm your crashes have been fixed by it please?

**Comment by donho** [comment] 2022-08-05 06:33
@jim-rosenvelt, @pribeirojtm  & @kalomakac 
Could you try this [pr](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11961) and confirm your crashes have been fixed by it please?

**Comment by jim-rosenvelt** [comment] 2022-08-05 16:43
@donho 

As I wrote before, the release (tested the [64-bit](https://ci.appveyor.com/api/buildjobs/6mp7rcfrsrp13im5/artifacts/Notepad%2B%2B.x64.Release.exe) one) suggested by @xomx has solved the menu issue or do you refer to a different release candidate?

**Comment by xomx** [comment] 2022-08-05 17:17
@jim-rosenvelt 

It is a different one - [direct link to the 64-bit binary](https://ci.appveyor.com/api/buildjobs/79voo6rtv9sr8rhp/artifacts/Notepad%2B%2B.x64.Release.exe). This one will not cripple the DarkMode stuff.
If you could test that too, it will be great.

**Comment by jim-rosenvelt** [comment] 2022-08-05 17:50
@xomx 

This version runs flawless as well when I browse through the whole menu structure, apart from that same small visual issue with the tab button symbols (see my earlier post).

Notepad++ v8.4.4   (64-bit)
Build time : Jul 31 2022 - 20:10:36
Path : C:\Program Files\Notepad++\Notepad++.x64.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Microsoft Windows 10 (64-bit) 
OS Build : 18362.0
Current ANSI codepage : 1252
WINE : 7.14
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.7)
    NppConverter (4.4)
    NppExport (0.4)

**Comment by xomx** [comment] 2022-08-05 18:19
@donho 

I think that the PR is ok. I tested that too (openSUSE, Wine 6).

I am still curious about the real reason of this COMCTL32 crash (probably a native Wine bug) , but now I will be computer-free for one week. Maybe later.

**Comment by kalomakac** [comment] 2022-08-12 11:09
Provided binary by xomx is working. Thank you.

**Comment by donho** [comment] 2022-08-13 21:33
Thank you @xomx for your explanation.
Thank you @jim-rosenvelt & @kalomakac for your confirmation!

**Closed** 2022-08-14 16:22 UTC
Labels: accepted, crash

**Comment by zzhiyi** [comment] 2022-08-24 03:28
Hi, Wine developer here. This bug should be fixed by https://source.winehq.org/git/wine.git/commitdiff/9b9fef2e112ff2ce0e1ce2da3aaacd2ffefa6d87
