### ISSUE TITLE
Fix "Ctrl + Q" in *.html files PLEASE!!!!!!!!!

### ISSUE THREAD

**Issue by manake** [notepad-plus-plus/notepad-plus-plus#3972] opened 2017-12-07 22:22 UTC
In `<script>` and `<style>` tags in *.html files Ctrl + Q should be making `//` and `/* */` comments and not `<!-- -->`.

**Comment by dail8859** [comment] 2017-12-11 14:07
Duplicate of #1850 (which I'm sure you are aware of).

**Closed by dail8859** 2017-12-11 14:07 UTC
