### ISSUE TITLE
Feature request: line up block by char

### ISSUE THREAD

**Issue by CarpeCimex** [notepad-plus-plus/notepad-plus-plus#1186] opened 2015-11-25 19:31 UTC
Notepad++ is a fabulous text editor!  It's been my editor of choice for over a year now and I love it.

I particularly like how easy it is to use Alt-drag to select and work with a block of text.  This is extremely useful.

I often like to make text tables line up when I'm writing source code, though, and it would be great to be able to select a block using Alt-drag and then say "line up the commas", colons, parens, or whatever.  It would probably be fine to add spaces on the left block edge to make the specified chars line up on the right block edge -- I think in general the block could be drawn to make that work.

Again, many thanks for an excellent program!

**Comment by dail8859** [comment] 2015-11-25 20:18
Sounds like what you want is already available with [this](http://www.codealignment.com/ForNotepadPlusPlus.html) plugin

**Comment by linquize** [comment] 2015-11-26 01:10
Does it help align markdown tables?

**Comment by CarpeCimex** [comment] 2015-11-26 03:26
It's puzzlingly difficult to find out how to work this plugin.  After experimenting for a while, I can see it works for some things but it's not really what I'm after.  Say you have text like this:

    {"name":  "Rsd",  "init": 20e-3, "vary": True, "min":  0.0, "max":  None},
    {"name":  "Rp1",  "init": 200, "vary": True, "min":  0.0, "max":  None},
    {"name":   "L1",  "init": 900e-9, "vary": True, "min":  0.0, "max":  None},

and you want to line up all the commas.  The first column of them is already aligned, but not the rest.  Code align doesn't do anything when I select this text, type Ctrl/Shift/= and specify ','.  

Maybe it doesn't work with multiple alignment chars on the same line?  This is why I wanted something which would align a *block*.  I'd like to drag out a block starting at the '2' on the first line and including the comma after `900e-9` on the third line, and have the commas lined up by inserting spaces at the left edge of my drawn block.  Or something like that.  I'd repeat that as necessary to line things up.

**Comment by linquize** [comment] 2015-11-26 07:14
json

**Comment by MetaChuh** [comment] 2019-04-13 02:17
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:17 UTC
