### ISSUE TITLE
Not responding Issue

### ISSUE THREAD

**Issue by tiwarinitin94** [notepad-plus-plus/notepad-plus-plus#4875] opened 2018-09-24 12:09 UTC
### Description of the Issue

Since when I have started using SherloEplorer my editor hangs, not always, but whenever I try to do something a little quick. Even that's not a major prolem. No matter how amazing your product is, it crashes at some point, but that clears all my file that I was editting. I have lost some very important codes. But I forgive you for that :P 

I don't know the detailed issue, but I do have .dmp file let me know if that helps, and I have found out that i cannot upload that file here. 

I don't have any other detailed report on this issue.

Another thing I have faced this problem in windows 7 64 bit

Notepad ++ version 7.5.8

### Steps to Reproduce the Issue

1. 
2. 
3. 

### Expected Behavior

I expect that your product should recover the data from the last session, I should get my file back when something like this happens. At least the saved one. Just like the MS Office does.  and also please provide a navigation on the left side for default, not a plugin. And If people don't want it they can close it, or toggle it. 

### Actual Behavior

Other files were safe, but the one I was editing was completely clean, there was nothing when I opened that File again. Also it runs slow after using SherloXplorer.

**Comment by sasumner** [comment] 2018-09-24 12:15
It surely seems like you are reporting a SherloExplorer plugin bug here.  The problem is, this issues list is for Notepad++ issues.  Try removing the plugin and see if your problems persist.  Report back here.  If the problems go away, suggest closing this issue and finding out where that specific plugin is supported and creating a bug report THERE.

**Comment by tiwarinitin94** [comment] 2018-09-24 12:18
And does Notepad++ has any built in navigation bar for default that I can use??

**Comment by MetaChuh** [comment] 2019-05-02 13:47
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-02 13:47 UTC
