### ISSUE TITLE
Redundant modal prompt when I "Reload from Disk"

### ISSUE THREAD

**Issue by tom-puckett** [notepad-plus-plus/notepad-plus-plus#10439] opened 2021-08-24 15:57 UTC
### Description of the Issue
I'm using v 8.1.2

When I "Reload from Disk" I get a prompt that the file has changed and do I want to reload the file.  This is distracting and not needed.  For what it's worth I have mapped a key to this menu item and access the feature using that mapped key. 

### Steps to Reproduce the Issue

1. Load a file that will change due to external influences (e.g. a log file from another active application)
2. Don't switch focus to another application
3. Wait until you know there is a change in the loaded file from the outside source
4. Invoke "Reload from Disk"

### Expected Behavior
The file reloads without asking me a redundant question

### Actual Behavior
Modal dialog notifying me that the file changed and do I want to reload it

**Comment by ArkadiuszMichalski** [comment] 2021-08-24 16:16
Have you tried these settings?
https://npp-user-manual.org/docs/preferences/#misc

![image](https://user-images.githubusercontent.com/2730894/130652454-e5ec344c-598d-41f3-942b-b1fb83cd619e.png)

**Comment by tom-puckett** [comment] 2021-08-24 16:20
I have not, but I don't see anything there that addresses this specific issue.  I like and rely on the status auto detection, except in the situation where I'm asking the software to reload the file. In that specific situation, the prompt is redundant.

**Comment by ArkadiuszMichalski** [comment] 2021-08-24 16:25
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8158.

**Closed by ArkadiuszMichalski** 2021-08-24 16:25 UTC
Labels: duplicate
