### ISSUE TITLE
npp crash while change line end format

### ISSUE THREAD

**Issue by imbear** [notepad-plus-plus/notepad-plus-plus#1085] opened 2015-11-03 02:14 UTC
![txt - notepad -2015-11-03 09_56_47](https://cloud.githubusercontent.com/assets/2120811/10899794/59902092-8213-11e5-8dab-c1b9db283f04.png)
![greenshot -2015-11-03 09_57_59](https://cloud.githubusercontent.com/assets/2120811/10899797/6257e476-8213-11e5-9ef0-97421515bff0.png)
![greenshot -2015-11-03 09_59_00](https://cloud.githubusercontent.com/assets/2120811/10899799/6781bc2e-8213-11e5-867d-570725aa1ad3.png)

windows7 home chinese(japanese locale)

I don't know how to upload the text file.

PS: the crashed version is 6.8.5. I test 6.8.6, it is ok.

**Comment by donho** [comment] 2016-01-30 12:19
@imbear Could you update to v6.8.8 and try again?
If you can always reproduce the crash, could you provide debug info via menu "?->Debug Info" ?

**Comment by imbear** [comment] 2016-02-01 01:29
I reproduced the crash on 6.8.8.

this is my test file: [米國.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/111625/default.txt)

Notepad++ v6.8.8

Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7
Plugins : AnalysePlugin.dll CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll guidguard.dll LightExplorer.dll LocationNavigate.dll mimeTools.dll NppCalc.dll NppConverter.dll NppExec.dll NppExport.dll NppFTP.dll NppGTags.dll NppSaveAsAdmin.dll PluginManager.dll SessionMgr.dll TagLEET.dll TagsJump.dll TagsView.dll

**Comment by MetaChuh** [comment] 2019-04-10 01:45
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 01:45 UTC
