### ISSUE TITLE
Editing window is small, pushing inward by strange 'x' boxes appearing

### ISSUE THREAD

**Issue by fordville** [notepad-plus-plus/notepad-plus-plus#10618] opened 2021-10-04 14:11 UTC
### Description of the Issue
When I open the app, the tabs/windows within the app are badly misplaced

### Steps to Reproduce the Issue

1. Open the app
2. 
3. 

### Expected Behavior
The editing window should fill the app workspace as it did in previous versions

### Actual Behavior
editting window is smaller and there are these 'x' boxes forcing the window to be smaller for no apparent reason.

### Debug Information
Notepad++ v8.1.5   (32-bit)
Build time : Sep 26 2021 - 15:15:32
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2009
OS Build : 19043.1165
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/16925668/135866393-16a91b48-6bbd-441f-8488-ef99c56f6301.png)

**Comment by dail8859** [comment] 2021-10-04 19:08
Duplicate of #9717

Also, see this community forum discussion: https://community.notepad-plus-plus.org/topic/21895/faq-desk-huge-gaps-blank-areas-in-the-ui-borders

**Closed by dail8859** 2021-10-04 19:08 UTC
