### ISSUE TITLE
Sub-window "Search Results" after performing a "Find All in..." shows expanded only in first instance

### ISSUE THREAD

**Issue by sakkamade** [notepad-plus-plus/notepad-plus-plus#9488] opened 2021-02-06 17:00 UTC
### Description of the Issue

Upon attempt to use "Find All in (Current or Opened) Documents" the "Search Results" won't show in expanded state and has to be dragged up in any instance excepting the first opened one.

### Steps to Reproduce the Issue

1. Open some files in program
2. Open some files in another instance of the program (keeping the first instance open)
3. Perform a "Find All in..." search in a second (third, and so forth) instances
4. Observe Search results window collapsed at the bottom (as docked window https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-774509392)

### Expected Behavior

Search results window should keep its size, otherwise display in expanded state in all a program's instances

### Actual Behavior

Search results window is collapsed in any instance apart from first opened one

### Debug Information

Notepad++ v7.9.2   (32-bit) (portable and installer)
Build time : Dec 31 2020 - 03:58:36
Path : C:\Users\oldman\Desktop\n\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.1082
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

### Extra info

Does not occur in Notepad++ v7.9.1 (32-bit) (portable and installer)

**Comment by sakkamade** [comment] 2021-02-06 17:17
Ah, thank you @thomassmith311 https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-774509392

Indeed.

**Comment by sasumner** [comment] 2021-02-06 17:24
>Open some files in another window of the program (keeping the first one open)

is better stated as: _Open some files in another instance of the program (keeping the first instance open)_

**Comment by sakkamade** [comment] 2021-02-06 17:28
I thought so, but the definition from _wiktionary_ "(computing) A specific occurrence of something that is created or instantiated, such as a database, or an object of a class in object-oriented programming," somewhat taken me aback. Thanks.

**Comment by thomassmith311** [comment] 2021-02-06 17:30
> Ah, thank you @thomassmith311 [#9487 (comment)](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-774509392)
> 
> Indeed.

Not sure exactly what you're thanking me for — that post was for a different issue.

Anyways, I tested this and I can't reproduce the issue. Using the command when two windows are open, like so:
![image](https://user-images.githubusercontent.com/19561856/107125304-0dfccb80-6877-11eb-9cc4-bf75c9e0ab6e.png)
works just fine for me.

**Comment by sakkamade** [comment] 2021-02-06 17:31
>  window actually does display, but it has to be dragged out

Exactly the same with "Search results" window

**Comment by sakkamade** [comment] 2021-02-06 18:59
Anyway, it appears to be a duplicate (look https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-774519583). 
I didn't notice them for they were closed.

----

So the offtopic will make no much of difference:

@thomassmith311 How did you type `—` in your previous commentary

> thanking me for — that post 

Albeit I'm using `Microsoft IME`, I need to switch to Japanese and only afterwards the hyphen key will allow me to type `—`. 
And such is not much convenient when wirting in English.
What is your way of typing it?

**Comment by thomassmith311** [comment] 2021-02-06 19:39
> @thomassmith311 How did you type `—` in your previous commentary
> 
> > thanking me for — that post
> 
> Albeit I'm using `Microsoft IME`, I need to switch to Japanese and only afterwards the hyphen key will allow me to type `—`.
> And such is not much convenient when writing in English.
> What is your way of typing it?

While holding Alt, press, on the number pad to the right: 0, 1, 5, then 1.

**Comment by sasumner** [comment] 2021-02-06 19:46
@sakkamade

>I thought so, but the definition from wiktionary "(computing) A specific occurrence of something that is created or instantiated, such as a database, or an object of a class in object-oriented programming," somewhat taken me aback.

Well, a quick way to test your reported problem is to right-click a tab, and choose *Open in New Instance*, which shows you the proper naming / nomenclature right there.

**Comment by sakkamade** [comment] 2021-02-06 20:02
@thomassmith311 Amazing! ❤️ 

@sasumner Never knew there was such string. What's important that you understood and corrected me.

At any rate, I'm not certain that I need to close the issue now, until the next release, for although it probably was fixed with https://github.com/notepad-plus-plus/notepad-plus-plus/commit/67234d22697f054e2f3b6985a87195eb00744bcb, new issues of similar content might still appear.
However you free to make a decision.

**Comment by sasumner** [comment] 2021-02-06 21:21
@sakkamade 

Why don't you test the build with the fix, and report back?
Click [HERE](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/37291084/job/uby0wb7a20ita35x/artifacts) and download the exe.  Put it in the same folder as your normal notepad++.exe and run it instead.  
Then check if the problem remains.

**Comment by sakkamade** [comment] 2021-02-06 22:44
> Why don't you test the build with the fix...

Already tested and fix confirmed to work in similar issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487#issuecomment-774530023

> ...and report back? Click HERE...

Tested. Problem solved.

**Comment by sasumner** [comment] 2021-02-07 02:54
Can't tell with 100% certainty what the preceding meant, but as original-poster seems satisfied...closing.

**Closed by sasumner** 2021-02-07 02:54 UTC

**Comment by sakkamade** [comment] 2021-02-07 03:43
> what the preceding meant

I meant that I had no idea that there are test builds, while you asked in the air that looked to me rather harsh. Anyhow, thank you for your help and quick response.
