### ISSUE TITLE
Wiki account creation disabled

### ISSUE THREAD

**Issue by dprodanov** [notepad-plus-plus/notepad-plus-plus#3540] opened 2017-07-18 16:17 UTC
Wiki account creation is disabled. Since there is no contact information in the web-site I write here. 

### Description of the Issue
It is impossible to create a new user account for the Wiki.

### Steps to Reproduce the Issue
1.  The help login page points to Wikimedia site and not the the wiki of Notepad++

**Comment by DavidHansen-0x454d43** [comment] 2017-10-11 20:50
This seems to be a duplicate of #1396.

**Comment by ArkadiuszMichalski** [comment] 2020-09-15 15:00
@sasumner Should not be close due NpWiki++ was closed?

**Closed** 2020-09-15 15:13 UTC
