### ISSUE TITLE
Document List panel is not displayed when new instance is run

### ISSUE THREAD

**Issue by voronovmaksim** [notepad-plus-plus/notepad-plus-plus#9710] opened 2021-03-28 12:59 UTC
### Description of the Issue
Document List panel a.k.a doc switcher is not displayed when new instance is run

### Steps to Reproduce the Issue

1. Enable document list panel (Doc panel is displayed in main instance)
2. Run second instance (alt + f6 or just clcik by icon of npp if multi-instance = always in multi-instance mode)

### Expected Behavior
Doc switcher is dispalyed

### Actual Behavior
Doc switcher is not dispalyed. 

I am forced  to go to Preferences->general->Document list panel->show is enable in otder to display it in new instance of npp.

win10 64bit, 7.9.5 version is used.

**Comment by dinkumoil** [comment] 2021-05-02 17:42
This issue has not only impact on `Document List` panel, **ALL** docked side panels are affected. Thus, multi instance mode is not usable anymore.

This is how Notepad++ v7.9.5 looks when only **one** instance is running:
![grafik](https://user-images.githubusercontent.com/24699812/116822227-eff4ed80-ab7d-11eb-9723-7955a166461e.png)

This is how it looks when it is started as **additional** instance (it makes no difference if the already running instance is also v7.9.5 or a much older one, e.g. v7.5.6):
![grafik](https://user-images.githubusercontent.com/24699812/116822238-08fd9e80-ab7e-11eb-9d73-2bff43caaf9c.png)

**Comment by Panzerbjrn** [comment] 2021-07-13 08:40
Is this something that is being worked on? It is a really annoying bug in an otherwise great product....

**Comment by ArkadiuszMichalski** [comment] 2021-07-14 10:40
Try run another instance with `-multiInst` argument. These Notepad++ commands which you mention probably use `-nosession`, and it closes all panels (see https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9487).

**Comment by Panzerbjrn** [comment] 2021-07-14 10:51
> Try run another instance with `-multiInst` argument. These Notepad++ commands which you mention probably use `-nosession`, and it closes all panels (see #9487).

Sadly, that gives me the error:  "C:\Program Files (x86)\Notepad++\-multiinst" doesn't exist. Create it?
![image](https://user-images.githubusercontent.com/10132417/125609922-14c0f1a9-0c9a-4a31-9d34-148e02b2ef0c.png)

That's from a command line. I don't see an option for this when rightclicking a file in the Document List, and choosing "Open in New Instance":
![image](https://user-images.githubusercontent.com/10132417/125610193-ef2f909b-89cc-4de8-b368-52c2b7dc610d.png)

**Comment by ArkadiuszMichalski** [comment] 2021-07-14 10:53
Use correct command: `"C:\Program Files (x86)\Notepad++\notepad++.exe" -multiinst`.

**Comment by Panzerbjrn** [comment] 2021-07-14 10:56
> Use correct command: `"C:\Program Files (x86)\Notepad++\notepad++.exe" -multiInst`.

That still give that same error.
Even if it worked, it still wouldn't be a fix to opening a file in a new instance by right clicking as described above.

**Comment by ArkadiuszMichalski** [comment] 2021-07-14 11:06
So add your own Run command: 
`"C:\Program Files (x86)\Notepad++\notepad++.exe" -multiInst "$(FULL_CURRENT_PATH)"`.

**Comment by Panzerbjrn** [comment] 2021-07-14 11:08
I don't know what you mean by that?

**Comment by MikeRena77** [comment] 2021-07-14 16:01
Running the 64 bit 8.1.1 from the command-line with -multiInst still
results in Notepad++ without persisting the Document List Panel.

After Notepad++ had opened, I still had to go through Settings =>
Preferences in order to open the Document List Panel.

**Comment by dhurd-c4h** [comment] 2021-08-21 15:26
This is EXTREMELY ANNOYING and simply wish Notepad++ would fix this PERIOD!!

**Comment by arfmach** [comment] 2021-09-14 14:32
With version 8.1.4, even running with mono-instance, the Document List panel doesn't keep open when closing and reopening N++. It didn't happen in a prior version (I don't remember what was the version I had when I updated to 8.1.4, but it was a recent version).

**Comment by Sc0tTyXL** [comment] 2021-09-21 13:00
I've been having issues the doc switcher not showing up in other sessions. I just updated to 8.1.4 in the hope it would be fixed. But now its worse. The option is now gone in the settings and now I can't even manually re-enable it!
![image](https://user-images.githubusercontent.com/24222938/134174934-c115ef06-4743-4642-9f83-24da419f5756.png)

**Comment by pryrt** [comment] 2021-11-09 14:00
@Sc0tTyXL ,
> The option is now gone in the settings and now I can't even manually re-enable it!

Because it's now in the View menu, like all the other panels, rather than hidden in an option screen somewhere.

**Comment by MWillberg** [comment] 2021-11-09 14:01
My take on this issue... All versions mentioned here are portable ones and saving settings works ok.

Clean installation and settings
- Set preferences / Multi Instance = Always in multi-instance mode
- View / Function List = Enable

Launch 8.1.9 exe
- Application windows opens and function list is visible
- Keep application window open

Launch 8.1.9 exe again

- Application window opens and fuction list is not visible

The last version in which this works ok is 7.9.1 so I suspect that the fix 8005 for 7.9.2 has broken this functionality:

[Folder as Workspace panel opened even with “-nosession” #8005](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8005)

I want to have the “document list” visible, but “function list” is used in this example as the settings is in the same place across versions.

**Comment by CmsWares** [comment] 2022-01-17 08:38
Confirming the following observations on the current version:

1. If I set Notepad++ to "Always in multi-instance", 
1.1 The first instance opens with any panels open (as I left it), and subsequent instances open "blank".
1.2 Same behavior with "Move to/Open in new instance"
1.3 Same behavior if I open ```notepad++.exe -multiInst``` from the command line.

However:

2. If I set Notepad++ to "Mono-instance",
2.1 & 2.2 as above;
2.3 A replica of the first instance (panels and files) is opened, reflecting the state when NP++ was first opened (ie. any added/deleted files or opened/closed panels are not replicated)

And further,

When I close all instances and open a new instance, it replicates the last-closed instance (expected behavior?). As memory serves, at some earlier version the panels were retained. It would be nice if the new instance could replicate the current panel setup of the instance from which it's opened.

**Comment by HolterPhylo** [comment] 2022-02-14 21:45
> Confirming the following observations on the current version:
> 
> 1. If I set Notepad++ to "Always in multi-instance",
>    1.1 The first instance opens with any panels open (as I left it), and subsequent instances open "blank".
>    1.2 Same behavior with "Move to/Open in new instance"
>    1.3 Same behavior if I open `notepad++.exe -multiInst` from the command line.
> 
> However:
> 
> 2. If I set Notepad++ to "Mono-instance",
>    2.1 & 2.2 as above;
>    2.3 A replica of the first instance (panels and files) is opened, reflecting the state when NP++ was first opened (ie. any added/deleted files or opened/closed panels are not replicated)
> 
> And further,
> 
> When I close all instances and open a new instance, it replicates the state of the last-closed instance (expected behavior?).
> 
> It would be nice if new instances could replicate the _current panel setup_ of the instance from which it's opened, assumption being I'd like to continue in the same workflow, rather than replicate a "historical state".

Completely agree with this ^

**Comment by pryrt** [comment] 2022-06-23 19:09
@donho, I see that you had self-assigned this some months back.  I am hoping that this hasn't been lost.

[it was recently reported in the Forum](https://community.notepad-plus-plus.org/topic/23152/please-add-show-document-list-back-to-preferences-instead-of-view-menu-only/), and I (having forgot about this issue) did some debug to figure out a set of instructions that showed the problem that the OP in the Forum was having:

0. Unzip a fresh portable v8.4.2
1. Only one instance open of Notepad++, from the portable v8.4.2 directory
2. Open `change.log` and `license.txt` (closing anything else first)
3. **File > Save Session...** => `main.sess`
4. **File > Close All**
5. **Settings > Preferences > Multi-Instance & Date > Multi-Instance** = **Open Session in new instance**
6.  **View > Document List** turned on
7. Open `readme.txt`
8. Exit Notepad++ and restart
9. At this point, the Document List is still visible, so the setting is correctly saved and applied
10. **File > Load Session...** => pick `main.sess`
11. It opens `change.log` and `license.txt` in a second Notepad++ instance, _but this instance does **not** have Document List visible_
12. Exit the second instance of Notepad++
13. Exit the first instance of Notepad++
14. Restart Notepad++ to prove that **Document List** is still visible, which proves that the setting is still in effect

And I concur that this breaks expectation.  The Document List panel is correctly set in the config.xml to be on, and it is on for the first instance of notepad++.exe run.  But if you open a session in the **Open Session in new instance** mode, the new instance launched does _not_ have the Document List panel -- even though both the config.xml settings and the currently-active Notepad++ window both have Document List panel turned on.  Opening a new instance should inherit at least all the settings from config.xml, and maybe even all the settings that have been changed-but-not-saved in the active Notepad++.

```
Notepad++ v8.4.2   (64-bit)
Build time : May 29 2022 - 16:47:30
Path : C:\usr\local\apps\npp\npp.8.4.2.portable.x64\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 20H2
OS Build : 19042.1586
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
```

**Comment by dinkumoil** [comment] 2022-06-24 07:34
@pryrt , @donho 

It doesn't matter whether a session is opened or if sessions are deactivated and _Notepad++_ starts up with no documents opened at all. It is even not necessary that you launch two instances of the same version of _Notepad++_. For example:

1. Launch _Notepad++_ newer than v7.9.1. Deactivate sessions, set it up to multi-instance mode and open _Document List_ or _Function List_ panel. But you could open any other docking panel (like _Folder as Workspace_ or _Projects_). You could even open a docking panel of any plugin, e.g. _Explorer_ plugin. The only prerequisite that has to be fullfilled is that it must be a panel whose display state is saved to some kind of config file, thus it will be shown the next time _Notepad++_ is launched.
2. Close the _Notepad++_ instance launched in step 1. => The config file will be saved.
3. Launch again the _Notepad++_ version of step 1. => The panel(s) you opened in step 1 will be displayed.
4. Close the _Notepad++_ instance launched in step 3.
5. Launch an instance of another version of _Notepad++_. It can be a much older version, for example v7.5.6.
6. Launch again the _Notepad++_ version of step 1. => None of the panel(s) you opened in step 1 will be displayed.
7. Close both instances of _Notepad++_.
8. Launch again the _Notepad++_ version of step 1. => The panel(s) you opened in step 1 will be displayed, i.e. the config file is valid and still contains the settings that have been saved in step 2.

If you do this test with _Notepad++_ v7.9.1 or older, in step 6 all the panels you opened in step 1 will be displayed.

**Comment by marieve** [comment] 2022-10-03 20:51
This bothering me since months! I work with one instance per client per project, so each time I open a project, I have to go click in menus to open the 4 panels i'm woking with (documents list, etc.). I would really love that it comes back like before: every instance opens with the panels that where opened in the previous instance. I now have v8.4.5. I wish with every update that it'll come back as before. I tried to add "multiInst" in the shortcut, same problem. Is there a problem with my installation of Notepad++ or the software is not working like that anymore and will not come back the way it worked before?

**Comment by xaminmo** [comment] 2022-12-01 16:38
Note that this also affects minimize-to-tray.  I have a plain install.  If NP++ is minimized to tray, and a new document is opened from explorer integration, the single instance is brought back to the screen with the document list closed.  In the view menu, document list is still listed as enabled.  I have to uncheck it then recheck it, which is 4 clicks in addition to the two to open the file.  Also, if the file was already opened in NP++, it opens a new copy instead of selecting the open copy.

If the instance is not minimized, then opening new documents is fine, and it properly selects the open copy.

All of the registry entries use:

   "C:\Program Files (x86)\Notepad++\notepad++.exe" "%1"

It seems that when opening windows, that NP++ does not check for the config of an existing session, and reverts some settings back to application defaults.  Hypothesis here.  I don't have traces / etc.

**Closed** 2022-12-30 19:08 UTC
Labels: bug
