### ISSUE TITLE
Are there any plans to support the goalng language highlighting?

### ISSUE THREAD

**Issue by chuyangyang** [notepad-plus-plus/notepad-plus-plus#3330] opened 2017-05-30 11:16 UTC
<h1>Are there any plans to support the goalng language highlighting?

**Comment by redmanmale** [comment] 2017-06-07 10:03
@chuyangyang 
Highlighting support for all languages are provided by Scintilla.
And since Scintilla devs [refuse to implement it](https://sourceforge.net/p/scintilla/feature-requests/750) the only way is to write your own custom language definition and submit it.

**Comment by ArkadiuszMichalski** [comment] 2020-09-20 14:05
@donho @sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8090, maybe close this because of the short description and leaving only the newer one.

**Comment by sasumner** [comment] 2020-09-20 14:38
Closing by suggestion

**Closed by sasumner** 2020-09-20 14:38 UTC
