### ISSUE TITLE
Javascript is listed twice in the Available Languages Settings

### ISSUE THREAD

**Issue by wadevelopers** [notepad-plus-plus/notepad-plus-plus#11955] opened 2022-07-31 01:41 UTC
### Description of the Issue
I have version 8.4.4 and Javascript is listed twice in the Available Languages Settings

### Steps to Reproduce the Issue
1.  Go to Settings -> Preferences > Languages
2. In the Available Items, Javascript is listed twice 

### Expected Behavior
Javascript like any other language should only be listed one time

### Actual Behavior
Javascript is listed twice

**Comment by ArkadiuszMichalski** [comment] 2022-07-31 01:48
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4521.

**Closed by ArkadiuszMichalski** 2022-07-31 01:48 UTC
