### ISSUE TITLE
[Feature Request] Document Switcher Reordering/Pinning

### ISSUE THREAD

**Issue by Andronomos** [notepad-plus-plus/notepad-plus-plus#4015] opened 2017-12-20 23:47 UTC
I would like to request the ability to reorder/pin documents in the document switcher. As a web developer/programmer on a normal day I can have 30+ files open. It's very frustrating when I've memorized the locations of documents in the list only to accidentally on the click doc switch title bar and have them all be reordered.

Having the ability to pin a document in place or be able to re order them by dragging would greatly enhance my productivity and lower my frustration while working in Notepad++.

**Comment by nebosite** [comment] 2018-01-09 17:21
+1

I use the switcher to manage the 20+ documents I have open and position is important to me.

**Comment by nebosite** [comment] 2018-01-09 17:24
Duplicate of: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1684

**Closed** 2018-02-19 22:48 UTC
