### ISSUE TITLE
Language list in Style Configurator is not sorted for all themes

### ISSUE THREAD

**Issue by sirzooro** [notepad-plus-plus/notepad-plus-plus#1989] opened 2016-06-21 12:58 UTC
Language list in Style Configurator is not sorted, please sort it alphabetically.

N++ 6.9.2, windows

**Comment by dail8859** [comment] 2016-06-22 23:10
It is in alphabetical order other than "Global Styles" at the beginning and "Search Results" at the end.

**Comment by sirzooro** [comment] 2016-06-23 10:16
For some reason they are not sorted on my PC:

![styles](https://cloud.githubusercontent.com/assets/1969912/16299768/3b43a970-393c-11e6-9bf2-0dc7d1feca77.jpg)

**Comment by sirzooro** [comment] 2016-06-23 10:28
I just restarted N++ and list is sorted now. Strange.

**Comment by dail8859** [comment] 2016-07-04 13:05
Closing for now. If you find there is some way to reproduce the issue feel free to reopen with any additional information.

**Comment by sirzooro** [comment] 2016-07-05 10:12
I found one thing - when I scrolled theme list dropdown with mouse scroll, I found that for some of them list is sorted, while for other don't - it looks as on screenshot added earlier.

I also noticed that sorted list is not completely sorted - Javascript, JSON and Fortran(fixed) are below "Search result" at the end.

How can I open this ticker? I do not see any "Reopen" button or something like this.

**Comment by dail8859** [comment] 2016-07-05 13:11
Reopening since some themes (e.g. Monokai) is not sorted.

**Comment by MetaChuh** [comment] 2019-04-24 18:22
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-24 18:22 UTC
