### ISSUE TITLE
Built-in syntax highlight for Shell files fails on double+single-quoted dollar sign " ' $ ' "

### ISSUE THREAD

**Issue by ethsol** [notepad-plus-plus/notepad-plus-plus#13911] opened 2023-07-20 11:30 UTC
### Description of the Issue
Built-in syntax highlight for Shell files fails on double+single-quoted dollar sign " ' $ ' "

### Steps to Reproduce the Issue

1. Create a new text file
2. Set language to Shell
3. Paste the following:

```
#Notepad++ 8.5.4 syntax highlight fault
#Language / S / Shell

#search for files not ending with LineFeed
fd . /root/scripts/ -t f -x sh -c "if tail -c1 {} | hexdump -c | head -1 | grep -v '\\n *$' ; then echo -e {}\\\n; fi"
echo FAULTY
echo " ' " REPAIR MAGIC

echo " $ " GOOD
echo ' $ ' GOOD
echo ' " $ "' GOOD

echo " ' $' " FAULTY
echo " ' " REPAIR MAGIC

for i in /*; do echo $i; done
```

### Expected Behavior
All echo statements should be coloured equally

### Actual Behavior
The two lines marked with FAULTY break the syntax highlight, the following content is colored like a string, until the REPAIR MAGIC lines correct it.

<img width="539" alt="2023-07-20_13_26_48-_uj 1 - Notepad++" src="https://github.com/notepad-plus-plus/notepad-plus-plus/assets/16744273/3492f62b-13b9-4272-8864-7b976eda90e0">

### Debug Information

> Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.2965
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment] 2023-07-20 17:47
Duplicate of ScintillaOrg/lexilla#180, which is [now fixed][0].

![npp-13911-patched](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/59004801/db74188b-3db5-4fb9-bca4-c7b9af34d52e)

Notepad++ still has t oupgrade to the next Lexilla version, whenever it gets releasd.

[0]: https://github.com/ScintillaOrg/lexilla/commit/5f0c21517fa71a2f00c29fd5997538aed051c42c

**Comment by ethsol** [comment] 2023-07-24 06:06
Good news, thanks

**Closed** 2023-08-01 17:46 UTC
