### ISSUE TITLE
Session file gets emptied without having changed anything

### ISSUE THREAD

**Issue by santinoscripts** [notepad-plus-plus/notepad-plus-plus#10986] opened 2022-01-02 20:42 UTC
### Description of the Issue

The session file that Notepad++ can use to _remember_ opened files gets reset to an empty template after opening and closing one. This behaviour never happened before.

### Steps to Reproduce the Issue

1. Open a previously saved session file (with some tabs and such) using Notepad++ 8.2.
2. The files get opened in their tabs as usual.
3. Close Notepad++.

### Expected Behavior

The file should be untouched. Notepad++ 8.1.9.3 doesn't have this problem.

### Actual Behavior

The session file is clean except some markup lines.

### Debug Information

This is the content of the emptied session file:

`<?xml version="1.0" encoding="UTF-8" ?>
<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="0" />
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>`

**Comment by xomx** [comment] 2022-01-02 22:40
You probably forget one step between your 2. and 3. - close some or all the opened session tabs (?)
If so and your N++ Preferences setting is the same as on the pic below, you are experiencing a desired change in the session handling (saving session automatically at exit).
![session_autosave](https://user-images.githubusercontent.com/13075183/147891174-674f39e4-74b4-4f08-ab8e-438ecc369ff2.png)

**Comment by donho** [comment] 2022-01-06 15:33
I believe it's yet a PEBKAC. Issue closed.

**Comment by santinoscripts** [comment] 2022-01-06 17:42
Tested again with a new untouched Notepad++ v8.2 installation. Still happening. My guess is that the issue is with the `-openSession` command line parameter. Again, v8.1.9.3 doesn't have this problem.

You should be more professional (and polite) and test the software instead of plainly disregard user bug reports.

**Comment by alankilborn** [comment] 2022-01-06 18:04
>My guess is that the issue is with the -openSession command line parameter

How come you didn't mention `-openSession` in the original complaint?

**Comment by xomx** [comment] 2022-01-06 18:16
Even if I re-test your steps while opening N++ with a 'notepad++.exe -openSession C:\TEMP\NPP\session.xml', my  session.xml file remains untouched (it is not emptied). But when I have ON the preference from the pic above and I close all my opened session tabs before I close N++, my session.xml file gets emptied (which is ok from version 8.2+).

**Comment by donho** [comment] 2022-01-07 03:37
@santinoscripts 
Using `-openSession` doesn't make it work even you set "Open session in a new instance" .
You have to open a session file via an instance of Notepad++, then the session will be in a new instance, and it will be saved automatically on exit of this instance.

**Comment by donho** [comment] 2022-01-07 04:01
@santinoscripts 
In v8.2, if you doesn't set Multi-Instance settings to "Default (Mono-instance)", then the session will be saved automatically on exit of current instance. It's a session enhancement in v8.2

**Comment by aleyvo** [comment] 2022-01-09 16:42
I am experiencing this very same issue, as @santinoscripts described.
Based on @santinoscripts's descriptions and based on my own experience:

### Steps to reproduce the issue:

1. Open an untouched instance of Notepad++ 8.2 (I've downloaded and used **npp.8.2.portable.x64.7z**);
2. Go to **Settings** > **Preferences**:
2.1. Go to **Backup**, and untick **Remember current session for next launch**;
2.2. Go to **Multi-Instance & Date**, and choose **Always in multi-instance mode** or **Open session in a new instance**;
3. Restart Notepad++ 8.2;
4. Go to **File** > **Load Session...**;
5. Choose any previously saved _session file_ (FYI, I've associated the extension **.npps** to my _session files_);
6. The session is opened as expected, with all its tabs/files open and the cursor located where it should be;
7. Close Notepad++ 8.2, without making any changes to the current session (i.e., the very same tabs/files are open and unchanged, and the cursor is also unchanged when I close the application);
8. Repeat **Step 4**.
9. Choose the same _session file_, as chosen in **Step 5**.

### Expected behavior:
The session should persist, in the same state as it was before closing Notepad++ 8.2 in the **Step 7**.

### Actual behavior
The session is not retrieved, no tabs are open (i.e., I get an empty session). The contents of my **.npps** _session file_ are lost.
Up until Notepad++ 8.1.9.3, this problem did not occur.

**Comment by xomx** [comment] 2022-01-09 17:44
Ok, now we got somewhere, I can reproduce that.

**Comment by donho** [comment] 2022-01-09 19:23
@aleyvo @xomx 
I still cannot reproduce...

**Comment by donho** [comment] 2022-01-09 19:37
OK, I miss read, with the following settings :
Remember current session for next launch : OFF
Open session in a new instance: ON

I can reproduce now.

**Comment by donho** [comment] 2022-01-09 19:39
@santinoscripts 
The PEBKAC. Issue still exist, but it's me.
I owe you an apology.  
Issue reopened.

**Comment by donho** [comment] 2022-01-09 19:42
@xomx 
Do you want to work on the PR to solve it?

**Comment by xomx** [comment] 2022-01-09 19:45
@donho 
Not this time, thanks, I have to go.

**Comment by donho** [comment] 2022-01-09 19:47
No problem.
I will do it. Thank you for testing and pointing out the error of code.

**Comment by santinoscripts** [comment] 2022-01-10 08:05
> @santinoscripts The PEBKAC. Issue still exists, but it's me. I owe you an apology. Issue reopened.

So glad I could be of help.
Can't wait to use v8.2. :)

**Closed** 2022-01-10 14:06 UTC
Labels: accepted
