### ISSUE TITLE
Bottom of sliders is cut off

### ISSUE THREAD

**Issue by scootergrisen** [notepad-plus-plus/notepad-plus-plus#616] opened 2015-07-31 19:21 UTC
Inside Preferences windows in Editing there are two sliders for blink rate and border width.
The bottom of these slider are cut off by maybe 3 pixels.

There is a small difference depending if you use the Windows 7 Classic Theme or the Basic Theme, so it more noticeable with Classic Theme.

**Comment by scootergrisen** [comment] 2015-07-31 19:27
![sliderscutoff](https://cloud.githubusercontent.com/assets/1836590/9015698/f58fa492-37ca-11e5-93c9-52e110a2fdcc.png)

**Comment by Rikk** [comment] 2015-07-31 20:34
Are you using non-default DPI?

**Comment by scootergrisen** [comment] 2015-07-31 20:45
Windows 7 is set to use standard 96 dpi (100%) in controlpanel screen settings.

**Comment by Rikk** [comment] 2015-08-01 02:06
I can confirm with Windows 7 Classic Theme (not with the Basic which looks the same as Aero)...
One workaround for you (keeping performance), is to disable Themes Service while you are using Aero or Basic, it will revert to a theme something between Classic and Basic.

**Comment by scootergrisen** [comment] 2015-08-01 02:45
It seems the square part the you slide is small with Aero and Basic theme, but big with Classic theme.

![aerobasic_normal](https://cloud.githubusercontent.com/assets/1836590/9020363/e6e718a2-3807-11e5-8f40-929d39142555.png)

But if Notepad++ is open and i'm using Aero/Basic theme, then switch to Classic theme, the square bit keeps to same small size, until i restart Notepad++, then it goes back to the big square.

![classic_type2](https://cloud.githubusercontent.com/assets/1836590/9020361/e6bc0f68-3807-11e5-9cc3-8624f0fb435b.png)

Same thing the other way around if i start Notepad++ during Classic theme, i have the big square, then if i switch to Aero/Basic theme it keeps the big square size (with bottom cut off), until i restart Notepad++.

![aerobasic_type2](https://cloud.githubusercontent.com/assets/1836590/9020362/e6d54596-3807-11e5-98ae-7c2d80535294.png)

**Comment by MetaChuh** [comment] 2019-04-09 22:58
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 22:58 UTC

**Comment by scootergrisen** [comment] 2019-04-09 23:05
Still the same in 7.6.6.
Why file a new issue?
All the info is already here.
