### ISSUE TITLE
Bash language formatting broken in 8.5.4

### ISSUE THREAD

**Issue by rinaldsb** [notepad-plus-plus/notepad-plus-plus#13943] opened 2023-07-28 11:25 UTC
### Description of the Issue
Bash langugage formatting for the following code in versions 8.5.3 works and is broken in version 8.5.4:
```
#!/usr/bin/bash 
# $ and " together makes bash language unreadable for v>8.5.3

# Block 1 
echo "Block 1"

mkdir -p ~/tmp/Config-$(date '+%Y%m%d')
echo ~/tmp/Config-$(date '+%Y%m%d')

# Block 2
echo "Block 2 $" # makes bug v>8.5.3

mkdir -p ~/tmp/Config-$(date '+%Y%m%d')
echo ~/tmp/Config-$(date '+%Y%m%d')

# "" : resetting the bug v>8.5.3

# Block 3 

echo "Block 3 $" # makes bug v>8.5.3

mkdir -p ~/tmp/Config-$(date '+%Y%m%d')
echo ~/tmp/Config-$(date '+%Y%m%d')

# Block 4 

# "" : resetting the bug v>8.5.3

echo "Block 4"

mkdir -p ~/tmp/Config-$(date '+%Y%m%d')
echo ~/tmp/Config-$(date '+%Y%m%d')
```

### Expected Behavior / Actual Behavior

Attaching screenshots of formatted code in v 8.5.3 (Expected) and 8.5.4 (Broken)

![Bash formatting bug](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/57134884/5cc6e7c9-36da-44c2-93bf-492fd5fae885)

**Comment by rdipardo** [comment] 2023-07-28 17:44
Duplicate of #13911

The next version of N++ will fix it

**Closed** 2023-08-01 17:46 UTC
