### ISSUE TITLE
Other instances of the selected text is not being highlighted when selecting some text at EOF

### ISSUE THREAD

**Issue by nikunjbhatt** [notepad-plus-plus/notepad-plus-plus#8908] opened 2020-09-26 21:22 UTC
### Description of the Issue
If some text is selected which is at the end of file (no character (including space/new line/tab) after the selected text) then the other instances of the same text is not being highlighted.

### Steps to Reproduce the Issue
1. I have these settings in Smart Highlighting:

- "Enable" **is** checked (Smart Highlighting is enabled)
- "Match case" is **not** checked
- "Match whole word only" is **not** checked

2. Write the following 2 lines in a blank file. Do not add any character after last "hello"
`hello`
`hello`

3. Select the second/last "hello" text

### Expected Behavior
The first "hello" should get highlighted.

### Actual Behavior
The first "hello" is not getting highlighted.

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : Z:\home\U\Programs\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Microsoft Windows 7 (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
WINE : 5.17
Plugins : BetterMultiSelection.dll ComparePlugin.dll DSpellCheck.dll Explorer.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll zoomdisabler_x64.dll 

### More info
If there is any character after last "hello" then the highlighting is working properly.
And, if the first "hello" is selected then the second instance is highlighted.

**Comment by sasumner** [comment] 2020-09-26 23:55
Duplicate of #4508 ?

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 00:15
No, this is funny, when you select second word (char by char), first also get highlighting, but after select all chars in hello (without EOL) first hello loses highlighting.

**Comment by nikunjbhatt** [comment] 2020-09-27 09:40
@sasumner @ArkadiuszMichalski 
CR and/or LF is included in the issue 4508, but I am not talking about selecting CR/LF in this issue. I don't know if internally both issues are same or different.

**Comment by nikunjbhatt** [comment] 2020-09-27 09:47
@ArkadiuszMichalski 
I think you referenced/mentioned wrong issue. Same/similar issue is #6280.

I just found that that issue's creator used the same word "hello" for posting the issue! Coincidence!

**Comment by ArkadiuszMichalski** [comment] 2020-09-27 09:48
@nikunjbhatt Sure, but both have same problem with highlighting, basically same problem, because your bug not occure in 7.5.3 (and older).

**Closed** 2020-10-03 02:10 UTC
Labels: verified
