### ISSUE TITLE
[BUG]  Find in Files: all fields highlighted

### ISSUE THREAD

**Issue by StijnBousard** [notepad-plus-plus/notepad-plus-plus#15584] opened 2024-08-27 19:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

In the latest version of Notepad++ (v8.6.9), when I open the “Find in Files” dialog box, the text in all fields is highlighted, instead of only the text of the active field
Example:
![1724763350241-findinfiles](https://github.com/user-attachments/assets/031a9a66-c2e4-406c-b0f0-bbbfd63dbba9)

Apparantly, it only happens the first time you open Notepad++.

When you start typing, only the text in ‘Find what’ is replaced, but the other fields remain highlighted. Once you enter the other fields and start typing, the text is also overwritten and the accessed fields that are already overwritten, are no longer highlighted. Also not when you close and re-open the dialog.

They are highlighted again when you leave and reopen Notepad++.

For the rest, the Find dialog functions as before, there is no impact on the way the dialog works.

Thanks already to all those that have already done some research into this issue.

I first created a topic in the Notepad++ community, where some people have already done some research: see [the topic here](https://community.notepad-plus-plus.org/topic/26053/find-in-files-all-fields-highlighted/11), and they suggested that I'd create this bug report.

Thanks in advance to investigate this issue and keep up the good work!

### Steps To Reproduce

1.  Open Notepad++
2.  In the Search menu, choose Find in files...

### Current Behavior

The Find in files dialog is opened and all fields that were/are filled in, are highlighted.

When you start typing, only the text in ‘Find what’ is replaced (you see the cursor is blinking there), but the other fields remain highlighted. Once you enter the other fields and start typing, the text is also overwritten and the accessed fields that are already overwritten, are no longer highlighted. Also not when you close and re-open the dialog.

They are highlighted again when you leave and reopen Notepad++.

### Expected Behavior

The Find in files dialog opens and only the 'Find what' field (where the cursor blinks) is highlighted.

All other fields that were/are filled, must not be highlighted.

### Debug Information

```shell
Notepad++ v8.6.9   (64-bit)
Build time : Jul 12 2024 - 05:09:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit)
OS Version : 23H2
OS Build : 22631.4037
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
```

### Anything else?

Here is a link to the topic I first created in the Notepad++ community, where some people have already done some research: [Find in Files: all fields highlighted](https://community.notepad-plus-plus.org/topic/26053/find-in-files-all-fields-highlighted/11), and they suggested that I'd create this bug report.

**Comment by alankilborn** [comment] 2024-08-27 20:58
Duplicate of #15583.  :-(

**Comment by pryrt** [comment] 2024-08-27 21:12
Apparently didn't see that I'd already submitted it.  I'll close this one, since the "steps to reproduce" are rather under-explained in this one.

**Closed by pryrt** 2024-08-27 21:12 UTC
