### ISSUE TITLE
Open files cannot be re-arranged

### ISSUE THREAD

**Issue by gtriant** [notepad-plus-plus/notepad-plus-plus#3108] opened 2017-03-29 09:10 UTC
### Description of the Issue

From the open files/tabs section when trying to re-arrange the open files nothing happens. The tabs do not move as they used to. For example when trying to put two open files next to each other to compare them.

### Steps to Reproduce the Issue

1. Open three or more files
2. Try to re-arrange the order
3. 

### Expected Behavior

Open files should be moveable and order should be re-arrange-able

### Actual Behavior

Open file-tabs do not move

### Debug Information

v7.3.3 32-bit build Mar 8 2017 - 03:37:37

**Comment by rddim** [comment] 2017-03-30 16:13
fixed in #3075

**Comment by Endor8** [comment] 2017-04-01 13:05
Since I have the same issue, where can I download the fixed version?

**Comment by AngryGamer** [comment] 2017-04-01 21:02
@Endor8 You can grab the binaries off Github's AppVeyor integration. They are here [x86](https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1097/job/ddqj0xyprys5io7o/artifacts) and [x64](https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1097/job/g89potc0fytk98dg/artifacts). Don't download that SciLexor since it doesn't have a signed certificate (the existing 7.3.3 one is fine).

**Comment by elijahgagne** [comment] 2017-04-04 14:18
Thanks. I can confirm that this fixed the issue for me.

**Comment by n-peugnet** [comment] 2017-04-08 09:53
thanks @AngryGamer this fixed it for me too

**Comment by MetaChuh** [comment] 2019-05-01 22:46
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:46 UTC
