### ISSUE TITLE
[BUG] hex plugin

### ISSUE THREAD

**Issue by TracyCurry** [notepad-plus-plus/notepad-plus-plus#15374] opened 2024-06-29 05:26 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Description of the Issue

I using hex plugin to view txt file in hex format and copy hex value 00, when i paste it shows 20. For other hex value like 7D, 07, 8E, it shows what i copy when pasting.

### Steps To Reproduce

1.  insert a hex value 00 (raw data)  in a txt file (probably could be any file format)
2.  open the file using notepad++ and view in hex format using the hex-plugin
3.  copy the value 00 then paste it somewhere else, and will find it show as 20 (ascii of space) not 00

### Current Behavior

copy 00 but show 20 when pasting in hex-view

### Expected Behavior

copy 00 and show 00 when pasting in hex-view

### Debug Information

```shell
none
```

**Comment by alankilborn** [comment] 2024-06-29 10:01
Plugins such as HexEditor are not supported by Notepad++ dev team.
Please find support site for this plugin and report problem there.

**Comment by ArkadiuszMichalski** [comment] 2024-07-08 12:40
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9289, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11003 and probably others. 

This applies to an external plugin that has its own repository and the issue should be reported there. However, for this one it already exist:
https://github.com/chcg/NPP_HexEdit/issues/22
https://github.com/chcg/NPP_HexEdit/issues/24

**Closed by ArkadiuszMichalski** 2024-07-08 12:40 UTC
