### ISSUE TITLE
Column Mode Corruption

### ISSUE THREAD

**Issue by FickoDeLux** [notepad-plus-plus/notepad-plus-plus#3483] opened 2017-07-04 10:19 UTC
How to reproduce:

Make a text file with the content of:

> 2014\0000001_10035_RG143390_27-08-2014

32974 times - 32974 Lines -

Mark all "2014\\" - 32974 lines - in Column Mode an press "Backspace" to delete the selected content - "2014\\".

It going to take a while and the resulted text will be heavily corrupted.

The corruption occurs on both x64 & x32 version.

**Comment by kkayal** [comment] 2017-07-05 13:26
Since I had similar problems, I tried to reproduce your case exactly. There was no problem. It seems, your file was not big enough to reproduce the massive corruption with my configuration.

So I have created a fresh new file, also with 32974 lines. However, I filled each line with 8 x "Lorem ipsum dolores."

Then I marked the first "ipsum" in all lines (using the mouse) and hit backspace **quickly**. Then I get massive corruption after line 10732.

The interresing part is, when I repeat the same test, but *wait ca. 3 seconds* after marking the column before I hit the backspace key, it works as expected without corruption. So it seems, when notepad++ shows the whole column as marked, it is actually not necessarily finished with marking it in its *"mind"*.

My config:

Notepad++ v7.3.2   (32-bit)
Build time : Feb 12 2017 - 23:15:39
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ccc.dll CodeAlignmentNpp.dll FingerText.dll HTMLTag_unicode.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll PoorMansTSqlFormatterNppPlugin.dll SpellChecker.dll sql.dll Tidy2.dll XMLTools.dll

**Comment by alankilborn** [comment] 2022-08-03 14:03
Attaching file for those that want to try reproducing @kkayal 's results.
[32974.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/9252017/32974.txt)

**Comment by alankilborn** [comment] 2022-08-03 14:09
I could NOT reproduce @kkayal 's bad results in N++ 8.4.4 (current version as of this writing).

However, I did not do it this way:

>I marked the first "ipsum" in all lines (using the mouse)

Because such a selection over a large number of lines would take an extremely long time to create.

I used the "Begin/End Select" feature to create the column mode block on the word `ipsum` on all lines:
* click before the `i` in `ipsum` on line 1
* invoke "Edit" > "Begin/End Select"
* move to last line of file
* alt+click after the `m` in `ipsum` on that last line
* invoke "Edit" > "Begin/End Select"

**Comment by donho** [comment] 2024-07-24 17:10
I use @alankilborn 's 32974.txt to have 32974 lines of `2014\0000001_10035_RG143390_27-08-2014` thanks to "Begin/end selection in column mode" (BTW, its indeed a good feature ;) ).
However, I cannot reproduce the corruption by removing the column `2014\`.
I guess the issue has been fixed by updated Scintilla.

**Closed by donho** 2024-07-24 17:10 UTC
