### ISSUE TITLE
removing recent file from the Notepadd++ Icon when right-clicking it 

### ISSUE THREAD

**Issue by Rat-7** [notepad-plus-plus/notepad-plus-plus#14825] opened 2024-03-02 23:44 UTC
removing recent file from the Notepadd++ Icon when right-clicking it

**Comment by molsonkiko** [comment] 2024-03-04 21:35
Nobody will help you unless you explain what you want in more detail. Pay attention to the guidelines for writing an issue.

**Comment by Rat-7** [comment] 2024-03-04 21:40
when you right-click on the icon that is in the taskbar, there a list of recent files, but for some reason I have 3 old files, that are stuck there, they are not PINned to the list, I can not remove them

**Comment by molsonkiko** [comment] 2024-03-05 11:39
@Rat-7
Did you think that repeatedly closing and reopening this issue would make me more interested in helping you? Really mature. Let me know when your childish behavior brings you joy and success.

Oh wait, I'll never know because I'm unsubscribing from this issue and making a note not to waste my time on you ever again.

**Comment by Rat-7** [comment] 2024-03-05 11:57
Sorry my cats were accidentally pressing the keys

**Comment by molsonkiko** [comment] 2024-03-09 19:11
Could you share debug info (`?->Debug info...` from the Notepad++ main menu) so that I have a better sense of context?

Has this always been a problem, or did it start when you updated Notepad++? If so, what version of Notepad++ did it start with?

**Comment by Rat-7** [comment] 2024-03-09 19:23
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : D:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\Users\Racette\OneDrive\Documents
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.3155
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

it started about a year ago, and was always hoping that with new update it would be fix, but it seems that is not going away so far

**Comment by molsonkiko** [comment] 2024-03-12 16:27
Are you referring to the list I circled in this image?

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/46202915/57ecc28e-2d84-413a-bf7a-69de6525d73c)

In any case, I notice that you have a Cloud Config set up. Maybe the issue is related to you using files on your OneDrive?

**Comment by Rat-7** [comment] 2024-03-12 21:05
No it is not what I was refering to
What I am talking about is when you right-click the icon on the taskbar

I have no idea what this Cloud Config is, all I did was install Notepad++, and use it to replace Notepad, I never touch the config

as for OneDrive I have it, but it does not move/copy anything to it, unless I do it manually, I prefer to keep my files on my computer, the only time I place something on OneDrive is because I may need to access it from another location (which is extremely rare)

**Comment by Rat-7** [comment] 2024-04-10 20:20
do you have any suggestion on how to fix the issue

**Comment by molsonkiko** [comment] 2024-04-10 20:32
@Rat-7 
I doubt I will be able to help you, but somebody *might* be able to help if you share an image rather than trying to describe your issue in writing.

**Comment by Rat-7** [comment] 2024-04-10 20:59
unfortunately, the list disappears as soon as you remove the mouse from it, ike any other program like the Office365 product that offer such a list

**Comment by Rat-7** [comment] 2024-04-10 20:59
unfortunately, the list disappear as soon as you remove the mouse from it, ike any other program like the Office365 product that offer such a list

**Comment by molsonkiko** [comment] 2024-04-10 21:01
I'm sorry, I can't help you. Maybe someone else will come along and propose a solution, but I give up, and am unsubscribing from this topic.

**Comment by xomx** [comment] 2024-04-10 22:32
https://www.youtube.com/watch?v=GAHr1B-OPoY

**Closed** 2024-06-15 03:21 UTC
