### ISSUE TITLE
Opening a blank file should use same encoding as for a new document 

### ISSUE THREAD

**Issue by raghvendrasingh92** [notepad-plus-plus/notepad-plus-plus#2339] opened 2016-09-26 03:29 UTC
Use case: I often create a new file by right-click in Windows Explorer, then open this file with Notepad++.

When creating a new file in Notepad++, it uses the New Document > Encoding preference (default UTF-8 w/o BOM).
Furthermore, if I open a file containing only ANSI characters, it uses UTF-8 as well.
BUT, if I open a blank file, it doesn't use UTF-8, but ANSI...
This is inconsistent and definitely has had caused me some troubleshooting headaches!

**Comment by dail8859** [comment] 2016-09-26 12:51
Duplicate of #1874

**Closed by dail8859** 2016-09-26 12:51 UTC
Labels: duplicate
