### ISSUE TITLE
NppShell_06.dll ShellExecute failed (2) only with 64 bit version

### ISSUE THREAD

**Issue by Fuzzo** [notepad-plus-plus/notepad-plus-plus#5189] opened 2019-01-02 15:15 UTC
### Description of the Issue

When using the shell extension "Edit with Notepad++" the "ShellExecute failed (2)" is displayed.
I tried the 32 bit installer and it works well.
Both tested version are 7.6.2.

### Steps to Reproduce the Issue

1. Install Notepad++ 64 bit with the installer
2. Right click on a text file and click on "Edit with Notepad++"

### Expected Behavior

The file is opened with 64 bit version as usual

### Actual Behavior

A popup window displays "ShellExecute failed (2): Is this command correct? "<C:\Program Files\Notepad++\notepad++.exe" "PATH_OF_OPENING_FILE"
Must use 32 bit version to make the shell extension works.

**Comment by AmbassadorLaZer** [comment] 2019-10-05 17:52
I'm also having the same problem.

**Comment by ArkadiuszMichalski** [comment] 2021-07-28 13:10
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2454. Follow the instruction included in previous issue.

**Closed by ArkadiuszMichalski** 2021-07-28 13:10 UTC
