### ISSUE TITLE
Perl parser does not work

### ISSUE THREAD

**Issue by wilkowy** [notepad-plus-plus/notepad-plus-plus#3180] opened 2017-04-18 15:52 UTC
There seems to be a problem with Perl parser used for "Function List" feature since version 7.3.2 - the FL window does not show any subs and remains empty (most likely bug in regex).

Using parser code from 7.3.1 version (only "perl_function" parser from functionList.xml) solves the problem.

N++ 7.3.3 // WinXP 32b SP3

**Comment by MAPJe71** [comment] 2017-04-18 20:55
Duplicate of #2963, see also #2964.

**Comment by MetaChuh** [comment] 2019-05-17 20:58
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-17 20:58 UTC
