### ISSUE TITLE
Error with Drag and Drop.

### ISSUE THREAD

**Issue by davidmachadoSP** [notepad-plus-plus/notepad-plus-plus#1929] opened 2016-06-04 18:55 UTC
Hi I recently upgrade to 6.9.2 version and when I tried to Drag my xml file from windows folder to the notepad++ it didn't work!!! The file wasn't open.

**Comment by SinghRajenM** [comment] 2017-02-24 18:43
Duplicate of #2641, #159, #556.

Issue is fixed in #2643 . Try latest version.

@dail8859 can we close this ticket?

**Comment by dail8859** [comment] 2017-02-24 18:51
Closed by #2643

**Closed by dail8859** 2017-02-24 18:51 UTC
