### ISSUE TITLE
Open dialog button shows as Save not Open

### ISSUE THREAD

**Issue by vytux-com** [notepad-plus-plus/notepad-plus-plus#10047] opened 2021-06-21 02:15 UTC
### Description of the Issue
When you click open a file the dialogue button text incorrectly shows as save and not open

### Actual Behavior
![image](https://user-images.githubusercontent.com/5370583/122698285-5b0f9600-d28a-11eb-8882-b1229aa0714f.png)

**Comment by sasumner** [comment] 2021-06-21 11:10
Duplicate of #9966 #10030 #10031 and others.
This has been fixed in 8.1.
Please search for existing issues (open OR closed) before creating a new one -- thanks.
Also, when creating an issue, fill out the issue template that is given to you -- don't simply delete out all of the information.
Closing.

**Closed by sasumner** 2021-06-21 11:10 UTC
