### ISSUE TITLE
Dark mode missed a few spots

### ISSUE THREAD

**Issue by xcasxcursex** [notepad-plus-plus/notepad-plus-plus#9958] opened 2021-06-07 07:35 UTC
Title. A major issue is plugins. As far as the base app goes:
![image](https://user-images.githubusercontent.com/58130821/120977326-8daf8e00-c7b6-11eb-9ecc-2ea3c174de68.png)

Dark mode though... finally... Feels good man!

**Comment by richardcrossley** [comment] 2021-06-07 11:36
Thanks for raising this, I was going to report the same. 

Notepad++, rocks, thanks this will be on my work PC in the morning.

**Comment by sasumner** [comment] 2021-06-07 12:08
Clearing refers to version 8.
I'm not looking forward to slogging through all of the "this bit was forgotten for dark mode!" issues that are probably soon to be created. :-)

**Comment by pixeltester** [comment] 2021-06-07 13:03
Plugins icons have disappeared from the toolbar even with darkmode deactivated or rolling back to previous release, is this the same issue? I can't see how to reinstate them.

**Comment by pixeltester** [comment] 2021-06-07 13:04
Plugin icons are invisible in light mode also.

**Comment by pixeltester** [comment] 2021-06-07 13:06
![invisible](https://user-images.githubusercontent.com/48839175/121021585-71e9bf00-c799-11eb-9441-7093469d6953.png)

Invisible plugin icons in light mode also.

**Comment by McCovican** [comment] 2021-06-08 11:52
Tabs seem to revert to light mode when multi-line tabs are enabled and you open enough tabs to go onto a second line.

**Comment by sasumner** [comment] 2021-06-08 11:58
@McCovican Maybe like described in #9957 ?

**Comment by tfkinc** [comment] 2021-06-16 13:51
The editor stayed for me in light mode on one system. I did restart NPP several times - no changes.

![image](https://user-images.githubusercontent.com/41904824/122230888-5168e580-ceba-11eb-9618-befb464c53f9.png)

On a secondary system it works just fine:

![image](https://user-images.githubusercontent.com/41904824/122231346-ac024180-ceba-11eb-855e-0932eb28914c.png)

**Comment by xcasxcursex** [comment] 2021-06-16 18:55
> The editor stayed for me in light mode on one system. I did restart NPP several times - no changes.
Settings... Style Configurator... Select Theme: ...

**Comment by xcasxcursex** [comment] 2021-08-16 10:37
Just a little bump for the tab overflow buttons: 

![image](https://user-images.githubusercontent.com/58130821/129551034-6407fe47-f8f5-4f65-8df1-40244b70e1b7.png)

Thanks :)

**Comment by ArkadiuszMichalski** [comment] 2021-08-16 11:31
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10171.

**Closed by ArkadiuszMichalski** 2021-08-16 11:31 UTC
Labels: dark mode
