### ISSUE TITLE
Problem with syntax highlighting in html files with javascript using template strings

### ISSUE THREAD

**Issue by mbeltoft** [notepad-plus-plus/notepad-plus-plus#11562] opened 2022-04-21 11:37 UTC
### Description of the Issue
Syntax highlighting fails in <script> sections when a javascript template string literal is used. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
It appears to stop at second } and not at </script>

### Steps to Reproduce the Issue
[demo.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8530470/demo.zip)

1. Copy contents from attached demo.zip into a new window, or open demo.html
2. Select Language: HTML
3. Watch syntax highlighting inside <script> section

### Expected Behavior

The whole <script> section should have a different background color, but stops inside template string (delimited by backticks).
Notice how the let keyword is a different color and is in italic. If there were another let below the template string literal, it fails to be colored as expected.

### Actual Behavior

Syntax highlighting seems to stop somewhere inside a javascript template string literal.
I would expect syntax highlighting to follow the <script> section.

### Debug Information
Notepad++ v8.3.3   (64-bit)
Build time : Mar 13 2022 - 17:20:02
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1645
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by ArkadiuszMichalski** [comment] 2022-07-26 23:44
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3822.

**Closed by ArkadiuszMichalski** 2022-07-26 23:44 UTC
