### ISSUE TITLE
Toolbar loses color when in Dark Mode but does not return when it is disabled

### ISSUE THREAD

**Issue by adamtheaustin** [notepad-plus-plus/notepad-plus-plus#10888] opened 2021-12-07 13:26 UTC
### Description of the Issue

I decided I wanted to try the dark mode of Notepad++ so I turned it on.  I noticed that the toolbar changed and lost almost all color so it was hard for me to clearly see the SAVE icon because it was nearly the same as the others.  I disabled dark mode but the toolar is still the same and it no longer has the colors that it used to have.

### Steps to Reproduce the Issue

1. Enable Dark Mode
2. NOTICE the toolbar has change (OPEN icon is no longer yellow-ish, for example)
3. Close Notepad++
4. Open Notepad++
5. Disable Dark Mode
6. Close Notepad++
7. Open Notepad++
8. OBSERVE the toolbar has NOT changed back (OPEN icon is still no longer yellow-ish)

### Expected Behavior

I want the toolbar to be the same as it was before I enabled Dark Mode.

### Actual Behavior

It was changed in Dark Mode but it never changed back.

### Debug Information

Notepad++ v8.1.9.2   (32-bit)
Build time : Nov 21 2021 - 04:27:12
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 7 Home Premium (64-bit) 
OS Build : 7601.0
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by rimrul** [comment] 2021-12-07 14:25
This seems to be a duplicate of #10212 and #10544.

**Comment by adamtheaustin** [comment] 2021-12-07 15:03
Please review the two attached images (one where Dark Mode was Never Enabled).
I don't know what "small icons" are but this looks very different than just small icons.
![DarkModeNeverEnabled](https://user-images.githubusercontent.com/93656956/145053647-dfb28361-553b-4f20-8a73-4fe8d1cad805.png)
![DarkModeDisabledAndToolbarIsBrokenAsInLostColor](https://user-images.githubusercontent.com/93656956/145053648-bee3595c-f079-43b2-8e71-ca1904b2c32c.png)

**Comment by rimrul** [comment] 2021-12-07 15:56
Oh, ignore the "small" part, I'm talking about the "Fluent UI" part. And that seems to be what your screenshot shows. What you want should be "standard icons".

**Closed** 2021-12-07 21:36 UTC
Labels: duplicate
