### ISSUE TITLE
What should I do if I wanted to propose a source code change ?  

### ISSUE THREAD

**Issue by Skrell** [notepad-plus-plus/notepad-plus-plus#13838] opened 2023-06-27 14:31 UTC
Background Info:
I've been using the jN plugin for awhile now as the "smart highlighter" feature is **absolutely essential** see pic below.  However, I quickly realized it had some severe limitations that truly prevented it from shining.  The main limitation I saw in the javascript was that it could ONLY apply a  "style token" as a means of getting the "smart highlighter" to correctly indicate where all the highlights were in a document.  I decided to take a look through the code at how the smart highlighting feature of NPP works.  

When I looked in the code I was surprised to see that the code for NPP's smart highlighting does not function at all like the "style tokens" as it ONLY highlights the visible portion of a document then updates it as you scroll up/down.  

I simply went and replaced this code with an almost identical function to how the style token's work and compiled and boom everything worked perfectly!  

I see no reason why my code wouldn't be acceptable as it'll simply make NPP's source code more uniform.  

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/590266/adec9e22-40e4-4f4a-b460-ef6780fbc466)

**Comment by alankilborn** [comment] 2023-06-27 17:43
>What should I do if I wanted to propose a source code change ?

Follow the instructions in CONTRIBUTING.md.

Perhaps the SmartHighlight works like that so that for a huge document it doesn't take a lot of time to colorize a lot of matches that you can't currently see?

**Comment by Skrell** [comment] 2023-06-27 20:50
I see no detriment in performance at all.  If anything I think there's less processing as currently the smart highlighting evaluates the document over and over as you scroll instead of all at once up front.   That would imply that using all 5 style tokens would have some negative impact on performance which is not true.  
I'll take a shot at following the CONTRIBUTING.md document. Ty

**Comment by Skrell** [comment] 2023-06-27 20:51
So I just looked over that document and it seems like the only way to get this change proposed is through a pull request?  Is that correct?

**Comment by alankilborn** [comment] 2023-06-27 23:08
>I see no detriment in performance at all.

What kind of testing did you do?

>pull request

Yes, that's the method.

**Comment by Skrell** [comment] 2023-06-28 18:38
> > I see no detriment in performance at all.
> 
> What kind of testing did you do?
> 
> > pull request
> 
> Yes, that's the method.

Well I took some performance benchmarks and I'm wrong...there IS a performance difference and it's quite pronounced.  However, the performance is ONLY impacted for smart highlighting, if I simply use all 5 style tokens on a LARGE document and scroll there is NO issue... so clearly the function you're using for smart highlighting must be called in a completely different path of the code than style tokens and this path consumes many more CPU cycles... 

So I guess until I figure out what that path is I guess I can't purpose this change.

**Comment by ArkadiuszMichalski** [comment] 2024-07-24 01:03
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3116.

**Closed by ArkadiuszMichalski** 2024-07-24 01:03 UTC
