### ISSUE TITLE
Unable to open folders/files using a UNC path on Windows

### ISSUE THREAD

**Issue by webex4727** [notepad-plus-plus/notepad-plus-plus#7772] opened 2019-12-23 18:15 UTC
I am not able to open a file using a UNC path or the folder it is in with the File|Open menu option.  This did work on versions prior to 7.7.1.

Version 7.7.1
Attempting to open UNC path: \\osd-app-cptprod\c$\Batch\logs
Windows Title: 'Cannot open file'
\\osd-app-cptprod\c$\c$\Batch\logs\cannot be opened:
Folder "\\osd-app-cptprod\c$\osd-app-cptprod\c$\Batch\Logs" doesn't exist.

\\osd-app-cptprod\c$ does work as expect where it opens the folder and allows me to select a file or another subfolder

Version 7.8.2
Attempting to open UNC path: \\osd-app-cptprod\c$\Batch\logs
Windows Title: 'Cannot open file'
"c:\osd-app-cptprod\c$\Batch\logs\" cannot be opened:
Folder "c:\osd-app-cptprod\c$\Batch\logs\" doesn't exist.

**Comment by sky5walk** [comment] 2021-03-18 20:44
I see a similar problem now with Windows 10 v20H2 and NP++ v793 x64.

File-Open-dialog and paste in --> \\1.2.3.4\blah\more\evenmore\myfile.txt
The dialog complains after truncating one leading backslash? --> \1.2.3.4\blah\more\evenmore\myfile.txt

[Window Title] Open
[Content]
\1.2.3.4\blah\more\evenmore\myfile.txt
File does not exist.
Check the path and try again.
[OK]

**Comment by sasumner** [comment] 2021-03-18 20:50
Similar/duplicate of #9582 which is scheduled to be fixed with Notepad++ 7.9.5.
Please check results obtained with 7.9.5 and report back in 9582 if any problems.

**Closed by sasumner** 2021-03-18 20:50 UTC
