### ISSUE TITLE
[Feature Request] Function list tool tip text

### ISSUE THREAD

**Issue by cjohnsonuk** [notepad-plus-plus/notepad-plus-plus#1212] opened 2015-12-02 10:03 UTC
A great enhancement would be the ability to pull tooltip text for each function from the code surrounding the function definition.  A regexp, defined in the XML for each language, could be used to identify text in the code to display as a tooltip when mousing over the function name in the function list, eg to show a list of parameters or expected usage/ limitations/ author etc.  The regexp could be used to identify text to show from a preceding line, same line or following line comment or just a list of function parameters if these matches don't return anything. 
 _Sometimes you don't need to see the code, just the comment (or even just a list of parameters)_

**Comment by MetaChuh** [comment] 2019-04-13 02:13
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:13 UTC
