### ISSUE TITLE
N++ contents get blurred when shown on the secondary screen

### ISSUE THREAD

**Issue by Prze-moC** [notepad-plus-plus/notepad-plus-plus#8856] opened 2020-09-14 08:47 UTC
### Description of the Issue
The N++ window itself and its contents get blurred when shown on the secondary screen. The same window on the primary screen looks OK. Other applications look OK on both screens.

### Steps to Reproduce the Issue
1. Primary laptop's monitor is 1920x1080 scaled to 125%
2. Desktop extended to the extra monitor.
3. Extra monitor is 1440x2560 and pivoted 
4. Open N++ window on the laptop's monitor (all thumbnails are blurred - click to enlarge and see the difference): 
![npp not-blurred ](https://user-images.githubusercontent.com/47782278/93062684-92a33f00-f675-11ea-83de-017da71a932b.png)
5. Drag the N++ window over to the extra monitor (all thumbnails are blurred - click to enlarge and see the difference): 
![npp blurred](https://user-images.githubusercontent.com/47782278/93062751-a484e200-f675-11ea-8f83-c423250bddba.png)

### Expected Behaviour
The text should look OK regardless of the monitor used.
Primary monitor (all thumbnails are blurred - click to enlarge and see the difference):
![notepad primary](https://user-images.githubusercontent.com/47782278/93063097-0c3b2d00-f676-11ea-9a68-f83411fb97b3.png)
Secondary monitor (all thumbnails are blurred - click to enlarge and see the difference):
![notepad secondary](https://user-images.githubusercontent.com/47782278/93063100-0d6c5a00-f676-11ea-9f99-83584e89b27a.png)

### Actual Behavior
Primary monitor (all thumbnails are blurred - click to enlarge and see the difference):
![npp not-blurred ](https://user-images.githubusercontent.com/47782278/93062684-92a33f00-f675-11ea-83de-017da71a932b.png)
Secondary monitor (all thumbnails are blurred - click to enlarge and see the difference):
![npp blurred](https://user-images.githubusercontent.com/47782278/93062751-a484e200-f675-11ea-8f83-c423250bddba.png)

### Debug Information
Notepad++ v7.8.9   (64-bit)
Build time : Jul 15 2020 - 20:31:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1016
Current ANSI codepage : 65001
Plugins : DSpellCheck.dll HTMLTag.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppExport.dll NppSaveAsAdmin.dll NppXmlTreeviewPlugin.dll XMLTools.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment] 2020-09-14 19:19
Closing as duplicate of #8115

**Closed by sasumner** 2020-09-14 19:19 UTC
