### ISSUE TITLE
"Folder as workspace" colors inverted when opening File Explorer

### ISSUE THREAD

**Issue by thomassmith311** [notepad-plus-plus/notepad-plus-plus#10805] opened 2021-11-19 22:18 UTC
### Description of the Issue
When I open a new instance of File Explorer while Notepad++ is also on, the Folder as Workspace window suddenly inverts colors. They stay inverted until I either hide and reshow the FaW window or restart the app. See the attached video at the bottom. This only occurs when I actually start a new instance of File Explorer, not just when I make an open one visible by clicking it on the taskbar.

### Steps to Reproduce the Issue
1. Enable "Folder as Workspace"
2. Open a new instance of File Explorer

### Expected Behavior
I would expect the colors of the FaW window to remain the same.

### Actual Behavior
The colors appear to have inverted.

### Debug Information
> Notepad++ v8.1.9.1   (64-bit)
Build time : Nov 13 2021 - 15:28:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19042.1348
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

https://user-images.githubusercontent.com/19561856/142698566-841eea81-5985-4c42-ba79-6d7baf377829.mp4

If that video does not work I also uploaded it to Google Drive:
https://drive.google.com/file/d/1kdPOVRAhbZr3mnQij85y3BelbwyVL8rL/view?usp=sharing

Screenshot:
![image](https://user-images.githubusercontent.com/19561856/142773588-59c58d2c-3ef9-4699-a8b0-1f5acbe392a3.png)

This also happens in light theme; colors are inverted, though of course it looks different:
![image](https://user-images.githubusercontent.com/19561856/142773572-46ad88ba-4549-4606-b886-c23cfbec2f36.png)

**Comment by thomassmith311** [comment] 2021-11-21 17:57
Actually, I just realized that it only happens when opening the File Explorer app. I will change the opening post to reflect that.

**Comment by thomassmith311** [comment] 2021-11-21 18:00
This also happens in light theme. See the screenshot:
![image](https://user-images.githubusercontent.com/19561856/142773546-80dfa14f-4b6e-46ab-af90-4f20e5ce3de0.png)
It's hard to see, but the background appears gray while text is highlighted white, which is the opposite of what it should be.

**Comment by ArkadiuszMichalski** [comment] 2021-11-21 18:13
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2937.

**Closed by ArkadiuszMichalski** 2021-11-21 18:13 UTC
