### ISSUE TITLE
Notepad++ does not correctly handle UTF-8 character U+00A7 (§)

### ISSUE THREAD

**Issue by Tzalumen** [notepad-plus-plus/notepad-plus-plus#3222] opened 2017-04-28 15:36 UTC
### Description of the Issue
Inputting character U+00A7 (§) displays correctly, but does not save correctly, converting either to ยง or U+0015 (NAK) on reloading. When examined in notepad or wordpad, notepad++ is prepending the character with U+00C2 (Â) to produce ยง or replacing the character with U+0015 (NAK).

The process to select between prepend Â or replace with NAK appears to be non-deterministic.

Writing the character § in notepad or wordpad by using alt+0167 results in the document being opened in ANSI encoding. Switching to UTF-8 encoding results in the character being displayed as a block character xA7

### Steps to Reproduce the Issue
Issue part 1:
1. Open notepad++
2. Set encoding to UTF-8
3. Type alt+0167 or paste § into notepad++ from any source
4. Save and reload file

Issue part 2:
1. Open notepad++
2. Set encoding to ANSI
3. Type alt+0167 or paste § into notepad++ from any source
4. Set encoding to UTF-8

### Expected Behavior
Inputting § into a UTF-8 encoding editor should save and persist the § character, as U+00A7 is explicitly defined in in the UTF-8 code page

A loaded ASCI-encoded document with a § should explicitly convert to a § in UTF-8, as the underlying encoding is identical.

### Actual Behavior
Inputting § into the UTF-8 Editor does not persist due to the character being changed when written to disk.

Converting an ANSI encoded § does not explicitly convert to a § character when converted to UTF-8

### Debug Information
Notepad++ v7.3.3   (64-bit)
Build time : Mar  8 2017 - 03:39:58
Path : C:\code\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll XMLTools.dll

**Comment by rddim** [comment] 2017-04-28 16:21
The 1st part is the same like #3188. You can disable the `Autodetect character encoding` in `Settings` > `Preferences..`. > `MISC.`

For the 2nd part I have no idea

**Comment by Tzalumen** [comment] 2017-04-28 16:25
That doesn't really address part one, since the issue appears to be the change in encoding when the file is written to disk.

**Comment by DavidHaslam** [comment] 2017-05-02 19:45
It's not changing when Notepad++ writes the file to disk.
If you open the saved file with [BabelPad](http://www.babelstone.co.uk/Software/BabelPad.html), it looks correct.

It's when Notepad++ opens the file containing a single § as the first letter when the problem occurs.

Multiple §§§§§§§ are treated right.  Even just a pair §§ works OK. But not say #§.

Saving Œ################§ gives the same problem, even though
saving Œ################ works fine.

**Comment by Tzalumen** [comment] 2017-05-02 19:57
Please indicate if you are addressing issue #1 or #2.

**Comment by DavidHaslam** [comment] 2017-05-02 20:55
I was looking at your issue part 1 out of mere curiosity.

1. Open BabelPad.
2. Type §
3. Save file (BabelPad only uses UTF-8 encoding)
4. Open the file with Notepad++

It's nothing to do with how Notepad++ saves a file. My use of BabelPad demonstrates this.

This problem is a bit like a funny old issue with earlier editions of Windows Notepad.

If you typed this in the first line (without an EOL) and saved the file. when it was re-opened with Notepad, all the characters displayed as Han CJK ideographs.

`Bush hid the facts`

Several other strings gave the same effect, though they all had to be word length pattern 4 3 3 5

Notepad++ must use an algorithm to detect what the encoding is when it opens a file.

You appear to have discovered something that "breaks" the algorithm.

The old Notepad algorithm was heuristic. 

Not quite sure what's the precise manner in which the § character messes up how Notepad++ determines the file encoding. That's for the programmers to address.

**Comment by Tzalumen** [comment] 2017-05-02 21:08
That was not my issue.
I am reporting an actual finding of unexpected (incorrect) characters when viewed in other programs, including VIM and (this probably should have been stressed more) the raw hex of the file.

Notepad++ *is* writing incorrect data.

If you are seeing the same results in BabelPad, then it may be replicating the bug.

**Comment by DavidHaslam** [comment] 2017-05-02 21:08
I too can reproduce issue part 2.  I don't think this is an issue. 

It's what can happen when you try make ANSI do something outwith its scope.

**Clue**: the UTF-8 byte codes for the section sign is \xC2\xA7.

The black \xA7 is merely the second half of it.

**Comment by Tzalumen** [comment] 2017-05-02 21:11
I am not expressing an issue with encoding detection, as I am specifying explicitly via the encoding menu what encoding I wish to view.

**Comment by DavidHaslam** [comment] 2017-05-02 21:17
Going back to part 1 of your issue.

1. New file in Notepad++ with encoding set to UTF-8
2. Type Alt-0167 to get the section sign
3. Save file as text.txt
4. Open file with trusted BabelPad. It displays correctly as § and it behaves correctly with BabelPad convert menu.
5. Close tab in Notepad++
6. Reopen file from recent list. It displays incorrectly.

I have no doubt that BabelPad is completely accurate here. 
It's proved its worth to me over several years of dealing with non-Roman scripts.
I'm even in contact with its developer.

**Comment by Tzalumen** [comment] 2017-05-02 21:20
So, I see the prepend is valid output.
It is not rendering correctly, even when UTF-8 encoding is specified, so that is still an issue.

Part 2 is then a product of an incomplete UTF-8 encoding.

That leaves the NAK, which should not be output at all in this case, 0x0F being in the single byte encoding range of UTF-8.

**Comment by DavidHaslam** [comment] 2017-05-02 21:21
A hex dump of the saved file (performed using TextPipe) gave:

`00000000  C2 A7`

**Comment by DavidHaslam** [comment] 2017-05-02 21:23
Are you using Notepad++ x64 or x32 ?

Though I have a 64-bit Win7 PC, I still use Notepad++ x32.

**Comment by Tzalumen** [comment] 2017-05-02 21:29
x64, in case I ever have to open a text file larger than 4GB. That shouldn't be a thing that happens, however, I got 'lucky'.

**Comment by DavidHaslam** [comment] 2017-05-02 21:31
I'm beginning to suspect that the described writing to disk issue may be unique to the x64 edition.
It's not happening with my combination of hardware, Windows and Notepad++.

**Comment by DavidHaslam** [comment] 2017-05-02 21:32
One reason for me to stick with x32 is plugin support. One plugin I use a lot is **XML Tools**.

**Comment by Tzalumen** [comment] 2017-05-02 21:36
I have figured out how to replicate the NAK.
1. Open notepad++
2. Set encoding to UTF-8
3. paste 
word § word
4. save
5. reload file
6. observe ยง
7. select ยง
8. delete ยง
9. alt+0167 or paste §
10. reload
11. observe NAK character

**Comment by DavidHaslam** [comment] 2017-05-02 21:37
I've not yet seen the NAK - but maybe only because I've not done exactly the same as you and because mine is the x32 edition.

**WordPad** does prepend the section sign with Â though, but I think that's a quirk of WordPad.

**EditPad Pro** displays only the section sign.

**Comment by Tzalumen** [comment] 2017-05-02 21:39
I was using XML Tools in x64.
loved being able to deminify some of our generated output.

**Comment by DavidHaslam** [comment] 2017-05-02 21:39
I followed your 11 part plan and got the NAK.

Wow!

**Comment by DavidHaslam** [comment] 2017-05-02 21:43
Aside: I assume that by "deminify" you were using one of the Pretty Print options of XML Tools.

I have one large XML file that it can't cope with (using x32). It never finishes processing.
Maybe I should reconsider x64 ?

**Comment by DavidHaslam** [comment] 2017-05-02 21:45
I'm on GMT+0 time zone, so I must finish now.

btw. I don't visit the project very often on GitHub.

**Comment by Tzalumen** [comment] 2017-05-02 21:47
Yes. I don't like the term pretty print in that context, because pretty print is associated with converting an array of raw bytes into human-readable hexadecimal.

**Comment by Tzalumen** [comment] 2017-05-02 22:15
Further discovery: if notepad++ has loaded the § from disk as ยง any new instances of § added to the file will save as a NAK until the file is closed without a § and reopened. Reload will not reset it.
Additionally, the incorrect display (and continual error state of notepad++) of the § only occurs when between two whitespaces, including tabs and newlines.
if the ยง is moved adjacent to non whitespace, and the file is closed and loaded, it will revert to §

**Comment by DavidHaslam** [comment] 2017-05-03 07:07
I already reported that #§ displayed wrong after opening so the claim about whitespace on both sides doesn't make sense to me.

**Comment by Marcono1234** [comment] 2017-06-05 13:43
I created #3359 for that now, not sure if this was the right move or if this report should have been edited.

**Comment by subchannel13** [comment] 2017-10-05 10:32
@DavidHaslam Do you have a reference for \xC2\xA7 being official bytes for section sign? All that I can find is that \xC2 and \xA7 are two separate symbols, one being accented A and other being section sign. Additionally U+C2A7 is not valid unicode character: http://www.fileformat.info/info/unicode/char/c2a7/index.htm

**Comment by DavidHaslam** [comment] 2017-10-05 10:57
Doh!

It's the UTF-8 byte codes for the section sign U+00A7.

Or did you not read all the earlier comments in this thread?

**Comment by subchannel13** [comment] 2017-10-06 11:20
You are not making sense and your hostility is unprovoked. In https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3222#issuecomment-298761887 you clearly state that `§` should be encoded as \xC2\xA7 and you don't take back that statement in any later comment. I simply asked what made you to believe so and if you can reference a source for that claim.

The reason behind my question is not to make you look stupid but to understand the situation around `§` symbol. In Notepad++'s Hex-Editor plugin I can see \xC2 character before \xA7 but in normal Notepad++ editor I don't see any extra character nor does it exists in C# string when I read whole file there. I'm interested in situation because I too battled `ยง` showing up where `§` should be and getting strange git diffs when retyping `§`.

**Comment by DavidHaslam** [comment] 2017-10-06 15:10
I did not say that.  I merely observed that the UTF-8 byte codes for `§` are `\xC2\xA7`.
That is what you get when you convert it to UTF-8 hexadecimal byte codes using **BabelPad**.

There's really no mystery in this. This is merely a _representational_ matter.
I never claimed that it's represented to **Notepad++** like this.

There are all sorts of _different_ ways to represent the same codepoint.
- `§`
- `&#x00A7;`
- `\u00A7`
- `\x{00A7}`
- `C2 A7`
- `\xC2\xA7`
- `00A7`
- `000000A7`
- `U+00A7`
- `SECTION SIGN`

The one we're discussing just happens to be the form required as the _Replace_ item in **DataMystic TextPipe** for **Perl** compatible _Search and Replace_ filters.
In that context, the Search item takes the form `\x{00A7}`.

**Comment by DavidHaslam** [comment] 2017-10-06 15:11
Character Properties for U+00A7
Character Name = SECTION SIGN
Formal Alias = 
Abbreviation = 
Unicode 1.0 Name = 
Block Name = Latin-1 Supplement
Script = Common
Introduced in Unicode 1.0.0 (October 1991)
General Category = Po [Punctuation, Other]
Canonical Combining Class = 0 [Spacing, split, enclosing, reordrant, and Tibetan subjoined]
Bidi Class = ON [Other Neutrals]
Decomposition Type = 
Numeric Type = 
Bidi Mirrored = No
Joining Type = U (Non Joining)
Joining Group = No Joining Group
Uppercase Mapping = 
Lowercase Mapping = 
Titlecase Mapping = 
Line Break = AI [Ambiguous (Alphabetic or Ideographic)]
Notes [*], Aliases [=] and Cross-References [x]
	* paragraph sign in some European usage
Binary Properties
	Grapheme Base
	Pattern Syntax
Encoding
	UTF-8 = C2 A7
	UTF-16 = 00A7
	UTF-32 = 000000A7

**Comment by Fabian42** [comment] 2020-05-22 12:16
I'm not sure if this is the same issue or even supported, but I'm reporting it here in case it helps:
I installed Notepad++ using the regular repositories in Manjaro (which makes it run with Wine and pre-sets some settings convenient for Linux) and today I entered "¹" in it (the same happens with "²"), closed and re-opened Notepad++ and it turned into "ยน". The rest of the file was unchanged. On later attempts, it always just turned into "?".
I'm using Notepad++ 7.8.6 with Wine 5.8 in Manjaro 20.0.1.

**Comment by Fabian42** [comment] 2020-06-30 13:37
Today "§" turned into "" (displayed as "NAK" in a box) and earlier into "ยง". This bug is fascinating.

**Comment by kleidt** [comment] 2021-08-19 13:07
Also related is #940

**Comment by kleidt** [comment] 2022-01-03 09:36
It looks like this issue is fixed together with #940 
I could not reproduce it with 8.1.9.3

**Comment by donho** [comment] 2022-01-05 04:24
It should be fixed in v8.2

**Closed by donho** 2022-01-05 04:24 UTC
