### ISSUE TITLE
"Active Server Pages script file" comment syntax highlighting wrong

### ISSUE THREAD

**Issue by jayrlsw** [notepad-plus-plus/notepad-plus-plus#3678] opened 2017-08-30 10:00 UTC
When you try to close off some ASP that has a comment on the same line, the syntax highlighter does not understand this. As seen in the image below, the HTML on the last line has the blue ASP background when it should be white.

![](http://i.imgur.com/WGV7tGQ.png)

**Comment by ArkadiuszMichalski** [comment] 2020-09-23 20:19
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3215.

**Closed** 2020-09-23 20:41 UTC
