### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by Tmp341** [notepad-plus-plus/notepad-plus-plus#1016] opened 2015-10-17 09:42 UTC
There is a problem with the Turkish localization file. Somehow, although i've already translated it, seems like "Restore Recent Closed File" line isn't changed.
Perhaps the translation line too long or something. Or there is a problem with my computer.
![screen](https://cloud.githubusercontent.com/assets/1683388/10558104/894cbaf6-74cc-11e5-8a30-4e9069203a0f.png)

**Comment by gamzeakmann** [comment] 2016-11-15 14:02
I want to resolve #1016 with a few commits

**Comment by gamzeakmann** [comment] 2016-11-18 08:53
@milipili Could you assign this error to me?

**Comment by donho** [comment] 2016-11-18 09:07
@gamzeakmann Cannot assign this issue to you.
You can always do the PR. if @Tmp341 approve your PR, I'll accept it and integrate it in the future release.

**Comment by Tmp341** [comment] 2018-02-21 08:41
[4ebd2d6](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4ebd2d6c6517eb68bea3c147a23646c6b6d0641b#diff-e11eebe23907f6f411b906128fca7872) should have fixed the issue, but it didn't. Waiting for future PRs.

**Comment by MetaChuh** [comment] 2019-04-10 23:44
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:44 UTC
Labels: translation
