### ISSUE TITLE
Website: Resources page claims that Plugin Manager is included

### ISSUE THREAD

**Issue by Stevoisiak** [notepad-plus-plus/notepad-plus-plus#3848] opened 2017-10-25 13:24 UTC
On the official website, [the resources page](https://notepad-plus-plus.org/resources.html) claims that the Plugin Manager is included with Notepad++. This is inaccurate, as [the Plugin Manager is no longer included as of Notepad++ v7.5](https://notepad-plus-plus.org/news/notepad-7.5-released.html).

> ### Plugins
> From the v3.1, Notepad++ has the extension capacity - the plugin system. Please see Plugins HOWTO to learn how to install a plugin or/and how to develop a plugin.
> 
> A list of plugins is maintained on NpWiki++ and should be complete. You can use this list to add/update your plugins, but it may not be necessary - **Plugin Manager plugin is included in Notepad++ release. It gets jobs done very well.**
> 
> If you can not find the plugin you need, just make your own.

**Comment by sasumner** [comment] 2017-10-27 15:25
Duplicate of #3841

**Comment by donho** [comment] 2019-07-22 07:54
Fixed

**Closed by donho** 2019-07-22 07:54 UTC
Labels: documentation
