### ISSUE TITLE
Notepad++ 32bit almost freezes

### ISSUE THREAD

**Issue by THausherr** [notepad-plus-plus/notepad-plus-plus#10296] opened 2021-07-31 12:15 UTC
### Description of the Issue
I opened the file and it froze, although I was able to close NOTEPAD++ after a few minutes

[pattern_colors_broken_unc.pdf](https://github.com/notepad-plus-plus/notepad-plus-plus/files/6911144/pattern_colors_broken_unc.pdf)

### Steps to Reproduce the Issue

1. open the file
2. try to click on anything
3. 

### Expected Behavior
able to move

### Actual Behavior
unable to move

### Debug Information

Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 2009
OS Build : 19043.1110
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by THausherr** [comment] 2021-07-31 12:27
I uninstalled my 32 bit version and installed the 64 bit version and it works there.

**Comment by donho** [comment] 2021-08-04 13:36
@THausherr 
> I uninstalled my 32 bit version and installed the 64 bit version and it works there.

Do you mean "it works `well`" ? So does the 64 bit solve the issue ?

**Comment by moledzki** [comment] 2021-08-06 21:11
I have similar problem. After dozens of minutes I'm unable to use Notepad++ anymore, but it isn't frozen completely.
I'm able to:
- open new files (by executing Notepad++.exe filename.txt)
- resize Notepad++ window using Win+Arrow shortcut, but it's not possible to maximize window. After about 20+ resize operation I'm unable to resize Notepad++ window anymore.

I'm unable to:
- edit opened files
- switch to other opened file

If I do not try to resize Notepad++ multiple times it is possible to exit application by clicking close window button. After about 20 resizes close window button is not working anymore, but it's still possible to close Notepad++ by clicking right button on taskbar and then clicking close window menu item.


### Debug Information
Notepad++ v8.1.2   (32-bit)
Build time : Jul 16 2021 - 01:56:21
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1909
OS Build : 18363.1679
Current ANSI codepage : 1250
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppXmlTreeviewPlugin.dll SQLinFormNpp.dll Tidy2.dll WakaTime.dll XMLTools.dll

**Comment by mere-human** [comment] 2021-08-07 07:37
@moledzki Was the dark mode enabled? Also can you try without plugins?

**Comment by moledzki** [comment] 2021-08-07 08:40
Dark mode was not enabled, only Obsidian theme was enabled.
I will try to use notepad++ without plugins. Is there a simple way to disable (not uninstall) all plugins?

**Comment by mere-human** [comment] 2021-08-07 08:45
@moledzki 
> I will try to use notepad++ without plugins. Is there a simple way to disable (not uninstall) all plugins?

Yes, if you're familiar with the command line.
Open cmd, navigate to Notepad++ directory, and start it like this `notepad++.exe -noPlugin`
https://npp-user-manual.org/docs/command-prompt/

**Comment by donho** [comment] 2021-08-19 00:13
@THausherr  @moledzki 
Could you try [fixed x32](download.notepad-plus-plus.org/repository/MISC/npp_fix_perf_32.zip) or [x64  binary](download.notepad-plus-plus.org/repository/MISC/npp_fix_perf_64.zip) ?
I believe this issue is fixed in the binaries I provide above.

**Comment by moledzki** [comment] 2021-08-19 15:22
@mere-human @donho 

Initially I thought that the problem can be solved by disabling all plugins (because after disabling all plugins everything stared to work correctly). But then I've started Notepad++ with enabled plugins and I was not able to reproduce this problem anymore.

**Comment by THausherr** [comment] 2021-08-19 17:37
I tried the 32bit version with that file and it worked. (The 64 bit version didn't have the problem)

**Comment by donho** [comment] 2021-08-19 21:32
@THausherr
Thank you for your confirmation!

**Comment by donho** [comment] 2021-08-19 21:34
@moledzki 
Thank you for your retesting.

**Closed** 2021-08-19 21:43 UTC
Labels: accepted, performance issue
