### ISSUE TITLE
Feature Request: Add narrow column to the left of the editor area to make selection easier

### ISSUE THREAD

**Issue by vrodax** [notepad-plus-plus/notepad-plus-plus#4653] opened 2018-07-10 16:50 UTC
### Description of the Issue
The text in the editor area butts right up against the left side of the editor area.  As a result You have to be very precise when attempting to start text selection with the first character on the line.  I am constantly creating a book mark instead of starting a new text selection as a result of this.

This may not be a problem for most, however, I have an essential tremor and it is sometimes difficult for me to begin the selection properly.

The Visual Studio editor provides a significant area to the left of the text allowing you to easily select whole lines of text.

This would be greatly appreciated.

**Comment by vrodax** [comment] 2018-07-14 13:53
Yes.  About 90 percent of the time when I am selecting from there it is for the purpose of selecting whole lines.  It never occurred to me to try clicking all the way over there.  I guess it is because in Visual Studio the area for breakpoints and bookmarks is to the left of the line numbers instead of to the right of it.
So I would like to revise my request and suggest providing an option to swap these so that the bookmark area is to the left of the line numbers.

By the way, I want to complement all of those who work on this project for the really great work you are doing.  I am a software developer and use Visual Studio for the bulk of my editing.  However, I use notepad++ whenever I want to do large multi-directory searches or scan log files or take a quick look at individual files because it starts up so fast and really excels at file searches.  I usually have it up an running on one screen with VS running on the other.  Thanks for all of your hard work.

**Comment by sasumner** [comment] 2018-07-14 15:29
One of the common things that makes me a bit crazy is that people often can't accept the way Notepad++ does things is because it does it differently than the way Visual Studio does it.  People don't consider that gee, maybe Notepad++ does it better...not saying this is true about your complaint, but there seems to be this attitude that there is a deficiency in "whatever tool" because it doesn't "do it like VS".

I'm not a developer on Notepad++, mainly due to I see how contributors' changes are mostly ignored by the true dev team, but I'm sure they appreciate your praise, if they even read this.

**Comment by nikunjbhatt** [comment] 2020-01-29 13:14
I am also/even creating bookmark when trying to select a whole line.

Besides the positions of line numbers space and bookmark space, I think, another reason for this problem is that the spaces are not marked with different colors and/or the mouse cursor is same when it is over any of these areas.

So, my suggestion is to either set different colors for bookmark and lines numbers spaces OR show different cursor (than line number cursor) when it is over the bookmark space OR highlight the particular line numbers space or bookmark space respectively whenever cursor is over them.

**Comment by sasumner** [comment] 2020-01-29 18:35
@nikunjbhatt said 

>I am also/even creating bookmark when trying to select a whole line.

Things can always be improved, but did you see my comment earlier about clicking ON the line number(s) when wanting to select the whole line(s)?  To me it seems very workable and I don't think I've ever set a bookmark when trying to select a whole line.

**Comment by nikunjbhatt** [comment] 2020-01-30 02:39
@sasumner yes, I had read your comment. And I am sorry that I failed to write my point properly which I had in my mind. I know about the feature that clicking on the line number selects the whole line.

What I was trying to tell is - when I try to select the whole line by clicking on the line number, I am accidentally clicking on the bookmark space, resulting in creating bookmark rather than selecting the line or vice-versa.

**Comment by sasumner** [comment] 2020-01-30 12:22
@nikunjbhatt said:

>when I try to select the whole line by clicking on the line number, I am accidentally clicking on the bookmark space

Suggest practice to make your mouse aim better? :-)
Seriously, though, my experimentation shows that you have to be a fair number of pixels to the right of the line number in order to get a bookmark placed rather than the whole line selected.  Thus, further visual delineation (although that in itself wouldn't be a bad thing) isn't going to solve your problem (as you describe it).

**Comment by nikunjbhatt** [comment] 2020-01-31 16:48
I am accidentally creating bookmark when trying to collapse/uncollapse lines also. I am using laptop and sometimes I don't have/can't use mouse, and aiming with touchpad is hard.

UX point of view, placements of the spaces of line numbers, bookmarks and collapse/uncollapse doesn't seems optimum because of the width of bookmarks and collapse/uncollapse spaces. So, it would be good to either change the placements of these spaces or provide some other solution/visual clue.

> One of the common things that makes me a bit crazy is that people often can't accept the way Notepad++ does things is because it does it differently than the way Visual Studio does it.

I am using Notepad++ because it has different features than other code editors, it is easy to use, it is doing some things better/differently than others; but these doesn't mean that everything should be different than other editor(s). It is better to improve our software by analyzing possible problems in the software and analyzing other similar software to know how our software can be improved to mitigate the problems. Isn't learning from virtues and mistakes of others good?

**Comment by sasumner** [comment] 2020-01-31 18:09
>aiming with touchpad is hard

I think you finally revealed the key point! :-)

>width of bookmarks and collapse/uncollapse spaces...So, it would be good to either change the placements of these spaces

I'm fairly certain the widths could be changed using a scripting plugin, or NppExec plugin.

>Isn't learning from virtues and mistakes of others good?

Yes, but all too typically people suggest that Visual Studio's editor's way of doing things is the way every other editor should do things (you aren't saying that, clearly).

**Comment by ArkadiuszMichalski** [comment] 2020-09-30 20:04
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2323? After https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8874 maybe the bookmarking by mistake will be smaller.

**Comment by sasumner** [comment] 2020-09-30 20:23
>Duplicate of #2323?

I don't know -- not much rationale was provided for 2323.

>After 8874 maybe the bookmarking by mistake will be smaller.

Fully agree, that is my main motivation for doing 8874 -- and I think it will allow users to avoid the problem of THIS issue, so closing.

**Closed by sasumner** 2020-09-30 20:23 UTC
