### ISSUE TITLE
Invalid JSON is shown as yellow on white in light mode

### ISSUE THREAD

**Issue by kenlyon** [notepad-plus-plus/notepad-plus-plus#12280] opened 2022-10-03 18:19 UTC
### Description of the Issue

The highlighting of invalid JSON seems to be not working correctly. I use light mode but I wonder if the yellow style was designed for dark mode.

### Steps to Reproduce the Issue

1. Ensure Dark Mode is disabled (Preferences > Dark Mode > Uncheck "Enable dark mode")
2. Create a blank document and add this invalid JSON text (The missing quote is deliberate)  
{"foo:"bar"}
3. Change the language to JSON (Language > J > JSON)

### Expected Behavior
The highlighting of the invalid portion should be readable on a white background.

### Actual Behavior
The invalid portion of text turns yellow, which is very hard to see on a white background.

### Debug Information

Notepad++ v8.4.5   (64-bit)
Build time : Sep  3 2022 - 04:05:32
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 21H2
OS Build : 19044.1889
Current ANSI codepage : 1252
Plugins : 
    JSMinNPP (1.2205)
    mimeTools (2.8)
    NppConverter (4.4)
    NppExport (0.4)
    NppMarkdownPanel (0.6.2)
    XMLTools (3.1.1.13)

**Comment by ArkadiuszMichalski** [comment] 2022-10-03 19:30
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8715.

**Closed by ArkadiuszMichalski** 2022-10-03 19:30 UTC

**Comment by ArkadiuszMichalski** [comment] 2022-10-04 17:22
`Current line background` or `Selected text background` overwrite `JSON ERROR background`. Unfortunately the default appearance of JSON ERROR inside `stylers.xml` is unfortunate. This should be corrected so that it does not interfere with each other (the text should be visible - yellow is a mistake here).
