### ISSUE TITLE
NPP asks for file-reload after closing NPP has been triggered.

### ISSUE THREAD

**Issue by alex77g2** [notepad-plus-plus/notepad-plus-plus#14762] opened 2024-02-20 08:50 UTC
### Description of the Issue
NPP asks for file-reload after closing NPP has been triggered.

### Steps to Reproduce the Issue
1. Open a File test.txt
2. Change File by another external tool.
3. Close NPP now (by red X in upper right window corner)

### Expected Behavior
NPP should close, without any reload file question.

### Actual Behavior
A MsgBox pops up and asks for reload changed file.
(after answering NPP closes)

### Debug Information
Notepad++ v8.6.2   (64-bit)
Build time : Jan 14 2024 - 02:16:00
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "E:\Sourcen\git\abcd\test.txt" 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit)
OS Version : 22H2
OS Build : 19045.4046
Current ANSI codepage : 1252
Plugins : 
    HexEditor (0.9.12)
    mimeTools (3)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by molsonkiko** [comment] 2024-02-27 04:33
I can't replicate this issue in Notepad++ 8.6.2 or any other version I've tested. If I click on the red button to close Notepad++ after modifying a file outside of Notepad++, Notepad++ closes without prompting me.

If I click anywhere in the Notepad++ window before clicking the red button, I receive the prompt, but that is correct behavior.

The only thing I can think of is that maybe HexEditor is involved. I have a bunch of plugins installed (including mimeTools, NppConverter, and NppExport), but HexEditor isn't one of them. Try removing HexEditor and seeing if the problem goes away.

**Comment by alankilborn** [comment] 2024-02-27 11:46
I can reproduce in 8.6.4:

Notepad++ v8.6.4   (64-bit)
Build time : Feb 20 2024 - 00:12:59
Path : C:\NotepadPlusPlus\Misc\_NoBackup\Releases\npp.8.6.4\npp.8.6.4.portable.x64\notepad++.exe
Command Line : -multiInst
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 11 Pro (64-bit)
OS Version : 22H2
OS Build : 22621.3155
Current ANSI codepage : 1252
Plugins : 
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)

**Comment by alex77g2** [comment] 2024-02-27 18:50
I tried again, and it happens in both cases: the changed file is the visible one and if not. (there are other file tabs open, but this should not matter). It also was there since weeks.

**Comment by molsonkiko** [comment] 2024-02-27 19:10
Forgive me if you already answered, but does it matter whether the file has
unsaved changes in NPP at the time you closed?

**Comment by alex77g2** [comment] 2024-02-28 06:41
I tried now (still 8.6.2), and I changed a file in NPP (without changes from outside) and I can close NPP without reload or saving questions. (open NPP again and the change is not lost - but file marked as unsaved).
After this, I tried to change a file, touch it from outside, close NPP triggered, and reload question again.
Thanks for your work.

**Comment by alex77g2** [comment] 2024-02-28 06:56
I updated to 8.6.4 now, same thing. After this I removed hex-plugin, but still the same.

**Comment by molsonkiko** [comment] 2024-03-01 01:12
I can replicate this under the following circumstances, whether or not there are saved changes in Notepad++:

* A __portable__ install of Notepad++ 8.6.4
* Every version I've tested since Notepad++ 8.3.3, with the `-nosession` command line arg.

But interestingly, when I try Notepad++ 7.3.3, I can only replicate it when there are unsaved changes in Notepad++. If the file is saved when I close it in Notepad++ 7.3.3, I can't replicate it at all.

**Comment by alex77g2** [comment] 2024-03-01 16:43
What do you mean by "unsaved changes" precisely? Of same file or any other file (another file tab) ?
> I can replicate this under the following circumstances, whether or not there are saved changes in Notepad++:
> 
>     * A **portable** install of Notepad++ 8.6.4
> 
>     * Every version I've tested since Notepad++ 8.3.3, with the `-nosession` command line arg.
> 
> 
> But interestingly, when I try Notepad++ 7.3.3, I can only replicate it when there are unsaved changes in Notepad++. If the file is saved when I close it in Notepad++ 7.3.3, I can't replicate it at all.

**Comment by molsonkiko** [comment] 2024-03-01 17:01
By "unsaved changes" I mean you edit the document in Notepad++ and close
Notepad++ without saving the changes first

**Comment by alex77g2** [comment] 2024-03-02 09:11
Ok, I repeat your work flow (without external changes) and can close NPP even with unsaved changes and see no question (NPP terminates as expected).

**Comment by donho** [comment] 2024-06-15 03:30
Apparently it's been fixed (Tested in v8.6.8) .

**Closed by donho** 2024-06-15 03:30 UTC
