### ISSUE TITLE
Save file "new xx"? dialog is missing shortcut keys

### ISSUE THREAD

**Issue by kalenwatermeyer** [notepad-plus-plus/notepad-plus-plus#7520] opened 2019-11-06 16:39 UTC
### Description of the Issue
When closing a new or modified file, the `"Save file?"` dialog is displayed.

Previous versions would have shortcut actions for **Y**es, **N**o, **C**ancel etc, allowing the user to hit 'N' if they don't want to save the file instead of clicking the button.

Version 7.8.1 (64-bit) / Windows no longer includes the shortcut keys.

### Steps to Reproduce the Issue
1. Create a new file and add some text
2. Click the close tab for this file
3. Observe that the "save file?" dialog does not have shortcuts on the action buttons.

### Expected Behavior
Expected to see standard shortcut keys for 'Yes', 'No' etc.

### Actual Behavior
The dialog is displayed, but the button text is not linked to short cut keys
![image](https://user-images.githubusercontent.com/1957266/68318044-208fc000-008a-11ea-9c43-99bd1c56548f.png)

![image](https://user-images.githubusercontent.com/1957266/68318035-1b327580-008a-11ea-9117-10ed97356179.png)

**Comment by sasumner** [comment] 2019-11-06 18:00
Duplicate of #6223

**Closed by sasumner** 2019-11-06 18:00 UTC
