### ISSUE TITLE
Ruby Syntax Highlighting broken

### ISSUE THREAD

**Issue by rovf** [notepad-plus-plus/notepad-plus-plus#6130] opened 2019-09-06 10:02 UTC
### Description of the Issue
Highlighter does not correctly recognize the end of the regular expression in the example shown in the screenshot:

![capture_20190906_115755](https://user-images.githubusercontent.com/6795665/64419836-152a1380-d09e-11e9-84dc-6d4c1138e0d9.jpg)

Notepad++ v7.7.1   (64-bit)
Build time : Jun 16 2019 - 21:24:47
Path : C:\p\nppp64bit\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS : Windows 10 (64-bit)
Plugins : AnalysePlugin.dll AutoEolFormat.dll Comment Wrap.dll ComparePlugin.dll CustomLineNumbers.dll MenuIcons.dll mimeTools.dll NppConverter.dll NppFavorites.dll NppXmlTreeviewPlugin.dll SelectQuotedText.dll SurroundSelection.dll XBrackets.dll _CustomizeToolbar.dll

**Comment by sasumner** [comment] 2019-09-06 12:16
How about providing that as text so that interested people here can try it for themselves?  For one, I don't know enough about Ruby to pick off the (likely small) relevant portion and retype.  Or maybe it is more "larger contextual" as the very last line seems correct.

**Comment by rovf** [comment] 2019-09-06 12:22
You are right. Here is a small, completely self-example:

`x = foo ? /.*/ : bar;  puts abc`

The Highlighter gets out of step with the closing slash of the regexp, but only when followed by the period belonging to the ternary-conditional.

**Comment by sasumner** [comment] 2019-09-06 12:48
I only see one period and it occurs _before_ the closing slash, not _following_.  But maybe my confusion is not going to be cleared up as I don't have Ruby knowledge.  Perhaps an even simpler example is:

`x = foo ? /.*/ : bar`

which makes more sense to me (I'm familiar with C's ternary op).  With that change, for me it manifests as follows in Notepad++:

![image](https://user-images.githubusercontent.com/30118311/64428710-6926ff00-d082-11e9-869a-b9f489c141d0.png)

...but I'm still not sure what the period has to do with it.

But, okay, this is _lexing_, and as such it is controlled by Scintilla, so I'm going to label this issue as "depending upon Scintilla" -- which means that unless the Scintilla project can handle it properly, Notepad++ can't either.

And here's how the Scintilla demo editor handles it:

![image](https://user-images.githubusercontent.com/30118311/64428885-d175e080-d082-11e9-92be-b48cb3b201c7.png)

...which is similar so we can blame Scintilla for this.  :)

**Comment by rovf** [comment] 2019-09-06 14:14
Sorry, I meant "colon" when I mistakingly wrote "period".

Parsing goes fine until slash-period-asterisk. The following slash should mark the end of the regexp, and the colon continues the ternary conditional. The subsequent `puts` statement is already not recognized as a new statement anymore. The same is true for the part after the colon.

**Comment by zufuliu** [comment] 2019-09-06 23:41
Filled a bug report at https://sourceforge.net/p/scintilla/bugs/2126/

**Comment by vinsworldcom** [comment] 2021-02-22 14:27
@donho
@sasumner

I can confirm this is NOT fixed in Notepad++ 7.9.3 Unicode Debug using the latest Scintilla 4.4.6 DLL. There is only 1 Ruby related update to Scintilla change log since 4.2.0 related to heredocs, not this issue.  Tests show it still lexes (incorrectly) as per this issue.

Cheers.

**Comment by rdipardo** [comment] 2022-06-19 04:52
Fixed in ScintillaOrg/lexilla@aa82bf0

![scintilla-2126](https://user-images.githubusercontent.com/59004801/174466387-98a7e269-221d-4eae-ad11-387c5df2f535.png)

This can be closed once #11734 is merged

**Closed** 2022-08-09 16:38 UTC
Labels: scintilla dependent
