### ISSUE TITLE
proxy setting

### ISSUE THREAD

**Issue by iguaduju** [notepad-plus-plus/notepad-plus-plus#1408] opened 2016-01-26 07:04 UTC
i cant set proxy.
Setting proxy, but dialog is empty.

**Comment by lourdas** [comment] 2017-01-08 10:52
Setting the proxy requires to execute Notepad++ in administrator mode. If you do that, the settings are saved and restored when reopening the set updater proxy window.

This however could use some improvement. A warning maybe that to set the proxy settings would require administrator privileges.

**Comment by jm009** [comment] 2018-07-26 22:09
I had this issue on Windows Server 2008. The proxy is not saved, no matter if I open the dialog from the menu or by ``gup -options``
If I call ``gup -options`` from cmd.exe started as Administrator, it works.
What I would hope to see improved is the fact, that there is no error message. if there was an error message like "Could not be saved, no permission", this would be a hint for what to do next.

**Comment by MetaChuh** [comment] 2019-04-13 01:47
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:47 UTC
