### ISSUE TITLE
support command line encoding conversion

### ISSUE THREAD

**Issue by wqcblog** [notepad-plus-plus/notepad-plus-plus#11953] opened 2022-07-30 07:02 UTC
Does notepad++ support command line encoding conversion? Thanks

**Comment by alankilborn** [comment] 2022-07-30 11:50
Questions go here: https://community.notepad-plus-plus.org/

**Comment by ArkadiuszMichalski** [comment] 2022-08-09 16:01
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9590.

**Closed by ArkadiuszMichalski** 2022-08-09 16:01 UTC
Labels: duplicate
