### ISSUE TITLE
Modifying files on WebDav file storage fails to modify the file date and time tag 

### ISSUE THREAD

**Issue by MortenBoegsted** [notepad-plus-plus/notepad-plus-plus#14488] opened 2023-12-14 08:07 UTC
### Description of the Issue
We have an internal storage, which is opened via WebDav folder link, when editing a file (ini, txt, xml etc.) in Notepad++ version 8.5.4.0, the file modified date and time is not updating correctly. PC OS Windows 11, if using build in Notepad (microsoft) adding a space and deleting again + save file, the date and time is updating correctly.

### Steps to Reproduce the Issue

1. Open any editable file from a WebDav location
2. edit the file
3. Save
4. Observa that file date and time doesn't update

### Expected Behavior
File modified data would update to local PC time

### Actual Behavior
Keeps original file date and time tag

### Debug Information

Notepad++ v8.5.4   (64-bit)
Build time : Jun 17 2023 - 20:42:45
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 11 Enterprise (64-bit)
OS Version : 22H2
OS Build : 22621.2715
Current ANSI codepage : 1252
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by MortenBoegsted** [comment] 2023-12-14 08:09
Seems to be corrected with Notepad++ v8.6, just updated after posting the ticket, for some odd reason I didn't get the prompt to update version

**Comment by xomx** [comment] 2023-12-14 17:17
> Seems to be corrected with Notepad++ v8.6

Yes, there was a regression caused by another fix implementation (for the NTFS Alternate Data Streams), it has been fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/2337a7b5b65f19b77b4b497a239af9392a31660f .

Glad to see that it has fixed your problem, I recommend to close this issue.

**Closed** 2023-12-15 02:16 UTC
