### ISSUE TITLE
Crash while  emoji exists 

### ISSUE THREAD

**Issue by enefry** [notepad-plus-plus/notepad-plus-plus#3846] opened 2017-10-25 09:05 UTC
### Description of the Issue
Notepad++ crash while i open an objective source file include this line 
 //不要再干掉下面👇这行独自初始化WXApi的代码了，否则会影响微信支付。
demo file is : https://mega.nz/#!QDQW3TBQ!N_pNcp3g4RP6xyp_6hWxGbi9aMTbWTFv1SpUAtVoeYg
system: win10 - 1703
notepad++: 32bit v7.5.1

### Steps to Reproduce the Issue

1. open this file 
2. scroll to this line
3. crash

### Expected Behavior
view source 

### Actual Behavior
crash

### Debug Information
https://mega.nz/#!QDQW3TBQ

**Comment by SinghRajenM** [comment] 2017-10-25 14:39
I could not reproduce. It works well. It might caused by a plugin. Try to without plugin. If still happening, paste debug info here.

**Comment by enefry** [comment] 2017-10-25 14:49
crash alway:
screenshot: https://mega.nz/#!caQRDY7J!3HX5_dKtdEHjtQioSW4vS9BI8ZQ-KJdbdJSvMF37zrg

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : none

**Comment by SinghRajenM** [comment] 2017-10-25 15:00
So, the crash was caused by plugin. So it is better to close the issue here and log it in respective plugin repository.

**Comment by enefry** [comment] 2017-10-25 15:05
when i remove all plugins also crash , you can see my screenshot

**Comment by SinghRajenM** [comment] 2017-10-26 17:54
Oops!!! my bad. I read ```crash always``` as ```**crach away**```.
Anyway I think, I figured out the root cause. The crash is triggered by lexer dll. Refer the below screenshot for details.

As lexer dll is rarely changed, I leave this issue open for @donho . 
![image](https://user-images.githubusercontent.com/14791461/32068679-7c72acd0-baa4-11e7-8bb6-1ea64d1fcb01.png)

**Comment by chcg** [comment] 2018-01-16 19:59
Still crashes with 7.5.4. On loading the mentioned text from some sample.m.
(https://stackoverflow.com/questions/652186/why-do-objective-c-files-use-the-m-extension)

Interestingly I just observe this for the 32bit version, but not for 64bit.

ch in Stylecontext is:
int ch;
probably to take an unicode character, but isdigit() is just the plain char version, see 

https://docs.microsoft.com/en-US/cpp/c-runtime-library/reference/isdigit-iswdigit-isdigit-l-iswdigit-l
with

> The behavior of isdigit and _isdigit_l is undefined if c is not EOF or in the range 0 through 0xFF, inclusive. When a debug CRT library is used and c is not one of these values, the functions raise an assertion. 

What we might face here.

**Comment by MetaChuh** [comment] 2019-05-02 14:03
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-02 14:03 UTC
Labels: not reproducible
