### ISSUE TITLE
python f-string color incorrect

### ISSUE THREAD

**Issue by BlownSnail** [notepad-plus-plus/notepad-plus-plus#5735] opened 2019-06-03 12:26 UTC
### Description of the Issue
Python fstring should have same display style as string, but it just display as normal text.

### Steps to Reproduce the Issue
1. Switch language to python
2. type
```
f''f""
u''u""
r''r""
b''b""
''""
```

### Expected Behavior
The fstring should also be orange.

### Actual Behavior
The fstring is white as normal text.

### Debug Information
Notepad++ v7.7   (32-bit)
Build time : May 19 2019 - 13:08:20
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NppTextFX.dll 

![766](https://user-images.githubusercontent.com/47628315/58801600-9310f580-863d-11e9-88a2-5e999fc9c896.png)
![77](https://user-images.githubusercontent.com/47628315/58801601-9310f580-863d-11e9-962c-ce9a4b5a3b85.png)

Test under 32bit of 7.6.6 and 7.7, themes files in `%APPDATA%\Notepad++\themes` is deleted before install different verion.

**Comment by sasumner** [comment] 2019-06-03 12:28
Duplicate of #5698

**Comment by MetaChuh** [comment] 2019-06-03 12:35
fixed in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6ae03f64e8b7f328091ad6a6ee762bccae03e68d

**Closed by MetaChuh** 2019-06-03 12:35 UTC
Labels: duplicate
