### ISSUE TITLE
Missing undo after drag-and-drop of text from Notepad++ to external destination

### ISSUE THREAD

**Issue by mrandreastoth** [notepad-plus-plus/notepad-plus-plus#7869] opened 2020-01-20 14:50 UTC
### Description of the Issue

Text cut by drag-and-drop of text from Notepad++ to external destination does not recover following undo.

### Steps to Reproduce the Issue

1. Highlight text in an open Notepad++ document.

2. Drag-and-drop text to external destination (not many destinations want to accept, in fact, the only destination I could find was the destination that had me discover this in the first place, and that is a rare web-based e-mail client https://webmail.xtra.co.nz/appsuite/)

3. Dragged text disappears from the Notepad++ document.

4. Execute undo action in Notepad++ document.

### Expected Behavior

Undo to recover the dragged-and-dropped text.

### Actual Behavior

Undo did not recover the dragged-and-dropped text.

### Debug Information

Notepad++ v7.8.2   (64-bit)
Build time : Dec  4 2019 - 01:39:49
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1184
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by sasumner** [comment] 2020-01-20 18:24
You're probably going to have to come up with a more-common drop target that works with Notepad++ in order for someone to reproduce...

**Comment by ArkadiuszMichalski** [comment] 2020-09-16 22:26
@mrandreastoth 
You still have this problem with new Notepad++ 7.9? I check some programs and can't reproduce:
- for Chrome data is copy (not cut), so no problem in Notepad++
- for Firefox, Thunderbird or MS Word data is cut but undo works in Notepad++

**Comment by sasumner** [comment] 2020-09-16 22:47
Closing because my own testing with drag-n-drop move from N++ to MS Word is undoable in N++.
Tested in 7.8.9

**Closed by sasumner** 2020-09-16 22:47 UTC
