### ISSUE TITLE
"Use new style save dialog" resets upon restart

### ISSUE THREAD

**Issue by M1dknyte** [notepad-plus-plus/notepad-plus-plus#2829] opened 2017-01-26 19:49 UTC
### Description of the Issue

For v7.3.1, the Preferences > Default Directory  > "Use new style save dialog" box gets rechecked when restarting Notepad++. 

### Steps to Reproduce the Issue

1. Open Preferences > Default Directory
2. Uncheck the "Use new style save dialog" box
3. Restart Notepad++
4. The "Use new style save dialog" box will have a checkmark again

### Expected Behavior

The "Use new style save dialog" box should say unchecked (works in v7.3.0)

### Actual Behavior

The "Use new style save dialog" box has a checkmark again.

### Debug Information

Notepad++ v7.3.1   (32-bit)
Build time : Jan 17 2017 - 00:21:10
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment] 2017-01-27 14:51
Duplicate of #2814 

Fixed by 1a0e6d76118ff55640c273f32fa0e64d2033f04f

This will be in the next release.

**Closed by dail8859** 2017-01-27 14:51 UTC
Labels: duplicate
