### ISSUE TITLE
Function List - behaviour

### ISSUE THREAD

**Issue by Docara** [notepad-plus-plus/notepad-plus-plus#9108] opened 2020-11-05 13:17 UTC
I don't know if this is by design but it's VERY counterintuitive if it is
Working on a C file.

I have the Function List dialogue box showing on screen and there are multiple instances of the same function displayed. To me this is wrong!
There is only ever one instance of a function so I would expect to be able to double click on it and it takes me to the start of the function. What is happening now is the function calls are also being displayed within the program. 

By all means have this functionality but make it a secondary option within the Function List dialogue box. 
![Capture](https://user-images.githubusercontent.com/70949806/98245634-1fc58e80-1f69-11eb-8f97-1e5ea39ddb67.PNG)

**Comment by MAPJe71** [comment] 2020-11-05 19:02
As you did'nt follow the report template please read [FAQ desk: Request for help without sufficient information to help you](https://community.notepad-plus-plus.org/topic/15739/faq-desk-request-for-help-without-sufficient-information-to-help-you).
Yes, I know you're not really asking for help but the point is that without sufficient information analysis of the issue is impossible.

**Comment by sasumner** [comment] 2020-11-05 19:16
Closing as duplicate; leaving 4794 open

**Closed by sasumner** 2020-11-05 19:16 UTC
