### ISSUE TITLE
function list 

### ISSUE THREAD

**Issue by gianbp** [notepad-plus-plus/notepad-plus-plus#10484] opened 2021-09-01 13:46 UTC
### Description of the Issue

javascript source,  js extension
a function declaration follwed by comment on same line is not listed in function list panel

screenshot

### Expected Behavior

list of all functions in source

### Actual Behavior

function with in line comment not listed

### Debug Information

![image](https://user-images.githubusercontent.com/66299876/131681130-1ebaf938-1e45-4e67-91bb-ed31e7e6aae2.png)

**Comment by ArkadiuszMichalski** [comment] 2021-09-01 14:59
Duplicate of/related to https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3685, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4094.

**Closed by ArkadiuszMichalski** 2021-09-01 14:59 UTC
