### ISSUE TITLE
Downloader for updating to version 7.5.7 displays erroneous "percent complete"

### ISSUE THREAD

**Issue by jnfrye** [notepad-plus-plus/notepad-plus-plus#4666] opened 2018-07-14 18:53 UTC
### Description of the Issue
When I opened Notepad++ today, it prompted me to update to the latest version. Upon clicking "Yes" to download, the "percent complete" prompt appeared and displayed the percent complete as "9223372036854775808 %" for a moment (see attached screenshot). It corrected itself shortly after and displayed the correct percent complete.

<img width="328" alt="ultra_complete_download" src="https://user-images.githubusercontent.com/10409297/42727423-2cd84106-875b-11e8-9b20-ef9a35295fb7.png">

### Steps to Reproduce the Issue
1. Install an older version (I was able to repro this with version 7.4.2)
2. Click "Update Notepad++" in the "?" menu
3. Click "Yes" when the prompt to download the new version appears
4. Observe the percent complete displayed

### Expected Behavior
"Percent downloaded" should be between 0 and 100

### Actual Behavior
"Percent downloaded" was above 100.

### Debug Information
Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by jnfrye** [comment] 2018-07-14 18:54
Let me know if you need any more information. Thanks!

**Comment by SinghRajenM** [comment] 2018-07-21 19:31
Duplicate of #4069 . Also this is an external component (wingup), so can be reported there.

**Comment by jnfrye** [comment] 2018-07-21 19:43
@SinghRajenM Is this where I should post? https://github.com/gup4win/wingup

**Comment by SinghRajenM** [comment] 2018-07-21 19:55
Yes, https://github.com/gup4win/wingup is correct place.

**Comment by ArkadiuszMichalski** [comment] 2022-08-18 22:46
Duplicate of #4069

**Closed by ArkadiuszMichalski** 2022-08-18 22:46 UTC
