### ISSUE TITLE
Feature request: Display e.g. CR/LF in a different colour

### ISSUE THREAD

**Issue by DietmarSchwertberger** [notepad-plus-plus/notepad-plus-plus#11413] opened 2022-03-20 14:00 UTC
Recent Scintilla versions have support for displaying e.g. CR/LF in a different colour.

Search https://www.scintilla.org/ScintillaDoc.html for SC_REPRESENTATION_COLOUR and SCI_SETREPRESENTATIONCOLOUR

It would be great if this feature makes it into N++ as well.

Some messages on the Scintilla mailing list:
https://groups.google.com/g/scintilla-interest/c/-zLNwzJ18Q4/m/EZfyqGEaAQAJ
Not sure whether this is related. The search engine finds it if one searches for the SC_/SCI_ constants, but I don't see why:
https://groups.google.com/g/scintilla-interest/c/g1Ypo8qijJU/m/o9zZCGSSAAAJ

The now closed feature request for Scintilla: https://sourceforge.net/p/scintilla/feature-requests/1129/

**Comment by dail8859** [comment] 2022-03-21 11:28
Duplicate of #4070

**Comment by donho** [comment] 2022-05-20 03:00
According Scintilla documentation here:
https://www.scintilla.org/ScintillaDoc.html#SCI_SETREPRESENTATION

I have tried the following code with no visual effect change:
```cpp
	char crlf[13] = "\x0a\x0d";
	_mainEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(crlf), SC_REPRESENTATION_COLOUR);
	_subEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(crlf), SC_REPRESENTATION_COLOUR);

	_mainEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(crlf), RGB(0x00, 0x00, 0xFF));
	_subEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(crlf), RGB(0xFF, 0x00, 0x00));
```
I have also tried `char crlf[13] = "\r\n";` without any success.

@DietmarSchwertberger Could you give me some hints to make it work?

**Comment by rimrul** [comment] 2022-05-20 06:12
> The encodedCharacter parameter is a NUL-terminated string of the bytes for one character in the current encoding. This can not be used to set a representation for multiple-character strings.

I think the issue is just that you need to do CR and LF separately.

**Comment by ozone10** [comment] 2022-05-20 14:14
@donho 
Notepad++ is not using combined "crlf" so it will color only "cr" I think. So it's better to color "cr" and "lf" separately.
`SCI_SETREPRESENTATIONCOLOUR` also use color with transparency so this could have some effect.

And mainly this need to be set after lexer is done styling otherwise it will override it.

You can try code below, insert it for example in `void Notepad_plus::launchClipboardHistoryPanel()`
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3750cf8fa34470e3196fd041254960d88534cd80/PowerEditor/src/Notepad_plus.cpp#L6661

and than open clipboard panel

```
const wchar_t* cr = L"\x0d";
const wchar_t* lf = L"\x0a";

_mainEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(cr), 0xFF00FF00);
_mainEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(lf), 0xFF00FFFF);
_subEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(cr), 0xFF00FF00);
_subEditView.execute(SCI_SETREPRESENTATIONCOLOUR, reinterpret_cast<WPARAM>(lf), 0xFF00FFFF);

_mainEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(cr), SC_REPRESENTATION_COLOUR);
_mainEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(lf), SC_REPRESENTATION_COLOUR);
_subEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(cr), SC_REPRESENTATION_COLOUR);
_subEditView.execute(SCI_SETREPRESENTATIONAPPEARANCE, reinterpret_cast<WPARAM>(lf), SC_REPRESENTATION_COLOUR);
```

btw `char crlf[13] = "\x0a\x0d";` should be `char crlf[13] = "\x0d\x0a";`

Also this is mainly speculation as I cannot test it now.

**Comment by donho** [comment] 2022-05-20 15:39
@ozone10 
It's working. Thank you!
I use char* instead of wchar_t*.

Strangely, the same code doesn't work in `LRESULT Notepad_plus::init(HWND hwnd)`:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/3750cf8fa34470e3196fd041254960d88534cd80/PowerEditor/src/Notepad_plus.cpp#L343

There must be some stuffs needed by this feature in Scintilla which are not yet initialized.
I'll figure it out.

**Comment by donho** [comment] 2022-05-20 18:07
After some tries, I don't really think this feature is interesting to the users:

![image](https://user-images.githubusercontent.com/90293/169587179-2477403d-8a58-4a02-aa98-5c92afe814e6.png)

It would be more interesting if we can set the (background) colour to the BLOB mode.

**Comment by alankilborn** [comment] 2022-05-20 18:10
>I don't really think this feature is interesting to the users

Your screenshot sample probably makes users that want to see line-ending characters less unhappy than current behavior with visible line-endings. :-)

**Comment by donho** [comment] 2022-05-20 18:38
> Your screenshot sample probably makes users that want to see line-ending characters less unhappy than current behavior with visible line-endings. :-)

Are you saying that the screenshot I provided is better than current behaviour?

**Comment by DietmarSchwertberger** [comment] 2022-05-20 18:42
OK, yes, seems that the Scintilla modification has several components, acc. to https://groups.google.com/g/scintilla-interest/c/-zLNwzJ18Q4/m/EZfyqGEaAQAJ

To quote:
"Attached is a patch that 
 - allows setting an unadorned plain appearance with no surrounding rounded rectangle for a representation with SCI_SETREPRESENTATIONAPPEARANCE
 - A colour can be set with SCI_SETREPRESENTATIONCOLOUR ."

The first part is indeed not interesting, I agree, but the second one would be great to have.
There is also a screenshot https://www.scintilla.org/Representations.png

The current (LF) blob is fine IMHO, it's just the solid colour that is too distracting.
(Maybe there is a good combined CR/LF blob as well. The Paragraph symbol from the screenshot is certainly not a good idea as it hides information.)

**Comment by alankilborn** [comment] 2022-05-20 18:43
>Are you saying that the screenshot I provided is better than current behaviour?

Yes, because current behavior is way too heavy.
When it is turned on, the CRLF markers are so heavy that they pull your attention away from what it should be on.
With the sample in your screenshot, the line-endings are visible, but not overbearing.
That's my feeling about it.

**Closed** 2022-06-12 17:41 UTC
