### ISSUE TITLE
Access Violation on Exit

### ISSUE THREAD

**Issue by postiffm** [notepad-plus-plus/notepad-plus-plus#4021] opened 2017-12-26 02:14 UTC
### Description of the Issue
Whenever I exit from 7.5.3, I get a window titled "Exception" with contents "Access violation" and an OK button. Hit OK. Then it repeats one time. Hit OK again. Notepad ++ exits.

### Steps to Reproduce the Issue
See above.

### Expected Behavior
No access violation.

### Actual Behavior
See above.

### Debug Information
Notepad++ v7.5.3   (32-bit)
Build time : Dec  5 2017 - 10:45:46
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : ComparePlugin.dll DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll NppTextFX.dll PluginManager.dll 

This started occuring immediately upon update to 7.5.3. I never encountered this behavior in earlier versions.

**Comment by MAPJe71** [comment] 2017-12-26 03:23
Duplicate of #3961.

**Comment by donho** [comment] 2017-12-27 01:24
@postiffm Can you reproduce the crash steadily?

**Comment by postiffm** [comment] 2017-12-27 01:26
Every time, no problem.

**Comment by postiffm** [comment] 2017-12-27 01:27
Can I do something to get a core dump or similar crash info for you to examine?

**Comment by donho** [comment] 2017-12-27 01:32
Could you download this zip and unzip to "C:\Program Files (x86)\Notepad++\" to replace your old "notepad++.exe"
[npp.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/1588144/npp.zip)

Launch Notepad++ and make it crash.
Then get log file from "c:\tmp\log.txt" and attach the file here please?

**Comment by postiffm** [comment] 2017-12-27 01:37
Expanded and copied to Program Files (x86). Gave me a "publisher could not be verified" warning to begin with. Then, upon starting, almost immediately gave me an error:
Notepad+ + :  a free (GNU) source code editor has stopped working...
All I could do was click OK and the program was terminated.

**Comment by postiffm** [comment] 2017-12-27 01:41
I updated to latest plugin manager and DSpellCheck 1.3.3 and no better.

**Comment by postiffm** [comment] 2017-12-27 01:46
I have a .DMP file from Task Manager, after I attempt to exit, and while the dialog box "Access violation" is open and awaiting my OK. How shall I upload it--.DMP is not supported, and .zip is 30MB. Github doesn't like it because it is too big.

**Comment by postiffm** [comment] 2017-12-27 01:47
Now, the access violation is gone. Strange. I cannot reproduce it now.

**Comment by donho** [comment] 2017-12-27 01:49
Could you go back to DSpellCheck 1.3.2 ?

**Comment by donho** [comment] 2017-12-27 01:51
> I have a .DMP file from Task Manager, after I attempt to exit, and while the dialog box "Access violation" is open and awaiting my OK. How shall I upload it--.DMP is not supported, and .zip is 30MB. Github doesn't like it because it is too big.

Could you send it to me: don.h@free.fr

**Comment by postiffm** [comment] 2017-12-27 03:21
I am not sure how to "downgrade" a notepad++ plugin, but I'm willing to do it.

**Comment by postiffm** [comment] 2017-12-27 03:23
My email won't let me send the attachment. So, you can grab it here: http://fbcaa.org/uploads/notepad++.DMP.zip

**Comment by postiffm** [comment] 2017-12-27 03:48
I cannot "remove" the DSpellCheck plugin. Upon restart of Notepadd++, it hangs when it tries to delete the DSpellCheck.dll file (v 1.3.3).

**Comment by postiffm** [comment] 2017-12-27 04:00
Replacing DLL does show old version in the About menu for the DSpellCheck plugin. But the access violation is still gone.

**Comment by donho** [comment] 2017-12-27 11:34
http://fbcaa.org/ is not reachable to me. Are you sure it's the good host name?

**Closed** 2017-12-27 17:20 UTC

**Comment by donho** [comment] 2017-12-27 17:53
@postiffm 
Could you please download DSpellCheck v1.3.5
https://github.com/Predelnik/DSpellCheck/releases/tag/v1.3.5 (same link of above provided by @Predelnik )
And confirm that issue has been fixed in this version?

**Comment by postiffm** [comment] 2017-12-27 20:38
Sorry about the website. Our server has been under some sort of attack for the past 9 hours or so.

DSpellCheck 1.3.5 installed and crash is not happening now.
