### ISSUE TITLE
Unable to update Notepad++

### ISSUE THREAD

**Issue by PalashBansal** [notepad-plus-plus/notepad-plus-plus#2517] opened 2016-11-03 06:35 UTC
### Description of the Issue

On clicking "Update Notepad++" option in "?" menu item, error is appearing, which is not understandable by end user. Either end user must be shown, what to do next in case of this error or this problem should not appear at all.
![image](https://cloud.githubusercontent.com/assets/6822117/19957450/c3c56e58-a1bc-11e6-9f66-3e5f411f5371.png)

This issue is appearing in Notepad++v7.2 (64-bit) Build time: Nov  2 2016 - 11:27:56
Same error also coming in 7.1 version.

### Steps to Reproduce the Issue

1. Click menu item "?"
2. Select option "Update Notepad++" from dropdown.

### Expected Behavior

Notepad++ must start updating, or if not possible, then should give user instructions on what to do next to resolve this problem, or gives a good understandable message.

### Actual Behavior

"curl error" is coming.

**Comment by dail8859** [comment] 2016-11-04 12:48
Can you post the debug information?

**Comment by PalashBansal** [comment] 2016-11-07 06:04
@dail8859  Please find below Debug info. -

**Notepad++ v7.2   (64-bit)
Build time : Nov  2 2016 - 11:27:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7
Plugins : mimeTools.dll NppConverter.dll** 

Please let me know if there is anything else required.

**Comment by Eagle3386** [comment] 2017-12-06 15:28
This might be a duplicate of #1237.

**Comment by MetaChuh** [comment] 2019-05-01 20:28
please update your notepad++ manually to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 20:28 UTC
Labels: not reproducible
