### ISSUE TITLE
[BUG] save as admin fails sometimes - filebuffer flushing fail

### ISSUE THREAD

**Issue by Uj947nXmRqV2nRaWshKtHzTvckUUpD** [notepad-plus-plus/notepad-plus-plus#14990] opened 2024-04-13 13:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Issue

attempting to save a file as admin

### Steps To Reproduce

1.  in notepad++ without admin open a txt file from c:\program files (x86)
2.  empty the file
3.  press save

### Current Behavior

filebuffer flushing fail error

### Expected Behavior

saves ok

### Debug Information

```shell
Notepad++ v8.6.5   (64-bit)
Build time : Mar 29 2024 - 17:04:43
Path : E:\Apps\Notepad++\notepad++.exe
Command Line : "<...>"
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
Periodic Backup : ON
OS Name : Windows 11 Pro (64-bit
OS Version : 23H2
OS Build : 22631.3447
Current ANSI codepage : 1252
Plugins : 
    ComparePlugin (2.0.2)
    JSMinNPP (1.2312)
    Linefilter3 (1)
    mimeTools (3.1)
    NppConverter (4.6)
    NppExport (0.4)
    NppFavorites (1.0.0.1)
    NppSaveAsAdmin (1.0.211)
    _CustomizeToolbar (5.3)
```

### Anything else?

Probably related with https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10751

**Comment by SubActif** [comment] 2024-04-13 15:36
I encountered the same problem yesterday when trying to save a document that requested administrator rights.

This is the first time I've encountered this problem even though I use this type of recording very often. For example, I adapt the FR translation of Notepad++ and so I often open its files in "_C:\Program Files\Notepad++_" and I never had a problem except yesterday.

I thought it was going to close Notepad++ but not at all, I tried to save again right after and it worked, I don't have the expertise for this kind of thing, but out of curiosity I looked here and I see that I am not the only one to have had this error message.

![notepad++_rpCM80nWFA](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/17392472/4a55aa6a-4bfd-4ed3-939f-7ef77edf8b3e)

**Comment by xomx** [comment] 2024-04-13 20:28
Cannot reproduce. I am able to save to that "C:\\Program Files (x86)\\..." or "C:\\Program Files\\..." without such error message. I tried both the launching the N++ from the start as admin ("Run as administrator"...) and the N++ inbuilt "Do you want to launch Notepad++ in Administrator mode" way until during the saving attempt.

![npp-admin-save-test-ok](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/26489012-c2bf-4735-b73a-c1a8e3b68f5f)

Also the error reported (6 - ERROR_INVALID_HANDLE) is interesting because it makes no sense at all. The flushing error & report originates from here (at this stage the file has to be already successfylly opened & saved via the `CreateFile` & `WriteFile` WINAPIs, now it is going to be flushed and closed via its `_hFile` file handle):
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/906f6e4386cf5acebfc1ace3aac9b83b26e7c70a/PowerEditor/src/MISC/Common/FileInterface.cpp#L91-L102

The `isOpened()` returns `true` only when the `_hFile != INVALID_HANDLE_VALUE`. So evidently we still have (if there had already been an error with the file handle opening or writing via that file handle, you would have been notified by a different error message earlier...) a valid file handle but then the `FlushFileBuffers(_hFile)` call fails with that `INVALID_HANDLE_VALUE`!

> ..., I tried to save again right after and it worked, 

So it smells like a problem with some external process interfering with the N++ file saving (AV?).

**Comment by alankilborn** [comment] 2024-04-13 20:38
I've observed this same problem behavior for many years with Notepad++.

**Comment by xomx** [comment] 2024-04-13 20:49
@alankilborn 
Do you mean you sometimes have to try to save a file twice before it finally succeeds?
Only to that "C:\\Program Files\\..." places or?

I have never experienced that. Maybe it is because I stopped using any antivirus many years ago ;-)

**Comment by xomx** [comment] 2024-04-13 21:24
@tarkett2018 
Thanks, I can reproduce it with that plugin now.

**Comment by alankilborn** [comment] 2024-04-13 23:01
> @alankilborn
> Do you mean you sometimes have to try to save a file twice before it finally succeeds?

Yes; it is very occasional.

> Only to that "C:\Program Files\..." places or?

No, I'm not saving to any unusual place (unusual in the sense that it would require some sort of elevated access).

**Comment by xomx** [comment] 2024-04-14 00:57
@donho 
Thanks to the new `FlushFileBuffers` error-reporting N++ capability, we have identified possible source of (some/all?) N++ data flushing problems - the NppSaveAsAdmin plugin.

This plugin installs a N++ `Win32_IO_File::Win32_IO_File` `CreateFile` WINAPI hook, which is then trying to call down the original N++ `CreateFile`:
https://github.com/Hsilgos/nppsaveasadmin/blob/ed402077aedd458b834b64c6e4719726b89b73f0/NppSaveAsAdminLib/plugin/SaveAsAdminImpl.cpp#L62

If that N++ call fails with the `ERROR_ACCESS_DENIED`, the NppSaveAsAdmin plugin hook knows that it needs to do its job (for that it [creates pipes](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea) and launches its own external app "NppAdminAccess.exe" via the ShellExecuteExW). Anyway, this all means that the N++ file handle then can fail in the final `FlushFileBuffers` (an [example](https://stackoverflow.com/questions/10451369/flushfilebuffers-error-handle-is-invalid-error-number-6) of such failing because of the remote process involved).

I will create a new issue in the NppSaveAsAdmin repo pointing here. Until this problem is fixed there, I do not recommend to use that plugin.

**Comment by alankilborn** [comment] 2024-04-14 11:08
BTW, I do not, and never have, used the _SaveAsAdmin_ plugin.
And I still, very occasionally, have to do a double-save.

**Comment by donho** [comment] 2024-04-14 19:19
@xomx 
> So I was right that it is a problem with some external process interfering with the N++ file saving.

That reminds me another crash issue reported by users - it turned out an internal value of Notepad++ (a string if I recall well) used by another application (NVDA?) for "synchronize" with Notepad++, and the usage of the value has been changed from a version of Notepad++, then the drama happened. (I found out by searching this special value in google, the same string has been found in their code, LOL).
 
Let me say "congrats" the 2nd time for the implementation in the same day. It's really nice to learn that we are not responsible for some bugs in Notepad++ :)

BTW, should I close the issue?

**Comment by xomx** [comment] 2024-04-14 20:56
@donho 
> should I close the issue?

IMO - yes.

I would like to rather keep this issue open and fix the NppSaveAsAdmin plugin myself, but I know I will not have a time for that :-(

I also find it overkill to use these powerful coding techniques (and thus also potentially very dangerous) for only one small functionality, which is even a duplicate of the already existing N++ one (built-in "You want to run Notepad++ in administrator mode"...). 

And BTW I see this hard-to-detect bug as one of the possible reasons that despite of our long time effort to limit the NUL-bug issues occurrences by using the FlushFileBuffers trick, users still from time to time reported some new ones, maybe because the FlushFileBuffers could fail silently without our knowledge before.

So maybe consider to put this plugin temporary on the blacklist? Or at least some note in the Plugins Admin?

**Comment by xomx** [comment] 2024-04-14 21:08
@alankilborn 
> BTW, I do not, and never have, used the SaveAsAdmin plugin.
And I still, very occasionally, have to do a double-save.

But then you cannot have the same error message as the users in this issue. So what is your one? Or there is not any, just it needs to hit the save twice?

Could you also list here your common plugins? (maybe there will be one among them that uses similar techniques as the NppSaveAsAdmin...)

**Comment by donho** [comment] 2024-04-15 00:30
@xomx 
> I also find it overkill to use these powerful coding techniques (and thus also potentially very dangerous) for only one small functionality, which is even a duplicate of the already existing N++ one (built-in "You want to run Notepad++ in administrator mode"...).

I'm asking myself why don't we offer this feature directly so it could avoid such situation.
OTOH, it needs another executable binary which might even make more complex...

> And BTW I see this hard-to-detect bug as one of the possible reasons that despite of our long time effort to limit the NUL-bug issues occurrences by using the FlushFileBuffers trick, users still from time to time reported some new ones, maybe because the FlushFileBuffers could fail silently without our knowledge before.

NUL chars issue was what I want to point out for this discover indeed. I have do a quick search - however, in the very little **Debug Info** (only 1) I didn't see the plugin in question in the list. I really hope NUL chars issue won't happen again, but it it does, the 1st thing we ask should be debug info.

Furthermore, I would add short log to end session critical zone as following:
```cpp
flushError = ::GetLastError();

if (!nppParam.isEndSessionCritical())
{
    ...
} 
else
{
    // writing log here 
}
```
so if it happens again we'll ask user for **"nppFlushFileBuffersFails.log"**.

> So maybe consider to put this plugin temporary on the blacklist? Or at least some note in the Plugins Admin?

For the current version of Plugin NppSaveAsAdmin, I can mark incompatible with Notepad++ v8.6.5 in nppPluginList.
If the bug is fixed in the plugin, then plugin author will update in nppPluginList.

**Closed** 2024-04-15 12:48 UTC

**Comment by Samoreen** [comment] 2024-05-02 10:09
Hi,

This problem also appeared recently on my system. I tried to temporary fix it by changing the notepad++.exe properties and make it systematically run "as administrator". This eliminated the issue but introduced a new one : the context menu command "Edit with Notepad++" immediately became inactive (no effect, no error message). I then removed the NppSaveAsAdmin plugin and the "Edit with Notepad++" context menu command worked again.

So, now Notepad++ is always running "as admin", the NppSaveAsAdmin plugin is disabled and everything is fine. This is an acceptable temporary fix for me.

Hope this help fix the problem.

**Comment by Samoreen** [comment] 2024-05-02 11:31
> i just disabled the plugin. no need to run as admin

If you need to edit a file that is located e.g. in a subfolder of Program Files, I think that Notepad++ needs to be run "as an administrator". Since I need to do this regularly by using the Notepad++ context menu, I need either a working NppSaveAsAdmin plugin (which I used until now) or to set the notepad++.exe properties adequately.

**Comment by xomx** [comment] 2024-05-02 12:16
@Samoreen 

Running N++ as an admin all the time has some inconveniences included (that aforementioned context menu issues, drag&drop files issues - elevated vs non-elevated..., etc.). Just try to open, edit and save such a protected file like:

![npp-save-as-admin-needed](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/011c4e46-2775-47f3-bf61-fd8b3325d44e)

![npp-save-as-admin-needed-after-UAC](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/c5b94a51-4476-44a2-b868-3df00730ce56)

**Comment by Fredrik-69** [comment] 2024-05-06 18:32
Sure, but when you re-open Notepad++ as Administrator, the changes you just made in the non-admin session are gone.

**Comment by xomx** [comment] 2024-05-07 08:40
@Fredrik-69 
Are you using N++ multi-instance mode?

Because as you can see from the pics in my previous post - the edits to the opened protected doc are still there after restarting in admin mode. Only the change-history markers are gone (that orange bar at line 2 in my pic).

But when I set my N++ to "Always in multi-instance mode" and restarted it, then trying to do the same thing resulted in the text edits I made being gone in the newly opened admin-mode instance of N++, indeed.

**Comment by Fredrik-69** [comment] 2024-05-07 12:54
Nope, always mono-instance. When the new adminwindow opens it is identical to what is saved on disk. The other non-admin windows with my unsaved changes is also there in the background so I can copy the made modifications from it to the new elevated one. It works even if it's not as smooth as with the saveAsAdmin plugin.

**Comment by xomx** [comment] 2024-05-07 14:14
@Fredrik-69 
Ok, I quickly checked the relevant N++ src - so then you must have the Preferences > Backup > "Enable session snapshot and periodic backup" OFF (?)

This is the current implementation logic behind:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/eb627b0677495c2b6d85d15eaf82a74ef6f38795/PowerEditor/src/NppIO.cpp#L662-L663

- so there is a nice bonus when you have the N++ snapshot feature ON (but multi-inst OFF) - N++ uses automatically that snapshot (with your changes in the protected file...) for the launched elevated N++ instance...

...

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/eb627b0677495c2b6d85d15eaf82a74ef6f38795/PowerEditor/src/NppIO.cpp#L698-L699

---

A note for a possible future improvement for active N++ multi-inst mode or disabled snapshot mode..

As the N++ already disables some WinVista+ security measures, namely the [WM_COPYDATA](https://learn.microsoft.com/en-us/windows/win32/dataxchg/wm-copydata) restriction between elevated/unelevated process:
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/eb627b0677495c2b6d85d15eaf82a74ef6f38795/PowerEditor/src/winmain.cpp#L33-L44

there is a possibility to transfer the current N++ filebuffer/tab data to the already running elevated N++ instance just by using the WM_COPYDATA ... (it will not be as easy as I wrote here but it should be doable somehow).

**Comment by Fredrik-69** [comment] 2024-05-07 15:28
Yes that is true. I do not want to remember and restore previously open files and tabs for every new session.
Then I understand why - thank you very much for the explanation :-)

**Comment by isillo** [comment] 2024-05-15 12:10
Can somebody please update "Save as admin" plugin so it can be loaded again? Thanks.

**Comment by alankilborn** [comment] 2024-05-15 12:12
> Can somebody please update "Save as admin" plugin

This plugin is not maintained by Notepad++ development team (thus you are asking for something in the wrong place).

**Comment by pebl-hank** [comment] 2024-05-15 13:46
When I open a file that is protected by UAC, NPP asks me to open in admin mode when I try to save it. When I do that, NPP starts in admin mode without loading my modifications. Can that be changed?

**Comment by xomx** [comment] 2024-05-16 12:43
@pebl-hank 
> NPP starts in admin mode without loading my modifications. Can that be changed?

Immediately - as I commented above, when you enable the Preferences > Backup > "Enable session snapshot and periodic backup".

Otherwise, it requires additional coding.

**Comment by pebl-hank** [comment] 2024-05-22 06:51
I intentionally disabled that because I need to start with a fresh session when NPP starts.

**Comment by dinkumoil** [comment] 2024-06-15 10:51
@isillo @pebl-hank
I have never used Notepad++'s session snapshot and periodic backup feature, nor do I want Windows to decide when to install updates and restart my computer automatically (and took measures to stop it from doing so), so I have never encountered the problem of NUL char file corruption. That's the reason why I'm not happy with the disablement of the _NppSaveAsAdmin_ plugin, too.

My workaround is to patch the version info of the plugin's DLL file to outwit Notepad++'s compatibility check in _PluginsAdmin_. This can be done with the small tool [Resource Hacker](https://www.angusj.com/resourcehacker/). I set the version number from 1.0.211 to 1.0.212, so the plugin can be used again. After saving a file with the plugin Notepad++ shows an error dialog mentioning an invalid handle but nevertheless the file gets saved correctly.

The other option, patching Notepad++'s _nppPluginList.dll_ file, doesn't work because this file is signed. Any changes of this file prevents it from being loaded with Notepad++.

**Comment by Montigomo** [comment] 2025-01-11 14:26
Get this warning when saving edited files in a mapped folder from a network share.

**Comment by xomx** [comment] 2025-01-11 16:14
@Montigomo 
Could you please append here your Notepad++ menu > ? > Debug Info... ?

And could you look in the Windows Event Viewer for a possible `FlushFileBuffers` error log?
- press WinKey+R, type there `eventvwr.msc /c:"System"` and press OK
- wait for attaching to the Windows System Logs
- look there for any sign of a file cache failure around the date your problem occurred (it can have different forms, e.g. "Invalid Device Request", "Disk Controller Error", "Delayed Write failed"...)

Alternatively you can use utilities like [ProcMon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) while repeating your error situation to get more details (if you are able/willing to do so).

So far I have only one idea what could happen. We have already noticed that some users' network storage can [incorrectly report](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/15776#issuecomment-2470075264) the directory-flag attribute for an open file to N++. And I know that the FlushFileBuffers WINAPI call used by the N++ [fails on a directory](https://stackoverflow.com/questions/56661972/windows-flushfilebuffers-system-call-fails-on-network-mapped-drive).
