### ISSUE TITLE
[Feature request] Modify Lines/Block - Prefix/Append text to lines

### ISSUE THREAD

**Issue by adrian-green** [notepad-plus-plus/notepad-plus-plus#9786] opened 2021-04-21 00:01 UTC
### Description of the Issue
It is frequently useful to be able to mass update lines of text by prefixing and/or appending text.

The editor Notepad2-mod has this under Edit > Block > Modify Lines...

![image](https://user-images.githubusercontent.com/3497084/115476897-241b0500-a286-11eb-81a5-f92e7601ef9a.png)

I realise that much of the same behaviour can be achieved using regexes and find/replace, however it usually takes multiple passes, and usually selecting "In selection" - all of which takes a while.

It'd be nice to just have basic prefix/append text built in as a core manipulation.

### Expected Behavior
Prefixes and/or Appends supplied characters to each line of the selected block.

**Comment by sasumner** [comment] 2021-04-21 01:34
Duplicate of #9779

**Closed by sasumner** 2021-04-21 01:34 UTC
