### ISSUE TITLE
Foreground Color of selected text cannot be changed

### ISSUE THREAD

**Issue by richlux** [notepad-plus-plus/notepad-plus-plus#3397] opened 2017-06-14 01:41 UTC
### Description of the Issue

Notepad++ does not use the standard selected text colors of white text on blue background. Because of this, the user should be able to change both the foreground and background colors of selected text. However, using the Style Configurator  and changing the Foreground Color of selected text does nothing and the color is always black. 

### Steps to Reproduce the Issue

1. Click "Settings" 
2. Click "Style Configurator"
3. Select "Global Style" 
4. Select "Selected text colour"
5. Change the foreground color and save the changes.

### Expected Behavior

The foreground text color of selected text should  change. Alternatively, the default secret text color should be the Windows standard OD white text on blue background. 
 
### Actual Behavior

The foreground text color of selected text does not change.

### Debug Information

Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll PluginManager.dll 

The color of the selected text in the npp dialog boxes as shown below is the windows standard and should be available in the npp editor. 
![2017-06-13_212346](https://user-images.githubusercontent.com/25157703/27111916-8a87d972-5081-11e7-80b9-3abb218b3329.png)

**Comment by Heshan94** [comment] 2017-06-24 18:57
i would like to work on this project.Can you please tell me what kind of programming languages i have to known for start this?

**Comment by jeffWhitridge** [comment] 2018-01-13 04:25
I have same issue.

**Comment by akimusume** [comment] 2019-07-22 09:34
Tow years passed, the issue remains in 7.7.1, and no one gives an explanation or fixes it.

In your screenshot, the "foreground colour" option is disabled, which looks impossiable to change. In my NotePad++(7.7.1), the "foreground colour" option is enabled, but Nothing happend after change it.

However, I do not think this is an issue. It's reasonable that not changing the foreground colour of selected text because the foreground colour indicate the type of the text, and changing the background colour can already make the seleced text clear enough to see. Thus the selected text should not has its own foreground colour and the "foreground colour" option should remain disabled.

**Comment by swbrains** [comment] 2019-11-20 04:28
I am used to seeing the selected text with a solid background color and the text foreground in white, so I would still like to see the foreground text color configurable.  While selecting text, it's not necessary for me to still see the syntax coloring as I'm simply selecting text for some action.  I only need to retain syntax coloring when viewing the text or typing.  I feel like it's fairly standard to see white text on a dark (blue usually) background when selecting text and I'd like to see NPP follow this widely-accepted practice.

**Comment by FireController1847** [comment] 2019-12-27 21:02
I think this option should definitely be implemented. I like the look of regular Windows Notepad, and when you highlight text there the background becomes a blue and the foreground becomes white text (which makes it easier to see it). I see no reason this shouldn't be an option.

**Comment by Targren** [comment] 2021-03-09 17:23
This problem still persists in 7.9.1, but the "Foreground Color" is enabled now, it just doesn't do anything.

**Comment by sasumner** [comment] 2021-03-09 21:01
@Targren

>This problem still persists in 7.9.1, but the "Foreground Color" is enabled now, it just doesn't do anything.

Probably best to write continuing comments against the version that is current as of this writing, and that is 7.9.3.
(Behavior _could_ be the same in 7.9.1 and 7.9.3, but nobody is going to check 7.9.1)

Anyway, if I run 7.9.3, _Foreground Colour_ for _Selected text colour_ is not enabled:

![image](https://user-images.githubusercontent.com/30118311/110537373-9b3e7480-80f0-11eb-98a4-7e296f6c61e7.png)

**Comment by Targren** [comment] 2021-03-09 21:34
Weird. I just ran "Update" and it gave me 7.9.1 and says no update is available. But I guess that's another issue entirely.

**Comment by mere-human** [comment] 2021-03-09 21:35
> Weird. I just ran "Update" and it gave me 7.9.1 and says no update is available. But I guess that's another issue entirely.

https://npp-user-manual.org/docs/upgrading/

**Comment by FireController1847** [comment] 2021-03-09 21:38
> > Weird. I just ran "Update" and it gave me 7.9.1 and says no update is available. But I guess that's another issue entirely.
> 
> https://npp-user-manual.org/docs/upgrading/

That article uses the wrong version of "which", does the manual have a GitHub as well? Sorry if this sounds like a grammar nazi type thing, I figure if we correct it it can look a little more professional :)

**Comment by Targren** [comment] 2021-03-09 21:39
> > Weird. I just ran "Update" and it gave me 7.9.1 and says no update is available. But I guess that's another issue entirely.
> 
> https://npp-user-manual.org/docs/upgrading/
![Capture](https://user-images.githubusercontent.com/11566412/110541600-faeb4e80-80f5-11eb-9b51-c4f33a179535.PNG)

Yeah, I just updated manually. 

The selector is still enabled on 7.9.3, too, though.

**Comment by sasumner** [comment] 2021-03-09 21:41
@FireController1847 said:

>That article uses the wrong version of "which", does the manual have a GitHub as well? Sorry if this sounds like a grammar nazi type thing, I figure if we correct it it can look a little more professional

I agree that section is a bit rough.
The user manual is [HERE](https://github.com/notepad-plus-plus/npp-usermanual).
If you want to officially complain about the verbage, create an "issue".
If you then think you can "fix" it well, you can create a PR.

**Comment by donho** [comment] 2021-04-30 03:53
It's cool to select text w/o losing the syntax highlighting.
I prefer to keep the current behaviour, so the old school behaviour won't be implemented

**Comment by FireController1847** [comment] 2021-04-30 03:55
So.... What? Why? I don't understand how current functionality would be lost. If you keep the option transparent or disabled then use the current functionality, otherwise change the color. What's wrong with giving the preference? Just because it's "cool"? What kind of open-source project is this?

**Comment by sasumner** [comment] 2021-04-30 12:02
So this issue and others of its type will no longer be considered as the Notepad++ author has made a final decision not to support it.  That decision is documented here:  https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9817#issuecomment-829785774

Any new issues on this topic will be immediately closed with a link to the final decision.

**Comment by FireController1847** [comment] 2021-04-30 14:55
Unbelievable.

**Comment by donho** [comment] 2021-04-30 15:25
@FireController1847 
The current behaviour exits since the 1st release of Notepad++, so it's a feature (selecting the text without losing the syntax highlighting) and not a bug to me.
If we changed this behaviour in the future releases, there would be more users would think it's "Unbelievable".

**Comment by FireController1847** [comment] 2021-04-30 15:29
> @FireController1847
> The current behaviour exits since the 1st release of Notepad++, so it's a feature (selecting the text without losing the syntax highlighting) and not a bug to me.
> If we changed this behaviour in the future releases, there would be more users would think it's "Unbelievable".

In what world does giving users more options cause unbelievable changes. Never was this issue implying the feature should be replaced. The PR maybe overidded it, but the issue was not claiming that. If you would prefer I would make another issue more directly worded stating we would like it as an OPTIONAL feature. I don't, I truly don't understand how you think this will override the existing feature in the first place. As I described in my previous comment the potential solution... Whatever, this is fruitless, "THE DEVELOPER HAS SPOKEN" strikes again in an open-source project.

**Comment by donho** [comment] 2021-04-30 16:14
I'm not really for adding more UI options for it, as we know "A lot of options, no option".
OTOH, it could be a solution: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9817#issuecomment-830180696

**Comment by FireController1847** [comment] 2021-04-30 16:38
That does sound like a reasonable compromise. I just ship my package as a theme compiled ZIP, so I wouldn't mind having to edit the hidden option. Thanks for being willing.

**Comment by richlux** [comment] 2021-04-30 17:13
Doesn't this option already exist?  The background color can be changed, but the foreground color is disabled.  If that were enabled, wouldn't that solve the problem?

![image](https://user-images.githubusercontent.com/25157703/116729996-e6b92480-a9b5-11eb-8a0a-567a349f61bf.png)

**Comment by donho** [comment] 2021-04-30 21:29
@rcdailey 
This problem could be solved programmatically with a hidden option.

**Closed** 2021-05-01 02:30 UTC
Labels: accepted

**Comment by FireController1847** [comment] 2021-05-01 02:39
@donho Sorry for my attitude earlier. Was having a rough morning. Thanks for doing this, I'll test it out next chance I get

**Comment by sasumner** [comment] 2021-05-01 11:41
Not to belabor a negative, but we've seen this kind of comment a few times:

>"THE DEVELOPER HAS SPOKEN" strikes again in an open-source project.

And I don't understand it, because it's the developer's project, and he has sole discretion about what happens with his project.

Often people open an issue and it gets declined and they get rather perturbed about it.
Like the thinking is just because you open an issue it has to be implemented.

**Comment by sasumner** [comment] 2021-05-01 11:43
@donho 

Don't forget to create an issue for the user manual so that you can describe your newly implemented behavior.
I'd say its rather important as it is not obvious how to activate it.

**Comment by FireController1847** [comment] 2021-05-01 21:08
@sasumner Oh no worries there. I think the primary reason this is a frustration is that usually when things like this happen the developer is unwilling to even discuss the issue or debate or even compromise like he did. Often it's just, "No, I'm not doing this and that's final." To make it even more frustrating many developers will lock the conversation if it continues. I totally get saying something like that after discussing for a bit and then if people are unwilling to compromise closing and locking the issue. But if a feature is rejected, I get that too but don't be so stubborn to not even discuss it or debate it, if you kind of know what I mean. At that point, why even make it open source, just use an issue tracker (yes, I know it's not just this simple and there's other reasons, but this is a huge primary reason.) And yeah, I agree it is the developer's project and ultimately up to them, but when I said "THE DEVELOPER HAS SPOKEN" I mostly meant like another case of unwillingness to compromise and stubbornness, as many open source developers are. I know this really isn't the place to discuss this so if you're more interested in my perspective add me on Discord I'd love to have a respectful, adult-like debate. I'm FireController1847#3577

**Comment by sasumner** [comment] 2021-05-01 23:16
@FireController1847 
Thanks for your follow-up comments.

**Comment by alankilborn** [comment] 2022-02-11 12:49
> is there a way or hidden way or trick to change "Selected Text Foreground Colour"?

There is indeed.  See https://npp-user-manual.org/docs/config-files/#:~:text=enableSelectFgColor.xml

**Comment by ten2120** [comment] 2022-02-11 13:51
> There is indeed. See https://npp-user-manual.org/docs/config-files/#:~:text=enableSelectFgColor.xml

Many thanks.
