### ISSUE TITLE
Cmd shell created by Notepad++ does not retrieve updated environment variables unless Notepad++ is restarted

### ISSUE THREAD

**Issue by allchannelson** [notepad-plus-plus/notepad-plus-plus#10749] opened 2021-11-05 10:14 UTC
### Description of the Issue
When using built-in right click context menu option "Open Containing Folder in cmd", the environment variables available to the shell do not update (whether added, modified, or removed). The environment variables are updated only if Notepad++ itself is restarted.

### Steps to Reproduce the Issue
1.  Open Notepad++
2.  Modify Environment Variable (for example, just add a random new one)
3.  Notepad++'s shell does not get access to any environment variable changes, regardless of how often the shell is opened or closed (normally that's how you update them)
4. Close and re-open Notepad++ for the shell's environment variables to update

### Expected Behavior
The shells should have their environment variables updated when it is closed and re-opened.

### Actual Behavior
Environment variables do not update.

### Debug Information
Notepad++ v8.1.5   (64-bit)
Build time : Sep 26 2021 - 15:23:23
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19043.1288
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by xomx** [comment] 2021-11-10 10:00
I can reproduce it (N++ 8.1.9 & 7.9.5 x64).

**Comment by xomx** [comment] 2021-11-13 14:44
First I have to say that this is not a bug, it is a standard behavior under the Windows OS. Environment variables are assigned to a process at its start and typically these are never touched again. Of course there are mechanisms how to propagate global environment changes (e.g. the system shell - Explorer does that), but it is not common for normal apps to do that.

For the cmd launching Notepad++ uses the ShellExecute WINAPI, which (in spite of the name "Shell..." within its name) does not spawn the new cmd-process from the system shell, but from the N++ process itself. So the newly spawned cmd-process inherits its environment set from the N++ and not from the system shell. That is why you do not see updated global environment variables until you restart N++. 

To achieve the expected behavior by you we can:

1) Change the N++ cmd-process spawning method (using CreateProcess somehow instead of the ShellExecute).

2) Process broadcasted WM_SETTINGCHANGE system message (checking its lParam for the string “Environment” and then use undocumented shell RegenerateUserEnvironment WINAPI)

Two notes:
- by both methods one probably loses a possible N++ local environment changes
- the RegenerateUserEnvironment is undocumented indeed but according to the following source, this is the method Windows shell uses itself for this kind of job:
https://jira.reactos.org/browse/CORE-14397

@donho 
What do you think about the possible change in N++ behavior (especially the 2nd solution would be relatively easy to implement)?

**Comment by donho** [comment] 2021-11-14 15:44
@xomx 
>  by both methods one probably loses a possible N++ local environment changes

By `N++ local environment changes`, could you provide a concrete example?

**Comment by xomx** [comment] 2021-11-15 13:17
@donho 

N++ (or its plugins) can change (e.g. via the SetEnvironmentVariable WINAPI) its own environment during runtime for some purposes, but this has no effect on the global system environment variables (these are in fact regkeys in the HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment). And if I e.g. simply spawn a new cmd-process in the context of the system shell process (method No.1), there will be actual global environment variables, but without a possible changes from the local N++ set...

Code example of the method No.1 realization:
https://devblogs.microsoft.com/oldnewthing/20190425-00/?p=102443

I do not know, how the RegenerateUserEnvironment from method No.2 handles the variables update, maybe it is sophisticated enough to only update stuff and not simply overwrite (I will check that if we decide for the method No.2).

We can overcome this problem anyway by simply getting the actual local set via the GetEnvironmentStrings WINAPI and then by parsing the obtained NULL-terminated strings list against the new global one we can update the local set accordingly (this is valid for both method 1 and method 2).

**Comment by xomx** [comment] 2021-11-18 09:35
@donho 
Ok, I will try when I find some time.

**Comment by xomx** [comment] 2021-11-21 02:19
@donho 

So I implemented the method No. 2 with the shell32!RegenerateUserEnvironment.

This WINAPI simply overwrites the running process environment block, so no sophisticated update is possible without further actions.

To see how many environment variables one can lost without further actions, I run the N++ from within the Visual Studio debugger with additional code to save the N++ process environment block before and after the RegenerateUserEnvironment call (see  the pic1-envdiff.gif).
![pic1-envdiff](https://user-images.githubusercontent.com/13075183/142746411-c48fd34a-0e86-4252-b7b1-460a0ef9b0d6.gif)

Then I have implemented also a logic to recreate the possible missing N++ process environment variables (pic2-envdiff-corrected.gif).
![pic2-envdiff-corrected](https://user-images.githubusercontent.com/13075183/142746455-a124c0e2-1da9-4593-9942-97355b1bf9f0.gif)

It is much better with these additional corrections.

Possible drawbacks of my implementation:
- if a global variable (system & user profile variables) is deleted during the N++ session, it will be recreated after the RegenerateUserEnvironment call in the running N++ process (it then exists only in the environment block of the running N++ process and after terminating the N++ process it will be gone, so it is ok)
- if there is a conflict (e.g. if we changed the PATH value somehow from within the N++ process before calling the RegenerateUserEnvironment, it can be overwritten from the global PATH variables), the RegenerateUserEnvironment value wins

**Comment by xomx** [comment] 2021-11-21 03:22
For a possible testing there is a helper function for saving the process environment block to a file:

void env2file(LPTCH lpEnv, LPCTSTR szFile)
{
	if (!lpEnv || !szFile)
		return;

	HANDLE hFile = ::CreateFile(szFile, GENERIC_WRITE, FILE_SHARE_READ, 0, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, 0);
	if (INVALID_HANDLE_VALUE != hFile)
	{
		LPTSTR lpszVariable = (LPTSTR)lpEnv;
		DWORD dwBytesWritten = 0;
		const UINT cStrBufMaxLen = 8191;
		TCHAR szBuf[cStrBufMaxLen + 1];
		::ZeroMemory(szBuf, sizeof(szBuf));

		while (*lpszVariable)
		{
			if (-1 == _stprintf_s(szBuf, _countof(szBuf), TEXT("%s\r\n"), lpszVariable))
				lstrcpy(szBuf, TEXT("?\r\n"));

			int iLen = lstrlen(szBuf);
			::WriteFile(hFile, szBuf, iLen * sizeof(TCHAR), &dwBytesWritten, NULL);

			lpszVariable += lstrlen(lpszVariable) + 1;
		}

		::CloseHandle(hFile);
	}
}

Use it in code like:

LPTCH lpCurProcEnv = ::GetEnvironmentStrings();
env2file(lpCurProcEnv, TEXT("C:\\TEMP\\procenv.txt"));
::FreeEnvironmentStrings(lpCurProcEnv);

**Closed** 2021-12-14 18:01 UTC
Labels: reject

**Comment by allchannelson** [comment] 2021-12-15 00:43
Can there be a note that mentions this behavior? It always catches me by surprise until I remember I need to restart Notepad++. I just need to know this happens, and not waste time restarting the shell and wondering what's going on.

**Comment by xomx** [comment] 2021-12-15 10:21
> Can there be a note that mentions this behavior?

@donho  
That would go? Only detect global environment changes (eg adding _isGlobalEnvChanged member state variable for that) and then show this to the user when needed somehow... A simple form could be eg a messagebox, when user is launching the cmd from N++. Or something else, I have not a better idea for now.

**Comment by donho** [comment] 2021-12-15 14:00
@xomx 
>  Only detect global environment changes (eg adding _isGlobalEnvChanged member state variable for that) and then show this to the user when needed somehow... A simple form could be eg a messagebox, when user is launching the cmd from N++

No, it'll be disturbing for people who don't need the notification.
I'm trying your first solution (CreateProcess) which is clean & straight forward.

**Comment by xomx** [comment] 2021-12-15 15:14
@donho 
> No, it'll be disturbing for people who don't need the notification.

Maybe it might not be so disturbing if we just somehow advertised that in the GUI, like on this image:
![env_warning](https://user-images.githubusercontent.com/13075183/146211346-6eb366f8-9b93-49d0-a3e1-2e99c1ec0c94.gif)


> I'm trying your first solution (CreateProcess)

Do not forget that this way the launched cmd-environment can be considerably different from the current N++ environment (I am not talking here about the changed global environment variables). For this issue it is irrelevant, but some other user could depend on that.

**Comment by donho** [comment] 2021-12-15 16:10
> Maybe it might not be so disturbing if we just somehow advertised that in the GUI, like on this image:

If hovering on the exclamation mark can provide a tooltip to tell user the global environment has been changed, otherwise it brings more confusion to users.

**Comment by donho** [comment] 2021-12-15 23:38
> I'm trying your first solution (CreateProcess) which is clean & straight forward (if it works).

FYI, there's no trivial way to make it work (from my side). I stop searching the solution.

**Comment by xomx** [comment] 2021-12-21 01:16
@donho @allchannelson 
> If hovering on the exclamation mark can provide a tooltip to tell user the global environment has been changed,

So I tried to implemented that and I would like to know your opinion - here are some pics of how it can looks like after the global environment change in N++:

mouse on File->OpenContainingFolder
![pic1-cmd_with_caution_sign](https://user-images.githubusercontent.com/13075183/146851958-6b175d8c-1997-4d18-9e2c-fff4fc634aa0.gif)

mouse on cmd menu command
![pic2-cmd_with_caution_sign_and_tooltip](https://user-images.githubusercontent.com/13075183/146851998-56ee09c4-dd41-418b-940f-7ba6774f0208.gif)

mouse on cmd menu command (dark mode on)
![pic3-cmd_with_caution_sign_and_tooltip_(darkmode)](https://user-images.githubusercontent.com/13075183/146852048-aa63936d-9409-49ef-ab85-2748e97f2229.gif)

I am opened to possible comments and corrections (eg better tooltip infotext, its appearance or position), but I do not want to play with the GUI stuff much more, as there is already more code, than in the original rejected PR ...

**Comment by donho** [comment] 2021-12-21 03:43
@xomx 
Is the exclamation mark a picture? It's less discrete than it should be. Could it be a character "!" with no color?
The position of tooltip looks OK, if it appears only when the mouse is hovering on the mark.
Text is a little bit too long, I would put "Global environment settings have been changed. If you need to update cmd evironment, restart Notepad++"

**Comment by alankilborn** [comment] 2021-12-21 12:44
Is it too late to mention that `cmd` is a bit dated?  I believe `cmd` is replaceable in Notepad++ with `PowerShell` (but I haven't set that up due to lack of a need for it).  But my point is that perhaps any new UI text introduced should refer to something more generic, e.g. "shell" ??

**Comment by xomx** [comment] 2021-12-21 20:30
@donho 

> Is the exclamation mark a picture?

No, it is created at runtime (detection of the current menu font size and combination of FillRect drawing and ExtTextOut for the '!'). That way there will not be a problem with possible DPI changes etc.

> It's less discrete than it should be. Could it be a character "!" with no color?

Maybe it is. I chose that way for two reasons:
- GUI coherency, I just mimic the menu style of Search menu (eg Search->ClearStyle)
- I had a problem with the menu background color detection in the dark mode, there are many COLORREFs and HBRUSHes defined in the NppDarkMode.cpp, but it seems that none is for the menu background (?) If I find that color, I can use the '!' alone for the SetMenuItemBitmaps.

> The position of tooltip looks OK, if it appears only when the mouse is hovering on the mark.

Now the tooltip appears, when the mouse is hovering anywhere at the menu command "cmd" (blue area on the 2nd image above, but not the one under the Open Containing Folder...). Did you mean it should be only on the menu item image bitmap "!" part on the left?

> Text is a little bit too long

I know, but there is a reason for it - users can use different ways to restart N++ and if one uses a launching from a previously opened app (eg from a running file manager), which does not dynamically update its environment (most apps will not do that), the restarted N++ will NOT have its environment updated at all, but this time there will not be the caution sign in the "cmd" menu about it. I tested that by simply launching the N++ "cmd" menu command after the N++ restart from already pre-opened apps (I tried FAR file manager, Visual Studio IDE and several others) and the changes then were not there (I verified that by issuing the "set" command in the opened cmd-window from N++, this batch command without any param lists all environment variables). A foolproof way is to logoff/logon or use the Windows Explorer or launch by doubleclicking the N++ icon on the Desktop or in the Start menu. From the file managers eg the Altap Salamander works as well, it probably updates its environment dynamically.


@alankilborn 
I do not think so. Anyone who uses "cmd" knows what type of shell it is. If we just use the "shell" as the menu command label, one user will expect the older cmd, another the Powershell one. But good idea anyway - we can create another menu item "Powershell" in the same submenu, it is up to Don. But this should go into another feature request issue.

**Comment by donho** [comment] 2021-12-22 00:27
> No, it is created at runtime (detection of the current menu font size and combination of FillRect drawing and ExtTextOut for the '!'). That way there will not be a problem with possible DPI changes etc.

That's great!

> but it seems that none is for the menu background

Menu and caption foreground/background is set by system. That's why their colors are always the same when you change the ton. Hard code `RGB(43, 43, 43);` as the background of declaration mark should be OK, please make the foreground as gray in dark mode - I prefer it as discrete as possible (and the same idea for the light mode).

> Did you mean it should be only on the menu item image bitmap "!" part on the left?

Yes. The reason is that, IMO, the most of users just don't need this information. So I don't want this feature becomes disturbing.

> I know, but there is a reason for it - users can use different ways to restart N++ and if one uses a launching from a previously opened app...

OK, I see. In this case, I would suggest:
"Global environment settings have been changed. If you need to update cmd environment, restart Notepad++ from a freshly opened Explorer"

One things also you should keep in mind - a complex & important amount of code will be rejected if it's not for an important bug-fix or a considerable feature. You could always submit your PR, but it may be refused for the code maintenance facility reason.  

> we can create another menu item "Powershell" in the same submenu, it is up to Don. But this should go into another feature request issue.

Add a new menu item "PowerShell" item, why not? But cmd deserved to be kept absolutely. And I agree, it should be in another PR.

**Comment by xomx** [comment] 2022-01-02 18:51
@donho 
Ok, I tried to take account of all your suggestions, here is the result:
![MenuCommandMark](https://user-images.githubusercontent.com/13075183/147885024-aa1cea69-85b2-4e88-93d2-6a9bd38f904a.png)

And here is a debug portable N++ set to play with:
http://redwoodal.sweb.cz/NotepadPlusPlus/NPP-MCM-test.7z

To test:
1. Run my version of N++.
2. Open the system Environment Variables ... dlg (see the pic below).
3. Add or change some variable.
4. Switch back to N++, go to the File->OpenContainingFolder menu.

![EnvironmentVariables](https://user-images.githubusercontent.com/13075183/147885322-a06c7259-bce5-48d8-82a9-aa5b4fb4a3cb.png)

The menu command mark bitmap is now created at runtime as fully transparent, so there should not be any visual glitch under any circumstances (I tested that under Win 7,  8.1 and 10). Its foreground color is calculated to be less bright (in dark mode, less dark in normal mode) than the menutext foreground one (if possible, of course, i.e. if the menu background color is not too close to the foreground one...).  Let me know 1st, if the look and behavior is ok.

**Comment by donho** [comment] 2022-01-03 15:49
@xomx 
Looks nice!
Why don't you open a PR for it?

**Comment by xomx** [comment] 2022-01-03 23:35
@donho 
Done.

> One things also you should keep in mind - a complex & important amount of code will be rejected if it's not for an important bug-fix or a considerable feature. You could always submit your PR, but it may be refused for the code maintenance facility reason.

Well, I tried my best :-) 
When it was clear to me, that the code could not be written on 3 lines, I changed it to a general reusable feature. So now all the N++ menuitems can have its own bitmap & tooltip. You can use any character or shape from the Windows fonts for it.
