### ISSUE TITLE
Suggestion: Add pyx (Cython) extension to supported Python extensions

### ISSUE THREAD

**Issue by jcrmatos** [notepad-plus-plus/notepad-plus-plus#3767] opened 2017-09-21 23:55 UTC
Hello

Please add pyx (Cython) extension to supported Python extensions.

Best regards,

JM

**Comment by ArkadiuszMichalski** [comment] 2020-09-23 20:59
@sasumner Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3069.

**Closed** 2024-08-30 22:09 UTC
