### ISSUE TITLE
(Enhancement) apply "Word Wrap" per document

### ISSUE THREAD

**Issue by j5v** [notepad-plus-plus/notepad-plus-plus#1427] opened 2016-01-30 00:07 UTC
Please consider having the "Word Wrap" feature applied **per document**, with the default setting defined **by Language**.

There might be other editor properties that would benefit from the same treatment.

**Background:**
I use Notepad++ (v6.8.8) for various files, several open at the same time. Some of these files are better with word wrap enabled; others not. When switching between these files, I need to change the Notepad++ "Word Wrap" manually.

**Comment by j5v** [comment] 2016-02-05 16:02
As a workaround, I can use "move to other instance", to create two instances (one with word wrap; one without). Downside: it creates document-switching confusion.

**Comment by MetaChuh** [comment] 2019-04-13 01:40
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 01:40 UTC
