### ISSUE TITLE
[FunctionList] Not found functions with comment in JavaScript files

### ISSUE THREAD

**Issue by fursformula** [notepad-plus-plus/notepad-plus-plus#12792] opened 2023-01-11 17:11 UTC
In notepad v8.4.8 functionList (javascript.js.xml) not found functions with comment in JavaScript files.

For example:
createCanvas = function(value) // value = "image"
{
 ...
}

This function don't add in functionList. If I delete '// value = "image"' in the end of string, it works correctly.
Need modify file 'javascript.js.xml' to fix this error. Thanks!

**Comment by ArkadiuszMichalski** [comment] 2023-01-14 01:20
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3685.

**Closed by ArkadiuszMichalski** 2023-01-14 01:20 UTC
