### ISSUE TITLE
Font size exceptionally large following disconnect from 4K TV/monitor

### ISSUE THREAD

**Issue by MrDrMcNinjas** [notepad-plus-plus/notepad-plus-plus#2890] opened 2017-02-09 21:09 UTC
### Description of the Issue
After I disconnect my machine from an HDMI connection to a 4K TV, the fonts in Notepad++ are distorted, even following program and machine shutdown/reboot.

### Steps to Reproduce the Issue

1. Open Notepad++
2. Connect machine via HDMI to 4K TV monitor/screen
3. Disconnect HDMI, returning to 1920x1080 resolution
4. Shut Notepad++ and/or machine down
5. Note that Notepad++ fonts remain exceptionally large, and that closing and re-opening the program nor re-booting Windows 10 will solve the problem.

### Expected Behavior
Fonts would scale back to normal following 4K HDMI disconnect

### Actual Behavior
Fonts across the program are scaled up

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll 
![debug 01](https://cloud.githubusercontent.com/assets/12601375/22803153/a229954a-eec8-11e6-941e-d44e673b9bc3.png)
![debug 02](https://cloud.githubusercontent.com/assets/12601375/22803167/b0925676-eec8-11e6-97d4-065d41593b06.png)
![debug 03](https://cloud.githubusercontent.com/assets/12601375/22803178/c1de76e4-eec8-11e6-84cc-1bd41c8dff9c.png)

**Comment by M-Jup** [comment] 2017-02-14 14:07
Duplicate of #629. A fix for this would be more than welcome.

**Comment by benoitparis** [comment] 2017-04-25 10:50
+1

**Comment by MetaChuh** [comment] 2019-05-01 15:04
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 15:04 UTC
