### ISSUE TITLE
No shortcut keys assigned in closedown popup

### ISSUE THREAD

**Issue by petersone** [notepad-plus-plus/notepad-plus-plus#6279] opened 2019-10-28 13:45 UTC
### Description of the Issue
Close NP++ with an unsaved document.

### Steps to Reproduce the Issue

1.  Make change to a document.
2.  Close NP++
3.  Popup with "Do you want to save" will occur.

### Expected Behavior
Shortcut key assigned to every button.

### Actual Behavior
Ja (Yes) / Nej (No) / Cancel / Yes to ALL / No to ALL
has no shortcut key assigned - so 'n' will not close the popup and the program (tab or mouse has to be used).
This was not the case before version 7.8

### Debug Information
Version: 7.8
Language: Danish

**Comment by sasumner** [comment] 2019-10-28 14:01
Duplicate of #6223 .  Please search existing issues before creating a new one to avoid unnecessary duplication.

**Closed by sasumner** 2019-10-28 14:01 UTC
