### ISSUE TITLE
Encoding (bullet) is not shown

### ISSUE THREAD

**Issue by devwebcl** [notepad-plus-plus/notepad-plus-plus#5201] opened 2019-01-06 01:12 UTC
### Description of the Issue
Since version 7.6 When opening any text file and click "encoding" to check the encoding format, it is not shown.

### Steps to Reproduce the Issue

1. open any text file 
2. click "encoding" option from menu
3. check if file's encoding is shown (with a bullet)

### Expected Behavior
bullet showing encoding format

### Actual Behavior
since version 7.6 till 7.6.2, it doesn't show the expected bullet

**Comment by MetaChuh** [comment] 2019-01-06 08:04
i can confirm this behaviour if encoding autodetect is activated, and a file is wrongly detected as eg. windows-1258 encoding, example: any utf-8 file with the word "Mosaïque" in it

**Comment by MetaChuh** [comment] 2019-05-06 19:39
your file encoding format bullet missing issue is fixed in 7.6.5 and above.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.6.2, as the plugin folder structure has changed once more since 7.6.3.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-06 19:39 UTC
