### ISSUE TITLE
Keyboard shortcuts not working for dialogs

### ISSUE THREAD

**Issue by CarlosOnline** [notepad-plus-plus/notepad-plus-plus#7614] opened 2019-11-18 18:08 UTC
### Description of the Issue

When I attempt to close an modified document, a Save dialog is presented with Yes, No, Cancel buttons.  The keyboard shortcuts do not work on these dialogs.

Also noticed that the Replace in Files keyboard shortcut doesn't work in Find In Files dialog.

### Steps to Reproduce the Issue
1. Create new document
2. Modify a document
3. Close document
Wait for Save dialog
Try to use shortcut to execute no button.

1. Bring up find in files dialog
2. Enter in pattern and replacement
3. Use keyboard shortcut to Replace in files
No effect

### Expected Behavior
Keyboard shortcuts to work as if the button was pressed.

### Actual Behavior
Keyboard shortcuts have no effect.

### Debug Information
Notepad++ v7.8.1   (32-bit)
Build time : Oct 27 2019 - 22:46:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1006
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll 

![image](https://user-images.githubusercontent.com/3691895/69077683-06f95b80-0a2e-11ea-9cef-43f83d77fe05.png)

![image](https://user-images.githubusercontent.com/3691895/69077641-f47f2200-0a2d-11ea-87ae-10bece37b842.png)

**Comment by sasumner** [comment] 2019-11-18 18:17
Closing as duplicate of #6223 .

Regarding the "Find" dialog part, you can follow the procedure in the comments of the referenced issue to add/change keyboard shortcuts.

**Closed by sasumner** 2019-11-18 18:17 UTC
