### ISSUE TITLE
function list not working with javascript since version 7.3.1

### ISSUE THREAD

**Issue by adahbingee** [notepad-plus-plus/notepad-plus-plus#2924] opened 2017-02-19 13:57 UTC
### Description of the Issue
function list not working with javascript

### Steps to Reproduce the Issue
show function list

### Actual Behavior
no any function shown

### Debug Information

**Comment by vlakoff** [comment] 2017-02-20 00:23
It works here. Could you provide an example of failing JavaScript content?

**Comment by adahbingee** [comment] 2017-02-20 00:48
The simplest one not works.
```
function myFun() {
}
```

**Comment by vlakoff** [comment] 2017-02-20 01:17
Mmm, right.
Apparently it's a regression introduced in 5d438aa08250e3389a77cd3635763ac4c20a36be.

**Comment by MAPJe71** [comment] 2017-02-20 01:56
See [Community topic](https://notepad-plus-plus.org/community/topic/12697/function-list-not-working-in-v7-2)

**Comment by frank-orellana** [comment] 2017-03-28 16:23
In effect it is one of the changes mentioned by @vlakoff  in 5d438aa.

specifically this one:
- Changed use of L_JS (19) to L_JAVASCRIPT (58).

If I change the langID in the XML back to 19 from 58 then **I see the js functions again!**

BUT... I also had to apply vlakoff changes made in this one: https://github.com/vlakoff/notepad-plus-plus/commit/ea51d5db6152ca22bf139dd67d5848a59806e4e1#diff-e804f743afae131d23e8eecb1feeb84a  to make them appear correctly. (Not sure why this is not in the master branch already)

**So in the end my functionList.xml looks like this: https://github.com/frank-orellana/notepad-plus-plus/commit/1a615dfab69bdc7e222c609a2f51dbd48d4f8947#diff-e804f743afae131d23e8eecb1feeb84a  and it works again!**

I'm not sure if I should make a pull request with these changes since I don't know why the langID was changed from 19 to 58, but for now this make the function list work again for javascript. This was made on a fresh install.

And btw. Java function list are not working for me either. Maybe we should go back to some older version of this file in case it was ruined by some commit??

**Comment by elmonty** [comment] 2017-04-12 12:42
This is still an issue in 7.3.3 fresh install. The function list is empty for js files.

**Comment by zekrom-vale** [comment] 2017-07-06 20:00
`(?s:/\*.*?\*/)|(?m-s://.*?$)` is an invalid regexp pattern, but fixing it does nothing.  Using the 64 bit function list or the 32 bit function list on notepad++ Version 7.4.2 (64x).  Works with xml, but not js.

**Comment by zekrom-vale** [comment] 2017-07-06 20:32
Switching `<association id=  "javascript_function"   langID="58"/>` to `<association id=  "javascript_function"   langID="19"/>` and removing the comment regexp pattern now shows functions!

**Comment by terpi** [comment] 2017-10-09 09:56
Does somebody knows when this bug will be fixed (in notepadd++), since many contributors seem to have solutions ?
Or, what can I do to get this function list ?  (where is the file in wich to make changes)

**Comment by miile7** [comment] 2018-05-17 09:01
What @zekrom-vale is suggesting works for me. Changing the `langID` to 19 does the trick.

> rem[e] the comment regexp pattern
I didn't do that but it is still working

**Comment by AleWin32** [comment] 2018-07-30 12:07
Still does not work in last version of Notepad++ (7.5.8)

**Comment by ValiantDD** [comment] 2018-08-08 17:14
For ver 7.5.8:
I found I had to check %appdata%\Notepad++\functionList.xml and I make sure the langID value was 58.
It was set to 19 and the XML file was clearly an older formatted file that what was in my program files folder.

**Comment by MetaChuh** [comment] 2019-05-01 14:51
@adahbingee 

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

<img width="964" alt="" src="https://user-images.githubusercontent.com/45773305/57023003-2fa43a00-6c31-11e9-90a2-a964f61f9294.png">

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-05-01 14:51 UTC
