### ISSUE TITLE
gap between maximized window and monitor screen

### ISSUE THREAD

**Issue by alexsong19** [notepad-plus-plus/notepad-plus-plus#8380] opened 2020-06-05 15:52 UTC
### Description of the Issue

On windows 10, multiple monitors. Maximize the windows of npp in one of the monitor. There's a ~1px (invisible) gap between the upper edge of the window and the actual screen.
It causes a serious problem: whenever we want to close the window, we move the mouse pointer to the upper right corner, and click. Now, with the gap, you'll actually click on the app beneath npp, and you'll close that window!

### Steps to Reproduce the Issue

1. win 10, multiple monitor (extended)
2. maximize npp window in one of the monitors
3. move mouse pointer to the upperright corner of the screen, click
4. You'll close on the app that's behind the npp window! 

### Expected Behavior

No gap between the maximized window and the screen

### Actual Behavior

~1px invisible gap

### Debug Information

Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\npp\notepad++.exe
Admin mode : OFF
Local Conf mode : ON
OS Name : Windows 10 Enterprise LTSC 2019 (64-bit) 
OS Version : 1809
OS Build : 17763.1158
Plugins : ComparePlugin.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll NppExport.dll

**Comment by alexsong19** [comment] 2020-06-05 17:20
> _Debug information_ ?

Updated; I am not sure what to look at in the debug info though; nothing is happening in npp, the mouse click is outside of the maximized window...

**Comment by sasumner** [comment] 2020-06-05 17:24
The _Debug information_ is for a developer that might look into your issue at some point.  He/she would have more to go on, and this is easy stuff as it is generated by N++ itself.

There really seems to be some confusion about providing the _Debug information_ even though the instructions are right there in the issue template.

It's often used to identify which issues are likely to be caused by plugins, so it reports which of those are present.

**Comment by jonzbonz** [comment] 2020-07-02 14:20
I wanted to report the same issue here. This is very urgent as it causes me to close other windows very often!
You can see that the upper bar in Notepad++ (which contains File, Edit, Search etc.) is wide enough but everything above that is one pixel short.

Please fix this issue as fast as possible!

**Comment by jonzbonz** [comment] 2020-07-02 16:25
Update:
> the upper bar in Notepad++ (which contains File, Edit, Search etc.) is wide enough but everything above that is one pixel short
It turns out that on my monitor, the described bar is 2 pixels too wide on the right side and everything below that is one pixel too wide.

I have two monitors, both 1920x1080 and Notepad++ maximized on the left monitor

**Comment by tab328** [comment] 2021-02-08 14:16
The workaround I use is right click the notepadd++.exe>properties>compatibility>change high DPI settings>Override...>change to "system"

I no longer have any issues with closing the wrong windows on any of my 3 extended monitors, and I have not noticed any issues resulting from this workaround. Please test this yourself and let us know if the workaround causes something else.

**Comment by sasumner** [comment] 2021-06-02 11:18
Closing; let's make #8660 the controlling issue on this.

**Closed by sasumner** 2021-06-02 11:18 UTC
