### ISSUE TITLE
[Suggestion] automaticaly recognize email address strings and make them clikable to send an email (ie behave like a "mailto:" link)

### ISSUE THREAD

**Issue by ldmpub** [notepad-plus-plus/notepad-plus-plus#9640] opened 2021-03-11 17:36 UTC
### Description of the Issue
Yet only some texts are made "clickable" like ftp ; http ; https 

### Expected Behavior
**I suggest to add clickable links on valid email address strings with mailto URI scheme.**

### Actual Behavior
In Notepad++ text file, there is no link on myname@mydomain.org

What do you think?

**Comment by ArkadiuszMichalski** [comment] 2021-03-11 21:12
@ldmpub Where is your debug info?

**Comment by sasumner** [comment] 2021-03-11 21:27
>Yet only some texts are made "clickable" like ftp ; http ; https

mailto links are shown for me in 7.9.3:

![image](https://user-images.githubusercontent.com/30118311/110856697-fa81bd80-8285-11eb-88d1-d2d14fe0656c.png)

Even though mailto isn't directly specified here:

![image](https://user-images.githubusercontent.com/30118311/110856858-29982f00-8286-11eb-95de-f5ab5f5fc67d.png)

I guess I understand that we have some links that work without being specified, but if that's the case, shouldn't they do the right thing (in this case open the email program and fill in the To box), since they can't be made non-links?
Or, be removed from being supported?
Are there others like this?

However, for mailto, I personally don't feel there is a lot of value.
If truly needed, a script could probably be written.

**Comment by ldmpub** [comment] 2021-03-11 22:43
Hi,

I've checked on an other PC and mailto; links are automaticaly recognized by NotePad++ like stated by @sasumner  👍.

I was not aware of the above settings and will check again the behavior tomorrow on my other computer. If I fix it, I will close this issue. Thanks for your answers.

PS: I performed some search on mailto: includind in GitHub issues here ... I guessed this feature was missing (see title of the current issue above) but it's obviously a lack of knowledge. Sorry for the annoyance if I caused any.

**Comment by ldmpub** [comment] 2021-03-12 08:48
Hi,

Confirmed this morning there is no mailto: link 😐.

ScreenShot:
![image](https://user-images.githubusercontent.com/1452146/110915350-ceaf1800-8317-11eb-8b52-b88b9b5a523c.png)


NP++ version :
![image](https://user-images.githubusercontent.com/1452146/110915428-e9818c80-8317-11eb-9f5d-13e8b453c4f8.png)

Tell me how I can send you more info / what else I can do (including NP++ settings on my PC if they are wrong to render email address as clickable).

Many thanks,

**Comment by ldmpub** [comment] 2021-03-12 08:54
Hello (again),

I confirm that when adding "mailto:" before the email address => link is clikable but that's not the behaviour I remember to have seen on my other Computer which was : just entering the email address and NP++ adds a "hidden mailto:" to allow me to compose a new mail by clicking on text (name@example.com).

Hope it's more clear? Waiting for your answers ...

**Comment by sasumner** [comment] 2021-03-12 12:04
>just entering the email address and NP++ adds a "hidden mailto:" to allow me to compose a new mail by clicking on text

This is not Notepad++ behavior.  Maybe a plugin?
If it is a plugin, maybe it also provides the behavior for when clicking on the link?

**Comment by ldmpub** [comment] 2021-03-14 00:21
> This is not Notepad++ behavior. Maybe a plugin?

Ok I confirmed the behavior is the same on my 2 PCs with NP++ and without any plugin
=> no clickable (ie HTML mailto:) when typing "name@domail.org".

I may have a dream ... but ... devs came make my dream come true 😉. What do you think?

PS : subject of this issue slightly changed to confirm it's an enhancement / improvement request.

**Comment by sasumner** [comment] 2021-03-20 23:22
@Idmpub The desired behavior could be scripted with the PythonScript plugin.  If you are interested in such a solution, let us know.  Since this _could_ be scripted, and probably doesn't have general appeal, I'm going to close this issue.

**Closed by sasumner** 2021-03-20 23:22 UTC

**Comment by ldmpub** [comment] 2021-03-20 23:27
Ok.

Unfortunately, I'm not a Python developer so if this behavior can not be added to one of the next Notepad++releases, I will take the habit to manually add the protocol "mailto:" before emails addresses to make them 'clickable" 😪.

Thanks for this discussion,

**Comment by sasumner** [comment] 2021-03-21 00:06
@ldmpub Actually you don't have to be a Python developer as I will write you a demo script.  You just have to be willing to use the PythonScript plugin.

**Comment by ldmpub** [comment] 2021-03-21 08:54
@sasumner Fine 👍. Many thanks for the proposal!
How can we proceed ? Still in this "Github Ticket" or by mail, webcall ...?

**Comment by sasumner** [comment] 2021-03-21 10:42
>How can we proceed ? Still in this "Github Ticket" or by email, webcall ...?

When I finish it, I'll post it here.

**Comment by sasumner** [comment] 2021-03-21 12:23
Actually, I discovered that no script is needed.
Why I didn't see this earlier is that my Windows setup didn't have the default mail program set to the correct program, so when I double-clicked on a mailto link, nothing happened.
So I think all you need to do is add `mailto` to the _Preferences_ > _Cloud & Link_ > _URI customized schemes:_ box and make sure that your default mail program in Windows is set to the way you want, and it should work.

**Comment by dodmi** [comment] 2021-03-21 14:09
I guess you're talking of different things?

I understand, that @ldmpub likes to have a feature, that Notepad++ recognizes "plain" mail addresses and handle them as they were prefixed with the protocol handle mailto: (e.g. to linkify them and by clicking on that link a mail window should be opened)
Use case: You have a plain text readme file containing something like `contact me at support@example.org`. Clicking on that email address should automatically open a mail window with a new mail to `support@example.org`.
This is already possible if the author of the readme text file will put `contact me at mailto:support@example.org` to the file, but no author would do this on a plain text file.

I understand @sasumner suggests to add `mailto:` to the custom protocol handles, that NPP would recognize `mailto:support@example.org` as a mail address (which isn't what @ldmpub requests). This is even already possible, since NPP has a second (secret) list of protocol handlers, which it will always use and which already contains `mailto:`
At least `mailto:support@example.org` is linkified here without adding it to the list.

**Comment by sasumner** [comment] 2021-03-21 14:24
>I guess you're talking of different things?

Perhaps, yes...I guess the title of this issue is the biggest clue.
I'm not sure where I got off the track in thinking about this.  :-)

Without the `mailto:` prefix, the problem is larger to solve.
It _could_ still be scripted, however, as the effort is larger, I don't choose to take that task on.
I could however, provide some pointers on how to do it, if needed.

Sorry for the misunderstanding.
