### ISSUE TITLE
soft line wrapping on "Vertical Edge"

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#482] opened 2015-07-12 21:18 UTC
An option to wrap lines at Vertical Edge instead of window edge would be really nice. Plus a further toggle to set it to wrap whole file or comments only.

**Comment by MetaChuh** [comment] 2019-04-09 23:20
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:20 UTC
Labels: feature

**Comment by mentallurg** [comment] 2019-07-26 15:50
@MetaChuh has closed this ticket incorrectly, without any reason.
His quote
>please close your issues as soon as you are satisfied 

is not relevant here, because the author is NOT satisfied.

Furthermore, before referring to the new version, @MetaChuh should have checked if this problem is resolved in the version he refers. I have checked the recent version: The problem is still not resolved.

The handling of this ticket and the handling of #1140 show that some developers of Notepad++ prefer to formally close as many tickets as possible and don't care about users.

**Comment by xylographe** [comment] 2019-07-26 17:30
This feature cannot be implemented by the developer of Notepad++. It has to be implemented in Scintilla! See the [Scintilla “Line wrapping” documentation.](https://www.scintilla.org/ScintillaDoc.html#LineWrapping)

**Comment by mentallurg** [comment] 2019-07-28 18:06
@xylographe: I didn't say it should be implemented by developers of Notepad++. I sayd that:
1. Closing this ticket was wrong.
2. Explanation of @MetaChuh was absolutely irrelevant.

Sure, first the base functionality should be implemented in the Scintilla. Then it should be integrated into Notepad++ (Settings should be provided to control it etc.). But it is not the task of users to coordinate developers of Scintilla and Notepad++. It is the task of developers of Notepadd++. This ticket should be open until the function is implemented.

**Comment by SMcCandlish** [comment] 2019-09-07 19:48
I concur with mentallurg on both points and their explication.

**Comment by cup** [comment] 2020-01-22 03:08
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7813

**Comment by cup** [comment] 2020-01-22 03:09
Not sure why is hasnt been mentioned, but this is possible via `Edit`, `Line Operations`, `Split Lines` (`Ctrl + I`) does this, splitting on the current Vertical Edge.

**Comment by Darklocq** [comment] 2020-01-22 11:19
That's splitting lines (inserting hard linebreaks), not soft line-wrapping.
