### ISSUE TITLE
Feature request : Add date & time stamps hotkey without need to use external plugins

### ISSUE THREAD

**Issue by SilvaASP** [notepad-plus-plus/notepad-plus-plus#2821] opened 2017-01-24 15:20 UTC
### Description of the Issue

In MS Notepad, if you press F5 Hotkey, it inserts the current Data & Time Stamp.

Unfortunately, I prefer to use notepad++ but it does not have this key functionality.

For example, later on when working on a project, or even to remember when I have done something previously, I would like to insert such date and time stamps, to recall when such steps/action took place, for example, putting together an RCA (Root Cause Analysis) document or even to remember something.

There is an external plugin called “TextFX Characters” that offer this functionality, but for security reasons I'm not allowed to install plugins. I suspect the majority of other users out there may be in the same situation as me, not allowed to install plugins.

### Steps to Reproduce the Issue

1. Not applicable
2. 
3. 

### Expected Behavior

Critical functionality missing from notepad++

### Actual Behavior

Not applicable

### Debug Information

Not Applicable

**Comment by dail8859** [comment] 2017-01-24 16:03
Duplicate of #497

**Comment by Olifair** [comment] 2019-04-16 14:45
I would also be very much interested in this functionality, especially of one would be able to choose the format (e.g. only date, no time).

**Comment by atbirder** [comment] 2019-05-06 09:14
I add to this request... For many years I also use notepad++ on MS. After a break of some days and an executed update of n++ I miss the "Timestamp-Function" again. Every time I set up a new machine and install n++, this is my first act, to add the "Timestamp-Function again. It looks like the "TextFX Characters" Plugin was deactivated. I read here and #497 that it is not up to date. A simple "Timestamp-Function" is highly appreciated. Best from Vienna, M.

**Comment by Olifair** [comment] 2019-05-07 11:15
@atbirder  have a look at this thread at sourcefoge "A small script to insert date and/or time " : 
https://sourceforge.net/p/npppythonscript/discussion/1188886/thread/22a63d6c05/#113c

works with PythonScript plugin and you can play with the format as much as you like :-)

**Comment by Gitoffthelawn** [comment] 2021-01-18 23:55
> works with PythonScript plugin and you can play with the format as much as you like :-)

This is what I do, but loading all of PythonScript just to insert a timestamp/datestamp does seem like overkill.  Also, with this technique, for each Notepad++ session, the first time you try to insert a timestamp/datestamp into a file, there is a noticeable delay.

It would be wonderful to have this basic functionality baked into Notepad++.

**Comment by sasumner** [comment] 2021-01-19 00:06
>the first time you try to insert a timestamp/datestamp into a file, there is a noticeable delay.

Longer that it would take you to check the date and time visually, and then type it as text?

Change PythonScript _Configuration_ so that _Initialisation_ is `ATSTARTUP` rather than `LAZY` (but that probably only shifts the delay).

>and uses up precious RAM

You must be as old as your username implies if this kind of thing concerns you.

>It would be wonderful to have this basic functionality baked into Notepad++.

Apparently it isn't likely to happen.

**Comment by dail8859** [comment] 2021-01-19 01:57
@Gitoffthelawn Personally I'm a bit biased and prefer LuaScript and it is _much_ lighter weight than PythonScript. ;)

**Comment by Gitoffthelawn** [comment] 2021-01-19 09:11
@dail8859 wrote:
> @Gitoffthelawn Personally I'm a bit biased and prefer LuaScript and it is _much_ lighter weight than PythonScript. ;)

Thanks for the idea of a better - hopefully temporary - workaround.  The more light weight the better for such a simple task!  What would the basic LuaScript be to output the date/time?  If you provide the following format, I can figure it out from there:   

`YYYY/MM/DD<space>HH:MM:DD<space>`  
(where HH is a 24-hour time format, and everything is forced to the number of digits specified:   
eg. `2021/01/02 03:04:05 `  for 3:04:05am on the 2nd of January in the year 2021).

Anything special to assign it to F5 for LuaScript?

**Comment by dail8859** [comment] 2021-01-19 12:14
@Gitoffthelawn 

You can add this to LuaScript's startup script and make sure to disable F5 in the shortcut mapper so it doesn't trigger the 'Run...' command. Restart N++ and you are good to go.

```lua
npp.AddShortcut("Insert Current Date/Time", "F5", function()
	editor:ReplaceSel(os.date('%Y/%m/%d %H:%M:%S', os.time()))
end)
```

**Comment by sasumner** [comment] 2021-01-19 12:54
>LuaScript ... is much lighter weight than PythonScript


@dail8859 

I'm confused about the "weight" issue.
Are we still talking about load time?  Or some other "weight"?
And I suppose I mean a "weight" that is really relevant is what I'm asking about...not some don't-waste-my-time RAM thing... :-)

**Comment by dail8859** [comment] 2021-01-19 13:11
> Are we still talking about load time?

Load time, hard drive space, ram.

**Comment by Gitoffthelawn** [comment] 2021-01-19 21:36
@dail8859 Thank you very much.  I will give it a try when I'm back on a Windows box.  That Lua syntax sure is interesting... ;)

**Closed** 2021-08-18 10:50 UTC
Labels: enhancement, accepted
