### ISSUE TITLE
Reload message doesn't appear under certain conditions

### ISSUE THREAD

**Issue by gpetrowitsch** [notepad-plus-plus/notepad-plus-plus#8538] opened 2020-07-08 15:18 UTC
I have a session with split views (some files moved to "Other View").
Let's say file A is active in the left view, file B is active in the right view.

I edit file B with Notepad++, then switch to a different program (Alt-Tab) and edit with that program file A.
Now I switch back to Notepad++ (Alt-Tab again).

There should be "Reload" message displayed for file A, because I edited that file outside of Notepad++, but this message doesn't appear for file A. It also doesn't appear when I click into the left view where file A is.

### Debug Information
Notepad++ v7.8.7   (64-bit)
Build time : Jun  5 2020 - 02:38:56
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1803
OS Build : 17134.1550
Current ANSI codepage : 1252
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PreviewHTML.dll XMLTools.dll

**Comment by sasumner** [comment] 2020-07-08 15:21
Duplicate of (or a lot of commonality with) #7581

**Comment by sasumner** [comment] 2020-09-09 11:53
Closing due to the aforementioned commonality.
@gpetrowitsch if you have additional concerns/information, please add to 7581.

**Closed by sasumner** 2020-09-09 11:53 UTC
