### ISSUE TITLE
Wrong interpretation of special character

### ISSUE THREAD

**Issue by Padg13** [notepad-plus-plus/notepad-plus-plus#1197] opened 2015-11-29 10:35 UTC
Hello,

if I try to search for the german special character "ß" in Notepad++ it also interprets it as "ss".
So if I for example try to search and replace "ß" with "&szlig" in a html document my div tags look like "div cla&szlig=something" instead of "div class=something".

Thank you for your time and please excuse possible writing mistakes as I'm no native speaker.
Padg13

**Comment by guy038** [comment] 2015-12-07 19:37
Hello **padg13**,

**Two** possibilities, with **`ß`** in the **search** field and **`&szlig`** in the **Replace** field :

- In **Regular** or **Extended** search mode : just **set** the **Match case** option

- In **Regular expression** mode : It should be **OK**, whatever the **Match case** option is **checked** or **not**

Tested with, both, **UTF-8** and **ANSI** encodings !

Best Regards,

guy038

**Comment by MetaChuh** [comment] 2019-04-13 02:16
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:16 UTC
