### ISSUE TITLE
[Feature request/ Enhancement]: Document list - move files in list to change files order in tabs

### ISSUE THREAD

**Issue by deweblooper** [notepad-plus-plus/notepad-plus-plus#12797] opened 2023-01-12 14:41 UTC
### Expected Behavior
Please, it could be handy, to have possibility to change order of tabs for opened files, with moving file rows in Document list block, for example when we have opened 25 files. It takes long to move certain tab to more comfortable position (for last opened file to transfer tab to some position near to start). 

### Actual Behavior
We have opened multiple files in NPP, and we see horizontal tabs for files, sometimes more than 10 (some are hidden out of NPP window)
With activated menu: View > Document list we see in special block list of all files opened in NPP.
We see in Document list file moving when we move any of file tab (left or right).
But it is imposible to do it in opposite: to move file row in Document list, to change position of file in tabs row.

![npp-screen](https://user-images.githubusercontent.com/57491379/212095900-b31076f7-1275-46ba-ab2d-f56fff316e99.png)

### Steps to Reproduce the Issue
1.  open more files in NPP (more than 5 to see better what happens)
2. activate Document list in View > Document list (if not checked) and make it visible
3. move file tab from position (left or right) to change order of files in file tabs row
4. you will see moving file row in Document list block to new position as file tab moving
5. try to move file row in Document list (up or down) - it won´t move

**Comment by robotboy655** [comment] 2023-01-18 00:07
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2221

**Closed** 2023-01-18 00:33 UTC

**Comment by deweblooper** [comment] 2023-02-02 15:11
thanks to @robotboy655 and @ArkadiuszMichalski we go back in line to 2016 :)
