### ISSUE TITLE
There are string not settable from XML

### ISSUE THREAD

**Issue by akittino** [notepad-plus-plus/notepad-plus-plus#1487] opened 2016-02-17 04:49 UTC
Take a look into these screenshots:

Every text that is in English on screens are not settable in XML.
Maybe I did not defined proper entry, if you know that, please let me know :)
1. Untranslatable check box.:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13099985/a7f93a98-d538-11e5-8f8b-b35c164c045d.png)
2. Dialog # 1:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13099992/b79c186c-d538-11e5-8157-071c9c1d913a.png)
3. Dialog # 2:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13099994/bbeae4b6-d538-11e5-8541-dabbd6a520ab.png)
4. Dialog # 3:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100000/c1ce2d16-d538-11e5-8cf4-85b0769c2e75.png)
5. Restore recent closed file:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100004/c98203ac-d538-11e5-8dc3-39ec7a83d193.png)
6. Column mode tip message box:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100007/ce365db2-d538-11e5-9506-28ec33519091.png)
7. SummaryBox:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100010/d1e32d00-d538-11e5-8c35-25aea6099778.png)
8. Shortcut mapper:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100012/d5c059ca-d538-11e5-8bb5-afff42100468.png)
9. Trim Trailling and Save:
   ![image](https://cloud.githubusercontent.com/assets/6968485/13100015/d9c9c8da-d538-11e5-84a8-b0e48f750873.png)
10. Run entries:
    ![image](https://cloud.githubusercontent.com/assets/6968485/13100017/dfa58a96-d538-11e5-830a-ab052f07f705.png)

**Comment by MetaChuh** [comment] 2019-04-11 23:47
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)


###################################
2019.04.10:

we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 23:47 UTC
