### ISSUE TITLE
Replace just one more time

### ISSUE THREAD

**Issue by amtype** [notepad-plus-plus/notepad-plus-plus#11113] opened 2022-02-01 03:35 UTC
### Description of the Issue

I'm requesting a new feature in the Replace dialog box: a button that replaces just one more instance of the searched text without continuing the search. The ancient (but wonderful) XyWrite word processor had such an option.

### Steps to Reproduce the Issue

1. In the Replace dialog box I insert text in "Find what" and "Replace with" fields
2. I search and replace until I land on the last instance I want to replace
3. There I want to replace once more and close the Replace dialog box, leaving the cursor at the last replacement

### Expected Behavior

If there already is a way to accomplish "replace once more and stop here", please tell me.

### Actual Behavior

I click on the Replace button and Notepad++ performs the replace and takes me to the next instance of the Find what text--as expected. Before I perform the last desired replacement, I have to write down text surrounding the replacement I'm about to perform so I can search back to find that exact replacement. Alternatively, instead of clicking Replace to make the last desired replacement, I can click Close to close the Replace dialog box and perform the final replacement manually, which is inconvenient.

**Comment by alankilborn** [comment] 2022-02-01 12:32
This issue has come up before and the somewhat lackluster solution that come out of it was:

![image](https://user-images.githubusercontent.com/77065706/151968862-7134b83d-a6cb-4b55-8a5e-856cf0f42063.png)

**Comment by amtype** [comment] 2022-02-02 04:49
Thanks! I agree, lackluster and more tedious, but workable without requiring me to write down what I'm replacing.

**Comment by alankilborn** [comment] 2022-02-02 12:03
Another way to do it is to _Undo_ (Ctrl+z) the last replacement and then _Redo_ (Ctrl+y) it.  This will leave your caret near your desired point.

**Comment by amtype** [comment] 2022-02-02 23:41
I assumed Ctrl+z would undo all the replacements, not just the last one. Thanks for the tip!

**Comment by alankilborn** [comment] 2022-02-24 13:52
Duplicate of #3214

**Comment by donho** [comment] 2022-04-27 16:21
Implemented.

**Closed by donho** 2022-04-27 16:21 UTC
