### ISSUE TITLE
Issue with vertical scroll bar slider

### ISSUE THREAD

**Issue by richlux** [notepad-plus-plus/notepad-plus-plus#3338] opened 2017-06-01 15:13 UTC
### Description of the Issue

When word-wrap is on and lines are wrapped, using the vertical scroll bar slider and dragging it all the way down to the bottom does not scroll the file all the way to the end.  It leaves a number of lines off the bottom of the screen. The larger the file, the more lines are left off. I was testing with files of 5,000 lines or more.

### Steps to Reproduce the Issue

1.  Open large text file (over 5,000 lines)
2.  Click and drag the vertical scrollbar slider all the way to the bottom
3.  Notice that the file does not scroll all the way to the bottom.  Some lines are still off the screen

### Expected Behavior

The file should scroll all the way to the bottom.

### Actual Behavior

The file does not scroll all the way to the bottom.  Some lines are still off the screen.

### Debug Information

Notepad++ v7.4.1 (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll PluginManager.dll

**Comment by dail8859** [comment] 2017-06-01 15:29
Please post your debug info.

**Comment by richlux** [comment] 2017-06-01 16:10
I have edited the original post because I did more testing and the problem seems to only occur when word-wrap is on and lines are wrapped.  Debug info is below and screenshots are attached.

Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll PluginManager.dll

**Comment by richlux** [comment] 2017-06-01 16:12
I have updated the original issue with more details on when it happens and the debug info.  Screenshots will follow.

**Comment by richlux** [comment] 2017-06-01 16:24
Here is a text file at the top with the window wide enough so lines are NOT wrapped:
![top without wordwrap](https://cloud.githubusercontent.com/assets/25157703/26689686/8132a968-46c4-11e7-9978-890cf1f22f44.png)

Here is the text file scrolled to the Bottom with the vertical slider.  Notice the "END" and line 9571 shows:
![scrolled to bottom without wordwrap](https://cloud.githubusercontent.com/assets/25157703/26689747/bcc45102-46c4-11e7-9144-e570aa04662b.png)

Here is a text file at the top with a smaller window so lines are wrapped:
![top with wordwrap](https://cloud.githubusercontent.com/assets/25157703/26689767/cac201aa-46c4-11e7-917b-e07e3b8e3ef0.png)

Here is the text file with words wrapped scrolled to the Bottom with the vertical slider.  Notice the last line "END" does not show and the last line on the screen is 9564:
![scrolled to bottom with wordwrap](https://cloud.githubusercontent.com/assets/25157703/26689793/e31c94fe-46c4-11e7-836c-2ca00cfca20f.png)

**Comment by dail8859** [comment] 2017-06-01 17:11
Hmm...not sure what is going on. I can't replicate it myself:

![capture](https://cloud.githubusercontent.com/assets/3694843/26691512/691f8e0c-46cb-11e7-9f10-86b5d377fa77.PNG)
```
Notepad++ v7.4.1   (64-bit)
Build time : May 18 2017 - 02:02:28
Path : C:\Users\xxx\Desktop\npp.7.4.1.bin.minimalist.x64\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS : Windows 7 (64-bit)
Plugins : none
```

Maybe someone else will have better luck.

**Comment by richlux** [comment] 2017-06-01 17:31
Did you scroll down all at once?  If you stop along the way, the issue doesn't happen.

Rich

**Comment by dail8859** [comment] 2017-06-01 17:32
Yes I tried several different ways but it always worked fine for me.

**Comment by richlux** [comment] 2017-06-01 17:55
Not that it will help, but here's a screen recording of what I see:

![notepad scrollbar issue](https://cloud.githubusercontent.com/assets/25157703/26693347/d49c335a-46d1-11e7-918f-46aafb83c7f9.gif)

**Comment by SinghRajenM** [comment] 2017-06-01 17:56
Couldn't reproduce even with 32 bit. However, little similar issue observed. After restarting N++, it does not show the last line. However caret remains same.

Before  Closing:
![image](https://cloud.githubusercontent.com/assets/14791461/26693268/3b8818be-4721-11e7-9118-c6a32076bab3.png)


After Restart:
![image](https://cloud.githubusercontent.com/assets/14791461/26693294/4e484258-4721-11e7-852e-444c98c2077b.png)

**Comment by dail8859** [comment] 2017-06-01 18:03
@SinghRajenM 

> it does not show the last line.

Probably the same thing as #3015 (and other very similar issues) which seems to be specifically addressed by the Scintilla documentation:

> If a file is read and the scroll position moved to a particular line in the text, such as occurs when a container tries to restore a previous editing session, then the scroll position will have been determined before wrapping so an unexpected range of text will be displayed. To scroll to the position correctly, delay the scroll until the wrapping has been performed by waiting for an initial SCN_PAINTED notification.

**Comment by MetaChuh** [comment] 2019-05-02 12:46
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-02 12:46 UTC
