### ISSUE TITLE
xml syntax highlighting bug

### ISSUE THREAD

**Issue by fpierrat** [notepad-plus-plus/notepad-plus-plus#1320] opened 2016-01-04 10:39 UTC
Hi,
I have XML files that don't display correctly, regarding syntax-highlighting.
I tried to shorten my file (over 20000 lines) to a very short sample: please see attached file.

Though it is correct XML, it breaks the syntax highlighting.

This seems to be due to CDATA in which npp-highlighter still interpretes some "<% ... %>" signs as tags.
Note that these signe are also interpreted in comments.
This appears like a first bug to me.

Then, IN THESE <%...%> tags, if a double quote is encoutered it has to be closed or the whole highlighting breaks. If a single quote is encoutered, then the whole highlighting breaks, wether this single quote is closed or not.

(Or have I done anything wrong with user-defined options? I don't think I have...)

[buggy.xml.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/77054/buggy.xml.txt)
![screenshot](https://cloud.githubusercontent.com/assets/16537778/12087846/91c82538-b2d6-11e5-8613-6ad6ed7d5fe0.PNG)

**Comment by MetaChuh** [comment] 2019-04-11 01:09
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 01:09 UTC
