### ISSUE TITLE
CTRL-F  Search

### ISSUE THREAD

**Issue by tmieske** [notepad-plus-plus/notepad-plus-plus#4052] opened 2018-01-05 18:57 UTC
When I press CTRL-F, the program 'crashes! 
I completely deleted the program, saved options & program directory

I'm running Win 7 64-Bit

**Comment by yut45390** [comment] 2018-01-05 23:50
I cannot reproduce.
When I press Ctrl-F, the Find Dialog box appears.
Which version of notepad++ are you using?
I am using windows 10 and notepad++ 7.5.3

**Comment by tmieske** [comment] 2018-01-06 02:50
It started about 5 versions back.  I uninstalled it completely today,reboot and installed today's new release.  Sam problem.
-ted

**Comment by cmeriaux** [comment] 2018-01-06 10:50
Try to do a fresh install (remove your user files C:\Users\xxxx\AppData\Roaming\Notepad++ ) 
Your saved configuration may be corrupted and generates silent exceptions.

You also can try the protable version https://notepad-plus-plus.org/repository/7.x/7.5.4/npp.7.5.4.bin.zip

**Comment by tmieske** [comment] 2018-01-06 18:57
See note below:

**Comment by cmeriaux** [comment] 2018-01-07 20:38
don't forget to close the issue.

**Comment by tmieske** [comment] 2018-01-08 15:55
Sorry, I'm old, cold and slow!!  Please send me a link so I can closethis issue.  Thanks, Ted

**Closed** 2018-01-08 16:42 UTC
