### ISSUE TITLE
"Unknown exception" with certain shortcuts

### ISSUE THREAD

**Issue by sheelx86** [notepad-plus-plus/notepad-plus-plus#1675] opened 2016-03-23 15:56 UTC
Hello,

After removing/disabling 4 specific shortcuts (listed below) in the Shortcut mapper, every start of NP++ gives a messagebox "Unknown exception". After clicking OK, the program still works normally. Removing the altered lines in the shortcuts.xml fixes the message box again.

The names are (all in the Scintilla command section):
SCI_ZOOMIN
SCI_ZOOMOUT
SCI_SETZOOM
SCI_SELECTIONDUPLICATE

Disabling other Scintilla shortcuts is no problem.

I noticed that of all shortcuts I tried in the Scintilla section, in shortcuts.xml, these four are the only ones with a menuCmdID different from 0.

Newest NP++ version (6.9), both WIndows and Wine
Happens without plugins too.

**Comment by ClaudiaFrank** [comment] 2016-03-24 20:31
Cannot confirm reported behaviour on Windows 7 x64 using latest 7z package.

![issue 1675](https://cloud.githubusercontent.com/assets/16170444/14030413/b9dc3cb0-f207-11e5-8eb5-1f3d36b4d4be.png)

**Comment by MetaChuh** [comment] 2019-04-13 02:22
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:22 UTC
