### ISSUE TITLE
Sorting file in "Folder as Workspace" by name

### ISSUE THREAD

**Issue by schadin** [notepad-plus-plus/notepad-plus-plus#1743] opened 2016-04-12 15:41 UTC
Hello. It would be great if the files in the workspace tree, sorted by name, now they are in some random order.

**Comment by jarrod180** [comment] 2017-06-26 00:48
See #1541

**Comment by SinghRajenM** [comment] 2019-04-27 17:18
@MetaChuh this is feature request which is duplicate of #1541. It is good to close this ticket and track it at #1541.

**Closed** 2019-04-27 18:40 UTC
Labels: duplicate
