### ISSUE TITLE
Unexplained crashing on fresh install (NVDA issue)

### ISSUE THREAD

**Issue by TheQuinbox** [notepad-plus-plus/notepad-plus-plus#11133] opened 2022-02-05 15:45 UTC
### Description of the Issue
I just installed Notepad++ 8.3, and when I try to open it, it opens for about a second, then promptly crashes.
### Steps to Reproduce the Issue
I ran the 8.3 installer, grabbed from the website, then attempted to run the program after it was installed.
### Expected Behavior
Notepad++ to launch without issue.
### Actual Behavior
NPP crashes, hardly even giving me enough time to know that it opened.

**Comment by TheQuinbox** [comment] 2022-02-05 15:49
I grabbed the 8.1.9.3 installer and it worked just fine (NPP opens without issue). It seems to only be a bug in the latest NPP

**Comment by TheQuinbox** [comment] 2022-02-05 15:51
Yup, every version works except 8.3. This is... Very odd.

**Comment by dail8859** [comment] 2022-02-05 15:53
Try launching Notepad++ from the command line with the `-noPlugin` argument. It may be a plugin compatibility issue.

**Comment by alankilborn** [comment] 2022-02-05 16:24
>Yup, every version works except 8.3. This is... Very odd.

It is not that odd as 8.3 is the first version to add in huge file support, and that drove a lot of changes that caused a lot of problems, and all of these problems aren't sorted out yet.

**Comment by TheQuinbox** [comment] 2022-02-05 20:58
I tried both -noplugin and -nosession, nothing fixed it.

**Comment by TheQuinbox** [comment] 2022-02-06 04:20
No, I actually cannot, because the program doesn't open for long enough.

**Comment by xomx** [comment] 2022-02-06 08:56
@TheQuinbox 

Could you please try the same but with replaced notepad++.exe from here:
- [32-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/42465473/job/x4opkfaihq3ilbhu/artifacts)
- [64-bit](https://ci.appveyor.com/project/donho/notepad-plus-plus/builds/42465473/job/q82pc3sc2iq4rhpj/artifacts)

(rename your current 'notepad++.exe' file to e.g. 'notepad++.exe.original', then rename the downloaded exe-file, e.g. 'Notepad++.x64.Release.exe', to 'notepad++.exe' and put it into your notepad++.exe directory)

**Comment by ArkadiuszMichalski** [comment] 2022-02-06 13:50
@TheQuinbox 
Try also with [fresh portable](https://github.com/notepad-plus-plus/notepad-plus-plus/wiki/Testing#using-the-latest-release-portable-version-of-notepad).

**Comment by TheQuinbox** [comment] 2022-02-06 20:15
@xomx, I tried that executable, and it has the same problem.

I use a screen reader, and so I open it, hear the start of the title bar read, but I can't arrow around or do anything else, and it promptly extis after around a second.

@ArkadiuszMichalski, I had no plugins installed anyways (I literally never used Notepad++ on this machine until I installed this version).

**Comment by xomx** [comment] 2022-02-06 22:39
@TheQuinbox 

Try to use MS SysInternals [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) utility:

- extract the attached zip-archive to your N++ main directory (where is the 'notepad++.exe' file), it is better to use a portable N++ package for this test (otherwise there could be a write access problem for the output files later)
[NppProcdump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8011353/NppProcdump.zip)
- for the 64-bit N++ run the 'npp-dump64.cmd' (doubleclick or enter on this file), 'npp-dump32.cmd' otherwise
- after N++ exit you should find two files in your main N++ directory: something like 'notepad++.exe_xxxxxx_xxxxxx.dmp' and 'npp-dump-output.txt', please zip them and post here (or similar)

**Comment by lukaszgo1** [comment] 2022-02-11 13:17
This crash occurs only when using a screen reader (to be able to present content of the document they query the Scintilla control via its API). For NVDA this is being tracked in https://github.com/nvaccess/nvda/issues/13311
@xomx  The crash dump and the procdump info [is here](https://github.com/notepad-plus-plus/notepad-plus-plus/files/8048875/npp_crash.zip)

**Comment by xomx** [comment] 2022-02-11 23:14
There is a first chance EXCEPTION_ACCESS_VIOLATION (0xC0000005) followed by the STATUS_FATAL_USER_CALLBACK_EXCEPTION (0xC000041D).

In the callstack is visible:
000000c0`5b5ff9f8 00007ffd`4eaa078e win32u!NtUserMsgWaitForMultipleObjectsEx+0x14
000000c0`5b5ffa00 00007ffd`292330ad user32!RealMsgWaitForMultipleObjectsEx+0x1e
000000c0`5b5ffa40 00000000`00000000 nvdaHelperRemote+0x30ad

The crash probably originates from the 'nvdaHelperRemote.dll' module (timestamp: Thu Feb 10 00:31:52 2022 (62044ee8), checksum: 00127ef4).

Here I ended up my crash-analysis, because of any attempt to install (or even run a portable version of) NVDA froze my computer totally (hard shutdown was required).

But I did a quick look at the NVDA code and think I have found a possible [culprit](https://github.com/nvaccess/nvda/blob/master/source/NVDAObjects/window/scintilla.py#L66). It is probably the same 2GB+ Scintilla interface incompatibility (`long Sci_PositionCR` changed to `intptr_t Sci_PositionCR`) as in the other cases, see e.g.:
[.\scintilla\include\Sci_Position change](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/db3308329bd23a073b7de6f4ded2a523b282fcc3
)
https://community.notepad-plus-plus.org/topic/22471/recompile-your-x64-plugins-with-new-header
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11104#issuecomment-1025206468

So authors of NVDA should update accordingly their cpMin/cpMax type to be a __int64 one at x64 builds for all the Notepad++ versions 8.3+:
```
class CharacterRangeStruct(ctypes.Structure):
	_fields_=[
		('cpMin',ctypes.c_long),
		('cpMax',ctypes.c_long),
	]
```

**Comment by lukaszgo1** [comment] 2022-02-11 23:47
> Here I ended up my crash-analysis, because of any attempt to install (or even run a portable version of) NVDA froze my computer totally (hard shutdown was required).

That is pretty unfortunate - while this is quite offtopic for this issue submitting a bug report on NVDA's bug tracker would be welcome.


> So authors of NVDA should update accordingly their cpMin/cpMax type to be a __int64 one at x64 builds for all the Notepad++ versions 8.3+:

I've confirmed locally that changing the type from `c_long` to `c_longlong` fixes the crash. Is there any other way to detect what type should be used for cpMin/cpMax - relying on version number and architecture should be a last resort especially given the fact that NVDA supports Scintilla in general and Notepad++ seems to deviate from the officially documented interface by redefining these types?

**Comment by xomx** [comment] 2022-02-12 00:10
@lukaszgo1 

> `c_long` to `c_longlong`

I do not know your custom types, but a `longlong` is surely a bad one there (it remains __int64 = 8 bytes in size in  32-bit builds).

> Is there any other way to detect what type should be used for cpMin/cpMax - relying on version number and architecture should be a last resort especially given the fact that NVDA supports Scintilla in general and Notepad++ seems to deviate from the officially documented interface by redefining these types?

Yes, this is a problem (I just edited my previous post with a note about that, when you posted this).

**Comment by lukaszgo1** [comment] 2022-02-16 18:42
Please forgive my ignorance (I've done very little programming in lower level languages) but I'm not sure I follow why `c_longlong` is a bad type for 64-bit builds of NPP 8.3+. If the concern is that it remains 8 bytes in 32-bit builds this is no concern at all since NVDA is purely 32-bit process therefore we need to just define different structures for 32-bit builds of Scintilla and use `c_long` there and `c_longlong` in the structure for 64-bit builds. In short we cannot use a single type which would have a appropriate size on a given architecture since we are exclusively 32-bit process. The only question which remains open is how to detect what size to use - unless there are any better ideas I'll probably just use `c_long` for 32-bit processes and `c_longlong` for 64-bit builds of Notepad++ 8.3+ though this is pretty ugly IMO.

**Comment by xomx** [comment] 2022-02-16 19:23
@lukaszgo1 

> If the concern is that it remains 8 bytes in 32-bit builds

Yes, that was my thought there (I know almost nothing about the NVDA system functioning).

> we need to just define different structures for 32-bit builds of Scintilla and use `c_long` there and `c_longlong` in the structure for 64-bit builds

Ok, then this is correct (but the `c_longlong` part only for the 64-bit N++ v8.3+, as you have correctly written hereafter)


> I'll probably just use `c_long` for 32-bit processes and `c_longlong` for 64-bit builds of Notepad++ 8.3+

This is also correct.


> though this is pretty ugly IMO

I know. But this is a price for the Scintilla hesitation (though I fully understand that, when I see the current compatibility problems in N++ plugins) in updating their `Sci_PositionCR`, as they announced in the past. Out of curiosity, I checked the SciTe source code to see, how they handle this problem with the 2GB+ files - [comment](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/11047#issuecomment-1016190937). But that means to completely overwrite otherwise fully functional N++ code (ditto for all the N++ plugins, which are currently using the `Sci_PositionCR`).

**Comment by rbakhshi72** [comment] 2022-02-18 12:30
I can't navigate between lines that I wrote in 8.3. I didn't this issue in 8.2. 
My screen reader is JAWS.

**Comment by TheQuinbox** [comment] 2022-02-18 12:47
@rbakhshi72, JAWS has always had issues with NPP. That's because it uses a Scintilla control for its edit field, and JAWS can't interact with these. See Notepad 2 / Notepad 3 for another example of this.

**Comment by rbakhshi72** [comment] 2022-02-18 13:38
This issue is for all screen readers. I have this issue with JAWS, too. I didn't have this issue in 8.2.

**Comment by lukaszgo1** [comment] 2022-02-18 23:24
I've created https://github.com/nvaccess/nvda/pull/13364 to fix this on NVDA's side - lets hope this would be merged in time for the next stable release.
@rbakhshi72  To fix this for JAWS you need to report this to Freedom Scientific.

**Comment by rbakhshi72** [comment] 2022-02-20 21:52
@lukaszgo1 
Hello, but I don't have any issue in Notepad++ 8.21.

**Comment by TheQuinbox** [comment] 2022-02-22 20:02
This seems to have been fixed in the latest NVDA. Should I close this? JAWS is a hole other monster, so not sure if keeping it open because of that will really be productive.

**Comment by rdipardo** [comment] 2022-02-22 22:35
+1 for closing this. The related problem with [the add-on] is already being tracked [elsewhere].


[the add-on]: https://github.com/nvaccess/nvda/pull/13364#issuecomment-1045524646
[elsewhere]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11198#nvda-addon

**Comment by donho** [comment] 2023-05-25 18:33
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11629#issuecomment-1135434814

**Closed by donho** 2023-05-25 18:33 UTC
