### ISSUE TITLE
The horizontal scrollbar area is never decreased.

### ISSUE THREAD

**Issue by tonyalpskog** [notepad-plus-plus/notepad-plus-plus#3256] opened 2017-05-09 08:46 UTC
### Description of the Issue
If you write a long text row the scroll bar space will increase but if you delete that long row the scrollbar won't decrease.

### Steps to Reproduce the Issue
1. Create a new file.
2. Write a short row.
3. Write a very long row (beyond the window edge)
4. Now the horizontal scrollbar will have an increased area.
5. Delete the long row.
6. ==> The horizontal scrollbar area doesn't decrease.
Now it doesn't matter if you save the file or reload from disk. The issue is still there.
You have to close the file and re-open it to make the scrollbar updated.

### Expected Behavior
Horizontal scrollbar should decrease its scrollable area according to the longest existing row during editing.

### Actual Behavior
The horizontal scrollbar area is never decreased.
It doesn't matter if you save the file or reload from disk. The issue is still there.
You have to close the file and re-open it to make the scrollbar updated.

### Debug Information
Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll sql.dll XMLTools.dll

**Comment by dail8859** [comment] 2017-05-09 11:59
Duplicate of #2687, #2211, #926,

**Comment by MetaChuh** [comment] 2019-05-01 23:04
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 23:04 UTC
