### ISSUE TITLE
Installations path 

### ISSUE THREAD

**Issue by gohelkrunalsinh** [notepad-plus-plus/notepad-plus-plus#9364] opened 2021-01-07 06:52 UTC
### Description of the Issue

I install notepad++ in other derive than  "C:" so when any new update comes and I try to install updated notepad++ by default path that set in the installation wizard is it show me to install s/w in c: not in by default install drive.

### Steps to Reproduce the Issue

1. install notepad++ in other than c: (Like E: , F:).
2. now update notepad++  and follow installation steps.
3. at a path of installing you show path pointe c:

### Expected Behavior
 at installing you show path pointe to an actual path where notepsde++ now installed 

### Actual Behavior
 at installing you show path pointe to C: path  

### Debug Information
Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : F:\Krunal gohel\app\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2004
OS Build : 19041.685
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by zanud** [comment] 2021-01-07 15:35
Looks like a duplicate of #9346

**Comment by sasumner** [comment] 2021-01-07 15:37
Closing as duplicate.
PLEASE people, search for existing open issues before creating a new one.

**Closed by sasumner** 2021-01-07 15:37 UTC
