### ISSUE TITLE
Crashes if you hold right mousebutton and scroll a couple of times

### ISSUE THREAD

**Issue by Dunderbullen** [notepad-plus-plus/notepad-plus-plus#2828] opened 2017-01-26 08:21 UTC
If you have a couple of tabs open and hold right mouse button and scroll a couple of times, NPP crashes.
This happens on Windows 10 at least.
It also kind of messes up the mouse cursor, and you need to move the mouse around a bunch before you can kind of control it again. 

### Steps to Reproduce the Issue

1. Hold right mouse button
2. Scroll
3. Profit

### Debug Information
Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll

**Comment by SinghRajenM** [comment] 2017-01-27 16:01
Duplicate of #2603

**Comment by SinghRajenM** [comment] 2017-01-28 14:07
Almost similar to #2603

**Closed** 2017-03-06 02:26 UTC
