### ISSUE TITLE
Feature Request: Option to turn off nagging update dialog

### ISSUE THREAD

**Issue by pdc4444** [notepad-plus-plus/notepad-plus-plus#7998] opened 2020-03-02 14:56 UTC
### Description of the Issue
There is no option in the preferences menu to turn off the check at the startup of notepadd++ which says something to the effect off "new version of notepadd++ available!". This dialog is a nagging annoyance. I'm happy with how the program functions already and don't want to update it.

### Steps to Reproduce the Issue
1. Have an older version of notepad++ installed
2. Open it
3. Observe the nagging update dialog

I think this only happens once per restart, but I restart my computer enough that I find it annoying enough to come to github and open this issue. Yes I could just update, but this will continue to happen on future updates!

### Expected Behavior
I expected the 'enable notepad++ auto updater' checkbox to also remove this nagging dialog. 

### Actual Behavior
Even with enable notepad++ auto updater' checkbox unchecked the dialog still pops up.

### Debug Information
Notepad++ v7.6.2   (64-bit)
Build time : Jan  1 2019 - 00:02:38
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppFTP.dll NPPJSONViewer.dll 

I appreciate Notepadd++ and I literally use it everyday at home and on the job. I don't see a reason to update since I use it mainly for clipboard storage / viewing of raw log files. Please remove the nagging dialog or give me some option that will disable it.

**Comment by abcasada** [comment] 2020-04-18 02:00
I can confirm the same issue. Please provide a solution. This is very frustrating across multiple computers.

**Comment by abcasada** [comment] 2020-04-18 02:22
@pdc4444 I have discovered this issue was reported previously in #5375 and was fixed by commits f3261f862022a4aa5d14de19a2b56358713bfd95 and 1c55e0daa7c214e14e8025d2346526ecfb2e9221, as discussed in the comments of the issue. The fix is present in v7.8.5, which unfortunately those of us who don't wish to update might never have seen without research.

I would recommend closing the issue now.

**Closed** 2020-04-18 12:16 UTC

**Comment by sasumner** [comment] 2020-04-18 12:37
>The fix is present in v7.8.5, which unfortunately those of us who don't wish to update might never have seen

Does anyone else see the irony here, or maybe it is best called a Catch-22? :-)

**Comment by Sharlikran** [comment] 2020-05-02 06:03
![image](https://user-images.githubusercontent.com/1912426/80856504-712e4300-8bff-11ea-9282-e5e798d80463.png)

![image](https://user-images.githubusercontent.com/1912426/80856518-8e631180-8bff-11ea-9dd2-c535d36f55a2.png)

I have updated each and every time, so since at the moment I have 7.8.6 I am fairly certain I had 7.8.5 yet it is STILL AS<KING ME to update. I have it unchecked!11!!!! So if it is unchecked it should not be telling me that something has updated!

**Comment by Sharlikran** [comment] 2020-05-02 06:07
I was just asked to update, AGAIN! Yet the option is disabled! As I noted in #5375
