### ISSUE TITLE
Feature request - Yes/No to all

### ISSUE THREAD

**Issue by skironDotNet** [notepad-plus-plus/notepad-plus-plus#2724] opened 2016-12-28 16:33 UTC
Please add custom buttons or if not possible create custom message box:
1. For "The file X doesn't exits anymore. Keep this file in editor", please add [Yes to all] and [No to all]
2. For "The file X has changed, reload?", please add [Yes to all] and [No to all]
3. To any similar question, please add [Yes to all] and [No to all]

Reason, loaded 100 files to do search/analysis, then deleted all files before closing npp, must answer 100 times, or kill npp process   

Thank you

**Comment by joeybab3** [comment] 2016-12-29 19:14
I agree with this one it can be a little tedious when you end up changing a lot of files to yes/no all of them

**Comment by glennfromiowa** [comment] 2017-08-19 12:46
Request #2867 is newer, but is related to this request, and addresses losing the focus of the tab when this happens also.

**Comment by 42degrees** [comment] 2018-10-12 20:04
This is essentially a duplicate of [1087](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1087) with minor differences in how it is handled.

**Comment by skironDotNet** [comment] 2018-10-12 21:14
@42degrees how switching tabs is relevant to confirmation Yes to all] and [No to all]
npp can ask if load modified file but does not switch tab, ie you hit yes to all and will load all in background but stay in current tab

**Closed** 2019-03-17 12:05 UTC

**Comment by sasumner** [comment] 2019-10-15 12:11
Sort of a side note:  Notepad++ 7.8 adds the "No to All" and "Yes to All" functionality to the Save dialog, but not to the Reload dialog.
