### ISSUE TITLE
Form "User Defined Language": button Dock/undock loose translate on click

### ISSUE THREAD

**Issue by WinterSilence** [notepad-plus-plus/notepad-plus-plus#10891] opened 2021-12-07 19:54 UTC
**Before click**
![изображение](https://user-images.githubusercontent.com/3521094/145096749-61b510ce-462b-4010-9485-28248067453d.png)
**After**
![изображение](https://user-images.githubusercontent.com/3521094/145096852-e34e4b39-bd9c-4682-b809-12695535774d.png)

Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\YandexDisk\NppBackup
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1387
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DoxyIt.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment] 2021-12-07 21:25
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8020.

**Closed by ArkadiuszMichalski** 2021-12-07 21:25 UTC
