### ISSUE TITLE
 Incremental Search: add match whole word only

### ISSUE THREAD

**Issue by martbase** [notepad-plus-plus/notepad-plus-plus#1308] opened 2016-01-02 02:56 UTC
I am using the incremental search located above the status bar to quickly make adjustments to multiple files and I have just realized it would be much easier and faster to search for exact words for example tags in css files.

This will avoid locating similar words when accuracy is required as in below all three occurrences match when searching for **nav**
- nav ul {} <- tag name
- .nav {} <- class name
- .navbar {} <- longer class name

**Comment by Duellmann** [comment] 2017-12-25 12:10
This would be extremely helpful. Can't believe it's not yet there in 2017. But even Firefox took years to implement that option...

**Comment by cmeriaux** [comment] 2017-12-25 14:30
You may use the classic search menu. They are a lots of feature inside.

**Comment by MetaChuh** [comment] 2019-04-13 02:02
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:02 UTC
