### ISSUE TITLE
Bug on Splitter of two File views

### ISSUE THREAD

**Issue by allainsim45** [notepad-plus-plus/notepad-plus-plus#1047] opened 2015-10-24 14:44 UTC
The "Doc Switcher" and the "Find Result" (research in all documents) are separated from the files view by a splitter, it possible to have two views for files  themselves separated by a splitter that can rotate left or right.

I noticed a bug which is to move the splitter of "Doc Switcher" or "Find Result", and move the mouse cursor from the first view to the second:
 a strange phenomenon occurs because the splitter separates the two views is moving when the mouse tries to cross it, this phenomenon disappears as soon as one selects another visual element other than splitters.

Thank.

**Comment by sanastasiou** [comment] 2015-10-26 07:39
I think it's the same as this one:

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/881

**Comment by MetaChuh** [comment] 2019-04-10 23:40
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-10 23:40 UTC
