### ISSUE TITLE
Opening multiple files at once will cause previous tabs to disappear

### ISSUE THREAD

**Issue by OsakaWebbie** [notepad-plus-plus/notepad-plus-plus#14161] opened 2023-09-20 02:22 UTC
I love the fact that NPP will remember unsaved files when I close and reopen it. And if I open one file (using double-click or right-click->Open or Open With in File Explorer, or any other method), NPP will launch and open the file in a fresh tab with my other in-progress stuff still in the other tabs. But just now I selected **two files** and chose "Open" from the context menu, and NPP launched with **only** those files - the other in-process stuff I was trusting NPP to save for me is gone!

### To replicate:
1. With one or more non-empty files still in tabs, close NPP. (It doesn't matter if the files are saved or unsaved.)
2. In File Explorer (or your favorite substitute - I use Directory Opus), select more than one file.
3. Right-click and select Open With (or just Open if the file type is associated with NPP). The previous files will no longer be in tabs, with no warning.

### Debug Info:
```
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\PortableStuff\PortableApps\Notepad++Portable\App\Notepad++64\notepad++.exe
Command Line : "C:\Users\karen\Documents\Kizuna\Clients\DMI\Student_list.php"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : C:\PortableStuff\PortableApps\Notepad++Portable\Data\Config
OS Name : Windows 11 Home (64-bit)
OS Version : 22H2
OS Build : 22621.2134
Current ANSI codepage : 932
Plugins : 
    ComparePlugin (2.0.2)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)
```

**Comment by xomx** [comment] 2023-09-24 10:06
Ok, I found some problem, but I was able to add additional file-tabs to my existing N++ session.

This is my N++ session before opening two additional files from the Windows Explorer ('new 2' is an empty N++ tab):
![npp-opened_session](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/17a4ca23-e909-43ad-a636-804c45c8fc9b)

When I selected one from my two additional files in the Explorer, I can see & use the mentioned 'Open with' (and that file is then added to the N++ tabs ok):
![npp_open_one_additional_file_from_Explorer](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/75f1584b-fb24-43be-adc2-9ff523445839)

> 3\. Right-click and select Open With (or just Open if the file type is associated with NPP). The previous files will no longer be in tabs, with no warning.

As you said, when I tried to select both of the files, I did not see the 'Open with':
![npp_open_two_additional_files_from_Explorer](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/2b03870a-005a-4ebe-a322-7a975b58524a)

So I associated the *.txt files with my N++ and used the 'Open' menu item instead with this result:
![npp_using_Open_on_two_additional_files](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/cca670bd-065a-41d6-b74f-f01276edb57f)
As you can see, the files are opened without loosing the previously opened tabs (missing empty 'new 2' is ok, as it was an empty file-tab there, which is not stored in the N++ session), but the arrangement of the N++ tabs is a little bit odd.
And the N++ ? > Debug Info... shows only this for the cmdline: `Command Line : "C:\TEMP\NPP\#14161\file2toopen.txt"
`

But when I used the 'Edit with Notepad++' N++ shell menu item instead, I was able to open the additional files and the order was as I expected so:
![npp-opening_additional_two_files](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/0c927b34-4986-40e5-a45f-a11765a0948b)

cmdline there is ok too:
```
Notepad++ v8.5.6   (64-bit)
Build time : Aug 15 2023 - 15:29:28
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : "C:\TEMP\NPP\#14161\file1toopen.txt" "C:\TEMP\NPP\#14161\file2toopen.txt" 
```

**Comment by OsakaWebbie** [comment] 2023-09-24 11:49
@xomx  The reason it only opened one file in your case is that the other file was already open. N++ won't open a second copy. To test this bug properly, at least two files you choose to open from File Explorer need to be files that are not already open in N++.

**Comment by xomx** [comment] 2023-09-24 12:09
> The reason it only opened one file in your case is that the other file was already open. N++ won't open a second copy.

Sorry, I am really lost. (?)

> To test this bug properly, at least two files you choose to open from File Explorer need to be files that are not already open in N++.

And I tested so and it worked for me ok (file1&2toopen.txt were not opened before):
![npp-opening_additional_two_files](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/13075183/827708ef-6f15-4982-abc0-3f5dde42bd15)

**Comment by Yaron10** [comment] 2023-09-24 12:42
@OsakaWebbie,

I'm using the NPP portable version, and have manually associated some files with NPP.
Using Open in File Explorer (Win 10), I can not reproduce your issue.
It might have to do with "Directory Opus".

@xomx,

> but the arrangement of the N++ tabs is a little bit odd.

I can reproduce that.
Interestingly - using an older NPP version, the problem only occurs on opening **3** files.

**Comment by OsakaWebbie** [comment] 2023-09-24 16:07
I also am using the portable version (managed by PortableApps). I noticed that I was on version 8.5.6 when I first tested, but since then I've updated and am now on 8.5.7. I also tested with File Explorer instead of Directory Opus. It still fails.

Here are two screenshots. The first is just before I close NPP with content in it - one real file and one unsaved bit of test text. Notice that what's open on the left is File Explorer, not Directory Opus.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4035163/9c608361-c026-4f69-a7a4-3c854fb65708)

After that, I closed NPP (that step is important - it does not fail if NPP is open), and then right-clicked on the two files I had highlighted, and selected Open.

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4035163/a6e1f4a6-b211-4afc-a0d7-bc68e40b21c0)

This is the result:

![image](https://github.com/notepad-plus-plus/notepad-plus-plus/assets/4035163/c6cb94aa-db26-40e3-b9e3-510c03083e25)

As you can see, the files that were previously open are gone.

**Comment by Yaron10** [comment] 2023-09-24 16:27
@OsakaWebbie,

Could you please try it with a _fresh_ portable NPP _not_ managed by PortableApps?

**Comment by Yaron10** [comment] 2023-10-22 12:57
See https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14252#issuecomment-1774088325.

**Comment by donho** [comment] 2023-10-22 15:48
@xomx 
> As you can see, the files are opened without loosing the previously opened tabs (missing empty 'new 2' is ok, as it was an empty file-tab there, which is not stored in the N++ session), but the arrangement of the N++ tabs is a little bit odd.
And the N++ ? > Debug Info... shows only this for the cmdline: Command Line : "C:\TEMP\NPP\#14161\file2toopen.txt" 

It's normal behaviour. Here the explanation:
When you choose 2 files and launch them via Explorer, the system launch 2 commands `Notepad++ "C:\TEMP\NPP\#14161\file1toopen.txt"` & `Notepad++ "C:\TEMP\NPP\#14161\file2toopen.txt"` simultaneously. The first command launches Notepad++ which opens "file1toopen.txt", and the 2nd command calls also Notepad++ - but since it exists already a Notepad++ instance, the existence of Notepad++ instance opens "file2toopen.txt", then updates the `Command Line`. Hence such result.

**Comment by donho** [comment] 2023-10-22 15:49
@OsakaWebbie 
It's definitely a critical issue.
However, I cannot reproduce this issue at all under Notepad++ v8.5.8 x64 official release.

Could you use the Notepad++ official release v8.5.8 portable version instead of the release of PortableApps to reproduce the bug?
Because we don't know if the binary of Notepad++ from PortableApps has been modified. Even it is not, I do believe this issue could come from PortableApps environment or the way of Notepad++ installation done by PortableApps.

If the bug cannot be reproduced in Notepad++ official release (So far 3 persons including me), there's nothing that can be done for this issue.

**Comment by OsakaWebbie** [comment] 2023-10-22 23:29
Hmm, I thought I reported back on this thread after trying it with a non-PortableApps version, but I don't see any mention of it here - sorry. A month ago I did discover that it doesn't fail with the regular version, so I reported it on the PortableApps forum and got acknowledgement and details here: https://portableapps.com/node/69289

**Comment by xomx** [comment] 2023-10-23 08:43
@OsakaWebbie
So I recommend closing of this issue.

@donho 
> It's definitely a critical issue.

It's not a N++ problem - quoting from the portableapps-answer:

"
Windows Explorer is launching the app twice in rapid succession rather than passing the multiple files on a single command line. 
That's why it works when you drag the files (passed on one command line) but not when you open a couple in Windows Explorer (launching twice really quickly).
As the launcher is starting up, the second instance is started before the first instance has finished setting itself up, so the session file is getting overwritten by the second instance as the first is still loading.
This is an issue with the PA.c Launcher itself in conjunction with how some apps load. It likely wasn't an issue when load times were a few milliseconds slower, but it is now.

To avoid triggering the bug for right now, make sure Notepad++ Portable is already open before opening multiple files at the same time.
"

**Closed** 2023-10-23 10:07 UTC

**Comment by OsakaWebbie** [comment] 2023-10-23 10:08
Okay, I'm closing this. Sorry again that I failed to circle back here after the conversation on the PA forum.

**Comment by donho** [comment] 2023-10-23 13:09
@OsakaWebbie @xomx 
Thank you for your answer!
FWIW: https://github.com/notepad-plus-plus/notepad-plus-plus/pull/14252#issuecomment-1775154843
