### ISSUE TITLE
[Feature Request] Make ZERO WIDTH SPACE have some visual component

### ISSUE THREAD

**Issue by GhbSmwc** [notepad-plus-plus/notepad-plus-plus#8284] opened 2020-05-19 09:30 UTC
Try sorting this:
```
https://pbs.twimg.com/media/
https://twitter.com/
​https://pbs.twimg.com/media/
```
Somehow, the last URL is positioned wrong.

Wait.., there is a zero-width character on the third (before the h in https) which is "​" (select to see that character). I think NP++'s show symbol should also show such characters.

**Comment by xylographe** [comment] 2020-05-19 10:54
The character is U+200B (Unicode name: ZERO WIDTH SPACE).

**Comment by sasumner** [comment] 2020-05-19 11:31
> I think NP++'s show symbol should also show such characters.

What's your opinion on what it should look like?

**Comment by GhbSmwc** [comment] 2020-05-19 20:01
A yellow line, much like when you make it show spaces and tabs.

**Comment by sasumner** [comment] 2020-05-19 20:16
@GhbSmwc I took the liberty of renaming your issue; hopefully that is okay with you. :-)

**Comment by sasumner** [comment] 2020-05-19 20:16
This is going to depend upon Scintilla.

**Comment by sasumner** [comment] 2020-05-19 20:27
This was "addressed" by the Scintilla project back in 2013:  https://sourceforge.net/p/scintilla/feature-requests/980/

Their response was to add an API so that you can represent any character you want, "specially":
https://www.scintilla.org/ScintillaDoc.html#SCI_SETREPRESENTATION

The representation mechanism is the "white text on black box" variety, much like line-endings look when visually enabled in Notepad++:

![image](https://user-images.githubusercontent.com/30118311/82374292-d7330c80-99ec-11ea-9020-48cc6c021ce4.png)

Here's an example of what it would look like to set the representation to `""` (an empty string), the narrowest possible thing, which is harmonious with a "zero-width" character:

![image](https://user-images.githubusercontent.com/30118311/82374618-4c064680-99ed-11ea-9346-33c2667ececb.png)

I suppose it is "workable" but I'd say it isn't ideal.

**Comment by Daksol** [comment] 2020-11-20 17:02
This request has come up more than once if you look back through the Issues history. I encountered this problem when "screen scraping" data out of certain HTML pages.

**If this is not taken up, then maybe add a Caution to NPP interface to say that the option "View-> Show Symbol -> Show All Characters" does NOT show characters such as ZeroWidthSpace and friends.**

Only way to detect a Zero Width Space is to move a cursor along a line of text while watching the character position number in the status bar,

**Comment by Daksol** [comment] 2020-11-20 17:10
Previous Issues raised on the same topic, going back to 2015

https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5062
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4731
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/827

**Comment by sasumner** [comment] 2020-11-20 18:00
@Daksol 

>This request has come up more than once 

And note that it remains an "open" request

> "View-> Show Symbol -> Show All Characters" does NOT show characters such as ZeroWidthSpace and friends.

The "Show All Characters" verbage is historical and comes from a time when "space", "tab" and "end-of-line" characters were the only things that weren't shown.  Today that menu item might be "Show space, tab, CR, LF"

The author of N++ has declined my proposal for making such things visible as a core Notepad++ feature, but has kept the door somewhat open by this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5062#issuecomment-699563782

You can have these characters visible RIGHT NOW if you are willing to use a Pythonscript to control them.

**Comment by donho** [comment] 2020-11-22 23:53
@sasumner 
> The author of N++ has declined my proposal for making such things as you mention visible as a core Notepad++ optional feature, but has kept the door somewhat open by this: #5062 (comment)

The issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5062 talked about the BOM, which is visible, but removed by Notepad++, so I won't reopen it since it's not an issue. OTOH, I agree the invisible Unicode character is an issue.
So let's add `Show Zero Width Non Breaking Space` menu command between `Show End Of Line` & `Show All Character`, and make `Show All Character` command shows also ZWNBS chars.

**Comment by sasumner** [comment] 2020-11-23 00:00
@donho 

Correct about BOM.  BOM should never be visible, except I guess HexEditor plugin?  (Not our problem!)

5062 was also used as a springboard for the general discussion of invisible characters.

> let's add Show Zero Width Non Breaking Space menu command

But...there are many more invisible UTF-8 characters than that, that users could want.
Hmmm...
Let me come up with a proposal for how to best handle this?

**Comment by donho** [comment] 2020-11-23 00:10
> Correct about BOM. BOM should never be visible, except I guess HexEditor plugin? (Not our problem!)

Yes, HexEditor does some dirty hacking to show these 3 bytes.

> But...there are many more invisible UTF-8 characters than that, that users could want.

Then let's add "Show all invisible character" menu command - I don't think users care about showing which kind of invisible characters.

> Let me come up with a proposal for how to best handle this?

OK. Please keep it simple & stupid.

**Comment by Daksol** [comment] 2020-11-24 16:11
@sasumner. Thanks for getting this back on the program, so to speak.

Some thoughts on what would be best way of handling hidden characters - this derived from the usecases I was encountering when I first discovered zero width space and friends.

My real world interaction with hidden chars has often been when troubleshooting web pages, urls et al. And what I have often found myself doing is putting a string into (say Excel) and adding formulae to show the Unicode code for each item. That then shows up the non-breaking spaces, zero-width spaces etc. Not very convenient to say the least.

* For the most common hidden, unprintable and whitespace characters
   * Examples: CR, LF, Tab, Space as at present, (suggest adding NonBreakingSpace here) 
   * With Show-All-Chars: 
      * show as descriptive block - exactly what happens in Notepad++ currently
* For other unprintable chars
   * Examples: Zero width space
   * With Show-All-Chars:
       * either show as dark-shaded rectangular block, and with onmouseover show the hex value
       * or as highlighted group of characters showing including Unicode value, eg _**%200B**_

**Comment by sasumner** [comment] 2020-11-24 16:17
@Daksol said

>Some thoughts on what would be best way of handling hidden characters...

Notepad++ only has limited control over the display; the display is primarily controlled by Scintilla.
The only possible thing that N++ can do with these characters is what is shown with CR and LF in my previous posting [HERE](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8284#issuecomment-631063957).
So any such characters would have to look like those.

**Comment by ArkadiuszMichalski** [comment] 2020-11-24 16:46
@sasumner But indicator for this not_visible_chars must be the orange dot (same as for standard space)? I would prefer to somehow distinguish a normal space from the other characters.

**Comment by sasumner** [comment] 2020-11-24 16:50
@ArkadiuszMichalski 
Scintilla controls the "orange dot" behavior, for but only for U+0020 character.
The best Notepad++ can do for making any new characters visible is like what it does for CR and LF.
In the default theme this means whiteish characters on a black background.

**Comment by sasumner** [comment] 2020-11-24 17:39
So here's a sampling of what could be done, stolen from a forgotten discussion thread on the Community site:

![image](https://user-images.githubusercontent.com/30118311/100131199-be029100-2e51-11eb-8588-791e153e0a17.png)

**Comment by ArkadiuszMichalski** [comment] 2020-11-24 17:44
OK thx, looks good, at least for me.

**Comment by sasumner** [comment] 2020-11-26 01:38
Here's the complete list as of now, that I plan to implement:

![image](https://user-images.githubusercontent.com/30118311/100297989-f42d3700-2f5d-11eb-919d-bafb1a70089c.png)

For some of these, I just made up an abbreviation so that the representation, the white letters on the black background, doesn't become too big/wide.  I don't know if there is a standard abbreviation...does anyone?

Comments are most welcome.

More "simple and stupid" spec'cing out of this feature to come...

**Comment by donho** [comment] 2020-11-26 12:52
@sasumner 
Are they (in the list above) all not displayed currently in Notepad++ ?

**Comment by sasumner** [comment] 2020-11-26 13:42
>Are they (in the list above) all not displayed currently in Notepad++ ?

Correct.
I do not know if the list is complete, but all of those currently in the above list are currently invisible in N++.
Unless someone says "You forgot about 'foo' !" we can start with the above list.

**Comment by sasumner** [comment] 2020-11-26 13:52
@donho

Here's the file the above image was made from, if you want to "see" how N++ displays the invisible characters:

[invisible_utf8_chars.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5603372/invisible_utf8_chars.txt)

**Comment by sasumner** [comment] 2020-11-26 13:55
BTW, here is what is displayed for the invisible_utf8_chars.txt in Windows' notepad.exe :

![image](https://user-images.githubusercontent.com/30118311/100359074-1017f380-2fc5-11eb-949c-f24d38a92b2d.png)

**Comment by donho** [comment] 2020-11-26 13:58
@sasumner 
For me FF, NEL, LS & PS are displayed:

![image](https://user-images.githubusercontent.com/90293/100359177-7ddd1300-2ff7-11eb-9212-231a7e2178f2.png)

My debug info:
```
Notepad++ v7.9.1   (32-bit)
Build time : Nov  2 2020 - 01:03:56
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 2004
OS Build : 19041.630
Current ANSI codepage : 1252
Plugins : DSpellCheck.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NppXmlTreeviewPlugin.dll 
```

**Comment by sasumner** [comment] 2020-11-26 13:59
Notice U+202E.
There may be some additional effort for Notepad++ (Scintilla) to actually respect something like the "right-to-left override" and actually display sections of a file in RTL form.

**Comment by sasumner** [comment] 2020-11-26 14:02
Here's what the Scintilla demo editor SciTE/Sc1 (v.4.3.0) shows for the invisible_utf8_chars.txt file:

![image](https://user-images.githubusercontent.com/30118311/100359836-18bcf980-2fc6-11eb-8692-951fb647377c.png)

**Comment by sasumner** [comment] 2020-11-26 14:03
@donho said:

>For me FF, NEL, LS & PS are displayed

I can confirm that -- Oops, my error on those.
We can drop them from the list.

**Comment by sasumner** [comment] 2020-11-26 14:07
>Notice U+202E.

Disregard what I said earlier about this.
It appears to already be working (reference @donho 's earlier screenshot -- the line with U+202E is in RTL).
I'm not sure yet why it isn't showing RTL for me, or in Scintilla demo editor!

**Comment by donho** [comment] 2020-11-26 14:11
@sasumner 
> For some of these, I just made up an abbreviation so that the representation, the white letters on the black background, doesn't become too big/wide

So with one command, all the invisible Unicode chars will be shown as your screenshot (https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8284#issuecomment-734023781) ?

**Comment by sasumner** [comment] 2020-11-26 14:11
Here is what I see in N++ 7.9.1 -- why don't I see the same as @donho for 2060, 2066 - 2069 ??

![image](https://user-images.githubusercontent.com/30118311/100360667-35a5fc80-2fc7-11eb-8ae8-83dc3f315a10.png)

**Comment by sasumner** [comment] 2020-11-26 14:15
@donho said

>So with one command, will all the invisible Unicode chars be shown as your screenshot

I didn't get to that part of the "simple & stupid" spec yet :-)
But yes, one "user" command.
As to Scintilla commands, it takes one [SCI_SETREPRESENTATION](https://www.scintilla.org/ScintillaDoc.html#SCI_SETREPRESENTATION) call for each UTF+8 character you want to set a representation for.
Or, alternatively, to turn off with [SCI_CLEARREPRESENTATION](https://www.scintilla.org/ScintillaDoc.html#SCI_CLEARREPRESENTATION)

**Comment by sasumner** [comment] 2020-11-26 14:17
@donho 

I case you can't tell, I really like the "simple & stupid" thing :-)

**Comment by donho** [comment] 2020-11-26 14:21
> Here is what I see in N++ 7.9.1 -- why don't I see the same as @donho for 2060, 2066 - 2069 ??

I have tested on my another laptop, both have the same result. I guess you are under the OS older than mine ?

**Comment by sasumner** [comment] 2020-11-26 14:25
@donho says:

> I guess you are under the OS older than mine ?

Slightly older:

```
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.1518
Current ANSI codepage : 1252
```

This introduces the complication of how well this entire feature works for all users of N++, under so many various versions of Windows...

**Comment by sasumner** [comment] 2020-11-26 14:26
I probably should do a larger survey of how other editors display this `invisible_utf8_chars.txt` file...

**Comment by ArkadiuszMichalski** [comment] 2020-11-26 14:40
I got this:
![image](https://user-images.githubusercontent.com/2730894/100363820-8df7f100-2ffd-11eb-8711-cde9e0b8d799.png)

**Comment by sasumner** [comment] 2020-11-26 15:27
@ArkadiuszMichalski @donho So there's 3 of us in our sampling, and all 3 get different results.  
Maybe attempting to do something for this feature is just asking for trouble, what with all the variation?

**Comment by sasumner** [comment] 2020-11-26 15:30
Uploading a new version of the file, this time with a byte-order-mark, to ensure that editors it is tried upon know that they are opening a UTF-8 encoded file:

[invisible_utf8_chars_2_w_bom.txt](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5603867/invisible_utf8_chars_2_w_bom.txt)

**Comment by donho** [comment] 2020-11-26 16:58
@sasumner 
I'm confused... now 2060, 2066, 2067, 2068 and 2069 in both files you provided don't display on my 1st laptop.

**Comment by donho** [comment] 2020-11-26 17:00
5 Unicode chars in both files you provided do display on my 2nd laptop.

**Comment by ArkadiuszMichalski** [comment] 2020-11-26 17:01
With BOM I got this:
![image](https://user-images.githubusercontent.com/2730894/100377381-7460a480-3011-11eb-9452-d1a557cacf34.png)

**Comment by sasumner** [comment] 2020-11-26 17:10
@ArkadiuszMichalski I see no changes in your two screenshots, except the lines that have been removed from the second file.  This is not a problem, I'm just stating it for the record.

**Comment by sasumner** [comment] 2020-11-26 17:12
@donho said:

>I'm confused... now 2060, 2066, 2067, 2068 and 2069 in both files you provided don't display on my 1st laptop.

>5 Unicode chars in both files you provided do display on my 2nd laptop.

That confuses me as well.  :-(

**Comment by donho** [comment] 2020-11-26 17:14
`config.xml` matters!

@sasumner 
use this one to check:
[config.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/5604341/config.zip)

**Comment by sasumner** [comment] 2020-11-27 13:04
So this N++ preference setting is going to impact how these characters appear:

![image](https://user-images.githubusercontent.com/30118311/100451909-29cd3f80-3086-11eb-8ba5-da10429155a7.png)

To hopefully be very clear, this is how the `invisible_utf8_chars_2_w_bom.txt` file appears for me with "direct write" unticked:

![image](https://user-images.githubusercontent.com/30118311/100452044-6862fa00-3086-11eb-894a-815bbdf225b2.png)

And here's what it looks like for me with "direct write" ticked:

![image](https://user-images.githubusercontent.com/30118311/100452127-8892b900-3086-11eb-9246-12e748911a8e.png)

I'm not at all sure what this means for the future of this feature.

@donho How long is the "direct write" preference setting going to remain?  Forever?
I turned it on and it has remained on forever for me.
No downside, only advantages.
To get good data on users that it wouldn't work well for, it should have been made to be on by default, and users could turn it off.
The way it was done, nobody notices it to turn it on and try.
Thus we get no feedback about users that it causes a problem for.

**Comment by donho** [comment] 2020-11-28 14:48
@sasumner 
> How long is the "direct write" preference setting going to remain? Forever?

I did read feedback that in some environments there's the performance issue when "direct write" is ON. So our experience can not be representative for the whole community. Furthermore, I don't want to scarify existing option (which could concern the performance issue) for a new feature which is benefit for less people.

The workaround for me is just treat 2060, 2066, 2067, 2068 and 2069 as invisible chars so there's no ambiguity whether if "direct write" is ON. What do you think?

**Comment by sasumner** [comment] 2020-11-28 16:22
>The workaround for me is just treat 2060, 2066, 2067, 2068 and 2069 as invisible chars so there's no ambiguity whether if "direct write" is ON

Yes, that can work.
Or, we detect when direct-write is "on" and then don't include those in the list of characters to set a new representation for.

**Comment by donho** [comment] 2020-11-28 19:01
@sasumner 
> we detect when direct-write is "on" and then don't include those in the list of characters to set a new representation for.

Yes, it could work if Scintilla has a message for that. The Notepad++'s option regarding "direct write" in Parameters class cannot be counted on because it's applied to next session.

**Comment by sasumner** [comment] 2020-11-28 19:29
>if Scintilla has a message for that.

[SCI_GETTECHNOLOGY](https://www.scintilla.org/ScintillaDoc.html#SCI_GETTECHNOLOGY)

**Comment by sasumner** [comment] 2020-12-04 20:53
Another user request: https://community.notepad-plus-plus.org/topic/20428/highlight-non-breaking-spaces

**Comment by sasumner** [comment] 2020-12-11 18:30
A couple of older but related Community links:

- https://community.notepad-plus-plus.org/topic/18900/persistent-highlight-of-characters-e-g-no-break-space
- https://community.notepad-plus-plus.org/topic/15649/visualization-for-zero-width-characters

**Comment by sasumner** [comment] 2020-12-19 23:41
One more that this feature would probably help:  https://community.notepad-plus-plus.org/topic/20490/invisible-spaces

**Comment by alankilborn** [comment] 2022-08-09 15:14
@ArkadiuszMichalski I think the "scintilla dependent" label can be removed from this issue.  Scintilla already supports everything needed to allow any normally-invisible character to be shown.  I suppose it is left to the programs that embed Scintilla to decide how they want to do this; at least up to now Scintilla has not added a default visual component to more than the "low ASCII" range (NULL, SOH, STX, ..., GS, RS, US).

**Comment by Daksol** [comment] 2022-08-09 15:50
@arkadiuszmichalski - Good to see some movement on this one. fyi There is another Open Issue #8530  which covers the same ground as #8384 which could perhaps also be updated. 

- Title:- Display Zero-width non-joiner and Zero-width joiner as their ISO keyboard symbols
- Link https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8530
- There is a more detailed discussion of the issues - and links to a related Scintilla issue (which was closed in Scintilla without action).
- The "scintilla dependent" tag is still attached to 8530 - could you remove that one too? - via same logic

**Comment by alankilborn** [comment] 2022-08-09 17:31
>Good to see some movement on this one.

What "movement"??
:-)

**Closed** 2023-02-05 03:20 UTC
Labels: accepted
