### ISSUE TITLE
<style>tag don’t highlighting in php file in <html> tag why??

### ISSUE THREAD

**Issue by jeyjey95** [notepad-plus-plus/notepad-plus-plus#11797] opened 2022-06-14 17:08 UTC
<style>tag don’t highlighting in php file in < html > tag why?
<img width="206" alt="1653206166456-capture-d-écran-2022-05-22-095025" src="https://user-images.githubusercontent.com/107499803/173636115-8108bebf-3aa6-448c-bcbf-48e7fcc6233d.png">

i use v8.4.2 64-bit

**Comment by ArkadiuszMichalski** [comment] 2022-06-14 17:16
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5663.

**Closed by ArkadiuszMichalski** 2022-06-14 17:16 UTC
