### ISSUE TITLE
Function List in PHP. If the name of a function starts with "if", the function name gets truncated.

### ISSUE THREAD

**Issue by tontonnono** [notepad-plus-plus/notepad-plus-plus#3321] opened 2017-05-26 22:19 UTC
### Description of the Issue

Function List PHP. If the name of function starts with "if", function name gets truncated.

### Steps to Reproduce the Issue

1. new PHP file
2. 
function ifsetor( &$val, $default = null){
   return isset($val) ? $val : $default;
}
3. Save php file

### Expected Behavior

Function list shows "ifsetor"

### Actual Behavior

Function list shows "fsetor"

**Comment by MAPJe71** [comment] 2017-05-26 22:31
Duplicate of #981.

**Comment by MalcolmFinlayson** [comment] 2019-12-24 21:21
Solve this issue with this this ticket. Do not open another. This is also reported in notepad-plus-plus/notepad-plus-plus#981 and notepad-plus-plus/notepad-plus-plus#2522.
Both 981 and 2522 have more information

**Closed** 2020-11-05 13:56 UTC
