### ISSUE TITLE
Command "Open User Defined Language folder..." doesn't work

### ISSUE THREAD

**Issue by WinterSilence** [notepad-plus-plus/notepad-plus-plus#10890] opened 2021-12-07 18:36 UTC
https://github.com/notepad-plus-plus/notepad-plus-plus/blob/5d2fc0d8c08e44afec176b3c37987810897e8a5c/PowerEditor/installer/nativeLang/english.xml#L321

Notepad++ v8.1.9.2   (64-bit)
Build time : Nov 21 2021 - 04:30:20
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : C:\YandexDisk\NppBackup
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 19044.1387
Current ANSI codepage : 1251
Plugins : ComparePlugin.dll DoxyIt.dll JSMinNPP.dll MarkdownViewerPlusPlus.dll mimeTools.dll NppConverter.dll NppExec.dll XMLTools.dll

**Comment by ArkadiuszMichalski** [comment] 2021-12-07 21:27
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8394.

**Closed by ArkadiuszMichalski** 2021-12-07 21:27 UTC
