### ISSUE TITLE
Replace notepad.exe with notepad++ in windows 11 stopped working

### ISSUE THREAD

**Issue by RandallFlagg** [notepad-plus-plus/notepad-plus-plus#10739] opened 2021-11-01 10:14 UTC
### Description of the Issue

When I try to replace notepad.exe with notepad++ in windows 11 using the registry notpad.exe still opens instead of notepad++.

### Steps to Reproduce the Issue

1. `reg add "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\notepad.exe" /v "Debugger" /t REG_SZ /d "\"%ProgramFiles%\Notepad++\notepad++.exe\" -notepadStyleCmdline -z" /f`
2. run notepad.exe 

### Expected Behavior

Notepad++ will open

### Actual Behavior

Notepad.exe opened

### Debug Information

Notepad++ v8.1.9   (64-bit)
Build time : Oct 21 2021 - 23:37:53
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 2009
OS Build : 22000.282
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

I see the debug info is showing Windows 10 Pro but I am using Windows 11 Build 22000.282
![image](https://user-images.githubusercontent.com/434681/139656251-7df26674-c8f8-4cbc-8d25-e265eccf6eab.png)

**Comment by rdipardo** [comment] 2021-11-02 03:57
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10653

**Closed** 2021-11-03 12:04 UTC
Labels: duplicate
