### ISSUE TITLE
NPP 8.5.7 Clear Read-Only Flag does not work

### ISSUE THREAD

**Issue by ConSargo** [notepad-plus-plus/notepad-plus-plus#14165] opened 2023-09-21 07:58 UTC
### Description of the Issue
NPP 8.5.7 Clear Read-Only Flag does not work

### Steps to Reproduce the Issue
1. Open a file which has a read-only flag ON. 
2. Confirm flag state via the read-only/r-write tab icon -- if setup to be visible. Alternatively confirm that the file is not editable
3. Right-click on the file's tab, and select the enabled Clear Read-Only Flag
4. Nothing happens 

### Expected Behavior
if setup to be visible, the file's tab icon read-only/r-write icon should switch to r-write,  and the file  should switch to editable state

### Actual Behavior
Selecting Clear Read-Only Flag has no effect. Tab icon remains in read-only state and the file continues to be not editable.
In a different scenario, opening a file with read-only flag OFF, then raising the flag to ON outside NPP, correctly triggers NPP's behavior (i.e. icon changes,  "Clear Read-Only" selection becomes enabled,  and buffer becomes non-editable), but here too toggling Clear Read-Only Flag does not work. NPP 8.5.6 was working properly. I use the feature numerous times daily as other users open common files with other editors which raise the read-only flag.
Incidentally toggling the other "Read Only" option works as expected, but does not solve my problem of course.

### Debug Information
Notepad++ v8.5.7   (32-bit)
Build time : Sep  6 2023 - 23:07:35
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit)
OS Version : 22H2
OS Build : 19045.3448
Current ANSI codepage : 1253
Plugins : 
    3P (1.8.8)
    AutoCodepage (1.2.5)
    ComparePlus (1.1)
    DSpellCheck (1.4.24)
    FingerText (0.5.60)
    LanguageHelp (1.7.5)
    LocationNavigate (0.4.8.1)
    mimeTools (2.9)
    NppConverter (4.5)
    NppExec (0.8.2)
    NppExport (0.4)
    NppQCP (2)
    NppTextFX (0.2.6)
    NppXmlTreeviewPlugin (2)
    PythonScript (2)
    SessionMgr (1.4.4)
    XMLTools (3.1.1.13)
    _CustomizeToolbar (5.3)

**Comment by xomx** [comment] 2023-09-21 10:28
Duplicate of #14138 .
Fixed by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/01ff1eb88163b8d3ca3356e3f8bf8de6fa33e786 (will be in the next N++ version).

**Closed** 2023-09-26 14:43 UTC
