### ISSUE TITLE
notepad++ crashes/closes when used with NVDA screen reader.

### ISSUE THREAD

**Issue by Heumader** [notepad-plus-plus/notepad-plus-plus#11480] opened 2022-04-06 05:46 UTC
### Description of the Issue

NVDA is an open source screen reader allowing blind people to access and operate windows.
It can be downloaded here: https://www.nvaccess.org/download/ 
When NVDA is running, and the notepad++ window gets the focus, it crashes/closes immediatly
### Steps to Reproduce the Issue

1. Start NVDA
2. Start notepad++
3. Focus the notepad++ window
4. notepad++ crashes

### Expected Behavior

notepad++ should not crash/close

### Actual Behavior

notepad++ crashes

**Comment by rimrul** [comment] 2022-04-06 09:00
Duplicate of #11424

**Closed** 2022-04-06 11:51 UTC
Labels: duplicate
