### ISSUE TITLE
[ENHANCEMENT] Allow other delimiter pairs for Ctrl + double-click

### ISSUE THREAD

**Issue by aaaxx** [notepad-plus-plus/notepad-plus-plus#441] opened 2015-07-09 19:07 UTC
It would be really handy. For example, I currently have it set to **> bla  bla <** for HTML, but I'd also like it for square and curvy brackets.

**Comment by Nightfirecat** [comment] 2015-11-03 00:20
:+1:

As I understand it, the difficulty would be in implementing around some quirks that might appear if given multiple sets of delimiters within a given string, like in the following example:

```
<div>
  This string (in its entirety) has a lot of { typeof (variable) }s in it.
</div>
```

**Comment by aaaxx** [comment] 2015-11-03 10:35
Well I guess the logical thing would be to look for the first delimiter to the left of the caret (that's listed in the Settings), and then select from there to the matching closing one.

**Comment by Nightfirecat** [comment] 2015-11-03 17:22
I think it depends more on where you double-click. If you double-clicked within one of the other delimited strings, it seems to me that the expected behavior would be to select only that substring. (eg. "in its entirety", "typeof (variable)" or "variable" if clicking within the parens/brackets)

**Comment by aaaxx** [comment] 2015-11-03 20:21
Huh? Isn't that what I said?

**Comment by Nightfirecat** [comment] 2015-11-03 21:07
Yeah, I just misunderstood how you phrased it... My bad.

**Comment by MetaChuh** [comment] 2019-04-09 23:22
we are closing this issue due to its age and multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html).
if your issue persists, and it is still of relevance to you, please feel free to file a new issue.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-09 23:22 UTC
