### ISSUE TITLE
Enhance Doc Switcher with 3-4 tabs

### ISSUE THREAD

**Issue by joe231** [notepad-plus-plus/notepad-plus-plus#1348] opened 2016-01-10 00:32 UTC
Hi,
     would you consider adding 3 or 4 tabs to the Doc Switcher?

a) Files - the current Doc Switcher view, list of opened files in NPP
b) Folders - add your favorite folders and all the files within can open/close in NPP at one click
c) Sessions - avail sessions are listed, open/close in one click
d)  maybe another tab will be useful too?

for the Folders and Sessions tabs i propose the option to click on the Folder (or Session) closes out all currently opened files and opens all those in the Folder or Session clicked on.  Then there might also be a "+" and "-" sign on the right side of each folder or session listed and if you clicked on those symbols clicking on the "+" would add those files to those currently open in NPP (without closing the currently opened files) and clicking on the "-" would close any files from that Folder or Session currently open in NPP.  

What do you think?

**Comment by MetaChuh** [comment] 2019-04-11 00:54
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:54 UTC
