### ISSUE TITLE
Functionlist and Comments in C

### ISSUE THREAD

**Issue by Simoris** [notepad-plus-plus/notepad-plus-plus#2712] opened 2016-12-21 16:52 UTC
### Description of the Issue

Functions, which start with a Annotation after the {, don't apear in the functionlist.

### Steps to Reproduce the Issue

1.  Create a new file (language: C)
2. Write two functions 

`void test1 (int a) {
	
}

void test2 (int b) { //test
	
}`
3. Open (or refresh) the functionlist.

### Expected Behavior

test1 and test2 are showing up in the functionlist.

### Actual Behavior

Only test1 is show.

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

![unbenannt](https://cloud.githubusercontent.com/assets/24701475/21398022/24f1c79e-c7a6-11e6-8bbd-889cbb8e02f7.PNG)

**Comment by MAPJe71** [comment] 2016-12-21 17:47
Duplicate of/related to #344 and #1023.

**Comment by MetaChuh** [comment] 2019-05-01 16:54
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

<img width="965" alt="Bildschirmfoto 2019-05-01 um 18 54 04" src="https://user-images.githubusercontent.com/45773305/57029609-8d8d4d80-6c42-11e9-944c-c647effa86ae.png">

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 16:54 UTC
