### ISSUE TITLE
change.log always shown on startup

### ISSUE THREAD

**Issue by Lukeeone** [notepad-plus-plus/notepad-plus-plus#2979] opened 2017-03-01 14:54 UTC
### Description of the Issue
change.log does always open on startup of n++, previously it was only shown for first usage after an update

### Steps to Reproduce the Issue
1. use Notepad++ v 7.3.2 64 bit, Win 10 Pro 64bit
2. open Notepad++

### Expected Behavior
change.log is only shown the first time the app is used after an update

### Actual Behavior
change.log is always shown when the app is opened (also if closed during a session)

### Debug Information
Notepad++ v7.3.2   (64-bit)
Build time : Feb 12 2017 - 23:17:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : mimeTools.dll NppConverter.dll

**Comment by dail8859** [comment] 2017-03-01 17:26
Duplicate of #2896. See that issue for a fix.

**Closed** 2017-03-01 17:26 UTC
Labels: duplicate
