### ISSUE TITLE
x64 version can't be set as default app for anything

### ISSUE THREAD

**Issue by Igor-Yavych** [notepad-plus-plus/notepad-plus-plus#3101] opened 2017-03-27 11:15 UTC
### Steps to Reproduce the Issue
1. Click "open with" in context menu
2. Locate Notepad++ exe
3. Select it
4. Nothing happens. It doesn't appear in the list

When you try to set it as default app via control panel, nothing happens either. 

### Expected Behavior
It should appear in the list but it doesn't. This problem doesn't exist with Notepad++ x32 version. 

I'm using Win 7 x 64

**Comment by sekile12** [comment] 2017-03-27 12:02
hi

**Comment by Igor-Yavych** [comment] 2017-04-21 19:03
Hello? Any news? Any additional information you need?

**Comment by Gusgus01** [comment] 2017-07-01 12:09
FYI, the expected behavior occurs on Windows 10 using v7.4.2 x64. Maybe a Windows 7 issue or not an issue anymore.

**Comment by Gusgus01** [comment] 2017-07-01 12:48
I think this is a duplicate of #2454

A workaround is available there are well.

**Comment by mlaffargue** [comment] 2017-09-06 10:00
I had the same problem (with the 32bits version), and resolved it with this  [Microsoft support note](https://support.microsoft.com/en-us/help/2159999/sometimes-you-can-not-associate-a-program-with-an-extension-in-windows)

I installed 64bits version of Notepad++ and because of some problem (plugin manager if I remember) I went back to 32bits version.

It seems that modifying the installed version didn't modify the Registry key : HKEY_CLASSES_ROOT\Applications\notepad++.exe\shell\open\command

It still pointed to `Program Files` instead of `Program Files(x86)`

Putting the right folder made everything work again.

**Comment by ke352802081770314** [comment] 2017-09-10 18:40
I just freshly installed a Win7 Pro x64 machine, and installed Notepad++ x64 on it, and the first time I doubleclick on a .php file, I am asked to choose the program. While I would have preferred being able to choose Notepad++ from the suggestion list without going through browse and selecting the exe, having done that it works fine for me. No register file extension tricks, no registry manipulation needed.

**Comment by MetaChuh** [comment] 2019-05-01 22:48
please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins if you update from version 7.5.9 or below.
if your issue still persists, and it is still of relevance, please feel free to file a new issue as easy to understand and reproducible as possible.

thank you for your help and best regards.

**Closed by MetaChuh** 2019-05-01 22:48 UTC
