### ISSUE TITLE
Make Find/Replace fileds multiline

### ISSUE THREAD

**Issue by babut85** [notepad-plus-plus/notepad-plus-plus#12174] opened 2022-09-14 14:18 UTC
i'm sorry, man, that i'm writing here, but i don't have the strength to be silent anymore. your program is good- it starts up fast and works fast, it can switch to "column mode" simply through an additional Alt(no one can do that!)- this is what i appreciate your program more than any similar ones. unfortunately, it has two critical drawbacks, the most important one is that it does not know how to replace text in multiline mode. yes, some techniques help to smooth out this drawback, but we won't even get close to the functionality that UltraEdit has. this is exactly the drawback because of which i can't get rid of the gluttonous, retarded, full of shit UltraEdit T_T the second drawback is not critical, but also important- the lack of hex-mode editing. yes, there is some external plugin, but it does not know how to work in insert mode(UltraEdit also does not know how, although "hex mode" is native to it).
i ask you to hammer the last nail into the coffin UltraEdit =^.^=

**Comment by alankilborn** [comment] 2022-09-14 14:25
>please save the kittens!

Your issue may get largely ignored, because of this odd title

**Comment by alankilborn** [comment] 2022-09-14 14:25
> i can't get rid of the gluttonous, retarded, full of shit UltraEdit 

>i ask you to hammer the last nail into the coffin UltraEdit

LOL!

**Comment by alankilborn** [comment] 2022-09-14 14:31
>replace text in multiline mode

You really should define what you expect in such a mode.
Or, if others have requested this before -- which I suspect -- then this might have already been laid out.
But if that's the case, then you shouldn't have opened a new issue, you should have just added your comments to an existing issue.
But if you're going to state your vision for it, don't simply say "like UltraEdit" because likely no one knows how that program does it.  We're loyal to N++ after all. :-)
That being said, I have some ideas about how such a mode would work, but this is YOUR issue, not mine. :-)

**Comment by alankilborn** [comment] 2022-09-14 14:36
>the lack of hex-mode editing

To be workable, an "issue" needs to define one specific request. Mentioning a second request for something totally unrelated to the multiline replacement mode request makes this "issue" difficult if not impossible to act upon.

Having stated that, with the advent of Unicode, hex editing in a text editor just really isn't that practical any longer.  Arguments can be made for it, but they just don't feel very strong.

**Comment by babut85** [comment] 2022-09-14 14:50
no space technologies are needed here, two multi-string fields are enough(but necessarily with the ability to scroll the contents and scaling the dialog box itself. the "word wrap" switch will also not hurt), in the first there will be the piece of text that needs to be replaced, and in the second a piece of text to replace. and you don't even need to implement "column mode"(maybe sometime later, since this is a difficult task, the same UltraEdit can't do it), it's enough to keep regexp support- i don't remember a case when it wasn't enough. in general, i don't think that reasonable people need to be explained how to do it, it's just that the problem is that reasonable people are not always busy with the same thing, so they don't know about each other's needs ;)

**Comment by babut85** [comment] 2022-09-14 14:54
> > the lack of hex-mode editing
> 
> To be workable, an "issue" needs to define one specific request. Mentioning a second request for something totally unrelated to the multiline replacement mode request makes this "issue" difficult if not impossible to act upon.
> 
> Having stated that, with the advent of Unicode, hex editing in a text editor just really isn't that practical any longer. Arguments can be made for it, but they just don't feel very strong.

i'll tell you this: humanity has had spaceships for a long time.. but do you have it? ;) the fact that unicode appeared does not mean that everything that preceded it died

**Comment by alankilborn** [comment] 2022-09-14 15:14
>the fact that unicode appeared does not mean that everything that preceded it died

Definitely true.
And Notepad++ maintains its support for older encodings ("everything that preceded it"), just take a look at the _Encoding_ menu.
But there isn't much new feature development along the lines of older encodings, because general interest in this is slowly fading.

Similarly because there isn't much of a general need for hex editing -- your specific need may be much greater than the general need!-- I wouldn't expect a native Notepad++ hex editing capability to appear.  In fact if you REALLY want this, you probably should pursue it through the Scintilla project, as that makes the most sense for how the capability would appear.  Then Notepad++ -- which embeds Scintilla as its editing component -- could simply just "turn it on" and have it.  I have no idea if a hex editing capability is on the development radar for Scintilla.

**Comment by alankilborn** [comment] 2023-02-23 15:46
Can someone...a moderator...give this issue a more meaningful title?

**Comment by ArkadiuszMichalski** [comment] 2023-02-24 01:09
For what because I see two requests.

**Comment by ArkadiuszMichalski** [comment] 2023-02-24 01:17
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/12834.

**Closed by ArkadiuszMichalski** 2023-02-24 01:17 UTC
