### ISSUE TITLE
Cannot drag & drop files to open them anymore

### ISSUE THREAD

**Issue by gabriele-ricci-kyklos** [notepad-plus-plus/notepad-plus-plus#2676] opened 2016-12-13 15:00 UTC
### Description of the Issue

I cannot drag & drop any file from a folder to the notepad++ window in order to open it

### Steps to Reproduce the Issue

1. Open notepad++
2. Try to drag a .txt file from a folder or desktop and try to drop it onto the notepad++ window
3. The cursor became like a 'stop' icon and the file won't open

### Expected Behavior

I expected the file to be opened by notepad++

### Actual Behavior

I can't open a file by dragging & dropping it onto the window of notepad++. This was very convenient

### Debug Information

Notepad++ v7.2.2   (32-bit)
Build time : Nov 27 2016 - 16:31:07
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 10
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll 

I just updated to the latest version through the program's auto update feature.
Also tried to uninstall and install 64-bit version but the problem's still there

**Comment by SinghRajenM** [comment] 2016-12-13 17:44
Possibly duplicate of #2641, #159, #556 and fix is submitted which may be available in next release.

But my curiosity is
1. Is it happening always (even after restarting NPP)?
2. If it is happening always, then how do you open notepad++. I mean do you open notepad++ forcefully "Run As Administrator" or how? I just want to know why Admin mode is ON in debug info.

**Comment by gabriele-ricci-kyklos** [comment] 2016-12-14 08:33
After a reboot, the problem is gone away. So it was just because I actually hadn't restarted my pc.
To answer your question I think to run Notepad++ normally, from the desktop icon or clicking on the shell _Edit with Notepad++_. Anyway the issue is resolved, thank you for support

**Comment by dail8859** [comment] 2017-02-24 18:51
Most likely fixed by #2643

**Closed by dail8859** 2017-02-24 18:51 UTC
