### ISSUE TITLE
Shortcut keys no longer available in "Save file?" dialog

### ISSUE THREAD

**Issue by mjj4791** [notepad-plus-plus/notepad-plus-plus#7577] opened 2019-11-14 19:41 UTC
### Description of the Issue

With latest npp new behaviour around closing open files is introduced. Before, when you closed a file that has changed, you would get a question to "Save the file?", which you could answer with &Yes or &No. This supported the use of the Y and N key as well.

In the new npp version, you have more flexability (Yes to All / No to all), but we have lost the possibility to answer the questions using the Y and N key.

### Steps to Reproduce the Issue

1. Open NPP
2. Open a file & make it dirty
3. Close the file (press the X in top right for example)
4. Question: "Save file "filename"? Yes/No/Cancel/….
5. THis dialog does not support pressing shortcut keys for the Yes/No/etc answers….

### Expected Behavior

The buttons in this dialog should support shortcut keys, and thus allow the answering using the keyboard (like before).

### Actual Behavior

You now have to use the mouse to answer the question.

### Debug Information

Notepad++ v7.8   (32-bit)
Build time : Oct  7 2019 - 00:58:16
Path : C:\prive\PortableApps\PortableApps\Notepad++Portable\App\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : ON
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1809
OS Build : 17763.805
Plugins : ComparePlugin.dll HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll NPPJSONViewer.dll NPPTextFX.dll PluginManager.dll XMLTools.dll

**Comment by sasumner** [comment] 2019-11-14 19:52
Closing as duplicate of #6223.

**Closed by sasumner** 2019-11-14 19:52 UTC
