### ISSUE TITLE
Document map highlight can remain outside of the main window after dragging it around

### ISSUE THREAD

**Issue by Vasto** [notepad-plus-plus/notepad-plus-plus#3204] opened 2017-04-24 12:18 UTC
### Description of the Issue

When Document Map is enabled and you want to drag the main window, the higlight overlay doesn't follow correctly the window movement and can stay outside of it after finishing. This behavior quite frequent when using Notepad++ on the remote desktop.

### Steps to Reproduce the Issue

1. Enable Document Map
2. Start dragging Notepad++ dynamicaly around the desktop
3. - On local machine: 
stop dragging with a move like you wanted to throw the window as far away as possible 
   - On remote destop: 
just stop dragging - it should happen

### Expected Behavior

 Document Map highlight should allign correctly with the main window after dragging it,

### Debug Information

Notepad++ v7.3.3   (32-bit)
Build time : Mar  8 2017 - 03:37:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : mimeTools.dll NppConverter.dll NppExport.dll PluginManager.dll

**Comment by dail8859** [comment] 2017-04-24 12:37
Duplicate of #440, #1247, #1317, #2763, #2840 and probably more

**Closed** 2017-04-24 13:02 UTC
