### ISSUE TITLE
Notepad++ cannot open text file with long path

### ISSUE THREAD

**Issue by IceLancerSR** [notepad-plus-plus/notepad-plus-plus#10493] opened 2021-09-03 03:33 UTC
I found this closed issue #4483 
But its still happening. Latest portable npp.8.1.4
File i am trying to open is in 255path , but its file name makes it over the top.
When attempting to open file it just opens blank 
If i shorten the file name i can open without problems
Here is short video trying to open file
https://youtu.be/rXIceqgAeEs

**Comment by ArkadiuszMichalski** [comment] 2021-09-03 10:21
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9181, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4078, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8501, https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5061.

**Closed by ArkadiuszMichalski** 2021-09-03 10:21 UTC
