### ISSUE TITLE
Crash (buffer overrun) in Notepad++ v6.8.8

### ISSUE THREAD

**Issue by MCKSysArgentina** [notepad-plus-plus/notepad-plus-plus#1289] opened 2015-12-27 04:26 UTC
Steps to reproduce:

1) Create a text file with the following python code:
    f = open('C:\bug.txt', 'wb')
    for i in range (500):
        f.write("bla" + str(i) + '\n')
        f.write("pXX\n")
        f.write("ble" + str(i) + '\n')
        f.write("pXX\n")
    f.close()
2) Open created file with Notepad++ v6.8.8
3) Put cursor in the end of the second line (the one with the first "pXX" string).
4) Use ALT+Mouse selection to selec the hole word backwards. All the "pXX" words should be highlighted.
5) Goto "Edit"-"Column Editor" and select "Number to Insert". Put 13 in "Initial number:". Put 1 in "Increase by:". Put the focus in the "Repeat:" textbox and press "OK".
6) An exception should be raised (from Olly 2: Log data, item 0 Address = 00D5043D Message = Access violation when reading [FFFFFFFC] - Shift+Run/Step to pass exception to the program)

**Comment by dail8859** [comment] 2015-12-28 23:22
Doesn't happen for me. Have you tried disabling your plugins?

**Comment by MCKSysArgentina** [comment] 2015-12-28 23:43
Still happens with all plugin removed. I'm on Win 8.1 Pro x86-64. I'm gonna try on a VM and clean installation.

**Comment by dail8859** [comment] 2015-12-29 00:51
Hmm, still can't get it to give me the exception. Maybe someone else can try.

**Comment by MCKSysArgentina** [comment] 2015-12-29 01:17
I'm uploading the crash dump and a video capture to help reproduce the crash (Same Win 7 SP1 i386 VM).
[NppDump.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/73661/NppDump.zip)
[capture.zip](https://github.com/notepad-plus-plus/notepad-plus-plus/files/73662/capture.zip)

**Comment by donho** [comment] 2016-01-30 12:13
@MCKSysArgentina could you provide debug info via menu "?->Debug Info" ?

**Comment by MCKSysArgentina** [comment] 2016-01-30 13:31
This is the dump with all plugin enabled (the crash happens):

```
Notepad++ v6.8.8
Build time : Dec 10 2015 - 01:11:37
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 8.1
Plugins : ComparePlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll PluginManager.dll XMLTools.dll 

```
I tried to reproduce the crash in another machine, and this doesn't happens. What's weird is that this happens inside th VM too

**Comment by donho** [comment] 2016-01-30 13:53
@MCKSysArgentina Could you move all plugins into another folder (ouside of Notepad++ installed dir) and try to reproduce the crash?

**Comment by MCKSysArgentina** [comment] 2016-01-30 14:08
Already done that (remove plugins dir as **dail8859** suggested). The crash remains.

**Comment by MetaChuh** [comment] 2019-04-13 02:05
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
(no extra account is needed, just use your github account to sign in)
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-13 02:05 UTC
