### ISSUE TITLE
Notepad replacement regression

### ISSUE THREAD

**Issue by neodyne** [notepad-plus-plus/notepad-plus-plus#12775] opened 2023-01-07 21:08 UTC
### Description of the Issue
Having replaced stock notepad with notepad++ in registry according to the  [docs](https://npp-user-manual.org/docs/other-resources/), selected formats open in notepad++ v8.4.8 but now additionally display a `Cannot open file " ".` (whitespace within doublequotes) error.

This can be observed by doubleclicking `.ps1` powershell files, or opening registry `.reg` files with the Edit action in the file context menu. Other file formats defaulting to Edit on open may be affected as well. Standard `.txt` files, as well as files potentially associated with (windows) notepad by the user (for example `.cfg`, `.json` , `.log`, `.xml` ...) are unaffected.

### Steps to Reproduce the Issue
1. Replace notepad with notepad++ in registry according to the documentation
2. Create a dummy test.ps1 or test.reg with any content
3. Doubleclick test.ps1, or rightclick->Edit test.reg

### Expected Behavior
File opens (notepad++ <=v8.4.7)

### Actual Behavior
File opens, but a `Cannot open file " ".` message box is displayed first (notepad++ v8.4.8)

![msgbox](https://user-images.githubusercontent.com/45676605/211169681-c835b823-4774-429e-a735-f4bea9fe1e84.png)

### Debug Information
Notepad++ v8.4.8   (64-bit)
Build time : Dec 24 2022 - 19:40:27
Path : C:\npp\notepad++.exe
Command Line : -notepadStyleCmdline -z "C:\Windows\System32\notepad.exe" "C:\test\test.ps1"
Admin mode : OFF
Local Conf mode : ON
Cloud Config : OFF
OS Name : Windows 10 Home (64-bit) 
OS Version : 22H2
OS Build : 19045.2364
Current ANSI codepage : 1250
Plugins : 
    mimeTools (2.9)
    NppConverter (4.5)
    NppExport (0.4)

**Comment by rdipardo** [comment] 2023-01-08 00:42
@neodyne,
The error dialog was added in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/4f1aa7b:

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/17eba0a3749912eacf90073701320e7fc2680932/PowerEditor/src/NppIO.cpp#L184-L211

You say the files open anyway, so either:

- [ ] the code path leading to the error message doesn't properly handle file names generated by the system's context menu

- [ ] the file names really are malformed. That's less likely on "Windows 10 Home". Windows 11, however, seems to have [broken the old registry hack] for replacinng `notepad.exe`, which is now developed as a UWP app

[broken the old registry hack]: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7902

**Comment by xomx** [comment] 2023-01-08 00:57
I have already identified the culprit, there is a flaw in my new v8.4.8 code #12613 .

@donho 
Assign this please to me.

**Comment by xomx** [comment] 2023-01-09 17:48
@donho 
Are you running Win10 or Win11?

Right now I tried to use your reg under Win10 and it is working ok as described.

But Win11 new UWP Notepad probably needs more [hacks](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/7902#issuecomment-1116503895).

**Comment by donho** [comment] 2023-01-10 19:21
@xomx 
Thank you for the info. It doesn't work for me either.
After some googling, I made it work under my Windows 11:
https://community.notepad-plus-plus.org/topic/21991/replace-notepad-on-windows-11/18?_=1673374535394

**Comment by donho** [comment] 2023-01-10 19:37
@xomx 
Hmm... Now I make "Notepad replacement" works on my Win11 (by removing Notepad UWP), but I cannot reproduce the bug reported by @neodyne now.

**Comment by xomx** [comment] 2023-01-10 22:04
@donho 
I will try to find a machine or VM with Win11 to test that too.

Win10 & N++ v8.4.8 (older versions have this problem too, but it is not manifested visually - `Notepad_plus::doOpen` tries to open the nonsense " " file-item and fails without a messagebox...):

![Image1](https://user-images.githubusercontent.com/13075183/211670267-e3093e3c-acad-43a7-b095-b89566f1ab6b.png)
![Image2](https://user-images.githubusercontent.com/13075183/211670283-12e1c677-b687-441f-8e20-b40810bb4e23.png)
![Image3](https://user-images.githubusercontent.com/13075183/211670292-c68d10aa-7347-42ac-9070-ea7acb7c11aa.png)
![Image4](https://user-images.githubusercontent.com/13075183/211670299-876e0ce9-70da-4ff7-b2ef-0338c29f42f7.png)
![Image5](https://user-images.githubusercontent.com/13075183/211670306-7126ce5c-0a24-4b75-b935-8613038a9b23.png)
![Image6](https://user-images.githubusercontent.com/13075183/211670314-7e5b08eb-d133-4cb4-b063-76d8383578dd.png)
![Image7](https://user-images.githubusercontent.com/13075183/211670322-1855094c-59bf-4d71-862f-35ecd1cf7f17.png)
![Image8](https://user-images.githubusercontent.com/13075183/211670334-753f6031-42ce-4371-97a5-4a131b3b00ec.png)

**Comment by ltdeta** [comment] 2023-01-11 08:40
I have the same problem with 8.4.8!
The file is opened, but the dialog is displayed
The problem can be easily reproduced if you use a file with spaces in path!

8.4.7 => d:\test 123\test.txt  => Ok
8.4.8 => d:\test 123\test.txt  => Error "Cannot open file...."

**Comment by donho** [comment] 2023-01-12 12:13
@ltdeta 
Are you under win11 or win10 ?

**Comment by ltdeta** [comment] 2023-01-12 15:24
Windows 10 Enterprise Version 22H2 (Build 19045.2364)

**Comment by donho** [comment] 2023-01-12 16:24
@xomx 
> then consequently [here](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b3934afd9210f7f580355c7eb54f263d425ebd43/PowerEditor/src/winmain.cpp#L575) had been added superfluous space-char delimiter at the end of the file-items list string

I do reproduce the added superfluous whitespace, and I do see how.

 > the [convertParamsToNotepadStyle](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b3934afd9210f7f580355c7eb54f263d425ebd43/PowerEditor/src/winmain.cpp#L428) incorrectly left one from the two (formerly filename surrounding) quote-chars at the end of the params item
 
 However, I do not see how there could be any parameter with extra quot(s) to pass to `convertParamsToNotepadStyle`.
 Does it come from the registry made by users who were guided by our manual?

**Comment by ltdeta** [comment] 2023-01-12 17:35
@donho
I have used this guide [https://www.winhelponline.com/blog/replace-notepad-text-editor-notepad-plus-association/](url)

**Comment by xomx** [comment] 2023-01-12 17:58
@donho 
Sorry, busy, that's why I have not tested the Win11 yet as promised.

> However, I do not see how there could be any parameter with extra quot(s) to pass to `convertParamsToNotepadStyle`.

My mistake - late nigh work :-) , I should have said that the problematic ending quote char (`\"`) has been left there incorrectly by [stripIgnoredParams](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/b3934afd9210f7f580355c7eb54f263d425ebd43/PowerEditor/src/winmain.cpp#L415):

![02-stripIgnoredParams_fai_(quote_at_end_left)](https://user-images.githubusercontent.com/13075183/212140183-d0a677f0-d54f-4be6-8192-1d1fac6ac7eb.png)

Then the `pCmdLineWithoutIgnores` is passed to `convertParamsToNotepadStyle`.

If I remember correctly, I chose not to fix directly the `stripIgnoredParams` but `convertParamsToNotepadStyle` in my PR, because of it was simpler for me, at least I think it was so.

> Does it come from the registry made by users who were guided by our manual?

No, Registry is ok. The quotes surrounding the passed filename param is added by Windows. At least I think so, otherwise there could be a problem with filenames including space-chars within.

**Comment by donho** [comment] 2023-01-12 21:56
@xomx 

Here is the screenshot attatched as debug mode, while I double-click "Nouveau document texte.txt" on Explorer on my Win11, without extra quote left:

![image](https://user-images.githubusercontent.com/90293/212187785-876ea315-30d2-4506-a10d-cf839b12f779.png)

Here's my settings in my registry key:

![image](https://user-images.githubusercontent.com/90293/212188783-215556bd-5f20-4fcb-b584-ef7ac0d96894.png)

So if users' (and your) registry keys are set correctly, there is a different treatment in Win10 from win11.
Could it be the bug in Win10 rather the one of Notepad++?

**Comment by xomx** [comment] 2023-01-12 22:52
@donho 

> So if users' (and your) registry keys are set correctly,

Your registry key looks like mine (except the different path, of course).

> there must be a different treatment in Win10 from win11.

Could you also append here a copy (or screenshot) of the initial pCmdLine content at the very start of `wWinMain`?

Mine in Win10 is:

pCmdLine = 0x0000021991fc30cc L"-notepadStyleCmdline -z `\"`C:\\WINDOWS\\system32\\notepad.exe`\"` `\"`C:\\NPP_TESTS\\#12775_-_Notepad_replacement_regression\\notepad-plus-plus-8.4.8\\PowerEditor\\visual.net\\x64\\Debug\\test.reg`\"`"

(I had to add the four code formating above to keep the relevant original surrouding quotes visible in this post)

Do you also see these `\"` in your Win11 debugging session?

**Comment by donho** [comment] 2023-01-13 00:44
@xomx 
> Could you also append here a copy (or screenshot) of the initial pCmdLine content at the very start of `wWinMain`?

Sure:

`-notepadStyleCmdline -z "C:\Windows\system32\NOTEPAD.EXE" C:\Users\xxxxxx\xxxxxxxx\Nouveau document texte.txt` 

![image](https://user-images.githubusercontent.com/90293/212210672-44b8c5ca-6348-49af-a3a1-508602d31f6c.png)

**Comment by donho** [comment] 2023-01-13 00:51
@xomx 
Your last parameter is correct : 
`\"C:\NPP_TESTS\#12775_-_Notepad_replacement_regression\notepad-plus-plus-8.4.8\PowerEditor\visual.net\x64\Debug\test.reg\"`
 If it's badly parsed in stripIgnoredParams, then it should be fixed in this function.
 I'll emulate your case to understand where is the problem.

**Comment by donho** [comment] 2023-01-13 01:17
> If it's badly parsed in stripIgnoredParams, then it should be fixed in this function.

BTW, the bug is rather in `advanceCmdLine` function.

**Closed** 2023-01-14 14:30 UTC
