### ISSUE TITLE
File Too Big To Open, during Find in Files

### ISSUE THREAD

**Issue by gregsohl** [notepad-plus-plus/notepad-plus-plus#4229] opened 2018-02-26 17:52 UTC
### Description of the Issue
When searching in files for text, if NotePad++ runs into a file that it cannot open due to the file size, it currently pauses with a message dialog. This then requires human intervention to continue the search.

### Expected Behavior
I would like to see this behavior changed so that instead of pausing with a message, the inability to  search in a file due to its size be logged in the find results with a warning, and the search process continue on it's own.

### Debug Information
Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS : Windows 7 (64-bit)
Plugins : CodeAlignmentNpp.dll ComparePlugin.dll Explorer.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NPPJSONViewer-win32.dll NppTextFX.dll PluginManager.dll SpellChecker.dll XMLTools.dll

**Comment by dail8859** [comment] 2018-02-26 20:03
Duplicate of #1889, #2072, #3068, #4131 

Pending PR #4151

Please search the list of issues before opening a new one.

**Comment by gregsohl** [comment] 2018-03-01 19:56
Sorry for the dup. I did search, but apparently failed to use the right words.

**Comment by donho** [comment] 2023-09-01 15:37
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/cf8ddc18c9833fb8f19df1c44dc769926a274d47

**Closed by donho** 2023-09-01 15:37 UTC
Labels: duplicate
