### ISSUE TITLE
NPP Simplified Chinese: The notepad++ check update screen does not have localizable strings

### ISSUE THREAD

**Issue by dpy013** [notepad-plus-plus/notepad-plus-plus#11732] opened 2022-05-27 01:32 UTC
### Steps to Reproduce the Issue

1. Open notepad++
2. Press alt to open menu Left cursor three times, up and down cursor to find update np++
3. Open the update npp++ and you will see the window without translation

### Expected Behavior

I hope the interface of np++ to check for updates is already translated.
### Actual Behavior

The actual current np++ check update screen is without the translation string in the translation file.
### Debug Information
Notepad++ v8.4.1   (64-bit)
Build time : May  8 2022 - 19:51:18
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise LTSC 2021 (64-bit) 
OS Version : 2009
OS Build : 19044.1706
Current ANSI codepage : 936
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 

*新文件 1 - Notepad++
文件(F) 有子菜单 Alt+f 
升级 Notepad++ 
Notepad++ update
No update is available
or the newest version is not triggered yet for updating (more info).

Go to the download page to update Notepad++ manually. 客户端
 more info 链接
Go to the download page 链接
Close 按钮
more info 链接

**Comment by ArkadiuszMichalski** [comment] 2023-02-15 16:34
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11732.

**Closed by ArkadiuszMichalski** 2023-02-15 16:34 UTC
Labels: translation
