### ISSUE TITLE
Feat request - CSS syntax highlighting

### ISSUE THREAD

**Issue by justinmreina** [notepad-plus-plus/notepad-plus-plus#10752] opened 2021-11-07 06:36 UTC
### Description of the Issue

Can we please have CSS comment highlighting enabled when used in HTML? See below, for '/* sidebar shading */' -

<ul>
<li><a href="https://www.dropbox.com/s/g7ufhsqis2s8alq/Comment%20Syntax%20colors.png?dl=0" /> Example Highlighting for CSS </li>
</ul>

### Actual Behavior
We currently see it in black, can it be in the green color for comments?

**Comment by ArkadiuszMichalski** [comment] 2021-11-10 23:24
Duplicate of https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5663.

**Closed by ArkadiuszMichalski** 2021-11-10 23:24 UTC
