### ISSUE TITLE
Character position not displayed in status bar

### ISSUE THREAD

**Issue by badon** [notepad-plus-plus/notepad-plus-plus#1268] opened 2015-12-19 00:11 UTC
If I need to debug string manipulation on a text file, I have to use workarounds because Notepad++ does not display character position in the status bar. String manipulation is universally done with character position numbers (AKA "index position"). Notepad++ only displays line and column numbers. 

There are 2 workarounds for this missing feature. The first one is to begin selecting text at the first character position of the file, and then use the count of selected characters to determine the cursor's character position. The other workaround is to use the "Go to..." function in the search menu or CTRL+G, and then select "Offset" and enter the character position you want to go to. 

Both workarounds are inadequate given the importance of knowing the character position, so I request that character position be displayed in the status bar.

**Comment by taxi16** [comment] 2018-01-02 01:30
I just have the same problem and totally agree with the judgement of the relevance of that enhancement request. I was really astonished that it is not available (as Notepad++ for me is by far the best tool in it's domain, not to write letters, but for code development :) ). So adding that would be great!

**Comment by Huud** [comment] 2019-02-18 15:27
You can put the cursor over where you want to find the offset, and then double click on the (Ln, Col, Sel) section on the bottom bar to get a popup window that contains your current offset.

But yeah, an option to display the offset directly on the bar instead of the (Sel) when nothing is selected would be ideal.

**Comment by MetaChuh** [comment] 2019-04-11 00:22
we are closing this issue due to multiple newer notepad++ versions since it was filed.

please update your notepad++ to the latest version [<kbd>Notepad++ 7.6.6</kbd>](https://notepad-plus-plus.org/download/v7.6.6.html) and migrate or reinstall your plugins.
if your issue still persists, and it is still of relevance to you, please feel free to file a new issue as detailed and reproducible as possible.

thank you for your help and best regards.

-----
```
general notes:

please close your issues as soon as you are satisfied, to help
keeping the notepad++ issue tracker clean.

when creating a new issue, please provide all information as shown at the issue template.
your notepad++ debug info is part of the minimum requirements.
(? > Debug Info... > Copy debug info into clipboard).

please also conduct a search at the issue tracker beforehand, to check if a similar issue
already exists.

for general questions, or if it is not sure, whether your issue is directly related to
the notepad++ source code, please visit us at the notepad++ community forum, and
search if related topics exists. you are welcome to post either at similar
topics, or to create a new topic at Help Wanted or General Discussion.
```
[<p align="center"><kbd> &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; Click here to visit the Notepad++ Community Forum &emsp; &emsp; &emsp; &emsp; &emsp; &emsp;&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; </kbd></p>](https://notepad-plus-plus.org/community/)

**Closed by MetaChuh** 2019-04-11 00:22 UTC
