### ISSUE TITLE
Feature request: Pinned Tabs

### ISSUE THREAD

**Issue by tobizviz** [notepad-plus-plus/notepad-plus-plus#8377] opened 2020-06-05 03:57 UTC
### Description of the Issue
Humble feature request
### Proposed feature
I would very much love to have a tab pinning feature (like in firefox/chrome/opera/etc), i.e. the ability to pin tabs which then stay present at the top left of the tab bar even when the tab bar is scrolled.

I often find myself scrolling through my many open files and there's a few that I frequently need to access which are always open (notes/etc) and it would be ideal if I could pin these tabs to avoid having to scroll back to and click through each tab until I find them again.

**Comment by xylographe** [comment] 2020-06-05 09:11
The 9 leftmost documents can be activated by a simple keyboard shortcut: **Ctrl+NumpadN** by default (where N is 1 to 9 inclusive), customizable via **Settings > Shortcut Mapper…** (type `tab` in the **Filter** input field).

Mouse alternative is **View > Tab > 1st Tab**, **View > Tab > 2nd Tab**, etc.

**Comment by sasumner** [comment] 2020-06-05 11:26
The usual workaround to this is to use the _Explorer_ plugin and its _Favorites_ feature.

**Comment by sasumner** [comment] 2020-06-05 11:29
Closing this because it is a duplicate of #5786
Semi-related might be #3244

**Comment by donho** [comment] 2024-11-21 19:57
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/ce58b424bdeec3616943f9ea8cd257f66700c3c0

**Closed by donho** 2024-11-21 19:57 UTC
