### ISSUE TITLE
Notepad++ not working from latest master code/Appveyor Build

### ISSUE THREAD

**Issue by Pyre909** [notepad-plus-plus/notepad-plus-plus#3535] opened 2017-07-17 17:41 UTC
There seems to be an issue with starting notepad++.exe when building from the latest code in the master branch and appveyor build. Notepad++ will not start when running from either. Original notepad++.exe runs as expected.

### Steps to Reproduce the Issue
1.  Download either the appveyor build or build it from code download from master branch.
2.  backup notepad++.exe and place the new built/downloaded exe into NPP directory.
3. Run notepad++.exe

### Expected Behavior
Notepad++.exe should run as normal.

### Actual Behavior
Notepad++ does not start up. (All plug-ins were removed. )

### Debug Information
No debug info available. Npp++ does not start up.(If there is a way to get this I am free to suggestions ). Only possible info I can provide at the moment unfortunately is that I am running the nightly build and tested the one built by downloading source and compiling in Visual studio. Both did not work.

If there is a means of being able to provide more info. Please let me know.
Thanks!
Pyre909

**Comment by AngryGamer** [comment] 2017-07-18 05:20
I can't replicate this problem. Installed 7.4.2 (x86) and replaced .exe with [latest build 164e2c67](https://ci.appveyor.com/api/buildjobs/1gfd2ky3i9t6a1tk/artifacts/Notepad%2B%2B.Win32.Unicode%20Release.exe)

Works fine.

**Comment by Pyre909** [comment] 2017-07-18 11:03
Ah one thing I forgot to mention it was (x64) version that I installed.

**Comment by Pyre909** [comment] 2017-07-18 15:51
Seems like an issue on this build.  Anything before that I can use and executes like normal when notepad++ starts up. As stated before I am using 64-bit version of NPP.

https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b85930314847727ee8070d1417e674afd1bb24ab

Appveyor Build 1.0.1365: 
https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1365

**Comment by Pyre909** [comment] 2017-07-18 15:53
I can use notepad++ 64-bit on builds before 1.0.1365. On 1.0.365 or latest I cannot seem to open.

https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1365

**Comment by SinghRajenM** [comment] 2017-07-18 18:31
Yes, I confirm. It does not work. Statement ```delete commandLine``` is culprit in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b85930314847727ee8070d1417e674afd1bb24ab.

@AngryGamer check debug build you will come to know the root cause.

@donho  you need to review the commit https://github.com/notepad-plus-plus/notepad-plus-plus/commit/b85930314847727ee8070d1417e674afd1bb24ab.

**Comment by Pyre909** [comment] 2017-07-24 03:01
Notepad starts up now without issue in the latest build now, but if you update to the latest build you will see that npp will not open the file that you are telling it to edit.

Right click on the file "Edit with Notepad++" it will not open the file. It will just show notepad opening with a tab.

I can't be sure which build after cb7d6070 https://ci.appveyor.com/project/donho/notepad-plus-plus/build/1.0.1396 might be having the issue. 

I tried the debug versions and no errors are thrown. This is still on the 64 bit version. Have not tried 32.

**Comment by Mattiwatti** [comment] 2017-07-26 23:18
The first issue (startup crash) was caused by commit b859303.
The second issue ("open with" not working) was strictly speaking also caused by this commit, but has only started manifesting after the crash was fixed in cb7d607.

The cause of the second problem is that a buffer is allocated in `parseCommandLine` and pointers to substrings within this buffer are then used to fill the `ParamVector` output parameter. This is OK in itself, but the buffer is then freed upon exit of the function, while the `ParamVector` containing (now invalid) pointers is returned for further use. The solution would be to allocate the command line string buffer prior to calling `parseCommandLine`, and only free it only when the `ParamVector` is no longer needed.

**Comment by donho** [comment] 2017-07-27 09:40
It has been fixed.

**Closed by donho** 2017-07-27 09:40 UTC

**Comment by Pyre909** [comment] 2017-07-27 13:08
Thanks Everyone!
