### ISSUE TITLE
Add Shift-DEL & Ctrl-INS back and prevent from copying/cutting/deleting entire line 

### ISSUE THREAD

**Issue by donho** [notepad-plus-plus/notepad-plus-plus#14557] opened 2024-01-06 16:17 UTC
In v8.6 & v8.61 some old behaviours has been changed. In order to restore these old behaviour, user can create the empty **"disableLineCopyCutDelete.xml"** file to add Shift-DEL & Ctrl-INS back and prevent from copying/cutting/deleting entire line.

This empty xml file is optional. By adding disableLineCopyCutDelete.xml in "%APPDATA%\Notepad++\" directory (or in the Notepad++ installed directory in portable mode) to:      
1. prevent hard coded Shift-DEL shortcut deletes whole line while no selection.  
2. prevent Copy command (Ctrl-C) copies whole line (without selection).          
3. prevent Cut command (Ctrl-X) cuts whole line (without selection).             
4. add SCI_CUT (Shift-DEL), SCI_COPY (Ctrl-INS) & SCI_PASTE (Shift-INS) shortcuts.

**Comment by fda77** [comment] 2024-01-06 16:29
Thanks for the workaround, it applies to further version, maybe v8.62 ? With v8.61 it does not work for me

v8.6 is working, i have installed it again to make it work

> some old behaviours has been changed.

Which "old" behaviours? CTRL/SHIFT+INS works with EVERYWHERE in Windows for all programs - except Notepad++ since 8.61.
Creating the `disableLineCopyCutDelete.xml` on every device is a little clumsy

**Comment by LagunaJim** [comment] 2024-01-06 21:17
This workaround with the "disableLineCopyCutDelete.xml" file seems cumbersome to change the behavior back to what is universal throughout the rest of Windows.

Please reconsider.

**Comment by molsonkiko** [comment] 2024-01-07 02:06
Agree with @LagunaJim that the new behavior should definitely not be the default. I personally don't care that much about the `Shift+INS` change, but I care __very much__ about the fact that [I had to make a hacky patch to my JsonTools plugin](https://community.notepad-plus-plus.org/post/91753) (as will *literally every other developer who made a plugin with C#*) to make Ctrl+V work again in my forms.

The worst part is that anyone who tries to make a workaround for the new behavior by hard-coding paste on Ctrl+V input, like I did with my patch to JsonTools, will likely end up pasting things twice if the empty `xml` file is present.

**Comment by alankilborn** [comment] 2024-01-07 11:14
IMO, revert everything that was done thus far to support entire-line-if-no-selection.  Then, add new menu commands in the _Edit_ > _Paste Special_ submenu in order to support the entire-line-if-no-selection copy/cut/delete.

Doing this would:

* not break any existing (i.e., pre-8.6) behavior
* make the new behavior entirely optional for those that want it (i.e., do not assign any default shortcuts to new behaviors)
* require a small amount of code
* not require any preference settings
* not require a zero-length xml config file

( sure, maybe consider renaming _Paste Special_ to _Copy / Cut / Paste Special_ )

**Comment by vinsworldcom** [comment] 2024-01-07 13:21
@alankilborn agree!!

**Comment by alankilborn** [comment] 2024-01-07 16:35
Regarding https://github.com/notepad-plus-plus/notepad-plus-plus/issues/14557#issuecomment-1880027692 , I'll even volunteer to code it.  But I'd provide it as a diff from 8.5.8 and let someone else figure out everything  that needs reversion in 8.6.x.

**Comment by fda77** [comment] 2024-01-07 16:37
Again, 8.6 does not have the bug!

**Comment by alankilborn** [comment] 2024-01-07 16:38
>Again, 8.6 does not have the bug!

The "problems" with the entire feature started with introduction, i.e., with 8.6.

**Comment by LagunaJim** [comment] 2024-01-07 16:38
> Again, 8.6 does not have the bug!

It's not a bug, it was a functionality change that was intended.  

Many of us aren't happy about it, but it is not a bug.

**Comment by fda77** [comment] 2024-01-07 16:39
Yes, sorry. its not a bug, its a feature :D

**Comment by NicolaP8** [comment] 2024-01-07 17:41
Broking an universal behaviour in this manner is simply and only pure incompetence!
And telling (without laughing) that it's a feature... is uncommentable.

**Comment by Coises** [comment] 2024-01-07 22:48
@donho Apparently there are a lot of plugins with non-modal dialogs which do not bother to register those dialogs using NPPM_MODELESSDIALOG. Changing cut/copy/paste from Scintilla shortcuts to Notepad++ shortcuts has broken the use of those keys in edit controls in unregistered modeless dialogs (including dockable dialogs).

According to documentation, Scintilla has [SCI_COPYALLOWLINE](https://www.scintilla.org/ScintillaDoc.html#CutCopyAndPaste) (though apparently not an equivalent cut command) and SCI_PASTE does the paste line before current line automatically if the copy was made SCI_COPYALLOWLINE and nothing selected.

Using the Scintilla features would restore the status quo for non-modal dialogs that aren’t registered using NPPM_MODELESSDIALOG, since Scintilla shortcuts aren’t translated in the message loop (and hence would make it to the unregistered modal dialogs unaltered).

**Comment by rdipardo** [comment] 2024-01-08 04:47
@molsonkiko 

Can you confirm that docked dialogs are likewise non-responsive to <kbd>Ctrl</kbd>+<kbd>C</kbd> and <kbd>Ctrl</kbd>+<kbd>X</kbd>?

If yes, the real problem is the handle ownership checks added in 0978b2e29f21e7797f488e9e6d2e85763b25a406, i.e.,

* https://github.com/donho/notepad-plus-plus/blob/6f5f246791c1e1a626587111de090bf8158d0736/PowerEditor/src/NppCommands.cpp#L361

* https://github.com/donho/notepad-plus-plus/blob/6f5f246791c1e1a626587111de090bf8158d0736/PowerEditor/src/NppCommands.cpp#L378

* https://github.com/donho/notepad-plus-plus/blob/6f5f246791c1e1a626587111de090bf8158d0736/PowerEditor/src/NppCommands.cpp#L477

When you execute a key combo inside a plugin's edit control, the handle returned belongs to the dialog window, so `focusedHwnd == _pEditView->getHSelf()` tests `FALSE`, and the entire block is skipped 😖.

#### Good news 

This is not a regression in 5.6.1 and the Visual Studio-style line copy/cut commands are *not* disruptive.

#### Bad new

The price of fixing #14410 was to intercept `IDM_EDIT_CUT|COPY|PASTE]` for *all* child windows, so these key combos will never reach the edit controls of plugin dialogs whose parent handle is the main application's , i.e, all the docked ones. Modal dialogs are not affected.

As a test, build Notepad++ from git just before 0978b2e29 and try to paste into any docked plugin window.

**Comment by Coises** [comment] 2024-01-08 07:15
@rdipardo:
> the real problem is the handle ownership checks added in https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0978b2e29f21e7797f488e9e6d2e85763b25a406

I don’t think so. If you look at the old sections in the commit, they never did anything but call _pEditView->execute anyway.

I believe you have the right commit, but the problem is that the entries in the Scintilla commands table were commented out and replaced with entries in the application accelerators table. As long as Ctrl+x/c/v were assigned to Scintilla commands, they weren’t affected by TranslateAccelerator in the message loop, so they never went to IDM_EDIT_CUT/COPY/PASTE. This change means that non-modal dialogs that fail to register with NPPM_MODELESSDIALOG now have those keys directed to the menu commands. (Many other key combinations were always mis-directed, but apparently few people care about keyboard navigation in dialogs, so nobody noticed — or if, like me, they did, they discovered NPPM_MODELESSDIALOG.)

One thing that helps demonstrate this is that, in 8.6.1, if you remove the Ctrl+V shortcut from Edit|Paste, it will then paste in the JsonTools JSON Tree View window. Moreover, if you assign it to *any* Scintilla command — say, SCI_CLEARALL — it will perform the assigned function in the main edit window, but **it will still paste** in JsonTools.

**Comment by rdipardo** [comment] 2024-01-08 10:31
@Coises 

Well, this works: 

```diff
diff --git a/PowerEditor/src/Notepad_plus.h b/PowerEditor/src/Notepad_plus.h
index 2157f10f..0638719b 100644
--- a/PowerEditor/src/Notepad_plus.h
+++ b/PowerEditor/src/Notepad_plus.h
@@ -416,6 +416,7 @@ private:
 	std::vector<HWND> _sysTrayHiddenHwnd;
 
 	BOOL notify(SCNotification *notification);
+	BOOL isPluginWindow(const HWND hwnd);
 	void command(int id);
 
 //Document management
diff --git a/PowerEditor/src/NppCommands.cpp b/PowerEditor/src/NppCommands.cpp
index df9d1f86..f85cc298 100644
--- a/PowerEditor/src/NppCommands.cpp
+++ b/PowerEditor/src/NppCommands.cpp
@@ -57,7 +57,22 @@ void Notepad_plus::macroPlayback(Macro macro)
 	_playingBackMacro = false;
 }
 
-
+BOOL Notepad_plus::isPluginWindow(const HWND hwnd)
+{
+	for (const auto& pCmd: (NppParameters::getInstance()).getPluginCommandList())
+	{
+		std::wstring pluginPath(MAX_PATH, L'\0');
+		std::wstring pathSep(L"\\");
+		if (::GetWindowModuleFileNameW(hwnd, pluginPath.data(), MAX_PATH) > 0)
+		{
+			auto pathParts = std::vector<std::wstring>();
+			stringSplit(pluginPath, pathSep, pathParts);
+			if(pathParts.back().compare(string2wstring(pCmd.getModuleName(), CP_UTF8)))
+				return TRUE;
+		}
+	}
+	return FALSE;
+}
 
 void Notepad_plus::command(int id)
 {
@@ -369,6 +384,8 @@ void Notepad_plus::command(int id)
 						_pEditView->execute(SCI_LINECUT); // Ctrl + X: without selected text, it will cut the whole line.
 				}
 			}
+			else if (isPluginWindow(focusedHwnd))
+				::SendMessage(focusedHwnd, WM_CUT, 0, 0);
 			break;
 		}
 
@@ -391,6 +408,8 @@ void Notepad_plus::command(int id)
 				Finder* finder = _findReplaceDlg.getFinderFrom(focusedHwnd);
 				if (finder)
 					finder->scintillaExecute(WM_COPY);
+				else if (isPluginWindow(focusedHwnd))
+					::SendMessage(focusedHwnd, WM_COPY, 0, 0);
 			}
 
 			break;
@@ -488,6 +507,8 @@ void Notepad_plus::command(int id)
 
 				_pEditView->execute(SCI_PASTE);
 			}
+			else if (isPluginWindow(focusedHwnd))
+				::SendMessage(focusedHwnd, WM_PASTE, 0, 0);
 		}
 		break;
 
```

**Comment by BobKnip** [comment] 2024-01-08 10:32
This does not seem to work for Notepad++ Portable 8.6.1 (i.e. via the PortableApps platform). After adding an (empty) file "disableLineCopyCutDelete.xml" to (in my case) directory "C:\Users\<USER_NAME>\Software\PortableApps\Notepad++Portable", I notice no difference in behavior. 

BTW: I only recently found out about Notepad++'s full no-selection-full-line copy/cut behavior, but want to disable it, if only to avoid accidentally deleting lines when hitting "Shift+Delete" instead of "Shift+End".

**Comment by rdipardo** [comment] 2024-01-08 10:45
**EDIT:** *I corrected the string comparison so it's true when it should be instead of always*

**Comment by rdipardo** [comment] 2024-01-08 12:46
**EDIT:**

A strange thing about .NET plugins (but not C++ or Pascal ones): the return value of `::GetWindowModuleFileName` is always `"notepad++.exe"`!

But if we checked for that, I think we'd always get a true result, which is effectively the same as having `else { ::SendMessage(focusedHwnd, ...); }` in the message handler . . . which is effectively the same as outright reverting 0978b2e. . . :thinking:

Anyway, a comparison that works for .NET plugins also would look like this:

~~~
TCHAR *moduleName = pathParts.back().data();
if (wcsicmp(moduleName, string2wstring(pCmd.getModuleName(), CP_UTF8).data()) == 0 ||
 	wcsicmp(moduleName, L"notepad++.exe") == 0)
 return TRUE;
~~~

**Comment by molsonkiko** [comment] 2024-01-08 16:27
@rdipardo 
> Can you confirm that docked dialogs are likewise non-responsive to Ctrl+C and Ctrl+X?

Almost all of my forms in JsonTools are unresponsive to Ctrl+C and Ctrl+X, now that you mention it.

The one exception is the [JSON-to-CSV form](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/JsonToolsNppPlugin/Forms/JsonToCsvForm.cs), which responds to all of Ctrl+C, Ctrl+X, Ctrl+V.

**Comment by henryford-metoffice** [comment] 2024-01-08 16:40
For me, I noticed immediately on upgrade to 8.6.1 that Ctrl+Insert doesn't copy and Shift+Insert doesn't paste.

I'm happy to find this thread that people recognise these shortcut alternatives for Ctrl+XCV being (Shift+Del, Ctrl+Ins, Shift+Ins, resp.), but I'm not so happy that I'm here trying to troubleshoot why I don't copy things into clipboard and how to solve it.

I knew there would be one day when these really old shortcuts would stop working, it's annoying enough when people redesign web-based text boxes to remove these shortcuts, but why on NP++ 8.6.1 do they now not work?

Does the community (or Author) think they'll come back or is the xml file workaround the accpeted solution?

**Comment by Coises** [comment] 2024-01-08 17:01
@molsonkiko

> The one exception is the [JSON-to-CSV form](https://github.com/molsonkiko/JsonToolsNppPlugin/blob/main/JsonToolsNppPlugin/Forms/JsonToCsvForm.cs), which responds to all of Ctrl+C, Ctrl+X, Ctrl+V. One difference is that Notepad++ is blocked until you submit or cancel from that form, as opposed to the others, which are non-blocking.

You may have noticed that Ctrl+x/c/v work in your Settings form, too. When we are talking about **modal** vs. **non-modal** (or modeless) dialogs, that is what that means: modal dialogs stop you from interacting with any other part of the application, non-modal dialogs do not. Dockable dialogs, of course, must be non-modal.

I don’t know C#, but if it is possible, and you want to fix this *now* (regardless of what is done about the issue for plugins in general), try sending [NPPM_MODELESSDIALOG](https://npp-user-manual.org/docs/plugin-communication/#2036-nppm-modelessdialog) messages when you open and close non-modal dialogs (i.e., non-blocking forms). It might be useful to have information as to whether this causes any problems with dockable dialogs — I don’t know if anyone is doing that. (Columns++ has a non-modal dialog, but it isn’t dockable; since I send NPPM_MODELESSDIALOG messages for it, it never had the Ctrl-x/c/v problem. Commenting out those sends causes the problem to appear.)

**Comment by Coises** [comment] 2024-01-08 17:27
> I think we'd always get a true result, which is effectively the same as having `else { ::SendMessage(focusedHwnd, ...); }` in the message handler . . . which is effectively the same as outright reverting [0978b2e](https://github.com/notepad-plus-plus/notepad-plus-plus/commit/0978b2e29f21e7797f488e9e6d2e85763b25a406). . . 🤔

I see that the before code in that commit calls _pEditView->execute without first checking to be sure _pEditView is the appropriate destination. It makes sense that when the keyboard shortcuts for those commands changed from Scintilla shortcuts to application accelerators, that would no longer be wise. It seems to me like sending WM_CUT/COPY/PASTE to whatever window is focused, if that’s not _pEditView, would work around the plugins problem in nearly all, if not all, real-world cases; but I don’t know if it could have other side-effects. I confess to having failed to follow the “visual glitchy” problem and solution.

**Comment by molsonkiko** [comment] 2024-01-08 23:58
So I've been experimenting with trying to register and unregister my forms using [`NPPM_MODELESSDIALOG`](https://npp-user-manual.org/docs/plugin-communication/#2036-nppm-modelessdialog) and the results are... not encouraging.

Basically, I try to register my plugin when my form is initialized, and that seems to work fine.

Then, in [the Dispose method](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.dispose?view=windowsdesktop-8.0), __I try to call `NPPM_MODELESSDIALOG` again, and it causes a plugin crash.__

Even if I eventually figure out a way to get this to work (and I will continue to work on this), I can't stress enough to the seasoned C++ developers out there that __developers like me who are used to working in high-level languages DO NOT LIKE HAVING TO WORRY ABOUT PROPERLY DISPOSING OF OBJECTS.__ You may be used to it, and shrug and say, "what's the big deal?" about adding some new thing that needs to be done before something like a form is destroyed. But people like me *care quite a bit* about the additional cognitive overhead of new "chores" that must be completed before a form is destroyed, not to mention that the higher-level languages we use tend to make it harder to ensure that these "chores" are completed at the right time.

I understand that the nature of Notepad++ makes it difficult or impossible to avoid offloading some tasks to plugin authors, but I hope it is very clear that __if Notepad++ makes design decisions that make it difficult or impossible to develop plugins in a language other than C++, the plugin community will suffer a serious loss.__ I for one am not willing to rework my projects in C++, and I would assume that most developers of C# plugins feel the same way.

**Comment by Coises** [comment] 2024-01-09 02:41
This is preliminary and would require a lot more testing; but my simple tests suggest that the following change to Notepad++:
https://github.com/Coises/notepad-plus-plus/commit/c4b1a461c16863ec3fc565e3ae94f351d1dafc1e
might work to remove the need for plugins to send NPPM_MODELESSDIALOG messages, thus fixing the Ctrl+x/c/v in plugins problem.

**Comment by donho** [comment] 2024-01-09 03:56
Fix in #14569

**Comment by molsonkiko** [comment] 2024-01-09 05:01
@Coises 
> This is preliminary and would require a lot more testing; but my simple tests suggest that the following change to Notepad++: [Coises@c4b1a46](https://github.com/Coises/notepad-plus-plus/commit/c4b1a461c16863ec3fc565e3ae94f351d1dafc1e) might work to remove the need for plugins to send NPPM_MODELESSDIALOG messages, thus fixing the Ctrl+x/c/v in plugins problem.


So I tried registering my forms with `NPPM_MODELESSDIALOG` in JsonTools, and I __really don't like the result.__ This makes me concerned that a change (like this proposed one) that makes `NPPM_MODELESSDIALOG` "unncessary" would cause *even more* breaking changes for C# plugin authors.

The problem is that when I register a form, it completely messes up the way Tab and Shift-Tab work for navigating between controls in the form. Presumably registering my form causes Notepad++ to somehow intercept the Tab keystroke and interpret it in some generic way.

**Comment by donho** [comment] 2024-01-10 00:32
@rdipardo 
> A strange thing about .NET plugins (but not C++ or Pascal ones): the return value of ::GetWindowModuleFileName is always "notepad++.exe"!

I confirm.

But the following code works and it seems reasonable:
```c
		case IDM_EDIT_PASTE:
		{
			std::lock_guard<std::mutex> lock(command_mutex);
			HWND focusedHwnd = ::GetFocus();
			if (focusedHwnd == _pEditView->getHSelf())
			{
				size_t nbSelections = _pEditView->execute(SCI_GETSELECTIONS);
				Buffer* buf = getCurrentBuffer();
				bool isRO = buf->isReadOnly();
				if (nbSelections > 1 && !isRO)
				{
					bool isPasteDone = _pEditView->pasteToMultiSelection();
					if (isPasteDone)
						return;
				}

				_pEditView->execute(SCI_PASTE);
			}
			else
				::SendMessage(focusedHwnd, WM_PASTE, 0, 0);
		}
		break;
```

Thank you for the idea!

**Comment by rdipardo** [comment] 2024-01-10 12:18
@donho
> Thank you for the idea!

*Mamma mia!*

Just make sure #14569 gets merged before you start tinkering with any new "idea". It's not the first time your clumsy feet stepped on a bunch of plugins. I hope the next release candidate gets tested with a few third-party ones installed.

**Comment by donho** [comment] 2024-01-10 14:36
@rdipardo 
> It's not the first time your clumsy feet stepped on a bunch of plugins.

Watching and criticizing is always easier than taking action, trust me.

**Closed** 2024-01-11 04:35 UTC
Labels: announcement
