### ISSUE TITLE
Boost build fails

### ISSUE THREAD

**Issue by ygoe** [notepad-plus-plus/notepad-plus-plus#1228] opened 2015-12-05 21:27 UTC
I have started to follow the build instructions and downloaded the latest version of boost (1.59), extracted it and ran scintilla\boostregex\BuildBoost.bat with the path to it. Here's what I've got instead of a build:

```
C:\Source\Apps\notepad-plus-plus\scintilla\boostregex>BuildBoost.bat C:\Source\Apps\boost
Building BJAM, the boost build tool
Das System kann den angegebenen Pfad nicht finden.
Der Befehl "bootstrap.bat" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Das System kann den angegebenen Pfad nicht finden.

***************************************************************
Building tool to check boost version
***************************************************************
Der Befehl "nmake" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
******************************
** ERROR building getboostver.exe
** Please see the error messages above, and post as much as you can to the
** Notepad++ Open Discussion forum
** http://sourceforge.net/projects/notepad-plus/forums/forum/331753
```

I have installed Visual Studio 2015 with C++ support and nothing else. This is Windows 7 x64 SP1.

Do I need to make some adjustments to the build script to make it work or is it supposed to run unmodified?

Sourceforge doesn't like me and I don't like Sourceforge so I can't post there.

**Comment by ClaudiaFrank** [comment] 2015-12-06 00:02
Boost 1.59 has different paths, so please use 1.55 as suggested.
One hint so, run it from your visual studio command prompt instead of a normal one.

**Comment by sanastasiou** [comment] 2015-12-06 01:33
Or just setup the correct enviromental variables by executing vcvars32.bat and use a normal command line.

**Comment by dg9ngf** [comment] 2015-12-06 08:09
Okay, I did that now. I still get strange messages:

    Unknown compiler version - please run the configure tests and report the results

This shows up after every file near the end. Then at the end comes this:

    msvc.archive ..\..\..\bin.v2\libs\regex\build\msvc\debug\link-static\runtime-link-static\threading-multi\libboost_regex-vc-mt-sgd-1_55.lib
    ...updated 21 targets...
    No correctly built boost regex libraries could be found.
    Try specifying the MSVC version on the command line.

    Boost is available free from www.boost.org

    Unzip the file downloaded from www.boost.org, and give the absolute path
    as the first parameter to buildboost.bat

    e.g.
    buildboost.bat d:\libs\boost_1_48_0


    You can specify which version of the Visual Studio compiler to use
    with --toolset.
    Use:
      --toolset msvc-8.0     for Visual studio 2005
      --toolset msvc-9.0     for Visual Studio 2008
      --toolset msvc-10.0    for Visual Studio 2010
      --toolset msvc-11.0    for Visual Studio 2012
      --toolset msvc-12.0    for Visual Studio 2013


    e.g.  To build with boost in d:\libs\boost_1_48_0 with Visual Studio 2008

            buildboost.bat --toolset msvc-9.0 d:\libs\boost_1_48_0

Does this mean it's failed or is everything good now?

**Comment by dg9ngf** [comment] 2015-12-06 08:12
As I continue with the next command, I get this:

    LINK : fatal error LNK1104: Datei "libboost_regex-vc120-mt-s-1_55.lib" kann nicht geöffnet werden.
    NMAKE : fatal error U1077: ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\link.EXE"": Rückgabe-Code "0x450"
    Stop.

This definitely looks like an error now. Could it be that the old Boost version isn't compatible with current tools and I really need the newer version?

**Comment by sanastasiou** [comment] 2015-12-06 14:20
No, the path to the .lib is not correct or the .lib is not generated. Can you see that the file exists at all ?

**Comment by dg9ngf** [comment] 2015-12-06 22:02
No it's not there.

**Comment by sanastasiou** [comment] 2015-12-06 22:04
Obvisously you cannot compile with visual studio greater than  --toolset msvc-12.0    for Visual Studio 2013.

So I'd suggest to download 2013 version..

**Comment by dg9ngf** [comment] 2015-12-06 22:07
Okay, then I'm out. Maybe I'll know when 2015 is supported. I don't need this, I just thought I'd look into the most annoying bugs in Notepad++ and try to propose a fix myself. But building that biest seems more complicated than I have time for.

**Comment by sanastasiou** [comment] 2015-12-08 11:47
Maybe you should give it another try.. ? I've followed the instructions and build this myself. It's not sooo complicated. Just don't use VS2015 - isn't supported, yet.

**Comment by dg9ngf** [comment] 2015-12-08 12:28
That's the point, I'm not going to install VS 2013 just for that. I have migrated everything else to VS 2015 (with very little effort) a few months ago and don't need older versions anymore.

It seems that Boost 1.58 can be [made compatible with VS 2015](http://stackoverflow.com/questions/30760889/unknown-compiler-version-while-compiling-boost-with-msvc-14-0-vs-2015/30959156#30959156). Not sure about 1.59. Maybe Notepad++ should just update their library references? There's even a VS 2015 solution/project file for NPP but it's not really useful if VS 2015 can't be used for its dependencies.

**Comment by Takeya-Yuki** [comment] 2015-12-24 02:05
I had compile it using VS2015+boost 1.58 succesfully. scintilla using VS2013(120/120_xp) to compile. notepad++ using VS2015(140/140_xp) to compile.

**Comment by IvanKostyuk** [comment] 2017-09-18 14:58
I also failed to compile with VS2013 due to `noexcept` does not exist in VS2013 fails on **json.hpp**
The instruction must be updated.
Is it required to have two vsproj files? If instruction will be update it makes sense to merge to one file.

**Comment by pankaj512** [comment] 2018-02-19 17:00
Hello, 
nmake -f scintilla.mak failed. Please help.

I'm using developer command prompt. My boost version is boost_1_55_0 and the visual studio version is 2013. Error screenshot is attached.
Provided my boost got build successfully and fatal error file does exist in boost_dir/stage/lib.

![capture](https://user-images.githubusercontent.com/17810719/36389101-047b13c2-15c4-11e8-8091-17b8e3d73d56.PNG)

**Comment by Lujaina95** [comment] 2018-04-04 17:28
i faced the same problem before but i fixed it by download 3 version of VS which are VS 2017, VS 2015 and VS 2013. 
and i download SDK . 
also i used boost 1_64_0  you can find it in the following link https://sourceforge.net/projects/boost/files/boost-binaries/
also you have to make a changes at the project properties. Also, you need to tell the linker where to look for libraries to link to. To access this setting, right-click on the project name in the Solution Explorer window, then Properties → Linker → General → Additional Library Directories. Enter <boost_path>\stage\lib



i use 
Windows 10 
system type:  x64

**Comment by bfridkis** [comment] 2018-05-14 21:19
So... is it safe to say that there is no way to build SciLexer.dll without VS2013? I tried a few times over with VS2017 (with and without BOOST), but encounter the issues listed above and on related tickets.

Without BOOST (LNK1104 for file 'libboost_regex...', but ran without BOOST..?):
![image](https://user-images.githubusercontent.com/32713413/40023552-0dbbd00c-5791-11e8-9d14-bbbb203bc606.png)

With BOOST:
![image](https://user-images.githubusercontent.com/32713413/40023724-9e682f74-5791-11e8-8271-79aace4c9021.png)

Of course I try adding the --toolset mscv-12.0 flag as suggested, but to no avail. (In fact in this case, the script doesn't even try to run, whereas without the toolset flag it does make partial progress.) 

So close, yet so far away. I tried indeed but unfortunately my circumstances seem intent on preventing me from accessing a working instance of VS2013.

**Comment by ClaudiaFrank** [comment] 2018-05-14 22:07
I'm using the boost 1.66 prebuild  NuGet Packages together with VS2017 
but with Visual Studio 2015 - Windows XP (v140_xp) platform toolset mode.
Seems to work

**Comment by ClaudiaFrank** [comment] 2018-05-16 22:27
Just in case you wanna give it another try with VS2017, the steps needed are

1) Download/Clone npp repository to your harddisk

2) Start VS 2017

3) Open Project/Solution and open the file 
    DOWNLOADED_REPO\notepad-plus-plus\PowerEditor\visual.net\notepadPlus.vcxproj
   Confirm the question about GIT soure control
-> now you should see that Notepad++ (Visual Studio 2015 - Windows XP) has been added to Solution Explorer
   
4) add scintilla project by right clicking Solution->Add->Existing project
   and open file DOWNLOADED_REPO\notepad-plus-plus\scintilla\win32\SciLexer.vcxproj

5) Save current solution
   
6) update boost nuget packages
   Tools->Nuget Package Manager->Manage Nuget Packages for solution
   and confirm to update the two boost packages
   
   wait some time until you see the ========== Finished ========== message
   
7) open file DOWNLOADED_REPO\notepad-plus-plus\scintilla\win32\SciLexer.vcxproj in Notepad++ 
   and delete the 4 lines referring to boost 1.58 -> save it
   
8) confirm to reload solution in VS2017

9) right click on SciLexer project -> Build ==>> done

**Comment by bfridkis** [comment] 2018-05-16 23:42
Yep! Worked like a charm. I didn't even have to do step 7, as it seems the updates changed those lines for me to the new version.

I had basically tried doing exactly this, except I didn't add the SciLexer.vcxproj to the notepadPlus.vcxproj but instead tried updating then building it separate. (The more you know I guess, huh?)

Anyway, these steps should be on page one. Thanks!

**Comment by ClaudiaFrank** [comment] 2018-05-16 23:51
Good to see - do you, by any chance, use VS2017 professional or higher?
Because for my VS 2017 Community Edition it seems it doesn't delete those old 1.58 entries.

**Comment by bfridkis** [comment] 2018-05-17 13:42
I am using the Enterprise edition, so that may explain it.

**Comment by ClaudiaFrank** [comment] 2018-06-10 01:08
Can't say for sure, but might be - but didn't we speak about toolset 14.0 (VS2015)?
If you do need to use 12.0 then yes, you need to install VS2013 (afaik there is no standalone product)
but if you don't care about it then you can compile it even with toolset 14.1

Just did it a few minutes ago.
VS2017, Notepad++ and SciLexer with Platform Toolset v141, boost 1.67 and boost_regex-vc141 1.67

**Comment by bfridkis** [comment] 2018-06-11 13:47
But again, you have VS2013 installed on your machine, right? I'm fairly sure you need 12.0 for BOOST, whether you use v140 or v141 for the notepad++ build. I was initially thinking your steps above required only VS2017, but it appears this is not the case.

I bring this up because I was trying to build a document (based on your steps above), but the build (step 9) fails, citing the lack of v120 as the problem. Once I can get another virtual machine and install VS2013 I will confirm.

**Comment by ClaudiaFrank** [comment] 2018-06-11 17:51
No, not anymore - only Visual Studio 2017 Community Edition.
Hopefully the Screenshot shows everything needed to know

![grafik](https://user-images.githubusercontent.com/16170444/41248259-bf922cb0-6db0-11e8-86a4-74e808cec205.png)

**Comment by bfridkis** [comment] 2018-06-11 18:53
Did you have to explicitly search for the boost_regex_vc141 package then? By default my VS tries to update the existing package boost_regex_vc120...

**Comment by ClaudiaFrank** [comment] 2018-06-11 19:03
I did as I was knowing that I want to use toolset 141 but you are right, I could image that 
VS tries to update the existing version even if you configure to use a newer toolset.
So what I did with this install after downloading the sources and building a solution file 
was to remove the existing boost versions and to replace them with the version 
compatible to the used toolset, which in my case was the version 1.67 build with toolset 141.

**Comment by bfridkis** [comment] 2018-06-11 19:06
Alrighty then I think I see my confusion. I'll rerun everything and make sure it works as expected. Thanks again!

**Comment by ClaudiaFrank** [comment] 2018-06-11 19:07
My pleasure and maybe now you need to remove the old entries I mentioned in step 7.

**Comment by bfridkis** [comment] 2018-06-11 19:11
There simply are no lines with '1.58' anywhere in that file after I do the package upgrades. This is probably because I was upgrading existing packages, whereas you were removing and reinstalling new ones? I think the update process automatically converted the 1.58 to 1.67 in SciLexer.vcxproj...

**Comment by bfridkis** [comment] 2018-06-11 19:12
But now I'm going to go back through from the beginning, and you're right I probably will have to do that. Only I think I'll just replace 58 with 67, rather than delete the lines.

**Comment by bfridkis** [comment] 2018-06-11 22:38
Well... my problem all along is that I haven't been able to retarget. 

![image](https://user-images.githubusercontent.com/32713413/41260149-ea4a5dd4-6d9b-11e8-8f99-d7c2eda70e60.png)

I don't have the option to select v141, as you can see in the screenshot. What it surely comes down to is if I can't successfully retarget, then of course I'll need v120 (i.e. VS2013)...

**Comment by bfridkis** [comment] 2018-06-11 22:46
It looks like in your screenshot you are doing a rebuild. The same should apply to build though, right? I would think so..

**Comment by ClaudiaFrank** [comment] 2018-06-12 10:13
@bfridkis, yes build works as well, as I haven't changed code, at the time I did the screenshot, and it was already build I used rebuild instead of cleaning first and then build it again.
If you cannot retarget, wouldn't this mean that you haven't installed the proper compiler?
Not 100% sure if this is even possible? I mean, to install VS2017 but not to install the 141 toolset?
I will give it a try,  ~8-9hours, once I'm back home again.

**Comment by bfridkis** [comment] 2018-06-12 14:41
I have v141 and v140 toolsets, but it seems to me the system can't retarget 120 to 140 or 141, and therefore it shows nothing in the selection dropdown.

Just to reconfirm, you are positive you do not have VS2013 (and therefore toolset 120) installed when you are performing the steps above?

**Comment by ClaudiaFrank** [comment] 2018-06-12 19:17
Yes - no VS2013 installed but as promised here the full steps I did
Note description of menu might be slightly different, as I installed windows 10 German accidentally
and had to translate it by guessing.

1.) COMPLETE NEW VM Windows 10 Installation - no snapshot rollback etc...
2.) Downloaded npp repo as zip 
    (https://github.com/notepad-plus-plus/notepad-plus-plus/archive/master.zip)
3.) Created C:\repo
4.) Extracted downloaded npp zip to C:\repo 
5.) Downloaded
    (https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15)
6.) Run downloaded installer tool
7.) Confirm Visual Studio Installer start
8.) Confirm agreement ... 
9.) Checked only desktop development with c++ in the left area
    on the right the following got checked automatically
    - Just in time debugger
    - newest v141 tools ...
    - c++ profiler ...
    - windows 10 SDK
    - Visual C++ tools for CMake
    - Testadapter for Boost.Testadapter
    - Testadapter for Google.Test

10.) Pressed Install button
11.) Closed installer windows
12.) VS start - didn't login but confirmed start with dark theme and setting->general

now the interesting parts

11.) Opened project
12.) Selected C:\repo\notepad-plus-plus-master\PowerEditor\visual.net\notepadPlus.vcxproj
13.) Confimred security warning about trusted sources -> new solution project notepadPlus generated
14.) Right-clicked on solution->add->existing project
15.) Selected C:\repo\notepad-plus-plus-master\scintilla\win32\SciLexer.vcxproj
16.) Confimred security warning about trusted sources
    -> Solution explorer has now
        Notepad++(Visual Studio 2015 - Windows XP)
        SciLexer(Visual Studio 2013 - Windows XP)
17.) Save all - created solution in C:\repo\notepad-plus-plus-master
18.) Tools->Nuget Package Manager->Manage Packages for Solution
19.) Clicked on boost_regex-vc120, selected SciLexer in the overview and chose deinstall (strange enough it first installs the package)
20.) Confirm deinstallation
21.) Clicked on boost and chose install version 1.67.0
22.) Confirm installation
23.) Search for needed boost regex package by using search term boost_regex-vc141
24.) select found package, double checked that SciLexer is still check in overview and chose install
25.) Confirm installation of boost_regex-vc141 1.67.0
26.) Opened C:\repo\notepad-plus-plus-master\scintilla\win32\SciLexer.vcxproj in Editor and removed
    <Import Project="..\..\PowerEditor\visual.net\packages\boost.1.58.0.0\build\native\boost.targets" Condition="Exists('..\..\PowerEditor\visual.net\packages\boost.1.58.0.0\build\native\boost.targets')" />
    <Import Project="..\..\PowerEditor\visual.net\packages\boost_regex-vc120.1.58.0.0\build\native\boost_regex-vc120.targets" Condition="Exists('..\..\PowerEditor\visual.net\packages\boost_regex-vc120.1.58.0.0\build\native\boost_regex-vc120.targets')" />
    <Error Condition="!Exists('..\..\PowerEditor\visual.net\packages\boost.1.58.0.0\build\native\boost.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\PowerEditor\visual.net\packages\boost.1.58.0.0\build\native\boost.targets'))" />
    <Error Condition="!Exists('..\..\PowerEditor\visual.net\packages\boost_regex-vc120.1.58.0.0\build\native\boost_regex-vc120.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\PowerEditor\visual.net\packages\boost_regex-vc120.1.58.0.0\build\native\boost_regex-vc120.targets'))" />
27.) Saved the SciLexer.vcxproj and went back to VS2017
28.) Confirmed the messagebox about the changes in SciLexer with reload project
29.) Right-clicked on SciLexer project->Properties and changed platform toolset to Visual Studio 2017 (v141)
30.) pressed OK
31.) Right-clicked on Notepad++ project->Properties and changed platform toolset to Visual Studio 2017 (v141)
32.) pressed OK
33.) Right-clicked on Solution and chose Retarget -> this opened a window with both projects checked and Windows SDK Version 10.0.17134.0 selected
34.) pressed OK
35.) Right-clicked on SciLexer -> build - successful 
36.) Right-clicked on Notepad++ -> build - unsuccessful as function GetVersionExW has been marked as deprecated and Compiler flag /WX used
37.) changed to not use /WX
38.) Right-clicked on Notepad++ -> build - successful

39.) double checked that only cl.exe from VS2017 can be found by running dir /s cl.exe in a cmd having C:\ as current directory
C:\>dir /s cl.exe
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: FE87-DC7B

 Verzeichnis von C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x64
12.06.2018  19:45           414.824 cl.exe
               1 Datei(en),        414.824 Bytes

 Verzeichnis von C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx64\x86
12.06.2018  19:45           416.360 cl.exe
               1 Datei(en),        416.360 Bytes

 Verzeichnis von C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx86\x64
12.06.2018  19:45           349.800 cl.exe
               1 Datei(en),        349.800 Bytes

 Verzeichnis von C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\Hostx86\x86
12.06.2018  19:45           351.336 cl.exe
               1 Datei(en),        351.336 Bytes

     Anzahl der angezeigten Dateien:
               4 Datei(en),      1.532.320 Bytes
               0 Verzeichnis(se), 29.595.561.984 Bytes frei

C:\>

**Comment by bfridkis** [comment] 2018-06-12 20:30
Thank you for all the details. Now indeed I see my misunderstanding, and have just compiled successfully without VS2013, using toolset 141 for both SciLexer and Notepad. 

Big thanks again!

**Comment by bfridkis** [comment] 2018-06-13 22:56
I created a procedural document with screenshots entitled "Building Notepad++ from Source - A Beginners Guide - OPTION A" available [here ](https://github.com/bfridkis/Building-Notepad-Plus-Plus-from-Source-A-Beginners-Guide), which is based on the steps provided by ClaudiaFrank above. Hope it may help someone down the line. Thanks yet again.

**Closed** 2019-04-13 02:09 UTC
