### ISSUE TITLE
Automatic file reloading should not steal focus from current tab

### ISSUE THREAD

**Issue by dswhite42** [notepad-plus-plus/notepad-plus-plus#2051] opened 2016-07-05 21:51 UTC
When focus is returned to Notepad++ and the program detects a file has been changed, it will popup a dialog box offering to reload the file.  That's fine.  But it also steals focus from the active tab that that uses has up and makes the changed file active.  That is almost never desirable.  Instead the tab should be reloaded in the background without changing the active tab.  

Thank you.

**Comment by Croydon** [comment] 2016-07-28 04:16
Duplicate of #1087. Please use the search first.

**Closed** 2016-07-28 12:06 UTC
Labels: duplicate
