### ISSUE TITLE
[Feature Request] Make AutoHotkey Version v1.1.x Built In Language 

### ISSUE THREAD

**Issue by lmstearn** [notepad-plus-plus/notepad-plus-plus#2191] opened 2016-08-20 11:20 UTC
### AutoHotkey is a widely used language!
 For some years there are a number of AHK users of N++ experiencing style/syntax/visual issues with UDLs in their setups. Please include AutoHotkey as a built in language.

The [UDLsyntax highlighter xmls](https://autohotkey.com/boards/viewtopic.php?f=7&t=50
) might provide some benefit for the implementers.
Thanks.

**Comment by dail8859** [comment] 2016-08-20 11:38
Duplicate of #1734

**Closed by dail8859** 2016-08-20 11:38 UTC
Labels: duplicate
