### ISSUE TITLE
Lost all tabs (session) after Windows update restart

### ISSUE THREAD

**Issue by GordonAitchJay** [notepad-plus-plus/notepad-plus-plus#8357] opened 2020-06-02 01:15 UTC
### Description of the Issue
Notepad++ loses your session when Windows 10 forcefully restarts your computer after an update.

### Steps to Reproduce the Issue
1. Update Windows (10)
2. Leave Notepad++ open
3. Windows will automatically restart when inactive (i.e. overnight)
4. Open Notepad++

### Expected Behavior
For Notepad++ to load my previous session

### Actual Behavior
Notepad++ starts a brand new session, with no existing tabs

### Debug Information
Notepad++ v7.8.6   (64-bit)
Build time : Apr 21 2020 - 15:23:03
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1909
OS Build : 18363.836
Plugins : ComparePlugin.dll HTMLTag.dll jN.dll JsMapParser.NppPlugin.dll JSMinNPP.dll mimeTools.dll NppConverter.dll nppcrypt.dll NppExport.dll NPPJSONViewer.dll XMLTools.dll

While you do lose your session, you can get the backup version of files you've previously had open from the **\backup** directory. It's a shame the session files aren't backed up, too.

**Comment by mirh** [comment] 2020-07-22 19:57
Probably a duplicate of #8508, #4148 and #5129 (that I have just experienced myself).

**Comment by momala454** [comment] 2020-07-28 21:44
#8508 have a more easily reproducible use case

**Comment by donho** [comment] 2022-11-01 13:50
Fix by https://github.com/notepad-plus-plus/notepad-plus-plus/commit/6000f3bb21a42a4d28d068617e0dc642ef739b26

**Closed** 2022-11-15 03:04 UTC
