### ISSUE TITLE
Could u pls add Dart/kotlin format doc suport to npp?

### ISSUE THREAD

**Issue by petercao** [notepad-plus-plus/notepad-plus-plus#13880] opened 2023-07-10 10:13 UTC
### Steps to Reproduce the Issue

1. 
2. 
3. 

### Debug Information

Could u pls add Dart/kotlin format doc suport to npp?
*.kt,

**Comment by rdipardo** [comment] 2023-07-11 01:57
Duplicate of &mdash; at least &mdash; #13700, #13179, #12638, #3708, #3266 and ScintillaOrg/lexilla#58

**Closed** 2024-08-28 14:57 UTC
Labels: duplicate
