### ISSUE TITLE
Assertion On ScintllaWin.cxx, Line 3240. 

### ISSUE THREAD

**Issue by ffdd270** [notepad-plus-plus/notepad-plus-plus#4499] opened 2018-05-16 03:12 UTC
### Description of the Issue

if Edit Document, PLATFORM_ASSERT in ScintllaWin.cxx. cause GetCurrentThreadId() == GetWindowThreadId(reinterpret_cast<ScintillaWin *>(ptr)->MainHWND(), NULL));

### Steps to Reproduce the Issue

1. Bulid NotepadPlus Unicode, x86. and ScintllaWin.cxx bulid use Boost 1.67. I`m Bulid On VS 2017, SDK Version Win 10. 
2. On Notepad++ Window, Type the any chars. 
3. wait a second, betide PLATFORM_ASSERT in ScintllaWin.cxx

### Expected Behavior

Notepad++ doesn`t have any Exception. 

### Actual Behavior

ScintllaWin.cxx throw Exception, Because Window Thread NOT Correct Current Thread. 
if press the ignore, The program works normally.

### Debug Information

![deubginfo](https://user-images.githubusercontent.com/21333789/40094372-912b72be-5901-11e8-9f07-6aa6d9e9263e.PNG)

Call stack
>	SciLexer.dll!Scintilla::Platform::Assert(const char * c, const char * file, int line) Line 3207	C++
 	SciLexer.dll!ScintillaWin::DirectFunction(long ptr, unsigned int iMessage, unsigned long wParam, long lParam) Line 3240	C++
 	notepad++.exe!ScintillaEditView::execute(unsigned int Msg, unsigned int wParam, long lParam) Line 226	C++
 	notepad++.exe!ScintillaEditView::getCurrentDocLen() Line 277	C++
 	notepad++.exe!FileManager::backupCurrentBuffer() Line 861	C++
 	notepad++.exe!Notepad_plus::backupDocument(void * __formal) Line 6627	C++

I think this Exception cause when File Create, Another Thread(File Thread) Begin and switch the Current Thread to Another thread. and When ScintllaWin Call, NowThread != WinThread. 

Save Document is not have Exception. 

Please help me.

**Comment by SinghRajenM** [comment] 2018-07-21 19:22
Duplicate of #4101

**Comment by Ekopalypse** [comment] 2019-05-23 16:00
Should be closed as duplicate

**Comment by MetaChuh** [comment] 2019-05-27 19:28
closed as duplicate of #4101

**Closed by MetaChuh** 2019-05-27 19:28 UTC
Labels: duplicate
