### ISSUE TITLE
Save dialog is missing shortcuts

### ISSUE THREAD

**Issue by micktion** [notepad-plus-plus/notepad-plus-plus#7666] opened 2019-11-26 06:54 UTC
Save dialog is missing shortcuts in release v7.8.1

Steps to Reproduce the Issue

1.  Create a new file or open an existing file
2.  Type anything to modify the file
3.  Press Crtl-W to close the file
4.  A dialog is presented, buttons "Yes", "No" and "Cancel", pressing N or Alt-N does not do anything 

You can press Enter to select yes or press Esc to cancel.  There's no means to select No via the keyboard other than to press tab then enter.  There also should be alternate shortcuts for the Yes and Cancel buttons, Y, C, or Alt-Y and Alt-C should activate these buttons.

**Comment by rddim** [comment] 2019-11-26 07:21
Duplicate #7656

**Comment by xylographe** [comment] 2019-11-26 10:04
@sasumner 
Perhaps, if the title of #7656 would be changed from “New save _confirmation_ lacks keyboard shortcuts” to “New save _dialogue_ lacks keyboard shortcuts”, there might be fewer duplicates?

**Comment by sasumner** [comment] 2019-11-26 12:47
Closing as duplicate of #6223.

**Closed by sasumner** 2019-11-26 12:47 UTC
