### ISSUE TITLE
Unicode characters inconsistently cannot be displayed in Notepad++

### ISSUE THREAD

**Issue by charliehoward4dp** [notepad-plus-plus/notepad-plus-plus#3747] opened 2017-09-18 06:19 UTC
### Description of the Issue

In a Notepad++ document that is encoded as UTF-8 (no BOM), many Unicode characters are not displayed, but the hollow square appears in their place.  If a displayable Unicode character is added to a line containing undisplayable Unicode characters, those undisplayable ones suddenly appear. Removing the "good" one makes the others revert to the hollow square.  A simple example:

☆◬⊗⊠⋆⧆⨂

Paste that line into NP++ and you will see all the characters.  Remove the leading star ☆ and the others become squares.  Restore the star and the others re-appear.
### Steps to Reproduce the Issue

1. Create a UTF-8 (no BOM) text file.  (This is the only hard part of the procedure.)
2.  copy & paste the following string into a UTF-8 (no BOM) Notepad++ document: ☆◬⊗⊠⋆⧆⨂
3.  all of those characters will display properly
4. delete the leading star ☆
5. the other characters become hollow squares
6. restore the ☆ and the other characters reappear
### Expected Behavior

All of the characters always should appear.
### Actual Behavior

They only appear if an always-acceptable Unicode character is on the same line. If an always-acceptable Unicode character is in the document but not on the same line, certain Unicode characters, such as, but not limited to, the ones shown above, will not be displayed properly.

### Debug Information

Notepad++ v7.5.1   (32-bit)
Build time : Aug 29 2017 - 02:35:41
Path : C:\Program Files (x86)\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : ComparePlugin.dll mimeTools.dll NppConverter.dll NppExport.dll NppFTP.dll NppTextFX.dll PluginManager.dll SpellChecker.dll 

This occurs with characters from many of the Unicode blocks.

**Comment by dennis-thomas-o** [comment] 2018-11-05 16:49
I was able to reproduce this as well.

I tested with the *Default Style* in *Style Configurator* set to `Courier New`, `Consolas`, `Arial` and `Times New Roman`.

I believe this issue would happen any time you enter a character that is **NOT** contained in the selected font and then add/remove on the same line a character which **IS** contained in the selected font.

IMHO seems like something not quite right with the font-substitution routines.

### Debug Information

Notepad++ v7.5.9   (64-bit)
Build time : Oct 14 2018 - 15:19:55
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by imallett** [comment] 2019-09-13 23:56
> I believe this issue would happen any time you enter a character that is NOT contained in the selected font

This may be, but it also appears to occur in other circumstances as-well. For-example, "⎷" (U+23B7 "RADICAL SYMBOL BOTTOM") is present in Consolas, Courier New, DejaVu Sans Mono, and Lucida Console, but if you put that in a new text file, it won't show up with any of those fonts.

**Comment by Uhf7** [comment] 2020-05-26 07:46
>  it also appears to occur in other circumstances as-well

Cannot confirm this example on my system.

The U+23B7 character is not in my _DejaVu Sans Mono_. There is U+23AE, followed by U+23CE.

The U+23B7 character is not in my _Courier New_ either. There is U+2321, followed by U+2500.

Same for my _Consoleas_, U+2321 followed by U+2460, same for my _Lucida Console_, this ends at U+0433.

So this example seems not to poke a hole into the theory, that only characters unavailable in the current font are affected.

**Comment by ValZapod** [comment] 2020-05-26 09:51
> The U+23B7 character is not in my DejaVu Sans Mono.

The same. There is smth magical about ☆? What can it be? I will paste my funny gif and close my issue about ∈ symbol. ![notepadcorruption](https://user-images.githubusercontent.com/31514790/82732777-006ada00-9d18-11ea-9538-699374bc1958.gif)

**Comment by ValZapod** [comment] 2020-05-26 10:26
Duplicate of #813, #870, #813, #4086, #4056, #675, #1621, #3458, #4490 may be many more.

**Comment by ValZapod** [comment] 2020-05-26 10:37
So, we need to test Notepad++ 7.6.6 as it was good (?) in #4490. Also all of it (brackets also) is said in this comment. https://github.com/notepad-plus-plus/notepad-plus-plus/issues/1621#issuecomment-260655014

**Comment by ValZapod** [comment] 2020-05-26 10:44
And, yes it totally does not happen in MS Gothic. Strange.

**Comment by Ekopalypse** [comment] 2020-05-26 11:09
It might be, somehow, related to SCI_SETTECHNOLOGY configuration. 

![font_issue](https://user-images.githubusercontent.com/47723516/82893924-15cb4880-9f52-11ea-9304-e92d8de83523.gif)

**Comment by ValZapod** [comment] 2020-05-26 11:27
@Ekopalypse https://trac.wxwidgets.org/ticket/17804#comment:34 Yep.

**Comment by Ekopalypse** [comment] 2020-05-26 11:44
but I don't see the issue with the larger autocompletion box.
Maybe this has been fixed already with the scintilla version in use by npp.

**Comment by ValZapod** [comment] 2020-05-26 12:33
@Ekopalypse
> with the larger autocompletion box.

You mean brackets? I think you use not Courier New Font? It is bad in it, and good in DejaVu Sans Mono. You can try from #442

**Comment by Uhf7** [comment] 2020-05-26 12:44
@Ekopalypse,
the `SCI_SETTECHNOLOGY` approach looks very promising on my system too.

I did include an `execute(SCI_SETTECHNOLOGY, <n>);` into `ScintillaEditView::init` to test it.

Techology 0:

![Techno-0](https://user-images.githubusercontent.com/40629737/82900633-1e754c00-9f5d-11ea-8aeb-5e585db40c89.png)

Technologies 1, 2 and 3:

![Techno-1](https://user-images.githubusercontent.com/40629737/82900672-2e8d2b80-9f5d-11ea-93a5-46adec7c39a3.png)

Both screenshots show the same file automatically loaded after start, the only thing I did was moving the cursor to the right bracket of the two marked brackets.

I used _Courier New_ here.



The new techologies seem to size the substituted chars better then techology 0.

**Comment by ValZapod** [comment] 2020-05-26 12:45
I found that this symbol ↘ (U+2198) is rendered in Consolas (it does not have this symbol) as ? in a square. Not just a square. But apart of that it is all the same.

**Comment by Ekopalypse** [comment] 2020-05-26 14:31
@ValZapod 
> You mean brackets? I think you use not Courier New Font? It is bad in it, and good in DejaVu Sans Mono. You can try from #442

No, I mean the screenshot and discussion you linked to
https://trac.wxwidgets.org/attachment/ticket/17804/17804-SetTechnology1.png

There it has been reported that the words in an autocompletion box are bigger using directwrite
instead of default. I'm using RobotoMono font.

**Comment by Ekopalypse** [comment] 2020-05-26 14:53
@ValZapod @Uhf7 
I don't seem to be able to get the results you get with the Courier New font. 
The ∈ is always displayed, so I assume that something else has an additional effect.

**Comment by Ekopalypse** [comment] 2020-05-26 15:45
Downloaded 7.8.6 x64 and did a retest

![font_issue2](https://user-images.githubusercontent.com/47723516/82921203-68b7f680-9f78-11ea-91f8-38017f823114.gif)

The "bracket issues" seems not to happen for me. (??)

**Comment by Uhf7** [comment] 2020-05-26 15:51
@Ekopalypse 

I can make the  ∈ visible with the _Courier New_ font now too, using technology 0 and some hand-configured font linking, which looks actually a little ill:

![Techno-0fs](https://user-images.githubusercontent.com/40629737/82919719-af0c5600-9f76-11ea-9ebe-d088708ed492.png)

What I did: There is a registry entry 

`HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink`

Under it, there are many multi-string values, named after fonts. There was no value named `Curier New`. So I created a multi-string value named `Courier New` and copied the data of the `Lucida Sans Unicode` into it. A shot in the blue. Immediately after it, nothing improved, but after I rebooted my system, the missing characters became visible. And: If I move the cursor to the famous right bracket, then the small ∈ mutates to a big ∈ instead to an empty frame. So it certainly depends on the Font linking setup too. And if I could set up the font linking in a way, that the font-linked ∈ looks the same as the "normal" ∈ (where ever it comes from), then everything would be fine with technology 0.

**Comment by Ekopalypse** [comment] 2020-05-26 16:09
@Uhf7 Is not set for me.
![image](https://user-images.githubusercontent.com/47723516/82923277-044a6680-9f7b-11ea-8c18-bbaa66113645.png)

**Comment by ValZapod** [comment] 2020-05-26 16:14
> The "bracket issues" doesn't seem to happen for me. (??)

The fon never actually changed, you need to press on Enable global font.

**Comment by Uhf7** [comment] 2020-05-26 16:20
@Ekopalypse 

then certainly another trick exists. Running out of thoughts here. On my system, the 32 bit version works exactly like the 64 bit version.

A major difference is the system itself: I use 
OS Name : Windows 10 Pro (64-bit) 
OS Version : 1607
OS Build : 14393.576,

you use Windows 7. I try it on my Windows 7 system ...

**Comment by Uhf7** [comment] 2020-05-26 17:00
Ok, under Windows 7, the ∈ works fine, with and without bracket highlighting, but some other characters don't. Using technology 0.

![Techno-0-w7](https://user-images.githubusercontent.com/40629737/82926911-2a263a00-9f80-11ea-9b91-1f941d0050f2.png)

With the 64 bit version of Npp, the same characters are missing.

Using technology 1:

![Techno-0-w7-t1](https://user-images.githubusercontent.com/40629737/82927998-d288ce00-9f81-11ea-9a97-a1f5eb98860c.png)

What else could you ask for? Looks perfect to me.

Technology 1, Windows 7, 64 bit version of Npp:

![Techno-0-w7-t1-64](https://user-images.githubusercontent.com/40629737/82928676-cf421200-9f82-11ea-846c-6f6207669ed3.png)

I dream, if you ask me, compared to the current state.

**Comment by ValZapod** [comment] 2020-05-26 17:05
@Uhf7 Now remove ☆ and ⇒. Oops.

**Comment by Ekopalypse** [comment] 2020-05-26 17:17
@ValZapod 
> The font never actually changed, you need to press on Enable global font

No, it was started with these settings. I switched to global overwrite to show that no other font is defined. If global override is NOT checked, the default setting takes precedence.
Yes, I still use Windows 7 why not? I don't do any "mission critical transaction" with windows OS anyway. 

>Cannot we somehow force the rendering that is used when yout type in ☆?

Npp has no setting for this yet. What you can do is to use one of the scripting language plugins,
like PythonScript, LuaScript ..., even NppExec can be used to set the technology to DirectWrite

@Uhf7 - hmm :-D what should I say - Windows 10 broke it :-(
Thanks for testing and btw. thank you for your contributing work. Much appreciated.

**Comment by Uhf7** [comment] 2020-05-26 17:20
@ValZapod 

I see no negative effect when removing the ☆, if i use technology 1:

![Techno-0-w7-t1-64-2](https://user-images.githubusercontent.com/40629737/82929635-46c47100-9f84-11ea-8713-5143b97041f8.png)

or the ⇒:

![Techno-0-w7-t1-64-3](https://user-images.githubusercontent.com/40629737/82929975-df5af100-9f84-11ea-860a-413b42b0ad93.png)

I certainly start to get messed up with my screenshot names here, that's why I don't post any pictures from re-inserting the ☆ and the ⇒ successfully, but for me, with technology 1 everything works fine. Under Windows 7 and under Windows 10, I believe.

**Comment by ValZapod** [comment] 2020-05-26 17:24
Well, are we going to open a bug https://sourceforge.net/p/scintilla/bugs/? Or just comment here https://sourceforge.net/p/scintilla/bugs/1393/

**Comment by Uhf7** [comment] 2020-05-26 17:33
@Ekopalypse 

using a plugin or NppExec to make the characters display correctly is not exactly what I call a solution of the problem. It's a possible work-around, but wouldn't it be nice when the characters are displayed correctly without additional actions?

And, @ValZapod, how long would it take until we have a new Scintilla version? (Perhaps, the Scintilla developers will say: Use technology 1 or higher! That would be interesting)

I would feel better, if Npp itself would switch the technology to a working one. May be, it can be included in the configuration somehow, so that there is a safe fallback if the technology switch doesn't work on some systems.

**Comment by Ekopalypse** [comment] 2020-05-26 17:36
@Uhf7 - 100% correct :-D

**Comment by ValZapod** [comment] 2020-05-26 17:41
https://sourceforge.net/p/scintilla/bugs/1393/ is our bug. But there is this problem about brackets... That is not there.

**Comment by Uhf7** [comment] 2020-05-27 09:51
Issue most close to this one is #2287. It is the same problem they describe there, existing since 2016, and it is solved there by setting the technology to DirectWrite with the help of a plug-in.

Thank you for that solution, but this is something for insiders. As a new user, or as a user who is just using it for editing files without caring about development, this solution is this is very hard to find. 

So I would fully support what @jefflomax said in #2287:

> Notepad++ should support ligatures out of the box, not thru hacks or adding plugins users neither need nor want.

So I will try to push it to the master now, with a PR. If we not do this now, the next ones come in two years wasting their time with testing it again and again and again.

**Comment by Uhf7** [comment] 2020-05-28 09:17
Found an old Windows Vista in my virtual machine park, the following screenshots support the necessity to make the DirectWrite technology feature configurable. That Scintilla can load Direct2D does not mean automatically that this produces better results on old (not prehistoric) systems.

Vista, Technology 0, Courier New
![Techno-0-Vista](https://user-images.githubusercontent.com/40629737/83121085-299db880-a0d2-11ea-869c-310e15946e53.png)

Vista, Technolgy 1, Courier New
![Techno-1-Vista-1](https://user-images.githubusercontent.com/40629737/83122775-62d72800-a0d4-11ea-9f02-0bb2de25020f.png)

Vista, Technology 0, DejaVu Sans Mono
![Techno-0-Vista-DejaVu](https://user-images.githubusercontent.com/40629737/83121202-4afea480-a0d2-11ea-8122-4ee48201e0d2.png)

Vista, Technology 1, DejaVu Sans Mono
![Techno-1-Vista-DejaVu](https://user-images.githubusercontent.com/40629737/83121236-55b93980-a0d2-11ea-8e63-71c15b1a46a6.png)

**Comment by ValZapod** [comment] 2020-05-28 09:50
That is just because there was no support for Unicode that far?

**Comment by Uhf7** [comment] 2020-05-28 17:05
May be. But Unicode itself was already there under Vista. What bugs me more is, that technology 1 under this Vista seems to wreck "normal" characters nearby the ∈ character, sometimes.

**Comment by ValZapod** [comment] 2020-05-28 17:07
> technology 1 under this Vista seems to wreck "normal" characters nearby the ∈ character, sometimes

Screenshot?

**Comment by Uhf7** [comment] 2020-05-28 17:39
@ValZapod 

You wrote 2 days ago

> https://sourceforge.net/p/scintilla/bugs/1393/ is our bug. 

The Unicode character U+25C6 (◆)displays in Npp with and without DirectWrite technology. Even in Windows 7.

So I cannot verify that this is exactly "our" bug. And it was 2012. And he used Windows XP. And I'm sure there are many effects which can lead to empty frames instead of correct characters. I simply don't believe that it's promising to go to them and ask them to fix exactly this issue now.

**Comment by Uhf7** [comment] 2020-05-28 17:43
> Screenshot?

The second screenshot of my Vista screenshots, headlined "Vista, Technolgy 1, Courier New".
Most "normal" characters in line 3 don't look like _Courier New_ anymore.
.

**Comment by ValZapod** [comment] 2020-06-07 22:34
> So I cannot verify that this is exactly "our" bug. And it was 2012. And he used Windows XP.

Okay, maybe open another issue?? Maybe also lets try @nyamatongwe?

**Comment by nyamatongwe** [comment] 2020-06-07 23:38
Valerii Zapodovnikov:

> Okay, maybe open another issue?? Maybe also lets try @nyamatongwe?

   For Scintilla bug #1393, text shaping for East Asian text can be influenced by the locale used so displaying in a Japanese context may differ from a Chinese context. There are other bugs about this like https://sourceforge.net/p/scintilla/bugs/2027/. 

   Problems with displaying particular symbol characters may be different. They seem to occur when the specified font does not include some characters so Windows tries to use glyphs from backup fonts. Scintilla does not have much control over this.

   For GDI (technology 0) you could try experimenting with the font creation setup call in SetLogFont inside win32/PlatWin.cxx. It is possible that the lfQuality and lfCharSet parameters will influence the behaviour.

   DirectWrite was originally implemented for Windows Vista but that early version had some problems and DirectWrite has improved over time. Applications could default to using DirectWrite from Windows 7 if there are too many problems with Vista or add an option that users can select. Some people prefer GDI’s less anti-aliased (blurry) text.

   Neil

**Comment by ValZapod** [comment] 2020-06-07 23:56
@nyamatongwe Wow. Paste ⊗⊠⋆⧆⨂ in your notepad3, it will get broken! Nice, I will open an issue there.

**Comment by hpwamr** [comment] 2020-06-08 08:24
> Wow. Paste ⊗⊠⋆⧆⨂ in your notepad3, it will get broken! Nice, I will open an issue there. P.S. **Or it is not yours?**

NOP, **Notepad3** is the property of "[**Derick Payne**](https://github.com/rizonesoft)"

**Comment by ValZapod** [comment] 2020-06-08 12:26
Wow, look here @Uhf7 https://github.com/rizonesoft/Notepad3/issues/2404#issuecomment-640456912 this is genious. One can chiose technology that you Draw.

**Comment by Ekopalypse** [comment] 2020-06-08 12:50
@ValZapod - seems you misunderstood most of the thread. 
This is what I suggested 13 days ago and what @Uhf7 is working on.

**Comment by ValZapod** [comment] 2020-06-08 12:51
Well, it will be without a UI?

**Comment by Ekopalypse** [comment] 2020-06-08 12:55
I don't think so, if you check his [PR](https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8326/files) then you will see that he added it to the preference dialog.

**Comment by ValZapod** [comment] 2020-06-08 13:04
Well, 4 variants vs 2 and need to restart to preserve plugin behaviours...
Also maybe try this advice from Sci author?

> For GDI (technology 0) you could try experimenting with the font creation setup call in SetLogFont inside win32/PlatWin.cxx. It is possible that the lfQuality and lfCharSet parameters will influence the behaviour.

**Comment by Ekopalypse** [comment] 2020-06-08 13:29
Too much noise for my taste, I'm out.

**Comment by Uhf7** [comment] 2020-06-11 20:52
@ValZapod I saw the UI already, but had no really opinion about it, because it doesn't belong to this project, so it does not help me here. My opinion regarding the Technology settings in the screen shot: Two options too many. The difference in text rendering is between the Windows GDI TextOut function on one side and the DirectWrite equivalent on the other side. The rest is about how to bring the rendering result of DirectWrite to the screen.

**Comment by ValZapod** [comment] 2020-08-31 12:11
Somebody just proposed a patch for this! https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8756#issuecomment-679320347

Change

https://github.com/notepad-plus-plus/notepad-plus-plus/blob/84430809df2f6607a3bc5b9f05866149842f2bd9/scintilla/win32/PlatWin.cxx#L407

to 
```
		auto TLen = text.length();
		if(TLen>1)TLen++;
		if (0) { //unicodeMode
			tlen = static_cast<int>(UTF16FromUTF8(text, buffer, TLen));
		} else {
			tlen = ::MultiByteToWideChar(codePage, 0, text.data(), static_cast<int>(TLen),
				buffer, static_cast<int>(TLen));
		}

```

**Comment by nyamatongwe** [comment] 2020-08-31 21:13
Valerii Zapodovnikov:
> Somebody just proposed a patch for this! #8756 (comment) <https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8756#issuecomment-679320347>   We already know that changing the text changes the presentation of this bug. The patch is not a fix.

   Neil

**Comment by Uhf7** [comment] 2020-09-01 13:14
This "fix" is at least a hint where the problem comes from: It comes directly from the Windows GDI text output functions for wide characters. I did some experiments based on this information.

The Windows GDI functions, which are used by Scintilla and which do not work correctly, are:
- `ExtTextOutW`
- `GetTextExtentPoint32W`
- `GetTextExtentExPointW`

The common error of these functions seems to be, that they use squares instead of characters for some 'bad' Unicode characters, as long as there is no 'good' Unicode character in the text string.

I have no list of 'good' or 'bad' Unicode characters, this is only a term for it I invented here. But I can name two 'good' Unicode characters: 0x0000 and 0x200B. If one of those two characters is in the text, all other Unicode characters are displayed correctly. The 0x0000 character has been used by @KnIfER for the "fix". Unfortunately, it has a width, when we use it with the Windows GDI functions.

So I went for the 0x200B character (Zero width space) in my experiments. A possible fix is to append the 0x200B character silently to all text strings passed to the Windows functions mentioned above. Then they produce the correct character width's and the correct output.

To make this experiment fly without additional text copy operations, I modified the `TextWide` class in a sneaky way. The `VarBuffer` is now one character longer than the actual text and this additional character is the Zero width space. `tlen` remains as it is, to avoid any behavior modifications. 

	class TextWide : public VarBuffer<wchar_t, stackBufferLength> {
	public:
		int tlen;	// Using int instead of size_t as most Win32 APIs take int.
		TextWide(std::string_view text, bool unicodeMode, int codePage=0) :
			VarBuffer<wchar_t, stackBufferLength>(text.length() + 1) {
			if (unicodeMode) {
				tlen = static_cast<int>(UTF16FromUTF8(text, buffer, text.length()));
			} else {
				// Support Asian string display in 9x English
				tlen = ::MultiByteToWideChar(codePage, 0, text.data(), static_cast<int>(text.length()),
					buffer, static_cast<int>(text.length()));
			}
			buffer [tlen] = 0x200b;
		}
	};

After modifying the `TextWide` class this way, I can use `tlen+1` as character count for the `ExtTextOutW` call and for all  `GetTextExtentPoint32W` calls, to smuggle in the 'good' Unicode character.

What remains here, is the `GetTextExtentExPointW` call in `SurfaceGDI::MeasureWidths`. Here, I had to increase the size of the `poses` buffer, and I had to set the result parameter `fit` to the actual length of the text. This can be done without side effects, because the `maxWidthMeasure` parameter is equal to `INT_MAX`, so that I assume, that all characters fit into this width anytime.

		const TextWide tbuf(text, unicodeMode, codePage);
		TextPositionsI poses(tbuf.tlen + 1);
		if (!::GetTextExtentExPointW(hdc, tbuf.buffer, tbuf.tlen + 1, maxWidthMeasure, &fit, poses.buffer, &sz)) {
			// Failure
			return;
		}
		fit = tbuf.tlen;

This experimental fix runs on my system without assertions in debug mode and displays the correct characters using the Windows GDI functions.

I don't know whether such a solution would be accepted by Scintilla, but perhaps there is someone who wants to try it this way too ...

**Comment by ValZapod** [comment] 2020-09-01 14:50
> squares instead of characters for some 'bad' Unicode characters

Those are not squares. It is .notdef (yes, it is not .null, U+0000) glyphs of the font)) You can see it in Fontlab. That is why Consolas is showing not just a square, but "?" in a square! https://docs.microsoft.com/en-us/typography/opentype/otspec170/recom#shape-of-notdef-glyph

**Comment by AgostinoSturaro** [comment] 2020-10-11 15:51
Here's another way to reproduce this, from #3747 originally reported with #813

Open a new Notepad++ file, set the encoding to UTF-8 and paste these symbols ([Double Arrow Unicode](http://unicode-table.com/en/search/?q=Double+Arrow) characters) on the first empty line
⇐⇑⇒⇓⇔⇕⇖⇗⇘⇙
Position the cursor before the last two characters and enter a newline, like this
⇐⇑⇒⇓⇔⇕⇖⇗
⇘⇙
The last two characters should turn into blocks.
![notepad unicode character corruptuion](https://cloud.githubusercontent.com/assets/1441393/9518640/924a17f2-4cb8-11e5-8613-74012a88d8dd.png)

**Comment by donho** [comment] 2020-10-12 03:43
Here's the solution:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5513#issuecomment-700255578

**Closed by donho** 2020-10-12 03:43 UTC
Labels: accepted

**Comment by ValZapod** [comment] 2020-10-24 00:54
Why did you close it if #8756 is still open and this issue is still not fixed??? Did you report it upstream?

**Comment by ValZapod** [comment] 2021-04-20 00:28
So, wow! This was a bug in Notepad after all! 🥂🥂🥂🥂 https://github.com/donho/notepad-plus-plus/commit/38bf76e84312db8e60d51126acf4853201470663

**Comment by ValZapod** [comment] 2021-06-08 12:26
Actually I just downloaded v8, it is still not fixed?? Why?

Also thanks for very nice reproduce vectors in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9599#issue-583898790

**Comment by sasumner** [comment] 2021-06-08 12:45
>Actually I just downloaded v8, it is still not fixed?? Why?

Maybe be more specific about what is not fixed.
There's a lot going on in this issue thread to be able to pick out what you mean.

**Comment by ValZapod** [comment] 2021-06-08 13:00
> > Actually I just downloaded v8, it is still not fixed?? Why?
> 
> Maybe be more specific about what is not fixed.
> There's a lot going on in this issue thread to be able to pick out what you mean.

Even the ◬⊗⊠⋆⧆⨂ is still not fixed.

**Comment by sasumner** [comment] 2021-06-08 13:07
![image](https://user-images.githubusercontent.com/30118311/121190340-f4758b80-c838-11eb-88e8-eaedfef7df72.png)

**Comment by ValZapod** [comment] 2021-06-08 13:12
This is using DirectWrite?

**Comment by sasumner** [comment] 2021-06-08 13:16
>This is using DirectWrite?

Actually, DirectWrite enabled / disabled has same effect.
Tested in fresh portable extract of 8.0.

**Comment by mere-human** [comment] 2021-06-08 18:23
Could it depend on system/application font?

**Comment by ValZapod** [comment] 2021-07-09 17:14
Okay, 8.1.1: still bad. So I found another cool thing! Apparently it is not always .notdef! It can also be (Courier .fon file (Windows 3.x font library file), not Courier  New)

![image](https://user-images.githubusercontent.com/31514790/125113279-1f315900-e0f1-11eb-8135-a39075ee78e0.png)

I checked with Fontforge, this is that symbol!

![image](https://user-images.githubusercontent.com/31514790/125114141-3b81c580-e0f2-11eb-8789-d0bef2fa499b.png)

**Comment by ValZapod** [comment] 2021-07-21 12:44
Tw more symbols: ∇, ∀, ℡. Tab can destroy it. That is from #4817.

**Comment by AgostinoSturaro** [comment] 2021-07-22 13:18
@ValZapod Would you suggest reopening this defect and closing the new ones, or something else?

**Comment by ValZapod** [comment] 2021-07-22 13:22
Yes and yes. Also add label "scintilla dependent" since that is https://sourceforge.net/p/scintilla/bugs/1393/

**Comment by ValZapod** [comment] 2021-08-14 09:05
Ping?

**Comment by Uhf7** [comment] 2021-08-19 19:44
Pong!

Seems to be a complicated issue. We should try to split up some different problems into different groups:

1.  There is an effect, that characters are displayed sometimes, and sometimes not, depending on the preceding character. This is, what this issue describes. The - in my opinion - most promising hack for this effect is this: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/3747#issuecomment-684844223.
2.  There are characters, which will be displayed by Windows only, if the DirectWrite API is used. Here, the DirectWrite option https://github.com/notepad-plus-plus/notepad-plus-plus/issues/5513#issuecomment-700255578 may help.
3. Encoding issues. Where invalid UTF-8 characters get into the text buffer, and hence, they will be displayed incorrectly. Such an issue has been fixed by #9599. But this does not guarantee, that all the correct UTF-8 characters can be displayed by Windows.

**Comment by ValZapod** [comment] 2021-08-19 19:58
> 3\. all the correct UTF-8 characters can be displayed by Windows.

That is fixed 100% by using UTF-8 BOM. I mean these files, thag you missed somehow: https://github.com/notepad-plus-plus/notepad-plus-plus/issues/8966#issuecomment-882086892

> 1. promising hack for this effect is this

Indeed, but if that is a bug in WINAPI, it is not a hack. And also this hack must be applied in scintilla, IMHO.

> 2\. which will be displayed by Windows only, if the DirectWrite API is used

What does it mean by Windows? Not by Linux? What are such examples with hack applied?

**Comment by Uhf7** [comment] 2021-08-19 20:43
> Indeed, but if that is a bug in WINAPI, it is not a hack. And also this hack must be applied in scintilla, IMHO.

It is a hack, and it has to be applied in Scintilla. I call it a hack, because I don't know exactly why it works. But it is not a too-bad hack, because it respects all the requirements the Windows-API has at this point, which means, we do nothing which is forbidden by the Windows-API. Actually, we expect to work the Windows-API without this hack, but it doesn't.

> What does it mean by Windows? Not by Linux?

Linux has nothing to do with it here. The problem is, that all characters we see displayed by Notepad++ are displayed by Windows-API-function calls. If the DirectWrite option in Notepad++ is disabled, Notepad++ uses the ancient Windows-GDI function TextOutW to display the character(s).  If the DirectWrite option in Notepad++ is enabled, Notepad++ uses the brand-new and super-fast DirectWrite text output function to display the character(s). Since both are different graphic API's, there are different results. 

> What are such examples with hack applied?

Cannot try out this momentarily, but as far as I remember from testing, some should work. Please try.

**Comment by ValZapod** [comment] 2021-08-19 21:13
> Actually, we expect to work the Windows-API without this hack,

Can we report this bug in windows? This already mentions this: https://support.microsoft.com/en-us/topic/why-does-some-text-display-with-square-boxes-in-some-apps-on-windows-10-b078a35f-9709-1780-44c0-8c27a58205a2

`Browsers or other apps that do complex layout using lower-level graphics APIs that do not provide font fallback (e.g., DrawGlyphRun, ExtTextOut using ETO_GLYPH_INDEX, ScriptTextOut).`

**Comment by Uhf7** [comment] 2021-08-19 21:32
Can we report this bug in windows?

First thought: I feel overcharged with this. Fighting the ministry of truth??? No way.

Second thought: The problem is so specific, that no one working at the 1st level of telephone or email support for Microsoft will grasp it.  So the only advice I expect from there is something like "Please reboot your computer to see if it's gone" or something like this. No hope, unless you know someone inside the system ...

**Comment by ValZapod** [comment] 2021-08-28 15:58
> Fighting the ministry of truth???

I did a couple times, they merget the fixes. https://github.com/MicrosoftDocs/sdk-api/pull/792
https://github.com/MicrosoftDocs/cpp-docs/pull/2758


> working at the 1st level of telephone or email support for Microsoft will grasp it

You can just at people, they are all on github.
