### ISSUE TITLE
File extension txt no longer default

### ISSUE THREAD

**Issue by noteovv** [notepad-plus-plus/notepad-plus-plus#2884] opened 2017-02-08 15:58 UTC
### Description of the Issue
On saving a generic text file, the file extension in the Windows Explorer file dialog is no longer .txt as was the case in previous versions of Npp. The file extension is empty.
If you consider it as a new feature, it should have been mentioned as a new feature in the Release notes.

### Steps to Reproduce the Issue
1.  Write something in an empty file window. Don't choose a "Language".
2.  OR: Open an existing .txt file.
3.  Save the file to disk with Save (case 1) or Save as (case2).

### Expected Behavior
The file should register on disk as a txt file, with Windows file extension .txt.

### Actual Behavior
The file is saved on disk without any Windows file extension.

### Debug Information
Notepad++ v7.3.1   (64-bit)
Build time : Jan 17 2017 - 00:28:43
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10
Plugins : mimeTools.dll NppConverter.dll 

Status of this bug: annoying.

**Comment by MAPJe71** [comment] 2017-02-08 17:12
Duplicate of #2838.

**Comment by ffes** [comment] 2017-02-08 21:21
Related to this (or just the same...) When you select any other language like SQL and you save a file without giving a full filename the extension `.sql` is not added as well.

**Comment by noteovv** [comment] 2017-02-09 10:02
Thanks,


I couldn't find any recent bug report about txt, so I filed a ticket myself.

Sorry for this.

Anyhow, my ticket is a bit more exactly worded.


Greetings,

Oscar van Vlijmen



________________________________
Van: Menno Vogels <notifications@github.com>
Verzonden: woensdag 8 februari 2017 18:12
Aan: notepad-plus-plus/notepad-plus-plus
CC: noteovv; Author
Onderwerp: Re: [notepad-plus-plus/notepad-plus-plus] File extension txt no longer default (#2884)


Duplicate of #2838<https://github.com/notepad-plus-plus/notepad-plus-plus/issues/2838>.

**Closed** 2017-02-09 13:16 UTC

**Comment by ffes** [comment] 2017-02-14 13:26
This bug is **not** fixed in 7.3.2!

Please re-open.

The bug mentioned as "dup" is another bug IMHO.

**Comment by dail8859** [comment] 2017-02-15 01:03
@ffes 

Make sure this is **unchecked**.

![capture](https://cloud.githubusercontent.com/assets/3694843/22956519/9fe9a14a-f2f0-11e6-96ba-254937932e80.PNG)

**Comment by ffes** [comment] 2017-02-15 07:11
You got to be kidding!
This is by design?????
Even the most basic editor in Windows `notepad.exe` has this feature and N++ has to disable it to add an extension to a filename?????

**Comment by noteovv** [comment] 2017-02-15 15:26
@dail8859: this did the trick (unchecking a Default directory preference).
Still it is a bug, since the behaviour changed from one Npp version to another.

@ffes: indeed, still a bug in version 7.3.2.

**Comment by dail8859** [comment] 2017-02-15 15:46
The problem was only with v7.3.1 ignoring that setting.

That setting has been there for several versions.

**Comment by Ubrio** [comment] 2019-12-04 23:21
> 
> 
> @ffes
> 
> Make sure this is **unchecked**.
> 
> ![capture](https://cloud.githubusercontent.com/assets/3694843/22956519/9fe9a14a-f2f0-11e6-96ba-254937932e80.PNG)

Thank You You Just Help Me Fixing This Issue
